# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Сачуване пријаве
window-close =
    .key = њ
focus-search-shortcut =
    .key = ф
focus-search-altshortcut =
    .key = к
copy-provider-url-cmd =
    .label = Копирај URL
    .accesskey = ѕ
copy-username-cmd =
    .label = Копирај корисничко име
    .accesskey = У
edit-username-cmd =
    .label = Уредите корисничко име
    .accesskey = д
copy-password-cmd =
    .label = Копирај лозинку
    .accesskey = Ц
edit-password-cmd =
    .label = Уредите лозинку
    .accesskey = У
search-filter =
    .accesskey = П
    .placeholder = Претражи
column-heading-provider =
    .label = Провајдер
column-heading-username =
    .label = Корисничко име
column-heading-password =
    .label = Лозинка
column-heading-time-created =
    .label = Први пут коришћено
column-heading-time-last-used =
    .label = Последњи пут коришћено
column-heading-time-password-changed =
    .label = Последњи пут измењено
column-heading-times-used =
    .label = Пута коришћено
remove =
    .label = Уклони
    .accesskey = У
import =
    .label = Увези...
    .accesskey = в
close-button =
    .label = Затвори
    .accesskey = З
show-passwords =
    .label = Прикажи лозинке
    .accesskey = П
hide-passwords =
    .label = Сакриј лозинке
    .accesskey = С
logins-description-all = Пријаве за следеће провајдере су сачуване на вашем рачунару
logins-description-filtered = Наведене пријаве одговарају вашој претрази:
remove-all =
    .label = Уклони све
    .accesskey = с
remove-all-shown =
    .label = Уклони све приказано
    .accesskey = к
remove-all-passwords-prompt = Јесте ли сигурни да желите да уклоните све лозинке?
remove-all-passwords-title = Уклони све лозинке
no-master-password-prompt = Јесте ли сигурни да желите да прикажете ваше лозинке?
