# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = 가져오기 마법사
import-from =
    { PLATFORM() ->
        [windows] 설정, 북마크, 기록, 비밀번호 및 기타 데이터를 가져올 원본:
       *[other] 설정, 북마크, 기록, 비밀번호 및 기타 데이터를 가져올 원본:
    }
import-from-bookmarks = 북마크를 가져올 원본:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-edge-legacy =
    .label = Microsoft Edge 레거시
    .accesskey = L
import-from-edge-beta =
    .label = Microsoft Edge Beta
    .accesskey = d
import-from-nothing =
    .label = 아무것도 가져오지 않기
    .accesskey = D
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chrome-beta =
    .label = Chrome Beta
    .accesskey = B
import-from-chrome-dev =
    .label = Chrome Dev
    .accesskey = D
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = X
import-from-360se =
    .label = 360 Secure Browser
    .accesskey = 3
no-migration-sources = 북마크, 기록 또는 비밀번호 데이터를 포함하고 있는 프로그램을 찾을 수 없습니다.
import-source =
    .label = 설정과 데이터 가져오기
import-items-title =
    .label = 가져올 항목
import-items-description = 가져올 항목을 선택하세요:
import-migrating-title =
    .label = 가져오는 중…
import-migrating-description = 다음 항목들을 가져오고 있습니다…
import-select-profile-title =
    .label = 프로필 선택
import-select-profile-description = 가져올 수 있는 프로필:
import-done-title =
    .label = 가져오기 완료
import-done-description = 다음 항목들을 성공적으로 가져 왔습니다:
import-close-source-browser = 계속하기 전에 선택한 브라우저가 닫혀 있는지 확인하세요.
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = { $source }(으)로부터
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-edge-beta = Microsoft Edge Beta
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chrome-beta = Google Chrome Beta
source-name-chrome-dev = Google Chrome Dev
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Secure Browser
imported-safari-reading-list = 구독 목록 (Safari로부터)
imported-edge-reading-list = 구독 목록 (Edge로부터)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = 인터넷 옵션
    .value = 인터넷 옵션
browser-data-edge-1 =
    .label = 설정
    .value = 설정
browser-data-safari-1 =
    .label = 기본 설정
    .value = 기본 설정
browser-data-chrome-1 =
    .label = 설정
    .value = 설정
browser-data-canary-1 =
    .label = 설정
    .value = 설정
browser-data-360se-1 =
    .label = 설정
    .value = 설정
browser-data-ie-2 =
    .label = 쿠키
    .value = 쿠키
browser-data-edge-2 =
    .label = 쿠키
    .value = 쿠키
browser-data-safari-2 =
    .label = 쿠키
    .value = 쿠키
browser-data-chrome-2 =
    .label = 쿠키
    .value = 쿠키
browser-data-canary-2 =
    .label = 쿠키
    .value = 쿠키
browser-data-firefox-2 =
    .label = 쿠키
    .value = 쿠키
browser-data-360se-2 =
    .label = 쿠키
    .value = 쿠키
browser-data-ie-4 =
    .label = 방문 기록
    .value = 방문 기록
browser-data-edge-4 =
    .label = 방문 기록
    .value = 방문 기록
browser-data-safari-4 =
    .label = 방문 기록
    .value = 방문 기록
browser-data-chrome-4 =
    .label = 방문 기록
    .value = 방문 기록
browser-data-canary-4 =
    .label = 방문 기록
    .value = 방문 기록
browser-data-firefox-history-and-bookmarks-4 =
    .label = 방문 기록 및 북마크
    .value = 방문 기록 및 북마크
browser-data-360se-4 =
    .label = 방문 기록
    .value = 방문 기록
browser-data-ie-8 =
    .label = 저장된 양식 기록
    .value = 저장된 양식 기록
browser-data-edge-8 =
    .label = 저장된 양식 기록
    .value = 저장된 양식 기록
browser-data-safari-8 =
    .label = 저장된 양식 기록
    .value = 저장된 양식 기록
browser-data-chrome-8 =
    .label = 저장된 양식 기록
    .value = 저장된 양식 기록
browser-data-canary-8 =
    .label = 저장된 양식 기록
    .value = 저장된 양식 기록
browser-data-firefox-8 =
    .label = 저장된 양식 기록
    .value = 저장된 양식 기록
browser-data-360se-8 =
    .label = 저장된 양식 기록
    .value = 저장된 양식 기록
browser-data-ie-16 =
    .label = 저장된 비밀번호
    .value = 저장된 비밀번호
browser-data-edge-16 =
    .label = 저장된 비밀번호
    .value = 저장된 비밀번호
browser-data-safari-16 =
    .label = 저장된 비밀번호
    .value = 저장된 비밀번호
browser-data-chrome-16 =
    .label = 저장된 비밀번호
    .value = 저장된 비밀번호
browser-data-canary-16 =
    .label = 저장된 비밀번호
    .value = 저장된 비밀번호
browser-data-firefox-16 =
    .label = 저장된 비밀번호
    .value = 저장된 비밀번호
browser-data-360se-16 =
    .label = 저장된 비밀번호
    .value = 저장된 비밀번호
browser-data-ie-32 =
    .label = 즐겨찾기
    .value = 즐겨찾기
browser-data-edge-32 =
    .label = 즐겨찾기
    .value = 즐겨찾기
browser-data-safari-32 =
    .label = 북마크
    .value = 북마크
browser-data-chrome-32 =
    .label = 북마크
    .value = 북마크
browser-data-canary-32 =
    .label = 북마크
    .value = 북마크
browser-data-360se-32 =
    .label = 북마크
    .value = 북마크
browser-data-ie-64 =
    .label = 기타 데이터
    .value = 기타 데이터
browser-data-edge-64 =
    .label = 기타 데이터
    .value = 기타 데이터
browser-data-safari-64 =
    .label = 기타 데이터
    .value = 기타 데이터
browser-data-chrome-64 =
    .label = 기타 데이터
    .value = 기타 데이터
browser-data-canary-64 =
    .label = 기타 데이터
    .value = 기타 데이터
browser-data-firefox-other-64 =
    .label = 기타 데이터
    .value = 기타 데이터
browser-data-360se-64 =
    .label = 기타 데이터
    .value = 기타 데이터
browser-data-firefox-128 =
    .label = 창과 탭
    .value = 창과 탭
