# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

report-broken-site-mainview-title = 깨진 사이트 신고
report-broken-site-panel-header =
    .label = 깨진 사이트 신고
    .title = 깨진 사이트 신고
report-broken-site-panel-intro-text = 여러분의 신고는 저희가 { -brand-product-name }의 문제를 이해하고 고쳐서 모든 사람을 위해 더 나은 제품으로 만들도록 도움을 줍니다.
report-broken-site-panel-learn-more-link = 더 알아보기
report-broken-site-panel-url-label = 깨진 사이트 URL
report-broken-site-panel-reason-intro-text = 작동하지 않는 것은 무엇입니까?
report-broken-site-panel-reason-load-moz-box-button =
    .label = 사이트가 로드되지 않음
# These terms are referring to ecommerce websites
report-broken-site-panel-reason-checkout-moz-box-button =
    .label = 결제, 체크 아웃 또는 쇼핑 할 수 없음
report-broken-site-panel-reason-slow-moz-box-button =
    .label = 사이트가 느림
report-broken-site-panel-reason-media-moz-box-button =
    .label = 동영상이 재생되지 않거나 로딩되지 않음
report-broken-site-panel-reason-content-moz-box-button =
    .label = 콘텐츠 누락
report-broken-site-panel-reason-account-moz-box-button =
    .label = 로그인 또는 등록할 수 없음
report-broken-site-panel-reason-adblocker-moz-box-button =
    .label = 사이트가 광고 차단기를 끄도록 요청함
report-broken-site-panel-reason-notsupported-moz-box-button =
    .label = 지원되지 않거나 차단된 브라우저
report-broken-site-panel-reason-deceptive-moz-box-button =
    .label = 의심스러운 사이트
report-broken-site-panel-reason-other-moz-box-button =
    .label = 그 밖의 다른 것
report-broken-site-panel-instructions-other = 조사에 도움이 되도록 문제를 자세히 설명해 주세요.
report-broken-site-panel-instructions-other-optional = 조사에 도움이 되도록 문제를 자세히 설명해 주세요. (선택 사항)
report-broken-site-panel-description2 =
    .placeholder = 무슨 일이 있었나요? 어떤 일이 일어날 것이라고 예상하셨나요? 문제를 재현하는 방법을 알려주세요.
report-broken-site-panel-send-more-info-button =
    .label = 추가 정보 보내기
report-broken-site-panel-intro = 모든 사람에게 더 나은 { -brand-product-name }를 만들 수 있도록 도와주세요. { -vendor-short-name }는 사용자가 보내는 정보를 사용하여 웹 사이트 문제를 해결합니다.
report-broken-site-panel-url = URL
report-broken-site-panel-reason-label = 어떤 문제인가요?
report-broken-site-panel-reason-optional-label = 어떤 문제인가요? (선택 사항)
report-broken-site-panel-reason-choose =
    .label = 이유 선택
report-broken-site-panel-reason-load =
    .label = 사이트가 로드되지 않음
# These terms are referring to ecommerce websites
report-broken-site-panel-reason-checkout =
    .label = 결제, 체크 아웃 또는 쇼핑 할 수 없음
report-broken-site-panel-reason-slow2 =
    .label = 사이트가 느림
report-broken-site-panel-reason-media2 =
    .label = 동영상이 재생되지 않거나 로딩되지 않음
report-broken-site-panel-reason-content2 =
    .label = 콘텐츠 누락
report-broken-site-panel-reason-account2 =
    .label = 로그인 또는 등록할 수 없음
report-broken-site-panel-reason-adblocker2 =
    .label = 사이트가 광고 차단기를 끄도록 요청함
report-broken-site-panel-reason-notsupported =
    .label = 지원되지 않거나 차단된 브라우저
report-broken-site-panel-reason-other =
    .label = 그 밖의 다른 것
report-broken-site-panel-description-label = 문제 설명
report-broken-site-panel-description-optional-label = 문제 설명 (선택 사항)
report-broken-site-panel-send-more-info-link = 추가 정보 보내기
report-broken-site-panel-button-cancel =
    .label = 취소
report-broken-site-panel-button-okay =
    .label = 확인
report-broken-site-panel-button-send-report =
    .label = 보고서 보내기
report-broken-site-panel-button-send =
    .label = 보내기
report-broken-site-panel-report-sent-label = 신고가 전송됨
report-broken-site-panel-report-sent-header =
    .label = 신고가 전송됨
    .title = 신고가 전송됨
report-broken-site-panel-report-sent-text = { -brand-product-name }가 웹을 모두에게 더 개방적이고 접근 가능하며 더 나은 환경으로 만드는 데 도움을 주셔서 감사합니다.
report-broken-site-panel-invalid-url-label = 올바른 URL을 입력하세요
# $minLength (number) - The minimum number of characters required in the description textarea.
report-broken-site-panel-invalid-description-label = { $minLength }자 이상 입력하세요
report-broken-site-panel-screenshot-label =
    .label = 스크린샷 보내기
report-broken-site-panel-blocked-trackers-label2 =
    .label = 추적 방지 기능에 의해 차단된 항목 목록 보내기
report-broken-site-panel-url-input-label =
    .aria-label = 신고된 페이지의 URL
report-broken-site-panel-missing-reason-label = 이유를 선택하세요
report-broken-site-panel-preview-button =
    .label = 보고서 미리보기
report-broken-site-panel-preview-header2 =
    .title = 보고서 미리보기
