# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Bewarje
dialogTitleAddBookmark = Nije blêdwizer
dialogTitleAddMulti = Nije blêdwizers
dialogTitleEdit = Eigenskippen fan ‘%S’
dialogTitleAddNewBookmark2 = Blêdwizer tafoegje
dialogTitleEditBookmark = ‘%S’ bewurkje
dialogTitleEditBookmark2 = Blêdwizer bewurkje
dialogTitleAddBookmarkFolder = Blêdwizermap tafoegje
dialogTitleEditBookmarkFolder = Blêdwizermap bewurkje
bookmarkAllTabsDefault = [Mapnamme]
newFolderDefault = Nije map
newBookmarkDefault = Nije blêdwizer
