# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = A' lorg { $host }…
network-connection-status-connected = Air ceangal a dhèanamh ri { $host }…
network-connection-status-sending-request = A' cur iarrtas gu { $host }…
network-connection-status-transferring-data = A' tar-aiseag dàta o { $host }…
network-connection-status-connecting = A' dèanamh ceangal ri { $host }…
network-connection-status-looked-up = Chaidh { $host } a lorg…
network-connection-status-tls-handshake = A’ dèanamh crathadh-làimhe TLS le { $host }…
network-connection-status-tls-handshake-finished = Chaidh an crathadh-làimhe TLS airson { $host } a choileanadh…
