# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Sparade Inloggningar
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-username-cmd =
    .label = Kopiera användarnamn
    .accesskey = a
edit-username-cmd =
    .label = Redigera användarnamn
    .accesskey = d
copy-password-cmd =
    .label = Kopiera lösenord
    .accesskey = o
edit-password-cmd =
    .label = Redigera lösenord
    .accesskey = R
column-heading-site =
    .label = Webbplats
column-heading-username =
    .label = Användarnamn
column-heading-password =
    .label = Lösenord
column-heading-time-created =
    .label = Först använd
column-heading-time-last-used =
    .label = Senast använd
column-heading-time-password-changed =
    .label = Senast ändrad
column-heading-times-used =
    .label = Använd gånger
remove =
    .label = Ta bort
    .accesskey = T
import =
    .label = Importera…
    .accesskey = I
close-button =
    .label = Stäng
    .accesskey = ä
logins-description-filtered = Följande inloggningar matchar din sökning:
remove-all-passwords-prompt = Är du säker på att du vill ta bort alla lösenord?
remove-all-passwords-title = Ta bort alla lösenord
no-master-password-prompt = Är du säker på att du vill visa dina lösenord?
