# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Spašene prijave
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Kopiraj URL
    .accesskey = K
launch-site-url-cmd =
    .label = Posjeti URL
    .accesskey = P
copy-username-cmd =
    .label = Kopiraj korisničko ime
    .accesskey = K
edit-username-cmd =
    .label = Uredi korisničko ime
    .accesskey = d
copy-password-cmd =
    .label = Kopiraj lozinku
    .accesskey = K
edit-password-cmd =
    .label = Uredi lozinku
    .accesskey = e
search-filter =
    .accesskey = T
    .placeholder = Traži
column-heading-site =
    .label = Stranica
column-heading-username =
    .label = Korisničko ime
column-heading-password =
    .label = Lozinka
column-heading-time-created =
    .label = Prvi put korišteno
column-heading-time-last-used =
    .label = Zadnji put korišteno
column-heading-time-password-changed =
    .label = Zadnja promjena
column-heading-times-used =
    .label = Broj korištenja
remove =
    .label = Ukloni
    .accesskey = U
import =
    .label = Uvoz…
    .accesskey = U
close-button =
    .label = Zatvori
    .accesskey = Z
show-passwords =
    .label = Prikaži lozinke
    .accesskey = P
hide-passwords =
    .label = Sakrij lozinke
    .accesskey = P
logins-description-all = Prijave za sljedeće stranice su pohranjene na vašem računaru
logins-description-filtered = Navedene lozinke se podudaraju sa pretragom:
remove-all =
    .label = Ukloni sve
    .accesskey = s
remove-all-shown =
    .label = Ukloni sve prikazane
    .accesskey = s
remove-all-passwords-prompt = Da li ste sigurni da želite ukloniti sve lozinke?
remove-all-passwords-title = Ukloni sve lozinke
no-master-password-prompt = Da li ste sigurni da želite prikazati vaše lozinke?
auto-fill-logins-and-passwords =
    .label = Automatsko popunjavanje prijava i lozinki
