# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Authenticationes salvate
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Copiar le URL
    .accesskey = U
launch-site-url-cmd =
    .label = Visitar le URL
    .accesskey = V
copy-username-cmd =
    .label = Copiar le nomine de usator
    .accesskey = n
edit-username-cmd =
    .label = Modificar le nomine de usator
    .accesskey = o
copy-password-cmd =
    .label = Copiar le contrasigno
    .accesskey = C
edit-password-cmd =
    .label = Modificar le contrasigno
    .accesskey = M
search-filter =
    .accesskey = C
    .placeholder = Cercar
column-heading-site =
    .label = Sito
column-heading-username =
    .label = Nomine de usator
column-heading-password =
    .label = Contrasigno
column-heading-time-created =
    .label = Prime vice usate
column-heading-time-last-used =
    .label = Ultime vice usate
column-heading-time-password-changed =
    .label = Ultime vice cambiate
column-heading-times-used =
    .label = Vices usate
remove =
    .label = Remover
    .accesskey = R
import =
    .label = Importar…
    .accesskey = I
close-button =
    .label = Clauder
    .accesskey = C
show-passwords =
    .label = Monstrar le contrasignos
    .accesskey = c
hide-passwords =
    .label = Celar le contrasigno
    .accesskey = P
logins-description-all = Le authenticationes pro le sitos sequente es salvate in tu computator
logins-description-filtered = Le authenticationes sequente corresponde a tu recerca:
remove-all =
    .label = Remover toto
    .accesskey = t
remove-all-shown =
    .label = Remover tote lo monstrate
    .accesskey = t
remove-all-passwords-prompt = Desira tu vermente remover tote le contrasignos?
remove-all-passwords-title = Remover tote le contrasignos
no-master-password-prompt = Desira tu vermente monstrar tu contrasignos?
auto-fill-logins-and-passwords =
    .label = Auto-popular le authenticationes pro apertura de session e le contrasignos
