# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = ਸਮਾਂ ਸਮਾਪਤ ਹੋਇਆ
openFile = ਫਾਈਲ ਨੂੰ ਖੋਲ੍ਹੋ
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = "%2$S" ਲਈ %1$S ਖੋਜ
contextMenuSearch.accesskey = S
contextMenuPrivateSearch = ਪ੍ਰਾਈਵੇਟ ਵਿੰਡੋ ਵਿੱਚ ਖੋਜੋ
contextMenuPrivateSearch.accesskey = h
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = ਇੱਕ ਪ੍ਰਾਈਵੇਟ ਵਿੰਡੋ ਵਿੱਚ %S ਨਾਲ ਖੋਜ ਕਰੋ
contextMenuPrivateSearchOtherEngine.accesskey = h
bookmarkAllTabsDefault = [ਫੋਲਡਰ ਦਾ ਨਾਂ]
unsignedAddonsDisabled.message = ਇੱਕ ਜਾਂ ਵੱਧ ਇੰਸਟਾਲ ਹੋਈਆਂ ਐਡ-ਆਨ ਨੂੰ ਤਸਦੀਕ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਦਾ ਅਤੇ ਅਸਮਰੱਥ ਬਣਾਇਆ ਗਿਆ ਹੈ।
unsignedAddonsDisabled.learnMore.label = ਹੋਰ ਜਾਣੋ
unsignedAddonsDisabled.learnMore.accesskey = L
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = ਆਖਰੀ ਐਕਸੈਸ %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = %S:// links
crashedpluginsMessage.title = %S ਪਲੱਗਇਨ ਕਰੈਸ਼ ਕਰ ਗਈ ਹੈ।
crashedpluginsMessage.reloadButton.label = ਸਫ਼ੇ ਨੂੰ ਮੁੜ-ਲੋਡ ਕਰੋ
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = ਕਰੈਸ਼ ਰਿਪੋਰਟ ਭੇਜੋ
crashedpluginsMessage.submitButton.accesskey = S
crashedpluginsMessage.learnMore = …ਹੋਰ ਜਾਣੋ
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = ਕੀ ਤੁਹਾਡਾ ਮਤਲਬ %S ਉੱਤੇ ਜਾਣ ਤੋਂ ਹੈ?
keywordURIFixup.goTo = ਹਾਂ, ਮੈਨੂੰ %S ਉੱਤੇ ਲੈ ਕੇ ਜਾਓ
keywordURIFixup.goTo.accesskey = Y
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = %S ਲਈ ਅੱਪਡੇਟ ਕਰੋ
update.downloadAndInstallButton.accesskey = U
menuOpenAllInTabs.label = ਸਭ ਨੂੰ ਟੈਬਾਂ 'ਚ ਖੋਲ੍ਹੋ
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = ਇਹ ਸਫ਼ਾ ਮੁੜ-ਲੋਡ ਕਰੋ
tabHistory.goBack = ਇਹ ਸਫ਼ੇ ਉੱਤੇ ਪਿੱਛੇ ਜਾਓ
tabHistory.goForward = ਇਹ ਸਫ਼ੇ ਲਈ ਅੱਗੇ ਜਾਓ
# URL Bar
pasteAndGo.label = ਚੇਪੋ ਅਤੇ ਖੋਲ੍ਹੋ
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = ਮੌਜੂਦਾ ਸਫ਼ੇ ਨੂੰ ਮੁੜ ਲੋਡ ਕਰੋ (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = ਇਸ ਸਫ਼ੇ ਨੂੰ ਲੋਡ ਹੋਣ ਤੋਂ ਰੋਕੋ (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = ਜ਼ੂਮ ਪੱਧਰ ਮੁੜ-ਸੈੱਟ ਕਰੋ (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = ਰੀਡਰ ਝਲਕ ਬਦਲੋ (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, ਜ਼ੂਮ ਪੱਧਰ ਨੂੰ ਮੁੜ-ਸੈੱਟ ਕਰੋ
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = ਆਪਣੇ ਬੁੱਕਮਾਰਕਾਂ ਨੂੰ ਵੇਖੋ (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = ਜਾਰੀ ਡਾਊਨਲੋਡ ਦੀ ਤਰੱਕੀ ਬਾਰੇ ਜਾਣਕਾਰੀ ਵੇਖੋ (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = ਨਵੀਂ ਵਿੰਡੋ ਨੂੰ ਖੋਲ੍ਹੋ (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = ਨਵੀਂ ਟੈਬ ਨੂੰ ਖੋਲ੍ਹੋ (%S)
newTabContainer.tooltip = ਨਵੀਂ ਟੈਬ (%S) ਖੋਲ੍ਹੋ\nਨਵੀਂ ਕਨਟੇਨਰ ਟੈਬ ਖੋਲ੍ਹਣ ਲਈ ਦਬਾ ਕੇ ਰੱਖੋ
newTabAlwaysContainer.tooltip = ਨਵੀਂ ਟੈਬ ਖੋਲ੍ਹਣ ਲਈ ਕਨਟੇਨਰ ਚੁਣੋ
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = %S ਨੂੰ ਤੁਹਾਡੇ HTML5 ਕੈਨਵਸ ਚਿੱਤਰ ਡਾਟੇ ਨੂੰ ਵਰਤਣ ਲਈ ਸਹਿਮਤੀ ਦੇਣੀ ਹੈ?
canvas.siteprompt2.warning = ਇਹ ਤੁਹਾਡੇ ਕੰਪਿਊਤਰ ਨੂੰ ਵਿਲੱਖਣ ਤੌਰ ਉੱਤੇ ਪਛਾਣ ਲਈ ਵਰਤਿਆ ਜਾ ਸਕਦਾ ਹੈ।
canvas.block = ਪਾਬੰਦੀ
canvas.block.accesskey = B
canvas.allow2 = ਮਨਜ਼ੂਰ
canvas.allow2.accesskey = A
canvas.remember2 = ਇਹ ਫ਼ੈਸਲੇ ਨੂੰ ਯਾਦ ਰੱਖੋ
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = ਜਾਂਚਿਆ: %S
identity.identified.verified_by_you = ਤੁਸੀਂ ਇਹ ਸਾਇਟ ਲਈ ਇੱਕ ਸੁਰੱਖਿਆ ਛੋਟ ਸ਼ਾਮਲ ਕਰ ਸਕਦੇ ਹੋ।
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = ਸਰਟੀਫਿਕੇਟ ਜਾਰੀ ਕੀਤਾ: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = ਸੁਰੱਖਿਅਤ ਨਹੀਂ
identity.notSecure.tooltip = ਕਨੈਕਸ਼ਨ ਸੁਰੱਖਿਅਤ ਨਹੀਂ ਹੈ
identity.extension.label = ਇਕਸਟੈਨਸ਼ਨ (%S)
identity.extension.tooltip = ਇਕਸਟੈਨਸ਼ਨ ਰਾਹੀਂ ਲੋਡ ਕੀਤਾ: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = ਜ਼ੂਮ ਆਉਟ (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = ਜ਼ੂਮ ਪੱਧਰ ਮੁੜ-ਸੈੱਟ ਕਰੋ(%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = ਜ਼ੂਮ ਇਨ (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = ਕੱਟੋ (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = ਕਾਪੀ ਕਰੋ (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = ਚੇਪੋ (%S)
geolocation.allow = ਮਨਜ਼ੂਰ
geolocation.allow.accesskey = A
geolocation.block = ਪਾਬੰਦੀ
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = ਇਹ ਸਿਸਟਮ ਟਿਕਾਣਾ ਸੈਟਿੰਗਾਂ ਨੂੰ ਖੋਲ੍ਹੇਗਾ। %S ਨੂੰ ਟਿਕਾਣਾ ਵਰਤਣ ਦੀ ਮਨਜ਼ੂਰੀ ਦਿਓ।
geolocation.shareWithSite4 = ਕੀ %S ਨੂੰ ਤੁਹਾਡੇ ਟਿਕਾਣੇ ਲਈ ਪਹੁੰਚ ਦੀ ਮਨਜ਼ੂਰੀ ਦੇਣੀ ਹੈ?
geolocation.shareWithFile4 = ਕੀ ਇਸ ਲੋਕਲ ਫਾਇਲ ਨੂੰ ਤੁਹਾਡੇ ਟਿਕਾਣੇ ਲਈ ਪਹੁੰਚ ਦੀ ਮਨਜ਼ੂਰੀ ਦੇਣੀ ਹੈ?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = ਕੀ %1$S ਨੂੰ ਤੁਹਾਡੇ ਟਿਕਾਣੇ ਲਈ ਪਹੁੰਚ ਕਰਨ ਵਾਸਤੇ %2$S ਇਜਾਜ਼ਤ ਦੇਣੀ ਹੈ?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = %S ਨੂੰ ਸਿਸਟਮ ਸੈਟਿੰਗਾਂ ਵਿੱਚ ਟਿਕਾਣਾ ਵਰਤਣ ਦੀ ਮਨਜ਼ੂਰੀ ਦਿਓ।
geolocation.systemSettingsTitle = ਟਿਕਾਣੇ ਲਈ ਮਨਜ਼ੂਰੀ ਦੀ ਉਡੀਕ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = ਸਿਸਤਮ ਤੁਹਾਨੂੰ %S ਨੂੰ ਇਹ ਮਨਜ਼ੂਰੀ ਦੇਣ ਲਈ ਪੁੱਛੇਗਾ।
geolocation.remember = ਇਹ ਫੈਸਲਾ ਯਾਦ ਰੱਖੋ
# Virtual Reality Device UI
xr.allow2 = ਮਨਜ਼ੂਰ
xr.allow2.accesskey = A
xr.block = ਪਾਬੰਦੀ
xr.block.accesskey = B
xr.shareWithSite4 = %S ਨੂੰ ਵਰਚੁਅਲ ਰਿਐਲਟੀ ਡਿਵਾਈਸਾਂ ਲਈ ਪਹੁੰਚ ਦੀ ਮਨਜ਼ੂਰੀ ਦੇਣੀ ਹੈ? ਇਹ ਨਾਲ ਸੰਵੇਦਨਸ਼ੀਲ ਜਾਣਕਾਰੀ ਪ੍ਰਗਟ ਹੋ ਸਕਦੀ ਹੈ।
xr.shareWithFile4 = ਕੀ ਇਸ ਲੋਕਲ ਫਾਇਲ ਨੂੰ ਮਵਰਚੁਅਲ ਰਿਐਲਟੀ ਡਿਵਾਈਸਾਂ ਲਈ ਪਹੁੰਚ ਦੀ ਮਨਜ਼ੂਰੀ ਦੇਣੀ ਹੈ? ਇਹ ਨਾਲ ਸੰਵੇਦਨਸ਼ੀਲ ਜਾਣਕਾਰੀ ਪ੍ਰਗਟ ਹੋ ਸਕਦੀ ਹੈ।
xr.remember = ਇਹ ਫ਼ੈਸਲਾ ਯਾਦ ਰੱਖੋ
# Persistent storage UI
persistentStorage.allow = ਮਨਜ਼ੂਰ
persistentStorage.allow.accesskey = A
persistentStorage.block.label = ਪਾਬੰਦੀ
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = ਕੀ %S ਨੂੰ ਪੱਕੀ ਸਟੋਰੇਜ਼ ਵਿੱਚ ਡਾਟਾ ਸਟੋਰ ਕਰਨ ਦੀ ਸਹਿਮਤੀ ਦੇਣੀ ਹੈ?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = ਮਨਜ਼ੂਰ
webNotifications.allow2.accesskey = A
webNotifications.notNow = ਕਦੇ ਨਹੀਂ
webNotifications.notNow.accesskey = n
webNotifications.never = ਕਦੇ ਵੀ ਇਜ਼ਾਜ਼ਤ ਨਾ ਦਿਓ
webNotifications.never.accesskey = v
webNotifications.alwaysBlock = ਹਮੇਸ਼ਾਂ ਪਾਬੰਦੀ ਲਾਓ
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = ਪਾਬੰਦੀ
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = %S ਨੂੰ ਸੂਚਨਾਵਾਂ ਭੇਜਣ ਦੀ ਸਹਿਮਤੀ ਦੇਣੀ ਹੈ?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S ਇਸ ਡਿਵਾਈਸ ਉੱਤੇ ਹੋਰ ਐਪਾਂ ਅਤੇ ਸਰਵਿਸਾਂ ਲਈ ਪਹੁੰਚ ਚਾਹੁੰਦੀ ਹੈ।
localhost.remember2 = ਇਸ ਸਾਈਟ ਲਈ ਮੇਰੀ ਚੋਣ ਨੂੰ ਯਾਦ ਰੱਖੋ
localhost.allowlabel = ਮਨਜ਼ੂਰ
localhost.blocklabel = ਪਾਬੰਦੀ
localhost.allow.accesskey = A
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S ਤੁਹਾਡੇ ਲੋਕਲ ਨੈੱਟਵਰਕ ਉੱਤੇ ਕਨੈਕਟ ਹੋਏ ਡਿਵਾਈਸਾਂ ਉੱਤੇ ਐਪਾਂ ਅਤੇ ਸੇਵਾਵਾਂ ਲਈ ਪਹੁੰਚ ਚਾਹੁੰਦੀ ਹੈ।
localNetwork.remember2 = ਇਸ ਸਾਈਟ ਲਈ ਮੇਰੀ ਚੋਣ ਨੂੰ ਯਾਦ ਰੱਖੋ
localNetwork.allowLabel = ਮਨਜ਼ੂਰ
localNetwork.allow.accesskey = A
localNetwork.blockLabel = ਪਾਬੰਦੀ
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = ਮੈਨੂੰ ਇੱਥੋਂ ਕੱਢੋ!
safebrowsing.getMeOutOfHereButton.accessKey = G
safebrowsing.deceptiveSite = ਭਰਮਪੂਰਨ ਸਾਈਟ!
safebrowsing.notADeceptiveSiteButton.label = ਇਹ ਭਰਮਪੂਰਨ ਸਾਈਟ ਨਹੀਂ ਹੈ…
safebrowsing.notADeceptiveSiteButton.accessKey = D
safebrowsing.reportedAttackSite = ਹਮਲਾਵਰ ਸਾਈਟ ਵਜੋਂ ਰਿਪੋਰਟ ਕਰੋ!
safebrowsing.notAnAttackButton.label = …ਇਹ ਹਮਲਾਵਰ ਸਾਈਟ ਨਹੀਂ ਹੈ
safebrowsing.notAnAttackButton.accessKey = A
safebrowsing.reportedUnwantedSite = ਬੇਲੋੜੀ ਸਾਫਟਵੇਅਰ ਵੈਬਸਾਈਟ ਵਜੋਂ ਰਿਪੋਰਟ ਕਰੋ!
safebrowsing.reportedHarmfulSite = ਨੁਕਸਾਨਦਾਇਕ ਸਾਈਟ ਵਜੋਂ ਰਿਪੋਰਟ ਕੀਤਾ!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = %S ਖੋਜ
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = %S ਨੂੰ ਸਮੱਸਿਆ ਨਿਪਾਟਾਰਾ ਢੰਗ ਵਿੱਚ ਮੁੜ ਸ਼ੁਰੂ ਕਰਨਾ ਹੈ?
troubleshootModeRestartPromptMessage = ਤੁਹਾਡੀਆਂ ਇਕਸਟੈਨਸ਼ਨਾਂ, ਥੀਮਾਂ ਅਤੇ ਕਸਟਮ ਸੈਟਿੰਗਾਂ ਨੂੰ ਆਰਜ਼ੀ ਤੌਰ ਉੱਤੇ ਬੰਦ ਕੀਤਾ ਜਾਵੇਗਾ।
troubleshootModeRestartButton = ਮੁੜ-ਸ਼ੁਰੂ ਕਰੋ
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = ਇਸ ਸਫ਼ਾ %1$S ਨੂੰ ਹੌਲੀ ਕਰ ਰਿਹਾ ਹੈ। ਆਪਣੇ ਬਰਾਊਜ਼ਰ ਨੂੰ ਤੇਜ਼ ਕਰਨ ਲਈ ਇਸ ਸਫ਼ੇ ਨੂੰ ਰੋਕੋ।
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = ਵੈੱਬ ਸਫ਼ਾ %1$S ਨੂੰ ਹੌਲੀ ਕਰ ਰਿਹਾ ਹੈ। ਆਪਣੇ ਬਰਾਊਜ਼ਰ ਨੂੰ ਤੇਜ਼ ਕਰਨ ਲਈ ਉਸ ਸਫ਼ੇ ਨੂੰ ਰੋਕੋ।
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = “%1$S”  %2$S ਨੂੰ ਹੌਲੀ ਕਰ ਰਿਹਾ ਹੈ। ਆਪਣੇ ਬਰਾਊਜ਼ਰ ਨੂੰ ਤੇਜ਼ ਕਰਨ ਲਈ ਉਸ ਸਫ਼ੇ ਨੂੰ ਰੋਕੋ।
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = “%1$S” %2$S ਨੂੰ ਹੌਲੀ ਕਰ ਰਹੀ ਹੈ। ਆਪਣੇ ਬਰਾਊਜ਼ਰ ਨੂੰ ਤੇਜ਼ ਕਰਨ ਲਈ ਉਸ ਇਕਸਟੈਨਸ਼ਨ ਨੂੰ ਰੋਕੋ।
processHang.add-on.learn-more.text = ਹੋਰ ਜਾਣੋ
processHang.button_stop2.label = ਠਹਿਰੋ
processHang.button_stop2.accessKey = S
processHang.button_debug.label = ਸਕ੍ਰਿਪਟ ਨੂੰ ਡੀਬੱਗ ਕਰੋ
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = ਵਿੰਡੋ ਪੂਰੀ ਸਕਰੀਨ 'ਤੇ ਵੇਖਾਓ (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = ਬਾਹੀ ਨੂੰ ਖੱਬੇ ਭੇਜੋ
sidebar.moveToRight = ਬਾਹੀ ਨੂੰ ਸੱਜੇ ਭੇਜੋ
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = ਇਸ ਸਫ਼ੇ ਉੱਤੇ ਕੁਝ ਆਡੀਓ ਜਾਂ ਵੀਡੀਓ ਨੂੰ ਚਲਾਉਣ ਲਈ ਤੁਹਾਨੂੰ DRM ਸਮਰੱਥ ਕਰਨੇ ਜ਼ਰੂਰੀ ਹਨ।
emeNotifications.drmContentDisabled.button.label = DRM ਸਮਰੱਥ ਕਰੋ
emeNotifications.drmContentDisabled.button.accesskey = E
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S ਭਾਗਾਂ ਨੂੰ ਇੰਸਟਾਲ ਕਰ ਰਿਹਾ ਹੈ, ਜੋ ਕਿ ਇਸ ਸਫ਼ੇ ਉੱਤੇ ਆਡੀਓ ਜਾਂ ਵੀਡੀਓ ਚਲਾਉਣ ਲਈ ਚਾਹੀਦੇ ਹਨ। ਬਾਅਦ ਵਿੱਚ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।
emeNotifications.unknownDRMSoftware = ਅਣਜਾਣ
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = %S ਨੂੰ ਕਸਟਮਾਈਜ਼ ਕਰੋ
decoder.noCodecs.button = ਸਿੱਖੋ ਕਿ ਕਿਵੇਂ
decoder.noCodecs.accesskey = L
decoder.noCodecsLinux.message = ਵੀਡੀਓ ਚਲਾਉਣ ਲਈ ਤੁਹਾਨੂੰ ਵੀਡੀਓ codecs ਇੰਸਟਾਲ ਕਰਨ ਦੀ ਲੋੜ ਹੋ ਸਕਦੀ ਹੈ।
decoder.noHWAcceleration.message = ਵੀਡੀਓ ਕੁਆਲਟੀ ਨੂੰ ਸੁਧਾਰਨ ਲਈ ਤੁਹਾਨੂੰ Microsoft ਦੇ ਮੀਡੀਆ ਫੀਚਰ ਪੈਕ ਨੂੰ ਇੰਸਟਾਲ ਕਰਨ ਦੀ ਲੋੜ ਹੋ ਸਕਦੀ ਹੈ।
decoder.noPulseAudio.message = ਆਡੀਓ ਚਲਾਉਣ ਲਈ ਤੁਹਾਨੂੰ ਲੋੜੀਂਦੇ PulseAudio ਸਾਫਟਵੇਅਰ ਇੰਸਟਾਲ ਕਰਨ ਦੀ ਲੋੜ ਹੈ।
decoder.unsupportedLibavcodec.message = libavcodec ਕਮਜ਼ੋਰ ਹੋ ਸਕਦੀ ਹੈ ਜਾਂ ਸਹਾਇਕ ਨਹੀਂ ਹੋ ਸਕਦੀ ਅਤੇ ਵੀਡੀਓ ਚਲਾਉਣ ਲਈ ਅੱਪਡੇਟ ਕਰਨਾ ਜ਼ਰੂਰੀ ਹੈ।
decoder.decodeError.message = ਮੀਡੀਆ ਸਰੋਤ ਨੂੰ ਡੀਕੋਡ ਕਰਨ ਦੇ ਦੌਰਾਨ ਗਲਤੀ ਵਾਪਰੀ ਹੈ।
decoder.decodeError.button = ਸਾਈਟ ਮਸਲੇ ਬਾਰੇ ਰਿਪੋਰਟ ਦਿਓ
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = ਮੀਡੀਆ ਸਰੋਤ ਨੂੰ ਡੀਕੋਡ ਕਰਨ ਦੌਰਾਨ ਪ੍ਰਾਪਤ ਕਰਨ ਯੋਗ ਗ਼ਲਤੀ ਵਾਪਰੀ ਹੈ।
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = ਇੰਟਰਨੈੱਟ ਦੀ ਵਰਤੋਂ ਕਰਨ ਵਾਸਤੇ ਪਹਿਲਾਂ ਤੁਹਾਨੂੰ ਇਸ ਨੈੱਟਵਰਕ ਵਿੱਚ ਲਾਗਇਨ ਕਰਨਾ ਪਵੇਗਾ।
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = ਨੈੱਟਵਰਕ ਲਾਗਇਨ ਸਫ਼ੇ ਨੂੰ ਖੋਲ੍ਹੋ
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = %S ਲਈ ਇਜਾਜ਼ਤਾਂ
permissions.remove.tooltip = ਇਹ ਇਜਾਜ਼ਤ ਸਾਫ਼ ਕਰੋ ਅਤੇ ਮੁੜ ਪੁੱਛੋ
permissions.fullscreen.promptCanceled = ਬਾਕੀ ਰਹਿੰਦੀਆਂ ਇਜਾਜ਼ਤ ਬੇਨਤੀਆਂ ਰੱਦ ਕੀਤੀਆਂ: DOM ਪੂਰੀ ਸਕਰੀਨ ਉੱਤੇ ਜਾਣ ਤੋਂ ਪਹਿਲਾਂ ਇਜ਼ਾਜ਼ਤ ਬੇਨਤੀਆਂ ਜਾਰੀ ਨਹੀਂ ਕੀਤੀਆਂ ਜਾਣੀਆਂ ਚਾਹੀਦੀਆਂ ਹਨ।
permissions.fullscreen.fullScreenCanceled = ਬੰਦ ਕੀਤੀ DOM ਪੂਰੀ ਸਕਰੀਨ: DOM ਪੂਰੀ ਸਕਰੀਨ ਉੱਤੇ ਜਾਣ ਤੋਂ ਪਹਿਲਾਂ ਇਜਾਜ਼ਤ ਬੇਨਤੀਆਂ
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-ਬਿੱਟ
aboutDialog.architecture.thirtyTwoBit = 32-ਬਿੱਟ
midi.allow.label = ਮਨਜ਼ੂਰ
midi.allow.accesskey = A
midi.block.label = ਪਾਬੰਦੀ
midi.block.accesskey = B
midi.remember = ਇਹ ਫ਼ੈਸਲਾ ਯਾਦ ਰੱਖੋ
midi.shareWithFile = ਕੀ ਇਸ ਲੋਕਲ ਫਾਇਲ ਨੂੰ ਤੁਹਾਡੇ MIDI ਡਿਵਾਈਸਾਂ ਲਈ ਪਹੁੰਚ ਦੀ ਮਨਜ਼ੂਰੀ ਦੇਣੀ ਹੈ?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = ਕੀ %S ਨੂੰ ਤੁਹਾਡੇ MIDI ਡਿਵਾਈਸਾਂ ਲਈ ਪਹੁੰਚ ਦੀ ਮਨਜ਼ੂਰੀ ਦੇਣੀ ਹੈ?
midi.shareSysexWithFile = ਕੀ ਇਸ ਲੋਕਲ ਫਾਈਲ ਨੂੰ ਆਪਣੇ MIDI ਡਿਵਾਈਸ ਤੱਕ ਪਹੁੰਚਣ ਅਤੇ SysEx ਸੁਨੇਹੇ ਭੇਜਣ/ਲੈਣ ਦੀ ਮਨਜ਼ੂਰੀ ਦੇਣੀ ਹੈ?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = ਕੀ %S ਨੂੰ ਆਪਣੇ MIDI ਡਿਵਾਈਸਾਂ ਤੱਕ ਪਹੁੰਚਣ ਅਤੇ SysEx ਸੁਨੇਹੇ ਭੇਜਣ/ਲੈਣ ਦੀ ਮਨਜ਼ੂਰੀ ਦੇਣੀ ਹੈ?
serial.allow.label = ਮਨਜ਼ੂਰ
serial.allow.accesskey = A
serial.block.label = ਪਾਬੰਦੀ
serial.block.accesskey = B
serial.shareWithFile = ਕੀ ਇਸ ਲੋਕਲ ਫਾਇਲ ਨੂੰ ਤੁਹਾਡੀਆਂ ਸੀਰੀਅਲ ਪੋਰਟਾਂ ਨੂੰ ਵਰਤਣ ਦੇਣਾ ਹੈ?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = ਕੀ %S ਨੂੰ ਤੁਹਾਡੀਆਂ ਸੀਰੀਅਲ ਪੋਰਟਾਂ ਨੂੰ ਵਰਤਣ ਦੇਣਾ ਹੈ?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = ਪਿੱਛੇ
storageAccess1.Allow.label = ਮਨਜ਼ੂਰ
storageAccess1.Allow.accesskey = A
storageAccess1.DontAllow.label = ਪਾਬੰਦੀ
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = %1$S ਨੂੰ %2$S ਉੱਤੇ ਆਪਣੇ ਕੂਕੀਜ਼ ਵਰਤਣ ਦੀ ਇਜਾਜ਼ਤ ਦੇਣੀ ਹੈ?
storageAccess1.hintText = ਜੇ ਤੁਹਾਨੂੰ ਸਪਸ਼ਟ ਨਹੀਂ ਕਿ %1$S ਨੂੰ ਇਹ ਡਾਟਾ ਕਿਉਂ ਚਾਹੀਦਾ ਹੈ ਤਾਂ ਤੁਸੀਂ ਪਾਬੰਦੀ ਲਾਉਣਾ ਚਾਹੋਗੇ।
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = “%S” ਲਈ ਵੈੱਬ ਨੂੰ ਖੋਜੋ
