#filter emptyLines

#define MOZ_LANGPACK_CREATOR Caio Tiago Oliveira

#define MOZ_LANGPACK_HOMEPAGE http://l10n.mozilla.org/pt-BR/seamonkeybr

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Carlos Une</em:contributor> <em:contributor>Leandro Mercês Xavier</em:contributor> 

#unfilter emptyLines
