# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = Interneti moɲoo woo goo ma bisandi doo taaga here. War ga baa ka bayhaya hantumantey sanba koyne doo taagaa here?
# Directory listing strings
DirTitle = %1$S maaboŋoo
DirGoUp = Zijandi fooloɲaa beeri here
ShowHidden = Haya tugantey cebe
DirColName = Maa
DirColSize = Adadu
DirColMTime = Barmay kokorantaa
DirFileLabel = Tuku:\u0020
UnsafeUriBlocked = Naarumi saajante na daliloo kaŋ goo “%1$S” ga gagayandi.
