# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Временско ограничење је истекло
openFile = Отвори датотеку
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Претражи „%2$S” у претраживачу %1$S
contextMenuSearch.accesskey = П
contextMenuPrivateSearch = Претражи у приватном прозору
contextMenuPrivateSearch.accesskey = р
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Претражи у претраживачу %S у приватном прозору
contextMenuPrivateSearchOtherEngine.accesskey = р
bookmarkAllTabsDefault = [Назив фасцикле]
unsignedAddonsDisabled.message = Један или више инсталираних додатака се не могу верификовати па су онемогућени.
unsignedAddonsDisabled.learnMore.label = Сазнајте више
unsignedAddonsDisabled.learnMore.accesskey = С
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Последњи приступ %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = %S:// везе
crashedpluginsMessage.title = Додатна компонента %S је отказала.
crashedpluginsMessage.reloadButton.label = Учитај поново
crashedpluginsMessage.reloadButton.accesskey = У
crashedpluginsMessage.submitButton.label = Пошаљи извештај о отказивању
crashedpluginsMessage.submitButton.accesskey = П
crashedpluginsMessage.learnMore = Сазнајте више…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Да ли сте хтели да одете на %S?
keywordURIFixup.goTo = Да, отвори %S
keywordURIFixup.goTo.accesskey = Д
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Ажурирај на %S
update.downloadAndInstallButton.accesskey = А
menuOpenAllInTabs.label = Отвори све у језичцима
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Освежи ову страницу
tabHistory.goBack = Назад на ову страницу
tabHistory.goForward = Иди напред до ове странице
# URL Bar
pasteAndGo.label = Налепи и иди
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Поново учитај тренутну страницу (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Заустави учитавање ове странице (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Врати оригиналну величину (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Укључи/искључи приказ читача (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, поништи ниво увећања
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Прикажи обележиваче (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Прикажи напредак тренутних преузимања (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Отвори нови прозор (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Отвори нов језичак (%S)
newTabContainer.tooltip = Отвори нови језичак (%S)\nПритисните и задржите да бисте отворили нови језичак у контејнеру
newTabAlwaysContainer.tooltip = Изаберите контејнер у ком желите да отворите нови језичак
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Дозволити да %S користи податке из HTML5 елемента canvas?
canvas.siteprompt2.warning = Може се користити за јединствену идентификацију рачунара.
canvas.block = Блокирај
canvas.block.accesskey = Б
canvas.allow2 = Дозволи
canvas.allow2.accesskey = Д
canvas.remember2 = Запамти ову одлуку
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Проверио %S
identity.identified.verified_by_you = За овај веб-сајт сте додали безбедносни изузетак.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Сертификат издан: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Није безбедно
identity.notSecure.tooltip = Веза није безбедна
identity.extension.label = Додатак (%S)
identity.extension.tooltip = Учитао додатак: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Умањи (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Врати оригиналну величину (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Увећај (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Исеци (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Копирај (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Налепи (%S)
geolocation.allow = Дозволи
geolocation.allow.accesskey = Д
geolocation.block = Блокирај
geolocation.block.accesskey = Б
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Ово ће отворити системска подешавања локације. Дајте овлашћење за локацију за %S.
geolocation.shareWithSite4 = Дозволити да %S приступа вашој локацији?
geolocation.shareWithFile4 = Дозволити да ова локална датотека приступа вашој локацији?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Дозволити %1$S да одобри %2$S приступ вашој локацији?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Дајте %S овлашћење за локацију у системским подешавањима.
geolocation.systemSettingsTitle = Чекање на овлашћење за локацију
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Систем ће од вас тражити да дате ово овлашћење за %S.
geolocation.remember = Запамти ову одлуку
# Virtual Reality Device UI
xr.allow2 = Дозволи
xr.allow2.accesskey = Д
xr.block = Блокирај
xr.block.accesskey = Б
xr.shareWithSite4 = Дозволити да %S приступа уређајима виртуелне реалности? Ово може изложити осетљиве информације.
xr.shareWithFile4 = Дозволити да ова локална датотека приступа уређајима виртуелне реалности? Ово може изложити осетљиве информације.
xr.remember = Запамти ову одлуку
# Persistent storage UI
persistentStorage.allow = Дозволи
persistentStorage.allow.accesskey = Д
persistentStorage.block.label = Блокирај
persistentStorage.block.accesskey = Б
persistentStorage.allowWithSite2 = Дозволити да %S складишти податке у трајну меморију?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Дозволи
webNotifications.allow2.accesskey = Д
webNotifications.notNow = Не сада
webNotifications.notNow.accesskey = Н
webNotifications.never = Блокирај
webNotifications.never.accesskey = ее
webNotifications.alwaysBlock = Увек блокирај
webNotifications.alwaysBlock.accesskey = У
webNotifications.block = Блокирај
webNotifications.block.accesskey = Б
webNotifications.receiveFromSite3 = Дозволити да %S шаље обавештења?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S жели да приступи другим апликацијама и услугама на овом уређају.
localhost.remember2 = Запамти мој избор за овај сајт
localhost.allowlabel = Дозволи
localhost.blocklabel = Блокирај
localhost.allow.accesskey = Д
localhost.block.accesskey = Б
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S жели да приступи апликацијама и услугама на уређајима повезаним на вашу локалну мрежу.
localNetwork.remember2 = Запамти мој избор за овај сајт
localNetwork.allowLabel = Дозволи
localNetwork.allow.accesskey = Д
localNetwork.blockLabel = Блокирај
localNetwork.block.accesskey = Б
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Води ме одавде!
safebrowsing.getMeOutOfHereButton.accessKey = В
safebrowsing.deceptiveSite = Обмањујући сајт!
safebrowsing.notADeceptiveSiteButton.label = Ово није обмањујућ сајт…
safebrowsing.notADeceptiveSiteButton.accessKey = о
safebrowsing.reportedAttackSite = Познати злонамеран сајт!
safebrowsing.notAnAttackButton.label = Ово није злонамеран сајт…
safebrowsing.notAnAttackButton.accessKey = О
safebrowsing.reportedUnwantedSite = Сајт можда садржи непожељан софтвер!
safebrowsing.reportedHarmfulSite = Сајт је потенцијално штетан!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Тражи %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Рестартовати %S у режиму за решавање проблема?
troubleshootModeRestartPromptMessage = Додаци, теме и прилагођена подешавања ће бити привремено онемогућени.
troubleshootModeRestartButton = Поново покрени
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Ова страница успорава %1$S. Зауставите је да бисте убрзали прегледач.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Нека страница успорава %1$S. Зауставите је да бисте убрзали прегледач.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = Страница „%1$S” успорава %2$S. Зауставите је да бисте убрзали прегледач.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = Страница „%1$S” успорава %2$S. Зауставите је да бисте убрзали прегледач.
processHang.add-on.learn-more.text = Сазнајте више
processHang.button_stop2.label = Заустави
processHang.button_stop2.accessKey = З
processHang.button_debug.label = Отклони грешке у скрипти
processHang.button_debug.accessKey = П
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Прикажи прозор у режиму целог екрана (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Помери бочни панел улево
sidebar.moveToRight = Помери бочни панел удесно
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = За репродукцију аудио или видео снимака на овој страници потребно је да омогућите DRM.
emeNotifications.drmContentDisabled.button.label = Омогући DRM
emeNotifications.drmContentDisabled.button.accesskey = ћ
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S инсталира компоненте које су потребне да би се пустио аудио или видео на овој страници. Покушајте поново касније.
emeNotifications.unknownDRMSoftware = Непознато
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Прилагођавање програма %S
decoder.noCodecs.button = Сазнајте како
decoder.noCodecs.accesskey = С
decoder.noCodecsLinux.message = Инсталирајте потребне кодеке да бисте пустили видео.
decoder.noHWAcceleration.message = Да побољшате видео квалитет, можда ћете морати да инсталирате пакет Microsoft’s Media Feature.
decoder.noPulseAudio.message = Да пуштате аудио, можда ћете морати да инсталирате захтевани PulseAudio софтвер.
decoder.unsupportedLibavcodec.message = libavcodec је можда рањив или није подржан и требао би да се ажурира ради пуштања видеа.
decoder.decodeError.message = Догодила се грешка приликом декодирања ресурса медије.
decoder.decodeError.button = Пријави проблем са сајтом
decoder.decodeError.accesskey = б
decoder.decodeWarning.message = Догодила се исправљива грешка приликом декодирања ресурса медије.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Морате да се пријавите на ову мрежу пре него што можете приступити интернету.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Отвори страницу за пријаву на мрежу
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Дозволе за %S
permissions.remove.tooltip = Поништи ову дозволу и питај поново
permissions.fullscreen.promptCanceled = Захтев за одобрење је отказан: захтеве за дозволе не треба издавати пре уласка у DOM приказ преко целог екрана.
permissions.fullscreen.fullScreenCanceled = Прекинут је DOM приказ преко целог екрана: захтеве за дозволе не треба подносити у режиму DOM приказа преко целог екрана.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bit
aboutDialog.architecture.thirtyTwoBit = 32-bit
midi.allow.label = Дозволи
midi.allow.accesskey = Д
midi.block.label = Блокирај
midi.block.accesskey = Б
midi.remember = Запамти ову одлуку
midi.shareWithFile = Дозволити овој локалној датотеци да приступа вашим MIDI уређајима?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Дозволити %S да приступа вашим MIDI уређајима?
midi.shareSysexWithFile = Дозволити овој локалној датотеци да приступа вашим MIDI уређајима и да шаље и прима SysEx поруке?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Дозволити %S да приступа вашим MIDI уређајима и да шаље и прима SysEx поруке?
serial.allow.label = Дозволи
serial.allow.accesskey = Д
serial.block.label = Блокирај
serial.block.accesskey = Б
serial.shareWithFile = Дозволити овој локалној датотеци приступ вашим серијским портовима?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Дозволити страници %S приступ вашим серијским портовима?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Назад
storageAccess1.Allow.label = Дозволи
storageAccess1.Allow.accesskey = Д
storageAccess1.DontAllow.label = Блокирај
storageAccess1.DontAllow.accesskey = Б
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Дозволити %1$S да користи своје колачиће на %2$S?
storageAccess1.hintText = Можете блокирати приступ ако није јасно зашто %1$S треба ове податке.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Претражи “%S” на вебу
