# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Czy zakwalifikować „%S” jako źródło godne zaufania w następujących przypadkach?
unnamedCA = Organ certyfikacji (bez nazwy)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Proszę wprowadzić hasło, użyte przy szyfrowaniu kopii bezpieczeństwa tego certyfikatu:
# Page Info
pageInfo_NoEncryption = Połączenie nie jest szyfrowane
pageInfo_Privacy_None1 = Pobierana strona WWW z witryny %S nie obsługuje szyfrowania danych.
pageInfo_Privacy_None2 = Informacje przesyłane przez sieć Internet bez uprzedniego szyfrowania mogą zostać odczytane przez inne osoby.
pageInfo_Privacy_None4 = Oglądana strona nie była zaszyfrowana podczas przesyłania przez Internet.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Połączenie szyfrowane (%1$S, %2$S-bitowe klucze, %3$S)
pageInfo_BrokenEncryption = Wadliwe szyfrowanie (%1$S, %2$S-bitowe klucze, %3$S)
pageInfo_Privacy_Encrypted1 = Wyświetlana strona została zaszyfrowana przed przesłaniem poprzez Internet.
pageInfo_Privacy_Encrypted2 = Szyfrowanie utrudnia osobom nieupoważnionym odczytanie informacji przesyłanych między komputerami. Dlatego jest mało prawdopodobne, aby ktokolwiek przeczytał tę stronę, gdy podróżowała przez sieć.
pageInfo_MixedContent = Połączenie częściowo szyfrowane
pageInfo_MixedContent2 = Niektóre części wyświetlanej strony nie zostały zaszyfrowane przed przesłaniem przez Internet.
pageInfo_WeakCipher = Połączenie z tą witryną nie jest w pełni bezpieczne, ponieważ zastosowane szyfrowanie nie jest wystarczające. Informacje na stronie mogą być dostępne dla innych, a jej działanie modyfikowane.
pageInfo_CertificateTransparency_Compliant = Ta witryna jest zgodna z zasadą przejrzystości certyfikatów.
# Token Manager
password_not_set = (nie ustawione)
