# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host } ಕ್ಕೆ ನೋಡಲಾಗುತ್ತಿದೆ...
network-connection-status-connected = { $host } ಕ್ಕೆ ಸಂಪರ್ಕಿಸಲಾಗಿದೆ...
network-connection-status-sending-request = { $host } ಕ್ಕೆ ಮನವಿ ಸಲ್ಲಿಸಲಾಗಿದೆ...
network-connection-status-transferring-data = { $host } ನಿಂದ ಮಾಹಿತಿಯನ್ನು ವರ್ಗಾಯಿಸಲಾಗುತ್ತಿದೆ...
network-connection-status-connecting = { $host } ಕ್ಕೆ ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ...
network-connection-status-read = { $host } ಅನ್ನು ಓದು
network-connection-status-wrote = { $host } ಕ್ಕೆ ಬರೆಯಲಾಯಿತು
network-connection-status-waiting = { $host } ಕ್ಕೆ ಕಾಯಲಾಗುತ್ತಿದೆ...
network-connection-status-looked-up = { $host } ಅನ್ನು ನೋಡಲಾಗಿದೆ…
