# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

title = درباره شبکه
warning = این بسیار آزمایشی است. بدون نظارت یک فرد بالغ استفاده نکنید.
show-next-time-checkbox = دفعهٔ بعدی هم این هشدار نمایش داده شود
ok = تأیید
http = HTTP
sockets = سوکت‌ها
dns = DNS
websockets = WebSockets
refresh = نوسازی
auto-refresh = نوسازی خودکار در هر ۳ ثانیه
hostname = نام میزبان
port = درگاه
http2 = HTTP/2
ssl = SSL
active = فعال
idle = بی‌کار
host = میزبان
tcp = TCP
sent = ارسال شده
received = دریافت شده
family = خانواده
trr = TRR
addresses = نشانی‌ها
expires = انقضا (ثانیه)
messages-sent = پیام‌های ارسال شده
messages-received = پیام‌های دریافت شده
bytes-sent = بایت‌های ارسال شده
bytes-received = بایت‌های دریافت شده
logging = وقایع
log-tutorial = برای اطلاع از نحوه استفاده از این ابزار به <a data-l10n-name="logging">وقایع HTTP</a> سر بزنید.
current-log-file = پرونده وقایع فعلی:
current-log-modules = ماژول‌های وقایع فعلی:
set-log-file = تنظیم پرونده وقایع
set-log-modules = تنظیم ماژول‌های وقایع
start-logging = شروع ثبت وقایع
stop-logging = توقف ثبت وقایع
dns-lookup = جست‌و‌جو DNS
dns-lookup-button = برطرف کردن
dns-domain = دامنه:
dns-lookup-table-column = IPs
rcwn = آمار RCWN
rcwn-status = وضعیت RCWN
rcwn-cache-won-count = تعداد برتری حافظه‌نهان
rcwn-net-won-count = تعداد برتری شبکه
total-network-requests = مجموع تعداد درخواست‌های شبکه
rcwn-operation = عملیات ذخیره‌ سازی موقت
rcwn-perf-open = باز کردن
rcwn-perf-read = خواندن
rcwn-perf-write = نوشتن
rcwn-perf-entry-open = ورودی باز
rcwn-avg-short = میانگین کوتاه
rcwn-avg-long = میانگین بلند
rcwn-std-dev-long = انحراف استاندارد بلند
rcwn-cache-slow = شمارش آرام ذخیره سازی موقت
rcwn-cache-not-slow = شماره سریع ذخیره سازی موقت
