# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Тражење: { $host }…
network-connection-status-connected = Повезан са: { $host }…
network-connection-status-sending-request = Слање захтева ка { $host }…
network-connection-status-tls-handshake = TLS руковање са { $host }…
network-connection-status-tls-handshake-finished = TLS руковање је завршено за { $host }…
