# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

MAINTENANCE_SERVICE_CHECKBOX_DESC = خزمەتگوزاری دامەزراندن و&چاودێری
SUMMARY_PAGE_SUBTITLE = ئامادەیت بۆ دامەزراندنی $BrandShortName
UN_SURVEY_CHECKBOX_LABEL = بە Mozilla بڵێ بۆ $BrandShortName سڕییەوە
# LOCALIZATION NOTE:
# The following text replaces the Install button text on the summary page.
UPGRADE_BUTTON = &بەرزکردنەوە
