# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-safebrowsing-term-1 = Abri les preferencies de l'aplicación
rights-safebrowsing-term-4 = Agora la navegación segura ta desactivada
rights-webservices-term-1 = { -vendor-short-name } y los sos collaboradores, llicenciatarios y socios trabayen p'apurrir los servicios más precisos y anovaos. Sicasí, nun podemos garantizar qu'esta información seya completa y tea llibre d'errores. Por exemplu, el serviciu de navegación segura pue que nun identifique dalgunos sitios peligrosos y pue qu'identifique dalgunos sitios seguros por error y les direiciones devueltes polos nuesos fornidores del serviciu de navegación basada na llocalización son namái estimaciones y nin nosotros nin los nuesos fornidores garantizamos la exactitú de les llocalizaciones proporcionaes.
rights-webservices-term-2 = { -vendor-short-name } pue dexar de suministrar, o camudar, los Servicios a discreción.
rights-webservices-term-3 = Pues usar estos servicios cola versión correspondiente de { -brand-short-name }, y { -vendor-short-name } date derechos pa facelo. { -vendor-short-name } y los sos llicenciatarios resérvense'l restu de derechos de los servicios. Estos términos nun llimiten dengún derechu dau poles llicencies de códigu abiertu aplicables a { -brand-short-name } y les versiones del códigu fonte correspondiente de { -brand-short-name }.
rights-webservices-term-4 = <strong>Los Servicios proporciónense "tal cual". { -vendor-short-name }, los sos contribuyentes, llicenciadores y distribuidores refuguen toa responsabilidá, explícita o implícita, incluyendo (ensin llimitación) la garantía de que los Servicios son comerciales y s'adauten a los tos envises particulares. Tú lleves la totalidá del riesgu al seleicionar los Servicios pa los tos envises y sobre la calidá y les prestaciones de los Servicios. Dalgunes xurisdicciones nun permiten la exclusión o llimitación de les garantíes implícites, polo que ye dable qu'esta renuncia de responsabilidá nun seya d'aplicación nel to casu.</strong>
rights-webservices-term-5 = <strong>Coles esceiciones espresaes pola llei, nin { -vendor-short-name }, nin los sos contribuyentes, llicenciadores y distribuidores fáense responsables de dengún dañu indireutu, especial, incidental, consecuente, punitivu o exemplar darréu de, o de dalguna forma rellacionao col usu de { -brand-short-name } y los Servicios. La responsabilidá colectiva sobre estos términos nun escederán de $500 (quinientos dólares). Dalgunes xurisdicciones nun permiten la exclusión o llimitación de ciertos daños, polo que pue qu'esta exclusión y llimitación nun seya d'aplicación nel to casu.</strong>
rights-webservices-term-7 = Estos términos tán regulaos poles lleis del Estáu de California, EE.UU., a esceición de les disposiciones llegales coles qu'entre en conflictu. Si dalguna parte d'estos términos se consideren non válidos o inaplicables, les partes restantes caltendrán tola so potencia y efeutos. el casu d'un conflictu ente una versión traducía d'estos términos y la versión en llingua inglesa, esta cabera, tendrá prioridá.
