# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Захаваныя лагіны
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-username-cmd =
    .label = Капіраваць імя карыстальніка
    .accesskey = К
edit-username-cmd =
    .label = Рэдагаваць імя карыстальніка
    .accesskey = д
copy-password-cmd =
    .label = Скапіяваць пароль
    .accesskey = к
edit-password-cmd =
    .label = Рэдагаваць пароль
    .accesskey = Р
search-filter =
    .accesskey = П
    .placeholder = Пошук
column-heading-site =
    .label = Сайт
column-heading-username =
    .label = Імя карыстальніка
column-heading-password =
    .label = Пароль
column-heading-time-created =
    .label = Першае выкарыстанне
column-heading-time-last-used =
    .label = Апошняе выкарыстанне
column-heading-time-password-changed =
    .label = Апошняя змена
column-heading-times-used =
    .label = Колькасць выкарыстанняў
remove =
    .label = Выдаліць
    .accesskey = д
import =
    .label = Імпарт…
    .accesskey = І
show-passwords =
    .label = Паказаць паролі
    .accesskey = п
hide-passwords =
    .label = Схаваць паролі
    .accesskey = п
logins-description-filtered = Наступныя лагіны адпавядаюць вашаму пошуку:
remove-all =
    .label = Выдаліць усе
    .accesskey = В
remove-all-shown =
    .label = Выдаліць усе паказаныя
    .accesskey = В
remove-all-passwords-prompt = Вы ўпэўнены, што хочаце выдаліць усе паролі?
remove-all-passwords-title = Выдаленне усіх пароляў
no-master-password-prompt = Вы сапраўды хочаце паказаць вашы паролі?
