# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Tempo scaduto
openFile = Apri file
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Cerca “%2$S” con %1$S
contextMenuSearch.accesskey = r
contextMenuPrivateSearch = Cerca in una finestra anonima
contextMenuPrivateSearch.accesskey = n
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Cerca con %S in una finestra anonima
contextMenuPrivateSearchOtherEngine.accesskey = n
bookmarkAllTabsDefault = [Nome cartella]
unsignedAddonsDisabled.message = Alcuni dei componenti aggiuntivi installati sono stati disattivati in quanto non è stato possibile verificarli.
unsignedAddonsDisabled.learnMore.label = Ulteriori informazioni
unsignedAddonsDisabled.learnMore.accesskey = U
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Ultimo accesso: %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = Link %S://
crashedpluginsMessage.title = Si è verificato un arresto anomalo del plugin %S.
crashedpluginsMessage.reloadButton.label = Ricarica la pagina
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = Invia segnalazione dell’arresto anomalo
crashedpluginsMessage.submitButton.accesskey = n
crashedpluginsMessage.learnMore = Ulteriori informazioni…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Forse volevi aprire %S?
keywordURIFixup.goTo = Sì, apri %S
keywordURIFixup.goTo.accesskey = S
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Aggiorna a %S
update.downloadAndInstallButton.accesskey = A
menuOpenAllInTabs.label = Apri tutti in schede
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Ricarica questa pagina
tabHistory.goBack = Torna indietro fino a questa pagina
tabHistory.goForward = Vai avanti fino a questa pagina
# URL Bar
pasteAndGo.label = Incolla e vai
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Ricarica la pagina corrente (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Interrompi il caricamento della pagina (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Reimposta il livello di zoom (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Attiva/disattiva Modalità lettura (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, reimposta il livello di zoom predefinito
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Visualizza i segnalibri (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Mostra l’avanzamento dei download in corso (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Apri una nuova finestra (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Apri una nuova scheda (%S)
newTabContainer.tooltip = Apri una nuova scheda (%S)\nTieni premuto per aprire una nuova scheda contenitore
newTabAlwaysContainer.tooltip = Scegli un contenitore per aprire una nuova scheda
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Consentire a %S di accedere ai dati delle immagini HTML5 canvas?
canvas.siteprompt2.warning = Queste informazioni potrebbero essere utilizzate per identificare il computer in modo univoco.
canvas.block = Blocca
canvas.block.accesskey = B
canvas.allow2 = Consenti
canvas.allow2.accesskey = C
canvas.remember2 = Ricorda questa scelta
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Verificata da: %S
identity.identified.verified_by_you = È stata aggiunta un’eccezione di sicurezza per questo sito.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Certificato rilasciato a: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Non sicuro
identity.notSecure.tooltip = La connessione non è sicura
identity.extension.label = Estensione (%S)
identity.extension.tooltip = Caricata da un’estensione: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Riduci zoom (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Reimposta il livello di zoom (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Aumenta zoom (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Taglia (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Copia (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Incolla (%S)
geolocation.allow = Consenti
geolocation.allow.accesskey = C
geolocation.block = Blocca
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Verranno aperte le impostazioni di sistema relative alla posizione. Garantire a %S il permesso di accedere alla posizione.
geolocation.shareWithSite4 = Consentire a %S di accedere alla posizione corrente?
geolocation.shareWithFile4 = Consentire a questo file di accedere alla posizione corrente?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Consentire a %1$S di garantire a %2$S il permesso di accedere alla posizione corrente?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Garantire a %S il permesso di accedere alla posizione nelle impostazioni di sistema.
geolocation.systemSettingsTitle = In attesa del permesso di accedere alla posizione
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Il sistema chiederà di garantire questo permesso a %S.
geolocation.remember = Ricorda questa scelta
# Virtual Reality Device UI
xr.allow2 = Consenti
xr.allow2.accesskey = C
xr.block = Blocca
xr.block.accesskey = B
xr.shareWithSite4 = Consentire a %S di accedere ai dispositivi per realtà virtuale? Questo potrebbe esporre informazioni riservate.
xr.shareWithFile4 = Consentire a questo file di accedere ai dispositivi per realtà virtuale? Questo potrebbe esporre informazioni riservate.
xr.remember = Ricorda questa scelta
# Persistent storage UI
persistentStorage.allow = Consenti
persistentStorage.allow.accesskey = C
persistentStorage.block.label = Blocca
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Consentire a %S di salvare dati nell’archivio permanente?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Consenti
webNotifications.allow2.accesskey = C
webNotifications.notNow = Non adesso
webNotifications.notNow.accesskey = N
webNotifications.never = Mai
webNotifications.never.accesskey = M
webNotifications.alwaysBlock = Blocca sempre
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = Blocca
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Consentire a %S di inviare notifiche?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S vuole accedere ad altre app e servizi su questo dispositivo.
localhost.remember2 = Ricorda la mia scelta per questo sito
localhost.allowlabel = Consenti
localhost.blocklabel = Blocca
localhost.allow.accesskey = C
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S vuole accedere ad app e servizi sui dispositivi connessi alla rete locale.
localNetwork.remember2 = Ricorda la mia scelta per questo sito
localNetwork.allowLabel = Consenti
localNetwork.allow.accesskey = C
localNetwork.blockLabel = Blocca
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Allontanarsi da questo sito
safebrowsing.getMeOutOfHereButton.accessKey = A
safebrowsing.deceptiveSite = Sito ingannevole
safebrowsing.notADeceptiveSiteButton.label = Non è un sito ingannevole…
safebrowsing.notADeceptiveSiteButton.accessKey = N
safebrowsing.reportedAttackSite = Segnalato sito malevolo
safebrowsing.notAnAttackButton.label = Non è un sito malevolo…
safebrowsing.notAnAttackButton.accessKey = N
safebrowsing.reportedUnwantedSite = Segnalato sito contenente software indesiderato
safebrowsing.reportedHarmfulSite = Segnalato sito dannoso
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Cerca %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Riavviare %S in Modalità risoluzione problemi?
troubleshootModeRestartPromptMessage = Estensioni, temi e impostazioni personalizzate verranno temporaneamente disattivate.
troubleshootModeRestartButton = Riavvia
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Questa pagina sta rallentando %1$S. Si consiglia di bloccarla per velocizzare il browser.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Il funzionamento di %1$S è rallentato da una pagina web. Si consiglia di bloccarla per velocizzare il browser.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = “%1$S” sta rallentando %2$S. Si consiglia di bloccare la pagina per velocizzare il browser.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = “%1$S” sta rallentando %2$S. Si consiglia di bloccare l’estensione per velocizzare il browser.
processHang.add-on.learn-more.text = Ulteriori informazioni
processHang.button_stop2.label = Blocca
processHang.button_stop2.accessKey = B
processHang.button_debug.label = Esegui il debug dello script
processHang.button_debug.accessKey = E
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Visualizza la finestra a schermo intero (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Sposta barra laterale a sinistra
sidebar.moveToRight = Sposta barra laterale a destra
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = È necessario attivare il DRM per riprodurre i contenuti video o audio presenti in questa pagina.
emeNotifications.drmContentDisabled.button.label = Attiva DRM
emeNotifications.drmContentDisabled.button.accesskey = A
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = Installazione in corso dei componenti necessari per riprodurre i contenuti audio o video presenti in questa pagina. Riprovare più tardi.%0.S
emeNotifications.unknownDRMSoftware = Sconosciuto
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Personalizza %S
decoder.noCodecs.button = Scopri come
decoder.noCodecs.accesskey = S
decoder.noCodecsLinux.message = Per riprodurre il video potrebbe essere necessario installare i codec richiesti.
decoder.noHWAcceleration.message = Per migliorare la qualità del video potrebbe essere necessario installare Media Feature Pack di Microsoft.
decoder.noPulseAudio.message = Per riprodurre l’audio potrebbe essere necessario installare il software PulseAudio.
decoder.unsupportedLibavcodec.message = La libreria libavcodec potrebbe essere vulnerabile o non supportata. Per riprodurre i video è necessario aggiornarla.
decoder.decodeError.message = Si è verificato un errore durante la decodifica di una risorsa multimediale.
decoder.decodeError.button = Segnala il problema con questo sito
decoder.decodeError.accesskey = S
decoder.decodeWarning.message = Si è verificato un errore reversibile durante la decodifica di una risorsa multimediale.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = È necessario accedere alla rete per navigare in Internet.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Apri la pagina di accesso alla rete
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Permessi per %S
permissions.remove.tooltip = Reimposta questo permesso e chiedi nuovamente
permissions.fullscreen.promptCanceled = Richiesta di permessi annullata: non è possibile effettuare una richiesta di permessi prima di passare a schermo intero (DOM),
permissions.fullscreen.fullScreenCanceled = Modalità schermo interno (DOM) terminata: non è possibile effettuare una richiesta di permessi in modalità schermo intero.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64 bit
aboutDialog.architecture.thirtyTwoBit = 32 bit
midi.allow.label = Consenti
midi.allow.accesskey = C
midi.block.label = Blocca
midi.block.accesskey = B
midi.remember = Ricorda questa scelta
midi.shareWithFile = Consentire a questo file l’accesso ai dispositivi MIDI?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Consentire a %S l’accesso ai dispositivi MIDI?
midi.shareSysexWithFile = Consentire a questo file l’accesso ai dispositivi MIDI e l’invio/ricezione di messaggi SysEx?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Consentire a %S l’accesso ai dispositivi MIDI e l’invio/ricezione di messaggi SysEx?
serial.allow.label = Consenti
serial.allow.accesskey = C
serial.block.label = Blocca
serial.block.accesskey = B
serial.shareWithFile = Consentire a questo file l’accesso alle porte seriali?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Consentire a %S l’accesso alle porte seriali?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Indietro
storageAccess1.Allow.label = Consenti
storageAccess1.Allow.accesskey = C
storageAccess1.DontAllow.label = Blocca
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Consentire a %1$S di utilizzare i propri cookie su %2$S?
storageAccess1.hintText = È consigliabile bloccare l’accesso se non è chiaro per quale motivo %S abbia bisogno di questi dati.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Cerca “%S” in Internet
