# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title Legosignoj
#define bookmarks_heading Legosignoj

#define bookmarks_toolbarfolder Dosierujo de la ilaro de legosignoj
#define bookmarks_toolbarfolder_description Aldonu legosignojn al tiu ĉi dosierujo por vidi ilin montritaj en la ilaro de legosignoj

# LOCALIZATION NOTE (getting_started):
# link title for http://en-US.www.mozilla.com/en-US/firefox/central/
#define getting_started Unuaj paŝoj

# LOCALIZATION NOTE (firefox_heading):
# Firefox links folder name
#define firefox_heading Mozilla Firefox

# LOCALIZATION NOTE (firefox_help):
# link title for http://en-US.www.mozilla.com/en-US/firefox/help/
#define firefox_help Helpo kaj gvidado

# LOCALIZATION NOTE (firefox_customize):
# link title for http://en-US.www.mozilla.com/en-US/firefox/customize/
#define firefox_customize Agordi Firefox

# LOCALIZATION NOTE (firefox_community):
# link title for http://en-US.www.mozilla.com/en-US/firefox/community/
#define firefox_community Partopreni

# LOCALIZATION NOTE (firefox_about):
# link title for http://en-US.www.mozilla.com/en-US/about/
#define firefox_about Pri ni

# LOCALIZATION NOTE (firefox_feedback):
# link title for browser feedback page
# currently used by Metro only: https://input.mozilla.org/feedback/metrofirefox
#define firefox_feedback Komentarii

#unfilter emptyLines
