# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

appmenu-update-available2 =
    .buttonlabel = Sader
    .buttonaccesskey = S
    .label = Yella lqem
    .secondarybuttonlabel = Kkes
    .secondarybuttonaccesskey = k
appmenu-update-available-message2 = Sader lqem aneggaru n { -brand-shorter-name }.
appmenu-update-manual2 =
    .buttonlabel = Sader
    .buttonaccesskey = S
    .label = Yella lqem
    .secondarybuttonlabel = Kkes
    .secondarybuttonaccesskey = k
appmenu-update-manual-message2 = { -brand-shorter-name } yegguma ad yettuleqqem s wudem awurman. Sader lqem amaynut — ur ak·am-tettuṛuḥu ara telɣut yettwaskelsen neɣ agganen.
appmenu-update-unsupported2 =
    .buttonlabel = Issin ugar
    .buttonaccesskey = I
    .label = Aleqqem d-awezɣi
    .secondarybuttonlabel = Kkes
    .secondarybuttonaccesskey = k
appmenu-update-unsupported-message2 = Anagraw-ik·im n wamud ur yemṣada ara akked lqem aneggaru n { -brand-shorter-name }.
appmenu-update-restart2 =
    .buttonlabel = Leqqem syen ales asenker
    .buttonaccesskey = L
    .label = Yella lqem
    .secondarybuttonlabel = Kkes
    .secondarybuttonaccesskey = k
appmenu-update-restart-message2 = Awi lqem aneggaru n { -brand-shorter-name }. Ldi accaren, isfuyla ad d-uɣalen.
appmenu-theme-installed =
    .secondarybuttonlabel = Sefsex
    .secondarybuttonaccesskey = S
appmenu-update-other-instance =
    .buttonlabel = Akken yebɣu yili leqqem { -brand-shorter-name }
    .buttonaccesskey = U
    .label = { -brand-shorter-name } ur izmir ara ad ileqqem s wudem awurman ɣer lqem aneggaru.
    .secondarybuttonlabel = Mačči tura
    .secondarybuttonaccesskey = N
appmenu-update-other-instance-message = Yella lqem amaynut n { -brand-shorter-name }, maca ur yezmir ara ad yettusebded acku yella nɣel-nniḍen n { -brand-shorter-name } la iteddu. Mdel-it i wakken ad tkemmleḍ lqem, neɣ fren ɣas akken leqqem (nɣel-nni-nniḍen yezmer ur iteddu ara akken iwata alamma tulseḍ-as asenker).
appmenu-addon-post-install-message3 = Sefrek izegrar d yisental inek·inem deg wumuɣ n usnas.
appmenu-addon-post-install-pin-toolbarbutton-checkbox =
    .label = Senteḍ asiɣzef ɣer ufeggag n yifecka
    .accesskey = S
appmenu-new-tab-controlled-changes =
    .buttonlabel = Eǧǧ isenfal
    .buttonaccesskey = K
    .label = Iccer-inek·inem amaynut yettusenfel.
    .secondarybuttonlabel = Sefrek accaren imaynuten
    .secondarybuttonaccesskey = M
appmenu-homepage-controlled-changes =
    .buttonlabel = Eǧǧ isenfal
    .buttonaccesskey = K
    .label = Asebter-inek·inem agejdayettusenfel.
    .secondarybuttonlabel = Sefrek asebter agejdan
    .secondarybuttonaccesskey = M
appmenu-tab-hide-controlled =
    .buttonlabel = Eǧǧ iccaren fren
    .buttonaccesskey = K
    .label = Kcem γer iccaren-inek ifren
    .secondarybuttonlabel = Sens aseɣzif
    .secondarybuttonaccesskey = D
