# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Amarag n ukter
import-from-bookmarks = Kter ticṛaḍ n isebtar seg:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = x
import-from-360se =
    .label = 360 Iminig aɣelsan
    .accesskey = 3
import-source =
    .label = Aktar n iɣewwaṛen d isefka
import-migrating-title =
    .label = Aktar…
import-migrating-description = Iferdisen-a la d-ttwaktaren akka tura…
import-select-profile-title =
    .label = Fren amaɣnu
import-select-profile-description = Imaɣnuten-a heggan iwakken ad ttwaketren seg:
import-done-title =
    .label = Aktar immed
import-done-description = Iferdisen-a ttwaketren akken iwata:
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = Sɣur { $source }
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Iminig aɣelsan
imported-safari-reading-list = Tabdart n tɣuṛi (seg Safari)
imported-edge-reading-list = Tabdart n tɣuṛi (seg Safari)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Iɣewwaṛen Intenet
    .value = Iɣewwaṛen Intenet
browser-data-edge-1 =
    .label = Iɣewwaṛen
    .value = Iɣewwaṛen
browser-data-safari-1 =
    .label = Ismenyifen
    .value = Ismenyifen
browser-data-chrome-1 =
    .label = Ismenyifen
    .value = Ismenyifen
browser-data-canary-1 =
    .label = Ismenyifen
    .value = Ismenyifen
browser-data-360se-1 =
    .label = Ismenyifen
    .value = Ismenyifen
browser-data-ie-2 =
    .label = Inagan n tuqqna
    .value = Inagan n tuqqna
browser-data-edge-2 =
    .label = Inagan n tuqqna
    .value = Inagan n tuqqna
browser-data-safari-2 =
    .label = Inagan n tuqqna
    .value = Inagan n tuqqna
browser-data-chrome-2 =
    .label = Inagan n tuqqna
    .value = Inagan n tuqqna
browser-data-canary-2 =
    .label = Inagan n tuqqna
    .value = Inagan n tuqqna
browser-data-firefox-2 =
    .label = Inagan n tuqqna
    .value = Inagan n tuqqna
browser-data-360se-2 =
    .label = Inagan n tuqqna
    .value = Inagan n tuqqna
browser-data-ie-8 =
    .label = Yettwakles seg umazray
    .value = Yettwakles seg umazray
browser-data-edge-8 =
    .label = Amzaray n tferkit yettwakelsen
    .value = Amzaray n tferkit yettwakelsen
browser-data-safari-8 =
    .label = Isefka n tferkit ttwakelsen
    .value = Isefka n tferkit ttwakelsen
browser-data-chrome-8 =
    .label = Amzaray n tferkit yettwakelsen
    .value = Amzaray n tferkit yettwakelsen
browser-data-canary-8 =
    .label = Amzaray n tferkit yettwakelsen
    .value = Amzaray n tferkit yettwakelsen
browser-data-firefox-8 =
    .label = Amzaray n tferkit yettwakelsen
    .value = Amzaray n tferkit yettwakelsen
browser-data-360se-8 =
    .label = Amzaray n tferkit yettwakelsen
    .value = Amzaray n tferkit yettwakelsen
browser-data-ie-16 =
    .label = Awalen uffiren yettwakelsen
    .value = Awalen uffiren yettwakelsen
browser-data-edge-16 =
    .label = Awalen uffiren yettwakelsen
    .value = Awalen uffiren yettwakelsen
browser-data-safari-16 =
    .label = Awalen uffiren yettwakelsen
    .value = Awalen uffiren yettwakelsen
browser-data-chrome-16 =
    .label = Awalen uffiren yettwakelsen
    .value = Awalen uffiren yettwakelsen
browser-data-canary-16 =
    .label = Awalen uffiren yettwakelsen
    .value = Awalen uffiren yettwakelsen
browser-data-firefox-16 =
    .label = Awalen uffiren yettwakelsen
    .value = Awalen uffiren yettwakelsen
browser-data-360se-16 =
    .label = Awalen uffiren yettwakelsen
    .value = Awalen uffiren yettwakelsen
browser-data-ie-32 =
    .label = Ismenyifen
    .value = Ismenyifen
browser-data-edge-32 =
    .label = Ismenyifen
    .value = Ismenyifen
browser-data-safari-32 =
    .label = Isɣalen
    .value = Isɣalen
browser-data-chrome-32 =
    .label = Isɣalen
    .value = Isɣalen
browser-data-canary-32 =
    .label = Isɣalen
    .value = Isɣalen
browser-data-360se-32 =
    .label = Isɣalen
    .value = Isɣalen
