# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Konservi
dialogTitleAddBookmark = Nova legosigno
dialogTitleAddMulti = Novaj legosignoj
dialogTitleEdit = Atributoj de "%S"
dialogTitleAddNewBookmark2 = Aldoni legosignon
dialogTitleEditBookmark = Modifi “%S”
dialogTitleEditBookmark2 = Modifi legosignon
dialogTitleAddBookmarkFolder = Aldoni legosignan dosierujon
dialogTitleEditBookmarkFolder = Modifi legosignan dosierujon
bookmarkAllTabsDefault = [nomo de dosierujo]
newFolderDefault = Nova dosierujo
newBookmarkDefault = Nova legosigno
