# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SaveImageTitle = Alzar a imachen
SaveMediaTitle = Alzar lo fichero multimedia
SaveVideoTitle = Alzar o vídeo
SaveAudioTitle = Alzar l'audio
SaveLinkTitle = Alzar como
WebPageCompleteFilter = Pachina web, completa
WebPageHTMLOnlyFilter = Pachina web, nomás HTML
WebPageXHTMLOnlyFilter = Pachina web, nomás XHTML
WebPageSVGOnlyFilter = Pachina web, nomás SVG
WebPageXMLOnlyFilter = Pachina web, nomás XML
