#filter emptyLines
# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title Отметки


#define bookmarks_heading Отметки


#define bookmarks_toolbarfolder Папка на лентата с отметки


#define bookmarks_toolbarfolder_description Добавянето на отметки към тази папка ще ги показва в лентата с отметки


# LOCALIZATION NOTE (getting_started):

# link title for http://en-US.www.mozilla.com/en-US/firefox/central/

#define getting_started Начални насоки на Firefox


# LOCALIZATION NOTE (firefox_heading):

# Firefox links folder name

#define firefox_heading Mozilla Firefox


# LOCALIZATION NOTE (firefox_help):

# link title for http://en-US.www.mozilla.com/en-US/firefox/help/

#define firefox_help Помощ и въведения


# LOCALIZATION NOTE (firefox_customize):

# link title for http://en-US.www.mozilla.com/en-US/firefox/customize/

#define firefox_customize Персонализиране на Firefox


# LOCALIZATION NOTE (firefox_community):

# link title for http://en-US.www.mozilla.com/en-US/firefox/community/

#define firefox_community Участвайте


# LOCALIZATION NOTE (firefox_about):

# link title for http://en-US.www.mozilla.com/en-US/about/

#define firefox_about За нас


#unfilter emptyLines