# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Ti boles fidare de “%S” pro custos iscopos?
unnamedCA = Autoridade de tzertificatzione (chena nòmine)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Inserta sa crae chi est istada impreada pro tzifrare sa còpia de seguresa de custu tzertificadu:
# Token Manager
password_not_set = (non definida)
