# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Искате ли „%S“ да е доверен за следните цели?
unnamedCA = Сертификатен удостоверител (неименуван CA)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Моля, въведете паролата, с която е шифровано това резервно копие:
# Page Info
pageInfo_NoEncryption = Връзката не е шифрована
pageInfo_Privacy_None1 = Сайтът %S не поддържа шифроване за страницата, която разглеждате.
pageInfo_Privacy_None2 = Информацията, изпратена през Интернет без шифроване, може да бъде видяна от други хора, докато се пренася.\u0020
pageInfo_Privacy_None4 = Тази страница не е шифрована преди да бъде изпратена през Интернет.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Шифрована връзка (%1$S, %2$S-битови ключове, %3$S)
pageInfo_BrokenEncryption = Развалено шифроване (%1$S, %2$S-битови ключове, %3$S)
pageInfo_Privacy_Encrypted1 = Тази страница е била шифрована преди да бъде изпратена през Интернет.
pageInfo_Privacy_Encrypted2 = Шифроването затруднява неоторизирани лица да преглеждат пренасяната между компютрите информация. Затова е много малко вероятно някой да е прочел тази страница, докато е пренасяна през Интернет.
pageInfo_MixedContent = Връзката е частично шифрована
pageInfo_MixedContent2 = Части от тази страница не са били шифровани преди да бъдат изпратени през Интернет.
pageInfo_WeakCipher = Връзката тази страница използва слабо шифроване и не е поверителна. Други хора могат да виждат вашата информация и да променят поведението на страницата.
pageInfo_CertificateTransparency_Compliant = Сайтът се придържа към политиката за прозрачност на сертификати.
# Token Manager
password_not_set = (не е зададена)
