# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Importiešonys vednis
import-from =
    { PLATFORM() ->
        [windows] Importeit īstatiejumus, gruomotzeimes, viesturi, paroles i cytus datus nu:
       *[other] Importeit īstatiejumus, gruomotzeimes, viesturi, paroles i cytus datus nu:
    }
import-from-bookmarks = Importeit gruomotzeimes nu:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-nothing =
    .label = Naimporteit nikū
    .accesskey = N
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = x
import-from-360se =
    .label = 360 Drūss puorlūks
    .accesskey = 3
no-migration-sources = Nav atrosta nivīna programa, nu kurys importeit gruomotzeimes, viesturi voi paroļu informaceju.
import-source =
    .label = Importeit īstatiejumus i datus
import-items-title =
    .label = Importiejamī elementi
import-items-description = Izavielit importiejamūs elementus:
import-migrating-title =
    .label = Nūteik importeišona...
import-migrating-description = Tīk importeiti izavālātī elementi...
import-select-profile-title =
    .label = Izavielit profilu
import-select-profile-description = Datus var importeit nu itim profilym:
import-done-title =
    .label = Importeišona ir pabeigta
import-done-description = Tyka sekmeigi importeiti:
import-close-source-browser = Lyudzu puorsalīcinojit ka izavālātais puorlūks ir aiztaiseits pyrms turpynuot.
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = Nu { $source }
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Drūss puorlūks
imported-safari-reading-list = Skaitamū lītu saroksts (Nu Safari)
imported-edge-reading-list = Skaitamū lītu saroksts (Nu Edge)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Šķārsteikla īstatiejumi
    .value = Šķārsteikla īstatiejumi
browser-data-edge-1 =
    .label = Īstatiejumi
    .value = Īstatiejumi
browser-data-safari-1 =
    .label = Īstatiejumi
    .value = Īstatiejumi
browser-data-chrome-1 =
    .label = Īstatiejumi
    .value = Īstatiejumi
browser-data-canary-1 =
    .label = Īstatiejumi
    .value = Īstatiejumi
browser-data-360se-1 =
    .label = Īstatiejumi
    .value = Īstatiejumi
browser-data-ie-2 =
    .label = Seikdatnes
    .value = Seikdatnes
browser-data-edge-2 =
    .label = Seikdatnes
    .value = Seikdatnes
browser-data-safari-2 =
    .label = Seikdatnes
    .value = Seikdatnes
browser-data-chrome-2 =
    .label = Seikdatnes
    .value = Seikdatnes
browser-data-canary-2 =
    .label = Seikdatnes
    .value = Seikdatnes
browser-data-firefox-2 =
    .label = Seikdatnes
    .value = Seikdatnes
browser-data-360se-2 =
    .label = Seikdatnes
    .value = Seikdatnes
browser-data-ie-4 =
    .label = Puorlūkuošonys viesture
    .value = Puorlūkuošonys viesture
browser-data-edge-4 =
    .label = Puorlūkuošonys viesture
    .value = Puorlūkuošonys viesture
browser-data-safari-4 =
    .label = Puorlūkuošonys viesture
    .value = Puorlūkuošonys viesture
browser-data-chrome-4 =
    .label = Puorlūkuošonys viesture
    .value = Puorlūkuošonys viesture
browser-data-canary-4 =
    .label = Puorlūkuošonys viesture
    .value = Puorlūkuošonys viesture
browser-data-firefox-history-and-bookmarks-4 =
    .label = Puorlūkuošonys viesture i gruomotzeimes
    .value = Puorlūkuošonys viesture i gruomotzeimes
browser-data-360se-4 =
    .label = Puorlūkuošonys viesture
    .value = Puorlūkuošonys viesture
browser-data-ie-8 =
    .label = Saglobuotā formu viesture
    .value = Saglobuotā formu viesture
browser-data-edge-8 =
    .label = Saglobuotā formu viesture
    .value = Saglobuotā formu viesture
browser-data-safari-8 =
    .label = Saglobuotā formu viesture
    .value = Saglobuotā formu viesture
browser-data-chrome-8 =
    .label = Saglobuotā formu viesture
    .value = Saglobuotā formu viesture
browser-data-canary-8 =
    .label = Saglobuotā formu viesture
    .value = Saglobuotā formu viesture
browser-data-firefox-8 =
    .label = Saglobuotā formu viesture
    .value = Saglobuotā formu viesture
browser-data-360se-8 =
    .label = Saglobuotā formu viesture
    .value = Saglobuotā formu viesture
browser-data-ie-16 =
    .label = Saglobuotuos paroles
    .value = Saglobuotuos paroles
browser-data-edge-16 =
    .label = Saglobuotuos paroles
    .value = Saglobuotuos paroles
browser-data-safari-16 =
    .label = Saglobuotuos paroles
    .value = Saglobuotuos paroles
browser-data-chrome-16 =
    .label = Saglobuotuos paroles
    .value = Saglobuotuos paroles
browser-data-canary-16 =
    .label = Saglobuotuos paroles
    .value = Saglobuotuos paroles
browser-data-firefox-16 =
    .label = Saglobuotuos paroles
    .value = Saglobuotuos paroles
browser-data-360se-16 =
    .label = Saglobuotuos paroles
    .value = Saglobuotuos paroles
browser-data-ie-32 =
    .label = Izlases
    .value = Izlases
browser-data-edge-32 =
    .label = Izlases
    .value = Izlases
browser-data-safari-32 =
    .label = Gruomotzeimes
    .value = Gruomotzeimes
browser-data-chrome-32 =
    .label = Gruomotzeimes
    .value = Gruomotzeimes
browser-data-canary-32 =
    .label = Gruomotzeimes
    .value = Gruomotzeimes
browser-data-360se-32 =
    .label = Gruomotzeimes
    .value = Gruomotzeimes
browser-data-ie-64 =
    .label = Cyti dati
    .value = Cyti dati
browser-data-edge-64 =
    .label = Cyti dati
    .value = Cyti dati
browser-data-safari-64 =
    .label = Cyti dati
    .value = Cyti dati
browser-data-chrome-64 =
    .label = Cyti dati
    .value = Cyti dati
browser-data-canary-64 =
    .label = Cyti dati
    .value = Cyti dati
browser-data-firefox-other-64 =
    .label = Cyti dati
    .value = Cyti dati
browser-data-360se-64 =
    .label = Cyti dati
    .value = Cyti dati
browser-data-firefox-128 =
    .label = Lūgus i cilnes
    .value = Lūgus i cilnes
