# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Finder værtsnavn { $host }…
network-connection-status-connected = Tilsluttet { $host }…
network-connection-status-sending-request = Sender forespørgsel til { $host }…
network-connection-status-transferring-data = Overfører data fra { $host }…
network-connection-status-connecting = Tilslutter til { $host }…
network-connection-status-read = Læste { $host }
network-connection-status-wrote = Skrev { $host }
network-connection-status-waiting = Venter på { $host }…
network-connection-status-looked-up = Slog { $host } op…
network-connection-status-tls-handshake = Udfører TLS-håndtryk med { $host }…
network-connection-status-tls-handshake-finished = Afsluttet TLS-håndtryk med { $host }…
