# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Vil du stola på «%S» for følgjande føremål?
unnamedCA = Sertifikatutskrivar (utan namn)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Skriv inn passordet som vart brukt til å kryptera denne sertifikat-tryggingskopien:
# Page Info
pageInfo_NoEncryption = Tilkoplinga er ikkje kryptert
pageInfo_Privacy_None1 = Nettstaden %S stør ikkje kryptering for nettsida du ser på.
pageInfo_Privacy_None2 = Informasjon som vert sendt over internett utan kryptering kan verta lesen av andre under overføringa.
pageInfo_Privacy_None4 = Sida du ser på vart ikkje kryptert før ho vart overført over Internett.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Tilkopling kryptert (%1$S, %2$S bitnyklar, %3$S)
pageInfo_BrokenEncryption = Øydelagd kryptering (%1$S, %2$S bit nyklar, %3$S)
pageInfo_Privacy_Encrypted1 = Sida du ser på vart kryptert før ho vart overført over Internett.
pageInfo_Privacy_Encrypted2 = Kryptering gjer det vanskeleg for uautoriserte personar å sjå informasjonen som vert overførd mellom datamaskiner. Det er derfor usannsynleg at nokon las nettsida medan ho vart overførd over nettverket.
pageInfo_MixedContent = Sambandet er delvis kryptert
pageInfo_MixedContent2 = Delar av sida du viser vart ikkje krypteret før ho vart overført over Internett.
pageInfo_WeakCipher = Tilkoplinga til denne nettstaden brukar svak kryptering og er ikkje privat. Andre personar kan sjå informasjonen, eller endra oppførselen til nettstaden.
pageInfo_CertificateTransparency_Compliant = Denne nettstaden følgjer sertifikatpraksisen om innsyn.
# Token Manager
password_not_set = (ikkje valt)
