#filter emptyLines
2 
3 # LOCALIZATION NOTE: The 'oc ' strings in the URLs will be replaced with
4 # your locale code, and link to your translated pages as soon as they're 
5 # live.
6 
7 #define bookmarks_title Marcapaginas
8 #define bookmarks_heading Marcapaginas
9 
10 # LOCALIZATION NOTE (bookmarks_addons):
11 # link title for https://en-US.add-ons.mozilla.com/oc /firefox/bookmarks/
12 #define bookmarks_addons Telecargar de moduls complementaris
13 
14 #define bookmarks_toolbarfolder Bookmarks Toolbar Folder
15 #define bookmarks_toolbarfolder_description Apondre de marcapaginas dins aqueste repertòri per los veire dins vòstra barra personala
16 
17 # LOCALIZATION NOTE (getting_started):
18 # link title for http://en-US.www.mozilla.com/oc /firefox/central/
19 #define getting_started Primièrs passes
20 
21 # LOCALIZATION NOTE (latest_headlines):
22 # link title for the live bookmarks sample, a redirect on
23 # http://en-US.fxfeeds.mozilla.com/oc /firefox/headlines.xml
24 # Changing the redirect is subject to approval of l10n-drivers.
25 #define latest_headlines Darrièras novèlas
26 
27 # LOCALIZATION NOTE (firefox_heading):
28 # Firefox links folder name
29 #define firefox_heading Mozilla Firefox
30 
31 # LOCALIZATION NOTE (firefox_help):
32 # link title for http://en-US.www.mozilla.com/oc /firefox/help/
33 #define firefox_help Ajuda e didacticials
34 
35 # LOCALIZATION NOTE (firefox_customize):
36 # link title for http://en-US.www.mozilla.com/oc /firefox/customize/
37 #define firefox_customize Personalizar Firefox
38 
39 # LOCALIZATION NOTE (firefox_community):
40 # link title for http://en-US.www.mozilla.com/oc /firefox/community/
41 #define firefox_community Contribuir
42 
43 # LOCALIZATION NOTE (firefox_about):
44 # link title for http://en-US.www.mozilla.com/oc /firefox/about/
45 #define firefox_about A prepaus de nosautres
46 
47 #unfilter emptyLines

