# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Запазване
dialogTitleAddBookmark = Нова отметка
dialogTitleAddMulti = Нови отметки
dialogTitleEdit = Свойства на „%S“
dialogTitleAddNewBookmark2 = Добавяне на отметка
dialogTitleEditBookmark = Редактиране на “%S”
dialogTitleEditBookmark2 = Редактиране на отметка
dialogTitleAddBookmarkFolder = Добавяне на папка с отметки
dialogTitleEditBookmarkFolder = Редактиране на папката с отметки
bookmarkAllTabsDefault = [Име на папка]
newFolderDefault = Нова папка
newBookmarkDefault = Нова отметка
