# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = کھولو
    .accesskey = O
places-open-in-tab =
    .label = نویں ٹیب وِچ کھولو
    .accesskey = w
places-open-in-container-tab =
    .label = نویں کنٹینر ٹیب وِچ کھولو
    .accesskey = i
places-open-all-bookmarks =
    .label = سبھ نشانیاں کھولو
    .accesskey = O
places-open-all-in-tabs =
    .label = سبھ ٹیباں وِچ کھولو
    .accesskey = O
places-open-in-window =
    .label = نویں ونڈو وِچ کھولو
    .accesskey = N
places-open-in-private-window =
    .label = نویں نجی ونڈو وِچ کھولو
    .accesskey = P
places-add-bookmark =
    .label = نشانی شامل کرو …
    .accesskey = B
places-add-folder-contextmenu =
    .label = فولڈر شامل کرو …
    .accesskey = F
places-add-folder =
    .label = فولڈر شامل کرو …
    .accesskey = o
places-add-separator =
    .label = انڄ کرݨ والا شامل کرو
    .accesskey = S
places-view =
    .label = ݙیکھو
    .accesskey = w
places-by-date =
    .label = حسبِ تاریخ
    .accesskey = D
places-by-site =
    .label = حسبِ سائٹ
    .accesskey = S
places-by-most-visited =
    .label = برائے زیادہ ملاحظہ کیتے ڳئے
    .accesskey = م
places-by-last-visited =
    .label = حسب چھیکڑی وار ملاحظہ کردہ
    .accesskey = L
places-by-day-and-site =
    .label = حسب تاریخ تے سائٹ
    .accesskey = t
places-history-search =
    .placeholder = تاریخ ڳولو
places-history =
    .aria-label = تاریخ
places-bookmarks-search =
    .placeholder = نشانیاں ڳولو
places-delete-domain-data =
    .label = ایں سائٹ بارے بھل ونڄو
    .accesskey = F
places-sortby-name =
    .label = بمطابق ناں چھانٹی کرو
    .accesskey = r
# places-edit-bookmark and places-edit-generic will show one or the other and can have the same access key.
places-edit-bookmark =
    .label = نشانی تدوین کرو …
    .accesskey = E
places-edit-generic =
    .label = تدوین کرو …
    .accesskey = E
places-edit-folder2 =
    .label = فولڈر دی تدوین کرو…
    .accesskey = E
places-delete-folder =
    .label =
        { $count ->
            [1] فولڈر مٹاؤ
           *[other] فولڈرز مٹاؤ
        }
    .accesskey = D
# Managed bookmarks are created by an administrator and cannot be changed by the user.
managed-bookmarks =
    .label = نشانیاں منظم کرو
# This label is used when a managed bookmarks folder doesn't have a name.
managed-bookmarks-subfolder =
    .label = ذیلی فولڈر
# This label is used for the "Other Bookmarks" folder that appears in the bookmarks toolbar.
other-bookmarks-folder =
    .label = ٻیاں نشانیاں
places-show-in-folder =
    .label = فولڈر وِچ ݙکھاؤ
    .accesskey = F
# Variables:
# $count (number) - The number of elements being selected for removal.
places-delete-bookmark =
    .label =
        { $count ->
            [1] نشانی مٹاؤ
           *[other] نشانیاں مٹاؤ
        }
    .accesskey = D
places-untag-bookmark =
    .label = ٹیگ ہٹاؤ
    .accesskey = R
places-manage-bookmarks =
    .label = نشانیاں منظم کرو
    .accesskey = M
places-forget-about-this-site-confirmation-title = ایں سائٹ بارے بھل ونڄو
places-forget-about-this-site-forget = بھل ونڄو
places-library3 =
    .title = لائبریری
places-organize-button =
    .label = منظم کرو
    .tooltiptext = اپݨیاں نشانیاں منظم کرو
    .accesskey = O
places-organize-button-mac =
    .label = منظم کرو
    .tooltiptext = اپݨیاں نشانیاں منظم کرو
places-file-close =
    .label = بند کرو
    .accesskey = C
places-cmd-close =
    .key = w
places-view-button =
    .label = نظارے
    .tooltiptext = اپݨا نظارہ تبدیل کرو
    .accesskey = V
places-view-button-mac =
    .label = نظارے
    .tooltiptext = اپݨے نظارے تبدیل کرو
places-view-menu-columns =
    .label = کالم ݙکھاؤ
    .accesskey = C
places-view-menu-sort =
    .label = چھانٹی کرو
    .accesskey = S
places-view-sort-unsorted =
    .label = اݨ چھانٹیا
    .accesskey = U
places-view-sort-ascending =
    .label = A > Z چھانٹی کرو
    .accesskey = A
places-view-sort-descending =
    .label = Z > A چھانٹی کرو
    .accesskey = Z
places-maintenance-button =
    .label = درآمد تے بیک اپ
    .tooltiptext = اپݨیاں نشانیاں بیک اپ تے درآمد کرو
    .accesskey = I
places-maintenance-button-mac =
    .label = درآمد تے بیک اپ
    .tooltiptext = اپݨیاں نشانیاں بیک آپ تے درآمد کرو
places-cmd-backup =
    .label = بیک اپ …
    .accesskey = B
places-cmd-restore =
    .label = بحال کرو
    .accesskey = R
places-cmd-restore-from-file =
    .label = فائل منتخب کرو …
    .accesskey = C
places-import-bookmarks-from-html =
    .label = HTML کنوں نشانیاں درآمد کرو ...
    .accesskey = I
places-export-bookmarks-to-html =
    .label = نشانیاں HTML وِچ برآمد کرو ...
    .accesskey = E
places-import-other-browser =
    .label = کہیں ٻئے براؤزر کنوں کوائف درآمد کرو …
    .accesskey = A
places-view-sort-col-name =
    .label = ناں
places-view-sort-col-tags =
    .label = ٹیگز
places-view-sort-col-url =
    .label = مقام
places-view-sort-col-most-recent-visit =
    .label = سب توں حالیہ دورہ
places-view-sort-col-visit-count =
    .label = ملاحظہ شماری
places-view-sort-col-date-added =
    .label = اضافہ شدہ
places-view-sort-col-last-modified =
    .label = چھیکڑی واری تبدیل تھیا
places-cmd-find-key =
    .key = f
places-back-button =
    .tooltiptext = واپس ون٘ڄو
places-forward-button =
    .tooltiptext = اڳو تے ودھو
places-details-pane-select-an-item-description = ہک آئٹم کوں ایندی خصوصیات کوں ݙیکھݨ تے ایندے وِچ ترمیم کرݨ کیتے منتخب کرو۔
