# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

#define Welcome_Title $ProductName$ सेटअप

#define Welcome_MessageWelcome %s मा स्वागत छ!

#define Welcome_Message0 तपाईँ %s २ अल्फा १ स्थापना गर्दै हुनुहुन्छ ।

#define Welcome_Message1 तपाईँलाई यो सेटअप कार्यक्रम चलाउनु अघि सबै विन्डोज कार्यक्रमहरू अन्त्य गर्न जोडदार सिफारिस गरिन्छ ।

#define Welcome_Message2 सेटअप अन्त्य गर्न 'रद्द गर्नुहोस्' बटन क्लिक गर्नुहोस् र त्यसपछि तपाईँले चलाउनुभएको कुनै कार्यक्रम बन्द गर्नुहोस् । सेटअप कार्यक्रम जारी राख्न 'पछिल्लो' बटन क्लिक गर्नुहोस् ।

#define Welcome_Message3 %s २ अल्फा १ लाई निरन्तर रूपमा स्थापना जारी राख्न 'पछिल्लो' बटन क्लिक गर्नुहोस् ।

#define License_Title सफ्टवेयर इजाजतपत्र सम्झौता

#define License_SubTitle यो सफ्टवेयर प्रयोग गर्नका लागि सर्त र अवस्था ।

#define License_Message0 कृपया निम्न इजाजतपत्र सम्झौता पढ्नुहोस् । यो सम्झौताको बाँकी भाग हेर्न स्क्रोलपट्टी प्रयोग गर्नुहोस् ।

#define License_Accept म इजाजतपत्र सम्झौताको सर्तहरू स्वीकार गर्छु

#define License_Decline म इजाजतपत्र सम्झौताको सर्तहरू स्वीकार गर्दिन

#define Type_Title सेटअप प्रकार

#define Type_SubTitle सेटअप विकल्प रोज्नुहोस् ।

#define Type_Message0 तपाईँले रूचाउनु भएको सेटअपको प्रकार रोज्नुहोस्, र 'पछिल्लो' बटन क्लिक गर्नुहोस् ।

#define Standard_Short मानक

#define Standard_Long थन्डरबर्ड धेरै साझा विकल्पहरूसँग स्थापना गरिनेछ ।

#define Custom_Short अनुकूल

#define Custom_Long तपाईँले स्थापना गर्नका लागि व्यक्तिगत विकल्पहरू पनि रोज्न सक्नुहुन्छ । अनुभवी प्रयोगकर्ताका लागि सिफारिस गरिएको छ ।

#define Select_Title अवयव चयन गर्नुहोस्

#define Select_SubTitle अतिरिक्त अवयव जसले $ProductName$ विस्तार गर्दछ ।

#define Select_Message0 तपाईँले स्थापना गर्न चाहनुभएको अतिरिक्त अवयवहरू रोज्नुहोस्, त्यसपछि 'पछिल्लो' बटन क्लिक गर्नुहोस् ।

#define Path_Title फोल्डर स्थापना गर्नुहोस्

#define Path_SubTitle $ProductName$ कहाँ स्थापना गरिनेछ ।

#define Path_Message0 $ProductName$ निम्न फोल्डरमा स्थापना गरिनेछ :

#define Integration_Title सेटअप सर्टकट

#define Integration_SubTitle कार्यक्रम प्रतिमाहरू सिर्जना गर्दछ

#define Integration_Message0 $ProductShortName$ का लागि प्रतिमा सिर्जना गर्दछ:

#define Integration_Desktop मेरो डेस्कटपमा

#define Integration_StartMenu मेरो सुरुआत मेनु कार्यक्रम फोल्डरमा

#define Integration_QuickLaunch मेरो द्रुत थालनीपट्टीमा

#define SelectFolder_Title $ProductName$ सेटअप - कार्यक्रम फोल्डर चयन गर्नुहोस्

#define SelectFolder_Message0 सेटअपले तल सूचीकृत कार्यक्रम फोल्डरमा कार्यक्रम प्रतिमाहरू थप्नेछ । तपाईँले नयाँ फोल्डर नाम टाइप गर्न सक्नुहुन्छ, वा अवस्थित फोल्डर सूचीबाट एउटा चयन गर्न सक्नुहुन्छ । जारी राख्न 'पछिल्लो ' बटन क्लिक गर्नुहोस् ।

#define Advanced_Title $ProductName$ सेटअप - उन्नत सेटिङ

#define Advanced_Message0 यदि तपाईँको इन्टरनेट जडानलाई प्रोक्सी सर्भरको आवश्यक पर्दछ भने, तपाईँको सर्भर नाम र पोर्ट जानकारी प्रविष्ट गर्नुहोस् । यदि तपाईँको इन्टरनेट जडानलाई प्रोक्सी सर्भरको आवश्यक्ता पर्दैन भने, फाँट खाली छोड्नुहोस् ।

#define Install_Title सारांश

#define Install_SubTitle $ProductName$ को स्थापना सुरु गर्न तयार हुनुहोस् ।

#define Install_MessageInstall सेटअपले अहिले निम्न अवयवहरू स्थापना गर्नेछ:

#define Install_MessageDownload सेटअपले अहिले डाउनलोड गर्नेछ र निम्न अवयवहरू स्थापना गर्नेछ:

#define Install_Message0 जारी राख्न 'पछिल्लो' बटन क्लिक गर्नुहोस् ।

#define Downloading_Title डाउनलोड गर्दैछ

#define Downloading_SubTitle आवश्यक अवयव डाउनलोड गर्दैछ...

#define Downloading_Blurb सेटअपले $ProductName$ स्थापना गर्न आवश्यक फाइल डाउनलोड गर्दैछ ।

#define Downloading_FileName हालै डाउनलोड भइहेको:

#define Downloading_Time बाँकी समय:

#define Installing_Title स्थापना गर्दै

#define Installing_SubTitle $ProductName$ स्थापना गर्दैछ...

#define Installing_Blurb सेटअपले अनुप्रयोग फाइलहरू स्थापना गर्दैछ ।

#define Installing_Status फाइल तयार गर्दै:

#define Installing_Component हालै स्थापना भइरहेको:

#define Success_Title पूरै स्थापना गर्नुहोस्

#define Success_Header पूरै स्थापना गर्नुहोस्

#define Success_Message0 %s सफलतापूर्वक स्थापना भयो ।

#define Success_Message1 सेटअप पूरा गर्न 'समाप्त' बटन क्लिक गर्नुहोस् ।

#define Success_Launch %s अहिले थालनी गर्नुहोस् ।

#define Check_Message $ProductName$ को डाउनलोड सफल भयो । $ProductNameInternal$ स्थापनासँग प्रक्रिया गर्न बन्द गरिनुपर्छ । $ProductNameInternal$ लाई स्वचालित रूपमा अन्त्य गर्न र स्थापना सुरु गर्न 'ठीक छ' बटन क्लिक गर्नुहोस् ।

#define Check_FullMessage स्थापनासँग प्रक्रिया गर्न $ProductNameInternal$ बन्द गरिनुपर्छ । $ProductNameInternal$ लाई स्वचालित रूपमा अन्त्य गर्न र स्थापना सुरु गर्न 'ठीक छ' बटन क्लिक गर्नुहोस् ।

#define Check_Wait $ProductNameInternal$ बन्द गर्दैछ ।  कृपया प्रतिक्षा गर्नुहोस्...

#define Component_XPCOM क्रस प्लेटफर्म सीओएम

#define Component_Mail $ProductName$

#define Component_Offline अफलाइन समर्थन

#define Component_Offline_Long $ProductName$ पत्रमा अफलाइन समर्थन थप्दछ ।

#define Component_RSS आरएसएस समर्थन

#define Component_RSS_Long $ProductName$ मा आरएसएस समर्थन थप्दछ ।

#define Component_QFA गुणस्तर पृष्ठपोषण अभिकर्ता

#define Component_QFA_Long $ProductName$ क्रस सूचना प्रतिवेदन गर्नका लागि
