# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Vrijeme isteklo
openFile = Otvori fajl
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Pretraži %1$S za "%2$S"
contextMenuSearch.accesskey = S
contextMenuPrivateSearch = Traži u privatnom prozoru
contextMenuPrivateSearch.accesskey = h
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Traži sa %S u Privatnom Prozoru
contextMenuPrivateSearchOtherEngine.accesskey = h
bookmarkAllTabsDefault = [Naziv direktorija]
unsignedAddonsDisabled.message = Jedan ili više instaliranih add-ona ne mogu biti provjereni i stoga su onemogućeni.
unsignedAddonsDisabled.learnMore.label = Saznajte više
unsignedAddonsDisabled.learnMore.accesskey = S
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Zadnji pristup %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = %S:// linkovi
crashedpluginsMessage.title = %S plugin se srušio.
crashedpluginsMessage.reloadButton.label = Ponovo učitaj stranicu
crashedpluginsMessage.reloadButton.accesskey = P
crashedpluginsMessage.submitButton.label = Pošalji izvještaj o rušenju
crashedpluginsMessage.submitButton.accesskey = š
crashedpluginsMessage.learnMore = Saznajte više…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Da li ste mislili otići na %S?
keywordURIFixup.goTo = Da, odvedi me na %S
keywordURIFixup.goTo.accesskey = D
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Nadogradi na %S
update.downloadAndInstallButton.accesskey = g
menuOpenAllInTabs.label = Otvori sve u tabovima
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Ponovo učitaj ovu stranicu
tabHistory.goBack = Vrati se na ovu stranicu
tabHistory.goForward = Idi naprijed na ovu stranicu
# URL Bar
pasteAndGo.label = Zalijepi & otvori
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Ponovo učitaj trenutnu stranicu (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Zaustavi učitavanje ove stranice (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Poništi stepen uvećanja (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Uključi/isključi prikaz čitača (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, resetuj nivo uvećanja
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Prikažite vaše zabilješke (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Prikaži napredak aktivnih preuzimanja (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Otvori novi prozor (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Otvori novi tab (%S)
newTabContainer.tooltip = Otvorite novi tab (%S)\nPritisnite i držite da biste otvorili novi kontejnerski tab
newTabAlwaysContainer.tooltip = Odaberite kontejner za otvaranje novog taba
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Dozvoliti %S da koristi vaše HTML5 podatke o slici platna?
canvas.siteprompt2.warning = Ovo se može koristiti za jedinstvenu identifikaciju vašeg računara.
canvas.block = Blokiraj
canvas.block.accesskey = B
canvas.allow2 = Dozvoli
canvas.allow2.accesskey = A
canvas.remember2 = Zapamti ovu odluku
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Verifikovao: %S
identity.identified.verified_by_you = Dodali ste sigurnosni izuzetak za ovaj site
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Certifikat izdat za: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Nije sigurno
identity.notSecure.tooltip = Veza nije sigurna
identity.extension.label = Ekstenzije (%S)
identity.extension.tooltip = Učitano od ekstenzije: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Umanji (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Poništi stepen uvećanja (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Uvećaj (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Isjeci (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Kopiraj (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Zalijepi (%S)
geolocation.allow = Dozvoli
geolocation.allow.accesskey = A
geolocation.block = Blokiraj
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Ovo će otvoriti postavke lokacije sistema. Molimo vas da odobrite lokaciju za %S.
geolocation.shareWithSite4 = Dozvoliti %S pristup vašoj lokaciji?
geolocation.shareWithFile4 = Dozvoliti ovoj lokalnoj datoteci pristup vašoj lokaciji?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Dopustiti %1$S da dopusti %2$S pristup vašoj lokaciji?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Dozvoli %S za lokaciju u postavkama sistema.
geolocation.systemSettingsTitle = Čekanje dozvole za lokaciju
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Sistem će vas zamoliti da odobrite ovu dozvolu za %S.
geolocation.remember = Zapamti ovu odluku
# Virtual Reality Device UI
xr.allow2 = Dozvoli
xr.allow2.accesskey = A
xr.block = Blokiraj
xr.block.accesskey = B
xr.shareWithSite4 = Dozvoliti %S pristup uređajima za virtuelnu stvarnost? Ovo može otkriti osjetljive informacije.
xr.shareWithFile4 = Dozvoliti ovoj lokalnoj datoteci pristup uređajima virtuelne stvarnosti? Ovo može otkriti osjetljive informacije.
xr.remember = Zapamti ovu odluku
# Persistent storage UI
persistentStorage.allow = Dozvoli
persistentStorage.allow.accesskey = o
persistentStorage.block.label = Blokiraj
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Dozvoli da %S čuva informacije u trajnom skladištu?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Dozvoli
webNotifications.allow2.accesskey = A
webNotifications.notNow = Ne sada
webNotifications.notNow.accesskey = n
webNotifications.never = Nikada ne dopusti
webNotifications.never.accesskey = k
webNotifications.alwaysBlock = Uvijek blokiraj
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = Blokiraj
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Dozvoliti %Su da šalje obavještenja?
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Vodi me odavdje!
safebrowsing.getMeOutOfHereButton.accessKey = G
safebrowsing.deceptiveSite = Obmanjujuća stranica!
safebrowsing.notADeceptiveSiteButton.label = Ovo nije obmanjujuća stranica…
safebrowsing.notADeceptiveSiteButton.accessKey = o
safebrowsing.reportedAttackSite = Prijavljena napadačka stranica!
safebrowsing.notAnAttackButton.label = Ovo nije napadačka stranica…
safebrowsing.notAnAttackButton.accessKey = a
safebrowsing.reportedUnwantedSite = Prijavljena stranica sa neželjenim softverom!
safebrowsing.reportedHarmfulSite = Prijavljena opasna stranica!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Traži %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Ponovo pokrenuti %S u načinu rada za rješavanje problema?
troubleshootModeRestartPromptMessage = Vaše ekstenzije, teme i prilagođene postavke bit će privremeno onemogućene.
troubleshootModeRestartButton = Restartuj
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Ova stranica usporava %1$S. Da biste ubrzali preglednik, zaustavite ovu stranicu.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Web stranica usporava %1$S. Da biste ubrzali preglednik, zaustavite tu stranicu.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = “%1$S” usporava %2$S. Da biste ubrzali preglednik, zaustavite tu stranicu.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = “%1$S” usporava %2$S. Da biste ubrzali preglednik, zaustavite tu ekstenziju.
processHang.add-on.learn-more.text = Saznajte više
processHang.button_stop2.label = Zaustavi
processHang.button_stop2.accessKey = S
processHang.button_debug.label = Debagiraj skriptu
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Prikaži prozor preko cijelog ekrana (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Pomjeri bočnu taku lijevo
sidebar.moveToRight = Pomjeri bočnu traku desno
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Morate omogućiti DRM za reprodukciju audio ili video sadržaja na ovoj stranici.
emeNotifications.drmContentDisabled.button.label = Omogući DRM
emeNotifications.drmContentDisabled.button.accesskey = O
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S instalira komponente potrebne za reproduciranje audio ili video sadržaja na ovoj stranici. Molimo pokušajte ponovo kasnije.
emeNotifications.unknownDRMSoftware = Nepoznato
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Prilagodi %S
decoder.noCodecs.button = Saznajte kako
decoder.noCodecs.accesskey = z
decoder.noCodecsLinux.message = Da biste reproducirali video, morat ćete instalirati zahtijevane video kodeke.
decoder.noHWAcceleration.message = Da biste poboljšali kvalitet videa, morat ćete instalirati Microsoft Media Feature Pack.
decoder.noPulseAudio.message = Da biste reproducirali audio, morat ćete instalirati zahtijevani PulseAudio softver.
decoder.unsupportedLibavcodec.message = libavcodec je možda ranjiv ili nije podržan, i treba ga nadograditi da bi reproducirao video.
decoder.decodeError.message = Došlo je do greške prilikom dekodiranja medijskog resursa.
decoder.decodeError.button = Prijavite problem sa stranicom
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = Došlo je do ispravljive greške prilikom dekodiranja medijskog resursa.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Morate biti prijavljeni na ovu mrežu da biste mogli pristupiti internetu.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Otvori stranicu za prijavu na mrežu
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Dozvole za %S
permissions.remove.tooltip = Poništi ovu dozvolu i pitaj ponovo
permissions.fullscreen.promptCanceled = Otkazani zahtjevi za dozvole na čekanju: zahtjevi za dozvole ne bi trebali biti izdani prije ulaska u DOM cijeli ekran.
permissions.fullscreen.fullScreenCanceled = Izašli ste iz DOM cijelog ekrana: zahtjevi za dozvole ne bi trebali biti izdavani dok ste u DOM cijelom ekranu.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bitni
aboutDialog.architecture.thirtyTwoBit = 32-bitni
midi.allow.label = Dozvoli
midi.allow.accesskey = A
midi.block.label = Blokiraj
midi.block.accesskey = B
midi.remember = Zapamti ovu odluku
midi.shareWithFile = Dozvoliti ovoj lokalnoj datoteci pristup vašim MIDI uređajima?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Dozvoliti %S pristup vašim MIDI uređajima?
midi.shareSysexWithFile = Dozvoliti ovoj lokalnoj datoteci pristup vašim MIDI uređajima i slanje/primanje SysEx poruka?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Dozvoliti %S pristup vašim MIDI uređajima i slanje/primanje SysEx poruka?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Nazad
storageAccess1.Allow.label = Dozvoli
storageAccess1.Allow.accesskey = A
storageAccess1.DontAllow.label = Blokiraj
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Dozvoliti %1$S da koristi svoje kolačiće na %2$S?
storageAccess1.hintText = Možda biste željeli blokirati pristup ako nije jasno zašto %1$S treba ove podatke.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Pretražite web za “%S”
