# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host } tapıştırıla…
network-connection-status-connected = { $host } sunucısına bağlanıldı…
network-connection-status-sending-request = { $host } sunucısına istem yiberile…
network-connection-status-transferring-data = { $host } qonumından veriler keçirile…
network-connection-status-connecting = { $host } sunucısına bağlanıla…
network-connection-status-read = { $host } oquldı
network-connection-status-wrote = { $host } yazıldı
network-connection-status-waiting = { $host } beklene…
network-connection-status-looked-up = { $host } tapıştırıldı…
network-connection-status-tls-handshake = { $host } ile bir TLS toqalaşması icra etile…
network-connection-status-tls-handshake-finished = { $host } içün TLS toqalaşması tamam…
