# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = 已超时
openFile = 打开文件
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = 用 %1$S 搜索“%2$S”
contextMenuSearch.accesskey = S
contextMenuPrivateSearch = 在隐私窗口中搜索
contextMenuPrivateSearch.accesskey = h
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = 在隐私窗口中用 %S 搜索
contextMenuPrivateSearchOtherEngine.accesskey = h
bookmarkAllTabsDefault = [文件夹名称]
unsignedAddonsDisabled.message = 某些已安装的附加组件未通过验证，现已被禁用。
unsignedAddonsDisabled.learnMore.label = 详细了解
unsignedAddonsDisabled.learnMore.accesskey = L
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = 上次访问于 %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = %S:// 链接
crashedpluginsMessage.title = 插件 %S 已崩溃。
crashedpluginsMessage.reloadButton.label = 重新加载页面
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = 提交崩溃报告
crashedpluginsMessage.submitButton.accesskey = S
crashedpluginsMessage.learnMore = 详细了解…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = 您是要访问 %S 吗？
keywordURIFixup.goTo = 是，带我前往 %S
keywordURIFixup.goTo.accesskey = Y
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = 更新到 %S
update.downloadAndInstallButton.accesskey = U
menuOpenAllInTabs.label = 全部打开
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = 刷新此页面
tabHistory.goBack = 后退至此页面
tabHistory.goForward = 前进至此页面
# URL Bar
pasteAndGo.label = 粘贴并前往
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = 刷新当前页面 (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = 停止加载此页面 (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = 重置缩放级别 (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = 切换阅读器视图 (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%，重置缩放级别
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = 显示您的书签 (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = 显示下载进度 (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = 打开新窗口 (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = 打开新标签页 (%S)
newTabContainer.tooltip = 打开新标签页 (%S)\n长按可新建身份标签页
newTabAlwaysContainer.tooltip = 选择新建标签页时所用身份
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = 要允许 %S 使用您的 HTML5 canvas 图像数据吗？
canvas.siteprompt2.warning = 这可用于唯一标识您的计算机。
canvas.block = 阻止
canvas.block.accesskey = B
canvas.allow2 = 允许
canvas.allow2.accesskey = A
canvas.remember2 = 记住此决定
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = 验证者：%S
identity.identified.verified_by_you = 您已将此网站加入安全例外。
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = 证书颁发给：%S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = 不安全
identity.notSecure.tooltip = 连接不安全
identity.extension.label = 扩展 (%S)
identity.extension.tooltip = 由扩展加载：%S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = 缩小 (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = 重置缩放级别 (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = 放大 (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = 剪切 (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = 复制 (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = 粘贴 (%S)
geolocation.allow = 允许
geolocation.allow.accesskey = A
geolocation.block = 阻止
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = 此操作将打开系统位置设置，请向 %S 授予位置权限。
geolocation.shareWithSite4 = 要允许 %S 获取您的位置吗？
geolocation.shareWithFile4 = 要允许此本地文件获取您的位置吗？
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = 要允许 %1$S 授权 %2$S 获取您的位置吗？
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = 在系统设置中向 %S 授予位置权限。
geolocation.systemSettingsTitle = 正在等待获得位置权限
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = 系统将询问是否向 %S 授予此权限。
geolocation.remember = 记住此决定
# Virtual Reality Device UI
xr.allow2 = 允许
xr.allow2.accesskey = A
xr.block = 阻止
xr.block.accesskey = B
xr.shareWithSite4 = 要允许 %S 访问 VR 设备吗？这可能会泄露敏感信息。
xr.shareWithFile4 = 要允许本地文件访问 VR 设备吗？这可能会泄露敏感信息。
xr.remember = 记住此决定
# Persistent storage UI
persistentStorage.allow = 允许
persistentStorage.allow.accesskey = A
persistentStorage.block.label = 阻止
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = 要允许 %S 在持久存储中存储数据吗？
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = 允许
webNotifications.allow2.accesskey = A
webNotifications.notNow = 暂时不要
webNotifications.notNow.accesskey = n
webNotifications.never = 永不允许
webNotifications.never.accesskey = v
webNotifications.alwaysBlock = 一律阻止
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = 阻止
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = 要允许 %S 发送通知吗？
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S 想要访问此设备上的其他应用和服务。
localhost.remember2 = 记住对此网站的选择
localhost.allowlabel = 允许
localhost.blocklabel = 阻止
localhost.allow.accesskey = A
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S 想要访问本地网络中的设备上的应用和服务。
localNetwork.remember2 = 记住对此网站的选择
localNetwork.allowLabel = 允许
localNetwork.allow.accesskey = A
localNetwork.blockLabel = 阻止
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = 带我离开！
safebrowsing.getMeOutOfHereButton.accessKey = G
safebrowsing.deceptiveSite = 诈骗网站！
safebrowsing.notADeceptiveSiteButton.label = 这不是诈骗网站…
safebrowsing.notADeceptiveSiteButton.accessKey = D
safebrowsing.reportedAttackSite = 此页面据举报有攻击行为！
safebrowsing.notAnAttackButton.label = 这不是一个有害网站…
safebrowsing.notAnAttackButton.accessKey = a
safebrowsing.reportedUnwantedSite = 此网站被举报提供流氓软件！
safebrowsing.reportedHarmfulSite = 举报恶意网站！
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = 用 %S 搜索
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = 要以排障模式重启 %S 吗？
troubleshootModeRestartPromptMessage = 您的扩展、主题和自定义设置将被暂时禁用。
troubleshootModeRestartButton = 重启
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = 此网页拖慢了您的 %1$S。可停止此页面，恢复浏览速度。
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = 有一网页拖慢了您的 %1$S。可停止该页面，恢复浏览速度。
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = “%1$S”拖慢了您的 %2$S。可停止该页面，恢复浏览速度。
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = “%1$S”拖慢了您的 %2$S。可停止该扩展，恢复浏览速度。
processHang.add-on.learn-more.text = 详细了解
processHang.button_stop2.label = 停止
processHang.button_stop2.accessKey = S
processHang.button_debug.label = 调试脚本
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = 全屏显示此窗口 (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = 移动侧栏到左侧
sidebar.moveToRight = 移动侧栏到右侧
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = 您必须启用 DRM 才能播放此页面上的某些音频或视频。
emeNotifications.drmContentDisabled.button.label = 启用数字版权管理（DRM）
emeNotifications.drmContentDisabled.button.accesskey = E
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S 正在安装组件，以便播放此页面上的音频或视频。请稍后再试。
emeNotifications.unknownDRMSoftware = 未知
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = 定制 %S
decoder.noCodecs.button = 了解如何运行
decoder.noCodecs.accesskey = L
decoder.noCodecsLinux.message = 为了播放视频，您可能需要安装所需的视频编解码器。
decoder.noHWAcceleration.message = 为了改善视频质量，您可能需要安装 Microsoft 的“媒体功能包”（Media Feature Pack）。
decoder.noPulseAudio.message = 要播放音频，您可能需要安装必需的 PulseAudio 软件。
decoder.unsupportedLibavcodec.message = libavcodec 可能存在安全隐患或已不再支持，应当被更新以播放视频。
decoder.decodeError.message = 解码媒体资源时发生错误。
decoder.decodeError.button = 反馈网站问题
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = 解码媒体资源时发生可恢复的错误。
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = 您必须先登录此网络才能访问互联网。
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = 打开网络登录页面
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = 权限：%S
permissions.remove.tooltip = 清除此权限并重新询问
permissions.fullscreen.promptCanceled = 已取消的待处理权限请求：不应在进入 DOM 全屏前发出权限请求。
permissions.fullscreen.fullScreenCanceled = 已退出 DOM 全屏：不应在 DOM 全屏时发出权限请求。
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64 位
aboutDialog.architecture.thirtyTwoBit = 32 位
midi.allow.label = 允许
midi.allow.accesskey = A
midi.block.label = 阻止
midi.block.accesskey = B
midi.remember = 记住此决定
midi.shareWithFile = 要允许此本地文件访问您的 MIDI 设备吗？
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = 要允许 %S 访问您的 MIDI 设备吗？
midi.shareSysexWithFile = 要允许此本地文件访问您的 MIDI 设备，并收发 SysEx 消息吗？
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = 要允许 %S 访问您的 MIDI 设备，并收发 SysEx 消息吗？
serial.allow.label = 允许
serial.allow.accesskey = A
serial.block.label = 阻止
serial.block.accesskey = B
serial.shareWithFile = 要允许此本地文件访问串行端口吗？
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = 要允许 %S 访问串行端口吗？
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = 后退
storageAccess1.Allow.label = 允许
storageAccess1.Allow.accesskey = A
storageAccess1.DontAllow.label = 阻止
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = 要允许 %1$S 在 %2$S 上使用它自己的 Cookie 吗？
storageAccess1.hintText = 若 %1$S 未明确阐述需要此数据的原因，则应该阻止它。
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = 在网上搜索“%S”
