# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dateformat-label =
    .value = Datums-Textformat:
    .accesskey = D
#   $date (String) - the formatted example date
dateformat-long =
    .label = Lang: { $date }
weekstart-label =
    .value = Erster Tag der Woche:
    .accesskey = r
day-1-name =
    .label = Sonntag
day-2-name =
    .label = Montag
day-3-name =
    .label = Dienstag
day-4-name =
    .label = Mittwoch
day-5-name =
    .label = Donnerstag
day-6-name =
    .label = Freitag
day-7-name =
    .label = Samstag
day-1-checkbox =
    .label = So
    .accesskey = S
day-2-checkbox =
    .label = Mo
    .accesskey = M
day-3-checkbox =
    .label = Di
    .accesskey = D
day-4-checkbox =
    .label = Mi
    .accesskey = i
day-5-checkbox =
    .label = Do
    .accesskey = o
day-6-checkbox =
    .label = Fr
    .accesskey = F
day-7-checkbox =
    .label = Sa
    .accesskey = a
dayweek-legend = Tages- und Wochenansichten
visible-hours-label =
    .value = Anzeigen:
    .accesskey = n
visible-hours-end-label =
    .value = Stunde(n)
day-end-label =
    .value = Tag endet um:
    .accesskey = e
midnight-label =
    .label = Mitternacht
noon-label =
    .label = Mittag
multiweek-legend = Mehrwöchige Ansicht
number-of-weeks-label =
    .value = Gesamtanzahl der Wochen (inkl. vergangener Wochen):
    .accesskey = G
week-0-label =
    .label = keine
week-1-label =
    .label = 1 Woche
week-2-label =
    .label = 2 Wochen
week-3-label =
    .label = 3 Wochen
week-4-label =
    .label = 4 Wochen
week-5-label =
    .label = 5 Wochen
week-6-label =
    .label = 6 Wochen
previous-weeks-label =
    .value = Anzahl der vergangenen Wochen:
    .accesskey = v
reminder-play-checkbox =
    .label = Einen Klang abspielen
    .accesskey = k
reminder-default-sound-label =
    .label = Standardklang verwenden
    .accesskey = s
reminder-browse-sound-label =
    .label = Durchsuchen…
    .accesskey = D
alarm-on-label =
    .label = Ein
alarm-off-label =
    .label = Aus
category-edit-label = Kategorie bearbeiten
category-overwrite-title = Warnung: Doppelter Name
category-overwrite = Eine Kategorie mit diesem Namen existiert bereits. Wollen Sie diese überschreiben?
category-blank-warning = Sie müssen einen Kategorienamen eingeben.
