# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

appmenu-update-available =
    .label = A new { -brand-shorter-name } update is redd.
    .buttonlabel = Doonload Update
    .buttonaccesskey = D
    .secondarybuttonlabel = No Jist Noo
    .secondarybuttonaccesskey = N
appmenu-update-available-message = Update yer { -brand-shorter-name } for the latest in speed and preevacy.
appmenu-update-manual =
    .label = { -brand-shorter-name } cannae update tae the latest version.
    .buttonlabel = Doonload { -brand-shorter-name }
    .buttonaccesskey = D
    .secondarybuttonlabel = No Jist Noo
    .secondarybuttonaccesskey = N
appmenu-update-manual-message = Doonload a fresh copy o { -brand-shorter-name } and we’ll help ye tae instaw it.
appmenu-update-whats-new =
    .value = See whit's new.
appmenu-update-unsupported =
    .label = { -brand-shorter-name } isnae able tae update tae the latest version.
    .buttonlabel = Lairn Mair
    .buttonaccesskey = L
    .secondarybuttonlabel = Sneck
    .secondarybuttonaccesskey = C
appmenu-update-unsupported-message = The latest version o { -brand-shorter-name } isnae supportit on yer seestem.
appmenu-update-restart =
    .label = Restert tae update { -brand-shorter-name }.
    .buttonlabel = Restert and Restore
    .buttonaccesskey = R
    .secondarybuttonlabel = No Jist Noo
    .secondarybuttonaccesskey = N
appmenu-update-restart-message = Efter a wee restert, { -brand-shorter-name } will restore aw yer open tabs and windaes that arenae in Preevat Stravaigin mode.
appmenu-update-available2 =
    .label = Update redd
    .buttonlabel = Doonload
    .buttonaccesskey = D
    .secondarybuttonlabel = Dae Withoot
    .secondarybuttonaccesskey = m
appmenu-update-available-message2 = Doonload the latest version o { -brand-shorter-name }.
appmenu-update-manual2 =
    .label = Update redd
    .buttonlabel = Doonload
    .buttonaccesskey = D
    .secondarybuttonlabel = Dae Withoot
    .secondarybuttonaccesskey = m
appmenu-update-manual-message2 = { -brand-shorter-name } couldnae update automatically. Doonload the new version — ye'll no loss saved information or customisations.
appmenu-update-unsupported2 =
    .label = No able tae update
    .buttonlabel = Lairn Mair
    .buttonaccesskey = L
    .secondarybuttonlabel = Rid
    .secondarybuttonaccesskey = m
appmenu-update-unsupported-message2 = Yer operatin seestem disnae gang wi the latest version o { -brand-shorter-name }.
appmenu-update-restart2 =
    .label = Update redd
    .buttonlabel = Update and restert
    .buttonaccesskey = U
    .secondarybuttonlabel = Dae Withoot
    .secondarybuttonaccesskey = m
appmenu-update-restart-message2 = Get the latest version o { -brand-shorter-name }. Open tabs and windaes will be restored.
