#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Иван Стоев</em:contributor> <em:contributor>Со помош од заедницата на корисници.</em:contributor> <em:contributor>Видете mozilla.blog.com.mk</em:contributor>

#unfilter emptyLines
