# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

connection-close-key =
    .key = w
connection-proxy-option-no =
    .label = 프록시 사용 안 함
    .accesskey = y
connection-proxy-option-system =
    .label = 시스템 프록시 설정 사용
    .accesskey = u
connection-proxy-option-auto =
    .label = 프록시 설정 자동 감지
    .accesskey = w
connection-proxy-http = HTTP 프록시
    .accesskey = x
connection-proxy-http-port = 포트
    .accesskey = P
connection-proxy-http-share =
    .label = 모든 프로토콜에 위의 프록시 설정 사용
    .accesskey = s
connection-proxy-ssl = SSL 프록시
    .accesskey = L
connection-proxy-ssl-port = 포트
    .accesskey = o
connection-proxy-ftp = FTP 프록시
    .accesskey = F
connection-proxy-ftp-port = 포트
    .accesskey = r
connection-proxy-socks = SOCKS 호스트
    .accesskey = C
connection-proxy-socks-port = 포트
    .accesskey = t
connection-proxy-socks4 =
    .label = SOCKS v4
    .accesskey = K
connection-proxy-socks5 =
    .label = SOCKS v5
    .accesskey = v
connection-proxy-noproxy = 프록시를 지나지 않음
    .accesskey = n
connection-proxy-noproxy-desc = 예: .mozilla.org, .net.nz, 192.168.1.0/24
connection-proxy-reload =
    .label = 새로 고침
    .accesskey = e
connection-proxy-autologin =
    .label = 비밀번호가 저장되어 있으면 인증시 묻지 않기
    .accesskey = i
    .tooltip = 저장한 자격 증명이 있으면 조용히 인증합니다. 인증이 되지 않으면 물어볼 것입니다.
