# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Notice: If you're updating this list, you should also
###         update the list in mozIntl.js.

region-name-ad = Андорра
region-name-ae = Амороти Муттаҳидаи Арабӣ
region-name-af = Афгонистон
region-name-ag = Антигуа ва Барбуда
region-name-ai = Ангилла
region-name-al = Албания
region-name-am = Арманистон
region-name-ao = Ангола
region-name-aq = Антарктика
region-name-ar = Аргентина
region-name-as = Самоаи Амрикоӣ
region-name-at = Австрия
region-name-au = Австралия
region-name-aw = Аруба
region-name-az = Озарбойҷон
region-name-ba = Босния ва Ҳерсеговина
region-name-bb = Барбадос
region-name-bd = Бангладеш
region-name-be = Белгия
region-name-bf = Буркина Фасо
region-name-bg = Булғористон
region-name-bh = Баҳрайн
region-name-bi = Бурунди
region-name-bj = Бенин
region-name-bl = Сен-Бартелеми
region-name-bm = Бермуда
region-name-bn = Бруней
region-name-bo = Боливия
region-name-bq = Бонэйр, Синт-Эстатиус ва Саба
region-name-br = Бразилия
region-name-bs = Ҷазираҳои Баҳам
region-name-bt = Бутон
region-name-bv = Ҷазираи Бувет
region-name-bw = Ботсвана
region-name-by = Белорусия
region-name-bz = Белиз
region-name-ca = Канада
region-name-cc = Ҷазираҳои Кокос (Килинг)
region-name-cd = Конго (Киншаса)
region-name-cf = Ҷумҳурии Африкаи Марказӣ
region-name-cg = Конго (Браззавил)
region-name-ch = Швейтсария
region-name-ci = Кот-д'Ивуар
region-name-ck = Ҷазираҳои Кук
region-name-cl = Чили
region-name-cm = Камерун
region-name-cn = Чин
region-name-co = Колумбия
region-name-cp = Ҷазираи Клиппертон
region-name-cr = Коста Рика
region-name-cu = Куба
region-name-cv = Кабо Верде
region-name-cw = Кюрасао
region-name-cx = Ҷазираи Кристмас
region-name-cy = Кипр
region-name-cz = Ҷумҳурии Чех
region-name-de = Германия
region-name-dg = Диего Гарсия
region-name-dj = Ҷибути
region-name-dk = Дания
region-name-dm = Доминика
region-name-do = Ҷумҳурии Доминикан
region-name-dz = Алҷазоир
region-name-ec = Эквадор
region-name-ee = Эстония
region-name-eg = Миср
region-name-eh = Саҳрои Ғарбӣ
region-name-er = Эритрея
region-name-es = Испания
region-name-et = Эфиопия
region-name-fi = Финляндия
region-name-fj = Фиҷи
region-name-fk = Ҷазираҳои Фолкленд (Ҷазираҳои Малвинас)
region-name-fm = Микронезия, Иёлоти Муттаҳида
region-name-fo = Ҷазираҳои Фарер
region-name-fr = Франсия
region-name-ga = Габон
region-name-pe = Перу
region-name-pk = Покистон
region-name-pl = Лаҳистон
region-name-pw = Палау
region-name-qa = Қатар
region-name-ru = Россия
region-name-rw = Руанда
region-name-sg = Сингапур
region-name-tg = Того
region-name-th = Таиланд
region-name-tj = Тоҷикистон
region-name-tm = Туркманистон
region-name-tr = Туркия
region-name-tw = Тайван
region-name-ua = Украина
region-name-us = Иёлоти Муттаҳидаи Америка
region-name-uy = Уругвай
region-name-uz = Ӯзбекистон
region-name-ve = Венесуэла
region-name-vn = Ветнам
region-name-vu = Вануату
region-name-ws = Самоа
region-name-xk = Косово
region-name-ye = Яман
region-name-za = Африкаи Ҷанубӣ
region-name-zm = Замбия
region-name-zw = Зимбабве
