# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = आपणास "%S" वर पुढील कारणांसाठी विश्वास ठेवायचे?
unnamedCA = प्रमाणपत्र अधिप्रमाणन (निनामी)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = या प्रमाणपत्राचा बॅकअप एन्क्रिप्ट करताना वापरलेला पासवर्ड टाका:
# Page Info
pageInfo_NoEncryption = जुळवणी एनक्रिप्टेड नाही
pageInfo_Privacy_None1 = संकेत स्थळ %S तर्फे आपण पहात असलेल्या पृष्ठाकरीता एनक्रिप्शन नाही.
pageInfo_Privacy_None2 = इंटरनेटवरील विना एनक्रिप्शन पाठविलेली माहिती इतरांकडुन स्थानांतरेवेळी पाहिल्या जाऊ शकते.\u0020
pageInfo_Privacy_None4 = इंटरनेटवर स्थानांतर करण्यापूर्वी आपण पहात असलेले पृष्ठ एनक्रिप्ट केले नव्हते.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = एनक्रिप्टेड जोडणी (%1$S, %2$S bit keys, %3$S)
pageInfo_BrokenEncryption = खंडित एनक्रिप्शन (%1$S, %2$S bit keys, %3$S)
pageInfo_Privacy_Encrypted1 = इंटरनेटवर स्थानांतर करण्यापूर्वी आपण पहात असलेले पृष्ठ एनक्रिप्ट केले होते.
pageInfo_Privacy_Encrypted2 = एनक्रिप्शनमुळे अनधिकृत व्यक्तिंना एका संगणकावरून दुसऱ्या संगणकावर पाठविलेली माहिती पाहण्यास कठिण जाते. त्यामुळे नेटवर्कवरून ये जा करणारे हे पृष्ठ कुणी वाचेल याची शक्यता खुप कमी आहे.
pageInfo_MixedContent = जुळवणी अंशतः कुटलिपीत
pageInfo_MixedContent2 = इंटरनेटवर स्थानांतर करण्यापूर्वी पृष्ठामधील काही भाग कुटलिपीत नाही.
pageInfo_WeakCipher = या वेबसाइटवर आपले कनेक्शन कमकुवत एनक्रिप्शन वापरते तसेच ते खाजगी नाही. इतर लोक आपली माहिती पाहु शकतात किंवा वेबसाइटचे वर्तन बदलू शकतात.
pageInfo_CertificateTransparency_Compliant = ही वेबसाईट प्रमाणपत्र पारदर्शकता धोरण पाळते.
# Token Manager
password_not_set = (स्थापित नाही)
