# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = Ova se web stranica preusmjerava na novu adresu. Želiš li poslati upisane podatke u obrascu na novu adresu?
# Directory listing strings
DirTitle = Indeks od %1$S
DirGoUp = Gore za jednu razinu direktorija
ShowHidden = Prikaži skrivene objekte
DirColName = Ime
DirColSize = Veličina
DirColMTime = Zadnja promjena
DirFileLabel = Datoteka:\u0020
TrackerUriBlockedByETP = Resurs „%1$S” je blokiran jer je poboljšana zaštita od praćenja aktivirana.
UnsafeUriBlocked = Resurs na „%1$S” je blokiran funkcijom „Sigurno pregledavanje”.
CookieBlockedByPermission = Zahtjev za pristup kolačićima ili spremištu na „”%1$S” je blokiran zbog prilagođenih dozvola za kolačiće.
CookieBlockedAll = Zahtjev za pristup kolačićima ili spremištu na „%1$S” je blokiran , jer blokiramo sve zahtjeve za pristup spremištu.
# LOCALIZATION NOTE(CookieSameSiteValueInvalid2): %1$S is cookie name. Do not localize "SameSite", "Lax", "Strict" and "None"
CookieSameSiteValueInvalid2 = Nevažeća vrijednost za “SameSite“ za kolačić “%1$S”. Podržane vrijednosti su: “Lax“, “Strict“, “None“.
# LOCALIZATION NOTE (CookieOversize): %1$S is the cookie name. %2$S is the number of bytes. "B" means bytes.
CookieOversize = Kolačić “%1$S” nije važeći iz razloga što je prevelik. Maksimalna veličina je %2$S B.
# LOCALIZATION NOTE (CookieRejectedByPermissionManager): %1$S is the cookie response header.
CookieRejectedByPermissionManager = Kolačić „%1$S” je odbijen zbog dozvola koje je postavio korisnik.
