# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

print-setup =
    .title = تنظیم صفحه
custom-prompt-title = سفارشی…
custom-prompt-prompt = متن سرصفحه/پاصفحهٔ سفارشی‌تان را وارد کنید
format-group-label =
    .value = قالب
orientation-label =
    .value = جهت
portrait =
    .label = پرتره‌ای
    .accesskey = پ
landscape =
    .label = منظره‌ای
    .accesskey = م
scale =
    .label = مقیاس:
    .accesskey = م
shrink-to-fit =
    .label = کوچک کردن به اندازهٔ عرض صفحه
    .accesskey = ک
options-group-label =
    .value = گزینه‌ها
margin-group-label-inches =
    .value = حاشیه‌ها (اینچ)
margin-group-label-metric =
    .value = حاشیه‌ها (میلی‌متر)
margin-top =
    .value = بالا:
    .accesskey = ب
margin-top-invisible =
    .value = بالا:
margin-bottom =
    .value = پایین:
    .accesskey = پ
margin-bottom-invisible =
    .value = پایین:
margin-left =
    .value = چپ:
    .accesskey = چ
margin-left-invisible =
    .value = چپ:
margin-right =
    .value = راست:
    .accesskey = ر
margin-right-invisible =
    .value = راست:
hf-left-label =
    .value = چپ:
hf-center-label =
    .value = وسط:
hf-right-label =
    .value = راست:
header-left-tip =
    .tooltiptext = سرصفحهٔ چپ
header-center-tip =
    .tooltiptext = سرصفحهٔ وسط
header-right-tip =
    .tooltiptext = سرصفحهٔ راست
footer-left-tip =
    .tooltiptext = پاصفحهٔ چپ
footer-center-tip =
    .tooltiptext = پاصفحهٔ وسط
footer-right-tip =
    .tooltiptext = پاصفحهٔ راست
hf-blank =
    .label = ‐‐خالی‐‐
hf-title =
    .label = عنوان
hf-url =
    .label = نشانی اینترنتی
hf-date-and-time =
    .label = تاریخ/زمان
hf-page =
    .label = صفحهٔ #
hf-page-and-total =
    .label = صفحهٔ # از #
hf-custom =
    .label = سفارشی…
print-preview-window =
    .title = پیش‌نمای چاپ
print-title =
    .value = عنوان:
print-preparing =
    .value = در حال آماده‌سازی…
print-progress =
    .value = پیشرفت:
print-window =
    .title = در حال چاپ
print-complete =
    .value = چاپ انجام شد.
dialog-cancel-label = انصراف
dialog-close-label = بستن
