# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

print-setup =
    .title = Utskriftsformat
custom-prompt-prompt = Skriv inn egen topp-/bunntekst
basic-tab =
    .label = Formatering og innstillinger
advanced-tab =
    .label = Marger og topp-/bunntekster
format-group-label =
    .value = Formatering
orientation-label =
    .value = Orientering:
scale-percent =
    .value = %
options-group-label =
    .value = Innstillinger
margin-group-label-inches =
    .value = Marger (tommer)
margin-group-label-metric =
    .value = Marger (millimeter)
margin-top-invisible =
    .value = Topp:
margin-bottom-invisible =
    .value = Bunn:
margin-left-invisible =
    .value = Venstre:
margin-right-invisible =
    .value = Høyre:
header-footer-label =
    .value = Topptekst og bunntekst
hf-left-label =
    .value = Venstre:
hf-center-label =
    .value = Midten:
hf-right-label =
    .value = Høyre:
header-left-tip =
    .tooltiptext = Venstre topptekst
header-center-tip =
    .tooltiptext = Midtstilt topptekst
header-right-tip =
    .tooltiptext = Høyre topptekst
footer-left-tip =
    .tooltiptext = Venstre bunntekst
footer-center-tip =
    .tooltiptext = Midtstilt bunntekst
footer-right-tip =
    .tooltiptext = Høyre bunntekst
hf-blank =
    .label = --blank--
hf-title =
    .label = Tittel
hf-url =
    .label = URL
hf-date-and-time =
    .label = Dato/tid
hf-page =
    .label = Side #
hf-page-and-total =
    .label = Side # av #
print-preparing =
    .value = Forbereder …
print-progress =
    .value = Fremdrift:
print-complete =
    .value = Utskriften er ferdig.
# Variables
# $percent (integer) - Number of printed percentage
print-percent =
    .value = { $percent } %
dialog-close-label = Lukk
