# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

custom-prompt-title = Personnaliser…
custom-prompt-prompt = Saisissez votre texte d’en-tête ou de pied de page
basic-tab =
    .label = Format et options
advanced-tab =
    .label = Marges, en-têtes et pieds de page
format-group-label =
    .value = Format
orientation-label =
    .value = Orientation :
portrait =
    .label = Portrait
    .accesskey = P
landscape =
    .label = Paysage
    .accesskey = a
scale =
    .label = Échelle :
    .accesskey = c
scale-percent =
    .value = %
options-group-label =
    .value = Options
print-bg =
    .label = Imprimer le fond de page (couleurs et images)
    .accesskey = I
margin-group-label-inches =
    .value = Marges (pouces)
margin-group-label-metric =
    .value = Marges (millimètres)
header-footer-label =
    .value = En-têtes et pieds de page
hf-left-label =
    .value = Gauche :
hf-center-label =
    .value = Centre :
hf-right-label =
    .value = Droite :
header-left-tip =
    .tooltiptext = En-tête de gauche
header-center-tip =
    .tooltiptext = En-tête centré
header-right-tip =
    .tooltiptext = En-tête de droite
footer-left-tip =
    .tooltiptext = Pied de page de gauche
footer-center-tip =
    .tooltiptext = Pied de page centré
footer-right-tip =
    .tooltiptext = Pied de page de droite
hf-blank =
    .label = --vide--
hf-title =
    .label = Titre
hf-url =
    .label = URL
hf-date-and-time =
    .label = Date/Heure
hf-page =
    .label = N° de page
hf-page-and-total =
    .label = Page # sur #
hf-custom =
    .label = Personnaliser…
print-preparing =
    .value = Préparation…
print-progress =
    .value = Progression :
# Variables
# $percent (integer) - Number of printed percentage
print-percent =
    .value = { $percent }%
