# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

print-setup =
    .title = გვერდის პარამეტრები
custom-prompt-prompt = თავსართის/ქვესართის მითითება
format-group-label =
    .value = ფორმატი
orientation-label =
    .value = ორიენტაცია:
margin-top-invisible =
    .value = ზედა:
margin-bottom-invisible =
    .value = ქვედა:
margin-left-invisible =
    .value = მარცხენა:
margin-right-invisible =
    .value = მარჯვენა:
hf-left-label =
    .value = მარცხენა:
hf-center-label =
    .value = შუა:
hf-right-label =
    .value = მარჯვენა:
header-left-tip =
    .tooltiptext = მარცხენა თავსართი
header-center-tip =
    .tooltiptext = შუა თავსართი
header-right-tip =
    .tooltiptext = მარჯვენა თავსართი
footer-center-tip =
    .tooltiptext = შუა ქვესართი
footer-right-tip =
    .tooltiptext = მარჯვხენა ქვესართი
hf-blank =
    .label = -ცარიელი-
hf-title =
    .label = სათაური
hf-date-and-time =
    .label = თარიღი
hf-page =
    .label = გვერდი #
hf-page-and-total =
    .label = გვერდი # სულ #
print-title =
    .value = სათაური:
print-preparing =
    .value = მზადება…
print-window =
    .title = ბეჭდვა
print-complete =
    .value = ბეჭდვა დასრულდა.
dialog-cancel-label = გაუქმება
dialog-close-label = დახურვა
