# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

#define Welcome_Title Подешавање за програм $ProductName$

#define Welcome_MessageWelcome Добро дошли у програм %s!

#define Welcome_Message0 Ускоро ћете да инсталирате програм %s 3 алфа 1.

#define Welcome_Message1 Препоручујемо вам да угасите све друге програме пре него покренете овај програм.

#define Welcome_Message2 Притисните „Откажи‟ да бисте напустили програм и затворили остале покренуте програме.  Притисните „Даље‟ како бисте наставили са радом у овом програму.

#define Welcome_Message3 Притисните „Даље‟ како бисте наставили са постављањем програма %s 3 алфа 1.

#define License_Title Споразум о лиценцирању програма

#define License_SubTitle Услови за употребу овог програма.

#define License_Message0 Молимо да прочитате дати споразум о лиценцирању.  Користите клизач како бисте прегледали и остатак споразума.

#define License_Accept &Прихватам споразум о лиценцирању

#define License_Decline &Не прихватам споразум о лиценцирању

#define Type_Title Врста инсталације

#define Type_SubTitle Изаберите начин инсталације.

#define Type_Message0 Изаберите врсту инсталације која Вам одговара, затим притисните „Даље‟.

#define Standard_Short &Стандардна

#define Standard_Long Програм Тандерберд (Thunderbird) биће постављен са уобичајеним могућностима.

#define Custom_Short &Прилагођена

#define Custom_Long Можете да изаберете могућности које желите да буду постављене.  Препоручује се искусним корисницима.

#define Select_Title Избор делова

#define Select_SubTitle Додатни делови за побољшање програма $ProductName$.

#define Select_Message0 Изаберите додатне делове које желите да инсталирате, затим притисните „Даље‟.

#define Path_Title Директоријум за инсталацију

#define Path_SubTitle Место где ће програм $ProductName$ бити инсталиран.

#define Path_Message0 Програм $ProductName$ биће инсталиран у овај директоријум:

#define Integration_Title Постављање скраћеница

#define Integration_SubTitle Прави сличице програма

#define Integration_Message0 Направи сличице за програм $ProductShortName$:

#define Integration_Desktop На радној површини

#define Integration_StartMenu У менију за покретање програма

#define Integration_QuickLaunch На траци за брзо покретање

#define SelectFolder_Title Подешавање програма $ProductName$ - Избор директоријума

#define SelectFolder_Message0 Инсталатер ће додати сличице програма у доле наведен директоријум.  Можете да унесете ново име директоријума или да изаберете један из списка постојећих.  Притисните „Даље‟ да наставите.

#define Advanced_Title Инсталатер програма $ProductName$ - Напредна подешавања

#define Advanced_Message0 Ако Ваша веза са Интернетом захтева посредника (proxy), можете да унесете његово име и податке о порту.  Ако веза са Интернетом не захтева посредника, оставите ово поље непопуњено.

#define Install_Title Сажетак

#define Install_SubTitle Све је спремно за инсталацију програма $ProductName$.

#define Install_MessageInstall Инсталатер ће поставити следеће делове:

#define Install_MessageDownload Инсталатер ће да прими и инсталира следеће делове:

#define Install_Message0 Притисните „Даље‟ да наставите.

#define Downloading_Title Пријем

#define Downloading_SubTitle Пријем неопходних делова…

#define Downloading_Blurb Инсталатер прима датотеке неопходне за инсталацију програма $ProductName$.

#define Downloading_FileName Тренутни пријем:

#define Downloading_Time Преостало време:

#define Installing_Title Инсталација

#define Installing_SubTitle Инсталација програма $ProductName$…

#define Installing_Blurb Инсталатер поставља датотеке програма.

#define Installing_Status Припрема датотеке:

#define Installing_Component Тренутно се инсталира:

#define Success_Title Инсталација је готова

#define Success_Header Инсталација је готова

#define Success_Message0 Програм %s је успешно инсталиран.

#define Success_Message1 Притисните „Заврши‟ да завршите инсталацију

#define Success_Launch Покрени одмах програм %s.

#define Check_Message Пријем производа $ProductName$ је успео. $ProductNameInternal$ мора да буде затворен како би се наставило са инсталацијом.  Притисните „У реду‟ да изађете из програма $ProductNameInternal$ и да отпочнете инсталацију.

#define Check_FullMessage Програм $ProductNameInternal$ мора да се заврши како би инсталација била настављена.  Притисните „У реду‟ како бисте аутоматски завришили рад са програмом $ProductNameInternal$ и како бисте почели инсталацију.

#define Check_Wait Крај рада са програмом $ProductNameInternal$.  Молимо да сачекате…

#define Component_XPCOM Преносиви COM

#define Component_Mail $ProductName$

#define Component_Offline Корисничка подршка

#define Component_Offline_Long Додавање корисничке подршке у програм $ProductName$.

#define Component_RSS Подршка за РСС

#define Component_RSS_Long Додаје подршку за РСС у програм $ProductName$.

#define Component_QFA Повратна информација о квалитету

#define Component_QFA_Long за пријаву проблема са програмом $ProductName$
