# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE (triedToSendReport):
# %1$S is the URI we attempted to send a report to.
triedToSendReport = Sizamile ukuthumela ingxelo kwi-URI:engeyiyo "%1$S"
# LOCALIZATION NOTE (ignoringUnknownOption):
# %1$S is the option that could not be understood
ignoringUnknownOption = Ayihoyi ukhetho olungaziwayo i-%1$S
# LOCALIZATION NOTE (ignoringDuplicateSrc):
# %1$S defines the duplicate src
ignoringDuplicateSrc = Ayiwuhoyi umthombo ophindiweyo %1$S
# LOCALIZATION NOTE (ignoringSrcFromMetaCSP):
# %1$S defines the ignored src
ignoringSrcFromMetaCSP = Ayiwusiso umthombo+ '%1$S' (Ayixhaswa xa ithunyelwa nge-elementi yemeta).
# LOCALIZATION NOTE (reportURInotHttpsOrHttp2):
# %1$S is the ETLD of the report URI that is not HTTP or HTTPS
reportURInotHttpsOrHttp2 = I-URI yengxelo (%1$S) ifanele ibe yi-URI ye-HTTP okanye iiHTTPS.
# LOCALIZATION NOTE (failedToParseUnrecognizedSource):
# %1$S is the CSP Source that could not be parsed
failedToParseUnrecognizedSource = Isilele ukuparsa umthombo ongaziwayo %1$S
# LOCALIZATION NOTE (upgradeInsecureRequest):
# %1$S is the URL of the upgraded request; %2$S is the upgraded scheme.
upgradeInsecureRequest = Iphucula isicelo esingakhuselwanga '%1$S' sokusebenzisa i-'%2$S
# LOCALIZATION NOTE (ignoreSrcForDirective):
ignoreSrcForDirective = Ityeshela ii-srcs zesalathisi '%1$S'
# LOCALIZATION NOTE (notSupportingDirective):
# directive is not supported (e.g. 'reflected-xss')
notSupportingDirective = \ Ayiluxhasi ulwalathiso lwe- '%1$S'. Ulwalathiso nemilinganiselo iya kungahoywa
# CSP Errors:
# LOCALIZATION NOTE (couldntParseInvalidSource):
# %1$S is the source that could not be parsed
couldntParseInvalidSource = yikwazi kuparse umthombo ongenguwo %1$S
# LOCALIZATION NOTE (couldntParseInvalidHost):
# %1$S is the host that's invalid
couldntParseInvalidHost = Ayikwazi kuparse umamkeli ongenguye %1$S
# LOCALIZATION NOTE (duplicateDirective):
# %1$S is the name of the duplicate directive
duplicateDirective = Izalathiso eziphindaphindiweyo %1$S zifunyanisiwe. Zonke ngaphandle kwesihlandlo sokuqala azizi kuhoywa
