# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Mencari { $host }…
network-connection-status-connected = Tersambung ke { $host }…
network-connection-status-sending-request = Mengirimkan permintaan ke { $host }…
network-connection-status-transferring-data = Mentransfer data dari { $host }…
network-connection-status-connecting = Mencari sambungan ke { $host }…
network-connection-status-read = Membaca { $host }
network-connection-status-wrote = Menulis ke { $host }
network-connection-status-waiting = Menunggu { $host }…
network-connection-status-looked-up = Mencari { $host }…
network-connection-status-tls-handshake = Melakukan jabat tangan TLS ke { $host }…
network-connection-status-tls-handshake-finished = Jabat tangan TLS selesai untuk { $host }…
