#filter emptyLines

#define MOZ_LANGPACK_EID {8f007c50-fcee-11d9-8cd6-0800200c9a66}
#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
# #define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Joe Solon</em:contributor> <em:contributor>Suzy Solon</em:contributor>

#unfilter emptyLines
