# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

addons-window =
    .title = অ্যাড-অন ব্যবস্থাপক
search-header-shortcut =
    .key = f
loading-label =
    .value = লোড করা হচ্ছে…
list-empty-installed =
    .value = আপনার এই ধরণের কোনো অ্যাড-অন ইনস্টল করা নেই
list-empty-available-updates =
    .value = কোনো হালনাগাদ পাওয়া যায়নি
list-empty-recent-updates =
    .value = আপনি সাম্প্রতিক সময়ে কোনো অ্যাড-অন হালনাগাদ করেননি
list-empty-find-updates =
    .label = হালনাগাদের জন্য পরীক্ষা
list-empty-button =
    .label = অ্যাড-অন সম্পর্কে আরও শিখুন
install-addon-from-file =
    .label = ফাইল থেকে অ্যাড-অন ইনস্টল… I
    .accesskey = I
tools-menu =
    .tooltiptext = সব অ্যাড-অন এর জন্য টুল
show-unsigned-extensions-button =
    .label = কিছু এক্সটেনশন ভ্যারিফাই করা হয়নি
show-all-extensions-button =
    .label = সব এক্সটেনশন দেখাও
debug-addons =
    .label = অ্যাড-অন ডিবাগ
    .accesskey = b
cmd-show-details =
    .label = আরও তথ্য প্রদর্শন করা হবে S
    .accesskey = S
cmd-enable-theme =
    .label = থীম যোগ W
    .accesskey = W
cmd-disable-theme =
    .label = থীম যোগ বন্ধ W
    .accesskey = W
cmd-install-addon =
    .label = ইনস্টল করুন I
    .accesskey = I
cmd-contribute =
    .label = অবদান রাখুন C
    .accesskey = C
    .tooltiptext = অ্যাড-অন উন্নয়নে অবদান রাখুন
discover-title = অ্যাড-অন কি?
discover-description = অ্যাড-অন হল এমন অ্যাপ্লিকেশন যা কি না অতিরিক্ত কার্যকরণ বা শৈলীসহ { -brand-short-name } এর সাথে আপনাকে পরিচিত করে। সময়- সংরক্ষণীয় সাইডবার, আবহাওয়া ঘোষক, বা { -brand-short-name } কে নিজের মত করে দেখার জন্য থীম চেহারা ব্যবহার করে।
discover-footer = আপনি যখন ইন্টারনেট এর সাথে সংযুক্ত থাকবেন তখন আপনার ব্যবহারের জন্য এ প্যানে কিছু সর্বোৎকৃষ্ট ও সবচেয়ে জনপ্রিয় অ্যাড-অন প্রদর্শিত হবে।
detail-version =
    .label = সংস্করণ
detail-last-updated =
    .label = সর্বশেষ হালনাগাদ
detail-contributions-description = এ অ্যাড-অন ডেভেলপার বলে যে, আপনি আপনার যে কোনো ছোট অবদান দিয়েও এই অ্যাড-অনের উন্নয়নে সহায়তা করতে পারেন।
detail-update-type =
    .value = স্বয়ংক্রিয় হালনাগাদ
detail-update-automatic =
    .label = সচল
    .tooltiptext = স্বয়ংক্রিয়ভাবে হালনাগাদ ইনস্টল করা হবে
detail-update-manual =
    .label = বন্ধ
    .tooltiptext = স্বয়ংক্রিয়ভাবে হালনাগাদ ইনস্টল করা হবে না
detail-home-value =
    .value = { detail-home.label }
detail-repository =
    .label = অ্যাড-অন প্রোফাইল
detail-repository-value =
    .value = { detail-repository.label }
detail-rating =
    .value = রেটিং
addon-restart-now =
    .label = এখন পুনরায় শুরু করুন
disabled-unsigned-heading =
    .value = কিছু অ্যাড-অন নিস্ক্রিয় করা হয়েছে
disabled-unsigned-description = নিম্নলিখিত অ্যাড-অনসমূহ { -brand-short-name } ব্যবহারের জন্য যাচাই করা হয় নি। আপনি যা করতে পারেন <label data-l10n-name="find-addons">প্রতিস্থাপন খুঁজুন</label> অথবা ডেভেলপার কে জিজ্ঞাসা করুন যাচাই করার জন্য
disabled-unsigned-learn-more = আপনাকে অনলাইনে নিরাপদ রাখতে সাহায্য করতে আমাদের প্রচেষ্টা সম্পর্কে আরও জানুন.
disabled-unsigned-devinfo = পড়ার অবিরত করতে পারেন যাচাই তাদের অ্যাড টার্ন পেতে আগ্রহী ডেভেলপারদের আমাদের <label data-l10n-name="learn-more">ম্যানুয়াল</label>।
plugin-deprecation-description = কোন কিছু পাওয়া যাচ্ছে না? কোন কোন প্লাগইন { -brand-short-name } আর সমর্থন করে না। <label data-l10n-name="learn-more">আরও জানুন।</label>
legacy-warning-show-legacy = সব পুরাতন এক্সটেনশন দেখাও
