# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host } অনুসন্ধান করা হচ্ছে…
network-connection-status-connected = { $host } এর সাথে সংযুক্ত…
network-connection-status-sending-request = { $host } এ অনুরোধ পাঠানো হচ্ছে…
network-connection-status-transferring-data = { $host } থেকে তথ্য স্থানান্তর করা হচ্ছে…
network-connection-status-connecting = { $host } এর সাথে সংযোগ করা হচ্ছে…
network-connection-status-read = { $host } পড়ুন
network-connection-status-wrote = { $host } লেখা হয়েছে
network-connection-status-waiting = { $host } এর জন্য অপেক্ষা করা হচ্ছে…
network-connection-status-looked-up = { $host } অনুসন্ধান করা হয়েছে…
network-connection-status-tls-handshake = { $host } এর সাথে TLS হ্যান্ডশেক করছে ...
network-connection-status-tls-handshake-finished = { $host } এর সাথে TLS হ্যান্ডশেক শেষ হয়েছে ...
