# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=Instalador de $ProductShortName$
Welcome_MessageWelcome=Bienvenido a %s
Welcome_Message0=Va a instalar %s 3 Alpha 1.
Welcome_Message1=Se recomienda que salga de todos los programas de Windows antes de ejecutar este programa instalador.
Welcome_Message2=Haga clic en Cancelar para salir de la instalación y cierre cualquier programa que esté ejecutando.  Haga clic en Siguiente para continuar el programa instalador.
Welcome_Message3=Haga clic en Siguiente para continuar instalando %s 3 Alpha 1.

License_Title=Contrato de Licencia de Software
License_SubTitle=Términos y condiciones para usar este software.
License_Message0=Lea el siguiente contrato de licencia. Use la barra de desplazamiento para ver el resto del contrato.
License_Accept=&Acepto los términos del contrato de licencia
License_Decline=&NO acepto los términos del contrato de licencia

Type_Title=Tipo de instalación
Type_SubTitle=Seleccione las opciones de instalación.
Type_Message0=Seleccione el tipo de instalación que prefiera, y haga clic en Siguiente.

Standard_Short=E&stándar
Standard_Long=Thunderbird se instalará con las opciones más comunes.

Custom_Short=Personali&zada
Custom_Long=Puede seleccionar opciones individuales para ser instaladas. Recomendado para usuarios experimentados.

Select_Title=Seleccionar componentes
Select_SubTitle=Componentes adicionales que mejoran a $ProductShortName$.
Select_Message0=Seleccione componentes adicionales que desee instalar y haga clic en Siguiente.

Path_Title=Carpeta de instalación
Path_SubTitle=Donde se instalará $ProductShortName$.
Path_Message0=$ProductShortName$ se instalará en la siguiente carpeta:

Integration_Title=Accesos Directos
Integration_SubTitle=Crear íconos de programa
Integration_Message0=Crear íconos para $ProductShortName$:

Integration_Desktop=En el Escritorio
Integration_StartMenu=En el Menú Inicio
Integration_QuickLaunch=En la barra de Inicio Rápido

SelectFolder_Title=Instalador de $ProductShortName$ - Seleccionar carpeta de programa
SelectFolder_Message0=El instalador agregará íconos de programa a la carpeta mencionada debajo.  Puede ingresar un nuevo nombre de carpeta, o seleccionar una de la lista de carpetas existentes.  Haga clic en Siguiente para continuar.

Advanced_Title=Instalador de $ProductShortName$ - Opciones avanzadas
Advanced_Message0=Si su conexión a Internet requiere un servidor proxy, ingréselo junto con la información de puertos.  Si su conexión a Internet no requiere un servidor proxy, deje los campos en blanco.

Install_Title=Resumen
Install_SubTitle=Listo para comenzar a instalar $ProductShortName$.
Install_MessageInstall=Se instalarán los siguientes componentes:
Install_MessageDownload=Se descargarán e instalarán los siguientes componentes:
Install_Message0=Haga clic en Siguiente para continuar.

Downloading_Title=Descargando
Downloading_SubTitle=Descargando componentes requeridos...
Downloading_Blurb=El instalador está descargando los archivos requeridos para instalar $ProductShortName$.
Downloading_FileName=Descargando:
Downloading_Time=Tiempo restante:

Installing_Title=Instalando
Installing_SubTitle=Instalando $ProductShortName$...
Installing_Blurb=Se están instalando los archivos de la aplicación.
Installing_Status=Preparando archivo:
Installing_Component=Instalando actualmente:

Success_Title=Instalación completa
Success_Header=Instalación completa
Success_Message0=%s fue correctamente instalado.
Success_Message1=Haga clic en Finalizar para terminar la instalación.
Success_Launch=Ejecutar %s ahora.

Check_Message=La descarga de $ProductShortName$ fue exitosa. $ProductNameInternal$ debe cerrarse para proceder con la instalación. Haga clic en Aceptar para salir de $ProductNameInternal$ automáticamente y comenzar la instalación.
Check_FullMessage=$ProductNameInternal$ debe cerrarse para proceder con la instalación. Haga clic en Aceptar para salir de $ProductNameInternal$  automáticamente y comenzar la instalación.
Check_Wait=Cerrando $ProductNameInternal$.  Espere...

Component_XPCOM=Com Multiplataforma
Component_Mail=$ProductName$
Component_Offline=Soporte sin conexión
Component_Offline_Long=Agrega soporte sin conexión al correo $ProductName$.
Component_RSS=Soporte RSS
Component_RSS_Long=Agrega soporte RSS a $ProductName$.
Component_QFA=Quality Feedback Agent
Component_QFA_Long=para informar sobre los errores de $ProductShortName$
