# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=$ProductName$ Ukuhlelwa
Welcome_MessageWelcome=Uyemukelwa e%s!
Welcome_Message0=You are about to install %s 2 Alpha 1.
Welcome_Message1=Kutuswa kakhulu ukuba uphume kuzo zonke izinhlelo ze-Windows ngaphambi kokusebenzisa lolu hlelo lokuHlelwa.
Welcome_Message2=Chofoza uKhansela ukuze uyeke ukuHlelwa bese uvala zonke izinhlelo ozisebenzisayo.  Chofoza okuthi Okulandelayo ukuze uqhubeke nohlelo lokuHlelwa.
Welcome_Message3=Click Next to continue installing %s 2 Alpha 1.

License_Title=Isivumelwano Semvume Yohlaka Olusetshenziswayo
License_SubTitle=Imigomo Nemibandela yokusebenzisa lolu hlaka olusetshenziswayo.
License_Message0=Sicela ufunde isivumelwano semvume esilandelayo. Sebenzisa umgoqo wokuhambisa ukuze usibone sonke lesi sivumelwano.
License_Accept=N&giyayamukela imigomo yalesi Sivumelwano Semvume
License_Decline=Angi&yamukeli imigomo yalesi Sivumelwano Semvume

Type_Title=Uhlobo Lokuhlelwa
Type_SubTitle=Khetha okokuhlela ongakhetha kukho.
Type_Message0=Khetha uhlobo lokuHlelwa oluthandayo, bese uchofoza Okulandelayo.

Standard_Short=&Okuvamile
Standard_Long=IThunderbird izofakelwa kanye nongakhetha kukho ovame kakhulu.

Custom_Short=&Indlela Evamile
Custom_Long=Ungakhetha ukuba kufakelwe ongakhetha kukho ngakunye. Lokhu kutuswa kwabangomakadebona.

Select_Title=Khetha Izakhi
Select_SubTitle=Ezinye izakhi ezithuthukisa i$ProductName$.
Select_Message0=Khetha ezinye izakhi ofuna ukuzifakela, bese uchofoza Okulandelayo.

Path_Title=Fakela Ifolda
Path_SubTitle=Lapho i$ProductName$ izofakelwa khona.
Path_Message0=$ProductName$ izofakelwa efolideni elandelayo:

Integration_Title=Hlela Izindlela Ezinqamulelayo
Integration_SubTitle=Yakha Izithonjana Zohlelo
Integration_Message0=Yakha izithonjana ze$ProductShortName$:

Integration_Desktop=Okukuskrini Sami
Integration_StartMenu=Kwifolda Yezinhlelo Ohlwini Lokukhona Ekuqaleni
Integration_QuickLaunch=Kwibha yami ethi Yiqale Ngokushesha

SelectFolder_Title=Ukuhlelwa kwe$ProductName$ - Khetha Ifolida Yohlelo
SelectFolder_Message0=UkuHlelwa kuzonezela izithonjana zezinhlelo kwiFolda Yezinhlelo engezansi.  Ungase ubhale igama lefolda entsha, noma ulikhethe ohlwini lwamaFolda Akhona.  Chofoza okuthi Okulandelayo ukuze uqhubeke.

Advanced_Title=UkuHlelwa kwe$ProductName$ - Ukuhlelwa Okuthuthukile
Advanced_Message0=Uma ukuxhunywa kwakho ne-Inthanethi kudinga isiphakeli se-proxy, faka igama lesiphakeli sakho nokwaziswa ngephothi.  Uma ukuxhunywa kwakho ne-Inthanethi kungasidingi isiphakeli se-proxy, ungafaki lutho esikhaleni.

Install_Title=Amanqampunqampu
Install_SubTitle=Isilungele ukuqala ukufakela i$ProductName$.
Install_MessageInstall=UkuHlelwa manje kuzofakela izakhi ezilandelayo:
Install_MessageDownload=UkuHlelwa manje kuzothatha kufake futhi kufakele izakhi ezilandelayo:
Install_Message0=Chofoza Okulandelayo ukuze uqhubeke.

Downloading_Title=Iyathatha Iyafaka
Downloading_SubTitle=Iyathatha iyafaka izakhi ezidingekayo...
Downloading_Blurb=UkuHlelwa kuthatha kufake amafayela adingekayo ukuze kufakelwe i$ProductName$.
Downloading_FileName=Njengamanje Iyathatha Iyafaka:
Downloading_Time=Isikhathi Esisele:

Installing_Title=Iyafakela
Installing_SubTitle=Iifakela i$ProductName$...
Installing_Blurb=Ukuhlelwa kufakela amafayela okusetshenziswayo.
Installing_Status=Ilungiselela Ifayela:
Installing_Component=Njengamanje Ifakela:

Success_Title=Ukufakela Sekuphelile
Success_Header=Ukufakela Sekuphelile
Success_Message0=%s ifakelwe ngempumelelo.
Success_Message1=Chofoza okuthi Isiqedile ukuze uqede ukuHlelwa.
Success_Launch=Qalisa i-%s manje.

Check_Message=UkuThathufake i$ProductName$ kube impumelelo. I$ProductNameInternal$ kumelwe ivalwe ukuze uqhubeke nokufakela. Chofoza u-Lungile ukuze uziphumele ku$ProductNameInternal$ futhi uqale ukufakela.
Check_FullMessage=$ProductNameInternal$ kumelwe ivalwe ukuze uqhubeke nokufakela. Chofoza okuthi Kulungile ukuze uvele uphume ku$ProductNameInternal$ futhi uqale ukufakela.
Check_Wait=Ivala $ProductNameInternal$.  Sicela ulinde...

Component_XPCOM=Nqamula iPulatifomu COM
Component_Mail=$ProductName$
Component_Offline=Ukusekelwa Ngaphandle Kwe-internet
Component_Offline_Long=Inezela ukusekelwa Ngaphandle Kwe-internet ePosini le$ProductName$.
Component_RSS=Ukusekelwa kweRSS
Component_RSS_Long=Inezela ukusekelwa kweRSS e$ProductName$.
Component_QFA=Inxusa Elibuyisa Umbiko Ngokuba Sezingeni
Component_QFA_Long=kokubika ukwaziswa ngokuphihlika kwe$ProductName$
