# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

print-setup =
    .title = Gosodiad Tudalen
format-group-label =
    .value = Fformat
orientation-label =
    .value = Cyfeiriadaeth:
portrait =
    .label = Portread
    .accesskey = P
landscape =
    .label = Tirwedd
    .accesskey = T
scale-percent =
    .value = %
shrink-to-fit =
    .label = Cywasgu i Led y Dudalen
    .accesskey = L
options-group-label =
    .value = Dewisiadau
margin-group-label-inches =
    .value = Ymylon (modfedd)
margin-group-label-metric =
    .value = Ymylon (milimetr)
margin-top =
    .value = Brig:
    .accesskey = B
margin-top-invisible =
    .value = Brig:
margin-bottom =
    .value = Gwaelod:
    .accesskey = G
margin-bottom-invisible =
    .value = Gwaelod:
margin-left =
    .value = Chwith:
    .accesskey = C
margin-left-invisible =
    .value = Chwith:
margin-right =
    .value = De:
    .accesskey = D
margin-right-invisible =
    .value = De:
hf-left-label =
    .value = Chwith:
hf-center-label =
    .value = Canoli:
hf-right-label =
    .value = De:
footer-left-tip =
    .tooltiptext = Troedyn chwith
footer-center-tip =
    .tooltiptext = Troedyn canol
footer-right-tip =
    .tooltiptext = Troedyn de
hf-blank =
    .label = --gwag--
hf-title =
    .label = Teitl
hf-date-and-time =
    .label = Dyddiad/Amser
hf-page =
    .label = Tudalen #
hf-page-and-total =
    .label = Tudalen # o #
print-preview-window =
    .title = Rhagolwg Argraffu
print-title =
    .value = Teitl:
print-progress =
    .value = Cynnydd:
print-window =
    .title = Argraffu
print-complete =
    .value = Argraffu wedi ei Gwblhau.
# Variables
# $percent (integer) - Number of printed percentage
print-percent =
    .value = { $percent }%
dialog-cancel-label = Diddymu
dialog-close-label = Cau
