# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Expirou
openFile = Abrir ficheiro
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Pesquisar por “%2$S” no %1$S
contextMenuSearch.accesskey = P
contextMenuPrivateSearch = Pesquisar numa janela privada
contextMenuPrivateSearch.accesskey = p
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Pesquisar com o %S numa janela privada
contextMenuPrivateSearchOtherEngine.accesskey = p
bookmarkAllTabsDefault = [Nome da pasta]
unsignedAddonsDisabled.message = Um ou mais dos complementos instalados não podem ser verificados e foram desativados.
unsignedAddonsDisabled.learnMore.label = Saber mais
unsignedAddonsDisabled.learnMore.accesskey = b
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Último acesso %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = Ligações %S://
crashedpluginsMessage.title = O plugin %S falhou.
crashedpluginsMessage.reloadButton.label = Recarregar página
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = Submeter relatório de falha
crashedpluginsMessage.submitButton.accesskey = S
crashedpluginsMessage.learnMore = Saber mais…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Pretendia ir para %S?
keywordURIFixup.goTo = Sim, leve-me para %S
keywordURIFixup.goTo.accesskey = S
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Atualização para %S
update.downloadAndInstallButton.accesskey = u
menuOpenAllInTabs.label = Abrir tudo em separadores
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Recarregar esta página
tabHistory.goBack = Retroceder para esta página
tabHistory.goForward = Avançar para esta página
# URL Bar
pasteAndGo.label = Colar e ir
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Recarregar página atual (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Parar de carregar esta página (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Repor nível de zoom (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Alternar visualização de leitura (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, Redefinir nível de zoom
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Mostrar os seus marcadores (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Mostrar progresso das transferências em curso (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Abrir uma nova janela (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Abrir um novo separador (%S)
newTabContainer.tooltip = Abra um novo separador (%S)\nPressione sem soltar para abrir um novo separador contentor
newTabAlwaysContainer.tooltip = Selecionar um contentor para abrir um novo separador
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Permitir que %S utilize os seus dados de imagem canvas do HTML5?
canvas.siteprompt2.warning = Isto pode ser utilizado para identificar o seu computador.
canvas.block = Bloquear
canvas.block.accesskey = B
canvas.allow2 = Permitir
canvas.allow2.accesskey = P
canvas.remember2 = Memorizar esta escolha
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Verificado por: %S
identity.identified.verified_by_you = Adicionou uma exceção de segurança para este site.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Certificado emitido para: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Não seguro
identity.notSecure.tooltip = Ligação não segura
identity.extension.label = Extensão (%S)
identity.extension.tooltip = Carregada pela extensão: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Reduzir (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Repor nível de zoom (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Ampliar (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Cortar (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Copiar (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Colar (%S)
geolocation.allow = Permitir
geolocation.allow.accesskey = P
geolocation.block = Bloquear
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Isto irá abrir as definições de localização do sistema. Por favor, conceda permissão de localização a %S.
geolocation.shareWithSite4 = Permitir que %S aceda à sua localização?
geolocation.shareWithFile4 = Permitir que este ficheiro local aceda à sua localização?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Permitir que %1$S dê permissão a %2$S para aceder à sua localização?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Conceder permissão de localização a %S nas definições do sistema.
geolocation.systemSettingsTitle = A aguardar permissão de localização
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = O sistema irá solicitar-lhe para que dê esta permissão a %S.
geolocation.remember = Memorizar esta decisão
# Virtual Reality Device UI
xr.allow2 = Permitir
xr.allow2.accesskey = P
xr.block = Bloquear
xr.block.accesskey = B
xr.shareWithSite4 = Permitir que %S aceda aos seus dispositivos de realidade virtual? Isto pode expor informação sensível.
xr.shareWithFile4 = Permitir que este ficheiro local aceda aos seus dispositivos de realidade virtual? Isto pode expor informação sensível.
xr.remember = Lembrar esta decisão
# Persistent storage UI
persistentStorage.allow = Permitir
persistentStorage.allow.accesskey = P
persistentStorage.block.label = Bloquear
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Permitir que %S guarde dados no armazenamento persistente?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Permitir
webNotifications.allow2.accesskey = P
webNotifications.notNow = Agora não
webNotifications.notNow.accesskey = n
webNotifications.never = Nunca permitir
webNotifications.never.accesskey = c
webNotifications.alwaysBlock = Bloquear sempre
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = Bloquear
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Permitir que %S envie notificações?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = O %S pretende aceder a outras aplicações e serviços neste dispositivo.
localhost.remember2 = Memorizar a minha escolha para este site
localhost.allowlabel = Permitir
localhost.blocklabel = Bloquear
localhost.allow.accesskey = P
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S pretende aceder a aplicações e serviços em dispositivos ligados à sua rede local.
localNetwork.remember2 = Memorizar a minha escolha para este site
localNetwork.allowLabel = Permitir
localNetwork.allow.accesskey = P
localNetwork.blockLabel = Bloquear
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Tirem-me daqui!
safebrowsing.getMeOutOfHereButton.accessKey = T
safebrowsing.deceptiveSite = Site decetivo!
safebrowsing.notADeceptiveSiteButton.label = Este não é um site decetivo…
safebrowsing.notADeceptiveSiteButton.accessKey = d
safebrowsing.reportedAttackSite = Reportado como site de ataque!
safebrowsing.notAnAttackButton.label = Este não é um site de ataque…
safebrowsing.notAnAttackButton.accessKey = a
safebrowsing.reportedUnwantedSite = Reportado como site de software não-solicitado!
safebrowsing.reportedHarmfulSite = Reportado como site prejudicial!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Pesquisar %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Reiniciar o %S no modo de diagnóstico?
troubleshootModeRestartPromptMessage = As suas extensões, temas e definições personalizadas serão temporariamente desativadas.
troubleshootModeRestartButton = Reiniciar
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Esta página está a reduzir o desempenho do %1$S. Para acelerar o seu navegador, pare esta página.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Uma página de Internet está a reduzir o desempenho do %1$S. Para acelerar o seu navegador, pare essa página.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = “%1$S” está a reduzir o desempenho do %2$S. Para acelerar o seu navegador, pare esta página.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = “%1$S” está a reduzir o desempenho do %2$S. Para acelerar o seu navegador, pare esta extensão.
processHang.add-on.learn-more.text = Saber mais
processHang.button_stop2.label = Parar
processHang.button_stop2.accessKey = P
processHang.button_debug.label = Depurar script
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Mostrar janela em ecrã completo (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Mover barra lateral para a esquerda
sidebar.moveToRight = Mover barra lateral para a direita
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Deve ativar o DRM para reproduzir algum áudio ou vídeo desta página.
emeNotifications.drmContentDisabled.button.label = Ativar DRM
emeNotifications.drmContentDisabled.button.accesskey = A
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = O %S está a instalar os componentes necessários para reproduzir áudio ou vídeo nesta página. Por favor tente novamente mais tarde.
emeNotifications.unknownDRMSoftware = Desconhecido
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Personalizar o %S
decoder.noCodecs.button = Saiba como
decoder.noCodecs.accesskey = S
decoder.noCodecsLinux.message = Para reproduzir vídeo, poderá ter de instalar os codecs de vídeo necessários.
decoder.noHWAcceleration.message = Para melhorar a qualidade de vídeo, poderá ter de instalar o Media Feature Pack da Microsoft.
decoder.noPulseAudio.message = Para reproduzir áudio, poderá ter de instalar o necessário software PulseAudio.
decoder.unsupportedLibavcodec.message = libavcodec pode ser vulnerável ou não é suportado, e deve ser atualizado para reproduzir vídeo.
decoder.decodeError.message = Ocorreu um erro enquanto descodificava um recurso multimédia.
decoder.decodeError.button = Reportar problema no site
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = Ocorreu um erro recuperável enquanto descodificava um recurso multimédia.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Tem de iniciar sessão nesta rede antes de poder aceder à Internet.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Abrir página de início de sessão da rede
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Permissões para %S
permissions.remove.tooltip = Limpar esta permissão e perguntar novamente
permissions.fullscreen.promptCanceled = Pedidos de permissão pendentes cancelados: os pedidos de permissão não deveriam ser emitidos antes de entrar em ecrã completo de DOM.
permissions.fullscreen.fullScreenCanceled = Saída do ecrã completo de DOM: os pedidos de permissão não devem ser emitidos em ecrã completo de DOM.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bit
aboutDialog.architecture.thirtyTwoBit = 32-bit
midi.allow.label = Permitir
midi.allow.accesskey = P
midi.block.label = Bloquear
midi.block.accesskey = B
midi.remember = Memorizar esta decisão
midi.shareWithFile = Permitir que este ficheiro local aceda aos seus dispositivos MIDI?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Permitir que %S aceda aos seus dispositivos MIDI?
midi.shareSysexWithFile = Permitir que este ficheiro local aceda aos seus dispositivos MIDI e envie/receba mensagens SysEx?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Permitir que %S aceda aos seus dispositivos MIDI e envie/receba mensagens SysEx?
serial.allow.label = Permitir
serial.allow.accesskey = P
serial.block.label = Bloquear
serial.block.accesskey = B
serial.shareWithFile = Permitir que este ficheiro local aceda às suas portas de série?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Permitir que %S aceda às suas portas de série?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Anterior
storageAccess1.Allow.label = Permitir
storageAccess1.Allow.accesskey = P
storageAccess1.DontAllow.label = Bloquear
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Permitir que %1$S utilize os seus cookies em %2$S?
storageAccess1.hintText = Pode bloquear o acesso se não for claro porque %1$S precisa destes dados.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Pesquisar na Internet por “%S”
