# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Час очікування минув
openFile = Відкрити файл
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Шукати “%2$S” з %1$S
contextMenuSearch.accesskey = Ш
contextMenuPrivateSearch = Пошук у приватному вікні
contextMenuPrivateSearch.accesskey = П
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Пошук з %S у приватному вікні
contextMenuPrivateSearchOtherEngine.accesskey = ш
bookmarkAllTabsDefault = [Назва теки]
unsignedAddonsDisabled.message = Неможливо перевірити один або більше встановлених додатків, тому їх було вимкнено.
unsignedAddonsDisabled.learnMore.label = Докладніше
unsignedAddonsDisabled.learnMore.accesskey = к
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Останній доступ %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = %S:// посилання
crashedpluginsMessage.title = Плагін %S аварійно завершив роботу.
crashedpluginsMessage.reloadButton.label = Перезавантажити сторінку
crashedpluginsMessage.reloadButton.accesskey = П
crashedpluginsMessage.submitButton.label = Надіслати звіт про цей збій
crashedpluginsMessage.submitButton.accesskey = з
crashedpluginsMessage.learnMore = Докладніше…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Можливо, ви хотіли перейти на %S?
keywordURIFixup.goTo = Так, перейти на %S
keywordURIFixup.goTo.accesskey = Т
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Оновити до %S
update.downloadAndInstallButton.accesskey = О
menuOpenAllInTabs.label = Відкрити всі у вкладках
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Перезавантажити цю сторінку
tabHistory.goBack = Повернутись на цю сторінку
tabHistory.goForward = Перейти на цю сторінку
# URL Bar
pasteAndGo.label = Вставити і перейти
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Оновити поточну сторінку (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Зупинити завантаження сторінки (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Відновити масштаб (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Перемкнути режим читання (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, скинути масштаб
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Показати закладки (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Показати стан поточних завантажень (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Відкрити нове вікно (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Відкрити нову вкладку (%S)
newTabContainer.tooltip = Відкрити нову вкладку (%S)\nНатисніть і утримуйте, щоб відкрити нову вкладку в контейнері
newTabAlwaysContainer.tooltip = Оберіть контейнер, щоб відкрити нову вкладку
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Дозволити %S використовувати ваші дані canvas-зображення HTML5?
canvas.siteprompt2.warning = Це може бути використано для унікальної ідентифікації вашого комп'ютера.
canvas.block = Блокувати
canvas.block.accesskey = Б
canvas.allow2 = Дозволити
canvas.allow2.accesskey = з
canvas.remember2 = Запам'ятати це рішення
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Засвідчено: %S
identity.identified.verified_by_you = Ви додали виняток безпеки для цього сайту.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Сертифікат виданий: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Не захищено
identity.notSecure.tooltip = З'єднання не захищене
identity.extension.label = Розширення (%S)
identity.extension.tooltip = Завантажено розширенням: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Зменшити (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Скинути масштаб (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Збільшити (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Вирізати (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Копіювати (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Вставити (%S)
geolocation.allow = Дозволити
geolocation.allow.accesskey = з
geolocation.block = Блокувати
geolocation.block.accesskey = Б
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Ця дія відкриє системні налаштування розташування. Надайте для %S дозвіл на доступ до розташування.
geolocation.shareWithSite4 = Дозволити %S доступ до вашого розташування?
geolocation.shareWithFile4 = Дозволити цьому локальному файлу доступ до вашого розташування?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Дозволити %1$S надати для %2$S доступ до вашого розташування?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Дозволити %S доступ до розташування в системних налаштуваннях.
geolocation.systemSettingsTitle = Очікується дозвіл на доступ до розташування
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Система запитає вас про надання цього дозволу для %S.
geolocation.remember = Запам'ятати це рішення
# Virtual Reality Device UI
xr.allow2 = Дозволити
xr.allow2.accesskey = з
xr.block = Блокувати
xr.block.accesskey = Б
xr.shareWithSite4 = Дозволити %S доступ до пристроїв віртуальної реальності? Це може викрити вразливу інформацію.
xr.shareWithFile4 = Дозволити цьому локальному файлу доступ до пристроїв віртуальної реальності? Це може викрити вразливу інформацію.
xr.remember = Запам'ятати це рішення
# Persistent storage UI
persistentStorage.allow = Дозволити
persistentStorage.allow.accesskey = в
persistentStorage.block.label = Блокувати
persistentStorage.block.accesskey = Б
persistentStorage.allowWithSite2 = Дозволити %S зберігати дані у постійному сховищі?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Дозволити
webNotifications.allow2.accesskey = з
webNotifications.notNow = Не зараз
webNotifications.notNow.accesskey = Н
webNotifications.never = Ніколи не дозволяти
webNotifications.never.accesskey = к
webNotifications.alwaysBlock = Завжди блокувати
webNotifications.alwaysBlock.accesskey = ж
webNotifications.block = Блокувати
webNotifications.block.accesskey = Б
webNotifications.receiveFromSite3 = Дозволити %S надсилати сповіщення?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S хоче отримати доступ до інших програм і служб на цьому пристрої.
localhost.remember2 = Запам'ятати мій вибір для цього сайту
localhost.allowlabel = Дозволити
localhost.blocklabel = Блокувати
localhost.allow.accesskey = о
localhost.block.accesskey = л
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S хоче отримати доступ до програм і служб на пристроях, під'єднаних до вашої локальної мережі.
localNetwork.remember2 = Запам'ятати мій вибір для цього сайту
localNetwork.allowLabel = Дозволити
localNetwork.allow.accesskey = З
localNetwork.blockLabel = Блокувати
localNetwork.block.accesskey = Б
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Заберіть мене звідси!
safebrowsing.getMeOutOfHereButton.accessKey = з
safebrowsing.deceptiveSite = Шахрайський сайт!
safebrowsing.notADeceptiveSiteButton.label = Це не шахрайський сайт…
safebrowsing.notADeceptiveSiteButton.accessKey = н
safebrowsing.reportedAttackSite = Відомий сайт-нападник!
safebrowsing.notAnAttackButton.label = Цей сайт не нападник…
safebrowsing.notAnAttackButton.accessKey = н
safebrowsing.reportedUnwantedSite = Відомий сайт з небажаним програмним забезпеченням!
safebrowsing.reportedHarmfulSite = Відомий небезпечний сайт!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Шукати %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Перезапустити %S у режимі усунення проблем?
troubleshootModeRestartPromptMessage = Ваші розширення, теми та власні налаштування будуть тимчасово вимкнені.
troubleshootModeRestartButton = Перезапустити
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Ця сторінка сповільнює %1$S. Щоб пришвидшити роботу браузера, зупиніть цю сторінку.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Вебсторінка сповільнює %1$S. Щоб пришвидшити роботу браузера, зупиніть цю сторінку.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = “%1$S” сповільнює %2$S. Щоб пришвидшити роботу браузера, зупиніть цю сторінку.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = “%1$S” сповільнює %2$S. Щоб пришвидшити роботу браузера, зупиніть це розширення.
processHang.add-on.learn-more.text = Докладніше
processHang.button_stop2.label = Зупинити
processHang.button_stop2.accessKey = З
processHang.button_debug.label = Налагодити скрипт
processHang.button_debug.accessKey = Н
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Показати вікно на весь екран (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Перемістити бічну панель вліво
sidebar.moveToRight = Перемістити бічну панель вправо
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Для відтворення аудіо чи відео на цій сторінці вам потрібно увімкнути DRM.
emeNotifications.drmContentDisabled.button.label = Активувати DRM
emeNotifications.drmContentDisabled.button.accesskey = А
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S встановлює компоненти, необхідні для відтворення аудіо чи відео на цій сторінці. Будь ласка, спробуйте знову пізніше.
emeNotifications.unknownDRMSoftware = Невідомо
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Пристосування %S
decoder.noCodecs.button = Навчитися
decoder.noCodecs.accesskey = Н
decoder.noCodecsLinux.message = Для відтворення відео, можливо, доведеться встановити необхідні відео-кодеки.
decoder.noHWAcceleration.message = Для поліпшення якості відео, можливо, доведеться встановити Media Feature Pack від Microsoft.
decoder.noPulseAudio.message = Для відтворення аудіо, можливо, доведеться встановити програмне забезпечення PulseAudio.
decoder.unsupportedLibavcodec.message = libavcodec може бути вразливим або непідтримуваним, тому для відтворення відео його необхідно оновити.
decoder.decodeError.message = При декодуванні джерела медіа сталась помилка.
decoder.decodeError.button = Проблема з сайтом
decoder.decodeError.accesskey = П
decoder.decodeWarning.message = При декодуванні джерела медіа сталась помилка, яку можливо виправити.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Перш ніж отримати доступ до інтернету, ви маєте ввійти в цю мережу.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Відкрити сторінку входу в мережу
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Дозволи для %S
permissions.remove.tooltip = Стерти цей дозвіл і запитувати знову
permissions.fullscreen.promptCanceled = Запити очікування дозволів скасовано: запити дозволів не повинні видаватися перед входом у повноекранний режим DOM.
permissions.fullscreen.fullScreenCanceled = Повноекранний режим DOM завершено: запити дозволів не повинні видаватися під час повноекранного режиму DOM.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-біт
aboutDialog.architecture.thirtyTwoBit = 32-біт
midi.allow.label = Дозволити
midi.allow.accesskey = з
midi.block.label = Блокувати
midi.block.accesskey = Б
midi.remember = Запам'ятати це рішення
midi.shareWithFile = Дозволити цьому локальному файлу доступ до ваших MIDI пристроїв?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Дозволити %S доступ до ваших MIDI пристроїв?
midi.shareSysexWithFile = Дозволити цьому локальному файлу доступ до ваших MIDI пристроїв та надсилати/отримувати SysEx повідомлення?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Дозволити %S доступ до ваших MIDI пристроїв та надсилати/отримувати SysEx повідомлення?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Назад
storageAccess1.Allow.label = Дозволити
storageAccess1.Allow.accesskey = з
storageAccess1.DontAllow.label = Блокувати
storageAccess1.DontAllow.accesskey = к
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Дозволити %1$S використовувати свої файли cookie на %2$S?
storageAccess1.hintText = Ви можете заблокувати доступ, якщо вам незрозуміло, нащо %1$S потребує ці дані.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Шукати в Інтернеті “%S”
