#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
# #define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Joe Solon</em:contributor> <em:contributor>Suzy Solon</em:contributor>

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>ജോയ്സി കെ ബാബു</em:contributor> <em:contributor>അനി പീറ്റര്‍</em:contributor><em:contributor>അനൂപ് പി</em:contributor><em:contributor>ഹരിവിഷ്ണു വി എന്‍</em:contributor>
#unfilter emptyLines
