#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.am

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Robert Sargsyan</em:contributor><em:contributor>Armen Zambrano Gasparnian</em:contributor><em:contributor>Vahe Khachikyan</em:contributor>

#unfilter emptyLines
