#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Amanpreet Singh Alam</em:contributor> <em:contributor>Punjabi Open Source Team</em:contributor> <em:contributor>http://www.satluj.com</em:contributor>
#unfilter emptyLines
