# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-title-reminder = Mementouri
dateformat-label =
    .value = Formatul datei:
    .accesskey = d
#   $date (String) - the formatted example date
dateformat-long =
    .label = Lung: { $date }
#   $date (String) - the formatted example date
dateformat-short =
    .label = Scurt: { $date }
timezone-label =
    .value = Fus orar:
weekstart-label =
    .value = Săptămâna începe:
    .accesskey = S
day-5-name =
    .label = Joi
workdays-label =
    .value = Zilele săptămânii lucrătoare:
dayweek-legend = Vizualizarea zi și săptămână
visible-hours-end-label =
    .value = ore odată
day-start-label =
    .value = Ziua începe la:
    .accesskey = Z
day-end-label =
    .value = Ziua se termină la:
    .accesskey = s
midnight-label =
    .label = Miezul nopții
noon-label =
    .label = Amiază
multiweek-legend = Vizualizarea mai multor săptămâni
week-0-label =
    .label = niciuna
week-1-label =
    .label = 1 săptămână
week-2-label =
    .label = 2 săptămâni
week-3-label =
    .label = 3 săptămâni
week-4-label =
    .label = 4 săptămâni
week-5-label =
    .label = 5 săptămâni
week-6-label =
    .label = 6 săptămâni
todaypane-legend = Panoul zilei de azi
default-length-label =
    .value = Durata implicită a unui eveniment și sarcini:
    .accesskey = E
task-start-1-label =
    .label = Niciuna
task-start-2-label =
    .label = Începutul zilei
task-start-3-label =
    .label = Ziua de finalizat
task-start-4-label =
    .label = Mâine
task-start-5-label =
    .label = Săptămâna viitoare
task-start-6-label =
    .label = Relativ față de ora actuală
task-start-7-label =
    .label = Relativ față de pornire
accessibility-legend = Accesibilitate
accessibility-colors-label =
    .label = Optimizează culorile pentru accesibilitate
    .accesskey = O
reminder-legend = Când pornește un memento:
reminder-play-checkbox =
    .label = Redă un sunet
    .accesskey = s
reminder-play-alarm-button =
    .label = Redă
    .accesskey = P
reminder-default-sound-label =
    .label = Folosește sunetul implicit
    .accesskey = d
reminder-browse-sound-label =
    .label = Răsfoiește…
    .accesskey = B
reminder-dialog-label =
    .label = Afișează caseta de dialog pentru memento
    .accesskey = x
missed-reminder-label =
    .label = Afișează mementouri ratate pentru calendarele cu drept de scriere
    .accesskey = m
reminder-default-legend = Setări implicite pentru mementouri
event-alarm-label =
    .value = Setarea implicită a mementoului pentru evenimente:
    .accesskey = e
alarm-on-label =
    .label = Activată
alarm-off-label =
    .label = Dezactivată
task-alarm-label =
    .value = Setarea implicită a mementoului pentru sarcini:
    .accesskey = a
event-alarm-time-label =
    .value = Cu cât timp înainte pornește mementoul pentru un eveniment:
    .accesskey = u
task-alarm-time-label =
    .value = Cu cât timp înainte pornește mementoul pentru o sarcină:
    .accesskey = o
category-edit-label = Editare categorie
category-overwrite-title = Avertisment: nume duplicat
