# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=Εγκατάσταση του $ProductName$
Welcome_MessageWelcome=%s
Welcome_Message0=Είστε έτοιμοι να εγκαταστήσετε τον %s $Version$.
Welcome_Message1=Είναι καλύτερο να κλείσετε όλα τα προγράμματα που εκτελούνται πριν να προχωρήσετε στην εγκατάσταση.
Welcome_Message2=Πατήστε Άκυρο για να σταματήσετε την εγκατάσταση και να κλείσετε τα προγράμματα που εκτελούνται. Πατήστε Επόμενο για να συνεχίσετε με την εγκατάσταση.
Welcome_Message3=Πατήστε Επόμενο για να συνεχίσετε με την εγκατάσταση του %s $Version$.

License_Title=Άδεια χρήσης λογισμικού
License_SubTitle=Όροι και συνθήκες χρήσης του λογισμικού.
License_Message0=Παρακαλώ διαβάστε την ακόλουθη άδεια χρήσης. Χρησιμοποιήστε την μπάρα κύλισης για να διαβάσετε παρακάτω.
License_Accept=Αποδέχομαι τους όρους της άδειας χρήσης
License_Decline=ΔΕΝ αποδέχομαι τους όρους της άδειας χρήσης

Type_Title=Τύπος εγκατάστασης
Type_SubTitle=Επιλογές εγκατάστασης.
Type_Message0= Επιλέξτε τον τύπο της εγκατάστασης που επιθυμείτε, και πατήστε Επόμενο.

Standard_Short=&Κανονική
Standard_Long=Η εφαρμογή θα εγκατασταθεί με τις πιο κοινές επιλογές.

Custom_Short=&Προσαρμοσμένη
Custom_Long=Μπορείτε να επιλέξετε μεμονωμένα στοιχεία για εγκατάσταση. Για προχωρημένους χρήστες.

Select_Title=Επιλογή στοιχείων
Select_SubTitle=Πρόσθετα στοιχεία που εμπλουτίζουν τον $ProductName$.
Select_Message0=Επιλέξτε τα πρόσθετα στοιχεία που θέλετε να εγκατασταθούν, και πατήστε Επόμενο.

Path_Title=Φάκελος εγκατάστασης
Path_SubTitle=Εκεί που θα εγκατασταθεί ο $ProductName$.
Path_Message0=Ο $ProductName$ θα εγκατασταθεί στον ακόλουθο φάκελο:

Integration_Title=Ορισμός συντομεύσεων
Integration_SubTitle=Δημιουργεί εικονίδια προγράμματος
Integration_Message0=Δημιουργία εικονιδίων για τον $ProductShortName$:

Integration_Desktop=Στην επιφάνεια εργασίας μου
Integration_StartMenu=Στο φάκελο Προγραμμάτων του μενού εκκίνησης
Integration_QuickLaunch=Στην μπάρα γρήγορης εκκίνησης

SelectFolder_Title=Εγκατάσταση $ProductName$  - Επιλογή φακέλου προγράμματος
SelectFolder_Message0=Η εγκατάσταση θα προσθέσει εικονίδια προγράμματος στον παρακάτω φάκελο προγραμμάτων.  Μπορείτε να πληκτρολογήσετε ένα νέο όνομα φακέλου, ή να επιλέξετε ένα από τη λίστα με τους υπάρχοντες φακέλους.

Advanced_Title=Εγκατάσταση $ProductName$  - Προχωρημένες ρυθμίσεις
Advanced_Message0=Αν η σύνδεση σας στο διαδίκτυο απαιτεί ένα διαμεσολαβητή δικτύου, εισάγετε το όνομα και τις πληροφορίες θύρας.  Αν δεν απαιτείται διαμεσολαβητής δικτύου αγήστε τα πεδία κενά.

Install_Title= Περίληψη
Install_SubTitle= Όλα έτοιμα για την εγκατάσταση του $ProductName$.
Install_MessageInstall=Η εγκατάσταση θα εγκαταστήσει τα ακόλουθα στοιχεία:
Install_MessageDownload=Η εγκατάσταση θα λάβει και θα εγκαταστήσει τα ακόλουθα στοιχεία:
Install_Message0=Πατήστε Επόμενο για συνέχεια.

Downloading_Title=Λήψη
Downloading_SubTitle=Λήψη απαιτούμενων στοιχείων...
Downloading_Blurb=Η εγκατάσταση λαμβάνει τα απαιτούμενα αρχεία για την εγκατάσταση του $ProductName$.
Downloading_FileName=Τώρα γίνεται λήψη:
Downloading_Time=Χρόνος που απομένει:

Installing_Title=Γίνεται εγκατάσταση
Installing_SubTitle=Γίνεται εγκατάσταση του $ProductName$...
Installing_Blurb=Εγκαθίστανται αρχεία προγράμματος 
Installing_Status=Προετοιμασία αρχείου:
Installing_Component=Τώρα γίνεται εγκατάσταση:

Success_Title=Η εγκατάσταση ολοκληρώθηκε
Success_Header=Η εγκατάσταση ολοκληρώθηκε
Success_Message0=Ο %s $Version$  εγκαταστάθηκε επιτυχώς.
Success_Message1=Πατήστε τέλος για να ολοκληρωθεί η εγκατάσταση. 
Success_Launch=Εκκίνηση %s $Version$ τώρα.

Check_Message=Η λήψη του $ProductName$ ήταν επιτυχής. Ο $ProductNameInternal$ τώρα πρέπει να κλείσει για να συνεχιστεί η εγκατάσταση. Πατήστε OK για να βγείτε από τον$ProductNameInternal$ και να αρχίσει αυτόματα η εγκατάσταση.
Check_FullMessage=Ο $ProductNameInternal$  πρέπει να κλείσει τώρα πρέπει να κλείσει για να συνεχιστεί η εγκατάσταση. Πατήστε OK για να βγείτε από τον$ProductNameInternal$ και να αρχίσει αυτόματα η εγκατάσταση.
Check_Wait=Ο $ProductNameInternal$ τερματίζεται.  Παρακαλώ περιμένετε...

Component_XPCOM=Cross Platform COM
Component_Mail=$ProductName$
Component_Offline=Υποστήριξη εργασίας χωρίς σύνδεση
Component_Offline_Long=Προσθέτει υποστήριξη εργασίας χωρίς συνδεση στον $ProductName$.
Component_RSS=Υποστήριξη RSS 
Component_RSS_Long=Προσθέτει υποστήριξη RSS στον $ProductName$.
Component_QFA=Quality Feedback Agent
Component_QFA_Long=για αναφορά προβλημάτων του  $ProductName$
