# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = פרטי כניסה שמורים
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = העתקת כתובת
    .accesskey = ע
launch-site-url-cmd =
    .label = ביקור בכתובת
    .accesskey = ב
copy-username-cmd =
    .label = העתקת שם משתמש
    .accesskey = ש
edit-username-cmd =
    .label = עריכת שם המשתמש
    .accesskey = ר
copy-password-cmd =
    .label = העתקת ססמה
    .accesskey = ה
edit-password-cmd =
    .label = עריכת הססמה
    .accesskey = ע
search-filter =
    .accesskey = ח
    .placeholder = חיפוש
column-heading-site =
    .label = אתר
column-heading-username =
    .label = שם משתמש
column-heading-password =
    .label = ססמה
column-heading-time-created =
    .label = שימוש ראשון
column-heading-time-last-used =
    .label = שימוש אחרון
column-heading-time-password-changed =
    .label = שינוי אחרון
column-heading-times-used =
    .label = כמות שימושים
remove =
    .label = הסרה
    .accesskey = ה
import =
    .label = ייבוא…
    .accesskey = ב
close-button =
    .label = סגירה
    .accesskey = ס
show-passwords =
    .label = הצגת ססמאות
    .accesskey = צ
hide-passwords =
    .label = הסתרת ססמאות
    .accesskey = ה
logins-description-all = במחשב שלך נשמרו פרטי הכניסה לאתרים הבאים
logins-description-filtered = פרטי ההתחברות הבאים תואמים לחיפוש שלך:
remove-all =
    .label = הסרת הכל
    .accesskey = כ
remove-all-shown =
    .label = הסרת כל הפריטים המוצגים
    .accesskey = כ
remove-all-passwords-prompt = האם ברצונך למחוק את כל הססמאות?
remove-all-passwords-title = הסרת כל הססמאות
no-master-password-prompt = האם ברצונך להציג את הססמאות שלך?
auto-fill-logins-and-passwords =
    .label = מילוי אוטומטי של כניסות וססמאות
