# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

appmenu-update-available2 =
    .buttonlabel = I-download
    .buttonaccesskey = D
    .label = Mayroong update
    .secondarybuttonlabel = Alisin
    .secondarybuttonaccesskey = l
appmenu-update-available-message2 = I-download ang pinakabagong bersyon ng { -brand-shorter-name }.
appmenu-update-manual2 =
    .buttonlabel = I-download
    .buttonaccesskey = D
    .label = Mayroong update
    .secondarybuttonlabel = Alisin
    .secondarybuttonaccesskey = l
appmenu-update-manual-message2 = Hindi makapag-update ang { -brand-shorter-name } nang automatiko. I-download ang bagong bersyon - hindi mawawala sa iyo ang nai-save mong impormasyon o mga customization.
appmenu-update-unsupported2 =
    .buttonlabel = Alamin pa
    .buttonaccesskey = L
    .label = Hindi makapag-update
    .secondarybuttonlabel = Alisin
    .secondarybuttonaccesskey = l
appmenu-update-unsupported-message2 = Ang iyong operating system ay hindi tugma sa pinakabagong bersyon ng { -brand-shorter-name }.
appmenu-update-restart2 =
    .buttonlabel = I-update at mag-restart
    .buttonaccesskey = U
    .label = Mayroong update
    .secondarybuttonlabel = Alisin
    .secondarybuttonaccesskey = l
appmenu-update-restart-message2 = Kunin ang pinakabagong bersyon ng { -brand-shorter-name }. Ang mga bukas na tab at window ay maibabalik.
appmenu-update-other-instance =
    .buttonlabel = I-update ang { -brand-shorter-name } kahit papaano
    .buttonaccesskey = U
    .label = { -brand-shorter-name } ay hindi automatikong makapag-update sa pinakabagong bersyon.
    .secondarybuttonlabel = Hindi sa Ngayon
    .secondarybuttonaccesskey = N
appmenu-update-other-instance-message = Hindi makapag-install ng bagon update  sa	{ -brand-shorter-name } dahil may isa pang kopya ng	{ -brand-shorter-name } na tumatakbo. Maaaring pakisara ito upang makapagpatuloy ang pag-update or piliting mag-update pa rin (ang isa pang kopya ay maaaring hindi gumana ng maayos hanggang ito ay i-restart).
appmenu-addon-post-install-message3 = Pamahalaan ang iyong mga add-on at tema sa pamamagitan ng application menu.
appmenu-new-tab-controlled-changes =
    .buttonlabel = Panatilihin ang mga Pagbabago
    .buttonaccesskey = K
    .label = Nagbago ang iyong new tab.
    .secondarybuttonlabel = I-manage ang New Tabs
    .secondarybuttonaccesskey = M
appmenu-homepage-controlled-changes =
    .buttonlabel = Panatilihin ang Pagbabago
    .buttonaccesskey = K
    .label = Ang iyong homepage ay nagbago.
    .secondarybuttonlabel = I-manage ang Homepage
    .secondarybuttonaccesskey = M
appmenu-tab-hide-controlled =
    .buttonlabel = Panatilihing nakatago ang mga Tab
    .buttonaccesskey = K
    .label = Puntahan ang mga Nakatagong Tab
    .secondarybuttonlabel = Disable Extension
    .secondarybuttonaccesskey = D
