# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

print-setup =
    .title = बिलाइनि सेटआप
custom-prompt-title = कास्टम...
custom-prompt-prompt = नोंथांनि कासटम हेडार/फुटार फराय बिजाबखौ हाबहो
basic-tab =
    .label = फरमेट आरो उफ्रा
advanced-tab =
    .label = रुगुं आरो हेडार/फुटार
format-group-label =
    .value = फरमेट
orientation-label =
    .value = अरियेन्टेसन:
portrait =
    .label = प'र्ट्रेट
    .accesskey = P
landscape =
    .label = लेण्डस्केप
    .accesskey = L
scale =
    .label = स्केल:
    .accesskey = S
scale-percent =
    .value = %
shrink-to-fit =
    .label = बिलाइनि गुवारखौ गोरोब होनो थन्थ्र हो
    .accesskey = W
options-group-label =
    .value = उफ्राफोर
print-bg =
    .label = सावगारिनि उनथिं थानाय (गाब आरो मुसुखा)खौ साफाय
    .accesskey = B
margin-group-label-inches =
    .value = रुगुंफोर (इनसि)
margin-group-label-metric =
    .value = रुगुंफोर (मिलिमिटार)
margin-top =
    .value = गोजौ:
    .accesskey = T
margin-top-invisible =
    .value = गोजौ:
margin-bottom =
    .value = गाहाय:
    .accesskey = B
margin-bottom-invisible =
    .value = गाहाय:
margin-left =
    .value = आगसि:
    .accesskey = L
margin-left-invisible =
    .value = आगसि:
margin-right =
    .value = आगदा:
    .accesskey = R
margin-right-invisible =
    .value = आगदा:
header-footer-label =
    .value = हेडार आरो फुटार
hf-left-label =
    .value = आगसि:
hf-center-label =
    .value = मिरु:
hf-right-label =
    .value = आगदा:
header-left-tip =
    .tooltiptext = आगसि हेडार
header-center-tip =
    .tooltiptext = मिरु हेडार
header-right-tip =
    .tooltiptext = आगदा हेडार
footer-left-tip =
    .tooltiptext = आगसि फुटार
footer-center-tip =
    .tooltiptext = मिरु फुटार
footer-right-tip =
    .tooltiptext = आगदा फुटार
hf-blank =
    .label = --लांदां--
hf-title =
    .label = बिमुं
hf-url =
    .label = URL
hf-date-and-time =
    .label = अक्‍त'/सम
hf-page =
    .label = बिलाइ #
hf-page-and-total =
    .label = # नि # बिलाइ
hf-custom =
    .label = कास्टम...
print-preview-window =
    .title = साफायनाय गिबि नुथाय
print-title =
    .value = बिमुं:
print-preparing =
    .value = थियारि खालाम गासिनो दङ...
print-progress =
    .value = दावगानाय:
print-window =
    .title = साफाय गासिनो दङ
print-complete =
    .value = साफायनाय आबुं जाबाय।
# Variables
# $percent (integer) - Number of printed percentage
print-percent =
    .value = { $percent }%
dialog-cancel-label = नेवसि
dialog-close-label = बन्द खालाम
