# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Noildzis
openFile = Atvērt datni
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Meklēt “%2$S” ar %1$S
contextMenuSearch.accesskey = M
contextMenuPrivateSearch = Meklēt privātajā logā
contextMenuPrivateSearch.accesskey = h
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Meklēt ar %S privātajā logā
contextMenuPrivateSearchOtherEngine.accesskey = h
bookmarkAllTabsDefault = [Mapes nosaukums]
unsignedAddonsDisabled.message = Vienu vai vairākus no uzstādītajiem papildinājumiem nevar apliecināt, un tie tika atspējoti.
unsignedAddonsDisabled.learnMore.label = Uzzināt vairāk
unsignedAddonsDisabled.learnMore.accesskey = U
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Pēdējā piekļuve %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = %S:// saites
crashedpluginsMessage.title = Spraudnis %S ir avarējis.
crashedpluginsMessage.reloadButton.label = Pārlādēt lapu
crashedpluginsMessage.reloadButton.accesskey = r
crashedpluginsMessage.submitButton.label = Nosūtīt avārijas ziņojumu
crashedpluginsMessage.submitButton.accesskey = s
crashedpluginsMessage.learnMore = Uzzināt vairāk…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Vai Jūs vēlējāties iet uz %S?
keywordURIFixup.goTo = Jā, vediet mani uz %S
keywordURIFixup.goTo.accesskey = J
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Atjaunināt uz %S
update.downloadAndInstallButton.accesskey = u
menuOpenAllInTabs.label = Atvērt visu cilnēs
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Pārlādēt šo lapu
tabHistory.goBack = Atgriezties šajā lapā
tabHistory.goForward = Doties uz priekšu uz šo lapu
# URL Bar
pasteAndGo.label = Ievietot un atvērt
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Pārlādēt pašreizējo lapu (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Apturēt šīs lapas (%S) ielādi
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Atjaunot noklusēto pietuvinājumu (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Pārslēgt lasītāja skatu (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, atiestatīt mērogu
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Parādīt visas grāmatzīmes (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Parādīt lejupielāžu progresu (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Atvērt jaunu logu (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Atvērt jaunu cilni (%S)
newTabContainer.tooltip = Atvērt jaunu cilni (%S)\nSpiest un turēt, lai atvērtu jaunu konteinera cilni
newTabAlwaysContainer.tooltip = Atlasiet konteineru, lai atvērtu jaunu cilni
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Atļaut %S izmantot HTML5 pamatnes attēla datus?
canvas.siteprompt2.warning = To var izmantot, lai identificētu tieši Tavu datoru.
canvas.block = Liegt
canvas.block.accesskey = B
canvas.allow2 = Atļaut
canvas.allow2.accesskey = A
canvas.remember2 = Atcerēties šo izvēli
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Apliecināja: %S
identity.identified.verified_by_you = Jūs esat pievienojis drošības izņēmumu šai lapai
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Sertifikāts izsniegts: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Nav droša
identity.notSecure.tooltip = Savienojums nav drošs
identity.extension.label = Paplašinājums (%S)
identity.extension.tooltip = Ielādēts ar paplašinājumu: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Attālināt (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Atjaunot noklusēto pietuvinājumu (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Pietuvināt (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Izgriezt (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Kopēt (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Ielīmēt (%S)
geolocation.allow = Atļaut
geolocation.allow.accesskey = A
geolocation.block = Liegt
geolocation.block.accesskey = B
geolocation.shareWithSite4 = Vai atļaut %S piekļūt atrašanās vietai?
geolocation.shareWithFile4 = Vai atļaut šai vietējai datnei piekļūt atrašanās vietai?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Vai atļaut %1$S piešķirt %2$S atļauju piekļūt atrašanās vietai?
geolocation.remember = Atcerēties šo izvēli
# Virtual Reality Device UI
xr.allow2 = Atļaut
xr.allow2.accesskey = A
xr.block = Liegt
xr.block.accesskey = B
xr.shareWithSite4 = Vai atļaut %S piekļūt virtuālās realitātes ierīcēm? Tas var atklāt sensitīvu informāciju.
xr.shareWithFile4 = Vai atļaut šai lokālajai datnei piekļūt virtuālās realitātes ierīcēm? Tas var atklāt sensitīvu informāciju.
xr.remember = Atcerēties šo izvēli
# Persistent storage UI
persistentStorage.allow = Atļaut
persistentStorage.allow.accesskey = A
persistentStorage.block.label = Liegt
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Atļaut %S glabāt datus pastāvīgajā krātuvē?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Atļaut
webNotifications.allow2.accesskey = A
webNotifications.notNow = Ne tagad
webNotifications.notNow.accesskey = n
webNotifications.never = Neatļaut nekad
webNotifications.never.accesskey = e
webNotifications.alwaysBlock = Vienmēr liegt
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = Liegt
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Atļaut %S sūtīt paziņojumus?
localhost.remember2 = Atcerēties manu izvēli šai vietnei
localhost.allowlabel = Atļaut
localhost.blocklabel = Liegt
localNetwork.remember2 = Atcerēties manu izvēli šai vietnei
localNetwork.allowLabel = Atļaut
localNetwork.blockLabel = Liegt
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Vediet mani prom no šejienes!
safebrowsing.getMeOutOfHereButton.accessKey = V
safebrowsing.deceptiveSite = Maldinoša lapa!
safebrowsing.notADeceptiveSiteButton.label = Šī nav maldinoša lapa…
safebrowsing.notADeceptiveSiteButton.accessKey = d
safebrowsing.reportedAttackSite = Kaitnieku lapa!
safebrowsing.notAnAttackButton.label = Šī lapa neveic uzbrukumus…
safebrowsing.notAnAttackButton.accessKey = a
safebrowsing.reportedUnwantedSite = Bīstama nevēlamas programmatūras lapa!
safebrowsing.reportedHarmfulSite = Ziņoja par kaitīgu lapu!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Meklēt %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Vai pārstartēt %S problēmu novēršanas režīmā?
troubleshootModeRestartPromptMessage = Jūsu paplašinājumi, motīvi un pielāgotie iestatījumi tiks uz laiku izslēgti.
troubleshootModeRestartButton = Pārstartēt
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Šī lapa palēnina %1$S. Lai paātrinātu pārlūku, šī lapa ir jāaptur.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Tīmekļa lapas darbība palēnina %1$S. Lai paātrinātu pārlūku, šī lapa ir jāaptur.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = “%1$S” palēnina %2$S. Lai paātrinātu pārlūku, šī lapa ir jāaptur.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = “%1$S” palēnina %2$S. Lai paātrinātu pārlūku, šis paplašinājums ir jāaptur.
processHang.add-on.learn-more.text = Uzzināt vairāk
processHang.button_stop2.label = Apturēt
processHang.button_stop2.accessKey = A
processHang.button_debug.label = Atkļūdot skriptu
processHang.button_debug.accessKey = d
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Parādīt logu pa visu ekrānu (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Pārvietot sānu joslu pa kreisi
sidebar.moveToRight = Pārvietot sānu joslu pa labi
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Jāiespējo DRM, lai šajā lapā atskaņotu kādu skaņu ierakstu vai video.
emeNotifications.drmContentDisabled.button.label = Iespējot DRM
emeNotifications.drmContentDisabled.button.accesskey = A
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S uzstāda sastāvdaļas, kas ir nepieciešamas skaņas vai video atskaņošanai šajā lapā. Lūgums vēlāk mēģināt vēlreiz.
emeNotifications.unknownDRMSoftware = Nezināms
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Pielāgot %S
decoder.noCodecs.button = Uzziniet kā
decoder.noCodecs.accesskey = L
decoder.noCodecsLinux.message = Lai atskaņotu video, varētu būt nepieciešams uzstādīt nepieciešamos video saspiedatspiedējus.
decoder.noHWAcceleration.message = Lai uzlabotu video kvalitāti, varētu būt nepieciešams uzstādīt Microsoft Media Feature Pack.
decoder.noPulseAudio.message = Lai atskaņotu audio, jums var vajadzēt instalēt nepieciešamo PulseAudio programmatūru.
decoder.unsupportedLibavcodec.message = libavcodec var būt nedrošs vai nav atbalstīts, to vajadzētu atjaunināt, lai atskaņotu video.
decoder.decodeError.message = Atkodējot mēdiju resursu notikusi kļūda.
decoder.decodeError.button = Ziņot par problēmu ar lapu
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = Atkodējot mēdiju resursu notikusi apejama kļūda.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Vispirms šajā tīklā jāpiesakās, lai varētu piekļūt internetam.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Atvērt tīkla pieteikšanās lapu
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = %S atļaujas
permissions.remove.tooltip = Notīrīt šo atļauju un jautāt vēlreiz
permissions.fullscreen.promptCanceled = Atcelti neapstiprinātie atļauju pieprasījumi: atļauju pieprasījumus nevajadzētu izsniegt, pirms tiek atvērts DOM pilnekrāna režīms.
permissions.fullscreen.fullScreenCanceled = Iziets no DOM pilnekrāna: atļauju pieprasījumus nedrīkst izsniegt, kamēr ir DOM pilnekrāna režīms.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bitu
aboutDialog.architecture.thirtyTwoBit = 32-bitu
midi.allow.label = Atļaut
midi.allow.accesskey = A
midi.block.label = Liegt
midi.block.accesskey = B
midi.remember = Atcerēties šo izvēli
midi.shareWithFile = Vai atļaut šai lokālajai datnei piekļūt jūsu MIDI ierīcēm?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Vai atļaut %S piekļūt jūsu MIDI ierīcēm?
midi.shareSysexWithFile = Atļaut šai vietējai datnei piekļūt MIDI ierīcēm un nosūtīt/saņemt SysEx ziņojumus?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Atļaut %S piekļūt MIDI ierīcēm un nosūtīt/saņemt SysEx ziņojumus?
serial.allow.label = Atļaut
serial.block.label = Liegt
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Atpakaļ
storageAccess1.Allow.label = Atļaut
storageAccess1.Allow.accesskey = A
storageAccess1.DontAllow.label = Liegt
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Vai atļaut %1$S izmantot savas sīkdatnes vietnē %2$S?
storageAccess1.hintText = Iespējams, vēlēsities bloķēt piekļuvi, ja nav skaidrs, kāpēc %1$S ir nepieciešami šie dati.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Tīmeklī meklēt “%S”
