# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

print-setup =
    .title = Sivun asetukset
custom-prompt-title = Oma…
custom-prompt-prompt = Kirjoita oma ylä-/alatunniste
basic-tab =
    .label = Muoto ja valinnat
advanced-tab =
    .label = Marginaalit ja ylä-/alatunnisteet
format-group-label =
    .value = Muoto
orientation-label =
    .value = Suunta:
scale-percent =
    .value = %
options-group-label =
    .value = Asetukset
margin-group-label-inches =
    .value = Marginaalit (tuumia)
margin-group-label-metric =
    .value = Marginaalit (millimetriä)
margin-top-invisible =
    .value = Ylä:
margin-bottom-invisible =
    .value = Ala:
margin-left-invisible =
    .value = Vasen:
margin-right-invisible =
    .value = Oikea:
header-footer-label =
    .value = Ylä- ja alatunnisteet
hf-left-label =
    .value = Vasen:
hf-center-label =
    .value = Keskellä:
hf-right-label =
    .value = Oikea:
header-left-tip =
    .tooltiptext = Vasen ylätunniste
header-center-tip =
    .tooltiptext = Keskimmäinen ylätunniste
header-right-tip =
    .tooltiptext = Oikea ylätunniste
footer-left-tip =
    .tooltiptext = Vasen alatunniste
footer-center-tip =
    .tooltiptext = Keskimmäinen alatunniste
footer-right-tip =
    .tooltiptext = Oikea alatunniste
hf-blank =
    .label = --tyhjä--
hf-title =
    .label = Otsikko
hf-url =
    .label = URL
hf-date-and-time =
    .label = Pvm/aika
hf-page =
    .label = Sivu #
hf-page-and-total =
    .label = Sivu #/#
hf-custom =
    .label = Oma…
print-preview-window =
    .title = Tulostuksen esikatselu
print-title =
    .value = Otsikko:
print-preparing =
    .value = Valmistellaan…
print-progress =
    .value = Edistyminen:
print-window =
    .title = Tulostetaan
print-complete =
    .value = Tulostus valmis.
# Variables
# $percent (integer) - Number of printed percentage
print-percent =
    .value = { $percent }%
dialog-cancel-label = Peruuta
dialog-close-label = Sulje
