# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Guarda-ho
dialogTitleAddBookmark = Adreça d'interés nova
dialogTitleAddMulti = Adreces d'interés noves
dialogTitleEdit = Propietats de «%S»
dialogTitleAddNewBookmark2 = Afig a les adreces d'interés
dialogTitleEditBookmark = Edita «%S»
dialogTitleEditBookmark2 = Edita l’adreça d’interés
dialogTitleAddBookmarkFolder = Afig una carpeta d'adreces d'interés
dialogTitleEditBookmarkFolder = Edita la carpeta d'adreces d'interés
bookmarkAllTabsDefault = [Nom de la carpeta]
newFolderDefault = Carpeta nova
newBookmarkDefault = Adreça d'interés nova
