# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host } को खोजी गरिँदैछ…
network-connection-status-connected = { $host } मा जडान भयो…
network-connection-status-sending-request = { $host } लाई अनुरोध पठाइदै…
network-connection-status-transferring-data = { $host } बाट तथ्याङ्क स्थानान्तर गरिँदैछ...
network-connection-status-connecting = { $host } मा जडान हुँदैछ…
network-connection-status-read = { $host } पढ्नुहोस्
network-connection-status-wrote = { $host } लेखियो
network-connection-status-waiting = { $host } लाई पर्खदै…
network-connection-status-looked-up = { $host } मा हेरियो …
network-connection-status-tls-handshake = { $host } सँग TLS ह्यान्डसेक गर्दै…
network-connection-status-tls-handshake-finished = { $host } को लागि TLS ह्यान्डसेक सकियो…
