# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# This is a multi-line message.
psmerr-hostreusedissuerandserial =
    Etibarsız bir sertifikat aldınız. Lütfən server idarəçisiylə əlaqə yaradın və ya qarşı tərəfə e-poçt ilə məlumat verin:
    
    Sertifikatınız, sertifikat orqanının verdiyi başqa bir sertifikat ilə eyni seriya nömrəsinə sahibdir. Lütfən təkrarsız bir seriya nömrəsi olan Sertifikat alın.
ssl-error-no-cypher-overlap = Qarşı tərəflə təhlükəsiz bağlantı qurulmadı: ortaq bir şifrələmə yolu yoxdur.
ssl-error-no-certificate = Təsdiqləmə üçün lazım olan təsdiq sənədi ya da açar tapılmadı.
ssl-error-bad-client = Server klientdə təhlükəli məlumatla qarşılaşdı.
ssl-error-bad-server = Klient serverdə təhlükəli məlumatla qarşılaşdı.
ssl-error-unsupported-certificate-type = Dəstəklənməyən təsdiq sənədi formatı.
ssl-error-unsupported-version = Qarşı tərəf dəstəklənməyən bir təhlükəsizlik protokolundan istifadə edir.
ssl-error-wrong-certificate = Klinet təsdiqləməsi uğursuz oldu: Açar bazasındakı şəxsi açar, təsdiq sənədi bazasındakı ümumi açarla uyğun gəlmir.
ssl-error-ssl2-disabled = Qarşı tərəf sadəcə, lokal olaraq söndürülmüş olan SSL 2 versiyasını dəstəkləyir.
ssl-error-bad-mac-read = SSL etibarsız bir qeyd aldı.
ssl-error-bad-mac-alert = SSL həmkarı, etibarsız bir məlumat təsdiqləmə kodunu bildirir.
ssl-error-bad-cert-alert = SSL həmkarı təsdiq sənədinizin doğruluğunu təsdiqləyə bilmir.
ssl-error-revoked-cert-alert = SSL həmkarı təsdiq sənədizi etibarsız olduğu üçün rədd etdi.
ssl-error-expired-cert-alert = SSL həmkarı təsdiq sənədinizi vaxtı bitdiyi üçün rədd etdi.
ssl-error-ssl-disabled = Bğlanıla bilmir: SSL söndürülüb.
ssl-error-fortezza-pqg = Bağlanıla bilmir: SSL digər bir FORTEZZA domen adındadır.
ssl-error-unknown-cipher-suite = Naməlum bir SSL şifrələmə dəsti tələb edildi.
ssl-error-no-ciphers-supported = Bu proqramda heç bir şifrələmə təsdqi yoxdur və ya aktiv deyil.
ssl-error-bad-block-padding = SSL səhv bir blok doldurulması olan bir qeyd aldı.
ssl-error-rx-record-too-long = SSL icazə verilən uzunluğu aşan bir qeyd aldı.
ssl-error-tx-record-too-long = SSL icazə verilən uzunluğu aşan bir qeyd göndərməyə cəhd etdi.
ssl-error-rx-malformed-hello-request = SSL xətalı bir qarşılama mesajı aldı.
ssl-error-rx-malformed-client-hello = SSL xətalı bir klient qarşılama mesajı aldı.
ssl-error-rx-malformed-server-hello = SSL xətalı bir server qarşılama mesajı aldı.
ssl-error-rx-malformed-certificate = SSL xətalı bir təsdiq sənədi qarşılama mesajı aldı.
ssl-error-rx-malformed-server-key-exch = SSL xətalı bir server açar dəyişikliyi mesajı aldı.
ssl-error-rx-malformed-cert-request = SSL xətalı bir təsdiq sənədi istəyi qarşılama mesajı aldı.
ssl-error-rx-malformed-hello-done = SSL xətalı bir server uğurludur qarşılama mesajı aldı.
ssl-error-rx-malformed-cert-verify = SSL xətalı bir təsdiq sənədi təsdiqləməsi qarşılama mesajı aldı.
ssl-error-rx-malformed-client-key-exch = SSL xətalı bir klient açar dəyişikliyi mesajı aldı.
ssl-error-rx-malformed-finished = SSL xətalı bir sonlandırma qarşılama mesajı aldı.
ssl-error-rx-malformed-change-cipher = SSL xətalı bir şifrələmə dəyişikliyi qeydi aldı.
ssl-error-rx-malformed-alert = SSL xətalı bir xəbədarlıq qeydi aldı.
ssl-error-rx-malformed-handshake = SSL xətalı bir qarşılama qeydi aldı.
ssl-error-rx-malformed-application-data = SSL xətalı bir proqram veriləni qeydi aldı.
ssl-error-rx-unexpected-hello-request = SSL gözlənilməyən bir qarşılam istəyi mesajı aldı.
ssl-error-rx-unexpected-client-hello = SSL gözlənilməyən bir klient qarşılama mesajı aldı.
ssl-error-rx-unexpected-server-hello = SSL gözlənilməyən bir server qarşılama mesajı aldı.
ssl-error-rx-unexpected-certificate = SSL gözlənilməyən bir təsdiq sənədi qarşılama mesajı aldı.
ssl-error-rx-unexpected-server-key-exch = SSL gözlənilməyən bir server açar dəyişikliyi qarşılama qeydi aldı.
ssl-error-rx-unexpected-cert-request = SSL gözlənilməyən bir təsdiq sənədi istəyi qarşılama mesajı aldı.
ssl-error-rx-unexpected-hello-done = SSL gözlənilməyən bir server uğurlu qarşılama mesajı aldı.
ssl-error-rx-unexpected-cert-verify = SSL gözlənilməyən bir təsdiq sənədi qarşılama mesajı aldı.
ssl-error-rx-unexpected-client-key-exch = SSL gözlənilməyən bir server açar dəyişikliyi qarşılama mesajı aldı.
ssl-error-rx-unexpected-finished = SSL gözlənilməyən bir bitiş qarşılama mesajı aldı.
ssl-error-rx-unexpected-change-cipher = SSL gözlənilməyən bir şifrələmə dəyişikliyi qeydi aldı.
ssl-error-rx-unexpected-alert = SSL gözlənilməyən bir xəbərdarlıq qeydi aldı.
ssl-error-rx-unexpected-handshake = SSL gözlənilməyən bir qarşılama mesajı aldı.
ssl-error-rx-unexpected-application-data = SSL gözlənilməyən bir proqram veriləni qeydi aldı.
ssl-error-rx-unknown-record-type = SSL naməlum bir məzmun formatı ilə bağlı qeyd aldı.
ssl-error-rx-unknown-handshake = SSL naməlum bir formatda qarşılama mesajı aldı.
ssl-error-close-notify-alert = SSL həmkarı bu bağlantını kəsdi.
ssl-error-handshake-unexpected-alert = SSL gəmkarı aldığı qarşılama mesajını gözləmirdi.
ssl-error-decompression-failure-alert = SSL həmkarı aldığı  SSL qeydini aça bilmədi.
ssl-error-handshake-failure-alert = SSL həmkarı mümkün sayda təhlükəsizlik dəyişəni ilə qarşılıqlı müzakirə edə bilmədi.
ssl-error-illegal-parameter-alert = SSL qəbul edilə bilməyən məzmun səbəbi ilə qarşılama mesajını rədd etdi.
ssl-error-unsupported-cert-alert = SSL həmkarı aldığı formatdakı təsdiq sənədlərini dəstəkləmir.
ssl-error-certificate-unknown-alert = SSL həmkarı aldığı təsdiq sənədləri ilə təyin edilə bilməyən problemlə üzləşdi.
ssl-error-generate-random-failure = SSL təsadüfi nömrə yaradıcısında bir problemlə üzləşdi.
ssl-error-sign-hashes-failure = Təsdiq sənədinizin doğruluğunu təsdiqləyəcək məlumat, rəqəmli olaraq imzalana bilmədi.
ssl-error-server-key-exchange-failure = SSL serveri açar dəyiştirmə qarşılaması zamanı bir səhvlə qarşılaşdı.
ssl-error-client-key-exchange-failure = SSL klienti açar dəyişdirmə qarşılaması zamanı göstərilməmiş bir səhvlə üzləşdi.
ssl-error-encryption-failure = Seçilmiş şifrələmə dəstindəki məlumat şifrələmə açma yolu uğursuz oldu.
ssl-error-decryption-failure = Seçilmiş şifrələmə dəstindəki məlumat şifrəsi açma yolu uğursuz oldu.
ssl-error-socket-write-failure = Girişə şifrəli məlumat yazma cəhdi uğursuz oldu.
ssl-error-md5-digest-failure = MD5 yığma funksiyası işləmədi.
ssl-error-sha-digest-failure = SHA-1 yığma funksiyası işləmədi.
ssl-error-mac-computation-failure = MAC hesaplaması başarısız oldu.
ssl-error-sym-key-context-failure = Simmetrik açar məzmunu yaradılması uğursuz oldu.
ssl-error-sym-key-unwrap-failure = Klient açar dəyişikliyi mesajındakı simmetrik açar açıla bilmədi.
ssl-error-pub-key-size-limit-exceeded = SSL serveri lokal ümumi açarla ixrac edilən şifrələmə dəstini istifadə etməyə çalışdı.
ssl-error-iv-param-failure = PKCS11 kodu, bir IV-ni bir dəyişənə çevirə bilmədi.
ssl-error-init-cipher-suite-failure = Seçilen şifrələmə dəsti işlədilə bilmədi.
ssl-error-session-key-gen-failure = Klient, SSL hesabı üçün bir açar yarada bilmədi.
ssl-error-no-server-key-for-alg = Server, üzərində işlənən dəyişik açma yolu üçün heç bir açara sahib deyil.
ssl-error-token-insertion-removal = Əməliyyat gedərkən PKCS#11 nişanı əlavə edildi ya da silindi.
ssl-error-token-slot-not-found = Lazım olan əməliyyatı etmək üçün axtarılan PKCS#11 nişanı tapılmadı.
ssl-error-no-compression-overlap = Qarşı tərəflə təhlükəsiz bağlantı qurulmadı: Ortaq birsıxışdırma açma yolu yoxdur.
ssl-error-bad-handshake-hash-value = Həmkardan səhv qarşılama dəyərləri alındı.
ssl-error-cert-kea-mismatch = Təqdim edilən təsdiq sənədi seçilən açar dəyişmə yolu ilə istifadə edilə bilməz.
ssl-error-no-trusted-ssl-client-ca = SSL klienti təsdiqləməsi üçün heç bir təsdiq sənədi rəsmisinə etibar edilmir.
ssl-error-decryption-failed-alert = Həmkar, aldığı bir SSL qeydinin şifrəsini aça bilmədi.
ssl-error-record-overflow-alert = Həmkar icazə veriləndən daha uzun olan bir SSl qeydi aldı.
ssl-error-unknown-ca-alert = Həmkar, təsdiq sənədinizi yayımlayan rəsmini tanımır və ona etibar etmir.
ssl-error-access-denied-alert = Həmkar etibarlı bir təsdiq sənədi aldı, ancaq istifadə bloklandı.
ssl-error-decode-error-alert = Həmkar bir SSL qarşılama mesajını aça bilmədi.
ssl-error-decrypt-error-alert = Həmkar imza təsdiqləmə ya da açar dəyişmə səhvi olduğunu bildirdi.
ssl-error-export-restriction-alert = Həmkar mübadilənin ixracat nizamları ilə uyğun olmadığını bildirir.
ssl-error-protocol-version-alert = Həmkar uyğun olmayan ya da dəstəklənməyən bağlantı qaydası versiyası olduğunu bildirir.
ssl-error-insufficient-security-alert = Server üçün şifrələrin klientin dəstəklədiyindən daha etibarlı olması lazımdır.
ssl-error-internal-error-alert = Həmkar daxili bir səhv olduğunu bildirir.
ssl-error-user-canceled-alert = Həmkar istifadəçi qarşılamağı ləğv etdi.
ssl-error-no-renegotiation-alert = Həmkar SSL təhlükəsizlik dəyişənlərinin yenidən müzakirəsinə icazə vermir.
ssl-error-server-cache-not-configured = SSL serveri bu socket üçün nizamlanmadı və söndürülmədi.
ssl-error-unsupported-extension-alert = SSL həmkarı istənən TLS əlavəsini dəstəkləmir.
ssl-error-certificate-unobtainable-alert = SSL həmkarı URL-dən təsdiq sənədinizi əldə edə bilmədi.
ssl-error-unrecognized-name-alert = SSL həmkarında istənən DNS üçün təsdiq sənədi yoxdur.
ssl-error-bad-cert-status-response-alert = SSL həmkarı təsdiq sənədi üçün OCSP cavabı ala bilmədi.
ssl-error-bad-cert-hash-value-alert = SSL həmkarı xarab olmuş təsdiq sənədi xülasəsi olduğunu xəbər verdi.
ssl-error-rx-unexpected-new-session-ticket = SSL gözlənilməyən bir Yeni Hesab İstəyi əl sıxışma mesajı aldı.
ssl-error-rx-malformed-new-session-ticket = SSL xədəli bir yeni Hesab İstəyi əl sıxışma mesajı aldı.
ssl-error-decompression-failure = SSL açıla bilməyən bir sıxışdırılmış qeyd aldı.
ssl-error-renegotiation-not-allowed = Bu SSL socketində yenidən əməliyyata icazə verilmir.
ssl-error-unsafe-negotiation = Həmkar, köhnə nəsil (potansial olaraq etibarsız) əl sıxışma istəyi verdi.
ssl-error-rx-unexpected-uncompressed-record = SSL gözlənilməyən bir sıxışdırılmış qeyd aldı.
ssl-error-weak-server-ephemeral-dh-key = SSL, serveri Açar Dəyişikliyi razılaşma mesajında zəif bir müvəqqəti Diffie-Hellman açarı aldı.
ssl-error-next-protocol-data-invalid = SSL, etibarsız NPN uzantı məlumatı aldı.
ssl-error-feature-not-supported-for-ssl2 = SSL 2.0 bağlantıları üçün SSL xüsusiyyəti dəstəklənmir.
ssl-error-feature-not-supported-for-servers = Serverlər üçün SSL xüsusiyyəti dəstəklənmir.
ssl-error-feature-not-supported-for-clients = Klientlər üçün SSL xüsusiyyəti dəstəklənmir.
sec-error-io = Təhlükəsizlik təsdiqləməsi zamanı giriş-çıxış səhvi baş verdi.
sec-error-library-failure = Təhlükəsizlik kitabxanası səhvi.
sec-error-bad-data = Təhlükəsiz kitabxanası: Pis məlumat alındı.
sec-error-output-len = Təhlükəsizlik kitabxansı: Çıxış uzunluğu səhvi.
sec-error-input-len = Təhlükəsizlik kitabxanası daxil etmə uzunluğu səhvi.
sec-error-invalid-args = Təhlükəsizlik kitabxansı: Etibarsız dəyişənlər.
sec-error-invalid-algorithm = Təhlükəsizlik kitabxanası: Etibarsız açma yolu.
sec-error-invalid-ava = Təhlükəsizlik kitabxanası: Etibarsız AVA.
sec-error-invalid-time = Düzgün formatlandırılmamış tarix düzümü.
sec-error-bad-der = Təhlükəsizlik kitabxanası: Düzgün formatlandırılmamış DER şifrəli mesaj.
sec-error-no-nodelock = Təhlükəsiz kitabxanası: Düyün kilidi yoxdur.
sec-error-bad-database = Təhlükəsiz kitabxanası: Xarab olmuş verilənlər bazası.
sec-error-no-memory = Təhlükəsiz kitabxanası: Yaddaş paylaşma səhvi.
sec-error-duplicate-cert = Təsdiq sənədi verilənlər bazanızda mövcuddur.
sec-error-adding-cert = Təsdiq sənədinin bazaya daxil edərkən səhv baş verdi.
sec-error-filing-key = Təsdiq sənədinin açarı yenidən doldurularkən səhv baş verdi.
sec-error-no-key = Bu təsdiq sənədinin şəxsi açarı bazada tapılmadı.
sec-error-cert-valid = Bu təsdiq sənədi etibarlıdır.
sec-error-cert-not-valid = Bu təsdiq sənədi etibarsızdır.
sec-error-cert-no-response = Təsdiq sənədi kitabxanası: Cavab yoxdur.
sec-error-crl-invalid = Yeni ləğv edilmişlər siyahısı etibarsız formata sahibddir.
sec-error-extension-value-invalid = Təsdiq sənədi uzantısı dəyəri etibarsızdır.
sec-error-extension-not-found = Təsdiq sənədi uzantısı tapılmadı.
sec-error-ca-cert-invalid = Yayımlayıcının təsdiq sənədi etibarsızdır.
sec-error-path-len-constraint-invalid = Təsdiq sənədi ünvan uzunluğu limiti etibarsızdır.
sec-error-cert-usages-invalid = Təsdiq sənədi istifadə adı etibarsızdır.
sec-internal-only = **YALNIZ daxili modul**
sec-error-invalid-key = Açar istənən əməliyyatı dəstəkləmir.
sec-error-unknown-critical-extension = Təsdiq sənədinə naməlum kritik uzantılar daxildi.
sec-error-no-email-cert = Şifrələnməmiş ya da imzalanmamış: Hələ ki e-poçt təsdiq sənədiniz yoxdur.
sec-error-no-recipient-certs-query = Şifrələnməmiş: Hər bir alıcı üçün təsdiq sənədiniz yoxdur.
sec-error-not-a-recipient = Şifrə açıla bilmir: Alıcı siz deyilsiniz ya da bir-biriylə uyğun gələn təsdiq sənədi ya da xüsusi açar tapılmadı.
sec-error-pkcs7-keyalg-mismatch = Şifrə açıla bilmir: Açar şifrələmə açma yolu təsdiq sənədinizlə uyğun gəlmir.
sec-error-pkcs7-bad-signature = Açar təsdiqləməsi uğursuz oldu: İmzaçı tapıla bilməmiş, çox artıq tapılmış ya da düzgün olmayan və ya əksik məlumatla əməliyyat aparılmış ola bilər.
sec-error-unsupported-keyalg = Dəstəklənməyən ya da naməlum açar açma yolu.
sec-error-decryption-disallowed = Şifrə açıla bilmir: İcazə verilməyən bir açma yolu ilə ya da açar ölçüsündə şifrələnib.
xp-sec-fortezza-no-card = Fortezza kartı tapılmadı
xp-sec-fortezza-none-selected = Fortezza kartı seçilmədi
xp-sec-fortezza-more-info = Lütfən daha çox məlumat almaq üçün bir şəxsiyyət seçin
xp-sec-fortezza-person-not-found = Kişilik bulunamadı
xp-sec-fortezza-no-more-info = Bu şəxsiyyətlə bağlı daha çox məlumat yoxdur
xp-sec-fortezza-bad-pin = Etibarsız şəxsi təyin etmə nömrəsi
sec-error-krl-invalid = Yeni etibarsız açar siyahısının format etibarsızdır.
sec-error-need-random = Təhlükəsizlik kitabxanası: təsadüfi məlumat lazımdır.
sec-error-no-module = Təhlükəsizlik kitabxanası: Heç bir təhlükəsizlik vahidi istənən əməliyyatı yerin yetirə bilmir.
sec-error-no-token = Təhlükəsizlik kartı ya da işarəsi yoxdur, başladılmalı ya da silinmiş ola bilər.
sec-error-read-only = Təhlükəsizlik kitabxanası: Verilnəlr bazası sadəcə oxunurdur.
sec-error-no-slot-selected = Slot ya da işarə seçilmədi.
sec-error-cert-nickname-collision = Eyni ləqəbdə bir təsdiq sənədi mövcuddur.
sec-error-key-nickname-collision = Eyni ləqəbdə bir açar mövcuddur.
sec-error-safe-not-created = Təhlükəsiz obyekt yaradılarkən səhv baş verdi.
sec-error-baggage-not-created = Baqaj obyekti yaradılarkən səhv baş verdi.
sec-error-bad-export-algorithm = İstenen açma yoluna icazə verilmir.
sec-error-exporting-certificates = Təsdiq sənədləri ixrac edilərkən səhv baş verdi.
sec-error-importing-certificates = təsdiq sənədləri idxal edilərkən səhv baş verdi.
sec-error-user-cancelled = İstifadəçi ləğv et düyməsinə basdı.
sec-error-pkcs12-duplicate-data = İdxal edilmədi: Bazada mövcuddur.
sec-error-message-send-aborted = İleti gönderilmedi.
sec-error-inadequate-key-usage = Təsdiq sənədi, açar istifadə etməyə çalışan əməliyyat üçün kifayət deyil.
sec-error-inadequate-cert-type = Təsdiq sənədi formatı proqram üçün təsdiqlənməyib.
sec-error-cert-addr-mismatch = İmzalanan təsdiq sənədindəki ünvan başlıqdakı ünvanla uyğun gəlmir.
sec-error-keygen-fail = Xüsusi və ümumi açar cütlüyü yarıla bilmir.
sec-error-bad-nickname = Təsdiq sənədi ləqəbi hazırda istifadə olunur.
sec-error-not-fortezza-issuer = Həmkarın FORTEZZA zəncirinə saf FORTEZZA olmayan təsdiq sənədi daxildir.
sec-error-cannot-move-sensitive-key = Həssas bir açar lazım olan slot saxlana bilmir.
sec-error-cert-not-in-name-space = Bu təsdiq sənədinin rəsmisinin adı ilə yayımlamağa icazə verilmir.
sec-error-krl-not-yet-valid = Bu təsdiq sənədinin ləğv edilmiş açarlar siyahısı hələki etibarlı deyil.
sec-error-crl-not-yet-valid = Bu təsdiq sənədinin ləğv edilmiş təsdiq sənədi hələki etibarlı deyil.
sec-error-unknown-cert = İstənən təsdiq sənədi tapılmadı.
sec-error-cert-bad-access-location = Təsdiq sənədi status serverinin ünvanı etibarsız formatdadır.
sec-error-ocsp-unknown-response-type = OCSP cavab tam açıla bilmir; naməlum formatdadır.
sec-error-ocsp-bad-http-response = OCSP serveri gözlənilməyən ya da etibarsız HTTP məlumatı aldı.
sec-error-ocsp-malformed-request = OCSP serveri istəyin yarıda kəsilmiş ya da düzgün olmayan formatda olduğunu bildirdi.
sec-error-ocsp-server-error = OCSP serveri daxili problemlə üzləşdi.
sec-error-ocsp-try-server-later = OCSPserveri daha sonra yoxlanılmasını təklif edir.
sec-error-ocsp-request-needs-sig = OCSP serveri bu istəkdə imza lazım olduğunu bildirir.
sec-error-ocsp-unauthorized-request = OCSP serveri icazəsiz olması əsası ilə bu istəyi rədd etdi.
sec-error-ocsp-unknown-response-status = OCSP serveri naməlum bir vəziyyətlə qarşılaşdı.
sec-error-ocsp-unknown-cert = OCSP serveri təsdiq sənədi ilə bağlı bir status bildirişi verə bilmir.
sec-error-ocsp-not-enabled = Bu əməliyyatı etmədən əvvəl OCSP-ni aktivləşdirməlsiniz.
sec-error-ocsp-no-default-responder = Bu əməliyyatı etməzdən qabaq OCSP-ni standart cavab verici olaraq nizamlamalısınız.
sec-error-ocsp-malformed-response = OCSP serveri cavabı korlanmış ya da düzgün olmayan formatdadır.
sec-error-ocsp-unauthorized-response = OCSP cavabının yayımlayıcısının bu təsdiq sənədi ilə bağlı statusu bildirmək icazəsi yoxdur.
sec-error-ocsp-future-response = OCSP cavabı hələki aktiv deyil, çünki gələvcək bir tarixi var.
sec-error-ocsp-old-response = OCSP cavabına vaxtı çıxmış məlumat daxildir.
sec-error-digest-not-found = İmzalanan cavabda CMS ya da PKCS #7 xülasəsi tapılmadı.
sec-error-unsupported-message-type = CMS ya da PKCS #7 cavabı formatı dəstəkləmir.
sec-error-bad-template = ASN.1 məlumatı açıla bilmir. Göstərilən qəlib etibarsızdır.
sec-error-crl-not-found = Uyğun gələn ləğv edilmişlər siyahısı tapılmadı.
sec-error-reused-issuer-and-serial = Mövcud olan bir təsdiq sənədi ilə eyni seriyaya və eyni yayımlayıcıya məxus yeni bir təsdiq sənədini idxal etmək istəyirsiniz, ancaq bu sənədlər eyni deyil.
sec-error-busy = NSS bağlanmadı. Obyektlər hələ də istifadə olunur.
sec-error-extra-input = DER şifrəli mesaj istifadə etməyənə artıq yerdən ibarətdi.
sec-error-unsupported-elliptic-curve = Dəstəklənməyən əyri.
sec-error-unsupported-ec-point-form = Dəstəklənməyən əyri şəkli.
sec-error-unrecognized-oid = Naməlum obyekt təyinedici.
sec-error-ocsp-invalid-signing-cert = OCSP cavabında etibarsız OCSP təsdiq sənədi imzası var.
sec-error-unknown-object-type = Naməlum obyekt növü göstərildi.
sec-error-incompatible-pkcs11 = PKCS #11 versiyasını qanunsuz yolla pozur.
sec-error-no-event = Hazırda yeni bir slot hərəkəti yoxdur.
sec-error-crl-already-exists = Ləğv edilmiş təsdiq sənədləri siyahısı istifadə olunur.
sec-error-not-initialized = NSS başladılmadı.
sec-error-token-not-logged-in = Əməliyyat uğursuzluqla nəticələndi, çünki PKCS#11 texnalogiyası daxil olmuyub.
sec-error-ocsp-bad-signature = OCSP cavabının etibarsız imzası var.
sec-error-out-of-search-limits = Sənəd təsdiqləmə axtarış axtarış limitlərinə daxil deyil
sec-error-invalid-policy-mapping = Qanun xəritləməsinə anypolicy daxildir
sec-error-policy-validation-failed = Təsdiq sənədi zənciri qanun təsdiqləməsindən keçmədi
sec-error-unknown-aia-location-type = Təsdiq sənədi AIA uzantısında naməlum ünvan formatı
sec-error-bad-http-response = Server xətalı HTTP cavabı qaytardı
sec-error-bad-ldap-response = erver xətalı LDAP cavabı qaytardı
sec-error-bad-info-access-location = Təsdiq sənədi uzantısında yanlış məlumat ünvanı
sec-error-libpkix-internal = Sertifikat təsdiqləməsi zamanı daxili Libpkix səhvi baş verdi.
sec-error-pkcs11-general-error = Bir PKCS #11 modulu bərpa edilə bilməyən bir səhvi göstərənn CKR_GENERAL_ERROR qaytardı.
sec-error-pkcs11-device-error = Bir PKCS #11 modulu bilet və ya slotta səhv yarandığını göstərən CKR_DEVICE_ERROR qaytardı.
sec-error-bad-info-access-method = Təsdiq sənədi uzantısında naməlum məlumat əldə etmə üsulu.
sec-error-crl-import-failed = Ləğv edilmiş təsdiq sənədi idxal edilərkən bir səhv baş verdi.
sec-error-unknown-pkcs11-error = Naməlum PKCS #11 xətası.
sec-error-bad-crl-dp-url = CRL paylama nöqtəsi adında etibarsız və ya dəstəklənilməyən URL.
sec-error-cert-signature-algorithm-disabled = Sertifikat, etibarlı olmadığı üçün söndürülən bir imza alqoritmi ilə imzalandı.
