# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = Aç
    .accesskey = A
places-open-all-in-tabs =
    .label = Hamısını Vərəqlərdə Aç
    .accesskey = A
places-view =
    .label = Görünüş
    .accesskey = G
places-by-date =
    .label = Tarix
    .accesskey = T
places-by-site =
    .label = Sayt
    .accesskey = S
places-by-most-visited =
    .label = Ən çox baxılanlar
    .accesskey = Ə
places-by-last-visited =
    .label = Son baxılanlar
    .accesskey = S
places-by-day-and-site =
    .label = Tarix və sayt
    .accesskey = T
places-history-search =
    .placeholder = Tarixçədə axtar
places-history =
    .aria-label = Tarixçə
places-bookmarks-search =
    .placeholder = Əlfəcinlərdə Axtar
places-delete-domain-data =
    .label = Bu saytı unut
    .accesskey = u
places-sortby-name =
    .label = Ada görə sırala
    .accesskey = k
places-library =
    .title = Kitabxana
    .style = width:700px; height:500px;
places-organize-button =
    .label = Redaktə
    .tooltiptext = Əlfəcinləri idarə et
    .accesskey = d
places-organize-button-mac =
    .label = Redaktə
    .tooltiptext = Əlfəcinləri idarə et
places-file-close =
    .label = Bağla
    .accesskey = B
places-cmd-close =
    .key = w
places-view-button =
    .label = Görünüş
    .tooltiptext = Görünüşü dəyişdirin
    .accesskey = n
places-view-button-mac =
    .label = Görünüş
    .tooltiptext = Görünüşü dəyişdirin
places-view-menu-columns =
    .label = Sütunları göstər
    .accesskey = S
places-view-menu-sort =
    .label = Sırala
    .accesskey = S
places-view-sort-unsorted =
    .label = Siniflənməmiş
    .accesskey = f
places-view-sort-ascending =
    .label = A-dan Z-yə sırala
    .accesskey = A
places-view-sort-descending =
    .label = Z-dən A-ya sırala
    .accesskey = Z
places-maintenance-button =
    .label = İdxal etmə və ehtiyatlama
    .tooltiptext = Əlfəcinlərinizi idxal edin və yedəkləyin
    .accesskey = y
places-maintenance-button-mac =
    .label = İdxal etmə və ehtiyatlama
    .tooltiptext = Əlfəcinlərinizi idxal edin və yedəkləyin
places-cmd-backup =
    .label = Nüsxəsini çıxar…
    .accesskey = N
places-cmd-restore =
    .label = Bərpa et
    .accesskey = e
places-cmd-restore-from-file =
    .label = Fayl seç…
    .accesskey = s
places-import-bookmarks-from-html =
    .label = Əlfəcinləri HTML-dən idxal et…
    .accesskey = i
places-export-bookmarks-to-html =
    .label = Əlfəcinləri HTML olaraq ixrac et…
    .accesskey = i
places-import-other-browser =
    .label = Başqa səyyahdan məlumatları idxal et…
    .accesskey = B
places-view-sort-col-name =
    .label = Ad
places-view-sort-col-tags =
    .label = Etiketlər
places-view-sort-col-url =
    .label = Ünvan
places-view-sort-col-most-recent-visit =
    .label = Ən son ziyarət
places-view-sort-col-visit-count =
    .label = Baxış sayı
places-view-sort-col-date-added =
    .label = Əlavə etmə tarixi
places-view-sort-col-last-modified =
    .label = Son dəyişiklik
places-cmd-find-key =
    .key = f
places-back-button =
    .tooltiptext = Geri get
places-forward-button =
    .tooltiptext = İrəli get
places-details-pane-select-an-item-description = Xüsusiyyətlərini görmək və dəyişmək üçün bir obyekt seçin
