# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE (RootCertModuleName): string limit is 64 bytes after
# conversion to UTF-8.
# length_limit = 64 bytes
RootCertModuleName = Riña màn nej nuguan' nata'a
# LOCALIZATION NOTE (ManufacturerID): string limit is 32 bytes after conversion
# to UTF-8.
# length_limit = 32 bytes
ManufacturerID = Mozilla.org
# LOCALIZATION NOTE (LibraryDescription): string limit is 32 bytes after
# conversion to UTF-8.
# length_limit = 32 bytes
LibraryDescription = PSM Sun Kriptografô dukuàa
# LOCALIZATION NOTE (TokenDescription): string limit is 32 bytes after
# conversion to UTF-8.
# length_limit = 32 bytes
TokenDescription = Sun Kriptografô 'na'a
# LOCALIZATION NOTE (PrivateTokenDescription): string limit is 32 bytes after
# conversion to UTF-8.
# length_limit = 32 bytes
PrivateTokenDescription = Sa dugumîn nej software
# LOCALIZATION NOTE (SlotDescription): string limit is 64 bytes after conversion
# to UTF-8.
# length_limit = 64 bytes
SlotDescription = PSM Sun Kriptografô dukuàa
# LOCALIZATION NOTE (PrivateSlotDescription): string limit is 64 bytes after
# conversion to UTF-8.
# length_limit = 64 bytes
PrivateSlotDescription = PSM Yabê huìi
# LOCALIZATION NOTE (Fips140TokenDescription): string limit is 32 bytes after
# conversion to UTF-8.
# length_limit = 32 bytes
Fips140TokenDescription = Sa dugumîn nej software (FIPS)
# LOCALIZATION NOTE (Fips140SlotDescription): string limit is 64 bytes after
# conversion to UTF-8.
# length_limit = 64 bytes
Fips140SlotDescription = FIPS 140 Sun kriptogrâfiko, guendâ da'nga'a ni sertifikado
# LOCALIZATION NOTE (nick_template): $1s is the common name from a cert (e.g. "Mozilla"), $2s is the CA name (e.g. VeriSign)
nick_template = %1$s’s %2$s ID
