# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host } so pyta…
network-connection-status-connected = Zwjazane z { $host }…
network-connection-status-sending-request = Sćele so naprašowanje na { $host }…
network-connection-status-tls-handshake = TLS-rukuzawdaće so z { $host } wuwjedźe…
network-connection-status-tls-handshake-finished = TLS-rukuzawdaće je so za { $host } skónčiło…
