# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Serĉado de adreso de { $host }…
network-connection-status-connected = Konekto al { $host }…
network-connection-status-sending-request = Sendo de peto al { $host }…
network-connection-status-transferring-data = Datumoj transmetataj el { $host }…
network-connection-status-connecting = Konektiĝo al { $host }…
network-connection-status-read = { $host } legita
network-connection-status-wrote = { $host } skribita
network-connection-status-waiting = Atendado je { $host }…
network-connection-status-looked-up = Adreso de { $host } serĉita…
network-connection-status-tls-handshake = Intertrakto de TLS kun { $host }…
network-connection-status-tls-handshake-finished = La intertrakto de TLS kun { $host } finiĝis…
