# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = ವಿಝಾರ್ಡನ್ನು ಆಮದು ಮಾಡಿಕೊ
import-from =
    { PLATFORM() ->
        [windows] ಇಲ್ಲಿಂದ ಆಯ್ಕೆಗಳನ್ನು, ಬುಕ್‍ಮಾರ್ಕುಗಳನ್ನು, ಇತಿಹಾಸ, ಗುಪ್ತಪದ ಹಾಗು ಇತರೆ ಮಾಹಿತಿಯನ್ನು ಆಮದು ಮಾಡಿಕೊ:
       *[other] ಇಲ್ಲಿಂದ ಆದ್ಯತೆಗಳನ್ನು, ಬುಕ್‍ಮಾರ್ಕುಗಳನ್ನು, ಇತಿಹಾಸ, ಗುಪ್ತಪದ ಹಾಗು ಇತರೆ ಮಾಹಿತಿಯನ್ನು ಆಮದು ಮಾಡಿಕೊ:
    }
import-from-bookmarks = ಇಲ್ಲಿಂದ ಬುಕ್‍ಮಾರ್ಕುಗಳನ್ನು ಆಮದು ಮಾಡಿಕೊ:
import-from-ie =
    .label = ಮೈಕ್ರೋಸಾಫ್ಟ್‍ ಇಂಟರ್ನೆಟ್ ಎಕ್ಸ್‍ಪ್ಲೋರರ್
    .accesskey = M
import-from-edge =
    .label = ಮೈಕ್ರೋಸಾಫ್ಟ್ ಎಜ್
    .accesskey = E
import-from-nothing =
    .label = ಏನನ್ನೂ ಆಮದು ಮಾಡಿಕೊಳ್ಳಬೇಡ
    .accesskey = D
import-from-safari =
    .label = ಸಫಾರಿ
    .accesskey = S
import-from-canary =
    .label = ಕ್ರೋಮ್ ಕ್ಯಾನರಿ
    .accesskey = n
import-from-chrome =
    .label = ಕ್ರೋಮ್
    .accesskey = C
import-from-chrome-beta =
    .label = ಕ್ರೋಮ್ ಬೀಟಾ
    .accesskey = B
import-from-chrome-dev =
    .label = ಕ್ರೋಮ್ ಡೆವ್
    .accesskey = D
import-from-chromium =
    .label = ಕ್ರೋಮಿಯಮ್
    .accesskey = u
import-from-firefox =
    .label = ಫೈರ್ಫಾಕ್ಸ್
    .accesskey = x
import-from-360se =
    .label = 360 ಸುರಕ್ಷಿತ ವೀಕ್ಷಕ
    .accesskey = 3
no-migration-sources = ಬುಕ್‍ಮಾರ್ಕುಗಳನ್ನು, ಇತಿಹಾಸ, ಅಥವ ಗುಪ್ತಪದವನ್ನು ಹೊಂದಿರುವ ಯಾವುದೆ ಪ್ರೊಗ್ರಾಂ ಕಂಡು ಬಂದಿಲ್ಲ.
import-source =
    .label = ಸಿದ್ಧತೆಗಳನ್ನು ಹಾಗು ಮಾಹಿತಿಯನ್ನು ಆಮದು ಮಾಡಿಕೊ
import-items-title =
    .label = ಆಮದು ಮಾಡಿಕೊಳ್ಳಲು ಅಂಶಗಳು
import-items-description = ಯಾವ ಅಂಶಗಳನ್ನು ಆಮದು ಮಾಡಬೇಕೆಂದು ಆರಿಸಿ:
import-migrating-title =
    .label = ಆಮದು ಮಾಡಲಾಗುತ್ತಿದೆ...
import-migrating-description = ಈ ಕೆಳಗಿನ ಅಂಶಗಳು ಈಗ ಆಮದು ಮಾಡಿಕೊಳ್ಳಲಾಗುತ್ತಿದೆ...
import-select-profile-title =
    .label = ಪ್ರೊಫೈಲ್‌ ಅನ್ನು ಆರಿಸಿ
import-select-profile-description = ಇಲ್ಲಿಂದ ಈ ಕೆಳಗಿನ ಪ್ರೊಫೈಲ್‌ಗಳು ಆಮದಿಗೆ ಲಭ್ಯವಿವೆ:
import-done-title =
    .label = ಆಮದು ಪೂರ್ಣಗೊಂಡಿದೆ
import-done-description = ಈ ಕೆಳಗಿನ ಅಂಶಗಳನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಆಮದು ಮಾಡಿಕೊಳ್ಳಲಾಯಿತು:
import-close-source-browser = ಮುಂದುವರೆಯುವ ಮೊದಲು, ಆಯ್ಕೆ ಮಾಡಲಾದ ಜಾಲವೀಕ್ಷಕವನ್ನು ಮುಚ್ಚಲಾಗಿದೆ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ.
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = { $source } ನಿಂದ
source-name-ie = ಇಂಟರ್ನೆಟ್ ಎಕ್ಸ್‍ಪ್ಲೋರರ್
source-name-edge = ಮೈಕ್ರೋಸಾಫ್ಟ್ ಎಜ್
source-name-safari = ಸಫಾರಿ
source-name-canary = ಗೂಗಲ್ ಕ್ರೋಮ್ ಕ್ಯಾನರಿ
source-name-chrome = ಗೂಗಲ್ ಕ್ರೋಮ್
source-name-chrome-beta = ಗೂಗಲ್ ಕ್ರೋಮ್ ಬೀಟಾ
source-name-chrome-dev = ಗೂಗಲ್ ಕ್ರೋಮ್ ಡೆವ್
source-name-chromium = ಕ್ರೋಮಿಯಮ್
source-name-firefox = ಮೋಝಿಲ್ಲಾ ಫೈರ್ಫಾಕ್ಸ್
source-name-360se = 360 ಸುರಕ್ಷಿತ ವೀಕ್ಷಕ
imported-safari-reading-list = ಓದುವ ಪಟ್ಟಿ (ಸಫಾರಿಯಿಂದ)
imported-edge-reading-list = ಓದುವ ಪಟ್ಟಿ (ಎಜ್‌ನಿಂದ)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = ಅಂತರಜಾಲದ ಆಯ್ಕೆಗಳು
    .value = ಅಂತರಜಾಲದ ಆಯ್ಕೆಗಳು
browser-data-edge-1 =
    .label = ಸಿದ್ಧತೆಗಳು
    .value = ಸಿದ್ಧತೆಗಳು
browser-data-safari-1 =
    .label = ಆದ್ಯತೆಗಳು
    .value = ಆದ್ಯತೆಗಳು
browser-data-chrome-1 =
    .label = ಆದ್ಯತೆಗಳು
    .value = ಆದ್ಯತೆಗಳು
browser-data-canary-1 =
    .label = ಆದ್ಯತೆಗಳು
    .value = ಆದ್ಯತೆಗಳು
browser-data-360se-1 =
    .label = ಆದ್ಯತೆಗಳು
    .value = ಆದ್ಯತೆಗಳು
browser-data-ie-2 =
    .label = ಕುಕಿಗಳು
    .value = ಕುಕಿಗಳು
browser-data-edge-2 =
    .label = ಕುಕಿಗಳು
    .value = ಕುಕಿಗಳು
browser-data-safari-2 =
    .label = ಕುಕಿಗಳು
    .value = ಕುಕಿಗಳು
browser-data-chrome-2 =
    .label = ಕುಕಿಗಳು
    .value = ಕುಕಿಗಳು
browser-data-canary-2 =
    .label = ಕುಕಿಗಳು
    .value = ಕುಕಿಗಳು
browser-data-firefox-2 =
    .label = ಕುಕಿಗಳು
    .value = ಕುಕಿಗಳು
browser-data-360se-2 =
    .label = ಕುಕಿಗಳು
    .value = ಕುಕಿಗಳು
browser-data-ie-4 =
    .label = ಜಾಲವೀಕ್ಷಣಾ ಇತಿಹಾಸ
    .value = ಜಾಲವೀಕ್ಷಣಾ ಇತಿಹಾಸ
browser-data-edge-4 =
    .label = ಜಾಲವೀಕ್ಷಣಾ ಇತಿಹಾಸ
    .value = ಜಾಲವೀಕ್ಷಣಾ ಇತಿಹಾಸ
browser-data-safari-4 =
    .label = ಜಾಲವೀಕ್ಷಣಾ ಇತಿಹಾಸ
    .value = ಜಾಲವೀಕ್ಷಣಾ ಇತಿಹಾಸ
browser-data-chrome-4 =
    .label = ಜಾಲವೀಕ್ಷಣಾ ಇತಿಹಾಸ
    .value = ಜಾಲವೀಕ್ಷಣಾ ಇತಿಹಾಸ
browser-data-canary-4 =
    .label = ಜಾಲವೀಕ್ಷಣಾ ಇತಿಹಾಸ
    .value = ಜಾಲವೀಕ್ಷಣಾ ಇತಿಹಾಸ
browser-data-firefox-history-and-bookmarks-4 =
    .label = ವೀಕ್ಷಣಾ ಇತಿಹಾಸ ಮತ್ತು ಬುಕ್‌ಮಾರ್ಕುಗಳು
    .value = ವೀಕ್ಷಣಾ ಇತಿಹಾಸ ಮತ್ತು ಬುಕ್‌ಮಾರ್ಕುಗಳು
browser-data-360se-4 =
    .label = ಜಾಲವೀಕ್ಷಣೆಯ ಇತಿಹಾಸ
    .value = ಜಾಲವೀಕ್ಷಣೆಯ ಇತಿಹಾಸ
browser-data-ie-8 =
    .label = ಇತಿಹಾಸದಿಂದ ಉಳಿಸಲಾದ
    .value = ಇತಿಹಾಸದಿಂದ ಉಳಿಸಲಾದ
browser-data-edge-8 =
    .label = ಇತಿಹಾಸದಿಂದ ಉಳಿಸಲಾದ
    .value = ಇತಿಹಾಸದಿಂದ ಉಳಿಸಲಾದ
browser-data-safari-8 =
    .label = ಇತಿಹಾಸದಿಂದ ಉಳಿಸಲಾದ
    .value = ಇತಿಹಾಸದಿಂದ ಉಳಿಸಲಾದ
browser-data-chrome-8 =
    .label = ಇತಿಹಾಸದಿಂದ ಉಳಿಸಲಾದ
    .value = ಇತಿಹಾಸದಿಂದ ಉಳಿಸಲಾದ
browser-data-canary-8 =
    .label = ಇತಿಹಾಸದಿಂದ ಉಳಿಸಲಾದ
    .value = ಇತಿಹಾಸದಿಂದ ಉಳಿಸಲಾದ
browser-data-firefox-8 =
    .label = ಇತಿಹಾಸದಿಂದ ಉಳಿಸಲಾದ
    .value = ಇತಿಹಾಸದಿಂದ ಉಳಿಸಲಾದ
browser-data-360se-8 =
    .label = ಇತಿಹಾಸದಿಂದ ಉಳಿಸಲಾದವು
    .value = ಇತಿಹಾಸದಿಂದ ಉಳಿಸಲಾದವು
browser-data-ie-16 =
    .label = ಉಳಿಸಲಾದ ಗುಪ್ತಪದಗಳು
    .value = ಉಳಿಸಲಾದ ಗುಪ್ತಪದಗಳು
browser-data-edge-16 =
    .label = ಉಳಿಸಲಾದ ಗುಪ್ತಪದಗಳು
    .value = ಉಳಿಸಲಾದ ಗುಪ್ತಪದಗಳು
browser-data-safari-16 =
    .label = ಉಳಿಸಲಾದ ಗುಪ್ತಪದಗಳು
    .value = ಉಳಿಸಲಾದ ಗುಪ್ತಪದಗಳು
browser-data-chrome-16 =
    .label = ಉಳಿಸಲಾದ ಗುಪ್ತಪದಗಳು
    .value = ಉಳಿಸಲಾದ ಗುಪ್ತಪದಗಳು
browser-data-canary-16 =
    .label = ಉಳಿಸಲಾದ ಗುಪ್ತಪದಗಳು
    .value = ಉಳಿಸಲಾದ ಗುಪ್ತಪದಗಳು
browser-data-firefox-16 =
    .label = ಉಳಿಸಲಾದ ಗುಪ್ತಪದಗಳು
    .value = ಉಳಿಸಲಾದ ಗುಪ್ತಪದಗಳು
browser-data-360se-16 =
    .label = ಉಳಿಸಲಾದ ಗುಪ್ತಪದಗಳು
    .value = ಉಳಿಸಲಾದ ಗುಪ್ತಪದಗಳು
browser-data-ie-32 =
    .label = ಅಚ್ಚುಮೆಚ್ಚಿನವು
    .value = ಅಚ್ಚುಮೆಚ್ಚಿನವು
browser-data-edge-32 =
    .label = ಅಚ್ಚುಮೆಚ್ಚಿನವು
    .value = ಅಚ್ಚುಮೆಚ್ಚಿನವು
browser-data-safari-32 =
    .label = ಬುಕ್‌ಮಾರ್ಕುಗಳು
    .value = ಬುಕ್‌ಮಾರ್ಕುಗಳು
browser-data-chrome-32 =
    .label = ಬುಕ್‌ಮಾರ್ಕುಗಳು
    .value = ಬುಕ್‌ಮಾರ್ಕುಗಳು
browser-data-canary-32 =
    .label = ಬುಕ್‌ಮಾರ್ಕುಗಳು
    .value = ಬುಕ್‌ಮಾರ್ಕುಗಳು
browser-data-360se-32 =
    .label = ಪುಟಗುರುತುಗಳು
    .value = ಪುಟಗುರುತುಗಳು
browser-data-ie-64 =
    .label = ಇತರೆ ಮಾಹಿತಿ
    .value = ಇತರೆ ಮಾಹಿತಿ
browser-data-edge-64 =
    .label = ಇತರೆ ಮಾಹಿತಿ
    .value = ಇತರೆ ಮಾಹಿತಿ
browser-data-safari-64 =
    .label = ಇತರೆ ಮಾಹಿತಿ
    .value = ಇತರೆ ಮಾಹಿತಿ
browser-data-chrome-64 =
    .label = ಇತರೆ ಮಾಹಿತಿ
    .value = ಇತರೆ ಮಾಹಿತಿ
browser-data-canary-64 =
    .label = ಇತರೆ ಮಾಹಿತಿ
    .value = ಇತರೆ ಮಾಹಿತಿ
browser-data-firefox-other-64 =
    .label = ಇತರೆ ದತ್ತಾಂಶ
    .value = ಇತರೆ ದತ್ತಾಂಶ
browser-data-360se-64 =
    .label = ಇತರೆ ದತ್ತಾಂಶ
    .value = ಇತರೆ ದತ್ತಾಂಶ
browser-data-firefox-128 =
    .label = ವಿಂಡೋಗಳು ಹಾಗು ಹಾಳೆಗಳು
    .value = ವಿಂಡೋಗಳು ಹಾಗು ಹಾಳೆಗಳು
