# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

title = નેટવર્કીંગ વિશે
warning = આ ખૂબ પરીક્ષણીય છે. વયસ્કના નીરિક્ષણ વિના વાપરશો નહિ.
show-next-time-checkbox = આગલા વખતે આ ચેતવણી બતાવો
ok = બરાબર
http = HTTP
sockets = સૉકેટ
dns = DNS
websockets = WebSockets
refresh = પુનઃતાજું કરો
auto-refresh = દર ૩ સેકન્ડો સ્વયં પુનઃતાજું કરો
hostname = યજમાનનામ
port = પોર્ટ
http2 = HTTP/2
ssl = SSL
active = સક્રિય
idle = ફાજલ
host = યજમાન
tcp = TCP
sent = મોકલાયો
received = મેળવાયો
family = પરિવાર
trr = TRR
addresses = સરનામાઓ
expires = નિવૃત્ત થાય છે (સેકન્ડો)
messages-sent = સંદેશાઓ મોકલાયા
messages-received = સંદેશાઓ મેળવાયા
bytes-sent = બાઇટ્સ મોકલાયા
bytes-received = બાઇટ્સ મેળવાયા
logging = લૉગિંગ
log-tutorial = આ સાધનનો ઉપયોગ કેવી રીતે કરવો તેની સૂચનાઓ માટે <a data-l10n-name="logging">HTTP લોગિંગ</a> જુઓ.
current-log-file = વર્તમાન લોગ ફાઇલ:
current-log-modules = વર્તમાન લોગ મોડ્યુલો:
set-log-file = લોગ ફાઇલ સેટ કરો
set-log-modules = લોગ મોડ્યુલ સેટ કરો
start-logging = લોગિંગ શરૂ કરો
stop-logging = લોગિંગ રોકો
dns-lookup = DNS Lookup
dns-lookup-button = ઉકેલો
dns-domain = ડોમેન:
dns-lookup-table-column = IPs
rcwn = RCWN આંકડા
rcwn-status = RCWN સ્થિતિ
rcwn-cache-won-count = કેશ ગણતરી જીતી
rcwn-net-won-count = નેટ ગણતરી જીતી
total-network-requests = કુલ નેટવર્ક વિનંતિ ગણતરી
rcwn-operation = કેશ ઓપરેશન
rcwn-perf-open = ખોલો
rcwn-perf-read = વાંચો
rcwn-perf-write = લખો
rcwn-perf-entry-open = પ્રવેશ ખોલો
rcwn-avg-short = લઘુ સરેરાશ
rcwn-avg-long = લાંબુ સરેરાશ
rcwn-std-dev-long = લાંબા ધોરણ વિચલન
rcwn-cache-slow = કેશ ધીમી ગણતરી
rcwn-cache-not-slow = કેશની ધીમી ગણતરી નથી
