# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Meklej { $host }…
network-connection-status-connected = Pīsasliedz pi { $host }…
network-connection-status-sending-request = Syuta pīprasiejumu iz { $host }…
network-connection-status-transferring-data = Puorsyuta datus nu { $host }…
network-connection-status-connecting = Pīsaslādz pi { $host }…
network-connection-status-read = Skaita { $host }
network-connection-status-wrote = Īraksteja { $host }
network-connection-status-waiting = Gaida iz { $host }…
network-connection-status-looked-up = Uzmeklieja { $host }…
