# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SaveImageTitle = Gcina umfuziselo
SaveMediaTitle = Gcina iMidiya
SaveVideoTitle = Gcina ividiyo
SaveAudioTitle = Gcina okunesandi
SaveLinkTitle = Gcina njenge
WebPageCompleteFilter = Ikhasi lewebhu, gqibezela
WebPageHTMLOnlyFilter = Ikhasi lewebhu, i-HTML kuphela
WebPageXHTMLOnlyFilter = Ikhasi lewebhu, i-XHTML kuphela
WebPageSVGOnlyFilter = Ikhasi lewebhu, i-SVG kuphela
WebPageXMLOnlyFilter = Ikhasi lewebhu, i-XML kuphela
