# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Daeth yr amser i ben
openFile = Agor Ffeil
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Chwilio %1$S am "%2$S"
contextMenuSearch.accesskey = C
contextMenuPrivateSearch = Chwilio mewn Ffenestr Breifat
contextMenuPrivateSearch.accesskey = h
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Chwilio gyda %S mewn Ffenestr Breifat
contextMenuPrivateSearchOtherEngine.accesskey = h
bookmarkAllTabsDefault = [Enw Ffolder]
unsignedAddonsDisabled.message = Mae un neu fwy o ychwanegion nad oedd modd eu gwirio wedi eu hanalluogi.
unsignedAddonsDisabled.learnMore.label = Darllen Rhagor
unsignedAddonsDisabled.learnMore.accesskey = D
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Mynediad diwethaf %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = Dolenni %S://
crashedpluginsMessage.title = Mae'r ategyn %S wedi chwalu.
crashedpluginsMessage.reloadButton.label = Ail lwytho tudalen
crashedpluginsMessage.reloadButton.accesskey = A
crashedpluginsMessage.submitButton.label = Cyflwyno adroddiad chwalu
crashedpluginsMessage.submitButton.accesskey = C
crashedpluginsMessage.learnMore = Darllen Rhagor…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Oeddech chi'n bwriadu mynd i %S?
keywordURIFixup.goTo = Oeddwn, cymrwch fi i %S
keywordURIFixup.goTo.accesskey = O
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Diweddaru %S
update.downloadAndInstallButton.accesskey = D
menuOpenAllInTabs.label = Agor Popeth mewn Tabiau
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Ail lwytho'r dudalen hon
tabHistory.goBack = Nôl i'r dudalen hon
tabHistory.goForward = Mynd ymlaen i'r dudalen hon
# URL Bar
pasteAndGo.label = Gludo a Mynd
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Ail lwytho'r dudalen gyfredol (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Peidio llwytho'r dudalen hon (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Ailosod lefel chwyddo (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Toglo golwg darllenydd (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, Ailosod lefel chwyddo
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Dangos eich nodau tudalen (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Dangos cynnydd y llwytho i lawr cyfredol (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Agor ffenestr newydd (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Agor tab newydd (%S)
newTabContainer.tooltip = Agorwch dab newydd (%S)\nPwyso a'i ddal i agor tab cynhwysydd newydd
newTabAlwaysContainer.tooltip = Dewiswch gynhwysydd i agor tab newydd
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Caniatáu i %S ddefnyddio'ch data delwedd cynfas HTML5?
canvas.siteprompt2.warning = Gall hyn gael ei ddefnyddio i adnabod unigrywedd eich cyfrifiadur.
canvas.block = Rhwystro
canvas.block.accesskey = R
canvas.allow2 = Caniatáu
canvas.allow2.accesskey = C
canvas.remember2 = Cofio'r penderfyniad yma
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Dilyswyd gan: %S
identity.identified.verified_by_you = Rydych wedi ychwanegu eithriad diogelwch ar gyfer y wefan hon.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Tystysgrif wedi'i ryddhau i: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Dim yn Ddiogel
identity.notSecure.tooltip = Nid yw'r cysylltiad yn ddiogel
identity.extension.label = Estyniad (%S)
identity.extension.tooltip = Llwythwyd gan estyniad: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Lleihau (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Ailosod lefel chwyddo (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Cynyddu (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Torri (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Copïo (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Gludo (%S)
geolocation.allow = Caniatáu
geolocation.allow.accesskey = C
geolocation.block = Rhwystro
geolocation.block.accesskey = R
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Bydd hyn yn agor gosodiadau lleoliad system. Rhowch ganiatâd lleoliad i %S.
geolocation.shareWithSite4 = Caniatáu i %S gael mynediad i'ch lleoliad?
geolocation.shareWithFile4 = Caniatáu i'r ffeil leol hon gael mynediad i'ch lleoliad?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Caniatáu i %1$S roi caniatâd i %2$S gael mynediad i'ch lleoliad?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Rhoi caniatâd lleoliad %S yng ngosodiadau'r system.
geolocation.systemSettingsTitle = Yn aros am Ganiatâd Lleoliad
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Bydd y system yn gofyn i chi roi'r caniatâd hwn i %S.
geolocation.remember = Cofio'r penderfyniad yma
# Virtual Reality Device UI
xr.allow2 = Caniatáu
xr.allow2.accesskey = C
xr.block = Rhwystro
xr.block.accesskey = R
xr.shareWithSite4 = Caniatáu i %S gael mynediad at ddyfeisiau rhithrealaeth? Gall hyn ddatgelu gwybodaeth sensitif.
xr.shareWithFile4 = Caniatáu i %S gael mynediad at ddyfeisiau rhithrealaeth? Gall hyn ddatgelu gwybodaeth sensitif.
xr.remember = Cofio'r penderfyniad yma
# Persistent storage UI
persistentStorage.allow = Caniatáu
persistentStorage.allow.accesskey = C
persistentStorage.block.label = Rhwystro
persistentStorage.block.accesskey = R
persistentStorage.allowWithSite2 = Caniatáu i %S storio data mewn storfa barhaus?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Caniatáu
webNotifications.allow2.accesskey = C
webNotifications.notNow = Nid Nawr
webNotifications.notNow.accesskey = n
webNotifications.never = Byth Caniatáu
webNotifications.never.accesskey = b
webNotifications.alwaysBlock = Rhwystro Bob Tro
webNotifications.alwaysBlock.accesskey = R
webNotifications.block = Rhwystro
webNotifications.block.accesskey = R
webNotifications.receiveFromSite3 = Caniatáu i %S anfon hysbysiadau?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = Mae %S eisiau cael mynediad i apiau a gwasanaethau eraill ar y ddyfais hon.
localhost.remember2 = Cofio fy newis ar gyfer y wefan hon
localhost.allowlabel = Caniatáu
localhost.blocklabel = Rhwystro
localhost.allow.accesskey = C
localhost.block.accesskey = R
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = Mae %S eisiau cael mynediad i apiau a gwasanaethau eraill ar ddyfeisiau eraill ar eich rhwydwaith leol.
localNetwork.remember2 = Cofio fy newis ar gyfer y wefan hon
localNetwork.allowLabel = Caniatáu
localNetwork.allow.accesskey = C
localNetwork.blockLabel = Rhwystro
localNetwork.block.accesskey = R
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Allan o fan hyn!
safebrowsing.getMeOutOfHereButton.accessKey = A
safebrowsing.deceptiveSite = Gwefan Twyllodrus!
safebrowsing.notADeceptiveSiteButton.label = Nid yw hon yn wefan twyllodrus…
safebrowsing.notADeceptiveSiteButton.accessKey = t
safebrowsing.reportedAttackSite = Gwefan Ymosod Hysbys!
safebrowsing.notAnAttackButton.label = Nid gwefan ymosodiad yw hwn…
safebrowsing.notAnAttackButton.accessKey = y
safebrowsing.reportedUnwantedSite = Gwefan Meddalwedd Digroeso Hysbys!
safebrowsing.reportedHarmfulSite = Gwefan Niweidiol Hysbys!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Chwilio %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Ailgychwyn %S yn y Modd Datrys Problemau?
troubleshootModeRestartPromptMessage = Bydd eich ychwanegion a'ch gosodiadau cyfaddas yn cael eu hanalluogi dros dro.
troubleshootModeRestartButton = Ailgychwyn
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Mae'r dudalen hon yn arafu %1$S. I gyflymu'ch porwr, stopiwch y dudalen hon.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Mae tudalen gwe'n arafu %1$S. I gyflymu'ch porwr, stopiwch y dudalen honno.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = Mae “%1$S” yn arafu %2$S. I gyflymu'ch porwr, stopiwch y dudalen honno.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = Mae “%1$S” yn arafu %2$S. I gyflymu'ch porwr, stopiwch yr estyniad hwnnw.
processHang.add-on.learn-more.text = Darllen rhagor
processHang.button_stop2.label = Atal
processHang.button_stop2.accessKey = A
processHang.button_debug.label = Sgript Dadfygio
processHang.button_debug.accessKey = S
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Dangos y ffenestr yn y sgrin lawn (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Symud y Bar Ochr i'r Chwith
sidebar.moveToRight = Symud y Bar Ochr i'r Dde
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Rhaid galluogi DRM i chwarae'r sain neu'r fideo sydd ar y dudalen hon. %S
emeNotifications.drmContentDisabled.button.label = Galluogi DRM
emeNotifications.drmContentDisabled.button.accesskey = G
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = Mae %S yn gosod cydrannau sydd eu hangen i chwarae'r sain a'r fideo ar y dudalen hon. Ceisiwch eto'n hwyrach ymlaen.
emeNotifications.unknownDRMSoftware = Anhysbys
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Cyfaddasu %S
decoder.noCodecs.button = Sut mae gwneud
decoder.noCodecs.accesskey = D
decoder.noCodecsLinux.message = I chwarae fideo, efallai y bydd angen gosod y codecsau fideo angenrheidiol.
decoder.noHWAcceleration.message = I wella ansawdd y fideo, efallai y bydd angen gosod y Microsoft Media Feature Pack.
decoder.noPulseAudio.message = I chwarae sain, efallai y bydd angen gosod y feddalwedd PulseAudio angenrheidiol.
decoder.unsupportedLibavcodec.message = Gall libavcodec fod yn fregus neu heb ei gynnal a dylai gael ei ddiweddaru ar gyfer chwarae fideo.
decoder.decodeError.message = Digwyddodd gwall wrth ddadgodio adnodd cyfrwng.
decoder.decodeError.button = Adrodd am fater gwefan
decoder.decodeError.accesskey = A
decoder.decodeWarning.message = Digwyddodd gwall adferadwy wrth ddadgodio adnodd cyfrwng.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Rhaid i chi fewngofnodi i'r rhwydwaith hwn cyn i chi gael mynediad i'r Rhyngrwyd.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Agor Tudalen Mewngofnodi i'r Rhwydwaith
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Caniatâd ar gyfer: %S
permissions.remove.tooltip = Clirio'r caniatâd a gofyn eto
permissions.fullscreen.promptCanceled = Diddymu ceisiadau am ganiatâd: peidiwch cyhoeddi ceisiadau am ganiatâd cyn mynd i mewn i sgrin lawn DOM.
permissions.fullscreen.fullScreenCanceled = Sgrin lawn DOM wedi'u Gadael: peidiwch cyhoeddi ceisiadau am ganiatâd tra ar sgrin lawn DOM.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64 did
aboutDialog.architecture.thirtyTwoBit = 32 did
midi.allow.label = Caniatáu
midi.allow.accesskey = C
midi.block.label = Rhwystro
midi.block.accesskey = R
midi.remember = Cofio'r penderfyniad yma
midi.shareWithFile = Caniatáu i'r ffeil leol hon gael mynediad i'ch dyfais MIDI?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Caniatáu i %S gael mynediad at eich dyfeisiau MIDI?
midi.shareSysexWithFile = Caniatáu i'r ffeil leol hon gael mynediad at eich dyfeisiau MIDI ac anfon/derbyn negeseuon SysEx?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Caniatáu i %S gael mynediad at eich dyfeisiau MIDI ac anfon/derbyn negeseuon SysEx?
serial.allow.label = Caniatáu
serial.allow.accesskey = C
serial.block.label = Rhwystro
serial.block.accesskey = R
serial.shareWithFile = Caniatáu i'r ffeil leol hon gael mynediad i'ch pyrth cyfresol?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Caniatáu i %S gael mynediad i'ch pyrth cyfresol?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Nôl
storageAccess1.Allow.label = Caniatáu
storageAccess1.Allow.accesskey = C
storageAccess1.DontAllow.label = Rhwystro
storageAccess1.DontAllow.accesskey = R
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Caniatáu i %1$S ddefnyddio ei gwcis ar %2$S?
storageAccess1.hintText = Efallai y byddwch am rwystro mynediad os nad yw'n glir pam mae angen y data hwn ar %1$S.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Chwiliwch ar y we am “%S”
