# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host }କୁ ଅବଲୋକନ କରୁଅଛି…
network-connection-status-connected = { $host } ସହିତ ସଂଯୁକ୍ତ…
network-connection-status-sending-request = { $host }କୁ ଅନୁରୋଧ ପଠାଯାଉଛି…
network-connection-status-transferring-data = { $host }ରୁ ତଥ୍ୟ ସ୍ଥାନାନ୍ତରଣ କରାଯାଉଛି…
network-connection-status-connecting = { $host } ସହିତ ସଂଯୋଗ ହେଉଛି…
network-connection-status-read = { $host } କୁ ପଢ଼ନ୍ତୁ
network-connection-status-wrote = { $host } ଲେଖନ୍ତୁ
network-connection-status-waiting = { $host } କୁ ଅପେକ୍ଷା କରିଛି…
network-connection-status-looked-up = { $host } କୁ ଦେଖିସାରିଛି …
