# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = x
import-from-360se =
    .label = 360 Secure Browser
    .accesskey = 3
import-select-profile-title =
    .label = Seleccionar perfil
import-done-title =
    .label = N'tsinu n'dakian
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = Ña { $source }
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-safari = Safari
source-name-canary = Safari
source-name-chrome = Google Chrome
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Secure Browser
imported-safari-reading-list = Lista kavii (Ña Safari)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Opciones de Internet
    .value = Opciones de Internet
browser-data-edge-1 =
    .label = Nda sama
    .value = Nda sama
browser-data-safari-1 =
    .label = Preferencias
    .value = Preferencias
browser-data-chrome-1 =
    .label = Preferencias
    .value = Preferencias
browser-data-canary-1 =
    .label = Preferencias
    .value = Preferencias
browser-data-360se-1 =
    .label = Preferences
    .value = Preferences
browser-data-ie-2 =
    .label = Cookies
    .value = Cookies
browser-data-edge-2 =
    .label = Cookies
    .value = Cookies
browser-data-safari-2 =
    .label = Cookies
    .value = Cookies
browser-data-chrome-2 =
    .label = Cookies
    .value = Cookies
browser-data-canary-2 =
    .label = Cookies
    .value = Cookies
browser-data-firefox-2 =
    .label = Cookies
    .value = Cookies
browser-data-360se-2 =
    .label = Cookies
    .value = Cookies
browser-data-ie-4 =
    .label = Nda nduku ña niya'a
    .value = Nda nduku ña niya'a
browser-data-edge-4 =
    .label = Nda nduku ña niya'a
    .value = Nda nduku ña niya'a
browser-data-safari-4 =
    .label = Nda nduku ña niya'a
    .value = Nda nduku ña niya'a
browser-data-chrome-4 =
    .label = Nda nduku ña niya'a
    .value = Nda nduku ña niya'a
browser-data-canary-4 =
    .label = Nda nduku ña niya'a
    .value = Nda nduku ña niya'a
browser-data-firefox-history-and-bookmarks-4 =
    .label = Nda nduku ña niya'a tsi marcadores
    .value = Nda nduku ña niya'a tsi marcadores
browser-data-360se-4 =
    .label = Nda nduku ña niya'a
    .value = Nda nduku ña niya'a
browser-data-ie-8 =
    .label = Chika vaà formulario ña niya'a
    .value = Chika vaà formulario ña niya'a
browser-data-edge-8 =
    .label = Chika vaà formulario ña niya'a
    .value = Chika vaà formulario ña niya'a
browser-data-safari-8 =
    .label = Chika vaà formulario ña niya'a
    .value = Chika vaà formulario ña niya'a
browser-data-chrome-8 =
    .label = Chika vaà formulario ña niya'a
    .value = Chika vaà formulario ña niya'a
browser-data-canary-8 =
    .label = Chika vaà formulario ña niya'a
    .value = Chika vaà formulario ña niya'a
browser-data-firefox-8 =
    .label = Chika vaà formulario ña niya'a
    .value = Chika vaà formulario ña niya'a
browser-data-360se-8 =
    .label = Chika vaà formulario ña niya'a
    .value = Chika vaà formulario ña niya'a
browser-data-ie-16 =
    .label = Contraseña inka va'a
    .value = Contraseña inka va'a
browser-data-edge-16 =
    .label = Contraseña inka va'a
    .value = Contraseña inka va'a
browser-data-safari-16 =
    .label = Contraseña inka va'a
    .value = Contraseña inka va'a
browser-data-chrome-16 =
    .label = Contraseña inka va'a
    .value = Contraseña inka va'a
browser-data-canary-16 =
    .label = Contraseña inka va'a
    .value = Contraseña inka va'a
browser-data-firefox-16 =
    .label = Contraseña inka va'a
    .value = Contraseña inka va'a
browser-data-360se-16 =
    .label = Contraseña inka va'a
    .value = Contraseña inka va'a
browser-data-ie-32 =
    .label = Favorito
    .value = Favorito
browser-data-edge-32 =
    .label = Favorito
    .value = Favorito
browser-data-safari-32 =
    .label = Marcadores
    .value = Marcadores
browser-data-chrome-32 =
    .label = Marcadores
    .value = Marcadores
browser-data-canary-32 =
    .label = Marcadores
    .value = Marcadores
browser-data-360se-32 =
    .label = Marcadores
    .value = Marcadores
browser-data-ie-64 =
    .label = Inka tutù
    .value = Inka tutù
browser-data-edge-64 =
    .label = Inka tutù
    .value = Inka tutù
browser-data-safari-64 =
    .label = Inka tutù
    .value = Inka tutù
browser-data-chrome-64 =
    .label = Inka tutù
    .value = Inka tutù
browser-data-canary-64 =
    .label = Inka tutù
    .value = Inka tutù
browser-data-firefox-other-64 =
    .label = Inka tutù
    .value = Inka tutù
browser-data-360se-64 =
    .label = Inka tutù
    .value = Inka tutù
browser-data-firefox-128 =
    .label = Ventana tsi pestañas
    .value = Ventana tsi pestañas
