# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host } တွင် ရှာနေသည်…
network-connection-status-connected = { $host } ကို ချိတ်ဆက်ထားသည်…
network-connection-status-sending-request = { $host } သို့ တောင်းဆိုမှု ပေးပို့နေသည်…
network-connection-status-transferring-data = { $host } ထံမှ အချက်အလက်များ ရယူလွှဲပြောင်းနေသည်…
network-connection-status-connecting = { $host } သို့ ချိတ်ဆက်နေသည်…
network-connection-status-read = { $host } ကို ဖတ်ပါ
network-connection-status-wrote = { $host } ကို ရေးမှတ်ခဲ့သည်
network-connection-status-waiting = { $host } ကို စောင့်ဆိုင်းနေသည်…
network-connection-status-looked-up = { $host } တွင် ရှာခဲ့သည်…
