# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Ukuqala phezulu { $host }...
network-connection-status-connected = Kuhlanganiswe ne { $host }...
network-connection-status-sending-request = Ukuthumela isibawo ku { $host }...
network-connection-status-transferring-data = Ukususa imininingwane ku { $host }...
network-connection-status-connecting = Ukuzihlanganisa ne { $host }...
network-connection-status-read = Kufundwe { $host }
network-connection-status-wrote = Kutlolwe { $host }
network-connection-status-waiting = Kulindelwe i-{ $host }...
