# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Tajin nisol ri rochochib'al { $host }…
network-connection-status-connected = Ximon rik'in { $host }…
network-connection-status-sending-request = Tajin nitaq chilab'enïk chi re ri { $host }…
network-connection-status-connecting = Tajin nok rik'in { $host }…
network-connection-status-wrote = Tzib'an { $host }
network-connection-status-waiting = Tajin noyob'ëx chi { $host }…
network-connection-status-looked-up = Xilitäj { $host }…
network-connection-status-tls-handshake = Kib'anik jun TLS handshake pa { $host }…
network-connection-status-tls-handshake-finished = Ri TLS Handshaker xk'is richin { $host }…
