# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = I khou lavhelesa { $host }...
network-connection-status-connected = Yo tumana na { $host }...
network-connection-status-sending-request = I khou rumela khumbelo kha { $host }...
network-connection-status-transferring-data = I khou rathisela vhutanzi u bva kha { $host }...
network-connection-status-connecting = I khou tumana na { $host }...
network-connection-status-read = Vhalani { $host }…
network-connection-status-wrote = Yo Nwala { $host }…
network-connection-status-waiting = Yo lindela { $host }...
