# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dateformat-label =
    .value = Формат дати:
    .accesskey = Ф
#   $date (String) - the formatted example date
dateformat-long =
    .label = Повний: { $date }
#   $date (String) - the formatted example date
dateformat-short =
    .label = Стислий: { $date }
weekstart-label =
    .value = Перший день тижня:
    .accesskey = П
day-1-name =
    .label = Неділя
day-2-name =
    .label = Понеділок
day-3-name =
    .label = Вівторок
day-4-name =
    .label = Середа
day-5-name =
    .label = Четвер
day-6-name =
    .label = П’ятниця
day-7-name =
    .label = Субота
dayweek-legend = Вигляд дня і тижня
visible-hours-label =
    .value = Показувати:
    .accesskey = о
visible-hours-end-label =
    .value = годин одразу
day-start-label =
    .value = День починається о:
    .accesskey = Д
day-end-label =
    .value = День закінчується о:
    .accesskey = к
midnight-label =
    .label = Опівночі
noon-label =
    .label = Опівдні
multiweek-legend = Вигляд кількох тижнів
number-of-weeks-label =
    .value = Показувати типово тижнів (включно з попередніми тижнями):
    .accesskey = е
week-0-label =
    .label = жодного
week-1-label =
    .label = 1 тиждень
week-2-label =
    .label = 2 тижні
week-3-label =
    .label = 3 тижні
week-4-label =
    .label = 4 тижні
week-5-label =
    .label = 5 тижнів
week-6-label =
    .label = 6 тижнів
previous-weeks-label =
    .value = Показувати попередніх тижнів:
    .accesskey = П
accessibility-legend = Доступність
accessibility-colors-label =
    .label = Оптимізувати кольори для доступності
    .accesskey = к
reminder-legend = При настанні часу сповіщення:
reminder-play-checkbox =
    .label = Відтворювати звук
    .accesskey = з
reminder-default-sound-label =
    .label = Використовувати типовий звук
    .accesskey = т
reminder-browse-sound-label =
    .label = Вибрати…
    .accesskey = В
reminder-dialog-label =
    .label = Показати вікно сповіщення
    .accesskey = к
reminder-default-legend = Типові значення для сповіщень
event-alarm-label =
    .value = Типові налаштування сповіщень для подій:
    .accesskey = п
alarm-on-label =
    .label = Вмикн.
alarm-off-label =
    .label = Вимкн.
task-alarm-label =
    .value = Типові налаштування сповіщень для завдань:
    .accesskey = з
event-alarm-time-label =
    .value = Типовий час сповіщення перед подією:
    .accesskey = с
task-alarm-time-label =
    .value = Типовий час сповіщення перед завданням:
    .accesskey = в
category-edit-label = Редагувати категорію
category-overwrite-title = Попередження: Однакові назви
category-overwrite = Категорія з такою назвою вже існує. Чи Ви хочете переписати її?
category-blank-warning = Ви повинні зазначити назву категорії.
