# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-intro = { -brand-full-name } is vrije en opensourcesoftware, gebouwd door een gemeenschap van duizenden mensen over de hele wereld. Er zijn een paar zaken die u moet weten:
rights-intro-point-1 = { -brand-short-name } wordt beschikbaar gesteld onder de voorwaarden van de <a data-l10n-name="mozilla-public-license-link">Mozilla Public License</a>. Dit betekent dat u { -brand-short-name } mag gebruiken, kopiëren en naar anderen mag distribueren. Ook mag u de broncode van { -brand-short-name } modificeren naar een vorm die aan uw eisen voldoet. De Mozilla Public License geeft u tevens het recht uw aangepaste versies te distribueren.
rights-intro-point-2 = Er worden u geen rechten of licenties verleend op de handelsmerken van de Mozilla Foundation of enige andere partij, met inbegrip van en zonder beperking tot de naam of het logo van Firefox. Aanvullende informatie over handelsmerken is <a data-l10n-name="mozilla-trademarks-link">hier</a> te vinden.
rights-intro-point-5 = Sommige { -brand-short-name }-functies maken gebruik van webgebaseerde informatiediensten. We kunnen echter niet garanderen dat deze 100% nauwkeurig of foutvrij zijn. Meer details, waaronder informatie over het uitschakelen van de functies die deze diensten gebruiken, is te vinden in de <a data-l10n-name="mozilla-service-terms-link">servicevoorwaarden</a>.
rights-intro-point-5-unbranded = Als in dit product webdiensten zijn opgenomen, dienen enige van toepassing zijnde servicevoorwaarden voor deze dienst(en) te worden gekoppeld aan de sectie <a data-l10n-name="mozilla-website-services-link">Websitediensten</a>.
rights-webservices-header = Webgebaseerde informatiediensten van { -brand-full-name }
rights-safebrowsing-term-1 = Open de toepassingsvoorkeuren
rights-safebrowsing-term-2 = Selecteer de sectie Beveiliging
rights-locationawarebrowsing-term-1 = Typ in de URL-balk <code>about:config</code>
rights-locationawarebrowsing-term-2 = Typ geo.enabled
rights-locationawarebrowsing-term-3 = Dubbelklik op de voorkeursinstelling geo.enabled
rights-locationawarebrowsing-term-4 = Locatiebewust navigeren is nu uitgeschakeld
rights-webservices-term-2 = { -vendor-short-name } kan de Diensten naar eigen goeddunken discontinueren of wijzigen.
rights-webservices-term-3 = U kunt deze Diensten gebruiken met de bijgeleverde versie van { -brand-short-name }, en { -vendor-short-name } geeft u alle benodigde rechten om dit te doen. { -vendor-short-name } en zijn licentiegevers behouden alle overige rechten in de Diensten. Deze voorwaarden zijn niet bedoeld om enige rechten die zijn verleend onder opensourcelicenties welke van toepassing zijn op { -brand-short-name } en overeenkomende broncodeversies van { -brand-short-name } te beperken.
rights-webservices-term-4 = <strong>De Diensten worden aangeboden zonder enige garantie. { -vendor-short-name }, zijn medewerkers, licentiegevers en distributeurs wijzen alle uitdrukkelijke of impliciete garanties af, met inbegrip van, maar niet beperkt tot garanties van verhandelbaarheid en geschiktheid van de Diensten voor een bepaald doel. U draagt de volledige verantwoordelijkheid wat betreft het selecteren van de Diensten voor uw doeleinden en wat betreft de kwaliteit en prestaties van de Diensten. Sommige wetgevingen staan uitsluitingen of beperkingen van impliciete garanties niet toe, dus mogelijk is deze disclaimer op u niet van toepassing.</strong>
rights-webservices-term-5 = <strong>Behoudens zoals vereist bij de wet zijn { -vendor-short-name }, zijn medewerkers, licentiegevers en distributeurs niet aansprakelijk voor enige indirecte, speciale, incidentele, straffende of gevolgschade voortvloeiend uit of op enige manier verband houdend met het gebruik van { -brand-short-name } en de Diensten. De collectieve aansprakelijkheid onder deze voorwaarden zal het bedrag van $500 (vijfhonderd dollar) niet overschrijden. Sommige wetgevingen staan uitsluitingen of beperkingen van bepaalde garanties niet toe, dus mogelijk zijn deze uitsluiting en beperking op u niet van toepassing.</strong>
rights-webservices-term-6 = { -vendor-short-name } is te allen tijde gerechtigd deze voorwaarden te wijzigen. Deze voorwaarden mogen niet worden gewijzigd of geannuleerd zonder schriftelijke toestemming van { -vendor-short-name }.
