#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

# LOCALIZATION NOTE: Some of these URLs are currently 404s, but should be coming
# online shortly.

# LOCALIZATION NOTE (bookmarks_title):
# title for the folder that will contains the default bookmarks
#define bookmarks_title Telefonìn

# LOCALIZATION NOTE (bookmarks_aboutBrowser):
# link title for about:fennec
#define bookmarks_aboutBrowser Firefox: in sce o têu navegatô

# LOCALIZATION NOTE (bookmarks_addons):
# link title for https://addons.mozilla.org/en-US/mobile
#define bookmarks_addons Firefox: Personalìzza i teu conponénti azónti

# LOCALIZATION NOTE (bookmarks_support):
# link title for https://support.mozilla.org/mobile
#define bookmarks_support Firefox: agiùtto

# LOCALIZATION NOTE (bookmarks_aboutHome):
# link title for about:home
#define bookmarks_aboutHome Inìçio do Firefox

#unfilter emptyLines
