#filter emptyLines
# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title Takku


#define bookmarks_heading Takku


#define bookmarks_toolbarfolder Banqaasu bopp


#define bookmarks_toolbarfolder_description Yokk ay takku ci wayndare bi boo leen bëggee gis ci banqaasu bopp


# LOCALIZATION NOTE (getting_started):

# link title for http://en-US.www.mozilla.com/en-US/firefox/central/

#define getting_started Ci yoonu tambali


# LOCALIZATION NOTE (firefox_heading):

# Firefox links folder name

#define firefox_heading Mosiyaa faayafoks


# LOCALIZATION NOTE (firefox_help):

# link title for http://en-US.www.mozilla.com/en-US/firefox/help/

#define firefox_help Ndimbal ak gindeekukaay


# LOCALIZATION NOTE (firefox_customize):

# link title for http://en-US.www.mozilla.com/en-US/firefox/customize/

#define firefox_customize Solal Faayafoks


# LOCALIZATION NOTE (firefox_community):

# link title for http://en-US.www.mozilla.com/en-US/firefox/community/

#define firefox_community Jàpp leen ci !


# LOCALIZATION NOTE (firefox_about):

# link title for http://en-US.www.mozilla.com/en-US/about/

#define firefox_about Ci mbirum Mozilla


#unfilter emptyLines