# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Notice: If you're updating this list, you should also
###         update the list in mozIntl.js.

region-name-ad = Andoora
region-name-ag = Antiguwa nda Barbuuda
region-name-ai = Angiila
region-name-am = Armeeniya
region-name-ao = Angoola
region-name-aq = Antarkitika
region-name-ar = Aržentiina
region-name-as = Ameriki Samoowa
region-name-at = Otiriši
region-name-au = Osutarali
region-name-aw = Aruuba
region-name-az = Azerbayjan
region-name-bd = Bangaladeeši
region-name-be = Belžiki
region-name-bf = Burkina Faaso
region-name-bg = Bulgaari
region-name-bh = Baharayn
region-name-bi = Burundi
region-name-bj = Beneŋ
region-name-bm = Bermuuda
region-name-bo = Boliiwi
region-name-br = Berezil
region-name-bv = Buuwe gungu
region-name-bw = Botusuwaana
region-name-by = Beelaarusu
region-name-bz = Beeliizi
region-name-ca = Kaanaada
region-name-cc = Kokosu (Kiiliŋ) gungey
region-name-ch = Suwiisu
region-name-ck = Kuuku gungey
region-name-cl = Šilli
region-name-cm = Kaamerun
region-name-cn = Šin
region-name-co = Kolonbi
region-name-cr = Kostariika
region-name-cu = Kuuba
region-name-cx = Kirisimaasu gungu
region-name-cy = Šiipuru
region-name-cz = Ceki laama
region-name-de = Alemaaɲi
region-name-dj = Jibuuti
region-name-dk = Danmark
region-name-dm = Dominika
region-name-do = Dominiki laama
region-name-dz = Alžeeri
region-name-ec = Ekuwador
region-name-ee = Estooni
region-name-eg = Ežibti
region-name-er = Eritere
region-name-et = Ecoopi
region-name-fi = Finlandi
region-name-fj = Fiiji
region-name-fo = Feero gungey
region-name-fr = Faranši
region-name-ga = Gaaboŋ
region-name-gd = Gerenada
region-name-ge = Žorži
region-name-gg = Gerenesey
region-name-gh = Gaana
region-name-gn = Gine
region-name-gp = Guwadelupu
region-name-gq = Ekuwater Gine
region-name-gr = Geresi
region-name-gt = Guwatemaala
region-name-gw = Gine-Bisaw
region-name-gy = Guwiyaana
region-name-hn = Honduura
region-name-hr = Korowaasi
region-name-ht = Hayti
region-name-hu = Hongiri
region-name-id = Indoneezi
region-name-ie = Irlandi
region-name-il = Izirayel
region-name-in = Indu
region-name-io = Briteŋ indu teekoo ganda
region-name-is = Islandi
region-name-it = Itaali
region-name-jm = Jamayka
region-name-jo = Žordaani
region-name-jp = Žaapoŋ
region-name-ke = Keniya
region-name-kg = Kirgiizistan
region-name-kh = Kanboodiya
region-name-ki = Kiribaati
region-name-km = Komooro (Komooro gungey)
region-name-kn = Seŋ Kiti nda Neewisi
region-name-ky = Kaymaan gungey
region-name-la = Laawosu
region-name-lb = Liiban
region-name-lc = Seŋt Luuša
region-name-li = Lišitensitayn
region-name-lk = Širi Lankaa
region-name-lr = Liberiya
region-name-ls = Leesooto
region-name-lt = Lituwaani
region-name-lu = Lukusanburugu
region-name-lv = Laatiwi (Leetooni)
region-name-ly = Libi
region-name-ma = Marooku
region-name-mc = Monaako
region-name-md = Moldoowa
region-name-me = Montenegoro
region-name-mf = Seŋ Marteŋ
region-name-mg = Maadagaskar
region-name-mh = Marišaal gungey
region-name-ml = Maali
region-name-mn = Mongooli
region-name-mp = Hawsa Mariyana gungey
region-name-mq = Martiniki
region-name-ms = Monseraati
region-name-mt = Malti
region-name-mu = Mooriši
region-name-mv = Maldiiwi
region-name-mw = Malaawi
region-name-my = Maaleezi
region-name-mz = Moozanbiki
region-name-nc = Kaleedooni taaga
region-name-ne = Niižer
region-name-nf = Norufolku gungu
region-name-ng = Naajiriya
region-name-nl = Hoolandu
region-name-no = Norweeži
region-name-pa = Panaama
region-name-pe = Peeru
region-name-pf = Faranši Polineezi
region-name-pg = Papuwa Gine taaga
region-name-ph = Filipin
region-name-pk = Paakistan
region-name-pl = Poloɲ
region-name-pm = Seŋ Piyer nda Miikeloŋ
region-name-pr = Portoriiko
region-name-pt = Portugal
region-name-pw = Palaawu
region-name-py = Paraaguway
region-name-qa = Katar
region-name-ro = Urumaani
region-name-rs = Serbi
region-name-rw = Uruwanda
region-name-sa = Sawudiya (Sawdi Arabiyya)
region-name-sb = Salomon gungey
region-name-sc = Seyšel
region-name-se = Suweedi
region-name-si = Soloweeni
region-name-sk = Solowaaki
region-name-sl = Siyera Leewon
region-name-sm = San Mariino
region-name-sn = Senegal
region-name-sr = Suurinam
region-name-st = Sawo Toome nda Pirinsiipe
region-name-sz = Suwaziilandu
region-name-tc = Turkey nda Kaykosu gungey
region-name-td = Caad
region-name-tg = Togo
region-name-tj = Taajiikisitan
region-name-tk = Tokeelaawu
region-name-tl = Timor-Leste (Timor Dandi)
region-name-to = Tonga
region-name-tr = Turkii
region-name-tv = Tuwaalu
region-name-tw = Taywan
region-name-tz = Tanzaani
region-name-ug = Uganda
region-name-us = Laama margantey
region-name-uy = Uruguway
region-name-uz = Uzbeekistan
region-name-ve = Wenezuweela
region-name-vu = Wanuwaatu
region-name-wf = Walisi nda Futuna
region-name-ws = Samoowa
region-name-ye = Yeemen
region-name-yt = Mayooti
region-name-za = Gurma Afiriki (Sudafirika)
region-name-zm = Zanbi
region-name-zw = Zinbaabuwe
