# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Przekroczono limit czasu
openFile = Otwórz plik
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Szukaj „%2$S” w %1$S
contextMenuSearch.accesskey = S
contextMenuPrivateSearch = Szukaj w prywatnym oknie
contextMenuPrivateSearch.accesskey = u
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Szukaj w %S w prywatnym oknie
contextMenuPrivateSearchOtherEngine.accesskey = u
bookmarkAllTabsDefault = [Nazwa folderu]
unsignedAddonsDisabled.message = Jeden lub więcej dodatków nie mogło zostać zweryfikowanych i zostały wyłączone.
unsignedAddonsDisabled.learnMore.label = Więcej informacji
unsignedAddonsDisabled.learnMore.accesskey = W
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Ostatni dostęp %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = Odnośniki typu %S://
crashedpluginsMessage.title = Wtyczka %S uległa awarii.
crashedpluginsMessage.reloadButton.label = Odśwież stronę
crashedpluginsMessage.reloadButton.accesskey = O
crashedpluginsMessage.submitButton.label = Prześlij zgłoszenie błędu
crashedpluginsMessage.submitButton.accesskey = P
crashedpluginsMessage.learnMore = Więcej informacji…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Wyszukano „%S”, ale jest to jednak również adres — przejść do niego?
keywordURIFixup.goTo = Przejdź do %S
keywordURIFixup.goTo.accesskey = P
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Uaktualnij do wersji %S
update.downloadAndInstallButton.accesskey = U
menuOpenAllInTabs.label = Otwórz wszystkie w kartach
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Odśwież tę stronę
tabHistory.goBack = Przejdź do tej strony (wstecz)
tabHistory.goForward = Przejdź do tej strony (do przodu)
# URL Bar
pasteAndGo.label = Wklej i przejdź
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Odśwież bieżącą stronę (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Zatrzymaj wczytywanie bieżącej strony (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Przywróć oryginalny rozmiar (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Przełącz poprawianie czytelności (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, przywróć oryginalny rozmiar
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Wyświetl zakładki (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Pokaż postęp pobierania plików (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Otwórz w nowym oknie (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Otwórz nową kartę (%S)
newTabContainer.tooltip = Otwórz nową kartę (%S)\nNaciśnij i przytrzymaj, aby otworzyć nową kartę w kontenerze
newTabAlwaysContainer.tooltip = Wybierz kontener, w którym otworzyć nową kartę
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Czy zezwolić witrynie „%S” na dostęp do danych obrazów HTML5 canvas?
canvas.siteprompt2.warning = Może to być wykorzystane do unikalnej identyfikacji tego urządzenia.
canvas.block = Zablokuj
canvas.block.accesskey = b
canvas.allow2 = Zezwól
canvas.allow2.accesskey = Z
canvas.remember2 = Pamiętaj tę decyzję
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Zweryfikowana przez: %S
identity.identified.verified_by_you = Użytkownik dodał wyjątek od reguł bezpieczeństwa dla tej witryny.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Certyfikat wystawiony dla: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Niezabezpieczone
identity.notSecure.tooltip = Połączenie nie jest bezpieczne
identity.extension.label = Rozszerzenie (%S)
identity.extension.tooltip = Wczytano przez rozszerzenie: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Pomniejsz (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Przywróć oryginalny rozmiar (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Powiększ (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Wytnij (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Kopiuj (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Wklej (%S)
geolocation.allow = Udostępnij
geolocation.allow.accesskey = U
geolocation.block = Nie udostępniaj
geolocation.block.accesskey = N
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Spowoduje to otwarcie systemowych ustawień położenia. Udziel przeglądarce %S uprawnienie do korzystania z informacji o położeniu.
geolocation.shareWithSite4 = Czy udostępnić witrynie „%S” informacje o położeniu?
geolocation.shareWithFile4 = Czy udostępnić temu lokalnemu plikowi informacje o położeniu?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Czy zezwolić witrynie „%1$S” na udostępnienie dostępu do informacji o położeniu witrynie „%2$S”?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Udziel przeglądarce %S uprawnienie do korzystania z informacji o położeniu w ustawieniach systemu.
geolocation.systemSettingsTitle = Oczekiwanie na uprawnienie do korzystania z informacji o położeniu
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = System poprosi o udzielenie tego uprawnienia przeglądarce %S.
geolocation.remember = Pamiętaj tę decyzję
# Virtual Reality Device UI
xr.allow2 = Zezwól
xr.allow2.accesskey = Z
xr.block = Zablokuj
xr.block.accesskey = b
xr.shareWithSite4 = Czy zezwolić witrynie „%S” na dostęp do urządzeń rzeczywistości wirtualnej? Może to ujawnić prywatne dane.
xr.shareWithFile4 = Czy zezwolić temu lokalnemu plikowi na dostęp do urządzeń rzeczywistości wirtualnej? Może to ujawnić prywatne dane.
xr.remember = Pamiętaj tę decyzję
# Persistent storage UI
persistentStorage.allow = Zezwól
persistentStorage.allow.accesskey = Z
persistentStorage.block.label = Zablokuj
persistentStorage.block.accesskey = b
persistentStorage.allowWithSite2 = Czy zezwolić witrynie „%S” na przechowywanie danych na komputerze?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Odbieraj
webNotifications.allow2.accesskey = O
webNotifications.notNow = Nie teraz
webNotifications.notNow.accesskey = t
webNotifications.never = Nie pozwalaj
webNotifications.never.accesskey = N
webNotifications.alwaysBlock = Zawsze blokuj
webNotifications.alwaysBlock.accesskey = w
webNotifications.block = Zablokuj
webNotifications.block.accesskey = b
webNotifications.receiveFromSite3 = Czy odbierać powiadomienia od witryny „%S”?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = „%S” prosi o dostęp do innych aplikacji i usług na tym urządzeniu.
localhost.remember2 = Zapamiętaj wybór dla tej witryny
localhost.allowlabel = Zezwól
localhost.blocklabel = Zablokuj
localhost.allow.accesskey = Z
localhost.block.accesskey = b
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = „%S” prosi o dostęp do aplikacji i usług na urządzeniach podłączonych do lokalnej sieci.
localNetwork.remember2 = Zapamiętaj wybór dla tej witryny
localNetwork.allowLabel = Zezwól
localNetwork.allow.accesskey = Z
localNetwork.blockLabel = Zablokuj
localNetwork.block.accesskey = b
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Zabierz mnie stąd!
safebrowsing.getMeOutOfHereButton.accessKey = Z
safebrowsing.deceptiveSite = Podejrzenie oszustwa!
safebrowsing.notADeceptiveSiteButton.label = To nie jest oszustwo…
safebrowsing.notADeceptiveSiteButton.accessKey = T
safebrowsing.reportedAttackSite = Zgłoszona strona dokonująca ataków!
safebrowsing.notAnAttackButton.label = To nie jest strona dokonująca ataków…
safebrowsing.notAnAttackButton.accessKey = T
safebrowsing.reportedUnwantedSite = Zgłoszone niechciane oprogramowanie!
safebrowsing.reportedHarmfulSite = Witryna zgłoszona jako szkodliwa!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Szukaj na stronie %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Uruchomić ponownie w trybie rozwiązywania problemów?
troubleshootModeRestartPromptMessage = Rozszerzenia, motywy i ustawienia użytkownika zostaną tymczasowo wyłączone.
troubleshootModeRestartButton = Uruchom ponownie
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Ta strona spowalnia działanie przeglądarki %1$S. Zatrzymaj tę stronę, aby ją przyspieszyć.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Strona spowalnia działanie przeglądarki %1$S. Zatrzymaj tę stronę, aby ją przyspieszyć.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = Strona „%1$S” spowalnia działanie przeglądarki %2$S. Zatrzymaj tę stronę, aby ją przyspieszyć.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = Rozszerzenie „%1$S” spowalnia działanie przeglądarki %2$S. Zatrzymaj to rozszerzenie, aby ją przyspieszyć.
processHang.add-on.learn-more.text = Więcej informacji
processHang.button_stop2.label = Zatrzymaj
processHang.button_stop2.accessKey = Z
processHang.button_debug.label = Debuguj skrypt
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Wyświetl okno w trybie pełnoekranowym (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Przenieś panel boczny na lewo
sidebar.moveToRight = Przenieś panel boczny na prawo
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Musisz włączyć DRM, aby odtwarzać dźwięk lub obraz na tej stronie.
emeNotifications.drmContentDisabled.button.label = Włącz DRM
emeNotifications.drmContentDisabled.button.accesskey = W
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S instaluje oprogramowanie wymagane do odtwarzania dźwięku lub obrazu na tej stronie. Proszę spróbować później.
emeNotifications.unknownDRMSoftware = Nieznane
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Dostosowywanie programu %S
decoder.noCodecs.button = Więcej informacji
decoder.noCodecs.accesskey = W
decoder.noCodecsLinux.message = Aby odtwarzać wideo, może być konieczna instalacja odpowiednich kodeków.
decoder.noHWAcceleration.message = Aby poprawić jakość wideo, może być konieczna instalacja pakietu Microsoft Media Feature Pack.
decoder.noPulseAudio.message = Aby odtwarzać dźwięk, może być konieczna instalacja PulseAudio.
decoder.unsupportedLibavcodec.message = Nieobsługiwana biblioteka libavcodec może być podatna na ataki i powinna zostać uaktualniona, aby odtwarzać wideo.
decoder.decodeError.message = Wystąpił błąd podczas dekodowania zasobu medialnego.
decoder.decodeError.button = Zgłoś problem
decoder.decodeError.accesskey = Z
decoder.decodeWarning.message = Wystąpił naprawialny błąd podczas dekodowania zasobu medialnego.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Ta sieć wymaga zalogowania, aby uzyskać dostęp do Internetu.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Zaloguj się do sieci
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Uprawnienia witryny %S
permissions.remove.tooltip = Wyczyść i używaj domyślnych ustawień
permissions.fullscreen.promptCanceled = Anulowano oczekujące żądania uprawnień: nie mogą one być emitowane przed włączeniem trybu pełnoekranowego DOM.
permissions.fullscreen.fullScreenCanceled = Wyłączono tryb pełnoekranowy DOM: żądania uprawnień nie mogą być emitowane w tym trybie.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64 bity
aboutDialog.architecture.thirtyTwoBit = 32 bity
midi.allow.label = Zezwól
midi.allow.accesskey = Z
midi.block.label = Zablokuj
midi.block.accesskey = b
midi.remember = Pamiętaj tę decyzję
midi.shareWithFile = Czy zezwolić na dostęp do urządzeń MIDI temu lokalnemu plikowi?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Czy zezwolić witrynie „%S” na dostęp do urządzeń MIDI?
midi.shareSysexWithFile = Czy zezwolić na dostęp do urządzeń MIDI oraz wysyłać i odbierać wiadomości SysEx temu lokalnemu plikowi?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Czy zezwolić na dostęp do urządzeń MIDI oraz wysyłać i odbierać wiadomości SysEx stronie „%S”?
serial.allow.label = Zezwól
serial.allow.accesskey = Z
serial.block.label = Zablokuj
serial.block.accesskey = b
serial.shareWithFile = Czy zezwolić na dostęp do portów szeregowych temu lokalnemu plikowi?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Czy zezwolić witrynie „%S” na dostęp do portów szeregowych?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Wstecz
storageAccess1.Allow.label = Zezwól
storageAccess1.Allow.accesskey = Z
storageAccess1.DontAllow.label = Zablokuj
storageAccess1.DontAllow.accesskey = b
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Czy zezwolić witrynie „%1$S” na używanie swoich ciasteczek na witrynie „%2$S”?
storageAccess1.hintText = Możesz zablokować dostęp, jeśli nie jest jasne, dlaczego witryna „%1$S” potrzebuje tych danych.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Wyszukaj „%S” w Internecie
