# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = ఈ వెబ్ పేజీ కొత్త స్థానానికి దారిమళ్ళించడుతోండి. మీరు టైపు చేసిన ఫారం డేటాను కొత్త స్థానానికీ పంపించమంటారా?
# Directory listing strings
DirTitle = %1$S సూచిక
DirGoUp = పై స్థాయి సంచయానికి
ShowHidden = దాచిన వస్తువులను చూపించు
DirColName = పేరు
DirColSize = పరిమాణం
DirColMTime = చివరిగా మార్పు
DirFileLabel = ఫైలు: 
UnsafeUriBlocked = “%1$S” వద్ద ఉన్న వనరు సురక్షిత విహారణచే నిరోధించబడింది.
