# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Importowanie ustawień i danych
import-from =
    { PLATFORM() ->
        [windows] Importuj opcje, zakładki, historię, hasła i inne dane z:
       *[other] Importuj preferencje, zakładki, historię, hasła i inne dane z:
    }
import-from-bookmarks = Importuj zakładki z:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-nothing =
    .label = Nie importuj niczego
    .accesskey = R
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-chrome =
    .label = Chrome
    .accesskey = C
no-migration-sources = Nie odnaleziono żadnych programów, z których można by zaimportować zakładki, historię lub hasła.
import-source =
    .label = Importuj ustawienia i dane
import-items-title =
    .label = Elementy do zaimportowania
import-items-description = Wybierz elementy do zaimportowania:
import-migrating-title =
    .label = Importowanie…
import-migrating-description = Poniższe elementy są właśnie importowane…
import-select-profile-title =
    .label = Wybierz profil
import-select-profile-description = Można zaimportować następujące profile:
import-done-description = Poniższe elementy zostały zaimportowane:
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = Z programu { $source }
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chrome-beta = Google Chrome Beta
source-name-chrome-dev = Google Chrome Dev
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Secure
imported-safari-reading-list = Lista Czytelnia (z Safari)
imported-edge-reading-list = Do przeczytania (z Edge)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Opcje internetowe
    .value = Opcje internetowe
browser-data-edge-1 =
    .label = Ustawienia
    .value = Ustawienia
browser-data-safari-1 =
    .label = Preferencje
    .value = Preferencje
browser-data-chrome-1 =
    .label = Ustawienia
    .value = Ustawienia
browser-data-canary-1 =
    .label = Ustawienia
    .value = Ustawienia
browser-data-360se-1 =
    .label = Preferencje
    .value = Preferencje
browser-data-ie-2 =
    .label = Ciasteczka
    .value = Ciasteczka
browser-data-edge-2 =
    .label = Ciasteczka
    .value = Ciasteczka
browser-data-safari-2 =
    .label = Ciasteczka
    .value = Ciasteczka
browser-data-chrome-2 =
    .label = Ciasteczka
    .value = Ciasteczka
browser-data-canary-2 =
    .label = Ciasteczka
    .value = Ciasteczka
browser-data-firefox-2 =
    .label = Ciasteczka
    .value = Ciasteczka
browser-data-360se-2 =
    .label = Ciasteczka
    .value = Ciasteczka
browser-data-ie-4 =
    .label = Historia
    .value = Historia
browser-data-edge-4 =
    .label = Historia
    .value = Historia
browser-data-safari-4 =
    .label = Historia
    .value = Historia
browser-data-chrome-4 =
    .label = Historia
    .value = Historia
browser-data-canary-4 =
    .label = Historia
    .value = Historia
browser-data-firefox-history-and-bookmarks-4 =
    .label = Historia i zakładki
    .value = Historia i zakładki
browser-data-360se-4 =
    .label = Historia
    .value = Historia
browser-data-ie-8 =
    .label = Zapamiętane dane formularzy
    .value = Zapamiętane dane formularzy
browser-data-edge-8 =
    .label = Zapamiętane dane formularzy
    .value = Zapamiętane dane formularzy
browser-data-safari-8 =
    .label = Zapamiętane dane formularzy
    .value = Zapamiętane dane formularzy
browser-data-chrome-8 =
    .label = Zapamiętane dane formularzy
    .value = Zapamiętane dane formularzy
browser-data-canary-8 =
    .label = Zapamiętane dane formularzy
    .value = Zapamiętane dane formularzy
browser-data-firefox-8 =
    .label = Zapamiętane dane formularzy
    .value = Zapamiętane dane formularzy
browser-data-360se-8 =
    .label = Zapamiętane dane formularzy
    .value = Zapamiętane dane formularzy
browser-data-ie-16 =
    .label = Zachowane hasła
    .value = Zachowane hasła
browser-data-edge-16 =
    .label = Zachowane hasła
    .value = Zachowane hasła
browser-data-safari-16 =
    .label = Zachowane hasła
    .value = Zachowane hasła
browser-data-chrome-16 =
    .label = Zachowane hasła
    .value = Zachowane hasła
browser-data-canary-16 =
    .label = Zachowane hasła
    .value = Zachowane hasła
browser-data-firefox-16 =
    .label = Zachowane hasła
    .value = Zachowane hasła
browser-data-360se-16 =
    .label = Zachowane hasła
    .value = Zachowane hasła
browser-data-ie-32 =
    .label = Ulubione
    .value = Ulubione
browser-data-edge-32 =
    .label = Ulubione
    .value = Ulubione
browser-data-safari-32 =
    .label = Zakładki
    .value = Zakładki
browser-data-chrome-32 =
    .label = Zakładki
    .value = Zakładki
browser-data-canary-32 =
    .label = Zakładki
    .value = Zakładki
browser-data-360se-32 =
    .label = Zakładki
    .value = Zakładki
browser-data-ie-64 =
    .label = Inne dane
    .value = Inne dane
browser-data-edge-64 =
    .label = Inne dane
    .value = Inne dane
browser-data-safari-64 =
    .label = Inne dane
    .value = Inne dane
browser-data-chrome-64 =
    .label = Inne dane
    .value = Inne dane
browser-data-canary-64 =
    .label = Inne dane
    .value = Inne dane
browser-data-firefox-other-64 =
    .label = Inne dane
    .value = Inne dane
browser-data-360se-64 =
    .label = Inne dane
    .value = Inne dane
browser-data-firefox-128 =
    .label = Okna i karty
    .value = Okna i karty
