# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = ទំព័រ​បណ្ដាញ​នេះ កំពុង​ត្រូវ​បាន​ប្ដូរ​ទិស​ទៅកាន់​ទីតាំង​ថ្មី ។ តើ​អ្នក​ចង់​ផ្ញើ​ឡើងវិញ​នូវ​ទិន្នន័យ​សំណុំ​បែបបទ​ដែល​អ្នក​បាន​វាយ ទៅកាន់​ទីតាំង​ថ្មី​ដែរ​ឬទេ ?
# Directory listing strings
DirTitle = លិបិក្រម​របស់ %1$S
DirGoUp = ឡើង​ទៅកាន់​ថត​កម្រិត​ខ្ពស់​ជាង​នេះ
ShowHidden = បង្ហាញ​វត្ថុ​ដែល​បាន​លាក់
DirColName = ឈ្មោះ
DirColSize = ទំហំ
DirColMTime = បាន​កែប្រែ​ចុងក្រោយ
DirFileLabel = ឯកសារ ៖
