# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Go nyaka { $host }…
network-connection-status-connected = Kgokagantšwe go { $host }…
network-connection-status-sending-request = Go romela kgopelo go { $host }…
network-connection-status-transferring-data = Go fetišetša tshedimošo go tšwa go { $host }…
network-connection-status-connecting = Go kgokaganya go { $host }…
network-connection-status-read = Bala { $host }
network-connection-status-wrote = Ngwadile { $host }
network-connection-status-waiting = Letetše { $host }…
network-connection-status-looked-up = E nyakile { $host }…
