# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Mba’ejegueru pytyvõha
import-from =
    { PLATFORM() ->
        [windows] Jeporavorã jegueru, techaukaha, tembiasakue, ñe’ẽñemi ha ambue mba’ekuaarã kóvagui:
       *[other] Jerohoryvéva jegueru, techaukaha, tembiasakue, ñe’ẽñemi ha ambue mba’ekuaarã kóvagui:
    }
import-from-bookmarks = Techaukaha jegueru kóvagui:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-edge-legacy =
    .label = Microsoft Edge Legacy
    .accesskey = L
import-from-edge-beta =
    .label = Microsoft Edge Beta
    .accesskey = d
import-from-nothing =
    .label = Ani regueru mba’eve
    .accesskey = D
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chrome-beta =
    .label = Chrome Beta
    .accesskey = B
import-from-chrome-dev =
    .label = Chrome Dev
    .accesskey = D
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = x
import-from-360se =
    .label = 360 Secure Browser
    .accesskey = 3
no-migration-sources = Ndojejuhúi tembiaporape oguerekóva techaukaha, tembiasakue térã mba’ekuaarã ñe’ẽñemi rehegua.
import-source =
    .label = Mba’epytyvõrã ha mba’ekuaarã jegueru
import-items-title =
    .label = Mba’epuru ojeguerútava
import-items-description = Eiporavo mba’epuru reguerútava:
import-migrating-title =
    .label = Jegueruhína…
import-migrating-description = Ojegueruhína ko’ã mba’epuru…
import-select-profile-title =
    .label = Rechaukaha jeporavo
import-select-profile-description = Ikatu regueru mba’ekuaarã ko’ã rechaukahakuéragui:
import-done-title =
    .label = Jeguerupaite
import-done-description = Ko’ã mba’epuru ojeguerupa porã:
import-close-source-browser = Ikatúpiko, ehechaporãke kundaha poravopyre oñembotýpara’e reku’e mboyvejey.
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = { $source } rehegua
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-edge-beta = Microsoft Edge Beta
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chrome-beta = Google Chrome Beta
source-name-chrome-dev = Google Chrome Dev
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Secure Browser
imported-safari-reading-list = Moñe'ẽ rysýi (Safari rehegua)
imported-edge-reading-list = Moñe'ẽrã rysýi (Edge Guive)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Ñanduti jeporavorã
    .value = Ñanduti jeporavorã
browser-data-edge-1 =
    .label = Ñemyatyrõ
    .value = Ñemyatyrõ
browser-data-safari-1 =
    .label = Jererohoryvéva
    .value = Jererohoryvéva
browser-data-chrome-1 =
    .label = Jerohoryvéva
    .value = Jerohoryvéva
browser-data-canary-1 =
    .label = Jerohoryvéva
    .value = Jerohoryvéva
browser-data-360se-1 =
    .label = Jerohoryvéva
    .value = Jerohoryvéva
browser-data-ie-2 =
    .label = Kookie
    .value = Kookie
browser-data-edge-2 =
    .label = Kookie
    .value = Kookie
browser-data-safari-2 =
    .label = Kookie
    .value = Kookie
browser-data-chrome-2 =
    .label = Kookie
    .value = Kookie
browser-data-canary-2 =
    .label = Kookie
    .value = Kookie
browser-data-firefox-2 =
    .label = Kookie
    .value = Kookie
browser-data-360se-2 =
    .label = Kookie
    .value = Kookie
browser-data-ie-4 =
    .label = Kundaha rembiasakue
    .value = Kundaha rembiasakue
browser-data-edge-4 =
    .label = Kundaha rembiasakue
    .value = Kundaha rembiasakue
browser-data-safari-4 =
    .label = Kundaha rembiasakue
    .value = Kundaha rembiasakue
browser-data-chrome-4 =
    .label = Kundaha rembiasakue
    .value = Kundaha rembiasakue
browser-data-canary-4 =
    .label = Kundaha rembiasakue
    .value = Kundaha rembiasakue
browser-data-firefox-history-and-bookmarks-4 =
    .label = Kundaha ha techaukaha rembiasakue
    .value = Kundaha ha techaukaha rembiasakue
browser-data-360se-4 =
    .label = Kundaha rembiasakue
    .value = Kundaha rembiasakue
browser-data-ie-8 =
    .label = Myanyhẽha ñongatupyre rembiasakue
    .value = Myanyhẽha ñongatupyre rembiasakue
browser-data-edge-8 =
    .label = Myanyhẽha ñongatupyre rembiasakue
    .value = Myanyhẽha ñongatupyre rembiasakue
browser-data-safari-8 =
    .label = Myanyhẽha ñongatupyre rembiasakue
    .value = Myanyhẽha ñongatupyre rembiasakue
browser-data-chrome-8 =
    .label = Myanyhẽha ñongatupyre rembiasakue
    .value = Myanyhẽha ñongatupyre rembiasakue
browser-data-canary-8 =
    .label = Myanyhẽha ñongatupyre rembiasakue
    .value = Myanyhẽha ñongatupyre rembiasakue
browser-data-firefox-8 =
    .label = Myanyhẽha ñongatupyre rembiasakue
    .value = Myanyhẽha ñongatupyre rembiasakue
browser-data-360se-8 =
    .label = Myanyhẽha ñongatupyre rembiasakue
    .value = Myanyhẽha ñongatupyre rembiasakue
browser-data-ie-16 =
    .label = Ñe'ẽñemi ñongatupyre
    .value = Ñe'ẽñemi ñongatupyre
browser-data-edge-16 =
    .label = Ñe'ẽñemi ñongatupyre
    .value = Ñe'ẽñemi ñongatupyre
browser-data-safari-16 =
    .label = Ñe'ẽñemi ñongatupyre
    .value = Ñe'ẽñemi ñongatupyre
browser-data-chrome-16 =
    .label = Ñe'ẽñemi ñongatupyre
    .value = Ñe'ẽñemi ñongatupyre
browser-data-canary-16 =
    .label = Ñe'ẽñemi ñongatupyre
    .value = Ñe'ẽñemi ñongatupyre
browser-data-firefox-16 =
    .label = Ñe'ẽñemi ñongatupyre
    .value = Ñe'ẽñemi ñongatupyre
browser-data-360se-16 =
    .label = Ñe'ẽñemi ñongatupyre
    .value = Ñe'ẽñemi ñongatupyre
browser-data-ie-32 =
    .label = Takate’ỹha
    .value = Takate’ỹha
browser-data-edge-32 =
    .label = Takate’ỹha
    .value = Takate’ỹha
browser-data-safari-32 =
    .label = Techaukaha
    .value = Techaukaha
browser-data-chrome-32 =
    .label = Techaukaha
    .value = Techaukaha
browser-data-canary-32 =
    .label = Techaukaha
    .value = Techaukaha
browser-data-360se-32 =
    .label = Techaukaha
    .value = Techaukaha
browser-data-ie-64 =
    .label = Ambue mba’ekuaarã
    .value = Ambue mba’ekuaarã
browser-data-edge-64 =
    .label = Ambue mba’ekuaarã
    .value = Ambue mba’ekuaarã
browser-data-safari-64 =
    .label = Ambue mba’ekuaarã
    .value = Ambue mba’ekuaarã
browser-data-chrome-64 =
    .label = Ambue mba’ekuaarã
    .value = Ambue mba’ekuaarã
browser-data-canary-64 =
    .label = Ambue mba’ekuaarã
    .value = Ambue mba’ekuaarã
browser-data-firefox-other-64 =
    .label = Ambue mba’ekuaarã
    .value = Ambue mba’ekuaarã
browser-data-360se-64 =
    .label = Ambue mba’ekuaarã
    .value = Ambue mba’ekuaarã
browser-data-firefox-128 =
    .label = Ovetã ha tendayke
    .value = Ovetã ha tendayke
