# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

reload-tab =
    .label = Tendayke myenyhẽjey
    .accesskey = R
select-all-tabs =
    .label = Eiporavopaite tendayke
    .accesskey = S
duplicate-tab =
    .label = Embojoyvy Tendayke
    .accesskey = D
duplicate-tabs =
    .label = Emomokõi tendayke
    .accesskey = D
close-tabs-to-the-end =
    .label = Tendayke mboty akatúa gotyo
    .accesskey = i
close-other-tabs =
    .label = Ambue togue pyahu ñemboty
    .accesskey = o
reload-tabs =
    .label = Emyanyhẽjey tendayke
    .accesskey = R
pin-tab =
    .label = Tendayke mombytapy
    .accesskey = P
unpin-tab =
    .label = Tendayke mombytapy mbogue
    .accesskey = b
pin-selected-tabs =
    .label = Tendayke mboja
    .accesskey = P
unpin-selected-tabs =
    .label = Tendayke pe'a
    .accesskey = b
bookmark-selected-tabs =
    .label = Emongurusu tendayke…
    .accesskey = k
bookmark-tab =
    .label = Techaukaha rendayke
    .accesskey = B
reopen-in-container =
    .label = Embojurujajey guerekohápe
    .accesskey = e
move-to-start =
    .label = Eguerova Ñepyrũme
    .accesskey = S
move-to-end =
    .label = Eguerova ipahápe
    .accesskey = E
move-to-new-window =
    .label = Ovetã pyahúpe jegueraha
    .accesskey = W
undo-close-tab =
    .label = Emboguevi ha emboty tendayke
    .accesskey = U
close-tab =
    .label = Tendayke mboty
    .accesskey = C
close-tabs =
    .label = Emboty tendayke
    .accesskey = S
move-tabs =
    .label = Eguerova tendayke
    .accesskey = v
move-tab =
    .label = Eguerova tendayke
    .accesskey = v
