# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Saglobuotuos paroles
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-username-cmd =
    .label = Kopēt lītuotuojvuordu
    .accesskey = u
edit-username-cmd =
    .label = Redigeit lītuotuojvuordu
    .accesskey = d
copy-password-cmd =
    .label = Kopēt paroli
    .accesskey = K
edit-password-cmd =
    .label = Redigeit paroli
    .accesskey = e
search-filter =
    .accesskey = M
    .placeholder = Mekleit
column-heading-site =
    .label = Vītne
column-heading-username =
    .label = Lītuotuojvuords
column-heading-password =
    .label = Parole
column-heading-time-created =
    .label = Pyrmū reizi izmontuota
column-heading-time-last-used =
    .label = Piedejū reizi izmontuota
column-heading-time-password-changed =
    .label = Last Changed
column-heading-times-used =
    .label = Izmontuošonu skaits
remove =
    .label = Izmest
    .accesskey = I
import =
    .label = Importeit…
    .accesskey = I
close-button =
    .label = Aiztaiseit
    .accesskey = z
show-passwords =
    .label = Ruodeit paroles
    .accesskey = P
hide-passwords =
    .label = Slēpt paroles
    .accesskey = P
logins-description-all = Jiusu datorā ir saglobuotys itū vītņu paroles
logins-description-filtered = Jiusu mekliešonai atbiļst ituos paroles:
remove-all =
    .label = Nūjimt vysu
    .accesskey = A
remove-all-shown =
    .label = Nūjimt vysys radzamuos
    .accesskey = A
remove-all-passwords-prompt = Voi tīšom vālotīs izmest vysys paroles?
remove-all-passwords-title = Izmest vysys paroles
no-master-password-prompt = Voi tīšom vālotīs ruodeit sovys paroles?
