# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = সঞ্চিত লগইনবোৰ
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = URL প্ৰতিলিপি
    .accesskey = y
launch-site-url-cmd =
    .label = URL দৰ্শন
    .accesskey = V
copy-username-cmd =
    .label = ব্যৱহাৰকাৰীনাম প্ৰতিলিপি
    .accesskey = U
edit-username-cmd =
    .label = ব্যৱহাৰকাৰীনাম সম্পাদনা
    .accesskey = d
copy-password-cmd =
    .label = পাছৱৰ্ড প্ৰতিলিপি
    .accesskey = C
edit-password-cmd =
    .label = পাছৱৰ্ড সম্পাদনা
    .accesskey = E
search-filter =
    .accesskey = S
    .placeholder = সন্ধান কৰক
column-heading-site =
    .label = ছাইট
column-heading-username =
    .label = ব্যৱহাৰকাৰীনাম
column-heading-password =
    .label = পাছৱৰ্ড
column-heading-time-created =
    .label = প্ৰথম ব্যৱহৃত
column-heading-time-last-used =
    .label = অন্তিম ব্যৱহৃত
column-heading-time-password-changed =
    .label = অন্তিম সলনি হৈছে
column-heading-times-used =
    .label = ব্যৱহাৰৰ সময়কাল
remove =
    .label = আঁতৰাওক
    .accesskey = R
import =
    .label = আমদানি কৰক…
    .accesskey = I
close-button =
    .label = বন্ধ কৰক
    .accesskey = C
show-passwords =
    .label = পাছৱৰ্ডবোৰ দেখুৱাওক
    .accesskey = P
hide-passwords =
    .label = পাছৱৰ্ডবোৰ লুকুৱাওক
    .accesskey = P
logins-description-all = নিম্নলিখিত ছাইটবোৰৰ বাবে লগইনবোৰ আপোনাৰ কম্পিউটাৰত সঞ্চিত কৰা হৈছে
logins-description-filtered = নিম্নলিখিত লগইনবোৰ আপোনাৰ সন্ধানৰ সৈতে মিলে:
remove-all =
    .label = সকলো আঁতৰাওক
    .accesskey = A
remove-all-shown =
    .label = দেখুৱা সকলো আঁতৰাওক
    .accesskey = A
remove-all-passwords-prompt = আপুনি সকলো পাছৱৰ্ড আঁতৰাব বিচাৰে বুলি নিশ্চিতনে?
remove-all-passwords-title = সকলো পাছৱৰ্ড আঁতৰাওক
no-master-password-prompt = আপুনি আপোনাৰ পাছৱৰ্ড দেখুৱাব বিচাৰে বুলি নিশ্চিতনে?
auto-fill-logins-and-passwords =
    .label = লগইন আৰু পাছৱৰ্ড স্বযংভৰ্তি কৰক
