# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = 시간 초과
openFile = 파일 열기
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = %S 검색: "%S"
contextMenuSearch.accesskey = S
contextMenuPrivateSearch = 사생활 보호 창에서 검색
contextMenuPrivateSearch.accesskey = h
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = 사생활 보호 창에서 %S 검색
contextMenuPrivateSearchOtherEngine.accesskey = h
bookmarkAllTabsDefault = (폴더 이름)
unsignedAddonsDisabled.message = 설치된 하나 이상의 부가 기능을 확인할 수 없어 비활성화되었습니다.
unsignedAddonsDisabled.learnMore.label = 더 알아보기
unsignedAddonsDisabled.learnMore.accesskey = L
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = 최근 접근 %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = %S:// 링크
crashedpluginsMessage.title = %S 플러그인이 충돌했습니다.
crashedpluginsMessage.reloadButton.label = 페이지 새로 고침
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = 충돌 보고서 제출
crashedpluginsMessage.submitButton.accesskey = S
crashedpluginsMessage.learnMore = 더 알아보기…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = %S로 이동하시겠습니까?
keywordURIFixup.goTo = 예, %S로 이동합니다
keywordURIFixup.goTo.accesskey = Y
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = %S 버전으로 업데이트
update.downloadAndInstallButton.accesskey = U
menuOpenAllInTabs.label = 모두 탭에서 열기
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = 이 페이지 새로고침
tabHistory.goBack = 이 페이지 뒤로 가기
tabHistory.goForward = 이 페이지 앞으로 가기
# URL Bar
pasteAndGo.label = 붙여넣고 바로 가기
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = 현재 페이지 새로 고침 (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = 이 페이지 로드 중지 (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = 확대/축소 초기화 (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = 리더뷰 표시/숨기기 (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S %%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, 확대/축소 수준 재설정
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = 북마크 보기 (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = 진행 중인 다운로드 상태 표시 (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = 새 창 열기 (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = 새 탭 열기 (%S)
newTabContainer.tooltip = 새 탭 열기(%S)\n새 컨테이너 탭을 열려면 길게 누르세요
newTabAlwaysContainer.tooltip = 새 탭에서 열 컨테이너 선택
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = %S 사이트가 HTML5 캔버스 이미지 데이터를 사용하도록 허용하시겠습니까?
canvas.siteprompt2.warning = 컴퓨터를 고유하게 식별하는 데 사용될 수 있습니다.
canvas.block = 차단
canvas.block.accesskey = B
canvas.allow2 = 허용
canvas.allow2.accesskey = A
canvas.remember2 = 이 선택 기억하기
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = 인증 기관: %S
identity.identified.verified_by_you = 이 사이트를 보안 예외로 추가했습니다.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = 인증서 발급 대상: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = 안전하지 않음
identity.notSecure.tooltip = 연결이 안전하지 않음
identity.extension.label = 확장 기능 (%S)
identity.extension.tooltip = 확장 기능에 의해 로드됨: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = 축소 (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = 확대/축소 초기화 (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = 확대 (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = 잘라내기 (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = 복사 (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = 붙여넣기 (%S)
geolocation.allow = 허용
geolocation.allow.accesskey = A
geolocation.block = 차단
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = 시스템 위치 설정이 열립니다. %S에 위치 권한을 부여해 주세요.
geolocation.shareWithSite4 = %S 사이트가 사용자 위치에 접근하도록 허용하시겠습니까?
geolocation.shareWithFile4 = 이 로컬 파일이 사용자 위치에 접근하도록 허용하시겠습니까?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = %1$S이(가) %2$S에 사용자 위치에 접근할 수 있도록 권한을 부여하는 것을 허용하시겠습니까?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = 시스템 설정에서 %S에 위치 권한을 부여하세요.
geolocation.systemSettingsTitle = 위치 권한 승인 대기 중
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = 시스템에서 %S에 이 권한을 부여할지 묻습니다.
geolocation.remember = 이 선택 기억하기
# Virtual Reality Device UI
xr.allow2 = 허용
xr.allow2.accesskey = A
xr.block = 차단
xr.block.accesskey = B
xr.shareWithSite4 = %S 사이트가 가상 현실 기기에 접근하도록 허용하시겠습니까? 민감한 정보가 노출될 수 있습니다.
xr.shareWithFile4 = 이 로컬 파일이 가상 현실 기기에 접근하도록 허용하시겠습니까? 민감한 정보가 노출될 수 있습니다.
xr.remember = 이 선택 기억하기
# Persistent storage UI
persistentStorage.allow = 허용
persistentStorage.allow.accesskey = A
persistentStorage.block.label = 차단
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = %S 사이트가 데이터를 영구 저장소에 저장하도록 허용하시겠습니까?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = 허용
webNotifications.allow2.accesskey = A
webNotifications.notNow = 나중에
webNotifications.notNow.accesskey = n
webNotifications.never = 항상 허용 안 함
webNotifications.never.accesskey = v
webNotifications.alwaysBlock = 항상 차단
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = 차단
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = %S 사이트가 알림을 보내도록 허용하시겠습니까?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S 사이트가 이 기기의 다른 앱과 서비스에 접근하려고 합니다.
localhost.remember2 = 이 사이트에 대해 내 선택 기억하기
localhost.allowlabel = 허용
localhost.blocklabel = 차단
localhost.allow.accesskey = A
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S 사이트가 로컬 네트워크에 연결된 기기의 앱과 서비스에 접근하려고 합니다.
localNetwork.remember2 = 이 사이트에 대해 내 선택 기억하기
localNetwork.allowLabel = 허용
localNetwork.allow.accesskey = A
localNetwork.blockLabel = 차단
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = 밖으로 나가기!
safebrowsing.getMeOutOfHereButton.accessKey = G
safebrowsing.deceptiveSite = 사기 사이트!
safebrowsing.notADeceptiveSiteButton.label = 이 사이트는 사기 사이트가 아닙니다…
safebrowsing.notADeceptiveSiteButton.accessKey = D
safebrowsing.reportedAttackSite = 보고된 공격 사이트!
safebrowsing.notAnAttackButton.label = 공격 사이트 아님…
safebrowsing.notAnAttackButton.accessKey = A
safebrowsing.reportedUnwantedSite = 사용자 동의 없이 설치하는 소프트웨어 사이트로 신고되었습니다!
safebrowsing.reportedHarmfulSite = 유해한 사이트로 신고됨!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = 검색: %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = %S를 문제 해결 모드로 다시 시작하시겠습니까?
troubleshootModeRestartPromptMessage = 확장 기능, 테마 및 사용자 지정 설정이 일시적으로 비활성화됩니다.
troubleshootModeRestartButton = 다시 시작
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = 이 페이지가 %1$S를 느리게 하고 있습니다. 브라우저를 빠르게 하려면 이 페이지를 중지하세요.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = 웹 페이지가 %1$S를 느리게 하고 있습니다. 브라우저를 빠르게 하려면 해당 페이지를 중지하세요.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = “%1$S” 탭이 %2$S를 느리게 하고 있습니다. 브라우저를 빠르게 하려면 해당 페이지를 중지하세요.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = “%1$S” 확장 기능이 %2$S를 느리게 하고 있습니다. 브라우저를 빠르게 하려면 해당 확장 기능을 중지하세요.
processHang.add-on.learn-more.text = 더 알아보기
processHang.button_stop2.label = 중지
processHang.button_stop2.accessKey = S
processHang.button_debug.label = 스크립트 디버그
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = 창을 전체 화면에 표시 (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = 사이드바를 왼쪽으로 이동
sidebar.moveToRight = 사이드바를 오른쪽으로 이동
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = 이 페이지에서 일부 오디오 또는 비디오를 재생하려면 DRM을 활성화해야 합니다.
emeNotifications.drmContentDisabled.button.label = DRM 활성화
emeNotifications.drmContentDisabled.button.accesskey = E
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S가 이 페이지에서 오디오나 비디오를 재생하는 데 필요한 구성 요소를 설치하고 있습니다. 나중에 다시 시도하세요.
emeNotifications.unknownDRMSoftware = 알 수 없음
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = %S 사용자 지정
decoder.noCodecs.button = 방법 알아보기
decoder.noCodecs.accesskey = L
decoder.noCodecsLinux.message = 동영상을 재생하기 위해 동영상 코덱을 설치해야 합니다.
decoder.noHWAcceleration.message = 동영상 재생 품질을 높이기 위해 Microsoft의 Media Feature Pack을 설치해야 합니다.
decoder.noPulseAudio.message = 소리를 재생하기 위해서는 PulseAudio 소프트웨어가 필요합니다.
decoder.unsupportedLibavcodec.message = libavcodec은 취약하거나 지원되지 않을 수 있으므로 동영상을 재생하기 위해서 업데이트되어야 합니다.
decoder.decodeError.message = 미디어 리소스를 디코딩하는 동안 오류가 발생했습니다.
decoder.decodeError.button = 이 사이트 문제 보고하기
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = 미디어 리소스를 디코딩하는 동안 복구 가능한 오류가 발생했습니다.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = 인터넷을 사용하기 위해선 반드시 이 네트워크에 로그인해야 합니다.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = 네트워크 로그인 페이지 열기
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = %S 권한
permissions.remove.tooltip = 이 승인을 지우고 다시 묻기
permissions.fullscreen.promptCanceled = 취소된 보류 중인 권한 요청: DOM 전체 화면으로 들어가기 전에 권한 요청을 발행해서는 안됩니다.
permissions.fullscreen.fullScreenCanceled = 종료된 DOM 전체 화면: DOM 전체 화면에서 권한 요청을 발행해서는 안됩니다.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64비트
aboutDialog.architecture.thirtyTwoBit = 32비트
midi.allow.label = 허용
midi.allow.accesskey = A
midi.block.label = 차단
midi.block.accesskey = B
midi.remember = 이 선택 기억하기
midi.shareWithFile = 이 로컬 파일이 사용자 MIDI 기기에 접근하도록 허용하시겠습니까?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = %S 사이트가 MIDI 기기에 접근하도록 허용하시겠습니까?
midi.shareSysexWithFile = 이 로컬 파일이 MIDI 기기에 접근하고 SysEx 메시지를 주고 받는 것을 허용하시겠습니까?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = %S 사이트가 MIDI 기기에 접근하고 SysEx 메시지를 주고 받는 것을 허용하시겠습니까?
serial.allow.label = 허용
serial.allow.accesskey = A
serial.block.label = 차단
serial.block.accesskey = B
serial.shareWithFile = 이 로컬 파일이 직렬 포트에 접근하도록 허용하시겠습니까?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = %S 사이트가 직렬 포트에 접근하도록 허용하시겠습니까?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = 뒤로
storageAccess1.Allow.label = 허용
storageAccess1.Allow.accesskey = A
storageAccess1.DontAllow.label = 차단
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = %1$S 사이트가 %2$S 사이트에서 쿠키를 사용하도록 허용하시겠습니까?
storageAccess1.hintText = %1$S에 이 데이터가 필요한 이유가 명확하지 않은 경우 접근을 차단할 수 있습니다.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = “%S” 웹 검색
