# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Збережені паролі
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-username-cmd =
    .label = Копіювати ім’я користувача
    .accesskey = і
edit-username-cmd =
    .label = Змінити ім'я користувача
    .accesskey = к
copy-password-cmd =
    .label = Копіювати пароль
    .accesskey = к
edit-password-cmd =
    .label = Змінити пароль
    .accesskey = З
search-filter =
    .accesskey = ш
    .placeholder = Пошук
column-heading-site =
    .label = Сайт
column-heading-username =
    .label = Ім’я користувача
column-heading-password =
    .label = Пароль
column-heading-time-created =
    .label = Вперше використано
column-heading-time-last-used =
    .label = Востаннє використано
column-heading-time-password-changed =
    .label = Остання зміна
column-heading-times-used =
    .label = Використань
remove =
    .label = Видалити
    .accesskey = и
import =
    .label = Імпорт…
    .accesskey = І
close-button =
    .label = Закрити
    .accesskey = З
hide-passwords =
    .label = Приховати паролі
    .accesskey = х
logins-description-filtered = Пошуку відповідають наступні паролі:
remove-all-passwords-prompt = Ви впевнені, що бажаєте вилучити всі паролі?
remove-all-passwords-title = Вилучити всі паролі
