# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SaveImageTitle = ઈમેજ સંગ્રહો
SaveMediaTitle = મીડિયા સાચવો
SaveVideoTitle = વીડિયો સંગ્રહો
SaveAudioTitle = ઓડિયો સંગ્રહો
SaveLinkTitle = આ રીતે સંગ્રહો
WebPageCompleteFilter = વેબ પાનું, સંપૂર્ણ
WebPageHTMLOnlyFilter = વેબ પાનું, માત્ર HTML
WebPageXHTMLOnlyFilter = વેબ પાનું, માત્ર XHTML
WebPageSVGOnlyFilter = વેબ પાનું, માત્ર SVG
WebPageXMLOnlyFilter = વેબ પાનું, માત્ર XML
