# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dateformat-label =
    .value = Formato de data:
    .accesskey = F
#   $date (String) - the formatted example date
dateformat-long =
    .label = Longo: { $date }
#   $date (String) - the formatted example date
dateformat-short =
    .label = Curto: { $date }
weekstart-label =
    .value = Começar a semana em:
    .accesskey = C
day-1-name =
    .label = Domingo
day-2-name =
    .label = Segunda
day-3-name =
    .label = Terça
day-4-name =
    .label = Quarta
day-5-name =
    .label = Quinta
day-6-name =
    .label = Sexta
day-7-name =
    .label = Sábado
day-1-checkbox =
    .label = Dom
    .accesskey = D
day-2-checkbox =
    .label = Seg
    .accesskey = S
day-3-checkbox =
    .label = Ter
    .accesskey = T
day-4-checkbox =
    .label = Qua
    .accesskey = Q
day-5-checkbox =
    .label = Qui
    .accesskey = u
day-6-checkbox =
    .label = Sex
    .accesskey = e
day-7-checkbox =
    .label = Sáb
    .accesskey = b
visible-hours-label =
    .value = Mostrar:
    .accesskey = M
visible-hours-end-label =
    .value = horas simultaneamente
day-start-label =
    .value = Dia começa às:
    .accesskey = o
day-end-label =
    .value = Dia acaba às:
    .accesskey = i
midnight-label =
    .label = Meia-noite
noon-label =
    .label = Meio-dia
week-0-label =
    .label = nenhuma
week-1-label =
    .label = 1 semana
week-2-label =
    .label = 2 semanas
week-3-label =
    .label = 3 semanas
week-4-label =
    .label = 4 semanas
week-5-label =
    .label = 5 semanas
week-6-label =
    .label = 6 semanas
previous-weeks-label =
    .value = Semanas anteriores a exibir:
    .accesskey = n
reminder-legend = Quando um alarme dispara:
reminder-play-checkbox =
    .label = Tocar som
    .accesskey = T
reminder-browse-sound-label =
    .label = Procurar…
    .accesskey = P
reminder-dialog-label =
    .label = Mostrar aviso
    .accesskey = M
event-alarm-label =
    .value = Configuração padrão de alarmes para eventos:
    .accesskey = C
alarm-on-label =
    .label = Ativado
alarm-off-label =
    .label = Desativado
task-alarm-label =
    .value = Configuração padrão de alarmes para tarefas:
    .accesskey = f
event-alarm-time-label =
    .value = Antecedência padrão de alarmes para eventos:
    .accesskey = A
task-alarm-time-label =
    .value = Antecedência padrão de alarmes para tarefas:
    .accesskey = n
category-edit-label = Editar categoria
category-overwrite-title = Aviso: nome já existe
category-overwrite = Já há uma categoria com este nome. Substituir?
category-blank-warning = Digite um nome para a categoria.
