# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = کیا تساں ہیٹھ درج مقاصد کیتے "%S" تے بھروسہ کرݨ چاہندے او؟
unnamedCA = سرٹیفکیٹ اتھارٹی (بے نام)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = براہ مہربانی او پاس ورڈ درج کرو جیڑھا ایں سرٹیفکیٹ دے بیک اپ کوں ڳجھا کرݨ کیتے استعمال کیتا ڳیا ہا۔
# Page Info
pageInfo_NoEncryption = کنکشن انکرپٹڈ کائنی۔
pageInfo_Privacy_None1 = ویب سائٹ %S تساں جیڑھا ورقہ ݙیکھدے پئے او اوندے کیتے خفیہ کاری دی حمایت نہیں کریندی ہے۔
pageInfo_Privacy_None2 = انٹرنیٹ تے خفیہ کاری دے بغیر بھیڄی ڳئی معلومات کوں ٻئے لوک ݙیکھ سڳدے ہن جݙآں ایہ راہداری وِچ ہووے۔
pageInfo_Privacy_None4 = تساں جیڑھا ورقہ ݙیکھدے پئے او او انٹرنیٹ تے منتقل تھیوݨ کنوں پہلے خفیہ کائنا ہا۔
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = کنکشن دیاں خفیہ کردہ (%1$S، %2$S بٹ کیز، %3$S)
pageInfo_BrokenEncryption = ترٹیاں ہویاں ڳجھیاں (%1$S، %2$S بٹ کیز، %3$S)
pageInfo_Privacy_Encrypted1 = تساں جیڑھا ورقہ ڈیکھدے پئے او او انٹرنیٹ تے منتقل تھیوݨ کنوں پہلے انکرپٹ کیتا ڳیا ہا۔
pageInfo_Privacy_Encrypted2 = خفیہ کاری غیر مجاز لوکاں کیتے کمپیوٹر دے درمیان سفر کرݨ والی معلومات کوں ݙیکھݨ مشکل بݨدی ہے۔ ایں واسطے ایں ڳالھ دا امکان کائنی جو کوئی وی ایں ورقے کوں اوں وقت پڑھے جݙاں اوں پورے نیٹ ورک تے سفر کیتا۔
pageInfo_MixedContent = کنکشن جزوی طور تے خفیہ کردہ
pageInfo_MixedContent2 = تساں جیڑھا ورقہ ݙیکھدے پئے او اوندے کجھ حصے انٹرنیٹ تے منتقل تھیوݨ کنوں پہلے ڳجھے نہ کیتے ڳئے ہن۔
pageInfo_WeakCipher = ایں ویب سائٹ کنوں تہاݙا کنکشن کمزور خفیہ کاری دا استعمال کریندا ہے تے ایہ نجی کائنی۔ ٻئے لوک تہاݙی معلومات ݙیکھ سڳدے ہن یا ویب سائٹ دے رویے وِچ ترمیم کر سڳدے ہن۔
pageInfo_CertificateTransparency_Compliant = ایہ ویب سائٹ سرٹیفکیٹ دی شفافیت دی پالیسی دی تعمیل کریندی ہے۔
# Token Manager
password_not_set = (سیٹ کائنی)
