# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Notice: If you're updating this list, you should also
###         update the list in mozIntl.js.

region-name-ad = অ্যান্ডোরা
region-name-ae = সংযুক্ত আরব আমিরশাহী
region-name-af = আফগানিস্তান
region-name-ag = অ্যান্টিগুয়া ও বারবুডা
region-name-ai = অ্যাঙ্গিলা
region-name-al = আলবেনিয়া
region-name-am = আর্মেনিয়া
region-name-ao = অ্যাঙ্গোলা
region-name-aq = আনটার্কটিকা
region-name-ar = আর্জেনটিনা
region-name-as = আমেরিকান সামোয়া
region-name-at = অস্ট্রিয়া
region-name-au = অস্ট্রেলিয়া
region-name-aw = আরুবা
region-name-az = আজারবাইজান
region-name-ba = বসনিয়া ও হার্জগোভিনা
region-name-bb = বার্বাডোস
region-name-bd = বাংলাদেশ
region-name-be = বেলজিয়াম
region-name-bf = বুর্কিনা ফাসো
region-name-bg = বুলগারিয়া
region-name-bh = বাহরেন
region-name-bi = বুরুন্ডি
region-name-bj = বেনিন
region-name-bl = সেন্ট বার্থলেমি
region-name-bm = বার্মুডা
region-name-bn = ব্রুনেই
region-name-bo = বোলিভিয়া
region-name-bq = বোনারি, ইউসট্যাটিয়াস এবং সাবা
region-name-br = ব্রাজিল
region-name-bs = বাহামা,
region-name-bt = ভুটান
region-name-bv = বুভে দ্বীপ
region-name-bw = বোটসওয়ানা
region-name-by = বেলারুস
region-name-bz = বেলিজে
region-name-ca = কানাডা
region-name-cc = কোকোস (কিলিং) দ্বীপ
region-name-cd = কঙ্গো (কিনসাসা)
region-name-cf = মধ্য আফ্রিকান প্রজাতন্ত্র
region-name-cg = কঙ্গো (ব্রাজাভিল)
region-name-ch = সুইৎজারল্যান্ড
region-name-ci = আইভরি কোস্ট
region-name-ck = কুক দ্বীপপুঞ্জ
region-name-cl = চিলি
region-name-cm = ক্যামেরুণ
region-name-cn = চীন
region-name-co = কোলোম্বিয়া
region-name-cp = ক্লিপারটন দ্বীপপুঞ্জ
region-name-cr = কোস্টা রিকা
region-name-cu = কিউবা
region-name-cv = কেপ ভার্ডি
region-name-cw = কিউরাসাও
region-name-cx = ক্রিস্টমাস দ্বীপ
region-name-cy = সাইপ্রাস
region-name-cz = চেক প্রজাতন্ত্র
region-name-de = জার্মানি
region-name-dg = দিয়েগো গার্সিয়া
region-name-dj = জিবুতি
region-name-dk = ডেনমার্ক
region-name-dm = ডোমিনিকা
region-name-do = ডমিনিকান প্রজাতন্ত্র
region-name-dz = আলজেরিয়া
region-name-ec = ইকুয়েডর
region-name-ee = এস্তোনিয়া
region-name-eg = মিশর
region-name-eh = পশ্চিম সাহারা
region-name-er = এরিট্রিয়া
region-name-es = স্পেন
region-name-et = ইথিওপিয়া
region-name-fi = ফিনল্যান্ড
region-name-fj = ফিজি
region-name-fk = ফল্কল্যান্ড দ্বীপপুঞ্জ (মালভিনাস)
region-name-fm = মাক্রোনেশিয়া, ফেডারেটেড স্টেটস্ অফ
region-name-fo = ফ্যারো দ্বীপপুঞ্জ
region-name-fr = ফ্রান্স
region-name-ga = গেবন
region-name-gb = যুক্তরাজ্য
region-name-gd = গ্রেনাডা
region-name-ge = জর্জিয়া
region-name-gf = ফ্রেঞ্চ গায়ানা
region-name-gg = গুয়ের্নসে
region-name-gh = ঘানা
region-name-gi = জিব্রাল্টার
region-name-gl = গ্রিনল্যান্ড
region-name-gm = গাম্বিয়া,
region-name-gn = গিনি
region-name-gp = গুয়াডেল্যুপ
region-name-gq = ইকুয়েটোরিয়াল গিনি
region-name-gr = গ্রিস
region-name-gs = দক্ষিণ জর্জিয়া ও দক্ষিণ স্যান্ডউইচ দ্বীপপুঞ্জ
region-name-gt = গুয়াতেমালা
region-name-gu = গুয়াম
region-name-gw = গিনি-বিসাউ
region-name-gy = গায়ানা
region-name-hk = হং কং
region-name-hm = হার্ড দ্বীপপুঞ্জ ও ম্যাকডোনাল্ড দ্বীপপুঞ্জ
region-name-hn = হন্ডুরাস
region-name-hr = ক্রোয়েশিয়া
region-name-ht = হাইতি
region-name-hu = হাঙ্গেরি
region-name-id = ইন্দোনেশিয়া
region-name-ie = আইরল্যান্ড
region-name-il = ইজরাইল
region-name-im = আইল অফ ম্যান
region-name-in = ভারত
region-name-io = ব্রিটিশ ভারত মহাসাগরীয় অঞ্চল
region-name-iq = ইরাক
region-name-ir = ইরান
region-name-is = আইসল্যান্ড
region-name-it = ইটালি
region-name-je = জার্সি
region-name-jm = জামাইকা
region-name-jo = জর্ডান
region-name-jp = জাপান
region-name-ke = কেনিয়া
region-name-kg = কির্গিজস্তান
region-name-kh = ক্যাম্বোডিয়া
region-name-ki = কিরিবাস
region-name-km = কোমোরোস
region-name-kn = সেন্ট কিটস ও নেভিস
region-name-kp = কোরিয়া, উত্তর
region-name-kr = কোরিয়া, দক্ষিণ
region-name-kw = কুয়েত
region-name-ky = কেম্যান দ্বীপপুঞ্জ
region-name-kz = কাজাখস্তান
region-name-la = লাওস
region-name-lb = লেবানন
region-name-lc = সেন্ট লুসিয়া
region-name-li = লিখতেনস্টাইন
region-name-lk = শ্রীলঙ্কা
region-name-lr = লাইবেরিয়া
region-name-ls = লেসোথো
region-name-lt = লিথুয়ানিয়া
region-name-lu = লাক্সেমবুর্গ
region-name-lv = লাটভিয়া
region-name-ly = লিবিয়া
region-name-ma = মরোক্কো
region-name-mc = মোনাকো
region-name-md = মোল্ডোভা প্রজাতন্ত্র
region-name-me = মন্টেনেগ্রো
region-name-mf = সেন্ট মার্টিন
region-name-mg = মাদাগাস্কার
region-name-mh = মার্শাল দ্বীপপুঞ্জ
region-name-mk = মেসিডোনিয়া
region-name-ml = মালি
region-name-mm = বার্মা
region-name-mn = মঙ্গোলিয়া
region-name-mo = মাকাও
region-name-mp = উত্তর মারিয়ানা দ্বীপপুঞ্জ
region-name-mq = মার্টিনিক
region-name-mr = মরিটানিয়া
region-name-ms = মন্টসেরাত
region-name-mt = মল্টা
region-name-mu = মরিশাস
region-name-mv = মালডিভস
region-name-mw = মালাউই
region-name-mx = মেক্সিকো
region-name-my = মালেশিয়া
region-name-mz = মোজাম্বিক
region-name-na = নামিবিয়া
region-name-nc = নিউ ক্যালেডোনিয়া
region-name-ne = নাইজার
region-name-nf = নরফোল্ক দ্বীপ
region-name-ng = নাইজেরিয়া
region-name-ni = নিকারাগুয়া
region-name-nl = নেদারল্যান্ড
region-name-no = নরওয়ে
region-name-np = নেপাল
region-name-nr = নাউরু
region-name-nu = নিউ
region-name-nz = নিউজিল্যান্ড
region-name-om = ওমান
region-name-pa = পানামা
region-name-pe = পেরু
region-name-pf = ফ্রেঞ্চ পলিনেশিয়া
region-name-pg = পাপুয়া নিউ গিনি
region-name-ph = ফিলিপাইনস
region-name-pk = পাকিস্তান
region-name-pl = পোল্যান্ড
region-name-pm = সেন্ট পিয়ের ও মিকেলন
region-name-pn = পিটকেয়ার্ন দ্বীপপুঞ্জ
region-name-pr = পুয়ের্তো রিকো
region-name-pt = পোর্টুগাল
region-name-pw = পালাউ
region-name-py = পারাগুয়ে
region-name-qa = কাতার
region-name-qm = মিডওয়ে দ্বীপপুঞ্জ
region-name-qs = বাসাস দা ভারত
region-name-qu = জুয়ান দে নোভা দ্বীপ
region-name-qw = ওয়েক দ্বীপ
region-name-qx = গ্লোরিওসো দ্বীপপুঞ্জ
region-name-qz = আক্রোতিরি
region-name-re = রিইউনিয়ান
region-name-ro = রোমানিয়া
region-name-rs = সার্বিয়া
region-name-ru = রাশিয়া
region-name-rw = রওয়ান্ডা
region-name-sa = সৌদি আরব
region-name-sb = সলোমান দ্বীপপুঞ্জ
region-name-sc = সেশেলস
region-name-sd = সুদান
region-name-se = সুইডেন
region-name-sg = সিঙ্গাপুর
region-name-sh = সেন্ট হেলেনা, আসেনশন, এবং ত্রিস্তান দা কুনহা
region-name-si = স্লোভেনিয়া
region-name-sk = স্লোভাকিয়া
region-name-sl = সিয়েরা লিওন
region-name-sm = সান মারিনো
region-name-sn = সেনেগাল
region-name-so = সোমালিয়া
region-name-sr = সুরিনাম
region-name-ss = দক্ষিণ সুদান
region-name-st = সাও টোমে ও প্রিন্সিপে
region-name-sv = এল সালভাডর
region-name-sx = সেন্ট মার্টিন
region-name-sy = সিরিয়া
region-name-sz = সোয়াজিল্যান্ড
region-name-tc = টার্কস ও কেইকোস দ্বীপ
region-name-td = চাড
region-name-tf = ফরাসি দক্ষিণ ও দখিনা জমি
region-name-tg = টোগো
region-name-th = থাইল্যান্ড
region-name-tj = তাজিকিস্তান
region-name-tk = টোকেলাউ
region-name-tl = টিমোর-লেস্তে
region-name-tm = তুর্কমেনিস্তান
region-name-tn = টিউনিশিয়া
region-name-to = টোঙ্গা
region-name-tr = তুর্কি
region-name-tt = ত্রিনিদাদ
region-name-tv = টুভালু
region-name-tw = তাইওয়ান
region-name-tz = তানজানিয়া
region-name-ua = ইউক্রেন
region-name-ug = উগান্ডা
region-name-us = মার্কিন যুক্তরাষ্ট্র
region-name-uy = উরুগুয়ে
region-name-uz = উজবেকিস্তান
region-name-va = ভ্যাটিকান
region-name-vc = সেন্ট ভিনসেন্ট ও গ্রেনাডিনস
region-name-ve = ভেনেজুয়েলা
region-name-vg = ব্রিটিশ ভার্জিন দ্বীপ
region-name-vi = মার্কিন ভার্জিন দ্বীপ
region-name-vn = ভিয়েতনাম
region-name-vu = ভানুয়াটু
region-name-wf = ওয়ালিস ও ফুটুনা
region-name-ws = সামোয়া
region-name-xa = আসমর এবং কারটিয়ের দ্বীপ
region-name-xb = বেকার দ্বীপ
region-name-xc = কোরাল সাগর দ্বীপ
region-name-xd = ধেকেলিয়া
region-name-xe = ইউরোপা দ্বীপ
region-name-xg = গাজা
region-name-xh = হল্যান্ড দ্বীপ
region-name-xj = জান মায়েন
region-name-xk = কসোভো
region-name-xl = পালমিরা প্রবালপ্রাচীর
region-name-xm = কিংম্যান রিফ
region-name-xp = প্যারাসেল দ্বীপপুঞ্জ
region-name-xq = জার্ভিস দ্বীপ
region-name-xr = সয়ালবার্ড
region-name-xs = স্প্রাল্টি দ্বীপপুঞ্জ
region-name-xt = ট্রোমেলিন দ্বীপ
region-name-xu = জনস্টন অ্যাটোল
region-name-xv = নাভাসা দ্বীপ
region-name-xw = পশ্চিম তীর
region-name-ye = ইয়েমেন
region-name-yt = মেওতে
region-name-za = দক্ষিণ আফ্রিকা
region-name-zm = জাম্বিয়া
region-name-zw = জিম্বাবুয়ে
