# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language-name-aa = Tiếng Afar
language-name-ab = Tiếng Abkhazia
language-name-ach = Tiếng Acholi
language-name-ae = Tiếng Avesta
language-name-af = Tiếng Afrikaans
language-name-ak = Tiếng Akan
language-name-am = Tiếng Amhara
language-name-an = Tiếng Aragon
language-name-ar = Tiếng Ả Rập
language-name-as = Tiếng Assam
language-name-ast = Tiếng Asturia
language-name-av = Tiếng Avar
language-name-ay = Tiếng Aymara
language-name-az = Tiếng Azerbaijan
language-name-ba = Tiếng Bashkir
language-name-be = Tiếng Belarut
language-name-bg = Tiếng Bungari
language-name-bh = Tiếng Bihar
language-name-bi = Tiếng Bislama
language-name-bm = Tiếng Bambara
language-name-bn = Tiếng Bengal
language-name-bo = Tiếng Tây Tạng
language-name-br = Tiếng Breton
language-name-bs = Tiếng Bosnia
language-name-ca = Tiếng Catalan
language-name-cak = Tiếng Kaqchikel
language-name-ce = Tiếng Chechnya
language-name-ch = Tiếng Chamorro
language-name-co = Tiếng Corsica
language-name-cr = Tiếng Cree
language-name-crh = Tiếng Thổ Nhĩ Kỳ
language-name-cs = Tiếng Séc
language-name-csb = Tiếng Kashubia
language-name-cu = Tiếng Xlavơ Cũ
language-name-cv = Tiếng Chuvash
language-name-cy = Tiếng Wales
language-name-da = Tiếng Đan Mạch
language-name-de = Tiếng Đức
language-name-dsb = Tiếng Hạ Sorbia
language-name-dv = Tiếng Divehi
language-name-dz = Tiếng Bhutan
language-name-ee = Tiếng Ewe
language-name-el = Tiếng Hy Lạp
language-name-en = Tiếng Anh
language-name-eo = Quốc tế ngữ
language-name-es = Tiếng Tây Ban Nha
language-name-et = Tiếng Estonia
language-name-eu = Tiếng Basque
language-name-fa = Tiếng Ba Tư
language-name-ff = Tiếng Fula
language-name-fi = Tiếng Phần Lan
language-name-fj = Tiếng Fiji
language-name-fo = Tiếng Faroe
language-name-fr = Tiếng Pháp
language-name-fur = Tiếng Friuli
language-name-fy = Tiếng Frisia
language-name-ga = Tiếng Ai Len
language-name-gd = Tiếng Gaelic Xcốtlen
language-name-gl = Tiếng Galicia
language-name-gn = Tiếng Guarani
language-name-gu = Tiếng Gujarat
language-name-gv = Tiếng Manx
language-name-ha = Tiếng Hausa
language-name-haw = Tiếng Hawaii
language-name-he = Tiếng Do Thái
language-name-hi = Tiếng Hindi
language-name-hil = Tiếng Hiligaynon
language-name-ho = Tiếng Hiri Motu
language-name-hr = Tiếng Croatia
language-name-hsb = Tiếng Thượng Sorb
language-name-ht = Tiếng Haiti
language-name-hu = Tiếng Hungari
language-name-hy = Tiếng Armenia
language-name-hz = Tiếng Herero
language-name-ia = Tiếng Interlingua
language-name-id = Tiếng Indonesia
language-name-ie = Tiếng Interlingue
language-name-ig = Tiếng Igbo
language-name-ii = Tiếng Lô Lô
language-name-ik = Tiếng Inupiaq
language-name-io = Tiếng Ido
language-name-is = Tiếng Iceland
language-name-it = Tiếng Ý
language-name-iu = Tiếng Inuktitut
language-name-ja = Tiếng Nhật
language-name-jv = Tiếng Java
language-name-ka = Tiếng Gruzia
language-name-kab = Tiếng Kabyle
language-name-kg = Tiếng Kongo
language-name-ki = Tiếng Kikuyu
language-name-kj = Tiếng Kuanyama
language-name-kk = Tiếng Kazakh
language-name-kl = Tiếng Greenland
language-name-km = Tiếng Khơ-me
language-name-kn = Tiếng Kannada
language-name-ko = Tiếng Hàn Quốc
language-name-kok = Tiếng Konkani
language-name-kr = Tiếng Kanuri
language-name-ks = Tiếng Kashmir
language-name-ku = Tiếng Kurd
language-name-kv = Tiếng Komi
language-name-kw = Tiếng Cornwall
language-name-ky = Tiếng Kyrgyz
language-name-la = Tiếng Latinh
language-name-lb = Tiếng Luxembourg
language-name-lg = Tiếng Ganda
language-name-li = Tiếng Limburg
language-name-lij = Tiếng Liguria
language-name-ln = Tiếng Lingala
language-name-lo = Tiếng Lào
language-name-lt = Tiếng Lithuania
language-name-ltg = Tiếng Latgalia
language-name-lu = Tiếng Luba-Katanga
language-name-lv = Tiếng Latvia
language-name-mai = Tiếng Maithili
language-name-meh = Tiếng Tây Nam Trahiko Mishtec
language-name-mg = Tiếng Malagasy
language-name-mh = Tiếng Marshall
language-name-mi = Tiếng Maori
language-name-mix = Tiếng Mixtepec Mixtec
language-name-mk = Tiếng Macedonia
language-name-ml = Tiếng Malayalam
language-name-mn = Tiếng Mông Cổ
language-name-mr = Tiếng Marathi
language-name-ms = Tiếng Mã Lai
language-name-mt = Tiếng Malta
language-name-my = Tiếng Miến Điện
language-name-na = Tiếng Nauru
language-name-nb = Tiếng Na Uy Bokmål
language-name-nd = Tiếng Ndebele, Bắc
language-name-ne = Tiếng Nepal
language-name-ng = Tiếng Ndonga
language-name-nl = Tiếng Hà Lan
language-name-nn = Tiếng Na Uy Nynorsk
language-name-no = Tiếng Na Uy
language-name-nr = Tiếng Nam Ndebele
language-name-nso = Tiếng Bắc Sotho
language-name-nv = Tiếng Navajo
language-name-ny = Tiếng Chichewa
language-name-oc = Tiếng Occitan
language-name-oj = Tiếng Ojibwa
language-name-om = Tiếng Oromo
language-name-or = Tiếng Odia
language-name-os = Tiếng Ossetia
language-name-pa = Tiếng Punjab
language-name-pi = Tiếng Pali
language-name-pl = Tiếng Ba Lan
language-name-ps = Tiếng Pashto
language-name-pt = Tiếng Bồ Đào Nha
language-name-qu = Tiếng Quechua
language-name-rm = Tiếng Rhaeto-Romanic
language-name-rn = Tiếng Kirundi
language-name-ro = Tiếng Rumani
language-name-ru = Tiếng Nga
language-name-rw = Tiếng Kinyarwanda
language-name-sa = Tiếng Phạn
language-name-sat = Tiếng Santali
language-name-sc = Tiếng Sardinia
language-name-sco = Tiếng Scots
language-name-sd = Tiếng Sindhi
language-name-se = Tiếng Bắc Sami
language-name-sg = Tiếng Trung Phi
language-name-si = Tiếng Sinhala
language-name-sk = Tiếng Slovak
language-name-skr = Tiếng Saraiki
language-name-sl = Tiếng Slovenia
language-name-sm = Tiếng Samoa
language-name-sn = Tiếng Shona
language-name-so = Tiếng Somali
language-name-son = Tiếng Songhay
language-name-sq = Tiếng Anbani
language-name-sr = Tiếng Serbia
language-name-ss = Tiếng Siswati
language-name-st = Tiếng Nam Sotho
language-name-su = Tiếng Sunda
language-name-sv = Tiếng Thụy Điển
language-name-sw = Tiếng Swahili
language-name-szl = Tiếng Silesia
language-name-ta = Tiếng Tamil
language-name-te = Tiếng Telugu
language-name-tg = Tiếng Tajik
language-name-th = Tiếng Thái
language-name-ti = Tiếng Tigrinya
language-name-tig = Tiếng Tigre
language-name-tk = Tiếng Turkmenistan
language-name-tl = Tiếng Tagalog
language-name-tlh = Tiếng Klingon
language-name-tn = Tiếng Tswana
language-name-to = Tiếng Tonga
language-name-tr = Tiếng Thổ Nhĩ Kỳ
language-name-trs = Tiếng Triqui
language-name-ts = Tiếng Tsonga
language-name-tt = Tiếng Tatar
language-name-tw = Tiếng Twi
language-name-ty = Tiếng Tahiti
language-name-ug = Tiếng Duy Ngô Nhĩ
language-name-uk = Tiếng Ucraina
language-name-ur = Tiếng Urdu
language-name-uz = Tiếng Uzbekistan
language-name-ve = Tiếng Venda
language-name-vi = Tiếng Việt
language-name-vo = Tiếng Volapük
language-name-wa = Tiếng Walloon
language-name-wen = Tiếng Sorb
language-name-wo = Tiếng Wolof
language-name-xh = Tiếng Xhosa
language-name-yi = Tiếng Yiddish
language-name-yo = Tiếng Yoruba
language-name-za = Tiếng Tráng
language-name-zam = Tiếng Zapotec Miahuatlán
language-name-zh = Tiếng Trung
language-name-zu = Tiếng Zulu
