# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language-name-aa = Afar
language-name-ab = Abkhazia
language-name-ae = Avesta
language-name-af = Afrikaans
language-name-ak = Akan
language-name-an = Aragon
language-name-ar = Ả Rập
language-name-as = Assam
language-name-ast = Asturia
language-name-av = Avar
language-name-ay = Aymara
language-name-az = Azerbaijan
language-name-ba = Bashkir
language-name-be = Belarut
language-name-bg = Bungari
language-name-bh = Bihar
language-name-bi = Bislama
language-name-bm = Bambara
language-name-bo = Tây Tạng
language-name-br = Breton
language-name-bs = Bosnia
language-name-ca = Catalan
language-name-ce = Chechnya
language-name-ch = Chamorro
language-name-co = Corsica
language-name-cs = Séc
language-name-cu = Xlavơ Cũ
language-name-cv = Chuvash
language-name-cy = Wales
language-name-da = Đan Mạch
language-name-de = Đức
language-name-dv = Divehi
language-name-dz = Bhutan
language-name-ee = Ewe
language-name-en = Anh
language-name-es = Tây Ban Nha
language-name-et = Estonia
language-name-eu = Basque
language-name-fa = Ba Tư
language-name-ff = Fula
language-name-fi = Phần Lan
language-name-fj = Fiji
language-name-fr = Pháp
language-name-fur = Friuli
language-name-ga = Ai Len
language-name-gd = Gaelic Xcốtlen
language-name-gl = Galicia
language-name-gn = Guarani
language-name-gu = Gujarat
language-name-gv = Manx
language-name-ha = Hausa
language-name-he = Do Thái
language-name-hi = Hindi
language-name-ho = Hiri Motu
language-name-hr = Croatia
language-name-hsb = Thượng Sorb
language-name-ht = Haiti
language-name-hu = Hungari
language-name-hy = Armenia
language-name-hz = Herero
language-name-id = Indonesia
language-name-ig = Igbo
language-name-ik = Inupiaq
language-name-io = Ido
language-name-is = Ai-xơ-len
language-name-it = Ý
language-name-iu = Inuktitut
language-name-jv = Java
language-name-ka = Gruzia
language-name-kg = Kongo
language-name-ki = Kikuyu
language-name-kj = Kuanyama
language-name-kk = Kazakh
language-name-kl = Greenland
language-name-km = Khơ-me
language-name-kn = Kannada
language-name-ko = Hàn Quốc
language-name-kok = Konkani
language-name-kr = Kanuri
language-name-ks = Kashmir
language-name-ku = Kurd
language-name-kv = Komi
language-name-kw = Cornwall
language-name-ky = Kyrgyz
language-name-la = Latinh
language-name-lb = Luxembourg
language-name-lg = Ganda
language-name-li = Limburg
language-name-ln = Lingala
language-name-lo = Lào
language-name-lt = Lithuania
language-name-lu = Luba-Katanga
language-name-lv = Latvia
language-name-mg = Malagasy
language-name-mh = Marshall
language-name-mi = Maori
language-name-mk = Macedonia
language-name-ml = Malayalam
language-name-mn = Mông Cổ
language-name-mr = Marathi
language-name-mt = Malta
language-name-na = Nauru
language-name-nd = Ndebele, Bắc
language-name-ne = Nepal
language-name-ng = Ndonga
language-name-nl = Hà Lan
language-name-nn = Na Uy Nynorsk
language-name-no = Na Uy
language-name-nv = Navajo
language-name-ny = Chichewa
language-name-oc = Occitan
language-name-oj = Ojibwa
language-name-om = Oromo
language-name-os = Ossetia
language-name-pi = Pali
language-name-pl = Ba Lan
language-name-ps = Pashto
language-name-pt = Bồ Đào Nha
language-name-qu = Quechua
language-name-rm = Rhaeto-Romanic
language-name-rn = Kirundi
language-name-ro = Rumani
language-name-ru = Nga
language-name-rw = Kinyarwanda
language-name-sa = Phạn
language-name-sd = Sindhi
language-name-se = Bắc Sami
language-name-sg = Trung Phi
language-name-sk = Slovak
language-name-sl = Slovenia
language-name-sn = Shona
language-name-so = Somali
language-name-sq = Anbani
language-name-sr = Serbia
language-name-ss = Siswati
language-name-su = Sunda
language-name-sv = Thụy Điển
language-name-sw = Swahili
language-name-ta = Tamil
language-name-te = Telugu
language-name-tg = Tajik
language-name-th = Thái
language-name-ti = Tigrinya
language-name-tig = Tigre
language-name-tk = Turkmenistan
language-name-tl = Tagalog
language-name-tlh = Klingon
language-name-tn = Tswana
language-name-to = Tonga
language-name-ts = Tsonga
language-name-tt = Tatar
language-name-tw = Twi
language-name-ug = Duy Ngô Nhĩ
language-name-uk = Ucraina
language-name-ur = Urdu
language-name-uz = Uzbekistan
language-name-ve = Venda
language-name-vi = Việt
language-name-wa = Walloon
language-name-wen = Sorb
language-name-wo = Wolof
language-name-yi = Yiddish
language-name-yo = Yoruba
language-name-zh = Hoa
language-name-zu = Zulu
