# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=$ProductName$in asennusohjelma
Welcome_MessageWelcome=%sin asentaja
Welcome_Message0=Olet asentamassa %s 2 alpha 1:ä.
Welcome_Message1=On suositeltavaa, että kaikki muut Windows-ohjelmat suljetaan ohjelman asentamisen ajaksi.
Welcome_Message2=Keskeytä asennus valitsemalla Peruuta, jonka jälkeen voit sulkea avoimet ohjelmat. Jatka asennusta valitsemalla Seuraava.
Welcome_Message3=Valitse Seuraava jatkaaksesi %s 2 alpha 1:n asennusta.

License_Title=Ohjelman lisenssisopimus
License_SubTitle=Ohjelman käyttöehdot.
License_Message0=Lue lisenssisopimus siirtymällä eteenpäin vierityspalkista.
License_Accept=&Hyväksyn lisenssisopimuksen
License_Decline=&En hyväksy lisenssisopimusta

Type_Title=Asennusmuoto
Type_SubTitle=Valitse asennuksen muoto.
Type_Message0=Valitse haluamasi asennusmuoto ja napsauta Seuraava.

Standard_Short=&Oletus
Standard_Long=Thunderbird asennetaan yleisimmillä ohjelmakomponenteilla.

Custom_Short=&Mukautettu
Custom_Long=Valitse mitkä ohjelmakomponentit asennetaan. Suositellaan kokeneille käyttäjille.

Select_Title=Valitse ohjelmakomponentit
Select_SubTitle=Lisäkomponentteja $ProductName$iin.
Select_Message0=Valitse lisäkomponentit, jotka haluat asentaa ja napsauta Seuraava.

Path_Title=Asennuskansio
Path_SubTitle=Kansio, johon $ProductName$ asennetaan.
Path_Message0=$ProductName$ asennetaan kansioon:

Integration_Title=Aseta pikalinkit
Integration_SubTitle=Luo ohjelmakuvakkeet
Integration_Message0=Luo kuvakkeet $ProductShortName$ille:

Integration_Desktop=Työpöydälle
Integration_StartMenu=Käynnistä-valikon ohjelmakansioon
Integration_QuickLaunch=Pikakäynnistyspalkkiin

SelectFolder_Title=$ProductName$in asennus - Valitse ohjelmakansio
SelectFolder_Message0=Asennusohjelmaa lisää ohjelmakuvakkeet alla annettuun ohjelmakansioon. Kirjoita uuden kansion nimi tai valitse jokin kansio listasta. Napsauta Seuraava jatkaaksesi.

Advanced_Title=$ProductName$in asennus - Lisäasetukset
Advanced_Message0=Jos verkkoyhteytesi vaatii välityspalvelimen käyttämistä, syötä kenttiin palvelimen nimi ja porttitiedot. Jos yhteytesi ei vaadi välityspalvelinta, jätä kentät tyhjiksi.

Install_Title=Yhteenveto
Install_SubTitle=Valmis asentamaan $ProductName$.
Install_MessageInstall=Asennetaan seuraavat ohjelmakomponentit:
Install_MessageDownload=Asennusohjelma lataa ja asentaa seuraavat ohjelmakomponentit:
Install_Message0=Napsauta Seuraava jatkaaksesi.

Downloading_Title=Ladataan
Downloading_SubTitle=Ladataan tarvittavia komponentteja…
Downloading_Blurb=Asennusohjelma lataa $ProductName$in asentamiseen vaadittuja tiedostoja.
Downloading_FileName=Ladataan:
Downloading_Time=Aikaa jäljellä:

Installing_Title=Asennetaan
Installing_SubTitle=Asennetaan $ProductName$…
Installing_Blurb=Asennusohjelma asentaa ohjelmatiedostoja.
Installing_Status=Valmistellaan tiedostoa:
Installing_Component=Asennetaan:

Success_Title=Asennus valmis
Success_Header=Asennus valmis
Success_Message0=%s asennettiin onnistuneesti.
Success_Message1=Napsauta Valmis lopettaaksesi asennuksen.
Success_Launch=Käynnistä %s nyt.

Check_Message=$ProductName$in lataus onnistui. $ProductNameInternal$ pitää sulkea, jotta asennusta voidaan jatkaa. Napsauta OK sulkeaksesi $ProductNameInternal$in automaattisesti ja aloittaaksesi asennuksen.
Check_FullMessage=$ProductNameInternal$ pitää sulkea, jotta asennusta voidaan jatkaa. Napsauta OK sulkeaksesi $ProductNameInternal$in automaattisesti ja aloittaaksesi asennuksen.
Check_Wait=Suljetaan $ProductNameInternal$. Ole hyvä ja odota…

Component_XPCOM=Alustariippumaton COM
Component_Mail=$ProductName$
Component_Offline=Verkkoyhteydettömän tilan tuki
Component_Offline_Long=Verkkoyhteydettömän tilan toiminnot $ProductName$iin.
Component_RSS=RSS-tuki
Component_RSS_Long=Tuki RSS-syötteille $ProductName$iin.
Component_QFA=Quality Feedback Agent
Component_QFA_Long=Quality Feedback Agentilla voi välittää Mozilla-säätiölle $ProductName$in mahdollisia kaatumistietoja
