# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

report-broken-site-mainview-title = 反馈网站问题
report-broken-site-panel-header =
    .label = 反馈网站问题
    .title = 反馈网站问题
report-broken-site-panel-intro-text = 您的反馈可帮助我们了解并修复 { -brand-product-name } 中的问题，从而为全体用户改进使用体验。
report-broken-site-panel-learn-more-link = 详细了解
report-broken-site-panel-url-label = 问题网站的网址
report-broken-site-panel-reason-intro-text = 哪一方面不正常？
report-broken-site-panel-reason-load-moz-box-button =
    .label = 网站无法加载
# These terms are referring to ecommerce websites
report-broken-site-panel-reason-checkout-moz-box-button =
    .label = 无法支付、结算或购物
report-broken-site-panel-reason-slow-moz-box-button =
    .label = 网站响应迟缓
report-broken-site-panel-reason-media-moz-box-button =
    .label = 视频无法播放或加载
report-broken-site-panel-reason-content-moz-box-button =
    .label = 内容缺失
report-broken-site-panel-reason-account-moz-box-button =
    .label = 无法登录或注册
report-broken-site-panel-reason-adblocker-moz-box-button =
    .label = 网站要求关闭广告拦截器
report-broken-site-panel-reason-notsupported-moz-box-button =
    .label = 浏览器不受支持或被阻止
report-broken-site-panel-reason-deceptive-moz-box-button =
    .label = 这是诈骗网站
report-broken-site-panel-reason-other-moz-box-button =
    .label = 其他
report-broken-site-panel-instructions-other = 请详细描述问题，帮助我们开展调查。
report-broken-site-panel-instructions-other-optional = 请详细描述问题，帮助我们开展调查。（选填）
report-broken-site-panel-description2 =
    .placeholder = 请描述出现的问题，说明期望的效果，并提供重现问题的步骤。
report-broken-site-panel-send-more-info-button =
    .label = 发送更多信息
report-broken-site-panel-intro = 帮助改善所有用户的 { -brand-product-name } 使用体验。{ -vendor-short-name } 会借助您发送的信息来修复网站问题。
report-broken-site-panel-url = 网址
report-broken-site-panel-reason-label = 什么方面出现问题？
report-broken-site-panel-reason-optional-label = 什么方面出现问题？（选填）
report-broken-site-panel-reason-choose =
    .label = 选择原因
report-broken-site-panel-reason-load =
    .label = 网站无法加载
# These terms are referring to ecommerce websites
report-broken-site-panel-reason-checkout =
    .label = 无法支付、结算或购物
report-broken-site-panel-reason-slow2 =
    .label = 网站响应迟缓
report-broken-site-panel-reason-media2 =
    .label = 视频无法播放或加载
report-broken-site-panel-reason-content2 =
    .label = 内容缺失
report-broken-site-panel-reason-account2 =
    .label = 无法登录或注册
report-broken-site-panel-reason-adblocker2 =
    .label = 网站要求关闭广告拦截器
report-broken-site-panel-reason-notsupported =
    .label = 浏览器不受支持或被阻止
report-broken-site-panel-reason-other =
    .label = 其他
report-broken-site-panel-description-label = 描述问题
report-broken-site-panel-description =
    .placeholder = 请描述出现的问题，说明期望的效果，以及关闭跟踪保护是否有效。
report-broken-site-panel-description-optional-label = 描述问题（选填）
report-broken-site-panel-send-more-info-link = 发送更多信息
report-broken-site-panel-button-cancel =
    .label = 取消
report-broken-site-panel-button-okay =
    .label = 确定
report-broken-site-panel-button-send-report =
    .label = 发送报告
report-broken-site-panel-button-send =
    .label = 发送
report-broken-site-panel-report-sent-label = 反馈已发送
report-broken-site-panel-report-sent-header =
    .label = 反馈已发送
    .title = 反馈已发送
report-broken-site-panel-report-sent-text = 感谢您帮助 { -brand-product-name } 打造更开放、更美好且人人可用的网络。
report-broken-site-panel-invalid-url-label = 请输入有效的网址
# $minLength (number) - The minimum number of characters required in the description textarea.
report-broken-site-panel-invalid-description-label = 请至少输入 { $minLength } 个字符
report-broken-site-panel-screenshot-label =
    .label = 发送截图
report-broken-site-panel-url-input-label =
    .aria-label = 要举报的页面的网址
report-broken-site-panel-missing-reason-label = 请选择原因
report-broken-site-panel-blocked-trackers-label =
    .label = 发送被跟踪保护拦截的网址
report-broken-site-panel-blocked-trackers-description = 增强型跟踪保护可能会拦截某些网站正常运作所需的跟踪器和脚本。
report-broken-site-panel-preview-button =
    .label = 预览报告
report-broken-site-panel-preview-header2 =
    .title = 预览报告
report-broken-site-panel-preview-header =
    .label = 预览报告
