# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = 您要信任“%S”用于如下目的吗？
unnamedCA = 证书颁发机构（未命名）
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = 请输入被用来加密此证书备份的密码：
# Page Info
pageInfo_NoEncryption = 连接未加密
pageInfo_Privacy_None1 = 此网站 %S 不支持加密您正在查看的页面。
pageInfo_Privacy_None2 = 未经加密的信息在互联网的传输过程中可能被他人窥探其内容。
pageInfo_Privacy_None4 = 您正在查看的页面在经互联网传输时未被加密。
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = 连接已加密（%1$S，%2$S 位密钥，%3$S）
pageInfo_BrokenEncryption = 脆弱的加密（%1$S，%2$S 位密钥，%3$S）
pageInfo_Privacy_Encrypted1 = 您当前查看的页面在传送到互联网之前已被加密。
pageInfo_Privacy_Encrypted2 = 加密使得未经授权的人难以查看计算机之间交流的信息。因此，其他人不太可能拦截此网页的传送并从中读取此页面。
pageInfo_MixedContent = 连接已部分加密
pageInfo_MixedContent2 = 您正在查看的页面的部分内容在传输到互联网之前没有经过加密。
pageInfo_WeakCipher = 您到此网站的连接使用了一个较弱的加密并且非私密。其他人可能查看您的信息和修改该网站的行为。
pageInfo_CertificateTransparency_Compliant = 此网站遵守“证书透明度”政策。
# Token Manager
password_not_set = （未设定）
