# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = احفظ
dialogTitleAddBookmark = علامة جديدة
dialogTitleAddMulti = علامات جديدة
dialogTitleEdit = خصائص ”%S“
dialogTitleAddNewBookmark2 = أضِف علامة
dialogTitleEditBookmark = حرّر ”%S“
dialogTitleEditBookmark2 = حرّر العلامة
dialogTitleAddBookmarkFolder = أضِف مجلد علامات
dialogTitleEditBookmarkFolder = حرّر مجلد العلامات
bookmarkAllTabsDefault = [اسم المجلّد]
newFolderDefault = مجلّد جديد
newBookmarkDefault = علامة جديدة
