# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title სანიშნეები
#define bookmarks_heading სანიშნეები

#define bookmarks_toolbarfolder სანიშნეების პულტის დასტა
#define bookmarks_toolbarfolder_description დაამატეთ სანიშნეები ამ დასტაში მათი სანიშნეების პულტზე საჩვენებლად

# LOCALIZATION NOTE (getting_started):
# link title for http://www.mozilla.com/ka/firefox/central/
#define getting_started პირველი ნაბიჯები

# LOCALIZATION NOTE (firefox_heading):
# Firefox links folder name
#define firefox_heading Mozilla Firefox

# LOCALIZATION NOTE (firefox_help):
# link title for http://www.mozilla.com/ka/firefox/help/
#define firefox_help დახმარება და სწავლება

# LOCALIZATION NOTE (firefox_customize):
# link title for http://www.mozilla.com/ka/firefox/customize/
#define firefox_customize Firefox-ის მორგება

# LOCALIZATION NOTE (firefox_community):
# link title for http://www.mozilla.com/ka/firefox/community/
#define firefox_community შემოგვიერთდით

# LOCALIZATION NOTE (firefox_about):
# link title for http://www.mozilla.com/ka/firefox/about/
#define firefox_about ჩვენს შესახებ

#unfilter emptyLines
