#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title სანიშნეები
#define bookmarks_heading სანიშნეები

#define bookmarks_toolbarfolder სანიშნეების პულტის დასტა
#define bookmarks_toolbarfolder_description სანიშნეების პულტზე ასახვისათვის ისინი ამ დასტაში დაამატეთ

# LOCALIZATION NOTE (getting_started):
# link title for http://www.mozilla.com/en-US/firefox/central/
#define getting_started პირველი ნაცნობობა

# LOCALIZATION NOTE (latest_headlines):
# link title for the live bookmarks sample, a redirect on
# http://fxfeeds.mozilla.com/en-US/firefox/headlines.xml
# Changing the redirect is subject to approval of l10n-drivers.
#define latest_headlines ბოლო სიახლეები

# LOCALIZATION NOTE (firefox_heading):
# Firefox links folder name
#define firefox_heading Mozilla Firefox

# LOCALIZATION NOTE (firefox_help):
# link title for http://www.mozilla.com/en-US/firefox/help/
#define firefox_help დახმარება და სწავლება

# LOCALIZATION NOTE (firefox_customize):
# link title for http://www.mozilla.com/en-US/firefox/customize/
#define firefox_customize Firefox-ის მორგება

# LOCALIZATION NOTE (firefox_community):
# link title for http://www.mozilla.com/en-US/firefox/community/
#define firefox_community მიიღეთ მონაწილეობა

# LOCALIZATION NOTE (firefox_about):
# link title for http://www.mozilla.com/en-US/about/
#define firefox_about ჩვენს შესახებ

#unfilter emptyLines
