# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're 

# live.


#define bookmarks_title Bookmarks


#define bookmarks_heading Bookmarks


#define bookmarks_toolbarfolder Ifolda yethulbha yeebhukhmakhi


#define bookmarks_toolbarfolder_description Yongeza iibhukhmakhi kule folda ukuzibona zibonisiwe kwithulbha yeebhukhmakhi


# LOCALIZATION NOTE (getting_started):


# link title for http://en-US.www.mozilla.com/en-US/firefox/central/


#define getting_started Qalisa


# LOCALIZATION NOTE (firefox_heading):


# Firefox links folder name


#define firefox_heading I-Mozilla Firefox


# LOCALIZATION NOTE (firefox_help):


# link title for http://en-US.www.mozilla.com/en-US/firefox/help/


#define firefox_help Uncedo neetyhuthoriyali


# LOCALIZATION NOTE (firefox_customize):


# link title for http://en-US.www.mozilla.com/en-US/firefox/customize/


#define firefox_customize Lungiselela i-Firefox


# LOCALIZATION NOTE (firefox_community):


# link title for http://en-US.www.mozilla.com/en-US/firefox/community/


#define firefox_community Bandakanyeka


# LOCALIZATION NOTE (firefox_about):


# link title for http://en-US.www.mozilla.com/en-US/about/


#define firefox_about Malunga Nathi


#unfilter emptyLines
