# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Hết thời gian chờ
openFile = Mở tập tin
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Tìm %1$S cho “%2$S”
contextMenuSearch.accesskey = S
contextMenuPrivateSearch = Tìm kiếm trong cửa sổ riêng tư
contextMenuPrivateSearch.accesskey = h
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Tìm kiếm với %S trong cửa sổ riêng tư
contextMenuPrivateSearchOtherEngine.accesskey = h
bookmarkAllTabsDefault = [Tên thư mục]
unsignedAddonsDisabled.message = Một số tiện ích đã cài đặt không thể được kiểm định nên đã bị vô hiệu hóa.
unsignedAddonsDisabled.learnMore.label = Tìm hiểu thêm
unsignedAddonsDisabled.learnMore.accesskey = L
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Truy cập lần cuối %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = %S:// đường dẫn
crashedpluginsMessage.title = Phần bổ trợ %S đã bị lỗi.
crashedpluginsMessage.reloadButton.label = Tải lại trang này
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = Gửi báo cáo lỗi
crashedpluginsMessage.submitButton.accesskey = S
crashedpluginsMessage.learnMore = Tìm hiểu thêm…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Có phải bạn muốn truy cập %S?
keywordURIFixup.goTo = Đúng, đưa tôi đến %S
keywordURIFixup.goTo.accesskey = Y
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Cập nhật lên bản %S
update.downloadAndInstallButton.accesskey = U
menuOpenAllInTabs.label = Mở toàn bộ trong các thẻ mới
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Tải lại trang này
tabHistory.goBack = Trở về lại trang này
tabHistory.goForward = Tiến đến trang này
# URL Bar
pasteAndGo.label = Dán & mở đường dẫn
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Tải lại trang này (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Dừng tải trang này (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Đặt lại mức độ thu phóng (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Chuyển đến chế độ đọc sách (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, Đặt lại mức phóng
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Hiển thị các dấu trang của bạn (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Hiển thị tiến độ tải xuống (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Mở một cửa sổ mới (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Mở thẻ mới (%S)
newTabContainer.tooltip = Mở một thẻ mới (%S)\nNhấp và giữ để mở ngăn chứa thẻ mới
newTabAlwaysContainer.tooltip = Chọn ngăn chứa để mở một thẻ mới
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Cho phép %S sử dụng dữ liệu hình ảnh canvas HTML5 của bạn?
canvas.siteprompt2.warning = Điều này có thể được sử dụng để xác định danh tính máy tính của bạn.
canvas.block = Chặn
canvas.block.accesskey = B
canvas.allow2 = Cho phép
canvas.allow2.accesskey = A
canvas.remember2 = Ghi nhớ quyết định này
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Xác minh bởi: %S
identity.identified.verified_by_you = Bạn vừa thêm một ngoại lệ an ninh cho tên miền này.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Chứng chỉ được cấp cho: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Không an toàn
identity.notSecure.tooltip = Kết nối không an toàn
identity.extension.label = Tiện ích mở rộng (%S)
identity.extension.tooltip = Được tải bởi tiện ích mở rộng: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Thu nhỏ (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Đặt lại mức độ thu phóng (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Phóng to (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Cắt (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Sao chép (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Dán (%S)
geolocation.allow = Cho phép
geolocation.allow.accesskey = A
geolocation.block = Chặn
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Điều này sẽ mở cài đặt vị trí của hệ thống. Vui lòng cấp quyền vị trí cho %S.
geolocation.shareWithSite4 = Cho phép %S truy cập vị trí của bạn?
geolocation.shareWithFile4 = Cho phép tập tin cục bộ này truy cập vào vị trí của bạn?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Cho phép %1$S cấp cho %2$S quyền truy cập vào vị trí của bạn?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Cấp quyền vị trí cho %S trong cài đặt hệ thống.
geolocation.systemSettingsTitle = Đang đợi quyền vị trí
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Hệ thống sẽ yêu cầu bạn cấp quyền này cho %S.
geolocation.remember = Ghi nhớ quyết định này
# Virtual Reality Device UI
xr.allow2 = Cho phép
xr.allow2.accesskey = A
xr.block = Chặn
xr.block.accesskey = B
xr.shareWithSite4 = Cho phép %S truy cập thiết bị thực tế ảo? Điều này có thể làm lộ thông tin nhạy cảm.
xr.shareWithFile4 = Cho phép tập tin cục bộ này truy cập thiết bị thực tế ảo? Điều này có thể làm lộ thông tin nhạy cảm.
xr.remember = Ghi nhớ quyết định này
# Persistent storage UI
persistentStorage.allow = Cho phép
persistentStorage.allow.accesskey = A
persistentStorage.block.label = Chặn
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Cho phép %S lưu trữ dữ liệu trong bộ nhớ lâu dài?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Cho phép
webNotifications.allow2.accesskey = A
webNotifications.notNow = Để sau
webNotifications.notNow.accesskey = n
webNotifications.never = Không bao giờ cho phép
webNotifications.never.accesskey = v
webNotifications.alwaysBlock = Luôn chặn
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = Chặn
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Cho phép %S gửi thông báo?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S muốn truy cập các ứng dụng và dịch vụ khác trên thiết bị này.
localhost.remember2 = Ghi nhớ lựa chọn của tôi cho trang web này
localhost.allowlabel = Cho phép
localhost.blocklabel = Chặn
localhost.allow.accesskey = A
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S muốn truy cập các ứng dụng và dịch vụ trên các thiết bị được kết nối với mạng cục bộ của bạn.
localNetwork.remember2 = Ghi nhớ lựa chọn của tôi cho trang web này
localNetwork.allowLabel = Cho phép
localNetwork.allow.accesskey = A
localNetwork.blockLabel = Chặn
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Đưa tôi ra khỏi đây!
safebrowsing.getMeOutOfHereButton.accessKey = G
safebrowsing.deceptiveSite = Trang web lừa đảo!
safebrowsing.notADeceptiveSiteButton.label = Đây không phải là một trang lừa đảo…
safebrowsing.notADeceptiveSiteButton.accessKey = D
safebrowsing.reportedAttackSite = Có người báo đây là trang web có ác ý!
safebrowsing.notAnAttackButton.label = Trang này không có ác ý…
safebrowsing.notAnAttackButton.accessKey = A
safebrowsing.reportedUnwantedSite = Trang này có nghi ngờ cài đặt phần mềm không mong muốn!
safebrowsing.reportedHarmfulSite = Báo cáo trang web độc hại!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Tìm %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Khởi động lại %S ở chế độ xử lý sự cố?
troubleshootModeRestartPromptMessage = Các tiện ích mở rộng, chủ đề và cài đặt tùy chỉnh của bạn sẽ tạm thời bị vô hiệu hóa.
troubleshootModeRestartButton = Khởi động lại
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Trang này đang làm chậm %1$S. Để tăng tốc trình duyệt của bạn, hãy dừng trang này.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Một trang web đang làm chậm %1$S. Để tăng tốc trình duyệt của bạn, hãy dừng trang này.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = “%1$S” đang làm chậm %2$S. Để tăng tốc trình duyệt của bạn, hãy dừng trang đó lại.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = “%1$S” đang làm chậm %2$S. Để tăng tốc trình duyệt của bạn, hãy dừng tiện ích đó lại.
processHang.add-on.learn-more.text = Tìm hiểu thêm
processHang.button_stop2.label = Dừng
processHang.button_stop2.accessKey = S
processHang.button_debug.label = Gỡ lỗi script
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Hiển thị cửa sổ chiếm toàn màn hình (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Chuyển thanh lề sang bên trái
sidebar.moveToRight = Chuyển thanh lề sang bên phải
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Bạn phải kích hoạt DRM để phát một số âm thanh hoặc video trên trang này.
emeNotifications.drmContentDisabled.button.label = Kích hoạt DRM
emeNotifications.drmContentDisabled.button.accesskey = E
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S đang cài đặt các thành phần cần thiết để xem audio hay video trên trang này. Xin hãy thử lại sau.
emeNotifications.unknownDRMSoftware = Không rõ
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Tùy biến %S
decoder.noCodecs.button = Tìm hiểu làm thế nào
decoder.noCodecs.accesskey = L
decoder.noCodecsLinux.message = Để phát video, bạn có thể cần phải cài codec.
decoder.noHWAcceleration.message = Để cải thiện chất lượng video, bạn có thể cần phải cài Media Feature Pack của Microsoft.
decoder.noPulseAudio.message = Để phát âm thanh, bạn có thể cần phải cài phần mềm PulseAudio.
decoder.unsupportedLibavcodec.message = libavcodec có thể bị tấn công hoặc không được hỗ trợ, và nên được cập nhật để phát video.
decoder.decodeError.message = Đã xảy ra lỗi khi mã hóa một tài nguyên phương tiện truyền thông.
decoder.decodeError.button = Báo cáo vấn đề về trang
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = Việc khôi phục đã xảy ra lỗi khi mã hóa một tài nguyên phương tiện truyền thông.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Bạn phải đăng nhập vào hệ thống này trước khi bạn có thể truy cập Internet.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Mở trang đăng nhập hệ thống
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Quyền hạn cho %S
permissions.remove.tooltip = Xóa quyền này và hỏi lại
permissions.fullscreen.promptCanceled = Đã hủy yêu cầu cấp phép đang chờ xử lý: không nên đưa ra yêu cầu cấp phép trước khi vào toàn màn hình DOM.
permissions.fullscreen.fullScreenCanceled = Toàn màn hình DOM đã thoát: không nên đưa ra yêu cầu cấp phép trong khi ở chế độ toàn màn hình DOM.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bit
aboutDialog.architecture.thirtyTwoBit = 32-bit
midi.allow.label = Cho phép
midi.allow.accesskey = A
midi.block.label = Chặn
midi.block.accesskey = B
midi.remember = Ghi nhớ quyết định này
midi.shareWithFile = Cho phép tập tin cục bộ này truy cập thiết bị MIDI của bạn?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Cho phép %S truy cập thiết bị MIDI của bạn?
midi.shareSysexWithFile = Cho phép tập tin cục bộ này truy cập thiết bị MIDI của bạn và gửi/nhận tin nhắn SysEx?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Cho phép %S truy cập thiết bị MIDI của bạn và gửi/nhận tin nhắn SysEx?
serial.allow.label = Cho phép
serial.allow.accesskey = A
serial.block.label = Chặn
serial.block.accesskey = B
serial.shareWithFile = Cho phép tập tin cục bộ này truy cập vào cổng nối tiếp của bạn?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Cho phép %S truy cập vào cổng nối tiếp của bạn?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Quay lại
storageAccess1.Allow.label = Cho phép
storageAccess1.Allow.accesskey = A
storageAccess1.DontAllow.label = Chặn
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Cho phép %1$S sử dụng cookie của mình trên %2$S?
storageAccess1.hintText = Bạn có thể muốn chặn quyền truy cập nếu không rõ tại sao %1$S cần dữ liệu này.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Tìm kiếm trên web cho “%S”
