# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SaveImageTitle = Salve la figure
SaveMediaTitle = Salve file multimediâl
SaveVideoTitle = Salve video
SaveAudioTitle = Salve audio
SaveLinkTitle = Salve cul non
WebPageCompleteFilter = Pagjine Web, complete
WebPageHTMLOnlyFilter = Pagjine Web, dome HTML
WebPageXHTMLOnlyFilter = Pagjine Web, dome XHTML
WebPageSVGOnlyFilter = Pagjine web, dome SVG
WebPageXMLOnlyFilter = Pagjine Web, dome XML
# LOCALIZATION NOTE (UntitledSaveFileName):
#    This is the default filename used when saving a file if a filename could
#    not be determined or if a filename was invalid. A period and file
#    extension may be appended to this string.
UntitledSaveFileName = Cence titul
