# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = সংরক্ষিত লগইন
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = URL অনুলিপি করুন
    .accesskey = y
launch-site-url-cmd =
    .label = URL এ যান
    .accesskey = V
copy-username-cmd =
    .label = ইউজারনেম অনুলিপি কর
    .accesskey = U
edit-username-cmd =
    .label = ইউজারনেম সম্পাদনা d
    .accesskey = d
copy-password-cmd =
    .label = পাসওয়ার্ড অনুলিপি C
    .accesskey = C
edit-password-cmd =
    .label = পাসওয়ার্ড সম্পাদনা E
    .accesskey = E
search-filter =
    .accesskey = S
    .placeholder = অনুসন্ধান
column-heading-site =
    .label = সাইট
column-heading-username =
    .label = ব্যবহারকারীর নাম
column-heading-password =
    .label = পাসওয়ার্ড
column-heading-time-created =
    .label = প্রথমবারের মত ব্যবহৃত
column-heading-time-last-used =
    .label = সর্বশেষ ব্যবহৃত
column-heading-time-password-changed =
    .label = সর্বশেষ পরিবর্তিত
column-heading-times-used =
    .label = যতবার ব্যবহৃত হয়েছে
remove =
    .label = অপসারণ R
    .accesskey = R
import =
    .label = ইমপোর্ট করুন… m
    .accesskey = m
close-button =
    .label = বন্ধ
    .accesskey = C
show-passwords =
    .label = পাসওয়ার্ড প্রদর্শন
    .accesskey = P
hide-passwords =
    .label = পাসওয়ার্ড আড়াল
    .accesskey = P
logins-description-all = আপনার কম্পিউটারে নিম্নলিখিত সাইটগুলোর জন্য লগইন সংরক্ষিত আছে
logins-description-filtered = আপনার অনুসন্ধানের সাথে নিম্নলিখিত লগইন মিলেছে:
remove-all =
    .label = সব অপসারণ করুন
    .accesskey = A
remove-all-shown =
    .label = প্রদর্শিত সকল কিছু অপসারণ করুন
    .accesskey = A
remove-all-passwords-prompt = আপনি কি নিশ্চিত আপনি সব পাসওয়ার্ড অপসারণ করতে চান?
remove-all-passwords-title = সব পাসওয়ার্ড অপসারণ করা হবে
no-master-password-prompt = আপনি কি নিশ্চিত আপনি পাসওয়ার্ড প্রদর্শন করতে চান?
