# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

appmenu-update-available2 =
    .label = Tá nuashonrú ar fáil
    .buttonlabel = Íosluchtaigh é
    .buttonaccesskey = D
    .secondarybuttonlabel = Ná bac leis
    .secondarybuttonaccesskey = m
appmenu-update-available-message2 = Íosluchtaigh an leagan is úire de { -brand-shorter-name }.
appmenu-update-manual2 =
    .label = Tá nuashonrú ar fáil
    .buttonlabel = Íosluchtaigh é
    .buttonaccesskey = D
    .secondarybuttonlabel = Ná bac leis
    .secondarybuttonaccesskey = m
appmenu-update-manual-message2 = Níorbh fhéidir le { -brand-shorter-name } nuashonrú go huathoibríoch. Íosluchtaigh an leagan is úire — ní chaillfidh tú faisnéis atá i dtaisce agat ná aon saincheapú.
appmenu-update-unsupported2 =
    .label = Ní féidir nuashonrú
    .buttonlabel = Tuilleadh eolais
    .buttonaccesskey = L
    .secondarybuttonlabel = Ná bac leis
    .secondarybuttonaccesskey = m
appmenu-update-unsupported-message2 = Níl do chóras oibriúcháin comhoiriúnach leis an leagan is úire de { -brand-shorter-name }.
appmenu-update-restart2 =
    .label = Tá nuashonrú ar fáil
    .buttonlabel = Nuashonraigh agus atosaigh é
    .buttonaccesskey = U
    .secondarybuttonlabel = Ná bac leis
    .secondarybuttonaccesskey = m
appmenu-update-restart-message2 = Faigh an leagan is déanaí de { -brand-shorter-name }. Cuirfear ar ais cluaisíní agus fuinneoga atá ar oscailt.
appmenu-theme-installed =
    .secondarybuttonlabel = Cealaigh
    .secondarybuttonaccesskey = C
appmenu-update-other-instance =
    .label = Ní féidir le { -brand-shorter-name } nuashonrú go huathoibríoch chuig an leagan is déanaí.
    .buttonlabel = Nuashonraigh { -brand-shorter-name } cibé ar bith
    .buttonaccesskey = U
    .secondarybuttonlabel = Ní anois
    .secondarybuttonaccesskey = N
appmenu-update-other-instance-message = Tá nuashonrú nua de { -brand-shorter-name } ar fáil, ach ní féidir é a shuiteáil mar tá leagan eile de { -brand-shorter-name } ag rith. Dún é chun leanúint leis an nuashonrú, nó roghnaigh chun é a nuashonrú cibé ar bith (b'fhéidir nach bhfeidhmeoidh an leagan eile i gceart go dtí go ndéanfaidh tú é atosú).
appmenu-addon-private-browsing-installed2 =
    .buttonlabel = Tá go maith
    .buttonaccesskey = O
appmenu-addon-post-install-message3 = Bainistigh do chuid breiseáin agus téamaí trí roghchlár an fheidhmchláir.
appmenu-addon-post-install-incognito-checkbox =
    .label = Lig don bhreiseán seo rith i bhFuinneoga Príobháideacha
    .accesskey = P
appmenu-new-tab-controlled-changes =
    .label = Athraíodh do chluaisín nua.
    .buttonlabel = Coinnigh na hathruithe
    .buttonaccesskey = K
    .secondarybuttonlabel = Bainistigh Cluaisíní Nua
    .secondarybuttonaccesskey = M
appmenu-homepage-controlled-changes =
    .label = Athraíodh do leathanach baile.
    .buttonlabel = Coinnigh na hathruithe
    .buttonaccesskey = K
    .secondarybuttonlabel = Bainistigh an Leathanach Baile
    .secondarybuttonaccesskey = M
appmenu-tab-hide-controlled =
    .label = Rochtain ar do chluaisíní i bhfolach
    .buttonlabel = Fág cluaisíní i bhfolach
    .buttonaccesskey = F
    .secondarybuttonlabel = Díchumasaigh an síneadh
    .secondarybuttonaccesskey = D
