# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# This is a multi-line message.
psmerr-hostreusedissuerandserial =
    Tá teastas neamhbhailí faighte agat. Téigh i dteagmháil le riarthóir an fhreastalaí nó do chomhfhreagraí ríomhphoist agus tabhair dó/di an t-eolas seo:
    
    Tá an tsraithuimhir chéanna ag do theastas agus atá ag teastas eile eisithe ag an údarás deimhniúcháin. Faigh teastas nua le sraithuimhir uathúil le do thoil.
ssl-error-no-certificate = Ní féidir an teastas nó an eochair atá riachtanach le haghaidh fíordheimhnithe a aimsiú.
ssl-error-bad-client = Fuair an freastalaí drochshonraí ón gcliant.
ssl-error-bad-server = Fuair an cliant drochshonraí ón bhfreastalaí.
ssl-error-unsupported-certificate-type = Ní thacaítear leis an gcineál teastais.
ssl-error-wrong-certificate = Theip ar fhíordheimhniú an chliaint: ní mheaitseálann an eochair phríobháideach sa bhunachar sonraí eochracha leis an eochair phoiblí sa bhunachar sonraí teastas.
ssl-error-ssl-disabled = Ní féidir ceangal: tá SSL díchumasaithe.
ssl-error-unknown-cipher-suite = Tá sraith shifir SSL anaithnid iarrtha.
ssl-error-no-ciphers-supported = Níl sraith shifir ar bith le fáil agus cumasaithe sa chlár seo.
ssl-error-bad-block-padding = Fuair SSL taifead le stuáil bhloic mhícheart.
ssl-error-rx-record-too-long = Fuair SSL taifead a sháraigh an fad is mó atá ceadaithe.
ssl-error-tx-record-too-long = Rinne SSL iarracht taifead a sheoladh a sháraigh an fad is mó atá ceadaithe.
ssl-error-rx-malformed-change-cipher = Fuair SSL taifead mídhéanta Athraigh Sonraíocht Sifir.
ssl-error-rx-malformed-alert = Fuair SSL taifead mídhéanta Airdill.
ssl-error-rx-malformed-handshake = Fuair SSL taifead mídhéanta Cumarsáid Thionscantach.
ssl-error-rx-malformed-application-data = Fuair SSL taifead mídhéanta Sonraí Feidhmchláir.
ssl-error-rx-unknown-record-type = Fuair SSL taifead le cineál inneachair anaithnid.
ssl-error-rx-unknown-alert = Fuair SSL taifead airdill le cur síos airdill anaithnid.
ssl-error-generate-random-failure = Theip ar ghineadóir uimhreacha randamacha SSL.
ssl-error-sign-hashes-failure = Níorbh fhéidir na sonraí atá riachtanach le do theastas a fhíorú a shíniú go digiteach.
ssl-error-server-key-exchange-failure = Teip neamhshonraithe le linn próiseála cumarsáide tionscantaí Malartú Eochrach Freastalaí SSL.
ssl-error-encryption-failure = Theip ar algartam criptiúcháin toirte sa sraith shifir roghnaithe.
ssl-error-decryption-failure = Theip ar algartam díchriptiúcháin toirte sa sraith shifir roghnaithe.
ssl-error-socket-write-failure = Theip ar iarracht sonraí criptithe a scríobh chuig an bunsoicéad.
ssl-error-md5-digest-failure = Theip ar an bhfeidhm achoimre MD5.
ssl-error-sha-digest-failure = Theip ar an bhfeidhm achoimre SHA-1.
ssl-error-mac-computation-failure = Theip ar ríomh an chóid fhíordheimhnithe teachtaireachta (MAC).
ssl-error-sym-key-context-failure = Theip ar chruthú comhthéacs Eochrach Siméadrach.
ssl-error-sym-key-unwrap-failure = Níorbh fhéidir an eochair shiméadrach i dteachtaireacht Mhalartú Eochrach Cliaint.
ssl-error-pub-key-size-limit-exceeded = Rinne an freastalaí SSL iarracht eochair phoiblí de ghrád intíre a úsáid le sraith shifir easpórtála.
ssl-error-iv-param-failure = Níor éirigh le bogearra PKCS11 veicteoir túsaithe a aistriú go paraiméadar.
ssl-error-init-cipher-suite-failure = Níorbh fhéidir an tsraith shifir roghnaithe a thúsú.
ssl-error-session-key-gen-failure = Níor éirigh leis an gcliant eochracha seisiúin a chruthú don seisiún SSL.
ssl-error-no-server-key-for-alg = Níl eochair ag an bhfreastalaí don algartam malartaithe eochrach a iarradh.
ssl-error-token-insertion-removal = Cuireadh isteach nó baineadh ceadchomhartha PKCS#11 le linn oibríochta.
ssl-error-token-slot-not-found = Níorbh fhéidir ceadchomhartha PKCS#11 a aimsiú chun oibríocht riachtanach a dhéanamh.
ssl-error-handshake-not-completed = Ní féidir cumarsáid thionscantach SSL eile a thosú go dtí go mbeidh an ceann reatha críochnaithe.
ssl-error-cert-kea-mismatch = Ní féidir an teastas a sholáthraíodh a úsáid leis an algartam malartaithe eochrach atá roghnaithe.
ssl-error-insufficient-security-alert = Tá sifir níos sláine ná na cinn a thacaíonn an cliant leo ag teastáil ón bhfreastalaí.
ssl-error-server-cache-not-configured = Níl taisce an fhreastalaí SSL cumraithe agus díchumasaithe don soicéad seo.
sec-error-io = Tharla earráid I/A le linn údarú slándála.
sec-error-library-failure = Teip sa leabharlann slándála.
sec-error-bad-data = leabharlann slándála: fuarthas sonraí mícheart.
sec-error-output-len = leabharlann slándála: earráid fhaid aschuir.
sec-error-input-len = earráid fhaid ionchuir sa leabharlann slándála.
sec-error-invalid-args = leabharlann slándála: argóintí neamhbhailí.
sec-error-invalid-algorithm = leabharlann slándála: algartam neamhbhailí.
sec-error-invalid-ava = leabharlann slándála: AVA neamhbhailí.
sec-error-invalid-time = Teaghrán ama drochfhormáidte.
sec-error-bad-der = leabharlann slándála: droch-fhormáidiú ar theachtaireacht códaithe de réir DER.
sec-error-bad-password = Tá an focal faire slándála a iontráladh mícheart.
sec-error-no-nodelock = leabharlann slándála: gan díghlasáil.
sec-error-bad-database = leabharlann slándála: bunachar sonraí neamhbhailí.
sec-error-no-memory = leabharlann slándála: theip ar leithdháileadh cuimhne
sec-error-duplicate-cert = Tá an teastas i do bhunachar sonraí cheana.
sec-error-adding-cert = Earráid agus an teastas á chur sa bhunachar sonraí.
sec-error-filing-key = Theip ar athchur i gcomhad na heochrach le haghaidh an teastais seo.
sec-error-no-key = Ní féidir eochair phríobháideach an teastais seo a aimsiú i mbunachar sonraí na n-eochracha.
sec-error-cert-valid = Tá an teastas seo bailí.
sec-error-cert-not-valid = Níl an teastas seo bailí.
sec-error-cert-no-response = Leabharlann teastais: ní bhfuarthas freagra
sec-error-crl-invalid = Tá an LTC nua i bhformáid neamhbhailí.
sec-error-extension-value-invalid = Tá luach eisínteachta an teastais neamhbhailí.
sec-error-extension-not-found = Níor aimsíodh eisínteacht an teastais.
sec-error-ca-cert-invalid = Tá teastas an eisitheora neamhbhailí.
sec-error-path-len-constraint-invalid = Tá iallach fhad na conaire neamhbhailí.
sec-error-cert-usages-invalid = Tá réimse úsáideanna an teastais neamhbhailí.
sec-internal-only = **Modúl inmheánach amháin**
sec-error-invalid-key = Ní thacaíonn an eochair leis an obráid iarrtha.
sec-error-unknown-critical-extension = Tá eisínteacht ríthábhachtach anaithnid sa teastas.
sec-error-old-crl = Níl an LTC nua níos déanaí ná an ceann reatha.
sec-error-no-email-cert = Gan criptiú agus gan síniú: níl teastas ríomhphoist agat fós.
sec-error-no-recipient-certs-query = Gan criptiú: níl teastas agat do gach uile faighteoir.
sec-error-not-a-recipient = Ní féidir díchriptiú a dhéanamh: ní faighteoir tú, nó níor aimsíodh teastas agus eochair phríobháideach a oireann dá chéile.
sec-error-pkcs7-keyalg-mismatch = Ní féidir díchriptiú: ní oireann an t-algartam criptithe eochrach do do theastas.
sec-error-pkcs7-bad-signature = Theip ar fíordheimhniú sínithe: níor aimsíodh sínitheoir, nó aimsíodh an iomarca sínitheoirí, nó bhí sonraí truaillithe nó mícheart ann.
sec-error-unsupported-keyalg = Algartam eochrach nach dtacaítear leis no nach n-aithnítear.
sec-error-decryption-disallowed = Ní féidir díchriptiú a dhéanamh: criptithe le halgartam nó méid eochrach mícheadaithe.
xp-sec-fortezza-no-card = Níor aimsíodh cárta Fortezza
xp-sec-fortezza-none-selected = Níl cárta Fortezza roghnaithe
xp-sec-fortezza-more-info = Roghnaigh pearsantacht faoina bhfuil breis eolais ag teastáil
xp-sec-fortezza-person-not-found = Níor aimsíodh an phearsantacht
xp-sec-fortezza-no-more-info = Níl breis eolais le fáil faoin bpearsantacht sin
xp-sec-fortezza-bad-pin = Uimhir Aitheantais Phearsanta (UAP) neamhbhailí
sec-error-krl-invalid = Tá formáid an Liosta Eochracha Cúlghairthe nua neamhbhailí.
sec-error-need-random = leabharlann slándála: tá sonraí randamacha ag teastáil.
sec-error-no-module = leabharlann slándála: ní féidir le modúl slándála ar bith an oibríocht iarrtha a dhéanamh.
sec-error-no-token = Níl an cárta nó ceadchomhartha slándála ann, nó ní mór é a thúsú, nó baineadh é.
sec-error-read-only = leabharlann slándála: bunachar sonraí inléite amháin.
sec-error-no-slot-selected = Níor roghnaíodh sliotán nó ceadchomhartha.
sec-error-cert-nickname-collision = Tá teastas ann cheana leis an leasainm sin.
sec-error-key-nickname-collision = Tá eochair ann cheana leis an leasainm sin.
sec-error-safe-not-created = earráid agus réad slán á chrúthú
sec-error-baggage-not-created = earráid agus réad bagáiste á chruthú
sec-error-bad-export-algorithm = Níl an algartam riachtanach ceadaithe.
sec-error-exporting-certificates = Earráid agus iarracht á déanamh teastais a easpórtáil.
sec-error-importing-certificates = Earráid agus iarracht á déanamh teastais a iompórtáil.
sec-error-user-cancelled = Bhrúigh an úsáideoir Cealaigh.
sec-error-pkcs12-duplicate-data = Níor iompórtáladh é; tá sé sa bhunachar sonraí cheana.
sec-error-message-send-aborted = Níor seoladh an teachtaireacht.
sec-error-inadequate-key-usage = Tá an úsáid eochrach teastais uireasach le haghaidh na hoibríochta iarrtha.
sec-error-inadequate-cert-type = Níl an cineál teastais ceadaithe don usáid.
sec-error-cert-addr-mismatch = Ní mheaitseálann an seoladh sa teastas sínithe leis an seoladh i gceanntásca na teachtaireachta.
sec-error-keygen-fail = Níorbh fhéidir an péire eochracha poiblí/príobháideach a chruthú.
sec-error-bad-nickname = Tá leasainm an teastais in úsáid cheana.
sec-error-cannot-move-sensitive-key = Ní féidir eochair íogair a bhogadh go dtí an sliotán ina bhfuil gá lei.
sec-error-js-invalid-module-name = Ainm neamhbhailí don mhodúl.
sec-error-js-invalid-dll = Tá conair nó ainm comhaid an mhodúil neamhbhailí
sec-error-js-add-mod-failure = Níorbh fhéidir an modúl a chur leis
sec-error-js-del-mod-failure = Níorbh fhéidir an modúl a scriosadh
sec-error-old-krl = Níl an Liosta Eochracha Cúlghairthe níos déanaí ná an ceann reatha.
sec-error-krl-not-yet-valid = Níl Liosta Eochracha Cúlghairthe an teastais seo bailí fós.
sec-error-crl-not-yet-valid = Níl Liosta Teastas Cúlghairthe an teastais seo bailí fós.
sec-error-unknown-cert = Níorbh fhéidir an teastas iarrtha a aimsiú.
sec-error-cert-bad-access-location = Tá formáid neamhbhailí ar an suíomh le haghaidh an fhreastalaí stádais teastas.
sec-error-ocsp-unknown-response-type = Ní féidir an freagra OCSP a dhíchódú ian iomláine; is de chineál anaithnid é.
sec-error-ocsp-bad-http-response = Sheol an freastalaí OCSP sonraí HTTP nach rabhthar ag súil leo nó atá neamhbhailí.
sec-error-ocsp-malformed-request = Mheas an freastalaí OCSP go bhfuil an t-iarratas truaillithe nó míchumtha.
sec-error-ocsp-server-error = Tharla earráid inmheánach ar an bhfreastalaí OCSP.
sec-error-ocsp-try-server-later = Molann an freastalaí OCSP iarracht a dhéanamh níos déanaí.
sec-error-ocsp-request-needs-sig = Tá síniú ar an iarratas seo ag teastáil ón bhfreastalaí OCSP.
sec-error-ocsp-unauthorized-request = Dhiúltaigh an freastalaí OCSP leis an iarratas seo toisc é a bheith neamhúdaraithe.
sec-error-ocsp-unknown-response-status = Sheol an freastalaí OCSP stádas do-aitheanta.
sec-error-ocsp-unknown-cert = Níl aon stádas ag an bhfreastalaí OCSP don teastas.
sec-error-ocsp-not-enabled = Caithfear OCSP a chumasú roimh an oibríocht seo a dhéanamh.
sec-error-ocsp-no-default-responder = Caithfear an freagróir OCSP réamhshocraithe a shocrú roimh an oibríocht seo a dhéanamh.
sec-error-ocsp-malformed-response = Bhí an freagra ón bhfreastalaí OCSP truaillithe nó míchumtha.
sec-error-ocsp-unauthorized-response = Níl sínitheoir an fhreagra OCSP údaraithe chun stádas an teastais seo a thabhairt.
sec-error-ocsp-future-response = Níl an freagra OCSP bailí fós (tá a dháta sa todhchaí).
sec-error-ocsp-old-response = Tá faisnéis atá as dáta sa bhfreagra OCSP.
sec-error-digest-not-found = Níor aimsíodh an achoimre CMS nó PKCS #7 sa teachtaireacht shínithe.
sec-error-unsupported-message-type = Ní thacaítear leis an gcineál teachtaireachta CMS nó PKCS #7.
sec-error-module-stuck = Níorbh fhéidir an modúl PKCS #11 a bhaint toisc é a bheith fós in úsáid.
sec-error-bad-template = Níorbh fhéidir sonraí ASN.1 a dhíchódú. Bhí an teimpléad sonraithe neamhbhailí.
sec-error-crl-not-found = Níor aimsíodh LTC a mheaitseálann.
sec-error-reused-issuer-and-serial = Tá tú ag iarraidh teastas a iompórtáil leis an eisitheoir nó an tsraithuimhir chéanna atá ar theastas atá ann cheana, ach nach an teastas céanna é.
sec-error-busy = Níorbh fhéidir le NSS stopadh. Tá réada fós in úsáid.
sec-error-extra-input = Bhí sonraí breise neamhúsáidte i dteachtaireacht códaithe de réir DER.
sec-error-unsupported-elliptic-curve = Cuar éilipseach nach dtacaítear leis.
sec-error-unsupported-ec-point-form = Cuar éilipseach i bhfoirm pointe nach dtacaítear leis.
sec-error-unrecognized-oid = Aitheantóir Réada neamhaitheanta.
sec-error-ocsp-invalid-signing-cert = Teastas sínithe OCSP neamhbhailí sa bhfreagra OCSP.
sec-error-unknown-object-type = Sonraíodh cineál réada anaithnid.
sec-error-incompatible-pkcs11 = Sáraíonn an tiománaí PKCS #11 an sonraíocht i slí neamhchomhoiriúnach.
sec-error-no-event = Níl imeacht nua sliotáin ar fáil faoi láthair.
sec-error-crl-already-exists = Tá an LTC ann cheana.
sec-error-not-initialized = Níl NSS (seirbhísí slándála líonra) túsaithe.
sec-error-ocsp-bad-signature = Tá síniú neamhbhailí ar an bhfreagra OCSP.
