# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = ई कलेल  देख रहल अछि { $host }...
network-connection-status-connected = { $host } मे जुड़ल अछि...
network-connection-status-sending-request = { $host } मे आग्रह पठाए रहल अछि...
network-connection-status-transferring-data = { $host } सँ आंकड़ा हस्तांतरित कए रहल अछि...
network-connection-status-connecting = { $host } मे जुड़ल अछि...
network-connection-status-read = { $host } पढू
network-connection-status-wrote = { $host } लिखू
network-connection-status-waiting = { $host } कलेल प्रतीक्षारत...
network-connection-status-looked-up = { $host } कलेल देखलक…
