# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Makîneya { $host }'ê tê dahûrandin...
network-connection-status-connected = Bi { $host }'ê ve girêdan pêk hat...
network-connection-status-sending-request = Ji { $host }'ê re daxwaz tê şandin...
network-connection-status-transferring-data = Ji cihê { $host }'ê dane tê guhêztin...
network-connection-status-connecting = { $host }'ê ve tê girêdan...
network-connection-status-read = { $host }'ê bixwîne
network-connection-status-wrote = { $host } nivîsand
network-connection-status-waiting = Li benda { $host }'ê ye...
network-connection-status-looked-up = Li { $host }ê digere…
