# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Viltu treysta “%S” fyrir eftirfarandi hluti?
unnamedCA = Vottunarstöð (ónefnt)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Settu inn lykilorðið sem var notað til að dulkóða öryggisafrit skilríkis:
# Page Info
pageInfo_NoEncryption = Tenging ekki dulkóðuð
pageInfo_Privacy_None1 = Vefsvæðið %S styður ekki dulritun fyrir síðuna sem þú ert að skoða.
pageInfo_Privacy_None2 = Þær upplýsingar sem eru sendar yfir netið án dulritunar geta aðrir skoðað á meðan gögnin eru að sendast.
pageInfo_Privacy_None4 = Síðan sem þú ert að skoða var ekki dulkóðuð áður en hún var send yfir Internetið.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Tenging dulkóðuð (%1$S, %2$S-bita lyklar, %3$S)
pageInfo_BrokenEncryption = Gölluð dulkóðuð (%1$S, %2$S-bita lyklar, %3$S)
pageInfo_Privacy_Encrypted1 = Síðan sem þú ert að skoða var dulkóðuð áður en hún var send yfir Internetið.
pageInfo_Privacy_Encrypted2 = Dulritun gerir óviðkomandi nánast ómögulegt að skoða upplýsingar sem eru að ferðast á milli tölva. Það er því frekar ólíklegt að nokkur geti lesið síðu þegar hún er send á netinu.
pageInfo_MixedContent = Tenging að hluta til dulkóðuð
pageInfo_MixedContent2 = Sumir hlutar af síðunni sem þú ert að skoða voru ekki dulkóðaðar áður en þær voru sendar yfir Internetið.
pageInfo_WeakCipher = Tengingin við þetta vefsvæði notar lélega dulritun og er ekki einangruð frá annarri umferð. Aðrir geta skoðað þessar upplýsingar eða breytt virkni vefsvæðisins.
pageInfo_CertificateTransparency_Compliant = Þetta vefsvæði er samhæft við reglur um gagnsæi skilríkja.
# Token Manager
password_not_set = (ekki sett)
