# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host } lahendamine...
network-connection-status-connected = Ühendatud { $host }...
network-connection-status-sending-request = Päringu saatmine { $host }...
network-connection-status-transferring-data = Andmete ülekanne { $host }...
network-connection-status-connecting = Ühendumine { $host }...
network-connection-status-read = { $host } loetud
network-connection-status-wrote = { $host } kirjutatud
network-connection-status-waiting = { $host } ootamine...
network-connection-status-looked-up = Lahendati { $host }…
network-connection-status-tls-handshake = TLS-kätlemine saidiga { $host }…
network-connection-status-tls-handshake-finished = TLS-kätlemine saidiga { $host } lõpetati…
