# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Atɨka ɨmɨe
import-from-bookmarks = Átɨri rigɨnoa bíemo:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-nothing =
    .label = Átɨñeno
    .accesskey = Á
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = x
import-from-360se =
    .label = 360 Ñúe makara
    .accesskey = 3
import-items-title =
    .label = Ráanɨaɨ atɨyena
import-items-description = Nɨze nana ranɨaɨ átɨyena:
import-migrating-title =
    .label = Atɨatɨka...
import-migrating-description = Bíe ráanɨaɨ já átɨka...
import-select-profile-title =
    .label = Nɨze náama mamekɨ
import-select-profile-description = Náama mamekɨ atɨrede:
import-done-title =
    .label = Átɨka já fúite
import-done-description = Bíe ráanɨaɨ ñue atɨka:
import-close-source-browser = Éroiri ñúe. makara nɨzeka ɨbaire makayena abɨdo:
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = Íe { $source }
source-name-ie = Internet Explorer
source-name-edge = Micosoft Edge
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Ñúe makara
imported-safari-reading-list = Fakádua raɨe kuejina (de Safari)
imported-edge-reading-list = Fakádua raɨe kuejina (de Edge)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Internetn nɨzeyena
    .value = Internetn nɨzeyena
browser-data-edge-1 =
    .label = Abɨdo fɨnoka
    .value = Abɨdo fɨnoka
browser-data-safari-1 =
    .label = Kúe gaɨga
    .value = Kúe gaɨga
browser-data-chrome-1 =
    .label = Kúe gaɨga
    .value = Kúe gaɨga
browser-data-canary-1 =
    .label = Kúe gaɨga
    .value = Kúe gaɨga
browser-data-360se-1 =
    .label = Kúe gaɨga
    .value = Kúe gaɨga
browser-data-ie-2 =
    .label = Cookies
    .value = Cookies
browser-data-edge-2 =
    .label = Cookies
    .value = Cookies
browser-data-safari-2 =
    .label = Cookies
    .value = Cookies
browser-data-chrome-2 =
    .label = Cookies
    .value = Cookies
browser-data-canary-2 =
    .label = Cookies
    .value = Cookies
browser-data-firefox-2 =
    .label = Cookies
    .value = Cookies
browser-data-360se-2 =
    .label = Cookies
    .value = Cookies
browser-data-ie-4 =
    .label = Jagaɨ makara
    .value = Jagaɨ makara
browser-data-edge-4 =
    .label = Jagaɨ makara
    .value = Jagaɨ makara
browser-data-safari-4 =
    .label = Jagaɨ makara
    .value = Jagaɨ makara
browser-data-chrome-4 =
    .label = Jagaɨ makara
    .value = Jagaɨ makara
browser-data-canary-4 =
    .label = Jagaɨ makara
    .value = Jagaɨ makara
browser-data-firefox-history-and-bookmarks-4 =
    .label = Jagaɨ makara rɨgɨnoa dɨga
    .value = Jagaɨ makara rɨgɨnoa dɨga
browser-data-360se-4 =
    .label = Jagaɨ makara
    .value = Jagaɨ makara
browser-data-ie-8 =
    .label = Jagaɨ makara kúega íe ja ñúe jonega
    .value = Jagaɨ makara kúega íe ja ñúe jonega
browser-data-edge-8 =
    .label = Jagaɨ makara kúega íe ja ñúe jonega
    .value = Jagaɨ makara kúega íe ja ñúe jonega
browser-data-safari-8 =
    .label = Jagaɨ makara kúega íe ja ñúe jonega
    .value = Jagaɨ makara kúega íe ja ñúe jonega
browser-data-chrome-8 =
    .label = Jagaɨ makara kúega íe ja ñúe jonega
    .value = Jagaɨ makara kúega íe ja ñúe jonega
browser-data-canary-8 =
    .label = Jagaɨ makara kúega íe ja ñúe jonega
    .value = Jagaɨ makara kúega íe ja ñúe jonega
browser-data-firefox-8 =
    .label = Jagaɨ makara kúega íe ja ñúe jonega
    .value = Jagaɨ makara kúega íe ja ñúe jonega
browser-data-360se-8 =
    .label = Jagaɨ makara kúega íe ja ñúe jonega
    .value = Jagaɨ makara kúega íe ja ñúe jonega
browser-data-ie-16 =
    .label = Fákara ráa ñúe jónega
    .value = Fákara ráa ñúe jónega
browser-data-edge-16 =
    .label = Fákara ráa ñúe jónega
    .value = Fákara ráa ñúe jónega
browser-data-safari-16 =
    .label = Fákara ráa ñúe jónega
    .value = Fákara ráa ñúe jónega
browser-data-chrome-16 =
    .label = Fákara ráa ñúe jónega
    .value = Fákara ráa ñúe jónega
browser-data-canary-16 =
    .label = Fákara ráa ñúe jónega
    .value = Fákara ráa ñúe jónega
browser-data-firefox-16 =
    .label = Fákara ráa ñúe jónega
    .value = Fákara ráa ñúe jónega
browser-data-360se-16 =
    .label = Fákara ráa ñúe jónega
    .value = Fákara ráa ñúe jónega
browser-data-ie-32 =
    .label = Gaɨga
    .value = Gaɨga
browser-data-edge-32 =
    .label = Gaɨga
    .value = Gaɨga
browser-data-safari-32 =
    .label = Rɨgɨnoa
    .value = Rɨgɨnoa
browser-data-chrome-32 =
    .label = Rɨgɨnoa
    .value = Rɨgɨnoa
browser-data-canary-32 =
    .label = Rɨgɨnoa
    .value = Rɨgɨnoa
browser-data-360se-32 =
    .label = Rɨgɨnoa
    .value = Rɨgɨnoa
browser-data-ie-64 =
    .label = Jɨaɨe ráanɨ
    .value = Jɨaɨe ráanɨ
browser-data-edge-64 =
    .label = Jɨaɨe ráanɨ
    .value = Jɨaɨe ráanɨ
browser-data-safari-64 =
    .label = Jɨaɨe ráanɨ
    .value = Jɨaɨe ráanɨ
browser-data-chrome-64 =
    .label = Jɨaɨe ráanɨ
    .value = Jɨaɨe ráanɨ
browser-data-canary-64 =
    .label = Jɨaɨe ráanɨ
    .value = Jɨaɨe ráanɨ
browser-data-firefox-other-64 =
    .label = Jɨaɨe ráanɨ
    .value = Jɨaɨe ráanɨ
browser-data-360se-64 =
    .label = Jɨaɨe ráanɨ
    .value = Jɨaɨe ráanɨ
browser-data-firefox-128 =
    .label = Éroirafo úitɨraɨ dɨga
    .value = Éroirafo úitɨraɨ dɨga
