# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Iseqdacen ittukelsen
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Nɣel URL
    .accesskey = y
launch-site-url-cmd =
    .label = Rzu γer URL
    .accesskey = V
copy-username-cmd =
    .label = Nɣel Isem n useqdac
    .accesskey = I
edit-username-cmd =
    .label = Ẓreg isem n useqdac
    .accesskey = e
copy-password-cmd =
    .label = Nɣel awal uffir
    .accesskey = N
edit-password-cmd =
    .label = Ẓreg awal uffir
    .accesskey = r
search-filter =
    .accesskey = N
    .placeholder = Nadi
column-heading-site =
    .label = Asmel web
column-heading-username =
    .label = Isem n useqdac
column-heading-password =
    .label = Awal uffir
column-heading-time-created =
    .label = Aseqdec amezwaru
column-heading-time-last-used =
    .label = Aseqdec anneggaru
column-heading-time-password-changed =
    .label = Asnifel aneggaru
column-heading-times-used =
    .label = Amḍan n useqdec
remove =
    .label = Kkes
    .accesskey = K
import =
    .label = Kter…
    .accesskey = r
close-button =
    .label = Mdel
    .accesskey = M
show-passwords =
    .label = Sken awalen uffiren
    .accesskey = P
hide-passwords =
    .label = Ffer awalen uffiren
    .accesskey = P
logins-description-all = Isulayen i yismal-agi ttwaskelsen ɣef uselkim-ik
logins-description-filtered = Inekcumen-agi meɣrun d wid akken tettnadiḍ:
remove-all =
    .label = Kkes akk
    .accesskey = K
remove-all-shown =
    .label = Kkes akk ayen ittwasknen
    .accesskey = a
remove-all-passwords-prompt = Tebɣiḍ tukksa n wawalen uffiren i meṛṛa?
remove-all-passwords-title = Kkes akk awalen uffiren
no-master-password-prompt = Tabɣiḍ ad d-sekneḍ awalen-ik uffiren?
auto-fill-logins-and-passwords =
    .label = Ččar inekcam d wawalen uffiren s wudem awurman
