# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = Šī tīmekļa lapa tiek pārvirzīta uz citu vietu. Vai atkārtoti nosūtīt veidlapā ievadītos datus uz jauno vietu?
# Directory listing strings
DirTitle = Mapes %1$S indekss
DirGoUp = Iet vienu mapi uz augšu
ShowHidden = Rādīt slēptus objektus
DirColName = Nosaukums
DirColSize = Izmērs
DirColMTime = Pēdējoreiz mainīts
DirFileLabel = Datne:
UnsafeUriBlocked = Resursu no “%1$S” bloķēja Drošā pārlūkošana.
CookieBlockedByPermission = Pieprasījums piekļūt sīkdatnēm vai krātuvei vietnē “%1$S” tika bloķēts, ņemot vērā pielāgotas sīkfailu atļaujas.
CookieBlockedAll = Pieprasījums piekļūt sīkdatnei vai krātuvei vietnē “%1$S” tika bloķēts, jo mēs bloķējam visus krātuves piekļuves pieprasījumus.
# LOCALIZATION NOTE (CookieRejectedByPermissionManager): %1$S is the cookie response header.
CookieRejectedByPermissionManager = Sīkdatne “%1$S” tika noraidīta lietotāja iestatītu atļauju dēļ.
CookieRejectedEmptyNameAndValue = Sīkdatne ar tukšu nosaukumu un vērtību tika noraidīta.
# LOCALIZATION NOTE (CookieRejectedInvalidCharName): %1$S is the cookie name.
CookieRejectedInvalidCharName = Sīkdatne “%1$S” tika noraidīta nosaukumā esošu nederīgu rakstzīmju dēļ.
# LOCALIZATION NOTE (CookieRejectedInvalidCharAttributes): %1$S is the cookie name.
CookieRejectedInvalidCharAttributes = Sīkdatne “%1$S” tika noraidīta īpašības esošu nederīgu rakstzīmju dēļ.
# LOCALIZATION NOTE (CookieRejectedInvalidDomain): %1$S is the cookie name.
CookieRejectedInvalidDomain = Sīkdatne “%1$S” tika noraidīta nederīga domēna dēļ.
# LOCALIZATION NOTE (CookieRejectedInvalidPrefix): %1$S is the cookie name.
CookieRejectedInvalidPrefix = Sīkdatne “%1$S” tika noraidīta nederīga priedēkļa dēļ.
# LOCALIZATION NOTE (CookieRejectedInvalidPath): %1$S is the cookie name.
CookieRejectedInvalidPath = Sīkdatne “%1$S” tika noraidīta nederīga ceļa dēļ.
# LOCALIZATION NOTE (CookieRejectedInvalidCharValue): %1$S is the cookie name.
CookieRejectedInvalidCharValue = Sīkdatne “%1$S” tika noraidīta vērtībā esošu nederīgu rakstzīmju dēļ.
# LOCALIZATION NOTE (CookieRejectedAttributePathOversize): %1$S is the cookie name.
CookieRejectedAttributePathOversize = Sīkdatne “%1$S” tika noraidīta, jo tās ceļa vērtība ir pārāk gara.
# LOCALIZATION NOTE (CookieRejectedAttributeDomainOversize): %1$S is the cookie name.
CookieRejectedAttributeDomainOversize = Sīkdatne “%1$S” tika noraidīta, jo tās domēna vērtība ir pārāk gara.
# LOCALIZATION NOTE (CookieRejectedAttributeExpiryOversize): %1$S is the cookie name.
CookieRejectedAttributeExpiryOversize = Sīkdatne “%1$S” tika noraidīta, jo tās beigu datums pārsniedz ierobežojumu.
# LOCALIZATION NOTE (CookieRejectedHttpOnlyButFromScript): %1$S is the cookie name.
CookieRejectedHttpOnlyButFromScript = Sīkdatne “%1$S” tika noraidīta, jo jau pastāv tikai HTTP sīkdatne, bet skripts mēģināja pievienot jaunu.
# LOCALIZATION NOTE (CookieRejectedSecureButHttp): %1$S is the cookie name.
CookieRejectedSecureButNonHttps = Sīkdatne “%1$S” tika noraidīta, jo ne HTTPS sīkdatni nevar iestatīt kā “secure”.
# LOCALIZATION NOTE (CookieRejectedThirdParty): %1$S is the cookie response header.
CookieRejectedThirdParty = Sīkdatne “%1$S” tika noraidīta kā trešo pušu.
# LOCALIZATION NOTE (CookieRejectedNonsecureOverSecure): %1$S is the cookie name.
CookieRejectedNonsecureOverSecure = Sīkdatne “%1$S” tika noraidīta, jo jau pastāv “secure” sīkdatne.
# LOCALIZATION NOTE (CookieRejectedForNonSameSiteness): %1$S is the cookie name.
CookieRejectedForNonSameSiteness = Sīkdatne “%1$S” tika noraidīta, jo tā ir starpvietņu kontekstā un tās “SameSite” vērtība ir “Lax” vai “Strict”.
# LOCALIZATION NOTE (CookieRejectedPartitionedRequiresSecure): %1$S is the cookie name.
CookieRejectedPartitionedRequiresSecure = Sīkdatne “%1$S” tika noraidīta, jo tai ir īpašība “Partitioned”, bet nav īpašības “secure”.
# LOCALIZATION NOTE (CookieAttributeIgnored): %1$S is the cookie name. %2$S is the attribute name. %3$S is the number of bytes. "B" means bytes.
CookieAttributeIgnored = Sīkdatnes “%1$S” īpašības “%2$S” vērtība tika noraidīta, jo tā ir pārāk liela. Lielākais pieļaujamais lielums ir %3$S B.
# LOCALIZATION NOTE (CookieForeignNoPartitionedError): %1$S is the cookie name. Do not translate "Partitioned"
CookieForeignNoPartitionedError = Sīkdatne “%1$S” tika noraidīta, jo tā ir sveša un tai nav īpašības “Partitioned“.
