# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Просрочено време
openFile = Отваряне на файл
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Търсене чрез %1$S за „%2$S“
contextMenuSearch.accesskey = Т
contextMenuPrivateSearch = Търсене в поверителен прозорец
contextMenuPrivateSearch.accesskey = в
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Търсене чрез %S в поверителен прозорец
bookmarkAllTabsDefault = [Име на папка]
unsignedAddonsDisabled.message = Една или повече добавки са непроверени и бяха изключени.
unsignedAddonsDisabled.learnMore.label = Научете повече
unsignedAddonsDisabled.learnMore.accesskey = Н
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Последен достъп %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = %S:// връзки
crashedpluginsMessage.title = Приставката %S се срина.
crashedpluginsMessage.reloadButton.label = Презареждане на страницата
crashedpluginsMessage.reloadButton.accesskey = П
crashedpluginsMessage.submitButton.label = Изпращане на доклад за срив
crashedpluginsMessage.submitButton.accesskey = И
crashedpluginsMessage.learnMore = Научете повече…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Имахте предвид да посетите %S?
keywordURIFixup.goTo = Да, към %S
keywordURIFixup.goTo.accesskey = Д
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Обновяване до %S
update.downloadAndInstallButton.accesskey = О
menuOpenAllInTabs.label = Отваряне на всички в раздели
tabHistory.goBack = Назад към тази страница
tabHistory.goForward = Напред към тази страница
# URL Bar
pasteAndGo.label = Поставяне и посещаване
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Презареждане на текущата страница (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Спиране зареждането на страницата (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Нулиране на мащабирането (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Превключва изгледа за четене (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Показване на отметките (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Напредък на текущите изтегляния (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Отваряне на нов прозорец (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Отваряне на раздел (%S)
newTabContainer.tooltip = Отваряне на нов раздел (%S)\nЗа отваряне на раздел в изолатор натиснете и задръжте
canvas.block = Блокиране
canvas.block.accesskey = Б
canvas.allow2 = Разрешаване
canvas.allow2.accesskey = А
canvas.remember2 = Запомняне на това решение
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Проверено от: %S
identity.identified.verified_by_you = Добавено е изключение в защитата на тази страница.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Сертификатът е издаден на: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Незащитена
identity.notSecure.tooltip = Връзката не е защитена
identity.extension.label = Разширение (%S)
identity.extension.tooltip = Отворена от разширение: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Намаляване (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Нулиране на мащабирането (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Увеличаване (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Изрязване (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Копиране (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Поставяне (%S)
geolocation.allow = Разрешаване
geolocation.block = Блокиране
geolocation.shareWithSite4 = Разрешавате ли на %S достъп до местоположението ви?
geolocation.shareWithFile4 = Разрешавате ли на този местен файл достъп до местоположението ви?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Разрешавате ли на %1$S да даде на %2$S разрешение за достъп до местоположението ви?
geolocation.remember = Запомняне на решението
# Virtual Reality Device UI
xr.allow2 = Разрешаване
xr.block = Блокиране
xr.remember = Запомняне на това решение
# Persistent storage UI
persistentStorage.allow = Разрешаване
persistentStorage.allow.accesskey = р
persistentStorage.block.label = Блокиране
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Разрешаване
webNotifications.notNow = Не сега
webNotifications.notNow.accesskey = с
webNotifications.never = Никога
webNotifications.never.accesskey = н
webNotifications.alwaysBlock = Винаги да се блокира
webNotifications.block = Блокиране
webNotifications.receiveFromSite3 = Разрешавате ли на %S да ви изпраща известия?
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Махнете ме от тук!
safebrowsing.getMeOutOfHereButton.accessKey = М
safebrowsing.deceptiveSite = Измамническа страница!
safebrowsing.notADeceptiveSiteButton.label = Това не е измамническа страница…
safebrowsing.notADeceptiveSiteButton.accessKey = d
safebrowsing.reportedAttackSite = Докладвана атакуваща страница!
safebrowsing.notAnAttackButton.label = Това не е атакуваща страница…
safebrowsing.notAnAttackButton.accessKey = а
safebrowsing.reportedUnwantedSite = Докладвана страница с нежелан софтуер!
safebrowsing.reportedHarmfulSite = Страница, докладвана като зловредна!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Търсене в %S
troubleshootModeRestartButton = Рестартиране
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Тази страница забавя %1$S. За да ускорите браузъра, спрете тази страница.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Някоя уеб страница забавя %1$S. За да ускорите браузъра спрете тази страница.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = "%1$S" забавя %2$S. За да ускорите браузъра спрете тази страница.
processHang.add-on.learn-more.text = Научете повече
processHang.button_stop2.label = Спиране
processHang.button_stop2.accessKey = С
processHang.button_debug.label = Дебъгване на скрипт
processHang.button_debug.accessKey = Д
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Показване на прозореца на цял екран (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Преместване на лентата отляво
sidebar.moveToRight = Преместване на лентата отдясно
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Трябва да активирате DRM, за да възпроизведете аудио или видео на тази страница.
emeNotifications.drmContentDisabled.button.label = Включване на DRM
emeNotifications.drmContentDisabled.button.accesskey = В
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S инсталира компоненти, необходими за работата на аудио или видеозапис от страницата. Моля, опитайте по-късно.
emeNotifications.unknownDRMSoftware = Неизвестен
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Приспособяване на %S
decoder.noCodecs.button = Научете как
decoder.noCodecs.accesskey = Н
decoder.noCodecsLinux.message = За възпроизвеждане на видеото, е нужно да инсталирате изискваните видео кодеци.
decoder.noHWAcceleration.message = За подобряване качеството на видеото, е нужно да инсталирате Media Feature Pack на Microsoft.
decoder.noPulseAudio.message = За възпроизвеждане на аудиото, е нужно да инсталирате изискваният софтуер на PulseAudio.
decoder.unsupportedLibavcodec.message = libavcodec може да е уязвима или неподдържана и за възпроизвеждане на видео трябва да бъде обновена.
decoder.decodeError.message = Възникна грешка при разкодиране да медиен ресурс.
decoder.decodeError.button = Докладване на проблем със сайта
decoder.decodeError.accesskey = Д
decoder.decodeWarning.message = Възникна възстановима грешка при разкодиране да медиен ресурс.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Трябва да се впишете в тази мрежа, за да получите достъп до интернет.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Страница за вписване в мрежа
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Права за %S
permissions.remove.tooltip = Изчистване на тези права и повторно питане
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-битово издание
aboutDialog.architecture.thirtyTwoBit = 32-битово издание
midi.allow.label = Разрешаване
midi.remember = Запомняне на решението
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Назад
storageAccess1.DontAllow.label = Забраняване
storageAccess1.DontAllow.accesskey = З
