# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Čas vypršel
openFile = Otevřít soubor
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Vyhledat „%2$S“ pomocí %1$S
contextMenuSearch.accesskey = H
contextMenuPrivateSearch = Vyhledat v anonymním okně
contextMenuPrivateSearch.accesskey = n
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Vyhledat v anonymním okně pomocí %S
contextMenuPrivateSearchOtherEngine.accesskey = n
bookmarkAllTabsDefault = [Název složky]
unsignedAddonsDisabled.message = Jeden nebo více nainstalovaných doplňků nelze ověřit, a proto byly zakázány.
unsignedAddonsDisabled.learnMore.label = Zjistit více
unsignedAddonsDisabled.learnMore.accesskey = Z
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Poslední přístup %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = odkazy typu %S://
crashedpluginsMessage.title = Zásuvný modul %S spadl.
crashedpluginsMessage.reloadButton.label = Znovu načíst stránku
crashedpluginsMessage.reloadButton.accesskey = o
crashedpluginsMessage.submitButton.label = Odeslat hlášení o pádu
crashedpluginsMessage.submitButton.accesskey = d
crashedpluginsMessage.learnMore = Zjistit více…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Nechcete spíše přejít na %S?
keywordURIFixup.goTo = Ano, přejít na %S
keywordURIFixup.goTo.accesskey = A
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Aktualizovat na %S
update.downloadAndInstallButton.accesskey = A
menuOpenAllInTabs.label = Otevřít vše v panelech
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Znovu načíst tuto stránku
tabHistory.goBack = Přejít zpět na tuto stránku
tabHistory.goForward = Přejít vpřed na tuto stránku
# URL Bar
pasteAndGo.label = Vložit a jít
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Znovu načte aktuální stránku (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Zastaví načítání stránky (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Obnoví velikost stránky (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Přepne zobrazení čtečky (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S %%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, Obnovit velikost stránky
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Zobrazí vaše záložky (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Zobrazí průběh stahování (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Otevře nové okno (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Otevře nový panel (%S)
newTabContainer.tooltip = Otevře nový panel (%S)\nPodržením stisknutého tlačítka otevře nový kontejnerový panel
newTabAlwaysContainer.tooltip = Pro otevření nového panelu vyberte kontejner
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Chcete serveru %S povolit používat obrazová data HTML5 canvasu?
canvas.siteprompt2.warning = To může být použito k unikátní identifikaci vašeho počítače.
canvas.block = Blokovat
canvas.block.accesskey = B
canvas.allow2 = Povolit
canvas.allow2.accesskey = P
canvas.remember2 = Zapamatovat si toto rozhodnutí
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Ověřil: %S
identity.identified.verified_by_you = Tomuto serveru jste udělili bezpečnostní výjimku
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Certifikát vydán pro: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Nezabezpečeno
identity.notSecure.tooltip = Připojení není zabezpečeno
identity.extension.label = Rozšíření (%S)
identity.extension.tooltip = Načteno doplňkem: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Zmenší velikost stránky (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Obnoví velikost stránky (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Zvětší velikost stránky (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Vyjme výběr do schránky (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Zkopíruje výběr do schránky (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Vloží obsah schránky (%S)
geolocation.allow = Povolit
geolocation.allow.accesskey = P
geolocation.block = Blokovat
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Otevře se nastavení systému pro zjišťování polohy. Povolte prosím aplikaci %S přístup k údajům o poloze.
geolocation.shareWithSite4 = Chcete serveru %S povolit přístup k údajům o vaší poloze?
geolocation.shareWithFile4 = Chcete povolit tomuto místnímu souboru přistupovat k údajům o vaší poloze?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Chcete serveru %1$S povolit, aby umožnil %2$S přístup k údajům o vaší poloze?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Povolte v nastavení systému aplikaci %S přístup k údajům o poloze.
geolocation.systemSettingsTitle = Čeká se na povolení zjišťovat polohu
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Systém vás požádá o udělení tohoto oprávnění pro %S.
geolocation.remember = Zapamatovat si toto rozhodnutí
# Virtual Reality Device UI
xr.allow2 = Povolit
xr.allow2.accesskey = P
xr.block = Blokovat
xr.block.accesskey = B
xr.shareWithSite4 = Chcete serveru %S povolit přístup k vašim zařízením pro virtuální realitu? Může tím dojít k odhalení citlivých informací.
xr.shareWithFile4 = Chcete povolit tomuto místnímu souboru přistupovat k vašim zařízením pro virtuální realitu? Může tím dojít k odhalení citlivých informací.
xr.remember = Zapamatovat si toto rozhodnutí
# Persistent storage UI
persistentStorage.allow = Povolit
persistentStorage.allow.accesskey = P
persistentStorage.block.label = Blokovat
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Chcete povolit serveru %S ukládat data natrvalo?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Povolit
webNotifications.allow2.accesskey = P
webNotifications.notNow = Teď ne
webNotifications.notNow.accesskey = n
webNotifications.never = Nikdy nepovolovat
webNotifications.never.accesskey = v
webNotifications.alwaysBlock = Vždy blokovat
webNotifications.alwaysBlock.accesskey = V
webNotifications.block = Blokovat
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Chcete serveru %S povolit zasílat vám oznámení?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S chce přistupovat k ostatním aplikacím a službám na tomto zařízení.
localhost.remember2 = Pamatovat si mou volbu pro tento web
localhost.allowlabel = Povolit
localhost.blocklabel = Blokovat
localhost.allow.accesskey = P
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S žádá o přístup k aplikacím a službám na zařízeních připojených k vaší místní síti.
localNetwork.remember2 = Pamatovat si mou volbu pro tento web
localNetwork.allowLabel = Povolit
localNetwork.allow.accesskey = P
localNetwork.blockLabel = Blokovat
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Rychle odsud pryč!
safebrowsing.getMeOutOfHereButton.accessKey = R
safebrowsing.deceptiveSite = Podvodná stránka!
safebrowsing.notADeceptiveSiteButton.label = Tato stránka není podvodná…
safebrowsing.notADeceptiveSiteButton.accessKey = k
safebrowsing.reportedAttackSite = Nahlášená útočná stránka!
safebrowsing.notAnAttackButton.label = Toto není útočná stránka…
safebrowsing.notAnAttackButton.accessKey = T
safebrowsing.reportedUnwantedSite = Nahlášená stránka s nežádoucím softwarem!
safebrowsing.reportedHarmfulSite = Nahlášená škodlivá stránka!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Hledat na %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Chcete aplikaci %S restartovat do režimu řešení potíží?
troubleshootModeRestartPromptMessage = Vaše rozšíření, motivy vzhledu a uživatelská nastavení budou dočasně zakázány.
troubleshootModeRestartButton = Restartovat
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Tato webová stránka prohlížeč %1$S zpomaluje. Pro jeho zrychlení zastavte její načítání.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Webová stránka zpomaluje prohlížeč %1$S. Pro jeho zrychlení zastavte její načítání.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = Webová stránka „%1$S“ prohlížeč %2$S zpomaluje. Pro jeho zrychlení zastavte její načítání.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = Rozšíření „%1$S“ prohlížeč %2$S zpomaluje. Pro zrychlení prohlížeče rozšíření zastavte.
processHang.add-on.learn-more.text = Zjistit více
processHang.button_stop2.label = Zastavit
processHang.button_stop2.accessKey = s
processHang.button_debug.label = Ladit skript
processHang.button_debug.accessKey = d
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Zobrazí okno v režimu celé obrazovky (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Přesunout postranní lištu doleva
sidebar.moveToRight = Přesunout postranní lištu doprava
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Pro přehrání audia nebo videa na této stránce musíte nejdříve povolit DRM.
emeNotifications.drmContentDisabled.button.label = Povolit DRM
emeNotifications.drmContentDisabled.button.accesskey = P
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S instaluje součásti potřebné pro přehrání audia nebo videa na této stránce. Zkuste to prosím znovu později.
emeNotifications.unknownDRMSoftware = Neznámý
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Přizpůsobit %S
decoder.noCodecs.button = Zjistěte jak
decoder.noCodecs.accesskey = Z
decoder.noCodecsLinux.message = Pro přehrávání videa může být potřeba nainstalovat video kodeky.
decoder.noHWAcceleration.message = Pro zlepšení kvality videa může být potřeba nainstalovat Media Feature Pack od Microsoftu.
decoder.noPulseAudio.message = Pro přehrávání hudby může být potřeba nainstalovat software PulseAudio.
decoder.unsupportedLibavcodec.message = Verze knihovny libavcodec může být zranitelná nebo není podporována a pro přehrání videa je potřeba její aktualizace.
decoder.decodeError.message = Při dekódování zdroje médií nastala chyba.
decoder.decodeError.button = Nahlásit problém se zobrazením stránky
decoder.decodeError.accesskey = r
decoder.decodeWarning.message = Při dekódování zdroje médií nastala chyba, kterou lze opravit.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Pro přístup na internet se musíte do této sítě nejprve přihlásit.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Otevřít přihlašovací stránku k síti
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Oprávnění serveru %S
permissions.remove.tooltip = Zapomenout mé nastavení tohoto oprávnění a příště se zeptat znovu
permissions.fullscreen.promptCanceled = Čekající požadavek na nová oprávnění byl zrušen: nová oprávnění by neměla být požadována před spuštěním režimu celé obrazovky.
permissions.fullscreen.fullScreenCanceled = Režim celé obrazovky ukončen: nová oprávnění by neměla být požadována v režimu celé obrazovky.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64 bitů
aboutDialog.architecture.thirtyTwoBit = 32 bitů
midi.allow.label = Povolit
midi.allow.accesskey = P
midi.block.label = Blokovat
midi.block.accesskey = B
midi.remember = Zapamatovat si toto rozhodnutí
midi.shareWithFile = Chcete povolit tomuto místnímu souboru přistupovat k vašim MIDI zařízením?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Chcete %S přístup k vašim kontaktům?
midi.shareSysexWithFile = Chcete povolit tomuto místnímu souboru přistupovat k vašim MIDI zařízením a posílat nebo přijímat SysEx zprávy?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Chcete serveru %S povolit přístup k vašim MIDI zařízením a posílat nebo přijímat SysEx zprávy?
serial.allow.label = Povolit
serial.allow.accesskey = P
serial.block.label = Blokovat
serial.block.accesskey = B
serial.shareWithFile = Povolit tomuto místnímu souboru přístup k sériovým portům?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Chcete serveru %S povolit přístup k sériovým portům?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Zpět
storageAccess1.Allow.label = Povolit
storageAccess1.Allow.accesskey = P
storageAccess1.DontAllow.label = Blokovat
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Povolit serveru %1$S používat své cookies také na serveru %2$S?
storageAccess1.hintText = Pokud není jasné, proč server %1$S tato data potřebuje, nejspíše můžete jeho požadavek zablokovat.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Vyhledat „%S“ na webu
