# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Gànahuij diu
openFile = Na'nïn' chrû ñanj
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Nana'ui' %1$S riña “%2$S”
contextMenuSearch.accesskey = S
contextMenuPrivateSearch = Nana’uì’ riña ‘ngō Bentanâ Huìi
contextMenuPrivateSearch.accesskey = h
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Nana’uì’ ngà %S riña ‘ngō Bentanâ Huìi
contextMenuPrivateSearchOtherEngine.accesskey = h
bookmarkAllTabsDefault = [Si yuguì carpeta]
unsignedAddonsDisabled.message = 'Ngo hùij nej sa nutâ't ni nu ga'ue natsij aga' na ma yi'í dan nu nahuin nakà ma.
unsignedAddonsDisabled.learnMore.label = Gahuin chrūn doj
unsignedAddonsDisabled.learnMore.accesskey = L
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Amān gatûj rukù nï't %S
crashedpluginsMessage.title = Gire' plugin %S nitaj si 'iaj sun ma.
crashedpluginsMessage.reloadButton.label = Na'nī ñu' pajinâ
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = Ganato' nuinsaj gire' ma
crashedpluginsMessage.submitButton.accesskey = S
crashedpluginsMessage.learnMore = Gahuin chrūn doj…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Si ruaj ni si ga'anjt rua ra' %S?
keywordURIFixup.goTo = Ganikaj ñunj ân %S
keywordURIFixup.goTo.accesskey = Y
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Nagui'iaj nako' %S
update.downloadAndInstallButton.accesskey = U
menuOpenAllInTabs.label = Na'nïn' dara'anj 'ngà rakïj ñanj
tabHistory.goBack = Nanikaj ñun' riña pajinâ na
tabHistory.goForward = Gutu' ne'ñàan pajinâ na
# URL Bar
pasteAndGo.label = Gachrun & guij
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Nagi'iaj ñunj pajinâ na (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Dunikïn' a'kun' pajinâ na (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Nagi'iaj ñu' daj gà yachij ma (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Naduno' daj gahio' (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Dgun' nej markador (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Ni'io' daj nikò 'ngà huaj sa naduni' (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Na'nïn' ventana nakàa (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Na'nïn' rakïj ñanj nakàa (%S)
newTabContainer.tooltip = Na'nïn 'ngō rakïj ñanj nakàa (%S)\nGinù nâ ra'a da' ga'ue na'nïnt 'ngō rakïj ñanj nakà kontenedor
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Ngà ganatsij sa gu'nàj: %S
identity.identified.verified_by_you = Duguatûjt 'ngo sa dugumî sò' riña sitio na.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Sertifikadô giri sa gu’nàj: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Nitaj si yitïnj hua ma
identity.notSecure.tooltip = Nitāj si yitïnj huā coneksion nan
identity.extension.label = Nej extensiûn (%S)
identity.extension.tooltip = Nachra extension: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Nagi'iaj li' doj (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Nagi'iaj ñu' daj gà yachij ma (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Nagi'iaj li' doj (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Ga'ne' (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Gido'o' ma (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Gachrun' (%S)
geolocation.remember = Nanu ruhuât sa ganï ruhuât
# Persistent storage UI
persistentStorage.allow = Ga'nïn
persistentStorage.allow.accesskey = A
webNotifications.notNow = Si ga'ue akuan'ni
webNotifications.notNow.accesskey = n
webNotifications.never = Nitaj dama ga'nï'
webNotifications.never.accesskey = v
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = ¡Gahui' ñunan!
safebrowsing.getMeOutOfHereButton.accessKey = G
safebrowsing.deceptiveSite = ¡Sitio diga'ñun'unj!
safebrowsing.notADeceptiveSiteButton.label = Se sitio diga'ñu'unj huin ma maj...
safebrowsing.notADeceptiveSiteButton.accessKey = D
safebrowsing.reportedAttackSite = ¡'Ngo sitiô yi'ìi huin na!
safebrowsing.notAnAttackButton.label = Sē sitio ata yi'ì huin ma...
safebrowsing.notAnAttackButton.accessKey = A
safebrowsing.reportedUnwantedSite = ¡Nikaj sitiô na sa yi'ìi a!
safebrowsing.reportedHarmfulSite = ¡'Ngà ga'anj nuguan' si sitio yi'ì huin ma!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Nanà'uì %S
processHang.add-on.learn-more.text = Gahuin chrūn doj
processHang.button_debug.label = Nagi'iaj niñun Skript
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Ni'io' da'ua ngè riña pantayâ (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Dusikï'ga'anj dukuán na ne' chrin'
sidebar.moveToRight = Dusikï'ga'anj dukuán na ne' huo'
emeNotifications.drmContentDisabled.button.label = Ngà 'iaj sunj DRM
emeNotifications.drmContentDisabled.button.accesskey = E
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S hìaj dugutujt nej sa gi'iaj da' gachrā ma chra'aj nej si videô riña pajinâ na. Gi'iaj suntuj u nī garahue ñunt.
emeNotifications.unknownDRMSoftware = Sê sa ni'în' huin
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Nagi'iô' daj huin ruhuô' %S
decoder.noCodecs.button = Gahuin chrūn daj
decoder.noCodecs.accesskey = L
decoder.noCodecsLinux.message = Dā duguchrát videô nī da'uit dugutujt kodeks sa nachin' videô na.
decoder.noHWAcceleration.message = Dā' gurui' hue'ê videô, nī da'ui' ga'nïnjt Media Feature Pack si'iaj Microsoft riña si aga't.
decoder.noPulseAudio.message = Dā' duguchrát chra'aj, nī da'uit dugutujt Software gu'naj PulseAudio.
decoder.unsupportedLibavcodec.message = libavcodec na'ue gi'iaj sun nī da'ui nahuin nakà ma da' gi'iaj sun videô.
decoder.decodeError.message = Hua 'ngò sa gire' 'ngà nachrunt multimedia.
decoder.decodeError.button = Natà’ sa ‘iaj sun a’nan’ riña sitiô na
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = Hua 'ngò sa gire' 'ngà nachrunt multimedia sanī huaj nahuin ma.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Da'uit gayi'ìt sesiôn asij gachrin gatut riña internet.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Nanïn' pajinâ riña Ayi'i' sesiôn riña red
permissions.remove.tooltip = Nayi'ì ñun' nī gachí nu'un'
permissions.fullscreen.promptCanceled = Giyichin’ nej sa achín nì’iát: si ga’ue gachìnj nì’iát asìj gàchin gatūt riña si DOM riña nahuin gachrà’ riña aga’a.
permissions.fullscreen.fullScreenCanceled = Gahuit riña nahuin gachrà’ riña aga’a DOM: nitāj si da’uît gàchinj nì’iát sisī nunt riña DOM gachrà’ riña aga’a.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bit
aboutDialog.architecture.thirtyTwoBit = 32-bit
midi.remember = Nanu ruhuât sa ganï ruhuât
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Ne' rukuu
