# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Ymportearassistint
import-from =
    { PLATFORM() ->
        [windows] Opsjes, blêdwizers, skiednis, wachtwurden en oare gegevens ymportearje út:
       *[other] Foarkarren, blêdwizers, skiednis, wachtwurden en oare gegevens ymportearje út:
    }
import-from-bookmarks = Blêdwizers ymportearje út:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-nothing =
    .label = Neat ymportearje
    .accesskey = t
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = x
import-from-360se =
    .label = 360 Secure Browser
    .accesskey = 3
no-migration-sources = Der binne gjin programma’s fûn dy't blêdwizers, skiednis of wachtwurden befetsje.
import-source =
    .label = Ynstellingen en gegevens ymportearje út:
import-items-title =
    .label = Te ymportearjen ûnderdielen
import-items-description = Selektearje de te ymportearjen ûnderdielen:
import-migrating-title =
    .label = Ymportearje…
import-migrating-description = De folgjende ûnderdielen wurde op dit stuit ymportearre…
import-select-profile-title =
    .label = Profyl selektearje
import-select-profile-description = De folgjende profilen binne beskikber om út te ymportearjen:
import-done-title =
    .label = Ymportearjen dien
import-close-source-browser = Soargje derfoar dat de selektearre browser sluten is eardat jo trochgean.
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = Ut { $source }
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Secure Browser
imported-safari-reading-list = Lêslist (út Safari)
imported-edge-reading-list = Lêslist (út Edge)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Ynternetopsjes
    .value = Ynternetopsjes
browser-data-edge-1 =
    .label = Ynstellingen
    .value = Ynstellingen
browser-data-safari-1 =
    .label = Foarkarren
    .value = Foarkarren
browser-data-chrome-1 =
    .label = Foarkarren
    .value = Foarkarren
browser-data-canary-1 =
    .label = Foarkarren
    .value = Foarkarren
browser-data-360se-1 =
    .label = Foarkarren
    .value = Foarkarren
browser-data-ie-2 =
    .label = Cookies
    .value = Cookies
browser-data-edge-2 =
    .label = Cookies
    .value = Cookies
browser-data-safari-2 =
    .label = Cookies
    .value = Cookies
browser-data-chrome-2 =
    .label = Cookies
    .value = Cookies
browser-data-canary-2 =
    .label = Cookies
    .value = Cookies
browser-data-firefox-2 =
    .label = Cookies
    .value = Cookies
browser-data-360se-2 =
    .label = Cookies
    .value = Cookies
browser-data-ie-4 =
    .label = Skiednis
    .value = Skiednis
browser-data-edge-4 =
    .label = Skiednis
    .value = Skiednis
browser-data-safari-4 =
    .label = Skiednis
    .value = Skiednis
browser-data-chrome-4 =
    .label = Skiednis
    .value = Skiednis
browser-data-canary-4 =
    .label = Skiednis
    .value = Skiednis
browser-data-firefox-history-and-bookmarks-4 =
    .label = Skiednis en blêdwizers
    .value = Skiednis en blêdwizers
browser-data-360se-4 =
    .label = Skiednis
    .value = Skiednis
browser-data-ie-8 =
    .label = Bewarre formulierskiednis
    .value = Bewarre formulierskiednis
browser-data-edge-8 =
    .label = Bewarre formulierskiednis
    .value = Bewarre formulierskiednis
browser-data-safari-8 =
    .label = Bewarre formulierskiednis
    .value = Bewarre formulierskiednis
browser-data-chrome-8 =
    .label = Bewarre formulierskiednis
    .value = Bewarre formulierskiednis
browser-data-canary-8 =
    .label = Bewarre formulierskiednis
    .value = Bewarre formulierskiednis
browser-data-firefox-8 =
    .label = Bewarre formulierskiednis
    .value = Bewarre formulierskiednis
browser-data-360se-8 =
    .label = Bewarre formulierskiednis
    .value = Bewarre formulierskiednis
browser-data-ie-16 =
    .label = Bewarre wachtwurden
    .value = Bewarre wachtwurden
browser-data-edge-16 =
    .label = Bewarre wachtwurden
    .value = Bewarre wachtwurden
browser-data-safari-16 =
    .label = Bewarre wachtwurden
    .value = Bewarre wachtwurden
browser-data-chrome-16 =
    .label = Bewarre wachtwurden
    .value = Bewarre wachtwurden
browser-data-canary-16 =
    .label = Bewarre wachtwurden
    .value = Bewarre wachtwurden
browser-data-firefox-16 =
    .label = Bewarre wachtwurden
    .value = Bewarre wachtwurden
browser-data-360se-16 =
    .label = Bewarre wachtwurden
    .value = Bewarre wachtwurden
browser-data-ie-32 =
    .label = Favorieten
    .value = Favorieten
browser-data-edge-32 =
    .label = Favorieten
    .value = Favorieten
browser-data-safari-32 =
    .label = Blêdwizers
    .value = Blêdwizers
browser-data-chrome-32 =
    .label = Blêdwizers
    .value = Blêdwizers
browser-data-canary-32 =
    .label = Blêdwizers
    .value = Blêdwizers
browser-data-360se-32 =
    .label = Blêdwizers
    .value = Blêdwizers
browser-data-ie-64 =
    .label = Oare gegevens
    .value = Oare gegevens
browser-data-edge-64 =
    .label = Oare gegevens
    .value = Oare gegevens
browser-data-safari-64 =
    .label = Oare gegevens
    .value = Oare gegevens
browser-data-chrome-64 =
    .label = Oare gegevens
    .value = Oare gegevens
browser-data-canary-64 =
    .label = Oare gegevens
    .value = Oare gegevens
browser-data-firefox-other-64 =
    .label = Oare gegevens
    .value = Oare gegevens
browser-data-360se-64 =
    .label = Oare gegevens
    .value = Oare gegevens
browser-data-firefox-128 =
    .label = Finsters en ljepblêden
    .value = Finsters en ljepblêden
