# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

ssl-error-export-only-server = Befeilige kommunikaasje net mooglik.  Peer stipet gjin hege graad fan fersifering.
ssl-error-us-only-server = Befeilige kommunikaasje net mooglik.  Peer fereasket hege graad fan fersifering, hokker net stipe wurd.
ssl-error-no-cypher-overlap = Kin net befeiligd kommunisearje mei peer: gjin algemien(e) fersiferingsalgoritme(n).
ssl-error-bad-certificate = Kin net befeiligd kommunisearje mei peer: peers sertifikaat wurde ferworpen.
ssl-error-unsupported-certificate-type = Net-stipe sertifikaattype.
ssl-error-wrong-certificate = Clientautentikaasje mislearre: priveekaai yn kaaidatabase komt net oerien mei iepenbare kaai yn sertifikaatdatabase.
ssl-error-bad-mac-alert = SSL-peer rapporteart ferkearde berjochtautentikaasjekoade.
ssl-error-bad-cert-alert = SSL-peer kin jo sertifikaat net ferifiearje.
ssl-error-revoked-cert-alert = SSL-peer fersmiet jo sertifikaat as ynlutsen.
ssl-error-tx-record-too-long = SSL probearre in record te ferstjoeren dat oer de maksimaal tastiene lingte hinne gie.
ssl-error-close-notify-alert = SSL-peer hat dizze ferbining sluten.
ssl-error-server-key-exchange-failure = Net spesifisearre flater tiidens ferwurkjen fan SSL Server Key Exchange-handshake.
ssl-error-client-key-exchange-failure = Net spesifisearre flater tiidens ferwurkjen fan SSL Client Key Exchange-handshake.
ssl-error-md5-digest-failure = MD5-kontrolefunksje mislearre.
ssl-error-sha-digest-failure = SHA-1-kontrolefunksje mislearre.
ssl-error-mac-computation-failure = MAC-berekkening mislearre.
ssl-error-sym-key-context-failure = Flater by meitsjen fan Symmetric Key-kontekst.
ssl-error-iv-param-failure = Oersetten fan in IV nei in parameter troch PKCS11-koade net slagge.
ssl-error-session-key-gen-failure = Generearjen fan sesjekaaien foar SSL-sesje troch client net slagge.
ssl-error-token-insertion-removal = PKCS#11-token wurde ynfoege of fuortsmiten tiidens foartgong fan bewurking.
ssl-error-no-compression-overlap = Kin net befeiligd kommunisearje mei peer: gjin mienskiplik(e) kompresje-algoritme(n).
ssl-error-protocol-version-alert = Peer rapporteart net-kompatibele of net-stipe protokolferzje.
ssl-error-internal-error-alert = Peer rapporteart in ynterne flater.
ssl-error-unrecognized-name-alert = SSL-peer hat gjin sertifikaat foar de opfrege DNS-namme.
ssl-error-bad-cert-status-response-alert = SSL-peer koe gjin OCSP-antwurd foar syn sertifikaat krije.
ssl-error-bad-cert-hash-value-alert = SSL-peer rapporteart ferkearde wearde foar sertifikaathash.
sec-error-io = Der is in I/O-flater bard tiidens befeiligingsautorisaasje.
sec-error-invalid-time = Ferkeard opstelde tiidstring.
sec-error-revoked-certificate = Sertifikaat fan peer is ynlutsen.
sec-error-unknown-issuer = Utjouwer fan sertifikaat fan peer wurdt net werkend.
sec-error-bad-password = It ynfierde befeiligingswachtwurd is net goed.
sec-error-duplicate-cert = Sertifikaat bestiat al yn jo database.
sec-error-adding-cert = Flater by it tafoegjen fan sertifikaat oan database.
sec-error-cert-valid = Dit sertifikaat is jildich.
sec-error-cert-not-valid = Dit sertifikaat is net jildich.
sec-internal-only = **UTSLUTEND ynterne module**
sec-error-invalid-key = De kaai stipet de frege bewurking net.
sec-error-old-crl = Nije CRL is net resinter as de aktuele.
xp-sec-fortezza-none-selected = Gjin Fortezza-kaart selektearre
xp-sec-fortezza-person-error = Koe Fortezza-persoanen net inisjalisearje.
sec-error-no-token = De befeiligingskaart of -token bestiet net, moat inisjalisearre wurde, of is fuortsmiten.
sec-error-no-slot-selected = Gjin leech plak of token selektearre.
sec-error-cert-nickname-collision = In sertifikaat mei deselde alias bestiet al.
sec-error-key-nickname-collision = In kaai mei deselde alias bestiet al.
sec-error-safe-not-created = flater tiidens it meitsjen fan feilich objekt
sec-error-baggage-not-created = flater tiidens it meitesjen fan bagage objekt
xp-java-remove-principal-error = Koe de haadpersoan net fuortsmite
xp-java-delete-privilege-error = Koe it privilege net fuortsmite
xp-java-cert-not-exists-error = Dit haadpersoan hat gjin sertifikaat
sec-error-bad-export-algorithm = Fereaske algoritme is net tastien.
sec-error-exporting-certificates = Flater by poging ta eksportearjen fan sertifikaten.
sec-error-importing-certificates = Flater by poging ta ymportearjen fan sertifikaten.
sec-error-pkcs12-unsupported-mac-algorithm = Kin net ymportearje.  MAC-algoritme net stipe.
sec-error-pkcs12-unsupported-transport-mode = Kin net ymportearje.  Allinnich wachtwurdyntegriteits- en privacymodi wurde stipe.
sec-error-pkcs12-unsupported-pbe-algorithm = Kin net ymportearje.  Fersiferingsalgoritme net stipe.
sec-error-pkcs12-privacy-password-incorrect = Kin net ymportearje.  Ferkeard privacywachtwurd.
sec-error-pkcs12-cert-collision = Kin net ymportearje.  Deselde alias bestiet al yn database.
sec-error-pkcs12-duplicate-data = Net ymportearre, al yn database.
sec-error-message-send-aborted = Berjocht net ferstjoerd.
sec-error-inadequate-cert-type = Sertifikaattype net goedkard foar tapassing.
sec-error-pkcs12-unable-to-import-key = Kin net ymportearje.  Flater by poging ta ymportearjen fan priveekaai.
sec-error-pkcs12-importing-cert-chain = Kin net ymportearje.  Flater by poging ta ymportearjen fan sertifikaatketen.
sec-error-pkcs12-unable-to-locate-object-by-name = Kin net eksportearje.  Kin sertifikaat of kaai net fine op alias.
sec-error-pkcs12-key-database-not-initialized = Kin net eksportearje.  Kaaidatabase skansearre of fuortsmiten.
sec-error-keygen-fail = Kin gjin iepenbier-priveekaaipear generearje.
sec-error-not-fortezza-issuer = FORTEZZA-keten fan peer hat in net-FORTEZZA-sertifikaat.
sec-error-js-invalid-module-name = Unjildige modulenamme.
sec-error-js-add-mod-failure = Kin module net tafoegje
sec-error-js-del-mod-failure = Kin module net fuortsmite
sec-error-old-krl = Nije KRL is net resinter as de aktuele.
sec-error-krl-not-yet-valid = De kaaiwerroppingslist foar dit sertifikaat is noch net jildich.
sec-error-crl-not-yet-valid = De sertifikaatwerroppingslist foar dit sertifikaat is noch net jildich.
sec-error-unsupported-message-type = It CMS- of PKCS #7-berjochttype wurdt net stipe.
sec-error-unsupported-elliptic-curve = Net-stipe elliptyske kromme.
sec-error-unsupported-ec-point-form = Net-stipe foarm fan punt op elliptyske kromme.
sec-error-unrecognized-oid = Net-herkende objektydentifikator.
sec-error-unknown-object-type = Unbekend objekttype spesifisearre.
sec-error-incompatible-pkcs11 = PKCS #11-stjoerprogramma schendt de spesifikaasje op in ynkompatibele manier.
sec-error-no-event = Gjin nij slotbarren beskikber op dit stuit.
sec-error-crl-already-exists = CRL bestiet al.
sec-error-not-initialized = NSS is net inisjalisearre.
sec-error-token-not-logged-in = De bewurking is mislearre, omdat de PKCS#11-token net oanmeld is.
sec-error-ocsp-responder-cert-invalid = Konfigurearre OCSP responder's sertifikaat is ynfalide.
sec-error-invalid-policy-mapping = Policy mapping befettet anypolicy
sec-error-policy-validation-failed = Sertifikaatketen foldocht net oan policy-falidaasje
sec-error-failed-to-encode-data = Kodearjen fan gegevens mei ASN1-encoder mislearre
sec-error-libpkix-internal = Ynterne flater fan Libpkix bard wylst sertifikaatfalidaasje.
sec-error-crl-import-failed = Flater by poging CRL te ymportearjen.
