# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = এই ওয়েবপেজকে অন্য একটি ঠিকানায় পাঠানো হচ্ছে। নতুন ঠিকানার ফর্মে যে তথ্য পূরণ করা হয়েছে তা কি আপনি আবার পাঠাতে ইচ্ছুক?
# Directory listing strings
DirTitle = %1$S এর সূচী
DirGoUp = উচ্চ স্তরের ডিরেক্টরি পর্যন্ত
ShowHidden = লুকানো অবজেক্ট প্রদর্শন করুন
DirColName = নাম
DirColSize = আকার
DirColMTime = সর্বশেষ পরিবর্তিত
DirFileLabel = ফাইল:\u0020
UnsafeUriBlocked = “%1$S” এর রিসোর্স সমূহ নিরাপদ ব্রাউজিং দ্বারা প্রতিরোধ করা হয়েছে।
CookieBlockedByPermission = কুকি অ্যাক্সেস করার জন্য আথবা “%1$S” তে কুকি স্টোরেজ করার জন্য অ্যাক্সেসের অনুরোধটিকে ব্লক করা হয়েছিল।
CookieBlockedAll = কুকি আথবা “%1$S” -এ স্টোরেজ অ্যাক্সেসের অনুরোধটি ব্লক করা হয়েছিল কারণ আমরা সকল স্টোরেজ অ্যাক্সেসের অনুরোধ ব্লক করেছি।
