# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-connected = Կապակցված է { $host }-ի հետ…
network-connection-status-sending-request = { $host } -ին Ուղարկվում է հարցում...
network-connection-status-transferring-data = Տվյալների փոխանցում { $host } -ից…
network-connection-status-connecting = Կապակցում { $host }-ին…
network-connection-status-read = Կարդացվել է { $host }
network-connection-status-wrote = Գրվել է { $host }
network-connection-status-waiting = Սպասում է { $host }-ի պատասխանին…
network-connection-status-looked-up = Գտնվել է՝ { $host }-ը…
network-connection-status-tls-handshake = TLS ձեռքսեղման կատարում { $host }-ի հետ…
network-connection-status-tls-handshake-finished = TLS ձեռքսեղմումը ավարտվել է { $host }-ի հետ…
