# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = සුරැකි පිවිසුම්
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
launch-site-url-cmd =
    .label = URL පිවිසෙන්න
    .accesskey = V
copy-username-cmd =
    .label = පරිශීලක නම පිටපත්
    .accesskey = U
edit-username-cmd =
    .label = පරිශීලක නම සකසන්න
    .accesskey = d
copy-password-cmd =
    .label = රහස්පදය පිටපත් කරන්න
    .accesskey = C
edit-password-cmd =
    .label = මුරපදය සකසන්න
    .accesskey = E
search-filter =
    .accesskey = S
    .placeholder = සොයන්න
column-heading-site =
    .label = අඩවිය
column-heading-username =
    .label = පරිශීලක නම
column-heading-password =
    .label = රහස්පදය
column-heading-time-created =
    .label = මුල් භාවිතය
column-heading-time-last-used =
    .label = අවසන් භාවිතය
column-heading-time-password-changed =
    .label = අවසන් වෙනස්කම
column-heading-times-used =
    .label = භාවිත කළ කාල
remove =
    .label = ඉවත් කරන්න
    .accesskey = R
import =
    .label = ආයාත කිරීම…
    .accesskey = I
close-button =
    .label = වසන්න
    .accesskey = C
show-passwords =
    .label = මුරපද පෙන්වන්න
    .accesskey = P
hide-passwords =
    .label = මුරපද සඟවන්න
    .accesskey = P
logins-description-filtered = පහත පිවිසුම් ඔබේ සෙවුම හා ගැළපේ:
remove-all =
    .label = සියල්ල ඉවත් කරන්න
    .accesskey = A
remove-all-passwords-prompt = ඔබට විශ්වාසද, ඔබගේ රහස්පද සියල්ල ඉවත් කිරීම කරන්නඅවශ්‍යද?
remove-all-passwords-title = සියලු රහස්පද ඉවත් කරන්න
no-master-password-prompt = ඔබට ඔබේ මුරපද දර්ශණයට අවශ්‍ය බව විශ්වාසද?
