# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Voi vālotīs uzaticeitīs "%S" itim mierkim?
unnamedCA = Sertifikatu autoritate (nanūsaukta)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Lyudzu īvodit paroli, kas tyka izmontuota sertifikata rezerves puorspīdumi šifriešonā:
# Page Info
pageInfo_NoEncryption = Savīnuojums nav šifreits
pageInfo_Privacy_None1 = Šķārsteikla vītne %S naatbolsta pošreiz attaiseituos lopys šifriešonu.
pageInfo_Privacy_None2 = Caur Šķārsteiklu bez šifriešonys nūsyuteitū informaceju tuos ceļuošonys laikā var izlaseit cyti cylvāki.
pageInfo_Privacy_None4 = The page you are viewing was not encrypted before being transmitted over the Internet.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Šifreits savīnuojums (%1$S, %2$S bitu atslāgi, %3$S)
pageInfo_BrokenEncryption = Šifreits savīnuojums (%1$S, %2$S bitu atslāgi, %3$S)
pageInfo_Privacy_Encrypted1 = The page you are viewing was encrypted before being transmitted over the Internet.
pageInfo_Privacy_Encrypted2 = Encryption makes it difficult for unauthorized people to view information traveling between computers. It is therefore unlikely that anyone read this page as it traveled across the network.
pageInfo_MixedContent = Savīnuojums daleji šifreits
pageInfo_MixedContent2 = Ituos sātys lopys daļis nav šifreitys pyrms nūsyuteišonys pa šķārsteiklu.
pageInfo_WeakCipher = Jiusu savīnuojums ar itū lopu izmontoj vuoju šifriešonu i nav privats. Cyti cylvāki var apsavērt jiusu informaceju voi modificeit lopys uzvedeibu.
pageInfo_CertificateTransparency_Compliant = This website complies with the Certificate Transparency policy.
# Token Manager
password_not_set = (nav īstateits)
