# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Saqlangan taxalluslar
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-username-cmd =
    .label = Foydalanuvchi nomidan nusxa olish
    .accesskey = F
edit-username-cmd =
    .label = Foydalanuvchi nomini tahrirlash
    .accesskey = t
copy-password-cmd =
    .label = Parollardan nusxa olish
    .accesskey = n
edit-password-cmd =
    .label = Parolni tahrirlash
    .accesskey = t
column-heading-site =
    .label = Sayt
column-heading-username =
    .label = Foydalanuvchi
column-heading-password =
    .label = Parol
column-heading-time-created =
    .label = Birinchi foydalanilgan
column-heading-time-last-used =
    .label = So‘ngi foydalanilgan
column-heading-time-password-changed =
    .label = So‘nggi o‘zgartirish
column-heading-times-used =
    .label = Foydalanilgan vaqtlari
remove =
    .label = Oʻchirish
    .accesskey = O
import =
    .label = Import qilish…
    .accesskey = I
close-button =
    .label = Yopish
    .accesskey = Y
show-passwords =
    .label = Parollarni koʻrsatish
    .accesskey = P
hide-passwords =
    .label = Parollarni yaxshirish
    .accesskey = P
logins-description-filtered = Qidiruv bo‘yicha quyidagi taxalluslar topildi:
remove-all-passwords-prompt = Barcha parollarni oʻchirishni xohlaysizmi?
remove-all-passwords-title = Barcha parollarni oʻchirish
no-master-password-prompt = Parollaringizni koʻrsatilishini xohlaysizmi?
