#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title ចំណាំ
#define bookmarks_heading ចំណាំ

#define bookmarks_toolbarfolder ថត​របារ​ឧបករណ៍​ចំណាំ
#define bookmarks_toolbarfolder_description បន្ថែម​ចំណាំ​ទៅកាន់​ថត​នេះ ដើម្បី​ឲ្យ​ឃើញ​ពួកវា​បង្ហាញ​នៅ​លើ​របារ​ឧបករណ៍​ចំណាំ

# LOCALIZATION NOTE (getting_started):
# link title for http://en-US.www.mozilla.com/en-US/firefox/central/
#define getting_started ចាប់ផ្ដើម

# LOCALIZATION NOTE (firefox_heading):
# Firefox links folder name
#define firefox_heading Mozilla Firefox

# LOCALIZATION NOTE (firefox_help):
# link title for http://en-US.www.mozilla.com/en-US/firefox/help/
#define firefox_help ជំនួយ និង​ការ​បង្ហាត់បង្រៀន

# LOCALIZATION NOTE (firefox_customize):
# link title for http://en-US.www.mozilla.com/en-US/firefox/customize/
#define firefox_customize ប្ដូរ Firefox តាម​បំណង

# LOCALIZATION NOTE (firefox_community):
# link title for http://en-US.www.mozilla.com/en-US/firefox/community/
#define firefox_community ចូលរួម

# LOCALIZATION NOTE (firefox_about):
# link title for http://en-US.www.mozilla.com/en-US/about/
#define firefox_about អំពី​យើង

#unfilter emptyLines
