# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Bu məqsədlər üçün "%S" təsdiq sənədinə etibar etmək istəyirsiniz?
unnamedCA = Təsdiq sənədi rəsmisi (adsız)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Lütfən bu sertifikatın yedəyini şifrələmək üçün istifadə ediləcək parolu daxil edin:
# Page Info
pageInfo_NoEncryption = Bağlantı Şifrələnməyib
pageInfo_Privacy_None1 = Bu %S saytı baxdığınız səhifə üçün şifrələməni dəstəkləmir.
pageInfo_Privacy_None2 = İnternetdə şifrələnmədən göndərilən məlumatlar başqaları tərəfindən görünə bilər.\u0020
pageInfo_Privacy_None4 = Gördüyünüz səhifə internet üzərindən sizə ötürülməzdən əvvəl şifrələnməyib.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Bağlantı Şifrələnib (%1$S, %2$S bit açarlar, %3$S)
pageInfo_BrokenEncryption = Sınmış Şifrələmə (%1$S, %2$S bit açarlar, %3$S)
pageInfo_Privacy_Encrypted1 = Bu səhifə sizə çatmamış şifrələndi.
pageInfo_Privacy_Encrypted2 = Şifrələmə, kompüterlər arasındakı məlumat ötürülməsinin üçüncü şəxslər tərəfindən görülməsinin qarşısını alır. Buna görə də açdığınız səhifənin başqalarına görünmə ehtimalı çox azdır.
pageInfo_MixedContent = Bağlantını vəziyyətə görə şifrəli quraşdır
pageInfo_MixedContent2 = Internetdən bağlantıya keçmədən əvvəl istədiyiniz səhifələr şifrəli olmaya bilər.
pageInfo_WeakCipher = Bu web saytı ilə bağlantınız zəif şifrələmə istifadə edir və məxfi deyil. Başqaları məlumatlarınızı görə və ya web saytın davranışını dəyişə bilərlər.
pageInfo_CertificateTransparency_Compliant = Bu sayt Sertifikat Şəffaflığı siyasətinə uyğundur.
# Token Manager
password_not_set = (heç nə seçilməyib)
