# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Cas pśekšocony
openFile = Dataju wócyniś
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Z %1$S "%2$S" pytaś
contextMenuSearch.accesskey = t
contextMenuPrivateSearch = W priwatnem woknje pytaś
contextMenuPrivateSearch.accesskey = i
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Z %S w priwatnem woknje pytaś
contextMenuPrivateSearchOtherEngine.accesskey = i
bookmarkAllTabsDefault = [Mě zarědnika]
unsignedAddonsDisabled.message = Jaden dodank abo někotare dodanki njejsu wobkšuśone a su se znjemóžnili.
unsignedAddonsDisabled.learnMore.label = Dalšne informacije
unsignedAddonsDisabled.learnMore.accesskey = D
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Slědny pśistup %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = Wótkaze %S://
crashedpluginsMessage.title = Tykac %S jo se wowalił.
crashedpluginsMessage.reloadButton.label = Bok znowego zacytaś
crashedpluginsMessage.reloadButton.accesskey = B
crashedpluginsMessage.submitButton.label = Wowaleńsku rozpšawu pósłaś
crashedpluginsMessage.submitButton.accesskey = r
crashedpluginsMessage.learnMore = Dalšne informacije…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Sćo kśěł k %S hyś?
keywordURIFixup.goTo = Jo, cu k %S
keywordURIFixup.goTo.accesskey = J
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Na %S aktualizěrowaś
update.downloadAndInstallButton.accesskey = a
menuOpenAllInTabs.label = Wšykne w rejtarikach wócyniś
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Toś ten bok znowego zacytaś
tabHistory.goBack = K toś tomu bokoju se wrośiś
tabHistory.goForward = K toś tomu bokoju doprědka hyś
# URL Bar
pasteAndGo.label = Zasajźiś a zachopiś
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Aktualny bok (%S) znowego zacytaś
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Cytanje toś togo boka (%S) zastajiś
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Skalěrowański schójźeńk (%S) slědk stajiś
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Cytánski naglěd pśešaltowaś (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, skalěrowańska rownina slědk stajiś
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Waše cytańske znamjenja (%S) pokazaś
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Póstup běžnych ześěgnjenjow (%S) zwobrazniś
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Nowe wokno wócyniś (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Nowy rejtarik (%S) wócyniś
newTabContainer.tooltip = Wócyńśo nowy rejtarik (%S)\nTłocćo a źaržćo, aby nowy kontejnerowy rejtarik wócynił
newTabAlwaysContainer.tooltip = Wubjeŕśo kontejner, aby nowy rejtarik wócynił
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = %S dowóliś, aby waše wobrazowe daty canvas HTML5 wužywał?
canvas.siteprompt2.warning = To dajo se wužywaś, aby wašo licadło jaden raz identificěrowało.
canvas.block = Blokěrowaś
canvas.block.accesskey = B
canvas.allow2 = Dowóliś
canvas.allow2.accesskey = D
canvas.remember2 = Toś ten rozsud se spomnjeś
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Pśespytany wót: %S
identity.identified.verified_by_you = Sćo wěstotne wuwześe za toś to sydło pśidał.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Certifikat wudany na: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Njewěsty
identity.notSecure.tooltip = Zwisk njejo wěsty
identity.extension.label = Rozšyrjenje (%S)
identity.extension.tooltip = Zacytany pśez rozšyrjenje: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Pómjeńšyś (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Skalěrowański schójźeńk (%S) slědk stajiś
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Pówětšyś (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Wurězaś (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Kopěrowaś (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Zasajźiś (%S)
geolocation.allow = Dowóliś
geolocation.allow.accesskey = D
geolocation.block = Blokěrowaś
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = To nastajenja za póstajenje pozicije wócynijo. Pšosym dajśo %S dowólnosć za póstajenje pozicije.
geolocation.shareWithSite4 = Cośo %S pśistup k swójomu stojnišćoju dowóliś?
geolocation.shareWithFile4 = Cośo toś tej lokalnej dataji pśistup k swójomu stojnišćoju dowóliś?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Cośo %1$S dowóliś, až %2$S pśistup k wašomu stojnišćoju dawa?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Dajśo %S dowólnosć za póstajenje pozicije w systemowych nastajenjach.
geolocation.systemSettingsTitle = Dowólnosć za póstajenje pozicije se wótcakujo
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = System buźo se was pšašaś, lěc %S toś to dowólnosć dajośo.
geolocation.remember = Toś ten rozsud se spomnjeś
# Virtual Reality Device UI
xr.allow2 = Dowóliś
xr.allow2.accesskey = D
xr.block = Blokěrowaś
xr.block.accesskey = B
xr.shareWithSite4 = Cośo %S pśistup k rědam wirtuelneje reality dowóliś? Pśez to se snaź sensibelne informacije pokazuju.
xr.shareWithFile4 = Cośo toś tej lokalnej dataji pśistup k rědam wirtuelneje reality dowóliś? Pśez to se snaź sensibelne informacije pokazuju.
xr.remember = Toś ten rozsud se spomnjeś
# Persistent storage UI
persistentStorage.allow = Dowóliś
persistentStorage.allow.accesskey = D
persistentStorage.block.label = Blokěrowaś
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Cośo %S dowóliś, daty w trajnem składowaku składowaś?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Dowóliś
webNotifications.allow2.accesskey = D
webNotifications.notNow = Nic něnto
webNotifications.notNow.accesskey = n
webNotifications.never = Nigda njedowóliś
webNotifications.never.accesskey = i
webNotifications.alwaysBlock = Pśecej blokěrowaś
webNotifications.alwaysBlock.accesskey = P
webNotifications.block = Blokěrowaś
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Cośo %S słanje powěźeńkow dowóliś?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S co pśistup k drugim nałoženjam a słužbam na toś tom rěźe.
localhost.remember2 = Móju wólbu za toś to sedło se spomnjeś
localhost.allowlabel = Dowóliś
localhost.blocklabel = Blokěrowaś
localhost.allow.accesskey = D
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S co pśistup k nałoženjam a słužbam na rědach, kótarež su z wašeju lokalneju seśu zwězane.
localNetwork.remember2 = Móju wólbu za toś to sedło se spomnjeś
localNetwork.allowLabel = Dowóliś
localNetwork.allow.accesskey = D
localNetwork.blockLabel = Blokěrowaś
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Cu how wen!
safebrowsing.getMeOutOfHereButton.accessKey = h
safebrowsing.deceptiveSite = Wobšudnikojske sedło!
safebrowsing.notADeceptiveSiteButton.label = To njejo wobšudnikojske sedło…
safebrowsing.notADeceptiveSiteButton.accessKey = w
safebrowsing.reportedAttackSite = Napadujuce sedło k wěsći dane!
safebrowsing.notAnAttackButton.label = To njejo napadujuce sedło…
safebrowsing.notAnAttackButton.accessKey = a
safebrowsing.reportedUnwantedSite = Sedło z njewitaneju softwaru k wěsći dane!
safebrowsing.reportedHarmfulSite = Škódne sedło k wěsći dane!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = %S pśepytaś
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = %S w modusu za rozwězowanje problemow znowego startowaś?
troubleshootModeRestartPromptMessage = Waše rozšyrjenja, drastwy a swójske nastajenja se nachylu znjemóžniju.
troubleshootModeRestartButton = Znowego startowaś
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Toś ten bok %1$S spómałšujo. Aby swój wobglědowak póspěšył, zastajśo toś ten bok.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Webbok %1$S spómałšujo. Aby swój wobglědowak póspěšył, zastajśo ten bok.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = „%1$S“ %2$S spómałšujo. Aby swój wobglědowak póspěšył, zastajśo ten bok.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = „%1$S“ %2$S spómałšujo. Aby swój wobglědowak póspěšył, zastajśo to rozšyrjenje.
processHang.add-on.learn-more.text = Dalšne informacije
processHang.button_stop2.label = Zastajiś
processHang.button_stop2.accessKey = Z
processHang.button_debug.label = Zmólki w skripśe namakaś
processHang.button_debug.accessKey = s
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Wokno na połnej wobrazowce zwobrazniś (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Bocnicu nalěwo pśesunuś
sidebar.moveToRight = Bocnicu napšawo pśesunuś
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Musyśo DRM zmóžniś, aby awdiodataju abo wideodataju na toś tom boku wótgrał.
emeNotifications.drmContentDisabled.button.label = DRM zmóžniś
emeNotifications.drmContentDisabled.button.accesskey = z
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S instalěrujo komponenty, kótarež su trjebne, aby awdio- abo wideodataju na toś tom boku wótgrali. Pšosym wopytajśo pózdźej hyšći raz.
emeNotifications.unknownDRMSoftware = Njeznaty
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = %S pśiměriś
decoder.noCodecs.button = Zgóńśo kak
decoder.noCodecs.accesskey = Z
decoder.noCodecsLinux.message = Aby wideo wótgrał, musyśo trjebne wideokodeki instalěrowaś.
decoder.noHWAcceleration.message = Aby wideokwalitu pólěpšył, musyśo Media Feature Pack pśedewześa Microsoft instalěrowaś.
decoder.noPulseAudio.message = Aby wideo wótgrał, musyśo trjebnu softwaru PulseAudio instalěrowaś.
decoder.unsupportedLibavcodec.message = libavcodec móžo napadojty byś abo se njepódpěra a by měł se za wótgraśe wideo aktualizěrowaś.
decoder.decodeError.message = Pśi dekoděrowanju medijoweje resurse jo zmólka nastała.
decoder.decodeError.button = Sedłowy problem k wěsći daś
decoder.decodeError.accesskey = d
decoder.decodeWarning.message = Pśi dekoděrowanju medijoweje resurse jo wótpórajobna zmólka nastała.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Musyśo se pla toś teje seśi pśizjawiś, nježli až móžośo pśistup k internetoju měś.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Pśizjawjeński bok seśi wócyniś
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Pšawa za %S
permissions.remove.tooltip = Pšawo wótpóraś a hyšći raz se pšašaś
permissions.fullscreen.promptCanceled = Njewobźěłane napšašowanja wó pšawa: Napšašowanja wó pšawa njeměli se wudaś, nježli až do połnowobrazowki DOM zastupijośo.
permissions.fullscreen.fullScreenCanceled = Połnowobrazowka DOM spušćona: Napšašowanja wó pšawa njeměli se wudaś, mjaztym sćo w połnowobrazowce DOM.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bitowy
aboutDialog.architecture.thirtyTwoBit = 32-bitowy
midi.allow.label = Dowóliś
midi.allow.accesskey = D
midi.block.label = Blokěrowaś
midi.block.accesskey = B
midi.remember = Toś ten rozsud se spomnjeś
midi.shareWithFile = Cośo toś tej lokalnej dataji pśistup k swójim MIDI-rědam dowóliś?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Cośo %S pśistup k swójim MIDI-rědam dowóliś?
midi.shareSysexWithFile = Cośo toś tej lokalnej dataji pśistup k swójim MIDI-rědam a słanje/dostawanje SysEx-powěsćow dowóliś?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Cośo toś %S pśistup k swójim MIDI-rědam a słanje/dostawanje SysEx-powěsćow dowóliś?
serial.allow.label = Dowóliś
serial.allow.accesskey = D
serial.block.label = Blokěrowaś
serial.block.accesskey = B
serial.shareWithFile = Cośo toś tej lokalnej dataji pśistup k swójim serijowym portam dowóliś?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Cośo %S pśistup k swójim serijowym portam dowóliś?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Slědk
storageAccess1.Allow.label = Dowóliś
storageAccess1.Allow.accesskey = D
storageAccess1.DontAllow.label = Blokěrowaś
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = %1$S dowóliś, jogo cookieje na %2$S wužywaś?
storageAccess1.hintText = Móžośo pśistup blokěrowaś, jolic njejo jasnje, cogodla %1$S toś te daty trjeba.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Web za „%S“ pytaś
