# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Encoding warnings and errors
EncNoDeclarationFrame = رمزگذاری نویسه‌های سند فریم‌شده اعلان نشده است. ممکن است سند بدون فریم والد متفاوت به نظر برسد.
EncXmlDecl = رمزگذاری نویسه‌های سند HTML با استفاده از نحو اعلان XML مشخص شده است. این شیوه با استاندارد مطابقت ندارد؛ اعلان رمزگذاری با استفاده از تگ meta در ابتدای بخش head کارآمدتر است.
EncMetaTooLate = تگ meta برای اعلان رمزگذاری نویسه‌ها بسیار دیر پیدا شد و رمزگذاری از روی محتوا حدس زده شد. تگ meta باید به ابتدای بخش head سند منتقل شود.
EncMetaTooLateFrame = تگ meta برای اعلان رمزگذاری نویسه‌ها بسیار دیر پیدا شد و به جای آن از رمزگذاری سند والد استفاده شد. تگ meta باید به ابتدای بخش head سند منتقل شود.
EncMetaAfterHeadInKilobyte = تگ meta برای اعلان رمزگذاری نویسه‌های سند باید به ابتدای بخش head سند منتقل شود.
EncNoDecl = رمزگذاری نویسه‌های سند اعلان نشده است، بنابراین رمزگذاری از روی محتوا حدس زده شد. رمزگذاری نویسه‌ها باید در هدر Content-Type پروتکل HTTP، با استفاده از تگ meta یا با استفاده از علامت ترتیب بایت (BOM) اعلان شود.
EncNoDeclPlain = رمزگذاری نویسه‌های سند اعلان نشده است، بنابراین رمزگذاری از روی محتوا حدس زده شد. رمزگذاری نویسه‌ها باید در هدر Content-Type پروتکل HTTP یا با استفاده از علامت ترتیب بایت (BOM) اعلان شود.
EncMetaUnsupported = یک رمزگذاری نویسهٔ پشتیبانی‌نشده برای سند HTML با استفاده از تگ meta اعلان شده است. این اعلان نادیده گرفته شد.
EncProtocolUnsupported = یک رمزگذاری نویسهٔ پشتیبانی‌نشده در سطح پروتکل انتقال اعلان شده است. این اعلان نادیده گرفته شد.
EncMetaUtf16 = از یک تگ meta برای اعلان رمزگذاری نویسه‌ها به صورت UTF-16 استفاده شده است. این اعلان به عنوان UTF-8 تفسیر شد.
EncMetaUserDefined = از یک تگ meta برای اعلان رمزگذاری نویسه‌ها به صورت x-user-defined استفاده شده است. به منظور سازگاری با فونت‌های قدیمی که عمداً با رمزگذاری نامناسب ساخته شده‌اند، این اعلان به عنوان windows-1252 تفسیر شد. این سایت باید به یونیکد مهاجرت کند.
EncMetaReplacement = از یک تگ meta برای اعلان رمزگذاری استفاده شده است که خطری برای حملات اسکریپت‌نویسی بین‌سایتی (XSS) محسوب می‌شود. به جای آن از رمزگذاری جایگزین (replacement) استفاده شد.
EncProtocolReplacement = یک رمزگذاری که خطری برای حملات اسکریپت‌نویسی بین‌سایتی (XSS) محسوب می‌شود در سطح پروتکل انتقال اعلان شده است. به جای آن از رمزگذاری جایگزین (replacement) استفاده شد.
EncDetectorReload = رمزگذاری نویسه‌های سند اعلان نشده بود و حدس زدن آن از روی محتوا با تأخیر ممکن شد. این موضوع باعث بارگیری مجدد سند شد. رمزگذاری نویسه‌ها باید در هدر Content-Type پروتکل HTTP، با استفاده از تگ meta یا با استفاده از علامت ترتیب بایت (BOM) اعلان شود.
EncDetectorReloadPlain = رمزگذاری نویسه‌های سند اعلان نشده بود و حدس زدن آن از روی محتوا با تأخیر ممکن شد. این موضوع باعث بارگیری مجدد سند شد. رمزگذاری نویسه‌ها باید در هدر Content-Type پروتکل HTTP یا با استفاده از علامت ترتیب بایت (BOM) اعلان شود.
EncError = جریان بایت‌ها بر اساس رمزگذاری نویسهٔ اعلان‌شده دارای خطا بود. اعلان رمزگذاری نویسه‌ها ممکن است نادرست باشد.
EncErrorFrame = جریان بایت‌ها بر اساس رمزگذاری نویسه‌ای که از سند والد به ارث رسیده است دارای خطا بود. رمزگذاری نویسه‌ها باید در هدر Content-Type پروتکل HTTP، با استفاده از تگ meta یا با استفاده از علامت ترتیب بایت (BOM) اعلان شود.
EncErrorFramePlain = جریان بایت‌ها بر اساس رمزگذاری نویسه‌ای که از سند والد به ارث رسیده است دارای خطا بود. رمزگذاری نویسه‌ها باید در هدر Content-Type پروتکل HTTP یا با استفاده از علامت ترتیب بایت (BOM) اعلان شود.
EncSpeculationFailMeta = ابتدای سند دوباره تجزیه شد، زیرا پیش از تگ meta که رمزگذاری را اعلان کرده بود، نویسه‌های غیر ASCII وجود داشت. تگ meta باید بدون هیچ کامنت حاوی نویسه‌های غیر ASCII قبل از آن، نخستین فرزند head باشد.
EncSpeculationFailXml = ابتدای سند دوباره تجزیه شد، زیرا در بخشی از سند که پیش از بازگشت به نحو اعلان XML به‌صورت ناموفق برای تگ meta جست‌وجو شده بود، نویسه‌های غیر ASCII وجود داشت. به جای استفاده از نحو اعلان XML، باید از یک تگ meta در ابتدای بخش head استفاده شود.
# The audience of the following message isn't the author of the document but other people debugging browser behavior.
EncSpeculationFail2022 = ابتدای سند دوباره تجزیه شد، زیرا ISO-2022-JP یک رمزگذاری ناسازگار با ASCII است.
# Tokenizer errors
errGarbageAfterLtSlash = نویسه‌های نامعتبر پس از «</».
errLtSlashGt = مشاهدهٔ «</>». علل احتمالی: «<» اسکیپ‌نشده (با «&lt;» جایگزین کنید) یا اشتباه تایپی در تگ پایانی.
errCharRefLacksSemicolon = ارجاع نویسه (Character reference) با نقطه ویرگول (;) خاتمه نیافته است.
errNoDigitsInNCR = در ارجاع عددی نویسه (Numeric character reference) هیچ رقمی وجود ندارد.
errGtInSystemId = وجود «>» در شناسهٔ سیستم (System identifier).
errGtInPublicId = وجود «>» در شناسهٔ عمومی (Public identifier).
errNamelessDoctype = نوع سند (Doctype) بدون نام.
errConsecutiveHyphens = خط‌های تیرهٔ متوالی کامنت را خاتمه ندادند. استفاده از «--» درون کامنت مجاز نیست، اما مثلاً «- -» مجاز است.
errPrematureEndOfComment = پایان زودهنگام کامنت. برای بستن صحیح کامنت از «-->» استفاده کنید.
errBogusComment = کامنت ساختگی و نامعتبر.
errUnquotedAttributeLt = وجود «<» در مقدار مشخصهٔ بدون علامت نقل‌قول. علت احتمالی: جا افتادن «>» بلافاصله پیش از آن.
errUnquotedAttributeGrave = وجود «`» در مقدار مشخصهٔ بدون علامت نقل‌قول. علت احتمالی: استفاده از نویسهٔ اشتباه به عنوان علامت نقل‌قول.
errUnquotedAttributeQuote = وجود علامت نقل‌قول در مقدار مشخصهٔ بدون نقل‌قول. علل احتمالی: چسبیدن مشخصه‌ها به هم یا وجود رشتهٔ پرسمان (Query string) نشانی وب در مقدار مشخصهٔ بدون نقل‌قول.
errUnquotedAttributeEquals = وجود «=» در مقدار مشخصهٔ بدون علامت نقل‌قول. علل احتمالی: چسبیدن مشخصه‌ها به هم یا وجود رشتهٔ پرسمان (Query string) نشانی وب در مقدار مشخصهٔ بدون نقل‌قول.
errSlashNotFollowedByGt = بعد از اسلش (/) بلافاصله «>» قرار نگرفته است.
errNoSpaceBetweenAttributes = عدم وجود فاصله بین مشخصه‌ها.
errUnquotedAttributeStartLt = وجود «<» در ابتدای مقدار مشخصهٔ بدون علامت نقل‌قول. علت احتمالی: جا افتادن «>» بلافاصله پیش از آن.
errUnquotedAttributeStartGrave = وجود «`» در ابتدای مقدار مشخصهٔ بدون علامت نقل‌قول. علت احتمالی: استفاده از نویسهٔ اشتباه به عنوان علامت نقل‌قول.
errUnquotedAttributeStartEquals = وجود «=» در ابتدای مقدار مشخصهٔ بدون علامت نقل‌قول. علت احتمالی: علامت مساوی تکراری و سرگردان.
errAttributeValueMissing = مقدار مشخصه وجود ندارد.
errBadCharBeforeAttributeNameLt = مشاهدهٔ «<» در جایی که نام مشخصه مورد انتظار بود. علت احتمالی: جا افتادن «>» بلافاصله پیش از آن.
errEqualsSignBeforeAttributeName = مشاهدهٔ «=» در جایی که نام مشخصه مورد انتظار بود. علت احتمالی: نام مشخصه جا افتاده است.
errBadCharAfterLt = نویسهٔ نامعتبر پس از «<». علت احتمالی: «<» اسکیپ‌نشده. سعی کنید آن را به‌صورت «&lt;» اسکیپ کنید.
errLtGt = مشاهدهٔ «<>». علل احتمالی: «<» اسکیپ‌نشده (با «&lt;» جایگزین کنید) یا اشتباه تایپی در تگ آغازین.
errProcessingInstruction = مشاهدهٔ «<?>». علت احتمالی: تلاش برای استفاده از دستور پردازشی XML در HTML. (دستورهای پردازشی XML در HTML پشتیبانی نمی‌شوند.)
errUnescapedAmpersandInterpretedAsCharacterReference = رشتهٔ بعد از «&» به عنوان ارجاع نویسه تفسیر شد. (احتمالاً «&» باید به‌صورت «&amp;» اسکیپ می‌شد.)
errNotSemicolonTerminated = ارجاع نام‌گذاری‌شدهٔ نویسه با نقطه ویرگول (;) خاتمه نیافته است. (یا «&» باید به‌صورت «&amp;» اسکیپ می‌شد.)
errNoNamedCharacterMatch = علامت «&» آغازگر هیچ ارجاع نویسه‌ای نبود. (احتمالاً «&» باید به‌صورت «&amp;» اسکیپ می‌شد.)
errQuoteBeforeAttributeName = مشاهدهٔ علامت نقل‌قول در جایی که نام مشخصه مورد انتظار بود. علت احتمالی: جا افتادن «=» بلافاصله پیش از آن.
errLtInAttributeName = وجود «<» در نام مشخصه. علت احتمالی: جا افتادن «>» بلافاصله پیش از آن.
errQuoteInAttributeName = وجود علامت نقل‌قول در نام مشخصه. علت احتمالی: جا افتادن علامت نقل‌قول جفت در جایی قبل‌تر.
errExpectedPublicId = شناسهٔ عمومی (Public identifier) مورد انتظار بود اما نوع سند (Doctype) به پایان رسید.
errBogusDoctype = نوع سند (Doctype) ساختگی و نامعتبر.
maybeErrAttributesOnEndTag = تگ پایانی دارای مشخصه بود.
maybeErrSlashInEndTag = علامت «/» سرگردان در انتهای تگ پایانی.
errNcrSurrogate = ارجاع نویسه به یک جانشین (Surrogate) گسترش می‌یابد.
errNcrInC1Range = ارجاع عددی نویسه به محدودهٔ کنترلی C1 گسترش یافته است.
errEofInPublicId = پایان غیرمنتظرهٔ فایل (EOF) درون شناسهٔ عمومی.
errEofInComment = پایان غیرمنتظرهٔ فایل (EOF) درون کامنت.
errEofInDoctype = پایان غیرمنتظرهٔ فایل (EOF) درون Doctype.
errEofInAttributeValue = پایان فایل هنگام قرار داشتن در مقدار مشخصه رخ داد. نادیده گرفتن تگ.
errEofInAttributeName = پایان فایل درون نام مشخصه رخ داد. نادیده گرفتن تگ.
errEofWithoutGt = پایان فایل بدون بسته شدن تگ قبلی با «>» مشاهده شد. نادیده گرفتن تگ.
errEofInTagName = پایان فایل هنگام جست‌وجوی نام تگ مشاهده شد. نادیده گرفتن تگ.
errEofInEndTag = پایان غیرمنتظرهٔ فایل (EOF) درون تگ پایانی. نادیده گرفتن تگ.
errEofAfterLt = پایان غیرمنتظرهٔ فایل (EOF) پس از «<».
errNcrOutOfRange = ارجاع نویسه خارج از محدودهٔ مجاز یونیکد است.
errNcrUnassigned = ارجاع نویسه به یک کدپوینت (Code point) به‌طور دائم تخصیص‌نیافته گسترش می‌یابد.
errDuplicateAttribute = مشخصهٔ تکراری.
errEofInSystemId = پایان غیرمنتظرهٔ فایل (EOF) درون شناسهٔ سیستم.
errExpectedSystemId = شناسهٔ سیستم (System identifier) مورد انتظار بود اما Doctype به پایان رسید.
errMissingSpaceBeforeDoctypeName = عدم وجود فاصله قبل از نام Doctype.
errNestedComment = مشاهدهٔ «<!--» درون یک کامنت. علت احتمالی: کامنت تودرتو (که مجاز نیست).
errNcrZero = ارجاع نویسه به صفر گسترش می‌یابد.
errNoSpaceBetweenDoctypeSystemKeywordAndQuote = نبود فاصله بین کلیدواژهٔ «SYSTEM» در Doctype و علامت نقل‌قول.
errNoSpaceBetweenPublicAndSystemIds = نبود فاصله بین شناسه‌های عمومی و سیستم در Doctype.
errNoSpaceBetweenDoctypePublicKeywordAndQuote = نبود فاصله بین کلیدواژهٔ «PUBLIC» در Doctype و علامت نقل‌قول.
# Tree builder errors
errDeepTree = درخت سند بیش از حد عمیق است. عمق درخت برای مسطح‌سازی به ۵۱۳ عنصر کاهش می‌یابد.
errStrayStartTag2 = تگ آغازین سرگردان «%1$S».
errStrayEndTag = تگ پایانی سرگردان «%1$S».
errUnclosedElements = تگ پایانی «%1$S» مشاهده شد، اما عناصر باز وجود داشتند.
errUnclosedElementsImplied = تگ پایانی «%1$S» به طور ضمنی استنباط شد، اما عناصر باز وجود داشتند.
errUnclosedElementsCell = یک سلول جدول به طور ضمنی بسته شد، اما عناصر باز وجود داشتند.
errStrayDoctype = مورد سرگردان Doctype.
errAlmostStandardsDoctype = اعلان Doctype برای حالت شبه‌استاندارد (Almost standards mode). مقدار مورد انتظار: «<!DOCTYPE html>».
errQuirkyDoctype = اعلان Doctype برای حالت ناسازگار (Quirks mode). مقدار مورد انتظار: «<!DOCTYPE html>».
errAlmostStandardsDoctypeVerbose = این صفحه در حالت شبه‌استاندارد (Almost Standards Mode) قرار دارد. چیدمان صفحه ممکن است تحت تأثیر قرار گیرد. برای حالت استاندارد از «<!DOCTYPE html>» استفاده کنید.
errQuirkyDoctypeVerbose = این صفحه در حالت ناسازگار (Quirks Mode) قرار دارد. چیدمان صفحه ممکن است تحت تأثیر قرار گیرد. برای حالت استاندارد از «<!DOCTYPE html>» استفاده کنید.
errNonSpaceInTrailer = نویسهٔ غیرفاصله‌ای در بخش پایانی صفحه (Trailer).
errNonSpaceAfterFrameset = نویسهٔ غیرفاصله‌ای پس از «frameset».
errNonSpaceInFrameset = نویسهٔ غیرفاصله‌ای در «frameset».
errNonSpaceAfterBody = نویسهٔ غیرفاصله‌ای پس از body.
errNonSpaceInColgroupInFragment = نویسهٔ غیرفاصله‌ای در «colgroup» هنگام تجزیهٔ قطعه‌کد.
errNonSpaceInNoscriptInHead = نویسهٔ غیرفاصله‌ای درون «noscript» داخل «head».
errFooBetweenHeadAndBody = عنصر «%1$S» بین «head» و «body».
errStartTagWithoutDoctype = مشاهدهٔ تگ آغازین بدون مشاهدهٔ قبلی Doctype. مقدار مورد انتظار: «<!DOCTYPE html>».
errNoSelectInTableScope = هیچ عنصر «select» در محدودهٔ table وجود ندارد.
errStartSelectWhereEndSelectExpected = تگ آغازین «select» در جایی که تگ پایانی مورد انتظار بود.
errStartTagWithSelectOpen = تگ آغازین «%1$S» با باز بودن «select».
errBadStartTagInNoscriptInHead = تگ آغازین نامعتبر «%1$S» در «noscript» داخل «head».
errImage = مشاهدهٔ تگ آغازین «image».
errFooSeenWhenFooOpen2 = تگ آغازین «%1$S» مشاهده شد در حالی که عنصری از همان نوع از قبل باز بود.
errHeadingWhenHeadingOpen = تیتر (Heading) نمی‌تواند فرزند یک تیتر دیگر باشد.
errFramesetStart = تگ آغازین «frameset» مشاهده شد.
errNoCellToClose = هیچ سلولی برای بسته شدن وجود ندارد.
errStartTagInTable = تگ آغازین «%1$S» در «table» مشاهده شد.
errFormWhenFormOpen = تگ آغازین «form» مشاهده شد، اما در حال حاضر یک عنصر فعال «form» وجود دارد. فرم‌های تودرتو مجاز نیستند. نادیده گرفتن تگ.
errTableSeenWhileTableOpen = تگ آغازین برای «table» مشاهده شد اما «table» قبلی هنوز باز است.
errStartTagInTableBody = تگ آغازین «%1$S» در بدنهٔ جدول (Table body).
errEndTagSeenWithoutDoctype = تگ پایانی بدون مشاهدهٔ قبلی Doctype مشاهده شد. مقدار مورد انتظار: «<!DOCTYPE html>».
errEndTagAfterBody = تگ پایانی پس از بسته شدن «body» مشاهده شد.
errEndTagSeenWithSelectOpen = تگ پایانی «%1$S» با باز بودن «select».
errGarbageInColgroup = نویسه‌های نامعتبر در قطعه‌کد «colgroup».
errEndTagBr = تگ پایانی «br».
errNoElementToCloseButEndTagSeen = عنصر «%1$S» در این محدوده وجود ندارد اما تگ پایانی «%1$S» مشاهده شد.
errHtmlStartTagInForeignContext = تگ آغازین HTML به نام «%1$S» در بافت فضای‌نام خارجی (Foreign namespace).
errNoTableRowToClose = هیچ سطر جدولی برای بسته شدن وجود ندارد.
errNonSpaceInTable = نویسه‌های غیرفاصله‌ای نابجا درون جدول.
errUnclosedChildrenInRuby = فرزندان بسته‌نشده در «ruby».
errStartTagSeenWithoutRuby = تگ آغازین «%1$S» بدون باز بودن عنصر «ruby» مشاهده شد.
errSelfClosing = استفاده از نحو خودبسته («/>») روی یک عنصر غیرتهی (Non-void) در HTML. اسلش نادیده گرفته شده و به عنوان تگ آغازین در نظر گرفته می‌شود.
errNoCheckUnclosedElementsOnStack = عناصر بسته‌نشده در پشته (Stack).
errEndTagDidNotMatchCurrentOpenElement = تگ پایانی «%1$S» با نام عنصر باز فعلی («%2$S») مطابقت نداشت.
errEndTagViolatesNestingRules = تگ پایانی «%1$S» قوانین تودرتویی (Nesting) را نقض می‌کند.
errEndWithUnclosedElements = تگ پایانی برای «%1$S» مشاهده شد، اما عناصر بسته‌نشده وجود داشتند.
errListUnclosedStartTags = یک یا چند عنصر بسته‌نشده.
