# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Lagra innloggingar
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-username-cmd =
    .label = Kopier brukarnamn
    .accesskey = u
edit-username-cmd =
    .label = Rediger brukarnamn
    .accesskey = d
copy-password-cmd =
    .label = Kopier passord
    .accesskey = K
edit-password-cmd =
    .label = Rediger passord
    .accesskey = R
search-filter =
    .accesskey = S
    .placeholder = Søk
column-heading-site =
    .label = Nettstad
column-heading-username =
    .label = Brukarnamn
column-heading-password =
    .label = Passord
column-heading-time-created =
    .label = Fyrst brukt
column-heading-time-last-used =
    .label = Sist brukt
column-heading-time-password-changed =
    .label = Sist endra
column-heading-times-used =
    .label = Gongar brukt
remove =
    .label = Fjern
    .accesskey = F
import =
    .label = Importer …
    .accesskey = I
close-button =
    .label = Lat att
    .accesskey = L
remove-all-passwords-title = Slett alle passorda
