# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

password-not-set =
    .value = (не е зададена)
failed-pw-change = Грешка при промяна на главната парола.
incorrect-pw = Главната парола, която въведохте е грешна. Моля, опитайте отново.
pw-change-ok = Главната парола е сменена успешно.
pw-empty-warning = Вашите запазени уеб и пощенски пароли, данни от формуляри и частни ключове няма да бъдат защитени.
pw-erased-ok = Изтрихте вашата главна парола. { pw-empty-warning }
pw-not-wanted = Внимание! Решихте да не използвате главна парола. { pw-empty-warning }
pw-change2empty-in-fips-mode = В момента е активен режим FIPS. Той изисква попълнена главна парола.
failed-pp-change = Грешка при промяна на главната парола.
incorrect-pp = Главната парола, която въведохте е грешна. Моля, опитайте отново.
pp-change-ok = Главната парола е сменена успешно.
pp-empty-warning = Запазени пароли и частни ключове няма да бъдат защитени.
pp-erased-ok = Изтрихте вашата главна парола. { pp-empty-warning }
pp-not-wanted = Внимание! Решихте да не използвате главна парола. { pp-empty-warning }
pp-change2empty-in-fips-mode = В момента сте в режим на FIPS. FIPS изисква главна парола.
pw-change-success-title = Успешна промяна на парола
pw-change-failed-title = Грешка при промяна на паролата
pw-remove-button =
    .label = Премахване
set-password =
    .title = Промяна на главната парола
primary-password-dialog =
    .title = Главна парола
set-password-old-password = Текуща парола:
set-password-new-password = Нова парола:
set-password-reenter-password = Нова парола отново:
set-password-meter = Качество на паролата
set-password-meter-loading = Зареждане
master-password-admin = Администраторът изисква да изберете главна парола, преди да запазвате пароли.
master-password-description = Главната Парола се използва за защитаване на чувствителна информация като пароли за страници. Ако създадете главна парола, когато { -brand-short-name } извлича защитената с нея информация ще трябва да я въвеждате, еднократно за сесията.
master-password-warning = Моля, погрижете се да запомните тази главната парола. Ако я забравите ще загубите достъпа до защитената с нея информация.
remove-password =
    .title = Премахване на главна парола
primary-password-admin = Администраторът изисква да изберете главна парола, преди да запазвате регистрации и пароли.
primary-password-description = Главната парола се използва за да защитава на чувствителната информация, като регистрации пароли, на устройството. Ако създадете главна парола, когато { -brand-short-name } извлича защитената с нея информация ще трябва да я въвеждате, еднократно за сесията.
primary-password-warning = Моля, погрижете се да запомните тази главната парола. Ако я забравите ще загубите достъпа до защитената с нея информация на това устройство.
remove-primary-password =
    .title = Премахване на главна парола
remove-info =
    .value = Трябва да въведете текущата си парола, за да продължите:
remove-warning1 = Вашата главна парола се използва за защитаване на чувствителна информация като напр. пароли за сайтове.
remove-warning2 = Ако премахнете главната парола, вашата информация няма да бъде защитена, ако има пробив в компютъра ви.
remove-primary-password-warning1 = Главната парола се използва за защитаване на чувствителна информация като регистрации и пароли.
remove-primary-password-warning2 = Ако премахнете главната парола, вашата информация няма да бъде защитена, в случай на пробив в сигурността на компютъра ви.
remove-password-old-password =
    .value = Текуща парола:
