# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

title = A-zivout ar rouedad
warning = Arnodel eo ar bajenn-mañ. Arverit anezhi gant evezh.
show-next-time-checkbox = Diskouez ar c'hemenn-mañ ar wech a zeu
ok = Mat eo
http = HTTP
sockets = Sockets
dns = DNS
websockets = WebSockets
refresh = Azbevaat
auto-refresh = Azbevaat ent emgefreek pep 3 eilenn
hostname = Anv ostiz
port = Porzh
http2 = HTTP/2
ssl = SSL
active = Oberiant
idle = Dioberiant
host = Ostiz
tcp = TCP
sent = Kaset
received = Degemeret
family = Familh
trr = TRR
addresses = Chomlec'hioù
expires = Deiziad termen (eilennoù)
messages-sent = Kemennadennoù kaset
messages-received = Kemennadennoù degemeret
bytes-sent = Eizhbitoù kaset
bytes-received = Eizhbitoù degemeret
logging = Kerzhlevr
log-tutorial = Lennit <a data-l10n-name="logging">Kerzhlevriñ HTTP</a> evit ditouroú war an doare da arverañ an ostilh-mañ.
current-log-file = Restr kerzhlevr bremanel:
current-log-modules = Molladoù kerzhlevr bremanel:
set-log-file = Lakaat ar restr kerzhlevr
set-log-modules = Arventennañ molladoù ar c'herzhlevr
start-logging = Kregiñ da skrivañ er c'herzhlevr
stop-logging = Paouez da skrivañ er c'herzhlevr
dns-lookup = Selladenn DNS
dns-lookup-button = Diskoulmañ
dns-domain = Domani:
dns-lookup-table-column = IPoù
rcwn = Stadegoù RCWN
rcwn-status = Satud RCWN
rcwn-cache-won-count = Konter berzhioù ar c'hrubuilh
rcwn-net-won-count = Konter berzhioù web
total-network-requests = Niver hollek a azgoulennoù rouedad
rcwn-operation = Obererezhioù ar c'hrubuilh
rcwn-perf-open = Digoradurioù
rcwn-perf-read = Lenn
rcwn-perf-write = Skrivañ
rcwn-perf-entry-open = Digoradur enankad
rcwn-avg-short = Keidenn vihan
rcwn-avg-long = Keidenn vras
rcwn-std-dev-long = Forc'had rizh bras
rcwn-cache-slow = Niver a grubuilh gorrek
rcwn-cache-not-slow = Niver a grubuilh prim
