# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = Veb sahifa yangi manzilga yoʻnaltirilmoqda. Siz kiritgan ma`lumotlar shaklini yangi manzilga ham joʻnatilishini xohlaysizmi?
# Directory listing strings
DirTitle = %1$S indeksi
DirGoUp = Yuqori darajadagi direktoriyaga koʻtarish
ShowHidden = Yashirilgan obyektlarni koʻrsatish
DirColName = Nomi
DirColSize = Hajmi
DirColMTime = Soʻnggi oʻzgartirilgan
DirFileLabel = Fayl:\u0020
