# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

e2e-intro-description = Om fersifere of digitaal ûndertekene berjochten te ferstjoeren, moatte jo in fersiferingstechnology ynstelle, itsij OpenPGP of S/MIME.
e2e-intro-description-more = Selektearje jo persoanlike kaai om it gebrûk fan OpenPGP mooglik te meitsjen, of jo persoanlike sertifikaat om it gebrûk fan S/MIME mooglik te meitsjen. Foar in persoanlike kaai of sertifikaat besitte jo de byhearrende geheime kaai.
openpgp-key-user-id-label = Account / Brûkers-ID
openpgp-keygen-title-label =
    .title = OpenPGP-kaai oanmeitsje
openpgp-cancel-key =
    .label = Annulearje
    .tooltiptext = Oanmeitsjen kaai annulearje
openpgp-key-gen-expiry-title =
    .label = Jildichheidsdoer kaai
openpgp-key-gen-expire-label = Kaai ferrint oer
openpgp-key-gen-days-label =
    .label = dagen
openpgp-key-gen-months-label =
    .label = moannen
openpgp-key-gen-years-label =
    .label = jier
openpgp-key-gen-no-expiry-label =
    .label = Kaai ferrint net
openpgp-key-gen-key-size-label = Kaaigrutte
openpgp-key-gen-console-label = Oanmeitsjen kaai
openpgp-key-gen-key-type-label = Kaaitype
openpgp-key-gen-key-type-rsa =
    .label = RSA
openpgp-key-gen-key-type-ecc =
    .label = ECC (Elliptyske Kurve)
openpgp-generate-key =
    .label = Kaai oanmeitsje
    .tooltiptext = Makket in nije OpenPGP-kaai oan foar fersifering en/of ûndertekening
openpgp-advanced-prefs-button-label =
    .label = Avansearre…
openpgp-keygen-desc = <a data-l10n-name="openpgp-keygen-desc-link">OPMERKING: it oanmeitsjen fan de kaai kin inkelde minuten duorje.</a> Slút de tapassing net ôf wylst de kaai oanmakke wurdt. Aktyf navigearje of skiifyntensive bewurkingen útfiere wylst it oanmeitsjen fan de kaai sil de ‘samar-wat-pool’ oanfolje en it proses fersnelle. Jo wurde warskôge wannear't it oanmeitsjen fan de kaai ree is.
openpgp-key-expiry-label =
    .label = Ferrindatum
openpgp-key-id-label =
    .label = Kaai-ID
openpgp-cannot-change-expiry = Dit is in kaai mei in komplekse struktuer, it wizigjen fan de ferrindatum wurdt net stipe.
openpgp-key-man-title =
    .title = OpenPGP-kaaibehearder
openpgp-key-man-generate =
    .label = Nije kaaipear
    .accesskey = p
openpgp-key-man-gen-revoke =
    .label = Ynlûkingssertifikaat
    .accesskey = Y
openpgp-key-man-ctx-gen-revoke-label =
    .label = Ynlûkingssertifikaat oanmeitsje en bewarje
openpgp-key-man-file-menu =
    .label = Bestân
    .accesskey = B
openpgp-key-man-edit-menu =
    .label = Bewurkje
    .accesskey = w
openpgp-key-man-view-menu =
    .label = Werjaan
    .accesskey = r
openpgp-key-man-generate-menu =
    .label = Oanmeitsje
    .accesskey = O
openpgp-key-man-keyserver-menu =
    .label = Kaaiserver
    .accesskey = K
openpgp-key-man-import-public-from-file =
    .label = Iepenbiere kaai(en) ymportearje út bestân
    .accesskey = I
openpgp-key-man-import-secret-from-file =
    .label = Geheime kaai(en) ymportearje út bestân
openpgp-key-man-import-sig-from-file =
    .label = Ynlûking(en) ymportearje út bestân
openpgp-key-man-import-from-clipbrd =
    .label = Kaai(en) ymportearje fan klamboerd ôf
    .accesskey = k
openpgp-key-man-import-from-url =
    .label = Kaai(en) ymportearje fan URL út
    .accesskey = U
openpgp-key-man-export-to-file =
    .label = Iepenbiere kaai(en) eksportearje nei bestân
    .accesskey = e
openpgp-key-man-send-keys =
    .label = Iepenbiere kaai(en) per e-mail ferstjoere
    .accesskey = f
openpgp-key-man-backup-secret-keys =
    .label = Reservekopybestân fan geheime kaai(en) meitsje
    .accesskey = R
openpgp-key-man-discover-cmd =
    .label = Kaaien online ûntdekke
    .accesskey = o
openpgp-key-man-discover-prompt = Fier om OpenPGP-kaaien online, op kaaiservers of mei it WKD-protokol te ûntdekken, in e-mailadres of in kaai-ID yn.
openpgp-key-man-discover-progress = Sykje…
openpgp-key-copy-key =
    .label = Iepenbiere kaai kopiearje
    .accesskey = k
openpgp-key-export-key =
    .label = Iepenbiere kaai nei bestân eksportearje
    .accesskey = k
openpgp-key-backup-key =
    .label = Reservekopybestân fan geheime kaai meitsje
    .accesskey = R
openpgp-key-send-key =
    .label = Iepenbiere kaai fia e-mail ferstjoere
    .accesskey = f
openpgp-key-man-copy-to-clipbrd =
    .label = Iepenbiere kaai(en) nei klamboerd kopiearje
    .accesskey = k
openpgp-key-man-ctx-expor-to-file-label =
    .label = Kaaien nei bestân eksportearje
openpgp-key-man-ctx-copy-to-clipbrd-label =
    .label = Iepenbiere kaaien nei klamboerd kopiearje
openpgp-key-man-close =
    .label = Slute
openpgp-key-man-reload =
    .label = Kaaibuffer opnij lade
    .accesskey = K
openpgp-key-man-change-expiry =
    .label = Ferrindatum wizigje
    .accesskey = F
openpgp-key-man-del-key =
    .label = Kaai(en) fuortsmite
    .accesskey = f
openpgp-delete-key =
    .label = Kaai fuortsmite
    .accesskey = f
openpgp-key-man-revoke-key =
    .label = Kaai ynlûke
    .accesskey = y
openpgp-key-man-key-props =
    .label = Kaaieigenskippen
    .accesskey = K
openpgp-key-man-key-more =
    .label = Mear
    .accesskey = M
openpgp-key-man-view-photo =
    .label = Foto-ID
    .accesskey = F
openpgp-key-man-ctx-view-photo-label =
    .label = Foto-ID besjen
openpgp-key-man-show-invalid-keys =
    .label = Unjildige kaaien werjaan
    .accesskey = U
openpgp-key-man-show-others-keys =
    .label = Kaaien fan oare persoanen werjaan
    .accesskey = K
openpgp-key-man-user-id-label =
    .label = Namme
openpgp-key-man-fingerprint-label =
    .label = Fingerôfdruk
openpgp-key-man-select-all =
    .label = Alle kaaien selektearje
    .accesskey = A
openpgp-key-man-empty-tree-tooltip =
    .label = Fier yn it boppesteande fjild syktermen yn
openpgp-key-man-nothing-found-tooltip =
    .label = Gjin inkelde kaai komt oerien mei jo syktermen
openpgp-key-man-please-wait-tooltip =
    .label = In amerijke geduld wylst de kaaien laden wurde…
openpgp-key-man-filter-label =
    .placeholder = Sykje nei kaaien
openpgp-key-man-select-all-key =
    .key = A
openpgp-key-man-key-details-key =
    .key = I
openpgp-key-details-title =
    .title = Kaaieigenskippen
openpgp-key-details-signatures-tab =
    .label = Sertifisearringen
openpgp-key-details-structure-tab =
    .label = Struktuer
openpgp-key-details-uid-certified-col =
    .label = Brûker-ID / Sertifisearre troch
openpgp-key-details-user-id2-label = Understelde kaaieigener
openpgp-key-details-id-label =
    .label = ID
openpgp-key-details-key-type-label = Type
openpgp-key-details-key-part-label =
    .label = Kaaidiel
openpgp-key-details-algorithm-label =
    .label = Algoritme
openpgp-key-details-size-label =
    .label = Grutte
openpgp-key-details-created-label =
    .label = Oanmakke
openpgp-key-details-created-header = Oanmakke
openpgp-key-details-expiry-label =
    .label = Ferrindatum
openpgp-key-details-expiry-header = Ferrindatum
openpgp-key-details-usage-label =
    .label = Gebrûk
openpgp-key-details-fingerprint-label = Fingerôfdruk
openpgp-key-details-sel-action =
    .label = Selektearje aksje…
    .accesskey = S
openpgp-key-details-also-known-label = Understelde alternative identiteiten fan de kaaieigener:
openpgp-card-details-close-window-label =
    .buttonlabelaccept = Slute
openpgp-acceptance-label =
    .label = Jo akseptaasje
openpgp-acceptance-rejected-label =
    .label = Nee, dizze kaai wegerje.
openpgp-acceptance-undecided-label =
    .label = Noch net, miskien letter.
openpgp-acceptance-unverified-label =
    .label = Ja, mar ik haw net kontrolearre oft dit de krekte kaai is.
openpgp-acceptance-verified-label =
    .label = Ja, ik haw persoanlik ferifiearre dat dizze kaai de krekte fingerôfdruk hat.
key-accept-personal =
    Foar dizze kaai hawwe jo sawol it iepenbiere as it geheime diel. Jo meie him brûke as in persoanlike kaai.
    As dizze kaai troch in oar oan jo jûn is, brûk him dan net as persoanlike kaai.
key-personal-warning = Hawwe jo dizze kaai sels oanmakke en it ferwiist it toande kaaieigendom nei josels?

## e2e encryption settings


## OpenPGP Key selection area


## Account settings export output

