# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = محفوظ  تھئویو
dialogTitleAddBookmark = نُو بوک مارْک
dialogTitleAddMulti = نُْو بوک مارْک
dialogTitleEdit = باپت پراپرٹی "%S"
bookmarkAllTabsDefault = [فولڈر ناو]
newFolderDefault = نئو  فولڈر
newBookmarkDefault = نُو بوک مارْک
