# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language-name-aa = আফাৰ
language-name-ab = আবখাজিয়ান
language-name-ach = অচলি
language-name-ae = আভেষ্টান
language-name-af = আফ্ৰিকান্স
language-name-ak = আকান
language-name-am = আম্‌হাৰিক
language-name-an = আৰাগ'নিছ
language-name-ar = আৰবী
language-name-as = অসমীয়া
language-name-ast = আষ্টুৰিয়ান
language-name-av = আভাৰিক
language-name-ay = আয়মাৰা
language-name-az = আজাৰ্বাইজানি
language-name-ba = বাছকিৰ
language-name-be = বেলাৰুচীয়
language-name-bg = বুলগেৰীয়
language-name-bh = বিহাৰি
language-name-bi = বিশ্লামা
language-name-bm = বাম্বাৰা
language-name-bn = বঙালি
language-name-bo = তিব্বতীয়
language-name-br = ব্ৰেটন
language-name-bs = ব'ছনীয়ান
language-name-ca = কেটেলান
language-name-cak = কাকচিকেল
language-name-ce = চেচেন
language-name-ch = ছামোৰো
language-name-co = ক'ৰ্ছিকান
language-name-cr = ক্ৰি
language-name-crh = ক্ৰিমিয়েন টাটৰ
language-name-cs = ছেক্‌
language-name-csb = কাশ্বুবিয়ান
language-name-cu = চার্চ শ্লাভিক
language-name-cv = চুভাশ্ব
language-name-cy = ৱেল্‌শ্ব
language-name-da = ডেনিশ্ব
language-name-de = জাৰ্মান
language-name-dsb = নিম্ন চৰবিয়ান
language-name-dv = ডিৱেহি
language-name-dz = ভুটানি
language-name-ee = ইৱি
language-name-el = গ্ৰীক
language-name-en = ইংৰাজী
language-name-eo = এস্পেৰান্টো
language-name-es = হিস্পানীয়
language-name-et = এস্টোনিয়ান
language-name-eu = বাস্ক
language-name-fa = ফৰাচি
language-name-ff = ফুলাহ
language-name-fi = ফিনিশ্ব
language-name-fj = ফিজিয়ান
language-name-fo = পেইৰোইছ
language-name-fr = ফৰাচী
language-name-fur = ফ্ৰিউলিয়ান
language-name-fy = ফ্ৰিচিয়ান
language-name-ga = আইৰিশ্ব
language-name-gd = স্কট্চ গেলিক
language-name-gl = গেইলিচিয়ান
language-name-gn = গুৱাৰানি
language-name-gu = গুজৰাটি
language-name-gv = মানক্স
language-name-ha = হাউছা
language-name-haw = হাৱাইয়ান
language-name-he = হিব্ৰিউ
language-name-hi = হিন্দী
language-name-hil = হিলিগেন'ন
language-name-ho = হিৰি ম'টু
language-name-hr = ক্ৰোয়েছিয়ান
language-name-hsb = আপাৰ ছ'ৰ্বিয়ান
language-name-ht = হাইছিয়ান
language-name-hu = হাঙ্গেৰিয়ান
language-name-hy = আৰ্মেনিয়ান
language-name-hz = হেৰেৰো
language-name-ia = ইন্টাৰ্লিঙ্গুৱা
language-name-id = ইন্ডোনেচিয়ান
language-name-ie = ইন্টাৰ্লিঙ্গ
language-name-ig = ইগ্বো
language-name-ii = চিচুৱা য়ি
language-name-ik = ইনুপিয়াক
language-name-io = ইডো
language-name-is = আইচলেণ্ডিক
language-name-it = ইটালীয়
language-name-iu = ইনুক্টিটুট
language-name-ja = জাপানী
language-name-jv = জাভানিছ
language-name-ka = জিয়'ৰ্জিয়ান
language-name-kab = কবাইল
language-name-kg = কঙ্গো
language-name-ki = কিকুয়ু
language-name-kj = কুৱান্যামা
language-name-kk = কাজাখ
language-name-kl = গ্ৰীনলেণ্ডিক
language-name-km = কেম্বোদিয়ান
language-name-kn = কন্নড়
language-name-ko = কোৰিয়া
language-name-kok = কোঙ্কনি
language-name-kr = কানুৰি
language-name-ks = কাশ্মিৰী
language-name-ku = কুৰ্ডিশ্ব
language-name-kv = ক'মি
language-name-kw = ক'ৰ্নিশ্ব
language-name-ky = কিৰ্ঘিশ্ব
language-name-la = লেটিন
language-name-lb = লাক্সেম্বৰ্গিশ্ব
language-name-lg = গান্ডা
language-name-li = লিম্বুৰ্গান
language-name-lij = লিগুৰীয়
language-name-ln = লিঙ্গালা
language-name-lo = লাওথিয়ান
language-name-lt = লিথুৱানিয়ান
language-name-ltg = লেতগেলিয়ান
language-name-lu = লুবা-কাটাঙ্গা
language-name-lv = লাট্‌ভিয়ান
language-name-mai = মৈথিলী
language-name-meh = দক্ষিণ পশ্চিম ট্‌লাক্সিয়াক' মিক্সটেক
language-name-mg = মালাগাচি
language-name-mh = মাৰ্শ্বালিছ
language-name-mi = মাঅ'ৰি
language-name-mix = মিক্সটেপেক মিক্সটেক
language-name-mk = মেচিডোনীয়
language-name-ml = মলয়ালম
language-name-mn = মঙ্গোলীয়
language-name-mr = মাৰাঠি
language-name-ms = মালয়
language-name-mt = মাল্টিছ
language-name-my = বাৰ্মিছ
language-name-na = নাউৰু
language-name-nb = ম'ৰ্ৱেইয়ান ব'মål
language-name-nd = ডেবেলে, উত্তৰ
language-name-ne = নেপালি
language-name-ng = ড'ঙ্গা
language-name-nl = ডাচ
language-name-nn = ন'ৰ্ৱেইয়ান নিন'ৰ্স্ক
language-name-no = ন'ৰ্ৱেইয়ান
language-name-nr = ডেবেলে, দক্ষিণ
language-name-nso = ছোথো, উত্তৰ
language-name-nv = নাভাজো
language-name-ny = ছিছেৱা
language-name-oc = অ'ক্কিটান
language-name-oj = অ'জিব্ৱা
language-name-om = অ'ৰ'ম'
language-name-or = ওড়িয়া
language-name-os = অ'ছেচিয়ান
language-name-pa = পাঞ্জাবি
language-name-pi = পালি
language-name-pl = প'লিশ্ব
language-name-ps = পাস্টো
language-name-pt = প'ৰ্টুগিছ
language-name-qu = ক্বেচুৱা
language-name-rm = ৰাইটো-ৰোমানিক
language-name-rn = কিৰুণ্ডি
language-name-ro = ৰ'মানিয়ান
language-name-ru = ৰুচীয়
language-name-rw = কিন্যাৰ্ৱাণ্ডা
language-name-sa = সংস্কৃত
language-name-sc = চাৰ্ডিনিয়ান
language-name-sd = সিন্ধি
language-name-se = নৰ্দাৰ্ণ ছামি
language-name-sg = ছাঙ্‌গ্ৰো
language-name-si = সিংহালিছ
language-name-sk = স্লোভাক
language-name-sl = স্লোভেনিয়ান
language-name-sm = ছামোৱান
language-name-sn = ছোৱা
language-name-so = ছোমালি
language-name-son = চনঘাই
language-name-sq = আল্বানিয়ান
language-name-sr = ছাৰ্বিয়ান
language-name-ss = চিস্বাটি
language-name-st = ছোথো, দক্ষিণ
language-name-su = ছুদানিছ
language-name-sv = চুইডিশ্ব
language-name-sw = স্বাহিলি
language-name-ta = তামিল
language-name-te = টেলুগু
language-name-tg = তাজিক
language-name-th = থাই
language-name-ti = টিগ্ৰিন্যা
language-name-tig = টিগ্ৰে
language-name-tk = টুৰ্কমেন
language-name-tl = টাগালগ
language-name-tlh = ক্লিংগন
language-name-tn = ছ্বানা
language-name-to = টঙ্গা
language-name-tr = টুৰ্কিশ্ব
language-name-trs = ট্ৰাইকী
language-name-ts = ছঙ্গা
language-name-tt = টাটাৰ
language-name-tw = ট্বি
language-name-ty = টাহিচিয়ান
language-name-ug = উইঘুৰ
language-name-uk = ইয়ুক্ৰেনিয়ান
language-name-ur = ঊৰ্দু
language-name-uz = উজ্‌বেক
language-name-ve = ভেণ্ডা
language-name-vi = ভইয়েটনামি
language-name-vo = ভলাপük
language-name-wa = ৱালুন
language-name-wen = ছ'ৰ্বিয়ান
language-name-wo = ৱলফ
language-name-xh = জ'ছা
language-name-yi = য়িদ্দিশ্ব
language-name-yo = য়'ৰুবা
language-name-za = জুৱাঙ
language-name-zam = মিয়াৱাট্‌লান জাপ'টেক
language-name-zh = চীনা
language-name-zu = জুলু
