# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Запазени регистрации
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Копиране на адреса
    .accesskey = а
launch-site-url-cmd =
    .label = Отваряне на адреса
    .accesskey = о
copy-username-cmd =
    .label = Копиране на потребителското име
    .accesskey = К
edit-username-cmd =
    .label = Редактиране на потребителско име
    .accesskey = п
copy-password-cmd =
    .label = Копиране на паролата
    .accesskey = К
edit-password-cmd =
    .label = Редактиране на парола
    .accesskey = Р
search-filter =
    .accesskey = Т
    .placeholder = Търсене
column-heading-site =
    .label = Страница
column-heading-username =
    .label = Потребителско име
column-heading-password =
    .label = Парола
column-heading-time-created =
    .label = Първо използване
column-heading-time-last-used =
    .label = Последно използване
column-heading-time-password-changed =
    .label = Последна промяна
column-heading-times-used =
    .label = Брой използвания
remove =
    .label = Премахване
    .accesskey = П
import =
    .label = Внасяне…
    .accesskey = В
close-button =
    .label = Затваряне
    .accesskey = З
show-passwords =
    .label = Показване на пароли
    .accesskey = П
hide-passwords =
    .label = Скриване на паролите
    .accesskey = С
logins-description-all = В компютъра са запазени регистрациите в следните сайтове
logins-description-filtered = Следните регистрации отговарят на търсенето ви:
remove-all =
    .label = Премахване на всички
    .accesskey = в
remove-all-shown =
    .label = Премахване на изброените
    .accesskey = б
remove-all-passwords-prompt = Сигурни ли сте, че желаете да изтриете всички запазени пароли?
remove-all-passwords-title = Изтриване на всички пароли
no-master-password-prompt = Сигурни ли сте, че желаете паролите ви да бъдат показани?
auto-fill-logins-and-passwords =
    .label = Автоматично попълване на регистрации и пароли
