# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title पुस्तकचिनोहरू


#define bookmarks_heading पुस्तकचिनोहरू


#define bookmarks_toolbarfolder पुस्तकचिनोहरू उपकरणपट्टी फोल्डर


#define bookmarks_toolbarfolder_description पुस्तकचिनोहरू उपकरणपट्टीमा देखिनको लागि यो फोल्डरमा तिनीहरु थप्नुहोस


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/firefox/central/


#define getting_started सुरु हुदैँछ


# LOCALIZATION NOTE (firefox_heading):


# Firefox links folder name


#define firefox_heading मोजिल्ला फायरफक्स


# LOCALIZATION NOTE (firefox_help):


# link title for https://www.mozilla.org/en-US/firefox/help/


#define firefox_help सहायता र अभ्यासहरु


# LOCALIZATION NOTE (firefox_customize):


# link title for https://www.mozilla.org/en-US/firefox/customize/


#define firefox_customize फायरफक्स अनुकूलन गर्नुहोस्


# LOCALIZATION NOTE (firefox_community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox_community लागि पर्नुहोस्


# LOCALIZATION NOTE (firefox_about):


# link title for https://www.mozilla.org/en-US/about/


#define firefox_about हाम्रो बारेमा


#unfilter emptyLines
