# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = ការ​ចូល​ដែល​បាន​រក្សាទុក
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-username-cmd =
    .label = ចម្លង​ឈ្មោះអ្នក​ប្រើ
    .accesskey = អ
edit-username-cmd =
    .label = កែ​ឈ្មោះ​អ្នក​ប្រើ
    .accesskey = d
copy-password-cmd =
    .label = ចម្លង​ពាក្យសម្ងាត់
    .accesskey = C
edit-password-cmd =
    .label = កែ​ពាក្យ​សម្ងាត់​
    .accesskey = E
search-filter =
    .accesskey = S
    .placeholder = ស្វែងរក
column-heading-site =
    .label = តំបន់​បណ្ដាញ
column-heading-username =
    .label = ឈ្មោះ​អ្នក​ប្រើ
column-heading-password =
    .label = ពាក្យ​សម្ងាត់
column-heading-time-created =
    .label = បាន​ប្រើ​ប្រាស់​ដំបូង
column-heading-time-last-used =
    .label = បាន​ប្រើ​ចុងក្រោយ
column-heading-time-password-changed =
    .label = បាន​ផ្លាស់​ប្ដូរ​ចុងក្រោយ
column-heading-times-used =
    .label = ពេលវេលា​ដែល​បាន​ប្រើ​ចុងក្រោយ
remove =
    .label = យកចេញ
    .accesskey = R
import =
    .label = នាំចូល...
    .accesskey = ល
close-button =
    .label = បិទ
    .accesskey = C
show-passwords =
    .label = បង្ហាញ​ពាក្យសម្ងាត់
    .accesskey = P
hide-passwords =
    .label = លាក់​ពាក្យសម្ងាត់
    .accesskey = P
logins-description-filtered = ការ​ចូល​ខាងក្រោម​ត្រូវ​គ្នា​នឹង​ការ​ស្វែងរក​របស់​អ្នក៖
remove-all =
    .label = យក​ចេញ​ទាំងអស់
    .accesskey = A
remove-all-passwords-prompt = តើ​អ្នក​ពិតជា​ចង់​យក​ពាក្យសម្ងាត់​ទាំងអស់​ចេញ​ឬ ?
remove-all-passwords-title = យក​ពាក្យសម្ងាត់​ទាំងអស់​ចេញ
no-master-password-prompt = តើ​អ្នក​ពិតជា​ចង់​បង្ហាញ​ពាក្យសម្ងាត់​របស់​អ្នក​ឬ ?
