# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Nana yiyloo { $host }…
network-connection-status-connected = Seŋiima e { $host }…
network-connection-status-sending-request = Nana nelda ɗaɓɓitaande to { $host }…
network-connection-status-transferring-data = Nana waanjitoo keɓe iwde e { $host }…
network-connection-status-connecting = Nana seŋoo e { $host }…
network-connection-status-read = Targol keɓe iwɗe to { $host }
network-connection-status-wrote = Winndii { $host }
network-connection-status-waiting = Nana sabbii { $host }…
network-connection-status-looked-up = Yiyliima { $host }…
network-connection-status-tls-handshake = Ciynugol handshake TLS to { $host }…
network-connection-status-tls-handshake-finished = Jookondiral TLS wonande { $host } timmii…
