# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Magtitiwala ka ba sa "%S" para sa mga sumusunod na layon?
unnamedCA = Certificate Authority (walang pangalan)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Pakipasok ang password na ginamit para ma-encrypt ang certificate backup na ito:
# Page Info
pageInfo_NoEncryption = Hindi Encrypted ang Koneksyon
pageInfo_Privacy_None1 = The web site %S does not support encryption for the page you are viewing.
pageInfo_Privacy_None2 = Ang impormasyon na ipinadala sa Internet nang walang encryption ay makikita ng ibang tao habang ito ay nasa transit.
pageInfo_Privacy_None4 = Ang pahinang tinitingnan mo ay hindi naka-encrypt bago mapadala sa Internet.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Connection Encrypted (%1$S, %2$S bit keys, %3$S)
pageInfo_BrokenEncryption = Broken Encryption (%1$S, %2$S bit keys, %3$S)
pageInfo_Privacy_Encrypted1 = Ang pahina na iyong tinitingnan ay naka-encrypt bago na ipinadala sa Internet.
pageInfo_Privacy_Encrypted2 = Sa pamamagitan ng encryption, pinapahirapan ang mga di-kanais-nais na tao mula sa pagsilip ng impormasyong napapadala sa iba't-ibang mga computer. Dahil dito, mababa ang tsansang may nakabasa sa pahinang ito habang pinadala ito sa network.
pageInfo_MixedContent = Bahaging Nakakripta ang Koneksiyon
pageInfo_MixedContent2 = Mga bahagi ng pahina na iyong tinitingnan ay hindi naka-encrypt bago na ipinadala sa Internet.
pageInfo_WeakCipher = Ang koneksyon mo sa website na ito ay gumagamit ng mahinang encryption at hindi pribado. Maaaring mabasa ng ibang tao ang impormasyon mo o kaya'y mabago ang asal ng website.
pageInfo_CertificateTransparency_Compliant = Ang website na ito ay umaayon sa patakaran ng Certificate Transparency.
# Token Manager
password_not_set = (not set)
