# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title ที่คั่นหน้า


#define bookmarks_heading ที่คั่นหน้า


#define bookmarks_toolbarfolder โฟลเดอร์แถบเครื่องมือที่คั่นหน้า


#define bookmarks_toolbarfolder_description เพิ่มที่คั่นหน้าลงในโฟลเดอร์นี้เพื่อให้แสดงในแถบเครื่องมือที่คั่นหน้า


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/firefox/central/


#define getting_started เริ่มต้นใช้งาน


# LOCALIZATION NOTE (firefox_heading):


# Firefox links folder name


#define firefox_heading Mozilla Firefox


# LOCALIZATION NOTE (firefox_help):


# link title for https://www.mozilla.org/en-US/firefox/help/


#define firefox_help ความช่วยเหลือและวิธีใช้


# LOCALIZATION NOTE (firefox_customize):


# link title for https://www.mozilla.org/en-US/firefox/customize/


#define firefox_customize ปรับแต่ง Firefox


# LOCALIZATION NOTE (firefox_community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox_community เข้ามามีส่วนร่วม


# LOCALIZATION NOTE (firefox_about):


# link title for https://www.mozilla.org/en-US/about/


#define firefox_about เกี่ยวกับเรา


#unfilter emptyLines
