# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=Suiteáil $ProductShortName$
Welcome_MessageWelcome=Fáilte chuig %s
Welcome_Message0=Tá tú ar tí %s $Version$ a shuiteáil.
Welcome_Message1=Moltar go láidir duit scoir de gach clár Windows sula gcuirfidh tú an Suiteálaí seo ar siúl.
Welcome_Message2=Gliogáil 'Cealaigh' chun scoir den tsuiteáil, agus dún ansin a bhfuil de chláracha ar siúl agat anois. Gliogáil 'Ar aghaidh' chun leanúint den tsuiteáil.
Welcome_Message3=Gliogáil 'Ar aghaidh' chun leanúint de %s $Version$ a shuiteáil.

License_Title=Comhaontú um an gCeadúnas Earra Bhoig
License_SubTitle=Téarmaí agus coinníollacha úsáide an bhogearra seo.
License_Message0=Léigh an comhaontú um cheadúnas earra bhoig seo a leanas, le do thoil. Úsáid an barra scrollála chun an chuid eile den chomhaontú seo a léamh.
License_Accept=&Táim toilteanach glacadh le coinníollacha an Chomhaontú um Cheadúnas.
License_Decline=&Nílim toilteanach glacadh le coinníollacha an Chomhaontú um Cheadúnas.

Type_Title=Modh Suiteála
Type_SubTitle=Roghanna suiteála an phacáiste seo.
Type_Message0=Roghnaigh an cineál suiteála is fearr leat, agus gliogáil 'Ar aghaidh' ina dhiaidh sin.

Standard_Short=Gnáth&shuiteáil
Standard_Long=Déanfar Thunderbird a shuiteáil leis na gnáthroghanna.

Custom_Short=S&ainshuiteáil
Custom_Long=Is féidir leat roghanna ar leith a shannadh lena suiteáil. Níl an rogha seo molta ach amháin d'úsaideoirí a bhfuil taithí mhaith acu ar an ábhar.

Select_Title=Roghnú Comhpháirteanna
Select_SubTitle=Comhpháirteanna breise a chuireann le cumas $ProductShortName$.
Select_Message0=Roghnaigh na comhpháirteanna breise is mian leat a shuiteáil, agus gliogáil 'Ar aghaidh' ina dhiaidh sin.

Path_Title=Fillteán Suiteála
Path_SubTitle=An áit ina shuiteálfar $ProductShortName$.
Path_Message0=Suiteálfar $ProductShortName$ san fhillteán thíos:

Integration_Title=Socrú Aicearraí
Integration_SubTitle=Cruthaigh Deilbhíní
Integration_Message0=Cruthaigh deilbhíní i gcomhair $ProductShortName$:

Integration_Desktop=Ar an Deasc agamsa
Integration_StartMenu=San fhillteán 'An Roghchlár Tosaigh/Ríomhchláir' (Start Menu Programs)
Integration_QuickLaunch=I mo Bharra Mearlainseála

SelectFolder_Title=Suiteáil $ProductShortName$ - Roghnaigh Fillteán Ríomhchlár
SelectFolder_Message0=Cuirfidh an Suiteálaí deilbhíní isteach san Fhillteán Ríomhchlár a luaitear thíos. Is féidir leat fillteán nua a chruthú, nó ceann a roghnú ar liosta na bhFillteán Reatha. Gliogáil 'Ar aghaidh' chun leanúint ar aghaidh.

Advanced_Title=Suiteáil $ProductShortName$ - Socruithe Casta
Advanced_Message0=I gcás go n-éilíonn do nasc Idirlín seachfhreastalaí, iontráil ainm do fhreastalaí agus eolas poirt anseo. Muna n-éilíonn, fág bán na réimsí sin.

Install_Title=Achoimre
Install_SubTitle=Réidh chun $ProductShortName$ a shuiteáil.
Install_MessageInstall=Déanfaidh an Suiteálaí na comhpháirteanna seo a leanas a shuiteáil:
Install_MessageDownload=Déanfaidh an Suiteálaí na comhpháirteanna seo a leanas a luchtú agus a shuiteáil:
Install_Message0=Gliogáil 'Ar aghaidh' chun leanúint ar aghaidh.

Downloading_Title=Íosluchtú
Downloading_SubTitle=Tá na comhpháirteanna a theastaíonn á n-íosluchtú...
Downloading_Blurb=Tá comhaid suiteála $ProductShortName$ á n-íosluchtú ag an Suiteálaí.
Downloading_FileName=Íosluchtú ar siúl:
Downloading_Time=Aga fanta:

Installing_Title=Á Shuiteáil
Installing_SubTitle=$ProductShortName$ á shuiteáil...
Installing_Blurb=Tá comhaid an fheidhmchláir á shuiteáil ag an Suiteálaí.
Installing_Status=Comhad á ullmhú:
Installing_Component=Á shuiteáil anois:

Success_Title=Suiteáil Críochnaithe
Success_Header=Suiteáil Críochnaithe
Success_Message0=D'éirigh le suiteáil %s $Version$.
Success_Message1= Gliogáil 'Críochnaigh' chun an tsuiteáil a chríochnú.
Success_Launch=Tosaigh %s $Version$ anois.

Check_Message=Íosuchtaíodh $ProductShortName$ mar ba chóir. Is gá $ProductShortName$ a dhúnadh anois chun leanúint den suiteáil. Gliogáil 'OK' chun scoir go huathoibríoch de $ProductShortName$ agus luí isteach ar a shuiteáil.
Check_FullMessage=Is gá $ProductNameInternal$ a dhúnadh chun leanúint den suiteáil.  Gliogáil 'OK' chun scoir go huathoibríoch de $ProductNameInternal$ agus luí isteach ar a shuiteáil.
Check_Wait=$ProductNameInternal$ á dhúnadh anois. Bíodh foighne agat...

Component_XPCOM=COM Ilárdán
Component_Mail=$ProductName$
Component_Offline=Tacaíocht d'Oibriú As Líne
Component_Offline_Long=Cuireann seo tacaíocht d'oibriú as líne le Ríomhphost $ProductName$.
Component_RSS=Tacaíocht RSS
Component_RSS_Long=Cuireann seo tacaíocht do RSS le $ProductName$.
Component_QFA=Gníomhaire Aiseolais um Cháilíocht
Component_QFA_Long=Le haghaidh tuairiscí maidir le tuairteanna $ProductShortName$
