# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=Instal·lació del $ProductName$
Welcome_MessageWelcome=Salutacions!
Welcome_Message0=Ara instal·lareu el %s.
Welcome_Message1=És molt recomanable que sortiu de tots els programes de Windows abans d'executar el programa d'instal·lació.
Welcome_Message2=Feu un clic a Cancel·la per a sortir de la instal·lació i llavors tanqueu tots aquells programes que podeu estar executant. Feu un clic a Endavant per a continuar amb el programa d'instal·lació.
Welcome_Message3=Feu un clic a Endavant per a continuar instal·lant el %s.

License_Title=Acord de llicència del programari
License_SubTitle=Termes i condicions per a utilitzar aquest programari.
License_Message0=Si us plau, llegiu el següent acord de llicència. Utilitzeu la barra de desplaçament per a visualitzar la resta d'aquest acord.
License_Accept=&Accepto els termes de l'acord de llicència.
License_Decline=&NO accepto els termes de l'acord de llicència.

Type_Title=Tipus d'instal·lació
Type_SubTitle=Trieu el tipus d'instal·lació.
Type_Message0=Trieu el tipus d'instal·lació que preferiu, llavors feu un clic a Endavant.

Standard_Short=E&stàndard
Standard_Long=El Thunderbird s'instal·larà amb les opcions més comunes.

Custom_Short=&Personalitzada
Custom_Long=Podeu triar les opcions individuals que s'instal·laran. Recomanant per als usuaris avançats.

Select_Title=Selecció dels components
Select_SubTitle=Components addicionals per al $ProductName$.
Select_Message0=Trieu els components addicionals que voleu instal·lar, llavors feu un clic a Endavant.

Path_Title=Carpeta d'instal·lació
Path_SubTitle=On s'instal·larà el $ProductName$.
Path_Message0=El $ProductName$ s'instal·larà en la següent carpeta:

Integration_Title=Definició de les dreceres
Integration_SubTitle=Crea les icones del programa
Integration_Message0=Crea les icones per al $ProductShortName$:

Integration_Desktop=Al meu escriptori
Integration_StartMenu=A la carpeta de programes del menú Inici
Integration_QuickLaunch=A la barra d'execució ràpida

SelectFolder_Title=Selecció de la carpeta del programa
SelectFolder_Message0=La instal·lació afegirà icones de programa a la carpeta de programa que se senyala més avall. Podeu escriure el nom d'una nova carpeta o seleccionar-ne una de la llista de carpetes existents. Feu un clic a Endavant per a continuar.

Advanced_Title=Paràmetres avançats
Advanced_Message0=Si la vostra connexió a Internet necessita un servidor intermediari, introduïu el nom del vostre servidor i la informació del port. Si no, deixeu els camps en blanc.

Install_Title=Resum
Install_SubTitle=Preparat per a instal·lar el $ProductName$.
Install_MessageInstall=S'instal·laran els següents components:
Install_MessageDownload=Es baixaran i instal·laran els següents components:
Install_Message0=Feu un clic a Endavant per a continuar.

Downloading_Title=Baixada
Downloading_SubTitle=S'estan baixant els components necessaris...
Downloading_Blurb=S'estan baixant els fitxers necessaris per a instal·lar el $ProductName$.
Downloading_FileName=S'està baixant actualment:
Downloading_Time=Temps restant:

Installing_Title=Instal·lació
Installing_SubTitle=S'està instal·lant el $ProductName$...
Installing_Blurb=S'estan instal·lant els fitxers de l'aplicació. 
Installing_Status=S'està preparant el fitxer:
Installing_Component=S'està instal·lant actualment:

Success_Title=Fi de la instal·lació
Success_Header=S'ha acabat la instal·lació
Success_Message0=El %s s'ha instal·lat amb èxit.
Success_Message1=Feu un clic a Finalitza per a sortir de l'instal·lador. 
Success_Launch=Executa el %s ara.

Check_Message=La baixada del $ProductName$ ha tingut èxit. No obstant, ha de tancar-se el $ProductNameInternal$ per a procedir amb la instal·lació. Feu un clic a D'acord per a sortir del $ProductNameInternal$ automàticament i començar la instal·lació.
Check_FullMessage=Ha de tancar-se el $ProductNameInternal$ per a procedir amb la instal·lació. Feu un clic a D'acord per a sortir del $ProductNameInternal$ automàticament i començar la instal·lació.
Check_Wait=S'està tancant el $ProductNameInternal$. Si us plau, espereu...

Component_XPCOM=COM interplataforma
Component_Mail=$ProductName$
Component_Offline=Suport fora de línia
Component_Offline_Long=Afegeix suport fora de línia al $ProductName$.
Component_RSS=Suport RSS
Component_RSS_Long=Afegeix suport RSS al $ProductName$.
Component_QFA=Agent de la gestió de qualitat
Component_QFA_Long=Permet informar de les errades del $ProductName$
