# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Anadi n usenneftaɣ { $host }…
network-connection-status-connected = iqqen ɣer { $host }…
network-connection-status-sending-request = Tuzzna n usuter ɣer { $host }…
network-connection-status-transferring-data = Armas n isefka seg { $host }…
network-connection-status-connecting = Tuqqna ɣer { $host }…
network-connection-status-tls-handshake = Aselkem n usenker n tuqqna TLS akked { $host }…
network-connection-status-tls-handshake-finished = Asenker n tuqqna TLS ifuk akked { $host }…
