# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Ñongatu
dialogTitleAddBookmark = Techaukaha pyahu
dialogTitleAddMulti = Techaukaha pyahu
dialogTitleEdit = “%S” mba’eteéva
dialogTitleAddNewBookmark2 = Embojuaju techaukaha
dialogTitleEditBookmark = Embosako’i “%S”
dialogTitleEditBookmark2 = Embosako’i techaukaha
dialogTitleAddBookmarkFolder = Embojuaju marandurenda rechaukaha
dialogTitleEditBookmarkFolder = Embosako’i marandurenda rechaukaha
bookmarkAllTabsDefault = [Ñongatuha réra]
newFolderDefault = Ñongatuha pyahu
newBookmarkDefault = Techaukaha pyahu
