# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Снимени најави
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Копирај адреса
    .accesskey = к
launch-site-url-cmd =
    .label = Посети адреса
    .accesskey = С
copy-username-cmd =
    .label = Копирај корисничко име
    .accesskey = К
edit-username-cmd =
    .label = Уреди корисничко име
    .accesskey = к
copy-password-cmd =
    .label = Копирај лозинка
    .accesskey = К
edit-password-cmd =
    .label = Уреди лозинка
    .accesskey = Л
search-filter =
    .accesskey = Б
    .placeholder = Барај
column-heading-site =
    .label = Место
column-heading-username =
    .label = Корисничко име
column-heading-password =
    .label = Лозинка
column-heading-time-created =
    .label = Првпат користена
column-heading-time-last-used =
    .label = Последен пат користена
column-heading-time-password-changed =
    .label = Последна измена
column-heading-times-used =
    .label = Број на користења
remove =
    .label = Отстрани
    .accesskey = р
import =
    .label = Увези…
    .accesskey = У
close-button =
    .label = Затвори
    .accesskey = З
show-passwords =
    .label = Покажи ги лозинките
    .accesskey = л
hide-passwords =
    .label = Скриј ги лозинките
    .accesskey = С
logins-description-all = Најави за следниве мрежни места се снимени на вашиот компјутер
logins-description-filtered = Следните најави се совпаѓаат со вашето пребарување:
remove-all =
    .label = Отстрани ги сите
    .accesskey = О
remove-all-shown =
    .label = Отстрани ги сите прикажани
    .accesskey = О
remove-all-passwords-prompt = Сигурно сакате да ги отстраните сите лозинки?
remove-all-passwords-title = Отстранување на сите лозинки
no-master-password-prompt = Сигурно сакате да ги покажете вашите лозинки?
