# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language-name-aa = ᱟᱹᱯᱷᱟᱹᱨ
language-name-ab = ᱟᱵᱠᱷᱟᱡᱤᱭᱟᱹᱱ
language-name-ach = ᱟᱹᱠᱷᱚᱞᱤ
language-name-ae = ᱟᱹᱣᱮᱥᱛᱟᱱ
language-name-af = ᱟᱹᱯᱷᱨᱤᱠᱟᱱᱥ
language-name-ak = ᱟᱠᱟᱱ
language-name-am = ᱟᱢᱦᱟᱨᱤᱠ
language-name-an = ᱟᱨᱟᱜᱚᱱᱤᱡᱽ
language-name-ar = ᱟᱹᱨᱵᱤ
language-name-as = ᱟᱥᱟᱢᱤ
language-name-ast = ᱮᱥᱴᱩᱨᱤᱭᱟᱹᱱ
language-name-av = ᱟᱣᱟᱨᱤᱠ
language-name-ay = ᱮᱢᱟᱨᱟ
language-name-az = ᱟᱹᱡᱟᱹᱨᱵᱮᱡᱟᱱᱤ
language-name-ba = ᱵᱟᱥᱠᱟᱹᱨ
language-name-be = ᱵᱮᱞᱟᱨᱩᱥᱤ
language-name-bg = ᱵᱩᱞᱜᱟᱹᱨᱤᱭᱟᱹᱱ
language-name-bh = ᱵᱤᱦᱟᱨᱤ
language-name-bi = ᱵᱤᱥᱢᱟᱞᱟ
language-name-bm = ᱵᱟᱹᱢᱵᱟᱨᱤ
language-name-bn = ᱵᱮᱝᱜᱚᱞᱤ
language-name-bo = ᱛᱤᱵᱚᱛ
language-name-br = ᱵᱽᱨᱤᱴᱮᱱ
language-name-bs = ᱵᱚᱥᱱᱤᱭᱟᱭᱤ
language-name-ca = ᱠᱮᱴᱞᱟᱱ
language-name-cak = ᱠᱟᱠᱪᱤᱠᱮᱞ
language-name-ce = ᱪᱷᱮᱪᱮ
language-name-ch = ᱪᱚᱢᱚᱨᱚ
language-name-co = ᱠᱚᱨᱥᱤᱠᱟᱱ
language-name-cr = ᱠᱨᱤ
language-name-crh = ᱠᱨᱤᱢᱤᱭᱟᱹᱱ ᱴᱟᱴᱟᱨ
language-name-cs = ᱪᱮᱠ
language-name-csb = ᱠᱟᱥᱩᱵᱤᱭᱟᱹᱱ
language-name-cu = ᱪᱟᱹᱨᱪ ᱥᱞᱟᱣᱤᱠ
language-name-cv = ᱪᱩᱣᱟᱥ
language-name-cy = ᱣᱮᱞᱥ
language-name-da = ᱰᱮᱱᱤᱥ
language-name-de = ᱡᱟᱹᱨᱢᱟᱹᱱ
language-name-dsb = ᱞᱚᱣᱟᱹᱨ ᱥᱚᱨᱵᱤᱭᱟᱹᱱ
language-name-dv = ᱰᱤᱣᱮᱦᱤ
language-name-dz = ᱡᱚᱸᱠᱷᱟ
language-name-ee = ᱤᱣᱮ
language-name-el = ᱜᱽᱨᱤᱠ
language-name-en = ᱤᱝᱨᱟᱡᱤ
language-name-eo = ᱮᱥᱯᱟᱨᱮᱱᱴᱚ
language-name-es = ᱥᱯᱮᱱᱤᱥ
language-name-et = ᱮᱥᱴᱚᱱᱤᱭᱟᱹᱱ
language-name-eu = ᱵᱟᱥᱠᱭᱩ
language-name-fa = ᱵᱷᱟᱹᱨᱥᱚᱱ
language-name-ff = ᱯᱷᱩᱞᱟᱦ
language-name-fi = ᱯᱷᱤᱱᱤᱥ
language-name-fj = ᱯᱷᱤᱡᱤᱭᱟᱹᱱ
language-name-fo = ᱯᱷᱟᱨᱚᱤᱥ
language-name-fr = ᱯᱷᱨᱮᱧᱪ
language-name-fur = ᱯᱷᱤᱡᱤᱭᱟᱹᱱ
language-name-fy = ᱯᱷᱤᱡᱤᱭᱟᱹᱱ
language-name-ga = ᱟᱭᱨᱤᱥ
language-name-gd = ᱥᱠᱚᱴᱤᱥ ᱜᱟᱞᱤᱠ
language-name-gl = ᱜᱮᱞᱤᱥᱤᱭᱟᱱ
language-name-gn = ᱜᱩᱟᱨᱟᱱᱤ
language-name-gu = ᱜᱩᱡᱨᱟᱴᱤ
language-name-gv = ᱢᱮᱸᱝᱠᱥ
language-name-ha = ᱦᱟᱣᱥᱟ
language-name-haw = ᱦᱟᱹᱭᱛᱤᱭᱟᱹᱱ
language-name-he = ᱦᱤᱵᱽᱨᱩ
language-name-hi = ᱦᱤᱱᱫᱤ
language-name-hil = ᱦᱤᱞᱤᱜᱟᱭᱱᱚᱱ
language-name-ho = ᱦᱤᱨᱤ ᱢᱚᱴᱩ
language-name-hr = ᱠᱨᱚᱮᱥᱤᱭᱟᱱ
language-name-hsb = ᱟᱹᱯᱟᱹᱨ ᱥᱚᱨᱵᱤᱭᱟᱹᱱ
language-name-ht = ᱦᱟᱭᱴᱟᱱ
language-name-hu = ᱦᱩᱝᱜᱟᱨᱤᱭᱟᱹᱱ
language-name-hy = ᱟᱨᱢᱮᱱᱤᱭᱟᱹᱱ
language-name-hz = ᱦᱮᱨᱮᱨᱚ
language-name-ia = ᱤᱱᱴᱟᱹᱨᱞᱤᱝᱜᱩᱟ
language-name-id = ᱤᱱᱰᱚᱱᱮᱥᱤᱭᱚᱱ
language-name-ie = ᱤᱱᱴᱟᱹᱨᱞᱤᱝᱜᱩᱣᱮ
language-name-ig = ᱤᱜᱽᱵᱚ
language-name-ii = ᱥᱩᱪᱩᱣᱟᱱ Yi
language-name-ik = ᱤᱱᱩᱯᱤᱭᱟᱠ
language-name-io = ᱤᱰᱳ
language-name-is = ᱟᱭᱥᱞᱮᱱᱰᱤᱠ
language-name-it = ᱤᱴᱟᱞᱤᱭᱟᱹᱱ
language-name-iu = ᱤᱱᱩᱠᱴᱤᱴᱩᱴ
language-name-ja = ᱡᱟᱯᱟᱱᱤᱡᱽ
language-name-jv = ᱡᱟᱣᱟᱱᱤᱡᱽ
language-name-ka = ᱡᱤᱭᱚᱨᱡᱤᱭᱟᱹᱱ
language-name-kab = ᱠᱟᱵᱮᱭᱞ
language-name-kg = ᱠᱚᱝᱜᱚ
language-name-ki = ᱠᱤᱠᱩᱭᱩ
language-name-kj = ᱠᱩᱭᱟᱱᱭᱟᱢᱟ
language-name-kk = ᱠᱟᱡᱟᱠᱷ
language-name-kl = ᱜᱽᱨᱤᱱᱞᱮᱸᱱᱰᱤᱠ
language-name-km = ᱠᱷᱟᱹᱢᱮᱨ
language-name-kn = ᱠᱟᱱᱟᱰᱟ
language-name-ko = ᱠᱳᱨᱤᱭᱟᱹᱱ
language-name-kok = ᱠᱚᱱᱠᱟᱱᱤ
language-name-kr = ᱠᱟᱱᱩᱨᱤ
language-name-ks = ᱠᱟᱥᱢᱤᱨᱤ
language-name-ku = ᱠᱩᱨᱫᱤᱥ
language-name-kv = ᱠᱚᱢᱤ
language-name-kw = ᱠᱚᱨᱱᱤᱥ
language-name-ky = ᱠᱤᱨᱜᱷᱤᱡᱽ
language-name-la = ᱞᱮᱴᱤᱱ
language-name-lb = ᱞᱩᱠᱥᱮᱢᱵᱚᱨᱜᱽ
language-name-lg = ᱜᱟᱱᱰᱟ
language-name-li = ᱞᱤᱢᱵᱩᱨᱜᱟᱱ
language-name-lij = ᱞᱤᱜᱩᱨᱤᱭᱟᱹᱱ
language-name-ln = ᱞᱤᱝᱜᱟᱞᱟ
language-name-lo = ᱞᱟᱣ
language-name-lt = ᱞᱤᱛᱷᱩᱣᱟᱱᱤᱭᱟᱹᱱ
language-name-lu = लुबा-कटांगा
language-name-lv = लाटबियान
language-name-mg = मालागासी
language-name-mh = मार्शलीज
language-name-mi = मावरी
language-name-mk = मेसिडोनियन
language-name-ml = मालयालोम
language-name-mn = मंगोलियान
language-name-mr = माराठी
language-name-ms = मालाय
language-name-mt = माल्टीज
language-name-my = बार्मिज
language-name-na = नौरू
language-name-nb = नोर्वेजियान बोक्माल
language-name-nd = न्डेबेले, उत्तरी
language-name-ne = नेपाली
language-name-ng = न्डोंगा
language-name-nl = डच
language-name-nn = नोर्वेजियान नैनोर्स्क
language-name-no = नार्वेजियन
language-name-nr = न्डेबेले, दोखिन
language-name-nso = सोथो, उत्तरी
language-name-nv = न्वाजो
language-name-ny = चिचेवा
language-name-oc = ओकितान
language-name-oj = ओजिब्वा
language-name-om = ओरोमो
language-name-os = ओस्सेटियान
language-name-pa = पंजाबी
language-name-pi = पाली
language-name-pl = पोलिश
language-name-ps = पश्तो
language-name-pt = पुर्तगाली
language-name-qu = क्वेचुआ
language-name-rm = राएटो-रोमानिक
language-name-rn = किरूंडी
language-name-ro = रोमानियाई
language-name-ru = रूस रेयाक्
language-name-rw = किनयारवांडा
language-name-sa = संस्कृत
language-name-sc = सारडिनयन
language-name-sd = सिन्धी
language-name-se = उत्तरी सामी
language-name-sg = सांगो
language-name-si = सिंहाला
language-name-sk = स्लोवाक
language-name-sl = स्लोवेनियान
language-name-sm = सामोवान
language-name-sn = शोना
language-name-so = सोमाली
language-name-son = सोनघाय
language-name-sq = अल्बेनियान
language-name-sr = सर्बियान
language-name-ss = सिसवाती
language-name-st = सोथो, दोखिन
language-name-su = सुडानीज
language-name-sv = स्वीडिश
language-name-sw = स्वाहिली
language-name-ta = तामिल
language-name-te = तेलुगु
language-name-tg = ताजिक
language-name-th = थाई
language-name-ti = टिग्रिंया
language-name-tig = टिग्रे
language-name-tk = तुर्कमेन
language-name-tl = टैगालॉग
language-name-tlh = क्लिंगोन
language-name-tn = ट्स्वाना
language-name-to = टोंगा
language-name-tr = तुर्किश
language-name-ts = त्सोन्गा
language-name-tt = तातार
language-name-tw = त्वी
language-name-ty = ताहिती
language-name-ug = विघुर
language-name-uk = यूक्रेनिया रेयाक्
language-name-ur = उर्दु
language-name-uz = उजबेक
language-name-ve = वेंडा
language-name-vi = वियतनामी
language-name-vo = वोलापुक
language-name-wa = वैलून
language-name-wen = सोर्बियाई
language-name-wo = वोलोफ
language-name-xh = खोसा
language-name-yi = यिड्डिश
language-name-yo = योरूबा
language-name-za = झुआंग
language-name-zh = चीनी
language-name-zu = जुलू
