# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language-name-aa = ᱟᱹᱯᱷᱟᱹᱨ
language-name-ab = ᱟᱵᱠᱷᱟᱡᱤᱭᱟᱹᱱ
language-name-ach = ᱟᱹᱠᱷᱚᱞᱤ
language-name-ae = ᱟᱹᱣᱮᱥᱛᱟᱱ
language-name-af = ᱟᱹᱯᱷᱨᱤᱠᱟᱱᱥ
language-name-ak = ᱟᱠᱟᱱ
language-name-am = ᱟᱢᱦᱟᱨᱤᱠ
language-name-an = ᱟᱨᱟᱜᱚᱱᱤᱡᱽ
language-name-ar = ᱟᱹᱨᱵᱤ
language-name-as = ᱟᱥᱟᱢᱤ
language-name-ast = ᱮᱥᱴᱩᱨᱤᱭᱟᱹᱱ
language-name-av = ᱟᱣᱟᱨᱤᱠ
language-name-ay = ᱮᱢᱟᱨᱟ
language-name-az = ᱟᱹᱡᱟᱹᱨᱵᱮᱡᱟᱱᱤ
language-name-ba = ᱵᱟᱥᱠᱟᱹᱨ
language-name-be = ᱵᱮᱞᱟᱨᱩᱥᱤ
language-name-bg = ᱵᱩᱞᱜᱟᱹᱨᱤᱭᱟᱹᱱ
language-name-bh = ᱵᱤᱦᱟᱨᱤ
language-name-bi = ᱵᱤᱥᱢᱟᱞᱟ
language-name-bm = ᱵᱟᱹᱢᱵᱟᱨᱤ
language-name-bn = ᱵᱮᱝᱜᱚᱞᱤ
language-name-bo = ᱛᱤᱵᱚᱛ
language-name-br = ᱵᱽᱨᱤᱴᱮᱱ
language-name-bs = ᱵᱚᱥᱱᱤᱭᱟᱭᱤ
language-name-ca = ᱠᱮᱴᱞᱟᱱ
language-name-ce = छेचेन
language-name-ch = चामोरो
language-name-co = कोर्सिकान
language-name-cr = क्री
language-name-cs = चेक
language-name-csb = कासुबियान
language-name-cu = चर्च स्लाविक
language-name-cv = चुवाश
language-name-cy = वेल्श
language-name-da = डैनिश
language-name-de = जर्मन
language-name-dsb = लातार सोरबियान
language-name-dv = डिवेही
language-name-dz = जोंखा
language-name-ee = इवे
language-name-el = ग्रीक
language-name-en = अंग्रेजी
language-name-eo = एस्पेरांटो
language-name-es = स्पेनी
language-name-et = इस्टोनियन
language-name-eu = बास्क
language-name-fa = फारसी
language-name-ff = फुलाह
language-name-fi = फिनिश
language-name-fj = फिजियन
language-name-fo = फेरोयसी
language-name-fr = फ्रेंच
language-name-fur = फ्रिलियन
language-name-fy = फ्रिसियन
language-name-ga = आइरिश
language-name-gd = एसकोटिस गायलिक
language-name-gl = गेलिसियन
language-name-gn = गुआरानी
language-name-gu = गुजराती
language-name-gv = मैंक्स
language-name-ha = हौसा
language-name-haw = हावांञ
language-name-he = हिब्रू
language-name-hi = हिन्दी
language-name-hil = हिलिगायनोल
language-name-ho = हिरी मोटू
language-name-hr = क्रोएशियाई
language-name-hsb = चेतान सॉर्बियाई
language-name-ht = हैतियन
language-name-hu = हंगेरियाई
language-name-hy = आर्मेनियाई
language-name-hz = हेरेरो
language-name-ia = अंतरभाषायी
language-name-id = इंडोनेशियन
language-name-ie = इंटारलिंग
language-name-ig = इग्बो
language-name-ii = सिचुआन Yi
language-name-ik = इनउपियाक
language-name-io = इडो
language-name-is = आइसलैंडिक
language-name-it = इतालवी
language-name-iu = इनुकट्टीटुट
language-name-ja = जापानी
language-name-jv = जावानीस
language-name-ka = जोर्जियाई
language-name-kg = कोंगो
language-name-ki = किकुयू
language-name-kj = कुयानयामा
language-name-kk = काजाख
language-name-kl = ग्रीनलैंडिक
language-name-km = ख्मेर
language-name-kn = कन्नड़
language-name-ko = कोरिया रेयाक्
language-name-kok = कोंकणी
language-name-kr = कानुरी
language-name-ks = काश्मीरी
language-name-ku = कुर्दिश
language-name-kv = कोमी
language-name-kw = कोर्निश
language-name-ky = किरगिज
language-name-la = लेटिन
language-name-lb = लक्जमबुर्गीश
language-name-lg = गैंडा
language-name-li = लिंबुर्गान
language-name-ln = लिंगाला
language-name-lo = लाव
language-name-lt = लिथुवानियाई
language-name-lu = लुबा-कटांगा
language-name-lv = लाटबियान
language-name-mg = मालागासी
language-name-mh = मार्शलीज
language-name-mi = मावरी
language-name-mk = मेसिडोनियन
language-name-ml = मालयालोम
language-name-mn = मंगोलियान
language-name-mr = माराठी
language-name-ms = मालाय
language-name-mt = माल्टीज
language-name-my = बार्मिज
language-name-na = नौरू
language-name-nb = नोर्वेजियान बोक्माल
language-name-nd = न्डेबेले, उत्तरी
language-name-ne = नेपाली
language-name-ng = न्डोंगा
language-name-nl = डच
language-name-nn = नोर्वेजियान नैनोर्स्क
language-name-no = नार्वेजियन
language-name-nr = न्डेबेले, दोखिन
language-name-nso = सोथो, उत्तरी
language-name-nv = न्वाजो
language-name-ny = चिचेवा
language-name-oc = ओकितान
language-name-oj = ओजिब्वा
language-name-om = ओरोमो
language-name-os = ओस्सेटियान
language-name-pa = पंजाबी
language-name-pi = पाली
language-name-pl = पोलिश
language-name-ps = पश्तो
language-name-pt = पुर्तगाली
language-name-qu = क्वेचुआ
language-name-rm = राएटो-रोमानिक
language-name-rn = किरूंडी
language-name-ro = रोमानियाई
language-name-ru = रूस रेयाक्
language-name-rw = किनयारवांडा
language-name-sa = संस्कृत
language-name-sc = सारडिनयन
language-name-sd = सिन्धी
language-name-se = उत्तरी सामी
language-name-sg = सांगो
language-name-si = सिंहाला
language-name-sk = स्लोवाक
language-name-sl = स्लोवेनियान
language-name-sm = सामोवान
language-name-sn = शोना
language-name-so = सोमाली
language-name-son = सोनघाय
language-name-sq = अल्बेनियान
language-name-sr = सर्बियान
language-name-ss = सिसवाती
language-name-st = सोथो, दोखिन
language-name-su = सुडानीज
language-name-sv = स्वीडिश
language-name-sw = स्वाहिली
language-name-ta = तामिल
language-name-te = तेलुगु
language-name-tg = ताजिक
language-name-th = थाई
language-name-ti = टिग्रिंया
language-name-tig = टिग्रे
language-name-tk = तुर्कमेन
language-name-tl = टैगालॉग
language-name-tlh = क्लिंगोन
language-name-tn = ट्स्वाना
language-name-to = टोंगा
language-name-tr = तुर्किश
language-name-ts = त्सोन्गा
language-name-tt = तातार
language-name-tw = त्वी
language-name-ty = ताहिती
language-name-ug = विघुर
language-name-uk = यूक्रेनिया रेयाक्
language-name-ur = उर्दु
language-name-uz = उजबेक
language-name-ve = वेंडा
language-name-vi = वियतनामी
language-name-vo = वोलापुक
language-name-wa = वैलून
language-name-wen = सोर्बियाई
language-name-wo = वोलोफ
language-name-xh = खोसा
language-name-yi = यिड्डिश
language-name-yo = योरूबा
language-name-za = झुआंग
language-name-zh = चीनी
language-name-zu = जुलू
