# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Notice: If you're updating this list, you should also
###         update the list in mozIntl.js.

region-name-ad = ᱮᱱᱰᱚᱨᱟ
region-name-ae = ᱭᱩᱱᱟᱭᱴᱮᱰ ᱟᱹᱨᱟᱹᱵ ᱮᱢᱤᱨᱮᱴᱥ
region-name-af = ᱟᱹᱯᱷᱜᱟᱱᱤᱥᱛᱟᱱ
region-name-ag = ᱮᱱᱴᱤᱜᱩᱟ ᱟᱨ ᱵᱟᱨᱵᱩᱰᱟ
region-name-ai = ᱟᱹᱱᱜᱩᱭᱤᱞᱟ
region-name-al = ᱟᱹᱞᱵᱮᱱᱤᱭᱟ
region-name-am = ᱟᱨᱢᱮᱱᱤᱭᱟ
region-name-ao = ᱟᱹᱝᱜᱚᱞᱟ
region-name-aq = ᱟᱹᱱᱴᱟᱨᱠᱴᱤᱠᱟ
region-name-ar = ᱟᱨᱡᱮᱱᱴᱤᱱᱟ
region-name-as = ᱟᱢᱮᱨᱤᱠᱟᱱ ᱥᱟᱢᱚᱟ
region-name-at = ᱚᱥᱴᱨᱤᱭᱟ
region-name-au = ᱚᱥᱴᱨᱮᱞᱤᱭᱟ
region-name-aw = ᱚᱨᱩᱵᱟ
region-name-az = ᱟᱹᱡᱟᱹᱨᱵᱮᱭᱡᱟᱱ
region-name-ba = ᱵᱚᱥᱱᱤᱭᱟ ᱟᱨ ᱦᱟᱹᱨᱡᱮᱜᱚᱣᱤᱱᱟ
region-name-bb = ᱵᱟᱨᱵᱟᱰᱚᱥ
region-name-bd = ᱵᱟᱝᱞᱟᱫᱮᱥ
region-name-be = ᱵᱮᱞᱜᱤᱭᱟᱹᱢ
region-name-bf = ᱵᱤᱨᱠᱤᱱᱟ ᱯᱷᱟᱥᱚ
region-name-bg = ᱵᱩᱞᱡᱮᱨᱤᱭᱟ
region-name-bh = ᱵᱟᱦᱨᱮᱱ
region-name-bi = ᱵᱩᱨᱩᱱᱰᱤ
region-name-bj = ᱵᱮᱱᱤᱱ
region-name-bl = ᱥᱮᱸᱴ ᱵᱟᱨᱛᱷᱮᱞᱮᱢᱤ
region-name-bm = ᱵᱟᱹᱨᱢᱩᱰᱟ
region-name-bn = ᱵᱽᱨᱩᱱᱮᱤ
region-name-bo = ᱵᱚᱞᱤᱣᱤᱭᱟ
region-name-bq = ᱵᱚᱱᱟᱭᱮᱨ, ᱥᱤᱱᱴ ᱤᱭᱩᱥᱴᱮᱴᱤᱭᱚᱥ, ᱟᱨ ᱥᱟᱵᱟ
region-name-br = ᱵᱽᱨᱟᱡᱤᱞ
region-name-bs = ᱵᱟᱦᱟᱢᱟᱥ, ᱫᱟᱹ
region-name-bt = ᱵᱷᱩᱴᱟᱱ
region-name-bv = ᱵᱚᱩᱣᱮᱴ ᱟᱭᱞᱮᱸᱱᱰ
region-name-bw = ᱵᱚᱴᱥᱣᱟᱱᱟ
region-name-by = ᱵᱮᱞᱟᱨᱩᱥ
region-name-bz = ᱵᱮᱞᱤᱡᱮ
region-name-ca = ᱠᱟᱱᱟᱰᱟ
region-name-cc = ᱠᱚᱠᱚᱥ(ᱠᱤᱞᱤᱝ) ᱫᱣᱤᱯ ᱠᱚ
region-name-cd = ᱠᱚᱝᱜᱚ (ᱠᱤᱱᱥᱟᱥᱟ)
region-name-cf = ᱥᱮᱱᱴᱨᱟᱞ ᱟᱯᱷᱨᱤᱠᱟ ᱨᱤᱯᱟᱹᱵᱞᱤᱠ
region-name-cg = ᱠᱚᱝᱜᱚ (ᱵᱽᱨᱟᱡᱟᱣᱤᱞᱮ)
region-name-ch = ᱥᱣᱤᱡᱟᱹᱨᱞᱮᱸᱱᱰ
region-name-ci = ᱠᱚᱴ ᱰᱤᱣᱟᱨᱮ
region-name-ck = ᱠᱩᱠ ᱫᱤᱯ
region-name-cl = ᱪᱤᱞᱤ
region-name-cm = ᱠᱟᱢᱮᱨᱩᱱ
region-name-cn = ᱪᱤᱱ
region-name-co = ᱠᱚᱞᱚᱢᱵᱤᱭᱟ
region-name-cp = ᱠᱞᱤᱯᱟᱹᱨᱴᱚᱱ ᱟᱭᱞᱮᱸᱱᱰ
region-name-cr = ᱠᱚᱥᱴᱟ ᱨᱤᱠᱟ
region-name-cu = ᱠᱭᱩᱵᱟ
region-name-cv = ᱠᱟᱵᱚ ᱣᱟᱹᱨᱰᱮ
region-name-cw = ᱠᱩᱨᱟᱠᱟᱣ
region-name-cx = ᱠᱨᱤᱥᱴᱢᱟᱹᱥ ᱫᱭᱤᱯ
region-name-cy = ᱥᱟᱭᱯᱨᱟᱹᱥ
region-name-cz = ᱪᱮᱠ ᱨᱤᱯᱟᱹᱵᱞᱤᱠ
region-name-de = ᱡᱟᱹᱨᱢᱟᱹᱱᱤ
region-name-dg = ᱰᱤᱭᱮᱜᱟ ᱜᱟᱨᱥᱤᱭᱟᱹ
region-name-dj = ᱰᱡᱤᱵᱚᱣᱴᱤ
region-name-dk = ᱰᱮᱱᱢᱟᱨᱠ
region-name-dm = ᱰᱚᱢᱤᱱᱤᱠᱟ
region-name-do = ᱰᱚᱢᱤᱱᱤᱠᱟᱹᱱ ᱨᱤᱯᱚᱵᱞᱤᱠ
region-name-dz = ᱟᱹᱞᱡᱤᱨᱤᱭᱟ
region-name-ec = ᱤᱠᱣᱟᱥᱚᱨ
region-name-ee = ᱤᱥᱴᱚᱱᱤᱭᱟ
region-name-eg = ᱢᱤᱥᱨᱚ
region-name-eh = ᱣᱮᱥᱴᱮᱱ ᱥᱟᱦᱟᱨᱟ
region-name-er = ᱮᱨᱤᱴᱨᱤᱭᱟ
region-name-es = ᱥᱯᱮᱱ
region-name-et = ᱤᱛᱷᱤᱭᱚᱯᱤᱭᱟ
region-name-fi = ᱯᱷᱤᱱᱞᱮᱱᱰ
region-name-fj = ᱯᱷᱤᱡᱤ
region-name-fk = ᱯᱷᱟᱞᱠᱞᱮᱸᱱᱰ ᱟᱭᱞᱮᱸᱱᱰᱥ (ᱤᱥᱞᱟᱥ ᱢᱟᱞᱰᱤᱣᱤᱥ)
region-name-fm = ᱢᱟᱭᱠᱨᱚᱱᱮᱥᱤᱭᱟ, ᱯᱷᱮᱰᱟᱹᱨᱮᱴᱮᱰ ᱥᱴᱮᱴᱥ ᱚᱯᱷ
region-name-fo = फारोई दीप
region-name-fr = फ्रांस
region-name-ga = गेबोन
region-name-gb = यूनाइटेड किंगडम
region-name-gd = ग्रेनाडा
region-name-ge = जार्जिया
region-name-gf = फ्रेंच गुयनिया
region-name-gg = गुयरनेसे
region-name-gh = घाना
region-name-gi = गिबरालटार
region-name-gl = ग्रिनलैंड
region-name-gn = गुयनिया
region-name-gp = गुवाडेलाउपे
region-name-gq = इकवाटोरियल गुयनिया
region-name-gr = ग्रीस
region-name-gt = गुआटेमाला
region-name-gu = गुवाम
region-name-gw = गुयनिया-बिसाउ
region-name-gy = गुयाना
region-name-hk = हांग कांग
region-name-hm = हेयार्ड दीप आर मेकडोनाल्ड दीप
region-name-hn = होंडुरास
region-name-hr = क्रोवेशिया
region-name-ht = हाइटी
region-name-hu = हानगारी
region-name-id = इनडोनेसिया
region-name-ie = आयरलैंड
region-name-il = इसराइल
region-name-im = इसले ऑफ मेन
region-name-in = भारोत
region-name-io = ब्रिटिस इंडिया दोरया पोनोत
region-name-iq = इराक
region-name-ir = इरान
region-name-is = आयसलैंड
region-name-it = इटली
region-name-je = जरसी
region-name-jm = जमैका
region-name-jo = जोर्डन
region-name-jp = जापान
region-name-ke = केनया
region-name-kg = किरजिसतान
region-name-kh = कामबोडिया
region-name-ki = किरिबाती
region-name-km = कोमोरोस
region-name-kn = सेंट कीट्स आर नेविस
region-name-kw = कुवैत
region-name-ky = कैमान दीप
region-name-kz = काजाखस्तान
region-name-la = लाओस
region-name-lb = लेबनान
region-name-lc = सेंट लुसिया
region-name-li = लिचेंस्टाइन
region-name-lk = श्रीलंका
region-name-lr = लिबेरिया
region-name-ls = लिसोथो
region-name-lt = लिथुवानिया
region-name-lu = लक्समबर्ग
region-name-lv = लाटभिया
region-name-ly = लीबिया
region-name-ma = मोरोक्को
region-name-mc = मोनाको
region-name-md = मोलडोबा
region-name-me = मोनटेनेग्रो
region-name-mf = सेंट मार्टिन
region-name-mg = माडागासकर
region-name-mh = मारसाल दीप
region-name-ml = माली
region-name-mn = मोंगोलिया
region-name-mp = उतोर नाखा मारियाना दीप
region-name-mq = मारटिनिक्यू
region-name-mr = माउरिटानिया
region-name-ms = मोंटसेराट
region-name-mt = मालटा
region-name-mu = मोरिसास
region-name-mv = मालदीवेस
region-name-mw = मालावी
region-name-mx = मेक्सिको
region-name-my = मालेसिया
region-name-mz = मोजामबिक्यू
region-name-na = नामिबिया
region-name-nc = नावा केलेडोनिया
region-name-ne = नाइजर
region-name-nf = नो़रफोक दीप
region-name-ng = नाइजेरिया
region-name-ni = निकारागुआ
region-name-nl = नेदारलैंड
region-name-no = नोर्वे
region-name-np = नेपाल
region-name-nr = नौरू
region-name-nu = निवये
region-name-nz = न्यू जीलैंड
region-name-om = ओमान
region-name-pa = पनामा
region-name-pe = पेरू
region-name-pf = फ्रेन्च पोलिनेसिया
region-name-pg = पपुआ न्यू गयनिया
region-name-ph = फिलीपींस
region-name-pk = पाकिस्तान
region-name-pl = पोलेंड
region-name-pm = सेंट पैरी आर मिकवेलोन
region-name-pr = प्यूरिटो रिको
region-name-pt = पोर्तुगल
region-name-pw = पालाउ
region-name-py = पराग्वे
region-name-qa = कातार
region-name-re = रियुनियान
region-name-ro = रोमानिया
region-name-rs = सारबिया
region-name-rw = रावनडा
region-name-sa = सऊदी अरब
region-name-sb = सोलोमोन दिप
region-name-sc = सैचेलेस
region-name-sd = सुडान
region-name-se = स्वीडन
region-name-sg = सिंगापुर
region-name-si = स्लोवेनिया
region-name-sk = स्लोवेकिया
region-name-sl = सेरालियोन लेवने
region-name-sm = सान मेरिनो
region-name-sn = सेनेगाल
region-name-so = सोमालिया
region-name-sr = सुरीनेम
region-name-st = साव टोम आर प्रिनसिपे
region-name-sv = एल साल्वाडोर
region-name-sy = साइरिया
region-name-sz = स्वाजिलैंड
region-name-tc = तुर्क आर कैकस दीप
region-name-td = छाड
region-name-tg = टोगो
region-name-th = थाइलैंड
region-name-tj = तजिकिस्तान
region-name-tk = टोकेलाउ
region-name-tl = टिमोर-लेसटे
region-name-tm = तुर्कमेनिस्तान
region-name-tn = ट्यूनीशिया
region-name-to = टोंगा
region-name-tr = तुर्की
region-name-tt = ट्रिनाडाड और टोबागो
region-name-tv = टुवालु
region-name-tw = ताइवान
region-name-tz = टानजोन
region-name-ua = यूक्रेइन
region-name-ug = उगांडा
region-name-us = संयुक्त राज्य
region-name-uy = उरुगवे
region-name-uz = उजबेकिस्तान
region-name-va = भेटिकन सिटी
region-name-vc = सेंट विनसेंट आर ग्रेनाडिनेस
region-name-ve = वेनेजुएला
region-name-vn = बैतनाम
region-name-vu = बानाउतु
region-name-wf = बालिस आर फुतुना
region-name-ws = सामुवा
region-name-ye = यमन
region-name-yt = मायोते
region-name-za = दोखिन अफ्रीका
region-name-zm = जामबिया
region-name-zw = जिम्बाब्वे
