# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language-name-ab = അബ്ഖാസ്സിയന്‍
language-name-ae = അവെസ്റ്റന്‍
language-name-af = ആഫ്രിക്കാന്‍സ്‌
language-name-ak = അകാന്‍
language-name-an = അരഗൊനീസ്‌
language-name-ar = അറബിക്‌
language-name-ba = ബാഷ്കിര്‍
language-name-be = ബെലാറസ്സിയന്‍
language-name-br = ബ്രിട്ടണ്‍
language-name-bs = ബോസ്നിയന്‍
language-name-ca = കട്ടളന്‍
language-name-co = കോര്‍സ്സിക്കന്‍
language-name-cs = ചെക്ക്‌
language-name-cu = ചര്‍ച്ച്‌ സാല്‍വിക്ക്‌
language-name-cv = ചുവാഷ്‌
language-name-cy = വെല്‍ഷ്‌
language-name-da = ഡാനിഷ്‌
language-name-dv = ഡിവെഹി
language-name-dz = ഭുട്ടാനീസ്‌
language-name-ee = ഏയ്വെയ്‌
language-name-en = ഇംഗ്ലീഷ്‌
language-name-eo = എസ്പെറാന്റൊ
language-name-ff = ഫുലാഹ്‌
language-name-fo = ഫെഹ്‌റോവ്വീസ്‌
language-name-fr = ഫ്രെഞ്ച്‌
language-name-fur = ഫ്രുയിലിയന്‍
language-name-gd = സ്കോട്ട്സ്‌ ഗായെലിക്ക്‌
language-name-gu = ഗുജറാത്തി
language-name-ha = ഹൌസ
language-name-ho = ഹിരി മൊട്ടു
language-name-hsb = അപ്പര്‍ സോര്‍ബിയന്‍
language-name-id = ഇന്തോനേഷിയന്‍
language-name-ie = ഇന്റര്‍ലിങ്ങുവ
language-name-is = ഐസ്‌ലാന്‍ഡിക്ക്‌
language-name-ja = ജാപ്പനീസ്‌
language-name-kl = ഗ്രീന്‍ലാന്‍ഡിക്ക്‌
language-name-kok = കൊങ്കിണി
language-name-kw = കോര്‍ണിഷ്‌
language-name-la = ലാറ്റിന്‍
language-name-lb = ലക്സംബോര്‍ഗ്ഗിഷ്‌
language-name-lg = ഗാന്‍ഡ
language-name-mn = മംഗോളിയന്‍
language-name-ms = മലായ്‌
language-name-my = ബര്‍മ്മീസ്‌
language-name-ne = നേപ്പാളി
language-name-nv = നവജൊ
language-name-ny = ചിചെവ
language-name-oc = ഓക്സിറ്റന്‍
language-name-oj = ഒജിബ്‌വെയ്‌
language-name-om = ഒറോമോ
language-name-os = ഒസ്സെറ്റിയന്‍
language-name-pl = പോളിഷ്‌
language-name-pt = പോര്‍ച്ചുഗീസ്‌
language-name-qu = കെച്ചുവ
language-name-ro = റോമാനിയന്‍
language-name-sd = സിന്ധി
language-name-si = സിംഹളീസ്‌
language-name-so = സൊമാലി
language-name-son = സോങ്കായ്
language-name-sr = സെര്‍ബിയന്‍
language-name-ss = സിസ്വാട്ടി
language-name-sw = സ്വാഹിളി
language-name-te = തെലുങ്ക്‌
language-name-tg = താജിക്ക്‌
language-name-th = തായ്‌
language-name-tn = ടസ്വാന
language-name-to = ടോന്‍ഗ
language-name-tt = ടാറ്റര്‍
language-name-ty = തഹിതിയന്‍
language-name-uk = ഉക്ക്രേനിയന്‍
language-name-ur = ഉര്‍ദു
language-name-ve = വേന്‍ഡ
language-name-vi = വിയറ്റ്നമീസ്‌
language-name-wa = വലൂണ്‍
language-name-wen = സൊര്‍ബിയന്‍
language-name-wo = വോവ്‌ളോഫ്‌
language-name-xh = ക്‌സ്‌ഹോസ
language-name-yi = യിദ്ദിഷ്‌
language-name-yo = യൊറുബ
language-name-zu = സുളു
