# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

ssl-error-no-cypher-overlap = Entumi ne mfɛfo ndi nkitaho yiye: Ɛnkryphyin akonta-hyehyɛe bi mbata abien no.
ssl-error-no-certificate = Enhu abodin krataa no anaa safoa a ehia ma ne ngyetomu.
ssl-error-bad-client = Somfo no ehyia deta-bɔne efi adwa-di-ni no hɔ.
ssl-error-unsupported-certificate-type = Abodin krataa no ndi mu.
ssl-error-unsupported-version = Mfɛfo no reyɛ banbɔ protokɔl vɛɛhyen bi ho adwuma a endi mu.
ssl-error-wrong-certificate = Entumi angye adwumadi-ni no anto mu: ehinta-safoa a ɛwɔ safoa detabes no mu ɛne amansan-safoa a ɛwɔ abodin krataa detabes no mu abɔ ebira.
ssl-error-ssl2-disabled = Somfo no yɛ SSL vɛɛhyen 2 no ho adwuma, a w'edum no.
ssl-error-bad-mac-read = SSL nsa aka akyerɛwsiede bi a ne nkratoɔ ngyetomu kood ndi mu.
ssl-error-bad-mac-alert = SSL mfɛfo abɔ nkratoɔ ngyetomu kood a endi mu ho amane.
ssl-error-bad-cert-alert = SSL somfo no ntumi nhwɛ w'abodin krataa no ndimu.
ssl-error-expired-cert-alert = SSL mfɛfo no apo w'abodin krataa no sɛ nea atwam.
ssl-error-ssl-disabled = Entumi nkɔnɛkte: SSL no edum.
ssl-error-fortezza-pqg = Entumi nkɔnɛkte: SSL mfɛfo no wɔ FORTEZZA domen foforo mu.
ssl-error-unknown-cipher-suite = Wɔebisa SSL saefa suite bi a yennim.
ssl-error-no-ciphers-supported = Saefa suite biara nni dwumadie yi mu a wɔasan asɔw.
ssl-error-bad-block-padding = SSL nsa aka akyerɛwsiede bi a ɛwɔ blɔk paden a ɛnyɛ.
ssl-error-rx-record-too-long = SSL nsa aka akyerɛwsiede a aboro atenten a wɔpene no so.
ssl-error-tx-record-too-long = SSL yɛɛ sɛ ɛbɛmane akyerɛwsiede bi a aboro atenten a wɔpene so.
ssl-error-rx-malformed-hello-request = SSL enya hɛlo mbisae nsakyea nkratoɔ a anhyehyɛ yiye.
ssl-error-rx-malformed-client-hello = SSL enya adwumadi-ni hɛlo nsakyea nkratoɔ a anhyehyɛ yiye.
ssl-error-rx-malformed-server-hello = SSL enya somfo hɛlo nsakyea nkratoɔ a anhyehyɛ yiye.
ssl-error-rx-malformed-certificate = SSL enya abodin krataa nsakyea nkratoɔ a anhyehyɛ yiye.
ssl-error-rx-malformed-server-key-exch = SSL enya somfo safoa nsesa-di nsakyea nkratoɔ a anhyehyɛ yiye.
ssl-error-rx-malformed-cert-request = SSL enya abodin krataa nsakyea nkratoɔ mbisae a anhyehyɛ yiye.
ssl-error-rx-malformed-hello-done = SSL nsa aka somfo hɛlo ewie nsakyea nkratoɔ a anhyehyɛ yiye.
ssl-error-rx-malformed-cert-verify = SSL enya abodin krataa ngye-to-mu nsakyea nkratoɔ a anhyehyɛ yiye.
ssl-error-rx-malformed-client-key-exch = SSL enya adwumadi-ni safoa nsesa-di nsakyea nkratoɔ a anhyehyɛ yiye.
ssl-error-rx-malformed-finished = SSL nsa aka nsakyea a ewie nkratoɔ a anhyehyɛ yiye.
ssl-error-rx-malformed-change-cipher = SSL nsa aka Sesa Saefa Spɛk akyerɛwsiede a anhyehyɛ yiye.
ssl-error-rx-malformed-alert = SSL nsa aka kɔkɔbɔ akyerɛwsiede a anhyehyɛ yiye.
ssl-error-rx-malformed-handshake = SSL nsa aka Nsakyea akyerɛwsiede a anhyehyɛ yiye.
ssl-error-rx-malformed-application-data = SSL nsa aka aplekehyen deta akyerɛwsiede a anhyehyɛ yiye.
ssl-error-rx-unexpected-hello-request = SSL nsa aka hɛlo nsakyea mbisae nkratoɔ a wanhwɛ enim.
ssl-error-rx-unexpected-client-hello = SSL nsa aka adwumadi-ni hɛlo nsakyea nkratoɔ a wanhwɛ enim.
ssl-error-rx-unexpected-server-hello = SSL nsa aka somfo hɛlo nsakyea nkratoɔ a wanhwɛ enim.
ssl-error-rx-unexpected-certificate = SSL nsa aka abodin krataa nsakyea nkratoɔ a wanhwɛ enim.
ssl-error-rx-unexpected-server-key-exch = SSL nsa aka somfo safoa nsesa-di nsakyea nkratoɔ a wanhwɛ enim.
ssl-error-rx-unexpected-cert-request = SSL nsa aka abodin krataa nsakyea mbisae nkratoɔ a wanhwɛ enim.
ssl-error-rx-unexpected-hello-done = SSL nsa aka somfo hɛlo ewie nsakyea nkratoɔ a wanhwɛ enim.
ssl-error-rx-unexpected-cert-verify = SSL nsa aka abodin krataa agye-ato-mu nsakyea nkratoɔ a wanhwɛ enim.
ssl-error-rx-unexpected-client-key-exch = SSL nsa aka adwumadi-ni safoa nsesa-di nsakyea nkratoɔ a wanhwɛ enim.
ssl-error-rx-unexpected-finished = SSL nsa aka ewie nsakyea nkratoɔ a wanhwɛ enim.
ssl-error-rx-unexpected-change-cipher = SSL nsa aka Sesa Saefa Spɛk akyerɛwsiede a wanhwɛ enim.
ssl-error-rx-unexpected-alert = SSL nsa aka kɔkɔbɔ akyerɛwsiede a wanhwɛ enim.
ssl-error-rx-unexpected-handshake = SSL nsa aka Nsakyea akyerɛwsiede a wanhwɛ enim.
ssl-error-rx-unexpected-application-data = SSL nsa aka aplekehyɛn deta akyerɛwsiede a wanhwɛ enim.
ssl-error-rx-unknown-record-type = SSL nsa aka akyerɛwsiede bi a ennim emu nsɛm.
ssl-error-rx-unknown-handshake = SSL nsa aka nsakyea nkratoɔ bi a ennim emu nkratoɔ nsɛm.
ssl-error-rx-unknown-alert = SSL nsa aka kɔkɔbɔ akyerɛwsiede bi a ɛwɔ kɔkɔbɔ nkyerɛmu a yennim.
ssl-error-close-notify-alert = SSL mfɛfo aka kɔnɛkhyɛn yi ato mu.
ssl-error-handshake-unexpected-alert = SSL mfɛfo nsa aka nsa-kyea nkratoɔ bi a anhwɛ enim.
ssl-error-decompression-failure-alert = SSL mfɛfo entumi ansane SSL akyerɛwsiede bi a ne nsa kaae.
ssl-error-handshake-failure-alert = SSL mfɛfo no entumi anpene banbɔ mparamita biara a wɔsɔ eni.
ssl-error-illegal-parameter-alert = SSL mfɛfo epu nsa-kyea nkratoɔ bi efisɛ emu ɛho ntew.
ssl-error-unsupported-cert-alert = SSL mfɛfo nnyɛ abodin krataa no a ne nsa aka no bi ho adwuma.
ssl-error-certificate-unknown-alert = SSL mfɛfo no anya esie-sɛm bi afa abodin krataa a ne nsa aka no ho.
ssl-error-generate-random-failure = SSL ehyia n'aba mpofrim gyɛnɛreta no nkugodi.
ssl-error-sign-hashes-failure = Entumi ansan deta a ehia sɛ wɔdebɛhwɛ w'abodin krataa no ndimu digyital kwan so.
ssl-error-server-key-exchange-failure = Mfomso-esie wɔ bere a wɔrebu SSL somfo safoa nkitahodi nsa-kyea ho nkonta.
ssl-error-client-key-exchange-failure = Mfomso-esie wɔ bere a wɔrebu SSL kliente safoa nkitahodi nsa-kyea ho nkonta.
ssl-error-encryption-failure = Etufoɔ deta ɛnkryphyin algɔridim endi mu wɔ saefa suite a wapaw no mu.
ssl-error-decryption-failure = Etufoɔ deta dekryphyin algɔridim endi mu wɔ saefa suite a wapaw no mu.
ssl-error-socket-write-failure = Mbɔdenbɔ wɔ deta a wɔaɛnkrypte nkyerɛwee ɛkɔ ɛda-ase sɔkɛt endi mu.
ssl-error-md5-digest-failure = MD5 daegyɛste fankhyɛn endi mu.
ssl-error-sha-digest-failure = SHA-1 daegyɛst fankhyɛn endi mu.
ssl-error-mac-computation-failure = MAC akontabu endi mu.
ssl-error-sym-key-context-failure = Entumi anbɔ Symɛtrik safoa kɔntɛkste.
ssl-error-sym-key-unwrap-failure = Entumi ansane Symɛtrik safoa no wɔ kliente safoa nkitahodi nkratoɔ no mu.
ssl-error-pub-key-size-limit-exceeded = SSL somfo no bɔɔ mbɔden sɛ ɛbɛyɛ fie-ade amansan safoa no ɛka amane saefa suite no ho.
ssl-error-iv-param-failure = PKCS11 kood no entumi ankyerɛ IV ankɔ param.
ssl-error-init-cipher-suite-failure = Entumi ansɔw saefa suite a wapaw no.
ssl-error-no-server-key-for-alg = Somfo no nni safoa biara mma safoa nsesae algɔredem no.
ssl-error-token-insertion-removal = Woyii anaa wɔsan de PKCS#11 mproprowa no hyɛɛe wɔ bere a edwumadi no rekɔ so.
ssl-error-token-slot-not-found = Enhu PKCS#11 mproprowa biara anfa annyɛ edwumadi ehiade biara.
ssl-error-no-compression-overlap = Entumi ne mfɛfo ndi nkitaho pefee: wonni mmiaso algɔredem biara a ɛyɛ na.
ssl-error-handshake-not-completed = Entumi nsɔw SSL nsakyea foforo ɛkosi sɛ nsakyea yi akɔ ewiei.
ssl-error-bad-handshake-hash-value = Nsa aka mfomso nsakyea hahye mba efi mfɛfo hɔ.
ssl-error-cert-kea-mismatch = Saa abodin krataa yi ntumi ne safoa nsesa-di a wapaw no algɔredem no ntumi nnyɛ adwuma.
ssl-error-no-trusted-ssl-client-ca = Wɔngye abodin krataa biara nto mu mma SSL kliente ngyentomu.
ssl-error-decryption-failed-alert = Mfɛfo entumi ndekrypte SSL akyerɛwsiede bi a ne nsa aka.
ssl-error-unknown-ca-alert = Mfɛfo nhyɛ-nso na ɛnsan ngye CA na eyii abodin krataa no puee no ntom.
ssl-error-access-denied-alert = Mfɛfo nsa aka abodin krataa a edi mu nso wannya kwan.
ssl-error-decode-error-alert = Mfɛfo no entumi ankyerɛ SSL nsakyea nkratoɔ no ase.
ssl-error-decrypt-error-alert = Mfɛfo bɔ nsatim anaa safoa ngyetomu nkugodi ho amande.
ssl-error-export-restriction-alert = Mfɛfo bɔ nkitahodi a enni amande ayɛde no mu ho amande.
ssl-error-protocol-version-alert = Mfɛfo bɔ protokɔl vɛɛhyen a emfa ho amande.
ssl-error-insufficient-security-alert = Somfo no hia nsaefa a wɔwɔ banbɔ anoɔden sen nea kliente no de yɛ adwuma.
ssl-error-internal-error-alert = Mfɛfo bɔ amande sɛ ehyia emuemu mfomso.
ssl-error-user-canceled-alert = Mfɛfo adwumadini etwa nsakyea mu.
ssl-error-no-renegotiation-alert = Mfɛfo mpene SSL banbɔ mparamita ho edwa-di apene-ka.
ssl-error-server-cache-not-configured = SSL somfo asiei no nni sɔkɛt yi ho ahosiesie na wɔasɔw.
ssl-error-unsupported-extension-alert = SSL mfɛfo ndi TLS hɛlo ntrɛw mbisae ho asɛm.
ssl-error-certificate-unobtainable-alert = SSL mfɛfo entumi antwe w'abodin krataa enfi URL a ɛmaneeɛ.
ssl-error-unrecognized-name-alert = SSL mfɛfo no nni abodin krataa mma DNS din a wɔebisa no.
ssl-error-bad-cert-status-response-alert = SSL mfɛfo no entumi enya OCSP anobua amma n'abodin krataa no.
ssl-error-bad-cert-hash-value-alert = SSL mfɛfo abɔ abodin krataa hahyɛ aba ho amande.
sec-error-io = I/O mfomso sii wɔ banbɔ ahokwanma no mu.
sec-error-library-failure = Banbɔ Nnwomasiebea Nkuguo.
sec-error-bad-data = Banbɔ Nnwomasiebea: nsa aka deta a asɛe.
sec-error-output-len = Banbɔ Nnwomasiebea: mbuaeɛ atenten mfomso.
sec-error-input-len = Banbɔ Nnwomasiebea ehyia nhyɛmu atenten mfomso.
sec-error-invalid-args = Banbɔ Nnwomasiebea: nkontompo mba.
sec-error-invalid-algorithm = Banbɔ Nnwomasiebea: algɔredem a endi mu.
sec-error-invalid-ava = Banbɔ Nnwomasiebea: AVA a endi mu.
sec-error-invalid-time = Mbere ntoasoɔ a wɔanfɔɔmate nno yiye.
sec-error-bad-der = Banbɔ Nnwomasiebea: DER-nkoode nkratoɔ a wɔanfɔɔmate no yiye.
sec-error-bad-password = Banbɔ ehintasɛmfua no ndi mu.
sec-error-no-nodelock = Banbɔ Nnwomasiebea: enni noodlɔk.
sec-error-bad-database = Banbɔ Nnwomasiebea: deta asiebea a asɛe.
sec-error-no-memory = Banbɔ Nnwomasiebea: akaebea akyɛw nkuguodi.
sec-error-duplicate-cert = Abodin krataa no wɔ wo deta siebea no mu dada.
sec-error-adding-cert = Entumi amfa abodin krataa anka wo deta siebea no ho.
sec-error-filing-key = Abodin krataa yi afaele ehyia mfomso.
sec-error-cert-valid = Abodin krataa no di mu.
sec-error-cert-not-valid = Abodin krataa no ndi mu.
sec-error-crl-invalid = CRL foforo no fɔɔmat ndi mu.
sec-error-extension-value-invalid = Abodin krataa ntrɛw aba no ndi mu.
sec-error-extension-not-found = Enhu abodin krataa ntrɛw no.
sec-error-ca-cert-invalid = Eyikyerɛni abodin krataa ndi mu.
sec-error-path-len-constraint-invalid = Abodin krataa akwan atenten ahokyerew ndi mu.
sec-error-cert-usages-invalid = Abodin krataa adwumadi kyerɛwbea ndi mu.
sec-error-invalid-key = Safoa no ndi adwumadi a wɔebisa no ho adwuma.
sec-error-unknown-critical-extension = Abodin krataa no wɔ ntrɛw titiriw bi a wo nnim.
sec-error-old-crl = CRL foforo no nnyɛ foforo sen dea wodeyɛ adwuma no.
sec-error-no-email-cert = Wontiim so na wɔn ɛnkrypteeɛ: wo nni e-mel abodin krataa ansa.
sec-error-no-recipient-certs-query = Wɔn ɛnkrypteeɛ: wo nni mbodin krataa mma wɔn a wɔn nsa bɛka no biara.
sec-error-not-a-recipient = Entumi ndekrypte: wo nnyɛ nea wɔn nsa bɛka no mu biara anaa abodin krataa ne safoa a wɔkɔ bom no nni hɔ.
sec-error-pkcs7-keyalg-mismatch = Entumi ndekrypte: safoa ɛnkryphyin algɔredem no ne w'abodin krataa no ndi nsɛ.
sec-error-pkcs7-bad-signature = Nsatim ngyetomu endi mu: enhu tumikyerɛni biara, tumikyerɛfo no yɛ pii dodow anaa deta no ndi mu anaa asɛe.
sec-error-unsupported-keyalg = Endi ho adwuma anaa ennim safoa no algɔredem.
sec-error-decryption-disallowed = Entumi ndekrypte: wɔde algɔredem anaa safoa kɛseɛ a wɔn mma ho kwan na ɛde ɛnkryptee.
