# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = Bue
    .accesskey = B
places-open-all-in-tabs =
    .label = Bue No Nyinara wɔ Ntab mu
    .accesskey = o
places-view =
    .label = Hwɛ
    .accesskey = w
places-by-date =
    .label = Fa Afeda
    .accesskey = d
places-by-site =
    .label = Fa Saet
    .accesskey = S
places-by-most-visited =
    .label = Fa beebi a wɔasra hɔ kyɛn beebi foforo biara
    .accesskey = w
places-by-last-visited =
    .label = Fa Beebi a Wɔkɔɔ hɔ Nnkyɛree
    .accesskey = k
places-by-day-and-site =
    .label = Fa Afeda ne Saet
    .accesskey = d
places-history =
    .aria-label = Abakɔsɛm
places-delete-domain-data =
    .label = Ma Wo Were Mfiri Saet Yi
    .accesskey = f
places-sortby-name =
    .label = Fa Din Hyehyɛ
    .accesskey = r
places-library =
    .title = Nwomasuabea
    .style = width:700px; height:500px;
places-organize-button =
    .label = Siesie
    .tooltiptext = Ɔganaez wo mbukmaak
    .accesskey = S
places-organize-button-mac =
    .label = Siesie
    .tooltiptext = Ɔganaez wo mbukmaak
places-file-close =
    .label = To-mu
    .accesskey = T
places-cmd-close =
    .key = w
places-view-button =
    .label = Nhwɛ
    .tooltiptext = Sesa sɛnea wo hwɛ
    .accesskey = w
places-view-button-mac =
    .label = Nhwɛ
    .tooltiptext = Sesa sɛnea wo hwɛ
places-view-menu-columns =
    .label = Kyerɛ Nkɔlɔm
    .accesskey = k
places-view-menu-sort =
    .label = Hyehyɛ
    .accesskey = H
places-view-sort-unsorted =
    .label = Nnhyehyɛe
    .accesskey = N
places-view-sort-ascending =
    .label = A > Z Nheyhɛe Kwan So
    .accesskey = A
places-view-sort-descending =
    .label = Z > A Nhyehyɛ Kwan So
    .accesskey = Z
places-maintenance-button =
    .label = Gye Bra na Fa Sie-bio
    .tooltiptext = Twe wo nsɛm a wo de esie ne wo mbukmaak
    .accesskey = i
places-maintenance-button-mac =
    .label = Gye Bra na Fa Sie-bio
    .tooltiptext = Twe wo nsɛm a wo de esie ne wo mbukmaak
places-cmd-backup =
    .label = Sie-bio…
    .accesskey = S
places-cmd-restore =
    .label = Fa San Bra
    .accesskey = F
places-cmd-restore-from-file =
    .label = Fa Fael…
    .accesskey = F
places-import-bookmarks-from-html =
    .label = Twe Mbukmaak firi HTML bra mu…
    .accesskey = T
places-export-bookmarks-to-html =
    .label = Mane mbukmaak kɔ HTML…
    .accesskey = M
places-import-other-browser =
    .label = Twe data firi brawsa foforo bra mu…
    .accesskey = f
places-view-sort-col-name =
    .label = Din
places-view-sort-col-tags =
    .label = Ntag
places-view-sort-col-url =
    .label = Lokehyɛn
places-view-sort-col-visit-count =
    .label = Nsrahwɛ no Dodow
places-view-sort-col-date-added =
    .label = Aka-ho
places-view-sort-col-last-modified =
    .label = Nsesae a Etwa To
places-cmd-find-key =
    .key = f
places-back-button =
    .tooltiptext = Kɔ ekyiri
places-forward-button =
    .tooltiptext = Kɔ enim
places-details-pane-select-an-item-description = Fa aetɛm, hwɛ na sesa ne ho nsɛm
