# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Importvegvisar
import-from =
    { PLATFORM() ->
        [windows] Importer innstillingar, bokmerke, historikk, passord og annan informasjon frå:
       *[other] Importer innstillingar, bokmerke, historikk, passord og annan informasjon frå:
    }
import-from-bookmarks = Importer bokmerke frå:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-nothing =
    .label = Ikkje importer noko
    .accesskey = I
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = F
import-source =
    .label = Importer innstillingar og data
import-items-title =
    .label = Element som skal importerast
import-items-description = Vel kva for element som skal importerast:
import-migrating-description = Følgjande element vert no importerte…
import-select-profile-title =
    .label = Vel profil
import-done-title =
    .label = Import fullført
import-done-description = Følgjande element er importerte:
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = Frå { $source }
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 trygg nettlesar
imported-safari-reading-list = Leseliste (frå Safari)
imported-edge-reading-list = Leseliste (frå Edge)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Internett-innstillingar
    .value = Internett-innstillingar
browser-data-edge-1 =
    .label = Innstillingar
    .value = Innstillingar
browser-data-safari-1 =
    .label = Innstillingar
    .value = Innstillingar
browser-data-chrome-1 =
    .label = Innstillingar
    .value = Innstillingar
browser-data-canary-1 =
    .label = Innstillingar
    .value = Innstillingar
browser-data-360se-1 =
    .label = Innstillingar
    .value = Innstillingar
browser-data-ie-2 =
    .label = Infokapslar
    .value = Infokapslar
browser-data-edge-2 =
    .label = Infokapslar
    .value = Infokapslar
browser-data-safari-2 =
    .label = Infokapslar
    .value = Infokapslar
browser-data-chrome-2 =
    .label = Infokapslar
    .value = Infokapslar
browser-data-canary-2 =
    .label = Infokapslar
    .value = Infokapslar
browser-data-firefox-2 =
    .label = Infokapslar
    .value = Infokapslar
browser-data-360se-2 =
    .label = Infokapslar
    .value = Infokapslar
browser-data-ie-4 =
    .label = Nettlesarhistorikk
    .value = Nettlesarhistorikk
browser-data-edge-4 =
    .label = Nettlesarhistorikk
    .value = Nettlesarhistorikk
browser-data-safari-4 =
    .label = Nettlesarhistorikk
    .value = Nettlesarhistorikk
browser-data-chrome-4 =
    .label = Nettlesarhistorikk
    .value = Nettlesarhistorikk
browser-data-canary-4 =
    .label = Nettlesarhistorikk
    .value = Nettlesarhistorikk
browser-data-firefox-history-and-bookmarks-4 =
    .label = Nettlesarhistorikk og bokmerke
    .value = Nettlesarhistorikk og bokmerke
browser-data-360se-4 =
    .label = Nettlesarhistorikk
    .value = Nettlesarhistorikk
browser-data-ie-8 =
    .label = Skjemahistorikk
    .value = Skjemahistorikk
browser-data-edge-8 =
    .label = Skjemahistorikk
    .value = Skjemahistorikk
browser-data-safari-8 =
    .label = Skjemahistorikk
    .value = Skjemahistorikk
browser-data-chrome-8 =
    .label = Skjemahistorikk
    .value = Skjemahistorikk
browser-data-canary-8 =
    .label = Skjemahistorikk
    .value = Skjemahistorikk
browser-data-firefox-8 =
    .label = Skjemahistorikk
    .value = Skjemahistorikk
browser-data-360se-8 =
    .label = Skjemahistorikk
    .value = Skjemahistorikk
browser-data-ie-16 =
    .label = Lagra passord
    .value = Lagra passord
browser-data-edge-16 =
    .label = Lagra passord
    .value = Lagra passord
browser-data-safari-16 =
    .label = Lagra passord
    .value = Lagra passord
browser-data-chrome-16 =
    .label = Lagra passord
    .value = Lagra passord
browser-data-canary-16 =
    .label = Lagra passord
    .value = Lagra passord
browser-data-firefox-16 =
    .label = Lagra passord
    .value = Lagra passord
browser-data-360se-16 =
    .label = Lagra passord
    .value = Lagra passord
browser-data-ie-32 =
    .label = Favorittar
    .value = Favorittar
browser-data-edge-32 =
    .label = Favorittar
    .value = Favorittar
browser-data-safari-32 =
    .label = Bokmerke
    .value = Bokmerke
browser-data-chrome-32 =
    .label = Bokmerke
    .value = Bokmerke
browser-data-canary-32 =
    .label = Bokmerke
    .value = Bokmerke
browser-data-360se-32 =
    .label = Bokmerke
    .value = Bokmerke
browser-data-ie-64 =
    .label = Andre data
    .value = Andre data
browser-data-edge-64 =
    .label = Andre data
    .value = Andre data
browser-data-safari-64 =
    .label = Andre data
    .value = Andre data
browser-data-chrome-64 =
    .label = Andre data
    .value = Andre data
browser-data-canary-64 =
    .label = Andre data
    .value = Andre data
browser-data-firefox-other-64 =
    .label = Andre data
    .value = Andre data
browser-data-360se-64 =
    .label = Andre data
    .value = Andre data
browser-data-firefox-128 =
    .label = Vindauge og faner
    .value = Vindauge og faner
