# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

reload-tab =
    .label = Oppdater fane
    .accesskey = O
select-all-tabs =
    .label = Vel alle faner
    .accesskey = f
duplicate-tab =
    .label = Dupliser fane
    .accesskey = D
duplicate-tabs =
    .label = Dupliser faner
    .accesskey = D
close-tabs-to-the-end =
    .label = Lat att faner til høgre
    .accesskey = h
close-other-tabs =
    .label = Lat att andre faner
    .accesskey = a
reload-tabs =
    .label = Oppdater faner
    .accesskey = O
pin-tab =
    .label = Fest fane
    .accesskey = F
unpin-tab =
    .label = Løys fana
    .accesskey = s
pin-selected-tabs =
    .label = Fest faner
    .accesskey = F
unpin-selected-tabs =
    .label = Løys faner
    .accesskey = e
bookmark-selected-tabs =
    .label = Bokmerk faner…
    .accesskey = B
bookmark-tab =
    .label = Bokmerk fana
    .accesskey = B
reopen-in-container =
    .label = Opne på nytt i behaldar
    .accesskey = e
move-to-start =
    .label = Flytt heilt til venstre
    .accesskey = v
move-to-end =
    .label = Flytt heilt til høgre
    .accesskey = h
move-to-new-window =
    .label = Flytt til eit nytt vindauge
    .accesskey = F
undo-close-tab =
    .label = Angre attlating av fane
    .accesskey = r
close-tab =
    .label = Lat att fana
    .accesskey = n
close-tabs =
    .label = Lat att faner
    .accesskey = t
move-tabs =
    .label = Flytt faner
    .accesskey = t
move-tab =
    .label = Flytt denne fana
    .accesskey = t
