# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

print-setup =
    .title = 页面设置
custom-prompt-title = 自定义…
custom-prompt-prompt = 请输入自定义的页眉/页脚文字
basic-tab =
    .label = 格式和选项
advanced-tab =
    .label = 页边距和页眉/页脚
format-group-label =
    .value = 格式
orientation-label =
    .value = 方向：
scale-percent =
    .value = %
options-group-label =
    .value = 选项
margin-group-label-inches =
    .value = 页边距 (英寸)
margin-group-label-metric =
    .value = 页边距 (毫米)
margin-left-invisible =
    .value = 左：
margin-right-invisible =
    .value = 右：
header-footer-label =
    .value = 页眉和页脚
hf-left-label =
    .value = 左：
hf-center-label =
    .value = 中：
hf-right-label =
    .value = 右：
header-left-tip =
    .tooltiptext = 左页眉
header-center-tip =
    .tooltiptext = 中心页眉
header-right-tip =
    .tooltiptext = 右页眉
footer-left-tip =
    .tooltiptext = 左页脚
footer-center-tip =
    .tooltiptext = 中心页脚
footer-right-tip =
    .tooltiptext = 右页脚
hf-blank =
    .label = --空白--
hf-title =
    .label = 标题
hf-url =
    .label = URL
hf-date-and-time =
    .label = 日期/时间
hf-page =
    .label = 第 # 页
hf-page-and-total =
    .label = 第 # 页，共 # 页
hf-custom =
    .label = 自定义…
print-preview-window =
    .title = 打印预览
print-title =
    .value = 标题：
print-preparing =
    .value = 准备…
print-progress =
    .value = 进度：
print-window =
    .title = 正在打印
print-complete =
    .value = 打印完成。
# Variables
# $percent (integer) - Number of printed percentage
print-percent =
    .value = { $percent }%
dialog-cancel-label = 取消
dialog-close-label = 关闭
