# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = விசார்டை இறக்குமதி செய்
import-from =
    { PLATFORM() ->
        [windows] தேர்வுகள், புத்தகக்குறிகள், வரலாறு, கடவுச்சொற்கள் மற்றும் வேறு தரவு போன்றவற்றை இதிலிருந்து இறக்கு:
       *[other] முன்னுரிமைகள், புத்தகக்குறிகள், வரலாறு, கடவுச்சொற்கள் மற்றும் வேறு தரவு போன்றவற்றை இதிலிருந்து இறக்கு:
    }
import-from-bookmarks = இதிலிருந்து புத்தகக்குறிகளை இறக்கு:
import-from-ie =
    .label = மைக்ரோசாப்ட் இன்டர்நெட் எக்ஸ்ப்லோரர்
    .accesskey = ம
import-from-edge =
    .label = மைக்ரொசொப்ட் எட்ஜ்
    .accesskey = E
import-from-nothing =
    .label = எதையும் இறக்க வேண்டாம்
    .accesskey = D
import-from-safari =
    .label = சபாரி
    .accesskey = ச
import-from-canary =
    .label = குரோம் கெனரி
    .accesskey = n
import-from-chrome =
    .label = கொறோம்
    .accesskey = க
import-from-chrome-beta =
    .label = குரோம் பீட்டா
    .accesskey = B
import-from-chrome-dev =
    .label = குரோம் டெவ்
    .accesskey = D
import-from-chromium =
    .label = குரோமியம்
    .accesskey = u
import-from-firefox =
    .label = பயர்பாக்ஸ்(x)
    .accesskey = x
import-from-360se =
    .label = 360 சுழற்சியில் பாதுகாப்பான உலாவி
    .accesskey = 3
no-migration-sources = புத்தகக்குறிகள், வரலாறு அல்லது கடவுச்சொல் தரவு போன்றவற்றைக் கொண்ட நிரல்களை காண முடியவில்லை.
import-source =
    .label = இறக்குதல் அமைவுகள் மற்றும் தரவு
import-items-title =
    .label = இறக்க வேண்டிய உருப்படிகள்
import-items-description = எந்த உருப்படிகளை இறக்க வேண்டும் என தேர்ந்தெடுக்கவும்:
import-migrating-title =
    .label = இறக்குகிறது…
import-migrating-description = பின்வரும் உருப்படிகள் தற்போது இறக்கப்பட வேண்டும்…
import-select-profile-title =
    .label = விவரக்குறிப்பை தேர்ந்தெடு
import-select-profile-description = பின்வரும் விவரக்குறிப்புகள் இறக்க தயாராக உள்ளன:
import-done-title =
    .label = இறக்குதல் முடிவு
import-done-description = பின்வரும் உருப்படிகள் வெற்றிகரமாக இறக்கப்பட்டது:
import-close-source-browser = தொடரும் முன் தேர்ந்தெடுக்கப்பட்ட உலாவி மூடப்பட்டுள்ளதா என உறுதிப்படுத்து.
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = { $source } லிருந்து
source-name-ie = இன்டர்நெட் எக்ஸ்ப்ளோரர்
source-name-edge = மைக்ரொசொப்ட் எட்ஜ்
source-name-safari = சபாரி
source-name-canary = கூகுள் குரோம் கெனரி
source-name-chrome = கூகுள் கொறோம்
source-name-chrome-beta = கூகுள் குரோம் பீட்டா
source-name-chrome-dev = கூகுள் குரோம் டெவ்
source-name-chromium = குரோமியம்
source-name-firefox = மொசில்லா பயர்பாக்ஸ்
source-name-360se = 360 சுழற்சியில் பாதுகாப்பான உலாவி
imported-safari-reading-list = (சபாரியில் இருந்து ) பட்டியல் படிக்கப்படுகிறது
imported-edge-reading-list = (எட்ஜ்லிருந்து) பட்டியல் படிக்கப்படுகிறது

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = இணையத் தேர்வுகள்
    .value = இணையத் தேர்வுகள்
browser-data-edge-1 =
    .label = அமைவுகள்
    .value = அமைவுகள்
browser-data-safari-1 =
    .label = முன்னுரிமைகள்
    .value = முன்னுரிமைகள்
browser-data-chrome-1 =
    .label = விருப்பங்கள்
    .value = விருப்பங்கள்
browser-data-canary-1 =
    .label = விருப்பங்கள்
    .value = விருப்பங்கள்
browser-data-360se-1 =
    .label = முன்னுரிமைகள்
    .value = முன்னுரிமைகள்
browser-data-ie-2 =
    .label = நினைவிகள்
    .value = நினைவிகள்
browser-data-edge-2 =
    .label = நினைவிகள்
    .value = நினைவிகள்
browser-data-safari-2 =
    .label = நினைவிகள்
    .value = நினைவிகள்
browser-data-chrome-2 =
    .label = நினைவிகள்
    .value = நினைவிகள்
browser-data-canary-2 =
    .label = நினைவிகள்
    .value = நினைவிகள்
browser-data-firefox-2 =
    .label = நினைவிகள்
    .value = நினைவிகள்
browser-data-360se-2 =
    .label = நினைவிகள்
    .value = நினைவிகள்
browser-data-ie-4 =
    .label = உலாவும் வரலாறு
    .value = உலாவும் வரலாறு
browser-data-edge-4 =
    .label = உலாவிய வரலாறு
    .value = உலாவிய வரலாறு
browser-data-safari-4 =
    .label = உலாவும் வரலாறு
    .value = உலாவும் வரலாறு
browser-data-chrome-4 =
    .label = உலாவலின் வரலாறு
    .value = உலாவலின் வரலாறு
browser-data-canary-4 =
    .label = உலாவலின் வரலாறு
    .value = உலாவலின் வரலாறு
browser-data-firefox-history-and-bookmarks-4 =
    .label = உலாவுதலின் வரலாறு மற்றும் பூக்மார்க்குகள்
    .value = உலாவுதலின் வரலாறு மற்றும் பூக்மார்க்குகள்
browser-data-360se-4 =
    .label = உலாவிய வரலாறு
    .value = உலாவிய வரலாறு
browser-data-ie-8 =
    .label = சேமிக்கப்பட்ட படிவ வரலாறு
    .value = சேமிக்கப்பட்ட படிவ வரலாறு
browser-data-edge-8 =
    .label = சேமிக்கப்பட்ட படிவ வரலாறு
    .value = சேமிக்கப்பட்ட படிவ வரலாறு
browser-data-safari-8 =
    .label = சேமிக்கப்பட்ட படிவ வரலாறு
    .value = சேமிக்கப்பட்ட படிவ வரலாறு
browser-data-chrome-8 =
    .label = சேமிக்கப்பட்ட படிவ வரலாறு
    .value = சேமிக்கப்பட்ட படிவ வரலாறு
browser-data-canary-8 =
    .label = சேமிக்கப்பட்ட படிவ வரலாறு
    .value = சேமிக்கப்பட்ட படிவ வரலாறு
browser-data-firefox-8 =
    .label = சேமிக்கப்பட்ட படிவ வரலாறு
    .value = சேமிக்கப்பட்ட படிவ வரலாறு
browser-data-360se-8 =
    .label = சேமிக்கப்பட்ட படிவ வரலாறு
    .value = சேமிக்கப்பட்ட படிவ வரலாறு
browser-data-ie-16 =
    .label = சேமிக்கப்பட்ட கடவுச்சொற்கள்
    .value = சேமிக்கப்பட்ட கடவுச்சொற்கள்
browser-data-edge-16 =
    .label = சேமித்த கடவுச்சொற்கள்
    .value = சேமித்த கடவுச்சொற்கள்
browser-data-safari-16 =
    .label = சேமிக்கப்பட்ட கடவுச்சொற்கள்
    .value = சேமிக்கப்பட்ட கடவுச்சொற்கள்
browser-data-chrome-16 =
    .label = சேமிக்கப்பட்ட கடவுச்சொற்கள்
    .value = சேமிக்கப்பட்ட கடவுச்சொற்கள்
browser-data-canary-16 =
    .label = சேமிக்கப்பட்ட கடவுச்சொற்கள்
    .value = சேமிக்கப்பட்ட கடவுச்சொற்கள்
browser-data-firefox-16 =
    .label = சேமிக்கப்பட்ட கடவுச்சொற்கள்
    .value = சேமிக்கப்பட்ட கடவுச்சொற்கள்
browser-data-360se-16 =
    .label = சேமித்த கடவுச்சொற்கள்
    .value = சேமித்த கடவுச்சொற்கள்
browser-data-ie-32 =
    .label = பிடித்தவைகள்
    .value = பிடித்தவைகள்
browser-data-edge-32 =
    .label = பிடித்தவைகள்
    .value = பிடித்தவைகள்
browser-data-safari-32 =
    .label = புத்தகக்குறிகள்
    .value = புத்தகக்குறிகள்
browser-data-chrome-32 =
    .label = புத்தகக்குறிகள்
    .value = புத்தகக்குறிகள்
browser-data-canary-32 =
    .label = புத்தகக்குறிகள்
    .value = புத்தகக்குறிகள்
browser-data-360se-32 =
    .label = புத்தகக்குறிகள்
    .value = புத்தகக்குறிகள்
browser-data-ie-64 =
    .label = வேறு தரவு
    .value = வேறு தரவு
browser-data-edge-64 =
    .label = பிற தரவு
    .value = பிற தரவு
browser-data-safari-64 =
    .label = வேறு தரவு
    .value = வேறு தரவு
browser-data-chrome-64 =
    .label = பிற தகவல்கள்
    .value = பிற தகவல்கள்
browser-data-canary-64 =
    .label = பிற தகவல்கள்
    .value = பிற தகவல்கள்
browser-data-firefox-other-64 =
    .label = வேறு தரவு
    .value = வேறு தரவு
browser-data-360se-64 =
    .label = பிற தரவு
    .value = பிற தரவு
browser-data-firefox-128 =
    .label = சாளரங்களும் கீற்றுகளும்
    .value = சாளரங்களும் கீற்றுகளும்
