# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Ku langutiwa { $host }...
network-connection-status-connected = Hlanganisiwile na { $host }...
network-connection-status-sending-request = Ku rhumeriwa xikombelo eka { $host }...
network-connection-status-transferring-data = Ku hundzisela mahungu eka { $host }...
network-connection-status-connecting = Hlanganisiwile na { $host }...
network-connection-status-read = Hlaya { $host }
network-connection-status-wrote = Tsarile { $host }
network-connection-status-waiting = Ku yimeriwile { $host }...
