# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Мастер импорта
import-from =
    { PLATFORM() ->
        [windows] Импортировать настройки, закладки, журнал, пароли и другие данные из:
       *[other] Импортировать настройки, закладки, журнал, пароли и другие данные из:
    }
import-from-bookmarks = Импортировать закладки из:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-edge-legacy =
    .label = Microsoft Edge Legacy
    .accesskey = L
import-from-edge-beta =
    .label = Microsoft Edge Beta
    .accesskey = d
import-from-nothing =
    .label = Не импортировать ничего
    .accesskey = н
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chrome-beta =
    .label = Chrome Бета
    .accesskey = е
import-from-chrome-dev =
    .label = Chrome Dev
    .accesskey = D
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = X
import-from-360se =
    .label = 360 Secure Browser
    .accesskey = 3
no-migration-sources = Ни одной программы, содержащей закладки, журнал или пароли, не найдено.
import-source =
    .label = Импорт настроек и данных
import-items-title =
    .label = Объекты для импорта
import-items-description = Выберите объекты для импортирования:
import-migrating-title =
    .label = Идёт импорт…
import-migrating-description = В данное время импортируются следующие объекты…
import-select-profile-title =
    .label = Выбор профиля
import-select-profile-description = Импорт может быть произведен из следующих профилей:
import-done-title =
    .label = Импорт успешно завершён
import-done-description = Следующие объекты были успешно импортированы:
import-close-source-browser = Прежде чем продолжить, пожалуйста, убедитесь, что выбранный вами браузер закрыт.
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = Из { $source }
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-edge-beta = Microsoft Edge Beta
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chrome-beta = Google Chrome Бета
source-name-chrome-dev = Google Chrome Dev
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Secure Browser
imported-safari-reading-list = Список для чтения (из Safari)
imported-edge-reading-list = Список для чтения (из Edge)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Настройки Интернета
    .value = Настройки Интернета
browser-data-edge-1 =
    .label = Параметры
    .value = Параметры
browser-data-safari-1 =
    .label = Настройки
    .value = Настройки
browser-data-chrome-1 =
    .label = Настройки
    .value = Настройки
browser-data-canary-1 =
    .label = Настройки
    .value = Настройки
browser-data-360se-1 =
    .label = Настройки
    .value = Настройки
browser-data-ie-2 =
    .label = Куки
    .value = Куки
browser-data-edge-2 =
    .label = Куки
    .value = Куки
browser-data-safari-2 =
    .label = Куки
    .value = Куки
browser-data-chrome-2 =
    .label = Куки
    .value = Куки
browser-data-canary-2 =
    .label = Куки
    .value = Куки
browser-data-firefox-2 =
    .label = Куки
    .value = Куки
browser-data-360se-2 =
    .label = Куки
    .value = Куки
browser-data-ie-4 =
    .label = Журнал посещений
    .value = Журнал посещений
browser-data-edge-4 =
    .label = Журнал посещений
    .value = Журнал посещений
browser-data-safari-4 =
    .label = Журнал посещений
    .value = Журнал посещений
browser-data-chrome-4 =
    .label = Журнал посещений
    .value = Журнал посещений
browser-data-canary-4 =
    .label = Журнал посещений
    .value = Журнал посещений
browser-data-firefox-history-and-bookmarks-4 =
    .label = Журнал посещений и закладки
    .value = Журнал посещений и закладки
browser-data-360se-4 =
    .label = Журнал посещений
    .value = Журнал посещений
browser-data-ie-8 =
    .label = Журнал сохранённых форм
    .value = Журнал сохранённых форм
browser-data-edge-8 =
    .label = Журнал сохранённых форм
    .value = Журнал сохранённых форм
browser-data-safari-8 =
    .label = Журнал сохранённых форм
    .value = Журнал сохранённых форм
browser-data-chrome-8 =
    .label = Журнал сохранённых форм
    .value = Журнал сохранённых форм
browser-data-canary-8 =
    .label = Журнал сохранённых форм
    .value = Журнал сохранённых форм
browser-data-firefox-8 =
    .label = Журнал сохранённых форм
    .value = Журнал сохранённых форм
browser-data-360se-8 =
    .label = Журнал сохранённых форм
    .value = Журнал сохранённых форм
browser-data-ie-16 =
    .label = Сохранённые пароли
    .value = Сохранённые пароли
browser-data-edge-16 =
    .label = Сохранённые пароли
    .value = Сохранённые пароли
browser-data-safari-16 =
    .label = Сохранённые пароли
    .value = Сохранённые пароли
browser-data-chrome-16 =
    .label = Сохранённые пароли
    .value = Сохранённые пароли
browser-data-canary-16 =
    .label = Сохранённые пароли
    .value = Сохранённые пароли
browser-data-firefox-16 =
    .label = Сохранённые пароли
    .value = Сохранённые пароли
browser-data-360se-16 =
    .label = Сохранённые пароли
    .value = Сохранённые пароли
browser-data-ie-32 =
    .label = Избранное
    .value = Избранное
browser-data-edge-32 =
    .label = Избранное
    .value = Избранное
browser-data-safari-32 =
    .label = Закладки
    .value = Закладки
browser-data-chrome-32 =
    .label = Закладки
    .value = Закладки
browser-data-canary-32 =
    .label = Закладки
    .value = Закладки
browser-data-360se-32 =
    .label = Закладки
    .value = Закладки
browser-data-ie-64 =
    .label = Другие данные
    .value = Другие данные
browser-data-edge-64 =
    .label = Другие данные
    .value = Другие данные
browser-data-safari-64 =
    .label = Другие данные
    .value = Другие данные
browser-data-chrome-64 =
    .label = Другие данные
    .value = Другие данные
browser-data-canary-64 =
    .label = Другие данные
    .value = Другие данные
browser-data-firefox-other-64 =
    .label = Другие данные
    .value = Другие данные
browser-data-360se-64 =
    .label = Другие данные
    .value = Другие данные
browser-data-firefox-128 =
    .label = Окна и вкладки
    .value = Окна и вкладки
