# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Đang giải quyết máy chủ { $host }…
network-connection-status-connected = Đã kết nối tới { $host }…
network-connection-status-sending-request = Đang gửi yêu cầu đến { $host }…
network-connection-status-transferring-data = Đang tải dữ liệu từ { $host }…
network-connection-status-connecting = Đang kết nối tới { $host }…
network-connection-status-read = Đã đọc { $host }
network-connection-status-wrote = Đã ghi { $host }
network-connection-status-waiting = Đang đợi { $host }…
network-connection-status-looked-up = Đã giải quyết máy chủ { $host }…
network-connection-status-tls-handshake = Thực hiện giao thức TLS tới { $host }…
network-connection-status-tls-handshake-finished = Giao thức TLS đã kết thúc tới { $host }…
