# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = این صفحهٔ وب در حال تغییر مسیر به مکان جدیدی است. آیا می‌خواهید اطلاعات فرمی که وارد کرده‌اید مجدداً به مکان جدید ارسال شود؟
# Directory listing strings
DirTitle = نمایهٔ ‪%1$S‬
DirGoUp = رفتن به شاخهٔ یک سطح بالاتر
ShowHidden = نمایش موارد مخفی
DirColName = نام
DirColSize = اندازه
DirColMTime = زمان آخرین تغییر
DirFileLabel = پرونده:\u0020
TrackerUriBlockedByETP = منبع موجود در «%1$S» مسدود شد، چون محافظت پیشرفته در برابر ردیابی فعال است.
UnsafeUriBlocked = منبع «%1$S» توسط «مرور امن» مسدود شد.
# LOCALIZATION NOTE (StrictUrlProtocolSetter): %1$S is the URL that has attempted to be changed. %2$S is the invalid target protocol.
StrictUrlProtocolSetter = تغییر پروتکل نشانی «%1$S» به «%2$S» مسدود شد.
# LOCALIZATION NOTE (CORPBlocked): %1$S is the URL of the blocked resource. %2$S is the URL of the MDN page about CORP.
CORPBlocked = منبع موجود در «%1$S» به دلیل سرآیند Cross-Origin-Resource-Policy (یا نبود آن) مسدود شد. %2$S را ببینید
CookieBlockedByPermission = درخواست دسترسی به کلوچک‌‌ها یا ذخیره‌سازی در «%1$S» به دلیل مجوز سفارشی کلوچک‌ مسدود شد.
CookieBlockedTrackerByETP = درخواست دسترسی به کلوچک‌ یا ذخیره‌سازی در «%1$S» مسدود شد، چون از یک ردیاب آمده بود و محافظت پیشرفته در برابر ردیابی فعال است.
CookieBlockedAll = درخواست دسترسی به کلوچک‌ یا ذخیره‌سازی در «%1$S» مسدود شد، چون همهٔ درخواست‌های دسترسی به ذخیره‌سازی را مسدود می‌کنیم.
CookieBlockedForeignByETP = درخواست دسترسی به کلوچک‌ یا ذخیره‌سازی در «%1$S» مسدود شد، چون همهٔ درخواست‌های دسترسی شخص ثالث به ذخیره‌سازی را مسدود می‌کنیم و محافظت پیشرفته در برابر ردیابی فعال است.
# As part of dynamic state partitioning, third-party resources might be limited to "partitioned" storage access that is separate from the first-party context.
# This allows e.g. cookies to still be set, and prevents tracking without totally blocking storage access. This message is shown in the web console when this happens
# to inform developers that their storage is isolated.
CookiePartitionedForeign2 = دسترسی افراز شدهٔ کلوچک یا ذخیره‌گاه به «%1$S» ارائه شده، چون در محتوای سوم‌شخص بار شده و افرازش حالت پویا به کار افتاده است.
# LOCALIZATION NOTE (CookieAllowedForOriginByStorageAccessAPI): %2$S and %1$S are URLs.
CookieAllowedForOriginByStorageAccessAPI = دسترسی به ذخیره‌سازی برای مبدأ «%2$S» در «%1$S» داده شد.
# LOCALIZATION NOTE (CookieAllowedForOriginByHeuristic): %2$S and %1$S are URLs.
CookieAllowedForOriginByHeuristic = دسترسی به ذخیره‌سازی برای مبدأ «%2$S» در «%1$S» به‌طور خودکار داده شد.
# LOCALIZATION NOTE (CookieAllowedForDFPIByHeuristic): %2$S and %1$S are URLs.
CookieAllowedForDFPIByHeuristic = دسترسی به ذخیره‌سازی برای Dynamic State Partitioning ‏«%2$S» در «%1$S» به‌طور خودکار داده شد.
# LOCALIZATION NOTE(CookieRejectedNonRequiresSecure2): %1$S is the cookie name. Do not localize "SameSite=None" and "secure".
CookieRejectedNonRequiresSecure2 = کلوچک‌ «%1$S» رد شد، چون ویژگی «SameSite=None» را دارد اما ویژگی «secure» را ندارد.
# LOCALIZATION NOTE(CookieRejectedNonRequiresSecureForBeta3): %1$S is the cookie name. %2$S is a URL. Do not localize "SameSite", "SameSite=None" and "secure".
CookieRejectedNonRequiresSecureForBeta3 = کلوچک‌ «%1$S» به‌زودی رد خواهد شد، چون ویژگی «SameSite» آن بدون ویژگی «secure» روی «None» تنظیم شده است. برای آشنایی بیشتر با ویژگی «SameSite»، %2$S را بخوانید
# LOCALIZATION NOTE(CookieLaxForced2): %1$S is the cookie name. Do not localize "SameSite", "Lax" and "SameSite=Lax".
CookieLaxForced2 = سیاست «SameSite» کلوچک‌ «%1$S» روی «Lax» تنظیم شد، چون ویژگی «SameSite» را ندارد و «SameSite=Lax» مقدار پیش‌فرض این ویژگی است.
# LOCALIZATION NOTE(CookieLaxForcedForBeta2): %1$S is the cookie name. %2$S is a URL. Do not localize "SameSite", "Lax" and "SameSite=Lax", "SameSite=None".
CookieLaxForcedForBeta2 = کلوچک‌ «%1$S» مقدار مناسبی برای ویژگی «SameSite» ندارد. به‌زودی با کلوچک‌‌هایی که ویژگی «SameSite» ندارند یا مقدار نامعتبر دارند مثل «Lax» رفتار خواهد شد. یعنی این کلوچک‌ دیگر در بافت‌های شخص ثالث فرستاده نمی‌شود. اگر برنامهٔ شما به در دسترس بودن این کلوچک‌ در چنین بافت‌هایی وابسته است، لطفاً ویژگی «SameSite=None» را به آن اضافه کنید. برای آشنایی بیشتر با ویژگی «SameSite»، %2$S را بخوانید
# LOCALIZATION NOTE(CookieSameSiteValueInvalid2): %1$S is cookie name. Do not localize "SameSite", "Lax", "Strict" and "None"
CookieSameSiteValueInvalid2 = مقدار «SameSite» برای کلوچک‌ «%1$S» نامعتبر است. مقادیر پشتیبانی‌شده: «Lax»، «Strict»، «None».
# LOCALIZATION NOTE(CookieInvalidMaxAgeAttribute): %1$S is cookie name. Do not localize "max-age".
CookieInvalidMaxAgeAttribute = مقدار «max-age» برای کلوچک‌ «%1$S» نامعتبر است. این ویژگی نادیده گرفته می‌شود.
# LOCALIZATION NOTE (CookieOversize): %1$S is the cookie name. %2$S is the number of bytes. "B" means bytes.
CookieOversize = کلوچک‌ «%1$S» نامعتبر است، چون اندازه‌اش بیش از حد بزرگ است. حداکثر اندازه %2$S بایت است.
# LOCALIZATION NOTE (CookieRejectedByPermissionManager): %1$S is the cookie response header.
CookieRejectedByPermissionManager = کلوچک‌ «%1$S» به دلیل مجوزهای تنظیم‌شده توسط کاربر رد شد.
CookieRejectedEmptyNameAndValue = کلوچک‌ با نام و مقدار خالی رد شد.
# LOCALIZATION NOTE (CookieRejectedInvalidCharName): %1$S is the cookie name.
CookieRejectedInvalidCharName = کلوچک‌ «%1$S» به دلیل نویسه‌های نامعتبر در نام رد شد.
# LOCALIZATION NOTE (CookieRejectedInvalidCharAttributes): %1$S is the cookie name.
CookieRejectedInvalidCharAttributes = کلوچک‌ «%1$S» به دلیل نویسه‌های نامعتبر در ویژگی‌ها رد شد.
# LOCALIZATION NOTE (CookieRejectedInvalidDomain): %1$S is the cookie name.
CookieRejectedInvalidDomain = کلوچک‌ «%1$S» به دلیل دامنهٔ نامعتبر رد شد.
# LOCALIZATION NOTE (CookieRejectedInvalidPrefix): %1$S is the cookie name.
CookieRejectedInvalidPrefix = کلوچک‌ «%1$S» به دلیل پیشوند نامعتبر رد شد.
# LOCALIZATION NOTE (CookieRejectedInvalidPath): %1$S is the cookie name.
CookieRejectedInvalidPath = کلوچک‌ «%1$S» به دلیل مسیر نامعتبر رد شد.
# LOCALIZATION NOTE (CookieRejectedInvalidCharValue): %1$S is the cookie name.
CookieRejectedInvalidCharValue = کلوچک‌ «%1$S» به دلیل نویسه‌های نامعتبر در مقدار رد شد.
# LOCALIZATION NOTE (CookieRejectedAttributePathOversize): %1$S is the cookie name.
CookieRejectedAttributePathOversize = کلوچک‌ «%1$S» رد شد، چون ویژگی path آن بیش از حد بزرگ است.
# LOCALIZATION NOTE (CookieRejectedAttributeDomainOversize): %1$S is the cookie name.
CookieRejectedAttributeDomainOversize = کلوچک‌ «%1$S» رد شد، چون ویژگی domain آن بیش از حد بزرگ است.
# LOCALIZATION NOTE (CookieRejectedAttributeExpiryOversize): %1$S is the cookie name.
CookieRejectedAttributeExpiryOversize = کلوچک‌ «%1$S» رد شد، چون تاریخ انقضای آن از حد مجاز فراتر است.
# LOCALIZATION NOTE (CookieRejectedHttpOnlyButFromScript): %1$S is the cookie name.
CookieRejectedHttpOnlyButFromScript = کلوچک‌ «%1$S» رد شد، چون از قبل یک کلوچک‌ HTTP-Only وجود دارد اما یک اسکریپت تلاش کرد کلوچک‌ جدیدی ذخیره کند.
# LOCALIZATION NOTE (CookieRejectedSecureButHttp): %1$S is the cookie name.
CookieRejectedSecureButNonHttps = کلوچک‌ «%1$S» رد شد، چون کلوچک‌ غیر HTTPS را نمی‌توان «secure» تنظیم کرد.
# LOCALIZATION NOTE (CookieRejectedThirdParty): %1$S is the cookie response header.
CookieRejectedThirdParty = کلوچک‌ «%1$S» به‌عنوان شخص ثالث رد شد.
# LOCALIZATION NOTE (CookieRejectedNonsecureOverSecure): %1$S is the cookie name.
CookieRejectedNonsecureOverSecure = کلوچک‌ «%1$S» رد شد، چون یک کلوچک‌ «secure» از قبل وجود دارد.
# LOCALIZATION NOTE (CookieRejectedForNonSameSiteness): %1$S is the cookie name.
CookieRejectedForNonSameSiteness = کلوچک‌ «%1$S» رد شد، چون در بافت بین‌سایتی است و «SameSite» آن «Lax» یا «Strict» است.
# LOCALIZATION NOTE (CookieRejectedPartitionedRequiresSecure): %1$S is the cookie name.
CookieRejectedPartitionedRequiresSecure = کلوچک‌ «%1$S» رد شد، چون ویژگی «Partitioned» را دارد اما ویژگی «secure» را ندارد.
# LOCALIZATION NOTE (CookieAttributeIgnored): %1$S is the cookie name. %2$S is the attribute name. %3$S is the number of bytes. "B" means bytes.
CookieAttributeIgnored = مقدار ویژگی «%2$S» برای کلوچک‌ «%1$S» رد شد، چون اندازه‌اش بیش از حد بزرگ است. حداکثر اندازه %3$S بایت است.
CookieAttributeOverwritten = مقدار ویژگی «%2$S» برای کلوچک‌ «%1$S» بازنویسی شد.
# LOCALIZATION NOTE (CookieForeignNoPartitionedWarning): %1$S is the cookie name. Do not translate "Partitioned"
CookieForeignNoPartitionedWarning = کلوچک‌ «%1$S» به‌زودی رد خواهد شد، چون خارجی است و ویژگی «Partitioned» را ندارد.
# LOCALIZATION NOTE (CookieForeignNoPartitionedError): %1$S is the cookie name. Do not translate "Partitioned"
CookieForeignNoPartitionedError = کلوچک‌ «%1$S» رد شد، چون خارجی است و ویژگی «Partitioned» را ندارد.
# LOCALIZATION NOTE (CookieBlockedCrossSiteRedirect): %1$S is the cookie name. Do not translate "SameSite", "Lax" or "Strict".
CookieBlockedCrossSiteRedirect = کلوچک‌ «%1$S» با مقدار «Lax» یا «Strict» برای ویژگی «SameSite» به دلیل تغییر مسیر بین‌سایتی کنار گذاشته شد.
# LOCALIZATION NOTE (APIDeprecationWarning): %1$S is the deprecated API; %2$S is the API function that should be used.
APIDeprecationWarning = هشدار: ‘%1$S’ منسوخ شده است، لطفاً از ‘%2$S’ استفاده کنید
# LOCALIZATION NOTE (ResourceBlockedCORS): %1$S is the url of the resource blocked by ORB. $2$S is the reason.
# example: The resource at <url> was blocked by OpaqueResponseBlocking. Reason: “nosniff with either blocklisted or text/plain”.
ResourceBlockedORB = منبع موجود در «%1$S» توسط OpaqueResponseBlocking مسدود شد. دلیل: «%2$S».
InvalidHTTPResponseStatusLine = خط وضعیت پاسخ HTTP نامعتبر است
# LOCALIZATION NOTE (LocalNetworkAccessDetected): %1$S is top-level site, %2$S is initiator, %3$S is target URL, %4$S is target IP, %5$S is port, %6$S is mechanism (e.g., fetch, xhr, websocket), %7$S is secure context (true or false), %8$S is prompt action (values: "Allow", "Deny", or "(empty)" if no prompt shown)
LocalNetworkAccessDetected = دسترسی به شبکهٔ محلی شناسایی شد: سایت سطح بالا «%1$S»، آغازگر «%2$S»، دسترسی به هدف «%3$S» (%4$S:%5$S) از طریق %6$S. بافت امن: %7$S، کنش درخواست: %8$S
# LOCALIZATION NOTE (LocalNetworkAccessPermissionRequired): %1$S is top-level site, %2$S is initiator, %3$S is target URL, %4$S is target IP, %5$S is port, %6$S is mechanism (e.g., fetch, xhr, websocket), %7$S is secure context (true or false)
LocalNetworkAccessPermissionRequired = مجوز دسترسی به شبکهٔ محلی لازم است: سایت سطح بالا «%1$S»، آغازگر «%2$S»، تلاش برای دسترسی به هدف «%3$S» (%4$S:%5$S) از طریق %6$S. بافت امن: %7$S
