# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = این صفحهٔ وب در حال تغییر مسیر به مکان جدیدی است. آیا می‌خواهید اطلاعات فرمی که وارد کرده‌اید مجدداً به مکان جدید ارسال شود؟
# Directory listing strings
DirTitle = نمایهٔ ‪%1$S‬
DirGoUp = رفتن به شاخهٔ یک سطح بالاتر
ShowHidden = نمایش موارد مخفی
DirColName = نام
DirColSize = اندازه
DirColMTime = زمان آخرین تغییر
DirFileLabel = پرونده:\u0020
UnsafeUriBlocked = منبع «%1$S» توسط «مرور امن» مسدود شد.
# As part of dynamic state partitioning, third-party resources might be limited to "partitioned" storage access that is separate from the first-party context.
# This allows e.g. cookies to still be set, and prevents tracking without totally blocking storage access. This message is shown in the web console when this happens
# to inform developers that their storage is isolated.
CookiePartitionedForeign2 = دسترسی افراز شدهٔ کلوچک یا ذخیره‌گاه به «%1$S» ارائه شده، چون در محتوای سوم‌شخص بار شده و افرازش حالت پویا به کار افتاده است.
