# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = การเข้าสู่ระบบที่บันทึกไว้
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = คัดลอก URL
    .accesskey = ค
launch-site-url-cmd =
    .label = เยี่ยมชม URL
    .accesskey = ย
copy-username-cmd =
    .label = คัดลอกชื่อผู้ใช้
    .accesskey = ล
edit-username-cmd =
    .label = แก้ไขชื่อผู้ใช้
    .accesskey = ข
copy-password-cmd =
    .label = คัดลอกรหัสผ่าน
    .accesskey = ด
edit-password-cmd =
    .label = แก้ไขรหัสผ่าน
    .accesskey = ก
search-filter =
    .accesskey = ค
    .placeholder = ค้นหา
column-heading-site =
    .label = ไซต์
column-heading-username =
    .label = ชื่อผู้ใช้
column-heading-password =
    .label = รหัสผ่าน
column-heading-time-created =
    .label = วันที่ใช้ครั้งแรก
column-heading-time-last-used =
    .label = วันที่ใช้ครั้งล่าสุด
column-heading-time-password-changed =
    .label = วันที่เปลี่ยนแปลงล่าสุด
column-heading-times-used =
    .label = จำนวนครั้งที่ใช้
remove =
    .label = เอาออก
    .accesskey = อ
import =
    .label = นำเข้า…
    .accesskey = น
close-button =
    .label = ปิด
    .accesskey = ป
show-passwords =
    .label = แสดงรหัสผ่าน
    .accesskey = ส
hide-passwords =
    .label = ซ่อนรหัสผ่าน
    .accesskey = ร
logins-description-all = การเข้าสู่ระบบสำหรับไซต์ดังต่อไปนี้ถูกจัดเก็บไว้ในคอมพิวเตอร์ของคุณ
logins-description-filtered = การเข้าสู่ระบบดังต่อไปนี้ตรงกับที่คุณค้นหา:
remove-all =
    .label = เอาทั้งหมดออก
    .accesskey = ท
remove-all-shown =
    .label = เอาที่แสดงทั้งหมดออก
    .accesskey = ท
remove-all-passwords-prompt = คุณแน่ใจหรือไม่ว่าต้องการเอารหัสผ่านทั้งหมดออก?
remove-all-passwords-title = เอารหัสผ่านทั้งหมดออก
no-master-password-prompt = คุณแน่ใจหรือไม่ว่าต้องการแสดงรหัสผ่านของคุณ?
auto-fill-logins-and-passwords =
    .label = กรอกข้อมูลการเข้าสู่ระบบและรหัสผ่านอัตโนมัติ
