# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Hüquqlarınız Haqqında
rights-intro = { -brand-full-name }, dünya səviyyəsində minlərlə insandan ibarət bir birlik tərəfindən inkişaf etdirilən azad və açıq qaynaqlı bir proqramdır. Bilməli olduğunuz bir neçə şey var:
rights-intro-point-1 = { -brand-short-name } <a data-l10n-name="mozilla-public-license-link">Mozilla İctimai Lisenziyası</a> ilə yayımlanmaqdadır. Yəni { -brand-short-name } sərbəst şəkildə istifadə oluna bilər, köçürülə bilər və parçalana bilər. Və ehtiyaclarınıza görə { -brand-short-name } qaynaq kodlarını da dəyişdirə bilərsiniz. Mozilla İctimai Lisenziyası, dəyişdirdiyiniz versiyaları yaymaq haqqını da sizə verir.
rights-intro-point-3 = { -brand-short-name } səyyahınızdakı Çökmə Xəbərçisi kimi bəzi funksiyalar sizə { -vendor-short-name } üçün əks əlaqə vermə imkanı verir. Əks əlaqə verməyi seçməklə { -vendor-short-name } tərəfinə məhsullarını inkişaf etdirmək üçün bu məlumatı istifadə etmə, verdiyiniz əks əlaqəni saytlarında nəşr etmək və əks əlaqənizlə bölüşmək icazəsi vermiş olursunuz.
rights-intro-point-4 = Şəxsi məlumat və əks əlaqənizi { -brand-short-name } ilə { -vendor-short-name }-ya göndərdiyinizdə necə istifadə etdiyimiz <a data-l10n-name="mozilla-privacy-policy-link">{ -brand-short-name } Məxfilik Siyasətində</a> təsvir edilib.
rights-intro-point-5 = Bəzi { -brand-short-name } funksiyaları veb əsaslı məlumat xidmətlərindən yararlanır, ancaq bunların 100% doğru və ya xətasız olduğuna zəmanət verə bilmərik. Daha ətraflı və həmçinin bu xidmətlərin necə söndürülməsi haqqında məlumatı buradan tapa bilərsiz:<a data-l10n-name="mozilla-service-terms-link">xidmət şərtləri</a>açıqlanmışdır.
rights-intro-point-6 = Bəzi video məzmunları oxutmaq üçün { -brand-short-name } bəzi üçüncü tərəf məzmun dekodlaşdırma modullarını endirir.
rights-webservices = { -brand-full-name } bu cütlük { -brand-short-name } versiyasında istifadənizə verilən bəzi funksiyalar üçün, aşağıda açıqlanan şərtlər əsasında web əsaslı məlumat xidmətlərindən ("Servislər") faydalanır. Xidmətlərdən birini və ya bir neçəsini istifadə etmək istəmirsinizsə və ya aşağıdakı şərtləri qəbul etmirsinizsə müvafiq funksiyanı və Xidmət(lər)i deaktiv edə bilərsiniz. Funksiya və Xidmətləri deaktiv etmək üçün təlimatlar <a data-l10n-name="mozilla-disable-service-link">buradan baxa bilərsiniz</a>. Digər xüsusiyətlər və Servislər tətbiqetmə seçimlərindən deaktiv edilə bilərlər.
rights-locationawarebrowsing = <strong>Vəziyyətə həssas baxış: </strong>həmişə sizin istəyinizlə işləyər.  İcazəniz olmadan heç vaxt mövqe məlumatlarınız göndərilməyib.  Əgər funksiyanı tamamən söndürmək istəyirsinizsə bu addımları təkrarlayın:
rights-locationawarebrowsing-term-1 = Ünvan sətirinə bunu yazın: URL <code>about:config</code>
rights-webservices-term-unbranded = Bu məhsulla bağlı bütün xidmət şərtləri burada yazılmalıdır.
rights-webservices-term-4 = <strong>Servislər "olduqları kimi" təmin olunur.  { -vendor-short-name }, ona yardım edənlər, lisenziya sahibləri və paylayıcılar, servislərin ticari dəyəri olduğu və ehtiyyaclarına uyğun olacağı barədə yazılı və ya sözlü hər hansı bir sığorta verməz.  Ehtiyaclarınızı qarşılamaq üçün Servisləri seçsəniz keyfiyyət və performans ilə bağlı bütün risklər sizə aiddir. Bəzı qanunlar sığortaların xaric tutulmasına və ya məhdudlaşdırılmasına icazə verməyə bilər. Bu halda bu şərtlər sizin üçün keçərli olmayacaqdır.</strong>
rights-webservices-term-5 = <strong>Qanunun tələb etdiyi vaxtlar xaric, { -vendor-short-name }, onun dəstəkçiləri, lisenziya sahibləri və yayanlar { -brand-short-name } və Servislərinin işlənməsindən yarana biləcək hər hansı bir dolayı, xüsusi, təsadüfi, sonradan yaranan, ağır və ya nümunəvi xəsardan cavabdeh deyillər.  Bu şərtlər altında kollektiv cəza $500 (beş yüz USD) üzəri ola bilməz. Bəzi yurisdiksiyalar məlum zərərlərin istisna hal olmasına və ya limitlənməsinə icazə vermirlər, bu səbəbdən bu istisna və limitləmə sizin üçün keçərli olmaya bilər.</strong>
