# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Apie jūsų teises
rights-intro-point-1 = Jums leidžiama naudotis „{ -brand-short-name }“ programa, vadovaujantis <a data-l10n-name="mozilla-public-license-link">„Mozilla“ viešąja licencija (Mozilla Public License)</a>. Ši licencija leidžia naudotis „{ -brand-short-name }“ programa, ją dauginti ir platinti.  Be to, galite laisvai modifikuoti programos pirminius tekstus. Licencija nedraudžia platinti ir jūsų modifikuotų programos versijų.
rights-intro-point-3 = Kai kurios „{ -brand-short-name }“ savybės, pavyzdžiui, strigčių pranešiklis, suteikia galimybę siųsti atsiliepimus „{ -vendor-short-name }i“. Siųsdami atsiliepimus, jūs suteikiate „{ -vendor-short-name }i“ teisę jais naudotis savo kuriamų produktų tobulinimo tikslais, skelbti juos savo svetainėse ir platinti juos kitais būdais.
rights-intro-point-6 = Kad galėtų atkurti tam tikrus vaizdo turinio formatus, „{ -brand-short-name }“ parsisiunčia tam tikrus turinio iššifravimo modulius iš trečiųjų šalių.
rights-webservices-unbranded = Čia turėtų būti pateiktas šioje programoje naudojamų saityno paslaugų aprašas bei instrukcijos, kaip šių paslaugų naudojimo atsisakyti, jei tai įmanoma.
rights-webservices-term-3 = Jūs esate kviečiami naudotis šiomis Paslaugomis su šia „{ -brand-short-name }“ laida, ir „{ -vendor-short-name }“ jums suteikia visas jos turimas tam reikalingas teises.  „{ -vendor-short-name }“ ir jos licencijų išdavėjai pasilieka visas kitas su Paslaugomis susijusias teises.  Šiomis taisyklėmis nesiekiama apriboti teisių, kurias jums suteikia programai „{ -brand-short-name }“ ir jos pirminiams tekstams taikoma atvirųjų programų licencija.
rights-webservices-term-5 = <strong>Išskyrus kiek to reikalauja įstatymai, „{ -vendor-short-name }“, jos bendradarbiai, licencijų išdavėjai ir platintojai nebus laikomi atsakingais už bet kokią netiesioginę, tyčinę, netyčinę, pasėkminę, baudžiamąją ar kitokią žalą, kilusią dėl „{ -brand-short-name }“ ir Paslaugų naudojimo ar bet kokiu būdu su tuo susijusią.  Pagal šias taisykles, kolektyvinė atsakomybė negali viršyti 500 (penkių šimtų) JAV dolerių.  Kai kuriose jurisdikcijose atsiriboti nuo kai kurių tipų žalos neleidžiama, tad gali būti, kad jums ši taisyklė negalioja.</strong>
rights-webservices-term-6 = Kilus poreikiui, „{ -vendor-short-name }“ šias taisykles gali keisti. Be raštiško „Mozillos“ sutikimo šios taisyklės negali būti taisomos ar atšaukiamos.
