# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = "%S" fidagarritzat jo nahi duzu ondoko helburu hauetarako?
unnamedCA = Autoritate ziurtagiri emailea (izenik gabe)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Idatzi ziurtagiriaren babeskopia hau zifratzeko erabili zen pasahitza:
# Page Info
pageInfo_NoEncryption = Konexioa zifratu gabe
pageInfo_Privacy_None1 = %S webguneak ez du onartzen ikusten ari zaren orriaren zifratzea.
pageInfo_Privacy_None2 = Interneten zifratu gabe bidalitako informazioa, batetik bestera dabilenean, beste norbaitek ikus dezake.
pageInfo_Privacy_None4 = Ikusten ari zaren orria ez da zifratu Internetetik transmititu aurretik.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Konexioa zifratuta (%1$S, %2$S biteko gakoak, %3$S)
pageInfo_BrokenEncryption = Zifraketa hautsia (%1$S, %2$S biteko gakoak, %3$S)
pageInfo_Privacy_Encrypted1 = Ikusten ari zaren orria zifratu egin da Internetetik transmititu aurretik.
pageInfo_Privacy_Encrypted2 = Ordenagailuen artean transmititzen den informazioa baimenik gabeko pertsonek ikustea zailtzen du zifratzeak. Horrela ia ezinezkoa da sarean zehar dabilela inork orri hau hau irakurtzea.
pageInfo_MixedContent = Konexioa erdizka zifratuta
pageInfo_MixedContent2 = Ikusten ari zaren orriaren zati batzuk ez dira zifratu Internetetik transmititu aurretik.
pageInfo_WeakCipher = Gune honetarako zure konexioak zifraketa ahula erabiltzen du eta ez da pribatua. Besteek zure informazioa ikusi edo webgunearen portaera alda lezakete.
pageInfo_CertificateTransparency_Compliant = Webgune honek ziurtagirien gardentasun-politika betetzen du.
# Token Manager
password_not_set = (ezarri gabe)
