# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Titouroù kennaskañ enrollet
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Eilañ an URL
    .accesskey = i
launch-site-url-cmd =
    .label = Gweladennin an URL
    .accesskey = G
copy-username-cmd =
    .label = Eilañ an anv arveriad
    .accesskey = a
edit-username-cmd =
    .label = Embann an anv arveriad
    .accesskey = m
copy-password-cmd =
    .label = Eilañ ar ger-tremen
    .accesskey = E
edit-password-cmd =
    .label = Embann ar ger-tremen
    .accesskey = E
search-filter =
    .accesskey = K
    .placeholder = Klask
column-heading-site =
    .label = Lec'hienn
column-heading-username =
    .label = Anv arveriad
column-heading-password =
    .label = Ger-tremen
column-heading-time-created =
    .label = Arver kentañ
column-heading-time-last-used =
    .label = Arver diwezhañ
column-heading-time-password-changed =
    .label = Kemm diwezhañ
column-heading-times-used =
    .label = Niver a arverioù
remove =
    .label = Dilemel
    .accesskey = l
import =
    .label = Import…
    .accesskey = I
close-button =
    .label = Serriñ
    .accesskey = r
show-passwords =
    .label = Diskouez ar gerioù-tremen
    .accesskey = D
hide-passwords =
    .label = Kuzhat ar gerioù-tremen
    .accesskey = K
logins-description-all = Gwaredet eo an titouroù kennaskañ evit al lec'hiennoù da heul war hoc'h urzhiataer
logins-description-filtered = An titouroù kennaskañ a glot gant ho klask :
remove-all =
    .label = Dilemel pep tra
    .accesskey = t
remove-all-shown =
    .label = Dilemel an holl re ziskouezet
    .accesskey = D
remove-all-passwords-prompt = Ha sur oc'h e fell deoc'h lemel kuit an holl c'herioù-tremen ?
remove-all-passwords-title = Dilemel an holl c'herioù-tremen
no-master-password-prompt = Ha sur oc'h ho peus c'hoant da ziskouez ho kerioù-tremen ?
auto-fill-logins-and-passwords =
    .label = Leuniañ an titouroù kennaskañ ent emgefreek
