# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = תם הזמן המוקצב
openFile = פתיחת קובץ
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = חיפוש ב־%1$S אחר ”%2$S“
contextMenuSearch.accesskey = ח
contextMenuPrivateSearch = חיפוש בחלון פרטי
contextMenuPrivateSearch.accesskey = ח
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = חיפוש באמצעות %S בחלון פרטי
contextMenuPrivateSearchOtherEngine.accesskey = ח
bookmarkAllTabsDefault = [שם תיקייה]
unsignedAddonsDisabled.message = אחת או יותר מהתוספות המותקנות אינה ניתנת לאימות ולכן נוטרלה.
unsignedAddonsDisabled.learnMore.label = מידע נוסף
unsignedAddonsDisabled.learnMore.accesskey = מ
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = זמן גישה אחרון %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = קישורי %S://‎
crashedpluginsMessage.title = התוסף החיצוני %S קרס.
crashedpluginsMessage.reloadButton.label = טעינת דף מחדש
crashedpluginsMessage.reloadButton.accesskey = מ
crashedpluginsMessage.submitButton.label = שליחת דיווח קריסה
crashedpluginsMessage.submitButton.accesskey = ק
crashedpluginsMessage.learnMore = מידע נוסף…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = האם התכוונת להגיע אל %S?
keywordURIFixup.goTo = כן, נא להעביר אותי אל %S
keywordURIFixup.goTo.accesskey = כ
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = עדכון לגרסה %S
update.downloadAndInstallButton.accesskey = ע
menuOpenAllInTabs.label = פתיחת הכל בלשוניות
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = טעינה מחדש של דף זה
tabHistory.goBack = חזור לדף זה
tabHistory.goForward = התקדם לדף זה
# URL Bar
pasteAndGo.label = הדבקה ומעבר
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = טעינה מחדש של דף נוכחי (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = הפסקת טעינת דף נוכחי (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = איפוס הגדרות מרחק מתצוגה (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = הפעלה/כיבוי של תצוגת קריאה (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, איפוס הגדרות מרחק מתצוגה
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = הצגת הסימניות שלך (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = הצגת ההתקדמות של ההורדות הפעילות (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = פתיחת חלון חדש (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = פתיחת לשונית חדשה (%S)
newTabContainer.tooltip = פתיחת לשונית חדשה (%S)\nיש ללחוץ לחיצה ארוכה כדי לפתוח מגירת לשוניות חדשה
newTabAlwaysContainer.tooltip = בחירת מגירה לפתיחת לשונית חדשה
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = לאפשר ל־%S להשתמש בנתוני התמונות שלך ממשטחי ציור ב־HTML5?
canvas.siteprompt2.warning = נתונים אלה יכולים לשמש לזיהוי המחשב שלך באופן נקודתי.
canvas.block = לחסום
canvas.block.accesskey = ח
canvas.allow2 = לאפשר
canvas.allow2.accesskey = א
canvas.remember2 = שמירת הבחירה הזו
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = אומת על־ידי %S
identity.identified.verified_by_you = הוספת חריגת אבטחה לאתר זה.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = האישור הונפק עבור: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = לא מאובטח
identity.notSecure.tooltip = החיבור אינו מאובטח
identity.extension.label = הרחבה (%S)
identity.extension.tooltip = נטען על־ידי ההרחבה: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = התרחקות ‎(%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = איפוס הגדרות מרחק מתצוגה (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = התקרבות ‎(%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = גזירה (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = העתקה (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = הדבקה (%S)
geolocation.allow = לאפשר
geolocation.allow.accesskey = א
geolocation.block = לחסום
geolocation.block.accesskey = ח
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = פעולה זו תפתח את הגדרות המיקום של המערכת. נא להעניק הרשאת מיקום ל־%S.
geolocation.shareWithSite4 = לאפשר ל־%S לגשת לנתוני המיקום שלך?
geolocation.shareWithFile4 = לאפשר לקובץ מקומי זה לגשת לנתוני המיקום שלך?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = לאפשר ל־%1$S לתת ל־%2$S הרשאה לגשת לנתוני המיקום שלך?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = נא להעניק הרשאת מיקום ל־%S בהגדרות המערכת.
geolocation.systemSettingsTitle = בהמתנה להרשאת מיקום
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = המערכת תבקש ממך להעניק הרשאה זו ל־%S.
geolocation.remember = שמירת הבחירה הזו
# Virtual Reality Device UI
xr.allow2 = לאפשר
xr.allow2.accesskey = א
xr.block = לחסום
xr.block.accesskey = ח
xr.shareWithSite4 = לאפשר ל־%S לגשת למכשירי מציאות מדומה? זה עשוי לחשוף מידע רגיש.
xr.shareWithFile4 = לאפשר לקובץ מקומי זה לגשת למכשירי מציאות מדומה? זה עשוי לחשוף מידע רגיש.
xr.remember = שמירת הבחירה הזו
# Persistent storage UI
persistentStorage.allow = לאפשר
persistentStorage.allow.accesskey = א
persistentStorage.block.label = לחסום
persistentStorage.block.accesskey = ח
persistentStorage.allowWithSite2 = לאפשר ל־%S לשמור נתונים באחסון הקבוע?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = לאפשר
webNotifications.allow2.accesskey = א
webNotifications.notNow = לא כעת
webNotifications.notNow.accesskey = ל
webNotifications.never = לעולם לא
webNotifications.never.accesskey = ע
webNotifications.alwaysBlock = תמיד לחסום
webNotifications.alwaysBlock.accesskey = ת
webNotifications.block = לחסום
webNotifications.block.accesskey = ח
webNotifications.receiveFromSite3 = לאפשר ל־%S לשלוח התרעות?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = האתר %S רוצה לגשת ליישומים ושירותים במכשיר זה.
localhost.remember2 = שמירת הבחירה שלי עבור אתר זה
localhost.allowlabel = לאפשר
localhost.blocklabel = לחסום
localhost.allow.accesskey = א
localhost.block.accesskey = ח
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = האתר %S רוצה לגשת ליישומים ושירותים במכשירים המחוברים לרשת המקומית שלך.
localNetwork.remember2 = שמירת הבחירה שלי עבור אתר זה
localNetwork.allowLabel = לאפשר
localNetwork.allow.accesskey = א
localNetwork.blockLabel = לחסום
localNetwork.block.accesskey = ח
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = קחו אותי מכאן!
safebrowsing.getMeOutOfHereButton.accessKey = ק
safebrowsing.deceptiveSite = אתר מטעה!
safebrowsing.notADeceptiveSiteButton.label = אתר זה אינו אתר מטעה…
safebrowsing.notADeceptiveSiteButton.accessKey = ט
safebrowsing.reportedAttackSite = אתר תקיפה מדווח!
safebrowsing.notAnAttackButton.label = אתר זה אינו אתר תקיפה…
safebrowsing.notAnAttackButton.accessKey = א
safebrowsing.reportedUnwantedSite = אתר תוכנה לא רצויה מדווח!
safebrowsing.reportedHarmfulSite = אתר שדווח כמזיק!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = חיפוש ב־%S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = להפעיל את %S מחדש במצב לפתרון בעיות?
troubleshootModeRestartPromptMessage = ההרחבות, ערכות הנושא וההגדרות המותאמות אישית שלך יושבתו באופן זמני.
troubleshootModeRestartButton = הפעלה מחדש
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = דף זה מאט את %1$S. כדי להאיץ את הדפדפן שלך, כדאי לעצור דף זה.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = דף אינטרנט מאט את %1$S. כדי להאיץ את הדפדפן שלך, כדאי לעצור דף זה.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = ‏“%1$S” מאט את %2$S. כדי להאיץ את הדפדפן שלך, כדאי לעצור דף זה.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = ההרחבה “%1$S” מאטה את %2$S. כדי להאיץ את הדפדפן שלך, כדאי לעצור הרחבה זו.
processHang.add-on.learn-more.text = מידע נוסף
processHang.button_stop2.label = עצירה
processHang.button_stop2.accessKey = ע
processHang.button_debug.label = ניפוי שגיאות בתסריט
processHang.button_debug.accessKey = נ
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = הצגת החלון במסך מלא (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = העברת סרגל הצד לשמאל
sidebar.moveToRight = העברת סרגל הצד לימין
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = עליך להפעיל את רכיב ניהול זכויות הקניין (DRM) כדי להשמיע אודיו או לצפות בווידאו בדף זה.
emeNotifications.drmContentDisabled.button.label = הפעלת ניהול זכויות קניין
emeNotifications.drmContentDisabled.button.accesskey = ז
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S מתקין כעת רכיבים הנחוצים כדי לנגן אודיו או וידאו בדף זה. נא להמתין ולנסות שוב מאוחר יותר.
emeNotifications.unknownDRMSoftware = לא ידוע
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = התאמה אישית של %S
decoder.noCodecs.button = מידע נוסף
decoder.noCodecs.accesskey = מ
decoder.noCodecsLinux.message = כדי לנגן וידאו יתכן שיהיה עליך להתקין את מפעני הווידאו הנדרשים.
decoder.noHWAcceleration.message = כדי לשפר את איכות הווידאו יתכן שיהיה עליך להתקין את חבילת תכונות המדיה מבית Microsoft.
decoder.noPulseAudio.message = כדי להשמיע קול, נדרשת התקנת היישום PulseAudio.
decoder.unsupportedLibavcodec.message = libavcodec כנראה חשוף לסכנות או אינו נתמך, ויש לעדכנו כדי לנגן וידאו.
decoder.decodeError.message = אירעה תקלה בעת פענוח משאב מדיה.
decoder.decodeError.button = דיווח על בעיה באתר
decoder.decodeError.accesskey = ב
decoder.decodeWarning.message = אירעה שגיאה במהלך פענוח משאב מדיה.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = עליך להתחבר לרשת זו לפני שתוכל לגלוש באינטרנט.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = פתיחת דף התחברות לרשת
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = הרשאות עבור %S
permissions.remove.tooltip = השבתת הרשאה זו והצגת השאלה שוב
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64 סיביות
aboutDialog.architecture.thirtyTwoBit = 32 סיביות
midi.allow.label = לאפשר
midi.allow.accesskey = א
midi.block.label = לחסום
midi.block.accesskey = ח
midi.remember = שמירת הבחירה הזו
midi.shareWithFile = לאפשר לקובץ המקומי הזה לגשת להתקני ה־MIDI שלך?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = לאפשר ל־%S לגשת להתקני ה־MIDI שלך?
midi.shareSysexWithFile = לאפשר לקובץ המקומי הזה לגשת להתקני ה־MIDI שלך ולשלוח/לקבל הודעות SysEx?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = לאפשר ל־%S לגשת להתקני ה־MIDI שלך ולשלוח/לקבל הודעות SysEx?
serial.allow.label = לאפשר
serial.allow.accesskey = א
serial.block.label = לחסום
serial.block.accesskey = ח
serial.shareWithFile = לאפשר לקובץ מקומי זה לגשת ליציאות הטוריות שלך?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = לאפשר ל־%S לגשת ליציאות הטוריות שלך?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = חזרה
storageAccess1.Allow.label = לאפשר
storageAccess1.Allow.accesskey = א
storageAccess1.DontAllow.label = לחסום
storageAccess1.DontAllow.accesskey = ח
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = לאפשר ל־%1$S להשתמש בעוגיות שלו ב־%2$S?
storageAccess1.hintText = אם לא ברור לך מדוע %1$S זקוק לנתונים האלו, ייתכן שכדאי לחסום את הגישה.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = חיפוש ברשת עבור ״%S״
