# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

3 = هونی جۊره %1$S…
4 = و %1$S منپیز وابی…
5 = هونی درخاست ن افشنه و %1$S…
6 = هونی داده یل ن جاگورو اکونه ز %1$S…
7 = هونی منپیز ابۊوه و %1$S…
8 = %1$S خونده وابی
9 = %1$S هؽل وابی
10 = مندیر سی %1$S…
11 = هونی جۊره %1$S…
# Directory listing strings
DirTitle = پوروفایل %1$S
DirColName = نوم
DirColSize = هندا
DirColMTime = آلشتکاری دیندایی
DirFileLabel = فایل:
