# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

appmenu-update-available2 =
    .label = ᱦᱟᱹᱞᱤᱭᱟᱹᱜ ᱢᱮᱱᱟᱜᱼᱟ
    .buttonlabel = ᱰᱟᱩᱱᱞᱚᱰ
    .buttonaccesskey = D
    .secondarybuttonlabel = ᱵᱚᱸᱫ ᱪᱷᱚ
    .secondarybuttonaccesskey = m
appmenu-update-available-message2 = { -brand-shorter-name } ᱨᱮᱭᱟᱜ ᱱᱮᱼᱱᱮ ᱦᱟᱹᱞᱤᱭᱟᱹᱠ ᱰᱟᱩᱱᱞᱚᱰ ᱢᱮ ᱾
appmenu-update-manual2 =
    .label = ᱦᱟᱹᱞᱤᱭᱟᱹᱜ ᱢᱮᱱᱟᱜᱼᱟ
    .buttonlabel = ᱰᱟᱩᱱᱞᱚᱰ
    .buttonaccesskey = D
    .secondarybuttonlabel = ᱵᱚᱸᱫ
    .secondarybuttonaccesskey = m
appmenu-update-manual-message2 = { -brand-shorter-name } ᱟᱡ ᱛᱮ ᱵᱟᱝ ᱦᱟᱹᱞᱤᱭᱟᱹᱠ ᱞᱮᱱᱟ ᱾ ᱱᱟᱶᱟ ᱦᱟᱹᱞᱤᱭᱟᱹᱠ ᱰᱟᱩᱱᱞᱳᱰ ᱢᱮ — ᱟᱢ ᱫᱚ ᱥᱟᱺᱪᱟᱣ ᱠᱟᱱ ᱡᱤᱱᱤᱥ ᱵᱟᱝᱠᱷᱟᱱ ᱢᱚᱱᱮᱛᱮᱭᱟᱜ ᱡᱤᱱᱤᱥ ᱠᱚ ᱵᱟᱝ ᱟᱫᱟ ᱾
appmenu-update-unsupported2 =
    .label = ᱦᱟᱹᱞᱤᱭᱟᱹᱠ ᱵᱟᱝ ᱜᱟᱱ ᱞᱮᱱᱟ
    .buttonlabel = ᱰᱷᱮᱨ ᱪᱮᱫ ᱢᱮ
    .buttonaccesskey = L
    .secondarybuttonlabel = ᱵᱚᱹᱫ
    .secondarybuttonaccesskey = m
appmenu-update-unsupported-message2 = ᱟᱢᱟᱜ ᱠᱟᱹᱢᱤ ᱥᱭᱥᱴᱚᱢ ᱫᱚ ᱱᱟᱶᱟ ᱦᱟᱹᱞᱤᱭᱟᱹᱠ { -brand-shorter-name } ᱥᱟᱞᱟᱜ ᱵᱟᱹᱭ ᱠᱟᱹᱢᱤᱭᱟᱭ ᱾
appmenu-update-restart2 =
    .label = ᱦᱟᱹᱞᱤᱭᱟᱹᱜ ᱢᱮᱱᱟᱜᱼᱟ
    .buttonlabel = ᱦᱟᱹᱞᱤᱭᱟᱹᱜ ᱟᱨ ᱨᱤᱥᱴᱟᱴ
    .buttonaccesskey = U
    .secondarybuttonlabel = ᱵᱚᱸᱫ
    .secondarybuttonaccesskey = m
appmenu-update-restart-message2 = { -brand-shorter-name } ᱨᱮᱭᱟᱜ ᱱᱮᱼᱱᱮ ᱦᱟᱹᱞᱤᱭᱟᱹᱠ ᱦᱟᱢᱮᱴ ᱢᱮ ᱾ ᱠᱷᱩᱞᱟᱹ ᱴᱮᱵᱽ ᱟᱨ ᱣᱤᱱᱰᱳ ᱠᱚ ᱫᱚ ᱫᱩᱦᱲᱟᱹ ᱫᱚᱦᱚᱜᱼᱟ ᱾
appmenu-update-other-instance =
    .label = { -brand-shorter-name } ᱫᱚ ᱱᱟᱶᱟ ᱵᱷᱟᱹᱨᱥᱚᱱ ᱛᱮ ᱟᱡ ᱛᱮ ᱵᱟᱭ ᱦᱟᱹᱞᱤᱭᱟᱹᱠᱚᱜ ᱫᱟᱲᱮᱭᱟᱫᱟ ᱾
    .buttonlabel = ᱡᱮᱞᱠᱟᱛᱮ { -brand-shorter-name } ᱛᱮ ᱦᱟᱹᱞᱤᱭᱟᱹᱠ ᱢᱮ
    .buttonaccesskey = U
    .secondarybuttonlabel = ᱱᱤᱛᱚᱜ ᱫᱚ ᱵᱟᱝᱟ
    .secondarybuttonaccesskey = N
appmenu-update-other-instance-message = ᱢᱤᱫᱴᱟᱹᱝ ᱱᱟᱶᱟ { -brand-shorter-name } ᱦᱟᱹᱞᱤᱭᱟᱹᱠ ᱢᱮᱱᱟᱜᱼᱟ, ᱢᱮᱱᱠᱷᱟᱱ { -brand-shorter-name } ᱨᱮᱭᱟᱜ ᱮᱴᱟᱜ ᱱᱚᱠᱚᱞ ᱢᱮᱱᱟᱜ ᱠᱷᱟᱹᱛᱤᱨ ᱵᱚᱦᱟᱞ ᱵᱟᱭ ᱜᱟᱱᱚᱜᱼᱟ ᱾ ᱦᱟᱹᱞᱤᱭᱟᱹᱠ ᱛᱮ ᱞᱟᱦᱟᱜ ᱞᱟᱹᱜᱤᱫ ᱵᱚᱸᱫᱚᱭ ᱢᱮ, ᱟᱨᱵᱟᱝᱠᱷᱟᱱ ᱡᱟᱦᱟᱺᱱ ᱞᱮᱠᱷᱟ ᱛᱮᱜᱮ ᱦᱟᱹᱞᱤᱭᱟᱹᱠ ᱞᱟᱹᱜᱤᱫ ᱵᱟᱪᱷᱟᱣ ᱢᱮ (ᱫᱩᱦᱲᱟᱹ ᱮᱛᱦᱚᱵ ᱵᱟᱝ ᱵᱷᱩᱨ ᱮᱴᱟᱜ ᱱᱚᱠᱚᱞ ᱫᱚ ᱴᱷᱤᱠ ᱥᱮ ᱵᱟᱭ ᱠᱟᱹᱢᱤᱟᱭ) ᱾
appmenu-addon-private-browsing-installed2 =
    .buttonlabel = ᱴᱷᱤᱠ ᱜᱮ
    .buttonaccesskey = ᱴ
appmenu-addon-post-install-message3 = ᱮᱯᱞᱤᱠᱮᱥᱚᱱ ᱢᱮᱱᱩ ᱛᱮ ᱮᱰᱼᱚᱱᱥ ᱟᱨ ᱛᱷᱤᱢ ᱠᱚ ᱢᱮᱱᱮᱡᱽ ᱢᱮ ᱾
appmenu-addon-post-install-incognito-checkbox =
    .label = ᱱᱤᱡᱚᱨ ᱣᱤᱱᱰᱳ ᱨᱮ ᱱᱚᱶᱟ ᱵᱤᱥᱤᱞ ᱦᱮᱸᱥᱮᱨᱤᱭᱟᱹ ᱪᱷᱚᱭ ᱢᱮ
    .accesskey = A
appmenu-new-tab-controlled-changes =
    .label = ᱟᱢᱟᱜ ᱱᱟᱶᱟ ᱴᱮᱵᱽ ᱵᱚᱫᱚᱞ ᱮᱱᱟ ᱾
    .buttonlabel = ᱵᱚᱫᱚᱞ ᱠᱚ ᱫᱚᱦᱚᱭ ᱢᱮ
    .buttonaccesskey = K
    .secondarybuttonlabel = ᱱᱟᱶᱟ ᱴᱮᱵᱽ ᱥᱚᱢᱵᱷᱲᱟᱣ ᱢᱮ
    .secondarybuttonaccesskey = M
appmenu-homepage-controlled-changes =
    .label = ᱟᱢᱟᱜ ᱚᱲᱟᱜ ᱥᱟᱦᱴᱟ ᱫᱚᱵᱚᱫᱚᱞ ᱮᱱᱟ ᱾
    .buttonlabel = ᱵᱚᱫᱚᱞ ᱠᱚ ᱫᱚᱦᱚᱭ ᱢᱮ
    .buttonaccesskey = K
    .secondarybuttonlabel = ᱚᱲᱟᱜ ᱥᱟᱦᱴᱟ ᱥᱚᱢᱵᱷᱲᱟᱣ ᱢᱮ
    .secondarybuttonaccesskey = M
appmenu-tab-hide-controlled =
    .label = ᱟᱢᱟᱜ ᱩᱠᱩ ᱴᱮᱵᱽ ᱠᱚ ᱟᱫᱮᱨ ᱢᱮ
    .buttonlabel = ᱩᱠᱩ ᱠᱟᱱ ᱴᱮᱵᱽ ᱠᱚ ᱫᱚᱦᱚᱭ ᱢᱮ
    .buttonaccesskey = K
    .secondarybuttonlabel = ᱵᱤᱥᱤᱞ ᱵᱚᱸᱫᱚᱭ ᱢᱮ
    .secondarybuttonaccesskey = D
