# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = ᱡᱷᱤᱡᱽ ᱢᱮ
    .accesskey = O
places-open-in-tab =
    .label = ᱱᱟᱶᱟ ᱴᱮᱵᱽ ᱨᱮ ᱡᱷᱤᱡᱽ ᱢᱮ
    .accesskey = w
places-open-all-bookmarks =
    .label = ᱡᱷᱚᱛᱚ ᱵᱩᱠᱢᱟᱨᱠ ᱡᱷᱤᱡᱽ ᱢᱮ
    .accesskey = O
places-open-all-in-tabs =
    .label = ᱡᱚᱛᱚ ᱴᱮᱵᱽ ᱠᱚ ᱡᱷᱤᱡᱽ ᱢᱮ
    .accesskey = O
places-view =
    .label = ᱧᱮᱞ ᱢᱮ
    .accesskey = w
places-by-date =
    .label = ᱢᱟᱹᱦᱤᱛ ᱫᱟᱨᱟᱭ ᱛᱮ
    .accesskey = D
places-by-site =
    .label = ᱥᱟᱭᱤᱴ ᱫᱟᱨᱟᱭ ᱛᱮ
    .accesskey = S
places-by-most-visited =
    .label = ᱟᱹᱰᱤ ᱰᱷᱮᱨ ᱧᱮᱞ ᱫᱟᱨᱟᱭ ᱛᱮ
    .accesskey = V
places-by-last-visited =
    .label = ᱢᱤᱪᱟᱹᱫ ᱧᱮᱞ ᱫᱟᱨᱟᱭ ᱛᱮ
    .accesskey = L
places-by-day-and-site =
    .label = ᱢᱟᱹᱦᱤᱛ ᱟᱨ ᱥᱟᱭᱤᱴ ᱫᱟᱨᱟᱭ ᱛᱮ
    .accesskey = t
places-history =
    .aria-label = ᱱᱟᱜᱟᱢ
places-delete-domain-data =
    .label = ᱱᱚᱣᱟ ᱥᱟᱦᱴᱟ ᱵᱟᱵᱚᱛ ᱛᱮ ᱦᱤᱲᱤᱧ ᱢᱮ
    .accesskey = F
places-sortby-name =
    .label = ᱧᱩᱛᱩᱢ ᱫᱟᱨᱟᱭ ᱛᱮ ᱡᱷᱤᱡᱽ ᱢᱮ
    .accesskey = r
places-library =
    .title = ᱯᱩᱛᱷᱤ ᱚᱲᱟᱜ
    .style = width:700px; height:500px;
places-organize-button =
    .label = ᱥᱟᱡᱟᱣ
    .tooltiptext = ᱟᱢᱟᱜ ᱯᱩᱛᱷᱤ ᱪᱤᱱᱦᱟᱹ ᱠᱚ ᱥᱟᱡᱟᱣ
    .accesskey = O
places-organize-button-mac =
    .label = ᱥᱟᱡᱟᱣ
    .tooltiptext = ᱟᱢᱟᱜ ᱯᱩᱛᱷᱤ ᱪᱤᱱᱦᱟᱹ ᱠᱚ ᱥᱟᱡᱟᱣ
places-file-close =
    .label = ᱵᱚᱸᱫᱚᱭ ᱢᱮ
    .accesskey = C
places-cmd-close =
    .key = w
places-view-button =
    .label = ᱧᱮᱞ ᱠᱚ
    .tooltiptext = ᱟᱢᱟᱜ ᱧᱮᱞ ᱵᱚᱫᱚᱞ ᱢᱮ
    .accesskey = V
places-view-button-mac =
    .label = ञेंल
    .tooltiptext = आमाक् ञेंल बोदोल मे
places-view-menu-columns =
    .label = ᱠᱟᱛᱷᱟ ᱠᱚ ᱩᱫᱩᱜ
    .accesskey = C
places-view-menu-sort =
    .label = साला
    .accesskey = S
places-view-sort-unsorted =
    .label = बाङ साला
    .accesskey = U
places-view-sort-ascending =
    .label = A > Z थार ते साला
    .accesskey = A
places-view-sort-descending =
    .label = Z > A थार ते साला
    .accesskey = Z
places-maintenance-button =
    .label = ᱟᱹᱜᱩ ᱵᱮᱠᱚᱯᱷ ᱛᱮᱭᱟᱨ
    .tooltiptext = ᱟᱢᱟᱜ ᱯᱩᱛᱷᱤ ᱪᱤᱱᱦᱟᱹ ᱠᱚ ᱟᱹᱜᱩ ᱟᱨ ᱵᱮᱠᱟᱹᱯ
    .accesskey = I
places-maintenance-button-mac =
    .label = ᱟᱹᱜᱩ ᱵᱮᱠᱚᱯᱷ ᱛᱮᱭᱟᱨ
    .tooltiptext = ᱟᱢᱟᱜ ᱵᱩᱠᱢᱟᱨᱠ ᱠᱚ ᱟᱹᱜᱩ ᱵᱮᱠᱚᱯᱷ ᱛᱮᱭᱟᱨ
places-cmd-backup =
    .label = ᱱᱚᱠᱚᱞ ᱡᱚᱜᱟᱣ…
    .accesskey = B
places-cmd-restore =
    .label = ᱫᱩᱦᱲᱟᱹ ᱡᱚᱜᱟᱣ
    .accesskey = R
places-cmd-restore-from-file =
    .label = ᱨᱮᱫ ᱵᱟᱪᱷᱟᱣ ᱢᱮ…
    .accesskey = C
places-import-bookmarks-from-html =
    .label = HTML ᱠᱷᱚᱱ ᱯᱩᱛᱷᱤ ᱪᱤᱱᱦᱟᱹ ᱠᱚ ᱟᱹᱜᱩ…
    .accesskey = I
places-export-bookmarks-to-html =
    .label = HTML ᱛᱮ ᱯᱩᱛᱷᱤ ᱪᱤᱱᱦᱟᱹ ᱠᱚ ᱵᱷᱮᱡᱟ…
    .accesskey = E
places-import-other-browser =
    .label = एटागाक् ब्राउजार खोन डाटा आ़गु …
    .accesskey = A
places-view-sort-col-name =
    .label = ञुतुम
places-view-sort-col-tags =
    .label = ᱛᱚᱞ ᱠᱚ:
places-view-sort-col-url =
    .label = ठांव
places-view-sort-col-most-recent-visit =
    .label = आ़डिसुराक् ञेल
places-view-sort-col-visit-count =
    .label = लेखा ञुल मे
places-view-sort-col-date-added =
    .label = सेलेद काना
places-view-sort-col-last-modified =
    .label = मुचा़त् रे बोदोल लेन
places-cmd-find-key =
    .key = f
places-back-button =
    .tooltiptext = तायोम चालाक् मे
places-forward-button =
    .tooltiptext = माड़ाङ सेत् चालाक् मे
places-details-pane-select-an-item-description = ᱢᱤᱫ ᱡᱤᱱᱤᱥ ᱟᱨ ᱚᱱᱟ ᱨᱮᱭᱟᱜ ᱜᱩᱱ ᱠᱚ ᱧᱮᱞ ᱟᱨ ᱥᱟᱥᱟᱯᱲᱟᱣ ᱞᱟᱹᱜᱤᱫ ᱵᱟᱪᱷᱟᱣ ᱢᱮ ᱾
