# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = झिच्
    .accesskey = O
places-open-all-in-tabs =
    .label = टेब रे जोतो  झिज मे
    .accesskey = O
places-view =
    .label = ञेल मे
    .accesskey = w
places-by-date =
    .label = मा़हित् दाराय ते
    .accesskey = D
places-by-site =
    .label = साइड दाराय ते .
    .accesskey = S
places-by-most-visited =
    .label = आ़डी ढेर ञेल दाराय ते
    .accesskey = V
places-by-last-visited =
    .label = मुचा़द ञेल दाराय ते.
    .accesskey = L
places-by-day-and-site =
    .label = मा़हित् आर साइट दाराय ते
    .accesskey = t
places-history =
    .aria-label = ᱱᱟᱜᱟᱢ
places-delete-domain-data =
    .label = नोवा साइड बाबोत ते हिंड़िग मे
    .accesskey = F
places-sortby-name =
    .label = ञुतुम दाराय ते झिज  मे
    .accesskey = r
places-library =
    .title = पुथी ओड़ाक्
    .style = width:700px; height:500px;
places-cmd-close =
    .key = w
places-view-sort-ascending =
    .label = A > Z थार ते साला
    .accesskey = A
places-view-sort-descending =
    .label = Z > A थार ते साला
    .accesskey = Z
places-view-sort-col-name =
    .label = ञुतुम
places-view-sort-col-tags =
    .label = तोल को
places-view-sort-col-url =
    .label = ठांव
places-view-sort-col-most-recent-visit =
    .label = आ़डिसुराक् ञेल
places-view-sort-col-visit-count =
    .label = लेखा ञुल मे
places-view-sort-col-date-added =
    .label = सेलेद काना
places-view-sort-col-last-modified =
    .label = मुचा़त् रे बोदोल लेन
places-cmd-find-key =
    .key = f
places-back-button =
    .tooltiptext = तायोम चालाक् मे
places-forward-button =
    .tooltiptext = माड़ाङ सेत् चालाक् मे
places-details-pane-select-an-item-description = मित् जिनिस आर ओना रेयाक् गुन को ञेल आर सासापड़ाव ला़गित् बाछाव मे  .
