# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-connected = Connectit tae { $host }…
network-connection-status-sending-request = Sendin speirin tae { $host }…
network-connection-status-transferring-data = Flittin data fae { $host }…
network-connection-status-connecting = Connectin tae { $host }…
network-connection-status-read = Read { $host }
network-connection-status-wrote = Scrieved { $host }
network-connection-status-waiting = Waitin on { $host }…
network-connection-status-looked-up = Luiked up { $host }…
