# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Vrijeme je isteklo
openFile = Otvori datoteku
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Traži „%2$S” pomoću %1$S
contextMenuSearch.accesskey = S
contextMenuPrivateSearch = Pretraži u privatnom prozoru
contextMenuPrivateSearch.accesskey = P
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Traži pomoću %S u privatnom prozoru
contextMenuPrivateSearchOtherEngine.accesskey = s
bookmarkAllTabsDefault = [Ime mape]
unsignedAddonsDisabled.message = Jedan ili više dodataka nije moguće verificirati, stoga su deaktivirani.
unsignedAddonsDisabled.learnMore.label = Saznaj više
unsignedAddonsDisabled.learnMore.accesskey = z
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Zadnji pristup %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = %S:// poveznice
crashedpluginsMessage.title = Dodatak %S se srušio.
crashedpluginsMessage.reloadButton.label = Ponovo učitaj stranicu
crashedpluginsMessage.reloadButton.accesskey = r
crashedpluginsMessage.submitButton.label = Pošalji izvještaj o prekidu rada programa
crashedpluginsMessage.submitButton.accesskey = š
crashedpluginsMessage.learnMore = Saznaj više …
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Jeste li mislili otići na %S?
keywordURIFixup.goTo = Da, odvedi me na %S
keywordURIFixup.goTo.accesskey = D
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Aktualiziraj na %S
update.downloadAndInstallButton.accesskey = u
menuOpenAllInTabs.label = Otvori sve u karticama
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Ponovo učitaj ovu stranicu
tabHistory.goBack = Natrag na ovu stranicu
tabHistory.goForward = Idi naprijed na ovu stranicu
# URL Bar
pasteAndGo.label = Umetni i kreni
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Ponovo učitaj trenutačnu stranicu (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Zaustavi učitavanje stranice (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Resetiraj zumiranje (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Uključivanje prikaza čitača (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S %%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, Poništi razinu zumiranja
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Prikaži tvoje zabilješke (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Prikaži napredak aktivnih preuzimanja (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Otvori novi prozor (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Otvori novu karticu (%S)
newTabContainer.tooltip = Otvori novu karticu (%S)\nPritisni i drži pritisnutim za otvaranje nove kontejnerske kartice
newTabAlwaysContainer.tooltip = Odaberi kontejner za otvaranje nove kartice
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Dopustiti da %S koristi tvoje podatke slike HTML5 platna?
canvas.siteprompt2.warning = Ovo se može koristiti za jedinstvenu identifikaciju tvog računala.
canvas.block = Blokiraj
canvas.block.accesskey = B
canvas.allow2 = Dopusti
canvas.allow2.accesskey = D
canvas.remember2 = Zapamti ovu odluku
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Potvrđeno od: %S
identity.identified.verified_by_you = Dodali ste sigurnosnu iznimku za ovu stranicu
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Certifikat izdan za: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Nije sigurno
identity.notSecure.tooltip = Veza nije sigurna
identity.extension.label = Dodaci (%S)
identity.extension.tooltip = Učitano dodatkom: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Umanji (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Resetiraj zumiranje (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Uvećaj (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Izreži (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Kopiraj (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Umetni (%S)
geolocation.allow = Dopusti
geolocation.allow.accesskey = D
geolocation.block = Blokiraj
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Ovo će otvoriti postavke lokacije sustava. Dajte dozvolu za lokaciju %Su.
geolocation.shareWithSite4 = Dopustiti da %S pristupi tvom mjestu?
geolocation.shareWithFile4 = Dopustiti ovoj lokalnoj datoteci da pristupi tvom mjestu?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Dopustiti %1$S da dopusti %2$S pristup tvom mjestu?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Dodijeli %Su dozvolu za lokaciju u postavkama sustava.
geolocation.systemSettingsTitle = Čekanje dozvole za lokaciju
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Sustav će od vas tražiti da date dopuštenje %Su.
geolocation.remember = Zapamti moju odluku
# Virtual Reality Device UI
xr.allow2 = Dopusti
xr.allow2.accesskey = D
xr.block = Blokiraj
xr.block.accesskey = B
xr.shareWithSite4 = Dopustiti stranici %S pristup uređajima virtualne stvarnosti? Ovo može izložiti osjetljive informacije.
xr.shareWithFile4 = Dopustiti ovoj lokalnoj datoteci pristup uređajima virtualne stvarnosti? Ovo može izložiti osjetljive informacije.
xr.remember = Zapamti ovu odluku
# Persistent storage UI
persistentStorage.allow = Dozvoli
persistentStorage.allow.accesskey = D
persistentStorage.block.label = Blokiraj
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Dopustiti stranici %S spremanje podataka u trajnu pohranu?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Dopusti
webNotifications.allow2.accesskey = D
webNotifications.notNow = Ne sad
webNotifications.notNow.accesskey = N
webNotifications.never = Nikada ne dozvoli
webNotifications.never.accesskey = k
webNotifications.alwaysBlock = Uvijek blokiraj
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = Blokiraj
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Dopustiti %S da šalje obavijesti?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S želi pristupiti drugim aplikacijama i uslugama na ovom uređaju.
localhost.remember2 = Zapamti moj izbor za ovu web-stranicu
localhost.allowlabel = Dozvoli
localhost.blocklabel = Blokiraj
localhost.allow.accesskey = D
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S želi pristupiti aplikacijama i uslugama na uređajima koji su spojeni na tvoju lokalnu mrežu.
localNetwork.remember2 = Zapamti moj izbor za ovu stranicu
localNetwork.allowLabel = Dozvoli
localNetwork.allow.accesskey = D
localNetwork.blockLabel = Blokiraj
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Izvuci me odavdje!
safebrowsing.getMeOutOfHereButton.accessKey = I
safebrowsing.deceptiveSite = Obmanjujuća stranica!
safebrowsing.notADeceptiveSiteButton.label = Ovo nije obmanjujuća stranica…
safebrowsing.notADeceptiveSiteButton.accessKey = o
safebrowsing.reportedAttackSite = Prijavi zloćudnu stranicu!
safebrowsing.notAnAttackButton.label = Ovo nije zloćudna stranica…
safebrowsing.notAnAttackButton.accessKey = n
safebrowsing.reportedUnwantedSite = Prijava stranice s neželjenim softverom!
safebrowsing.reportedHarmfulSite = Prijavljena zlonamjerna stranica!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Traži %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Ponovo pokrenuti %S u modusu za rješavanje problema?
troubleshootModeRestartPromptMessage = Tvoja proširenja, teme i prilagođene postavke privremeno će biti onemogućene.
troubleshootModeRestartButton = Ponovno pokreni
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Ova stranica usporava %1$S. Za ubrzanje preglednika, zaustavi ovu stranicu.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Jedna web stranica usporava %1$S. Za ubrzanje preglednika zaustavi tu stranicu.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = “%1$S” usporava %2$S. Za ubrzanje preglednika, zaustavi tu stranicu.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = “%1$S” usporava %2$S. Za ubrzanje preglednika, zaustavi to proširenje.
processHang.add-on.learn-more.text = Saznaj više
processHang.button_stop2.label = Zaustavi
processHang.button_stop2.accessKey = Z
processHang.button_debug.label = Ispravi greške u skripti
processHang.button_debug.accessKey = g
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Prikaži prozor u cjeloekranskom prikazu (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Premjesti bočnu traku na lijevu stranu
sidebar.moveToRight = Premjesti bočnu traku na desnu stranu
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Za reprodukciju nekih audiosnimaka ili videa na ovoj stranici moraš aktivirati DRM.
emeNotifications.drmContentDisabled.button.label = Aktiviraj DRM
emeNotifications.drmContentDisabled.button.accesskey = O
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S instalira komponente potrebne za reproduciranje audio ili video materijala na ovoj stranici. Pokušaj kasnije ponovo.
emeNotifications.unknownDRMSoftware = Nepoznato
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Prilagodi %S
decoder.noCodecs.button = Saznaj kako
decoder.noCodecs.accesskey = z
decoder.noCodecsLinux.message = Da biste reproducirali video, možda ćete trebati instalirati potrebne video kodeke.
decoder.noHWAcceleration.message = Za poboljšavanje kvalitete videa možda moraš instalirati Microsoftov Media Feature Pack.
decoder.noPulseAudio.message = Za reprodukciju videa ćeš možda morati instalirati potreban PulseAudio softver.
decoder.unsupportedLibavcodec.message = libavcodec je možda ranjiv ili nije podržan i za prikaz videa, trebao bi se aktualizirati.
decoder.decodeError.message = Pojavila se greška tijekom dekodiranja medijskog resursa.
decoder.decodeError.button = Prijavi problem sa stranicom
decoder.decodeError.accesskey = r
decoder.decodeWarning.message = Pojavila se greška koja se može ispraviti tijekom dekodiranja medijskog resursa.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Moraš se prijaviti na ovu mrežu, ako želiš koristiti internet.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Otvaranje stranice prijave na mrežu
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Dozvole za %S
permissions.remove.tooltip = Izbriši ovu dozvolu i pitaj ponovo
permissions.fullscreen.promptCanceled = Prekinuti su čekajući zahtjevi za dozvolom: zahtjevi za dozvolom se ne bi trebali izdavati prije ulaska u DOM prikaz preko cijelog ekrana.
permissions.fullscreen.fullScreenCanceled = Prekinut je DOM prikaz preko cijelog ekrana: zahtjevi za dozvolom se ne bi trebali izdavati za vrijeme rada u DOM prikazu preko cijelog ekrana.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bitni
aboutDialog.architecture.thirtyTwoBit = 32-bitni
midi.allow.label = Dopusti
midi.allow.accesskey = D
midi.block.label = Blokiraj
midi.block.accesskey = B
midi.remember = Zapamti ovu odluku
midi.shareWithFile = Dopustiti ovoj lokalnoj datoteci pristup tvojim MIDI uređajima?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Dopustiti %S pristup tvojim MIDI uređajima?
midi.shareSysexWithFile = Dopustiti ovoj lokalnoj datoteci pristup tvojim MIDI uređajima i slanje/primanje SysEx poruka?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Dopustiti %S pristup tvojim MIDI uređajima i slanje/primanje SysEx poruka?
serial.allow.label = Dozvoli
serial.allow.accesskey = D
serial.block.label = Blokiraj
serial.block.accesskey = B
serial.shareWithFile = Dopustiti ovoj lokalnoj datoteci pristup tvojim serijskim portovima?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Dopustiti da %S pristupi tvojem serijskom portu?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Natrag
storageAccess1.Allow.label = Dopusti
storageAccess1.Allow.accesskey = D
storageAccess1.DontAllow.label = Blokiraj
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Dopusti %1$S da koristi svoje kolačiće na %2$S?
storageAccess1.hintText = Vjerojatno ćeš htjeti blokirati pristup ukoliko nije jasno zašto %1$S treba ove podatke.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Pretražite web za “%S”
