# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Vill du lita på “%S” för följande syften?
unnamedCA = Certifikatutfärdare (namnlös)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Ange det lösenord som användes för att kryptera denna backup av certifikat:
# Page Info
pageInfo_NoEncryption = Anslutningen är ej krypterad
pageInfo_Privacy_None1 = Webbplatsen %S stöder inte kryptering av sidan som visas.
pageInfo_Privacy_None2 = Information som skickas över Internet utan kryptering kan under överföringen läsas av obehöriga personer.\u0020
pageInfo_Privacy_None4 = Sidan du visar krypterades inte innan den skickades över internet.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Anslutning krypterad (%1$S, %2$S bitar, %3$S)
pageInfo_BrokenEncryption = Skadad kryptering (%1$S, %2$S bitars nyckel, %3$S)
pageInfo_Privacy_Encrypted1 = Sidan som visas krypterades innan den skickades över Internet.
pageInfo_Privacy_Encrypted2 = Kryptering gör det svårt för obehöriga personer att se information som skickas mellan datorer. Det är därför osannolikt att någon läste denna sida när den skickades över nätverket.
pageInfo_MixedContent = Anslutningen är delvis krypterad
pageInfo_MixedContent2 = Delar av sidan som visas krypterades inte innan den skickades över Internet.
pageInfo_WeakCipher = Anslutningen till denna webbplats använder en dålig kryptering och är inte privat. Andra personer kan se din information eller ändra webbplatsens beteende.
pageInfo_CertificateTransparency_Compliant = Denna webbplats följer certifikatpolicyn om insyn.
# Token Manager
password_not_set = (ej valt)
