# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host } көрдөөһүн…
network-connection-status-connected = Манна холбонно { $host }…
network-connection-status-sending-request = Манна ыйытык ыытыы { $host }…
network-connection-status-transferring-data = Мантан дааннай ылыы { $host }…
network-connection-status-connecting = Манна холбонуу { $host }…
network-connection-status-read = Ааҕыы { $host }
network-connection-status-wrote = Суруйуу { $host }
network-connection-status-waiting = Маны кэтэһэр { $host }…
network-connection-status-looked-up = { $host } көһүннэ…
