# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Pretečen čas
openFile = Odpri datoteko
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Išči "%2$S" z iskalnikom %1$S
contextMenuSearch.accesskey = I
contextMenuPrivateSearch = Išči v zasebnem oknu
contextMenuPrivateSearch.accesskey = č
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Išči z iskalnikom %S v zasebnem oknu
contextMenuPrivateSearchOtherEngine.accesskey = č
bookmarkAllTabsDefault = [ime mape]
unsignedAddonsDisabled.message = Enega ali več nameščenih dodatkov ni bilo mogoče potrditi, zato so bili onemogočeni.
unsignedAddonsDisabled.learnMore.label = Več o tem
unsignedAddonsDisabled.learnMore.accesskey = V
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Zadnji dostop %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = Povezave %S://
crashedpluginsMessage.title = Vtičnik %S se je sesul.
crashedpluginsMessage.reloadButton.label = Ponovno naloži stran
crashedpluginsMessage.reloadButton.accesskey = O
crashedpluginsMessage.submitButton.label = Pošlji poročilo o sesutju
crashedpluginsMessage.submitButton.accesskey = S
crashedpluginsMessage.learnMore = Več o tem …
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Ali ste želeli obiskati %S?
keywordURIFixup.goTo = Da, odpri %S
keywordURIFixup.goTo.accesskey = D
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Posodobi na %S
update.downloadAndInstallButton.accesskey = P
menuOpenAllInTabs.label = Odpri vse v zavihkih
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Ponovno naloži stran
tabHistory.goBack = Pojdi nazaj na to stran
tabHistory.goForward = Pojdi naprej na to stran
# URL Bar
pasteAndGo.label = Prilepi in odpri
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Ponovno naloži trenutno stran (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Ustavi nalaganje te strani (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Ponastavi povečavo (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Vklopi/izklopi bralni pogled (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S %%, ponastavi raven povečave
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Prikaži zaznamke (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Prikaži napredek prenosov v teku (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Odpri novo okno (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Odpri nov zavihek (%S)
newTabContainer.tooltip = Odprite nov zavihek (%S)\nPritisnite in pridržite, da odprete nov vsebniški zavihek
newTabAlwaysContainer.tooltip = Izberi vsebnik za odpiranje novega zavihka
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Dovolite %S, da uporablja vaše slikovne podatke HTML5 canvas?
canvas.siteprompt2.warning = Ta podatek se lahko uporabi za enolično prepoznavo vašega računalnika.
canvas.block = Zavrni
canvas.block.accesskey = Z
canvas.allow2 = Dovoli
canvas.allow2.accesskey = D
canvas.remember2 = Zapomni si to odločitev
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Overil: %S
identity.identified.verified_by_you = Za to stran ste dodali varnostno izjemo
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Potrdilo izdano: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Ni varno
identity.notSecure.tooltip = Povezava ni varna
identity.extension.label = Razširitev (%S)
identity.extension.tooltip = Naložila razširitev: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Pomanjšaj (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Ponastavi povečavo (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Povečaj (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Izreži (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Kopiraj (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Prilepi (%S)
geolocation.allow = Dovoli
geolocation.allow.accesskey = D
geolocation.block = Zavrni
geolocation.block.accesskey = Z
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = To bo odprlo sistemske nastavitve lokacije. Podelite %Su dovoljenje za uporabo lokacije.
geolocation.shareWithSite4 = Dovolite %S dostop do vaše lokacije?
geolocation.shareWithFile4 = Dovolite tej krajevni datoteki dostop do vaše lokacije?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Dovolite %1$S, da %2$S omogoči dostop do vaše lokacije?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = V sistemskih nastavitvah %Su podelite dovoljenje za uporabo lokacije.
geolocation.systemSettingsTitle = Čakanje na dovoljenje za lokacijo
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Sistem vas bo prosil za dodelitev tega dovoljenja %Su.
geolocation.remember = Zapomni si to odločitev
# Virtual Reality Device UI
xr.allow2 = Dovoli
xr.allow2.accesskey = D
xr.block = Zavrni
xr.block.accesskey = Z
xr.shareWithSite4 = Dovolite strani %S dostop do naprav navidezne resničnosti? To lahko izpostavi občutljive podatke.
xr.shareWithFile4 = Dovolite tej krajevni datoteki dostop do naprav navidezne resničnosti? To lahko izpostavi občutljive podatke.
xr.remember = Zapomni si to odločitev
# Persistent storage UI
persistentStorage.allow = Dovoli
persistentStorage.allow.accesskey = D
persistentStorage.block.label = Zavrni
persistentStorage.block.accesskey = Z
persistentStorage.allowWithSite2 = Dovolite strani %S shranjevanje podatkov v trajno shrambo?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Dovoli
webNotifications.allow2.accesskey = D
webNotifications.notNow = Ne zdaj
webNotifications.notNow.accesskey = n
webNotifications.never = Nikoli ne dovoli
webNotifications.never.accesskey = i
webNotifications.alwaysBlock = Vedno zavrni
webNotifications.alwaysBlock.accesskey = V
webNotifications.block = Zavrni
webNotifications.block.accesskey = Z
webNotifications.receiveFromSite3 = Dovolite strani %S pošiljanje obvestil?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S zahteva dostop do drugih aplikacij in storitev na tej napravi.
localhost.remember2 = Zapomni si izbiro za to spletno mesto
localhost.allowlabel = Dovoli
localhost.blocklabel = Zavrni
localhost.allow.accesskey = D
localhost.block.accesskey = Z
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S zahteva dostop do aplikacij in storitev na napravah, povezanih v vaše lokalno omrežje.
localNetwork.remember2 = Zapomni si izbiro za to spletno mesto
localNetwork.allowLabel = Dovoli
localNetwork.allow.accesskey = D
localNetwork.blockLabel = Zavrni
localNetwork.block.accesskey = Z
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Hočem stran!
safebrowsing.getMeOutOfHereButton.accessKey = H
safebrowsing.deceptiveSite = Zavajajoča stran!
safebrowsing.notADeceptiveSiteButton.label = To ni zavajajoča stran …
safebrowsing.notADeceptiveSiteButton.accessKey = n
safebrowsing.reportedAttackSite = Napadalna stran!
safebrowsing.notAnAttackButton.label = To ni napadalna stran …
safebrowsing.notAnAttackButton.accessKey = N
safebrowsing.reportedUnwantedSite = Morebitna stran z neželeno programsko opremo!
safebrowsing.reportedHarmfulSite = Prijavljena škodljiva stran!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Išči %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Znova zaženi %S v načinu za odpravljanje težav?
troubleshootModeRestartPromptMessage = Vaše razširitve, teme in nastavitve bodo začasno onemogočene.
troubleshootModeRestartButton = Ponovno zaženi
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Ta stran upočasnjuje %1$S. Brskalnik lahko razbremenite tako, da jo ustavite.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Ena od spletnih strani upočasnjuje %1$S. Brskalnik lahko razbremenite tako, da jo ustavite.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = Stran »%1$S« upočasnjuje %2$S. Brskalnik lahko razbremenite tako, da jo ustavite.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = Razširitev »%1$S« upočasnjuje %2$S. Brskalnik lahko razbremenite tako, da jo ustavite.
processHang.add-on.learn-more.text = Več o tem
processHang.button_stop2.label = Ustavi
processHang.button_stop2.accessKey = U
processHang.button_debug.label = Razhroščevanje skripta
processHang.button_debug.accessKey = R
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Prikaži okno čez celoten zaslon (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Premakni stransko vrstico na levo
sidebar.moveToRight = Premakni stransko vrstico na desno
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Za predvajanje zvoka ali videa na tej strani morate omogočiti DRM.
emeNotifications.drmContentDisabled.button.label = Omogoči DRM
emeNotifications.drmContentDisabled.button.accesskey = O
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S namešča komponente, ki so potrebne za predvajanje zvoka ali videa na tej strani. Poskusite znova pozneje.
emeNotifications.unknownDRMSoftware = Neznano
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Prilagodi %S
decoder.noCodecs.button = Naučite se, kako
decoder.noCodecs.accesskey = N
decoder.noCodecsLinux.message = Za predvajanje videoposnetka boste morda morali namestiti zahtevane videokodeke.
decoder.noHWAcceleration.message = Za izboljšanje kakovosti slike boste morda morali namestiti Microsoftov paket predstavnostnih funkcij.
decoder.noPulseAudio.message = Za predvajanje zvoka boste morda morali namestiti zahtevano programsko opremo PulseAudio.
decoder.unsupportedLibavcodec.message = libavcodec je morda ranljiv ali ni posodobljen. Posodobite ga za predvajanje videoposnetkov.
decoder.decodeError.message = Med dekodiranjem vira predstavnosti je prišlo do napake.
decoder.decodeError.button = Prijavi napako strani
decoder.decodeError.accesskey = P
decoder.decodeWarning.message = Med dekodiranjem vira predstavnosti je prišlo do popravljive napake.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Preden lahko dostopate do interneta, se morate prijaviti v omrežje.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Odpri stran za prijavo v omrežje
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Dovoljenja za %S
permissions.remove.tooltip = Počisti to dovoljenje in znova vprašaj
permissions.fullscreen.promptCanceled = Čakanje na zahteve za dovoljenje je preklicano: zahtev za dovoljenje ne smete izdati pred vstopom v celozaslonski način DOM.
permissions.fullscreen.fullScreenCanceled = Celoten zaslon DOM končan: zahtev za dovoljenje ne bi smeli izdajati, ko ste v celotnem zaslonu DOM.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bitni
aboutDialog.architecture.thirtyTwoBit = 32-bitni
midi.allow.label = Dovoli
midi.allow.accesskey = D
midi.block.label = Zavrni
midi.block.accesskey = Z
midi.remember = Zapomni si to odločitev
midi.shareWithFile = Dovolite lokalni datoteki dostop do vaših naprav MIDI?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Dovolite strani %S dostop do vaših naprav MIDI?
midi.shareSysexWithFile = Dovolite lokalni datoteki dostop do vaših naprav MIDI in pošiljanje/prejemanje sporočil SysEx?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Dovolite strani %S dostop do vaših naprav MIDI in pošiljanje/prejemanje sporočil SysEx?
serial.allow.label = Dovoli
serial.allow.accesskey = D
serial.block.label = Zavrni
serial.block.accesskey = Z
serial.shareWithFile = Dovolite tej krajevni datoteki dostop do vaših zaporednih vrat?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Dovolite strani %S dostop do vaših zaporednih vrat?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Nazaj
storageAccess1.Allow.label = Dovoli
storageAccess1.Allow.accesskey = D
storageAccess1.DontAllow.label = Zavrni
storageAccess1.DontAllow.accesskey = Z
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Ali dovolite %1$S uporabo svojih piškotkov na %2$S?
storageAccess1.hintText = Če ni jasno, zakaj %1$S potrebuje te podatke, lahko zavrnete dostop.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Išči "%S" na spletu
