# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = ई वेब पृष्ठ नव स्थानमे फेर प्रेषित कएल जाए रहल अछि. की अहाँ फार्म आंकड़ा केँ फेर पठोअनाइ चाहैत छी जकरा अहाँ नव स्थान मे फेर टाइप कएने छी?
# Directory listing strings
DirTitle = Index of %1$S
DirGoUp = उच्चतर स्तर निर्देशिका धरि
ShowHidden = नुकाएल वस्तु देखाबैछ
DirColName = नाम
DirColSize = आकार
DirColMTime = अंतिम रूपांतरित
DirFileLabel = फाइल:\u0020
