# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Innflutningshjálp
import-from =
    { PLATFORM() ->
        [windows] Flytja inn stillingar, bókamerki, ferla, lykilorð og önnur gögn frá:
       *[other] Flytja inn stillingar, bókamerki, ferla, lykilorð og önnur gögn frá:
    }
import-from-bookmarks = Flytja inn bókamerki frá:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-nothing =
    .label = Flytja ekkert inn
    .accesskey = e
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = x
import-from-360se =
    .label = 360 Öruggur vafri
    .accesskey = 3
no-migration-sources = Engin forrit fundust sem gætu innihaldið bókamerki, ferill eða lykilorð.
import-source =
    .label = Flytja inn stillingar og gögn
import-items-title =
    .label = Hlutir til að flytja inn
import-items-description = Veldu hvaða hluti þú vilt flytja inn:
import-migrating-title =
    .label = Flyt inn…
import-migrating-description = Verið er að flytja inn eftirfarandi hluti…
import-select-profile-title =
    .label = Veldu notanda
import-select-profile-description = Hægt er að flytja eftirfarandi notendur inn frá:
import-done-title =
    .label = Innflutningi lokið
import-done-description = Eftirfarandi hluti tókst að flytja inn:
import-close-source-browser = Gakktu úr skugga um að valinn vafri sé lokaður áður en haldið er áfram.
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = Frá { $source }
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Öruggur vafri
imported-safari-reading-list = Leslisti (Frá Safari)
imported-edge-reading-list = Leslisti (Frá Edge)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Internet stillingar
    .value = Internet stillingar
browser-data-edge-1 =
    .label = Stillingar
    .value = Stillingar
browser-data-safari-1 =
    .label = Valkostir
    .value = Valkostir
browser-data-chrome-1 =
    .label = Valkostir
    .value = Valkostir
browser-data-canary-1 =
    .label = Valkostir
    .value = Valkostir
browser-data-360se-1 =
    .label = Valkostir
    .value = Valkostir
browser-data-ie-2 =
    .label = Smákökur
    .value = Smákökur
browser-data-edge-2 =
    .label = Smákökur
    .value = Smákökur
browser-data-safari-2 =
    .label = Smákökur
    .value = Smákökur
browser-data-chrome-2 =
    .label = Smákökur
    .value = Smákökur
browser-data-canary-2 =
    .label = Smákökur
    .value = Smákökur
browser-data-firefox-2 =
    .label = Smákökur
    .value = Smákökur
browser-data-360se-2 =
    .label = Smákökur
    .value = Smákökur
browser-data-ie-4 =
    .label = Ferill vafra
    .value = Ferill vafra
browser-data-edge-4 =
    .label = Ferill vafra
    .value = Ferill vafra
browser-data-safari-4 =
    .label = Ferill vafra
    .value = Ferill vafra
browser-data-chrome-4 =
    .label = Ferill vafra
    .value = Ferill vafra
browser-data-canary-4 =
    .label = Ferill vafra
    .value = Ferill vafra
browser-data-firefox-history-and-bookmarks-4 =
    .label = Skoða feril og bókamerki
    .value = Skoða feril og bókamerki
browser-data-360se-4 =
    .label = Ferill vafra
    .value = Ferill vafra
browser-data-ie-8 =
    .label = Vistaðir eyðublaða ferlar
    .value = Vistaðir eyðublaða ferlar
browser-data-edge-8 =
    .label = Vistaðir eyðublaða ferlar
    .value = Vistaðir eyðublaða ferlar
browser-data-safari-8 =
    .label = Vistaðir eyðublaða ferlar
    .value = Vistaðir eyðublaða ferlar
browser-data-chrome-8 =
    .label = Vistaðir eyðublaða ferlar
    .value = Vistaðir eyðublaða ferlar
browser-data-canary-8 =
    .label = Vistaðir eyðublaða ferlar
    .value = Vistaðir eyðublaða ferlar
browser-data-firefox-8 =
    .label = Vistaðir eyðublaða ferlar
    .value = Vistaðir eyðublaða ferlar
browser-data-360se-8 =
    .label = Vistaðir eyðublaða ferlar
    .value = Vistaðir eyðublaða ferlar
browser-data-ie-16 =
    .label = Vistuð lykilorð
    .value = Vistuð lykilorð
browser-data-edge-16 =
    .label = Vistuð lykilorð
    .value = Vistuð lykilorð
browser-data-safari-16 =
    .label = Vistuð lykilorð
    .value = Vistuð lykilorð
browser-data-chrome-16 =
    .label = Vistuð lykilorð
    .value = Vistuð lykilorð
browser-data-canary-16 =
    .label = Vistuð lykilorð
    .value = Vistuð lykilorð
browser-data-firefox-16 =
    .label = Vistuð lykilorð
    .value = Vistuð lykilorð
browser-data-360se-16 =
    .label = Vistuð lykilorð
    .value = Vistuð lykilorð
browser-data-ie-32 =
    .label = Uppáhald
    .value = Uppáhald
browser-data-edge-32 =
    .label = Uppáhald
    .value = Uppáhald
browser-data-safari-32 =
    .label = Bókamerki
    .value = Bókamerki
browser-data-chrome-32 =
    .label = Bókamerki
    .value = Bókamerki
browser-data-canary-32 =
    .label = Bókamerki
    .value = Bókamerki
browser-data-360se-32 =
    .label = Bókamerki
    .value = Bókamerki
browser-data-ie-64 =
    .label = Önnur gögn
    .value = Önnur gögn
browser-data-edge-64 =
    .label = Önnur gögn
    .value = Önnur gögn
browser-data-safari-64 =
    .label = Önnur gögn
    .value = Önnur gögn
browser-data-chrome-64 =
    .label = Önnur gögn
    .value = Önnur gögn
browser-data-canary-64 =
    .label = Önnur gögn
    .value = Önnur gögn
browser-data-firefox-other-64 =
    .label = Önnur gögn
    .value = Önnur gögn
browser-data-360se-64 =
    .label = Önnur gögn
    .value = Önnur gögn
browser-data-firefox-128 =
    .label = Gluggar og flipar
    .value = Gluggar og flipar
