# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

fxa-toolbar-sync-syncing =
    .label = Er að samstilla…
fxa-toolbar-sync-syncing-tabs =
    .label = Samstilli flipa…
fxa-toolbar-sync-syncing2 = Er að samstilla…
fxa-menu-connect-another-device =
    .label = Tengja annað tæki…
