#filter emptyLines

#define MOZ_LANGPACK_CREATOR Mozilla-fy-NL

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
# #define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Wim Benes</em:contributor><em:contributor>Tim Maks van den Broek</em:contributor><em:contributor>leden FryskeSoftware forum</em:contributor>

#unfilter emptyLines
