# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Vrei să acorzi încredere „%S” în următoarele scopuri?
unnamedCA = Autoritate de certificare (fără nume)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Te rugăm să introduci parola cu care s-a criptat această copie de siguranță a certificatelor:
# Page Info
pageInfo_NoEncryption = Conexiune necriptată
pageInfo_Privacy_None1 = Site-ul web %S nu suportă criptare pentru pagina pe care o vezi.
pageInfo_Privacy_None2 = Informațiile trimise prin internet fără criptare pot fi văzute și de alte persoane în timpul tranzitului.
pageInfo_Privacy_None4 = Pagina pe care o vezi a fost criptată înainte de a fi trimisă prin internet.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Conexiune criptată (%1$S, chei pe %2$S biți, %3$S)
pageInfo_BrokenEncryption = Criptare nesigură (%1$S, chei pe %2$S biți, %3$S)
pageInfo_Privacy_Encrypted1 = Pagina pe care o vezi a fost criptată înainte de a fi transmisă prin internet.
pageInfo_Privacy_Encrypted2 = Criptarea face dificilă interceptarea de către persoane neautorizate a informațiilor transmise între calculatoare. Prin urmare, este puțin probabil ca altcineva să citească această pagină așa cum a fost transmisă prin rețea.
pageInfo_MixedContent = Conexiune criptată parțial
pageInfo_MixedContent2 = Părți din pagina vizualizată nu au fost criptate înainte de a fi transmise prin internet.
pageInfo_WeakCipher = Conexiunea la acest site web folosește criptare slabă și nu este privată. Alte persoane îți pot vedea informațiile și pot modifica comportamentul site-ului web.
pageInfo_CertificateTransparency_Compliant = Acest site web respectă politica privind transparența certificatelor.
# Token Manager
password_not_set = (nesetată)
