# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

OPTIONS_PAGE_TITLE = نوع پۊرنیڌن
OPTIONS_PAGE_SUBTITLE = پسند گۊزینه یل پۊرنیڌن
SHORTCUTS_PAGE_TITLE = سامووݩ ره نهنگا
SHORTCUTS_PAGE_SUBTITLE = وورکل آیکونا برنومه
SUMMARY_PAGE_TITLE = خولاسه
UN_REFRESH_LEARN_MORE = &قلوه دووسته بۊین
