# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Konservitaj akreditiloj
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Kopii URL
    .accesskey = K
launch-site-url-cmd =
    .label = Viziti URL
    .accesskey = V
copy-username-cmd =
    .label = Kopii nomon de uzanto
    .accesskey = u
edit-username-cmd =
    .label = Redakti uzantonomon
    .accesskey = u
copy-password-cmd =
    .label = Kopii pasvorton
    .accesskey = K
edit-password-cmd =
    .label = Redakti pasvorton
    .accesskey = p
search-filter =
    .accesskey = S
    .placeholder = Serĉi
column-heading-site =
    .label = Retejo
column-heading-username =
    .label = Nomo de uzanto
column-heading-password =
    .label = Pasvorto
column-heading-time-created =
    .label = Unuafoje uzita
column-heading-time-last-used =
    .label = Lastfoje uzita
column-heading-time-password-changed =
    .label = Lastfoje ŝanĝita
column-heading-times-used =
    .label = Nombro de uzoj
remove =
    .label = Forigi
    .accesskey = o
import =
    .label = Importi…
    .accesskey = I
close-button =
    .label = Fermi
    .accesskey = F
show-passwords =
    .label = Montri pasvortojn
    .accesskey = P
hide-passwords =
    .label = Kaŝi pasvortojn
    .accesskey = P
logins-description-all = En via komputilo vi havas konservitajn akreditilojn por la jenaj retejoj
logins-description-filtered = La jenaj akreditiloj kongruas kun via serĉo:
remove-all =
    .label = Forigi ĉiujn
    .accesskey = F
remove-all-shown =
    .label = Forigi ĉiujn montritajn
    .accesskey = m
remove-all-passwords-prompt = Ĉu vi certas ke vi volas forviŝi ĉiujn pasvortojn?
remove-all-passwords-title = Forviŝi ĉiujn pasvortojn
no-master-password-prompt = Ĉu vi certas ke vi ŝatus montri viajn pasvortojn?
auto-fill-logins-and-passwords =
    .label = Aŭtomate plenigi akreditilojn kaj pasvortojn
