# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

print-setup =
    .title = ورقہ سیٹ اپ
custom-prompt-title = مخصوص...
custom-prompt-prompt = اپݨا حسب ضرورت ہیڈر/فوٹر دا متن درج کرو۔
basic-tab =
    .label = فارمیٹ تے اختیارات
advanced-tab =
    .label = حاشیہ تے ہیڈر/فوٹر
format-group-label =
    .value = وضع
orientation-label =
    .value = سمت بندی:
portrait =
    .label = عمودی انداز
    .accesskey = P
landscape =
    .label = افقی انداز
    .accesskey = L
scale =
    .label = پیمانہ:
    .accesskey = S
scale-percent =
    .value = %
shrink-to-fit =
    .label = ورقہ دے پیٹے وِچ فٹ کرݨ کیتے سنگوڑو
    .accesskey = W
options-group-label =
    .value = اختیارات
print-bg =
    .label = بیک گراؤنڈ (رنگ تے تصویراں) چھاپو
    .accesskey = B
margin-group-label-inches =
    .value = حاشیے (انچ)
margin-group-label-metric =
    .value = حاشیے (ملی میٹر)
margin-top =
    .value = چوٹی:
    .accesskey = T
margin-top-invisible =
    .value = چوٹی:
margin-bottom =
    .value = تل:
    .accesskey = B
margin-bottom-invisible =
    .value = تَل
margin-left =
    .value = کھٻا:
    .accesskey = L
margin-left-invisible =
    .value = کھٻا:
margin-right =
    .value = سڄا:
    .accesskey = R
margin-right-invisible =
    .value = سڄا:
header-footer-label =
    .value = ہیڈرز اینڈ فوٹرز
hf-left-label =
    .value = کھٻا:
hf-center-label =
    .value = آدھل:
hf-right-label =
    .value = سڄا:
header-left-tip =
    .tooltiptext = کھٻا ہیڈر
header-center-tip =
    .tooltiptext = ادھلا ہیڈر
header-right-tip =
    .tooltiptext = سڄا ہیڈر
footer-left-tip =
    .tooltiptext = کھٻا فوٹر
footer-center-tip =
    .tooltiptext = ادھلا فوٹر
footer-right-tip =
    .tooltiptext = سڄا فوٹر
hf-blank =
    .label = --blank--
hf-title =
    .label = عنوان
hf-url =
    .label = یوآرایل
hf-date-and-time =
    .label = وقت/تریخ
hf-page =
    .label = ورقہ #
hf-page-and-total =
    .label = ورقہ # دا #
hf-custom =
    .label = مخصوص...
print-preview-window =
    .title = چھپائی دا پیش نظارہ
print-title =
    .value = عنوان:
print-preparing =
    .value = تیار تھیندا پیا ہے…
print-progress =
    .value = پیش رفت:
print-window =
    .title = چھپائی
print-complete =
    .value = چھپائی مکمل تھی ڳئی ہے

# Variables
# $percent (integer) - Number of printed percentage
print-percent =
    .value = { $percent }%
dialog-cancel-label = منسوخ
dialog-close-label = بند کرو
