# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = सम बारलांबाय
openFile = फाइलखौ खेव
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = "%2$S" नि थाखाय %1$Sनागिर
contextMenuSearch.accesskey = S
bookmarkAllTabsDefault = [फल्डारनि मुं]
unsignedAddonsDisabled.learnMore.label = गोबां सोलों
unsignedAddonsDisabled.learnMore.accesskey = L
crashedpluginsMessage.title = %S प्लागिनखौ बोफ्लेबाय।
crashedpluginsMessage.reloadButton.label = बिलाइखौ फिन ल'ड खालाम
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = मोनसे क्रेस रिपर्टखौ गथाय
crashedpluginsMessage.submitButton.accesskey = S
crashedpluginsMessage.learnMore = गोबां सोलों...
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = नोंथाङा %S आव थांनायखौ फोरमायदों नामा?
keywordURIFixup.goTo = नंगौ, आंखौ %S आव लां
keywordURIFixup.goTo.accesskey = Y
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = %S आव आपडेट खालाम
update.downloadAndInstallButton.accesskey = U
menuOpenAllInTabs.label = गासैखौबो टेबफोराव खेव
tabHistory.goBack = बे बिलाइनि उनथिं थां
tabHistory.goForward = बे बिलाइनि सिगांथिं थां
# URL Bar
pasteAndGo.label = फोनांजाब हो आरो थां
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = (%S) जुम लेभेलखौ फिन फज
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = नोंथांनि बुकमार्क (%S) खौ दिन्थि
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = दा सोलिबाय थानाय डाउनल'ड (%S) खौ दिन्थिफुं
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = गोदान उइन्ड' (%S) खौ खेव\u0020
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = गोदान टेब (%S) खौ खेव\u0020
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = ..जों नायबिजिरबाय: %S
identity.identified.verified_by_you = नोंथाङा बे साइटनि थाखाय रैखाथि एंगारथाय दाजाबदेरबाय।
identity.identified.state_and_country = %S, %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = (%S) खौ फिसायै जुम खालाम
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = (%S) जुम लेभेलखौ फिन फज
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = (%S) खौ गेदेरै जुम खालाम
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = (%S) दानस'
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = कपि %S
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = (%S) खौ फोनांजाब हो
persistentStorage.allow.accesskey = A
webNotifications.notNow = दानो नङा
webNotifications.notNow.accesskey = n
webNotifications.never.accesskey = v
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = बेनिफ्राय आंखौ लां!
safebrowsing.getMeOutOfHereButton.accessKey = G
safebrowsing.notADeceptiveSiteButton.accessKey = D
safebrowsing.reportedAttackSite = रिपर्ट खालामखानाय गाग्लोबनाय साइट!
safebrowsing.notAnAttackButton.label = बेयो मोनसे गाग्लोबनाय साइट गैया...
safebrowsing.notAnAttackButton.accessKey = a
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = %S नागिर
processHang.add-on.learn-more.text = गोबां सोलों
processHang.button_debug.label = डेबाग स्क्रिप्ट
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = उइन्ड'खौ आबुं स्क्रिन (%S) आव दिन्थिफुं
emeNotifications.drmContentDisabled.button.label = DRM मावथि खालाम
emeNotifications.drmContentDisabled.button.accesskey = E
emeNotifications.unknownDRMSoftware = मोनथिमोनै
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = %Sखौ गावनि गोसोबादि खालाम...
decoder.noCodecs.accesskey = L
decoder.decodeError.accesskey = R
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-बिट
aboutDialog.architecture.thirtyTwoBit = 32-बिट
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = उनथिं
