# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Bida cendi ka dam
import-from =
    { PLATFORM() ->
        [windows] Suubarey, doo-šilbawey, šennikufaley nda bayhaya tanayaŋ bere ka hun ne:
       *[other] Ibaayey, doo-šilbawey, šennikufaley nda bayhaya tanayaŋ bere ka hun ne:
    }
import-from-bookmarks = Doo-šilbawey bere ka hun ne:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-nothing =
    .label = War ma ši haya kul zaa
    .accesskey = W
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = x
import-from-360se =
    .label = 360 Ceecikaw saajante
    .accesskey = 3
no-migration-sources = Porogaramey kul ši kaŋ goo nda doo-šilbayyaŋ, taariki wala šennikufal kaŋ ga duwandi.
import-source =
    .label = Cendi ka zaa kayandiyaney nda bayhayey
import-items-title =
    .label = Hayiizey kaŋ ga cendi ka zaandi
import-items-description = Suuba hayiizey kaŋ ga cendi ka zaandi:
import-migrating-title =
    .label = Cendi ga zaandi…
import-migrating-description = Hayiizey wey goo ma cenda ka zaandi…
import-select-profile-title =
    .label = Alhal suuba
import-select-profile-description = Alhaaley wey goo no cendi ka zaa ne se:
import-done-title =
    .label = Cendi ka zaayan timme
import-done-description = Hayiizey wey n' ka bere ka ben:
import-close-source-browser = Soobay ka ceecikaw suubantaa daabu jina ka koy jine.
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = Hun { $source } ra
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Ceecikaw saajante
imported-safari-reading-list = Cawhaya maašeede (Safari ra)
imported-edge-reading-list = Cawhaya maašeede (From Edge)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Interneti suubarey
    .value = Interneti suubarey
browser-data-edge-1 =
    .label = Kayandiyaney
    .value = Kayandiyaney
browser-data-safari-1 =
    .label = Ibaayey
    .value = Ibaayey
browser-data-chrome-1 =
    .label = Ibaayey
    .value = Ibaayey
browser-data-canary-1 =
    .label = Ibaayey
    .value = Ibaayey
browser-data-360se-1 =
    .label = Ibaayey
    .value = Ibaayey
browser-data-ie-2 =
    .label = Aleewawey
    .value = Aleewawey
browser-data-edge-2 =
    .label = Aleewawey
    .value = Aleewawey
browser-data-safari-2 =
    .label = Aleewawey
    .value = Aleewawey
browser-data-chrome-2 =
    .label = Aleewawey
    .value = Aleewawey
browser-data-canary-2 =
    .label = Aleewawey
    .value = Aleewawey
browser-data-firefox-2 =
    .label = Aleewawey
    .value = Aleewawey
browser-data-360se-2 =
    .label = Aleewawey
    .value = Aleewawey
browser-data-ie-4 =
    .label = Ceeciyan taariki
    .value = Ceeciyan taariki
browser-data-edge-4 =
    .label = Ceeciyan taariki
    .value = Ceeciyan taariki
browser-data-safari-4 =
    .label = Ceeciyan taariki
    .value = Ceeciyan taariki
browser-data-chrome-4 =
    .label = Ceeciyan taariki
    .value = Ceeciyan taariki
browser-data-canary-4 =
    .label = Ceeciyan taariki
    .value = Ceeciyan taariki
browser-data-firefox-history-and-bookmarks-4 =
    .label = Naarumi taariki nda doo-šilbawey
    .value = Naarumi taariki nda doo-šilbawey
browser-data-360se-4 =
    .label = Ceeciyan taariki
    .value = Ceeciyan taariki
browser-data-ie-8 =
    .label = Takari gaabunte taariki
    .value = Takari gaabunte taariki
browser-data-edge-8 =
    .label = Takari gaabunte taariki
    .value = Takari gaabunte taariki
browser-data-safari-8 =
    .label = Takari gaabunte taariki
    .value = Takari gaabunte taariki
browser-data-chrome-8 =
    .label = Takari gaabunte taariki
    .value = Takari gaabunte taariki
browser-data-canary-8 =
    .label = Takari gaabunte taariki
    .value = Takari gaabunte taariki
browser-data-firefox-8 =
    .label = Takari gaabunte taariki
    .value = Takari gaabunte taariki
browser-data-360se-8 =
    .label = Takari gaabunte taariki
    .value = Takari gaabunte taariki
browser-data-ie-16 =
    .label = Šennikufal gaabuntey
    .value = Šennikufal gaabuntey
browser-data-edge-16 =
    .label = Šennikufal gaabuntey
    .value = Šennikufal gaabuntey
browser-data-safari-16 =
    .label = Šennikufal gaabuntey
    .value = Šennikufal gaabuntey
browser-data-chrome-16 =
    .label = Šennikufal gaabuntey
    .value = Šennikufal gaabuntey
browser-data-canary-16 =
    .label = Šennikufal gaabuntey
    .value = Šennikufal gaabuntey
browser-data-firefox-16 =
    .label = Šennikufal gaabuntey
    .value = Šennikufal gaabuntey
browser-data-360se-16 =
    .label = Šennikufal gaabuntey
    .value = Šennikufal gaabuntey
browser-data-ie-32 =
    .label = Kaasey
    .value = Kaasey
browser-data-edge-32 =
    .label = Kaasey
    .value = Kaasey
browser-data-safari-32 =
    .label = Doo-šilbawey
    .value = Doo-šilbawey
browser-data-chrome-32 =
    .label = Doo-šilbawey
    .value = Doo-šilbawey
browser-data-canary-32 =
    .label = Doo-šilbawey
    .value = Doo-šilbawey
browser-data-360se-32 =
    .label = Doo-šilbawey
    .value = Doo-šilbawey
browser-data-ie-64 =
    .label = Bayhaya taney
    .value = Bayhaya taney
browser-data-edge-64 =
    .label = Bayhaya taney
    .value = Bayhaya taney
browser-data-safari-64 =
    .label = Bayhaya taney
    .value = Bayhaya taney
browser-data-chrome-64 =
    .label = Bayhaya taney
    .value = Bayhaya taney
browser-data-canary-64 =
    .label = Bayhaya taney
    .value = Bayhaya taney
browser-data-firefox-other-64 =
    .label = Bayhaya taney
    .value = Bayhaya taney
browser-data-360se-64 =
    .label = Bayhaya taney
    .value = Bayhaya taney
browser-data-firefox-128 =
    .label = Zanfuney nda kanjey
    .value = Zanfuney nda kanjey
