# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-firefox =
    .label = Firefox
    .accesskey = x
no-migration-sources = Porogaramey kul ši kaŋ goo nda doo-šilbayyaŋ, taariki wala šennikufal kaŋ ga duwandi.
import-source =
    .label = Cendi ka zaa kayandiyaney nda bayhayey
import-items-title =
    .label = Hayiizey kaŋ ga cendi ka zaandi
import-items-description = Suuba hayiizey kaŋ ga cendi ka zaandi:
import-migrating-title =
    .label = Cendi ga zaandi…
import-migrating-description = Hayiizey wey goo ma cenda ka zaandi…
import-select-profile-title =
    .label = Alhal suuba
import-done-title =
    .label = Cendi ka zaayan timme
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = Hun { $source } ra
source-name-ie = Internet Explorer
source-name-safari = Safari
source-name-chrome = Google Chrome
source-name-firefox = Mozilla Firefox
imported-safari-reading-list = Cawhaya maašeede (Safari ra)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Interneti suubarey
    .value = Interneti suubarey
browser-data-safari-1 =
    .label = Ibaayey
    .value = Ibaayey
browser-data-chrome-1 =
    .label = Ibaayey
    .value = Ibaayey
browser-data-canary-1 =
    .label = Ibaayey
    .value = Ibaayey
browser-data-ie-2 =
    .label = Aleewawey
    .value = Aleewawey
browser-data-safari-2 =
    .label = Aleewawey
    .value = Aleewawey
browser-data-chrome-2 =
    .label = Aleewawey
    .value = Aleewawey
browser-data-canary-2 =
    .label = Aleewawey
    .value = Aleewawey
browser-data-firefox-2 =
    .label = Aleewawey
    .value = Aleewawey
browser-data-ie-4 =
    .label = Ceeciyan taariki
    .value = Ceeciyan taariki
browser-data-safari-4 =
    .label = Ceeciyan taariki
    .value = Ceeciyan taariki
browser-data-chrome-4 =
    .label = Ceeciyan taariki
    .value = Ceeciyan taariki
browser-data-canary-4 =
    .label = Ceeciyan taariki
    .value = Ceeciyan taariki
browser-data-firefox-history-and-bookmarks-4 =
    .label = Naarumi taariki nda doo-šilbawey
    .value = Naarumi taariki nda doo-šilbawey
browser-data-ie-8 =
    .label = Takari gaabunte taariki
    .value = Takari gaabunte taariki
browser-data-safari-8 =
    .label = Takari gaabunte taariki
    .value = Takari gaabunte taariki
browser-data-chrome-8 =
    .label = Takari gaabunte taariki
    .value = Takari gaabunte taariki
browser-data-canary-8 =
    .label = Takari gaabunte taariki
    .value = Takari gaabunte taariki
browser-data-firefox-8 =
    .label = Takari gaabunte taariki
    .value = Takari gaabunte taariki
browser-data-ie-16 =
    .label = Šennikufal gaabuntey
    .value = Šennikufal gaabuntey
browser-data-safari-16 =
    .label = Šennikufal gaabuntey
    .value = Šennikufal gaabuntey
browser-data-chrome-16 =
    .label = Šennikufal gaabuntey
    .value = Šennikufal gaabuntey
browser-data-canary-16 =
    .label = Šennikufal gaabuntey
    .value = Šennikufal gaabuntey
browser-data-firefox-16 =
    .label = Šennikufal gaabuntey
    .value = Šennikufal gaabuntey
browser-data-safari-32 =
    .label = Doo-šilbawey
    .value = Doo-šilbawey
browser-data-chrome-32 =
    .label = Doo-šilbawey
    .value = Doo-šilbawey
browser-data-canary-32 =
    .label = Doo-šilbawey
    .value = Doo-šilbawey
browser-data-ie-64 =
    .label = Bayhaya taney
    .value = Bayhaya taney
browser-data-safari-64 =
    .label = Bayhaya taney
    .value = Bayhaya taney
browser-data-chrome-64 =
    .label = Bayhaya taney
    .value = Bayhaya taney
browser-data-canary-64 =
    .label = Bayhaya taney
    .value = Bayhaya taney
browser-data-firefox-other-64 =
    .label = Bayhaya taney
    .value = Bayhaya taney
