# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

ssl-error-no-cypher-overlap = Ši hin ka toonandi nda ceroo: tuguyan kabu kul ši ihinkaa game.
ssl-error-unsupported-certificate-type = Tabatiyan-tiira dumi ši nda faaba.
ssl-error-unsupported-version = Cere goo ma goy nda saajaw berehaw dumi kaŋ ši nda faaba.
ssl-error-wrong-certificate = Daykaw lasal-tabatandiyan kay: sutura kufal bayhayhugu beeri ra ši hima baytal kufal tabatiyan-tiira bayhayhugu ra.
ssl-error-bad-mac-read = SSL duu jiširi nda alhabar tabatandiyan ašariya laybante.
ssl-error-bad-mac-alert = SSL ga alhabar tabatandiyan ašariya laybante bayrandi.
ssl-error-bad-cert-alert = SSL ši hin ka tabatiyan-tiira koroši.
ssl-error-ssl-disabled = Ši hin ka ciya: SSL kayante.
ssl-error-fortezza-pqg = Ši hin ka ciya: SSL ceroo goo FORTEEZA laama waani foo ra.
ssl-error-unknown-cipher-suite = SSL hawari-harfu foo kaŋ šibayante ga wirandi.
ssl-error-no-ciphers-supported = Hawari-harfu kul ši bara nda a goo goy ra porogaramoo woo ra.
ssl-error-bad-block-padding = SSL duu jiširi kaŋ goo nda toonandi gurunbu laala.
ssl-error-rx-record-too-long = SSL duu jiširi kaŋ nga kuuyan bebbeeroo hoo.
ssl-error-tx-record-too-long = SSL ceeci ka jiširi sanba kaŋ na kuuyan bebbeeroo hoo.
ssl-error-rx-malformed-hello-request = SSL duu fooyan alhabar "War ga ban" kaŋ ši kubay.
ssl-error-rx-malformed-client-hello = SSL duu "War ga ban duukaw" kaŋ ši kubay.
ssl-error-rx-malformed-server-hello = SSL duu "War ga ban feršikaw" fooyan kaŋ ši kubay.
ssl-error-rx-malformed-certificate = SSL duu tabatandiyan fooyan kaŋ ši kubay.
ssl-error-rx-malformed-server-key-exch = SSL duu "Feršikaw kufal barmay" fooyan kaŋ ši kubay.
ssl-error-rx-malformed-cert-request = SSL duu "Tabatandiyan hãayan" fooyan kaŋ ši kubay.
ssl-error-rx-malformed-hello-done = SSL duu "War ga ban feršikaw" fooyan kaŋ ši kubay.
ssl-error-rx-malformed-cert-verify = SSL duu "Tabatandiyan koroši" fooyan kaŋ ši kubay.
ssl-error-rx-malformed-client-key-exch = SSL duu "Feršikaw kufal barmay" fooyan kaŋ ši kubay.
ssl-error-rx-malformed-finished = SSL duu "Ben" alhabar.
ssl-error-rx-malformed-change-cipher = SSL duu "Hawari-harfu cimi barmay" jiširi.
ssl-error-rx-malformed-alert = SSL duu "Yaamar" kaŋ ši kubay.
ssl-error-rx-malformed-handshake = SSL duu "War ga ban" jiširi.
ssl-error-rx-malformed-application-data = SSL duu "Porogaramu bayhayey" jiširi kaŋ ši kubay.
ssl-error-rx-unexpected-hello-request = SSL duu "Fooyan hãayan" kaŋ ši kubay.
ssl-error-rx-unexpected-client-hello = SSL duu "Daykaw foofo" alhabar kaŋ ši tammahã ra.
ssl-error-rx-unexpected-server-hello = SSL duu "Feršikaw foofo" alhabar kaŋ ši tammahã ra.
ssl-error-rx-unexpected-certificate = SSL duu "Tabatiyan-tiira" kaŋ ši tammahã ra.
ssl-error-rx-unexpected-server-key-exch = SSL duu "Feršikaw kufal barmay" alhabar kaŋ ši tammahã ra.
ssl-error-rx-unexpected-cert-request = SSL duu "Tabatiyan-tiira hãayan" alhbar kaŋ ši tammahã ra.
ssl-error-rx-unexpected-hello-done = SSL duu "Feršikaw foofo - a ben" alhabar kaŋ ši tammahã ra.
ssl-error-rx-unexpected-cert-verify = SSL duu "Tabatiyan-tiira koroši" alhbar kaŋ ši tammahã ra.
ssl-error-rx-unexpected-client-key-exch = SSL duu "Feršikaw kufal barmay" alhabar kaŋ ši tammahã ra.
ssl-error-rx-unexpected-finished = SSL duu "Ben" alhabar kaŋ ši tammahã ra.
ssl-error-rx-unexpected-change-cipher = SSL duu "Hawari-harfu cimi barmay" jiširi.
ssl-error-rx-unexpected-alert = SSL duu "Yaamar" jiširi kaŋ ši tammahã ra.
ssl-error-rx-unexpected-handshake = SSL duu "Foofo" jiširi kaŋ ši tammahã ra.
ssl-error-rx-unexpected-application-data = SSL duu "Porogaramu bayhayey" jiširi.
ssl-error-rx-unknown-record-type = SSL duu jiširi kaŋ gundekunaa ši bayrandi.
ssl-error-rx-unknown-handshake = SSL duu fooyan kaŋ alhabaroo gundekunaa ši bayrandi.
ssl-error-rx-unknown-alert = SSL duu yaamar jiširi kaŋ yaamaroo šilbayroo ši bayrandi.
ssl-error-close-notify-alert = SSL na ciyaroo woo daabu.
ssl-error-handshake-unexpected-alert = SSL mana fooyanoo kaŋ a n'a duu'wa tammahã.
ssl-error-decompression-failure-alert = SSL ceroo mana hin ka SSL jiširoo kaŋ a duu'wa feeri boryo.
ssl-error-handshake-failure-alert = SSL mana hin ka saajaw adadu hansari dam kaŋ ga kubay.
ssl-error-illegal-parameter-alert = SSL wanga fooyan alhabaroo zama nga gundekunaa ši kubay.
ssl-error-unsupported-cert-alert = SSL ši tabatiyan-tiirawey dumoo kaŋ a duu'wa juwal.
ssl-error-certificate-unknown-alert = SSL duu mise kaŋ ši fahamandi nda tabatiyan-tiira duwantaa.
ssl-error-generate-random-failure = SSL hinna birjante kaataraykaa kay.
ssl-error-sign-hashes-failure = Mana hin ka bayhayey kaŋ ka war tabatiyan-tiiraa koroši žeeri nda hinna maa.
ssl-error-server-key-exchange-failure = Kayyan kaŋ mana tabatandi waatoo kaŋ "SSL feršikaw kufal barmay" goo ma foo.
ssl-error-client-key-exchange-failure = Kayyan kaŋ mana tabatandi waatoo kaŋ "SSL daykaw kufal barmay" goo ma foo.
ssl-error-socket-write-failure = Ceeciyan ka bayhaya tugante hantum ganda sanka-moɲoo ra kay.
ssl-error-md5-digest-failure = MD5 surkumandi goyyan kay.
ssl-error-sha-digest-failure = SHA-1 goyyan kay.
ssl-error-mac-computation-failure = MAC kabuyan kay.
ssl-error-sym-key-context-failure = Kufal tenjante kundekuna teeyan kay.
ssl-error-sym-key-unwrap-failure = Ceeciyan ka kufal tenjante "Daykaw kufal barmay alhabar ra" feeri kay.
ssl-error-iv-param-failure = PKCS11 ašariya mana hin ka IV foo berandi adadu hansari ra.
ssl-error-init-cipher-suite-failure = Mana hin ka hawari-harfu suubantaa haŋakaari.
ssl-error-no-compression-overlap = Ši hin ka toonandi saajante tee ceroo: kankamandi kabu kul ši i game.
ssl-error-handshake-not-completed = Ši hin ka SSL fooyan foo šintin hala sohõ fooyanoo ma ben.
ssl-error-cert-kea-mismatch = Tabatiyan-tiiraa kaŋ noondi mana hin ka goyandi nda kufal barmay suubante kaboo.
ssl-error-decryption-failed-alert = Ceroo mana hin ka SSL jiširoo kufaloo kaa.
ssl-error-record-overflow-alert = Ceroo du SSL jiširi kaŋ ši duɲe koyne.
ssl-error-unknown-ca-alert = Ceroo ši tabatiyan-tiira hinoo kaŋ hun war tabatiyan-tiiraa do bay wal'a ma naanay y'a.
ssl-error-access-denied-alert = Ceroo duu tabatiyan-tiira boryo, amma huraa wanjandi.
ssl-error-decode-error-alert = Ceroo mana hin ka SSL fooyanoo alhabaryaa feerandi.
ssl-error-decrypt-error-alert = Ceroo ga bayrandi kaŋ mayray šilbay korošiyan wala kufal barmayyan kaŋ.
ssl-error-export-restriction-alert = Ceroo ga bayrandi kaŋ hacciyanoo ši hanga jinay-kaataray alhukum bande.
ssl-error-protocol-version-alert = Ceroo ga bayrandi kaŋ berehaw dumoo manti cerekanbante wala gaakašinante.
ssl-error-insufficient-security-alert = Feršikaa ga hawari-harfuyaŋ waažibandi kaŋ ga saajaw ka bisa daykaa gaakašinay waney.
ssl-error-internal-error-alert = Ceroo ga bayrandi kaŋ nga na kunahere firka maate.
ssl-error-user-canceled-alert = Cere goykaa na fooyanoo naŋ.
ssl-error-no-renegotiation-alert = Ceroo ši nda fondo ka SSL saajaw adadu hansarey hacci taaga.
ssl-error-certificate-unobtainable-alert = SSL ceroo mana hin ka duu tabatiyan-tiira ka hun URL woo do.
ssl-error-bad-cert-hash-value-alert = SSL ceroo na tabatiyan-tiira dundu hinna laala bayrandi.
sec-error-library-failure = saajaw tiirahugu kayyaŋ.
sec-error-bad-data = saajaw tiirahugu: bayhayey duwante laalayaŋ.
sec-error-output-len = saajaw tiirahugu: fattari kuuyan firka.
sec-error-input-len = saajaw tiirahugu na damyan kuuyan firka maate.
sec-error-invalid-args = saajaw tiirahugu: sennigoy laalayaŋ.
sec-error-invalid-algorithm = saajaw tiirahugu: kabu laala.
sec-error-invalid-ava = saajaw tiirahugu: AVA laala.
sec-error-bad-der = saajaw tiirahugu: DER-harfu-hawante alhabaryu fasal šiirante.
sec-error-bad-password = Saajaw šennikufal damantaa ga laala.
sec-error-no-nodelock = saajaw tiirahugu: gamkufal kul ši.
sec-error-bad-database = saajaw tiirahugu: bayrayhaya hugu laala.
sec-error-no-memory = saajaw tiirahugu: lakkal nooyan kayyan.
sec-error-duplicate-cert = Tabatiyan-tiiraa ga bara ka ben war bayrayhaya hugoo ra.
sec-error-adding-cert = Firka goo tabatiyan-tiiraa tontonandiyanoo ra bayrayhaya hugoo ga.
sec-error-cert-valid = Tabatiyan-tiiraa woo ga boori.
sec-error-cert-not-valid = Tabatiyan-tiiraa woo ši boori.
sec-error-cert-no-response = Tabatiyan-tiiraa tiirahugu: Ši tuuru
sec-error-crl-invalid = Tabatiyan-tiira dogu maašeedaa goo nda takari laala.
sec-error-extension-value-invalid = Tabatiyan-tiira dobuyanoo hinna ši boori.
sec-error-extension-not-found = Tabatiyan-tiira dobuyanoo mana duwandi.
sec-error-path-len-constraint-invalid = Tabatiyan-tiira fondo kuuyan šugullaa ši boori.
sec-error-cert-usages-invalid = Tabatiyan-tiira goy-miɲey faaroo ši boori.
sec-internal-only = **Kunahere HINNE dunbu**
sec-error-unknown-critical-extension = Tabatiyan-tiiraa goo nda šugulla mise dobuyan šibayante.
sec-error-old-crl = Tabatiyan-tiira dogu maašeedaa ga žen sohõda wanoo.
sec-error-no-email-cert = Manti tugante wala mayray-šilbante: war ši nda bataga tabatiyan-tiiraa jina.
sec-error-not-a-recipient = Ši hin ka kufal-kaa: war manti duukaw, wala tabatiyan-tiira nda sutura kufal sawante mana duwandi.
sec-error-pkcs7-keyalg-mismatch = Ši hin la kufal-kaa: kufal tuguyan kabu ši sawa nda war tabatiyan-tiiraa.
sec-error-decryption-disallowed = Ši hin la kufal-kaa: tugante nda kabu kaŋ ši nda fondo wala fufal adadu.
xp-sec-fortezza-no-card = Fortezza kattawey kul mana duwandi
xp-sec-fortezza-none-selected = Fortezza kattaa kul mana suubandi
xp-sec-fortezza-more-info = Taare boro suuba k'a duu a ga alhabar tontoni
xp-sec-fortezza-person-not-found = Borotaraa mana duwandi
xp-sec-fortezza-no-more-info = Alhabar tontoni kul ši borotaraa din ga
sec-error-krl-invalid = KRL taagaa ši nda takari boryo.
sec-error-need-random = saajaw tiirahugu: ga boona bayhaya birjanteyaŋ.
sec-error-no-module = saajaw tiirahugu: saajaw dunbu kul ši hin ka goy wirantaa tee.
sec-error-cert-nickname-collision = Tabatiyan-tiira nda maakanbari follokaa ga bara ka ben.
sec-error-key-nickname-collision = Kufal nda maakanbari follokaa ga bara ka ben.
sec-error-safe-not-created = firka haya saajante teeyan waate
sec-error-exporting-certificates = Firka ceeciyan ka tabatiyan-tiirayaŋ fattandi waate.
sec-error-importing-certificates = Firka ceeciyan ka tabatiyan-tiirayaŋ cendiyan waate.
sec-error-user-cancelled = Goykaw na naŋ naagu.
sec-error-pkcs12-duplicate-data = Mana cendandi, ga ba bayrayhaya hugoo ka ben.
sec-error-message-send-aborted = Alhabaryu mana sanbandi.
sec-error-cert-addr-mismatch = Aderesu tabatiyan-tiira maa žeeriyan ra ši sawa nda aderesu alhabaryu boŋdekewey ra.
sec-error-keygen-fail = Ši hin ka baytal/sutura kufal hinka kaataray.
sec-error-bad-nickname = Tabatiyan-tiira maakanbaroo ga bara ka ben.
sec-error-not-fortezza-issuer = FORTEZZA cere tenjiri ši nda manti-FORTEZZA tabatiyan-tiira.
sec-error-js-invalid-module-name = Dunbu maa laala.
sec-error-js-invalid-dll = Dunbu fondo/maa tuku laala
sec-error-js-add-mod-failure = Ši hin ka dunbu tonton
sec-error-js-del-mod-failure = Ši hin ka dunbu tuusu
sec-error-old-krl = KRL taaga ši žen sohõda wanoo.
sec-error-unknown-cert = Tabatiyan-tiira wirantaa mana hin ka duwandi.
sec-error-cert-bad-access-location = Gorodoo tabatiyan-tiira assariya feršikaw ši nda takari boryo.
sec-error-ocsp-unknown-response-type = OCSP tuuruyan ši hin ka feerandi ka timme; dumoo manti bayante.
sec-error-ocsp-server-error = OCSP feršikaa na kunehere firka maate.
sec-error-ocsp-try-server-later = OCSP feršikaa nee a ma šii koyne.
sec-error-ocsp-unauthorized-request = OCSP feršikaa wanji ka wiriyanoo woo ga sanda a ši alhukum ra.
sec-error-ocsp-unknown-response-status = OCSP feršikaa na assariya ši-bayrante willi.
sec-error-ocsp-not-enabled = War ga hima ka OCSP tunandi jina ka goyoo woo tee.
sec-error-ocsp-no-default-responder = War ga hima ka OCSP tilasu tuurukaw kayandi jina ka goyoo woo tee.
sec-error-digest-not-found = CMS wala PKCS #7 surkumandikaw mana duwandi alhabaryu mayray-šilbantaa ra.
sec-error-unsupported-message-type = CMS wala PKCS #7 alhabaryaa ši nda gaakašinay.
sec-error-module-stuck = PKCS #11 dunbu mana hin ka dogandi zama a goy ra hala sohõ.
sec-error-bad-template = Mana hin ASN. 1 bayhayey feerandi. Leeti tabatante mana boori.
sec-error-reused-issuer-and-serial = War ga ceeci ka tabatiyan-tiira cendi ka dam nda kaataraykaw/fannu follokaa sanda tabatiyan-tiira barante, amma woodin manti tabatiyan-tiira follokaa.
sec-error-busy = NSS mana hin ka buu. Hayayaŋ cindi goy ra.
sec-error-extra-input = DER-harfu-hawante alhabaryu bara nda bayhaya tontoni kaŋ mana goyandi.
sec-error-unsupported-elliptic-curve = Windirayobante kuubi bila nda gaakašinay.
sec-error-unsupported-ec-point-form = Windirayobante kuubi tonbi takari bila nda gaakašinay.
sec-error-unrecognized-oid = Haya taamansakaw mana-bayrante.
sec-error-ocsp-invalid-signing-cert = OCSP tabatiyan-tiira maa žeeriyan OCSP tuuruyan ra.
sec-error-unknown-object-type = Haya šibayante dumi tabatandi.
sec-error-incompatible-pkcs11 = PKCS #11 dirandikaw ga tabatandiyan hoo da taka kaŋ ši cerekanbe.
sec-error-no-event = Moo taaga kul ši bara waatoo woo ra.
sec-error-crl-already-exists = CRL ga bara ka ben.
sec-error-not-initialized = NSS mana haŋakaari.
sec-error-token-not-logged-in = Goy kay zama PKCS#11 taamansa mana huru.
sec-error-ocsp-bad-signature = OCSP tuuruyanoo ši nda mayray šilbay boryo.
