# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Shrani
dialogTitleAddBookmark = Nov zaznamek
dialogTitleAddMulti = Novi zaznamki
dialogTitleEdit = Lastnosti "%S"
dialogTitleAddNewBookmark2 = Dodaj zaznamek
dialogTitleEditBookmark = Uredi "%S"
dialogTitleEditBookmark2 = Uredi zaznamek
dialogTitleAddBookmarkFolder = Dodaj mapo zaznamkov
dialogTitleEditBookmarkFolder = Uredi mapo zaznamkov
bookmarkAllTabsDefault = [ime mape]
newFolderDefault = Nova mapa
newBookmarkDefault = Nov zaznamek
