# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Resolviendo la dirección de { $host }…
network-connection-status-connected = Conectado a { $host }…
network-connection-status-sending-request = Enviando petición a { $host }…
network-connection-status-transferring-data = Transfiriendo datos desde { $host }…
network-connection-status-connecting = Conectando a { $host }…
network-connection-status-read = Leído { $host }
network-connection-status-wrote = Escrito { $host }
network-connection-status-waiting = Esperando a { $host }…
network-connection-status-looked-up = Encontrado { $host }…
network-connection-status-tls-handshake = Realizando handshake de TLS a { $host }…
network-connection-status-tls-handshake-finished = Finalizó handshake de TLS para { $host }…
