# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Αποθηκευμένοι λογαριασμοί
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-username-cmd =
    .label = Αντιγραφή ονόματος χρήστη
    .accesskey = τ
edit-username-cmd =
    .label = Επεξεργασία ονόματος χρήστη
    .accesskey = χ
copy-password-cmd =
    .label = Αντιγραφή κωδικού
    .accesskey = γ
edit-password-cmd =
    .label = Επεξεργασία κωδικού
    .accesskey = ξ
search-filter =
    .accesskey = Α
    .placeholder = Αναζήτηση
column-heading-site =
    .label = Σελίδα
column-heading-username =
    .label = Όνομα χρήστη
column-heading-password =
    .label = Κωδικός
column-heading-time-created =
    .label = Πρώτη χρήση
column-heading-time-last-used =
    .label = Τελευταία χρήση
column-heading-time-password-changed =
    .label = Τελευταία τροποποίηση
column-heading-times-used =
    .label = Αριθμός χρήσεων
import =
    .label = Εισαγωγή…
    .accesskey = ε
close-button =
    .label = Κλείσιμο
    .accesskey = Κ
show-passwords =
    .label = Εμφάνιση κωδικών
    .accesskey = Ε
hide-passwords =
    .label = Απόκρυψη κωδικών
    .accesskey = Α
no-master-password-prompt = Σίγουρα επιθυμείτε να εμφανίσετε τους κωδικούς σας;
