# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = Нээ
    .accesskey = Н
places-open-all-in-tabs =
    .label = Бүгдийг нь самбарт нээ
    .accesskey = н
places-view =
    .label = Харах
    .accesskey = р
places-by-date =
    .label = Огноогоор
    .accesskey = О
places-by-site =
    .label = Хуудсаар
    .accesskey = с
places-by-most-visited =
    .label = Хамгийн их зорчсоноор
    .accesskey = з
places-by-last-visited =
    .label = Сүүлд зорчсоноор
    .accesskey = л
places-by-day-and-site =
    .label = Огноо ба Хуудсаар
    .accesskey = б
places-delete-domain-data =
    .label = Энэ хуудсыг март
    .accesskey = м
places-sortby-name =
    .label = Нэрээр эрэмбэл
    .accesskey = э
places-library =
    .title = Сан
    .style = width:700px; height:500px;
places-view-menu-sort =
    .label = Эрэмбэл
    .accesskey = Э
places-cmd-backup =
    .label = Нөөцөл…
    .accesskey = ц
places-cmd-restore-from-file =
    .label = Файл сонго…
    .accesskey = Ф
places-view-sort-col-name =
    .label = Нэр
places-view-sort-col-tags =
    .label = Таглаа
places-back-button =
    .tooltiptext = Буцна
places-details-pane-select-an-item-description = Харахыг болон засварлахыг хүссэн зүйлээ сонгоно уу
