# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Sàbhail
dialogTitleAddBookmark = Comharra-lìn ùr
dialogTitleAddMulti = Comharran-lìn ùra
dialogTitleEdit = Roghainnean airson “%S”
dialogTitleAddNewBookmark2 = Cuir comharra-lìn ris
dialogTitleEditBookmark = Deasaich “%S”
dialogTitleEditBookmark2 = Deasaich an comharra-lìn
dialogTitleAddBookmarkFolder = Cuir pasgan chomharran-lìn ris
dialogTitleEditBookmarkFolder = Deasaich am pasgan chomharran-lìn
bookmarkAllTabsDefault = [Ainm pasgain]
newFolderDefault = Pasgan ùr
newBookmarkDefault = Comharra-lìn ùr
