# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Αναζήτηση { $host }…
network-connection-status-connected = Έγινε σύνδεση με { $host }…
network-connection-status-sending-request = Αποστολή αιτήματος στο { $host }…
network-connection-status-transferring-data = Μεταφορά δεδομένων από { $host }…
network-connection-status-connecting = Σύνδεση με { $host }…
network-connection-status-read = Ανάγνωση { $host }
network-connection-status-wrote = έγραψε { $host }
network-connection-status-waiting = Αναμονή για { $host }…
network-connection-status-looked-up = Αναζήτηση για { $host }…
network-connection-status-tls-handshake = Εκτέλεση χειραψίας TLS σε { $host }…
network-connection-status-tls-handshake-finished = Η χειραψία TLS ολοκληρώθηκε για το { $host }…
