# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

psmerr-ssl-disabled = უსაფრთხო დაკავშირება ვერ ხერხდება, რადგან SSL ოქმი ამორთულია.
psmerr-ssl2-disabled = უსაფრთხო დაკავშირება ვერ ხერხდება, რადგან საიტი SSL ოქმის მოძველებულ ვერსიას იყენებს.
ssl-error-unsupported-version = კვანძი უსაფრთხოების მიუღებელ ოქმს იყენებს.
ssl-error-ssl2-disabled = კვანძისთვის მისაღებია მხოლოდ SSL ვერსია 2, რომელიც ლოკალურად ამორთულია.
ssl-error-ssl-disabled = დაკავშირება ვერ ხერხდება: SSL ამორთულია.
ssl-error-fortezza-pqg = დაკავშირება ვერ ხერხდება: SSL კვანძი სხვა FORTEZZA დომენშია.
ssl-error-rx-record-too-long = SSL - მიღებულია მაქსიმალურ დასაშვებზე მეტი ზომის ჩანაწერი.
ssl-error-tx-record-too-long = SSL - მაქსიმალურ დასაშვებზე მეტი ზომის ჩანაწერის გაგზავნის მცდელობა.
ssl-error-rx-malformed-hello-request = SSL - მიღებულია დაზიანებული Hello Request გზავნილი.
ssl-error-rx-malformed-client-hello = SSL - მიღებულია დაზიანებული Client Hello გზავნილი.
ssl-error-rx-malformed-server-hello = SSL - მიღებულია დაზიანებული Server Hello გზავნილი.
ssl-error-rx-malformed-certificate = SSL - მიღებულია დაზიანებული Certificate გზავნილი.
ssl-error-rx-malformed-server-key-exch = SSL - მიღებულია დაზიანებული Server Key გზავნილი.
ssl-error-rx-malformed-cert-request = SSL - მიღებულია დაზიანებული Certificate Request გზავნილი.
ssl-error-rx-malformed-hello-done = SSL - მიღებულია დაზიანებული Hello Done გზავნილი.
ssl-error-rx-malformed-cert-verify = SSL - მიღებულია დაზიანებული Certificate Verify გზავნილი.
ssl-error-rx-malformed-client-key-exch = SSL - მიღებულია დაზიანებული Client Key Exchange გზავნილი.
ssl-error-rx-malformed-finished = SSL - მიღებულია დაზიანებული Finished გზავნილი.
ssl-error-rx-malformed-change-cipher = SSL - მიღებულია დაზიანებული Change Cipher Spec ჩანაწერი.
ssl-error-rx-malformed-alert = SSL - მიღებულია დაზიანებული Alert ჩანაწერი.
ssl-error-rx-malformed-handshake = SSL - მიღებულია დაზიანებული Handshake ჩანაწერი.
ssl-error-rx-malformed-application-data = SSL - მიღებულია დაზიანებული Application Data ჩანაწერი.
ssl-error-rx-unexpected-hello-request = SSL - მიღებულია გაუთვალისწინებელი Hello Request გზავნილი.
ssl-error-rx-unexpected-client-hello = SSL - მიღებულია გაუთვალისწინებელი Client Hello გზავნილი.
ssl-error-rx-unexpected-server-hello = SSL - მიღებულია გაუთვალისწინებელი Server Hello გზავნილი.
ssl-error-rx-unexpected-certificate = SSL - მიღებულია გაუთვალისწინებელი Certificate გზავნილი.
ssl-error-rx-unexpected-server-key-exch = SSL - მიღებულია გაუთვალისწინებელი Server Key Exchange გზავნილი.
ssl-error-rx-unexpected-cert-request = SSL - მიღებულია გაუთვალისწინებელი Certificate Request გზავნილი.
ssl-error-rx-unexpected-hello-done = SSL - მიღებულია გაუთვალისწინებელი Server Hello Done გზავნილი.
ssl-error-rx-unexpected-cert-verify = SSL - მიღებულია გაუთვალისწინებელი Certificate Verify გზავნილი.
ssl-error-rx-unexpected-client-key-exch = SSL - მიღებულია გაუთვალისწინებელი Client Key Exchange გზავნილი.
ssl-error-rx-unexpected-finished = SSL - მიღებულია გაუთვალისწინებელი Finished გზავნილი.
ssl-error-rx-unexpected-change-cipher = SSL - მიღებულია გაუთვალისწინებელი Change Cipher Spec ჩანაწერი.
ssl-error-rx-unexpected-alert = SSL - მიღებულია გაუთვალისწინებელი Alert ჩანაწერი.
ssl-error-rx-unexpected-handshake = SSL - მიღებულია გაუთვალისწინებელი Handshake ჩანაწერი.
ssl-error-rx-unexpected-application-data = SSL - მიღებულია გაუთვალისწინებელი Application Data ჩანაწერი.
ssl-error-rx-unknown-alert = SSL - მიღებულია გაფრთხილების ჩანაწერი უცნობი აღწერილობით.
ssl-error-close-notify-alert = SSL კვანძმა კავშირი დახურა.
ssl-error-handshake-unexpected-alert = SSL კვანძისთვის მიღებული გზავნილი გაუთვალისწინებელი აღმოჩნდა.
ssl-error-decompression-failure-alert = SSL კვანძი ვერ ახერხებს მიღებული SSL ჩანაწერის გახსნას.
ssl-error-handshake-failure-alert = SSL კვანძი ვერ ახერხებს უსაფრთხოების მისაღებ პარამეტრებზე მოლაპარაკებას.
ssl-error-illegal-parameter-alert = SSL კვანძმა უარყო გზავნილი მიუღებელი შიგთავსის გამო.
ssl-error-generate-random-failure = SSL კვანძს პრობლემები აქვს შემთხვევითი რიცხვის გენერატორთან.
ssl-error-decode-error-alert = კვანძი ვერ ახერხებს SSL გზავნილის გაშიფვრას.
sec-error-no-recipient-certs-query = Not encrypted: you do not have certificates for each of the recipients.
sec-error-pkcs7-keyalg-mismatch = Cannot decrypt: key encryption algorithm does not match your certificate.
sec-error-pkcs7-bad-signature = Signature verification failed: no signer found, too many signers found, or improper or corrupted data.
sec-error-unsupported-keyalg = Unsupported or unknown key algorithm.
sec-error-decryption-disallowed = Cannot decrypt: encrypted using a disallowed algorithm or key size.
xp-sec-fortezza-no-card = No Fortezza cards Found
xp-sec-fortezza-none-selected = No Fortezza card selected
xp-sec-fortezza-more-info = Please select a personality to get more info on
xp-sec-fortezza-person-not-found = Personality not found
xp-sec-fortezza-no-more-info = No more information on that Personality
xp-sec-fortezza-bad-pin = Invalid Pin
xp-sec-fortezza-person-error = Couldn't initialize Fortezza personalities.
sec-error-no-krl = No KRL for this site's certificate has been found.
sec-error-krl-expired = The KRL for this site's certificate has expired.
sec-error-krl-bad-signature = The KRL for this site's certificate has an invalid signature.
sec-error-krl-invalid = New KRL has an invalid format.
sec-error-need-random = security library: need random data.
sec-error-no-module = security library: no security module can perform the requested operation.
sec-error-no-token = The security card or token does not exist, needs to be initialized, or has been removed.
sec-error-no-slot-selected = No slot or token was selected.
sec-error-cert-nickname-collision = A certificate with the same nickname already exists.
sec-error-key-nickname-collision = A key with the same nickname already exists.
sec-error-safe-not-created = error while creating safe object
sec-error-baggage-not-created = error while creating baggage object
xp-java-remove-principal-error = Couldn't remove the principal
xp-java-delete-privilege-error = Couldn't delete the privilege
xp-java-cert-not-exists-error = This principal doesn't have a certificate
sec-error-bad-export-algorithm = Required algorithm is not allowed.
sec-error-exporting-certificates = Error attempting to export certificates.
sec-error-importing-certificates = Error attempting to import certificates.
sec-error-user-cancelled = The user pressed cancel.
sec-error-pkcs12-duplicate-data = Not imported, already in database.
sec-error-message-send-aborted = Message not sent.
sec-error-inadequate-key-usage = Certificate key usage inadequate for attempted operation.
sec-error-cert-addr-mismatch = Address in signing certificate does not match address in message headers.
sec-error-bad-nickname = Certificate nickname already in use.
sec-error-not-fortezza-issuer = Peer FORTEZZA chain has a non-FORTEZZA Certificate.
sec-error-cannot-move-sensitive-key = A sensitive key cannot be moved to the slot where it is needed.
sec-error-js-invalid-module-name = Invalid module name.
sec-error-js-invalid-dll = Invalid module path/filename
sec-error-js-add-mod-failure = Unable to add module
sec-error-js-del-mod-failure = Unable to delete module
sec-error-old-krl = New KRL is not later than the current one.
sec-error-cert-not-in-name-space = The Certifying Authority for this certificate is not permitted to issue a certificate with this name.
sec-error-krl-not-yet-valid = The key revocation list for this certificate is not yet valid.
sec-error-crl-not-yet-valid = The certificate revocation list for this certificate is not yet valid.
sec-error-unknown-cert = The requested certificate could not be found.
sec-error-unknown-signer = The signer's certificate could not be found.
sec-error-cert-bad-access-location = The location for the certificate status server has invalid format.
sec-error-ocsp-unknown-response-type = The OCSP response cannot be fully decoded; it is of an unknown type.
sec-error-ocsp-bad-http-response = The OCSP server returned unexpected/invalid HTTP data.
sec-error-ocsp-malformed-request = The OCSP server found the request to be corrupted or improperly formed.
sec-error-ocsp-server-error = The OCSP server experienced an internal error.
sec-error-ocsp-try-server-later = The OCSP server suggests trying again later.
sec-error-ocsp-request-needs-sig = The OCSP server requires a signature on this request.
sec-error-ocsp-unauthorized-request = The OCSP server has refused this request as unauthorized.
sec-error-ocsp-unknown-response-status = The OCSP server returned an unrecognizable status.
sec-error-ocsp-unknown-cert = The OCSP server has no status for the certificate.
sec-error-ocsp-not-enabled = You must enable OCSP before performing this operation.
sec-error-ocsp-no-default-responder = You must set the OCSP default responder before performing this operation.
sec-error-ocsp-malformed-response = The response from the OCSP server was corrupted or improperly formed.
sec-error-ocsp-unauthorized-response = The signer of the OCSP response is not authorized to give status for this certificate.
sec-error-ocsp-future-response = The OCSP response is not yet valid (contains a date in the future).
sec-error-ocsp-old-response = The OCSP response contains out-of-date information.
sec-error-digest-not-found = The CMS or PKCS #7 Digest was not found in signed message.
sec-error-unsupported-message-type = The CMS or PKCS #7 Message type is unsupported.
sec-error-module-stuck = PKCS #11 module could not be removed because it is still in use.
sec-error-bad-template = Could not decode ASN.1 data. Specified template was invalid.
sec-error-crl-not-found = No matching CRL was found.
sec-error-reused-issuer-and-serial = You are attempting to import a cert with the same issuer/serial as an existing cert, but that is not the same cert.
sec-error-busy = NSS could not shutdown. Objects are still in use.
sec-error-extra-input = DER-encoded message contained extra unused data.
sec-error-unsupported-elliptic-curve = Unsupported elliptic curve.
sec-error-unsupported-ec-point-form = Unsupported elliptic curve point form.
sec-error-unrecognized-oid = ობიექტის იდენტიფიკატორი უცნობია.
sec-error-incompatible-pkcs11 = PKCS #11 წამყვანი არღვევს სპეციფიკაციას და არათავსებადია.
sec-error-no-event = ამ დროისთვის ახალი ბუდე არაა.
sec-error-crl-already-exists = სია უკვე არსებობს.
