# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

report-broken-site-mainview-title = არეული საიტის მოხსენება
report-broken-site-panel-header =
    .label = არეული საიტის მოხსენება
    .title = არეული საიტის მოხსენება
report-broken-site-panel-intro-text = თქვენი მოხსენება გვეხმარება ხარვეზების გამოვლენაში, რომ გამოვასწოროთ { -brand-product-name } და გავხადოთ უკეთესი ყველასთვის.
report-broken-site-panel-learn-more-link = ვრცლად
report-broken-site-panel-reason-load-moz-box-button =
    .label = საიტი არ იტვირთება
# These terms are referring to ecommerce websites
report-broken-site-panel-reason-checkout-moz-box-button =
    .label = ვერ ხერხდება გადახდა, გამოწერა ან შეძენა
report-broken-site-panel-reason-slow-moz-box-button =
    .label = საიტი შენელებულია
report-broken-site-panel-reason-media-moz-box-button =
    .label = ვიდეო ვერ ეშვება ან ვერ იტვირთება
report-broken-site-panel-reason-content-moz-box-button =
    .label = აკლია ნაწილები
report-broken-site-panel-reason-account-moz-box-button =
    .label = ანგარიშში შესვლა ან ახლის შექმნა ვერ ხერხდება
report-broken-site-panel-reason-adblocker-moz-box-button =
    .label = საიტი ითხოვს რეკლამის შემზღუდავის გათიშვას
report-broken-site-panel-reason-notsupported-moz-box-button =
    .label = ბრაუზერი არაა მხარდაჭერილი ან იზღუდება
report-broken-site-panel-reason-other-moz-box-button =
    .label = სხვა
report-broken-site-panel-send-more-info-button =
    .label = დაწვრილებით მონაცემების გაგზავნა
report-broken-site-panel-intro = დაგვეხმარეთ, რომ გავაუმჯობესოთ { -brand-product-name } ყველასთვის. { -vendor-short-name } თქვენ მიერ გამოგზავნილ მონაცემებს იყენებს ვებსაიტზე ხარვეზების მოსაგვარებლად.
report-broken-site-panel-url = ბმული
report-broken-site-panel-reason-label = რა დაზიანდა?
report-broken-site-panel-reason-optional-label = რა დაზიანდა? (არასავალდებულო)
report-broken-site-panel-reason-choose =
    .label = მიზეზის არჩევა
report-broken-site-panel-reason-load =
    .label = საიტი არ იტვირთება
# These terms are referring to ecommerce websites
report-broken-site-panel-reason-checkout =
    .label = ვერ ხერხდება გადახდა, გამოწერა ან შეძენა
report-broken-site-panel-reason-slow2 =
    .label = საიტი შენელებულია
report-broken-site-panel-reason-media2 =
    .label = ვიდეო ვერ ეშვება ან ვერ იტვირთება
report-broken-site-panel-reason-content2 =
    .label = აკლია ნაწილები
report-broken-site-panel-reason-account2 =
    .label = ანგარიშში შესვლა ან ახლის შექმნა ვერ ხერხდება
report-broken-site-panel-reason-adblocker2 =
    .label = საიტი ითხოვს რეკლამის შემზღუდავის გათიშვას
report-broken-site-panel-reason-notsupported =
    .label = ბრაუზერი არაა მხარდაჭერილი ან იზღუდება
report-broken-site-panel-reason-other =
    .label = სხვა
report-broken-site-panel-description-label = ხარვეზის აღწერა
report-broken-site-panel-description =
    .placeholder = რა მოხდა? რა უნდა მომხდარიყო? შედეგი ჰქონდა თვალთვალისგან დაცვის გამორთვას?
report-broken-site-panel-description-optional-label = აღწერეთ ხარვეზი (არასავალდებულო)
report-broken-site-panel-send-more-info-link = დაწვრილებით მონაცემების გაგზავნა
report-broken-site-panel-button-cancel =
    .label = გაუქმება
report-broken-site-panel-button-okay =
    .label = კარგი
report-broken-site-panel-button-send =
    .label = გაგზავნა
report-broken-site-panel-report-sent-label = თქვენი მოხსენება გაგზავნილია
report-broken-site-panel-report-sent-header =
    .label = თქვენი მოხსენება გაგზავნილია
    .title = თქვენი მოხსენება გაგზავნილია
report-broken-site-panel-report-sent-text = გმადლობთ რომ გვეხმარებით, თქვენი მხარდაჭერით { -brand-product-name } ცდილობს აქციოს ვებსივრცე მეტად გახსნილი, ხელმისაწვდომი და საყოველთაო სარგებლის მომტანი.
report-broken-site-panel-invalid-url-label = გთხოვთ შეიყვანეთ მართებული URL-ბმული
report-broken-site-panel-missing-reason-label = გთხოვთ მიუთითოთ მიზეზი
report-broken-site-panel-blocked-trackers-label =
    .label = თვალთვალისგან დაცვისას შეზღუდული ბმულების გადაგზავნა
report-broken-site-panel-blocked-trackers-description = თვალთვალისგან გაძლიერებულმა დაცვამ ზოგიერთ საიტზე შეიძლება შეზღუდოს გამართულად მუშაობისთვის საჭირო მეთვალყურეები და სკრიპტები.
report-broken-site-panel-preview-button =
    .label = მოხსენების შეთვალიერება
report-broken-site-panel-preview-header2 =
    .title = მოხსენების შეთვალიერება
report-broken-site-panel-preview-header =
    .label = მოხსენების შეთვალიერება
