# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Ви хочете довіряти “%S” для таких цілей?
unnamedCA = Центр сертифікації (безіменний)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Введіть пароль, який був використаний для шифрування цієї резервної копії сертифіката:
# Page Info
pageInfo_NoEncryption = З'єднання не зашифроване
pageInfo_Privacy_None1 = Сайт %S не підтримує шифрування для цієї сторінки.
pageInfo_Privacy_None2 = Інформація, переслана по інтернету без шифрування, може бути перехоплена під час передачі.
pageInfo_Privacy_None4 = Сторінка, яку ви переглядаєте, не була зашифрована перед тим, як була передана через Інтернет.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = З'єднання зашифроване (%1$S, ключі %2$S біт, %3$S)
pageInfo_BrokenEncryption = Пошкоджене шифрування (%1$S, довжина ключів %2$S біт, %3$S)
pageInfo_Privacy_Encrypted1 = Сторінка, яку ви переглядаєте, була зашифрована перед тим, як була передана через Інтернет.
pageInfo_Privacy_Encrypted2 = Шифрування значно ускладнює перегляд інформації, що передається між комп'ютерами, сторонніми особами. Тому малоймовірно, що хтось зможе прочитати цю сторінку під час її передавання в мережі.
pageInfo_MixedContent = З'єднання частково зашифроване
pageInfo_MixedContent2 = Частини сторінки, яку ви переглядаєте, не були зашифровані перед їх передаванням в Інтернеті.
pageInfo_WeakCipher = Ваше з'єднання з цим вебсайтом використовує слабке шифрування і не є приватним. Інші люди можуть переглядати вашу інформацію чи змінювати поведінку вебсайту.
pageInfo_CertificateTransparency_Compliant = Цей вебсайт відповідає вимогам політики Прозорості Сертифікату.
# Token Manager
password_not_set = (не встановлено)
