# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = ဒီကွန်ရက် စာမျက်နှာကို နေရာသစ်ဆီ လမ်းလွှဲနေတယ်။ နေရာသစ်မှာ သင်ရေးထည့်တဲ့ ပုံစံဖြည့် အချက်အလက်ကို သင် ပြန်ပို့လိုသလား။
# Directory listing strings
DirTitle = %1$S ၏ အညွှန်း
DirGoUp = ဖိုင်တွဲ အပေါ်တစ်ဆင့်တက်ရန်
ShowHidden = ကွယ်ဝှက်ထားသော အရာများကို ပြသပါ
DirColName = အမည်
DirColSize = အရွယ်အ​စား
DirColMTime = နောက်ဆုံး မွမ်းမံခဲ့သောချိန်
DirFileLabel = ဖိုင် -
UnsafeUriBlocked = The resource at “%1$S” was blocked by Safe Browsing.
