# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = નીચે અાપેલા પ્રયોજન માટે તમે "%S" પર વિશ્વાસ કરવા માંગો છે?
unnamedCA = સત્તાને પ્રમાણીત કરો (નામ નહી અાપેલુ)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = મહેરબાની કરીને પાસવર્ડ દાખલ કરો કે જે આ પ્રમાણપત્ર બૅકઅપ એનક્રિપ્ટ કરવા માટે વાપરવામાં આવ્યું હતું:
# Page Info
pageInfo_NoEncryption = જોડાણ એનક્રિપ્ટ થયેલ નથી
pageInfo_Privacy_None1 = વેબ સાઈટ %S તમે જે પાનું જોઈ રહ્યા છો તેના માટે એનક્રિપ્શનને આધાર આપતું નથી.
pageInfo_Privacy_None2 = એનક્રિપ્શન વિના ઈન્ટરનેટ ઉપર મોકલાયેલ જાણકારી અન્ય લોકો દ્વારા જોઈ શકાય છે જ્યારે તે પરિવહન થઈ રહી હોય.
pageInfo_Privacy_None4 = તમે જોઈ રહ્યાં છો તે પૃષ્ઠ ઇન્ટરનેટ પર પ્રસારિત થતાં પહેલાં એન્ક્રિપ્ટ કરેલું નથી.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = કનેક્શન એન્ક્રિપ્ટેડ (%1$S, %2$S bit keys, %3$S)
pageInfo_BrokenEncryption = તૂટેલી એન્ક્રિપ્શન (%1$S, %2$S bit કીઓ, %3$S)
pageInfo_Privacy_Encrypted1 = તમે જોઈ રહ્યાં છો તે પૃષ્ઠ ઇન્ટરનેટ પર પ્રસારિત થતાં પહેલાં એન્ક્રિપ્ટ કરાયું હતું.
pageInfo_Privacy_Encrypted2 = એન્ક્રિપ્શન અનધિકૃત લોકો કમ્પ્યુટર્સ વચ્ચે મુસાફરીની માહિતી જોવાનું મુશ્કેલ બનાવે છે. તે અસંભવિત છે કે કોઈ પણ વ્યક્તિ આ પૃષ્ઠને વાંચે છે કારણ કે તે સમગ્ર નેટવર્કમાં પ્રવાસ કરે છે.
pageInfo_MixedContent = જોડાણ અંશતઃ એનક્રિપ્ટ થયેલ છે
pageInfo_MixedContent2 = ઇન્ટરનેટ પર પ્રસારિત થતાં પહેલાં તમે જે પાનું જોઈ રહ્યાં છો તે ભાગ એનક્રિપ્ટ થયેલ ન હતા.
pageInfo_WeakCipher = આ વેબસાઇટ પરનું તમારું જોડાણ નબળા એન્ક્રિપ્શનનો ઉપયોગ કરે છે અને ખાનગી નથી. અન્ય લોકો તમારી માહિતી જોઈ શકે છે અથવા વેબસાઈટના વર્તનને સુધારી શકે છે.
pageInfo_CertificateTransparency_Compliant = આ વેબસાઇટ પ્રમાણપત્ર પારદર્શિતા નીતિનું પાલન કરે છે.
# Token Manager
password_not_set = (ગોઠવેલ નથી)
