# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Acerca dos seus direitos
rights-intro = O { -brand-full-name } é um software livre e de código aberto, construído por uma comunidade de milhares de pessoas por todo o mundo. Existem algumas coisas que deve saber:
rights-intro-point-4 = Como é que usamos a sua informação pessoal e feedback enviados para a { -vendor-short-name } através do { -brand-short-name } é descrito na <a data-l10n-name="mozilla-privacy-policy-link">Política de privacidade do { -brand-short-name }</a>.
rights-webservices-term-3 = Está à vontade para utilizar estes Serviços que acompanham a sua versão do { -brand-short-name }, e a { -vendor-short-name } concede-lhe os direitos necessários para o fazer.  A { -vendor-short-name } e os seus licenciantes reservam todos os outros direitos nos Serviços.  Estes termos não têm a intenção de limitar quaisquer direitos sobre as licenças de código aberto aplicáveis ao { -brand-short-name } e às correspondentes versões do código fonte do { -brand-short-name }.
rights-webservices-term-4 = <strong>Os serviços são disponibilizados "as-is."  A { -vendor-short-name }, os seus contribuidores, licenciantes e distribuidores renunciam a todas as garantias, sejam elas explícitas ou implícitas, incluindo sem limites, garantias que o serviço é comercial e serve para os seus objetivos pessoais.  Você é responsável por selecionar os serviços para os seus propósitos, assim como a qualidade e o desempenho dos serviços. Algumas jurisdições não permitem a exclusão ou a limitação de garantias implícitas, como tal este aviso poderá não ser adequado para si.</strong>
rights-webservices-term-5 = <strong>Exceto quando obrigatório por lei, a { -vendor-short-name }, os seus contribuidores, licenciantes e distribuidores não poderão ser responsabilizados por qualquer dano indireto, especial, acidental, consequente, punitivo, exemplares ou danos diretos decorrentes da utilização do { -brand-short-name } e os seus serviços.  A responsabilidade coletiva sob estes termos, não poderá exceder $500 (quinhentos dólares). Algumas jurisdições não permitem a exclusão ou a limitação de alguns danos e, como tal, esta exclusão e limitação poderá não ser aplicável a si.</strong>
