# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language-name-aa = آفاری
language-name-ab = آبخازی
language-name-ach = آچولی
language-name-ae = اوستایی
language-name-af = آفریکانس
language-name-ak = آکدی
language-name-am = ٱمهری
language-name-an = آراگونی
language-name-ar = عروی
language-name-as = آسامی
language-name-ast = آستوریاسی
language-name-av = آواری
language-name-ay = آیمارایی
language-name-az = تۊرکی آذربایجۊوی
language-name-ba = باشغیری
language-name-be = بلارۊسی
language-name-bg = بولغاری
language-name-bh = بیهاری
language-name-bi = بیسلاما
language-name-bm = بامبارایی
language-name-bn = بنگالی
language-name-bo = تبتی
language-name-br = برتانیایی
language-name-bs = بوسنیایی
language-name-ca = کاتالونیایی
language-name-cak = کاکچیکل
language-name-ce = چچنی
language-name-ch = چامورویی
language-name-co = کورسیایی
language-name-cr = کریایی
language-name-crh = تاتاری کریمه
language-name-cs = چکی
language-name-csb = کاشۊبی
language-name-cu = اسلاوی کلیسایی
language-name-cv = چۊواشی
language-name-cy = ویلزی
language-name-da = دانمارکی
language-name-de = آلمانی
language-name-dsb = سربی سفلی
language-name-dv = دیوهی
language-name-dz = جونخایی
language-name-en = اینگیلیسی
language-name-eo = اسپرانتو
language-name-es = اسپانیایی
language-name-et = استونیایی
language-name-eu = باسکی
language-name-fa = فارسی
