# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelAddItem = Əlavə et
dialogAcceptLabelSaveItem = Dəyişiklikləri saxla
dialogAcceptLabelAddMulti = Əlfəcinləri Əlavə et
dialogAcceptLabelEdit = Dəyişiklikləri saxla
dialogTitleAddBookmark = Yeni Əlfəcin
dialogTitleAddFolder = Qovluq əlavə et
dialogTitleAddMulti = Yeni Əlfəcinlər
dialogTitleEdit = “%S” xüsusiyyətləri
dialogTitleAddBookmarksFolder = Əlfəcin qovluğu əlavə et
dialogTitleAddBookmarkFolder = Əlfəcin qovluğu əlavə et
bookmarkAllTabsDefault = [Qovluq adı]
newFolderDefault = Qovluq əlavə et
newBookmarkDefault = Yeni Əlfəcin
