# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Tražim { $host }…
network-connection-status-connected = Povezan na { $host }…
network-connection-status-sending-request = Šaljem zahtjev na { $host }…
network-connection-status-transferring-data = Prijenos podataka sa { $host }…
network-connection-status-connecting = Povezujem se na { $host }…
network-connection-status-read = Pročitano { $host }
network-connection-status-wrote = Zapisano { $host }
network-connection-status-waiting = Čekam na { $host }…
network-connection-status-looked-up = Potražio { $host }…
network-connection-status-tls-handshake = Izvršavam TLS handshake sa { $host }…
network-connection-status-tls-handshake-finished = Završen je TLS handshake sa { $host }…
