# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=Boalo jwa $ProductName$
Welcome_MessageWelcome=O amogelesegile mo %s!
Welcome_Message0=You are about to install %s 2 Alpha 1.
Welcome_Message1=Go atlenegisiwa thata gore o tswe mo diporokeramong tsotlhe tsa Windows pele fa o tsamaisa porokeramo eno ya Boalo.
Welcome_Message2=Tobetsa Khansela go tloga mo Boalong mme o tswale diporokeramo tsotlhe tse di tsamayang.  Tobetsa Latelang go tswelela pele ka porokeramo ya Boalo.
Welcome_Message3=Click Next to continue installing %s 2 Alpha 1.

License_Title=Tumelano ya Laesense ya Serweboleta
License_SubTitle=Mabaka le dipeelo tsa go dirisa serweboleta seno.
License_Message0=Tsweetswee buisa tumelano e e latelang ya laesense. Dirisa baratshutiso go leba tumelano eno yotlhe.
License_Accept=Ke &Amogela mabaka a Tumelano ya Laesense
License_Decline=Ga K&E amogele mabaka a Tumelano ya Laesense

Type_Title=Mofuta wa Boalo
Type_SubTitle=Tlhopha diitlhophelwa tsa boalo.
Type_Message0=Tlhopha mofuta wa Boalo o o ratang, mme o tobetse Latelang.

Standard_Short=&Boemo
Standard_Long=Thunderbird e tla tlhomiwa ka diitlhophelwa tse di tlwaelegileng go gaisa.

Custom_Short=&Magoro
Custom_Long=O ka tlhopha diitlhophelwa tse di tshwanetseng go tlhomiwa. E atlenegisediwa badirisi ba ba nang le maitemogelo.

Select_Title=Tlhopha Dikarolowana
Select_SubTitle=Dikarolwana tsa tlaleletso tse di tokafatsang $ProductName$.
Select_Message0=Tlhopha dikarolwana tsa tlaleletso tse o batlang go di tlhoma, mme o tobetse Latelang.

Path_Title=Tlhoma Setsholadifaele
Path_SubTitle=Moo $ProductName$ e tla tlhomiwang gona.
Path_Message0=$ProductName$ e tla tlhomiwa mo setsholadifaeleng se se latelang:

Integration_Title=Tselakhutshwane ya Boalo
Integration_SubTitle=E Tlhama Diaekhone tsa Porokeramo
Integration_Message0=Tlhoma diaekhone tsa $ProductShortName$:

Integration_Desktop=Mo Desktop ya me
Integration_StartMenu=Mo Setsholadifaeleng sa me sa Diporokeramo tsa Lenanekhomphiutara la Simolola
Integration_QuickLaunch=Mo bareng ya me ya Simolola ka Bonako

SelectFolder_Title=Boalo jwa $ProductName$ - Tlhopha Setsholadifaele sa kungo
SelectFolder_Message0=Boalo bo tla tlhakanya diaekhone mo setsholadifaeleng tsa sa Diporokeramo se se kwadilweng fa tlase.  O ka nna wa tlanya leina le lentšhwa la setsholadifaele, kgotsa wa tlhopha nngwe go tswa mo lenaneng la Ditsholadifaele tse di leng teng.  Tobetsa latelang go tswelela.

Advanced_Title=Boalo jwa $ProductName$ - Boalo jo bo Tsweletseng
Advanced_Message0=Fa kgolagano ya gago ya inthanete e tlhoka kgatlho ya kemela, kwala leina la dikgatlho tsa gago le tshedimosetso ka setshwaraganyi.  Fa kgolagano ya gago ya inthanete e sa tlhoke dikgatlho tsa kemela, tlogela tsela e le lolela.

Install_Title=Tshobokanyo
Install_SubTitle=E siametse go simolola go tlhoma $ProductName$.
Install_MessageInstall=Boalo jaanong bo tla tlhoma dikarolwana tse di latelang:
Install_MessageDownload=Boalo jaanong bo tla kopolola le go tlhoma dikarolwana tse di latelang:
Install_Message0=Tobetsa Latelang go tswelela.

Downloading_Title=E a kopolola
Downloading_SubTitle=E kopolola dikarolwana tse di tlhokegang...
Downloading_Blurb=Boalo bo kopolola difaele tse di tlhokegang go tlhoma $ProductName$.
Downloading_FileName=Ga jaana e kopolola:
Downloading_Time=Nako e e setseng:

Installing_Title=E tlhoma
Installing_SubTitle=E tlhoma $ProductName$...
Installing_Blurb=Boalo bo tlhoma difaele tsa serweboleta.
Installing_Status=E Baakanya faele:
Installing_Component=Ga jaana e tlhoma:

Success_Title=Tlhomo e Feditswe
Success_Header=Tlhomo e Feditswe
Success_Message0=%s was successfully installed.
Success_Message1=Tobetsa Fetsa go wetsa Boalo.
Success_Launch=Launch %s now.

Check_Message=Kopololo ya $ProductName$ e atlegile. $ProductNameInternal$ e tshwanetse go tswalwa go tswelela ka tlhomo. Tobetsa OK go tswa mo $ProductNameInternal$ ka boitiriso le go simolola tlhomo.
Check_FullMessage=$ProductNameInternal$ e tshwanetse go tswalwa gore go tswelelwe ka tlhomo. Tobetsa OK go tswa mo $ProductNameInternal$ ka boitiriso le go simolola tlhomo.
Check_Wait=Go tswalwa $ProductNameInternal$.  Tsweetswee leta...

Component_XPCOM=Polatefomo-thalalo COM
Component_Mail=$ProductName$
Component_Offline=Tshegetso ya mo kgaogong ya nakwana
Component_Offline_Long=E tsenya tshegetso ya mo Kgaogong ya Nakwana mo Posong ya $ProductName$.
Component_RSS=Tshegetso ya RSS
Component_RSS_Long=E tsenya tshegetso ya RSS mo $ProductName$.
Component_QFA=Moemedi wa Pegelo ya Boleng
Component_QFA_Long=go bega tshedimosetso ya phutlhamo ya $ProductName$
