# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Saqlanğan İçeri İmzalanışlar
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = URL'ni kopiyala
    .accesskey = o
launch-site-url-cmd =
    .label = URL'ni ziyaret et
    .accesskey = z
copy-username-cmd =
    .label = Qullanıcı Adını Kopiyala
    .accesskey = u
edit-username-cmd =
    .label = Qullanıcı-adını Tarir Et
    .accesskey = u
copy-password-cmd =
    .label = Sır-sözni Kopiyala
    .accesskey = K
edit-password-cmd =
    .label = Sır-sözni Tarir Et
    .accesskey = S
search-filter =
    .accesskey = d
    .placeholder = Qıdır
column-heading-site =
    .label = Sayt
column-heading-username =
    .label = Qullanıcı adı
column-heading-password =
    .label = Sır-söz
column-heading-time-created =
    .label = İlk Qullanım
column-heading-time-last-used =
    .label = Soñ Qullanım
column-heading-time-password-changed =
    .label = Soñ Deñiştiriliş
column-heading-times-used =
    .label = Qullanım Sayısı
remove =
    .label = Çetleştir
    .accesskey = r
import =
    .label = İtal Et…
    .accesskey = t
close-button =
    .label = Qapat
    .accesskey = Q
show-passwords =
    .label = Sır-sözlerni Köster
    .accesskey = S
hide-passwords =
    .label = Sır-sözlerni Gizle
    .accesskey = S
logins-description-all = Bilgisayarıñız üzerinde aşağıdaki saytlardan içeri-imzalanışlar mağazlanğandır
logins-description-filtered = Aşağıdaki içeri imzalanışlar qıdırmañız ile eşleşe:
remove-all =
    .label = Episini Çetleştir
    .accesskey = e
remove-all-shown =
    .label = Kösterilgenlerniñ Episini Çetleştir
    .accesskey = e
remove-all-passwords-prompt = Sır-sözlerniñ episini silmege istegeniñizden eminsiñizmi?
remove-all-passwords-title = Episi sır-sözlerni sil
no-master-password-prompt = Parolleriñizni köstermege istegeniñizden eminsiñizmi?
auto-fill-logins-and-passwords =
    .label = İçeri-imzalanışlarnı ve sır-sözlerni saqla
