# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

CertPasswordPromptDefault = Introduz la contraseña primaria, por favor.
# LOCALIZATION NOTE (ManufacturerID): string limit is 32 bytes after conversion
# to UTF-8.
# length_limit = 32 bytes
ManufacturerID = Mozilla.org
certErrorTrust_SelfSigned = El certificáu nun ye d'enfotu porque se robló a sigo mesmu.
CertExceptionPermanent = Permanente
CertExceptionTemporary = Temporal
