# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = 保存
dialogTitleAddBookmark = 新規ブックマーク
dialogTitleAddMulti = 新規ブックマーク
dialogTitleEdit = "%S" の情報
dialogTitleAddNewBookmark2 = 新規ブックマークを追加
dialogTitleEditBookmark = “%S” を編集
dialogTitleEditBookmark2 = ブックマークを編集
dialogTitleAddBookmarkFolder = ブックマークフォルダーを追加
dialogTitleEditBookmarkFolder = ブックマークフォルダーを編集
bookmarkAllTabsDefault = [フォルダーの名前]
newFolderDefault = 名称未設定フォルダー
newBookmarkDefault = 新規ブックマーク
