# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

appmenu-update-available =
    .label = Al è disponibil un gnûf inzornament par { -brand-shorter-name }.
    .buttonlabel = Discjame inzornament
    .buttonaccesskey = D
    .secondarybuttonlabel = No cumò
    .secondarybuttonaccesskey = N
appmenu-update-available-message = Inzorne { -brand-shorter-name } par otignî la velocitât e la riservatece plui resinte.
appmenu-update-manual =
    .label = { -brand-shorter-name } nol pues inzornâsi ae ultime version.
    .buttonlabel = Discjame { -brand-shorter-name }
    .buttonaccesskey = D
    .secondarybuttonlabel = No cumò
    .secondarybuttonaccesskey = N
appmenu-update-manual-message = Discjame une gnove copie di { -brand-shorter-name } e ti judarìn a instalâle.
appmenu-update-whats-new =
    .value = Viôt lis novitâts!
appmenu-update-unsupported =
    .label = { -brand-shorter-name } nol rive a inzornâsi ae ultime version.
    .buttonlabel = Plui informazions
    .buttonaccesskey = P
    .secondarybuttonlabel = Siere
    .secondarybuttonaccesskey = s
appmenu-update-unsupported-message = Il to sisteme nol è supuartât de ultime version di { -brand-shorter-name }.
appmenu-update-restart =
    .label = Torne invie par inzornâ { -brand-shorter-name }.
    .buttonlabel = Torne a inviâ e ripristine
    .buttonaccesskey = R
    .secondarybuttonlabel = No cumò
    .secondarybuttonaccesskey = N
appmenu-update-restart-message = Dopo che si sarà tornât a inviâ, { -brand-shorter-name } al ripristinarà ducj i barcons e lis schedis viertis che no son in modalitât navigazion privade.
appmenu-update-available2 =
    .label = Inzornament disponibil
    .buttonlabel = Discjame
    .buttonaccesskey = D
    .secondarybuttonlabel = Ignore
    .secondarybuttonaccesskey = I
appmenu-update-available-message2 = Discjame la ultime version di { -brand-shorter-name }.
appmenu-update-manual2 =
    .label = Inzornament disponibil
    .buttonlabel = Discjame
    .buttonaccesskey = D
    .secondarybuttonlabel = Ignore
    .secondarybuttonaccesskey = g
appmenu-update-manual-message2 = { -brand-shorter-name } nol è rivât a inzornâsi in automatic. Discjame la gnove version — no tu pierdarâs lis personalizazions o lis informazions salvadis.
appmenu-update-unsupported2 =
    .label = Impussibil inzornâ
    .buttonlabel = Plui informazions
    .buttonaccesskey = L
    .secondarybuttonlabel = Scarte
    .secondarybuttonaccesskey = c
appmenu-update-unsupported-message2 = Il to sisteme operatîf nol è compatibil cu la ultime version di { -brand-shorter-name }.
appmenu-update-restart2 =
    .label = Inzornament disponibil
    .buttonlabel = Inzorne e torne invie
    .buttonaccesskey = z
    .secondarybuttonlabel = Ignore
    .secondarybuttonaccesskey = n
appmenu-update-restart-message2 = Oten la ultime version di { -brand-shorter-name }. Lis schedis e i barcons vierts a vignaran ripristinâts.
appmenu-update-other-instance =
    .label = { -brand-shorter-name } nol rive a inzornâsi in automatic ae ultime version.
    .buttonlabel = Inzorne { -brand-shorter-name } distès
    .buttonaccesskey = I
    .secondarybuttonlabel = No cumò
    .secondarybuttonaccesskey = N
appmenu-update-other-instance-message = Al è disponibil un gnûf inzornament di { -brand-shorter-name }, ma no si pues instalâ par vie che e je in esecuzion une altre copie di { -brand-shorter-name }. Sierile par continuâ l'inzornament, o sielç di inzornâ distès (chê altre copie  e podarès no lavorâ ben fintremai che no tu le tornis a inviâ).
appmenu-addon-private-browsing-installed =
    .buttonlabel = Va ben, capît!
    .buttonaccesskey = V
appmenu-addon-post-install-message = Gjestìs lis tôs zontis fasint clic <image data-l10n-name='addon-install-icon'></image> intal menù <image data-l10n-name='addon-menu-icon'></image>.
appmenu-addon-private-browsing-installed2 =
    .buttonlabel = Va ben
    .buttonaccesskey = V
appmenu-addon-post-install-message2 = Gjestìs lis tôs estensions e i temis midiant il menù aplicazion.
appmenu-addon-post-install-message3 = Gjestìs lis tôs zontis e i temis midiant il menù aplicazion.
appmenu-addon-post-install-incognito-checkbox =
    .label = Permet a cheste estension di zirâ tai barcons privâts
    .accesskey = P
appmenu-new-tab-controlled =
    .label = La tô gnove schede e je cambiade.
    .buttonlabel = Ten lis modifichis
    .buttonaccesskey = T
    .secondarybuttonlabel = Disabilite la estension
    .secondarybuttonaccesskey = D
appmenu-homepage-controlled =
    .label = La tô pagjine iniziâl e je cambiade.
    .buttonlabel = Ten lis modifichis
    .buttonaccesskey = T
    .secondarybuttonlabel = Disabilite la estension
    .secondarybuttonaccesskey = D
appmenu-new-tab-controlled-changes =
    .label = La tô gnove schede e je cambiade.
    .buttonlabel = Ten lis modifichis
    .buttonaccesskey = T
    .secondarybuttonlabel = Gjestìs lis gnovis schedis
    .secondarybuttonaccesskey = G
appmenu-homepage-controlled-changes =
    .label = La tô pagjine iniziâl e je cambiade.
    .buttonlabel = Ten lis modifichis
    .buttonaccesskey = T
    .secondarybuttonlabel = Gjestìs la pagjine iniziâl
    .secondarybuttonaccesskey = G
appmenu-tab-hide-controlled =
    .label = Acedi aes tôs schedis platadis
    .buttonlabel = Ten platadis lis schedis
    .buttonaccesskey = T
    .secondarybuttonlabel = Disabilite la estension
    .secondarybuttonaccesskey = D
