# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = Vierç
    .accesskey = V
places-open-tab =
    .label = Vierç intune gnove lengute
    .accesskey = l
places-open-all-in-tabs =
    .label = Vierç ducj intes lengutis
    .accesskey = d
places-open-window =
    .label = Vierç intun gnûf barcon
    .accesskey = b
places-new-bookmark =
    .label = Gnûf segnelibri…
    .accesskey = b
places-new-folder-contextmenu =
    .label = Gnove cartele…
    .accesskey = F
places-new-folder =
    .label = Gnove cartele…
    .accesskey = o
places-new-separator =
    .label = Gnûf separadôr
    .accesskey = s
places-view =
    .label = Viodude
    .accesskey = o
places-by-date =
    .label = Par date
    .accesskey = P
places-by-site =
    .label = Par sît
    .accesskey = P
places-by-most-visited =
    .label = Par plui visitât
    .accesskey = P
places-by-last-visited =
    .label = Par ultin visitât
    .accesskey = u
places-by-day-and-site =
    .label = Par date e sît
    .accesskey = P
places-delete-domain-data =
    .label = Dismentee chest sît
    .accesskey = D
places-sortby-name =
    .label = Met in ordin par non
    .accesskey = r
places-properties =
    .label = Proprietâts
    .accesskey = i
