# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

print-setup =
    .title = साहटा साजाव
custom-prompt-title = कुसियाक् तेयार …
custom-prompt-prompt = आमक कुसियाक्  तेयार चेतान /लातार ञुतुम  ओनो ल आदेर मे
basic-tab =
    .label = तेयार आपनार मोने तेयाक्.
advanced-tab =
    .label = साहटा सिमा़ साहटा चेतान/ साहटा लातार
format-group-label =
    .value = तेयार
orientation-label =
    .value = झालकावाक् जिनिस:
portrait =
    .label = चिता़र बेनाव
    .accesskey = P
landscape =
    .label = ञेल ञामाक्
    .accesskey = L
scale =
    .label = नापाक्:
    .accesskey = S
scale-percent =
    .value = %
shrink-to-fit =
    .label = साहटा ओसार  खाप हा़विच् ओताय मे.
    .accesskey = W
options-group-label =
    .value = आपनार मोने तेयाक् को
print-bg =
    .label = छापा ओनोड़  (रोङ चिता़र को )
    .accesskey = B
margin-group-label-inches =
    .value = साहटा सिमा़  को (इंच को)
margin-group-label-metric =
    .value = साहटा सिमा़  को (मिलीमीटर को)
margin-top =
    .value = चेतान
    .accesskey = T
margin-top-invisible =
    .value = चेतान
margin-bottom =
    .value = लातार
    .accesskey = B
margin-bottom-invisible =
    .value = लातार
margin-left =
    .value = लेंगा:
    .accesskey = L
margin-left-invisible =
    .value = लेंगा:
margin-right =
    .value = जोजोम:
    .accesskey = R
margin-right-invisible =
    .value = जोजोम:
header-footer-label =
    .value = साहटा चेतान साहटालातार को
hf-left-label =
    .value = लेंगा:
hf-center-label =
    .value = ताला:
hf-right-label =
    .value = जोजोम सेत्:
header-left-tip =
    .tooltiptext = लेंगा सेदाक् चेतान ञुतुम
header-center-tip =
    .tooltiptext = तालामा चेतान ञुतुम
header-right-tip =
    .tooltiptext = जोजोम सेदाक् चेतान ञुतुम
footer-left-tip =
    .tooltiptext = लेंगा सेदाक् लातार ञुतुम
footer-center-tip =
    .tooltiptext = जोजोम सेदाक् लातार ञुतुम
footer-right-tip =
    .tooltiptext = जोजोम सेदाक् लातार ञुतुम
hf-blank =
    .label = --सादा--
hf-title =
    .label = ञुतुम एम
hf-url =
    .label = URL
hf-date-and-time =
    .label = मा़हित्/ओकतो
hf-page =
    .label = साहटा #
hf-page-and-total =
    .label = रेयाक् # साहटा #
hf-custom =
    .label = कुसियाक् तेयार …
print-preview-window =
    .title = छापा माड़ाङ तेयाक् ञेल.
print-title =
    .value = ञुतुम:
print-preparing =
    .value = तेयारेत् आ..
print-progress =
    .value = उथनाव:
print-window =
    .title = छापाक् काना
print-complete =
    .value = छापा दो पुरा़वेना.
# Variables
# $percent (integer) - Number of printed percentage
print-percent =
    .value = { $percent }%
dialog-cancel-label = बा़डरा़
dialog-close-label = बोंद मे
