# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

weekstart-label =
    .value = 周起始日为：
    .accesskey = r
dayweek-legend = 日周视图
visible-hours-label =
    .value = 每次显示：
    .accesskey = o
visible-hours-end-label =
    .value = 小时
day-start-label =
    .value = 每日开始于：
    .accesskey = D
day-end-label =
    .value = 每日结束于：
    .accesskey = y
multiweek-legend = 多周视图
number-of-weeks-label =
    .value = 默认显示周数 （包括前几周）：
    .accesskey = e
week-0-label =
    .label = 无
week-1-label =
    .label = 1 周
week-2-label =
    .label = 2 周
week-3-label =
    .label = 3 周
week-4-label =
    .label = 4 周
week-5-label =
    .label = 5 周
week-6-label =
    .label = 6 周
previous-weeks-label =
    .value = 显示之前周数：
    .accesskey = P
reminder-legend = 当提醒闹响时：
reminder-play-checkbox =
    .label = 播放声音
    .accesskey = s
reminder-default-sound-label =
    .label = 使用默认声音
    .accesskey = d
reminder-browse-sound-label =
    .label = 浏览…
    .accesskey = B
reminder-dialog-label =
    .label = 显示提醒框
    .accesskey = x
reminder-default-legend = 默认提醒设置
event-alarm-label =
    .value = 事件的默认提醒设置：
    .accesskey = e
alarm-on-label =
    .label = 开
alarm-off-label =
    .label = 关
task-alarm-label =
    .value = 任务的默认提醒设置：
    .accesskey = a
event-alarm-time-label =
    .value = 在事件触发前默认的提醒时间：
    .accesskey = u
task-alarm-time-label =
    .value = 在任务触发前默认的提醒时间：
    .accesskey = o
category-edit-label = 编辑类别
category-overwrite-title = 警告： 重复的名称
category-overwrite = 该名称类别已存在。 您是否希望覆盖该类别？
category-blank-warning = 您必须输入类别名称。
