# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Huruyan maa gaabuntey
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-username-cmd =
    .label = Goykaw maa berandi
    .accesskey = y
edit-username-cmd =
    .label = Goykaw maa fasal
    .accesskey = f
copy-password-cmd =
    .label = Šennikufal berandi
    .accesskey = b
edit-password-cmd =
    .label = Šennikufal fasal
    .accesskey = E
search-filter =
    .accesskey = C
    .placeholder = Ceeci
column-heading-site =
    .label = Nungu
column-heading-username =
    .label = Goykaw maa
column-heading-password =
    .label = Šennikufal
column-heading-time-created =
    .label = Goyandi cee jina
column-heading-time-last-used =
    .label = Goyandi cee kora
column-heading-time-password-changed =
    .label = Barmay cee kora
column-heading-times-used =
    .label = Goy ceehinna
remove =
    .label = Kaa
    .accesskey = K
import =
    .label = Cendi ka dam…
    .accesskey = C
close-button =
    .label = Daabu
    .accesskey = D
show-passwords =
    .label = Šennikufaley cebe
    .accesskey = P
hide-passwords =
    .label = Šennikufaley tugu
    .accesskey = P
logins-description-filtered = Huruyan tammaasawey wey ši sawa nda war ceeciroo:
remove-all =
    .label = Kul kaa
    .accesskey = K
remove-all-shown =
    .label = Cebantey kul kaa
    .accesskey = k
remove-all-passwords-prompt = Alhakiika war ga boonay ka war šennikufaley kaa?
remove-all-passwords-title = Šennikufaley kul kaa
no-master-password-prompt = Alhakiika war ga boona ka war šennikufaley cebe?
