# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

appmenu-update-available =
    .label = وەشانێکی نوێی { -brand-shorter-name } بەردەستە.
    .buttonlabel = ئێستا دایبگرە
    .buttonaccesskey = س
    .secondarybuttonlabel = جارێ نا
    .secondarybuttonaccesskey = N
appmenu-update-available-message = { -brand-shorter-name } نوێبکەرەوە بۆ نوێترین خێرایی و تایبەتی.
appmenu-update-manual =
    .label = { -brand-shorter-name } ناتوانرێت بەرزبکرێتەوە بۆ نوێترین وەشان.
    .buttonlabel = { -brand-shorter-name } دابگرە
    .buttonaccesskey = د
    .secondarybuttonlabel = ئێستا نا
    .secondarybuttonaccesskey = ن
appmenu-update-manual-message = وەشانێکی پاکی { -brand-shorter-name } دابگرە و ئێمە یارمەتیت دەدەین کە دایمەزرێنیت.
appmenu-update-whats-new =
    .value = بزانە چی نوێ هەیە.
appmenu-update-unsupported =
    .label = { -brand-shorter-name } ناتوانرێت بەرزبکرێتەوە بۆ نوێترین وەشان.
    .buttonlabel = زیاتر بزانە
    .buttonaccesskey = ز
    .secondarybuttonlabel = داخست
    .secondarybuttonaccesskey = د
appmenu-update-restart =
    .label = پێبکەرەوە بۆ نوێکردنەوە { -brand-shorter-name }.
    .buttonlabel = پێبکەرەوە بۆ نوێکردنەوە
    .buttonaccesskey = ێ
    .secondarybuttonlabel = ئێستا نا
    .secondarybuttonaccesskey = N
appmenu-addon-private-browsing-installed =
    .buttonlabel = باشە، تێگەشتم
    .buttonaccesskey = ب
appmenu-addon-post-install-incognito-checkbox =
    .label = ڕێگە بدە ئەم پێوەکراوە لە پەنجەرەی تایبەت کاربکات
    .accesskey = گ
appmenu-new-tab-controlled =
    .label = بازدەری نوێ گۆڕا.
    .buttonlabel = گۆڕانکارییەکان بهێڵەوە
    .buttonaccesskey = ب
    .secondarybuttonlabel = زیادکراوە ناچالاک بکە
    .secondarybuttonaccesskey = ن
appmenu-homepage-controlled =
    .label = پەڕەی سەرەکیت گۆڕانکاری بەسەرهات.
    .buttonlabel = گۆڕانکارییەکان بهێڵەوە
    .buttonaccesskey = ب
    .secondarybuttonlabel = زیادکراو ناچالاک بکە
    .secondarybuttonaccesskey = د
