# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = کردنەوە
    .accesskey = O
places-open-all-in-tabs =
    .label = هەمووی لە ناو بازدەرەکان بکەرەوە
    .accesskey = O
places-empty-bookmarks-folder =
    .label = (بەتاڵ)
places-view =
    .label = پیشاندان
    .accesskey = w
places-by-date =
    .label = بە پێی ڕۆژ
    .accesskey = D
places-by-site =
    .label = بەپێی ماڵپەڕ
    .accesskey = S
places-by-most-visited =
    .label = بەپێی زۆرترین سەردانکراو
    .accesskey = V
places-by-last-visited =
    .label = بەپێی دووا سەردانیکراو
    .accesskey = L
places-by-day-and-site =
    .label = بەپێی ڕۆژ و ماڵپەڕ
    .accesskey = t
places-history-search =
    .placeholder = گەڕان لە ناو مێژووی کاردا
places-history =
    .aria-label = مێژوو
places-bookmarks-search =
    .placeholder = گەڕان لە دڵخوازەکان
places-delete-domain-data =
    .label = دەربارەی ئەم ماڵپەڕە لە بیربکە
    .accesskey = F
places-sortby-name =
    .label = بەپێی ناو
    .accesskey = r
# Variables:
#   $count (number) - The number of pages selected for removal.
places-delete-page =
    .label =
        { $count ->
            [1] پەڕە بسڕەوە
           *[other] پەڕەکان بسڕەوە
        }
    .accesskey = D
places-library3 =
    .title = کتێبخانە
places-organize-button =
    .label = ڕێکخستنەوە
    .tooltiptext = ڕێککردنەوەی دڵخوازەکانت
    .accesskey = O
places-organize-button-mac =
    .label = ڕێکخستنەوە
    .tooltiptext = ڕێککردنەوەی دڵخوازەکانت
places-file-close =
    .label = داخستن
    .accesskey = C
places-cmd-close =
    .key = w
places-view-button =
    .label = پیشاندان
    .tooltiptext = بینین بگۆڕە
    .accesskey = V
places-view-button-mac =
    .label = پیشاندان
    .tooltiptext = بینین بگۆڕە
places-view-menu-columns =
    .label = ستوونەکان پیشان بدە
    .accesskey = C
places-view-menu-sort =
    .label = ڕێکخستن بە پێی
    .accesskey = S
places-view-sort-unsorted =
    .label = ڕێکنەخراوە
    .accesskey = U
places-view-sort-ascending =
    .label = ڕێکخستن بە شێوەی A > Z
    .accesskey = A
places-view-sort-descending =
    .label = ڕێکخستن بە شێوەی Z > A
    .accesskey = Z
places-maintenance-button =
    .label = هێنان و پاڵپشتی (باکئەپ)
    .tooltiptext = هێنانی پاڵپشتیکردنی دڵخوازەکانت (باکئەپ)
    .accesskey = I
places-maintenance-button-mac =
    .label = هێنان و پاڵپشتی (باکئەپ)
    .tooltiptext = هێنانی پاڵپشتیکردنی دڵخوازەکانت (باکئەپ)
places-cmd-backup =
    .label = پاڵپشتی...
    .accesskey = B
places-cmd-restore =
    .label = هێنانەوە
    .accesskey = R
places-cmd-restore-from-file =
    .label = پەڕگە هەڵبژێرە...
    .accesskey = C
places-import-bookmarks-from-html =
    .label = هێنانی دڵخوازەکان لە پەڕگەی HTML...
    .accesskey = I
places-export-bookmarks-to-html =
    .label = ناردنی دڵخوازەکان بۆ پەڕگەی HTML...
    .accesskey = E
places-import-other-browser =
    .label = هێنان لە وێبگەڕی ترەوە...
    .accesskey = A
places-view-sort-col-name =
    .label = ناو
places-view-sort-col-tags =
    .label = تاگەکان
places-view-sort-col-url =
    .label = شوێن
places-view-sort-col-most-recent-visit =
    .label = دوواترین سەردانکراو
places-view-sort-col-visit-count =
    .label = ژمارەی سەردانیکردن
places-view-sort-col-date-added =
    .label = زیادکرا
places-view-sort-col-last-modified =
    .label = دووا دەستکاریکراو
places-view-sortby-name =
    .label = بەپێی ناو
    .accesskey = N
places-view-sortby-url =
    .label = ڕێکخستن بەپێی شوێن
    .accesskey = L
places-view-sortby-date =
    .label = ڕێکخستن بەپێی دووا سەردانیکردن
    .accesskey = V
places-view-sortby-visit-count =
    .label = ڕێکخستن بەپێی ژمارەی سەردانیکردن
    .accesskey = C
places-view-sortby-date-added =
    .label = ڕێکخستن بە پێی زیادکردن
    .accesskey = e
places-view-sortby-last-modified =
    .label = ڕێکخستن بە پێی دووا دەستکاریکردن
    .accesskey = M
places-view-sortby-tags =
    .label = ڕێکخستن بە پێی تاگ
    .accesskey = T
places-cmd-find-key =
    .key = f
places-back-button =
    .tooltiptext = بڕۆ دواوە
places-forward-button =
    .tooltiptext = بڕۆ پێشەوە
places-details-pane-select-an-item-description = بڕگەیەک هەڵبژێرە بۆ پیشاندان و دەستکاریکردنی تایبەتمەندییەکانی
places-details-pane-no-items =
    .value = هیچ برگەیەک نیە

## Strings used as a placeholder in the Library search field. For example,
## "Search History" stands for "Search through the browser's history".

places-search-bookmarks =
    .placeholder = گەڕان لە دڵخوازەکان
places-search-history =
    .placeholder = گەڕان لە ناو مێژووی کاردا
places-search-downloads =
    .placeholder = گەڕان لەناو داگرتنەکان
