# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = आयात विजार्ड
import-from =
    { PLATFORM() ->
        [windows] विकल्पहरू, पुस्तकचिनोहरू, इतिहास, गोप्यशब्दहरू र अन्य डाटा आयात गर्नुहोस्:
       *[other] प्राथमिकताहरू ,पुस्तकचिनोहरू, इतिहास, गोप्यशब्दहरू र अन्य डाटा आयात गर्नुहोस्:
    }
import-from-bookmarks = बाट पुस्तकचिनो आयात गर्नुहोस्:
import-from-ie =
    .label = माइक्रोसफ्ट इन्टरनेट एक्सप्लोरर
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-nothing =
    .label = केहि पनि आयात नगर्नुहोस्
    .accesskey = D
import-from-safari =
    .label = सफारी
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = क्रोम
    .accesskey = C
import-from-chrome-beta =
    .label = Chrome Beta
    .accesskey = B
import-from-chrome-dev =
    .label = Chrome Dev
    .accesskey = D
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = x
import-from-360se =
    .label = 360 Secure Browser
    .accesskey = 3
no-migration-sources = पुस्तकचिनोहरू, इतिहास अथवा गोप्यशब्द डाटा नभएका कार्यक्रमहरू भेटिन सक्छन्।
import-source =
    .label = डाटा र सेटिङहरू आयात गर्नुहोस्
import-items-title =
    .label = आयत गर्नपर्ने कुराहरू
import-items-description = आयात गर्ने चिज छान्नुहोस:
import-migrating-title =
    .label = आयात हुँदैछ…
import-migrating-description = निम्नलिखित चिजहरू आयात हुँदै…
import-select-profile-title =
    .label = प्रोफाइल छान्नुहोस्
import-select-profile-description = निम्न लिखित प्रोफाइलहरू आयात गर्न उपलब्ध छन्:
import-done-title =
    .label = आयात पूरा भयो
import-done-description = निम्नलिखित चिजहरू सफलतापूर्वक आयात गरियो:
import-close-source-browser = कृपया जारी गर्नु पुर्व, चयन गरिएको ब्राउजर बन्द भएको सुनिश्चित गर्नुहोस्।
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = { $source } बाट
source-name-ie = ईन्टरनेट एक्स्पोलर
source-name-edge = Microsoft Edge
source-name-safari = सफारी
source-name-canary = Google Chrome Canary
source-name-chrome = गूगल क्रोम
source-name-chrome-beta = Google Chrome Beta
source-name-chrome-dev = Google Chrome Dev
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Secure Browser
imported-safari-reading-list = पढ्ने सुची (सफारी बाट)
imported-edge-reading-list = पढ्ने सूची (किनाराबाट)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = इन्टरनेट विकल्पहरू
    .value = इन्टरनेट विकल्पहरू
browser-data-edge-1 =
    .label = सेटिङहरू
    .value = सेटिङहरू
browser-data-safari-1 =
    .label = प्राथमिकताहरू
    .value = प्राथमिकताहरू
browser-data-chrome-1 =
    .label = प्राथमिकताहरू
    .value = प्राथमिकताहरू
browser-data-canary-1 =
    .label = प्राथमिकताहरू
    .value = प्राथमिकताहरू
browser-data-360se-1 =
    .label = प्राथमिकताहरू
    .value = प्राथमिकताहरू
browser-data-ie-2 =
    .label = कुकिज
    .value = कुकिज
browser-data-edge-2 =
    .label = कुकीहरू
    .value = कुकीहरू
browser-data-safari-2 =
    .label = कुकिज
    .value = कुकिज
browser-data-chrome-2 =
    .label = कुकिज
    .value = कुकिज
browser-data-canary-2 =
    .label = कुकिज
    .value = कुकिज
browser-data-firefox-2 =
    .label = कुकीहरू
    .value = कुकीहरू
browser-data-360se-2 =
    .label = कुकीहरू
    .value = कुकीहरू
browser-data-ie-4 =
    .label = ब्राउजिङ्ग इतिहास
    .value = ब्राउजिङ्ग इतिहास
browser-data-edge-4 =
    .label = ब्राउजिङ्ग इतिहास
    .value = ब्राउजिङ्ग इतिहास
browser-data-safari-4 =
    .label = ब्राउजिङ्ग इतिहास
    .value = ब्राउजिङ्ग इतिहास
browser-data-chrome-4 =
    .label = ब्राउजिङ्ग इतिहास
    .value = ब्राउजिङ्ग इतिहास
browser-data-canary-4 =
    .label = ब्राउजिङ्ग इतिहास
    .value = ब्राउजिङ्ग इतिहास
browser-data-firefox-history-and-bookmarks-4 =
    .label = ब्राउजिङ्ग इतिहास तथा पुस्तकचिनोहरू
    .value = ब्राउजिङ्ग इतिहास तथा पुस्तकचिनोहरू
browser-data-360se-4 =
    .label = ब्राउजिङ्ग इतिहास
    .value = ब्राउजिङ्ग इतिहास
browser-data-ie-8 =
    .label = सङ्ग्रह गरिएको फारम इतिहास
    .value = सङ्ग्रह गरिएको फारम इतिहास
browser-data-edge-8 =
    .label = सङ्ग्रह गरिएको फारम इतिहास
    .value = सङ्ग्रह गरिएको फारम इतिहास
browser-data-safari-8 =
    .label = सङ्ग्रह गरिएको फारम इतिहास
    .value = सङ्ग्रह गरिएको फारम इतिहास
browser-data-chrome-8 =
    .label = सङ्ग्रह गरिएको फारम इतिहास
    .value = सङ्ग्रह गरिएको फारम इतिहास
browser-data-canary-8 =
    .label = सङ्ग्रह गरिएको फारम इतिहास
    .value = सङ्ग्रह गरिएको फारम इतिहास
browser-data-firefox-8 =
    .label = सङ्ग्रह गरिएको फारम इतिहास
    .value = सङ्ग्रह गरिएको फारम इतिहास
browser-data-360se-8 =
    .label = सङ्ग्रह गरिएको फारम इतिहास
    .value = सङ्ग्रह गरिएको फारम इतिहास
browser-data-ie-16 =
    .label = सङ्ग्रह गरिएका गोप्यशब्दहरू
    .value = सङ्ग्रह गरिएका गोप्यशब्दहरू
browser-data-edge-16 =
    .label = सङ्ग्रह गरिएका गोप्यशब्दहरू
    .value = सङ्ग्रह गरिएका गोप्यशब्दहरू
browser-data-safari-16 =
    .label = सङ्ग्रह गरिएका गोप्यशब्दहरू
    .value = सङ्ग्रह गरिएका गोप्यशब्दहरू
browser-data-chrome-16 =
    .label = सङ्ग्रह गरिएका गोप्यशब्दहरू
    .value = सङ्ग्रह गरिएका गोप्यशब्दहरू
browser-data-canary-16 =
    .label = सङ्ग्रह गरिएका गोप्यशब्दहरू
    .value = सङ्ग्रह गरिएका गोप्यशब्दहरू
browser-data-firefox-16 =
    .label = सङ्ग्रह गरिएका गोप्यशब्दहरू
    .value = सङ्ग्रह गरिएका गोप्यशब्दहरू
browser-data-360se-16 =
    .label = सङ्ग्रह गरिएका गोप्यशब्दहरू
    .value = सङ्ग्रह गरिएका गोप्यशब्दहरू
browser-data-ie-32 =
    .label = मनपर्नेहरू
    .value = मनपर्नेहरू
browser-data-edge-32 =
    .label = मनपर्नेकुराहरू
    .value = मनपर्नेकुराहरू
browser-data-safari-32 =
    .label = पुस्तकचिनोहरू
    .value = पुस्तकचिनोहरू
browser-data-chrome-32 =
    .label = पुस्तकचिनोहरू
    .value = पुस्तकचिनोहरू
browser-data-canary-32 =
    .label = पुस्तकचिनोहरू
    .value = पुस्तकचिनोहरू
browser-data-360se-32 =
    .label = पुस्तकचिनोहरू
    .value = पुस्तकचिनोहरू
browser-data-ie-64 =
    .label = अरु डाटा
    .value = अरु डाटा
browser-data-edge-64 =
    .label = अरु तथ्यांक
    .value = अरु तथ्यांक
browser-data-safari-64 =
    .label = अरू डाटा
    .value = अरू डाटा
browser-data-chrome-64 =
    .label = अरु डाटा
    .value = अरु डाटा
browser-data-canary-64 =
    .label = अरु डाटा
    .value = अरु डाटा
browser-data-firefox-other-64 =
    .label = अरु डाटा
    .value = अरु डाटा
browser-data-360se-64 =
    .label = अरु तथ्यांक
    .value = अरु तथ्यांक
browser-data-firefox-128 =
    .label = संझ्याल तथा ट्याबहरू
    .value = संझ्याल तथा ट्याबहरू
