# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

MimeNotCss = La stilfolio %1$S ne estis ŝargita ĉar ĝia MIMEa tipo "%2$S", ne estas "text/css".
MimeNotCssWarn = La stilfolio %1$S estis ŝargita kiel CSS malgraŭ tio ke ĝia MIMEa tipo "%2$S", ne estas "text/css".
PEDeclDropped = Deklaro rifuzita.
PEDeclSkipped = Pretersaltis al la sekvanta deklaro.
PEUnknownProperty = Nekonata atributo'%1$S'.
PEPRSyntaxFieldMissing = Mankas la priskribilo de sintakso @property.
PEPRSyntaxFieldEmptyInput = La priskribilo de sintakso @property estas malplena.
PEPRSyntaxFieldExpectedPipe = La priskribilo de sintakso @property `%S` enhavas elementojn sen la signo «|» inter ili.
PEPRSyntaxFieldInvalidNameStart = La priskribilo de sintakso @property `%S` enhavas elementon kiu komenciĝas per nevalida signo.
PEPRSyntaxFieldInvalidName = La priskribilo de sintakso @property `%S` enhavas elementon kiu havas nevalidan signon.
PEPRSyntaxFieldUnclosedDataTypeName = La priskribilo de sintakso @property `%S` enhavas nefermitan nomon de tipo de datumoj.
PEPRSyntaxFieldUnexpectedEOF = La priskribilo de sintakso @property `%S` ne estas kompleta.
PEPRSyntaxFieldUnknownDataTypeName = La priskribilo de sintakso @property `%S` enhavas nekonatan nomon de tipo de datumoj.
# LOCALIZATION NOTE (PEPRInheritsFieldMissing): Do not translate "inherits" because it is a technical term.
PEPRInheritsFieldMissing = Mankas la priskribilo de @property inherits.
# LOCALIZATION NOTE (PEPRInheritsFieldInvalid): Do not translate "inherits" because it is a technical term.
PEPRInheritsFieldInvalid = La priskribilo de @property inherits ‘%S’ ne kongruas kun la specifita sintakso.
PEValueParsingError = Error in parsing value for '%1$S'.
PEUnknownAtRule = Nerekonita "at" regulo aŭ eraro dum analizo de "at" regulo '%1$S'.
PEMQUnexpectedOperator = Neatendita operaciilo en listo de aŭdvidaĵoj.
PEMQUnexpectedToken = Neatendita ĵetono ‘%1$S’ en listo de aŭdvidaĵoj.
PEAtNSUnexpected = Neatendita ĵetono ene de @namespace: ‘%1$S’.
PEKeyframeBadName = Identigilo atendita kiel nomo de @keyframes regulo.
PEBadSelectorRSIgnored = Aro de reguloj ignorita pro malĝusta elektilo.
PEBadSelectorKeyframeRuleIgnored = Keyframe rule ignored due to bad selector.
PESelectorGroupNoSelector = Elektilo atendita.
PESelectorGroupExtraCombinator = Pendanta kombinaĵo.
PEClassSelNotIdent = Identigilo atendita kiel elektilo de klaso, sed ‘%1$S’ trovita.
PETypeSelNotType = Nomo de elemento aŭ ’*’ atendita, sed ‘%1$S’ trovita.
PEUnknownNamespacePrefix = Nekonata prefikso de nomspaco ‘%1$S’.
PEAttributeNameExpected = Identigilo atendita kiel nomo de atributo sed ‘%1$S’ trovita.
PEAttributeNameOrNamespaceExpected = Nomo de atributo aŭ nomspaco atendita sed ‘%1$S’ trovita.
PEAttSelNoBar = ‘|’ atendita, sed ‘%1$S’ trovita.
PEAttSelUnexpected = Neatendita ĵetono en elektilo de atributo: ‘%1$S’.
PEAttSelBadValue = Identigilo aŭ teksto estis atendita kiel valoro en elektilo de atributo sed ‘%1$S’ estis trovita.
PEPseudoSelBadName = Estis atendita identigilo por pseŭdoklaso aŭ pseŭdoelemento, sed ‘%1$S’ estis trovita.
PEPseudoSelEndOrUserActionPC = Post pseŭdoelemento estis atendita fino de elektilo aŭ pseŭdoklaso de ago de uzanto, sed ‘%1$S’ estis trovita.
PEPseudoSelUnknown = Nekonata pseŭdoklaso aŭ pseŭdoelemento ‘%1$S’.
PEPseudoClassArgNotIdent = Estis atendita Identigilo por pseŭdoklasa parametro, sed ‘%1$S’ estis trovita.
PEColorNotColor = Koloro atendita sed ‘%1$S’ trovita.
PEParseDeclarationDeclExpected = Deklaro atendita, sed ‘%1$S’ trovita.
PEUnknownFontDesc = Unknown descriptor '%1$S' in @font-face rule.
PEMQExpectedFeatureName = Aŭdvida trajto atendita, sed ‘%1$S’ trovita.
PEMQNoMinMaxWithoutValue = Media features with min- or max- must have a value.
PEMQExpectedFeatureValue = Nevalida valoro por aŭdvida trajto.
PEExpectedNoneOrURL = ‘none’ aŭ URL atendita, sed ‘%1$S’ trovita.
PEExpectedNoneOrURLOrFilterFunction = ‘none’, URL aŭ filtrila funkcio atendita, sed ‘%1$S’ trovita.
PEDisallowedImportRule = reguloj @import ankoraŭ ne validas en konstruitaj stilfolioj.
PENeverMatchingHostSelector = la elektilo de :host en ‘%S’ ne estas sentrajta kaj ĝi neniam kongruos. Ĉu vi eble celis :host()?
PEImportantDeclError = Ne eblas deklari la atributon kiel !important en tiu ĉi kunteksto.
TooLargeDashedRadius = La radiuso de la rando estas tro granda por la stilo ‘dashed’ (la limo estas 100000px). Ĝi videblos kiel solida rando.
TooLargeDottedRadius = La radiuso de la rando estas tro granda por la stilo ‘dotted’ (la limo estas 100000px). Ĝi videblos kiel solida rando.
