# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = Tá an leathanach Gréasáin seo á atreorú go suíomh nua. An bhfuil tú ag iarraidh na sonraí foirme a chlóscríobh tú a athsheoladh go dtí an suíomh nua?
# Directory listing strings
DirTitle = Innéacs %1$S
DirGoUp = Suas go dtí comhadlann ar leibhéal níos airde
ShowHidden = Taispeáin réada folaithe
DirColName = Ainm
DirColSize = Méid
DirColMTime = Athraithe
DirFileLabel = Comhad:\u0020
UnsafeUriBlocked = Cuireadh cosc ar an acmhainn “%1$S” mar gheall ar Bhrabhsáil Shábháilte.
