# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=$ProductName$ Инсталатор
Welcome_MessageWelcome=Това е %s!
Welcome_Message0=Вие ще инсталирате %s $Version$.
Welcome_Message1=Препоръчително е да затворите всички Windows програми преди да продължите с инсталатора.
Welcome_Message2=Натиснете Cancel, за да излезете от инсталатора и да затворите работещите програми. Натиснете Next, за да продължите инсталирането.
Welcome_Message3=Натиснете Next, за да продължите инсталирането на %s $Version$.

License_Title=Лицензионно споразумение
License_SubTitle=Правила и условия за използване на този софтуер.
License_Message0=Моля, прочетете това лицензно споразумение. Използвайте плъзгащата лента, за да видите останалата част от текста.
License_Accept=&Приемам условията на споразумението
License_Decline=&НЕ приемам условията на споразумението

Type_Title=Начин на инсталиране
Type_SubTitle=Изберете начин за инсталиране.
Type_Message0=Изберете предпочитания начин за инсталиране, след което натиснете Next.

Standard_Short=&Стандартен
Standard_Long=Thunderbird ще се инсталира със стандартната окомплектовка.

Custom_Short=&По избор
Custom_Long=Можете да избирате самостоятелно компоненти за инсталиране. За напреднали потребители.

Select_Title=Избор на компоненти
Select_SubTitle=Допълнителни компоненти за $ProductName$.
Select_Message0=Изберете допълнителни компоненти за инсталиране и натиснете Next.

Path_Title=Инсталационна папка
Path_SubTitle=Къде ще бъде инсталиран $ProductName$.
Path_Message0=$ProductName$ ще се инсталира в тази папка:

Integration_Title=Създаване на препратки
Integration_SubTitle=Създаване на програмни икони
Integration_Message0=Създаване на икони за $ProductShortName$:

Integration_Desktop=На работния плот
Integration_StartMenu=В папката на меню Старт
Integration_QuickLaunch=В лента Quick Launch

SelectFolder_Title=$ProductName$ Инсталатор - Избор на програмна папка
SelectFolder_Message0=Инсталаторът ще добави икони на програмата в нейната папка. Можете да напишете ново име на папката или да изберете име от списъка на съществуващите папки. Натиснете Next за да продължите.

Advanced_Title=$ProductName$ Инсталатор – Допълнителни възможности
Advanced_Message0=Ако вашата интернет връзка изисква прокси сървър, въведете името на сървъра и порта. Ако тази информация не е необходима, оставете тези полета празни.

Install_Title=Обобщение
Install_SubTitle=Готовност за начало на инсталирането на $ProductName$.
Install_MessageInstall=Инсталаторът ще инсталира следните компоненти:
Install_MessageDownload=Инсталатора ще изтегли и инсталира следните компоненти:
Install_Message0=Натиснете Next, за да продължите.

Downloading_Title=Изтегляне
Downloading_SubTitle=Изтегляне на нужните компоненти...
Downloading_Blurb=Инсталатора изтегля нужните файлове за инсталирането на $ProductName$.
Downloading_FileName=В момента се изтегля:
Downloading_Time=Оставащо време:

Installing_Title=Инсталиране
Installing_SubTitle=Инсталиране на $ProductName$...
Installing_Blurb=Инсталиране на файловете на програмата.
Installing_Status=Подготовка на файл:
Installing_Component=В момента се инсталира:

Success_Title=Инсталацията завършена
Success_Header=Инсталацията е завършена
Success_Message0=%s $Version$ бе успешно инсталиран.
Success_Message1= Натиснете Finish, за да приключи инсталацията
Success_Launch=Стартиране на %s $Version$.

Check_Message=Изтеглянето на $ProductName$ бе успешно. $ProductNameInternal$ трябва да бъде затворен, за да се продължи с инсталацията. Натиснете ОK, за да се затвори $ProductNameInternal$ автоматично и да започне инсталацията.
Check_FullMessage=$ProductNameInternal$ трябва да бъде затворен, за да се продължи с инсталацията. Натиснете ОK, за да се затвори $ProductNameInternal$ автоматично и да започне инсталацията.
Check_Wait=Спиране на $ProductNameInternal$.  Моля, изчакайте...

Component_XPCOM=Междуплатформен COM
Component_Mail=$ProductName$
Component_Offline=Поддръжка на работа без мрежа
Component_Offline_Long=Добавяне на поддръжка на работа без мрежа за пощенския клиент $ProductName$.
Component_RSS=RSS поддръжка
Component_RSS_Long=Добавяне на RSS поддръжка за $ProductName$.
Component_QFA=Модул за обратна връзка
Component_QFA_Long=за изпращане на информация за сривове на $ProductName$
