# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Mewngofnodion wedi eu Cadw
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Copïo URL
    .accesskey = o
launch-site-url-cmd =
    .label = Mynd i URL
    .accesskey = M
copy-username-cmd =
    .label = Copïo Enw Defnyddiwr
    .accesskey = E
edit-username-cmd =
    .label = Golygu Enw Defnyddiwr
    .accesskey = o
copy-password-cmd =
    .label = Copïo'r Cyfrinair
    .accesskey = o
edit-password-cmd =
    .label = Golygu Cyfrinair
    .accesskey = G
search-filter =
    .accesskey = C
    .placeholder = Chwilio
column-heading-site =
    .label = Gwefan
column-heading-username =
    .label = Enw Defnyddiwr
column-heading-password =
    .label = Cyfrinair
column-heading-time-created =
    .label = Defnyddiwyd Gyntaf
column-heading-time-last-used =
    .label = Defnyddiwyd Diwethaf
column-heading-time-password-changed =
    .label = Newidiwyd Diwethaf
column-heading-times-used =
    .label = Gwaith Defnyddiwyd
remove =
    .label = Tynnu
    .accesskey = T
import =
    .label = Mewnforio…
    .accesskey = M
close-button =
    .label = Cau
    .accesskey = C
show-passwords =
    .label = Dangos Cyfrineiriau
    .accesskey = C
hide-passwords =
    .label = Cuddio Cyfrineiriau
    .accesskey = C
logins-description-all = Mae'r cyfrineiriau ar gyfer y gwefannau hyn ar gadw ar eich cyfrifiadur
logins-description-filtered = Mae'r cyfrineiriau'n cydweddu a'ch chwilio:
remove-all =
    .label = Tynnu Popeth
    .accesskey = P
remove-all-shown =
    .label = Tynnu Popeth sy'n Cael ei Ddangos
    .accesskey = P
remove-all-passwords-prompt = Ydych chi'n siŵr eich bod am dynnu pob cyfrinair?
remove-all-passwords-title = Tynnu pob cyfrinair
no-master-password-prompt = Ydych chi'n siŵr eich bod am ddangos eich cyfrinair?
auto-fill-logins-and-passwords =
    .label = Awtolanw mewngofnodion a chyfrineiriau
