# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host } axtarılır…
network-connection-status-connected = { $host } serverinə bağlanıldı…
network-connection-status-sending-request = { $host } serverinə istək göndərilir…
network-connection-status-transferring-data = { $host } ünvanından məlumat ötürülür…
network-connection-status-connecting = { $host } serverinə bağlanılır…
network-connection-status-read = { $host } oxundu
network-connection-status-wrote = { $host } yazılır
network-connection-status-waiting = { $host } gözlənilir…
network-connection-status-looked-up = { $host } axtarılır…
