# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = War ga baa ka naanay "%S" almuraadey wey še?
unnamedCA = Tabatiyan-tiira hini (bila-nda-maa)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Taare šennikufaloo dam, kaŋ nda war na tabatiyan-tiira banda-gaaboo woo tugandi:
# Page Info
pageInfo_NoEncryption = Ciyaroo mana tugandi
pageInfo_Privacy_None1 = Interneti nungoo %S ši hin ka moɲoo kaŋ war g'a guna tugandi.
pageInfo_Privacy_None2 = Alhabaroo kaŋ sanbandi Interneti bande bila nda boro waaniyaŋ ma hib ja dii tuguyanoo fondaa ra.\u0020
pageInfo_Privacy_None4 = Moɲoo kaŋ war goo m'a guna mana tugandi jina hal'a ma toonandi Interneti bande.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Ciyari kufalante (cebsi kufal %1$S, %2$S, %3$S)
pageInfo_BrokenEncryption = Tugandiyan hasaraw (cebsi kufal %1$S, %2$S, %3$S)
pageInfo_Privacy_Encrypted1 = Moɲoo kaŋ war g'a guna mana tugandi jina hal'a ma toonandi Interneti bande.
pageInfo_Privacy_Encrypted2 = Kufalyanoo g'a šendandi borey kaŋ ši nda fondo se, i ma dii alhabar kaŋ ga bisa ordinaterey game. Adiši, a ši hima, boro kul ma hin ka moɲoo woo caw waati kaŋ a ga bisa sankaa ra.
pageInfo_MixedContent = Ciyari jere tugante
pageInfo_MixedContent2 = Moɲoo jerey kaŋ war g'i guna mana tugandi jina ka bisandi Interneti bande.
pageInfo_WeakCipher = War ciyaroo interneti nungoo woo ga ga goy nda tuguyan yalaafante nd'a ši sutura. Boro tanayaŋ ga hin ka dii war alhabarey wala war nungoo aladaboo barmay.
# Token Manager
password_not_set = (mana hanseyandi)
