# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SaveImageTitle = وێنە پاشەکەوت بکە
SaveMediaTitle = میدیا پاشەکەوت بکە
SaveVideoTitle = ڤیدیۆ پاشەکەوت بکە
SaveAudioTitle = دەنگ پاشەکەوت بکە
SaveLinkTitle = پاشەکەوتی بکە وەک
WebPageCompleteFilter = پەڕەی وێب، هەمووی
WebPageHTMLOnlyFilter = ماڵپەڕی وێب، تەنها HTML
WebPageXHTMLOnlyFilter = ماڵپەڕی وێب، تەنها XHTML
WebPageSVGOnlyFilter = ماڵپەڕی وێب، تەنها SVG
WebPageXMLOnlyFilter = ماڵپەڕی وێب، تەنها XML
