# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

password-not-set =
    .value = (not set)
failed-pw-change = Hindi mapalitan ang Master Password.
incorrect-pw = Hindi mo naipasok ang tamang kasalukuyang Master Password. Maaaring subukan muli.
pw-change-ok = Matagumpay na napalitan ang Master Password.
pw-empty-warning = Hindi mapoprotektahan ang nakaimbak mong mga web at email password, form data, at private key.
pw-erased-ok = Binura mo na ang iyong Master Password. { pw-empty-warning }
pw-not-wanted = Babala! Nagdesisyon kang huwag gumamit ng Master Password. { pw-empty-warning }
pw-change2empty-in-fips-mode = Kasalukuyang nasa FIPS mode ka.  Nangangailangan ang FIPS ng isang may laman na Master Password.
failed-pp-change = Hindi kayang mapalitan ang Primary Password.
incorrect-pp = Hindi ka nagpasok ng tamang kasalukuyang Primary Password. Subukan uli.
pp-change-ok = Matagumpay na napalitan ang Primary Password.
pp-empty-warning = Hindi mapoprotektahan ang iyong mga nakaimbak na password at private key.
pp-erased-ok = Binura mo na ang iyong Primary Password. { pp-empty-warning }
pp-not-wanted = Babala! Nagdesisyon kang huwag gumamit ng Primary Password. { pp-empty-warning }
pp-change2empty-in-fips-mode = Kasalukuyan kang naka-FIPS mode. Kinakailangan ng FIPS ang isang hindi blangkong Primary Password.
pw-change-success-title = Tagumpay na Napalitan ang Password
pw-change-failed-title = Nabigo ang Pagpalit ng Password
pw-remove-button =
    .label = Alisin
set-password =
    .title = Palitan ang Master Password
primary-password-dialog =
    .title = Primary Password
set-password-old-password = Kasalukuyang na password:
set-password-new-password = Ilagay ang bagong password:
set-password-reenter-password = Ilagay ulit ang password:
set-password-meter = Sukatan ng kalidad ng password
set-password-meter-loading = Nag-lo-load
master-password-admin = Dinidikta ng iyong administrator na mayroon ka dapat na Master Password para makapag-save ng mga password.
master-password-description = Ang Master Password ay ginagamit para maprotektahan ang mga maseselang impormasyon tulad ng site passwords. Kung ikaw ay gagawa ng master password, ikaw ay tatanungin na mag-enter ng isa kada session kung ang { -brand-short-name } ay mag-retrieve ng sinave na impormasyon na protektado ng password.
master-password-warning = Mangyaring tiyakin na natandaan mo ang itinakdang Master Password. Kapag nakalimutan mo ang iyong Master Password, hindi mo na maaaring ma-access ang anumang impormasyon na pinoprotektahan nito.
remove-password =
    .title = Tanggalin ang Master Password
primary-password-admin = Dinidikta ng iyong administrator na mayroon ka dapat na Primary Password para makapag-save ng mga login at password.
primary-password-description = Ang Primary Password ay ginagamit para maprotektahan ang mga maseselang impormasyon tulad ng mga login at password sa device na ito. Kung gagawa ka ng Primary Password, hihingin ito sa iyo kada session kapag kukuha ang { -brand-short-name } ng impormasyong pinoprotektahan ng password na ito.
primary-password-warning = Mangyaring tiyakin na natandaan mo ang itinakdang Primary Password. Kapag nakalimutan mo ang iyong Primary Password, hindi mo na maaaring ma-access ang anumang impormasyon na pinoprotektahan nito.
remove-primary-password =
    .title = Tanggalin ang Primary Password
remove-info =
    .value = Kailangan mong i-enter ang iyong kasalukuyang password upang magpatuloy:
remove-warning1 = Ang iyong Master Password ay ginagamit upang protektahan ang sensitibong impormasyon tulad ng mga password sa mga site.
remove-warning2 = Kapag tinanggal mo ang iyong Master Password, hindi protektado ang iyong impormasyon kapag ang iyong computer ay makompromiso.
remove-primary-password-warning1 = Ang iyong Primary Password ay ginagamit upang maprotektahan ang mga sensitibong impormasyon kagaya ng mga login at password.
remove-primary-password-warning2 = Kapag tinanggal mo ang iyong Primary Password, hindi na mapoprotektahan ang iyong impormasyon kapag nakompromiso ang iyong computer.
remove-password-old-password =
    .value = Kasalukuyang na password:
