#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Danishka Navin</em:contributor> <em:contributor>Kalpa Pathum</em:contributor><em:contributor>Kosala Anuruddha</em:contributor><em:contributor>Rohana Dasanayaka</em:contributor>

#unfilter emptyLines
