# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Notice: If you're updating this list, you should also
###         update the list in mozIntl.js.

region-name-ad = Andorra
region-name-af = Afghanistan
region-name-ag = Antigua ha Barbuda
region-name-ai = Anguilla
region-name-al = Albania
region-name-am = Armenia
region-name-ao = Angola
region-name-aq = Antarktika
region-name-ar = Arc'hantina
region-name-as = Samoa Amerikan
region-name-at = Aostria
region-name-au = Aostralia
region-name-aw = Aruba
region-name-az = Azerbaidjan
region-name-ba = Bosnia ha Herzegovina
region-name-bb = Barbados
region-name-bd = Bangladesh
region-name-be = Belgia
region-name-bf = Burkina Faso
region-name-bg = Bulgaria
region-name-bh = Bahrein
region-name-bi = Burundi
region-name-bj = Benin
region-name-bm = Bermuda
region-name-bo = Bolivia
region-name-br = Brazil
region-name-bt = Bhoutan
region-name-bv = Enez Bouvet
region-name-bw = Botswana
region-name-by = Belarus
region-name-bz = Belize
region-name-ca = Kanada
region-name-cc = Inizi Kokoz (Keeling)
region-name-cf = Republik Kreizafrikan
region-name-ch = Suis
region-name-ck = Inizi Cook
region-name-cl = Chile
region-name-cm = Kameroun
region-name-cn = Sina
region-name-co = Kolombia
region-name-cr = Costa Rica
region-name-cu = Kuba
region-name-cx = Enez Christmas
region-name-cy = Kiprenez
region-name-cz = Republik Tchek
region-name-de = Alamagn
region-name-dj = Djibouti
region-name-dk = Danmark
region-name-dm = Dominica
region-name-do = Republik Dominikan
region-name-dz = Aljeria
region-name-ec = Ecuador
region-name-ee = Estonia
region-name-eg = Egipt
region-name-eh = Sahara ar C'hornôg
region-name-er = Eritrea
region-name-es = Spagn
region-name-et = Etiopia
region-name-fi = Finland
region-name-fj = Fidji
region-name-fo = Inizi Faero
region-name-fr = Frañs
region-name-ga = Gabon
region-name-gb = Rouantelezh-Unanet
region-name-gd = Grenada
region-name-ge = Jorjia
region-name-gf = Gwiana C'hall
region-name-gg = Gwernenez
region-name-gh = Ghana
region-name-gi = Jibraltar
region-name-gl = Greunland
region-name-gn = Ginea
region-name-gp = Gwadeloup
region-name-gq = Ginea ar C'heheder
region-name-gr = Gres
region-name-gt = Guatemala
region-name-gu = Guam
region-name-gw = Ginea-Bissau
region-name-gy = Guyana
region-name-hk = Hong Kong
region-name-hm = Inizi Heard ha McDonald
region-name-hn = Honduras
region-name-hr = Kroatia
region-name-ht = Haiti
region-name-hu = Hungaria
region-name-id = Indonezia
region-name-ie = Iwerzhon
region-name-il = Israel
region-name-im = Enez Vanav
region-name-in = India
region-name-io = Tiriad breizhveurat Meurvor Indez
region-name-iq = Iraq
region-name-ir = Iran
region-name-is = Island
region-name-it = Italia
region-name-je = Jerzenez
region-name-jm = Jamaika
region-name-jo = Jordania
region-name-jp = Japan
region-name-ke = Kenya
region-name-kg = Kyrgyzstan
region-name-kh = Kambodja
region-name-ki = Kiribati
region-name-km = Komorez
region-name-kn = Sant Kitts ha Nevis
region-name-kw = Koweit
region-name-ky = Inizi Cayman
region-name-kz = Kazakstan
region-name-la = Laos
region-name-lb = Liban
region-name-lc = Saint Lucia
region-name-li = Liechtenstein
region-name-lk = Sri Lanka
region-name-lr = Liberia
region-name-ls = Lesotho
region-name-lt = Lituania
region-name-lu = Luksembourg
region-name-lv = Latvia
region-name-ly = Libia
region-name-ma = Maroko
region-name-mc = Monaco
region-name-md = Moldova
region-name-me = Montenegro
region-name-mf = Saint Martin
region-name-mg = Madagaskar
region-name-mh = Inizi Marshall
region-name-ml = Mali
region-name-mn = Mongolia
region-name-mp = Inizi Mariana an Norzh
region-name-mq = Martinik
region-name-mr = Maouritania
region-name-ms = Montserrat
region-name-mt = Malta
region-name-mu = Moris
region-name-mv = Maldivez
region-name-mw = Malawi
region-name-mx = Mec'hiko
region-name-my = Malaysia
region-name-mz = Mozambik
region-name-na = Namibia
region-name-nc = Kaledonia Nevez
region-name-ne = Niger
region-name-nf = Enez Norfolk
region-name-ng = Nigeria
region-name-ni = Nicaragua
region-name-nl = Izelvroioù
region-name-no = Norvegia
region-name-np = Nepal
region-name-nr = Nauru
region-name-nu = Niue
region-name-nz = Zeland-Nevez
region-name-om = Oman
region-name-pa = Panamá
region-name-pe = Perou
region-name-pf = Polinezia C'hall
region-name-pg = Papoua Ginea Nevez
region-name-ph = Filipinez
region-name-pk = Pakistan
region-name-pl = Polonia
region-name-pm = Sant-Pêr-ha-Mikelon
region-name-pr = Puerto Rico
region-name-pt = Portugal
region-name-pw = Palau
region-name-py = Paraguay
region-name-qa = Qatar
region-name-re = Reünion
region-name-ro = Roumania
region-name-rs = Serbia
region-name-rw = Rwanda
region-name-sa = Arabia Saoudat
region-name-sb = Inizi Salomon
region-name-sc = Sechelez
region-name-sd = Soudan
region-name-se = Sveden
region-name-sg = Singapour
region-name-si = Slovenia
region-name-sk = Slovakia
region-name-sl = Sierra Leone
region-name-sm = San Marino
region-name-sn = Senegal
region-name-so = Somalia
region-name-sr = Surinam
region-name-st = São Tomé ha Príncipe
region-name-sv = El Salvador
region-name-sy = Siria
region-name-sz = Swaziland
region-name-tc = Inizi Turks ha Caicos
region-name-td = Tchad
region-name-tg = Togo
region-name-th = Thailand
region-name-tj = Tadjikistan
region-name-tk = Tokelau
region-name-tl = Timor-Leste
region-name-tm = Turkmenistan
region-name-tn = Tunizia
region-name-to = Tonga
region-name-tr = Turkia
region-name-tt = Trinidad ha Tobago
region-name-tv = Tuvalu
region-name-tw = Taiwan
region-name-tz = Tanzania
region-name-ua = Ukraina
region-name-ug = Ouganda
region-name-us = Stadoù-Unanet
region-name-uy = Uruguay
region-name-uz = Ouzbekistan
region-name-va = Vatikan
region-name-vc = Sant Visant hag ar Grenadinez
region-name-ve = Venezuela
region-name-vn = Viêt Nam
region-name-vu = Vanuatu
region-name-wf = Wallis ha Futuna
region-name-ws = Samoa
region-name-ye = Yemen
region-name-yt = Mayotte
region-name-za = Suafrika
region-name-zm = Zambia
region-name-zw = Zimbabwe
