# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Вақти интизорӣ ба анҷом расид
openFile = Кушодани файл
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Ҷустуҷӯи «%2$S» дар %1$S
contextMenuSearch.accesskey = S
contextMenuPrivateSearch = Ҷустуҷӯ дар равзанаи хусусӣ
contextMenuPrivateSearch.accesskey = h
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Ҷустуҷӯ тавассути %S дар равзанаи хусусӣ
contextMenuPrivateSearchOtherEngine.accesskey = h
bookmarkAllTabsDefault = [Номи ҷузвдон]
unsignedAddonsDisabled.message = Як ё якчанд ҷузъи иловагии насбшуда тасдиқ карда намешаванд, бинобар ин, онҳр ғайрифаъол карда шудаанд.
unsignedAddonsDisabled.learnMore.label = Маълумоти бештар
unsignedAddonsDisabled.learnMore.accesskey = М
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Дастрасии охирин %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = Пайвандҳои %S://
crashedpluginsMessage.title = Плагини %S вайрон шудааст.
crashedpluginsMessage.reloadButton.label = Аз нав бор кардани саҳифа
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = Пешниҳоди гузориш дар бораи вайронӣ
crashedpluginsMessage.submitButton.accesskey = S
crashedpluginsMessage.learnMore = Маълумоти бештар…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Шумо ба %S рафтан мехостед?
keywordURIFixup.goTo = Бале, маро ба %S баред
keywordURIFixup.goTo.accesskey = Y
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = То %S навсозӣ карда шавад
update.downloadAndInstallButton.accesskey = U
menuOpenAllInTabs.label = Ҳамаро дар варақаҳо кушоед
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Аз нав бор кардани ин саҳифа
tabHistory.goBack = Бозгашт ба ин саҳифа
tabHistory.goForward = Гузариш ба ин саҳифа
# URL Bar
pasteAndGo.label = Нусха бардоштан ва гузаштан
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Аз нав бор кардани саҳифаи ҷорӣ (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Қатъ кардани боркунии ин саҳифа (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Бозсозии андозаи миқёс (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Фаъолсозии намоиши хониш (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, Бозсозии андозаи миқёс
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Намоиш додани хатбаракҳои худ (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Намоиш додани раванди боргириҳои ҷорӣ (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Кушодани равзанаи нав (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Кушодани варақаи нав (%S)
newTabContainer.tooltip = Кушодани варақаи нав (%S)\nБарои кушодани варақаи нави дарбаргиранда ин тугмаро зер карда, доред
newTabAlwaysContainer.tooltip = Интихоб кардани дарбаргиранда барои кушодани варақаи нав
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Ба %S барои истифодаи маълумоти тасвири саҳнаи HTML5-и шумо иҷозат медиҳед?
canvas.siteprompt2.warning = Ин метавонад барои ба таври мушаххас муайян кардани компютери шумо истифода шавад.
canvas.block = Манъ кардан
canvas.block.accesskey = B
canvas.allow2 = Иҷозат додан
canvas.allow2.accesskey = A
canvas.remember2 = Ин қарорро дар хотир доред
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Тасдиқ аз ҷониби: «%S»
identity.identified.verified_by_you = Шумо барои ин сомона истиснои амниятро илова кардед.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Гувоҳнома дода шуд ба: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Бехатар нест
identity.notSecure.tooltip = Пайвастшавӣ бехатар нест
identity.extension.label = Васеъшавӣ (%S)
identity.extension.tooltip = Бо васеъшавӣ бор карда шудааст: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Хурд кардан (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Бозсозии андозаи миқёс (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Калон кардан (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Буридан (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Нусха бардоштан (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Гузоштан (%S)
geolocation.allow = Иҷозат додан
geolocation.allow.accesskey = A
geolocation.block = Манъ кардан
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Ин амал танзимоти низомии ҷойгиршавиро мекушояд. Лутфан, ба «%S» иҷозат диҳед, то тавонад ҷойгиршавиро муайян кунад.
geolocation.shareWithSite4 = Ба %S барои пайдо кардани дастрасӣ ба ҷойгиршавии шумо иҷозат медиҳед?
geolocation.shareWithFile4 = Ба ин файли маҳаллӣ барои пайдо кардани дастрасӣ ба ҷойгиршавии шумо иҷозат медиҳед?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Ба %1$S иҷозат медиҳед, ки ба ҷойгиршавии шумо ба %2$S дастрасиро таъмин намояд?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Ба «%S» иҷозат диҳед, ки тавонад дар танзимоти низом муайянкунии ҷойгиршавиро татбиқ кунад.
geolocation.systemSettingsTitle = Мунтазири иҷозат барои муайянкунии ҷойгиршавӣ
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Барои татбиқ кардани ин иҷозат ба «%S», низом аз шумо иҷозат мепурсад.
geolocation.remember = Ин қарорро дар хотир доред
# Virtual Reality Device UI
xr.allow2 = Иҷозат додан
xr.allow2.accesskey = A
xr.block = Манъ кардан
xr.block.accesskey = B
xr.shareWithSite4 = Ба %S барои пайдо кардани дастрасӣ ба дастгоҳҳои воқеияти маҷозӣ иҷозат медиҳед? Ин амал метавонад маълумоти шахсии шуморо ошкор кунад.
xr.shareWithFile4 = Ба ин файли маҳаллӣ барои пайдо кардани дастрасӣ ба дастгоҳҳои воқеияти маҷозӣ иҷозат медиҳед? Ин амал метавонад маълумоти шахсии шуморо ошкор кунад.
xr.remember = Ин қарорро дар хотир доред
# Persistent storage UI
persistentStorage.allow = Иҷозат додан
persistentStorage.allow.accesskey = A
persistentStorage.block.label = Манъ кардан
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Ба %S иҷозат медиҳед, ки маълумотро дар захирагоҳи доимӣ нигоҳ дорад?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Иҷозат додан
webNotifications.allow2.accesskey = A
webNotifications.notNow = Ҳоло не
webNotifications.notNow.accesskey = n
webNotifications.never = Ҳеҷ гоҳ иҷозат дода нашавад
webNotifications.never.accesskey = v
webNotifications.alwaysBlock = Ҳамеша манъ карда шавад
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = Манъ кардан
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Ба %S барои фиристодани огоҳномаҳо иҷозат медиҳед?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = «%S» мехоҳад, ки дар ин дастгоҳ ба барномаҳо ва хизматҳои дигар дастрасӣ пайдо кунад.
localhost.remember2 = Интихоби ман барои ин сомона дар хотир дошта шавад
localhost.allowlabel = Иҷозат додан
localhost.blocklabel = Манъ кардан
localhost.allow.accesskey = И
localhost.block.accesskey = М
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = «%S» мехоҳад, ки дар дастгоҳҳои пайвастшуда ба шабакаи маҳаллии шумо ба барномаҳо ва хизматҳо дастрасӣ пайдо кунад.
localNetwork.remember2 = Интихоби ман барои ин сомона дар хотир дошта шавад
localNetwork.allowLabel = Иҷозат додан
localNetwork.allow.accesskey = И
localNetwork.blockLabel = Манъ кардан
localNetwork.block.accesskey = М
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Маро аз ин ҷо дуртар баред!
safebrowsing.getMeOutOfHereButton.accessKey = G
safebrowsing.deceptiveSite = Сомонаи қалбакӣ!
safebrowsing.notADeceptiveSiteButton.label = Сомонаи ҷорӣ қалбакӣ нест…
safebrowsing.notADeceptiveSiteButton.accessKey = D
safebrowsing.reportedAttackSite = Дар бораи сомонаи ҳамлакунанда гузориш диҳед!
safebrowsing.notAnAttackButton.label = Ин сомонаи ҳамлакунанда нест…
safebrowsing.notAnAttackButton.accessKey = A
safebrowsing.reportedUnwantedSite = Гузориш дода шудааст, ки ин сомона дорои нармафзори номатлуб мебошад!
safebrowsing.reportedHarmfulSite = Гузориш дода шудааст, ки ин сомона дорои нармафзори зараровар мебошад!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Ҷустуҷӯ аз рӯи %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = %S-ро дар реҷаи ислоҳи нуқсонҳо аз нав оғоз мекунед?
troubleshootModeRestartPromptMessage = Васеъшавиҳо, мавзуъҳо ва танзимоти фармоишии шумо муваққатан ғайрифаъол карда мешаванд.
troubleshootModeRestartButton = Аз нав оғоз кардан
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Ин саҳифа кори %1$S-ро суст мекунад. Барои суръат бахшидани кори барузери шумо, ин саҳифаро манъ кунед.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Саҳифаи сомона кори %1$S-ро суст мекунад. Барои суръат бахшидани кори барузери шумо, саҳифаи сомонаро манъ кунед.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = «%1$S» кори «%2$S»-ро суст мекунад. Барои суръат бахшидани кори барузери шумо, саҳифаи сомонаро манъ кунед.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = «%1$S» кори «%2$S»-ро суст мекунад. Барои суръат бахшидани кори барузери шумо, ин васеъшавиро манъ кунед.
processHang.add-on.learn-more.text = Маълумоти бештар
processHang.button_stop2.label = Қатъ кардан
processHang.button_stop2.accessKey = S
processHang.button_debug.label = Ислоҳ кардани хатоҳои скрипт
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Намоиш додани равзана дар экрани пурра (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Ҷойгир кардани навори ҷонибӣ аз тарафи чап
sidebar.moveToRight = Ҷойгир кардани навори ҷонибӣ аз тарафи рост
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Барои пахш кардани баъзе аудио ё видео дар ин саҳифа, шумо бояд DRM-ро фаъол кунед.
emeNotifications.drmContentDisabled.button.label = Фаъол кардани DRM
emeNotifications.drmContentDisabled.button.accesskey = E
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = Барои пахш кардани аудио ва видео дар ин саҳифа, %S унсурҳои лозимиро насб карда истодааст. Лутфан, баъдтар аз нав кӯшиш кунед.
emeNotifications.unknownDRMSoftware = Номаълум
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Танзимоти %S
decoder.noCodecs.button = Бифаҳмед, ки чӣ тавр
decoder.noCodecs.accesskey = L
decoder.noCodecsLinux.message = Барои пахш кардани видео, ба шумо лозим мешавад, ки кодекҳои видеоии лозимиро насб намоед.
decoder.noHWAcceleration.message = Барои беҳтар кардани сифати видео, ба шумо лозим мешавад, ки бастаи «Media Feature Pack»-ро аз Microsoft насб намоед.
decoder.noPulseAudio.message = Барои пахш кардани аудио, ба шумо лозим мешавад, ки нармафзори лозимии «PulseAudio»-ро насб намоед.
decoder.unsupportedLibavcodec.message = Рамзкушои «libavcodec» метавонад осебпазир бошад ё дастгирӣ намешавад, ва барои пахш кардани видео он бояд навсозӣ карда шавад.
decoder.decodeError.message = Ҳангоми рамзкушоӣ кардани манбаи медиа хато ба миён омад.
decoder.decodeError.button = Гузориш дар бораи мушкилии сомона
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = Ҳангоми рамзкушоӣ кардани манбаи медиа хато ислоҳшаванда ба миён омад.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Пеш аз пайдо кардани дастрасӣ ба Интернет, шумо бояд ба ин шабака ворид шавед.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Кушодани саҳифа барои ворид шудан ба шабака
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Иҷозатҳо барои %S
permissions.remove.tooltip = Ин иҷозатро тоза кунед ва аз нав дархост намоед
permissions.fullscreen.promptCanceled = Раванди интизори дархостҳо барои иҷозат бекор карда шуд: дархостҳо барои иҷозат бояд пеш аз гузариш ба реҷаи экрани пурраи DOM ирсол карда нашаванд.
permissions.fullscreen.fullScreenCanceled = Баромад аз реҷаи экрани пурраи DOM: дархостҳо барои иҷозат бояд ҳангоми истифодаи реҷаи экрани пурраи DOM ирсол карда нашаванд.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-бит
aboutDialog.architecture.thirtyTwoBit = 32-бит
midi.allow.label = Иҷозат додан
midi.allow.accesskey = И
midi.block.label = Манъ кардан
midi.block.accesskey = М
midi.remember = Ин қарорро дар хотир доред
midi.shareWithFile = Ба ин файли маҳаллӣ барои пайдо кардани дастрасӣ ба дастгоҳҳои MIDI-и шумо иҷозат медиҳед?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Ба %S барои пайдо кардани дастрасӣ ба дастгоҳҳои MIDI-и шумо иҷозат медиҳед?
midi.shareSysexWithFile = Ба ин файли маҳаллӣ барои пайдо кардани дастрасӣ ба дастгоҳҳои MIDI-и шумо ва ирсол/қабул кардани паёмҳои SysEx иҷозат медиҳед?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Ба %S барои пайдо кардани дастрасӣ ба дастгоҳҳои MIDI-и шумо ва ирсол/қабул кардани паёмҳои SysEx иҷозат медиҳед?
serial.allow.label = Иҷозат додан
serial.allow.accesskey = И
serial.block.label = Манъ кардан
serial.block.accesskey = М
serial.shareWithFile = Ба ин файли маҳаллӣ барои пайдо кардани дастрасӣ ба портҳои силсилавии шумо иҷозат медиҳед?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Ба %S барои пайдо кардани дастрасӣ ба портҳои силсилавии шумо иҷозат медиҳед?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Ба қафо
storageAccess1.Allow.label = Иҷозат додан
storageAccess1.Allow.accesskey = И
storageAccess1.DontAllow.label = Манъ кардан
storageAccess1.DontAllow.accesskey = М
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Ба %1$S иҷозат медиҳед, ки кукиҳои худро дар %2$S истифода барад?
storageAccess1.hintText = Шумо метавонед ба он дастрасӣ маҳдуд кунед, агар номаълум бошад, ки чаро ба %1$S ин маълумот лозим аст.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Ҷустуҷӯи «%S» дар Интернет
