# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Temps de connexion despassat
openFile = Dobrir lo fichièr
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Recercar « %2$S » sus %1$S
contextMenuSearch.accesskey = R
contextMenuPrivateSearch = Recercar dins una fenèstra privada
contextMenuPrivateSearch.accesskey = r
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Cercar amb %S dins una fenèstra de navegacion privada
contextMenuPrivateSearchOtherEngine.accesskey = r
bookmarkAllTabsDefault = [Nom de repertòri]
unsignedAddonsDisabled.message = Un o mai moduls installats an pas pogut èsser verificats e foguèron doncas desactivats.
unsignedAddonsDisabled.learnMore.label = Ne saber mai
unsignedAddonsDisabled.learnMore.accesskey = s
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Darrièr accès %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = ligams %S://
crashedpluginsMessage.title = Lo plugin %S a plantat.
crashedpluginsMessage.reloadButton.label = Actualizar la pagina
crashedpluginsMessage.reloadButton.accesskey = A
crashedpluginsMessage.submitButton.label = Mandar un rapòrt de fracàs
crashedpluginsMessage.submitButton.accesskey = M
crashedpluginsMessage.learnMore = Ne saber mai…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Voliatz anar a %S ?
keywordURIFixup.goTo = Òc, dobrir %S
keywordURIFixup.goTo.accesskey = O
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Metre a jorn %S
update.downloadAndInstallButton.accesskey = M
menuOpenAllInTabs.label = Tot dobrir dins d'onglets
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Recargar aquesta pagina
tabHistory.goBack = Tornar a aquesta pagina
tabHistory.goForward = Tornar a aquesta pagina
# URL Bar
pasteAndGo.label = Pegar e anar
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Actualizar la pagina correnta (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Arrestar lo cargament d'aquesta pagina (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Reïnicializar lo nivèl de zoom (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Activar/Desactivar lo mòde lectura (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Afichar vòstres marcapaginas (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Afichar la progression dels telecargaments en cors (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Dobrir una fenèstra novèla (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Dobrir un onglet novèl (%S)
newTabContainer.tooltip = Dobrir un onglet novèl (%S)\nMantenètz quichat per dobrir un onglet contextual novèl
newTabAlwaysContainer.tooltip = Seleccionar un contèxte per dobrir un onglet novèl
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Autorizar %S a utilizar vòstras donadas d’imatge de canabàs HTML5 ?
canvas.siteprompt2.warning = Pòt servir a identificar d’un biais unic vòstre ordenador.
canvas.block = Blocar
canvas.block.accesskey = B
canvas.allow2 = Autorizar
canvas.allow2.accesskey = A
canvas.remember2 = Memorizar aquesta decision
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Verificat per : %S
identity.identified.verified_by_you = Avètz apondut una excepcion de seguretat per aqueste site
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Certificat emés per : %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Pas segur
identity.notSecure.tooltip = La connexion es pas segura
identity.extension.label = Extension (%S)
identity.extension.tooltip = Cargat per l'extension : %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Zoom arrièr (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Reïnicializar lo nivèl de zoom (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Zoom avant (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Talhar (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Copiar (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Pegar (%S)
geolocation.allow = Autorizar
geolocation.allow.accesskey = A
geolocation.block = Blocar
geolocation.block.accesskey = B
geolocation.shareWithSite4 = Volètz que %S pòsca accedir a vòstra adreça ?
geolocation.shareWithFile4 = Volètz autorizar aqueste fichièr local a accedir a vòstra adreça ?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Volètz que %1$S dòne accès a %2$S a la localizacion ?
geolocation.remember = Memorizar aquesta decision
# Virtual Reality Device UI
xr.allow2 = Autorizar
xr.allow2.accesskey = A
xr.block = Blocar
xr.block.accesskey = B
xr.shareWithSite4 = Autorizar %S a accedir als periferics de realitat virtuala ? Aquò poiriá expausar d’informacions confidencialas.
xr.shareWithFile4 = Autorizar aqueste fichièr local a accedir als periferics de realitat virtuala ? Aquò poiriá expausar d’informacions confidencialas.
xr.remember = Memorizar aquesta decision
# Persistent storage UI
persistentStorage.allow = Autorizar
persistentStorage.allow.accesskey = A
persistentStorage.block.label = Blocar
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Autorizar %S a servar las donadas dins l’emmagazinatge persistent ?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Autorizar
webNotifications.allow2.accesskey = A
webNotifications.notNow = Pas ara
webNotifications.notNow.accesskey = p
webNotifications.never = Autorizar pas jamai
webNotifications.never.accesskey = j
webNotifications.alwaysBlock = Totjorn blocar
webNotifications.alwaysBlock.accesskey = b
webNotifications.block = Blocar
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Autorizar %S a enviar de notificacions ?
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Sortissètz-me d'aicí !
safebrowsing.getMeOutOfHereButton.accessKey = S
safebrowsing.deceptiveSite = Site enganaire !
safebrowsing.notADeceptiveSiteButton.label = Aqueste site es pas enganaire…
safebrowsing.notADeceptiveSiteButton.accessKey = D
safebrowsing.reportedAttackSite = Aqueste site es estat senhalat coma una malvolent !
safebrowsing.notAnAttackButton.label = Aqueste site es pas malvolent…
safebrowsing.notAnAttackButton.accessKey = A
safebrowsing.reportedUnwantedSite = Site que compòrta de logicials pas desirats !
safebrowsing.reportedHarmfulSite = Site denonciat coma malfasent !
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Recèrca %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Reaviar %S en mòde resolucion de problèmas ?
troubleshootModeRestartPromptMessage = Vòstras extensions, tèmas e paramètres personalizats seràn temporàriament desactivats.
troubleshootModeRestartButton = Reaviar
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Aquesta pagina alentís %1$S. Per accelerar vòstre navegador, arrestatz aquesta pagina.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Una pagina web alentís %1$S. Per accelerar vòstre navegador, arrestatz aquela pagina.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = « %1$S » alentís %2$S. Per accelerar vòstre navegador, arrestatz aquesta pagina.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = « %1$S » alentís %2$S. Per accelerar vòstre navegador, arrestatz aquesta extension.
processHang.add-on.learn-more.text = Ne saber mai
processHang.button_stop2.label = Arrestar
processHang.button_stop2.accessKey = A
processHang.button_debug.label = Desbugar l'escript
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Afichar la fenèstra en ecran complèt (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Desplaçar la barra laterala cap a esquèrra
sidebar.moveToRight = Desplaçar la barra laterala cap a drecha
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Cal activar lo DRM per legir d'àudio e de vidèo sus aquela pagina.
emeNotifications.drmContentDisabled.button.label = Activar lo DRM
emeNotifications.drmContentDisabled.button.accesskey = A
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S installa de mesas a jorn necessàrias a la lectura d'elements àudio o vidèo sus aquesta pagina. Ensajatz tornamai mai tard.
emeNotifications.unknownDRMSoftware = Desconegut
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Personalizar %S
decoder.noCodecs.button = Ne saber mai
decoder.noCodecs.accesskey = S
decoder.noCodecsLinux.message = Per legir la vidèo, benlèu vos cal installar los codècs de vidèos necessaris.
decoder.noHWAcceleration.message = Per melhorar la qualitat de la vidèo, benlèu vos cal installar Microsoft’s Media Feature Pack.
decoder.noPulseAudio.message = Per legir l'àudio, benlèu vos cal installar lo logicial PulseAudio necessari.
decoder.unsupportedLibavcodec.message = Lo libavcodec es benlèu vulnerable o non compatible, e deuriatz l'actualizar per legir la vidèo.
decoder.decodeError.message = Una error s'es producha pendent lo descodatge d'una font mèdia.
decoder.decodeError.button = Reportar lo problèma del site
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = Una error corregibla s'es producha pendent lo descodatge d'una font mèdia.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Cal se connectar al ret per poder accedir a Internet.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Dobrir la pagina de connexion al malhum
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Permissions per %S
permissions.remove.tooltip = Escafar aquesta permission e tornar demandar
permissions.fullscreen.promptCanceled = Demanda d’autorizacion en espèra anullada : las demandas d’autorizacion devon pas èsser emisas abans de dintrar en mòde DOM plen ecran.
permissions.fullscreen.fullScreenCanceled = Sortida del mòde DOM plen ecran : las demandas d’autorizacion devon pas èsser emesas en plen ecran.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bit
aboutDialog.architecture.thirtyTwoBit = 32-bit
midi.allow.label = Autorizar
midi.allow.accesskey = A
midi.block.label = Blocar
midi.block.accesskey = B
midi.remember = Memorizar aquesta decision
midi.shareWithFile = Volètz autorizar aqueste fichièr local a accedir a vòstre periferic MIDI ?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Volètz autorizar %S a accedir al periferic MIDI ?
midi.shareSysexWithFile = Volètz autorizar aqueste fichièr local a accedir als periferics MIDI e mandar/recebre de messatges SysEx ?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Volètz autorizar %S a accedir als periferics MIDI e a mandar/recebre de messatges SysEx ?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Tornar
storageAccess1.Allow.label = Autorizar
storageAccess1.Allow.accesskey = A
storageAccess1.DontAllow.label = Blocar
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Permetre a %1$S d’utilizar sos cookies sus %2$S ?
storageAccess1.hintText = Volriatz benlèu blocar l’accès se sabètz pas exactament perque %1$S a mestièr de vòstras donadas.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Cercar sul web « %S »
