# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = ಈ ಜಾಲತಾಣವು ಒಂದು ಹೊಸ ಸ್ಥಳಕ್ಕೆ ಮರಳಿ ನಿರ್ದೇಶನಗೊಳ್ಳುತ್ತಿದೆ. ನೀವು ನಮೂದಿಸಿದ ಫಾರ್ಮ್‍ ಮಾಹಿತಿಯನ್ನು ಮರಳಿ ಕಳುಹಿಸಲು ಬಯಸುತ್ತೀರೆ?
# Directory listing strings
DirTitle = %1$S ನ ಪರಿವಿಡಿ
DirGoUp = ಮೇಲ್ಮಟ್ಟದ ಕಡತ ಕೋಶದ ವರೆಗೆ
ShowHidden = ಅಡಗಿಸಲಾದ ವಸ್ತುಗಳನ್ನು ತೋರಿಸು
DirColName = ಹೆಸರು
DirColSize = ಗಾತ್ರ
DirColMTime = ಕಡೆಯ ಬಾರಿ ಮಾರ್ಪಡಿಸಲಾಗಿದ್ದು
DirFileLabel = ಕಡತ:
