# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Aqlarıñız Aqqında
rights-intro = { -brand-full-name }, bütün dünya miqyasındaki biñlerce kişilik bir toplulıq tarafından inşa etilgen serbest ve açıq menbalı yazılımdır. Bilmeñiz lâzim olğan bir qaç şey bardır:
rights-intro-point-1 = { -brand-short-name } sizge <a data-l10n-name="mozilla-public-license-link">Mozilla Aleniy Litsenziyası</a> şartları altında faydalandırıla. Bu demek ki, { -brand-short-name } uyğulamasını qullana, kopiyalay ve başqalarğa dağıtabilirsiñiz. Em de { -brand-short-name } menba kodunı ihtiyaclarıñıznı qarşılamaq üzre deñiştirebilirsiñiz. Mozilla Aleniy Litsenziyası sizge başqalaştırılğan sürümleriñizni dağıtmağa da aq bere.
rights-intro-point-2 = Mozilla Vaqfı ya da er angi tarafnıñ ticariy markalarına, Firefox logosı yaki ismi de sıñırlamasız olaraq dahil olmak üzre, er angi ticariy marka aqları ya da litsenziyaları bahşış etilgen degilsiñiz. Ticariy markalarğa dair ek malümat <a data-l10n-name="mozilla-trademarks-link">mında</a> tapılabilir.
rights-intro-point-3 = { -brand-short-name } içindeki bazı hususiyetler, Çöküş Maruzacısı kibi, sizge { -vendor-short-name } içün keribesleme temin etüv ihtiyarını bereler. Keribesleme teslim etmege saylayaraq, { -vendor-short-name } içün mahsullarını yahşılaştırmaq, ağ saytlarında neşretmek ve dağıtmaq üzre bu keribeslemeni qullanmağa ruhset beresiñiz.
rights-intro-point-4 = { -brand-short-name } vastasınen { -vendor-short-name } içün teslim etilgen şahsiy malümat ve keribeslemeñizni nasıl qullanğanımız <a data-l10n-name="mozilla-privacy-policy-link">{ -brand-short-name } Hususiyet Siyaseti</a>nde tasvir etilgendir.
rights-intro-point-4-unbranded = Bu mahsul içün uyğulanabilgen er türlü hususiyat siyasetleriniñ mında listelenmesi lâzim.
rights-intro-point-5 = Bazı { -brand-short-name } hususiyetleri ağ-esaslı malümat hızmetlerini qullanır, lâkin, olarnıñ 100% itinalı ve hatasız olğanlarına kefalet beralmaymız. Hızmetlerniñ nasıl ğayrıqabilleştirilebilgeni aqqındaki malümat dahil, daa çoq tafsilât <a data-l10n-name="mozilla-service-terms-link">hızmet şartları</a>nda tapılabilir.
rights-intro-point-5-unbranded = Bu mahsul ağ hızmetlerini ihtiva ete ise, hızmet(ler) içün uyğulanabilgen er türlü hızmet şartlarınıñ <a data-l10n-name="mozilla-website-services-link">Ağ-Saytı Hızmetleri</a> bölügine ilişimlenmesi lâzim.
rights-intro-point-6 = Muayyen video muhtevası türlerini oynatabilmek içün, { -brand-short-name } üçünci taraflardan muayyen muhteva deşifreleme modüllerini endirir.
rights-webservices-header = { -brand-full-name } Ağ-Esaslı Malümat Hızmetleri
rights-webservices = { -brand-full-name }, { -brand-short-name } uyğulamasınıñ bu ekişerli sürümi ile sizge temin etilgen bazı hususiyetlerni temin etmek üzre aşağıda tasvir etilgeni şartlar altında ağ-esaslı malümat hızmetlerini ("Hızmetler") qullanır. Bu Hızmetlerniñ bir yaki daa çoqusını qullanmağa istemeseñiz yaki aşağıdaki şartlar namaqbul ise, hususiyet yaki Hızmet(ler)ni ğayrıqabilleştirebilirsiñiz. Belli bir hususiyet yaki Hızmetniñ nasıl ğayrıqabilleştirilgeni aqqındaki talimat <a data-l10n-name="mozilla-disable-service-link">mında</a>tapılabilir. Diger hususiyetler ve Hızmetler uyğulama tercihlerinde ğayrıqabilleştirilebilir.
rights-safebrowsing = <strong>EminKezinüv: </strong>Emin Kezinüv hususiyetiniñ ğayrıqabilleştirilmesi tevsiye etilmey çünki siziñ emin olmağan saytlarğa baruvıñız ile neticelenebilir. Bu hususiyetni bütünley ğayrıqabilleştirmege isteseñiz, bu adımlarnı taqip etiñiz:
rights-safebrowsing-term-1 = Uyğulama tercihlerini açıñız
rights-safebrowsing-term-2 = Emniyet saylamını saylañız
rights-safebrowsing-term-3 = "{ enableSafeBrowsing-label }"mek içün seçenekni çavkesizle
enableSafeBrowsing-label = Tehlükeli ve yañıltıcı muhtevanı blokla
rights-safebrowsing-term-4 = Emin Kezinüv şimdi qabil degildir
rights-locationawarebrowsing = <strong>Qonumdan Haberdar Kezinüv: </strong>er zaman şahsen ihtiyar etilir.  Ruhsetiñiz olmadan iç bir qonum malümatı asla yiberilmez.  Bu hususiyetni bütünley ğayrıqabilleştirmege isteseñiz, bu adımlarnı taqip etiñiz:
rights-locationawarebrowsing-term-1 = URL (adres) çubuğında, tuşlañız <code>about:config</code>
rights-locationawarebrowsing-term-2 = geo.enabled tuşlañız
rights-locationawarebrowsing-term-3 = geo.enabled tercihine çift çertiñiz
rights-locationawarebrowsing-term-4 = Qonumdan-Haberdar Kezinüv şimdi qabil degildir
rights-webservices-unbranded = Mahsulnıñ ihtiva etkeni ağ-saytı hızmetleriniñ bir üstbaqışınıñ, olarnıñ nasıl ğayrıqabilleştirilgeni aqqındaki talimatlar dahil (uyğulanabilir ise), mında dahil etilmesi lâzim.
rights-webservices-term-unbranded = Bu mahsul içün uyğulanabilgen er angi hızmet şartlarınıñ mında listelenmesi lâzim.
rights-webservices-term-1 = { -vendor-short-name } ve onıñ isse qoşucıları, lisansçıları ve ortaqları eñ itinalı ve tarihdaş Hızmerlerni temin etmek üzre çalışırlar. Lâkin, biz bu malümatnıñ şümulli ve hatasız olğanına kefalet beralmaymız.  Meselâ, Emin Kezinüv Hızmeti bazı muhataralı saytlarnı kimliklemeybilir ve bazı emin saytlarnı hataen teşhis etebilir ve Qonumdan Haberdar Hızmet içün hizmet teminatçılarımız tarafından qaytarılğan qonumlarnıñ episi faqat tahminlerdir ve ne bizce, ne de bizim hızmet teminatçılarımızca temin etilgen qonumlarnıñ doğrulığına kefalet berile.
rights-webservices-term-2 = { -vendor-short-name }, Hızmetlerni öz tefriğına köre devamsızlandıra yaki deñiştire bilir.
rights-webservices-term-3 = Bu Hızmetlerni refaqat etici { -brand-short-name } sürümi ile qullanuvıñızdan hoşlanırmız ve { -vendor-short-name } sizge bunıñ içün onıñ aqlarını bahşış ete.  { -vendor-short-name } ve onıñ lisansçıları Hızmetlerdeki bütün başqa aqlarnı saqlı tutar.  Bu şartlar, { -brand-short-name } içün uyğulanabilgen açıq menba lisansları altındaki ve müteqabil { -brand-short-name } menba kodu sürümlerine bahşış etilgen er angi aqlarnı sıñırlamaq niyetinden degildir.
rights-webservices-term-4 = <strong>Mezkür Hızmetler "olğanı-kibi" temin etilir.  { -vendor-short-name }, onıñ isse qoşqanları, lisansçıları ve dağıtıcıları, Hızmetlerniñ alıp-berilebilir ve siziñ belli muradıñızğa kelişikli olğanlarına kefaletler sıñırlamasız olaraq dahil olmaq üzre, ifade etilgen yaki zımniy olsun, episi kefaletlerni inkâr ete.</strong>
rights-webservices-term-5 = <strong>Qanun ükmünce olğanları harıc, { -vendor-short-name }, onıñ isse qoşqanları, lisansçıları ve dağıtıcıları, { -brand-short-name } yaki Hızmetlerniñ qullanımından ortağa çıqqan yaki qullanımına er angi surette alâqalı olğan vastalı, mahsus, tesadufiy, aqibetli, cezalandırıcı yaki ibretli ziyanlardan mesul olmaycaq. Bu şartlar altındaki kollektiv mesuliyet 500$ (beş yüz dollar) meblâğını aşmaycaq. Bazı qazaiy aqlar belli ziyanlarnıñ istisnasına yaki sıñırlanmasına izin bermey, böyleliknen bu istisna ve sıñırlama sizge uyğulanmaybilir.</strong>
rights-webservices-term-6 = { -vendor-short-name }, kerekli olğanda zaman-zaman bu şartlarnı yañartabilir. Bu şartlar { -vendor-short-name } tarafından yazılı añlaşma olmadan deñiştirilalmaz ve lâğu etilalmaz.
rights-webservices-term-7 = Bu şartlarğa, onıñ qanun ükümleri çatışması müstesna, Kaliforniya, A.Q.Ş., qanunları akimdir. Bu şartlarnıñ er angi bir qısmı keçersiz yaki tatbiq etilalmaz olaraq tutulacaq olsa, qalğan qısımları tolusınen tatbiqat ve yürerlik içinde qalacaq. Bu şartlarnıñ tercime etilgen bir sürümi ile İngliz tilindeki sürümi arasında bir çatışma olğanı taqdirde, İngliz tilindeki sürümi muraqabe etecek.
