# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Wachttiid foarby
openFile = Bestân iepenje
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Sykje by %1$S nei ‘%2$S’
contextMenuSearch.accesskey = S
contextMenuPrivateSearch = Sykje yn in priveefinster
contextMenuPrivateSearch.accesskey = S
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Mei %S sykje yn in priveefinster
contextMenuPrivateSearchOtherEngine.accesskey = M
bookmarkAllTabsDefault = [Mapnamme]
unsignedAddonsDisabled.message = Ien of mear ynstallearre add-ons kinne net ferifiearre wurde en binne útskeakele.
unsignedAddonsDisabled.learnMore.label = Mear ynfo
unsignedAddonsDisabled.learnMore.accesskey = M
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Lêste tagong %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = %S://-keppelingen
crashedpluginsMessage.title = De %S ynstekker is ferûngelokke.
crashedpluginsMessage.reloadButton.label = Side opnij lade
crashedpluginsMessage.reloadButton.accesskey = S
crashedpluginsMessage.submitButton.label = Stjoer in ûngelokrapport
crashedpluginsMessage.submitButton.accesskey = S
crashedpluginsMessage.learnMore = Mear ynfo…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Woenen jo eins nei %S?
keywordURIFixup.goTo = Ja, bring mt nei %S
keywordURIFixup.goTo.accesskey = J
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Bywurkje nei %S
update.downloadAndInstallButton.accesskey = B
menuOpenAllInTabs.label = Alle iepenje yn ljepblêden
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Side opnij lade
tabHistory.goBack = Gean tebek nei dizze side
tabHistory.goForward = Gean foarút nei dizze side
# URL Bar
pasteAndGo.label = Plakke & iepenje
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Aktuele side fernije (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = It laden fan dizze side stopje (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Zoomnivo weromsette (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Lêzerwerjefte yn-/útskeakelje (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, zoomnivo opnij inisjalisearje
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Jo blêdwizers toane (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = De foartgong fan aktive downloads werjaan (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = In nij finster iepenje (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Nij ljepblêd iepenje (%S)
newTabContainer.tooltip = Iepenje in nij ljepblêd (%S)\nHâld yndrukt om in nij kontenerljepblêd te iepenjen
newTabAlwaysContainer.tooltip = Selektearje kontener om in nij ljepblêd te iepenjen
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Tastean dat %S jo HTML5-canvasôfbyldingsgegevens brûkt?
canvas.siteprompt2.warning = Dit kin brûkt wurde om jo kompjûter unyk te identifisearjen.
canvas.block = Blokkearje
canvas.block.accesskey = B
canvas.allow2 = Tastean
canvas.allow2.accesskey = T
canvas.remember2 = Dizze beslissing ûnthâlde
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Ferifiearre troch: %S
identity.identified.verified_by_you = Jo hawwe in feilichheidsútsûndering tafoege foar dizze website
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Sertifikaat útjûn oan: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Net feilich
identity.notSecure.tooltip = Ferbining is net befeilige
identity.extension.label = Utwreiding (%S)
identity.extension.tooltip = Laden troch útwreiding: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Utzoome (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Zoomnivo weromsette (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Ynzoome (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Knippe (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Kopiearje (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Plakke (%S)
geolocation.allow = Tastean
geolocation.allow.accesskey = T
geolocation.block = Blokkearje
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Dit iepenet de systeemynstellingen foar lokaasje. Jou lokaasjetastimming oan %S.
geolocation.shareWithSite4 = Tagong ta jo lokaasje troch %S tastean?
geolocation.shareWithFile4 = Tagong ta jo lokaasje troch dit lokale bestân tastean?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Tastean dat %1$S tastimming oan %2$S jout foar tagong ta jo lokaasje?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = %S lokaasjetastimming jaan yn systeemynstellingen.
geolocation.systemSettingsTitle = Wacht op tastimming foar lokaasje
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = It systeem sil jo freegje dizze tastimming oan %S te jaan.
geolocation.remember = Dizze beslissing ûnthâlde
# Virtual Reality Device UI
xr.allow2 = Tastean
xr.allow2.accesskey = T
xr.block = Blokkearje
xr.block.accesskey = B
xr.shareWithSite4 = Tagong ta virtual-reality-apparaten troch %S tastean? Dit kin gefoelige ynformaasje bleatlizze.
xr.shareWithFile4 = Tagong ta virtual-reality-apparaten troch dit lokale bestân tastean? Dit kin gefoelige ynformaasje bleatlizze.
xr.remember = Dizze beslissing ûnthâlde
# Persistent storage UI
persistentStorage.allow = Tastean
persistentStorage.allow.accesskey = T
persistentStorage.block.label = Blokkearje
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Bewarjen fan gegevens yn permaninte opslach troch %S tastean?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Tastean
webNotifications.allow2.accesskey = T
webNotifications.notNow = No net
webNotifications.notNow.accesskey = n
webNotifications.never = Nea tastean
webNotifications.never.accesskey = a
webNotifications.alwaysBlock = Altyd blokkearje
webNotifications.alwaysBlock.accesskey = b
webNotifications.block = Blokkearje
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = %S tastean om meldingen te ferstjoeren?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S wol tagong ta oare apps en tsjinsten op dit apparaat.
localhost.remember2 = Myn kar ûnthâlde foar dizze website
localhost.allowlabel = Tastean
localhost.blocklabel = Blokkearje
localhost.allow.accesskey = T
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S wol tagong ta apps en tsjinsten op apparaten dy’t ferbûn binne mei jo lokale netwurk.
localNetwork.remember2 = Myn kar ûnthâlde foar dizze website
localNetwork.allowLabel = Tastean
localNetwork.allow.accesskey = T
localNetwork.blockLabel = Blokkearje
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Helje my hjir út!
safebrowsing.getMeOutOfHereButton.accessKey = H
safebrowsing.deceptiveSite = Misliedende website!
safebrowsing.notADeceptiveSiteButton.label = Dit is gjin misliedende website…
safebrowsing.notADeceptiveSiteButton.accessKey = m
safebrowsing.reportedAttackSite = Rapportearre oanfalside!
safebrowsing.notAnAttackButton.label = Dit is gjin oanfalside…
safebrowsing.notAnAttackButton.accessKey = o
safebrowsing.reportedUnwantedSite = Rapportearre website mei net-winske software!
safebrowsing.reportedHarmfulSite = Rapportearre skeadlike website!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = %S trochsykje
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = %S opnij starte yn probleemoplossingsmodus?
troubleshootModeRestartPromptMessage = Jo útwreidingen, tema’s en oanpaste ynstellingen wurde tydlik útskeakele.
troubleshootModeRestartButton = Opnij starte
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Dizze side fertraget %1$S. Stopje dizze side om jo browser te fersnellen.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = In webside fertraget %1$S. Stopje dy side om jo browser te fersnellen.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = ‘%1$S’ fertraget %2$S. Stopje dy side om jo browser te fersnellen.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = ‘%1$S’ fertraget %2$S. Stopje dy útwreiding om jo browser te fersnellen.
processHang.add-on.learn-more.text = Mear ynfo
processHang.button_stop2.label = Stopje
processHang.button_stop2.accessKey = S
processHang.button_debug.label = Script debugge
processHang.button_debug.accessKey = d
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = It finster yn folslein skerm werjaan (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Sidebalke nei links ferpleatse
sidebar.moveToRight = Sidebalke nei rjochts ferpleatse
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Jo moatte DRM ynskeakelje om bepaalde audio of fideo op dizze side ôf te spyljen.
emeNotifications.drmContentDisabled.button.label = DRM ynskeakelje
emeNotifications.drmContentDisabled.button.accesskey = D
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = Om de audio of fideo op dizze side ôf te spyljen ynstallearret %S de nedige komponinten. Probearje it letter opnij.
emeNotifications.unknownDRMSoftware = Unbekend
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = %S oanpasse
decoder.noCodecs.button = Mear ynfo
decoder.noCodecs.accesskey = M
decoder.noCodecsLinux.message = Om fideo ôf te spyljen, moatte jo mooglik de fereaske fideocodecs ynstallearje.
decoder.noHWAcceleration.message = Om de fideokwaliteit te ferbetterjen, moatte jo mooglik Microsoft’s Media Feature Pack ynstallearje.
decoder.noPulseAudio.message = Om audio ôf te spyljen, moatte jo mooglik it fereaske PulseAudio-programma ynstallearje.
decoder.unsupportedLibavcodec.message = libavcodec kin kwetsber wêze of wurdt net stipe en soe fernijd wurde moatte om fideo ôf te spyljen.
decoder.decodeError.message = Der is in flater bard wylst it dekodearjen fan in mediaboarne.
decoder.decodeError.button = Websiteprobleem rapportearje
decoder.decodeError.accesskey = W
decoder.decodeWarning.message = Der is in werstelbere flater bard wylst it dekodearjen fan in mediaboarne.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Jo moatte jo by dit netwurk oanmelde eardat jo tagong krije ta it ynternet.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Oanmeldside fan netwurk iepenje
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Tastimmingen foar %S
permissions.remove.tooltip = Dizze tastimming wiskje en opnij freegje
permissions.fullscreen.promptCanceled = Annulearre wachtsjende machtigingsoanfragen: machtigingsoanfragen meie net takend wurde foar it iepenjen fan DOM yn de modus folslein skerm.
permissions.fullscreen.fullScreenCanceled = DOM-modus yn folslein skerm ôfsluten: machtigingsoanfragen meie net takend wurde wylst DOM yn folslein skerm útfierd wurdt.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bits
aboutDialog.architecture.thirtyTwoBit = 32-bits
midi.allow.label = Tastean
midi.allow.accesskey = T
midi.block.label = Blokkearje
midi.block.accesskey = B
midi.remember = Dizze beslissing ûnthâlde
midi.shareWithFile = Tagong ta jo MIDI-apparaten troch dit lokale bestân tastean?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Tagong ta jo MIDI-apparaten troch %S tastean?
midi.shareSysexWithFile = Tagong ta jo MIDI-apparaten en it ferstjoeren/ûntfangen fan SysEx-berjochten troch dit lokale bestân tastean?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Tagong ta jo MIDI-apparaten en it ferstjoeren/ûntfangen fan SysEx-berjochten troch %S tastean?
serial.allow.label = Tastean
serial.allow.accesskey = T
serial.block.label = Blokkearje
serial.block.accesskey = B
serial.shareWithFile = Tagong ta jo seriële poarten troch dit lokale bestân tastean?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Tagong ta jo seriële poarten troch %S tastean?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Tebek
storageAccess1.Allow.label = Tastean
storageAccess1.Allow.accesskey = T
storageAccess1.DontAllow.label = Blokkearje
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = %1$S tastean harren cookies te brûken op %2$S?
storageAccess1.hintText = Jo kinne de tagong blokkearje as it net dúdlik is wêrom %1$S dizze gegevens nedich hat.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Op it web nei ‘%S’ sykje
