# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Pretende confiar em “%S” para os seguintes propósitos?
unnamedCA = Autoridade certificadora (sem nome)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Escreva a palavra-passe utilizada para encriptar a cópia deste certificado:
# Page Info
pageInfo_NoEncryption = Ligação não encriptada
pageInfo_Privacy_None1 = O site %S não suporta encriptação para a página que está a ver.
pageInfo_Privacy_None2 = Informação enviada através da Internet sem encriptação pode ser vista por outras pessoas enquanto esta está em trânsito.
pageInfo_Privacy_None4 = A página que está a ver não foi encriptada antes de ser transmitida pela Internet.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Ligação encriptada (%1$S, chave %2$S bit, %3$S)
pageInfo_BrokenEncryption = Encriptação obsoleta (%1$S, chaves de %2$S bits, %3$S)
pageInfo_Privacy_Encrypted1 = A página que está a ver foi encriptada antes de ser transmitida pela Internet.
pageInfo_Privacy_Encrypted2 = A encriptação torna difícil para que pessoas não autorizadas vejam a informação que circula entre os computadores. Portanto é pouco provável que alguém leia esta página enquanto circulou pela rede.
pageInfo_MixedContent = Ligação parcialmente encriptada
pageInfo_MixedContent2 = Partes da página que está a ver não foram encriptadas antes de serem transmitidas pela Internet.
pageInfo_WeakCipher = A sua ligação a este site utiliza uma encriptação fraca que não é privada. Outras pessoas poder ver a sua informação ou modificar o comportamento do site.
pageInfo_CertificateTransparency_Compliant = Este site cumpre com a política do certificado de transparência.
# Token Manager
password_not_set = (não definida)
