# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Ricerca di { $host }…
network-connection-status-connected = Connesso a { $host }…
network-connection-status-sending-request = Invio richiesta a { $host }…
network-connection-status-transferring-data = Trasferimento dati da { $host }…
network-connection-status-connecting = Connessione in corso a { $host }…
network-connection-status-read = Lettura di { $host }
network-connection-status-wrote = Scritto { $host }
network-connection-status-waiting = In attesa di { $host }…
network-connection-status-looked-up = Cercato { $host }…
network-connection-status-tls-handshake = Esecuzione in corso di TLS handshake a { $host }…
network-connection-status-tls-handshake-finished = Completato TLS handshake a { $host }…
