# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Provjerava se { $host } …
network-connection-status-connected = Spojeno na { $host } …
network-connection-status-sending-request = Slanje zahtjeva na { $host } …
network-connection-status-transferring-data = Prijenos podataka iz { $host } …
network-connection-status-connecting = Povezivanje na { $host } …
network-connection-status-read = Pročitano { $host }
network-connection-status-wrote = Zapisano { $host }
network-connection-status-waiting = Čekanje na { $host } …
network-connection-status-looked-up = Provjeren { $host }…
network-connection-status-tls-handshake = Izvršavanje TLS provjere s { $host }…
network-connection-status-tls-handshake-finished = Završena TLS provjera s { $host }…
