# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Ուզո՞ւմ էք վստահել "%S"-ին հետեւեալ նպատակի համար:
unnamedCA = Վկայագրման կենտրոն (անանուն)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Խնդրեմ նշէք վկայագրի այս կրկնաւրինակը ծածկագրելու համար աւգտագործուած գաղտնաբառը:
# Page Info
pageInfo_NoEncryption = Կապակցումը գաղտնագրուած չէ
pageInfo_Privacy_None1 = %S-ի կայքը չի աջակցում գաղտնագրում դիտարկուող էջի համար։
pageInfo_Privacy_None2 = Համացանցով ուղարկուած չծածկագրուած տեղեկութիւնը փոխանցման ընթացքում կարող է դիտուել այլ անձանց կողմից:
pageInfo_Privacy_None4 = Ձեր կողմից դիտուող էջը չի ծածկագրուել նախքան համացանցով ուղարկուելը:
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Կապակցումը գաղտնագրուած է (%1$S, բանալի %2$S բիթ, %3$S)
pageInfo_BrokenEncryption = Վնասուած գաղտնագրում (%1$S բանալի, %2$S բիթ , %3$S)
pageInfo_Privacy_Encrypted1 = Ձեր կողմից դիտուող էջը ծածկագրուել է նախքան համացանցով ուղարկուելը:
pageInfo_Privacy_Encrypted2 = Գաղտնագրումը բարդացնում  է չարտօնուած անձանց կողմից համակարգիչների միջեւ փոխանցուող տեղեկատուութեան կարդալը: Հետեւաբար, հաւանական չէ, որ այս էջը որեւէ մեկը կարդացած լինի:
pageInfo_MixedContent = Կապը մասամբ ծածկագրուած է
pageInfo_MixedContent2 = Ձեր դիտած էջի որոշ մասեր համացանցով փոխանցուելիս չեն գաղտնագրուել:
pageInfo_WeakCipher = Այս կայքի հետ ձեր կապը թոյլ գաղտնագրում է աւգտագործում եւ գաղտնի չէ: Այլ մարդիկ կարող են տեսնել ձեր տեղեկատուութիւնը կամ փոփոխել կայքի աշխատանքը:
pageInfo_CertificateTransparency_Compliant = Այս կայքը համապատասխանում է Վկայագրի Թափանցիկութեան քաղաքականութեանը։
# Token Manager
password_not_set = (նշուած չէ)
