# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language-name-am = Amhariko
language-name-an = Aragones
language-name-ar = Arabo
language-name-ast = Asturiano
language-name-az = Azeri
language-name-be = Belaruso
language-name-bg = Bulgar
language-name-bn = Benggali
language-name-bo = Tibetano
language-name-bs = Bosnio
language-name-ca = Katalan
language-name-ch = Tsamorro
language-name-co = Korso
language-name-cs = Tseko
language-name-cu = Eslabiko Relihioso
language-name-cv = Tsubas
language-name-da = Danes
language-name-de = Aleman
language-name-el = Griego
language-name-en = Inggles
language-name-et = Estonio
language-name-eu = Basko
language-name-fa = Persiko
language-name-fj = Pihiano
language-name-fo = Faroes
language-name-fr = Pranses
language-name-fur = Priulano
language-name-fy = Prisio
language-name-ga = Irlandes
language-name-gd = Gaeliko nga Eskoses
language-name-gl = Galiego
language-name-gn = Guanari
language-name-he = Hebreo
language-name-hr = Kroata
language-name-hsb = Sorbio a Nangatngato
language-name-ht = Haitiano
language-name-hu = Ungaro
language-name-hy = Armenio
language-name-ii = Yi
language-name-is = Islandes
language-name-it = Italiano
language-name-ja = Hapon
language-name-jv = Habanes
language-name-ka = Heorhio
language-name-kg = Konggo
language-name-kl = Grenlandes
language-name-ko = Koreano
language-name-kok = Kokani
language-name-ks = Kasmiri
language-name-ku = Kurdo
language-name-kw = Kornuales
language-name-ky = Kirgis
language-name-li = Limburgano
language-name-ln = Linggala
language-name-lo = Laosiano
language-name-lt = Lituanio
language-name-lu = Luba-Katangga
language-name-lv = Leton
language-name-mg = Malgatse
language-name-mh = Marsiales
language-name-mk = Masedonio
language-name-mn = Monggol
language-name-ms = Malayo
language-name-mt = Maltes
language-name-my = Burmano
language-name-nb = Noruego (Bokmål)
language-name-nd = Ndebele (Amianan)
language-name-ng = Ndongga
language-name-nl = Olandes
language-name-nn = Noruego (Nynorsk)
language-name-no = Noruego
language-name-nr = Ndebele (Abagatan)
language-name-nso = Sotho (Amianan)
language-name-nv = Nabaho
language-name-ny = Tsitsewa
language-name-oc = Oksitan
language-name-pl = Polako
language-name-ps = Pasto
language-name-pt = Portuges
language-name-qu = Ketsua
language-name-rm = Reto-romaniko
language-name-ro = Romanio
language-name-ru = Ruso
language-name-sa = Sanskrito
language-name-sc = Sardo
language-name-se = Sami nga Amianan
language-name-sg = Sanggo
language-name-si = Singhales
language-name-sk = Eslobako
language-name-sm = Samoano
language-name-sr = Serbio
language-name-st = Sotho nga Abagatan
language-name-su = Sudanes
language-name-sv = Sueko
language-name-tk = Turkmeno
language-name-to = Tongga
language-name-tr = Turko
language-name-ty = Tahitiano
language-name-uk = Ukranio
language-name-uz = Usbek
language-name-vi = Bietnames
language-name-wa = Walon
language-name-wen = Sorbio
language-name-zh = Insek
