# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title Bokmärken


#define bookmarks_heading Bokmärken


#define bookmarks_toolbarfolder Bokmärkesfältsmapp


#define bookmarks_toolbarfolder_description Lägg bokmärken i denna mapp för att visa dem i Bokmärkesfältet


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/firefox/central/


#define getting_started Kom igång


# LOCALIZATION NOTE (firefox_heading):


# Firefox links folder name


#define firefox_heading Mozilla Firefox


# LOCALIZATION NOTE (firefox_help):


# link title for https://www.mozilla.org/en-US/firefox/help/


#define firefox_help Hjälp och vägledning


# LOCALIZATION NOTE (firefox_customize):


# link title for https://www.mozilla.org/en-US/firefox/customize/


#define firefox_customize Anpassa Firefox


# LOCALIZATION NOTE (firefox_community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox_community Engagera dig


# LOCALIZATION NOTE (firefox_about):


# link title for https://www.mozilla.org/en-US/about/


#define firefox_about Om oss


# LOCALIZATION NOTE (firefox_feedback):


# link title for browser feedback page


# currently used by Metro only: https://input.mozilla.org/feedback/metrofirefox


#define firefox_feedback Ge synpunkter


#unfilter emptyLines
