#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title Bokmärken
#define bookmarks_heading Bokmärken

#define bookmarks_toolbarfolder Bokmärkesfältsmapp
#define bookmarks_toolbarfolder_description Lägg bokmärken i denna mapp för att visa dem i Bokmärkesfältet

# LOCALIZATION NOTE (getting_started):
# link title for http://sv-se.www.mozilla.com/sv-SE/firefox/central/
#define getting_started Kom igång

# LOCALIZATION NOTE (latest_headlines):
# link title for the live bookmarks sample, a redirect on
# http://sv-se.fxfeeds.mozilla.com/sv-SE/firefox/headlines.xml
# Changing the redirect is subject to approval of l10n-drivers.
#define latest_headlines Senaste nytt

# LOCALIZATION NOTE (firefox_heading):
# Firefox links folder name
#define firefox_heading Mozilla Firefox

# LOCALIZATION NOTE (firefox_help):
# link title for http://sv-se.www.mozilla.com/sv-SE/firefox/help/
#define firefox_help Hjälp och vägledning

# LOCALIZATION NOTE (firefox_customize):
# link title for http://sv-se.www.mozilla.com/sv-SE/firefox/customize/
#define firefox_customize Anpassa Firefox

# LOCALIZATION NOTE (firefox_community):
# link title for http://sv-se.www.mozilla.com/sv-SE/firefox/community/
#define firefox_community Engagera dig

# LOCALIZATION NOTE (firefox_about):
# link title for http://sv-se.www.mozilla.com/sv-SE/about/
#define firefox_about Om oss

#unfilter emptyLines
