# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

customize-mode-restore-defaults =
    .label = Reafitar
customize-mode-menu-and-toolbars-header = Arrastra los elementos que prefieras a la barra de ferramientes o al menú flotante.
customize-mode-overflow-list-title = Menú flotante
customize-mode-uidensity =
    .label = Densidá
customize-mode-done =
    .label = Fecho
customize-mode-lwthemes-menu-manage =
    .label = Xestionar
    .accesskey = X
customize-mode-toolbars =
    .label = Barres de ferramientes
customize-mode-titlebar =
    .label = Barra de títulos
customize-mode-uidensity-menu-touch =
    .label = Táctil
    .accesskey = T
    .tooltiptext = Táctil
customize-mode-uidensity-auto-touch-mode-checkbox =
    .label = Usar «Táctil» pal mou de tableta
customize-mode-extra-drag-space =
    .label = Espaciu d'arrastre
customize-mode-lwthemes =
    .label = Estilos
customize-mode-overflow-list-description = Arrastra y suelta elementos equí pa tenelos a mano mas fuera de la barra de ferramientes…
customize-mode-uidensity-menu-normal =
    .label = Normal
    .accesskey = N
    .tooltiptext = Normal
customize-mode-uidensity-menu-compact =
    .label = Compauta
    .accesskey = C
    .tooltiptext = Compauta
customize-mode-uidensity-menu-compact-unsupported =
    .label = Compauta (nun se sofita)
    .accesskey = C
    .tooltiptext = Compauta (nun se sofita)
customize-mode-lwthemes-menu-get-more =
    .label = Consiguir más estilos
    .accesskey = C
customize-mode-undo-cmd =
    .label = Desfacer
customize-mode-lwthemes-my-themes =
    .value = Estilos de mio
customize-mode-touchbar-cmd =
    .label = Personalizar la barra táctil…
