# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

ssl-error-bad-mac-read = SSL recibió un rexistru con un códigu d'identificación de mensaxe incorreutu.
ssl-error-bad-block-padding = SSL recibió un rexistru con un axuste de bloque incorreutu.
ssl-error-rx-malformed-hello-request = SSL recibió un mensaxe de negociación Hello Request mal formáu.
ssl-error-rx-malformed-client-hello = SSL recibió un mensaxe de negociación Client Hello mal formáu.
ssl-error-rx-malformed-server-hello = SSL recibió un mensaxe de negociación Server Hello mal formáu.
ssl-error-rx-malformed-certificate = SSL recibió un mensaxe de negociación Certificate mal formáu.
ssl-error-rx-malformed-server-key-exch = SSL recibió un mensaxe de negociación Server Key Exchange mal formáu.
ssl-error-rx-malformed-cert-request = SSL recibió un mensaxe de negociación Certificate Reques mal formáu.
ssl-error-rx-malformed-hello-done = SSL recibió un mensaxe de negociación Server Hello Done mal formáu.
ssl-error-rx-malformed-cert-verify = SSL recibió un mensaxe de negociación Certificate Verify mal formáu.
ssl-error-rx-malformed-client-key-exch = SSL recibió un mensaxe de negociación Client Key Exchange mal formáu.
ssl-error-rx-malformed-finished = SSL recibió un mensaxe de negociación Finished mal formáu.
ssl-error-rx-malformed-change-cipher = SSL recibió un rexistru de cambéu d'especificaciones de cifráu mal formáu.
ssl-error-rx-unexpected-certificate = SSL recibió un mensaxe de negociación Certificate inesperáu.
ssl-error-rx-unexpected-server-key-exch = SSL recibió un mensaxe de negociación Server Key Exchange inesperáu.
ssl-error-rx-unexpected-cert-request = SSL recibió un mensaxe de negociación Certificate Request inesperáu.
ssl-error-pub-key-size-limit-exceeded = El sirvidor SSL tentó d'usar una clave pública de grau domésticu con una suite de cifráu d'esportación.
ssl-error-unknown-ca-alert = La otra parte nun reconoz o confía na CA qu'emitió el so certificáu.
ssl-error-access-denied-alert = La otra parte recibió un certificáu válidu, pero refugóse l'accesu.
ssl-error-decode-error-alert = L'otru cabu de la conexón, nun pudo decodificar un mensaxe de negociación SSL (SSL handshake).
ssl-error-decrypt-error-alert = La otra parte conseña un fallu na verificación de la robla o intercambéu de claves.
ssl-error-export-restriction-alert = La otra parte informa que la negociación nun cumple les regulaciones d'exportación.
ssl-error-protocol-version-alert = La otra parte informa d'una versión del protocolu non compatible o non almitida.
ssl-error-insufficient-security-alert = El sirvidor requier cifráu más seguru del sofitáu pol veceru
ssl-error-internal-error-alert = La otra parte informa qu'esperimentó un fallu internu
ssl-error-user-canceled-alert = L'usuariu del otru cabu de la conexón encaboxó la negociación.
ssl-error-no-renegotiation-alert = La otra parte nun permite renegociar los parámetros de seguridá SSL.
ssl-error-server-cache-not-configured = El caché del sirvidor SSL nun ta configuráu nin desactiváu nesti socket.
ssl-error-unsupported-extension-alert = L'otru cabu de la conexón SSL nun almite la estensión hello TLS solicitada.
ssl-error-certificate-unobtainable-alert = L'otru cabu de la conexón SSL nun pudo obtener el so certificáu de la URL suministrada.
ssl-error-unrecognized-name-alert = L'otru cabu de la conexón SSL nun tien certificáu pal nome DNS solicitáu.
ssl-error-bad-cert-status-response-alert = L'otru cabu de la conexón SSL nun pudo obtener una rempuesta OCSP pal so certificáu.
ssl-error-bad-cert-hash-value-alert = L'otru cabu de la conexón SSL informó d'un valor hash de certificáu erróneu.
sec-error-io = Hebo un fallu de E/S durante l'autorización de seguridá.
sec-error-library-failure = fallu de la biblioteca de seguridá.
sec-error-bad-data = biblioteca de seguridá: recibiéronse datos incorreutos.
sec-error-output-len = biblioteca de seguridá: fallu de llonxitú de salida.
sec-error-input-len = la biblioteca de seguridá esperimentó un fallu de llonxitú d'entrada.
sec-error-invalid-args = biblioteca de seguridá: argumentos non válidos.
sec-error-invalid-algorithm = biblioteca de seguridá: algoritmu non válidu.
sec-error-invalid-ava = biblioteca de seguridá: AVA non válidu.
sec-error-invalid-time = Cadena de data/hora incorreutamente formateada.
sec-error-bad-der = biblioteca de seguridá: mensaxe codificáu en DER incorreutamente formateáu.
sec-error-bad-signature = El certificáu de la otra parte tien una robla non válida.
sec-error-expired-certificate = El certificáu de la otra parte caducó.
sec-error-revoked-certificate = El certificáu de la otra parte revocóse.
sec-error-unknown-issuer = L'emisor del certificáu de la otra parte nun se reconoz.
sec-error-bad-key = La clave pública de la otra parte nun ye válida.
sec-error-bad-password = La contraseña de seguridá introducida ye incorreuta.
sec-error-retry-password = La nueva contraseña introdúxose incorreutamente. Por favor, inténtalo otra vegada.
sec-error-no-nodelock = biblioteca de seguridá: nun hai bloquéu de nodu (nodelock).
sec-error-bad-database = biblioteca de seguridá: base de datos incorreuta.
sec-error-no-memory = biblioteca de seguridá: fallu d'ubicación (allocation) de memoria.
sec-error-untrusted-issuer = L'emisor del certificáu de la otra parte conseñóse como non confiable pol usuariu.
sec-error-untrusted-cert = El certificáu de la otra parte conseñóse como non confiable pol usuariu.
sec-error-duplicate-cert = El certificáu yá esiste na base de datos.
sec-error-duplicate-cert-name = El nome del certificáu descargáu duplica ún yá instaláu na base de datos.
sec-error-adding-cert = Fallu al amestar el certificáu a la base de datos.
sec-error-filing-key = Fallu al enllenar la clave pa esti certificáu.
sec-error-no-key = La clav privada d' esti certificáu nun pue alcontrase na base de datos de claves
sec-error-cert-valid = Esti certificáu ye válidu.
sec-error-cert-not-valid = Esti certificáu nun ye válidu.
sec-error-cert-no-response = Biblioteca de certificaos: nun hai rempuesta
sec-error-expired-issuer-certificate = El certificáu del emisor del certificáu expiró. Compruebe la data y hora del so sistema.
sec-error-crl-expired = La CRL del emisor del certificáu expiró. Actualízala o comprueba la data y hora del so sistema.
sec-error-crl-bad-signature = La CRL del emisor del certificáu tien una robla non válida.
sec-error-crl-invalid = La nueva CRL tien un formatu non válidu.
sec-error-extension-value-invalid = El valor de la estensión del certificáu nun ye válidu.
sec-error-extension-not-found = Nun s'alcontró una estensión del certificáu.
sec-error-ca-cert-invalid = El certificáu del emisor nun ye válidu.
sec-error-path-len-constraint-invalid = La restricción a la llonxitú del camín del certificáu nun ye válida.
sec-error-cert-usages-invalid = El campu d'usos del certificáu nun ye válidu.
sec-internal-only = **Módulu EXCLUSIVAMENTE internu**
sec-error-invalid-key = La clave nun almite la operación solicitada.
sec-error-unknown-critical-extension = El certificáu contién una estensión crítica desconocida.
sec-error-old-crl = La nueva CRL nun ye postrera a l'actual.
sec-error-no-email-cert = Non cifráu o robláu: entá nun tienes un certificáu de corréu electrónicu.
sec-error-no-recipient-certs-query = Non cifráu: nun tien certificaos pa cada ún de los recipientes.
sec-error-not-a-recipient = Nun se pue descifrar: nun yes un destinatariu, o bien nun s'alcontró una clave privada o certificáu afayadizos.
sec-error-pkcs7-keyalg-mismatch = Nun se pue descifrar: l'algoritmu de cifráu de clave nun concasa col so certificáu.
sec-error-pkcs7-bad-signature = Verificación de la robla fallida: o nun s'alcontró roblante, o alcontráronse abondos roblantes, o los datos son inadecuaos o corruptos.
sec-error-unsupported-keyalg = Algoritmu de claves non almitíu o desconocíu.
sec-error-decryption-disallowed = Nun se pue descifrar: cifróse usando un algoritmu o tamañu de clave non permitíos.
xp-sec-fortezza-bad-card = La tarxeta Fortezza nun s'anició correctamente. Por favor, desaníciala y devuélvila al so emisor.
xp-sec-fortezza-no-card = Nun s'alcontraron tarxetes Fortezza
xp-sec-fortezza-none-selected = Nun hai tarxeta Fortezza seleicionada
xp-sec-fortezza-more-info = Seleicione una personalidá pa obtener más información sobro
xp-sec-fortezza-person-not-found = Personalidá non atopada
xp-sec-fortezza-no-more-info = Nun hai más información nesa personalidá
xp-sec-fortezza-bad-pin = PIN non válidu
sec-error-no-krl = Nun s'alcontró KRL pal certificáu d'esti sitiu.
sec-error-krl-expired = La KRL del certificáu d'esti sitiu expiró
sec-error-krl-bad-signature = La KRL del certificáu d'esti sitiu tien una robla non válida.
sec-error-revoked-key = La clave pal certificáu d'esti sitiu revocóse.
sec-error-krl-invalid = La nueva KRL tien un formatu non válidu.
sec-error-need-random = biblioteca de seguridá: necesítense datos al debalu.
sec-error-no-module = biblioteca de seguridá: dengún módulu de seguridá pue executar la operación solicitada.
sec-error-no-token = La tarxeta o token de seguridá nun esiste, tien qu'anicializase, o ta desaniciada.
sec-error-read-only = biblioteca de seguridá: base de datos de namái llectura.
sec-error-no-slot-selected = Nun se seleicionó una ranura o token.
sec-error-cert-nickname-collision = Yá esiste un certificáu col mesmu nomatu
sec-error-key-nickname-collision = Yá esiste una clave col mesmu nomatu
sec-error-safe-not-created = Fallu al crear l'oxetu seguru
sec-error-baggage-not-created = Fallu al crear l'oxetu de tresporte
xp-java-delete-privilege-error = Nun puede desaniciase'l privilexu
xp-java-cert-not-exists-error = Esti principal nun tien un certificáu
sec-error-bad-export-algorithm = L'algoritmu requeríu nun ta permitíu.
sec-error-exporting-certificates = Fallu al intentar esportar certificaos.
sec-error-importing-certificates = Fallu al intentar importar certificaos.
sec-error-pkcs12-decoding-pfx = Nun ye dable importar. Fallu de decodificación. Ficheru non válidu.
sec-error-pkcs12-invalid-mac = Nun ye dable importar. MAC non válida. Contraseña incorreuta o ficheru corruptu.
sec-error-pkcs12-unsupported-mac-algorithm = Nun ye dable importar. Algoritmu MAC non almitíu.
sec-error-pkcs12-unsupported-transport-mode = Nun ye dable importar. Namái s'almiten los moos de privacidá ya integridá de contraseña.
sec-error-pkcs12-corrupt-pfx-structure = Nun ye dable importar. La cadarma del ficheru ta corrupta.
sec-error-pkcs12-unsupported-pbe-algorithm = Nun ye dable importar. Algoritmu de cifráu non almitíu.
sec-error-pkcs12-unsupported-version = Nun ye dable importar. Versión del ficheru non almitida.
sec-error-pkcs12-privacy-password-incorrect = Nun ye dable importar. Contraseña de privacidá incorreuta.
sec-error-pkcs12-cert-collision = Nun ye dable importar. El mesmu nomatu esiste yá na base de datos.
sec-error-user-cancelled = L'usuariu calcó Encaboxar.
sec-error-pkcs12-duplicate-data = Non importáu, yá ta na base de datos.
sec-error-message-send-aborted = Mensaxe non unviáu.
sec-error-inadequate-key-usage = L'usu de la clave del certificáu ye inapropiada pa la operación pretendida.
sec-error-inadequate-cert-type = Tipu de certificáu non aprobáu pa l'aplicación.
sec-error-cert-addr-mismatch = La direición nel certificáu de robla nun concasa cola direición nes cabeceres del mensaxe.
sec-error-pkcs12-unable-to-import-key = Nun ye dable importar. Fallu al intentar importar la clave privada.
sec-error-pkcs12-importing-cert-chain = Nun ye dable importar. Fallu al intentar importar la cadena de certificaos.
sec-error-pkcs12-key-database-not-initialized = Nun ye dable esportar. La base de datos de claves ta frayada o ta desaniciada.
sec-error-keygen-fail = Nun ye dable xenerar el par de claves pública/privada.
sec-error-invalid-password = La contraseña introducida nun ye válida. Por favor, escueyi una distinta.
sec-error-retry-old-password = Contraseña anterior introducida incorreutamente. Por favor, inténtalo de nueves.
sec-error-bad-nickname = El nomatu del certificáu yá ta n'usu.
sec-error-not-fortezza-issuer = La cadena FORTEZZA de la otra parte tien un certificáu que nun ye de FORTEZZA.
sec-error-js-invalid-module-name = Nome de módulu non válidu.
sec-error-js-invalid-dll = Camín o nome de ficheru de módulu non válidu
sec-error-js-add-mod-failure = Nun ye dable amestar el módulu
sec-error-js-del-mod-failure = Nun ye dable desaniciar el módulu
sec-error-old-krl = La nueva KRL nun ye postrera a l'actual.
sec-error-ckl-conflict = La nueva CKL tien un emisor distintu de la CKL actual. Desanicia la CKL actual.
sec-error-cert-not-in-name-space = L'Autoridá Certificadora d'esti certificáu nun tien permitío emitir un certificáu con esti nome.
sec-error-krl-not-yet-valid = La llista de revocación de claves pa esti certificáu entá nun ye válida.
sec-error-crl-not-yet-valid = La llista de revocación de certificaos pa esti certificáu entá nun ye válida.
sec-error-unknown-cert = Nun se pudo alcontrar el certificáu solicitáu.
sec-error-unknown-signer = Nun se pudo alcontrar el certificáu del roblante.
sec-error-cert-bad-access-location = La direición del sirvidor d'estáu de certificáu tien un formatu non válidu.
sec-error-ocsp-unknown-response-type = La rempuesta OCSP nun pue decodificase ensembre; ye d'un tipu desconocíu.
sec-error-ocsp-bad-http-response = El sirvidor OCSP devolvió datos HTTP inesperaos/non válidos.
sec-error-ocsp-malformed-request = El sirvidor OCSP alcontró que la solicitú ta frañada o incorreutamente formada.
sec-error-ocsp-server-error = El sirvidor OCSP esperimentó un fallu internu.
sec-error-ocsp-try-server-later = El sirvidor OCSP suxer que lo intentes otra vegada más sero.
sec-error-ocsp-request-needs-sig = El sirvidor OCSP requier una robla nesta solicitú.
sec-error-ocsp-unauthorized-request = El sirvidor OCSP refugó esta solicitú como non autorizada.
sec-error-ocsp-unknown-response-status = El sirvidor OCSP devolvió un estáu irreconocible.
sec-error-ocsp-unknown-cert = El sirvidor OCSP nun tien estáu pal certificáu.
sec-error-ocsp-not-enabled = Tienes d'activar OCSP enantes d'executar esta operación.
sec-error-ocsp-no-default-responder = Tienes d'afitar el respondedor OCSP predetermináu enantes d'executar esta operación.
sec-error-ocsp-malformed-response = La rempuesta del sirvidor OCSP taba frañada o incorreutamente formada.
sec-error-ocsp-unauthorized-response = El roblante de la rempuesta OCSP nun ta autorizáu a dar l'estáu d'esti certificáu.
sec-error-ocsp-future-response = La rempuesta OCSP entá nun ye válida (contién una data nel futuru).
sec-error-ocsp-old-response = La rempuesta OCSP contién información non anovada.
sec-error-digest-not-found = Nun s'alcontró'l resume CMS o PKCS #7 nel mensaxe robláu.
sec-error-unsupported-message-type = El tipu de mensaxe CMS o PKCS #7 nun ta almitíu.
sec-error-module-stuck = El módulu PKCS #11 nun se pudo desaniciar darréu qu'entá ta n'usu
sec-error-bad-template = Nun se pudo decodificar los datos ASN.1. La plantía especificada nun yera válida.
sec-error-crl-not-found = Nun s'alcontró CRL afayadiza.
sec-error-reused-issuer-and-serial = Tas intentando importar un certificáu col mesmu númberu de serie/emisor qu'un certificáu esistente, pero nun ye'l mesmu certificáu.
sec-error-busy = NSS nun pudo zarrase. Entá hai oxetos n'usu.
sec-error-extra-input = El mensaxe codificáu con DER contenía datos estra ensin usar.
sec-error-unsupported-elliptic-curve = Curva elíptica non almitida.
sec-error-unsupported-ec-point-form = Forma de puntu de curva elíptica non almitida.
sec-error-unrecognized-oid = Identificador d'oxetu non reconocíu.
sec-error-ocsp-invalid-signing-cert = Certificáu de robla OCSP non válidu en rempuesta OCSP.
sec-error-revoked-certificate-crl = El certificáu ta revocáu na llista de revocación de certificaos del emisor.
sec-error-revoked-certificate-ocsp = El respondedor OCSP del emisor informa que'l certificáu ta revocáu
sec-error-crl-invalid-version = La llista de revocación de certificaos del emisor tien un númberu de versión desconocíu.
sec-error-crl-v1-critical-extension = La llista de revocación de certificaos V1 del emisor tien una estensión crítica.
sec-error-crl-unknown-critical-extension = La llista de revocación de certificaos V2 del emisor tien una estensión crítica desconocida.
sec-error-unknown-object-type = Tipu d'oxetu especificáu desconocíu.
sec-error-incompatible-pkcs11 = El controlador PKCS #11 viola la especificación nuna forma incompatible.
sec-error-no-event = Nun hai disponible dengún nuevu eventu de ranura nesti intre
sec-error-crl-already-exists = La CRL yá esiste.
sec-error-not-initialized = NSS nun ta anicializáu.
sec-error-token-not-logged-in = La operación falló darréu que'l token PKCS#11 nun anició sesión.
sec-error-ocsp-responder-cert-invalid = El certificáu configuráu del respondedor OCSP nun ye válidu.
sec-error-ocsp-bad-signature = La rempuesta OCSP tien una robla non válida
