# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = Xëtu web bii ñi ngi kooy jubalaat ci beneen berab. Ndax bëgg nga yonneewaat rootaani formileer yi ñu jota dugal ñu jëm ci xët bu bees bi?
# Directory listing strings
DirTitle = Alluwa baat bu %1$S
DirGoUp = Jëm ci wayndare bu gëna kawe
ShowHidden = Wone mbir yi nëbbu
DirColName = Tur
DirColSize = Dayo
DirColMTime = Besu soppi
DirFileLabel = Dencukaay:\u0020
