# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

third-party-page-title = معلومات وحدة الطرف الثالث
third-party-section-title = قائمة وحدات الطرف الثالث في { -brand-short-name }
third-party-message-empty = لم تكتشف أي وحدات طرف ثالث.
third-party-message-no-duration = غير مسجل
third-party-detail-version = إصدار الملف
third-party-detail-vendor = معلومات المنتِج
third-party-detail-occurrences = التكرارات
    .title = كم مرة تم تحميل هذه الوحدة.
third-party-detail-app = التطبيق
third-party-detail-publisher = الناشر
third-party-th-process = عملية
third-party-th-duration = مدة التحميل (مللي ثانية)
third-party-th-status = الحالة
third-party-icon-unsigned =
    .title = هذه الوحدة غير موقعة
    .alt = هذه الوحدة غير موقعة
third-party-icon-warning =
    .title = إنهار { -brand-short-name } برمجيا بسبب هذه الوحدة
    .alt = إنهار { -brand-short-name } برمجيا بسبب هذه الوحدة
third-party-status-loaded = حُمِّل
third-party-status-blocked = حُجبت
third-party-status-redirected = تمت إعادة توجيهه
third-party-button-copy-to-clipboard = انسخ البيانات الخام إلى الحافظة
third-party-loading-data =
    .alt = جارٍ تحميل معلومات النظام…
    .title = جارٍ تحميل معلومات النظام…
third-party-button-reload = أعد التحميل مع معلومات النظام
    .title = أعد التحميل مع معلومات النظام
third-party-button-open =
    .title = افتح مكان الملف…
third-party-button-to-block =
    .title = احجب هذه الوحدة
    .aria-label = احجب هذه الوحدة
third-party-button-to-unblock =
    .title = محجوب حاليا، انقر لإلغاء حجبه.
    .aria-label = محجوب حاليا، انقر لإلغاء حجبه.
third-party-button-to-block-module = احجب هذه الوحدة
    .title = احجب هذه الوحدة
    .aria-label = احجب هذه الوحدة
third-party-button-to-unblock-module = إلغاء حظر هذه الوحدة
    .title = محجوب حاليا، انقر لإلغاء حجبه.
    .aria-label = محجوب حاليا، انقر لإلغاء حجبه.
third-party-button-expand =
    .title = أظهر المعلومات المفصلة
third-party-button-collapse =
    .title = اطو المعلومات المفصلة
third-party-blocking-requires-restart = لحجب وحدة من طرف ثالث، يجب إعادة تشغيل { -brand-short-name }.
third-party-should-restart-title = أعِد تشغيل { -brand-short-name }
third-party-restart-now = أعِد التشغيل الآن
