# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language-name-aa = Աֆարերէն
language-name-ab = Աբխազերէն
language-name-ach = Աչոլի
language-name-ae = Աւեստերէն
language-name-af = Աֆրիկաանս
language-name-ak = Ական
language-name-am = Ամհարերէն
language-name-an = Արագոներէն
language-name-ar = Արաբերէն
language-name-as = Ասսամերէն
language-name-ast = Աւստրերէն
language-name-av = Աւարերէն
language-name-ay = Այմարա
language-name-az = Ադրբեջաներէն
language-name-ba = Բաշկիրերէն
language-name-be = Բելառուսերէն
language-name-bg = Բուլղարերէն
language-name-bh = Բիհարի
language-name-bi = Բիսլամա
language-name-bm = Բամբարա
language-name-bn = Բենգալերէն
language-name-bo = Տիբեթերէն
language-name-br = Բրետոներէն
language-name-bs = Բոսնիերէն
language-name-ca = Կատալոներէն
language-name-cak = Կաքչիքելերէն
language-name-ce = Չեչեներէն
language-name-ch = Չամորերէն
language-name-co = Կորսիկերէն
language-name-cr = Կրի
language-name-crh = Ղրիմի թաթարերէն
language-name-cs = Չեխերէն
language-name-csb = Կաշուբերէն
language-name-cu = Եկեղեցական սլաւոներէն
language-name-cv = Չուվաշերէն
language-name-cy = Ուելսերէն
language-name-da = Դանիերէն
language-name-de = Գերմաներէն
language-name-dsb = Ստորին սորբերէն
language-name-dv = Մալդիւերէն
language-name-dz = Ձոնգքհա
language-name-ee = էվէ
language-name-el = Յունարէն
language-name-en = Անգլերէն
language-name-eo = Էսպերանտո
language-name-es = Իսպաներէն
language-name-et = Էստոներէն
language-name-eu = Բասկերէն
language-name-fa = Պարսկերէն
language-name-ff = ֆուլահ
language-name-fi = Ֆիններէն
language-name-fj = Ֆիջիերէն
language-name-fo = Ֆարեօրերէն
language-name-fr = Ֆրանսերէն
language-name-fur = Ֆրիուլիերէն
language-name-fy = Ֆրիզերէն
language-name-ga = Իռլանդերէն
language-name-gd = Շոտլանդական գելերեն
language-name-gl = Գալլերէն
language-name-gn = գուարանի
language-name-gu = Գուջարաթի
