# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = सहेजल लॉगिन
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-username-cmd =
    .label = प्रयोक्तानाम केर नकल लिअ
    .accesskey = U
edit-username-cmd =
    .label = उपयोक्तानाम संपादन
    .accesskey = स
copy-password-cmd =
    .label = कूटशब्द क नक़ल लिअ
    .accesskey = C
edit-password-cmd =
    .label = कूटशब्द संपादन
    .accesskey = क
column-heading-site =
    .label = साइट
column-heading-username =
    .label = प्रयोक्तानाम
column-heading-password =
    .label = गुड़किल्ली
column-heading-time-created =
    .label = पहिलबेर प्रयोग
column-heading-time-last-used =
    .label = अंतिमबेर प्रयुक्त
column-heading-time-password-changed =
    .label = अंतिम बदलाव
column-heading-times-used =
    .label = जतेकबेर प्रयुक्त
remove =
    .label = हटाउ
    .accesskey = R
import =
    .label = आयात करू…
    .accesskey = I
close-button =
    .label = बन्न  करू
    .accesskey = C
logins-description-filtered = निम्नलिखित गुड़किल्ली अहाँक खोज सँ मैच करैत अछि:
remove-all-passwords-prompt = की अहाँ सबहि कूटशब्दकेँ हटाना चाहैत छी?
remove-all-passwords-title = सभटा गुड़किल्ली हटाउ
no-master-password-prompt = की अहाँ अपन कूटशब्दकेँ देखाबै चाहैत छी?
