# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = E sheba { $host }...
network-connection-status-connected = E hoketse ho { $host }...
network-connection-status-sending-request = E romela kopo ho { $host }...
network-connection-status-transferring-data = E fetisa data ho tswa ho { $host }...
network-connection-status-connecting = E hokela ho { $host }...
network-connection-status-read = E badile { $host }
network-connection-status-wrote = E ngotse { $host }
network-connection-status-waiting = E emetse { $host }...
