# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

REG_APP_DESC = $BrandShortName nodrošina drošu un vienkāršu tīmekļa pārlūkošanu. Pazīstama lietotāja saskarne, uzlabota drošība, kas sevī iekļauj aizsardzību no interneta krāpniecībām, un integrētas meklēšanas iespējas ļauj jums iegūt maksimāli iespējamo sērfojot internetā.
BRIEF_APP_DESC = Ātra un privāta tīmekļa pārlūkošana
# LOCALIZATION NOTE:
# The non-variable portion of this MUST match the translation of
# "private-browsing-shortcut-text-2" in browser.ftl
PRIVATE_BROWSING_SHORTCUT_TITLE = $BrandShortName privātā pārlūkošana
CONTEXT_OPTIONS = $BrandShortName &iestatījumi
CONTEXT_SAFE_MODE = $BrandShortName drošai&s režīms
OPTIONS_PAGE_TITLE = Iestatīšanas veids
OPTIONS_PAGE_SUBTITLE = Izvēlies iestatīšanas iespējas
SHORTCUTS_PAGE_TITLE = Izveidot saīsnes
SHORTCUTS_PAGE_SUBTITLE = Izveidot programmas ikonas
COMPONENTS_PAGE_TITLE = Iestatīt papildu sastāvdaļas
COMPONENTS_PAGE_SUBTITLE = Ieteiktās papildu sastāvdaļas
OPTIONAL_COMPONENTS_DESC = Apkopes serviss ļaus jums netraucēti fonā atjaunināt $BrandShortName.
MAINTENANCE_SERVICE_CHECKBOX_DESC = Uzstādīt &apkopes pakalpojumu
SUMMARY_PAGE_TITLE = Kopsavilkums
SUMMARY_PAGE_SUBTITLE = Viss gatavs $BrandShortName uzstādīšanai
SUMMARY_INSTALLED_TO = $BrandShortName tiks instalēta šajā vietā:
SUMMARY_REBOOT_REQUIRED_INSTALL = Instalēšanas pabeigšanai var būt nepieciešama datora pārstartēšana.
SUMMARY_REBOOT_REQUIRED_UNINSTALL = Atinstalēšanas pabeigšanai var būt nepieciešama datora pārstartēšana.
SUMMARY_TAKE_DEFAULTS = I&zmantot $BrandShortName kā manu noklusēto tīmekļa pārlūku
SUMMARY_INSTALL_CLICK = Klikšķiniet uz Instalēt, lai turpinātu.
SUMMARY_UPGRADE_CLICK = Klikšķini uz “Jaunināt”, lai turpinātu!
SURVEY_TEXT = Pas&tāstiet mums, ko jūs domājat par $BrandShortName
LAUNCH_TEXT = Pa&laist $BrandShortName
CREATE_ICONS_DESC = Izveidot $BrandShortName ikonas:
ICONS_DESKTOP = Uz &darbvirsmas
ICONS_STARTMENU = Manā &Start izvēlnes Programmu mapē
ICONS_TASKBAR = Manā &uzdevumjoslā
WARN_MANUALLY_CLOSE_APP_INSTALL = $BrandShortName ir jāaizver, lai turpinātu uzstādīšanu.\n\nLūgums aizvērt $BrandShortName, lai turpinātu.
WARN_MANUALLY_CLOSE_APP_UNINSTALL = $BrandShortName ir jāaizver, lai turpinātu noņemšanu.\n\nLūgums aizvērt $BrandShortName, lai turpinātu.
WARN_MANUALLY_CLOSE_APP_REFRESH = $BrandShortName ir jāaizver, lai turpinātu atsvaidzināšanu.\n\nLūgums aizvērt $BrandShortName, lai turpinātu.
WARN_WRITE_ACCESS = Jums nav pietiekamu tiesību, lai rakstītu instalēšanas mapē.\n\nSpiediet Labi, lai izvēlētos citu mapi.
WARN_DISK_SPACE = Jums nav pietiekami daudz brīvas diska vietas instalēšanas mapē.\n\nSpiediet Labi, lai izvēlētos citu mapi.
WARN_MIN_SUPPORTED_OSVER_MSG = Atvainojiet, nevar instalēt $BrandShortName. Šai $BrandShortName versijai ir nepieciešama ${MinSupportedVer} vai jaunāka. Lūdzu, noklikšķiniet uz pogas Labi, lai iegūtu papildu informāciju.
WARN_MIN_SUPPORTED_CPU_MSG = Atvainojiet, nevar instalēt $BrandShortName. Šai $BrandShortName versijai ir nepieciešams procesors ar ${MinSupportedCPU} atbalstu. Lūdzu, noklikšķiniet uz pogas Labi, lai iegūtu papildu informāciju.
WARN_MIN_SUPPORTED_OSVER_CPU_MSG = Atvainojiet, nevar instalēt $BrandShortName. Šai $BrandShortName versijai ir nepieciešama ${MinSupportedVer} vai jaunāka un procesors ar ${MinSupportedCPU} atbalstu. Lūdzu, noklikšķiniet uz pogas Labi, lai iegūtu papildu informāciju.
WARN_RESTART_REQUIRED_UNINSTALL = Dators ir jāpārsāknē, lai pabeigtu iepriekšējo $BrandShortName noņemšanu. Vai darīt to tagad?
WARN_RESTART_REQUIRED_UPGRADE = Dators ir jāpārsāknē, lai pabeigtu iepriekšējo $BrandShortName jaunināšanu. Vai darīt to tagad?
ERROR_CREATE_DIRECTORY_PREFIX = Kļūda, veidojot mapi:
ERROR_CREATE_DIRECTORY_SUFFIX = Klikšķiniet uz Atcelt, lai pārtrauktu instalēšanu, vai\nAtkārtot, lai mēģinātu vēlreiz.
UN_CONFIRM_PAGE_TITLE = Atinstalēt $BrandFullName
UN_CONFIRM_PAGE_SUBTITLE = Aizvākt $BrandFullName no jūsu datora.
UN_CONFIRM_UNINSTALLED_FROM = $BrandShortName tiks aizvākta no sekojošas vietas:
UN_CONFIRM_CLICK = Jāklikšķina uz "Noņemt", lai turpinātu.
UN_REFRESH_PAGE_TITLE = Vai tā vietā atsvaidzināt $BrandShortName?
UN_REFRESH_PAGE_EXPLANATION = Ja jums ir problēmas ar $BrandShortName, atsvaidzināšana varētu palīdzēt.\n\nTādējādi tiks atjaunoti noklusējuma iestatījumi un izņemti papildinājumi. Sāciet no jauna, lai nodrošinātu optimālu veiktspēju.
UN_REFRESH_LEARN_MORE = &Uzzināt vairāk
UN_REFRESH_BUTTON = &Atsvaidzināt $BrandShortName
BANNER_CHECK_EXISTING = Pārbauda esošo instalāciju...
STATUS_INSTALL_APP = Uzstāda $BrandShortName…
STATUS_INSTALL_LANG = Uzstāda valodu datnes (${AB_CD})…
STATUS_UNINSTALL_MAIN = Noņem $BrandShortName…
STATUS_CLEANUP = Notiek neliela uzkopšana…
UN_SURVEY_CHECKBOX_LABEL = Pastāsti Mozilla, kāpēc noņēmi $BrandShortName
# _DESC strings support approximately 65 characters per line.
# One line
OPTIONS_SUMMARY = Jāizvēlas vēlamais uzstādīšanas veids, tad jāspiež poga “Turpināt".
# One line
OPTION_STANDARD_DESC = $BrandShortName tiks uzstādīta ar biežāk izmantotajām iespējām.
OPTION_STANDARD_RADIO = &Standarta
# Two lines
OPTION_CUSTOM_DESC = Šajā režīmā jūs varat izvēlēties sastāvdaļas pa vienai. Ieteicams pieredzējušiem lietotājiem.
OPTION_CUSTOM_RADIO = &Pielāgota instalācija
# LOCALIZATION NOTE:
# The following text replaces the Install button text on the summary page.
UPGRADE_BUTTON = &Atjaunināt
