# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SaveImageTitle = Sàbhail an dealbh
SaveMediaTitle = Sàbhail am meadhan
SaveVideoTitle = Sàbhail am video
SaveAudioTitle = Sàbhail an fhuaim
SaveLinkTitle = Sàbhail mar
WebPageCompleteFilter = Duilleag-lìn, gu h-iomlan
WebPageHTMLOnlyFilter = Duilleag-lìn, HTML a-mhàin
WebPageXHTMLOnlyFilter = Duilleag-lìn, XHTML a-mhàin
WebPageSVGOnlyFilter = Duilleag-lìn, SVG a-mhàin
WebPageXMLOnlyFilter = Duilleag-lìn, XML a-mhàin
# LOCALIZATION NOTE (UntitledSaveFileName):
#    This is the default filename used when saving a file if a filename could
#    not be determined or if a filename was invalid. A period and file
#    extension may be appended to this string.
UntitledSaveFileName = Gun tiotal
