# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=Ho seta $ProductName$
Welcome_MessageWelcome=O amohetswe ho %s!
Welcome_Message0=You are about to install %s 2 Alpha 1.
Welcome_Message1=O kgothaletswa ka matla ho tswa diprokremeng tsohle tsa Windows bulela prokreme ena ya Ho seta.
Welcome_Message2=Tlelika Khansela ho tswa ho Seteng eb o kwala diprokreme dife kapa dife tse buletsweng.  Tlelika E latelang ho tswela pele ka Ho seta prokreme.
Welcome_Message3=Click Next to continue installing %s 2 Alpha 1.

License_Title=Laesense ya Tumellano ya Software
License_SubTitle=Dipehelo le maemo bakeng sa ho sebedisa software ena.
License_Message0=Ka kopo bala tumellano e latelang ya laesense. Sebedisa mola wa ho tsamaya ho sheba tumellano yohle ya laesense ena.
License_Accept=Ke&Amohela dipehelo tsa Tumellano ya Laesense
License_Decline=HA KE Amo&hele dipehelo tsa Tumellanao ya Laesense

Type_Title=Mofuta wa Ho seta
Type_SubTitle=Kgetha dikgethong tsa ho seta.
Type_Message0=Kgetha mofuta wa ho Seta o batlwang ke wena, ebe o tobetsa E lateng.

Standard_Short=&E tlwaelehileng
Standard_Long=Thunderbird e tla instolwa ka dikgetho tse atileng ka ho fetisisa.

Custom_Short=&Ya tlwaelo
Custom_Long=O ka kgetha dikgetho ka bonngwe hore di instolwe. E kgothaletswa basebedisi ba hatetseng pele.

Select_Title=Kgetha dikarolowana
Select_SubTitle=Dikarolwana tsa tlatsetso tse matlafatsang $ProductName$.
Select_Message0=Kgetha dikarolo tsa tlatsetso tseo o batlang ho di instola, ebe o tlelika E latelang.

Path_Title=Instola Foldara
Path_SubTitle=Moo $ProductName$ e tla kenngwa.
Path_Message0=$ProductName$ e tla instolwa foldareng e latelang:

Integration_Title=Dikgutsufatso tsa Ho seta
Integration_SubTitle=E etsa Diaekhone tsa prokreme
Integration_Message0=Etsa diaekhone tsa $ProductShortName$:

Integration_Desktop=Deskethopong ya ka
Integration_StartMenu=Foldareng ya prokreme ya Menu ya ho Qala
Integration_QuickLaunch=Moleng wa ka wa Ho thakgola Kapele

SelectFolder_Title=$ProductName$ Ho seta - Kgetha Foldara ya Prokreme
SelectFolder_Message0=Ho seta ho tla eketsa diaekhone tsa prokreme Foldareng ya prokreme e lenaneng le katlase.  O ka nna wa thaepa lebitso le letjha la foldara, kapa o kgethe le leng lenaneng le Teng la Difoldara.  Tlelika E latelang ho tswela pele.

Advanced_Title=$ProductName$ Ho Seta - Disetwa tse Hatetseng Pele
Advanced_Message0=Ha kgokelo ya hao inthaneteng e hloka seva ya proksi kenya lebitso la seva le tlhahisoleseding ya port.  Ha kgokelo ya hao inthaneteng e sa hloke seva ya proksi tlohela dibaka di sa tlatswa.

Install_Title=Kakaretso
Install_SubTitle=E lokile ho ka qala ho instola $ProductName$.
Install_MessageInstall=Jwale ho seta ho tla instola dikaro tse latelang:
Install_MessageDownload=Jwale ho seta ho tla jarolla le ho instola dikarolwana tse latelang:
Install_Message0=Tobetsa E latelang ho tswela pele.

Downloading_Title=Ho jarolla
Downloading_SubTitle=Ho jarolla ho hlokile dikarolwana tsa...
Downloading_Blurb=Ho seta ho jarolla difaele tse hlokehang ho instola $ProductName$.
Downloading_FileName=Hajwale e Jarolla:
Downloading_Time=Nako e Setseng:

Installing_Title=E a instola
Installing_SubTitle=E instola $ProductName$...
Installing_Blurb=Ho seta ho instola difaele tsa tshebetso.
Installing_Status=E lokisa Faele:
Installing_Component=Hajwale e Instola:

Success_Title=Ho instola ho Phethilwe
Success_Header=Ho instola ho Phethilwe
Success_Message0=%s was successfully installed.
Success_Message1=Tlelika Qeta ho phethela Ho seta.
Success_Launch=Launch %s now.

Check_Message=Ho jarolla $ProductName$ ho atlehile. $ProductNameInternal$ e lokela ho kwalwa hre o tswele pele ka ho instola. Tlelika OK ho tswa ho $ProductNameInternal$ ka ho iketsa le ho qala ho instola.
Check_FullMessage=$ProductNameInternal$ le tshwanetse ho kwalwa hore o tswele pele ka ho instola. Tobetsa OK hore o tswe ho $ProductNameInternal$ ka ho iketsa hore o qale ho instola.
Check_Wait=E kwalwa $ProductNameInternal$.  Ka kopo ema...

Component_XPCOM=Polateforomo-ya-Sefapano COM
Component_Mail=$ProductName$
Component_Offline=Tshehetso ya Ha o hakolotse
Component_Offline_Long=E eketsa Tshehetso ya Ha o hakolotse ho Meile ya $ProductName$.
Component_RSS=Tshehetso ya RSS
Component_RSS_Long=E eketsa tshehetso ya RSS ho $ProductName$.
Component_QFA=Kemedi ya Tlalehelo ya Khwalithi
Component_QFA_Long=bakeng sa to tlaleha tlhahisoleseding ya ho wa ha $ProductName$
