# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host }  ژھانڈان ...
network-connection-status-connected = { $host } ئس رٲبطئ كرمُت...
network-connection-status-sending-request = { $host } ئ سوزان درخواست...
network-connection-status-transferring-data = { $host } پ۪یٹھئ ڈاٹا منتقل كران ...
network-connection-status-connecting = { $host } ئس رٲبطئ كران
network-connection-status-read = پریو { $host }...
network-connection-status-wrote = لیوكھ { $host }...
network-connection-status-waiting = { $host }پیاران ...
network-connection-status-looked-up = { $host } ژھونڈ...
