# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Credenciais guardadas
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Copiar URL
    .accesskey = r
launch-site-url-cmd =
    .label = Visitar URL
    .accesskey = V
copy-username-cmd =
    .label = Copiar nome de utilizador
    .accesskey = u
edit-username-cmd =
    .label = Editar nome de utilizador
    .accesskey = d
copy-password-cmd =
    .label = Copiar palavra-passe
    .accesskey = C
edit-password-cmd =
    .label = Editar palavra-passe
    .accesskey = E
search-filter =
    .accesskey = s
    .placeholder = Pesquisar
column-heading-site =
    .label = Site
column-heading-username =
    .label = Nome de utilizador
column-heading-password =
    .label = Palavra-passe
column-heading-time-created =
    .label = Primeira utilização
column-heading-time-last-used =
    .label = Última utilização
column-heading-time-password-changed =
    .label = Última alteração
column-heading-times-used =
    .label = Vezes usada
remove =
    .label = Remover
    .accesskey = R
import =
    .label = Importar…
    .accesskey = I
close-button =
    .label = Fechar
    .accesskey = e
show-passwords =
    .label = Mostrar palavras-passe
    .accesskey = P
hide-passwords =
    .label = Ocultar palavras-passe
    .accesskey = P
logins-description-all = As credenciais para os seguintes sites estão armazenadas no seu computador
logins-description-filtered = As seguintes credenciais correspondem à sua pesquisa:
remove-all =
    .label = Remover todas
    .accesskey = t
remove-all-shown =
    .label = Remover todas as mostradas
    .accesskey = t
remove-all-passwords-prompt = Tem a certeza que pretende remover todas as suas palavras-passe?
remove-all-passwords-title = Remover todas as palavras-passe
no-master-password-prompt = Tem a certeza que pretende mostrar todas as suas palavras-passe?
auto-fill-logins-and-passwords =
    .label = Auto-preencher credenciais e palavras-passe
