# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Inicios de sesión guardados
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Copiar URL
    .accesskey = y
launch-site-url-cmd =
    .label = Visitar URL
    .accesskey = V
copy-username-cmd =
    .label = Copiar usuario
    .accesskey = u
edit-username-cmd =
    .label = Editar Nombre de usuario
    .accesskey = d
copy-password-cmd =
    .label = Copiar contraseña
    .accesskey = C
edit-password-cmd =
    .label = Editar contraseña
    .accesskey = E
search-filter =
    .accesskey = S
    .placeholder = Buscar
column-heading-site =
    .label = Sitio
column-heading-username =
    .label = Nombre de usuario
column-heading-password =
    .label = Contraseña
column-heading-time-created =
    .label = Usado por primera vez
column-heading-time-last-used =
    .label = Usado por última vez
column-heading-time-password-changed =
    .label = Última vez cambiado
column-heading-times-used =
    .label = Veces usada
remove =
    .label = Eliminar
    .accesskey = E
import =
    .label = Importar…
    .accesskey = I
close-button =
    .label = Cerrar
    .accesskey = C
show-passwords =
    .label = Mostrar contraseñas
    .accesskey = P
hide-passwords =
    .label = Ocultar contraseñas
    .accesskey = P
logins-description-all = Los inicios de sesión para los siguientes sitios web están almacenados en tu computadora
logins-description-filtered = Los siguientes inicios de sesión coinciden con tu búsqueda:
remove-all =
    .label = Eliminar todo
    .accesskey = A
remove-all-shown =
    .label = Eliminar todas las mostradas
    .accesskey = A
remove-all-passwords-prompt = ¿Seguro que quieres eliminar todas las contraseñas?
remove-all-passwords-title = Eliminar todas las contraseñas
no-master-password-prompt = ¿Seguro que quieres mostrar tus contraseñas?
auto-fill-logins-and-passwords =
    .label = Autocompletar inicios de sesión y contraseñas
