# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = ຕົວຊ່ວຍນຳເຂົ້າ
import-from =
    { PLATFORM() ->
        [windows] ນຳເຂົ້າຕົວເລືອກ, ບຸກມາກ, ປະຫວັດການໃຊ້ງານ, ລະຫັດຜ່ານ ແລະຂໍ້ມູນອື່ນໆຈາກ:
       *[other] ນຳເຂົ້າການຕັ້ງຄ່າ, ບຸກມາກ, ປະຫວັດການໃຊ້ງານ, ລະຫັດຜ່ານ ແລະຂໍ້ມູນອື່ນໆຈາກ:
    }
import-from-bookmarks = ນຳເຂົ້າບຸກມາກຈາກ:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-nothing =
    .label = ບໍ່ນຳເຂົ້າສິ່ງໃດໆເລີຍ
    .accesskey = D
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chrome-beta =
    .label = Chrome Beta
    .accesskey = B
import-from-chrome-dev =
    .label = Chrome Dev
    .accesskey = D
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = X
import-from-360se =
    .label = 360 Secure Browser
    .accesskey = 3
no-migration-sources = ບໍ່ພົບໂປຣແກຣມທີ່ມີບຸກມາກ, ປະຫວັດການໃຊ້ງານ ຫລືຂໍ້ມູນລະຫັດຜ່ານ.
import-source =
    .label = ນຳເຂົ້າການຕັ້ງຄ່າແລະຂໍ້ມູນ
import-items-title =
    .label = ລາຍການທີ່ຈະນຳເຂົ້າ
import-items-description = ເລືອກລາຍການທີ່ຈະນຳເຂົ້າ:
import-migrating-title =
    .label = ກຳລັງນຳເຂົ້າ…
import-migrating-description = ກຳລັງນຳເຂົ້າລາຍການດັ່ງຕໍ່ໄປນີ້ໃນຂະນະນີ້…
import-select-profile-title =
    .label = ເລືອກໂປຣໄຟລ໌
import-select-profile-description = ໂປຣໄຟລ໌ດັ່ງຕໍ່ໄປນີ້ພ້ອມທີ່ຈະນຳເຂົ້າ:
import-done-title =
    .label = ການນຳເຂົ້າສຳເລັດສົມບູນ
import-done-description = ນຳເຂົ້າລາຍການດັ່ງຕໍ່ໄປນີ້ສຳເລັດແລ້ວ:
import-close-source-browser = ກະລຸນາກວດໃຫ້ແນ່ໃຈວ່າບຣາວເຊີທີ່ເລືອກປິດຢູ່ກ່ອນທີ່ຈະສືບຕໍ່.
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = ຈາກ { $source }
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chrome-beta = Google Chrome Beta
source-name-chrome-dev = Google Chrome Dev
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Secure Browser
imported-safari-reading-list = ລາຍການອ່ານ (ຈາກ Safari)
imported-edge-reading-list = ລາຍການອ່ານ (ຈາກ Edge)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = ຕົວເລືອກອິນເຕີເນັດ
    .value = ຕົວເລືອກອິນເຕີເນັດ
browser-data-edge-1 =
    .label = ການຕັ້ງຄ່າ
    .value = ການຕັ້ງຄ່າ
browser-data-safari-1 =
    .label = ການຕັ້ງຄ່າ
    .value = ການຕັ້ງຄ່າ
browser-data-chrome-1 =
    .label = ການຕັ້ງຄ່າ
    .value = ການຕັ້ງຄ່າ
browser-data-canary-1 =
    .label = ການຕັ້ງຄ່າ
    .value = ການຕັ້ງຄ່າ
browser-data-360se-1 =
    .label = ການຕັ້ງຄ່າ
    .value = ການຕັ້ງຄ່າ
browser-data-ie-2 =
    .label = ຄຸກກີ້
    .value = ຄຸກກີ້
browser-data-edge-2 =
    .label = ຄຸກກີ້
    .value = ຄຸກກີ້
browser-data-safari-2 =
    .label = ຄຸກກີ້
    .value = ຄຸກກີ້
browser-data-chrome-2 =
    .label = ຄຸກກີ້
    .value = ຄຸກກີ້
browser-data-canary-2 =
    .label = ຄຸກກີ້
    .value = ຄຸກກີ້
browser-data-firefox-2 =
    .label = ຄຸກກີ້
    .value = ຄຸກກີ້
browser-data-360se-2 =
    .label = ຄຸກກີ້
    .value = ຄຸກກີ້
browser-data-ie-4 =
    .label = ປະຫວັດການທ່ອງເວັບ
    .value = ປະຫວັດການທ່ອງເວັບ
browser-data-edge-4 =
    .label = ປະຫວັດການທ່ອງເວັບ
    .value = ປະຫວັດການທ່ອງເວັບ
browser-data-safari-4 =
    .label = ປະຫວັດການທ່ອງເວັບ
    .value = ປະຫວັດການທ່ອງເວັບ
browser-data-chrome-4 =
    .label = ປະຫວັດການທ່ອງເວັບ
    .value = ປະຫວັດການທ່ອງເວັບ
browser-data-canary-4 =
    .label = ປະຫວັດການທ່ອງເວັບ
    .value = ປະຫວັດການທ່ອງເວັບ
browser-data-firefox-history-and-bookmarks-4 =
    .label = ປະຫວັດການທ່ອງເວັບ ແລະ ບຸກມາກ
    .value = ປະຫວັດການທ່ອງເວັບ ແລະ ບຸກມາກ
browser-data-360se-4 =
    .label = ປະຫວັດການທ່ອງເວັບ
    .value = ປະຫວັດການທ່ອງເວັບ
browser-data-ie-8 =
    .label = ປະຫວັດແບບຟອມທີ່ບັນທຶກໄວ້
    .value = ປະຫວັດແບບຟອມທີ່ບັນທຶກໄວ້
browser-data-edge-8 =
    .label = ປະຫວັດແບບຟອມທີ່ບັນທຶກໄວ້
    .value = ປະຫວັດແບບຟອມທີ່ບັນທຶກໄວ້
browser-data-safari-8 =
    .label = ປະຫວັດແບບຟອມທີ່ບັນທຶກໄວ້
    .value = ປະຫວັດແບບຟອມທີ່ບັນທຶກໄວ້
browser-data-chrome-8 =
    .label = ປະຫວັດແບບຟອມທີ່ບັນທຶກໄວ້
    .value = ປະຫວັດແບບຟອມທີ່ບັນທຶກໄວ້
browser-data-canary-8 =
    .label = ປະຫວັດແບບຟອມທີ່ບັນທຶກໄວ້
    .value = ປະຫວັດແບບຟອມທີ່ບັນທຶກໄວ້
browser-data-firefox-8 =
    .label = ປະຫວັດແບບຟອມທີ່ບັນທຶກໄວ້
    .value = ປະຫວັດແບບຟອມທີ່ບັນທຶກໄວ້
browser-data-360se-8 =
    .label = ປະຫວັດແບບຟອມທີ່ບັນທຶກໄວ້
    .value = ປະຫວັດແບບຟອມທີ່ບັນທຶກໄວ້
browser-data-ie-16 =
    .label = ລະຫັດຜ່ານທີ່ບັນທຶກໄວ້
    .value = ລະຫັດຜ່ານທີ່ບັນທຶກໄວ້
browser-data-edge-16 =
    .label = ລະຫັດຜ່ານທີ່ບັນທຶກໄວ້
    .value = ລະຫັດຜ່ານທີ່ບັນທຶກໄວ້
browser-data-safari-16 =
    .label = ລະຫັດຜ່ານທີ່ບັນທຶກໄວ້
    .value = ລະຫັດຜ່ານທີ່ບັນທຶກໄວ້
browser-data-chrome-16 =
    .label = ລະຫັດຜ່ານທີ່ບັນທຶກໄວ້
    .value = ລະຫັດຜ່ານທີ່ບັນທຶກໄວ້
browser-data-canary-16 =
    .label = ລະຫັດຜ່ານທີ່ບັນທຶກໄວ້
    .value = ລະຫັດຜ່ານທີ່ບັນທຶກໄວ້
browser-data-firefox-16 =
    .label = ລະຫັດຜ່ານທີ່ບັນທຶກໄວ້
    .value = ລະຫັດຜ່ານທີ່ບັນທຶກໄວ້
browser-data-360se-16 =
    .label = ລະຫັດຜ່ານທີ່ບັນທຶກໄວ້
    .value = ລະຫັດຜ່ານທີ່ບັນທຶກໄວ້
browser-data-ie-32 =
    .label = ລາຍການທີ່ມັກ
    .value = ລາຍການທີ່ມັກ
browser-data-edge-32 =
    .label = ລາຍການທີ່ມັກ
    .value = ລາຍການທີ່ມັກ
browser-data-safari-32 =
    .label = ບຸກມາກ
    .value = ບຸກມາກ
browser-data-chrome-32 =
    .label = ບຸກມາກ
    .value = ບຸກມາກ
browser-data-canary-32 =
    .label = ບຸກມາກ
    .value = ບຸກມາກ
browser-data-360se-32 =
    .label = ບຸກມາກ
    .value = ບຸກມາກ
browser-data-ie-64 =
    .label = ຂໍ້ມູນອື່ນໆ
    .value = ຂໍ້ມູນອື່ນໆ
browser-data-edge-64 =
    .label = ຂໍ້ມູນອື່ນໆ
    .value = ຂໍ້ມູນອື່ນໆ
browser-data-safari-64 =
    .label = ຂໍ້ມູນອື່ນໆ
    .value = ຂໍ້ມູນອື່ນໆ
browser-data-chrome-64 =
    .label = ຂໍ້ມູນອື່ນໆ
    .value = ຂໍ້ມູນອື່ນໆ
browser-data-canary-64 =
    .label = ຂໍ້ມູນອື່ນໆ
    .value = ຂໍ້ມູນອື່ນໆ
browser-data-firefox-other-64 =
    .label = ຂໍ້ມູນອື່ນໆ
    .value = ຂໍ້ມູນອື່ນໆ
browser-data-360se-64 =
    .label = ຂໍ້ມູນອື່ນໆ
    .value = ຂໍ້ມູນອື່ນໆ
browser-data-firefox-128 =
    .label = ວີນໂດ ແລະ ແທັບ
    .value = ວີນໂດ ແລະ ແທັບ
