# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


# DO NOT ADD THINGS OTHER THAN ERROR MESSAGES HERE.
# This file gets parsed into a JS dictionary of all known error message ids in
# gen_aboutneterror_codes.py . If we end up needing fluent attributes or
# refactoring them in some way, the script will need updating.

# Variables:
# $error (string) - NSS error code string that specifies type of cert error. e.g. unknown issuer, invalid cert, etc.
cert-error-code-prefix = ລະຫັດຂໍ້ຜິດພາດ: { $error }
psmerr-ssl-disabled = ບໍ່ສາມາດເຊື່ອມຕໍ່ໄດ້ຢ່າງປອດໄພ ເພາະວ່າໂປຣໂຕຄໍ SSL ຖືກປິດໃຊ້ງານ.
psmerr-ssl2-disabled = ບໍ່​ສາ​ມາດ​ເຊື່ອມ​ຕໍ່​ໄດ້​ຢ່າງ​ປອດ​ໄພ​ເນື່ອງ​ຈາກ​ວ່າ​ເວັບ​ໄຊ​ໄດ້​ໃຊ້​ສະ​ບັບ​ເກົ່າ​, ບໍ່​ປອດ​ໄພ​ຂອງ SSL protocol​.
ssl-error-export-only-server = ບໍ່ສາມາດຕິດຕໍ່ສື່ສານຢ່າງປອດໄພໄດ້. Peer ບໍ່ຮອງຮັບການເຂົ້າລະຫັດລະດັບສູງ.
ssl-error-us-only-server = ບໍ່ສາມາດຕິດຕໍ່ສື່ສານຢ່າງປອດໄພໄດ້. Peer ຕ້ອງການການເຂົ້າລະຫັດລະດັບສູງທີ່ບໍ່ຮອງຮັບ.
ssl-error-no-cypher-overlap = ບໍ່​ສາ​ມາດ​ຕິດ​ຕໍ່​ພົວ​ພັນ​ຢ່າງ​ປອດ​ໄພ​ກັບ​ຫມູ່​ເພື່ອນ​: ບໍ່​ມີ​ວິ​ທີ​ການ​ເຂົ້າ​ລະ​ຫັດ​ທົ່ວ​ໄປ​.
ssl-error-no-certificate = ບໍ່ສາມາດຊອກຫາໃບຢັ້ງຢືນ ຫຼືກະແຈທີ່ຈຳເປັນສຳລັບການພິສູດຢືນຢັນໄດ້.
ssl-error-bad-certificate = ບໍ່​ສາ​ມາດ​ຕິດ​ຕໍ່​ພົວ​ພັນ​ຢ່າງ​ປອດ​ໄພ​ກັບ​ຫມູ່​ເພື່ອນ​: ໃບ​ຢັ້ງ​ຢືນ​ຂອງ​ຫມູ່​ເພື່ອນ​ໄດ້​ຖືກ​ປະ​ຕິ​ເສດ​.
ssl-error-bad-client = ເຊີບເວີໄດ້ພົບກັບຂໍ້ມູນທີ່ບໍ່ດີຈາກລູກຄ້າ.
ssl-error-bad-server = ລູກຄ້າໄດ້ພົບກັບຂໍ້ມູນທີ່ບໍ່ດີຈາກເຄື່ອງແມ່ຂ່າຍ.
ssl-error-unsupported-certificate-type = ປະເພດໃບຢັ້ງຢືນທີ່ບໍ່ຮອງຮັບ.
ssl-error-unsupported-version = ຄູ່​ຮ່ວມ​ງານ​ການ​ນໍາ​ໃຊ້​ສະ​ບັບ​ທີ່​ບໍ່​ຮອງ​ຮັບ​ຂອງ​ອະ​ນຸ​ສັນ​ຍາ​ຄວາມ​ປອດ​ໄພ​.
ssl-error-wrong-certificate = ການກວດສອບລູກຄ້າລົ້ມເຫລວ: ລະຫັດສ່ວນຕົວໃນຖານຂໍ້ມູນລະຫັດບໍ່ກົງກັບລະຫັດສາທາລະນະໃນຖານຂໍ້ມູນໃບຢັ້ງຢືນ.
ssl-error-bad-cert-domain = ບໍ່ສາມາດຕິດຕໍ່ສື່ສານຢ່າງປອດໄພກັບເພື່ອນມິດ: ຊື່ໂດເມນທີ່ຮ້ອງຂໍບໍ່ກົງກັບໃບຢັ້ງຢືນຂອງເຊີບເວີ.
ssl-error-post-warning = ລະຫັດຄວາມຜິດພາດ SSL ທີ່ບໍ່ຮູ້ຈັກ.
ssl-error-ssl2-disabled = Peer ຮອງຮັບ SSL ລຸ້ນ 2 ເທົ່ານັ້ນ, ເຊິ່ງຖືກປິດໃຊ້ງານຢູ່ໃນເຄື່ອງ.
ssl-error-bad-mac-read = SSL ໄດ້ຮັບບັນທຶກທີ່ມີລະຫັດຢືນຢັນຂໍ້ຄວາມທີ່ບໍ່ຖືກຕ້ອງ.
ssl-error-bad-mac-alert = SSL peer ລາຍງານລະຫັດຢືນຢັນຂໍ້ຄວາມບໍ່ຖືກຕ້ອງ.
ssl-error-bad-cert-alert = SSL peer ບໍ່ສາມາດກວດສອບໃບຮັບຮອງຂອງທ່ານໄດ້.
ssl-error-revoked-cert-alert = ມິດສະຫາຍ SSL ປະຕິເສດໃບຮັບຮອງຂອງທ່ານເມື່ອຖືກຖອນຄືນ.
ssl-error-expired-cert-alert = SSL peer ປະຕິເສດໃບຮັບຮອງຂອງທ່ານທີ່ໝົດອາຍຸແລ້ວ.
ssl-error-ssl-disabled = ບໍ່ສາມາດເຊື່ອມຕໍ່ໄດ້: SSL ຖືກປິດໃຊ້ງານ.
ssl-error-fortezza-pqg = ບໍ່ສາມາດເຊື່ອມຕໍ່ໄດ້: SSL peer ຢູ່ໃນໂດເມນ FORTEZZA ອື່ນ.
ssl-error-unknown-cipher-suite = ຊຸດລະຫັດລັບ SSL ທີ່ບໍ່ຮູ້ຈັກໄດ້ຖືກຮ້ອງຂໍ.
ssl-error-no-ciphers-supported = ບໍ່ມີຊຸດລະຫັດລັບ ແລະເປີດໃຊ້ຢູ່ໃນໂປຣແກຣມນີ້.
ssl-error-bad-block-padding = SSL ໄດ້ຮັບບັນທຶກທີ່ມີແຜ່ນປິດກັ້ນທີ່ບໍ່ດີ.
ssl-error-rx-malformed-hello-done = SSL ໄດ້ຮັບຂໍ້ຄວາມການຈັບມືຂອງເຊີບເວີ Hello Done ທີ່ບໍ່ຖືກຕ້ອງ.
ssl-error-rx-unexpected-hello-request = SSL ໄດ້ຮັບຂໍ້ຄວາມຈັບມື Hello Request ທີ່ບໍ່ຄາດຄິດ.
ssl-error-rx-unexpected-server-hello = SSL ໄດ້ຮັບຂໍ້ຄວາມສະບາຍດີເຊີບເວີທີ່ບໍ່ໄດ້ຄາດຫວັງ.
ssl-error-rx-unexpected-certificate = SSL ໄດ້ຮັບຂໍ້ຄວາມຈັບມືໃບຮັບຮອງທີ່ບໍ່ຄາດຄິດ.
ssl-error-client-key-exchange-failure = ຄວາມລົ້ມເຫຼວທີ່ບໍ່ໄດ້ລະບຸໃນຂະນະທີ່ປະມວນຜົນ SSL Client Key Exchange handshake.
ssl-error-socket-write-failure = ຄວາມພະຍາຍາມຂຽນຂໍ້ມູນທີ່ເຂົ້າລະຫັດໄວ້ໃສ່ຊັອກເກັດທີ່ຢູ່ເບື້ອງຕົ້ນລົ້ມເຫລວ.
ssl-error-md5-digest-failure = ຟັງຊັນການຍ່ອຍ MD5 ລົ້ມເຫລວ.
ssl-error-sha-digest-failure = ຟັງຊັນການຍ່ອຍ SHA-1 ລົ້ມເຫລວ.
ssl-error-mac-computation-failure = ການຄິດໄລ່ MAC ລົ້ມເຫລວ.
ssl-error-sym-key-context-failure = ລົ້ມເຫລວໃນການສ້າງເນື້ອຫາ Symmetric Key.
ssl-error-sym-key-unwrap-failure = ລົ້ມເຫລວໃນການຖອດລະຫັດ Symmetric ໃນຂໍ້ຄວາມ Exchange Key ລູກຄ້າ.
ssl-error-iv-param-failure = ລະຫັດ PKCS11 ລົ້ມເຫລວໃນການແປ IV ເປັນ param.
ssl-error-init-cipher-suite-failure = ລົ້ມເຫລວໃນການເລີ່ມຕົ້ນຊຸດລະຫັດລັບທີ່ເລືອກ.
ssl-error-session-key-gen-failure = ລູກຄ້າລົ້ມເຫລວໃນການສ້າງລະຫັດເຊດຊັນສໍາລັບເຊດຊັນ SSL.
ssl-error-no-server-key-for-alg = ເຊີບເວີບໍ່ມີກະແຈສຳລັບການພະຍາຍາມແລກປ່ຽນລະຫັດ.
ssl-error-no-compression-overlap = ບໍ່​ສາ​ມາດ​ຕິດ​ຕໍ່​ສື່​ສານ​ຢ່າງ​ປອດ​ໄພ​ກັບ​ຫມູ່​ເພື່ອນ​: ບໍ່​ມີ​ວິ​ທີ​ການ​ບີບ​ອັດ​ທົ່ວ​ໄປ​.
ssl-error-no-trusted-ssl-client-ca = ບໍ່ມີສິດອຳນາດຂອງໃບຮັບຮອງທີ່ເຊື່ອຖືໄດ້ສຳລັບການພິສູດຢືນຢັນລູກຂ່າຍ SSL.
ssl-error-decryption-failed-alert = Peer ບໍ່ສາມາດຖອດລະຫັດບັນທຶກ SSL ທີ່ມັນໄດ້ຮັບ.
ssl-error-record-overflow-alert = Peer ໄດ້ຮັບບັນທຶກ SSL ທີ່ຍາວກວ່າທີ່ອະນຸຍາດ.
ssl-error-internal-error-alert = Peer ລາຍງານວ່າມັນປະສົບກັບຄວາມຜິດພາດພາຍໃນ.
ssl-error-user-canceled-alert = ຜູ້ໃຊ້ທີ່ຈະຈັບຄູ່ໄດ້ຍົກເລີກການຈັບມື.
ssl-error-bad-cert-hash-value-alert = SSL peer ລາຍງານຄ່າໃບຮັບຮອງທີ່ບໍ່ດີ.
ssl-error-renegotiation-not-allowed = ບໍ່ອະນຸຍາດໃຫ້ມີການເຈລະຈາຄືນໃໝ່ຢູ່ໃນເຕົ້າຮັບ SSL ນີ້.
ssl-error-unsafe-negotiation = ອີກຝັ່ງພະຍາຍາມຈັບມືແບບເກົ່າ (ທີ່ອາດຈະມີຄວາມສ່ຽງ).
ssl-error-rx-unexpected-uncompressed-record = SSL ໄດ້ຮັບບັນທຶກການບີບອັດທີ່ບໍ່ຄາດຄິດ.
ssl-error-invalid-version-range = ຊ່ວງລຸ້ນ SSL ບໍ່ຖືກຕ້ອງ.
ssl-error-digest-failure = ຟັງຊັນຍ່ອຍບໍ່ສຳເລັດ.
ssl-error-rx-short-dtls-read = ບໍ່ມີຫ້ອງພຽງພໍໃນ buffer ສໍາລັບບັນທຶກ DTLS.
sec-error-library-failure = ຄວາມລົ້ມເຫຼວຂອງຫ້ອງສະຫມຸດຄວາມປອດໄພ.
sec-error-invalid-args = ຫ້ອງສະໝຸດຄວາມປອດໄພ: arguments ບໍ່ຖືກຕ້ອງ.
sec-error-invalid-algorithm = ຫ້ອງສະໝຸດຄວາມປອດໄພ: ອັນກໍລິທືມບໍ່ຖືກຕ້ອງ.
sec-error-invalid-ava = ຫ້ອງສະໝຸດຄວາມປອດໄພ: AVA ບໍ່ຖືກຕ້ອງ.
sec-error-invalid-time = ສະຕຣິງເວລາຈັດຮູບແບບບໍ່ຖືກຕ້ອງ.
sec-error-bad-der = ຫ້ອງສະໝຸດຄວາມປອດໄພ: ຮູບແບບຂໍ້ຄວາມທີ່ເຂົ້າລະຫັດ DER ບໍ່ຖືກຕ້ອງ.
sec-error-bad-signature = ໃບຮັບຮອງຂອງເພື່ອນມີລາຍເຊັນບໍ່ຖືກຕ້ອງ.
sec-error-expired-certificate = ໃບຢັ້ງຢືນຂອງ Peer ໄດ້ຫມົດອາຍຸ.
sec-error-bad-key = ກະແຈສາທາລະນະຂອງ Peer ບໍ່ຖືກຕ້ອງ.
sec-error-bad-password = ລະຫັດຜ່ານຄວາມປອດໄພທີ່ໃສ່ນັ້ນບໍ່ຖືກຕ້ອງ.
sec-error-retry-password = ລະຫັດຜ່ານໃໝ່ໃສ່ຜິດ. ກະລຸນາລອງອີກຄັ້ງ.
sec-error-no-nodelock = ຫ້ອງສະຫມຸດຄວາມປອດໄພ: ບໍ່ມີ nodelock.
sec-error-bad-database = ຫ້ອງສະຫມຸດຄວາມປອດໄພ: ຖານຂໍ້ມູນທີ່ບໍ່ດີ.
sec-error-no-memory = ຫ້ອງສະໝຸດຄວາມປອດໄພ: ການຈັດສັນຄວາມຈຳລົ້ມເຫລວ.
sec-error-duplicate-cert = ໃບຢັ້ງຢືນມີຢູ່ໃນຖານຂໍ້ມູນຂອງເຈົ້າແລ້ວ.
sec-error-adding-cert = ເກີດຄວາມຜິດພາດໃນການເພີ່ມໃບຢັ້ງຢືນໃສ່ຖານຂໍ້ມູນ.
sec-error-cert-valid = ໃບຮັບຮອງນີ້ແມ່ນຖືກຕ້ອງ.
sec-error-cert-not-valid = ໃບຮັບຮອງນີ້ບໍ່ຖືກຕ້ອງ.
sec-error-cert-no-response = ຫ້ອງສະໝຸດໃບຮັບຮອງ: ບໍ່ມີການຕອບສະໜອງ
sec-error-crl-invalid = CRL ໃໝ່ມີຮູບແບບທີ່ບໍ່ຖືກຕ້ອງ.
sec-error-extension-value-invalid = ຄ່າການຂະຫຍາຍໃບຮັບຮອງບໍ່ຖືກຕ້ອງ.
sec-error-extension-not-found = ບໍ່ພົບສ່ວນຂະຫຍາຍໃບຢັ້ງຢືນ.
sec-error-ca-cert-invalid = ໃບຮັບຮອງຜູ້ອອກບໍ່ຖືກຕ້ອງ.
sec-error-path-len-constraint-invalid = ຂໍ້ຈຳກັດຄວາມຍາວຂອງເສັ້ນທາງໃບຢັ້ງຢືນບໍ່ຖືກຕ້ອງ.
sec-error-cert-usages-invalid = ຊ່ອງຂໍ້ມູນການນຳໃຊ້ໃບຮັບຮອງບໍ່ຖືກຕ້ອງ.
sec-internal-only = ** ໂມດູນພາຍໃນເທົ່ານັ້ນ **
sec-error-invalid-key = ກະແຈບໍ່ຮອງຮັບການດຳເນີນການທີ່ຮ້ອງຂໍ.
sec-error-unknown-critical-extension = ໃບຢັ້ງຢືນປະກອບມີສ່ວນຂະຫຍາຍທີ່ສໍາຄັນທີ່ບໍ່ຮູ້ຈັກ.
sec-error-no-recipient-certs-query = ບໍ່ໄດ້ເຂົ້າລະຫັດ: ທ່ານບໍ່ມີໃບຢັ້ງຢືນສໍາລັບແຕ່ລະຜູ້ຮັບ.
sec-error-not-a-recipient = ບໍ່​ສາ​ມາດ​ຖອດ​ລະ​ຫັດ: ທ່ານ​ບໍ່​ແມ່ນ​ຜູ້​ຮັບ, ຫຼື​ໃບ​ຢັ້ງ​ຢືນ​ການ​ທີ່​ກົງ​ກັນ​ແລະ​ກະ​ແຈ​ສ່ວນ​ຕົວ​ບໍ່​ພົບ.
sec-error-pkcs7-keyalg-mismatch = ບໍ່ສາມາດຖອດລະຫັດໄດ້: ຂັ້ນຕອນການເຂົ້າລະຫັດລະຫັດບໍ່ກົງກັບໃບຢັ້ງຢືນຂອງທ່ານ.
sec-error-unsupported-keyalg = ສູດການຄິດໄລ່ຫຼັກທີ່ບໍ່ຮອງຮັບ ຫຼືບໍ່ຮູ້.
xp-sec-fortezza-no-card = ບໍ່ພົບບັດ Fortezza
xp-sec-fortezza-none-selected = ບໍ່ໄດ້ເລືອກບັດ Fortezza
xp-sec-fortezza-more-info = ກະລຸນາເລືອກບຸກຄະລິກກະພາບເພື່ອຮັບຂໍ້ມູນເພີ່ມເຕີມ
xp-sec-fortezza-person-not-found = ບໍ່ພົບບຸກຄະລິກກະພາບ
xp-sec-fortezza-no-more-info = ບໍ່ມີຂໍ້ມູນເພີ່ມເຕີມກ່ຽວກັບບຸກຄະລິກກະພາບນັ້ນ
xp-sec-fortezza-bad-pin = Pin ບໍ່ຖືກຕ້ອງ
xp-sec-fortezza-person-error = ບໍ່ສາມາດເລີ່ມຕົ້ນສ່ວນບຸກຄົນ Fortezza ໄດ້.
sec-error-revoked-key = ກະແຈສຳລັບໃບຢັ້ງຢືນຂອງເວັບໄຊນີ້ໄດ້ຖືກຖອນຄືນແລ້ວ.
sec-error-krl-invalid = KRL ໃໝ່ມີຮູບແບບທີ່ບໍ່ຖືກຕ້ອງ.
sec-error-need-random = ຫ້ອງສະຫມຸດຄວາມປອດໄພ: ຕ້ອງການຂໍ້ມູນແບບສຸ່ມ.
sec-error-no-module = ຫ້ອງສະຫມຸດຄວາມປອດໄພ: ບໍ່ມີໂມດູນຄວາມປອດໄພສາມາດປະຕິບັດການຮ້ອງຂໍ.
sec-error-no-token = ບັດຄວາມປອດໄພ ຫຼືໂທເຄັນບໍ່ມີຢູ່, ຕ້ອງໄດ້ຮັບການເລີ່ມຕົ້ນ, ຫຼືຖືກຖອດອອກ.
sec-error-no-slot-selected = ບໍ່ໄດ້ເລືອກຊ່ອງ ຫຼືໂທເຄັນ.
sec-error-cert-nickname-collision = ໃບຢັ້ງຢືນທີ່ມີຊື່ຫຼິ້ນດຽວກັນມີຢູ່ແລ້ວ.
sec-error-safe-not-created = ຜິດພາດໃນຂະນະທີ່ການສ້າງວັດຖຸທີ່ປອດໄພ
sec-error-baggage-not-created = ຜິດພາດໃນຂະນະທີ່ສ້າງວັດຖຸກະເປົ໋າ
xp-java-remove-principal-error = ບໍ່ສາມາດເອົາເງິນຕົ້ນອອກໄດ້
xp-java-delete-privilege-error = ບໍ່ສາມາດລຶບສິດທິພິເສດໄດ້
xp-java-cert-not-exists-error = Principal ບໍ່ມີໃບຮັບຮອງ
sec-error-bad-export-algorithm = ບໍ່ອະນຸຍາດໃຫ້ໃຊ້ສູດການຄິດໄລ່ທີ່ຕ້ອງການ.
sec-error-exporting-certificates = ເກີດຄວາມຜິດພາດໃນການພະຍາຍາມສົ່ງອອກໃບຮັບຮອງ.
sec-error-importing-certificates = ເກີດຄວາມຜິດພາດໃນການພະຍາຍາມນຳເຂົ້າໃບຮັບຮອງ.
sec-error-pkcs12-corrupt-pfx-structure = ບໍ່ສາມາດນໍາເຂົ້າໄດ້. ໂຄງສ້າງໄຟລ໌ເສຍຫາຍ.
sec-error-pkcs12-unsupported-pbe-algorithm = ບໍ່ສາມາດນໍາເຂົ້າໄດ້. ບໍ່ຮອງຮັບລະບົບການເຂົ້າລະຫັດ.
sec-error-pkcs12-unsupported-version = ບໍ່ສາມາດນໍາເຂົ້າໄດ້. ບໍ່ຮອງຮັບເວີຊັນໄຟລ໌.
sec-error-pkcs12-privacy-password-incorrect = ບໍ່ສາມາດນໍາເຂົ້າໄດ້. ລະຫັດຜ່ານຄວາມເປັນສ່ວນຕົວບໍ່ຖືກຕ້ອງ.
sec-error-pkcs12-cert-collision = ບໍ່ສາມາດນໍາເຂົ້າໄດ້. ຊື່ຫຼິ້ນດຽວກັນມີຢູ່ໃນຖານຂໍ້ມູນແລ້ວ.
sec-error-user-cancelled = ຜູ້ໃຊ້ກົດຍົກເລີກ.
sec-error-pkcs12-duplicate-data = ບໍ່ໄດ້ນໍາເຂົ້າ, ມີຢູ່ໃນຖານຂໍ້ມູນແລ້ວ.
sec-error-message-send-aborted = ຂໍ້ຄວາມບໍ່ໄດ້ຖືກສົ່ງໄປ.
sec-error-inadequate-key-usage = ການນຳໃຊ້ກະແຈໃບຮັບຮອງບໍ່ພຽງພໍກັບຄວາມພະຍາຍາມ.
sec-error-inadequate-cert-type = ປະເພດໃບຢັ້ງຢືນບໍ່ໄດ້ຮັບການອະນຸມັດສໍາລັບຄໍາຮ້ອງສະຫມັກ.
sec-error-cert-addr-mismatch = ທີ່ຢູ່ໃນການເຊັນໃບຢັ້ງຢືນບໍ່ກົງກັບທີ່ຢູ່ໃນສ່ວນຫົວຂໍ້ຄວາມ.
sec-error-pkcs12-unable-to-import-key = ບໍ່ສາມາດນໍາເຂົ້າໄດ້. ເກີດຄວາມຜິດພາດໃນການພະຍາຍາມນຳເຂົ້າກະແຈສ່ວນຕົວ.
sec-error-pkcs12-importing-cert-chain = ບໍ່ສາມາດນໍາເຂົ້າໄດ້. ເກີດຄວາມຜິດພາດໃນການພະຍາຍາມນຳເຂົ້າລະບົບຕ່ອງໂສ້ໃບຮັບຮອງ.
sec-error-pkcs12-unable-to-locate-object-by-name = ບໍ່ສາມາດສົ່ງອອກໄດ້. ບໍ່ສາມາດຊອກຫາໃບຢັ້ງຢືນ ຫຼືກະແຈດ້ວຍຊື່ຫຼິ້ນໄດ້.
sec-error-invalid-password = ລະຫັດຜ່ານທີ່ໃສ່ບໍ່ຖືກຕ້ອງ. ກະລຸນາເລືອກອັນອື່ນ.
sec-error-bad-nickname = ຊື່ຫຼິ້ນໃບຮັບຮອງຖືກໃຊ້ແລ້ວ.
sec-error-js-invalid-module-name = ຊື່ໂມດູນບໍ່ຖືກຕ້ອງ.
sec-error-js-invalid-dll = ເສັ້ນທາງ/ຊື່ໄຟລ໌ຂອງໂມດູນບໍ່ຖືກຕ້ອງ
sec-error-js-add-mod-failure = ບໍ່ສາມາດເພີ່ມໂມດູນໄດ້
sec-error-js-del-mod-failure = ບໍ່ສາມາດລຶບໂມດູນໄດ້
sec-error-unknown-cert = ບໍ່ພົບໃບຢັ້ງຢືນທີ່ຮ້ອງຂໍ.
sec-error-unknown-signer = ບໍ່ພົບໃບຮັບຮອງຂອງຜູ້ລົງນາມ.
sec-error-ocsp-not-enabled = ທ່ານຕ້ອງເປີດໃຊ້ OCSP ກ່ອນທີ່ຈະດໍາເນີນການນີ້.
sec-error-unsupported-message-type = ປະເພດຂໍ້ຄວາມ CMS ຫຼື PKCS #7 ບໍ່ຮອງຮັບ.
sec-error-bad-template = ບໍ່ສາມາດຖອດລະຫັດຂໍ້ມູນ ASN.1 ໄດ້. ແມ່ແບບທີ່ລະບຸບໍ່ຖືກຕ້ອງ.
sec-error-crl-not-found = ບໍ່ພົບ CRL ທີ່ກົງກັນ.
sec-error-reused-issuer-and-serial = ທ່ານກໍາລັງພະຍາຍາມນໍາເຂົ້າໃບຢັ້ງຢືນກັບຜູ້ອອກ / serial ດຽວກັນກັບໃບຢັ້ງຢືນທີ່ມີຢູ່ແລ້ວ, ແຕ່ນັ້ນບໍ່ແມ່ນໃບຢັ້ງຢືນດຽວກັນ.
sec-error-busy = NSS ບໍ່ສາມາດປິດໄດ້. ວັດຖຸຍັງຖືກນຳໃຊ້ຢູ່.
sec-error-extra-input = ຂໍ້ຄວາມທີ່ເຂົ້າລະຫັດ DER ມີຂໍ້ມູນທີ່ບໍ່ໄດ້ໃຊ້ເປັນພິເສດ.
sec-error-unsupported-elliptic-curve = ບໍ່ຮອງຮັບເສັ້ນໂຄ້ງຮູບຮີ.
sec-error-unsupported-ec-point-form = ຮູບແບບຈຸດໂຄ້ງຮູບສ້ວຍທີ່ບໍ່ຮອງຮັບ.
sec-error-unrecognized-oid = ຕົວລະບຸວັດຖຸທີ່ບໍ່ຮູ້ຈັກ.
sec-error-ocsp-invalid-signing-cert = ໃບຢັ້ງຢືນການເຊັນ OCSP ບໍ່ຖືກຕ້ອງໃນການຕອບສະໜອງ OCSP.
sec-error-revoked-certificate-crl = ໃບ​ຢັ້ງ​ຢືນ​ຖືກ​ຖອນ​ຄືນ​ໃນ​ບັນ​ຊີ​ລາຍ​ການ​ຖອນ​ໃບ​ຢັ້ງ​ຢືນ​ຂອງ​ຜູ້​ອອກ​ໃບ​ຢັ້ງ​ຢືນ.
sec-error-unknown-object-type = ລະບຸປະເພດວັດຖຸທີ່ບໍ່ຮູ້ຈັກ.
sec-error-incompatible-pkcs11 = ໄດເວີ PKCS #11 ລະເມີດສະເປັກໃນແບບທີ່ບໍ່ເຂົ້າກັນໄດ້.
sec-error-no-event = ບໍ່ມີເຫດການສະລັອດຕິງໃຫມ່ທີ່ມີຢູ່ໃນເວລານີ້.
sec-error-crl-already-exists = CRL ມີຢູ່ແລ້ວ.
sec-error-not-initialized = NSS ບໍ່ໄດ້ຖືກເລີ່ມຕົ້ນ.
sec-error-out-of-search-limits = ການຄົ້ນຫາການຢັ້ງຢືນແມ່ນເກີນຂອບເຂດຈໍາກັດການຊອກຫາ
sec-error-invalid-policy-mapping = ແຜນທີ່ນະໂຍບາຍປະກອບມີນະໂຍບາຍໃດໆ
sec-error-policy-validation-failed = ລະບົບຕ່ອງໂສ້ Cert ລົ້ມເຫລວໃນການກວດສອບນະໂຍບາຍ
sec-error-bad-http-response = ເຊີບເວີສົ່ງຄືນການຕອບ HTTP ທີ່ບໍ່ດີ
sec-error-bad-ldap-response = ເຊີບເວີສົ່ງຄືນການຕອບສະໜອງ LDAP ທີ່ບໍ່ດີ
sec-error-failed-to-encode-data = ລົ້ມເຫລວໃນການເຂົ້າລະຫັດຂໍ້ມູນດ້ວຍຕົວເຂົ້າລະຫັດ ASN1
sec-error-bad-info-access-location = ຂໍ້ມູນທີ່ບໍ່ດີເຂົ້າເຖິງສະຖານທີ່ຢູ່ໃນການຂະຫຍາຍໃບຢັ້ງຢືນ
sec-error-libpkix-internal = Libpkix ຄວາມຜິດພາດພາຍໃນທີ່ເກີດຂື້ນໃນຊ່ວງການກວດສອບໃບຮັບຮອງ.
sec-error-bad-info-access-method = ວິທີການເຂົ້າເຖິງຂໍ້ມູນທີ່ບໍ່ຮູ້ຈັກໃນການຂະຫຍາຍໃບຢັ້ງຢືນ.
sec-error-crl-import-failed = ເກີດຄວາມຜິດພາດໃນການພະຍາຍາມນໍາເຂົ້າ CRL.
sec-error-expired-password = ລະຫັດຜ່ານໝົດອາຍຸແລ້ວ.
sec-error-locked-password = ລະຫັດຜ່ານຖືກລັອກ.
sec-error-unknown-pkcs11-error = ຄວາມຜິດພາດ PKCS #11 ທີ່ບໍ່ຮູ້ຈັກ.
sec-error-bad-crl-dp-url = URL ບໍ່ຖືກຕ້ອງ ຫຼື ບໍ່ຮອງຮັບໃນຊື່ຈຸດແຈກຢາຍ CRL.
sec-error-cert-signature-algorithm-disabled = ໃບຮັບຮອງໄດ້ຖືກເຊັນໂດຍໃຊ້ສູດການຄິດໄລ່ລາຍເຊັນທີ່ຖືກປິດໃຊ້ງານເພາະວ່າມັນບໍ່ປອດໄພ.
mozilla-pkix-error-key-pinning-failure = ເຊີບເວີໃຊ້ການປັກໝຸດຫຼັກ (HPKP) ແຕ່ບໍ່ມີລະບົບຕ່ອງໂສ້ໃບຢັ້ງຢືນທີ່ເຊື່ອຖືໄດ້ສາມາດສ້າງທີ່ກົງກັບ pinset ໄດ້. ການລະເມີດການປັກໝຸດຫຼັກບໍ່ສາມາດຖືກລົບລ້າງໄດ້.
mozilla-pkix-error-not-yet-valid-certificate = ເຊີບເວີໄດ້ນຳສະເໜີໃບຮັບຮອງທີ່ຍັງບໍ່ຖືກຕ້ອງ.
mozilla-pkix-error-not-yet-valid-issuer-certificate = ໃບຮັບຮອງທີ່ຍັງບໍ່ຖືກຕ້ອງຖືກໃຊ້ເພື່ອອອກໃບຢັ້ງຢືນຂອງເຊີບເວີ.
mozilla-pkix-error-signature-algorithm-mismatch = ສູດການຄິດໄລ່ລາຍເຊັນໃນຊ່ອງລາຍເຊັນຂອງໃບຢັ້ງຢືນບໍ່ກົງກັບສູດການຄິດໄລ່ໃນຊ່ອງລາຍເຊັນຂອງມັນ.
mozilla-pkix-error-ocsp-response-for-cert-missing = ຄໍາຕອບຂອງ OCSP ບໍ່ປະກອບມີສະຖານະສໍາລັບໃບຢັ້ງຢືນທີ່ກໍາລັງຖືກກວດສອບ.
mozilla-pkix-error-validity-too-long = ເຊີບເວີໄດ້ນຳສະເໜີໃບຮັບຮອງທີ່ໃຊ້ໄດ້ດົນເກີນໄປ.
mozilla-pkix-error-required-tls-feature-missing = ບໍ່ມີຄຸນສົມບັດ TLS ທີ່ຕ້ອງການ.
mozilla-pkix-error-empty-issuer-name = ເຊີບເວີໄດ້ນຳສະເໜີໃບຮັບຮອງທີ່ມີຊື່ທີ່ໂດດເດັ່ນຂອງຜູ້ອອກໃບປະກາດເປົ່າຫວ່າງ.
mozilla-pkix-error-additional-policy-constraint-failed = ຂໍ້ຈຳກັດດ້ານນະໂຍບາຍເພີ່ມເຕີມລົ້ມເຫລວເມື່ອກວດສອບໃບຢັ້ງຢືນນີ້.
mozilla-pkix-error-self-signed-cert = ໃບຢັ້ງຢືນບໍ່ເຊື່ອຖືໄດ້ເພາະມັນລົງນາມເອງ.
