# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Αποθήκευση
dialogTitleAddBookmark = Νέος σελιδοδείκτης
dialogTitleAddMulti = Νέοι σελιδοδείκτες
dialogTitleEdit = Ιδιότητες για «%S»
dialogTitleAddNewBookmark2 = Προσθήκη σελιδοδείκτη
dialogTitleEditBookmark = Επεξεργασία «%S»
dialogTitleEditBookmark2 = Επεξεργασία σελιδοδείκτη
dialogTitleAddBookmarkFolder = Προσθήκη φακέλου σελιδοδεικτών
dialogTitleEditBookmarkFolder = Επεξεργασία φακέλου σελιδοδεικτών
bookmarkAllTabsDefault = [Όνομα φακέλου]
newFolderDefault = Νέος φάκελος
newBookmarkDefault = Νέος σελιδοδείκτης
