# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Aşağıdaki maqsatlar içün “%S” itimat etilsinmi?
unnamedCA = Sertifika Yetkilisi (isimsiz)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Lütfen bu şeadetname yedegini şifrelemek içün qullanılğan sır-sözni kirsetiñiz:
# Page Info
pageInfo_NoEncryption = Bağlantı şifrelenmiyor
pageInfo_Privacy_None1 = İnternet saytı %S seyretkeniñiz saife içün şifrelemeni desteklemey.
pageInfo_Privacy_None2 = İnternette şifrelenmeden gönderilen bilgiler aktarım sırasında başkaları tarafından görülebilir.
pageInfo_Privacy_None4 = Seyrete olğanıñız saife İnternet üzerinden naqletilmezden evvel şifrelenmedi.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Bağlantı Şifrelendirilgen (%1$S, %2$S bit anahtarlar, %3$S)
pageInfo_BrokenEncryption = Qırıq Şifreleme (%1$S, %2$S bit anahtarlar, %3$S)
pageInfo_Privacy_Encrypted1 = Seyrete olğanıñız saife İnternet üzerinden naqletilmezden evvel şifrelendi.
pageInfo_Privacy_Encrypted2 = Şifreleme, bilgisayarlar arasında seyahat etken malümatnıñ salâhiyetsiz kişilerce körülmesini zorlaştırır. Ondan dolayı bu saifeniñ şebeke arqalı dolaşqanında er angi biri tarafından oqulğanı ğayrımuhtemeldir.
pageInfo_MixedContent = Bağlantıyı duruma göre şifreli kur
pageInfo_MixedContent2 = Seyrete olğanıñız saifeniñ qısımları, İnternet üzerinden naqletilmezden evvel şifrelenmegen edi.
pageInfo_WeakCipher = Bu ağ-saytına bağlantıñız zayıf şifreleme qullana ve hususiy degildir. Başqa kişiler malümatıñıznı körebilir yaki ağ-saytınıñ davranışını başqalaştırabilir.
pageInfo_CertificateTransparency_Compliant = Bu ağ-saytı Lehadetname Şeffaflığı siyasetine riayet ete.
# Token Manager
password_not_set = (ayarlı değil)
