# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Importálás varázsló
import-from =
    { PLATFORM() ->
        [windows] Beállítások, könyvjelzők, előzmények, jelszavak és egyéb adatok importálása a következő termékből:
       *[other] Beállítások, könyvjelzők, előzmények, jelszavak és egyéb adatok importálása a következő termékből:
    }
import-from-bookmarks = Könyvjelzők importálása
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-edge-legacy =
    .label = Microsoft Edge Legacy
    .accesskey = L
import-from-edge-beta =
    .label = Microsoft Edge béta
    .accesskey = d
import-from-nothing =
    .label = Ne importáljon semmit
    .accesskey = N
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chrome-beta =
    .label = Chrome béta
    .accesskey = b
import-from-chrome-dev =
    .label = Chrome fejlesztői
    .accesskey = f
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = x
import-from-360se =
    .label = 360 biztonságos böngésző
    .accesskey = 3
no-migration-sources = Nem található olyan program, amely könyvjelzőket, előzményeket vagy jelszóadatokat tartalmaz.
import-source =
    .label = Beállítások és adatok importálása
import-items-title =
    .label = Importálandó elemek
import-items-description = Válassza ki az importálni kívánt elemeket:
import-migrating-title =
    .label = Importálás…
import-migrating-description = A következő elemek importálása folyik…
import-select-profile-title =
    .label = Profil kiválasztása
import-select-profile-description = A következő profilokból lehet importálni:
import-done-title =
    .label = Importálás befejeződött
import-done-description = A következő elemek sikeresen importálva lettek:
import-close-source-browser = Ne feledje el bezárni a kiválasztott böngészőt a folytatás előtt.
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = { $source } helyről
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-edge-beta = Microsoft Edge béta
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chrome-beta = Google Chrome béta
source-name-chrome-dev = Google Chrome fejlesztői
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 biztonságos böngésző
imported-safari-reading-list = Olvasási lista (a Safariból)
imported-edge-reading-list = Olvasási lista (az Edge-ből)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Internet-beállítások
    .value = Internet-beállítások
browser-data-edge-1 =
    .label = Beállítások
    .value = Beállítások
browser-data-safari-1 =
    .label = Beállítások
    .value = Beállítások
browser-data-chrome-1 =
    .label = Beállítások
    .value = Beállítások
browser-data-canary-1 =
    .label = Beállítások
    .value = Beállítások
browser-data-360se-1 =
    .label = Beállítások
    .value = Beállítások
browser-data-ie-2 =
    .label = Sütik
    .value = Sütik
browser-data-edge-2 =
    .label = Sütik
    .value = Sütik
browser-data-safari-2 =
    .label = Sütik
    .value = Sütik
browser-data-chrome-2 =
    .label = Sütik
    .value = Sütik
browser-data-canary-2 =
    .label = Sütik
    .value = Sütik
browser-data-firefox-2 =
    .label = Sütik
    .value = Sütik
browser-data-360se-2 =
    .label = Sütik
    .value = Sütik
browser-data-ie-4 =
    .label = Böngészési előzmények
    .value = Böngészési előzmények
browser-data-edge-4 =
    .label = Böngészési előzmények
    .value = Böngészési előzmények
browser-data-safari-4 =
    .label = Böngészési előzmények
    .value = Böngészési előzmények
browser-data-chrome-4 =
    .label = Böngészési előzmények
    .value = Böngészési előzmények
browser-data-canary-4 =
    .label = Böngészési előzmények
    .value = Böngészési előzmények
browser-data-firefox-history-and-bookmarks-4 =
    .label = A böngészés előzményei és könyvjelzők
    .value = A böngészés előzményei és könyvjelzők
browser-data-360se-4 =
    .label = Böngészési előzmények
    .value = Böngészési előzmények
browser-data-ie-8 =
    .label = Mentett űrlapadatok
    .value = Mentett űrlapadatok
browser-data-edge-8 =
    .label = Mentett űrlapadatok
    .value = Mentett űrlapadatok
browser-data-safari-8 =
    .label = Mentett űrlapadatok
    .value = Mentett űrlapadatok
browser-data-chrome-8 =
    .label = Mentett űrlapadatok
    .value = Mentett űrlapadatok
browser-data-canary-8 =
    .label = Mentett űrlapadatok
    .value = Mentett űrlapadatok
browser-data-firefox-8 =
    .label = Mentett űrlapadatok
    .value = Mentett űrlapadatok
browser-data-360se-8 =
    .label = Mentett űrlapadatok
    .value = Mentett űrlapadatok
browser-data-ie-16 =
    .label = Mentett jelszavak
    .value = Mentett jelszavak
browser-data-edge-16 =
    .label = Mentett jelszavak
    .value = Mentett jelszavak
browser-data-safari-16 =
    .label = Mentett jelszavak
    .value = Mentett jelszavak
browser-data-chrome-16 =
    .label = Mentett jelszavak
    .value = Mentett jelszavak
browser-data-canary-16 =
    .label = Mentett jelszavak
    .value = Mentett jelszavak
browser-data-firefox-16 =
    .label = Mentett jelszavak
    .value = Mentett jelszavak
browser-data-360se-16 =
    .label = Mentett jelszavak
    .value = Mentett jelszavak
browser-data-ie-32 =
    .label = Kedvencek
    .value = Kedvencek
browser-data-edge-32 =
    .label = Kedvencek
    .value = Kedvencek
browser-data-safari-32 =
    .label = Könyvjelzők
    .value = Könyvjelzők
browser-data-chrome-32 =
    .label = Könyvjelzők
    .value = Könyvjelzők
browser-data-canary-32 =
    .label = Könyvjelzők
    .value = Könyvjelzők
browser-data-360se-32 =
    .label = Könyvjelzők
    .value = Könyvjelzők
browser-data-ie-64 =
    .label = További adatok
    .value = További adatok
browser-data-edge-64 =
    .label = További adatok
    .value = További adatok
browser-data-safari-64 =
    .label = További adatok
    .value = További adatok
browser-data-chrome-64 =
    .label = További adatok
    .value = További adatok
browser-data-canary-64 =
    .label = További adatok
    .value = További adatok
browser-data-firefox-other-64 =
    .label = További adatok
    .value = További adatok
browser-data-360se-64 =
    .label = További adatok
    .value = További adatok
browser-data-firefox-128 =
    .label = Ablakok és lapok
    .value = Ablakok és lapok
