# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Ukufuna i-{ $host }…
network-connection-status-connected = Ixhumeke ku-{ $host }…
network-connection-status-sending-request = Ukuthumela isicelo ku-{ $host }…
network-connection-status-transferring-data = Ukuthumela ukwaziswa kusuka ku-{ $host }…
network-connection-status-connecting = Ixhumeka ku-{ $host }…
network-connection-status-read = Funda i-{ $host }
network-connection-status-wrote = Kubhale i-{ $host }
network-connection-status-waiting = Kulindelwe i-{ $host }…
network-connection-status-looked-up = Ifune i-{ $host }…
