# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = Eli khasi lewebhu likhonjiswa kwindawo entsha. Ungathanda ukuthumela iingcombolo zefom ozichwethezileyo kwindawo entsha?
# Directory listing strings
DirTitle = Isalathi se-%1$S
DirGoUp = Ukufikelela kuvimba weefayili wenqanaba eliphezulu ngakumbi
ShowHidden = Bonisa izinto ezifihlakeleyo
DirColName = Igama
DirColSize = Ubukhulu
DirColMTime = Ihlengahlengiswe Okokugqibela
DirFileLabel = Ifayile:\u0020
UnsafeUriBlocked = Uvimba we-“%1$S” ubuvalelwe kukuBhrawuza okuKhuselekileyo.
