# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Denbora-muga gaindituta
openFile = Ireki fitxategia
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Bilatu "%2$S" %1$S(e)n
contextMenuSearch.accesskey = B
contextMenuPrivateSearch = Bilatu leiho pribatuan
contextMenuPrivateSearch.accesskey = h
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Bilatu leiho pribatuan %S erabiliz
contextMenuPrivateSearchOtherEngine.accesskey = h
bookmarkAllTabsDefault = [Karpetaren izena]
unsignedAddonsDisabled.message = Instalatutako gehigarri bat edo gehiago ezin dira egiaztatu eta desgaitu egin dira.
unsignedAddonsDisabled.learnMore.label = Argibide gehiago
unsignedAddonsDisabled.learnMore.accesskey = A
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Azken atzipena: %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = %S:// loturak
crashedpluginsMessage.title = %S pluginak huts egin du.
crashedpluginsMessage.reloadButton.label = Berritu orria
crashedpluginsMessage.reloadButton.accesskey = B
crashedpluginsMessage.submitButton.label = Bidali hutsegite-txostena
crashedpluginsMessage.submitButton.accesskey = B
crashedpluginsMessage.learnMore = Argibide gehiago…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = %S ostalarira nahi zenuen joan?
keywordURIFixup.goTo = Bai, eraman nazazu %S ostalarira
keywordURIFixup.goTo.accesskey = B
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Eguneratu %S bertsiora
update.downloadAndInstallButton.accesskey = E
menuOpenAllInTabs.label = Ireki guztiak fitxetan
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Berritu orri hau
tabHistory.goBack = Joan atzera orri honetara
tabHistory.goForward = Joan aurrera orri honetara
# URL Bar
pasteAndGo.label = Itsatsi eta joan
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Berritu uneko orria (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Utzi orria kargatzeari (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Berrezarri zoomaren maila (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Txandakatu irakurtzeko ikuspegia (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %%%S
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %%%S, berrezarri zoomaren maila
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Erakutsi laster-markak (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Bistaratu abiarazitako deskargen aurrerapena (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Ireki leiho berria (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Ireki fitxa berria (%S)
newTabContainer.tooltip = Ireki fitxa berria (%S)\nSakatu eta mantendu edukiontzi-fitxa berri bat irekitzeko
newTabAlwaysContainer.tooltip = Hautatu fitxa berria irekitzeko edukiontzia
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Baimendu %S guneak zure HTML5 canvas-eko irudi-datuak erabiltzea?
canvas.siteprompt2.warning = Zure ordenagailua modu esklusiboan identifikatzeko erabil liteke hau.
canvas.block = Blokeatu
canvas.block.accesskey = B
canvas.allow2 = Baimendu
canvas.allow2.accesskey = a
canvas.remember2 = Gogoratu erabakia
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Egiaztapena: %S
identity.identified.verified_by_you = Segurtasun salbuespen bat gehitu duzu gune honentzat.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Ziurtagiria honi jaulkia: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Ez-segurua
identity.notSecure.tooltip = Konexioa ez da segurua
identity.extension.label = Hedapena (%S)
identity.extension.tooltip = Luzapen bidez kargatua: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Urrundu zooma (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Berrezarri zoomaren maila (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Gerturatu zooma (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Ebaki (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Kopiatu (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Itsatsi (%S)
geolocation.allow = Baimendu
geolocation.allow.accesskey = a
geolocation.block = Blokeatu
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Sistemaren kokaleku-ezarpenak irekiko ditu honek. Eman mesedez kokalekuaren baimenak %S aplikazioari.
geolocation.shareWithSite4 = Baimendu %S guneak zure kokapena erabiltzea?
geolocation.shareWithFile4 = Baimendu fitxategi lokal honi zure kokapena erabiltzea?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Baimendu %1$S guneak %2$S guneari zure kokapenaren sarbidea izateko baimena ematea?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Eman %S aplikazioari kokalekuaren baimenak sistema-ezarpenetan.
geolocation.systemSettingsTitle = Kokapenaren baimenen zain
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Sistemak baimen hau %S aplikazioari emateko galdetuko dizu.
geolocation.remember = Gogoratu erabakia
# Virtual Reality Device UI
xr.allow2 = Baimendu
xr.allow2.accesskey = a
xr.block = Blokeatu
xr.block.accesskey = B
xr.shareWithSite4 = Baimendu %S guneak errealitate birtualeko gailuetarako sarbidea izatea? Honek kontuzko informazioa argitara eman lezake.
xr.shareWithFile4 = Baimendu fitxategi lokal honek errealitate birtualeko gailuetarako sarbidea izatea? Honek kontuzko informazioa argitara eman lezake.
xr.remember = Gogoratu erabaki hau
# Persistent storage UI
persistentStorage.allow = Baimendu
persistentStorage.allow.accesskey = B
persistentStorage.block.label = Blokeatu
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Baimendu %S guneak datuak biltegiratze iraunkorrean gordetzea?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Baimendu
webNotifications.allow2.accesskey = a
webNotifications.notNow = Une honetan ez
webNotifications.notNow.accesskey = z
webNotifications.never = Inoiz ez baimendu
webNotifications.never.accesskey = n
webNotifications.alwaysBlock = Blokeatu beti
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = Blokeatu
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Baimendu %S guneari jakinarazpenak bidaltzea?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S(e)k beste aplikazio eta zerbitzuetarako sarbidea nahi du gailu honetan.
localhost.remember2 = Gogoratu nire aukera gune honetarako
localhost.allowlabel = Baimendu
localhost.blocklabel = Blokeatu
localhost.allow.accesskey = B
localhost.block.accesskey = k
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S(e)k beste aplikazio eta zerbitzuetarako sarbidea nahi du zure sare lokalean konektatutako gailuetan.
localNetwork.remember2 = Gogoratu nire aukera gune honetarako
localNetwork.allowLabel = Baimendu
localNetwork.allow.accesskey = B
localNetwork.blockLabel = Blokeatu
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Eraman nazazu hemendik at!
safebrowsing.getMeOutOfHereButton.accessKey = E
safebrowsing.deceptiveSite = Gune iruzurtia!
safebrowsing.notADeceptiveSiteButton.label = Hau ez da gune iruzurtia…
safebrowsing.notADeceptiveSiteButton.accessKey = i
safebrowsing.reportedAttackSite = Ustezko web erasoa!
safebrowsing.notAnAttackButton.label = Hau ez da gune erasotzailea…
safebrowsing.notAnAttackButton.accessKey = n
safebrowsing.reportedUnwantedSite = Salatutako nahi ez den softwarearen gunea!
safebrowsing.reportedHarmfulSite = Gune erasotzaile gisa markatuta!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Search %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Berrabiarazi %S arazoak konpontzeko moduan?
troubleshootModeRestartPromptMessage = Zure hedapenak, itxurak eta ezarpen pertsonalizatuak behin-behinean desgaitu egingo dira.
troubleshootModeRestartButton = Berrabiarazi
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Orri hau %1$S mantsotzen ari da. Zure nabigatzailea bizkortzeko, gelditu orri hau.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Webgune bat %1$S mantsotzen ari da. Zure nabigatzailea bizkortzeko, gelditu orri hori.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = "%1$S" fitxa %2$S mantsotzen ari da. Zure nabigatzailea bizkortzeko, gelditu orri hori.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = "%1$S" hedapena %2$S mantsotzen ari da. Zure nabigatzailea bizkortzeko, gelditu hedapen hori.
processHang.add-on.learn-more.text = Argibide gehiago
processHang.button_stop2.label = Gelditu
processHang.button_stop2.accessKey = G
processHang.button_debug.label = Araztu scripta
processHang.button_debug.accessKey = A
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Bistaratu leihoa pantaila osoan (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Aldatu lekuz alboko barra ezkerrera
sidebar.moveToRight = Aldatu lekuz alboko barra eskuinera
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = DRMa gaitu behar duzu orri honetako zenbait audio edo bideo erreproduzitzeko.
emeNotifications.drmContentDisabled.button.label = Gaitu DRMa
emeNotifications.drmContentDisabled.button.accesskey = G
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = Orri honetako audioa edo bideoa erreproduzitzeko behar diren osagaiak instalatzen ari da %S. Saiatu berriro geroago mesedez.
emeNotifications.unknownDRMSoftware = Ezezaguna
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Pertsonalizatu %S
decoder.noCodecs.button = Ikasi nola
decoder.noCodecs.accesskey = I
decoder.noCodecsLinux.message = Bideoa erreproduzitzeko, baliteke beharrezko bideo-kodekak instalatu behar izatea.
decoder.noHWAcceleration.message = Bideoaren kalitatea hobetzeko, baliteke Microsoft-en Media Feature Pack-a instalatu behar izatea.
decoder.noPulseAudio.message = Bideoa erreproduzitzeko, baliteke PulseAudio softwarea instalatu behar izatea.
decoder.unsupportedLibavcodec.message = libavcodec babesik edo euskarririk gabe egon liteke eta eguneratu egin behar da bideoa erreproduzitzeko.
decoder.decodeError.message = Errorea gertatu da multimedia-baliabide bat deskodetzean.
decoder.decodeError.button = Eman gunearen arazoaren berri
decoder.decodeError.accesskey = E
decoder.decodeWarning.message = Berreskuragarria den errore bat gertatu da multimedia-baliabide bat deskodetzean.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Internetera sartu ahal izateko saioa hasi behar duzu sare honetan.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Ireki sarearen saio-hasiera orria
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = %S ostalariaren baimenak
permissions.remove.tooltip = Garbitu baimen hau eta galdetu berriro
permissions.fullscreen.promptCanceled = Bertan behera utzi dira baimenen eskaerak: eskaerak ez dira egin behar DOMeko pantaila osoan sartu aurretik.
permissions.fullscreen.fullScreenCanceled = DOMeko pantaila osoa irten da: baimenen eskaerak ez dira egin behar pantaila osoan egon bitartean.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64 bit
aboutDialog.architecture.thirtyTwoBit = 32 bit
midi.allow.label = Baimendu
midi.allow.accesskey = a
midi.block.label = Blokeatu
midi.block.accesskey = B
midi.remember = Gogoratu erabakia
midi.shareWithFile = Baimendu fitxategi lokal honi zure MIDI gailuak atzitzea?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Baimendu %S guneari zure MIDI gailuak atzitzea?
midi.shareSysexWithFile = Baimendu fitxategi lokal honi zure MIDI gailuak atzitu eta SysEx mezuak bidali eta jasotzea?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Baimendu %S guneari zure MIDI gailuak atzitu eta SysEx mezuak bidali eta jasotzea?
serial.allow.label = Baimendu
serial.allow.accesskey = a
serial.block.label = Blokeatu
serial.block.accesskey = B
serial.shareWithFile = Baimendu fitxategi lokal honi zure serieko atakak erabiltzea?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Baimendu %S guneak zure serieko atakak atzitzea?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Atzera
storageAccess1.Allow.label = Baimendu
storageAccess1.Allow.accesskey = B
storageAccess1.DontAllow.label = Blokeatu
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Baimendu %1$S guneari bere cookieak %2$S gunean erabiltzea?
storageAccess1.hintText = Sarbidea blokeatu nahiko duzu ez badago garbi zergatik behar dituen datu hauek %1$S guneak.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Bilatu “%S” webean
