#filter emptyLines
# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title Obulambe


#define bookmarks_heading Obulambe


# LOCALIZATION NOTE (bookmarks_addons):

# link title for https://en-US.add-ons.mozilla.com/en-US/firefox/bookmarks/

#define bookmarks_addons Funa eby'okwongera ku bulambe


#define bookmarks_toolbarfolder Olusangiro lw'ebikozeso ebiramba


#define bookmarks_toolbarfolder_description Ggatta obulmbe ku tterekero lino okubulaba nga bwoleseddwa ku mulabba gw'obulambe


# LOCALIZATION NOTE (getting_started):

# link title for http://en-US.www.mozilla.com/en-US/firefox/central/

#define getting_started Entandika


# LOCALIZATION NOTE (latest_headlines):

# link title for the live bookmarks sample, a redirect on

# http://en-US.fxfeeds.mozilla.com/en-US/firefox/headlines.xml

# Changing the redirect is subject to approval of l10n-drivers.

#define latest_headlines Emitwe eggya kabaawo


# LOCALIZATION NOTE (firefox_heading):

# Firefox links folder name

#define firefox_heading Mozilla Fayafokisi


# LOCALIZATION NOTE (firefox_help):

# link title for http://en-US.www.mozilla.com/en-US/firefox/help/

#define firefox_help Obuyambi n'ebyokuyiga


# LOCALIZATION NOTE (firefox_customize):

# link title for http://en-US.www.mozilla.com/en-US/firefox/customize/

#define firefox_customize Kyuusa Fayafokisi nga bwoyagala


# LOCALIZATION NOTE (firefox_community):

# link title for http://en-US.www.mozilla.com/en-US/firefox/community/

#define firefox_community Wenyigiremu


# LOCALIZATION NOTE (firefox_about):

# link title for http://en-US.www.mozilla.com/en-US/firefox/about/

#define firefox_about Ebitufaako


#unfilter emptyLines