# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Chceće "%S" za slědowace zaměry dowěrić?
unnamedCA = Certifikatowa awtorita (bjez mjena)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Prošu zapodajće hesło, kotrež je so za zaklučowanje tutoho zawěsćenja certifikata wužiło:
# Page Info
pageInfo_NoEncryption = Zwisk njezaklučowany
pageInfo_Privacy_None1 = Websydło %S njepodpěruje zaklučowanje za stronu, kotruž sej runje wobhladujeće.
pageInfo_Privacy_None2 = Informacije, kotrež sćelu so bjez zaklučowanja přez Internet, hodźa so wot druhich ludźi widźeć, mjeztym zo jón přeprěkuja.\u0020
pageInfo_Privacy_None4 = Strona, kotruž sej wobhladujeće, njebě zaklučowana, prjedy hač je so přez internet pósłała.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Zwisk zaklučowany (%1$S, bitowe kluče %2$S, %3$S)
pageInfo_BrokenEncryption = Złamane zaklučowanje (%1$S, bitowe kluče %2$S, %3$S)
pageInfo_Privacy_Encrypted1 = Strona, kotruž sej wobhladujeće, je so zaklučowała, prjedy hač je so přez internet pósłała.
pageInfo_Privacy_Encrypted2 = Zaklučowanje poćežuje njeawtorizowanym wosobam informacije widźeć, kotrež so mjez ličakami wuměnjeja. Je tohodla prawdźe jara njepodobne, zo je něchtó tutu stronu přečitał, hdyž je wona syć přeprěčiła.
pageInfo_MixedContent = Zwisk zdźěla zaklučowany
pageInfo_MixedContent2 = Dźěle strony, kotruž sej runje wobhladujeće, njejsu so zaklučowali, prjedy hač internet přepřěčichu.
pageInfo_WeakCipher = Waš zwisk z tutym websydłom wužiwa słabe zaklučowanje a njeje priwatny. Druzy ludźo móža waše informacije widźeć abo zadźerženje websydła změnić.
pageInfo_CertificateTransparency_Compliant = Tute websydło wotpowěduje prawidłam certifikatoweje transparency.
# Token Manager
password_not_set = (njenastajeny)
