# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Over uw rechten
rights-intro-point-3 = Enkele onderdelen in { -brand-short-name }, zoals de Crashreporter, bieden u de mogelijkheid feedback aan { -vendor-short-name } te leveren. Door het indienen van feedback geeft u { -vendor-short-name } toestemming de feedback te gebruiken om zijn producten te verbeteren, de feedback op zijn websites te publiceren en de feedback te verspreiden.
rights-intro-point-4 = Hoe we uw persoonlijke gegevens en feedback gebruiken die via { -brand-short-name } naar { -vendor-short-name } wordt verzonden, wordt beschreven in het <a data-l10n-name="mozilla-privacy-policy-link">{ -brand-short-name }-privacybeleid</a>.
rights-intro-point-6 = Om bepaalde typen video-inhoud af te spelen, downloadt { -brand-short-name } bepaalde inhouddecoderingsmodules van derden.
rights-webservices = { -brand-full-name } maakt gebruik van webgebaseerde informatiediensten (‘Diensten’) om een aantal functies die met deze binaire versie van { -brand-short-name } worden meegeleverd onder de onderstaande voorwaarden te gebruiken. Als u een of meer van de diensten niet wilt gebruiken of de onderstaande voorwaarden niet wilt accepteren, kunt u de functie of dienst(en) uitschakelen. Instructies over het uitschakelen van een bepaalde functie of dienst kunt u <a data-l10n-name="mozilla-disable-service-link">hier</a> vinden. Andere onderdelen en diensten kunnen worden uitgeschakeld in de voorkeuren van de toepassing.
rights-locationawarebrowsing = <strong>Locatiebewust navigeren: </strong>vraagt altijd om toestemming. Er worden nooit locatiegegevens verzonden zonder uw toestemming. Als u de functie volledig wilt uitschakelen, volg dan deze stappen:
rights-webservices-unbranded = Een overzicht van de in het product opgenomen websitediensten, samen met instructies over het uitschakelen ervan, wanneer van toepassing, dienen hier te worden bijgesloten.
rights-webservices-term-unbranded = Servicevoorwaarden die op dit product van toepassing zijn, dienen hier te worden vermeld.
rights-webservices-term-1 = { -vendor-short-name } en zijn medewerkers, licentiegevers en partners werken aan het verstrekken van de meest nauwkeurige en bijgewerkte Diensten. We kunnen echter niet garanderen dat deze informatie volledig en foutvrij is. De dienst Safe Browsing bijvoorbeeld identificeert mogelijk bepaalde riskante websites niet, en bepaalde veilige websites ten onrechte wel. Alle locaties die door de dienst Locatiebewust navigeren van onze serviceproviders worden verkregen, zijn enkel schattingen. Noch wij, noch de serviceproviders garanderen de nauwkeurigheid van de gegeven locaties.
rights-webservices-term-7 = Deze voorwaarden vallen onder de wetten van de staat Californië, U.S.A., met uitzondering van zijn bepalingen van internationaal privaatrecht. Als een of meer van deze voorwaarden als ongeldig of onafdwingbaar worden beschouwd, blijven de overige bepalingen onverminderd van kracht. In geval van strijdigheid tussen een vertaalde versie van deze voorwaarden en de Engelse versie prevaleert de Engelse versie.
