# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Da li želite vjerovati "%S" u sljedeće svrhe?
unnamedCA = Certifikacijski Autoritet (neimenovani)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Molimo da unesete lozinku koja je korištena za enkripciju ovog backupa certifikata:
# Page Info
pageInfo_NoEncryption = Konekcija nije enkriptovana
pageInfo_Privacy_None1 = Web stranica %S ne podržava enkripciju za stranicu koju gledate.
pageInfo_Privacy_None2 = Informacija poslana putem Interneta bez enkripcije može biti dostupna drugim osobama za vrijeme prijenosa.\u0020
pageInfo_Privacy_None4 = Stranica koju pregledavate nije enkriptovana prije slanja putem interneta.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Enkriptovana veza (%1$S, %2$S bitni ključevi, %3$S)
pageInfo_BrokenEncryption = Neispravna enkripcija (%1$S, %2$S bitni ključevi, %3$S)
pageInfo_Privacy_Encrypted1 = Stranica koju pregledavate je enkriptovana prije slanja putem interneta.
pageInfo_Privacy_Encrypted2 = Enkripcija neovlaštenim osobama otežava pregledavanje informacija koje putuju između računara. Stoga je mala vjerovatnoća da je neko pročitao ovu stranicu dok je putovala mrežom.
pageInfo_MixedContent = Veza je djelimično enkriptovana
pageInfo_MixedContent2 = Dijelovi stranice koju pregledavate nisu enkriptovani prije slanja putem interneta.
pageInfo_WeakCipher = Vaša veza na ovu web stranicu koristi slabu enkripciju i nije privatna. Drugi ljudi mogu vidjeti vaše informacije ili promijeniti ponašanje web stranice.
pageInfo_CertificateTransparency_Compliant = Ova web stranica je u skladu sa Certificate Transparency policom.
# Token Manager
password_not_set = (nije postavljeno)
