# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = An bhfuil tú ag iarraidh muinín a chur i “%S” maidir leis na cuspóirí seo leanas?
unnamedCA = Údarás Deimhniúcháin (gan ainm)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Cuir isteach an focal faire a d'úsáid tú chun an cúlra teastais seo a chriptiú:
# Page Info
pageInfo_NoEncryption = Níl an ceangal criptithe
pageInfo_Privacy_None1 = Ní thacaíonn an suíomh Gréasáin %S le criptiúchán don leathanach a bhfuil tú ag amharc air.
pageInfo_Privacy_None2 = Is féidir le daoine eile faisnéis gan criptiúchán a sheoltar thar an Idirlíon a fheiceáil agus é ar an aistear.\u0020
pageInfo_Privacy_None4 = Níor criptíodh an leathanach ar a bhfuil tú ag amharc roimh é a thraschur ar an Idirlíon.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Ceangal Criptithe (%1$S, eochracha %2$S giotán, %3$S)
pageInfo_BrokenEncryption = Criptiúchán Briste (%1$S, eochracha %2$S giotán, %3$S)
pageInfo_Privacy_Encrypted1 = Criptíodh an leathanach ar a bhfuil tú ag amharc roimh é a thraschur ar an Idirlíon.
pageInfo_Privacy_Encrypted2 = De bharr criptiúcháin, tá sé an-deacair do dhaoine faisnéis a léamh gan cead agus í á traschur idir ríomhairí. Is beag seans, mar sin, gur léigh aon duine an leathanach seo agus é ag taisteal tríd an líonra.
pageInfo_MixedContent = Ceangal páirtchriptithe
pageInfo_MixedContent2 = Níor criptíodh cuid den leathanach ar a bhfuil tú ag amharc roimh é a thraschur thar an Idirlíon.
pageInfo_WeakCipher = Úsáideann do cheangal leis an suíomh seo criptiúchán lag nach bhfuil príobháideach. Is féidir le daoine eile do shonraí a fheiceáil agus iompar an tsuímh a athrú.
pageInfo_CertificateTransparency_Compliant = Cloíonn an suíomh seo leis an bpolasaí Trédhearcacht Teastais.
# Token Manager
password_not_set = (gan socrú)
