# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Volètz far fisança a « %S » per las accions seguentas ?
unnamedCA = Autoritat de certificacion (pas de nom)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Picatz lo senhal per chifrar la còpia de seguretat d'aqueste certificat :
# Page Info
pageInfo_NoEncryption = Connexion pas chifrada
pageInfo_Privacy_None1 = Lo site Web %S supòrta pas lo chiframent per la pagina actualament afichada.
pageInfo_Privacy_None2 = Las entresenhas mandadas sus Internet sens chiframent pòdon èsser vistas per d'autras personas durant lor transit.
pageInfo_Privacy_None4 = La pagina que vesètz es estada chifrada abans sa transmission sus Internet.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Connexion chifrada (claus %1$S, %2$S bits, %3$S)
pageInfo_BrokenEncryption = Chiframent pas fisable (claus %1$S, %2$S bits, %3$S)
pageInfo_Privacy_Encrypted1 = La pagina que vesètz es estada chifrada abans sa transmission sus Internet.
pageInfo_Privacy_Encrypted2 = Lo chiframent fa fòrt dificil a las personas pas autorizadas la visualizacion de la pagina durant son transit entre ordenadors. Doncas, es fòrt improbable que qualqu'un pòsca legir aquesta pagina durant son transit sus la ret.
pageInfo_MixedContent = Connexion parcialament chifrada
pageInfo_MixedContent2 = D'unas partidas de la pagina que visionatz son pas estadas chifradas abans d'èsser transmesas sus Internet.
pageInfo_WeakCipher = Vòstra connexion a aquel site web utiliza un nivèl de chiframent feble e es pas privada. D'autres pòdon veire vòstras informacions o modificar lo compòrtament del site web.
pageInfo_CertificateTransparency_Compliant = Lo site web respècta lo certificat de la politica de transparéncia.
# Token Manager
password_not_set = (pas definit)
