# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Vuelistu fidâti di "%S" par chescj?
unnamedCA = Autoritât di certificazion (cence non)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Par plasê inserìs la password che e je stade doprade par cifrâ la copie di backup di chest certificât:
# Page Info
pageInfo_NoEncryption = Conession no cifrade
pageInfo_Privacy_None1 = Il sît web %S nol supuarte la cifradure pe pagjine che tu stâs viodint.
pageInfo_Privacy_None2 = Lis informazions mandadis su Internet cence cifrazion a puedin jessi viodudis di altris personis dilunc il transit.
pageInfo_Privacy_None4 = La pagjine che tu stâs visualizant no je stade cifrade prime de sô trasmission su internet.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Conession cifrade (%1$S, clâfs a %2$S bits, %3$S)
pageInfo_BrokenEncryption = Cifradure difetose (%1$S, clâfs a %2$S bits, %3$S)
pageInfo_Privacy_Encrypted1 = La pagjine che tu sês daûr a cjalâ e je stade cifrade prime di jessi trasmitude su Internet.
pageInfo_Privacy_Encrypted2 = La cifradure e rint dificil osservâ lis informazions scambiadis tra computers a personis no autorizadis. Al è duncje improbabil che cualchidun al sedi rivât a lei il contignût di cheste pagjine dilunc il transit vie pe rêt.
pageInfo_MixedContent = Conession cifrade in part
pageInfo_MixedContent2 = Tocs de pagjine che tu sês daûr a cjalâ no son stâts cifrâts prime di jessi trasmetûts in Internet.
pageInfo_WeakCipher = La tô conession a chest sît web e dopre une cifradure debile e no je privade. Altris personis a puedin viodi lis informazions mandadis e modificâ il compuartament dal sît.
pageInfo_CertificateTransparency_Compliant = Chest sît web al è conformi aes politichis di trasparence dai certificâts.
# Token Manager
password_not_set = (no definît)
