# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Cawa otum woko
openFile = Yab pwail
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Yeny %1$S pi “%2$S”
contextMenuSearch.accesskey = S
contextMenuPrivateSearch = Yeny ii Dirica me Mung
contextMenuPrivateSearch.accesskey = h
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Yeny ki %S ii Dirica me Mung
contextMenuPrivateSearchOtherEngine.accesskey = h
bookmarkAllTabsDefault = [Nying Boc]
unsignedAddonsDisabled.message = Med-ikome acel nyo makato ma kiketo pe ki twero moko ada gi kadong kijuko woko.
unsignedAddonsDisabled.learnMore.label = Nong ngec mapol
unsignedAddonsDisabled.learnMore.accesskey = N
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Nong me agiki %S
crashedpluginsMessage.title = Larwak man me %S opoto woko.
crashedpluginsMessage.reloadButton.label = Nwo cano pot buk
crashedpluginsMessage.reloadButton.accesskey = N
crashedpluginsMessage.submitButton.label = Cwal ripot me poto
crashedpluginsMessage.submitButton.accesskey = C
crashedpluginsMessage.learnMore = Nong ngec mapol…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = I mito no me cito i %S?
keywordURIFixup.goTo = Eyo, cwala i %S
keywordURIFixup.goTo.accesskey = Y
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Ket ngec manyen ocit i %S
update.downloadAndInstallButton.accesskey = K
menuOpenAllInTabs.label = Yab weng i dirica matino
tabHistory.goBack = Dok cen i pot buk man
tabHistory.goForward = Cit anyim i pot buk man
# URL Bar
pasteAndGo.label = Mwon kadong iciti
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Nwo cano potbuk man (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Juk cano potbuk man (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Nwo tero rwom me kwot (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Nyut alam buk mamegi (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Yar kit ma gam tye kawot kwede (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Yab dirica manyen (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Yab dirica matidi manyen (%S)
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Lamoke aye: %S
identity.identified.verified_by_you = Ityeko medo ma kiweko woko me ber bedo pi kakube man.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Kimiyo catibiket bot: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Pe ki ber bedo
identity.notSecure.tooltip = Kube pe tye ki ber bedo
identity.extension.label = Lamed (%S)
identity.extension.tooltip = Lamed ma ocano aye: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Jwiki matidi (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Nwo tero rwom me kwot (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Jwiki matidi (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Ngol (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Lok (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Mwon (%S)
geolocation.remember = Poo ikom moko tam man
xr.remember = Poo ikom moko tam man
# Persistent storage UI
persistentStorage.allow = Yee
persistentStorage.allow.accesskey = A
webNotifications.notNow = Pe Kombedi
webNotifications.notNow.accesskey = n
webNotifications.never = Matwal pe iyee
webNotifications.never.accesskey = v
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Kwanya woko ki kany!
safebrowsing.getMeOutOfHereButton.accessKey = K
safebrowsing.deceptiveSite = Kakube me bwola!
safebrowsing.notADeceptiveSiteButton.label = Man pe kakube me bwola…
safebrowsing.notADeceptiveSiteButton.accessKey = b
safebrowsing.reportedAttackSite = Ripot ma kigoyo ikom kakube me kamony!
safebrowsing.notAnAttackButton.label = Man pe obedo kakube me kamony…
safebrowsing.notAnAttackButton.accessKey = m
safebrowsing.reportedUnwantedSite = Kakube pi purugram mape kimito ma kimiyo ripote!
safebrowsing.reportedHarmfulSite = Kakube ma kimiyo ripot ni rac!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Yeny %S
processHang.add-on.learn-more.text = Nong ngec mapol
processHang.button_debug.label = Coc me nongo bal
processHang.button_debug.accessKey = n
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Yar dirica opong wang komputa weng (%S)
emeNotifications.drmContentDisabled.button.label = Cak DRM
emeNotifications.drmContentDisabled.button.accesskey = C
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S tye ka keto jami ma mite me tuko dwon onyo vidio i pot buk man. Tim ber i tem doki lacen.
emeNotifications.unknownDRMSoftware = Pe ngene
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Ter %S
decoder.noCodecs.button = Nong ngec i kit yoo
decoder.noCodecs.accesskey = L
decoder.noCodecsLinux.message = Me tuko vidio, twero mite ni myero kong iket latuk vidio ma mite.
decoder.noHWAcceleration.message = Me weko video onen maleng, twero mite ni myero iket Microsoft’s Media Feature Pack.
decoder.noPulseAudio.message = Me tuko dwon, twero mite ni myero kong iket purugram me PulseAudio ma mite.
decoder.unsupportedLibavcodec.message = libavcodec twero bedo goro onyo pe kicwako, kadong myero ki ket ngec manyen wek otuk vidio.
decoder.decodeError.button = Mi ripot ikom peko me kakube
decoder.decodeError.accesskey = R
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Myero kong i dony iyie netwak man me nongo intanet
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Yab potbuk me donyo iyie netwak
permissions.remove.tooltip = Jwa twero man ka i peny doki
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bit
aboutDialog.architecture.thirtyTwoBit = 32-bit
midi.remember = Poo ikom moko tam man
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Cen
