# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

print-setup =
    .title = Sideopsætning
custom-prompt-title = Brugerdefineret…
custom-prompt-prompt = Skriv teksten til dit brugerdefinerede sidehoved/sidefod
basic-tab =
    .label = Format og indstillinger
advanced-tab =
    .label = Margener og sidehoved/sidefod
format-group-label =
    .value = Formater
orientation-label =
    .value = Orientering:
portrait =
    .label = Portræt
    .accesskey = P
landscape =
    .label = Landskab
    .accesskey = L
scale =
    .label = Skaler:
    .accesskey = S
scale-percent =
    .value = %
shrink-to-fit =
    .label = Tilpas til sidebredden
    .accesskey = i
options-group-label =
    .value = Valgmuligheder
print-bg =
    .label = Udskriv baggrunden (farver & baggrundsbilleder)
    .accesskey = U
margin-group-label-inches =
    .value = Margener (tommer)
margin-group-label-metric =
    .value = Margener (millimeter)
header-footer-label =
    .value = Sidehoveder og sidefødder
hf-blank =
    .label = --blank--
hf-title =
    .label = Titel
hf-url =
    .label = URL
hf-page =
    .label = Side #
hf-page-and-total =
    .label = Side # af #
hf-custom =
    .label = Brugerdefineret…
print-preview-window =
    .title = Vis udskrift
print-title =
    .value = Titel:
print-preparing =
    .value = Forbereder…
print-progress =
    .value = Forløb:
print-window =
    .title = Udskriver
print-complete =
    .value = Udskriften er fuldført.
# Variables
# $percent (integer) - Number of printed percentage
print-percent =
    .value = { $percent }%
dialog-cancel-label = Annuller
dialog-close-label = Luk
