# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

show-next-time-checkbox = Monstrar iste advertentia le proxime vice
ok = OK
http = HTTP
sockets = Sockets
dns = DNS
websockets = WebSockets
refresh = Actualisar
auto-refresh = Refrescamento automatic cata 3 secundas
port = Porta
http2 = HTTP/2
ssl = SSL
active = Active
idle = Inactive
tcp = TCP
sent = Inviate
received = Recipite
family = Familia
trr = TRR
addresses = Adresses
expires = Expira (Secundas)
messages-sent = Messages inviate
messages-received = Messages recipite
bytes-sent = Bytes inviate
bytes-received = Bytes recipite
logging = Registros
current-log-file = File de diario actual:
current-log-modules = Modulos de diario actual:
set-log-file = Definir le file de registro
set-log-modules = Definir le modulos de registro
start-logging = Initiar le registration
dns-lookup = Recerca de DNS
dns-lookup-button = Resolver
dns-domain = Dominio:
dns-lookup-table-column = IPs
rcwn = Statistica de RCWN
rcwn-status = Stato de RCWN
rcwn-cache-won-count = Numero de victorias del cache
rcwn-net-won-count = Numero de victorias del rete
total-network-requests = Numero total del requestas de rete
rcwn-operation = Operation de cache
rcwn-perf-open = Aperir
rcwn-perf-read = Leger
rcwn-perf-write = Scriber
rcwn-perf-entry-open = Entrata aperite
rcwn-avg-short = Media curte
rcwn-std-dev-long = Deviation standard longe
