# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = A proposito de tu derectos
rights-intro = { -brand-full-name } es software gratis e de codice aperite, construite per un communitate de milles de contributores de tote le mundo. Il ha poc cosas que tu deberea saper:
rights-intro-point-1 = { -brand-short-name } es facite disponibile a te sub le terminos del <a data-l10n-name="mozilla-public-license-link">Licentia public Mozilla</a>. Isto significa que tu pote usar, copiar e distribuer { -brand-short-name } a alteres.  Tu tamben es benvenite de modificar le codice fonte de { -brand-short-name } comocunque tu vole pro attinger tu necessitates. Le licentia public de Mozilla tamben te da le derecto de distribuer tu versiones modificate.
rights-intro-point-3 = Alcun functionalitates in { -brand-short-name }, como le reportator de collapsos, te da le option de provider feedback a { -vendor-short-name }. Eligente inviar feedback, tu dara a { -vendor-short-name } permission de usar le feedback pro meliorar su productos, de publicar le feedback in su sitos web e de distribuer le feedback.
rights-intro-point-4-unbranded = Omne politicas de confidentialitate applicabile pro iste producto debe esser listate hic.
rights-intro-point-6 = A fin de poter leger alcun typos de contento de video, { -brand-short-name } discarga certe modulos de deciframento de contento de terties.
rights-safebrowsing-term-3 = Dismarca le option pro "{ enableSafeBrowsing-label }"
enableSafeBrowsing-label = Blocar le contentos periculose o fraudulente
rights-webservices-unbranded = Un resumpto del servicios del sito web que le producto incorpora, accompaniate de instructiones sur como inactivar los, si applicabile, debe esser includite hic.
rights-webservices-term-1 = { -vendor-short-name } e su contributores, licentiantes e partenarios labora pro provider le servicios le plus accurate e actualisate.  Totevia nos non pote garantir que iste informationes es exhaustive e libere de errores.  Pro exemplo, le servicio de navigation secur non pote identificar alcun sitos malfaciente e pote suspectar de alcun sitos secur erroneemente e in le servicio de geolocalisation, tote le localisationes retornate per nostre fornitores de servicio es estimate solmente e ni nos ni nostre fornitores garanti le precision del localisationes fornite.
rights-webservices-term-2 = { -vendor-short-name } pote discontinuar o cambiar le Servicios a su discretion.
rights-webservices-term-3 = Tu es benvenite a usar iste Servicios con le version accompaniante de { -brand-short-name }, e { -vendor-short-name } te concede derectos de facer lo.  { -vendor-short-name } e su licentiantes reserva tote le altere derectos sur le Servicios.  Iste terminos non es intendite a limitar qualcunque derectos concedite sub altere licentias de codice aperite applicabile a { -brand-short-name } e al versiones de codice fonte correspondente de { -brand-short-name }.
rights-webservices-term-4 = <strong>Le Servicios es fornite "tal qual."  { -vendor-short-name }, su contributores, licentiantes e distributores, renega tote le garantias, expresse o implicite, inclusive sin limitation, garantias que le Servicios es commerciabile e conveni pro tu propositos particular.  Tu supporta tote le risco de seliger le Servicios pro tu propositos concernente le qualitate e le rendimento del Servicios. Alcun jurisdictiones non permitte le exclusion o limitation de garantias implicite, alora iste clausula non se applica a te.</strong>
rights-webservices-term-5 = <strong>Salvo si requirite per lege, { -vendor-short-name }, su contributores, licentiantes e distributores non essera responsabilisate per qualcunque damno indirecte, incidental, consequential, punitive o exemplar decurrente de o de omne maniera concernente le uso de { -brand-short-name } e le Servicios.  Le responsabilitate collective sub iste terminos non excedera $500 (cinque centos dollars). Alcun jurisdictiones non permitte le exclusion o limitation de certe damnos, alora iste exclusion e limitation pote non applicar se a te. </strong>
rights-webservices-term-7 = Iste terminos es governate per le leges del stato de California, SUA, excludente su conflicto de provisiones legal. Si qualcunque potion de iste terminos es tenite como invalide o non applicabile, le portiones restante remanera in tote fortia e effectos. In un eventual conflicto inter un version traducite de iste terminos e le version in lingua anglese, le version in lingua anglese prevalera.
