# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = ᱱᱚᱣᱟ ᱠᱚ ᱦᱩᱫᱤᱥ ᱞᱟᱹᱜᱤᱫ ᱪᱮᱫ ᱟᱢ ”%S” ᱨᱮ ᱯᱟᱹᱛᱭᱟᱣ ᱥᱟᱱᱟᱢ ᱠᱟᱱᱟ ?
unnamedCA = ᱯᱚᱨᱢᱟᱱ ᱥᱟᱠᱟᱢ ᱮᱢᱚᱜᱤᱡ (ᱵᱮᱜᱚᱨ ᱧᱩᱛᱩᱢ)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = ᱫᱟᱭᱟᱠᱟᱛᱮ ᱫᱟᱱᱟᱝ ᱥᱟᱵᱟᱫᱽ ᱟᱫᱮᱨ ᱢᱮ ᱡᱟᱦᱟᱸ ᱫᱚ ᱱᱚᱶᱟ ᱥᱟᱴᱤᱯᱷᱤᱠᱮᱴ ᱵᱮᱠᱚᱯᱷ ᱫᱟᱱᱟᱝᱟᱜ ᱪᱷᱚ ᱞᱟᱹᱜᱤᱫ ᱵᱮᱵᱷᱟᱨ ᱞᱮᱱᱟ :
# Page Info
pageInfo_NoEncryption = ᱡᱚᱱᱚᱲᱟᱣ ᱵᱟᱭ ᱫᱟᱱᱟᱝ
pageInfo_Privacy_None1 = ᱣᱮᱵᱥᱟᱭᱤᱴ %S ᱟᱢᱮᱢ ᱧᱮᱞᱮᱫ ᱥᱟᱦᱴᱟ ᱞᱟᱹᱜᱤᱫ ᱫᱟᱱᱟᱝᱠ ᱵᱟᱭ ᱜᱚᱲᱚᱣᱟᱜ ᱟ ᱾
pageInfo_Privacy_None2 = ᱵᱮᱜᱚᱨ ᱫᱟᱱᱟᱝ ᱛᱮ ᱤᱱᱴᱟᱨᱱᱮᱴ ᱪᱮᱛᱟᱱ ᱛᱮ ᱞᱟᱹᱭ ᱥᱚᱫᱚᱨ ᱠᱩᱞᱮᱱᱟ ᱮᱴᱟᱜ ᱦᱚᱲ ᱫᱟᱨᱟᱭ ᱛᱮ ᱩᱪᱟᱹ़ᱲᱚᱜ ᱡᱚᱦᱚᱜ ᱠᱚ ᱧᱮᱞ ᱫᱟᱲᱮᱭᱟᱜ ᱟ ᱾
pageInfo_Privacy_None4 = ᱟᱢᱮᱢ ᱧᱮᱞᱮᱫ ᱥᱟᱦᱴᱟ ᱤᱱᱴᱚᱨᱱᱮᱴ ᱪᱮᱛᱟᱱ ᱛᱮ ᱩᱪᱟᱹ़ᱲᱚᱠ ᱢᱟᱲᱟᱝ ᱨᱮ ᱟᱵᱝ ᱫᱟᱱᱟᱝᱟᱜ ᱞᱮᱱᱟ ᱾
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = ᱡᱩᱲᱟᱹᱣ ᱫᱟᱱᱟᱝ ᱠᱟᱱᱟ (%1$S, %2$S bit ᱪᱟᱹᱵᱤ, %3$S)
pageInfo_BrokenEncryption = ᱨᱟᱹᱯᱩᱫ ᱠᱟᱱ ᱫᱟᱱᱟᱝ (%1$S, %2$S bit ᱪᱟᱹᱵᱤ, %3$S)
pageInfo_Privacy_Encrypted1 = ᱟᱢᱮᱢ ᱧᱮᱞᱮᱫ ᱥᱟᱦᱴᱟ ᱤᱱᱴᱟᱨ ᱱᱮᱴ ᱪᱮᱛᱟᱱ ᱛᱮ ᱩᱪᱟᱹ़ᱲᱚᱠ ᱢᱟᱲᱟᱝ ᱫᱟᱱᱟᱝ ᱨᱮ ᱛᱟᱦᱮᱸ ᱞᱮᱱ ᱛᱟᱦᱮᱸᱱᱟ ᱾
pageInfo_Privacy_Encrypted2 = ᱫᱟᱱᱟᱝ ᱫᱚ ᱵᱟᱝ ᱟᱫᱮᱨ ᱪᱷᱚ ᱦᱚᱲᱠᱚ ᱠᱚᱢᱯᱩᱴᱚᱨ ᱵᱷᱤᱛᱨᱤ ᱨᱮ ᱦᱟᱹᱴᱤᱧᱚᱜ ᱠᱷᱚᱵᱚᱨ ᱠᱚ ᱠᱚᱵᱡᱟ ᱨᱮ ᱟᱸᱴ ᱠᱚᱣᱟᱭ ᱾ ᱢᱮᱱᱠᱷᱟᱱ ᱱᱚᱶᱟ ᱫᱚ ᱩᱱᱟᱹᱜ ᱥᱚᱢᱵᱷᱚᱵ ᱵᱟᱝ ᱠᱟᱱᱟ ᱡᱮ ᱱᱚᱶᱟ ᱥᱟᱦᱴᱟ ᱫᱚ ᱡᱟᱦᱟᱸᱭ ᱜᱮ ᱯᱟᱲᱦᱟᱣ ᱫᱟᱲᱮᱭᱟᱜᱼᱟᱭ ᱪᱮᱫᱟᱜ ᱥᱮ ᱱᱚᱶᱟ ᱫᱚ ᱱᱮᱴᱣᱟᱨᱠ ᱛᱮ ᱯᱟᱨᱚᱢᱚᱜ ᱠᱟᱱᱟ ᱾
pageInfo_MixedContent = ᱡᱚᱱᱚᱲᱟᱣ ᱦᱤᱸᱥ ᱞᱮᱠᱟᱛᱮ ᱫᱟᱱᱟᱝᱚᱜ ᱠᱟᱱᱟ
pageInfo_MixedContent2 = ᱟᱢᱟᱜ ᱧᱮᱞ ᱨᱮᱭᱟᱜ ᱥᱟᱦᱴᱟ ᱦᱟᱹᱴᱤᱧ ᱚᱱᱛᱚᱨ ᱡᱟᱞᱟᱢ ᱪᱮᱛᱟᱱ ᱛᱮ ᱩᱪᱟᱲᱚᱜ ᱢᱟᱬᱟᱝ ᱵᱟᱭ ᱞᱮᱱ ᱛᱟᱦᱮᱱᱟ᱾
pageInfo_WeakCipher = ᱱᱚᱣᱟ ᱣᱮᱵᱽᱥᱟᱭᱤᱴ ᱛᱮ ᱟᱢᱟᱜ ᱡᱩᱲᱟᱹᱣ ᱫᱚ ᱠᱚᱢᱡᱚᱨᱤᱭᱟ ᱫᱟᱱᱟᱝ ᱵᱮᱵᱷᱟᱨᱮᱫᱟᱭ ᱟᱨ ᱱᱚᱶᱟ ᱫᱚ ᱱᱤᱡᱚᱨᱟᱜ ᱞᱮᱠᱷᱟ ᱵᱟᱝ ᱠᱟᱱᱟ ᱾ ᱮᱴᱟᱜ ᱦᱚᱲ ᱟᱢᱟᱜ ᱡᱤᱱᱤᱥ ᱠᱚ ᱧᱮᱞ ᱫᱟᱲᱮᱭᱟᱜᱼᱟ  ᱥᱮ ᱣᱮᱵᱽᱥᱟᱭᱤᱴᱟᱜ ᱠᱟᱹᱢᱤᱦᱚᱨᱟ ᱠᱚ ᱵᱚᱫᱚᱞ ᱫᱟᱲᱮᱭᱟᱜᱼᱟ ᱾
pageInfo_CertificateTransparency_Compliant = ᱱᱚᱶᱟ ᱣᱮᱵᱽᱥᱟᱭᱤᱴ ᱫᱚ ᱯᱚᱨᱢᱟᱱ ᱥᱟᱠᱟᱢ ᱯᱟᱨᱫᱚᱨᱥᱤ ᱱᱤᱛᱤ ᱥᱟᱞᱟᱜ ᱡᱚᱲᱟᱣ ᱨᱮ ᱢᱮᱱᱟᱜᱼᱟ ᱾
# Token Manager
password_not_set = (ᱵᱟᱝ ᱥᱮᱴ ᱠᱟᱱᱟ)
