# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SaveImageTitle = Danndu Natal
SaveMediaTitle = Daɗndu mejaa
SaveVideoTitle = Danndu Widewoo
SaveAudioTitle = Danndu Ojoo
SaveLinkTitle = Danndu e Innde
WebPageCompleteFilter = Hello Geese, gasii
WebPageHTMLOnlyFilter = Hello Geese, HTML tan
WebPageXHTMLOnlyFilter = Hello Geese, XHTML tan
WebPageSVGOnlyFilter = Hello Geese, SVG tan
WebPageXMLOnlyFilter = Hello Geese, XML tan
