# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Składowane přizjewjenja
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = URL kopěrować
    .accesskey = k
launch-site-url-cmd =
    .label = URL wopytać
    .accesskey = U
copy-username-cmd =
    .label = Wužiwarske mjeno kopěrować
    .accesskey = u
edit-username-cmd =
    .label = Wužiwarske mjeno wobdźěłać
    .accesskey = b
copy-password-cmd =
    .label = Hesło kopěrować
    .accesskey = H
edit-password-cmd =
    .label = Hesło wobdźěłać
    .accesskey = d
search-filter =
    .accesskey = P
    .placeholder = Pytać
column-heading-site =
    .label = Sydło
column-heading-username =
    .label = Wužiwarske mjeno
column-heading-password =
    .label = Hesło
column-heading-time-created =
    .label = Prěnje wužiće
column-heading-time-last-used =
    .label = Poslednje wužiće
column-heading-time-password-changed =
    .label = Posledni raz změnjeny
column-heading-times-used =
    .label = Hustosć wužića
remove =
    .label = Wotstronić
    .accesskey = W
import =
    .label = Importować…
    .accesskey = I
close-button =
    .label = Začinić
    .accesskey = Z
show-passwords =
    .label = Hesła pokazać
    .accesskey = H
hide-passwords =
    .label = Hesła schować
    .accesskey = H
logins-description-all = Přizjewjenja za slědowace sydła so na wašim ličaku składuja
logins-description-filtered = Slědowace přizjewjenja wotpowěduja wašemu pytanju:
remove-all =
    .label = Wšě wotstronić
    .accesskey = W
remove-all-shown =
    .label = Wšě pokazane wotstronić
    .accesskey = W
remove-all-passwords-prompt = Ccheće woprawdźe wšě hesła wotstronić?
remove-all-passwords-title = Wšě hesła wotstronić
no-master-password-prompt = Chceće woprawdźe swoje hesła pokazać?
auto-fill-logins-and-passwords =
    .label = Přizjewjenja a hesła awtomatisce zapisać
