# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=Instalação do $ProductName$
Welcome_MessageWelcome=Bem-vindo ao %s!
Welcome_Message0=Você está iniciando a instalação do %s 2 Alpha 1.
Welcome_Message1=É altamente recomendado que você saia de todos programas do Windows antes de executar o programa de instalação.
Welcome_Message2=Clique em Cancelar para interromper a instalação e então saia de todos os programas. Clique em Avançar para continuar a instalação.
Welcome_Message3=Clique em Avançar para continuar a instalação do %s 2 Alpha 1.

License_Title=Acordo de licença do software
License_SubTitle=Termos e condições para usar este software.
License_Message0=Por favor, leia o acordo de licença. Use a barra de rolagem para ver o restante do texto.
License_Accept=&Eu aceito os termos da licença
License_Decline=Eu &NÃO aceito os termos da licença

Type_Title=Tipo da instalação
Type_SubTitle=Selecione as opções de instalação.
Type_Message0=Selecione o tipo de instalação que você prefere, depois clique em Avançar.

Standard_Short=&Padrão
Standard_Long=O Thunderbird será instalado com as opções mais comuns.

Custom_Short=P&ersonalizada
Custom_Long=Você pode selecionar quais opções deseja instalar. Recomendado para usuários experientes.

Select_Title=Selecione os componentes
Select_SubTitle=Componentes adicionais que aperfeiçoam o $ProductName$.
Select_Message0=Selecione os componentes adicionais que você deseja instalar, depois clique em Avançar.

Path_Title=Pasta de instalação
Path_SubTitle=Onde o $ProductName$ deverá ser instalado.
Path_Message0=O $ProductName$ será instalado na pasta:

Integration_Title=Configurar atalhos
Integration_SubTitle=Criar ícones do programa
Integration_Message0=Criar ícones para o $ProductShortName$:

Integration_Desktop=Na área de trabalho
Integration_StartMenu=Na pasta Programas do menu Iniciar
Integration_QuickLaunch=Na barra de inicialização rápida

SelectFolder_Title=Instalação do $ProductName$ - Selecione a pasta do programa
SelectFolder_Message0=A instalação criará ícones na pasta listada abaixo.  Você pode fornecer um outro nome ou selecionar um da lista de pastas existentes.  Clique em Avançar para continuar.

Advanced_Title=Instalação do $ProductName$ - Configurações avançadas
Advanced_Message0=Se a sua conexão com a internet necessitar de um servidor proxy, forneça o nome de usuário e a porta do servidor. Deixe os campos em branco se a conexão não exigir um proxy.

Install_Title=Sumário
Install_SubTitle=Pronto para instalar o $ProductName$.
Install_MessageInstall=Serão instalados estes componentes:
Install_MessageDownload=A instalação irá baixar e instalar estes componentes:
Install_Message0=Clique em Avançar para continuar.

Downloading_Title=Efetuando o download
Downloading_SubTitle=Baixando os componentes necessários...
Downloading_Blurb=A instalação está baixando os arquivos necessários para instalar o $ProductName$.
Downloading_FileName=Baixando o arquivo:
Downloading_Time=Tempo restante:

Installing_Title=Instalando
Installing_SubTitle=Instalando o $ProductName$...
Installing_Blurb=Instalando os arquivos do programa.
Installing_Status=Preparando arquivos:
Installing_Component=Instalando agora:

Success_Title=Instalação concluída
Success_Header=Instalação concluída
Success_Message0=O %s foi instalado com êxito.
Success_Message1=Clique em Concluir para finalizar a instalação.
Success_Launch=Iniciar o %s agora

Check_Message=O download do $ProductName$ foi efetuado com êxito. O $ProductNameInternal$ deverá ser encerrado para iniciar a instalação. Clique em OK para sair do $ProductNameInternal$ automaticamente e iniciar a instalação.
Check_FullMessage=O $ProductNameInternal$ deverá ser encerrado para iniciar a instalação. Clique em OK para sair do $ProductNameInternal$ automaticamente e iniciar a instalação.
Check_Wait=Encerrando o $ProductNameInternal$.  Por favor, aguarde...

Component_XPCOM=Cross Platform COM
Component_Mail=$ProductName$
Component_Offline=Suporte offline
Component_Offline_Long=Adiciona o suporte offline para o $ProductName$.
Component_RSS=Suporte RSS
Component_RSS_Long=Adiciona suporte RSS para o $ProductName$.
Component_QFA=Quality Feedback Agent
Component_QFA_Long=Comunique os travamentos do $ProductName$.
