# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Składowaś
dialogTitleAddBookmark = Nowe cytańske znamje
dialogTitleAddMulti = Nowe cytańske znamjenja
dialogTitleEdit = Kakosći za "%S"
dialogTitleAddNewBookmark2 = Cytańske znamje pśidaś
dialogTitleEditBookmark = „%S“ wobźěłaś
dialogTitleEditBookmark2 = Cytańske znamje wobźěłaś
dialogTitleAddBookmarkFolder = Zarědnik cytańskich znamjenjow pśidaś
dialogTitleEditBookmarkFolder = Zarědnik cytańskich znamjenjow wobźěłaś
bookmarkAllTabsDefault = [Mě zarědnika]
newFolderDefault = Nowy zarědnik
newBookmarkDefault = Nowe cytańske znamje
