# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Tenggang Waktu Habis
openFile = Buka Berkas
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Cari lewat %1$S untuk “%2$S”
contextMenuSearch.accesskey = C
contextMenuPrivateSearch = Cari di Jendela Pribadi
contextMenuPrivateSearch.accesskey = p
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Cari lewat %S di Jendela Pribadi
contextMenuPrivateSearchOtherEngine.accesskey = l
bookmarkAllTabsDefault = [Nama Folder]
unsignedAddonsDisabled.message = Satu atau beberapa pengaya terinstal tidak dapat diverifikasi dan telah dinonaktifkan.
unsignedAddonsDisabled.learnMore.label = Pelajari Lebih Lanjut
unsignedAddonsDisabled.learnMore.accesskey = P
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Terakhir diakses %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = Tautan %S://
crashedpluginsMessage.title = Plugin %S berhenti bekerja tiba-tiba.
crashedpluginsMessage.reloadButton.label = Muat ulang laman
crashedpluginsMessage.reloadButton.accesskey = M
crashedpluginsMessage.submitButton.label = Kirim laporan mogok
crashedpluginsMessage.submitButton.accesskey = K
crashedpluginsMessage.learnMore = Pelajari Lebih Lanjut…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Apakah yang dimaksud adalah buka %S?
keywordURIFixup.goTo = Ya, buka %S
keywordURIFixup.goTo.accesskey = Y
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Perbarui ke %S
update.downloadAndInstallButton.accesskey = P
menuOpenAllInTabs.label = Buka Semua di Tab
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Muat ulang laman
tabHistory.goBack = Mundur ke laman ini
tabHistory.goForward = Maju ke laman ini
# URL Bar
pasteAndGo.label = Tempelkan & Kunjungi
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Muat ulang laman ini (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Berhenti memuat laman ini (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Setel ulang tingkat perbesaran (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Aktif/nonaktifkan tampilan baca (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, Setel ulang tingkat perbesaran
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Tampilkan markah Anda (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Tampilkan kemajuan unduhan yang sedang berlangsung (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Buka jendela baru (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Buka tab baru (%S)
newTabContainer.tooltip = Buka tab baru (%S)\nTekan dan tahan untuk membuka tab kontainer baru
newTabAlwaysContainer.tooltip = Pilih kontainer untuk membuka tab baru
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Izinkan %S untuk menggunakan data gambar canvas HTML5?
canvas.siteprompt2.warning = Ini dapat digunakan untuk mengidentifikasi komputer Anda secara unik.
canvas.block = Blokir
canvas.block.accesskey = B
canvas.allow2 = Izinkan
canvas.allow2.accesskey = I
canvas.remember2 = Ingat pilihan ini
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Diverifikasi oleh: %S
identity.identified.verified_by_you = Anda telah membuat pengecualian keamanan untuk situs ini
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Sertifikat diterbitkan untuk: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Tidak Aman
identity.notSecure.tooltip = Sambungan tidak aman
identity.extension.label = Ekstensi (%S)
identity.extension.tooltip = Dimuat oleh ekstensi: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Perkecil (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Setel ulang tingkat perbesaran (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Perbesar (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Potong (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Salin (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Tempel (%S)
geolocation.allow = Izinkan
geolocation.allow.accesskey = I
geolocation.block = Blokir
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Ini akan membuka pengaturan lokasi sistem. Berikan izin lokasi kepada %S.
geolocation.shareWithSite4 = Izinkan %S untuk mengakses lokasi Anda?
geolocation.shareWithFile4 = Izinkan berkas lokal ini untuk mengakses lokasi Anda?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Izinkan %1$S untuk memberi akses kepada %2$S untuk mengakses lokasi Anda?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Berikan izin akses lokasi pada %S di pengaturan sistem.
geolocation.systemSettingsTitle = Menunggu Izin Lokasi
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Sistem akan meminta Anda untuk memberikan izin ini kepada %S.
geolocation.remember = Ingat pilihan ini
# Virtual Reality Device UI
xr.allow2 = Izinkan
xr.allow2.accesskey = I
xr.block = Blokir
xr.block.accesskey = B
xr.shareWithSite4 = Izinkan %S untuk mengakses perangkat realitas virtual? Ini bisa memaparkan informasi rahasia.
xr.shareWithFile4 = Izinkan berkas lokal ini untuk mengakses perangkat realitas virtual? Ini bisa memaparkan informasi rahasia.
xr.remember = Ingat pilihan ini
# Persistent storage UI
persistentStorage.allow = Izinkan
persistentStorage.allow.accesskey = I
persistentStorage.block.label = Blokir
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Izinkan %S untuk menyimpan data di penyimpanan persisten?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Izinkan
webNotifications.allow2.accesskey = I
webNotifications.notNow = Jangan Sekarang
webNotifications.notNow.accesskey = n
webNotifications.never = Jangan Pernah Izinkan
webNotifications.never.accesskey = g
webNotifications.alwaysBlock = Selalu Blokir
webNotifications.alwaysBlock.accesskey = S
webNotifications.block = Blokir
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Izinkan %S untuk mengirim pemberitahuan?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S ingin mengakses aplikasi dan layanan lain di perangkat ini.
localhost.remember2 = Ingat pilihan saya untuk situs ini
localhost.allowlabel = Izinkan
localhost.blocklabel = Blokir
localhost.allow.accesskey = A
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S ingin mengakses aplikasi dan layanan pada perangkat yang terhubung ke jaringan lokal Anda.
localNetwork.remember2 = Ingat pilihan saya untuk situs ini
localNetwork.allowLabel = Izinkan
localNetwork.allow.accesskey = A
localNetwork.blockLabel = Blokir
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Kabur!
safebrowsing.getMeOutOfHereButton.accessKey = K
safebrowsing.deceptiveSite = Situs Tipuan!
safebrowsing.notADeceptiveSiteButton.label = Ini bukan situs tipuan…
safebrowsing.notADeceptiveSiteButton.accessKey = t
safebrowsing.reportedAttackSite = Telah Dilaporkan Sebagai Situs Penyerang!
safebrowsing.notAnAttackButton.label = Situs ini bukan situs penyerang…
safebrowsing.notAnAttackButton.accessKey = s
safebrowsing.reportedUnwantedSite = Telah Dilaporkan Sebagai Situs Perangkat Lunak yang Tidak Diinginkan!
safebrowsing.reportedHarmfulSite = Laporkan Situs Berbahaya!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Cari %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Mulai ulang %S dalam Mode Pemecahan Masalah?
troubleshootModeRestartPromptMessage = Ekstensi, tema, dan setelan khusus Anda akan dinonaktifkan sementara.
troubleshootModeRestartButton = Mulai Ulang
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Laman ini memperlambat %1$S. Untuk mempercepat peramban, hentikan laman ini.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Sebuah laman web memperlambat %1$S. Untuk mempercepat peramban, hentikan laman tersebut.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = “%1$S” memperlambat %2$S. Untuk mempercepat peramban, hentikan laman tersebut.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = “%1$S” memperlambat %2$S. Untuk mempercepat peramban, hentikan ekstensi tersebut.
processHang.add-on.learn-more.text = Pelajari lebih lanjut
processHang.button_stop2.label = Hentikan
processHang.button_stop2.accessKey = H
processHang.button_debug.label = Debug Skrip
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Tampilkan jendela dalam layar penuh (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Pindahkan Bilah Samping ke Kiri
sidebar.moveToRight = Pindahkan Bilah Samping ke Kanan
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Anda harus mengaktifkan DRM untuk memainkan suara atau video pada laman ini.
emeNotifications.drmContentDisabled.button.label = Aktifkan DRM
emeNotifications.drmContentDisabled.button.accesskey = A
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S sedang memasang komponen yang dibutuhkan untuk memutar audio atau video pada laman ini. Coba lagi nanti.
emeNotifications.unknownDRMSoftware = Tidak dikenal
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Ubahsuai %S
decoder.noCodecs.button = Pelajari caranya
decoder.noCodecs.accesskey = P
decoder.noCodecsLinux.message = Untuk memutar video, Anda mungkin harus menginstal kodek video yang dibutuhkan.
decoder.noHWAcceleration.message = Untuk meningkatkan kualitas video, Anda mungkin harus menginstal Media Feature Pack dari Microsoft.
decoder.noPulseAudio.message = Untuk memutar audio, Anda mungkin harus menginstal perangkat lunak PulseAudio.
decoder.unsupportedLibavcodec.message = libavcodec mungkin rentan atau tidak didukung, dan harus diperbarui untuk memutar video.
decoder.decodeError.message = Masalah terjadi ketika mendekode sumber daya media.
decoder.decodeError.button = Laporkan Masalah Situs
decoder.decodeError.accesskey = L
decoder.decodeWarning.message = Masalah yang bisa diperbaiki terjadi ketika mendekode sumber daya media.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Anda harus masuk ke dalam jaringan ini sebelum Anda dapat mengakses Internet.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Buka laman masuk jaringan
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Izin untuk %S
permissions.remove.tooltip = Hilangkan perizinan ini dan tanyakan lagi
permissions.fullscreen.promptCanceled = Permintaan izin tertunda yang dibatalkan: permintaan izin tidak boleh diajukan sebelum memasuki layar penuh DOM.
permissions.fullscreen.fullScreenCanceled = Keluar dari layar penuh DOM: permintaan izin tidak boleh diajukan saat dalam layar penuh DOM.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bit
aboutDialog.architecture.thirtyTwoBit = 32-bit
midi.allow.label = Izinkan
midi.allow.accesskey = I
midi.block.label = Blokir
midi.block.accesskey = B
midi.remember = Ingat keputusan ini
midi.shareWithFile = Izinkan berkas lokal ini untuk mengakses perangkat MIDI Anda?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Izinkan %S mengakses perangkat MIDI Anda?
midi.shareSysexWithFile = Izinkan berkas lokal ini untuk mengakses perangkat MIDI Anda dan mengirim/menerima pesan SysEx?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Izinkan %S untuk mengakses perangkat MIDI Anda dan mengirim/menerima pesan SysEx?
serial.allow.label = Izinkan
serial.allow.accesskey = A
serial.block.label = Blokir
serial.block.accesskey = B
serial.shareWithFile = Izinkan berkas lokal ini mengakses port serial Anda?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Izinkan %S untuk mengakses port serial Anda?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Kembali
storageAccess1.Allow.label = Izinkan
storageAccess1.Allow.accesskey = A
storageAccess1.DontAllow.label = Blokir
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Izinkan %1$S untuk menggunakan kukinya pada %2$S?
storageAccess1.hintText = Anda mungkin ingin memblokir akses jika tidak jelas mengapa %1$S membutuhkan data ini.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Cari di web untuk “%S”
