# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=Ndzulamiso wa $ProductName$
Welcome_MessageWelcome=U amukeriwile eka %s!
Welcome_Message0=You are about to install %s 2 Alpha 1.
Welcome_Message1=Ku bumabumeriwa swinene leswaku u huma eka tiphurogireme ta Windows hinkwawo u nga si tirhisa Ndzulamiso wa phurogireme leyi.
Welcome_Message2=Tshikelela Khansele ku suka eka Ndzulamiso kutani u pfala tiphurogireme hinkwato leti a wu ti tirhisa.  Tshikelela Leswi landzelaka ku ya emahlweni na Ndzulamiso wa phurogireme.
Welcome_Message3=Click Next to continue installing %s 2 Alpha 1.

License_Title=Ntwanano wa Layisense ya Switirhisiwa
License_SubTitle=Titheme na swipimelo swa ku tirhisa switirhisiwa.
License_Message0=Hlaya mpfumelelo lowu landzelaka wa layisense. Tirhisa barha yo secha ku vona mpfumelelano hinkwawo.
License_Accept=&Ndzi amukela swipimelo hinkwaswo swa Mpfumelelo wa Layisense
License_Decline=A nd&zi amukeli swipimelo swa Mpfumelelo wa Layisense

Type_Title=Lulamisa Muxaka
Type_SubTitle=Hlawula ndzulamiso wa tiopxini.
Type_Message0=Hlawulo muxaka wa ndzulamiso lowu u wu rhandzaka, kutani u tshikelela Leswi landzelaka.

Standard_Short=&Xitandati
Standard_Long=Thunderbird yi ta nghenisiwa hi swihlawulekisi swo hambana.

Custom_Short=&Khasimende
Custom_Long=U nga ha hlawula minhlawulo ya wena nwíni yo yi nghenisa. Leswi swi bumabumeriwa vatirhisi va ntokoto.

Select_Title=Hlawula swiphemu
Select_SubTitle=Swiphemu swin'wana swo engetela swa $ProductName$.
Select_Message0=Hlawula swiphemu swin'wana u lavaka ku swi nghenisa ivi u tshikelela Leswi landzelaka.

Path_Title=Nghenisa folidara
Path_SubTitle=Where $ProductName$ will be installed.
Path_Message0=$ProductName$ ri ta nghenisiwa eka folidara leyi landzelaka:

Integration_Title=Lulamisa tindlela to koma
Integration_SubTitle=Tumbuluxa tiiyikhoni ta Phurogireme
Integration_Message0=Tumbuluxa tiiyikhoni ta $ProductShortName$:

Integration_Desktop=Eka Desikithopo
Integration_StartMenu=Eka folidara ya phurogireme ya menyu wo sungula
Integration_QuickLaunch=Eka bara ya mina yo sungula hi xihatla

SelectFolder_Title=$ProductName$ Ndzulamiso - Hlawula Folidara ya Phurogireme
SelectFolder_Message0=Ndzulamiso wu ta engetela tiayikon leti phurogimetiweke ekafoldara ya phurogireme leyi tsariweke ehansi.  U nga tsala vito ra foldara yintshwa, kumbe u hlawula yin'we eka nongonoko wa tifoldara leti nga kona.  Tshikelela landzelaka ku ya emahlweni.

Advanced_Title=$ProductName$ Ndzulamiso - Ndzulamiso wa le henhla
Advanced_Message0=Loko nhlanganiso wa Internete ya wena wu lava sevha ya prozi, nghenisa vito ra wena ra sevha na mahungu ya photo.  Loko nhlanganiso wa Internete ya wena wu nga lavi sevha ya prozi, tshika rivala ri nga ri na nchumu.

Install_Title=Nkatsakanyo
Install_SubTitle=Tiyimiserile ku nghenisa $ProductName$.
Install_MessageInstall=Ndzulamiso wu ta nghenisa swiphemu leswi landzelaka:
Install_MessageDownload=Ndzulamiso wu ta panga ni ku nghenisa swiphemu leswi landzelaka:
Install_Message0=Tshikelela leswi landzelaka ku ya emahlweni.

Downloading_Title=Panga
Downloading_SubTitle=Ku laveka swiphemu swo panga...
Downloading_Blurb=Ndzulamiso wu le ku pangeni tifayili leti lavekaka to nghenisa $ProductName$.
Downloading_FileName=Ku le ku pangiweni sweswi:
Downloading_Time=Nkarhi lowu nga sala:

Installing_Title=Ku nghenisa
Installing_SubTitle=Nghenisa $ProductName$...
Installing_Blurb=Ndzulamiso wu le ku ngheniseni tifayili ta apulikhexini.
Installing_Status=Ku lulamisiwa fayili:
Installing_Component=Ku le ku nghenisiweni sweswi:

Success_Title=Ku nghenisa swi herile
Success_Header=Ku nghenisa swi herile
Success_Message0=%s was successfully installed.
Success_Message1=Tshikelela Hetile ku hetisa Ndzulamiso.
Success_Launch=Launch %s now.

Check_Message=Mpango wa $ProductName$ wu humelerile. $ProductNameInternal$ ri fanele ku pfariwa ku ya emahlweni no nghenisa. Tshikelela OK ku huma $ProductNameInternal$ hi othomethiki u sungula ku nghenisa.
Check_FullMessage=$ProductNameInternal$ ri fanele ku pfariwa ku ya emahlweni na ku nghenisa. Tshikelela OK ku huma eka $ProductNameInternal$ hi othomethiki na ku sungula ku nghenisa.
Check_Wait=Ku pfala $ProductNameInternal$.  Yima...

Component_XPCOM=Khiroso-Pulatifomo COM
Component_Mail=$ProductName$
Component_Offline=Nseketelo wa Ofolayini
Component_Offline_Long=Engetela Nseketelo wa Ofolayini wa $ProductName$.
Component_RSS=Nseketelo wa RSS
Component_RSS_Long=Engetela Nseketelo wa RSS eka $ProductName$.
Component_QFA=Ejenti ya Nthleriselo wa Timhaka ta Nkoka
Component_QFA_Long=ku tivisa $ProductName$ tsema mahungu
