# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Meklē { $host }…
network-connection-status-connected = Pieslēdzies pie { $host }…
network-connection-status-sending-request = Sūta pieprasījumu uz { $host }…
network-connection-status-transferring-data = Pārsūta datus no { $host }…
network-connection-status-connecting = Pieslēdzas pie { $host }…
network-connection-status-read = Lasa { $host }
network-connection-status-wrote = Ierakstīja { $host }
network-connection-status-waiting = Gaida uz { $host }…
network-connection-status-looked-up = Uzmeklēja { $host }…
network-connection-status-tls-handshake = Veic TLS rokasspiedienu ar { $host }…
network-connection-status-tls-handshake-finished = TLS rokasspiediens pabeigts { $host }…
