# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=Kusethwa kwe$ProductName$
Welcome_MessageWelcome=Wemukelekile ku %s!
Welcome_Message0=You are about to install %s 2 Alpha 1.
Welcome_Message1=Kuyanconywa kakhulu kutsi uphume kuto tonkhe tinhlelo tema Windows ungakacali kuSetha luhlelo.
Welcome_Message2=Chafata Yesula utewuphuma kulokusethwa bese uvala tonkhe tinhlelo lotivulile.  Chafata Lokulandzelako utewuchubeka nekusethwa kweluhlelo.
Welcome_Message3=Click Next to continue installing %s 2 Alpha 1.

License_Title=Sivumelwane selayisense yesoftiwe
License_SubTitle=Imibandzela nemidanti yekusebentisa lesoftiwe.
License_Message0=Uyacelwa fundza lesivumelwane selayisense lesilandzelako. Sebentisa ibha yekugicita kuze ubone konkhe lokumalunga nalesivumelwane.
License_Accept=Ngi&yayemukela lemibandzela yalesivumelwane salelayisense
License_Decline=Angiye&mukeli lemibandzela Yelesivumelwane Salelayisense

Type_Title=Setha inhlobo
Type_SubTitle=Khetsa intfo yekutikhetsela yekusetha.
Type_Message0=Khetsa inhlobo yekusetha loyitsandzako, bese uchafata Lokulandzelako.

Standard_Short=&Sitandathi
Standard_Long=Thunderbird utawufakwa nekwekutikhetsela lokuvamise kakhulu.

Custom_Short=&Ikhastomu
Custom_Long=Ungakhetsa kutikhetsela kwemuntfu kutsi kufakwe. Kuncomeka kakhulu kubasebentisi lababochwephesha.

Select_Title=Khetsa takhi
Select_SubTitle=Takhi letingetulu letikhutsata $ProductName$.
Select_Message0=Khetsa letinye takhi letingetulu lofuna kutifaka, bese uchafata Lokulandzelako.

Path_Title=Faka ifolda
Path_SubTitle=Lapho kutawufakwa khona $ProductName$.
Path_Message0=$ProductName$ litawufakwa kulamafolda lalandzelako:

Integration_Title=Setha letijubako
Integration_SubTitle=Kwakha ema-ayikhoni eluhlelo
Integration_Message0=Kwakha ema-ayikhoni a $ProductShortName$:

Integration_Desktop=Kubusokhompyutha yami
Integration_StartMenu=Kufolda yami yeMenyu Yekucala Tinhlelo
Integration_QuickLaunch=Kubha yami yaphutfuma wetfule

SelectFolder_Title=Setha $ProductName$ - Khetsa ifolda yeluhlelo
SelectFolder_Message0=Setha utakwengeta luhlelo lwema-ayikhoni kufolda yeluhlelo lelandzela ngentasi.  Ungalithayipha libito lenhlobo lensha, nome ukhetse yinye kuloluhlu lwemafolda lakhona.  Chafata Lokulandzelako kuze uchubeke.

Advanced_Title=Setha $ProductName$ - Tinhlelo letichubekile
Advanced_Message0=Nangabe kuchumana kwe-Inthanethi yakho kudzinga iproksi yesilondvoloti, faka libito lesilondvoloti sakho nelwati lwesikhumulo.  Nangabe kuchumana kwe-Inthanethi yakho akuyidzingi iproksi yesilondvoloti, shiya leto tikhala tite lutfo.

Install_Title=Sifishaniso
Install_SubTitle=Sewulungele kufaka $ProductName$.
Install_MessageInstall=Kusetha sekuitawufaka letakhi letilandzelako:
Install_MessageDownload=Kusetha sekutawulayisha bese kufaka letakhi letilandzelako:
Install_Message0=Chafata Lokulandzelako kuze uchubeke.

Downloading_Title=Kulayishela
Downloading_SubTitle=Kulayishela kudzinga takhi...
Downloading_Blurb=Kusetha kulayishela emafayela ladzingekako kuze kufakwe $ProductName$.
Downloading_FileName=Kwanyalo iyalayishela:
Downloading_Time=Sikhatsi lesisele:

Installing_Title=Kufaka
Installing_SubTitle=Kufaka $ProductName$...
Installing_Blurb=Kusetha sekufaka kusetjentiswa kwemafayela.
Installing_Status=Kulungisa lifayela:
Installing_Component=Kwanyalo iyafaka:

Success_Title=Kuphelile kufaka
Success_Header=Kuphelile kufaka
Success_Message0=%s was successfully installed.
Success_Message1=Chafata Cedza kuze ucedzele kusetha.
Success_Launch=Launch %s now.

Check_Message=Kulayishelwa kwa $ProductName$ kuphumelele kahle. $ProductNameInternal$ kufanele livalwe kuze kuchutjekwe nekufakwa. Chafata OK utewuphuma ku $ProductNameInternal$ othomathikhali nekucalisa kufaka.
Check_FullMessage=$ProductNameInternal$ kufanele avalwe kuze kuchutjekwe nekufaka. Chafata OK utewuphuma othomethikhali ku $ProductNameInternal$ utewucala kufaka.
Check_Wait=Kuvala $ProductNameInternal$.  Uyacelwa lindza...

Component_XPCOM=Yengca-iPlatfomu COM
Component_Mail=$ProductName$
Component_Offline=Kusekela lokungaphandle kwelilayini
Component_Offline_Long=Yengeta kusekela lokungaphandle kwelilayini kwa $ProductName$ Liposi.
Component_RSS=RSS Sisekelo
Component_RSS_Long=Yengeta RSS sisekelo ku $ProductName$.
Component_QFA=Lincusa lekhwality yekubika
Component_QFA_Long=yekubika $ProductName$ lwati lwekufahlaka
