# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Jiggo Ɗoworde
import-from =
    { PLATFORM() ->
        [windows] Jiggo Cuɓe, Maantore, Aslol, Finndeeji e keɓe goɗɗe iwdi e:
       *[other] Jiggo Cuɓoraaɗe, Maantore, Aslol, Finndeeji e keɓe goɗɗe iwdi e:
    }
import-from-bookmarks = Jiggo Maantore iwɗe e:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-nothing =
    .label = Hoto jiggo hay baɗte
    .accesskey = H
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chrome-beta =
    .label = Chrome Beta
    .accesskey = B
import-from-chrome-dev =
    .label = Chrome Gol
    .accesskey = D
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = x
import-from-360se =
    .label = 360 Secure Browser
    .accesskey = 3
no-migration-sources = Alaa jaaɓnirɗe jogiiɗe maantore, aslol walla finndeeji njiytaa.
import-source =
    .label = Jiggo Teelte e Keɓe
import-items-title =
    .label = Teme Jiggeteeɗe
import-items-description = Suɓo hol teme njiggetee:
import-migrating-title =
    .label = Nana jiggoo…
import-migrating-description = Ɗee-ɗoo teme ngoni ko e jiggeede…
import-select-profile-title =
    .label = Labo Heftinirde
import-select-profile-description = Ɗee-ɗoo keftinirɗe ena ngoodi ngam jiggaade e mum'en:
import-done-title =
    .label = Jiggagol Gasii
import-done-description = Ɗee-ɗoo teme njiggoraama no moƴƴirta:
import-close-source-browser = Tiiɗno teeŋtin wonde wanngorde suɓaande ndee ko uddiinde hade maa jokkude.
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = Iwde e { $source }
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Secure Browser
imported-safari-reading-list = Nana Tara Doggol (Iwde e Safari)
imported-edge-reading-list = Doggol Tarol (Iwde e Safari)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Cuɓe Enternet
    .value = Cuɓe Enternet
browser-data-edge-1 =
    .label = Teelte
    .value = Teelte
browser-data-safari-1 =
    .label = Cuɓoraaɗe
    .value = Cuɓoraaɗe
browser-data-chrome-1 =
    .label = Cuɓoraaɗe
    .value = Cuɓoraaɗe
browser-data-canary-1 =
    .label = Cuɓoraaɗe
    .value = Cuɓoraaɗe
browser-data-360se-1 =
    .label = Cuɓoraaɗe
    .value = Cuɓoraaɗe
browser-data-ie-2 =
    .label = Kukiije
    .value = Kukiije
browser-data-edge-2 =
    .label = Kukiije
    .value = Kukiije
browser-data-safari-2 =
    .label = Kukiije
    .value = Kukiije
browser-data-chrome-2 =
    .label = Kukiije
    .value = Kukiije
browser-data-canary-2 =
    .label = Kukiije
    .value = Kukiije
browser-data-firefox-2 =
    .label = Kukiije
    .value = Kukiije
browser-data-360se-2 =
    .label = Kukiije
    .value = Kukiije
browser-data-ie-4 =
    .label = Aslol Peeragol
    .value = Aslol Peeragol
browser-data-edge-4 =
    .label = Aslol Peeragol
    .value = Aslol Peeragol
browser-data-safari-4 =
    .label = Aslol Peeragol
    .value = Aslol Peeragol
browser-data-chrome-4 =
    .label = Aslol Peeragol
    .value = Aslol Peeragol
browser-data-canary-4 =
    .label = Aslol Peeragol
    .value = Aslol Peeragol
browser-data-360se-4 =
    .label = Aslol Peeragol
    .value = Aslol Peeragol
browser-data-ie-8 =
    .label = Danndaama iwde e Aslol
    .value = Danndaama iwde e Aslol
browser-data-edge-8 =
    .label = Ko danndaa e Aslol
    .value = Ko danndaa e Aslol
browser-data-safari-8 =
    .label = Danndaama iwde e Aslol
    .value = Danndaama iwde e Aslol
browser-data-chrome-8 =
    .label = Danndaama iwde e Aslol
    .value = Danndaama iwde e Aslol
browser-data-canary-8 =
    .label = Danndaama iwde e Aslol
    .value = Danndaama iwde e Aslol
browser-data-firefox-8 =
    .label = Danndaama iwde e Aslol
    .value = Danndaama iwde e Aslol
browser-data-360se-8 =
    .label = Danndaama iwde e Aslol
    .value = Danndaama iwde e Aslol
browser-data-ie-16 =
    .label = Finndeeji Danndaaɗi
    .value = Finndeeji Danndaaɗi
browser-data-edge-16 =
    .label = Finndeeji Danndaaɗi
    .value = Finndeeji Danndaaɗi
browser-data-safari-16 =
    .label = Finndeeji Danndaaɗi
    .value = Finndeeji Danndaaɗi
browser-data-chrome-16 =
    .label = Finndeeji Danndaaɗi
    .value = Finndeeji Danndaaɗi
browser-data-canary-16 =
    .label = Finndeeji Danndaaɗi
    .value = Finndeeji Danndaaɗi
browser-data-firefox-16 =
    .label = Finndeeji Danndaaɗi
    .value = Finndeeji Danndaaɗi
browser-data-360se-16 =
    .label = Finndeeji Danndaaɗi
    .value = Finndeeji Danndaaɗi
browser-data-ie-32 =
    .label = Cuɓaɗe
    .value = Cuɓaɗe
browser-data-edge-32 =
    .label = Cuɓaɗe
    .value = Cuɓaɗe
browser-data-safari-32 =
    .label = Maantore
    .value = Maantore
browser-data-chrome-32 =
    .label = Maantore
    .value = Maantore
browser-data-canary-32 =
    .label = Maantore
    .value = Maantore
browser-data-360se-32 =
    .label = Maantore
    .value = Maantore
browser-data-ie-64 =
    .label = Keɓe Goɗɗe
    .value = Keɓe Goɗɗe
browser-data-edge-64 =
    .label = Keɓe Goɗɗe
    .value = Keɓe Goɗɗe
browser-data-safari-64 =
    .label = Keɓe Goɗɗe
    .value = Keɓe Goɗɗe
browser-data-chrome-64 =
    .label = Keɓe Goɗɗe
    .value = Keɓe Goɗɗe
browser-data-canary-64 =
    .label = Keɓe Goɗɗe
    .value = Keɓe Goɗɗe
browser-data-firefox-other-64 =
    .label = Keɓe Goɗɗe
    .value = Keɓe Goɗɗe
browser-data-360se-64 =
    .label = Keɓe Goɗɗe
    .value = Keɓe Goɗɗe
browser-data-firefox-128 =
    .label = Kenorɗe e Tabbe
    .value = Kenorɗe e Tabbe
