#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title Закладки
#define bookmarks_heading Закладки

# LOCALIZATION NOTE (bookmarks_addons):
# link title for https://ru.add-ons.mozilla.com/ru/firefox/bookmarks/
#define bookmarks_addons Расширения для работы с закладками

#define bookmarks_toolbarfolder Папка панели закладок
#define bookmarks_toolbarfolder_description Добавьте закладки в эту папку чтобы увидеть их на панели закладок

# LOCALIZATION NOTE (getting_started):
# link title for http://www.mozilla.com/ru/firefox/central/
#define getting_started Начальная страница

# LOCALIZATION NOTE (latest_headlines):
# link title for the live bookmarks sample, a redirect on
# http://fxfeeds.mozilla.com/ru/firefox/headlines.xml
# Changing the redirect is subject to approval of l10n-drivers.
#define latest_headlines Лента новостей

# LOCALIZATION NOTE (firefox_heading):
# Firefox links folder name
#define firefox_heading Mozilla Firefox

# LOCALIZATION NOTE (firefox_help):
# link title for http://www.mozilla.com/ru/firefox/help/
#define firefox_help Справка и руководства

# LOCALIZATION NOTE (firefox_customize):
# link title for http://www.mozilla.com/ru/firefox/customize/
#define firefox_customize Настройка Firefox

# LOCALIZATION NOTE (firefox_community):
# link title for http://www.mozilla.com/ru/firefox/community/
#define firefox_community Присоединяйтесь к сообществу

# LOCALIZATION NOTE (firefox_about):
# link title for http://www.mozilla.com/ru/firefox/about/
#define firefox_about О нас

#unfilter emptyLines
