# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title Закладки
#define bookmarks_heading Закладки

#define bookmarks_toolbarfolder Папка панели закладок
#define bookmarks_toolbarfolder_description Добавьте закладки в эту папку чтобы увидеть их на панели закладок

# LOCALIZATION NOTE (getting_started):
# link title for http://www.mozilla.com/ru/firefox/central/
#define getting_started Начальная страница

# LOCALIZATION NOTE (firefox_heading):
# Firefox links folder name
#define firefox_heading Mozilla Firefox

# LOCALIZATION NOTE (firefox_help):
# link title for http://www.mozilla.com/ru/firefox/help/
#define firefox_help Справка и руководства

# LOCALIZATION NOTE (firefox_customize):
# link title for http://www.mozilla.com/ru/firefox/customize/
#define firefox_customize Настройка Firefox

# LOCALIZATION NOTE (firefox_community):
# link title for http://www.mozilla.com/ru/firefox/community/
#define firefox_community Присоединяйтесь к сообществу

# LOCALIZATION NOTE (firefox_about):
# link title for http://www.mozilla.com/ru/firefox/about/
#define firefox_about О нас

#unfilter emptyLines
