# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Tempo elĉerpita
openFile = Malfermi dosieron
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Serĉi "%2$S" per %1$S
contextMenuSearch.accesskey = S
contextMenuPrivateSearch = Serĉi en privata fenestro
contextMenuPrivateSearch.accesskey = p
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Serĉi per %S en privata fenestro
contextMenuPrivateSearchOtherEngine.accesskey = p
bookmarkAllTabsDefault = [nomo de dosierujo]
unsignedAddonsDisabled.message = Unu aŭ pluraj instalitaj aldonaĵoj ne povas esti kontrolitaj kaj do ili estis malaktivigitaj.
unsignedAddonsDisabled.learnMore.label = Pli da informo
unsignedAddonsDisabled.learnMore.accesskey = P
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Lasta aliro %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = Ligiloj %S://
crashedpluginsMessage.title = La kromprogramo %S paneis.
crashedpluginsMessage.reloadButton.label = Reŝargi paĝon
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = Sendi raporton pri paneo
crashedpluginsMessage.submitButton.accesskey = S
crashedpluginsMessage.learnMore = Pli da informo…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Ĉu vi volis iri al %S?
keywordURIFixup.goTo = Jes, bonvolu iri al %S
keywordURIFixup.goTo.accesskey = J
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Ĝisdatigi al %S
update.downloadAndInstallButton.accesskey = d
menuOpenAllInTabs.label = Malfermi ĉiujn en langetoj
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Reŝargi tiun ĉi paĝon
tabHistory.goBack = Iri reen al tiu paĝo
tabHistory.goForward = Iri antaŭen al tiu paĝo
# URL Bar
pasteAndGo.label = Alglui kaj iri tien
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Reŝargi nunan paĝon (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Halti ŝargadon de ĉi tiu paĝo (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Remeti normalan grandon (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Ŝalti/malŝalti legilan vidon (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, Remeti normalan grandon
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Montri viajn legosignojn (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Montri la progreson de kurantaj elŝutoj (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Malfermi novan fenestron (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Malfermi novan langeton (%S)
newTabContainer.tooltip = Malfermi novan langeton (%S)\nPremi kaj teni por malfermi novan ingan langeton
newTabAlwaysContainer.tooltip = Elekti ingon por malfermi novan langeton
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Ĉu permesi al %S uzi bildan informon de HTML5 kanvaso?
canvas.siteprompt2.warning = Per tio oni povus unike identigi vian komputilon.
canvas.block = Bloki
canvas.block.accesskey = B
canvas.allow2 = Permesi
canvas.allow2.accesskey = P
canvas.remember2 = Memori tiun ĉi decidon
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Kontrolita de: %S
identity.identified.verified_by_you = Vi aldonis sekurecan escepton por tiu ĉi retejo.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Atestilo eldonita por: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Nesekura
identity.notSecure.tooltip = Nesekura konekto
identity.extension.label = Etendaĵo (%S)
identity.extension.tooltip = Ŝargita de etendaĵo: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Etigi (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Remeti normalan grandon (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Grandigi (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Eltondi (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Kopii (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Alglui (%S)
geolocation.allow = Permesi
geolocation.allow.accesskey = P
geolocation.block = Bloki
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Tio malfermos la agordojn de pozicio de la sistemo. Bonvolu rajtigi %S aliri la pozicion.
geolocation.shareWithSite4 = Ĉu permesi al %S uzi vian pozicion?
geolocation.shareWithFile4 = Ĉu permesi al tiu ĉi loka dosiero aliri vian pozicion?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Ĉu permesi al %1$S rajtigi %2$S aliri vian pozicion?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Rajtigi %S aliri la pozicion en la agordoj sistemaj.
geolocation.systemSettingsTitle = Atendo je rajtigo aliri la pozicion
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = La sistemo petos al vi doni al %S tiun ĉi permeson.
geolocation.remember = Memori tiun ĉi decidon
# Virtual Reality Device UI
xr.allow2 = Permesi
xr.allow2.accesskey = P
xr.block = Bloki
xr.block.accesskey = B
xr.shareWithSite4 = Ĉu permesi al %S aliri viajn aparatojn de virtuala realo? Tio povus elmeti konfidecan informon.
xr.shareWithFile4 = Ĉu permesi al tiu ĉi loka dosiero aliri viajn aparatojn de virtuala realo? Tio povus elmeti konfidecan informon.
xr.remember = Memori tiun ĉi decidon
# Persistent storage UI
persistentStorage.allow = Permesi
persistentStorage.allow.accesskey = P
persistentStorage.block.label = Bloki
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Ĉu permesi al %S konservi datumojn en konstanta konservejo?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Permesi
webNotifications.allow2.accesskey = P
webNotifications.notNow = Ne nun
webNotifications.notNow.accesskey = n
webNotifications.never = Neniam permesi
webNotifications.never.accesskey = i
webNotifications.alwaysBlock = Ĉiam bloki
webNotifications.alwaysBlock.accesskey = a
webNotifications.block = Bloki
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Ĉu permesi al %S sendi sciigojn?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S volas aliri aliajn programojn kaj servojn en tiu ĉi aparato.
localhost.remember2 = Memori mian elekton por tiu ĉi retejo
localhost.allowlabel = Permesi
localhost.blocklabel = Bloki
localhost.allow.accesskey = P
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S volas aliri aliajn programojn kaj servojn en aparatoj konektitaj al via loka reto.
localNetwork.remember2 = Memori mian elekton por tiu ĉi retejo
localNetwork.allowLabel = Permesi
localNetwork.allow.accesskey = P
localNetwork.blockLabel = Bloki
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Lasu min foriri el ĉi tie!
safebrowsing.getMeOutOfHereButton.accessKey = G
safebrowsing.deceptiveSite = Trompa retejo!
safebrowsing.notADeceptiveSiteButton.label = Tiu ĉi ne estas trompa retejo…
safebrowsing.notADeceptiveSiteButton.accessKey = t
safebrowsing.reportedAttackSite = Raportita ataka retejo!
safebrowsing.notAnAttackButton.label = Tio ĉi ne estas ataka retejo…
safebrowsing.notAnAttackButton.accessKey = A
safebrowsing.reportedUnwantedSite = Denuncita programtruda retejo!
safebrowsing.reportedHarmfulSite = Denuncita danĝera retejo!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Serĉi %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Ĉu restartigi %S en problemsolva reĝimo?
troubleshootModeRestartPromptMessage = Viaj etendaĵoj, etosoj kaj personaj agordoj estos provizore malaktivaj.
troubleshootModeRestartButton = Restartigi
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Tiu ĉi paĝo malrapidigas %1$S. Por rapidigi vian retumilon, haltigu tiun ĉi paĝon.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Retpaĝo malrapidigas %1$S. Por rapidigi vian retumilon, haltigu tiun paĝon.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = “%1$S” malrapidigas %2$S. Por rapidigi vian retumilon, haltigu tiun paĝon.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = “%1$S” malrapidigas %2$S. Por rapidigi vian retumilon, haltigu tiun etendaĵon.
processHang.add-on.learn-more.text = Pli da informo
processHang.button_stop2.label = Haltigi
processHang.button_stop2.accessKey = H
processHang.button_debug.label = Senerarigi skripton
processHang.button_debug.accessKey = S
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Montri la fenestron plenekrane (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Movi flankan strion maldekstren
sidebar.moveToRight = Movi flankan strion dekstren
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Vi devas aktivigi DRM por ludi sonon aŭ videon en tiu ĉi paĝo.
emeNotifications.drmContentDisabled.button.label = Aktivigi DRM
emeNotifications.drmContentDisabled.button.accesskey = A
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S nun instalas komponantojn bezonatajn por ludi la sonon aŭ filmeton en tiu ĉi paĝo. Bonvolu klopodi denove poste.
emeNotifications.unknownDRMSoftware = Nekonata
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Personecigi %S
decoder.noCodecs.button = Lernu kiel fari
decoder.noCodecs.accesskey = L
decoder.noCodecsLinux.message = Por ludi videon vi eble devos instali la postulatajn videajn kodekojn.
decoder.noHWAcceleration.message = Por plibonigi la videan kvaliton, vi eble devos instali Microsoft’s Media Feature Pack.
decoder.noPulseAudio.message = Por ludi sonon, vi eble devos instali la postulatajn programojn de PulseAudio.
decoder.unsupportedLibavcodec.message = libavcodec povas esti sendefenda aŭ ne subtenata. Oni devus ĝisdatigi ĝin antaŭ ol ludi videon.
decoder.decodeError.message = Eraro okazis dum malkodado de aŭdvidaĵo.
decoder.decodeError.button = Raporti problemon de retejo
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = Solvebla eraro okazis dum malkodado de aŭdvidaĵo.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Vi devas komenci seancon en tiu ĉi reto antaŭ ol vi povos aliri Interreton.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Malfermi paĝon por komenci seancon en reto
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Permesoj por %S
permissions.remove.tooltip = Forigi tiun ĉi permeson kaj demandi denove
permissions.fullscreen.promptCanceled = Nuligita dum peto pri permesoj: petoj pri permesoj ne devus okazi nek dum plenekrana DOM aŭ nek enirante ĝin.
permissions.fullscreen.fullScreenCanceled = Fino de plenekrana DOM: peto pri permesoj ne devus okazi dum plenekrana DOM.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bit
aboutDialog.architecture.thirtyTwoBit = 32-bit
midi.allow.label = Permesi
midi.allow.accesskey = P
midi.block.label = Bloki
midi.block.accesskey = B
midi.remember = Memori tiun ĉi decidon
midi.shareWithFile = Ĉu permesi al tiu ĉi loka dosiero aliri vian aparatojn MIDI?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Ĉu permesi al %S aliri viajn aparatojn MIDI?
midi.shareSysexWithFile = Ĉu permesi al tiu ĉi loka dosiero aliri viajn aparatojn MIDI kaj sendi/ricevi mesaĝojn SysEx?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Ĉu permesi al %S aliri viajn aparatojn MIDI kaj sendi/ricevi mesaĝojn SysEx?
serial.allow.label = Permesi
serial.allow.accesskey = P
serial.block.label = Bloki
serial.block.accesskey = B
serial.shareWithFile = Ĉu permesi al tiu ĉi loka dosiero aliri viajn seriajn konektojn?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Ĉu permesi al %S aliri viajn seriajn konektojn?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Reen
storageAccess1.Allow.label = Permesi
storageAccess1.Allow.accesskey = P
storageAccess1.DontAllow.label = Bloki
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Ĉu permesi al %1$S uzi siajn kuketojn en %2$S?
storageAccess1.hintText = Vi povus voli bloki la aliron, se ne estas klare, kial %1$S bezonas tiujn ĉi datumojn.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Serĉi “%S” en la reto
