# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = ບັນທຶກການເຂົ້າສູ່ລະບົບໄວ້
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-username-cmd =
    .label = ສຳເນົາຊື່ຜູ້ໃຊ້
    .accesskey = U
edit-username-cmd =
    .label = ແກ້ໄຂຊື່ຜູ້ໃຊ້
    .accesskey = d
copy-password-cmd =
    .label = ສຳເນົາລະຫັດຜ່ານ
    .accesskey = C
edit-password-cmd =
    .label = ແກ້ໄຂລະຫັດຜ່ານ
    .accesskey = E
search-filter =
    .accesskey = S
    .placeholder = ຄົ້ນຫາ
column-heading-site =
    .label = ​ໄຊ​ຕ໌
column-heading-username =
    .label = ຊື່ຜູ້ໃຊ້
column-heading-password =
    .label = ລະຫັດຜ່ານ
column-heading-time-created =
    .label = ໃຊ້ຄັ້ງທຳອິດ
column-heading-time-last-used =
    .label = ໃຊ້ຄັ້ງຫລ້າສຸດ
column-heading-time-password-changed =
    .label = ປ່ຽນແປງຄັ້ງຫລ້າສຸດ
column-heading-times-used =
    .label = ຈຳນວນຄັ້ງທີ່ນໍາໃຊ້
remove =
    .label = ລຶບ
    .accesskey = ລ
import =
    .label = ນໍາເຂົ້າ…
    .accesskey = I
close-button =
    .label = ປິດ
    .accesskey = C
show-passwords =
    .label = ສະແດງລະຫັດຜ່ານ
    .accesskey = P​
hide-passwords =
    .label = ເຊື່ອງລະຫັດຜ່າານ
    .accesskey = P​
logins-description-filtered = ການເຂົ້າສູ່ລະບົບດັ່ງຕໍ່ໄປນີ້ກົງກັບທີ່ທ່ານຄົ້ນຫາ:
remove-all-passwords-prompt = ທ່ານແນ່ໃຈແລ້ວບໍ່ວາຕ້ອງການທີ່ຈະລຶບລະຫັດຜ່ານທັງຫມົດອອກ?
remove-all-passwords-title = ລຶບລະຫັດຜ່ານທັງຫມົດ
no-master-password-prompt = ທ່ານແນ່ໃຈແລ້ວບໍ່ວາຕ້ອງການທີ່ຈະສະແດງລະຫັດຜ່ານ?
