# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Surpassà il temp
openFile = Avrir la datoteca
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Tschertgar "%2$S" cun agid da %1$S
contextMenuSearch.accesskey = S
contextMenuPrivateSearch = Tschertgar en ina fanestra privata
contextMenuPrivateSearch.accesskey = h
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Tschertgar cun %S en ina fanestra privata
contextMenuPrivateSearchOtherEngine.accesskey = h
bookmarkAllTabsDefault = [num da l'ordinatur]
unsignedAddonsDisabled.message = Impussibel da verifitgar in u plirs supplements installads. Els èn vegnids deactivads.
unsignedAddonsDisabled.learnMore.label = Ulteriuras infurmaziuns
unsignedAddonsDisabled.learnMore.accesskey = L
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Ultim access %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = Colliaziuns %S://
crashedpluginsMessage.title = Il plug-in %S è collabà.
crashedpluginsMessage.reloadButton.label = Rechargiar la pagina
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = Trametter ina annunzia da collaps
crashedpluginsMessage.submitButton.accesskey = T
crashedpluginsMessage.learnMore = Ulteriuras infurmaziuns…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Has ti vulì visitar %S?
keywordURIFixup.goTo = Gea, chargia %S
keywordURIFixup.goTo.accesskey = Y
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Actualisar a %S
update.downloadAndInstallButton.accesskey = A
menuOpenAllInTabs.label = Avrir tuts en tabs
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Rechargiar questa pagina
tabHistory.goBack = Enavos a questa pagina
tabHistory.goForward = Enavant a questa pagina
# URL Bar
pasteAndGo.label = Encollar & chargiar
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Rechargiar la pagina actuala (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Interrumper il chargiar da questa pagina (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Grondezza normala (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Activar/deactivar il modus da lectura (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, Reinizialisar il nivel da zoom
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Mussar tes segnapaginas (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Mussar il progress da las telechargiadas actualas (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Avrir ina nova fanestra (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Avrir in nov tab (%S)
newTabContainer.tooltip = Avrir in nov tab (%S)\nSmatgar e tegnair per avrir in nov tab da container
newTabAlwaysContainer.tooltip = Tscherna in container per avrir in nov tab
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Permetter a %S dad utilisar tias datas da maletg dal canvas HTML5?
canvas.siteprompt2.warning = Questas infurmaziuns pon eventualmain vegnir duvradas per identifitgar tes computer a moda univoca.
canvas.block = Bloccar
canvas.block.accesskey = B
canvas.allow2 = Permetter
canvas.allow2.accesskey = P
canvas.remember2 = Tegnair endament questa decisiun
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Verifitgà da: %S
identity.identified.verified_by_you = Ti has agiuntà in'excepziun da segirezza per questa website.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Certificat emess per: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Betg segir
identity.notSecure.tooltip = Connexiun betg segirada
identity.extension.label = Extensiun (%S)
identity.extension.tooltip = Chargià da l'extensiun: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Empitschnir (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Grondezza normala (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Engrondir (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Tagliar ora (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Copiar (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Encollar (%S)
geolocation.allow = Permetter
geolocation.allow.accesskey = P
geolocation.block = Bloccar
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Quai vegn ad avrir ils parameters da posiziun dal sistem. Permetta per plaschair ad %S dad acceder a la posiziun.
geolocation.shareWithSite4 = Permetter a %S dad acceder a tia posiziun?
geolocation.shareWithFile4 = Permetter a questa datoteca locala dad acceder a tia posiziun?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Lubir a %1$S da permetter a %2$S dad acceder a tia posiziun?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Permetter ad %S dad acceder a la posiziun en ils parameters dal sistem.
geolocation.systemSettingsTitle = Spetgar la permissiun dad acceder a la posiziun
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Il sistem ta vegn a dumandar da conceder questa permissiun a %S.
geolocation.remember = Memorisar questa decisiun
# Virtual Reality Device UI
xr.allow2 = Permetter
xr.allow2.accesskey = P
xr.block = Bloccar
xr.block.accesskey = B
xr.shareWithSite4 = Permetter a %S dad acceder als apparats da realitad virtuala? Quai po cumprometter infurmaziuns sensiblas.
xr.shareWithFile4 = Permetter a questa datoteca locala dad acceder als apparats da realitad virtuala? Quai po cumprometter infurmaziuns sensiblas.
xr.remember = Memorisar questa decisiun
# Persistent storage UI
persistentStorage.allow = Permetter
persistentStorage.allow.accesskey = P
persistentStorage.block.label = Bloccar
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Permetter a %S da memorisar datas en la memoria durabla?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Permetter
webNotifications.allow2.accesskey = P
webNotifications.notNow = Betg ussa
webNotifications.notNow.accesskey = u
webNotifications.never = Mai permetter
webNotifications.never.accesskey = a
webNotifications.alwaysBlock = Adina bloccar
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = Bloccar
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Permetter a %S da trametter communicaziuns?
localhost.remember2 = Memorisar mia decisiun per questa website
localhost.allowlabel = Permetter
localhost.blocklabel = Bloccar
localhost.allow.accesskey = P
localhost.block.accesskey = B
localNetwork.remember2 = Memorisar mia decisiun per questa website
localNetwork.allowLabel = Permetter
localNetwork.allow.accesskey = P
localNetwork.blockLabel = Bloccar
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Bandunar questa pagina
safebrowsing.getMeOutOfHereButton.accessKey = B
safebrowsing.deceptiveSite = Pagina che engiona!
safebrowsing.notADeceptiveSiteButton.label = Quai n'è betg ina website che engiona…
safebrowsing.notADeceptiveSiteButton.accessKey = e
safebrowsing.reportedAttackSite = Pagina classifitgada sco website attatganta!
safebrowsing.notAnAttackButton.label = Quai n'è betg ina website attatganta…
safebrowsing.notAnAttackButton.accessKey = b
safebrowsing.reportedUnwantedSite = Rapportà sco pagina cun software nungiavischada!
safebrowsing.reportedHarmfulSite = Pagina rapportada sco privlusa!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Tschertgar %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Reaviar %S en il modus per schliar problems?
troubleshootModeRestartPromptMessage = Tias extensiuns, tes designs e tes parameters persunalisads vegnan deactivads temporarmain.
troubleshootModeRestartButton = Reaviar
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Questa pagina ralentescha %1$S. Per accelerar tes navigatur, ferma questa pagina.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Ina pagina web ralentescha %1$S. Per accelerar tes navigatur, ferma quella pagina.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = «%1$S» ralentescha %2$S. Per accelerar tes navigatur, ferma quella pagina.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = «%1$S» ralentescha %2$S. Per accelerar tes navigatur, blochescha questa extensiun.
processHang.add-on.learn-more.text = Ulteriuras infurmaziuns
processHang.button_stop2.label = Fermar
processHang.button_stop2.accessKey = F
processHang.button_debug.label = Debugar il script
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Mussar la fanestra en il modus da maletg entir (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Spustar la trav laterala a sanestra
sidebar.moveToRight = Spustar la trav laterala a dretga
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Ti stos activar DRM per pudair far ir l'audio u video da questa pagina.
emeNotifications.drmContentDisabled.button.label = Activar DRM
emeNotifications.drmContentDisabled.button.accesskey = A
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S installescha las cumponentas necessarias per far ir video u audio sin questa pagina. Emprova pli tard anc ina giada.
emeNotifications.unknownDRMSoftware = Nunenconuschent
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Persunalisar %S
decoder.noCodecs.button = Vegnir a savair co
decoder.noCodecs.accesskey = V
decoder.noCodecsLinux.message = Per far ir il video stos ti eventualmain installar ils codecs necessaris.
decoder.noHWAcceleration.message = Per augmentar la qualitad da video stos ti eventualmain installar il «Media Feature Pack» da Microsoft.
decoder.noPulseAudio.message = Per far ir il tun stos ti eventualmain installar la software «PulseAudio».
decoder.unsupportedLibavcodec.message = libavcodec è eventualmain attatgabel u betg pli sustegnì e stuess vegnir actualisà per far ir videos.
decoder.decodeError.message = Ina errur è cumparida durant decodar ina resursa da medias.
decoder.decodeError.button = Rapportar in problem cun la pagina
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = Ina errur curregibla è cumparida durant decodar ina resursa da medias.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Ti stos t'annunziar en questa rait avant che ti pos acceder a l'internet.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Avrir la pagina per s'annunziar en la rait
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Permissiuns per %S
permissions.remove.tooltip = Stizzar questa autorisaziun e puspè dumandar
permissions.fullscreen.promptCanceled = Annullà las dumondas d'autorisaziun pendenta: dumondas d'autorisaziun na dastgan betg vegnir fatgas avant che entrar en il modus da maletg entir DOM.
permissions.fullscreen.fullScreenCanceled = Terminà il modus da maletg entir DOM: dumondas d'autorisaziun na dastgan betg vegnir fatgas en il modus da maletg entir DOM.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64 bits
aboutDialog.architecture.thirtyTwoBit = 32 bits
midi.allow.label = Permetter
midi.allow.accesskey = P
midi.block.label = Bloccar
midi.block.accesskey = B
midi.remember = Tegnair endament questa decisiun
midi.shareWithFile = Permetter a questa datoteca locala dad acceder a tes apparats MIDI?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Permetter a %S dad acceder a tes apparats MIDI?
midi.shareSysexWithFile = Permetter a questa datoteca locala dad acceder a tes apparats MIDI e trametter/retschaiver messadis SysEx?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Permetter a %S dad acceder a tes apparats MIDI e trametter/retschaiver messadis SysEx?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Enavos
storageAccess1.Allow.label = Permetter
storageAccess1.Allow.accesskey = P
storageAccess1.DontAllow.label = Bloccar
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Permetter a %1$S dad utilisar ses cookies sin %2$S?
storageAccess1.hintText = Ti pos bloccar l'access sch'i n'è betg cler pertge che %1$S dovra questas datas.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Tschertgar «%S» en il web
