# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SaveImageTitle = Save Image
SaveMediaTitle = Save Media
SaveVideoTitle = Save Video
SaveAudioTitle = Save Soond
SaveLinkTitle = Save As
WebPageCompleteFilter = Wab Page, complete
WebPageHTMLOnlyFilter = Wab Page, HTML anely
WebPageXHTMLOnlyFilter = Wab Page, XHTML anely
WebPageSVGOnlyFilter = Wab Page, SVG anely
WebPageXMLOnlyFilter = Wab Page, XML anely
