# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

addons-window =
    .title = অ্যাড-অন ব্যবস্থাপক
search-header-shortcut =
    .key = f
loading-label =
    .value = লোড করা হচ্ছে…
list-empty-available-updates =
    .value = কোনো হালনাগাদ পাওয়া যায়নি
list-empty-find-updates =
    .label = হালনাগাদের জন্য পরীক্ষা
list-empty-button =
    .label = অ্যাড-অন সম্পর্কে আরও শিখুন
install-addon-from-file =
    .label = ফাইল থেকে অ্যাড-অন ইনস্টল… I
    .accesskey = I
tools-menu =
    .tooltiptext = সব অ্যাড-অন এর জন্য টুল
cmd-show-details =
    .label = আরও তথ্য প্রদর্শন করা হবে S
    .accesskey = S
cmd-enable-theme =
    .label = থীম যোগ W
    .accesskey = W
cmd-disable-theme =
    .label = থীম যোগ বন্ধ W
    .accesskey = W
cmd-install-addon =
    .label = ইনস্টল করুন I
    .accesskey = I
cmd-contribute =
    .label = অবদান রাখুন C
    .accesskey = C
    .tooltiptext = অ্যাড-অন উন্নয়নে অবদান রাখুন
discover-title = অ্যাড-অন কি?
detail-version =
    .label = সংস্করণ
detail-last-updated =
    .label = সর্বশেষ হালনাগাদ
detail-contributions-description = এ অ্যাড-অন ডেভেলপার বলে যে, আপনি আপনার যে কোনো ছোট অবদান দিয়েও এই অ্যাড-অনের উন্নয়নে সহায়তা করতে পারেন।
detail-update-type =
    .value = স্বয়ংক্রিয় হালনাগাদ
detail-update-automatic =
    .label = সচল
    .tooltiptext = স্বয়ংক্রিয়ভাবে হালনাগাদ ইনস্টল করা হবে
detail-home-value =
    .value = { detail-home.label }
detail-repository =
    .label = অ্যাড-অন প্রোফাইল
detail-repository-value =
    .value = { detail-repository.label }
detail-rating =
    .value = রেটিং
addon-restart-now =
    .label = এখন পুনরায় শুরু করুন
