# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

title = Información sobre o ret
warning = Isto ye a saber que experimental. No s'ha de fer servir sin a supervisión d'un adulto.
show-next-time-checkbox = Mostra ista alvertencia a vegada siguient
ok = OK
http = HTTP
sockets = Sockets
dns = DNS
websockets = WebSockets
refresh = Esviellar
auto-refresh = Esviellar automaticament cada 3 segundos
hostname = Nombre d'o servidor
port = Puerto
http2 = HTTP/2
ssl = SSL
active = Activo
idle = Inactivo
host = Servidor
tcp = TCP
sent = Ninviau
received = Recibiu
family = Familia
trr = TRR
addresses = Adrezas
expires = Expira (segundos)
messages-sent = Mensaches ninviaus
messages-received = Mensaches recibius
bytes-sent = Bytes ninviaus
bytes-received = Bytes recibius
logging = Rechistro
log-tutorial = Mirar <a data-l10n-name="logging">Rechistro HTTP</a> pa saber cómo usar ista ferramienta.
current-log-file = Fichero de rechistro actual:
current-log-modules = Modulos de rechistro actuals:
set-log-file = Determinar fichero de rechistro
set-log-modules = Determinar modulos de rechistro
start-logging = Empecipiar a rechistrar
stop-logging = Deixar de rechistrar
dns-lookup = DNS Lookup
dns-lookup-button = Resolver
dns-domain = Dominio:
dns-lookup-table-column = IPs
rcwn = Estatisticas de RCWN
rcwn-status = Estatus de RCWN
rcwn-cache-won-count = Numero de victorias d'o caché
rcwn-net-won-count = Numero de victorias neto
total-network-requests = Numero de demandas totals de ret
rcwn-operation = Operación d'a caché
rcwn-perf-open = Ubrir
rcwn-perf-read = Leyer
rcwn-perf-write = Escribir
rcwn-perf-entry-open = Abrir dentrada
rcwn-avg-short = Meya curta
rcwn-avg-long = Meya larga
rcwn-std-dev-long = Desviación estandard larga
rcwn-cache-slow = Numero d'ocasions que la caché ye lenta
rcwn-cache-not-slow = Numero d'ocasions que la caché no ye lenta
