# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

title = Informaçioin in sciâ ræ
warning = A l'é ina fonçion sperimentale. No adeuviâ sensa a supervixon de 'n grande.
show-next-time-checkbox = Veddi torna sto avizo inte l'avegnî
ok = Va ben
http = HTTP
sockets = Socket
dns = DNS
websockets = WebSocket
refresh = Agiorna
auto-refresh = Agiorna outomaticamente ògni 3 segondi
hostname = Nomme server
port = Pòrta
http2 = HTTP/2
ssl = SSL
active = Ativo
idle = Inativo
host = Server
tcp = TCP
sent = Mandæ
received = Riçevui
family = Famiggia
trr = TRR
addresses = Indirissi
expires = Scadensa (segondi)
messages-sent = Mesaggi mandæ
messages-received = Mesaggi reçevui
bytes-sent = Byte mandæ
bytes-received = Byte reçevui
logging = Registro
log-tutorial = Amia o <a data-l10n-name="logging"> diaio HTTP</a> pe instruçioin in sce comme dueviâ sto strumento.
current-log-file = Schedaio de diaio corente:
current-log-modules = Mòdoli do diaio corente:
set-log-file = Seleçionn-a schedaio de diaio
set-log-modules = Inpòsta mòdoli do diaio
start-logging = Iniçia a registrâ
stop-logging = Ferma a registraçion
dns-lookup = Lookup DNS
dns-lookup-button = Risolvi
dns-domain = Dominio:
dns-lookup-table-column = IP
rcwn = Statistiche RCWN
rcwn-status = Stato RCWN
rcwn-cache-won-count = Conto da cache goagnâ
rcwn-net-won-count = Conto da ræ goagnâ
total-network-requests = Conto de tutte e domande da ræ
rcwn-operation = Operaçion Cache
rcwn-perf-open = Arvi
rcwn-perf-read = Lezi
rcwn-perf-write = Scrivi
rcwn-perf-entry-open = Arvi elemento
rcwn-avg-short = Media curta
rcwn-avg-long = Media longa
rcwn-std-dev-long = Deviaçion standard longa
rcwn-cache-slow = Conto da cache lenta
rcwn-cache-not-slow = Conto da cache no lenta
