# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = Ukurasa wavuti unaelekezwa tena mahali papya. Ungependa kutuma tena data ya fomu uliyochapa kwenye mahali papya?
# Directory listing strings
DirTitle = Kielezo cha %1$S
DirGoUp = Kwa kiwango cha juu cha mpangilio orodha
ShowHidden = Onyesha vipengee vilivyofichwa
DirColName = Jina
DirColSize = Ukubwa
DirColMTime = Ilibadilishwa Mwisho
DirFileLabel = Faili:\u0020
