# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

appmenu-update-available2 =
    .label = Actualizare disponibilă
    .buttonlabel = Descarcă
    .buttonaccesskey = D
    .secondarybuttonlabel = Respinge
    .secondarybuttonaccesskey = m
appmenu-update-available-message2 = Descarcă cea mai recentă versiune de { -brand-shorter-name }.
appmenu-update-manual2 =
    .label = Actualizare disponibilă
    .buttonlabel = Descarcă
    .buttonaccesskey = D
    .secondarybuttonlabel = Respinge
    .secondarybuttonaccesskey = m
appmenu-update-manual-message2 = { -brand-shorter-name } nu s-a putut actualiza automat. Descarcă noua versiune - nu vei pierde informațiile sau personalizările salvate.
appmenu-update-unsupported2 =
    .label = Nu se poate actualiza
    .buttonlabel = Află mai multe
    .buttonaccesskey = L
    .secondarybuttonlabel = Respinge
    .secondarybuttonaccesskey = m
appmenu-update-unsupported-message2 = Sistemul tău de operare nu este compatibil cu cea mai recentă versiune de { -brand-shorter-name }.
appmenu-update-restart2 =
    .label = Actualizare disponibilă
    .buttonlabel = Actualizează și repornește
    .buttonaccesskey = U
    .secondarybuttonlabel = Respinge
    .secondarybuttonaccesskey = m
appmenu-update-restart-message2 = Obține cea mai recentă versiune de { -brand-shorter-name }. Filele deschise și ferestrele vor fi restaurate.
appmenu-theme-installed =
    .secondarybuttonlabel = Anulează
    .secondarybuttonaccesskey = U
appmenu-update-other-instance =
    .label = { -brand-shorter-name } nu se poate actualiza automat la ultima versiune.
    .buttonlabel = Actualizează { -brand-shorter-name } oricum
    .buttonaccesskey = U
    .secondarybuttonlabel = Nu acum
    .secondarybuttonaccesskey = N
appmenu-update-other-instance-message = Este disponibilă o actualizare { -brand-shorter-name } nouă, dar nu poate fi instalată pentru că rulează altă instalare { -brand-shorter-name }. Închide-o ca să continui cu actualizarea sau alege să actualizezi oricum (este posibil ca cealaltă instalare să nu funcționeze corect până ce nu o repornești).
appmenu-addon-private-browsing-installed2 =
    .buttonlabel = OK
    .buttonaccesskey = O
appmenu-addon-post-install-message3 = Gestionează-ți suplimentele și temele prin meniul aplicației.
appmenu-addon-post-install-incognito-checkbox =
    .label = Permite acestei extensii să ruleze în ferestre private
    .accesskey = A
appmenu-new-tab-controlled-changes =
    .label = Fila ta nouă s-a schimbat.
    .buttonlabel = Păstrează modificările
    .buttonaccesskey = K
    .secondarybuttonlabel = Administrează file noi
    .secondarybuttonaccesskey = M
appmenu-tab-hide-controlled =
    .label = Accesează filele ascunse
    .buttonlabel = Păstrează filele ascunse
    .buttonaccesskey = K
    .secondarybuttonlabel = Dezactivează extensia
    .secondarybuttonaccesskey = D
