# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

reload-tab =
    .label = Reîncarcă fila
    .accesskey = R
select-all-tabs =
    .label = Selectează toate filele
    .accesskey = S
duplicate-tab =
    .label = Duplică fila
    .accesskey = D
close-tabs-to-the-end =
    .label = Închide filele de la dreapta
    .accesskey = i
close-other-tabs =
    .label = Închide celelalte file
    .accesskey = o
reload-tabs =
    .label = Reîncarcă filele
    .accesskey = R
pin-tab =
    .label = Fixează fila
    .accesskey = P
unpin-tab =
    .label = Anulează fixarea filei
    .accesskey = b
bookmark-tab =
    .label = Marchează fila
    .accesskey = B
move-to-start =
    .label = Mută la început
    .accesskey = S
move-to-end =
    .label = Mută la sfârșit
    .accesskey = E
move-to-new-window =
    .label = Mută într-o fereastră nouă
    .accesskey = W
undo-close-tab =
    .label = Anulează închiderea filei
    .accesskey = U
close-tab =
    .label = Închide fila
    .accesskey = c
close-tabs =
    .label = Închide filele
    .accesskey = S
move-tabs =
    .label = Mută filele
    .accesskey = v
move-tab =
    .label = Mută fila
    .accesskey = v
