# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dateformat-label =
    .value = Fformat Testun Dyddiad:
    .accesskey = F
#   $date (String) - the formatted example date
dateformat-long =
    .label = Hir: { $date }
#   $date (String) - the formatted example date
dateformat-short =
    .label = Byr: { $date }
weekstart-label =
    .value = Cychwyn yr wythnos ar:
    .accesskey = C
day-1-name =
    .label = Dydd Sul
day-2-name =
    .label = Dydd Llun
day-3-name =
    .label = Dydd Mawrth
day-4-name =
    .label = Dydd Mercher
day-5-name =
    .label = Dydd Iau
day-6-name =
    .label = Dydd Gwener
day-7-name =
    .label = Dydd Sadwrn
day-1-checkbox =
    .label = Sul
    .accesskey = S
day-2-checkbox =
    .label = Llu
    .accesskey = L
day-3-checkbox =
    .label = Maw
    .accesskey = M
day-4-checkbox =
    .label = Mer
    .accesskey = e
day-5-checkbox =
    .label = Iau
    .accesskey = I
day-6-checkbox =
    .label = Gwe
    .accesskey = G
day-7-checkbox =
    .label = Sad
    .accesskey = a
dayweek-legend = Golwg Diwrnod ac Wythnos
visible-hours-label =
    .value = Dangos:
    .accesskey = a
visible-hours-end-label =
    .value = awr ar y tro
day-start-label =
    .value = Diwrnod yn cychwyn:
    .accesskey = D
day-end-label =
    .value = Diwrnod yn gorffen:
    .accesskey = i
midnight-label =
    .label = Canol Nos
noon-label =
    .label = Canol Dydd
multiweek-legend = Golwg Wythnosau
number-of-weeks-label =
    .value = Nifer o wythnosau i'w dangos (gan gynnwys yr wythnos flaenorol):
    .accesskey = N
week-0-label =
    .label = dim
week-1-label =
    .label = 1 wythnos
week-2-label =
    .label = 2 wythnos
week-3-label =
    .label = 3 wythnos
week-4-label =
    .label = 4 wythnos
week-5-label =
    .label = 5 wythnos
week-6-label =
    .label = 6 wythnos
previous-weeks-label =
    .value = Dangos yr wythnos flaenorol:
    .accesskey = f
task-start-label =
    .value = Dyddiad Cychwyn:
task-due-label =
    .value = Dyddiad Gorffen:
accessibility-legend = Hygyrchedd
accessibility-colors-label =
    .label = Mireinio lliwiau ar gyfer hygyrchedd
    .accesskey = M
reminder-legend = Pan fydd Disgwyl Atgoffwr:
reminder-default-sound-label =
    .label = Defnyddio'r sain rhagosodedig
    .accesskey = s
reminder-browse-sound-label =
    .label = Pori…
    .accesskey = P
reminder-default-legend = Rhagosodiadau Atgoffwyr
event-alarm-label =
    .value = Gosodiadau atgoffa rhagosodedig ar gyfer digwyddiadau:
    .accesskey = G
alarm-on-label =
    .label = Ymlaen
alarm-off-label =
    .label = Diffodd
task-alarm-label =
    .value = Gosodiadau atgoffa rhagosodedig ar gyfer tasgau:
    .accesskey = o
event-alarm-time-label =
    .value = Amser rhagosodedig y bydd atgoffwr yn cael ei bennu cyn digwyddiad:
    .accesskey = A
task-alarm-time-label =
    .value = Amser rhagosodedig y bydd atgoffwr yn cael ei bennu cyn tasg:
    .accesskey = m
category-edit-label = Golygu Categori
category-overwrite-title = Rhybudd: Enw dyblyg
category-overwrite = Mae categori o'r enw yna yn bodoli eisoes. Hoffech chi ysgrifennu trosto?
category-blank-warning = Rhaid rhoi enw categori.
