# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=$ProductName$ のセットアップ
Welcome_MessageWelcome=%s へようこそ
Welcome_Message0=%s $Version$ のインストールを開始します。
Welcome_Message1=このセットアップを実行する前にすべての Windows プログラムを終了させることを強くお勧めします。
Welcome_Message2=セットアップを中止して実行中のプログラムを終了する場合は [キャンセル] をクリックしてください。セットアップを続行するには [次へ] をクリックしてください。
Welcome_Message3=%s $Version$ のインストールを続行するには [次へ] をクリックしてください。

License_Title=ソフトウェア使用許諾書
License_SubTitle=このソフトウェアを使用するための条項
License_Message0=スクロールバーを使用して次の使用許諾書をよくお読みください。
License_Accept=使用許諾書に同意する(&A)
License_Decline=使用許諾書に同意しない(&T)

Type_Title=セットアップの種類
Type_SubTitle=セットアップオプションの選択
Type_Message0=実行するセットアップの種類を選択して［次へ］をクリックしてください。

Standard_Short=標準(&S)
Standard_Long=最も一般的な構成で Thunderbird をインストールします。

Custom_Short=カスタム(&C)
Custom_Long=インストールする構成を選択します(上級ユーザ向け)。

Select_Title=コンポーネントの選択
Select_SubTitle=$ProductName$ を強化する追加コンポーネントです。
Select_Message0=インストールするコンポーネントを選択し [次へ] をクリックしてください。

Path_Title=インストール先の選択
Path_SubTitle=$ProductName$ のインストール先を選択してください
Path_Message0=以下のプログラムフォルダに $ProductName$ をインストールします:

Integration_Title=ショートカットの設定
Integration_SubTitle=プログラムアイコンを作成する
Integration_Message0=$ProductShortName$ アイコンの作成先:

Integration_Desktop=デスクトップ
Integration_StartMenu=スタートメニュー
Integration_QuickLaunch=クイック起動ツールバー

SelectFolder_Title=$ProductName$ セットアップ - プログラムフォルダの選択
SelectFolder_Message0=以下のプログラムフォルダにプログラムアイコンを作成します。新しいフォルダ名を指定したり既存のフォルダから選択することもできます。

Advanced_Title=$ProductName$ セットアップ - 高度な設定
Advanced_Message0=インターネット接続にプロキシサーバが必要な場合は、サーバ名とポート情報を入力してください。プロキシサーバが必要でない場合は、このフィールドは空白のままにしてください。

Install_Title=セットアップ設定の確認
Install_SubTitle=$ProductName$ をインストールする準備が出来ました。
Install_MessageInstall=以下のコンポーネントがインストールされます:
Install_MessageDownload=以下のコンポーネントがダウンロードしてインストールされます:
Install_Message0=[次へ] をクリックするとインストールを開始します。

Downloading_Title=ダウンロード中
Downloading_SubTitle=必要なコンポーネントをダウンロードしています...
Downloading_Blurb=$ProductName$ のインストールに必要なファイルをダウンロードしています...
Downloading_FileName=ダウンロード中のファイル:
Downloading_Time=残り時間:

Installing_Title=インストール中
Installing_SubTitle=$ProductName$ をインストールしています...
Installing_Blurb=アプリケーションファイルをインストールしています。
Installing_Status=準備中のファイル:
Installing_Component=インストール中のファイル:

Success_Title=インストール完了
Success_Header=インストールを完了しました。
Success_Message0=%s $Version$ が正常にインストールされました。
Success_Message1=[完了] をクリックするとインストールが完了します。
Success_Launch=今すぐ %s $Version$ を起動する

Check_Message=$ProductName$ が正常にダウンロードされました。インストールを続行するには $ProductNameInternal$ を閉じる必要があります。［OK］ボタンをクリックすると自動的に $ProductNameInternal$ を終了してインストールを開始します。
Check_FullMessage=インストールを続行するには $ProductNameInternal$ を閉じる必要があります。［OK］ボタンをクリックすると自動的に $ProductNameInternal$ を終了してインストールを開始します。
Check_Wait=$ProductNameInternal$ を終了しています。しばらくお待ちください...


Component_XPCOM=クロスプラットフォーム COM
Component_Mail=$ProductName$
Component_Offline=オフラインサポート
Component_Offline_Long=$ProductName$ をオフラインモードで動作させられるようにします。
Component_RSS=RSS サポート
Component_RSS_Long=$ProductName$ で RSS を受信できるようにします。
Component_QFA=品質フィードバックエージェント
Component_QFA_Long=$ProductName$ クラッシュ情報の報告に使用します
