# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Ieškoma { $host }…
network-connection-status-connected = Prisijungta prie { $host }…
network-connection-status-sending-request = Siunčiama užklausa į { $host }…
network-connection-status-transferring-data = Siunčiama iš { $host }…
network-connection-status-connecting = Jungiamasi prie { $host }…
network-connection-status-read = Skaitoma { $host }
network-connection-status-wrote = Įrašyta { $host }
network-connection-status-waiting = Laukiama { $host }…
network-connection-status-looked-up = Surastas { $host }…
network-connection-status-tls-handshake = Vykdomas TLS pasisveikinimas su { $host }…
network-connection-status-tls-handshake-finished = TLS pasisveikinimas su { $host } užbaigtas…
