# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Clàraidhean a-steach sàbhailte
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Dèan lethbhreac dhen URL
    .accesskey = y
launch-site-url-cmd =
    .label = Tadhail air an URL
    .accesskey = V
copy-username-cmd =
    .label = Dèan lethbhreac dhen ainm-chleachdaiche
    .accesskey = D
edit-username-cmd =
    .label = Deasaich an t-ainm-cleachdaiche
    .accesskey = D
copy-password-cmd =
    .label = Dèan lethbhreac dhen fhacal-fhaire
    .accesskey = c
edit-password-cmd =
    .label = Deasaich am facal-faire
    .accesskey = e
search-filter =
    .accesskey = L
    .placeholder = Lorg
column-heading-site =
    .label = Seòladh
column-heading-username =
    .label = Ainm-cleachdaiche
column-heading-password =
    .label = Facal-faire
column-heading-time-created =
    .label = Ciad chleachdadh
column-heading-time-last-used =
    .label = Cleachdadh mu dheireadh
column-heading-time-password-changed =
    .label = Atharrachadh mu dheireadh
column-heading-times-used =
    .label = Dè cho tric
remove =
    .label = Thoir air falbh
    .accesskey = r
import =
    .label = Ion-phortaich…
    .accesskey = I
close-button =
    .label = Dùin
    .accesskey = D
show-passwords =
    .label = Seall na faclan-faire
    .accesskey = P
hide-passwords =
    .label = Falaich na faclan-faire
    .accesskey = P
logins-description-all = Tha clàraidhean a-steach air na làraichean a leanas ’gan stòradh air a’ choimpiutair agad
logins-description-filtered = Tha na clàraidhean a-steach a leanas a’ freagairt ris an lorg agad:
remove-all =
    .label = Thoir air falbh a h-uile
    .accesskey = a
remove-all-shown =
    .label = Thoir air falbh gach aon a tha ’ga shealltainn
    .accesskey = a
remove-all-passwords-prompt = A bheil thu airson gach facal-faire a thoirt air falbh?
remove-all-passwords-title = Thoir air falbh a h-uile facal-faire
no-master-password-prompt = A bheil thu cinnteach gu bheil thu airson na faclan-faire agad a shealltainn?
auto-fill-logins-and-passwords =
    .label = Autofill logins and passwords
