#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Bob Po-chiang Chao(bobchao)</em:contributor> <em:contributor>Alan Cheng</em:contributor> <em:contributor>Wei-Lun Sun(josesun)</em:contributor> <em:contributor>Daniel Boelzle</em:contributor> <em:contributor>Rafaella Braconi</em:contributor> <em:contributor>Wu, Ru-kang(akong)</em:contributor> <em:contributor>Peter Pin-Guang Chen(petercpg)</em:contributor>

#unfilter emptyLines
