#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>أيمن حورية</em:contributor> <em:contributor>جهاد عفيفي</em:contributor><em:contributor>خالد حسني</em:contributor><em:contributor>سبأ برتو</em:contributor><em:contributor>عبد الرحمن حسني </em:contributor><em:contributor>علاء كساب</em:contributor>

#unfilter emptyLines
