# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Որոնում { $host }…
network-connection-status-connected = Կապակցուած է { $host }-ի հետ…
network-connection-status-sending-request = { $host } -ին Ուղարկուում է հարցում...
network-connection-status-transferring-data = Տուեալների փոխանցում { $host } -ից…
network-connection-status-connecting = Միանում է { $host }-ին…
network-connection-status-read = Կարդացուել է { $host }
network-connection-status-wrote = Գրուել է { $host }
network-connection-status-waiting = Սպասում է { $host }-ի պատասխանին…
network-connection-status-looked-up = Որոնուած՝ { $host }-ը…
network-connection-status-tls-handshake = TLS ձեռքսեղման կատարում { $host }-ի հետ…
network-connection-status-tls-handshake-finished = TLS ձեռքսեղմումն { $host }-ի հետ աւարտուել է․․․
