# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Որոնում { $host }…
network-connection-status-connected = Կապակցուած է { $host }-ի հետ…
network-connection-status-sending-request = { $host } -ին Ուղարկուում է հարցում...
network-connection-status-transferring-data = Տուեալների փոխանցում { $host } -ից…
network-connection-status-connecting = Միանում է { $host }-ին…
