#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Saša Teković</em:contributor> <em:contributor>Danijel Šnajder</em:contributor> <em:contributor>Robert Okadar</em:contributor> <em:contributor>Anton Gagić</em:contributor> <em:contributor>Ante Karamatić</em:contributor>
#unfilter emptyLines
