# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = Itei lopa tīk puorvirzeita iz cytu vītu. Voi vālotīs nūsyuteit īvadeitūs formys datus iz itū jaunu vītu?
# Directory listing strings
DirTitle = Mapes %1$S indekss
DirGoUp = Īt vīnu mapi iz augšu
ShowHidden = Ruodeit slāptus objektus
DirColName = Nūsaukums
DirColSize = Izmārs
DirColMTime = Pādejūreiz maineits
DirFileLabel = Fails:
UnsafeUriBlocked = Resursu nu “%1$S” blokieja Drūsā puorlūkuošona.
