# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

PINotInProlog2 = <?%1$S?> 처리 중인 명령어는 prolog 외부에 영향을 미치지 않습니다.
