# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

breakpointMenuItem.enableSelf = Wezasha sehemu ya kiungo
breakpointMenuItem.disableSelf = Lemaza sehemu ya kiungo
breakpointMenuItem.deleteSelf = Ondoa sehemu ya kiungo
breakpointMenuItem.enableOthers = Wezesha zingine
breakpointMenuItem.disableOthers = Lemaza zingine
breakpointMenuItem.deleteOthers = Ondoa zingine
breakpointMenuItem.enableAll = Wezesha sehemu za viungo vyote
breakpointMenuItem.disableAll = Lemaza sehemu za viungo
breakpointMenuItem.deleteAll = Ondoa sehemu za viungo vyote
# LOCALIZATION NOTE (loadingText): The text that is displayed in the script
# editor when the loading process has started but there is no file to display
# yet.
loadingText = Kupakia…
# LOCALIZATION NOTE (variablesSeparatorLabel): The text that is displayed
# in the variables list as a separator between the name and value.
variablesSeparatorLabel = :
