# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SaveImageTitle = Pildi salvestamine
SaveMediaTitle = Meedia salvestamine
SaveVideoTitle = Video salvestamine
SaveAudioTitle = Audio salvestamine
SaveLinkTitle = Salvestamine
WebPageCompleteFilter = Veebileht, täielik
WebPageHTMLOnlyFilter = Veebileht, ainult HTML
WebPageXHTMLOnlyFilter = Veebileht, ainult XHTML
WebPageSVGOnlyFilter = Veebileht, ainult SVG
WebPageXMLOnlyFilter = Veebileht, ainult XML
