# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Tiden løb ud
openFile = Åbn fil
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Søg efter "%2$S" med %1$S
contextMenuSearch.accesskey = S
contextMenuPrivateSearch = Søg i et privat vindue
contextMenuPrivateSearch.accesskey = p
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Søg med %S i et privat vindue
contextMenuPrivateSearchOtherEngine.accesskey = p
bookmarkAllTabsDefault = [Mappenavn]
unsignedAddonsDisabled.message = En eller flere installerede tilføjelser kan ikke verificeres og er derfor blevet deaktiveret.
unsignedAddonsDisabled.learnMore.label = Læs mere
unsignedAddonsDisabled.learnMore.accesskey = L
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Senest tilgået %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = %S:// links
crashedpluginsMessage.title = Der opstod en fejl i plugin'et %S.
crashedpluginsMessage.reloadButton.label = Genindlæs side
crashedpluginsMessage.reloadButton.accesskey = G
crashedpluginsMessage.submitButton.label = Send en fejlrapport
crashedpluginsMessage.submitButton.accesskey = S
crashedpluginsMessage.learnMore = Læs mere…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Ville du gå til %S?
keywordURIFixup.goTo = Ja, tag mig til %S
keywordURIFixup.goTo.accesskey = J
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Opdater til %S
update.downloadAndInstallButton.accesskey = O
menuOpenAllInTabs.label = Åbn alle i faneblade
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Genindlæs denne side
tabHistory.goBack = Gå tilbage til denne side
tabHistory.goForward = Gå frem til denne side
# URL Bar
pasteAndGo.label = Indsæt og gå
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Genindlæs nuværende side (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Stop indlæsningen af denne side (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Nulstil zoom-niveau (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Slå læsevisning til/fra (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, Nulstil zoom-niveau
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Vis dine bogmærker (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Vis fremgang for den aktuelle filhentning (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Åbn et nyt vindue (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Åbn et nyt faneblad (%S)
newTabContainer.tooltip = Åbn et nyt faneblad  (%S)\nTryk og hold for at åbne et nyt kontekst-faneblad
newTabAlwaysContainer.tooltip = Vælg kontekst for at åbne et nyt faneblad
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Tillad %S at bruge dine data for HTML 5-canvas-image?
canvas.siteprompt2.warning = Dette kan bruges til at identificere din computer.
canvas.block = Bloker
canvas.block.accesskey = B
canvas.allow2 = Tillad
canvas.allow2.accesskey = T
canvas.remember2 = Husk dette valg
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Bekræftet af: %S
identity.identified.verified_by_you = Du har tilføjet en sikkerhedsundtagelse til dette websted
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Certifikatet er udstedt til: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Ikke sikker
identity.notSecure.tooltip = Forbindelsen er ikke sikker
identity.extension.label = Udvidelse (%S)
identity.extension.tooltip = Indlæst af udvidelse: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Zoom ud (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Nulstil zoom-niveau (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Zoom ind (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Klip (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Kopier (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Indsæt (%S)
geolocation.allow = Tillad
geolocation.allow.accesskey = T
geolocation.block = Bloker
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Dette åbner systemets indstillinger for position. Giv %S tilladelse til at se din position.
geolocation.shareWithSite4 = Tillad %S at anvende din position?
geolocation.shareWithFile4 = Tillad denne lokale fil at få adgang til din position?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Tillad %1$S at give %2$S tilladelse til at få adgang til din position?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Giv %S adgang til at se din position i systemindstillingerne.
geolocation.systemSettingsTitle = Venter på tilladelse til at se position
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Systemet vil spørge dig om at give denne tilladelse til %S.
geolocation.remember = Husk dette valg
# Virtual Reality Device UI
xr.allow2 = Tillad
xr.allow2.accesskey = T
xr.block = Bloker
xr.block.accesskey = B
xr.shareWithSite4 = Tillad %S at tilgå virtual reality-enheder? Dette kan eksponere følsom information.
xr.shareWithFile4 = Tillad denne lokal fil at tilgå virtual reality-enheder? Dette kan eksponere følsom information.
xr.remember = Husk dette valg
# Persistent storage UI
persistentStorage.allow = Tillad
persistentStorage.allow.accesskey = T
persistentStorage.block.label = Bloker
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Tillad %S at gemme data i vedvarende lager?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Tillad
webNotifications.allow2.accesskey = T
webNotifications.notNow = Ikke nu
webNotifications.notNow.accesskey = n
webNotifications.never = Tillad aldrig
webNotifications.never.accesskey = a
webNotifications.alwaysBlock = Bloker altid
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = Bloker
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Giv %S lov til at sende beskeder?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S ønsker at få adgang til andre apps og tjenester på denne enhed.
localhost.remember2 = Husk mit valg for dette websted
localhost.allowlabel = Tillad
localhost.blocklabel = Bloker
localhost.allow.accesskey = T
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S ønsker at få adgang til apps og tjenester på enheder forbundet til dit lokale netværk.
localNetwork.remember2 = Husk mit valg for dette websted
localNetwork.allowLabel = Tillad
localNetwork.allow.accesskey = T
localNetwork.blockLabel = Bloker
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Få mig væk herfra!
safebrowsing.getMeOutOfHereButton.accessKey = F
safebrowsing.deceptiveSite = Vildledende websted!
safebrowsing.notADeceptiveSiteButton.label = Dette er ikke et vildledende websted…
safebrowsing.notADeceptiveSiteButton.accessKey = D
safebrowsing.reportedAttackSite = Anmeldt angrebswebsted!
safebrowsing.notAnAttackButton.label = Dette er ikke et websted som spreder skadelig software…
safebrowsing.notAnAttackButton.accessKey = D
safebrowsing.reportedUnwantedSite = Anmeldt websted med uønsket software!
safebrowsing.reportedHarmfulSite = Anmeldt skadeligt websted!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Søg %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Genstart %S i fejlsøgnings-tilstand?
troubleshootModeRestartPromptMessage = Dine udvidelser, temaer og tilpassede indstillinger bliver deaktiveret midlertidigt.
troubleshootModeRestartButton = Genstart
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Denne side gør %1$S langsom. Stop siden for at gøre din browser hurtigere.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = En webside gør %1$S langsom. Stop siden for at gøre din browser hurtigere.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = "%1$S" gør %2$S langsom. Stop siden for at gøre din browser hurtigere.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = “%1$S” gør %2$S langsom. Stop udvidelsen for at gøre din browser hurtigere.
processHang.add-on.learn-more.text = Læs mere
processHang.button_stop2.label = Stop
processHang.button_stop2.accessKey = S
processHang.button_debug.label = Debug script
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Vis vinduet i fuld skærm (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Flyt sidepanelet til venstre
sidebar.moveToRight = Flyt sidepanelet til højre
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Du skal aktivere DRM for at afspille lyd eller video på denne side.
emeNotifications.drmContentDisabled.button.label = Aktivér DRM
emeNotifications.drmContentDisabled.button.accesskey = A
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S er ved at installere komponenter, der er nødvendige for at afspille lyd eller video på siden. Prøv venligst igen senere.
emeNotifications.unknownDRMSoftware = Ukendt
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Tilpas %S
decoder.noCodecs.button = Læs mere
decoder.noCodecs.accesskey = L
decoder.noCodecsLinux.message = For at afspille video skal du muligvis installere de påkrævede video-codecs.
decoder.noHWAcceleration.message = For at forbedre video-kvaliteten skal du muligvis installere Microsofts Media Feature Pack.
decoder.noPulseAudio.message = PulseAudio skal være installeret for at du kan afspille lyd.
decoder.unsupportedLibavcodec.message = libavcodec kan være sårbar eller er ikke understøttet. Du bør opdatere libavcodec for at afspille video.
decoder.decodeError.message = Der opstod en fejl under dekodning af et medie
decoder.decodeError.button = Indrapporter problem
decoder.decodeError.accesskey = I
decoder.decodeWarning.message = Der opstod en oprettelig fejl under dekodning af et medie
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Du skal logge ind på dette netværk for at kunne tilgå internettet.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Åbn netværkets login-side
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Tilladelser for %S
permissions.remove.tooltip = Ryd denne tilladelse og spørg igen
permissions.fullscreen.promptCanceled = Annullerede ventende anmodning om tilladelse. Anmodninger om tilladelser bør ikke udstedes før aktivering af DOM fullscreen.
permissions.fullscreen.fullScreenCanceled = Gik ud af DOM fullscreen. Anmodninger om tilladelser bør ikke udstedes i DOM fullscreen.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bit
aboutDialog.architecture.thirtyTwoBit = 32-bit
midi.allow.label = Tillad
midi.allow.accesskey = T
midi.block.label = Bloker
midi.block.accesskey = B
midi.remember = Husk dette valg
midi.shareWithFile = Tillad denne lokale fil at få adgang til dine MIDI-enheder?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Tillad %S at få adgang til dine MIDI-enheder?
midi.shareSysexWithFile = Tillad denne lokale fil at få adgang til dine MIDI-enheder og sende/modtage SysEx-beskeder?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Tillad %S at få adgang til dine MIDI-enheder og sende/modtage SysEx-beskeder?
serial.allow.label = Tillad
serial.allow.accesskey = T
serial.block.label = Bloker
serial.block.accesskey = B
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Tilbage
storageAccess1.Allow.label = Tillad
storageAccess1.Allow.accesskey = T
storageAccess1.DontAllow.label = Bloker
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Tillad %1$S at bruge sine cookies på %2$S?
storageAccess1.hintText = Overvej at blokere adgangen, hvis det ikke er tydeligt, hvorfor %1$S behøver disse data.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Søg efter "%S" på nettet
