# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = Pot buk me Web man tye kanyutu ne nitit ni i kabedo manyen. Onyo imito cwalo tic ma i coyo nitit kabedo manyen?
# Directory listing strings
DirTitle = Namba pi %1$S
DirGoUp = Naka wa i lanyut me rwom me boc me lamal
ShowHidden = Nyut cal mukane
DirColName = Nying
DirColSize = Dite
DirColMTime = Ma giyub me Agiki
DirFileLabel = Pwail:\u0020
UnsafeUriBlocked = Jami tic ma i “%1$S” kigengo woko ki Yeny Maber.
