# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = Ndee lowre geese woni ko e ɓennineede to nokku goɗɗo. Aɗa yiɗi neltirde keɓe formere nde tappu-ɗaa ndee to nokku keso oo?
# Directory listing strings
DirTitle = Enndekse %1$S
DirGoUp = Dow fayde to runngere ɓurnde toowde
ShowHidden = Hollu piije cuuɗiiɗe
DirColName = Innde
DirColSize = Ɓetol
DirColMTime = Waylaa Sakket
DirFileLabel = Fiilde:\u0020
UnsafeUriBlocked = Keɓe to “%1$S” paddaama ngam hisnude banngagol.
