# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Søker etter { $host } …
network-connection-status-connected = Tilkoblet { $host } …
network-connection-status-sending-request = Sender forespørsel til { $host } …
network-connection-status-transferring-data = Overfører data fra { $host } …
network-connection-status-connecting = Kobler til { $host } …
network-connection-status-read = Leste { $host }
network-connection-status-wrote = Skrev { $host }
network-connection-status-waiting = Venter på { $host } …
network-connection-status-looked-up = Søkte etter { $host } …
network-connection-status-tls-handshake = Utfører en TLS-handshake med { $host }…
network-connection-status-tls-handshake-finished = TLS-handshake fullført for { $host }…
