# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Server { $host } opzoeken…
network-connection-status-connected = Verbonden met { $host }…
network-connection-status-sending-request = Aanvraag verzenden naar { $host }…
network-connection-status-transferring-data = Gegevens overbrengen van { $host }…
network-connection-status-connecting = Verbinden met { $host }…
network-connection-status-read = { $host } gelezen
network-connection-status-wrote = { $host } geschreven
network-connection-status-waiting = Wachten op { $host }…
network-connection-status-looked-up = { $host } opgezocht…
network-connection-status-tls-handshake = Een TLS-handshake uitvoeren op { $host }…
network-connection-status-tls-handshake-finished = De TLS-handshake voor { $host } is voltooid…
