# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title ओळखचिन्हे


#define bookmarks_heading ओळखचिन्हे


#define bookmarks_toolbarfolder ओळखचिन्हे साधनपट्टी फोल्डर


#define bookmarks_toolbarfolder_description ओळखचिन्हे साधनपट्टीवर दाखवण्यासाठी या फोल्डरवर ओळखचिन्हे समाविष्ट करा


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/firefox/central/


#define getting_started सुरू करा


# LOCALIZATION NOTE (firefox_heading):


# Firefox links folder name


#define firefox_heading मोझिला फायरफॉक्स


# LOCALIZATION NOTE (firefox_help):


# link title for https://www.mozilla.org/en-US/firefox/help/


#define firefox_help मदत व ट्यूटोरिअल्स्


# LOCALIZATION NOTE (firefox_customize):


# link title for https://www.mozilla.org/en-US/firefox/customize/


#define firefox_customize फायरफॉक्स पसंतीचे करा


# LOCALIZATION NOTE (firefox_community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox_community सामिल व्हा


# LOCALIZATION NOTE (firefox_about):


# link title for https://www.mozilla.org/en-US/about/


#define firefox_about आमच्या विषयी


# LOCALIZATION NOTE (firefox_feedback):


# link title for browser feedback page


# currently used by Metro only: https://input.mozilla.org/feedback/metrofirefox


#define firefox_feedback प्रतिसाद पाठवा


#unfilter emptyLines
