# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = Ochish
    .accesskey = O
places-open-tab =
    .label = Yangi ichki oynada ochish
    .accesskey = n
places-open-all-in-tabs =
    .label = Barchasini ichki oynalarda ochish
    .accesskey = o
places-open-window =
    .label = Yangi oynada ochish
    .accesskey = Y
places-new-bookmark =
    .label = Yangi xatchoʻp
    .accesskey = x
places-new-folder-contextmenu =
    .label = Yangi jild
    .accesskey = F
places-new-folder =
    .label = Yangi jild
    .accesskey = j
places-new-separator =
    .label = Yangi ajratgich
    .accesskey = a
places-view =
    .label = Koʻrinishi
    .accesskey = i
places-by-date =
    .label = Sana boʻyicha
    .accesskey = S
places-by-site =
    .label = Sayt boʻyicha
    .accesskey = S
places-by-most-visited =
    .label = Koʻp kirilganligi boʻyicha
    .accesskey = K
places-by-last-visited =
    .label = Soʻnggi kirilgani boʻyicha
    .accesskey = S
places-by-day-and-site =
    .label = Sana va sayt boʻyicha
    .accesskey = S
places-delete-domain-data =
    .label = Bu saytni unutish
    .accesskey = u
places-sortby-name =
    .label = Nomi boʻyicha saralash
    .accesskey = r
places-properties =
    .label = Xossalari
    .accesskey = r
