# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

#   $date (String) - the formatted example date
dateformat-long =
    .label = Dài: { $date }
weekstart-label =
    .value = Bắt đầu tuần vào:
    .accesskey = B
day-2-name =
    .label = Thứ Hai
day-3-name =
    .label = Thứ Ba
day-4-name =
    .label = Thứ Tư
day-5-name =
    .label = Thứ Năm
day-6-name =
    .label = Thứ Sáu
day-7-name =
    .label = Thứ Bảy
day-1-checkbox =
    .label = ChN
    .accesskey = C
day-2-checkbox =
    .label = Th2
    .accesskey = 2
day-3-checkbox =
    .label = Th3
    .accesskey = 3
day-4-checkbox =
    .label = Th4
    .accesskey = 4
day-5-checkbox =
    .label = Th5
    .accesskey = 5
day-6-checkbox =
    .label = Th6
    .accesskey = 6
day-7-checkbox =
    .label = Th7
    .accesskey = 7
visible-hours-label =
    .value = Hiện:
    .accesskey = H
visible-hours-end-label =
    .value = giờ cùng một lúc
day-start-label =
    .value = Ngày bắt đầu lúc:
    .accesskey = N
day-end-label =
    .value = Ngày kết thúc lúc:
    .accesskey = y
midnight-label =
    .label = Nửa đêm
noon-label =
    .label = Trưa
number-of-weeks-label =
    .value = Số lượng tuần mà bạn muốn hiển thị (bao gồm cả các tuần trước đó):
    .accesskey = l
week-0-label =
    .label = không
week-1-label =
    .label = 1 tuần
week-2-label =
    .label = 2 tuần
week-3-label =
    .label = 3 tuần
week-4-label =
    .label = 4 tuần
week-5-label =
    .label = 5 tuần
week-6-label =
    .label = 6 tuần
previous-weeks-label =
    .value = Số lượng tuần trước đó mà bạn muốn hiển thị:
    .accesskey = S
reminder-legend = Khi đổ chuông báo:
alarm-on-label =
    .label = Bật
alarm-off-label =
    .label = Tắt
category-edit-label = Chỉnh sửa Phân mục
category-overwrite-title = Cảnh báo: Trùng tên
category-overwrite = Đã tồn tại một phân mục có tên đó. Bạn có muốn ghi đè nó không?
category-blank-warning = Bạn phải nhập một tên phân mục.
