# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-title = Calendario
calendar-title-reminder = Recordatorios
calendar-title-category = Categorías
dateformat-label =
    .value = Formato de texto de fecha:
    .accesskey = F
#   $date (String) - the formatted example date
dateformat-long =
    .label = Largo: { $date }
#   $date (String) - the formatted example date
dateformat-short =
    .label = Corto: { $date }
timezone-label =
    .value = Zona horaria:
weekstart-label =
    .value = Comenzar la semana en:
    .accesskey = z
day-1-name =
    .label = Domingo
day-2-name =
    .label = Lunes
day-3-name =
    .label = Martes
day-4-name =
    .label = Miércoles
day-5-name =
    .label = Jueves
day-6-name =
    .label = Viernes
day-7-name =
    .label = Sábado
show-weeknumber-label =
    .label = Mostrar el número de semana en las vistas y el minimés
    .accesskey = M
workdays-label =
    .value = Días laborables:
day-1-checkbox =
    .label = Dom
    .accesskey = D
day-2-checkbox =
    .label = Lun
    .accesskey = L
day-3-checkbox =
    .label = Mar
    .accesskey = M
day-4-checkbox =
    .label = Mié
    .accesskey = i
day-5-checkbox =
    .label = Jue
    .accesskey = J
day-6-checkbox =
    .label = Vie
    .accesskey = V
day-7-checkbox =
    .label = Sáb
    .accesskey = S
dayweek-legend = Vistas diaria y semanal
visible-hours-label =
    .value = Mostrar:
    .accesskey = o
visible-hours-end-label =
    .value = horas a la vez
day-start-label =
    .value = El día comienza a las:
    .accesskey = d
day-end-label =
    .value = El día termina a las:
    .accesskey = t
midnight-label =
    .label = Medianoche
noon-label =
    .label = Mediodía
location-checkbox =
    .label = Mostrar dirección
    .accesskey = d
multiweek-legend = Vista multisemana
number-of-weeks-label =
    .value = Número de semanas a mostrar (incluyendo semanas previas):
    .accesskey = e
week-0-label =
    .label = ninguna
week-1-label =
    .label = 1 semana
week-2-label =
    .label = 2 semanas
week-3-label =
    .label = 3 semanas
week-4-label =
    .label = 4 semanas
week-5-label =
    .label = 5 semanas
week-6-label =
    .label = 6 semanas
previous-weeks-label =
    .value = Semanas previas a mostrar:
    .accesskey = p
todaypane-legend = Panel Para hoy
# Note: "Upcoming" is the name of a section and the translation must match the
# translation of that section name (calendar.upcoming.button.label). Also,
# it should be upper case (as a proper name) if the target language permits.
soon-label =
    .value = La sección Próximamente muestra:
    .accesskey = P
event-task-legend = Eventos y tareas
default-length-label =
    .value = Longitud predeterminada de eventos y tareas:
    .accesskey = L
task-start-label =
    .value = Fecha de inicio:
task-start-1-label =
    .label = Ninguna
task-start-2-label =
    .label = Comienzo del día
task-start-3-label =
    .label = Final del día
task-start-4-label =
    .label = Mañana
task-start-5-label =
    .label = Semana siguiente
task-start-6-label =
    .label = Relativo a la hora actual
task-start-7-label =
    .label = Relativo al comienzo
task-start-8-label =
    .label = Relativo a la hora siguiente
task-due-label =
    .value = Fecha límite:
edit-intab-label =
    .label = Editar eventos y tareas en una pestaña en lugar de en una ventana de diálogo.
    .accesskey = t
accessibility-legend = Accesibilidad
accessibility-colors-label =
    .label = Optimizar colores para accesibilidad
    .accesskey = O
reminder-legend = Cuando se activa un aviso:
reminder-play-checkbox =
    .label = Reproducir sonido
    .accesskey = R
reminder-play-alarm-button =
    .label = Reproducir
    .accesskey = e
reminder-default-sound-label =
    .label = Usar sonido predeterminado
    .accesskey = d
reminder-custom-sound-label =
    .label = Usar el siguiente archivo de sonido
    .accesskey = U
reminder-browse-sound-label =
    .label = Examinar...
    .accesskey = x
reminder-dialog-label =
    .label = Mostrar la ventana de aviso
    .accesskey = M
missed-reminder-label =
    .label = Mostrar recordatorios ocultados en calendarios escribibles
    .accesskey = o
reminder-default-legend = Valores predeterminados para avisos
default-snooze-label =
    .value = Duración predeterminada del retardo:
    .accesskey = u
event-alarm-label =
    .value = Config. predet. de aviso para eventos:
    .accesskey = C
alarm-on-label =
    .label = Encendido
alarm-off-label =
    .label = Apagado
task-alarm-label =
    .value = Config. predet. de aviso para tareas:
    .accesskey = n
event-alarm-time-label =
    .value = Antelación predet. con la que un aviso aparece antes de un evento:
    .accesskey = P
task-alarm-time-label =
    .value = Antelación predet. con la que un aviso aparece antes de una tarea:
    .accesskey = v
category-new-label = Nueva categoría
category-edit-label = Editar categoría
category-overwrite-title = Advertencia: nombre duplicado
category-overwrite = Ya existe una categoría con ese nombre. ¿Quiere sobreescribirla?
category-blank-warning = Debe introducir un nombre de categoría.
