#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're 

# live.


#define bookmarks_title Leabharmharcanna


#define bookmarks_heading Leabharmharcanna



#define bookmarks_toolbarfolder Fillteán do Bharra Uirlisí Leabharmharcanna



#define bookmarks_toolbarfolder_description Cuir leabharmharcanna san fhillteán seo chun iad a thaispeáint ar Bharra na Leabharmharcanna.




# LOCALIZATION NOTE (getting_started):




# link title for http://en-US.www.mozilla.com/en-US/firefox/central/




#define getting_started Tús Maith





# LOCALIZATION NOTE (latest_headlines):





# link title for the live bookmarks sample, a redirect on





# http://en-US.fxfeeds.mozilla.com/en-US/firefox/headlines.xml





# Changing the redirect is subject to approval of l10n-drivers.





#define latest_headlines Na Cinnlínte Is Déanaí






# LOCALIZATION NOTE (firefox_heading):






# Firefox links folder name






#define firefox_heading Mozilla Firefox







# LOCALIZATION NOTE (firefox_help):







# link title for http://en-US.www.mozilla.com/en-US/firefox/help/







#define firefox_help Cabhair agus Cúrsaí Teagaisc








# LOCALIZATION NOTE (firefox_customize):








# link title for http://en-US.www.mozilla.com/en-US/firefox/customize/








#define firefox_customize Saincheap Firefox









# LOCALIZATION NOTE (firefox_community):









# link title for http://en-US.www.mozilla.com/en-US/firefox/community/









#define firefox_community Glac Páirt










# LOCALIZATION NOTE (firefox_about):










# link title for http://en-US.www.mozilla.com/en-US/about/










#define firefox_about Maidir Linn











#unfilter emptyLines
