# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Kas usaldad SK-d "%S" järgnevaks otstarbeks?
unnamedCA = Sertifitseerimiskeskus (nimi määramata)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Palun sisesta selle sertifikaadi varukoopia krüptimiseks kasutatud parool:
# Page Info
pageInfo_NoEncryption = Ühendus pole krüptitud
pageInfo_Privacy_None1 = Veebileht %S ei toeta vaadatava lehe näitamisel krüptimist.
pageInfo_Privacy_None2 = Interneti kaudu ülekantavad krüptimata andmed võivad olla ülekande ajal nähtavad ka teistele inimestele.
pageInfo_Privacy_None4 = Kuvatav leht edastati krüptimata kujul.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Krüptitud ühendus (%1$S, %2$S-bitised võtmed, %3$S)
pageInfo_BrokenEncryption = Ebaturvaline krüpteering (%1$S, %2$S-bitised võtmed, %3$S)
pageInfo_Privacy_Encrypted1 = Vaadatava lehe sisu krüptiti enne interneti teel edastamist.
pageInfo_Privacy_Encrypted2 = Krüptimine teeb volitamata isikutel arvutite vahel edastatava info vaatamise keeruliseks. Seetõttu pole tõenäoline, et keegi sai selle lehe sisu võrgus edastamise ajal lugeda.
pageInfo_MixedContent = Osaliselt krüptitud ühendus
pageInfo_MixedContent2 = Vaadatava veebilehe osasid ei krüptitud enne nende interneti teel edastamist.
pageInfo_WeakCipher = Sinu ühendus selle saidiga on turvatud nõrga krüpteeringuga ja pole seetõttu privaatne. Teised inimesed saavad vaadata sinu andmeid või muuta veebilehe käitumist.
pageInfo_CertificateTransparency_Compliant = See sait on vastavuses läbipaistvate sertifikaatide poliitikaga.
# Token Manager
password_not_set = (määramata)
