# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = ‫מחפש את ‪{ $host }‬…
network-connection-status-connected = ‫מחובר אל ‪{ $host }‬…‬
network-connection-status-sending-request = נשלחת בקשה אל ‪{ $host }‬…
network-connection-status-transferring-data = ‫מעביר נתונים מ־‪{ $host }‬…
network-connection-status-connecting = ‫מתחבר אל ‪{ $host }‬…
network-connection-status-read = קריאת ‪{ $host }‬‬
network-connection-status-wrote = ‫כותב את ‪{ $host }‬‬
network-connection-status-waiting = ‫בהמתנה ל־‪{ $host }‬…
network-connection-status-looked-up = מאתר ‬{ $host }‬…
network-connection-status-tls-handshake = הזדהות TLS עבור { $host } בביצוע…
network-connection-status-tls-handshake-finished = הזדהות TLS הסתיימה עבור { $host }…
