# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Ingin mempercayai "%S" untuk penggunaan berikut?
unnamedCA = Otoritas Sertifikat (tanpa nama)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Masukkan sandi yang digunakan untuk mengenkripsi cadangan sertifikat:
# Page Info
pageInfo_NoEncryption = Sambungan Tak Terenkripsi
pageInfo_Privacy_None1 = Situs web %S tidak mendukung enkripsi untuk laman yang Anda lihat.
pageInfo_Privacy_None2 = Informasi tanpa enkripsi yang dikirim lewat Internet dapat dilihat oleh pihak lain dalam perjalanan.\u0020
pageInfo_Privacy_None4 = Laman yang sedang Anda lihat tidak dienkripsi sebelum dikirim melalui Internet.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Sambungan Terenkripsi (%1$S, kunci %2$S bita, %3$S)
pageInfo_BrokenEncryption = Enkripsi Rusak (%1$S, kunci %2$S bita, %3$S)
pageInfo_Privacy_Encrypted1 = Laman yang dilihat telah dienkripsi sebelum dikirim melalui Internet.
pageInfo_Privacy_Encrypted2 = Enkripsi membuat informasi yang disampaikan antar komputer lebih sulit dilihat oleh pihak yang tidak diizinkan. Oleh karenanya, sangat tidak umum seseorang mampu membaca laman ini saat ditransfer melalui jaringan.
pageInfo_MixedContent = Sambungan Terenkripsi Sebagian
pageInfo_MixedContent2 = Beberapa bagian dari laman yang dilihat tidak dienkripsi sebelum dikirim melalui Internet.
pageInfo_WeakCipher = Sambungan Anda ke situs web ini menggunakan enkripsi leman dan tidak pribadi. Orang lain dapat melihat informasi Anda atau memodifikasi perilaku situs web ini.
pageInfo_CertificateTransparency_Compliant = Situs ini tunduk pada kebijakan Transparansi Sertifikat.
# Token Manager
password_not_set = (belum diatur)
