# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Wachttijd verstreken
openFile = Bestand openen
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Zoeken bij %1$S naar ‘%2$S’
contextMenuSearch.accesskey = Z
contextMenuPrivateSearch = Zoeken in een privévenster
contextMenuPrivateSearch.accesskey = Z
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Met %S zoeken in een privévenster
contextMenuPrivateSearchOtherEngine.accesskey = M
bookmarkAllTabsDefault = [Mapnaam]
unsignedAddonsDisabled.message = Een of meer geïnstalleerde add-ons kunnen niet worden geverifieerd en zijn uitgeschakeld.
unsignedAddonsDisabled.learnMore.label = Meer info
unsignedAddonsDisabled.learnMore.accesskey = M
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Laatste toegang %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = %S://-koppelingen
crashedpluginsMessage.title = De %S-plug-in is gecrasht.
crashedpluginsMessage.reloadButton.label = Pagina vernieuwen
crashedpluginsMessage.reloadButton.accesskey = n
crashedpluginsMessage.submitButton.label = Een crashrapport verzenden
crashedpluginsMessage.submitButton.accesskey = c
crashedpluginsMessage.learnMore = Meer info…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Wilde u naar %S gaan?
keywordURIFixup.goTo = Ja, ik wil naar %S
keywordURIFixup.goTo.accesskey = J
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Bijwerken naar %S
update.downloadAndInstallButton.accesskey = B
menuOpenAllInTabs.label = Alle openen in tabbladen
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Deze pagina opnieuw laden
tabHistory.goBack = Terug gaan naar deze pagina
tabHistory.goForward = Vooruit gaan naar deze pagina
# URL Bar
pasteAndGo.label = Plakken & Gaan
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Huidige pagina vernieuwen (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Het laden van deze pagina stoppen (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Zoomniveau terugzetten (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Lezerweergave in-/uitschakelen (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, zoomniveau herinitialiseren
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Uw bladwijzers tonen (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = De voortgang van actieve downloads weergeven (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Een nieuw venster openen (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Een nieuw tabblad openen (%S)
newTabContainer.tooltip = Open een nieuw tabblad (%S)\nHoud ingedrukt om een nieuw containertabblad te openen
newTabAlwaysContainer.tooltip = Selecteer container om een nieuw tabblad te openen
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Toestaan dat %S uw HTML5-canvasafbeeldingsgegevens gebruikt?
canvas.siteprompt2.warning = Dit kan worden gebruikt om uw computer uniek te identificeren.
canvas.block = Blokkeren
canvas.block.accesskey = B
canvas.allow2 = Toestaan
canvas.allow2.accesskey = T
canvas.remember2 = Deze beslissing onthouden
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Geverifieerd door: %S
identity.identified.verified_by_you = U hebt een beveiligingsuitzondering toegevoegd voor deze website.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Certificaat uitgegeven aan: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Niet beveiligd
identity.notSecure.tooltip = Verbinding is niet beveiligd
identity.extension.label = Extensie (%S)
identity.extension.tooltip = Geladen door extensie: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Uitzoomen (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Zoomniveau terugzetten (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Inzoomen (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Knippen (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Kopiëren (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Plakken (%S)
geolocation.allow = Toestaan
geolocation.allow.accesskey = T
geolocation.block = Blokkeren
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Dit opent de systeeminstellingen voor locatie. Verleen locatietoestemming aan %S.
geolocation.shareWithSite4 = Toegang tot uw locatie door %S toestaan?
geolocation.shareWithFile4 = Toegang tot uw locatie door dit lokale bestand toestaan?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Toestaan dat %1$S toestemming aan %2$S geeft voor toegang tot uw locatie?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = %S locatietoestemming geven in systeeminstellingen.
geolocation.systemSettingsTitle = Wacht op toestemming voor locatie
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Het systeem zal u vragen deze toestemming aan %S te geven.
geolocation.remember = Deze beslissing onthouden
# Virtual Reality Device UI
xr.allow2 = Toestaan
xr.allow2.accesskey = T
xr.block = Blokkeren
xr.block.accesskey = B
xr.shareWithSite4 = Toegang tot virtual-reality-apparaten door %S toestaan? Dit kan gevoelige informatie blootleggen.
xr.shareWithFile4 = Toegang tot virtual-reality-apparaten door dit lokale bestand toestaan? Dit kan gevoelige informatie blootleggen.
xr.remember = Deze beslissing onthouden
# Persistent storage UI
persistentStorage.allow = Toestaan
persistentStorage.allow.accesskey = T
persistentStorage.block.label = Blokkeren
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Bewaren van gegevens in permanente opslag door %S toestaan?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Toestaan
webNotifications.allow2.accesskey = T
webNotifications.notNow = Niet nu
webNotifications.notNow.accesskey = N
webNotifications.never = Nooit toestaan
webNotifications.never.accesskey = o
webNotifications.alwaysBlock = Altijd blokkeren
webNotifications.alwaysBlock.accesskey = b
webNotifications.block = Blokkeren
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = %S toestaan om meldingen te verzenden?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S wil toegang tot andere apps en services op dit apparaat.
localhost.remember2 = Mijn keuze onthouden voor deze website
localhost.allowlabel = Toestaan
localhost.blocklabel = Blokkeren
localhost.allow.accesskey = T
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S wil toegang tot apps en services op apparaten die zijn verbonden met uw lokale netwerk.
localNetwork.remember2 = Mijn keuze onthouden voor deze website
localNetwork.allowLabel = Toestaan
localNetwork.allow.accesskey = T
localNetwork.blockLabel = Blokkeren
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Haal me hier vandaan!
safebrowsing.getMeOutOfHereButton.accessKey = H
safebrowsing.deceptiveSite = Misleidende website!
safebrowsing.notADeceptiveSiteButton.label = Dit is geen misleidende website…
safebrowsing.notADeceptiveSiteButton.accessKey = m
safebrowsing.reportedAttackSite = Gerapporteerde aanvalsite!
safebrowsing.notAnAttackButton.label = Dit is geen aanvalsite…
safebrowsing.notAnAttackButton.accessKey = a
safebrowsing.reportedUnwantedSite = Gerapporteerde website met ongewenste software!
safebrowsing.reportedHarmfulSite = Gerapporteerde schadelijke website!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = %S doorzoeken
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = %S herstarten in probleemoplossingsmodus?
troubleshootModeRestartPromptMessage = Uw extensies, thema’s en aangepaste instellingen worden tijdelijk uitgeschakeld.
troubleshootModeRestartButton = Herstarten
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Deze pagina vertraagt %1$S. Stop deze pagina om uw browser te versnellen.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Een webpagina vertraagt %1$S. Stop die pagina om uw browser te versnellen.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = ‘%1$S’ vertraagt %2$S. Stop die pagina om uw browser te versnellen.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = ‘%1$S’ vertraagt %2$S. Stop die extensie om uw browser te versnellen.
processHang.add-on.learn-more.text = Meer info
processHang.button_stop2.label = Stoppen
processHang.button_stop2.accessKey = S
processHang.button_debug.label = Script debuggen
processHang.button_debug.accessKey = d
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Het venster in volledig scherm weergeven (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Zijbalk naar links verplaatsen
sidebar.moveToRight = Zijbalk naar rechts verplaatsen
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = U moet DRM inschakelen om bepaalde audio of video op deze pagina af te spelen.
emeNotifications.drmContentDisabled.button.label = DRM inschakelen
emeNotifications.drmContentDisabled.button.accesskey = D
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S installeert onderdelen die nodig zijn voor het afspelen van de audio of video op deze pagina. Probeer het later opnieuw.
emeNotifications.unknownDRMSoftware = Onbekend
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = %S aanpassen
decoder.noCodecs.button = Meer info
decoder.noCodecs.accesskey = M
decoder.noCodecsLinux.message = Om video af te spelen, dient u mogelijk de vereiste videocodecs te installeren.
decoder.noHWAcceleration.message = Om de videokwaliteit te verbeteren, dient u mogelijk Microsofts Media Feature Pack te installeren.
decoder.noPulseAudio.message = Om audio af te spelen, dient u mogelijk de vereiste PulseAudio-software te installeren.
decoder.unsupportedLibavcodec.message = libavcodec kan kwetsbaar zijn of wordt niet ondersteund, en dient te worden bijgewerkt om video af te spelen.
decoder.decodeError.message = Er is een fout opgetreden tijdens het decoderen van een mediabron.
decoder.decodeError.button = Websiteprobleem melden
decoder.decodeError.accesskey = W
decoder.decodeWarning.message = Er is een herstelbare fout opgetreden tijdens het decoderen van een mediabron.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = U moet zich aanmelden bij dit netwerk voordat u toegang hebt tot het internet.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Aanmeldingspagina voor netwerk openen
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Toestemmingen voor %S
permissions.remove.tooltip = Deze toestemming wissen en opnieuw vragen
permissions.fullscreen.promptCanceled = Geannuleerde wachtende machtigingsaanvragen: machtigingsaanvragen mogen niet worden toegekend voor het openen van DOM in de modus volledig scherm.
permissions.fullscreen.fullScreenCanceled = DOM-modus in volledig scherm afgesloten: machtigingsaanvragen mogen niet worden toegekend terwijl DOM in volledig scherm wordt uitgevoerd.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bits
aboutDialog.architecture.thirtyTwoBit = 32-bits
midi.allow.label = Toestaan
midi.allow.accesskey = T
midi.block.label = Blokkeren
midi.block.accesskey = B
midi.remember = Deze beslissing onthouden
midi.shareWithFile = Toegang tot uw MIDI-apparaten door dit lokale bestand toestaan?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Toegang tot uw MIDI-apparaten door %S toestaan?
midi.shareSysexWithFile = Toegang tot uw MIDI-apparaten en het verzenden/ontvangen van SysEx-berichten door dit lokale bestand toestaan?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Toegang tot uw MIDI-apparaten en het verzenden/ontvangen van SysEx-berichten door %S toestaan?
serial.allow.label = Toestaan
serial.allow.accesskey = T
serial.block.label = Blokkeren
serial.block.accesskey = B
serial.shareWithFile = Toegang tot uw seriële poorten door dit lokale bestand toestaan?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Toegang tot uw seriële poorten door %S toestaan?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Terug
storageAccess1.Allow.label = Toestaan
storageAccess1.Allow.accesskey = T
storageAccess1.DontAllow.label = Blokkeren
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = %1$S toestaan zijn cookies te gebruiken op %2$S?
storageAccess1.hintText = U kunt de toegang blokkeren als het niet duidelijk is waarom %1$S deze gegevens nodig heeft.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Op het web naar ‘%S’ zoeken
