# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dateformat-label =
    .value = Format daty:
    .accesskey = F
#   $date (String) - the formatted example date
dateformat-long =
    .label = długi: { $date }
weekstart-label =
    .value = Pierwszy dzień tygodnia:
    .accesskey = e
day-1-name =
    .label = niedziela
day-2-name =
    .label = poniedziałek
day-3-name =
    .label = wtorek
day-4-name =
    .label = środa
day-5-name =
    .label = czwartek
day-6-name =
    .label = piątek
day-7-name =
    .label = sobota
day-1-checkbox =
    .label = Nie
    .accesskey = N
day-2-checkbox =
    .label = Pon
    .accesskey = P
day-3-checkbox =
    .label = Wto
    .accesskey = W
day-4-checkbox =
    .label = Śro
    .accesskey = r
day-5-checkbox =
    .label = Czw
    .accesskey = C
day-6-checkbox =
    .label = Pią
    .accesskey = i
day-7-checkbox =
    .label = Sob
    .accesskey = S
visible-hours-label =
    .value = Wyświetl jednocześnie:
    .accesskey = o
visible-hours-end-label =
    .value = godzin
day-start-label =
    .value = Dzień zaczyna się o:
    .accesskey = z
day-end-label =
    .value = Dzień kończy się o:
    .accesskey = k
midnight-label =
    .label = Północ
noon-label =
    .label = Południe
multiweek-legend = Widok wielu tygodni
number-of-weeks-label =
    .value = Liczba wyświetlanych tygodni (w tym poprzednich tygodni):
    .accesskey = m
week-0-label =
    .label = brak
previous-weeks-label =
    .value = Liczba poprzedzających tygodni:
    .accesskey = L
task-start-label =
    .value = Początek:
task-due-label =
    .value = Koniec:
reminder-legend = Sygnalizacja przypomnień
reminder-play-checkbox =
    .label = Odtwórz dźwięk:
    .accesskey = O
reminder-default-sound-label =
    .label = Użyj domyślnego dźwięku
    .accesskey = d
reminder-browse-sound-label =
    .label = Przeglądaj…
    .accesskey = g
reminder-dialog-label =
    .label = Wyświetl okno przypomnienia
    .accesskey = k
reminder-default-legend = Domyślne ustawienia przypomnień
event-alarm-label =
    .value = Przypomnienia dla wydarzeń:
    .accesskey = y
alarm-on-label =
    .label = włączone
alarm-off-label =
    .label = wyłączone
task-alarm-label =
    .value = Przypomnienia dla zadań:
    .accesskey = a
event-alarm-time-label =
    .value = Czas przypomnienia przed wydarzeniem:
    .accesskey = c
task-alarm-time-label =
    .value = Czas przypomnienia przed zadaniem:
    .accesskey = z
category-edit-label = Edytuj kategorię
category-overwrite-title = Ostrzeżenie: taka nazwa już istnieje
category-blank-warning = Należy wprowadzić nazwę kategorii.
