# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Timpul de conectare a expirat
openFile = Deschide fișierul
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Caută pe %1$S „%2$S”
contextMenuSearch.accesskey = S
contextMenuPrivateSearch = Căutare în fereastră privată
contextMenuPrivateSearch.accesskey = h
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Căutare cu %S într-o fereastră privată
contextMenuPrivateSearchOtherEngine.accesskey = h
bookmarkAllTabsDefault = [Numele dosarului]
unsignedAddonsDisabled.message = Unul sau mai multe suplimente instalate nu pot fi verificate și au fost dezactivate.
unsignedAddonsDisabled.learnMore.label = Află mai multe
unsignedAddonsDisabled.learnMore.accesskey = L
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Ultima accesare %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = Linkuri %S://
crashedpluginsMessage.title = Pluginul %S s-a închis neașteptat.
crashedpluginsMessage.reloadButton.label = Reîncarcă pagina
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = Trimite un raport de defecțiuni
crashedpluginsMessage.submitButton.accesskey = S
crashedpluginsMessage.learnMore = Află mai multe…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Ai vrut să accesezi %S?
keywordURIFixup.goTo = Da, du-mă la %S
keywordURIFixup.goTo.accesskey = Y
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Actualizează la %S
update.downloadAndInstallButton.accesskey = U
menuOpenAllInTabs.label = Deschide-le pe toate în file
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Reîncarcă pagina
tabHistory.goBack = Mergi înapoi pe această pagină
tabHistory.goForward = Navighează înainte la această pagină
# URL Bar
pasteAndGo.label = Inserează și accesează
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Reîncarcă pagina actuală (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Oprește încărcarea paginii (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Resetează nivelul zoomului (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Activează/dezactivează modul de lectură (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, Resetează nivelul de zoom
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Afișează marcajele (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Afișează progresul descărcărilor în curs (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Deschide o fereastră nouă (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Deschide o filă nouă (%S)
newTabContainer.tooltip = Deschide o filă nouă (%S)\nApasă lung pentru a deschide o filă container nouă
newTabAlwaysContainer.tooltip = Selectează un container pentru a deschide o filă nouă
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Permiți %S să îți folosească datele de imagini canvas HTML5?
canvas.siteprompt2.warning = Acestea pot fi folosite pentru a identifica în mod unic calculatorul tău.
canvas.block = Blochează
canvas.block.accesskey = B
canvas.allow2 = Permite
canvas.allow2.accesskey = A
canvas.remember2 = Ține minte decizia
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Verificat de: %S
identity.identified.verified_by_you = Ai adăugat o excepție de securitate pentru acest site.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Certificat emis către: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Nesecurizat
identity.notSecure.tooltip = Conexiunea nu este securizată
identity.extension.label = Extensie (%S)
identity.extension.tooltip = Încărcat de extensia: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Micșorează (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Resetează nivelul zoomului (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Mărește (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Taie (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Copiază (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Inserează (%S)
geolocation.allow = Permite
geolocation.allow.accesskey = A
geolocation.block = Blochează
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Va deschide setările de locație ale sistemului. Te rugăm să acorzi permisiunea de locație pentru %S.
geolocation.shareWithSite4 = Permiți %S să îți acceseze locația?
geolocation.shareWithFile4 = Permiți acestui fișier local să îți acceseze locația?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Permiți %1$S să dea %2$S permisiunea de a-ți accesa locația?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Acordă permisiunea de locație pentru %S în setările de sistem.
geolocation.systemSettingsTitle = Se așteaptă permisiunea pentru locație
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Sistemul îți va cere să acorzi această permisiune pentru %S.
geolocation.remember = Ține minte decizia
# Virtual Reality Device UI
xr.allow2 = Permite
xr.allow2.accesskey = A
xr.block = Blochează
xr.block.accesskey = B
xr.shareWithSite4 = Permiți %S să îți acceseze dispozitivele de realitate virtuală? Pot fi expuse informații sensibile.
xr.shareWithFile4 = Permiți acestui fișier local să îți acceseze dispozitivele de realitate virtuală? Pot fi expuse informații sensibile.
xr.remember = Ține minte decizia
# Persistent storage UI
persistentStorage.allow = Permite
persistentStorage.allow.accesskey = A
persistentStorage.block.label = Blochează
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Permiți %S să stocheze date în stocarea persistentă?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Permite
webNotifications.allow2.accesskey = A
webNotifications.notNow = Nu acum
webNotifications.notNow.accesskey = n
webNotifications.never = Nu permite niciodată
webNotifications.never.accesskey = v
webNotifications.alwaysBlock = Blochează întotdeauna
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = Blochează
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Permiți %S să trimită notificări?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S vrea acces la alte aplicații și servicii de pe acest dispozitiv.
localhost.remember2 = Ține minte decizia pentru acest site
localhost.allowlabel = Permite
localhost.blocklabel = Blochează
localhost.allow.accesskey = A
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S vrea acces la aplicații și servicii de pe dispozitive conectate în rețeaua ta locală.
localNetwork.remember2 = Ține minte decizia pentru acest site
localNetwork.allowLabel = Permite
localNetwork.allow.accesskey = A
localNetwork.blockLabel = Blochează
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Du-mă de aici!
safebrowsing.getMeOutOfHereButton.accessKey = G
safebrowsing.deceptiveSite = Site înșelător!
safebrowsing.notADeceptiveSiteButton.label = Nu este un site înșelător…
safebrowsing.notADeceptiveSiteButton.accessKey = D
safebrowsing.reportedAttackSite = Raportat ca site de atac!
safebrowsing.notAnAttackButton.label = Nu este un site de atac…
safebrowsing.notAnAttackButton.accessKey = A
safebrowsing.reportedUnwantedSite = Raportat ca site cu programe nedorite!
safebrowsing.reportedHarmfulSite = Raportat ca site dăunător!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Caută %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Repornești %S în modul de depanare?
troubleshootModeRestartPromptMessage = Suplimentele, temele și setările personalizate vor fi dezactivate temporar.
troubleshootModeRestartButton = Repornește
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Această pagină încetinește %1$S. Pentru a accelera browserul, oprește pagina.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = O pagină web încetinește %1$S. Pentru a accelera browserul, oprește pagina.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = „%1$S” încetinește %2$S. Pentru a accelera browserul, oprește pagina.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = „%1$S” încetinește %2$S. Pentru a accelera browserul, oprește extensia.
processHang.add-on.learn-more.text = Află mai multe
processHang.button_stop2.label = Stop
processHang.button_stop2.accessKey = S
processHang.button_debug.label = Depanează scriptul
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Afișează fereastra în modul ecran complet (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Mută bara laterală în stânga
sidebar.moveToRight = Mută bara laterală în dreapta
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Trebuie să activezi DRM pentru redare audio sau video pe această pagină.
emeNotifications.drmContentDisabled.button.label = Activează DRM
emeNotifications.drmContentDisabled.button.accesskey = E
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S instalează componentele necesare pentru a reda videoclipurile sau sunetele de pe aceasta pagină. Te rugăm să încerci din nou mai târziu.
emeNotifications.unknownDRMSoftware = Necunoscut
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Personalizează %S
decoder.noCodecs.button = Află cum
decoder.noCodecs.accesskey = L
decoder.noCodecsLinux.message = Pentru a redare video, ar putea fi necesară instalarea de codecuri video.
decoder.noHWAcceleration.message = Pentru a îmbunătăți calitatea video, ar putea fi necesară instalarea pachetului de funcții media de la Microsoft.
decoder.noPulseAudio.message = Pentru redare audio ar putea fi necesară instalarea programelor PulseAudio.
decoder.unsupportedLibavcodec.message = Este posibil ca libavcodec să fie vulnerabil sau să nu fie suportat și trebuie actualizat pentru redare video.
decoder.decodeError.message = A intervenit o eroare la decodarea unei resurse media.
decoder.decodeError.button = Raportează problemă cu site-ul
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = A intervenit o eroare recuperabilă la decodarea unei resurse media.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Trebuie să te autentifici la această rețea înainte de a accesa internetul.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Deschide pagina de autentificare în rețea
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Permisiuni pentru %S
permissions.remove.tooltip = Șterge permisiunea și cere una din nou
permissions.fullscreen.promptCanceled = Cereri de permisiuni în așteptare anulate: cererile de permisiuni nu trebuie emise înainte de a intra în DOM pe ecran complet.
permissions.fullscreen.fullScreenCanceled = S-a ieșit din DOM pe ecran complet: cererile de permisiuni nu trebuie emise cât timp DOM e în ecran complet.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64 de biți
aboutDialog.architecture.thirtyTwoBit = 32 de biți
midi.allow.label = Permite
midi.allow.accesskey = A
midi.block.label = Blochează
midi.block.accesskey = B
midi.remember = Ține minte această decizie
midi.shareWithFile = Permiți acestui fișier local să îți acceseze dispozitivele MIDI?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Permiți %S să îți acceseze dispozitivele MIDI?
midi.shareSysexWithFile = Permiți acestui fișier local să îți acceseze dispozitivele MIDI și să trimită/să primească mesaje SysEx?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Permiți %S să îți acceseze dispozitivele MIDI și să trimită/să primească mesaje SysEx?
serial.allow.label = Permite
serial.allow.accesskey = A
serial.block.label = Blochează
serial.block.accesskey = B
serial.shareWithFile = Permiți acestui fișier local să îți acceseze porturile seriale?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Permiți %S să îți acceseze porturile seriale?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Înapoi
storageAccess1.Allow.label = Permite
storageAccess1.Allow.accesskey = A
storageAccess1.DontAllow.label = Blochează
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Permiți %1$S să-și folosească cookie-urile pe %2$S?
storageAccess1.hintText = Poate vrei să blocați accesul dacă nu este clar de ce are nevoie %1$S de aceste date.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Caută „%S” pe web
