# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = এই ৱেব পৃষ্ঠাৰ নতুন স্থানলৈ নিৰ্দেশ কৰা হৈছে। আপুনি লিখা ফৰ্মৰ তথ্য সেই নতুন স্থানলৈ পুনৰ পঠিয়াব বিচাৰে নেকি ?
# Directory listing strings
DirTitle = %1$S ৰ সূচিপত্ৰ
DirGoUp = ওপৰৰ স্তৰৰ ডাইৰেকটৰিলৈ
ShowHidden = লুকুৱা বস্তু দেখুৱাওক
DirColName = নাম
DirColSize = আকাৰ
DirColMTime = শেহতীয়াভাবে সলনি কৰা
DirFileLabel = ফাইল:\u0020
UnsafeUriBlocked = নিৰাপদ ব্ৰাউজিং দ্বাৰা “%1$S”ত থকা সম্পদ অৱৰোধ কৰা হৈছে।
