# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Wzeranié za adresã serwera { $host }…
network-connection-status-connected = Sparłãczony z { $host }…
network-connection-status-sending-request = Sélanié żądaniô do { $host }…
network-connection-status-transferring-data = Sélanié pòdôwków z { $host }…
network-connection-status-connecting = Parłãczenié sã z { $host }…
network-connection-status-read = Przeczëtano { $host }
network-connection-status-wrote = Zapisano { $host }
network-connection-status-waiting = Żdanié za { $host }…
network-connection-status-looked-up = Looked up { $host }…
