# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

report-broken-site-mainview-title = Eman hondatutako gunearen berri
report-broken-site-panel-header =
    .label = Eman hondatutako gunearen berri
    .title = Eman hondatutako gunearen berri
report-broken-site-panel-intro-text = Zure txostenak { -brand-product-name }(e)n arazoak ulertu eta konpontzen laguntzen digu, horrela denontzat hobetzeko.
report-broken-site-panel-learn-more-link = Argibide gehiago
report-broken-site-panel-intro = Lagundu { -brand-product-name } denontzat hobetzen. { -vendor-short-name }(e)k zuk bidalitako informazioa webguneetako arazoak konpontzeko erabiltzen du.
report-broken-site-panel-url = URLa
report-broken-site-panel-reason-label = Zer dago hondatuta?
report-broken-site-panel-reason-optional-label = Zer dago hondatuta? (aukerakoa)
report-broken-site-panel-reason-choose =
    .label = Aukeratu arrazoia
report-broken-site-panel-reason-load =
    .label = Gunea ez da kargatzen
# These terms are referring to ecommerce websites
report-broken-site-panel-reason-checkout =
    .label = Ezin da ordaindu edo erosketarik egin
report-broken-site-panel-reason-slow2 =
    .label = Gunea mantso doa
report-broken-site-panel-reason-media2 =
    .label = Bideoa ez da erreproduzitzen edo kargatzen
report-broken-site-panel-reason-content2 =
    .label = Edukia falta da
report-broken-site-panel-reason-account2 =
    .label = Ezin da saioa hasi edo erregistratu
report-broken-site-panel-reason-adblocker2 =
    .label = Guneak iragarki-blokeatzailea desgaitzeko eskatu du
report-broken-site-panel-reason-notsupported =
    .label = Nabigatzailea ez da onartzen edo blokeatuta dago
report-broken-site-panel-reason-other =
    .label = Beste zerbait
report-broken-site-panel-description-label = Azaldu arazoa
report-broken-site-panel-description =
    .placeholder = Zer gertatu da? Zer gertatu beharko luke? Lagundu du jarraipenaren babesa desaktibatzeak?
report-broken-site-panel-description-optional-label = Azaldu arazoa (aukerakoa)
report-broken-site-panel-send-more-info-link = Bidali informazio gehiago
report-broken-site-panel-button-cancel =
    .label = Utzi
report-broken-site-panel-button-okay =
    .label = Ados
report-broken-site-panel-button-send =
    .label = Bidali
report-broken-site-panel-report-sent-label = Zure txostena bidali da
report-broken-site-panel-report-sent-header =
    .label = Zure txostena bidali da
    .title = Zure txostena bidali da
report-broken-site-panel-report-sent-text = Eskerrik asko { -brand-product-name }(r)i laguntzeagatik weba denontzat irekiagoa, eskuragarriagoa eta hobeagoa egiten.
report-broken-site-panel-invalid-url-label = Idatzi baliozko URLa
report-broken-site-panel-missing-reason-label = Aukeratu arrazoia
report-broken-site-panel-blocked-trackers-label =
    .label = Bidali jarraipenaren babesak blokeatutako URLak
report-broken-site-panel-blocked-trackers-description = Webguneek behar bezala aritzeko behar dituzten jarraipen-elementu eta scriptak blokea litzake jarraipenaren babes hobetuak.
report-broken-site-panel-preview-button =
    .label = Aurreikusi txostena
report-broken-site-panel-preview-header =
    .label = Aurreikusi txostena
