# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Tempore limite excedite
openFile = Aperir le file
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Cercar “%2$S” in %1$S
contextMenuSearch.accesskey = e
contextMenuPrivateSearch = Cercar in un fenestra private
contextMenuPrivateSearch.accesskey = c
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Cercar con %S in un fenestra private
contextMenuPrivateSearchOtherEngine.accesskey = c
bookmarkAllTabsDefault = [Nomine del dossier]
unsignedAddonsDisabled.message = Un o plus additivos installate non ha potite esser verificate e ha essite disactivate.
unsignedAddonsDisabled.learnMore.label = Saper plus
unsignedAddonsDisabled.learnMore.accesskey = L
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Ultime accesso le %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = Ligamines de %S://
crashedpluginsMessage.title = Le plugin %S ha collabite.
crashedpluginsMessage.reloadButton.label = Recarga le pagina
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = Submitter un reporto de collapso
crashedpluginsMessage.submitButton.accesskey = S
crashedpluginsMessage.learnMore = Saper plus…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Voleva tu ir a %S?
keywordURIFixup.goTo = Si, porta me a %S
keywordURIFixup.goTo.accesskey = S
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Actualisar a %S
update.downloadAndInstallButton.accesskey = U
menuOpenAllInTabs.label = Aperir toto in schedas
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Recargar iste pagina
tabHistory.goBack = Revenir a iste pagina
tabHistory.goForward = Avantiar a iste pagina
# URL Bar
pasteAndGo.label = Collar e ir
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Recargar le pagina actual (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Stoppar le cargamento de iste pagina (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Reinitialisar le nivello de zoom (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Commutar le vista de lectura (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S %%, Reinitialisar le nivello de zoom
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Monstrar tu marcapaginas (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Monstrar le progresso de discargamentos in curso (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Aperir un nove fenestra (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Aperir un nove scheda (%S)
newTabContainer.tooltip = Aperir un nove scheda (%S)\nMantene premite pro aperir un nove scheda contentor
newTabAlwaysContainer.tooltip = Selige un contentor pro aperir un nove scheda
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Permitter que %S usa tu datos de imagine de canevas HTML5?
canvas.siteprompt2.warning = Isto pote esser usate pro univocamente identificar tu computator.
canvas.block = Blocar
canvas.block.accesskey = B
canvas.allow2 = Permitter
canvas.allow2.accesskey = A
canvas.remember2 = Memorisar iste decision
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Verificate per: %S
identity.identified.verified_by_you = Tu ha addite un exception de securitate pro iste sito.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Certificato emittite a: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Insecur
identity.notSecure.tooltip = Le connexion non es secur
identity.extension.label = Extension (%S)
identity.extension.tooltip = Cargate per le extension: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Distantiar (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Reinitialisar le nivello de zoom (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Approximar (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Taliar (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Copiar (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Collar (%S)
geolocation.allow = Permitter
geolocation.allow.accesskey = P
geolocation.block = Blocar
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Isto aperira le parametros de systema del position. Per favor concede a %S le accesso al position.
geolocation.shareWithSite4 = Permitter que %S accede a tu position geographic?
geolocation.shareWithFile4 = Permitter que iste file local accede a tu position geographic?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Permitter que %1$S concede a %2$S le permission de acceder a tu position geographic?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Conceder a %S accesso al position in parametros de systema.
geolocation.systemSettingsTitle = Attendente permissiones de geolocalisation
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Le systema te demandara de conceder iste permission a %S.
geolocation.remember = Memorisar iste decision
# Virtual Reality Device UI
xr.allow2 = Permitter
xr.allow2.accesskey = P
xr.block = Blocar
xr.block.accesskey = B
xr.shareWithSite4 = Permitter que %S accede a apparatos de realitate virtual? Isto pote exponer informationes sensibile.
xr.shareWithFile4 = Permitter que iste file local accede a apparatos de realitate virtual? Isto pote exponer informationes sensibile.
xr.remember = Memorisar iste decision
# Persistent storage UI
persistentStorage.allow = Permitter
persistentStorage.allow.accesskey = P
persistentStorage.block.label = Blocar
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Permitter que %S immagazina datos in le immagazinage persistente?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Permitter
webNotifications.allow2.accesskey = P
webNotifications.notNow = Non ora
webNotifications.notNow.accesskey = n
webNotifications.never = Non permitter jammais
webNotifications.never.accesskey = j
webNotifications.alwaysBlock = Blocar sempre
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = Blocar
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Permitter que %S invia notificationes?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S vole acceder a altere applicationes e servicios sur iste apparato.
localhost.remember2 = Rememorar mi election pro iste sito
localhost.allowlabel = Permitter
localhost.blocklabel = Blocar
localhost.allow.accesskey = P
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S vole acceder a applicationes e servicios sur apparatos connexe a tu rete local.
localNetwork.remember2 = Rememorar mi election pro iste sito
localNetwork.allowLabel = Permitter
localNetwork.allow.accesskey = P
localNetwork.blockLabel = Blocar
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Porta me foras de hic!
safebrowsing.getMeOutOfHereButton.accessKey = G
safebrowsing.deceptiveSite = Sito fraudulente!
safebrowsing.notADeceptiveSiteButton.label = Iste sito non es fraudulente…
safebrowsing.notADeceptiveSiteButton.accessKey = D
safebrowsing.reportedAttackSite = Sito denunciate como attaccante!
safebrowsing.notAnAttackButton.label = Isto non es un sito attaccante…
safebrowsing.notAnAttackButton.accessKey = A
safebrowsing.reportedUnwantedSite = Sito denunciate como portator de software indesirabile!
safebrowsing.reportedHarmfulSite = Sito denunciate como nocive!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Cercar in %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Reinitiar %S in modo diagnostic?
troubleshootModeRestartPromptMessage = Tu extensiones, themas e parametros personalisate essera temporarimente disactivate.
troubleshootModeRestartButton = Reinitiar
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Iste pagina relenta %1$S. Pro accelerar tu navigator, arresta iste pagina.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Un pagina web relenta %1$S. Pro accelerar tu navigator, arresta iste pagina.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = “%1$S” relenta %2$S. Pro accelerar tu navigator, arresta iste pagina.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = “%1$S” relenta %2$S. Pro accelerar tu navigator, arresta iste extension.
processHang.add-on.learn-more.text = Saper plus
processHang.button_stop2.label = Stoppar
processHang.button_stop2.accessKey = S
processHang.button_debug.label = Depurar le script
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Monstrar le fenestra in plen schermo (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Mover le barra lateral a sinistra
sidebar.moveToRight = Displaciar le barra lateral a dextra
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Tu debe activar DRM pro reproducer certe elementos audio o video sur iste pagina.
emeNotifications.drmContentDisabled.button.label = Activar DRM
emeNotifications.drmContentDisabled.button.accesskey = A
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S es installante componentes necessari pro leger le audio o video in iste pagina. Per favor retenta plus tarde.
emeNotifications.unknownDRMSoftware = Incognite
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Personalisar %S
decoder.noCodecs.button = Apprende como
decoder.noCodecs.accesskey = A
decoder.noCodecsLinux.message = Pro leger le video, tu debe possibilemente installar le codecs de video necessari.
decoder.noHWAcceleration.message = A fin de meliorar le qualitate del video, pote esser necessari installar le Media Feature Pack de Microsoft.
decoder.noPulseAudio.message = Pro leger le audio, tu debe possibilemente installar le software PulseAudio requirite.
decoder.unsupportedLibavcodec.message = libavcodec pote esser vulnerabile o non es supportate, e debe esser actualisate pro reproducer le video.
decoder.decodeError.message = Un error occurreva durante le decodification de un ressource multimedia.
decoder.decodeError.button = Reportar un problema del sito
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = Un error recovrabile occurreva durante le decodification de un ressource multimedia.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Tu debe aperir session in iste rete ante que tu pote acceder a internet.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Aperir le pagina de apertura de session del rete
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Permissiones pro %S
permissions.remove.tooltip = Vacuar iste permission e demandar novemente
permissions.fullscreen.promptCanceled = Le requestas de permission pendente ha essite cancellate: le requestas de permission non debe esser emittite ante de entrar in modo DOM a plen schermo.
permissions.fullscreen.fullScreenCanceled = Le modo DOM a plen schermo ha terminate: le requestas de permission non debe esser emittite in modo DOM a plen schermo.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64 bits
aboutDialog.architecture.thirtyTwoBit = 32 bits
midi.allow.label = Permitter
midi.allow.accesskey = P
midi.block.label = Blocar
midi.block.accesskey = B
midi.remember = Rememorar iste decision
midi.shareWithFile = Permitter que iste file local accede a tu apparatos MIDI?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Permitter que %S accede tu apparatos MIDI?
midi.shareSysexWithFile = Permitter que iste file local accede tu apparatos MIDI e invia/recipe messages SysEx?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Permitter que %S accede tu apparatos MIDI e invia/recipe messages SysEx?
serial.allow.label = Permitter
serial.allow.accesskey = P
serial.block.label = Blocar
serial.block.accesskey = B
serial.shareWithFile = Permitte tu que iste file local accede a tu portas serial?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Permitte tu que %S accede a tu portas serial?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Retro
storageAccess1.Allow.label = Permitter
storageAccess1.Allow.accesskey = P
storageAccess1.DontAllow.label = Blocar
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Permitter que %1$S usa su cookies sur %2$S?
storageAccess1.hintText = Es un bon idea blocar le accesso si non es clar proque %1$S require iste datos.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Cercar “%S” in le web
