# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Buscando { $host }…
network-connection-status-connected = Conectado a { $host }…
network-connection-status-sending-request = Enviando solicitude a { $host }…
network-connection-status-transferring-data = Transferindo datos de { $host }…
network-connection-status-connecting = Conectando a { $host }…
network-connection-status-read = Lido { $host }
network-connection-status-wrote = Escrito { $host }
network-connection-status-waiting = Esperando por { $host }…
network-connection-status-looked-up = Resolveuse { $host }…
network-connection-status-tls-handshake = Executando un estabelecemento de comunicación TLS con { $host }…
network-connection-status-tls-handshake-finished = O estabelecemento de comunicación TLS rematou para { $host }…
