# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = આ પાનું બીજા સ્થળ પર લઇ જવાયું છે. શું તમે ટાઇપ કરેલી માહિતી તમે નવાં સ્થળ પર ફરી મોકલવા માંગો છો?
# Directory listing strings
DirTitle = %1$S ની અનુક્રમણિકા
DirGoUp = ઉપરના સ્તરની ડિરેક્ટરીમાં જાવ
ShowHidden = છુપા ઓબ્જેક્ટો બતાવો
DirColName = નામ
DirColSize = માપ
DirColMTime = છેલ્લે સુધારેલ
DirFileLabel = ફાઈલ:\u0020
UnsafeUriBlocked = “%1$S” પરનો સ્રોત સલામત બ્રાઉઝિંગ દ્વારા અવરોધિત કરવામાં આવ્યો હતો.
CookieBlockedByPermission = કસ્ટમ કૂકી પરવાનગીને કારણે “%1$S” પર કૂકીઝ અથવા સંગ્રહને ઍક્સેસ કરવા માટે વિનંતી કરવામાં આવી હતી.
CookieBlockedAll = “%1$S” પર કૂકી અથવા સંગ્રહ ઍક્સેસ કરવાની વિનંતી અવરોધિત કરવામાં આવી હતી કારણ કે અમે તમામ સંગ્રહ ઍક્સેસ વિનંતીઓને અવરોધિત કરી રહ્યાં છીએ.
