# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Vista
dialogTitleAddBookmark = Nýtt bókamerki
dialogTitleAddMulti = Ný bókamerki
dialogTitleEdit = Eiginleikar fyrir “%S”
dialogTitleAddNewBookmark2 = Bæta við bókamerki
dialogTitleEditBookmark = Breyta „%S“
dialogTitleEditBookmark2 = Breyta bókamerki
dialogTitleAddBookmarkFolder = Bæta við bókamerkjamöppu
dialogTitleEditBookmarkFolder = Breyta bókamerkjamöppu
bookmarkAllTabsDefault = [Nafn möppu]
newFolderDefault = Ný mappa
newBookmarkDefault = Nýtt bókamerki
