#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.ba

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Kerim Kalamujić</em:contributor> <em:contributor>Muris Herak</em:contributor> <em:contributor>Alma Granov</em:contributor> <em:contributor>Lejla Selimović</em:contributor> <em:contributor>Kenan Dervišević</em:contributor>

#unfilter emptyLines
