# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = I mito geno "%S" pi tic magi?
unnamedCA = Twero me Waraga (pe kimino nying)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Tim ber i ket mung me donyo ma onongo kitiyo kwede me mungo catibiket man:
# Page Info
pageInfo_NoEncryption = Kube Pe Kicono
pageInfo_Privacy_None1 = Kakube %S pe cwako coc me pot buk ma itye kaneno.
pageInfo_Privacy_None2 = Gicwalo Ngec iwi Intanet labongo coc ma romo neno gi jo mapat kun tero.\u0020
pageInfo_Privacy_None4 = Pot buk ma itye kaneno ni pe ki mungo ma onongo pwod pe kicwalo iwi Intanet.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Kube kimungo woko (%1$S, %2$S bit keys, %3$S)
pageInfo_BrokenEncryption = Loko ngec i kod ma otur (%1$S, %2$S bit keys, %3$S)
pageInfo_Privacy_Encrypted1 = Pot buk ma itye kaneno gicono woko mapwod gicwalo iwi Intanet.
pageInfo_Privacy_Encrypted2 = Mungo coc miyo bedo tek pi jo mape ki twero me neno ngec mawoto ikin kompiuta. Ka dong man pe romo twere ni ngat mo okwano pot buk man ma tye kawot arir i kube.
pageInfo_MixedContent = Kicono Kube Maber
pageInfo_MixedContent2 = Dul kom pot buk ma itye kaneno gucono woko mapwod gicwalo iwi intanet.
pageInfo_WeakCipher = Kube ni ki kakube man tiyo ki loko ngec i kod ma goro ki pe tye i mung. Jo mukene twero nno ngec mamegi onyo yiko kit kakube.
# Token Manager
password_not_set = (pe kitero)
