# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Salvesta
dialogTitleAddBookmark = Järjehoidja lisamine
dialogTitleAddMulti = Kõigi kaartide järjehoidjatesse panemine
dialogTitleEdit = Järjehoidja "%S" omadused
dialogTitleAddNewBookmark2 = Järjehoidja lisamine
dialogTitleEditBookmark = Järjehoidja “%S” muutmine
dialogTitleEditBookmark2 = Järjehoidja muutmine
dialogTitleAddBookmarkFolder = Järjehoidjate kausta lisamine
dialogTitleEditBookmarkFolder = Järjehoidjate kausta muutmine
bookmarkAllTabsDefault = [Kausta nimi]
newFolderDefault = Uus kaust
newBookmarkDefault = Uus järjehoidja
