# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = Agor
    .accesskey = A
places-open-tab =
    .label = Agor mewn Tab Newydd
    .accesskey = w
places-open-in-tab =
    .label = Agor mewn Tab Newydd
    .accesskey = A
places-open-all-bookmarks =
    .label = Agor Pob Nod Tudalen
    .accesskey = A
places-open-all-in-tabs =
    .label = Agor pob Tab
    .accesskey = T
places-open-window =
    .label = Agor mewn Ffenestr Newydd
    .accesskey = N
places-open-private-window =
    .label = Agor mewn Ffenestr Breifat Newydd
    .accesskey = F
places-new-bookmark =
    .label = Nod Tudalen Newydd…
    .accesskey = N
places-new-folder-contextmenu =
    .label = Ffolder Newydd…
    .accesskey = F
places-new-folder =
    .label = Ffolder Newydd…
    .accesskey = F
places-new-separator =
    .label = Ymwahanydd Newydd
    .accesskey = Y
places-open-in-window =
    .label = Agor mewn Ffenestr Newydd
    .accesskey = N
places-open-in-private-window =
    .label = Agor mewn Ffenestr Breifat Newydd
    .accesskey = B
places-add-bookmark =
    .label = Ychwanegu Nod Tudalen…
    .accesskey = N
places-add-folder-contextmenu =
    .label = Ychwanegu Ffolder…
    .accesskey = F
places-add-folder =
    .label = Ychwanegu Ffolder…
    .accesskey = o
places-add-separator =
    .label = Ychwanegu Ymwahanydd
    .accesskey = Y
places-view =
    .label = Golwg
    .accesskey = w
places-by-date =
    .label = Yn ôl Dyddiad
    .accesskey = D
places-by-site =
    .label = Yn ôl Gwefan
    .accesskey = G
places-by-most-visited =
    .label = Ymwelwyd Amlaf
    .accesskey = A
places-by-last-visited =
    .label = Ymwelwyd Diwethaf
    .accesskey = D
places-by-day-and-site =
    .label = Yn ôl Dyddiad a Gwefan
    .accesskey = Y
places-history-search =
    .placeholder = Hanes chwilio
places-bookmarks-search =
    .placeholder = Chwilio'r nodau tudalen
places-delete-domain-data =
    .label = Anghofio'r Wefan Hon
    .accesskey = W
places-sortby-name =
    .label = Trefnu yn Ôl Enw
    .accesskey = r
places-properties =
    .label = Priodweddau
    .accesskey = P
# Managed bookmarks are created by an administrator and cannot be changed by the user.
managed-bookmarks =
    .label = Nodau Tudalen wedi'u rheoli
# This label is used when a managed bookmarks folder doesn't have a name.
managed-bookmarks-subfolder =
    .label = Is-ffolder
# This label is used for the "Other Bookmarks" folder that appears in the bookmarks toolbar.
other-bookmarks-folder =
    .label = Nodau Tudalen Eraill
