# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Ruto'onel k'amoj
import-from =
    { PLATFORM() ->
        [windows] Kejik' taq cha'oj, taq yaketal, natab'äl, ewan taq tzij chuqa' juley chik taq rutzij:
       *[other] Kejik' taq cha'oj, taq yaketal, natab'äl, ewan taq tzij chuqa' juley chik taq rutzij:
    }
import-from-bookmarks = Kek'am taq ch'aoj pa:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-nothing =
    .label = Majun tijik' pe
    .accesskey = M
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chrome-beta =
    .label = Chrome Beta
    .accesskey = B
import-from-chrome-dev =
    .label = Chrome Dev
    .accesskey = D
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = x
import-from-360se =
    .label = 360 Ütz chi K'amaya'l
    .accesskey = 3
no-migration-sources = Man tikirel ta xe'ilitäj taq cholkema' ri k'o taq yaketal, natab'äl o taq ruwäch ewan taq tzij.
import-source =
    .label = Kek'am runuk'ulem chuqa' taq tzij
import-items-title =
    .label = Taq ruch'akulal xkek'am
import-items-description = Ke'acha' achike taq ruch'akulal xekek'am:
import-migrating-title =
    .label = Tajin nik'am…
import-migrating-description = Tajin nik'am re taq ruch'akulal re'…
import-select-profile-title =
    .label = Tichax rub'anikil
import-select-profile-description = Tikirel yek'am taq tzij chi kikojol re taq rub'anikil re':
import-done-title =
    .label = Xtz'aqät ruk'amik
import-done-description = Pa rub'eyal xek'am re jujun taq ruch'akulal re':
import-close-source-browser = Tab'ana' utzil, tajikib'a' awi' chi ri okik'amaya'l xacha' k'o chi tz'apäl chuwäch xtachäp chik samaj.
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = Richin { $source }
source-name-ie = Explorer K'amaya'l
source-name-edge = Microsoft Edge
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chrome-beta = Google Chrome Beta
source-name-chrome-dev = Google Chrome Dev
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Ütz chi K'amaya'l
imported-safari-reading-list = Rucholajem taq sik'inem (richin ri Safari)
imported-edge-reading-list = Rucholajem taq sik'inem (richin Edge)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Taq rucha'oj K'amaya'l
    .value = Taq rucha'oj K'amaya'l
browser-data-edge-1 =
    .label = Nuk’ulem
    .value = Nuk’ulem
browser-data-safari-1 =
    .label = Taq cha'oj
    .value = Taq cha'oj
browser-data-chrome-1 =
    .label = Taq cha'oj
    .value = Taq cha'oj
browser-data-canary-1 =
    .label = Taq cha'oj
    .value = Taq cha'oj
browser-data-360se-1 =
    .label = Taq ajowab'äl
    .value = Taq ajowab'äl
browser-data-ie-2 =
    .label = Taq kaxlanwey
    .value = Taq kaxlanwey
browser-data-edge-2 =
    .label = Taq kaxlanwey
    .value = Taq kaxlanwey
browser-data-safari-2 =
    .label = Taq kaxlanwey
    .value = Taq kaxlanwey
browser-data-chrome-2 =
    .label = Taq kaxlanwey
    .value = Taq kaxlanwey
browser-data-canary-2 =
    .label = Taq kaxlanwey
    .value = Taq kaxlanwey
browser-data-firefox-2 =
    .label = Taq kaxlanwey
    .value = Taq kaxlanwey
browser-data-360se-2 =
    .label = Taq kaxlanwey
    .value = Taq kaxlanwey
browser-data-ie-4 =
    .label = Runatab'al okem pa k'amaya'l
    .value = Runatab'al okem pa k'amaya'l
browser-data-edge-4 =
    .label = Runatab'al okem pa k'amaya'l
    .value = Runatab'al okem pa k'amaya'l
browser-data-safari-4 =
    .label = Runatab'al okem pa k'amaya'l
    .value = Runatab'al okem pa k'amaya'l
browser-data-chrome-4 =
    .label = Runatab'al okem pa k'amaya'l
    .value = Runatab'al okem pa k'amaya'l
browser-data-canary-4 =
    .label = Runatab'al okem pa k'amaya'l
    .value = Runatab'al okem pa k'amaya'l
browser-data-firefox-history-and-bookmarks-4 =
    .label = Kinatab'al okem pa k'amaya'l chuqa' taq yaketal
    .value = Kinatab'al okem pa k'amaya'l chuqa' taq yaketal
browser-data-360se-4 =
    .label = Runatab'al okem pa k'amaya'l
    .value = Runatab'al okem pa k'amaya'l
browser-data-ie-8 =
    .label = Kinatab'al taq nojwuj, ri eyakon
    .value = Kinatab'al taq nojwuj, ri eyakon
browser-data-edge-8 =
    .label = Kinatab'al taq nojwuj, ri eyakon
    .value = Kinatab'al taq nojwuj, ri eyakon
browser-data-safari-8 =
    .label = Kinatab'al taq nojwuj, ri eyakon
    .value = Kinatab'al taq nojwuj, ri eyakon
browser-data-chrome-8 =
    .label = Kinatab'al taq nojwuj, ri eyakon
    .value = Kinatab'al taq nojwuj, ri eyakon
browser-data-canary-8 =
    .label = Kinatab'al taq nojwuj, ri eyakon
    .value = Kinatab'al taq nojwuj, ri eyakon
browser-data-firefox-8 =
    .label = Kinatab'al taq nojwuj, ri eyakon
    .value = Kinatab'al taq nojwuj, ri eyakon
browser-data-360se-8 =
    .label = Kinatab'al taq nojwuj, ri eyakon
    .value = Kinatab'al taq nojwuj, ri eyakon
browser-data-ie-16 =
    .label = Yakäl ewan taq tzij
    .value = Yakäl ewan taq tzij
browser-data-edge-16 =
    .label = Yakäl ewan taq tzij
    .value = Yakäl ewan taq tzij
browser-data-safari-16 =
    .label = Yakäl ewan taq tzij
    .value = Yakäl ewan taq tzij
browser-data-chrome-16 =
    .label = Yakäl ewan taq tzij
    .value = Yakäl ewan taq tzij
browser-data-canary-16 =
    .label = Yakäl ewan taq tzij
    .value = Yakäl ewan taq tzij
browser-data-firefox-16 =
    .label = Yakäl ewan taq tzij
    .value = Yakäl ewan taq tzij
browser-data-360se-16 =
    .label = Yakäl ewan taq tzij
    .value = Yakäl ewan taq tzij
browser-data-ie-32 =
    .label = Taq ajowab'äl
    .value = Taq ajowab'äl
browser-data-edge-32 =
    .label = Taq ajowab'äl
    .value = Taq ajowab'äl
browser-data-safari-32 =
    .label = Taq retal
    .value = Taq retal
browser-data-chrome-32 =
    .label = Taq retal
    .value = Taq retal
browser-data-canary-32 =
    .label = Taq retal
    .value = Taq retal
browser-data-360se-32 =
    .label = Yaketal
    .value = Yaketal
browser-data-ie-64 =
    .label = Juley chik taq tzij
    .value = Juley chik taq tzij
browser-data-edge-64 =
    .label = Juley chik taq tzij
    .value = Juley chik taq tzij
browser-data-safari-64 =
    .label = Juley chik taq tzij
    .value = Juley chik taq tzij
browser-data-chrome-64 =
    .label = Juley chik taq tzij
    .value = Juley chik taq tzij
browser-data-canary-64 =
    .label = Juley chik taq tzij
    .value = Juley chik taq tzij
browser-data-firefox-other-64 =
    .label = Juley chik taq tzij
    .value = Juley chik taq tzij
browser-data-360se-64 =
    .label = Juley chik taq tzij
    .value = Juley chik taq tzij
browser-data-firefox-128 =
    .label = Taq ruwäch chuqa' taq ruwi'
    .value = Taq ruwäch chuqa' taq ruwi'
