# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Dae ye want tae trust “%S” fur the follaein purposes?
unnamedCA = Certificate Authority (no nemmed)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Gonnae inpit the passwird that wis yaised tae encrypt this certificate backup:
# Page Info
pageInfo_NoEncryption = Connection No Encryptit
pageInfo_Privacy_None1 = The website %S disnae support encryption fur the page ye're luikin at.
pageInfo_Privacy_None2 = Information sent ower the Internet withoot encryption can be seen by ither fowk while it's on its wey.
pageInfo_Privacy_None4 = The page ye're luikin at wisnae encryptit afore bein transmittit ower the Internet.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Connection Encryptit (%1$S, %2$S bit keys, %3$S)
pageInfo_BrokenEncryption = Braken Encryption (%1$S, %2$S bit keys, %3$S)
pageInfo_Privacy_Encrypted1 = The page ye're luikin at wis encryptit afore bein transmittit ower the Internet.
pageInfo_Privacy_Encrypted2 = Encryption hinders unauthorised fowk fae seein information that's flittin atween computers. Sae chances are that naebody read this page as it flittit across the netwark.
pageInfo_MixedContent = Connection Pairt Encryptit
pageInfo_MixedContent2 = Pairts o the page ye're luikin at wirnae encryptit afore bein transmittit ower the Internet.
pageInfo_WeakCipher = Yer connection tae this wqbsite yaises stintit encryption and isnae private. Ither fowk can see yer information or chynge the wabsite’s behaviour.
pageInfo_CertificateTransparency_Compliant = This wabsite complies wi the Certificate Transparency policy.
# Token Manager
password_not_set = (no set)
