# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = ᱥᱟᱺᱪᱟᱣ ᱢᱮ
dialogTitleAddBookmark = ᱱᱟᱶᱟ ᱯᱩᱛᱷᱤ ᱪᱤᱱᱦᱟᱹ
dialogTitleAddMulti = ᱱᱟᱶᱟ ᱯᱩᱛᱷᱤ ᱪᱤᱱᱦᱟᱹ ᱠᱚ
dialogTitleEdit = “%S” ᱞᱟᱹᱜᱤᱫ ᱜᱩᱱ ᱠᱚ
dialogTitleAddNewBookmark2 = ᱯᱩᱛᱷᱤ ᱪᱤᱱᱦᱟᱹ ᱥᱮᱞᱮᱫᱽ ᱢᱮ
dialogTitleEditBookmark = “%S” ᱥᱟᱯᱲᱟᱣ ᱢᱮ
dialogTitleEditBookmark2 = ᱯᱩᱛᱷᱤᱪᱤᱱᱦᱟᱹ ᱥᱟᱯᱲᱟᱣ ᱢᱮ
dialogTitleAddBookmarkFolder = ᱯᱩᱜᱷᱤᱪᱤᱱᱦᱟᱹ ᱯᱚᱴᱚᱢ ᱥᱮᱞᱮᱫ ᱢᱮ
dialogTitleEditBookmarkFolder = ᱯᱩᱜᱷᱤᱪᱤᱱᱦᱟᱹ ᱯᱚᱴᱚᱢ ᱥᱟᱯᱲᱟᱣ ᱢᱮ
bookmarkAllTabsDefault = [ᱯᱚᱴᱚᱢ ᱧᱩᱛᱩᱢ]
newFolderDefault = ᱱᱚᱶᱟ ᱯᱚᱴᱚᱢ
newBookmarkDefault = ᱱᱟᱶᱟ ᱯᱩᱛᱷᱤ ᱪᱤᱱᱦᱟᱹ
