# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

ssl-error-no-certificate = Tidak dapat mencari sijil tertentu atau kunci keperluan untuk pengesahihan.
ssl-error-unsupported-certificate-type = Jenis sijil tidak disokong.
ssl-error-bad-mac-read = SSL menerima satu rekod dengan Message Authentication Code yang tidak betul.
ssl-error-ssl-disabled = Tidak boleh disambung: SSL dinyahdayakan.
ssl-error-unknown-cipher-suite = Satu cip SSL yang tidak diketahui telah diminta.
ssl-error-bad-block-padding = SSL menerima rakaman dengan rekod yang tidak berkualiti.
ssl-error-tx-record-too-long = rekod SSL yang cuba dihantar melebihi panjang yang dibenarkan.
ssl-error-rx-malformed-change-cipher = SSL menerima satu rekod tukar bentuk Change Cipher Spec.
ssl-error-rx-malformed-alert = SSL menerima kecacatan rekod amaran.
ssl-error-rx-unexpected-application-data = SSL menerima rekod Data Aplikasi yang tidak dijangka.
ssl-error-rx-unknown-record-type = SSL menerima satu rekod dengan jenis kandungan yang tidak diketahui.
ssl-error-rx-unknown-handshake = SSL menerima mesej getaran dengan jenis mesej yang tidak diketahui.
ssl-error-rx-unknown-alert = SSL menerima rakaman peringatan dengan peringatan yang tidak diketahui.
ssl-error-generate-random-failure = SSL mengalami kegagalan menjanakan nombor secara rawak.
ssl-error-sign-hashes-failure = tidak mampu menanda data secara digital untuk mengesahkan sijil.
ssl-error-decryption-failure = Algoritma penyahsulitan data pukal gagal di ruang penyahsulitan terpilih.
ssl-error-md5-digest-failure = Fungsi diges MD5 gagal.
ssl-error-sym-key-context-failure = Gagal untuk mencipta konteks Kekunci Simmetrik.
ssl-error-iv-param-failure = Kod PKCS11 gagal untuk menterjemah IV kepada param.
ssl-error-init-cipher-suite-failure = gagal untuk memastikan pemilihan chiper suite.
ssl-error-no-server-key-for-alg = Pelayan tidak mempunyai kekunci untuk melakukan pertukaran kekunci algoritma tersebut.
ssl-error-cert-kea-mismatch = Sijil yang diberi tidak boleh digunakan bersama algoritma pertukaran kekunci yang dipilih.
ssl-error-no-trusted-ssl-client-ca = Tiada penguasa sijil yang dipercayai untuk pengesahan pengguna SSL.
ssl-error-renegotiation-not-allowed = Perundingan adalah dilarang bagi soket SSL.
ssl-error-rx-unexpected-uncompressed-record = SSL telah menerima rekod yang tidak dijangka dan tidak tersusun.
ssl-error-feature-not-supported-for-ssl2 = Ciri-ciri SSL tidak disokong untuk sambungan SSL 2.0.
ssl-error-feature-not-supported-for-servers = Ciri-ciri SSL tidak diterima oleh pelayan.
ssl-error-feature-not-supported-for-clients = Ciri-ciri SSL tidak diterima oleh klien.
sec-error-io = Kesalahan I/O berlaku semasa pengesahan keselamatan.
sec-error-library-failure = Kegagalan Sekuriti Perpustakaan.
sec-error-bad-data = Sekuriti Perpustakaan: menerima data yang buruk.
sec-error-invalid-args = perpustakaan keselamatan : arahan tidak sah
sec-error-invalid-algorithm = Perpustakaan Keselamatan : Algoritma tidak sah
sec-error-invalid-ava = Sekuriti Perpustakaan: AVA yang tidak sah.
sec-error-invalid-time = Format waktu tidak sah.
sec-error-bad-password = Kata laluan keselamatan yang dimasukkan adalah salah.
sec-error-no-nodelock = pustaka sekuriti: tiada kuncinod.
sec-error-bad-database = putaka sekuriti: pengkalan data yang tidak elok.
sec-error-no-memory = pustaka sekuriti: peruntukan memori gagal.
sec-error-duplicate-cert = Sijil telahpun wujud di dalam pangkalan data anda.
sec-error-adding-cert = Ralat menambah sijil ke pangkalan data.
sec-error-filing-key = Ralat isi semula kunci bagi sijil ini.
sec-error-no-key = Kunci peribadi untuk sijil ini tidak dapat ditemui di dalam pengkalan data kunci
sec-error-cert-valid = Sijil ini adalah sah.
sec-error-cert-not-valid = Sijil ini adalah tidak sah.
sec-error-cert-no-response = Sijil Perpustakaan : tiada maklum balas
sec-error-crl-invalid = CRL baru mempunyai format yang tidak sah.
sec-error-ca-cert-invalid = Pengeluar sijil adalah tidak sah.
sec-error-path-len-constraint-invalid = Kekangan sebahagian sijil adalah tidak sah.
sec-error-cert-usages-invalid = Ruang penggunaan sijil tidak sah.
sec-internal-only = **Modul dalaman SAHAJA**
sec-error-old-crl = CRL yang baru adalah bukan baru banding dengan yang terkini.
sec-error-pkcs7-bad-signature = Tandatangan penentusahan telah gagal: tidak ada penandatangan , didapati terlalu banyak penandatangan, atau tidak sempurna atau data tercemar.
sec-error-unsupported-keyalg = Kekunci algoritma tidak disokong atau tidak diketahui.
xp-sec-fortezza-none-selected = Tiada kad Fortezza dipilih
xp-sec-fortezza-more-info = Sila pilih satu personaliti untuk mendapatkan maklumat yang lebih lanjut
xp-sec-fortezza-no-more-info = Tiada maklumat lanjut tentang personaliti ini
xp-sec-fortezza-bad-pin = Pin Tidak Sah
sec-error-krl-invalid = KRL baru mempunyai format yang tidak sah.
sec-error-need-random = Perpustakaan Keselamatan : memerlukan data secara rawak
sec-error-no-module = Perpustakaan Keselamatan : Tiada Modul Keselamatan mempunyai operasi permintaan
sec-error-read-only = Perpustakaan keselamtan: hanya membaca database.
sec-error-no-slot-selected = Tiada slot atau token telah dipilih.
sec-error-cert-nickname-collision = Suatu sijil dengan nama panggilan yang sama telahpun wujud.
sec-error-key-nickname-collision = Suatu kunci dengan nama panggilan yang sama telahpun wujud.
sec-error-safe-not-created = ralat apabila mencipta objek simpanan
sec-error-baggage-not-created = ralat semasa mencipta objek bagasi.
sec-error-bad-export-algorithm = Algoritma yang dikehendaki adalah tidak dibenarkan.
sec-error-exporting-certificates = Ralat ketika cuba untuk mengeksport sijil-sijil.
sec-error-importing-certificates = Ralat ketika cuba mengimport sijil-sijil.
sec-error-user-cancelled = Pengguna klik butang batal.
sec-error-pkcs12-duplicate-data = Tidak diimport kerana telah wujud dalam pangkalan data.
sec-error-message-send-aborted = Mesej tidak dihantar.
sec-error-inadequate-key-usage = Kunci pensijilan tidak mencukupi untuk percubaan operasi.
sec-error-inadequate-cert-type = Jenis sijil tidak diluluskan bagi aplikasi.
sec-error-keygen-fail = Tidak dapat menjana pasangan kekunci awam/swasta.
sec-error-bad-nickname = nama timangan dalam sijil sudah digunakan.
sec-error-cannot-move-sensitive-key = Satu kunci sensitif tidak boleh dialih pada slot yang diperlukan.
sec-error-js-invalid-module-name = Nama modul tidak sah.
sec-error-js-invalid-dll = Modul haluan/nama fail tidak sah
sec-error-js-add-mod-failure = Tidak dapat menambah modul
sec-error-old-krl = KRL yang baru adalah tidak lama banding dengan yang terkini.
sec-error-cert-not-in-name-space = Lembaga Persijilan untuk sijil ini tidak membenarkan sijil dengan nama yang sama dibekalkan.
sec-error-krl-not-yet-valid = Senarai pembatalan bagi sijil ini belum lagi disahkan.
sec-error-ocsp-server-error = Pelayar OCSP mengalami satu ralat pendalaman.
sec-error-ocsp-unknown-cert = Tiada status pada pelayan OCSP untuk sijil tersebut.
sec-error-ocsp-malformed-response = Balas dari pelayar OCSP telah cemar atau pembentukan yang tidak wajar.
sec-error-ocsp-old-response = OCSP mengandungi informasi yang lama.
sec-error-bad-template = Tidak dapat mengekod data ASN.1. Templat tertentu tidak sah.
sec-error-busy = NSS tidak boleh ditutup. Objek masih lagi sedang digunakan.
sec-error-unsupported-elliptic-curve = Lengkung eliptik tidak disokong.
sec-error-unsupported-ec-point-form = Bentuk titik lengkung eliptik tidak disokong.
sec-error-unrecognized-oid = Objek yang tidak dikenalpasti.
sec-error-unknown-object-type = Jenis objek dinyatakan tidak dapat dikenal pasti.
sec-error-incompatible-pkcs11 = Pemacu PKCS #11 melanggar spesifikasi dalam cara yang tidak sesuai.
sec-error-crl-already-exists = CRL telah wujud.
sec-error-not-initialized = NSS adalah tidak dapat dimulakan.
sec-error-token-not-logged-in = Operasi gagal kerana token PKCS#11 tidak menglog masuk.
sec-error-out-of-search-limits = Pencarian pengesahsahihan cert adalah melebihi had gelintaran
sec-error-invalid-policy-mapping = Pemetaan polici mempunyai mana-mana polici
sec-error-policy-validation-failed = Rantai Cert telah menggagalkan had polici
sec-error-bad-http-response = Pelayar menerima maklum balas HTTP yang buruk
sec-error-bad-ldap-response = Pelayar menerima maklum balas LDAP yang teruk
sec-error-failed-to-encode-data = Gagal untuk mengekod data dengan pengekod ASN1
sec-error-libpkix-internal = Ralat pendalaman Libpkix berlaku semasa pengesahsahihan cert.
sec-error-pkcs11-general-error = Satu  PKCS #11 modul mengembalikan CKR_GENERAL_ERROR, menunjukkan sebuah ralat yang tidak dapat dipulihkan telah berlaku.
sec-error-pkcs11-device-error = Satu  PKCS #11 modul mengembalikan CKR_DEVICE_ERROR, menunjukkan satu masalah telah berlaku dengan token atau slot.
sec-error-crl-import-failed = Ralat ketika cuba mengimport satu CRL.
sec-error-expired-password = Kata laluan tamat tempoh.
sec-error-locked-password = Kata laluan dikunci.
sec-error-unknown-pkcs11-error = Kesilapan PKCS #11 tidak dikenali.
sec-error-bad-crl-dp-url = URL sah atau tidak disokong nama pusat dalam pembahagian CRL.
sec-error-cert-signature-algorithm-disabled = Sijil ditandatangan menggunakan algoritma yang dilumpuhkan kerana tidak selamat.
