# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

appmenu-update-available2 =
    .buttonlabel = Baixa
    .buttonaccesskey = B
    .label = Hi ha una actualització
    .secondarybuttonlabel = Descarta
    .secondarybuttonaccesskey = D
appmenu-update-available-message2 = Baixeu la darrera versió del { -brand-shorter-name }.
appmenu-update-manual2 =
    .buttonlabel = Baixa
    .buttonaccesskey = B
    .label = Hi ha una actualització
    .secondarybuttonlabel = Descarta
    .secondarybuttonaccesskey = D
appmenu-update-manual-message2 = El { -brand-shorter-name } no s'ha pogut actualitzar automàticament. Baixeu la versió nova; no perdreu la informació guardada ni les personalitzacions.
appmenu-update-unsupported2 =
    .buttonlabel = Més informació
    .buttonaccesskey = M
    .label = No es pot actualitzar
    .secondarybuttonlabel = Descarta
    .secondarybuttonaccesskey = D
appmenu-update-unsupported-message2 = El vostre sistema operatiu és incompatible amb la versió més recent del { -brand-shorter-name }.
appmenu-update-restart2 =
    .buttonlabel = Actualitza i reinicia
    .buttonaccesskey = A
    .label = Hi ha una actualització
    .secondarybuttonlabel = Descarta
    .secondarybuttonaccesskey = D
appmenu-update-restart-message2 = Obteniu la versió més recent del { -brand-shorter-name }. Les pestanyes i finestres obertes es restauraran.
appmenu-update-other-instance =
    .buttonlabel = Actualitza el { -brand-shorter-name } de totes maneres.
    .buttonaccesskey = u
    .label = El { -brand-shorter-name } no s'ha pogut actualitzar a la versió més recent.
    .secondarybuttonlabel = Ara no
    .secondarybuttonaccesskey = n
appmenu-update-other-instance-message = Hi ha disponible una actualització del { -brand-shorter-name }, però no es pot instal·lar perquè hi ha una altra còpia del { -brand-shorter-name } en execució. Tanqueu-la per a continuar l'actualització, o trieu actualitzar-la igualment (és possible que l'altra còpia no funcione correctament fins que no la reinicieu).
appmenu-addon-post-install-message3 = Gestioneu els vostres complements i temes mitjançant el menú de l'aplicació.
appmenu-new-tab-controlled-changes =
    .buttonlabel = Mantén els canvis
    .buttonaccesskey = M
    .label = La pàgina de «Pestanya nova» ha canviat.
    .secondarybuttonlabel = Gestiona les pestanyes noves
    .secondarybuttonaccesskey = G
appmenu-homepage-controlled-changes =
    .buttonlabel = Mantén els canvis
    .buttonaccesskey = M
    .label = La pàgina d'inici ha canviat.
    .secondarybuttonlabel = Gestiona la pàgina d'inici
    .secondarybuttonaccesskey = G
appmenu-tab-hide-controlled =
    .buttonlabel = Mantén les pestanyes amagades
    .buttonaccesskey = M
    .label = Accedeix a les pestanyes ocultes
    .secondarybuttonlabel = Inhabilita l'extensió
    .secondarybuttonaccesskey = I
