# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Auxiliar d'importació
import-from =
    { PLATFORM() ->
        [windows] Importa les opcions, adreces d'interés, historial, contrasenyes i altres dades des de:
       *[other] Importa les preferències, adreces d'interés, historial, contrasenyes i altres dades des de:
    }
import-from-bookmarks = Importa les adreces d'interés del:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-edge-legacy =
    .label = Microsoft Edge antic
    .accesskey = M
import-from-edge-beta =
    .label = Microsoft Edge Beta
    .accesskey = d
import-from-nothing =
    .label = No importis res
    .accesskey = r
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chrome-beta =
    .label = Chrome Beta
    .accesskey = B
import-from-chrome-dev =
    .label = Chrome Dev
    .accesskey = D
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = x
import-from-360se =
    .label = 360 Secure Browser
    .accesskey = 3
no-migration-sources = No s'ha trobat cap programa que continga adreces d'interés, o dades d'historial o contrasenyes.
import-source =
    .label = Importació dels paràmetres i de les dades
import-items-title =
    .label = Elements per importar
import-items-description = Seleccioneu quins elements voleu importar:
import-migrating-title =
    .label = S'està important…
import-migrating-description = Els elements següents s'estan important en estos moments…
import-select-profile-title =
    .label = Selecció de perfil
import-select-profile-description = Els perfils següents estan disponibles per importar-se des de:
import-done-title =
    .label = Fi de la importació
import-done-description = Els elements següents s'han importat correctament:
import-close-source-browser = Abans de continuar, assegureu-vos que el navegador seleccionat estiga tancat.
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = De { $source }
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-edge-beta = Microsoft Edge Beta
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chrome-beta = Google Chrome Beta
source-name-chrome-dev = Google Chrome Dev
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Secure Browser
imported-safari-reading-list = Llista de lectura (del Safari)
imported-edge-reading-list = Llista de lectura (de l'Edge)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Opcions d'Internet
    .value = Opcions d'Internet
browser-data-edge-1 =
    .label = Paràmetres
    .value = Paràmetres
browser-data-safari-1 =
    .label = Preferències
    .value = Preferències
browser-data-chrome-1 =
    .label = Preferències
    .value = Preferències
browser-data-canary-1 =
    .label = Preferències
    .value = Preferències
browser-data-360se-1 =
    .label = Preferències
    .value = Preferències
browser-data-ie-2 =
    .label = Galetes
    .value = Galetes
browser-data-edge-2 =
    .label = Galetes
    .value = Galetes
browser-data-safari-2 =
    .label = Galetes
    .value = Galetes
browser-data-chrome-2 =
    .label = Galetes
    .value = Galetes
browser-data-canary-2 =
    .label = Galetes
    .value = Galetes
browser-data-firefox-2 =
    .label = Galetes
    .value = Galetes
browser-data-360se-2 =
    .label = Galetes
    .value = Galetes
browser-data-ie-4 =
    .label = Historial de navegació
    .value = Historial de navegació
browser-data-edge-4 =
    .label = Historial de navegació
    .value = Historial de navegació
browser-data-safari-4 =
    .label = Historial de navegació
    .value = Historial de navegació
browser-data-chrome-4 =
    .label = Historial de navegació
    .value = Historial de navegació
browser-data-canary-4 =
    .label = Historial de navegació
    .value = Historial de navegació
browser-data-firefox-history-and-bookmarks-4 =
    .label = Historial de navegació i adreces d'interés
    .value = Historial de navegació i adreces d'interés
browser-data-360se-4 =
    .label = Historial de navegació
    .value = Historial de navegació
browser-data-ie-8 =
    .label = Historial de formularis guardats
    .value = Historial de formularis guardats
browser-data-edge-8 =
    .label = Historial de formularis guardats
    .value = Historial de formularis guardats
browser-data-safari-8 =
    .label = Historial de formularis guardats
    .value = Historial de formularis guardats
browser-data-chrome-8 =
    .label = Historial de formularis guardats
    .value = Historial de formularis guardats
browser-data-canary-8 =
    .label = Historial de formularis guardats
    .value = Historial de formularis guardats
browser-data-firefox-8 =
    .label = Historial de formularis guardats
    .value = Historial de formularis guardats
browser-data-360se-8 =
    .label = Historial de formularis guardats
    .value = Historial de formularis guardats
browser-data-ie-16 =
    .label = Contrasenyes guardades
    .value = Contrasenyes guardades
browser-data-edge-16 =
    .label = Contrasenyes guardades
    .value = Contrasenyes guardades
browser-data-safari-16 =
    .label = Contrasenyes guardades
    .value = Contrasenyes guardades
browser-data-chrome-16 =
    .label = Contrasenyes guardades
    .value = Contrasenyes guardades
browser-data-canary-16 =
    .label = Contrasenyes guardades
    .value = Contrasenyes guardades
browser-data-firefox-16 =
    .label = Contrasenyes guardades
    .value = Contrasenyes guardades
browser-data-360se-16 =
    .label = Contrasenyes guardades
    .value = Contrasenyes guardades
browser-data-ie-32 =
    .label = Preferits
    .value = Preferits
browser-data-edge-32 =
    .label = Preferits
    .value = Preferits
browser-data-safari-32 =
    .label = Adreces d'interés
    .value = Adreces d'interés
browser-data-chrome-32 =
    .label = Adreces d'interés
    .value = Adreces d'interés
browser-data-canary-32 =
    .label = Adreces d'interés
    .value = Adreces d'interés
browser-data-360se-32 =
    .label = Adreces d'interés
    .value = Adreces d'interés
browser-data-ie-64 =
    .label = Altres dades
    .value = Altres dades
browser-data-edge-64 =
    .label = Altres dades
    .value = Altres dades
browser-data-safari-64 =
    .label = Altres dades
    .value = Altres dades
browser-data-chrome-64 =
    .label = Altres dades
    .value = Altres dades
browser-data-canary-64 =
    .label = Altres dades
    .value = Altres dades
browser-data-firefox-other-64 =
    .label = Altres dades
    .value = Altres dades
browser-data-360se-64 =
    .label = Altres dades
    .value = Altres dades
browser-data-firefox-128 =
    .label = Finestres i pestanyes
    .value = Finestres i pestanyes
