# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

appmenu-update-available2 =
    .buttonlabel = Atsiųsti
    .buttonaccesskey = A
    .label = Išleistas naujinimas
    .secondarybuttonlabel = Paslėpti
    .secondarybuttonaccesskey = s
appmenu-update-available-message2 = Gaukite naujausią „{ -brand-shorter-name }“ versiją.
appmenu-update-manual2 =
    .buttonlabel = Atsiųsti
    .buttonaccesskey = A
    .label = Išleistas naujinimas
    .secondarybuttonlabel = Paslėpti
    .secondarybuttonaccesskey = s
appmenu-update-manual-message2 = Automatinis „{ -brand-shorter-name }“ naujinimas nepavyko. Atsisiųskite naują versiją – neprarasite įrašytų duomenų ar pakeitimų.
appmenu-update-unsupported2 =
    .buttonlabel = Sužinoti daugiau
    .buttonaccesskey = d
    .label = Naujinimas nepavyko
    .secondarybuttonlabel = Paslėpti
    .secondarybuttonaccesskey = s
appmenu-update-unsupported-message2 = Jūsų operacinė sistema nesuderinama su naujausia „{ -brand-shorter-name }“ versija.
appmenu-update-restart2 =
    .buttonlabel = Atnaujinti ir paleisti iš naujo
    .buttonaccesskey = A
    .label = Išleistas naujinimas
    .secondarybuttonlabel = Paslėpti
    .secondarybuttonaccesskey = s
appmenu-update-restart-message2 = Gaukite naujausią „{ -brand-shorter-name }“ versiją. Atvertos kortelės ir langai bus įkelti iš naujo.
appmenu-update-other-instance =
    .buttonlabel = Vis tiek naujinti „{ -brand-shorter-name }“
    .buttonaccesskey = V
    .label = Automatinis „{ -brand-shorter-name }“ naujinimas nepavyko.
    .secondarybuttonlabel = Ne dabar
    .secondarybuttonaccesskey = N
appmenu-update-other-instance-message = Yra išleistas „{ -brand-shorter-name }“ naujinimas, tačiau jo negalima įdiegti dėl šiuo metu veikiančios kitos „{ -brand-shorter-name }“ kopijos. Užverkite ją, norėdami tęsti naujinimą, arba pasirinkite „Vis tiek naujinti“ (kita kopija gali veikti netinkamai, kol nepaleisite iš naujo).
appmenu-addon-post-install-message3 = Tvarkykite savo priedus ir grafinius apvalkalus per programos meniu.
appmenu-new-tab-controlled-changes =
    .buttonlabel = Palikti pakeitimus
    .buttonaccesskey = P
    .label = Pasikeitė jūsų nauja kortelė.
    .secondarybuttonlabel = Tvarkyti naujas korteles
    .secondarybuttonaccesskey = T
appmenu-homepage-controlled-changes =
    .buttonlabel = Palikti pakeitimus
    .buttonaccesskey = P
    .label = Pasikeitė jūsų pradžios tinklalapis.
    .secondarybuttonlabel = Tvarkyti pradžios tinklalapį
    .secondarybuttonaccesskey = T
appmenu-tab-hide-controlled =
    .buttonlabel = Korteles laikyti paslėptas
    .buttonaccesskey = K
    .label = Pasiekite paslėptas korteles
    .secondarybuttonlabel = Išjungti priedą
    .secondarybuttonaccesskey = g
