# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SaveImageTitle = Enregistrar l'imatge
SaveMediaTitle = Enregistrar lo mèdia
SaveVideoTitle = Enregistrar la vidèo
SaveAudioTitle = Enregistrar lo fichièr àudio
SaveLinkTitle = Enregistrar jos
WebPageCompleteFilter = Pagina web, complèta
WebPageHTMLOnlyFilter = Pagina web, HTML unicament
WebPageXHTMLOnlyFilter = Pagina web, XHTML unicament
WebPageSVGOnlyFilter = Pagina web, SVGsonque
WebPageXMLOnlyFilter = Pagina web, SVG unicament
# LOCALIZATION NOTE (UntitledSaveFileName):
#    This is the default filename used when saving a file if a filename could
#    not be determined or if a filename was invalid. A period and file
#    extension may be appended to this string.
UntitledSaveFileName = Sens títol
