# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language-name-aa = ئەفەر
language-name-ab = ئەبخازی
language-name-ae = ئاڤێستایی
language-name-af = ئەفریقی
language-name-ak = ئاکان
language-name-am = ئەمهەری
language-name-an = ئاراگۆنی
language-name-ar = عەرەبی
language-name-as = ئاسامی
language-name-ast = ئاستۆری
language-name-av = ئەڤاری
language-name-ay = ئایمارا
language-name-az = ئازەربایجانی
language-name-ba = باشکیەر
language-name-be = بیلاڕووسی
language-name-bg = بولگاریای
language-name-bh = بیهاری
language-name-bi = بیسلامی
language-name-bm = بامبارا
language-name-bn = بنگالی
language-name-bo = تبتی
language-name-br = بریتۆنی
language-name-bs = بۆسنی
language-name-ca = کەتەلۆنی
language-name-ce = چیچانی
language-name-ch = چامۆرۆ
language-name-co = کۆرسیکی
language-name-cr = کری
language-name-cs = چیکی
language-name-csb = کاشوبی
language-name-cu = سلاڤی کەنیسەیی
language-name-cv = چووڤاشی
language-name-cy = وێڵزی
language-name-da = دانیمارکی
language-name-de = ئەڵمانی
language-name-dsb = سڕبی خواروو
language-name-dv = دیڤێهی
language-name-dz = دزۆنخی
language-name-ee = ئێوی
language-name-el = یۆنانی
language-name-en = ئینگلیزی
language-name-eo = ئێسپیرانتۆ
language-name-es = ئیسپانی
language-name-et = ئەستۆنی
language-name-eu = باسکی
language-name-fa = فارسی
language-name-ff = فوولایی
language-name-fi = فنلەندی
language-name-fj = فیجی
language-name-fo = فەرۆیی
language-name-fr = فەڕەنسی
language-name-fur = فریئوولی
language-name-fy = فریزی
language-name-ga = ئیرلەندی
language-name-gd = گەلیکی سکۆتلەندی
language-name-gl = گالیسی
language-name-gn = گووارانی
language-name-gu = گوجاراتی
language-name-gv = مانکی
language-name-ha = هاوسایی
language-name-haw = هاوایی
language-name-he = عبری
language-name-hi = هندی
language-name-hil = هیلیگاینۆنی
language-name-ho = هیری مۆتو
language-name-hr = کرواتی
language-name-hsb = سڕبی سەروو
language-name-ht = هایتی
language-name-hu = هەنگاری
language-name-hy = ئەرمەنی
language-name-hz = هێرێرۆی
language-name-ia = ئینترلینگووا
