# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Notice: If you're updating this list, you should also
###         update the list in mozIntl.js.

region-name-ad = ئەندۆرا
region-name-ae = ئیماڕاتی یەکگرتوو
region-name-af = ئەفغانستان
region-name-ag = ئەنتیگوا و باربودە
region-name-ai = ئونگیلا
region-name-al = ئەلبانیا
region-name-am = ئەرمینیا
region-name-ao = ئەنگۆلا
region-name-aq = ئەنتارتیکا
region-name-ar = ئەرجەنتین
region-name-as = ساموای ئەمریکی
region-name-at = نەمسا
region-name-au = ئوسترالیا
region-name-aw = ئاروبا
region-name-az = ئازەربایجان
region-name-ba = بۆسنەو هەرسک
region-name-bb = باربادۆس
region-name-bd = بەنگلادیش
region-name-be = بەلجیکا
region-name-bf = بۆرکینا فاسۆ
region-name-bg = بولگاریا
region-name-bh = بەحرەین
region-name-bi = بوروندی
region-name-bj = بێنین
region-name-bl = سانت بارسێلێمی
region-name-bm = بەرمۆدا
region-name-bn = برۆنای
region-name-bo = بۆلیڤیا
region-name-bq = بۆناری، سانت ئوستاتوس و سابا
region-name-br = بەڕازیل
region-name-bs = باهاماس،
region-name-bt = بۆتان
region-name-bv = دورگەی  بۆڤێت
region-name-bw = بۆتسوانا
region-name-by = بیلاڕووس
region-name-bz = بێلیز
region-name-ca = کەنەدا
region-name-cc = دورگەی  کۆکۆس
region-name-cd = کۆنگۆ (کینشاسا)
region-name-cf = کۆماری ئەفریقای ناوەڕاست
region-name-cg = کۆنگۆ (برازاڤیل)
region-name-ch = سویسرا
region-name-ci = کۆت دیڤوار
region-name-ck = دورگەی  کوک
region-name-cl = چیلی
region-name-cm = کامیرۆن
region-name-cn = چین
region-name-co = کۆڵۆمبیا
region-name-cp = دورگەی  کلیپەرتۆن
region-name-cr = کۆستاریکا
region-name-cu = کوبا
region-name-cv = کاپۆ ڤێردی
region-name-cw = کوراچاو
region-name-cx = دورگەی کریسمس
region-name-cy = قوبرس
region-name-cz = کۆماری چیک
region-name-de = ئەڵمانیا
region-name-dg = دیگۆ گارسیا
region-name-dj = جیبۆتی
region-name-dk = دانیمارک
region-name-dm = دۆمەنیک
region-name-do = کۆماری دۆمەنیک
region-name-dz = جەزائیر
region-name-ec = ئێکوادۆر
region-name-ee = ئەستۆنیا
region-name-eg = مسر
region-name-eh = سەحارەی ڕۆژئاوا
region-name-er = ئەریتریا
region-name-es = ئیسپانیا
region-name-et = ئەسیوپیا
region-name-fi = فینلەندا
region-name-fj = فیجی
region-name-fk = دوورگەکانی فاڵکلاند (ئیسلاس مالڤیناس)
region-name-fm = میکرۆنیسیا، بەشێکە لە هەرێمە یەکگرتووەکانی
region-name-fo = دورگەی فارۆ
region-name-fr = فەڕەنسا
region-name-ga = گابۆن
region-name-gb = شانشینی یەکگرتووی بەریتانیا
region-name-gd = گرینادا
region-name-ge = جۆرجیا
region-name-gf = غینیای فەڕەنسی
region-name-gg = گۆرێنسی
region-name-gh = غانا
region-name-gi = گیبراڵتار
region-name-gl = گرینلاند
region-name-gm = غامبيا،
region-name-gn = گینیا
region-name-gp = گوادەلۆپی
region-name-gq = گینیای جەمسەری
region-name-gr = یۆنان
region-name-gs = جۆرجیای باشور و دورگەی باشوری ساندویچ
region-name-gt = گواتیمالا
region-name-gu = گوام
region-name-gw = گینیا-بیساو
region-name-gy = گویانا
region-name-hk = هۆنگ کۆنگ
region-name-hm = دورگەی هارد و دورگەی McDonald
region-name-hn = هندوراس
region-name-hr = کرواتیا
region-name-ht = هایتی
region-name-hu = هەنگاریا
region-name-id = ئیندۆنیزیا
region-name-ie = ئیرلەندا
region-name-il = ئیسرائیل
region-name-im = ئایسڵ ئۆف مان
region-name-in = هندستان
region-name-io = ناوچەی زەریای بەریتابی هندی
region-name-iq = عێراق
region-name-ir = ئێران
region-name-is = ئایسلەندا
region-name-it = ئیتاڵیا
region-name-je = جێرسی
region-name-jm = جامایکا
region-name-jo = ئوردن
region-name-jp = یابان
region-name-ke = کینیا
region-name-kg = قیرغستان
region-name-kh = کەمبۆدیا
region-name-ki = کیریباتی
region-name-km = کۆمۆرۆس
region-name-kn = سانت کیتس و نێڤس
region-name-kp = کۆریا، باکوور
region-name-kr = کۆریا، باشوور
region-name-kw = کوەیت
region-name-ky = دوورگەکانی لایمان
region-name-kz = کازاغستان
region-name-la = لاوس
region-name-lb = لوبنان
region-name-lc = سانت لوسیا
region-name-li = لیشنشتاین
region-name-lk = سریلانکا
region-name-lr = لیبریا
region-name-ls = لیسۆتۆ
region-name-lt = لیتوانیا
region-name-lu = لۆکسەمبۆرگ
region-name-lv = لاتیڤیا
region-name-ly = لیبیا
region-name-ma = مەغریب
region-name-mc = مۆناکۆ
region-name-md = مۆڵدۆڤا
region-name-me = مۆنتینیگرۆ
region-name-mf = سانت مارتن
region-name-mg = مەدەگەسکەر
region-name-mh = دوورگەکانی مارشال
region-name-mk = مەقدۆنیا
region-name-ml = مالی
region-name-mm = بۆرما
region-name-mn = مەنگۆلیا
region-name-mo = ماکاو
region-name-mp = دوورگەکانی ماریانای باکوور
region-name-mq = مارتینک
region-name-mr = مۆریتانیا
region-name-ms = مۆنتسێرات
region-name-mt = ماڵتا
region-name-mu = ماوریتیۆس
region-name-mv = ماڵدیڤ
region-name-mw = مالاوی
region-name-mx = مەکسیک
region-name-my = مالیزیا
region-name-mz = مۆزەمبیق
region-name-na = نامیبیا
region-name-nc = کالیدۆنیای نوێ
region-name-ne = نەیجەر
region-name-nf = دوورگەکانی نۆرفۆڵک
region-name-ng = نێجیریا
region-name-ni = نیگاراگوا
region-name-nl = هۆڵەندا
region-name-no = نەرویج
region-name-np = نیپاڵ
region-name-nr = ناورو
region-name-nu = نیو
region-name-nz = نیوزلەندا
region-name-om = عومان
region-name-pa = پەنەما
region-name-pe = پیرۆ
