# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Notice: If you're updating this list, you should also
###         update the list in mozIntl.js.

region-name-ad = ئەندۆرا
region-name-ae = ئیماڕاتی یەکگرتوو
region-name-af = ئەفغانستان
region-name-ag = ئەنتیگوا و باربودە
region-name-ai = ئونگیلا
region-name-al = ئەلبانیا
region-name-am = ئەرمینیا
region-name-ao = ئەنگۆلا
region-name-aq = ئەنتارتیکا
region-name-ar = ئەرجەنتین
region-name-as = ساموای ئەمریکی
region-name-at = نەمسا
region-name-au = ئوسترالیا
region-name-aw = ئاروبا
region-name-az = ئازەربایجان
region-name-ba = بۆسنەو هەرسک
region-name-bb = باربادۆس
region-name-bd = بەنگلادیش
region-name-be = بەلجیکا
region-name-bf = بۆرکینا فاسۆ
region-name-bg = بولگاریا
region-name-bh = بەحرەین
region-name-bi = بوروندی
region-name-bj = بێنین
region-name-bl = سانت بارسێلێمی
region-name-bm = بەرمۆدا
region-name-bn = برۆنای
region-name-bo = بۆلیڤیا
region-name-br = بەڕازیل
region-name-bs = باهاماس،
region-name-bt = بۆتان
region-name-bv = دورگەی  بۆڤێت
region-name-bw = بۆتسوانا
region-name-by = بیلاڕووس
region-name-bz = بێلیز
region-name-ca = کەنەدا
region-name-cc = دورگەی  کۆکۆس
region-name-cd = کۆنگۆ (کینشاسا)
region-name-cf = کۆماری ئەفریقای ناوەڕاست
region-name-cg = کۆنگۆ (برازاڤیل)
region-name-ch = سویسرا
region-name-ci = کۆت دیڤوار
region-name-ck = دورگەی  کوک
region-name-cl = چیلی
region-name-cm = کامیرۆن
region-name-cn = چین
region-name-co = کۆڵۆمبیا
region-name-cp = دورگەی  کلیپەرتۆن
region-name-cr = کۆستاریکا
region-name-cu = کوبا
region-name-cw = کوراچاو
region-name-cx = دورگەی کریسمس
region-name-cy = قوبرس
region-name-de = ئەڵمانیا
region-name-dg = دیگۆ گارسیا
region-name-dj = جیبۆتی
region-name-dk = دانیمارک
region-name-dm = دۆمەنیک
region-name-do = کۆماری دۆمەنیک
region-name-dz = جەزائیر
region-name-ec = ئێکوادۆر
region-name-ee = ئەستۆنیا
region-name-eg = مسر
region-name-eh = سەحارەی ڕۆژئاوا
region-name-er = ئەریتریا
region-name-es = ئیسپانیا
region-name-et = ئەسیوپیا
region-name-fi = فینلەندا
region-name-fj = فیجی
region-name-fk = دوورگەکانی فاڵکلاند (ئیسلاس مالڤیناس)
region-name-fm = میکرۆنیسیا، بەشێکە لە هەرێمە یەکگرتووەکانی
region-name-fo = دورگەی فارۆ
region-name-fr = فەڕەنسا
region-name-ga = گابۆن
region-name-gb = شانشینی یەکگرتووی بەریتانیا
region-name-gd = گرینادا
region-name-ge = جۆرجیا
region-name-gf = غینیای فەڕەنسی
region-name-gg = گۆرێنسی
region-name-gh = غانا
region-name-gi = گیبراڵتار
region-name-gl = گرینلاند
region-name-gm = غامبيا،
region-name-gn = گینیا
region-name-gp = گوادەلۆپی
region-name-gq = گینیای جەمسەری
region-name-gr = یۆنان
region-name-gs = جۆرجیای باشور و دورگەی باشوری ساندویچ
region-name-gt = گواتیمالا
region-name-gu = گوام
region-name-gw = گینیا-بیساو
region-name-gy = گویانا
region-name-hk = هۆنگ کۆنگ
region-name-hm = دورگەی هارد و دورگەی McDonald
region-name-hn = هندوراس
region-name-hr = کرواتیا
region-name-ht = هایتی
region-name-hu = هەنگاریا
region-name-id = ئیندۆنیزیا
region-name-ie = ئیرلەندا
region-name-il = ئیسرائیل
region-name-im = ئایسڵ ئۆف مان
region-name-in = هندستان
region-name-io = ناوچەی زەریای بەریتابی هندی
region-name-iq = عێراق
region-name-ir = ئێران
region-name-is = ئایسلەندا
region-name-it = ئیتاڵیا
region-name-je = جێرسی
region-name-jm = جامایکا
region-name-jo = ئوردن
region-name-jp = یابان
region-name-ke = کینیا
region-name-kg = قیرغستان
region-name-kh = کەمبۆدیا
region-name-ki = کیریباتی
region-name-km = کۆمۆرۆس
region-name-kn = سانت کیتس و نێڤس
region-name-kp = کۆریا، باکوور
region-name-kr = کۆریا، باشوور
region-name-kw = کوەیت
region-name-ky = دوورگەکانی لایمان
region-name-kz = کازاغستان
region-name-la = لاوس
region-name-lb = لوبنان
region-name-lc = سانت لوسیا
region-name-li = لیشنشتاین
region-name-lk = سریلانکا
region-name-lr = لیبریا
region-name-ls = لیسۆتۆ
region-name-lt = لیتوانیا
region-name-lu = لۆکسەمبۆرگ
region-name-lv = لاتیڤیا
region-name-ly = لیبیا
region-name-ma = مەغریب
region-name-mc = مۆناکۆ
region-name-md = مۆڵدۆڤا
region-name-me = مۆنتینیگرۆ
region-name-mf = سانت مارتن
region-name-mg = مەدەگەسکەر
region-name-mh = دوورگەکانی مارشال
region-name-ml = مالی
region-name-mm = بۆرما
region-name-mn = مەنگۆلیا
region-name-mo = ماکاو
region-name-mp = دوورگەکانی ماریانای باکوور
region-name-mq = مارتینک
region-name-mr = مۆریتانیا
region-name-ms = مۆنتسێرات
region-name-mt = ماڵتا
region-name-mu = ماوریتیۆس
region-name-mv = ماڵدیڤ
region-name-mw = مالاوی
region-name-mx = مەکسیک
region-name-my = مالیزیا
region-name-mz = مۆزەمبیق
region-name-na = نامیبیا
region-name-nc = کالیدۆنیای نوێ
region-name-ne = نەیجەر
region-name-nf = دوورگەکانی نۆرفۆڵک
region-name-ng = نێجیریا
region-name-ni = نیگاراگوا
region-name-nl = هۆڵەندا
region-name-no = نەرویج
region-name-np = نیپاڵ
region-name-nr = ناورو
region-name-nu = نیو
region-name-nz = نیوزلەندا
region-name-om = عومان
region-name-pa = پەنەما
region-name-pe = پیرۆ
region-name-pf = پۆڵەنیسیای فەڕەنسی
region-name-pg = پاپوا غینیای نوێ
region-name-ph = فلیپین
region-name-pk = پاکستان
region-name-pl = پۆڵەندا
region-name-pm = سانت پێیر و میکۆلین
region-name-pn = دوورگەکانی پیتکەیرن
region-name-pr = پۆرتۆریکۆ
region-name-pt = پرتوگال
region-name-pw = پاڵاو
region-name-py = پاراگوای
region-name-qa = قەتەر
region-name-qm = دوورگەکانی میدوەی
region-name-qs = باساس با ئیندیا
region-name-qu = دوورگەی خوان دی نۆڤا
region-name-qw = دوورگەی وەیک
region-name-qx = دوورگەکانی گلۆریۆسۆ
region-name-qz = ئەکرۆتیری
region-name-re = ڕینیۆن
region-name-ro = ڕۆمانیا
region-name-rs = سڕبیا
region-name-ru = ڕوسیا
region-name-rw = ڕواندا
region-name-sa = سعودییەی عەرەبی
region-name-sb = دوورگەکانی سۆلۆمۆن
region-name-sc = سیشیل
region-name-sd = سودان
region-name-se = سوید
region-name-sg = سینگاپور
region-name-sh = سانت هێلینا، ئاکسێنسیۆن، و تریستان دا کونها
region-name-si = سلۆڤینیا
region-name-sk = سلۆڤاکیا
region-name-sl = سیرالیۆن
region-name-sm = سان مارین
region-name-sn = سینیگال
region-name-so = سۆماڵ
region-name-sr = سۆرینام
region-name-ss = باشووری سودان
region-name-st = ساو تۆم و پرینسپ
region-name-sv = سلڤادۆر
region-name-sx = سانت مارتن
region-name-sy = سوریا
region-name-tc = دوورگەکانی تورکس و کایکۆس
region-name-td = چاد
region-name-tf = فەڕەنسای باشوور و دورگەی ئەنتارکتیک
region-name-tg = تۆگۆ
region-name-th = تایلەند
region-name-tj = تاجیکستان
region-name-tk = تۆکیلاو
region-name-tl = تەیمور-لێستی
region-name-tm = تورکمانستان
region-name-tn = تونس
region-name-to = تۆنگا
region-name-tr = تورکیا
region-name-tt = ترینیداد و تۆباگۆ
region-name-tv = توڤالو
region-name-tw = تایوان
region-name-tz = تانزانیا
region-name-ua = ئۆکرانیا
region-name-ug = ئۆگەندا
region-name-us = ویلایەتە یەکگرتووەکانی ئەمریکا
region-name-uy = ئۆرۆگوای
region-name-uz = ئۆزبەکستان
region-name-va = شاری ڤاتیکان
region-name-vc = سانت ڤیبسنت و گرینادینس
region-name-ve = فەنزوێلا
region-name-vg = دوورگەکانی ڤیجن، بەریتانی
region-name-vi = دوورگەکانی ڤیرجن، ئەمریکی
region-name-vn = ڤێتنام
region-name-vu = ڤانواتو
region-name-wf = واڵیس و فوتونا
region-name-ws = ساموا
region-name-xa = ئاشمۆر و دوورگەکانی کارتێر
region-name-xb = دوورگەی باکەر
region-name-xc = دوورگەکانی دەریای کۆراڵ
region-name-xd = دێکیلیا
region-name-xe = دوورگەی ئەوروپا
region-name-xg = کەرتی غەززە
region-name-xh = دوورگەی هۆلاند
region-name-xj = جان ماین
region-name-xk = کۆسۆڤۆ
region-name-xl = پالمیرا ئەتۆڵ
region-name-xm = کینگمان ڕێف
region-name-xp = دوورگەکانی پاراسێل
region-name-xq = دوورگەی جارڤیس
region-name-xr = سڤالبارد
region-name-xs = دوورگەکانی سپارتلی
region-name-xt = دوورگەی ترۆمێلین
region-name-xu = جۆنستۆن ئەتۆڵ
region-name-xv = دوورگەی ناڤاسسا
region-name-xw = ئوردنی ڕۆژئاوا
region-name-ye = یەمەن
region-name-yt = مایۆتێ
region-name-za = ئەفریقای باشوور
region-name-zm = زامبیا
region-name-zw = زیمبابۆی
