# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE These strings are used inside the Memory Tools
# which is available from the Browser Tools sub-menu -> 'Memory'.
# The correct localization of this file might be to keep it in
# English, or another language commonly spoken among web developers.
# You want to make that choice consistent across the developer tools.
# A good criteria is the language in which you'd find the best
# documentation on web development on the web.

# LOCALIZATION NOTE (snapshot.io.save): The label for the link that saves a
# snapshot to disk.
snapshot.io.save = Сними
# LOCALIZATION NOTE (snapshot.io.delete): The label for the link that deletes
# a snapshot
snapshot.io.delete = Избриши
# LOCALIZATION NOTE (toolbar.displayBy): The label describing the select menu
# options of the display options.
toolbar.displayBy = Групирај според:
# LOCALIZATION NOTE (toolbar.labelBy): The label describing the select menu
# options of the label options.
toolbar.labelBy = Означи според:
# LOCALIZATION NOTE (toolbar.view): The label for the view selector in the
# toolbar.
toolbar.view = Приказ:
# LOCALIZATION NOTE (toolbar.view.census): The label for the census view option
# in the toolbar.
toolbar.view.census = Спои
# LOCALIZATION NOTE (diffing.state.error): The label describing the diffing
# state ERROR, used in the snapshot list when an error occurs while diffing two
# snapshots.
diffing.state.error = Грешка
# LOCALIZATION NOTE (dominatorTree.state.error): The label describing the
# dominator tree state ERROR.
dominatorTree.state.error = Грешка
# LOCALIZATION NOTE (individuals.state.error): The short message displayed when
# there is an error fetching individuals from a group.
individuals.state.error = Грешка
# LOCALIZATION NOTE (snapshot.state.error): The label describing the snapshot
# state ERROR, used in the snapshot list view.
snapshot.state.error = Грешка
# LOCALIZATION NOTE (heapview.none-match): Message displayed when there report
# is empty.
heapview.empty = Празно.
# LOCALIZATION NOTE (heapview.field.name): The name of the column in the heap
# view for name.
heapview.field.name = Група
