# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Hua ruhuât garasunt “%S” guendâ nej sa hua nan anj.
unnamedCA = Sa natsij na (nitaj si yugui)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Gi'iaj 'ngo sunnuj ni, gachrun da'nga' hùi garajsunt nga na'nin sà't si nuguàn' sertifikadô nan:
# Page Info
pageInfo_NoEncryption = Nitaj si hua huì Koneksiûn nan
pageInfo_Privacy_None1 = Sitiô %S na'ue nani'in si hua huì pajinâ ni'iajt nan.
pageInfo_Privacy_None2 = Nuguan' nitaj si hua huì a'nïnt riña internet ni ga'ue gini'iaj a'ngô guìi man hiaj nïn' aché nunt.
pageInfo_Privacy_None4 = Nitaj si hua huì pajinâ ni'iajt net asî gachin gisìj man riña internet.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Hua huì Koneksiûn (%1$S, %2$S si teklâ bit, %3$S)
pageInfo_BrokenEncryption = Gire sa nagi'ia huìi (%1$S, %2$S si teclâ bit, %3$S)
pageInfo_Privacy_Encrypted1 = Hua huì pajinâ ni'iajt net asî gachin gisìj man riña internet.
pageInfo_Privacy_Encrypted2 = Sifrâdo narán da' si gini'iāj nasinùnj guìi nuguan' aché riña nej aga' sikà' ràa. Ô' ni, nitāj gà' si 'ngō guìi gini'in sa gi'iát nga gaché nunt riña red.
pageInfo_MixedContent = Nitaj si hua huì Koneksiûn nan
pageInfo_MixedContent2 = Nitaj si huā huì da'aj sa 'na' riña pajinâ ni'iajt net asî gachin gisìj man riña internet.
pageInfo_WeakCipher = Nitāj si nūkuaj hua si sifradô sitiô nan nī nitàj si huì hua man. Ga'ue ni'iāj a'ngô guìi sa 'na' riña asi nadunā ni sa 'na' riñanj.
pageInfo_CertificateTransparency_Compliant = Dugahuin sitiô nan ngà sertifikadô tna'uej yi'ì sa huìi.
# Token Manager
password_not_set = (nitāj si nunj)
