# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Encoding warnings and errors
EncNoDeclarationFrame = เอกสารภายในเฟรมไม่ได้ประกาศการเข้ารหัสอักขระ การแสดงผลเอกสารอาจต่างออกไปถ้าหากเปิดดูโดยไม่อยู่ในเฟรมของเอกสารอื่น
EncXmlDecl = รหัสอักขระของเอกสาร HTML ถูกประกาศโดยใช้ไวยากรณ์ในการประกาศแบบ XML ซึ่งไม่เป็นไปตามข้อกำหนด และการประกาศรหัสอักขระโดยใช้แท็ก meta ที่จุดเริ่มต้นของส่วน head จะมีประสิทธิภาพมากกว่า
EncMetaTooLate = พบแท็ก meta ที่พยายามประกาศรหัสอักขระช้าเกินไป และได้เดารหัสอักขระจากเนื้อหาแทน แท็ก meta จะต้องถูกย้ายไปอยู่ที่จุดเริ่มต้นของส่วน head ของเอกสาร
EncMetaTooLateFrame = พบแท็ก meta ที่พยายามประกาศรหัสอักขระช้าเกินไป และได้ใช้รหัสอักขระของเอกสารแม่แทน แท็ก meta จะต้องถูกย้ายไปอยู่ที่จุดเริ่มต้นของส่วน head ของเอกสาร
EncMetaAfterHeadInKilobyte = แท็ก meta ที่ประกาศรหัสอักขระของเอกสารควรจะถูกย้ายไปที่จุดเริ่มต้นของส่วน head ของเอกสาร
EncNoDecl = ไม่ได้ประกาศรหัสอักขระของเอกสาร จึงได้เดารหัสอักขระจากเนื้อหาแทน รหัสอักขระจะต้องถูกประกาศในเฮดเดอร์ HTTP Content-Type โดยใช้แท็ก meta หรือโดยใช้เครื่องหมายลำดับไบต์
EncNoDeclPlain = ไม่ได้ประกาศรหัสอักขระของเอกสาร จึงได้เดารหัสอักขระจากเนื้อหาแทน รหัสอักขระจะต้องถูกประกาศในเฮดเดอร์ HTTP Content-Type โดยใช้เครื่องหมายลำดับไบต์
EncMetaUnsupported = เอกสาร HTML ประกาศการเข้ารหัสอักขระที่ไม่สนับสนุนโดยใช้แท็ก meta การประกาศนี้จะไม่มีผล
EncProtocolUnsupported = เอกสาร HTML ประกาศการเข้ารหัสอักขระที่ไม่สนับสนุนในระดับโพรโทคอลการส่งข้อมูล การประกาศนี้จะไม่มีผล
EncMetaUtf16 = แท็ก meta ถูกใช้ประกาศการเข้ารหัสอักขระเป็นแบบ UTF-16 จะถูกตีความว่าเป็นการประกาศแบบ UTF-8 แทน
EncMetaUserDefined = แท็ก meta ถูกใช้ประกาศการเข้ารหัสอักขระเป็นแบบ x-user-defined จะถูกตีความว่าเป็นการประกาศแบบ windows-1252 แทนเพื่อให้เข้ากันได้กับแบบอักษรแบบเก่าซึ่งเข้ารหัสอักขระผิดโดยตั้งใจ ไซต์นี้ควรเปลี่ยนไปใช้รหัสอักขระแบบ Unicode
EncMetaReplacement = แท็ก meta ถูกใช้เพื่อประกาศรหัสอักขระที่เป็นอันตรายต่อการเขียนสคริปต์แบบข้ามไซต์ (cross-site scripting) จึงใช้รหัสอักขระทดแทน
EncProtocolReplacement = รหัสอักขระที่เป็นอันตรายต่อการเขียนสคริปต์แบบข้ามไซต์ (cross-site scripting) ถูกประกาศที่ระดับโพรโทคอลการถ่ายโอน จึงใช้รหัสอักขระทดแทน
EncDetectorReload = ไม่ได้ประกาศรหัสอักขระของเอกสาร และได้เดารหัสอักขระจากเนื้อหา ซึ่งส่งผลให้เอกสารถูกโหลดซ้ำ รหัสอักขระจะต้องถูกประกาศในเฮดเดอร์ HTTP Content-Type โดยใช้แท็ก meta หรือโดยใช้เครื่องหมายลำดับไบต์
EncDetectorReloadPlain = ไม่ได้ประกาศรหัสอักขระของเอกสาร และได้เดารหัสอักขระจากเนื้อหา ซึ่งส่งผลให้เอกสารถูกโหลดซ้ำ รหัสอักขระจะต้องถูกประกาศในเฮดเดอร์ HTTP Content-Type หรือโดยใช้เครื่องหมายลำดับไบต์
EncError = สตรีมไบต์มีข้อผิดพลาดตามรหัสอักขระที่ประกาศ การประกาศรหัสอักขระอาจไม่ถูกต้อง
EncErrorFrame = สตรีมไบต์มีข้อผิดพลาดตามรหัสอักขระที่สืบทอดมาจากเอกสารแม่ รหัสอักขระจะต้องถูกประกาศในเฮดเดอร์ HTTP Content-Type โดยใช้แท็ก meta หรือโดยใช้เครื่องหมายลำดับไบต์
EncErrorFramePlain = สตรีมไบต์มีข้อผิดพลาดตามรหัสอักขระที่สืบทอดมาจากเอกสารแม่ รหัสอักขระจะต้องถูกประกาศในเฮดเดอร์ HTTP Content-Type หรือโดยใช้เครื่องหมายลำดับไบต์
EncSpeculationFailMeta = ส่วนเริ่มต้นของเอกสารถูกแจงส่วนใหม่ เนื่องจากมีอักขระที่ไม่ใช่ ASCII ก่อนแท็ก meta ที่ประกาศรหัสอักขระไว้ meta ควรเป็นแท็กลูกแท็กแรกของเฮดเดอร์ที่ไม่มีคำอธิบายที่ไม่ใช่ ASCII มาก่อน
EncSpeculationFailXml = ส่วนเริ่มต้นของเอกสารถูกแจงส่วนใหม่ เนื่องจากมีอักขระที่ไม่ใช่ ASCII ในส่วนของเอกสารที่ค้นหาแท็ก meta ไม่สำเร็จก่อนที่จะถอยกลับไปใช้ไวยาการณ์การประกาศแบบ XML ควรใช้แท็ก meta ที่ส่วนเริ่มต้นของเฮดเดอร์แทนไวยากรณ์การประกาศแบบ XML
# The audience of the following message isn't the author of the document but other people debugging browser behavior.
EncSpeculationFail2022 = ส่วนเริ่มต้นของเอกสารถูกแจงส่วนใหม่ เนื่องจาก ISO-2022-JP เป็นรหัสอักขระที่ใช้ร่วมกับ ASCII ไม่ได้

# The bulk of the messages below are derived from
# https://hg.mozilla.org/projects/htmlparser/file/1f633cef7de7/src/nu/validator/htmlparser/impl/ErrorReportingTokenizer.java
# which is available under the MIT license.

# Tokenizer errors
errGarbageAfterLtSlash = พบเนื้อหาที่ไม่ถูกต้องหลังจาก “</”
errLtSlashGt = พบ “</>” สาเหตุที่เป็นไปได้: ไม่ได้หลีก “<” (หลีกได้ในรูปของ “&lt;”) หรือพิมพ์แท็กปิดผิด
errCharRefLacksSemicolon = ตัวอ้างอิงอักขระไม่ได้ปิดท้ายด้วยเซมิโคลอน
errNoDigitsInNCR = ไม่มีตัวเลขในตัวอ้างอิงอักขระแบบตัวเลข
errGtInSystemId = “>” ในตัวระบุระบบ
errGtInPublicId = “>” ในตัวระบุสาธารณะ
errNamelessDoctype = doctype ไม่มีชื่อ
errConsecutiveHyphens = เครื่องหมายขีดกลางติดกันไม่ได้ปิดความคิดเห็น ไม่อนุญาตให้ใช้ “--” ภายในความคิดเห็น แต่สามารถใช้ “- -” ได้
errPrematureEndOfComment = พบจุดสิ้นสุดของความคิดเห็นก่อนจุดที่เหมาะสม ให้ใช้ “-->” เพื่อปิดความคิดเห็นอย่างเหมาะสม
errBogusComment = ความคิดเห็นไม่ถูกต้อง
errUnquotedAttributeLt = มี “<” ในค่าแอตทริบิวต์ที่ไม่ได้อยู่ในเครื่องหมายคำพูด สาเหตุที่เป็นไปได้: ไม่มี “>” ทันทีข้างหน้า
errUnquotedAttributeGrave = มี “`” ในค่าแอตทริบิวต์ที่ไม่ได้อยู่ในเครื่องหมายคำพูด สาเหตุที่เป็นไปได้: ใช้อักขระผิดเป็นเครื่องหมายคำพูด
errUnquotedAttributeQuote = มีเครื่องหมายคำพูดในค่าแอตทริบิวต์ที่ไม่ได้อยู่ในเครื่องหมายคำพูด สาเหตุที่เป็นไปได้: แอตทริบิวต์อยู่ติดกันหรือสตริงคำค้น URL ในค่าแอตทริบิวต์ที่ไม่ได้อยู่ในเครื่องหมายคำพูด
errUnquotedAttributeEquals = มี “=” ในค่าแอตทริบิวต์ที่ไม่ได้อยู่ในเครื่องหมายคำพูด สาเหตุที่เป็นไปได้: แอตทริบิวต์อยู่ติดกันหรือสตริงคำค้น URL ในค่าแอตทริบิวต์ที่ไม่ได้อยู่ในเครื่องหมายคำพูด
errSlashNotFollowedByGt = เครื่องหมายทับไม่ได้ตามด้วย “>” ทันที
errNoSpaceBetweenAttributes = ไม่มีช่องว่างระหว่างแอตทริบิวต์
errUnquotedAttributeStartLt = มี “<” ที่จุดเริ่มต้นของค่าแอตทริบิวต์ที่ไม่ได้อยู่ในเครื่องหมายคำพูด สาเหตุที่เป็นไปได้: ไม่มี “>” ทันทีข้างหน้า
errUnquotedAttributeStartGrave = มี “`” ที่จุดเริ่มต้นของค่าแอตทริบิวต์ที่ไม่ได้อยู่ในเครื่องหมายคำพูด สาเหตุที่เป็นไปได้: ใช้อักขระผิดเป็นเครื่องหมายคำพูด
errUnquotedAttributeStartEquals = มี “=” ที่จุดเริ่มต้นของค่าแอตทริบิวต์ที่ไม่ได้อยู่ในเครื่องหมายคำพูด สาเหตุที่เป็นไปได้: เครื่องหมายเท่ากับซ้ำซ้อนโดยไม่จำเป็น
errAttributeValueMissing = ค่าแอตทริบิวต์ขาดหายไป
errBadCharBeforeAttributeNameLt = พบ “<” เมื่อต้องการชื่อแอตทริบิวต์ สาเหตุที่เป็นไปได้: ไม่มี “>” ทันทีข้างหน้า
errEqualsSignBeforeAttributeName = พบ “=” เมื่อต้องการชื่อแอตทริบิวต์ สาเหตุที่เป็นไปได้: ชื่อแอตทริบิวต์ขาดหายไป
errBadCharAfterLt = มีอักขระที่ไม่ถูกต้องหลังจาก “<” สาเหตุที่เป็นไปได้: ไม่ได้หลีก “<” ให้ลองหลีกในรูปของ “&lt;”
errLtGt = พบ “<>” สาเหตุที่เป็นไปได้: ไม่ได้หลีก “<” (หลีกได้ในรูปของ “&lt;”) หรือพิมพ์แท็กเปิดผิด
errProcessingInstruction = พบ “<?” สาเหตุที่เป็นไปได้: พยายามใช้คำสั่งการประมวลผล XML ใน HTML (ไม่รองรับคำสั่งการประมวลผล XML ใน HTML)
errUnescapedAmpersandInterpretedAsCharacterReference = สตริงที่ตามด้วย “&” ถูกตีความว่าเป็นตัวอ้างอิงอักขระ (“&” น่าจะต้องหลีกด้วย “&amp;”)
errNotSemicolonTerminated = ตัวอ้างอิงอักขระแบบระบุชื่อไม่ได้ปิดท้ายด้วยเซมิโคลอน (หรือควรหลีก “&” ด้วย “&amp;”)
errNoNamedCharacterMatch = “&” ไม่ได้ขึ้นต้นตัวอ้างอิงอักขระ (“&” น่าจะต้องหลีกด้วย “&amp;”)
errQuoteBeforeAttributeName = พบเครื่องหมายคำพูดเมื่อต้องการชื่อแอตทริบิวต์ สาเหตุที่เป็นไปได้: ไม่มี “=” ทันทีข้างหน้า
errLtInAttributeName = มี “<” ในชื่อแอตทริบิวต์ สาเหตุที่เป็นไปได้: ไม่มี “>” ทันทีข้างหน้า
errQuoteInAttributeName = เครื่องหมายคำพูดในชื่อแอตทริบิวต์ สาเหตุที่เป็นไปได้: ขาดเครื่องหมายคำพูดที่ตรงกันในส่วนใดส่วนหนึ่งก่อนหน้านี้
errExpectedPublicId = ต้องการ public identifier แต่ชนิดเอกสารถูกปิดไปแล้ว
errBogusDoctype = ชนิดเอกสารไม่ถูกต้อง
maybeErrAttributesOnEndTag = แท็กปิดมีแอตทริบิวต์
maybeErrSlashInEndTag = มี “/” เกินมาที่จุดสิ้นสุดของแท็กปิด
errNcrNonCharacter = ตัวอ้างอิงอักขระมีการขยายไปสู่สิ่งที่ไม่ใช่อักขระ
errNcrSurrogate = ตัวอ้างอิงอักขระมีการขยายไปสู่รหัสตัวแทน
errNcrControlChar = ตัวอ้างอิงอักขระมีการขยายไปสู่อักขระควบคุม
errNcrCr = ตัวอ้างอิงอักขระแบบตัวเลขมีการขยายไปสู่อักขระปัดแคร่
errNcrInC1Range = ตัวอ้างอิงอักขระแบบตัวเลขมีการขยายไปสู่ช่วงอักขระควบคุม C1
errEofInPublicId = End of file inside public identifier.
errEofInComment = End of file inside comment.
errEofInDoctype = End of file inside doctype.
errEofInAttributeValue = End of file reached when inside an attribute value. Ignoring tag.
errEofInAttributeName = End of file occurred in an attribute name. Ignoring tag.
errEofWithoutGt = Saw end of file without the previous tag ending with “>”. Ignoring tag.
errEofInTagName = End of file seen when looking for tag name. Ignoring tag.
errEofInEndTag = End of file inside end tag. Ignoring tag.
errEofAfterLt = End of file after “<”.
errNcrOutOfRange = Character reference outside the permissible Unicode range.
errNcrUnassigned = Character reference expands to a permanently unassigned code point.
errDuplicateAttribute = Duplicate attribute.
errEofInSystemId = End of file inside system identifier.
errExpectedSystemId = Expected a system identifier but the doctype ended.
errMissingSpaceBeforeDoctypeName = Missing space before doctype name.
errNestedComment = พบ “<!--” ในความคิดเห็น สาเหตุที่เป็นไปได้: ความคิดเห็นที่ซ้อนกัน (ไม่อนุญาต)
errNcrZero = Character reference expands to zero.
errNoSpaceBetweenDoctypeSystemKeywordAndQuote = No space between the doctype “SYSTEM” keyword and the quote.
errNoSpaceBetweenPublicAndSystemIds = No space between the doctype public and system identifiers.
errNoSpaceBetweenDoctypePublicKeywordAndQuote = No space between the doctype “PUBLIC” keyword and the quote.
# Tree builder errors
errDeepTree = ทรีเอกสารลึกเกินไป ทรีจะถูกลดขนาดให้เหลือความลึกเพียง 513 อิลิเมนต์
errStrayStartTag2 = Stray start tag “%1$S”.
errStrayEndTag = Stray end tag “%1$S”.
errUnclosedElements = End tag “%1$S” seen, but there were open elements.
errUnclosedElementsImplied = End tag “%1$S” implied, but there were open elements.
errUnclosedElementsCell = A table cell was implicitly closed, but there were open elements.
errStrayDoctype = Stray doctype.
errAlmostStandardsDoctype = Almost standards mode doctype. Expected “<!DOCTYPE html>”.
errQuirkyDoctype = Quirky doctype. Expected “<!DOCTYPE html>”.
errAlmostStandardsDoctypeVerbose = หน้านี้อยู่ในโหมดเกือบมาตรฐาน เค้าโครงหน้าอาจได้รับผลกระทบ สำหรับโหมดมาตรฐาน ให้ใช้ “<!DOCTYPE html>”
errQuirkyDoctypeVerbose = หน้านี้อยู่ในโหมด Quirks เค้าโครงหน้าอาจได้รับผลกระทบ สำหรับโหมดมาตรฐาน ให้ใช้ “<!DOCTYPE html>”
errNonSpaceInTrailer = Non-space character in page trailer.
errNonSpaceAfterFrameset = Non-space after “frameset”.
errNonSpaceInFrameset = Non-space in “frameset”.
errNonSpaceAfterBody = Non-space character after body.
errNonSpaceInColgroupInFragment = Non-space in “colgroup” when parsing fragment.
errNonSpaceInNoscriptInHead = Non-space character inside “noscript” inside “head”.
errFooBetweenHeadAndBody = “%1$S” element between “head” and “body”.
errStartTagWithoutDoctype = Start tag seen without seeing a doctype first. Expected “<!DOCTYPE html>”.
errNoSelectInTableScope = No “select” in table scope.
errStartSelectWhereEndSelectExpected = “select” start tag where end tag expected.
errStartTagWithSelectOpen = “%1$S” start tag with “select” open.
errBadStartTagInNoscriptInHead = แท็กเริ่มต้น “%1$S” ใน “noscript” ใน “head” ไม่ถูกต้อง
errImage = Saw a start tag “image”.
errFooSeenWhenFooOpen2 = เห็นแท็กเริ่มต้น “%1$S” แล้วแต่อิลิเมนต์ของชนิดเดียวกันถูกเปิดไว้อยู่แล้ว
errHeadingWhenHeadingOpen = Heading cannot be a child of another heading.
errFramesetStart = “frameset” start tag seen.
errNoCellToClose = No cell to close.
errStartTagInTable = Start tag “%1$S” seen in “table”.
errFormWhenFormOpen = Saw a “form” start tag, but there was already an active “form” element. Nested forms are not allowed. Ignoring the tag.
errTableSeenWhileTableOpen = Start tag for “table” seen but the previous “table” is still open.
errStartTagInTableBody = “%1$S” start tag in table body.
errEndTagSeenWithoutDoctype = End tag seen without seeing a doctype first. Expected “<!DOCTYPE html>”.
errEndTagAfterBody = Saw an end tag after “body” had been closed.
errEndTagSeenWithSelectOpen = “%1$S” end tag with “select” open.
errGarbageInColgroup = Garbage in “colgroup” fragment.
errEndTagBr = End tag “br”.
errNoElementToCloseButEndTagSeen = No “%1$S” element in scope but a “%1$S” end tag seen.
errHtmlStartTagInForeignContext = HTML start tag “%1$S” in a foreign namespace context.
errNoTableRowToClose = No table row to close.
errNonSpaceInTable = Misplaced non-space characters inside a table.
errUnclosedChildrenInRuby = Unclosed children in “ruby”.
errStartTagSeenWithoutRuby = Start tag “%1$S” seen without a “ruby” element being open.
errSelfClosing = Self-closing syntax (“/>”) used on a non-void HTML element. Ignoring the slash and treating as a start tag.
errNoCheckUnclosedElementsOnStack = Unclosed elements on stack.
errEndTagDidNotMatchCurrentOpenElement = End tag “%1$S” did not match the name of the current open element (“%2$S”).
errEndTagViolatesNestingRules = End tag “%1$S” violates nesting rules.
errEndWithUnclosedElements = พบแท็กปิดท้ายสำหรับ “%1$S” แต่มีอิลิเมนต์ที่ยังไม่ได้ปิด
errListUnclosedStartTags = อิลิเมนต์ที่ไม่ได้ปิด
