# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Shranjene prijave
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Kopiraj URL
    .accesskey = o
launch-site-url-cmd =
    .label = Obišči URL
    .accesskey = b
copy-username-cmd =
    .label = Kopiraj uporabniško ime
    .accesskey = a
edit-username-cmd =
    .label = Uredi uporabniško ime
    .accesskey = r
copy-password-cmd =
    .label = Kopiraj geslo
    .accesskey = K
edit-password-cmd =
    .label = Uredi geslo
    .accesskey = E
search-filter =
    .accesskey = I
    .placeholder = Išči
column-heading-site =
    .label = Stran
column-heading-username =
    .label = Uporabniško ime
column-heading-password =
    .label = Geslo
column-heading-time-created =
    .label = Prvič uporabljeno
column-heading-time-last-used =
    .label = Nazadnje uporabljeno
column-heading-time-password-changed =
    .label = Nazadnje spremenjeno
column-heading-times-used =
    .label = Število uporab
remove =
    .label = Odstrani
    .accesskey = O
import =
    .label = Uvozi …
    .accesskey = U
close-button =
    .label = Zapri
    .accesskey = Z
show-passwords =
    .label = Pokaži gesla
    .accesskey = P
hide-passwords =
    .label = Skrij gesla
    .accesskey = s
logins-description-all = Prijave za naslednje strani so shranjene na vašem računalniku
logins-description-filtered = Prijave, ki ustrezajo vašemu iskanju:
remove-all =
    .label = Odstrani vse
    .accesskey = v
remove-all-shown =
    .label = Odstrani vsa prikazana
    .accesskey = v
remove-all-passwords-prompt = Ali ste prepričani, da želite odstraniti vsa gesla?
remove-all-passwords-title = Odstrani vsa gesla
no-master-password-prompt = Ali ste prepričani, da želite pokazati svoja gesla?
auto-fill-logins-and-passwords =
    .label = Samodejno izpolni prijave in gesla
