# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Om dine rettigheder
rights-intro = { -brand-full-name } er software med fri og åben kildekode, skabt af en sammenslutning af tusindvis af mennesker over hele kloden. Der er et par ting, som du bør vide:
rights-intro-point-1 = { -brand-short-name } gøres tilgængelig for dig under retningslinjerne i <a data-l10n-name="mozilla-public-license-link">Mozilla Public License</a>. Dette betyder at du må bruge, kopiere og videregive { -brand-short-name } til andre. Du er er også velkommen til at ændre i kildekoden til { -brand-short-name } for at opfylde dine behov. Mozilla Public License tildeler dig også retten til at videregive dine ændrede versioner.
rights-intro-point-3 = Nogle funktioner i { -brand-short-name }, såsom Fejlrapportør, giver dig mulighed for at give feedback til  { -vendor-short-name }. Ved at vælge at sende feedback giver du { -vendor-short-name } tilladelse til at bruge de givne informationer til at forbedre deres produkter, offenliggøre disse på deres webside(r) samt at videredistribuere disse frit.
rights-intro-point-5-unbranded = Hvis dette produkt bruger webbaserede tjenester skal alle vedkommende vilkår for tjenesterne linkes til under afsnittet <a data-l10n-name="mozilla-website-services-link">Webbaserede tjenester</a>.
rights-webservices = { -brand-full-name } bruger webbaserede informationstjenester ("Tjenester") som gøres tilgængelig for dig ved brug af denne binære version af { -brand-short-name } som beskrevet i de nedenstående vilkår. Hvis du ikke ænsker at bruge en eller flere af disse tjenester, eller hvis du ikke kan tilslutte dig de nedenstående vilkår, kan du deaktivere funktionen eller tjenesten. Instruktioner til at deaktivere en given funktion eller tjeneste kan findes <a data-l10n-name="mozilla-disable-service-link">her</a>. Andre funktioner og tjenester kan deaktiveres i indstillingerne.
rights-locationawarebrowsing = <strong>Positionsbevidst browsing: </strong>Du bliver altid spurgt om du ønsker at dele din position. Din position bliver aldrig sendt uden dit samtykke. Hvis du ønsker at deaktivere denne funktion fuldstændigt kan det gøres ved følgende trin:
rights-locationawarebrowsing-term-1 = Skriv følgende i adressefeltet <code>about:config</code>
rights-locationawarebrowsing-term-4 = Positionsbevidt browsing er nu deaktiveret
rights-webservices-unbranded = Et overblik over de webbaserede tjenester, produktet bruger, samt instruktioner om, hvordan de deaktiveres (hvis muligt), skal inkluderes her.
rights-webservices-term-1 = { -vendor-short-name } og dets bidragydere, licensholdere og forretningspartnere arbejder på at yde de mest korrekte og ajourførte tjenester. Vi kan dog ikke garantere at denne information er fyldestgørende eller fejlfri. Eksempelvis kan Safe Browsing-tjenesten ikke altid identificere risikofyldte websteder og kan tillige fejlagtigt blokere for sikre websteder. Ved positionsbevidst browsing vil positioner returneret af vores tjenesteudbydere kun være omtrentlige og vi garanterer ikke for præcisionen.
rights-webservices-term-4 = <strong>Tjenesten leveres "som den fremstår." { -vendor-short-name }, dets bidragydere, licensholdere og distributører fraskriver sig alle garantier, udtrykt eller indforstået, inklusive garantier om hvorvidt tjenesten er handelsgyldig eller passer til dit formål. Du bærer den fulde risiko ved at bruge tjenesten til dine formål samt kvaliteten og ydelsen, som tjenesten leverer. Nogle retskredse tillader ikke eksklusion eller begrænsning af indforståede garantier, så denne fraskrivelse af garanti kan i visse tilfælde ikke berøre dig.</strong>
rights-webservices-term-5 = <strong>Undtaget som lovpåkrævet vil { -vendor-short-name }, dets bidragydere, licensholdere og distributører ikke hæfte for nogen indirekte, specielle, incidentale, afledte, strafmæssige eller statutmæssige krav som opstår af, eller på nogen måde er relateret til brugen af { -brand-short-name } og dets tjenester. Den samlede hæfte under disse vilkår kan ikke overstige $500 (Femhundrede dollars USD). Nogle retskredse tillader ikke eksklusion eller begrænsning af hæfte/krav, så denne fraskrivelse af hæfte kan i visse tilfælde ikke berøre dig.</strong>
