# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

url-classifier-title = URL বৰ্গীকাৰক তথ্য
url-classifier-search-title = সন্ধান কৰক
url-classifier-search-result-title = ফলাফল
url-classifier-search-result-uri = URI: { $uri }
url-classifier-search-result-list = তালিকাৰ সূচি: { $list }
url-classifier-search-input = URL
url-classifier-search-error-invalid-url = অবৈধ URL
url-classifier-search-error-no-features = কোনো সুবিধা চয়ন কৰা নাই
url-classifier-search-btn = সন্ধান আৰম্ভ কৰক
url-classifier-search-features = সুবিধাবোৰ
url-classifier-search-listType = সূচিৰ ধৰণ
url-classifier-provider-title = প্ৰদানকাৰী
url-classifier-provider = প্ৰদানকাৰী
url-classifier-provider-last-update-time = অন্তিম আপডেটৰ সময়
url-classifier-provider-next-update-time = পৰৱৰ্তী আপডেটৰ সময়
url-classifier-provider-back-off-time = বেক-অফ সময়
url-classifier-provider-last-update-status = অন্তিম আপডেটৰ স্থিতি
url-classifier-provider-update-btn = আপডেট
url-classifier-cache-title = কেশ্ব
url-classifier-cache-refresh-btn = সতেজ কৰক
url-classifier-cache-clear-btn = পৰিষ্কাৰ
url-classifier-cache-table-name = তালিকাৰ নাম
url-classifier-cache-ncache-entries = নেতিবাচক কেশ্ব প্ৰবিষ্টিৰ সংখ্যা
url-classifier-cache-pcache-entries = ইতিবাচক কেশ্ব প্ৰবিষ্টিৰ সংখ্যা
url-classifier-cache-show-entries = প্ৰবিষ্টিবোৰ দেখুৱাওক
url-classifier-cache-entries = কেশ্ব প্ৰবিষ্টিবোৰ
url-classifier-cache-prefix = উপসৰ্গ
url-classifier-cache-ncache-expiry = নেতিবাচক কেশ্ব সমাপ্তি
url-classifier-cache-fullhash = পূৰ্ণ হেশ্ব
url-classifier-cache-pcache-expiry = ইতিবাচক কেশ্ব সমাপ্তি
url-classifier-debug-title = ত্ৰুটি সংশোধন
url-classifier-debug-module-btn = লগ মডিউল ছেট কৰক
url-classifier-debug-file-btn = লগ ফাইল ছেট কৰক
url-classifier-debug-js-log-chk = JS লগ ছেট কৰক
url-classifier-debug-sb-modules = নিৰাপদ ব্ৰাউজিং লগ মডিউল
url-classifier-debug-modules = বৰ্তমানৰ লগ মডিউল
url-classifier-debug-sbjs-modules = নিৰাপদ ব্ৰাউজিং JS লগ
url-classifier-debug-file = বৰ্তমানৰ লগ ফাইল
url-classifier-trigger-update = আপডেট ট্ৰিগাৰ কৰক
url-classifier-not-available = প্ৰ/ন
url-classifier-disable-sbjs-log = নিৰাপদ ব্ৰাউজিং JS লগ অক্ষম কৰক
url-classifier-enable-sbjs-log = নিৰাপদ ব্ৰাউজিং JS লগ সক্ষম কৰক
url-classifier-enabled = সক্ষম কৰা হ'ল
url-classifier-disabled = অক্ষম কৰা হ'ল
url-classifier-updating = আপডেট হৈ আছে
url-classifier-cannot-update = আপডেট কৰিব নোৱাৰি
url-classifier-success = সফল
url-classifier-update-error = আপডেট ত্ৰুটি ({ $error })
url-classifier-download-error = ডাউনল'ড ত্ৰুটি ({ $error })
