# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SaveImageTitle = Sarva inmagine
SaveMediaTitle = Sarva media
SaveVideoTitle = Sarva video
SaveAudioTitle = Sarva son
SaveLinkTitle = Sarva co-o nomme
WebPageCompleteFilter = Pagina Web,conpleta
WebPageHTMLOnlyFilter = Pagina Web, solo HTML
WebPageXHTMLOnlyFilter = Pagina Web, solo XHTML
WebPageSVGOnlyFilter = Pagina Web, solo SVG
WebPageXMLOnlyFilter = Pagina Web, solo XML
