# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = Տեղի ունեցավ վերահասցեավորում։ Ցանկանու՞մ էք մուտքագրած Ձեր տվյալները վերահասցեավորել դեպի նոր հասցե։
# Directory listing strings
DirTitle = %1$S -ի ինդեքս
DirGoUp = Բարձրանալ վերևի պանակ
ShowHidden = Ցուցադրել թաքցված օբյեկտները
DirColName = Անվանումը
DirColSize = Չափը
DirColMTime = Վերջին փոփոխությունը
DirFileLabel = ֆայլ`
UnsafeUriBlocked = Ռեսուրսը “%1$S”-ում արգելափակվել է Գաղտնի դիտարկման կողմից:
CookieBlockedByPermission = “%1$S”-ում թխուկների կամ հիշողության հասանելիության դիմումն արգելափակվել է, հարմարեցված թխուկի արտոնության պատճառով։
CookieBlockedAll = «%1$S»-ում թխուկների կամ հիշողության հասանելիության դիմումը արգելափակվել է, որովհետև մենք արգելափակում ենք հիշողության հասանելիության բոլոր դիմումները։
# LOCALIZATION NOTE (CookieAllowedForOriginByStorageAccessAPI): %2$S and %1$S are URLs.
CookieAllowedForOriginByStorageAccessAPI = Պահեստի մատչումը թույլատրված է սկզբնական “%2$S”-ի համար “%1$S”-ում:
# LOCALIZATION NOTE (CookieAllowedForOriginByHeuristic): %2$S and %1$S are URLs.
CookieAllowedForOriginByHeuristic = Պահեստի մատչումը ինքնաբար  թույլատրված է սկզբնական “%2$S”-ի համար “%1$S”-ում:
# LOCALIZATION NOTE (CookieOversize): %1$S is the cookie name. %2$S is the number of bytes. "B" means bytes.
CookieOversize = Նշոցիկ «%1$S» անվավեր է, քանի որ դրա չափը չափազանց մեծ է։ Առավելագույն չափը %2$S B է։
InvalidHTTPResponseStatusLine = HTTP պատասխանի կարգավիճակի տողն անվավեր է
