# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Localizando { $host }…
network-connection-status-connected = Conectado a { $host }…
network-connection-status-sending-request = Enviando solicitação para { $host }…
network-connection-status-transferring-data = Transferindo dados de { $host }…
network-connection-status-connecting = Conectando a { $host }…
network-connection-status-read = Leu { $host }
network-connection-status-wrote = Escreveu { $host }
network-connection-status-waiting = Esperando por { $host }…
network-connection-status-looked-up = Localizado { $host }…
network-connection-status-tls-handshake = Realizando um handshake TLS para { $host }…
network-connection-status-tls-handshake-finished = O handshake TLS terminou para { $host }…
