# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Soek tans { $host } op…
network-connection-status-connected = Gekoppel aan { $host }…
network-connection-status-sending-request = Stuur tans versoek na { $host }…
network-connection-status-transferring-data = Dra tans data oor van { $host }…
network-connection-status-connecting = Koppel tans aan { $host }…
network-connection-status-read = Lees { $host }
network-connection-status-wrote = Skryf { $host }
network-connection-status-waiting = Wag tans vir { $host }…
network-connection-status-looked-up = Het { $host } opgesoek…
