# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

addons-window =
    .title = ຕົວຈັດການກັບ Add-ons
search-header-shortcut =
    .key = f
loading-label =
    .value = ກຳລັງໂຫລດ…
list-empty-installed =
    .value = ທ່ານບໍ່ໄດ້ຕິດຕັ້ງ Add-ons ປະເພດນີ້ໄວ້
list-empty-available-updates =
    .value = ບໍ່ພົບການອັບເດດ
list-empty-recent-updates =
    .value = ທ່ານບໍ່ໄດ້ອັບເດດ Add-ons ຈັກອັນເລີຍ
list-empty-find-updates =
    .label = ກວດເບິງການອັບເດດ
list-empty-button =
    .label = ຮຽນຮູ້ເພີ່ມເຕີມກ່ຽວກັບ Add-ons ນີ້
install-addon-from-file =
    .label = ຕິດຕັ້ງ Add-ons ຈາກໄຟລ໌…
    .accesskey = I
tools-menu =
    .tooltiptext = ເຄື່ອງມືສຳລັບທຸກ Add-ons
show-unsigned-extensions-button =
    .label = ບໍ່ສາມາດຢືນຢັນບາງ extension ໄດ້
show-all-extensions-button =
    .label = ສະແດງ extension ທັງຫມົດ
debug-addons =
    .label = ດີບັກ Add-on
    .accesskey = B
cmd-find-updates =
    .label = ຊອກຫາການອັບເດດ
    .accesskey = F
cmd-enable-theme =
    .label = ໃຊ້ຊຸດປັບແຕ່ງ
    .accesskey = W
cmd-install-addon =
    .label = ການຕິດຕັ້ງ
    .accesskey = I
detail-last-updated =
    .label = ອັດເດດຫຼ້າສຸດ
detail-update-type =
    .value = ອັບເດດອັດຕະໂນມັດ
detail-home =
    .label = ຫນ້າທຳອິດ
detail-home-value =
    .value = { detail-home.label }
detail-repository-value =
    .value = { detail-repository.label }
detail-check-for-updates =
    .label = ກວດສອບການອັບເດດ
    .accesskey = F
    .tooltiptext = ກວດເບິ່ງການອັບເດດນີ້ສຳລັບ add-on
detail-rating =
    .value = ຄະແນນ
