# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Notice: If you're updating this list, you should also
###         update the list in mozIntl.js.

region-name-ad = Andorre
region-name-ao = Angola
region-name-as = Samoa américaines
region-name-aw = Aruba
region-name-ba = Bosnie-Herzégovine
region-name-be = Belsik
region-name-bf = Burkina Faso
region-name-bi = Burundi
region-name-br = Beresil
region-name-bv = Bouvet, île
region-name-ca = Kanada
region-name-ch = Siwis
region-name-ck = Cook, îles
region-name-cm = Kamërun
region-name-cn = Siin
region-name-cx = Christmas, île
region-name-cy = Chypre
region-name-cz = Tchèque, République
region-name-de = Almaañ
region-name-dz = Alseri
region-name-eh = Sahara Occidental
region-name-er = Érythrée
region-name-es = Espaañ
region-name-et = Écoopi
region-name-fj = Fidji
region-name-fo = Féroé, îles
region-name-fr = Farans
region-name-gd = Grenade
region-name-ge = Géorgie
region-name-gf = Guyane Française
region-name-gg = Guernesey
region-name-gh = Gaana
region-name-gi = Sibaraltaar
region-name-gl = Groenland
region-name-gw = Gine Bisawo
region-name-gy = Giyaan
region-name-hm = Heard, îles et McDonald, îles
region-name-hr = Croatie
region-name-hu = Hongrie
region-name-im = Man, île de
region-name-in = Inde
region-name-iq = Irak
region-name-ir = Iran
region-name-is = Islande
region-name-it = Itali
region-name-jm = Jamayik
region-name-jp = Japon
region-name-kg = Kirghizistan
region-name-kh = Cambodge
region-name-ki = Kiribati
region-name-km = Komoor
region-name-kn = Saint-Kitts-et-Nevis
region-name-kw = Kowet
region-name-ky = Caïmans, îles
region-name-lb = Liban
region-name-lc = Sainte-Lucie
region-name-li = Liechtenstein
region-name-lr = Liberiya
region-name-ls = Lësoto
region-name-lt = Lituanie
region-name-lv = Lettonie
region-name-ly = Libi
region-name-ma = Marok
region-name-md = Moldavie
region-name-me = Monténégro
region-name-mh = Marshall, îles
region-name-ml = Mali
region-name-mn = Mongolie
region-name-mp = Mariannes du Nord, îles
region-name-mr = Moritani
region-name-ms = Montserrat
region-name-mt = Malte
region-name-mu = Maurice
region-name-mw = Malawi
region-name-mx = Meksik
region-name-na = Namibi
region-name-nc = Nouvelle-Calédonie
region-name-nf = Norfolk, île
region-name-ng = Niseriya
region-name-nl = Pays-Bas
region-name-no = Norvège
region-name-np = Népal
region-name-nu = Niué
region-name-pa = Panama
region-name-pe = Peru
region-name-pf = Polynésie française
region-name-pg = Papouasie-Nouvelle-Guinée
region-name-ph = Filipin
region-name-pk = Pakistan
region-name-pl = Poloñ
region-name-pm = Saint-Pierre-et-Miquelon
region-name-pt = Portugaal
region-name-pw = Palaos
region-name-re = Réunion
region-name-ro = Roumanie
region-name-rs = Serbie
region-name-rw = Ruwanda
region-name-sa = Arabi sawudit
region-name-sb = Salomon, îles
region-name-sd = Soudan
region-name-se = Suwed
region-name-sg = Singapuur
region-name-si = Slovénie
region-name-sk = Slovaquie
region-name-sl = Sera leyon
region-name-sm = Saint-Marin
region-name-sn = Senegaal
region-name-so = Somali
region-name-st = Sao Tomé-et-Principe
region-name-sy = Siri
region-name-tc = Turques et Caïques, îles
region-name-td = Cadd
region-name-tg = Togo
region-name-th = Thaïlande
region-name-tj = Tadjikistan
region-name-tk = Tokelau
region-name-tm = Turkménistan
region-name-tn = Tinisi
region-name-to = Tonga
region-name-tr = Tirki
region-name-tt = Trinidad
region-name-tw = Taywan
region-name-tz = Tansani
region-name-ug = Uganda
region-name-us = Etasini
region-name-uz = Ouzbékistan
region-name-va = Vatican
region-name-vc = Saint-Vincent-et-les-Grenadines
region-name-vn = Wiyetnaam
region-name-wf = Wallis-et-Futuna
region-name-ye = Yemen
region-name-za = Afirik di Sid
region-name-zm = Sambi
region-name-zw = Simbabwe
