# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Oer jo rjochten
rights-intro-point-3 = Inkelde ûnderdielen yn { -brand-short-name }, lykas de Ungelokrapportearder, jouwe jo de mooglikheid om kommentaar te leverjen oan { -vendor-short-name }. As jo kieze om kommentaar te leverjen, jouwe jo { -vendor-short-name } tastimming om it kommentaar te brûken om har produkten te ferbetterjen, it kommentaar te publisearjen op syn websites en om it kommentaar te fersprieden.
rights-intro-point-5 = Inkelde { -brand-short-name } funksjes meitsje gebrûk fan web-basearre ynformaasje tsjinsten, mar, wy kinne net fersekerje dat se 100% akkuraat of flaterfrij binne. Mear details, ynklusyf ynformaasje oer hoe't jo dizze funksjes útskeakelje kinne dy't dizze tsjinsten brûke, kinne fûn wurde yn de <a data-l10n-name="mozilla-service-terms-link">tsjinsttermen</a>.
rights-intro-point-5-unbranded = As dit produkt webtsjinsten brûkt, moat elke tapaste tsjinsttermen foar de tsjinst(en) keppele nei de <a data-l10n-name="mozilla-website-services-link">Websitetsjinsten</a> seksje.
rights-webservices = { -brand-full-name } brûkt web-basearre ynformaasjetsjinsten (‘Tsjinsten’) om funksjes oan te bieden foar jo gebrûk mei dizze binêre ferzje fan { -brand-short-name } ûnder de betingsten as hjirûnder beskreaun. As jo ien of mear fan dizze Tsjinsten net brûke wolle of de betingsten hjirûnder binne net te akseptearjen, kinne jo de funksjes of Tsjinst(en) útskeakelje. Ynstruksjes oer hoe't jo in bepaalde funksje of Tsjinst útskeakelje kinne, kinne jo <a data-l10n-name="mozilla-disable-service-link">hjir</a> fine. Oare ûnderdielen en tsjinsten kinne útskeakele wurde yn de opsjes fan de tapassing.
rights-locationawarebrowsing = <strong>Lokaasjebewust sneupe: </strong>is altyd opt-yn.  Lokaasje-ynformaasje wurdt nea ferstjoerd sûnder jo tastimming.  As jo dizze funksje folslein útskeakelje wolle, folgje dan dizze stappen:
rights-webservices-unbranded = In oersicht fan de websitetsjinsten dy't yn it produkt sitte, tegearre mei ynstruksjes oer hoe't jo se útskeakelje kinne, wannear mooglik, soe hjir stean moatte.
rights-webservices-term-4 = <strong>De Tjinsten wurde "as-is" oanbean.  { -vendor-short-name }, syn meiwurkers, lisinsje-útjouwers, en distributeurs, ûntkenne alle garânsjes, ekspres of mei opsetsin, ynklusyf sûnder beheining, garânsjes dat de Tsjinsten ferhannelber binne en oerienkomme mei jo spesifike doel.  Jo drage it folsleine risiko foar it selektearjen fan de Tsjinsten foar jo doel en foar de kwaliteit en prestaasje fan de Tsjinsten. Guon jurisdiksjes stean útsluting, beheining of ymplisite garânsjes net ta, dus dizze disclaimer kin foar jo net fan tapassing wêze.</strong>
rights-webservices-term-5 = <strong>Utsein as ferplicht troch de wet, { -vendor-short-name }, syn meiwurkers, lisinsje-útjouwers, en distributeurs sille net oanspraaklik wêze foar elke yndirekte, spesjale, ynsidintele, konsekwinsjele, bestraffende, of eksimplaryske skansearring as gefolch fan of op ien oft oare manier relatearre ta it gebrûk fan { -brand-short-name } en de Tsjinsten.  De kollektive oanspraaklikheid ûnder dizze betingsten sille net heger wurde as $500 (fiifhûndert dollar). Guon jurisdiksjes stean útsluting, beheining of ymplisite garânsjes net ta, dus dizze disclaimer kin foar jo net fan tapassing wêze.</strong>
