# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Emoñepyrũ tembiapo ñongatupyre
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Emonguatia URL
    .accesskey = y
launch-site-url-cmd =
    .label = Eike URL pe
    .accesskey = V
copy-username-cmd =
    .label = Puruhára réra mbohasarã
    .accesskey = U
edit-username-cmd =
    .label = Puruhára réra mbosako'i
    .accesskey = d
copy-password-cmd =
    .label = Ñe'ẽñemi mbohasarã
    .accesskey = C
edit-password-cmd =
    .label = Ñe'ẽñemi mbosako'i
    .accesskey = E
search-filter =
    .accesskey = H
    .placeholder = Heka
column-heading-site =
    .label = Tenda
column-heading-username =
    .label = Puruhára réra
column-heading-password =
    .label = Ñe'ẽñemi
column-heading-time-created =
    .label = Ojepuru pyahúva
column-heading-time-last-used =
    .label = Ojepurúva ipahaitépe
column-heading-time-password-changed =
    .label = Moambuepyre ipaháva
column-heading-times-used =
    .label = Mboyjeýpa ojepuru
remove =
    .label = Mboguete
    .accesskey = R
import =
    .label = Mba'egueru…
    .accesskey = I
close-button =
    .label = Mboty
    .accesskey = C
show-passwords =
    .label = Ñe'ẽñemi jehechauka
    .accesskey = P
hide-passwords =
    .label = Ñe'ẽñemi moñemi
    .accesskey = P
logins-description-all = Tembiapo ñepyrũ heta tendápe g̃uarã oñemboheta ne mohendahápe
logins-description-filtered = Tembiapo ñepyrũ ojogueraha nde jehekaha ndive:
remove-all =
    .label = Emboguepaite
    .accesskey = A
remove-all-shown =
    .label = Emboguete umi jehechapyréva
    .accesskey = A
remove-all-passwords-prompt = Emboguepasépa opaite ñe'ẽñemikuéra
remove-all-passwords-title = Emboguepa opaite ñe'ẽñemikuéra
no-master-password-prompt = Ehechaukasépa neñe'ẽñemikuéra
auto-fill-logins-and-passwords =
    .label = Tembiapo ñepyrũ ha ñe’ẽñemi myanehẽjehegui
