# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Notice: If you're updating this list, you should also
###         update the list in mozIntl.js.

region-name-ad = అండోరా
region-name-ae = యునైటెడ్ అరబ్ ఎమిరేట్స్
region-name-af = అఫ్ఘనిస్థాన్
region-name-ag = ఐంటిగ్వా మరియు బార్బుడా
region-name-ai = అంగుల్లా
region-name-al = అల్బేనియా
region-name-am = ఆర్మేనియా
region-name-ao = అంగోలా
region-name-aq = అంటార్కిటికా
region-name-ar = అర్జెంటినా
region-name-at = ఆస్ట్రియా
region-name-au = ఆస్ట్రేలియా
region-name-aw = అరుబా
region-name-ba = బోస్నియా మరియు హర్జేగోవినా
region-name-be = బెల్జియమ్
region-name-bg = బల్గేరియా
region-name-bh = బహ్రెయిన్
region-name-bi = బురుండి
region-name-bj = బెనిన్
region-name-bl = సెయింట్ బర్తెలెమీ
region-name-bm = బెర్ముడా
region-name-bn = బ్రుూనై
region-name-br = బ్రెజిల్
region-name-bs = బహమాస్
region-name-bt = భూటాన్
region-name-bv = బావెట్ దీవులు
region-name-bw = బోత్స్వానా
region-name-by = బెలారస్
region-name-bz = బెలైజ్
region-name-ca = కెనడా
region-name-cc = కోకోస్ (కీలింగ్) దీవులు
region-name-cd = కాంగో (కిన్‌షాస)
region-name-cf = మధ్య ఆఫ్రికన్ రిపబ్లిక్
region-name-cg = కాంగో (బ్రెజ్‌విల్లీ)
region-name-ck = కుక్ దీవులు
region-name-cm = కామెరూన్
region-name-cn = చైనా
region-name-co = కొలంబియా
region-name-cp = క్లిపర్టన్ ద్వీపం
region-name-cr = కోస్టా రికా
region-name-cu = క్యూబా
region-name-cw = కురాకో
region-name-cx = క్రిస్మస్ ద్విపం
region-name-cy = సైప్రస్
region-name-cz = చెక్ రిపబ్లిక్
region-name-de = జర్మనీ
region-name-dg = డియాగొ గార్సియా
region-name-dj = జిబౌటి
region-name-dk = డెన్మార్క్
region-name-dm = డోమినికా
region-name-do = డొమినికన్ రిపబ్లిక్
region-name-dz = అల్జేరియా
region-name-ec = ఈక్వడార్
region-name-ee = ఏస్తోనియా
region-name-eg = ఈజిప్ట్
region-name-er = ఇరిట్రే
region-name-es = స్పెయిన్
region-name-et = ఎథియోపియా
region-name-fi = ఫిన్లాండ్
region-name-fk = ఫాక్‌లాండ్ దీవులు (ఇస్లాస్ మాల్వినాస్)
region-name-fr = ఫ్రాన్స్
region-name-gb = యునైటెడ్ కింగ్డమ్
region-name-gd = గ్రేనాడా
region-name-ge = జార్జియా
region-name-gg = గ్విర్నసే
region-name-gh = ఘనా
region-name-gl = గ్రీన్‌లాండ్
region-name-gm = గాంబియా
region-name-gp = గ్వాడేలోప్
region-name-gr = గ్రీస్
region-name-gs = దక్షిణ జార్జియా మరియు దక్షిణ సాండ్విచ్ దీవులు
region-name-gu = గువామ్
region-name-hn = హాండురస్
region-name-ht = హైతీ
region-name-hu = హంగరీ
region-name-id = ఇండోనేషియా
region-name-ie = ఐర్లాండ్
region-name-io = హిందూ మహాసముద్ర బ్రిటిష్ ప్రాంతం
region-name-iq = ఇరాక్
region-name-ir = ఇరాన్
region-name-it = ఇటలీ
region-name-jm = జమైకా
region-name-jo = జోర్డాన్
region-name-jp = జపాన్
region-name-ke = కెన్యా
region-name-kg = కిర్గిస్తాన్
region-name-kh = కాంబోడియా
region-name-ki = కిరీబాటీ
region-name-km = కొమరోస్
region-name-kp = ఉత్తర కొరియా
region-name-kr = దక్షిణ కొరియా
region-name-kw = కువైట్
region-name-ky = కేమన్ దీవులు
region-name-kz = కజకిస్తాన్
region-name-la = లావోస్
region-name-lb = లెబనాన్
region-name-li = లైచెన్‌స్టయిన్
region-name-ls = లెసోతో
region-name-lu = లగ్జెంబర్గ్
region-name-lv = లాట్వియా
region-name-ly = లిబియా
region-name-ma = మొరాకో
region-name-mc = మొనాకో
region-name-md = మాల్డోవా
region-name-me = మౌంటెనీగ్రో
region-name-mf = సెయింట్ మార్టీన్
region-name-mg = మడగాస్కర్
region-name-mh = మార్షల్ దీవులు
region-name-mk = మాసిడోనియా
region-name-ml = మాలి
region-name-mm = బర్మా
region-name-mn = మంగోలియా
region-name-mo = మకావ్
region-name-mq = మార్టినిక్
region-name-mr = మౌరిషానియా
region-name-ms = మాంట్‌సెరాట్
region-name-mt = మాల్టా
region-name-mu = మారిషస్
region-name-mw = మలావి
region-name-mx = మెక్సికో
region-name-my = మలేషియా
region-name-mz = మొజాంబిక్
region-name-na = నమీబియా
region-name-nc = న్యూ కాలిడోనియా
region-name-ne = నైజెర్
region-name-nf = నార్ఫొక్ ద్విపం
region-name-ng = నైజీరియా
region-name-ni = నికారాగ్వా
region-name-no = నార్వే
region-name-np = నేపాల్
region-name-nr = నౌరు
region-name-nu = నియూ
region-name-nz = న్యూజిలాండ్
region-name-om = ఓమన్
region-name-pa = పనామా
region-name-pe = పెరూ
region-name-pf = ఫ్రెంచి పాలినెషియా
region-name-pk = పాకిస్థాన్
region-name-pl = పోలాండ్
region-name-pn = పిట్కారియన్ దీవులు
region-name-pt = పోర్చుగల్
region-name-py = పరాగ్వే
region-name-qs = బస్సాస్ డా భారతదేశం
region-name-qu = జువాన్ డి నోవా ద్వీపం
region-name-qw = వేక్ ద్వీపం
region-name-qx = గ్లోరియోసో దీవులు
region-name-qz = ఏక్రోతిరీ
region-name-re = రియూనియన్
region-name-ro = రోమేనియా
region-name-rs = సెర్బియా
region-name-ru = రష్యా
region-name-rw = రువాండా
region-name-sa = సౌదీ అరేబియా
region-name-sb = సాలోమన్ దీవులు
region-name-sd = సుడాన్
region-name-se = స్వీడన్
region-name-sg = సింగపూర్
region-name-sh = సెయింట్ హెలెనా, అసెన్సన్ మరియు ట్రిస్టాన్ డా కున్హా
region-name-si = స్లోవేనియా
region-name-sm = సాన్ మారినో
region-name-sn = సెనెగల్
region-name-so = సోమాలియా
region-name-sr = సురినేమ్
region-name-ss = దక్షిణ సుడాన్
region-name-sx = సింట్ మార్టెన్
region-name-sy = సిరియా
region-name-sz = స్వాజీలాండ్
region-name-tc = టర్కస్ మరియు కైకోస్ దీవులు
region-name-td = చాడ్
region-name-tf = ఫ్రెంచ్ సదరన్ మరియు అంటార్కటిక్ లాండ్స్
region-name-tg = టోగో
region-name-th = థాయ్‌లాండ్
region-name-tj = తజికిస్తాన్
region-name-tk = టొకెలౌ
region-name-tl = టైమర్-లెస్టి
region-name-tm = టర్కమెనిస్తాన్
region-name-tn = టునీషియా
region-name-to = టోంగా
region-name-tr = టర్కీ
region-name-tv = తువాలు
region-name-tw = తైవాన్
region-name-tz = టాంజానియా
region-name-ua = ఉక్రెయిన్
region-name-ug = ఉగాండా
region-name-us = యునైటెడ్ స్టేట్స్
region-name-uz = ఉజ్బెకిస్తాన్
region-name-va = వాటికన్ నగరం
region-name-vg = బ్రిటిష్ వర్జిన్ దీవులు
region-name-vi = వర్జిన్ ఐలాండ్స్, U.S.
region-name-vn = వియత్నాం
region-name-vu = వనౌతు
region-name-wf = వాలిస్ మరియు పుటునా
region-name-ws = సమోవా
region-name-xa = ఆష్మోర్ మరియు కార్టియర్ దీవులు
region-name-xb = బేకర్ ద్వీపం
region-name-xc = కోరల్ సీ దీవులు
region-name-xd = ధెకెలియా
region-name-xe = ఐరోపా దీవి
region-name-xh = హౌలాండ్ ద్వీపం
region-name-xj = జాన్ మయెన్
region-name-xk = కొసావో
region-name-xm = కింగ్‌మాన్ రీఫ్
region-name-xp = పారసెల్ దీవులు
region-name-xq = జార్విస్ దీవి
region-name-xs = స్ప్రాట్లీ దీవులు
region-name-xt = ట్రోమెలిన్ ద్వీపం
region-name-xu = జాన్‌స్టన్ అటోల్
region-name-xv = నవాసా ద్వీపం
region-name-xw = పశ్చిమ ఒడ్డు
region-name-ye = యెమన్
region-name-za = దక్షిణ ఆఫ్రికా
region-name-zm = జాంబియా
