# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE (frame.unknownSource): When we do not know the source filename of
# a frame, we use this string instead.
frame.unknownSource = (nezināms)
# LOCALIZATION NOTE (frame.viewsourceindebugger): The label for the tooltip when hovering over
# a source link that links to the debugger.
# %S represents the URL to match in the debugger.
frame.viewsourceindebugger = Aplūkot kodu atkļūdotājā → %S
# LOCALIZATION NOTE (notificationBox.closeTooltip): The content of a tooltip that
# appears when hovering over the close button in a notification box.
notificationBox.closeTooltip = Aizvērt šo paziņojumu
# LOCALIZATION NOTE (editor.noResultsFound): Editor Search bar message
# for when no results found.
editor.noResultsFound = Nekas netika atrasts
# LOCALIZATION NOTE (editor.searchResults.close): Editor Search bar
# tooltip for closing the search bar.
editor.searchResults.close = Aizvērt meklēšanu
# LOCALIZATION NOTE (splitter.label): The accessible label of the bar which
# separates the two panels of a split view. It can be moved with the arrow keys
# to give more room to either panel.
splitter.label = Mainīt paneļu izmēru
