# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE (dom.filterDOMPanel): A placeholder text used for
# DOM panel search box.
dom.filterDOMPanel = Atsijāt DOM panelī
# LOCALIZATION NOTE (dom.refresh): A label for Refresh button in
# DOM panel toolbar
dom.refresh = Atjaunināt
