# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loginsDescriptionAll2 = ເຂົ້າສູ່ລະບົບສໍາລັບການຕິດຕາມເວັບໄຊຕ໌ແມ່ນຖືກຈັດເກັບໄວ້ໃນຄອມພິວເຕີຂອງທ່ານ
# LOCALIZATION NOTE (loginHostAge):
# This is used to show the context menu login items with their age.
# 1st string is the username for the login, 2nd is the login's age.
loginHostAge = ​%1$S %2$S
# LOCALIZATION NOTE (noUsername):
# String is used on the context menu when a login doesn't have a username.
noUsername = ບໍ່ມີຊື່ຜູ້ໃຊ້
# LOCALIZATION NOTE (insecureFieldWarningDescription2):
# %1$S will contain insecureFieldWarningLearnMore and look like a link to indicate that clicking will open a tab with support information.
insecureFieldWarningDescription2 = ການເຊື່ອມຕໍນີ້ບໍ່ມີຄວາມປອດໄພ. ການປ້ອນຂໍ້ມູນການລັອກອິນໃສ່ນີ້ອາດຈະຖືກບຸກລຸກໄດ້. %1$S
insecureFieldWarningLearnMore = ຮຽນຮູ້ເພີ່ມເຕີມ
