# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=Nzudzanyo ya $ProductName$
Welcome_MessageWelcome=No ṱanganedzwa kha %s!
Welcome_Message0=You are about to install %s 2 Alpha 1.
Welcome_Message1=Zwi khou tsivhudzwa tshoṱhe uri ni bve kha mbekanyamushumo dza Windows dzothe musi ni saathu u shumisa hei mbekanyamushumo ya Nzudzanyo.
Welcome_Message2=Kiḽikani Fhelisa u itela u bva kha Nzudzanyo u bva afho ni vale mbekanyamushumo ine na khou i shumisa.  Kiḽikani zwi Tevhelaho u bvela phanḓa na Nzudzanyo ya mbekanyamushumo.
Welcome_Message3=Click Next to continue installing %s 2 Alpha 1.

License_Title=Thendelano ya Ḽaisentsi ya Sofuthiwee
License_SubTitle=Milayo na nyimele dza u shumisa hei sofuthiwee.
License_Message0=Ni khou humbelwa uri ni vhale hei thendelano ya ḽaisentsi i tevhelaho. Shumisani baa ya u sikiroḽa u itela u vhona hei thendelano yoṱhe.
License_Accept=Ndi a &Tanganedza milayo ya hei Thendelano ya Laisentsi
License_Decline=A &THI ṱanganedzi milayo ya hei Thendelano ya Ḽaisentsi

Type_Title=Lushaka lwa Nzudzanyo
Type_SubTitle=Nangani khetho dza nzudzanyo.
Type_Message0=Nangani lwa Nzudzanyo lune na lu takalela, u bva afho ni kiḽike zwi Tevhelaho.

Standard_Short=&Yo Ḓoweleaho
Standard_Long=Thunderbird tshi ḓo longelwa na khetho dzo ḓoweleaho tshoṱhe.

Custom_Short=&Mvelele
Custom_Long=Ni nga nanga khetho dzaṅu inwi muṅwe uri dzi dzhenisiwe. Yo themendelwa uri i shumiswe nga vhashumisi vha re na ndalukanyo.

Select_Title=Zwipiḓa zwo Nangiwaho
Select_SubTitle=Zwipiḓa zwiṅwe hafhu zwi khwaṱhisedzaho $ProductName$.
Select_Message0=Nangani zwiṅwe zwipiḓa hafhu zwine na khou ṱoḓa u zwi dzhenisa, u bva afho ni kiḽike zwi Tevhelaho.

Path_Title=Dzhenisani Foḽuda
Path_SubTitle=Hune $ProductName$ ḽa ḓo longelwa.
Path_Message0=$ProductName$ ḽi ḓo longelwa kha foḽuda i tevhelaho:

Integration_Title=Zwikhau zwa u Dzudzanya
Integration_SubTitle=Vhumbani Zwiga zwa Mbekanyamushumo
Integration_Message0=Vhumbani zwiga zwa $ProductShortName$:

Integration_Desktop=Kha Desikethopho yanga
Integration_StartMenu=Kha foḽuda yanga ya Mbekanyamushumo dza Menu wa u Thoma
Integration_QuickLaunch=Kha buḽoko yanga ya u ḽontsha nga u ṱavhanya

SelectFolder_Title=Nzudzanyo ya $ProductName$ - yo Nanga Foḽuda ya Mbekanyamushumo
SelectFolder_Message0=Nzudzanyo i ḓo engedza zwiga zwa mbekanyamushumo kha Foḽuda ya Mbekanyamushumo yo bulwaho afho fhasi.  Ni nga kha ḓi thaipha foḽuda ntswa u bva kha mutevhe wa Foḽuda ure Hone.  Kilikani zwi tevhelaho u bvela phanda.

Advanced_Title=Nzudzanyo ya $ProductName$ - Mbekanyo dzo Bvelelaho
Advanced_Message0=Arali ṱhumanyo ya inthanete yaṅu itshi ṱoḓa seva thusedzi, dzhenisani dzina ḽaṅu ḽa seva vhuṱanzi ha fhethu.  Arali thumanyo ya inthanete yaṅu isa ṱoḓa seva thusedzi, litshani mabuḓo a sina tshithu.

Install_Title=Manweledzo
Install_SubTitle=Yo ḓi imisela u longela $ProductName$.
Install_MessageInstall=Nzudzanyo zwino i ḓo dzhenisa zwipiḓa zwi tevhelaho:
Install_MessageDownload=Nzudzanyo zwino i ḓo dzhenisa na u longela zwipiḓa zwi tevhelaho:
Install_Message0=Kiḽikani zwi Tevhelaho u itela u bvela phanḓa.

Downloading_Title=I khou Dzhenisa
Downloading_SubTitle=I khou dzhenisa zwipiḓa zwine zwa khou ṱoḓea...
Downloading_Blurb=Nzudzanyo i khou longela faela dzine dza khou ṱoḓea u itela u longela $ProductName$.
Downloading_FileName=I khou Dzhenisa Zwino:
Downloading_Time=Tshifhinga tsho Salaho:

Installing_Title=I khou longela
Installing_SubTitle=Longelani $ProductName$...
Installing_Blurb=Nzudzanyo i khou longela faela dza khumbelo.
Installing_Status=I khou Lugisa Faela:
Installing_Component=I khou Longela Zwino:

Success_Title=U Longela ho Fhela
Success_Header=U Longela ho Fhela
Success_Message0=%s was successfully installed.
Success_Message1=Kiḽikani Fhedza u fhedzisa Nzudzanyo.
Success_Launch=Launch %s now.

Check_Message=U longelwa ha $ProductName$ ho tshimbila zwavhuḓi. $ProductNameInternal$ ḽi tea u valiwa u itela u bvela phanḓa na u longela. Kiḽikani Zwo Luga u itela u bva kha $ProductNameInternal$ nga noṱhe na u thoma u longela.
Check_FullMessage=$ProductNameInternal$ i tea u valiwa u itela u bvela phanḓa na u longela. Kiḽikani Zwo Luga u itela u bva kha $ProductNameInternal$ nga yoṱhe nahone ni mbo ḓi thoma u longela.
Check_Wait=I khou vala $ProductNameInternal$.  Ni khou humbelwa zwauri ni lindele...

Component_XPCOM=Fhambana-Tshiteidzhi COM
Component_Mail=$ProductName$
Component_Offline=Thikhedzo ire Nnḓa ha Ḽaini
Component_Offline_Long=Engedza thikhedzo ya Nnḓa ha Ḽaini kha Meiḽi wa $ProductName$.
Component_RSS=Thikhedzo ya RSS
Component_RSS_Long=Engedza thikhedzo ya RSS kha $ProductName$.
Component_QFA=Zhendedzi ḽa Mawanwa a Ndeme
Component_QFA_Long=ya u vhiga vhuṱanzi ha u thutha ha $ProductName$
