# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Chcete dôverovať “%S” pre nasledujúce účely:
unnamedCA = Certifikačná autorita (bez názvu)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Zadajte heslo, ktorým bola zašifrovaná táto záloha certifikátov:
# Page Info
pageInfo_NoEncryption = Pripojenie nie je šifrované
pageInfo_Privacy_None1 = Server %S nepodporuje šifrovanie pre stránku, ktorú práve čítate.
pageInfo_Privacy_None2 = Informácie odoslané cez internet bez zašifrovania môžu byť počas cesty pozorované inými ľuďmi.
pageInfo_Privacy_None4 = Zobrazená stránka nebola zašifrovaná predtým, ako bola odoslaná cez internet.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Pripojenie je šifrované (%1$S, %2$S bitové kľúče, %3$S)
pageInfo_BrokenEncryption = Prelomené šifrovanie (%1$S, %2$S bitové kľúče, %3$S)
pageInfo_Privacy_Encrypted1 = Stránka, ktorú čítate, bola zašifrovaná predtým, ako bola odoslaná cez internet.
pageInfo_Privacy_Encrypted2 = Vďaka zašifrovaniu je pre neautorizovaných ľudí ťažké vidieť informácie, putujúce medzi dvoma počítačmi. Je preto nepravdepodobné, že by niekto prečítal túto stránku počas jej cesty po internete.
pageInfo_MixedContent = Pripojenie je čiastočne šifrované
pageInfo_MixedContent2 = Časť práve prehliadanej stránky nebola zašifrovaná predtým, ako bola odoslaná cez internet.
pageInfo_WeakCipher = Pripojenie k tejto webovej stránke používa slabé zabezpečenie a nie je súkromné. Iní ľudia môžu zobraziť vaše údaje alebo zmeniť správanie stránky.
pageInfo_CertificateTransparency_Compliant = Táto webová stránka je v súlade s Certificate Transparency.
# Token Manager
password_not_set = (nie je zadané)
