# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = ନିମ୍ନଲିଖିତ ଉଦ୍ଦେଶ୍ୟଗୁଡ଼ିକ ପାଇଁ କଣ ଆପଣ "%S"ଉପରେ ବିଶ୍ୱାସ କରିବାକୁ ଚାହୁଁଛନ୍ତି?
unnamedCA = ପ୍ରମାଣପତ୍ର ଅଧିକାରୀ (ବେନାମୀ)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = ଏହି ସାର୍ଟିଫିକେଟର ବ୍ୟାକଅପ ଗୋପନ (ଏନକ୍ରିପ୍ଟ) କରିବାରେ ବ୍ୟବହୃତ ପାସୱାର୍ଡ଼ ଦିଅନ୍ତୁ:
# Page Info
pageInfo_NoEncryption = ସଂଯୋଗଟି ସଂଗୁପ୍ତ ନୁହଁ
pageInfo_Privacy_None1 = ଆପଣ ଦେଖୁଥିବା ପୃଷ୍ଠା ପାଇଁ ସଂଗୁପ୍ତକୁ ୱେବ ସାଇଟ %S ସମର୍ଥନ କରେ ନାହିଁ.
pageInfo_Privacy_None2 = ଇଣ୍ଟରନେଟରେ ସଂଗୁପ୍ତ ବିନା ପଠାଯାଇଥିବା ସୂଚନାକୁ ଗତିକରୁଥିବା ସମୟରେ ଅନ୍ୟବ୍ୟକ୍ତି ଦେଖିପାରିବେ.\u0020
pageInfo_Privacy_None4 = ଆପଣ ଦେଖୁଥିବା ପୃଷ୍ଠାଟି ଇଣ୍ଟରନେଟରେ ଛଡ଼ାହେବା ଆଗରୁ ଗୋପନ (ଏନକ୍ରିପ୍ଟ) କରାଯାଇନଥିଲା ।
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = ସଂଯୋଗ ଗୋପନ (ଏନକ୍ରିପ୍ଟ) କରାଗଲା (%1$S, %2$S ବିଟ କି, %3$S)
pageInfo_BrokenEncryption = ଭଙ୍ଗା ଏନକ୍ରିପସନ (%1$S, %2$S ବିଟ କି, %3$S)
pageInfo_Privacy_Encrypted1 = ଆପଣ ଦେଖୁଥିବା ପୃଷ୍ଠାଟି ଇଣ୍ଟରନେଟରେ ପ୍ରସାରଣ ହେବା ପୂର୍ବରୁ ସଂଗୁପ୍ତ କରାଯାଇଥିଲା.
pageInfo_Privacy_Encrypted2 = ଏନକ୍ରିପସନ କମ୍ପୁଟରଗୁଡ଼ିକ ମଧ୍ୟରେ ଯାଉଥିବା ସୂଚନାକୁ ଅନୁମୋଦନ ପାଇନଥିବା ଲୋକଙ୍କ ପାଇଁ ଦେଖିବା କଠିନ କରିଦେଇଥାଏ । ସେଥିପାଇଁ ଏହା ନେଟୱାର୍କ ଭିତରେ ଯାଉଥିବା ବେଳେ କୌଣସି ଲୋକ ଏହାକୁ ପଢ଼ିବାର ସମ୍ଭାବନା ନଥାଏ ।
pageInfo_MixedContent = ସଂଯୋଗଟି ଆଂଶିକ ସଂଗୁପ୍ତ ଅଟେ
pageInfo_MixedContent2 = ଆପଣ ଦେଖୁଥିବା ପୃଷ୍ଠାର ଅଂଶଟି ଇଣ୍ଟରନେଟରେ ସଞ୍ଚାର କରିବା ପୂର୍ବରୁ ସଂଗୁପ୍ତ ହୋଇନାହିଁ.
pageInfo_WeakCipher = ଏହି ୱେବସାଇଟ ସହ ଆପଣଙ୍କ ସଂଯୋଗ ଦୁର୍ବଳ ଏନକ୍ରିପସନ ବ୍ୟବହାର କରେ ଓ ତାହା ଗୋପନୀୟ ନୁହେଁ । ଅନ୍ୟ ଲୋକେ ଆପଣଙ୍କ ତଥ୍ୟ ଦେଖିପାରିବେ ଓ ୱେବସାଇଟର ବ୍ୟବହାର ବଦଳାଇପାରିବେ ।
# Token Manager
password_not_set = (ବିନ୍ୟାସିତ ନୁହଁ)
