# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Wilt u ‘%S’ vertrouwen voor de volgende doeleinden?
unnamedCA = Certificaatautoriteit (naamloos)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Voer het wachtwoord in dat bij het versleutelen van de reservekopie van dit certificaat is gebruikt:
# Page Info
pageInfo_NoEncryption = Niet-versleutelde verbinding
pageInfo_Privacy_None1 = De website %S ondersteunt geen versleuteling voor de pagina die u bekijkt.
pageInfo_Privacy_None2 = Gegevens die zonder versleuteling over het internet worden verzonden, kunnen onderweg door anderen worden ingezien.
pageInfo_Privacy_None4 = De pagina die u bekijkt was niet versleuteld voordat deze over het internet werd verzonden.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Versleutelde verbinding (%1$S, %2$S-bits sleutels, %3$S)
pageInfo_BrokenEncryption = Onbetrouwbare versleuteling (%1$S, %2$S-bits sleutels, %3$S)
pageInfo_Privacy_Encrypted1 = De pagina die u bekijkt is versleuteld voordat deze over het internet werd verzonden.
pageInfo_Privacy_Encrypted2 = Versleuteling maakt het moeilijk voor onbevoegde personen om gegevens te bekijken die tussen computers worden uitgewisseld. Het is daarom onwaarschijnlijk dat iemand deze pagina heeft gelezen terwijl hij over het netwerk werd verzonden.
pageInfo_MixedContent = Gedeeltelijk versleutelde verbinding
pageInfo_MixedContent2 = Delen van de pagina die u bekijkt waren niet versleuteld voordat ze over het internet werden verzonden.
pageInfo_WeakCipher = Uw verbinding met deze website gebruikt een zwakke versleuteling en is niet privé. Andere personen kunnen uw gegevens bekijken of het gedrag van de website aanpassen.
pageInfo_CertificateTransparency_Compliant = Deze website voldoet aan het beleid voor Certificaattransparantie.
# Token Manager
password_not_set = (niet ingesteld)
