# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Chirchende { $host }…
network-connection-status-connected = Connètidu a { $host }…
network-connection-status-sending-request = Imbiende sa rechesta a { $host }…
network-connection-status-transferring-data = Trasferende datos dae { $host }…
network-connection-status-connecting = Connetende a { $host }…
network-connection-status-read = Letura de { $host }
network-connection-status-wrote = Iscritura de { $host }
network-connection-status-waiting = Abetende a { $host }…
network-connection-status-looked-up = Chirca de { $host }…
network-connection-status-tls-handshake = Creende una connessione TLS cun { $host }…
network-connection-status-tls-handshake-finished = Cumpletada sa connessione TLS cun { $host }…
