# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dateformat-label =
    .value = Format de la date :
    .accesskey = F
#   $date (String) - the formatted example date
dateformat-long =
    .label = Long : { $date }
#   $date (String) - the formatted example date
dateformat-short =
    .label = Court : { $date }
weekstart-label =
    .value = Premier jour de la semaine :
    .accesskey = P
day-1-name =
    .label = Dimanche
day-2-name =
    .label = Lundi
day-3-name =
    .label = Mardi
day-4-name =
    .label = Mercredi
day-5-name =
    .label = Jeudi
day-6-name =
    .label = Vendredi
day-7-name =
    .label = Samedi
day-1-checkbox =
    .label = Dim
    .accesskey = D
day-2-checkbox =
    .label = Lun
    .accesskey = L
day-3-checkbox =
    .label = Mar
    .accesskey = M
day-4-checkbox =
    .label = Mer
    .accesskey = e
day-5-checkbox =
    .label = Jeu
    .accesskey = J
day-6-checkbox =
    .label = Ven
    .accesskey = V
day-7-checkbox =
    .label = Sam
    .accesskey = S
dayweek-legend = Vues quotidienne et hebdomadaire
visible-hours-label =
    .value = Afficher :
    .accesskey = h
visible-hours-end-label =
    .value = heures à la fois
day-start-label =
    .value = La journée commence à :
    .accesskey = c
day-end-label =
    .value = La journée se termine à :
    .accesskey = u
midnight-label =
    .label = Minuit
noon-label =
    .label = Midi
multiweek-legend = Vue multisemaine
number-of-weeks-label =
    .value = Nombre total de semaines par défaut :
    .accesskey = N
week-0-label =
    .label = Aucune
week-1-label =
    .label = 1 semaine
week-2-label =
    .label = 2 semaines
week-3-label =
    .label = 3 semaines
week-4-label =
    .label = 4 semaines
week-5-label =
    .label = 5 semaines
week-6-label =
    .label = 6 semaines
previous-weeks-label =
    .value = Nombre de semaines passées :
    .accesskey = o
reminder-legend = Quand survient une alarme :
reminder-play-checkbox =
    .label = Jouer un son
    .accesskey = J
reminder-default-sound-label =
    .label = Utiliser le son par défaut
    .accesskey = U
reminder-browse-sound-label =
    .label = Parcourir…
    .accesskey = P
alarm-on-label =
    .label = Activée
alarm-off-label =
    .label = Désactivée
category-edit-label = Modifier la catégorie
category-overwrite-title = Attention : nom en double
category-overwrite = Une catégorie portant le même nom existe déjà. Voulez-vous la remplacer ?
category-blank-warning = Vous devez saisir un nom de catégorie.
