# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Notice: If you're updating this list, you should also
###         update the list in mozIntl.js.

region-name-ad = Andorra
region-name-ae = U.A.E.
region-name-ag = Antigua y Barbuda
region-name-ai = Anguilla
region-name-al = Albania
region-name-am = Armenia
region-name-ao = Angola
region-name-ar = Argentina
region-name-as = Samoa Americana
region-name-at = Austria
region-name-au = Australia
region-name-aw = Aruba
region-name-az = Azerbaijan
region-name-ba = Bosnia Herzegovina
region-name-bb = Barbados
region-name-bd = Bangladesh
region-name-bf = Burkina Faso
region-name-bg = Bulgaria
region-name-bh = Bahrein
region-name-bi = Burundi
region-name-bj = Benin
region-name-bm = Bermuda
region-name-bn = Brunei Darussalam
region-name-bo = Bolivia
region-name-br = Brasil
region-name-bs = Bahamas
region-name-bt = Bhutan
region-name-bv = Isla Bouvet
region-name-bw = Botswana
region-name-by = Bielorrusia
region-name-bz = Belice
region-name-cc = Islas Cocos (Keeling)
region-name-cd = Congo-Kinshasa
region-name-cg = Congo-Brazzaville
region-name-ch = Suiza
region-name-ci = Costa de Marfil
region-name-ck = Islas Cook
region-name-cl = Chile
region-name-cn = China
region-name-co = Colombia
region-name-cr = Costa Rica
region-name-cu = Cuba
region-name-cv = Cabo Verde
region-name-cx = Isla Navidad
region-name-cy = Chipre
region-name-de = Alemania
region-name-dj = Djibouti
region-name-dk = Dinamarca
region-name-dm = Dominica
region-name-dz = Argelia
region-name-ec = Ecuador
region-name-ee = Estonia
region-name-eg = Egipto
region-name-eh = Sahara Occidental
region-name-er = Eritrea
region-name-fi = Finlandia
region-name-fj = Fiji
region-name-fk = Islas Malvinas
region-name-fm = Micronesia
region-name-fo = Islas Faroe
region-name-fr = Francia
region-name-gb = Reino Unido
region-name-gd = Granada
region-name-ge = Georgia
region-name-gf = Guayana Francesa
region-name-gg = Guernsey
region-name-gh = Ghana
region-name-gi = Gibraltar
region-name-gl = Groenlandia
region-name-gm = Gambia
region-name-gn = Guinea
region-name-gp = Guadalupe
region-name-gq = Guinea Ecuatorial
region-name-gr = Grecia
region-name-gs = Islas Georgia y Sandwich del Sur
region-name-gt = Guatemala
region-name-gu = Guam
region-name-gw = Guinea-Bissau
region-name-gy = Guyana
region-name-hk = Hong Kong
region-name-hn = Honduras
region-name-hr = Croacia
region-name-id = Indonesia
region-name-ie = Irlanda
region-name-il = Israel
region-name-in = India
region-name-iq = Irak
region-name-is = Islandia
region-name-it = Italia
region-name-je = Jersey
region-name-jm = Jamaica
region-name-jo = Jordania
region-name-ke = Kenia
region-name-kg = Kyrgyzstan
region-name-kh = Camboya
region-name-ki = Kiribati
region-name-km = Comoros
region-name-kp = Corea del Norte
region-name-kr = Corea del Sur
region-name-kw = Kuwait
region-name-kz = Kazakhstan
region-name-la = Laos
region-name-li = Liechtenstein
region-name-lk = Sri Lanka
region-name-lr = Liberia
region-name-ls = Lesotho
region-name-lt = Lituania
region-name-lu = Luxemburgo
region-name-lv = Letonia
region-name-ly = Libia
region-name-ma = Marruecos
region-name-md = Moldova
region-name-mg = Madagascar
region-name-mh = Islas Marshall
region-name-ml = Mali
region-name-mm = Myanmar
region-name-mn = Mongolia
region-name-mo = Macao
region-name-mq = Martinica
region-name-mr = Mauritania
region-name-ms = Montserrat
region-name-mt = Malta
region-name-mu = Mauricio
region-name-mv = Maldivas
region-name-mw = Malawi
region-name-my = Malasia
region-name-mz = Mozambique
region-name-na = Namibia
region-name-nc = Nueva Caledonia
region-name-nf = Isla Norfolk
region-name-ng = Nigeria
region-name-ni = Nicaragua
region-name-nl = Holanda
region-name-no = Noruega
region-name-np = Nepal
region-name-nr = Nauru
region-name-nu = Niue
region-name-nz = Nuev Zelanda
region-name-om = Oman
region-name-pf = Polinesia Francesa
region-name-ph = Filipinas
region-name-pl = Polonia
region-name-pm = San Pedro y Miquelon
region-name-pn = Pitcairn
region-name-pr = Puerto Rico
region-name-pt = Portugal
region-name-pw = Palau
region-name-py = Paraguay
region-name-qa = Qatar
region-name-re = Reunion
region-name-ro = Rumania
region-name-sa = Arabia Saudita
region-name-sb = Islas Solomon
region-name-sc = Seychelles
region-name-se = Suecia
region-name-sg = Singapur
region-name-sh = Santa Helena
region-name-si = Eslovenia
region-name-sk = Eslovaquia
region-name-sl = Sierra Leona
region-name-sm = San Marino
region-name-sn = Senegal
region-name-sr = Surinam
region-name-st = Sao Tome y Principe
region-name-sv = El Salvador
region-name-sy = Siria
region-name-sz = Swazilandia
region-name-td = Chad
region-name-tg = Togo
region-name-th = Tailandia
region-name-tj = Tajikistan
region-name-tk = Tokelau
region-name-tl = Timor-Leste
region-name-to = Tonga
region-name-tt = Trinidad y Tobago
region-name-tv = Tuvalu
region-name-tw = Taiwan
region-name-tz = Tanzania
region-name-ua = Ucrania
region-name-ug = Uganda
region-name-us = Estados Unidos
region-name-uy = Uruguay
region-name-uz = Uzbekistan
region-name-va = Vaticano
region-name-ve = Venezuela
region-name-vn = Vietnam
region-name-vu = Vanuatu
region-name-wf = Wallis y Futuna
region-name-ws = Samoa
region-name-ye = Yemen
region-name-yt = Mayotte
region-name-zm = Zambia
region-name-zw = Zimbabwe
