# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Күту уақыты аяқталды
openFile = Файлды ашу
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = %1$S ішінен "%2$S" іздеу
contextMenuSearch.accesskey = з
contextMenuPrivateSearch = Жекелік шолу терезесінде іздеу
contextMenuPrivateSearch.accesskey = ш
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = %S көмегімен жекелік шолу терезесінде іздеу
contextMenuPrivateSearchOtherEngine.accesskey = ш
bookmarkAllTabsDefault = [Бума аты]
unsignedAddonsDisabled.message = Бір немесе бірнеше орнатылған қосымшаны растау мүмкін емес, сондықтан олар сөндіріледі.
unsignedAddonsDisabled.learnMore.label = Көбірек білу
unsignedAddonsDisabled.learnMore.accesskey = К
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Соңғы қатынау %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = %S:// сілтемелері
crashedpluginsMessage.title = %S плагині құлап түсті.
crashedpluginsMessage.reloadButton.label = Парақты қайта жүктеу
crashedpluginsMessage.reloadButton.accesskey = П
crashedpluginsMessage.submitButton.label = Құлау хабарламасын жіберу
crashedpluginsMessage.submitButton.accesskey = е
crashedpluginsMessage.learnMore = Көбірек білу…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = %S адресіне өтуді қаладыңыз ба?
keywordURIFixup.goTo = Иә, %S адресіне өтуді қалаймын
keywordURIFixup.goTo.accesskey = И
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = %S нұсқасына жаңарту
update.downloadAndInstallButton.accesskey = ж
menuOpenAllInTabs.label = Әрқайсысын жаңа бетте ашу
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Бұл бетті қайта жүктеу
tabHistory.goBack = Осы параққа қайту
tabHistory.goForward = Осы параққа өту
# URL Bar
pasteAndGo.label = Кірістіру және өту
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Ағымдағы бетті жаңарту (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Бұл беттің жүктелуін тоқтату (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Масштабты тастау (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Оқу режимін іске қосу/сөндіру (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, Масштабты қалпына келтіру
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Сіздің бетбелгілерді көрсету (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Ағымдағы жүктемелердің орындалуын көрсету (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Жаңа терезені ашу (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Жаңа бетті ашу (%S)
newTabContainer.tooltip = Жаңа бетті ашу (%S)\nЖаңа контейнерлік бетті ашу үшін басып ұстаңыз
newTabAlwaysContainer.tooltip = Жаңа бетті ашу үшін контейнерді таңдаңыз
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = %S үшін сіздің HTML5 canvas-суретін қолдануды рұқсат ету керек пе?
canvas.siteprompt2.warning = Бұл сіздің компьютеріңізді бірегей анықтау үшін пайдаланылуы мүмкін.
canvas.block = Бұғаттау
canvas.block.accesskey = б
canvas.allow2 = Рұқсат ету
canvas.allow2.accesskey = а
canvas.remember2 = Осы таңдауымды есте сақтау
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Расталды: %S
identity.identified.verified_by_you = Осы сайт үшін сіз қауіпсіздік ережелерінен бөлек рұқсат бердіңіз
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Сертификат кімге шығарылған: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Қауіпсіз емес
identity.notSecure.tooltip = Байланыс қауіпсіз емес
identity.extension.label = Кеңейту (%S)
identity.extension.tooltip = Кеңейтумен жүктелген: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Кішірейту (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Масштабты тастау (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Үлкейту (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Қиып алу (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Көшіріп алу (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Кірістіру (%S)
geolocation.allow = Рұқсат ету
geolocation.allow.accesskey = а
geolocation.block = Бұғаттау
geolocation.block.accesskey = б
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Бұл жүйенің орналасу баптауларын ашады. %S үшін орналасуды анықтау рұқсатын беріңіз.
geolocation.shareWithSite4 = %S үшін орналасуыңызға қатынау рұқсат ету керек пе?
geolocation.shareWithFile4 = Бұл жергілікті файл үшін орналасуыңызға қатынауға рұқсат ету керек пе?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = %1$S %2$S үшін орналасуыңызға қатынау рұқсатын беруді рұқсат ету керек пе?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = %S үшін жүйелік баптауларында орналасуды анықтау рұқсатын беру.
geolocation.systemSettingsTitle = Орналасуды анықтау рұқсатын күтуде
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Жүйе сізден %S үшін осы рұқсатты беруіңізді сұрайды.
geolocation.remember = Осы таңдауымды есте сақтау
# Virtual Reality Device UI
xr.allow2 = Рұқсат ету
xr.allow2.accesskey = а
xr.block = Бұғаттау
xr.block.accesskey = Б
xr.shareWithSite4 = %S үшін виртуалды шынайылық құрылғыларына қатынау рұқсат ету керек пе? Бұл жеке мәліметтердің ашылуына әкеп соғуы мүмкін.
xr.shareWithFile4 = Бұл жергілікті файл үшін виртуалды шынайылық құрылғыларына қатынау рұқсат ету керек пе? Бұл жеке мәліметтердің ашылуына әкеп соғуы мүмкін.
xr.remember = Бұл таңдауымды есте сақтау
# Persistent storage UI
persistentStorage.allow = Рұқсат ету
persistentStorage.allow.accesskey = а
persistentStorage.block.label = Блоктау
persistentStorage.block.accesskey = Б
persistentStorage.allowWithSite2 = %S үшін деректерді тұрақты қоймада сақтауды рұқсат ету керек пе?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Рұқсат ету
webNotifications.allow2.accesskey = А
webNotifications.notNow = Қазір емес
webNotifications.notNow.accesskey = м
webNotifications.never = Ешқашан рұқсат етпеу
webNotifications.never.accesskey = ш
webNotifications.alwaysBlock = Әрқашан бұғаттау
webNotifications.alwaysBlock.accesskey = Б
webNotifications.block = Бұғаттау
webNotifications.block.accesskey = Б
webNotifications.receiveFromSite3 = %S үшін хабарламаларды жіберуді рұқсат ету керек пе?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S осы құрылғыдағы басқа қолданбалар мен қызметтерге қол жеткізгісі келеді.
localhost.remember2 = Бұл сайт үшін таңдауымды есте сақтау
localhost.allowlabel = Рұқсат ету
localhost.blocklabel = Блоктау
localhost.allow.accesskey = А
localhost.block.accesskey = Б
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S жергілікті желіге қосылған құрылғылардағы қолданбалар мен қызметтерге қол жеткізгісі келеді.
localNetwork.remember2 = Бұл сайт үшін таңдауымды есте сақтау
localNetwork.allowLabel = Рұқсат ету
localNetwork.allow.accesskey = а
localNetwork.blockLabel = Блоктау
localNetwork.block.accesskey = Б
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Осыдан кеткім келеді!
safebrowsing.getMeOutOfHereButton.accessKey = к
safebrowsing.deceptiveSite = Фишингті сайт!
safebrowsing.notADeceptiveSiteButton.label = Бұл фишингті сайт емес…
safebrowsing.notADeceptiveSiteButton.accessKey = ф
safebrowsing.reportedAttackSite = Бұл сайт компьютерлерге шабуыл жасауға қолданылатыны туралы ақпарат бар!
safebrowsing.notAnAttackButton.label = Бұл шабуыл жасайтын сайт емес…
safebrowsing.notAnAttackButton.accessKey = ш
safebrowsing.reportedUnwantedSite = Осы сайт ұнамсыз бағдарламалық қамтаманы таратуға қатысатыны туралы ақпарат бар!
safebrowsing.reportedHarmfulSite = Хабарланған зиянкес сайт!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = %S іздеу
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = %S өнімін жөндеу режимінде қайта іске қосу керек пе?
troubleshootModeRestartPromptMessage = Сіздің кеңейтулер, темалар мен өзгертілген баптауларыңыз уақытша сөндірілетін болады.
troubleshootModeRestartButton = Қайта қосу
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Бұл парақ %1$S жұмысын тежеп тұр. Браузеріңізді жылдамдату үшін, бұл парақты тоқтатыңыз.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Веб-парағы %1$S жұмысын тежеп тұр. Браузеріңізді жылдамдату үшін, ол парақты тоқтатыңыз.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = "%1$S" "%2$S" жұмысын тежеп тұр. Браузеріңізді жылдамдату үшін, ол парақты тоқтатыңыз.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = "%1$S" "%2$S" жұмысын тежеп тұр. Браузеріңізді жылдамдату үшін, ол кеңейтуді тоқтатыңыз.
processHang.add-on.learn-more.text = Көбірек білу
processHang.button_stop2.label = Тоқтату
processHang.button_stop2.accessKey = т
processHang.button_debug.label = Скриптті жөндеу
processHang.button_debug.accessKey = д
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Терезені толық экранға көрсету (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Бүйір панелін солға жылжыту
sidebar.moveToRight = Бүйір панелін оңға жылжыту
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Бұл беттегі кейбір аудио немесе видеоны ойнату үшін сізге DRM іске қосу керек.
emeNotifications.drmContentDisabled.button.label = DRM іске қосу
emeNotifications.drmContentDisabled.button.accesskey = е
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S бұл беттегі аудио не видеоны ойнатуға керек құрауыштарды орнатуда. Кейінірек қайталап көріңіз.
emeNotifications.unknownDRMSoftware = Белгісіз
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = %S баптау
decoder.noCodecs.button = Көбірек білу
decoder.noCodecs.accesskey = л
decoder.noCodecsLinux.message = Видеоны ойнату үшін, сізге керек болған видео кодектерін орнату керек болуы мүмкін.
decoder.noHWAcceleration.message = Видео сапасын арттыру үшін, сізге Microsoft Media Feature Pack орнату керек болуы мүмкін.
decoder.noPulseAudio.message = Аудионы ойнату үшін, сізге керек болған PulseAudio БҚ орнату керек болуы мүмкін.
decoder.unsupportedLibavcodec.message = libavcodec ақаулығы бар немесе оған қолдауы жоқ болуы мүмкін, видеоны ойнату үшін оны жаңарту керек.
decoder.decodeError.message = Медиа көзін декодтау кезінде қате орын алды.
decoder.decodeError.button = Сайт мәселесі жөнінде хабарлау
decoder.decodeError.accesskey = т
decoder.decodeWarning.message = Медиа көзін декодтау кезінде жөнделетін қате орын алды.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Интернетке қатынау үшін бұл желіге кіруіңіз керек.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Желіге кіру парағын ашу
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = %S үшін рұқсаттар
permissions.remove.tooltip = Бұл рұқсатты өшіріп, қайта сұрау
permissions.fullscreen.promptCanceled = Қатынауға рұқсат ету сұранымдары болдырылмады: рұқсат сұранымдары DOM толық экран режиміне өтуге дейін жасалмауы тиіс.
permissions.fullscreen.fullScreenCanceled = DOM толық экран режимінен шығу: рұқсат сұранымдары DOM толық экран режимі кезінде жасалмауы тиіс.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-биттік
aboutDialog.architecture.thirtyTwoBit = 32-биттік
midi.allow.label = Рұқсат ету
midi.allow.accesskey = а
midi.block.label = Бұғаттау
midi.block.accesskey = б
midi.remember = Бұл таңдауымды есте сақтау
midi.shareWithFile = Бұл жергілікті файл үшін MIDI құрылғыларыңызға қатынауға рұқсат ету керек пе?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = %S үшін MIDI құрылғыларыңызға қатынауға рұқсат ету керек пе?
midi.shareSysexWithFile = Бұл жергілікті файл үшін MIDI құрылғыларыңызға қатынау және SysEx хабарламаларын жіберу/қабылдауды рұқсат ету керек пе?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = %S үшін MIDI құрылғыларыңызға қатынау және SysEx хабарламаларын жіберу/қабылдауды рұқсат ету керек пе?
serial.allow.label = Рұқсат ету
serial.allow.accesskey = А
serial.block.label = Блоктау
serial.block.accesskey = Б
serial.shareWithFile = Бұл жергілікті файл үшін тізбекті порттарыңызға қол жеткізуді рұқсат ету керек пе?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = %S үшін тізбекті порттарыңызға қол жеткізуді рұқсат ету керек пе?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Артқа
storageAccess1.Allow.label = Рұқсат ету
storageAccess1.Allow.accesskey = а
storageAccess1.DontAllow.label = Бұғаттау
storageAccess1.DontAllow.accesskey = б
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = %1$S үшін %2$S жеріндегі өз cookie файлдарын қолдануға рұқсат беру керек пе?
storageAccess1.hintText = %1$S бұл деректерге қатынау мақсаты түсініксіз болса, қатынау құқығын бұғаттауыңызға болады.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Интернеттен "%S" іздеу
