# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Вы хочаце давяраць "%S" з наступнымі мэтамі?
unnamedCA = Цэнтр сертыфікацыі (без назвы)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Калі ласка, увядзіце пароль, выкарыстаны пры шыфраванні гэтай запасной копіі сертыфіката:
# Page Info
pageInfo_NoEncryption = Злучэнне не зашыфравана
pageInfo_Privacy_None1 = Вэб-сайт %S не падтрымлівае шыфраванне для старонкі, якую вы праглядаеце.
pageInfo_Privacy_None2 = Інфармацыя, якая перасылаецца праз Інтэрнэт без шыфравання, можа быць даступна іншым людзям у часе яе перадачы.
pageInfo_Privacy_None4 = Старонка, якую вы праглядаеце, не была зашыфравана для перадачы праз Сеціва.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Злучэнне зашыфравана (%1$S, %2$S біт ключы, %3$S)
pageInfo_BrokenEncryption = Зламанае шыфраванне (%1$S, %2$S біт ключы, %3$S)
pageInfo_Privacy_Encrypted1 = Старонка, якую вы праглядаеце, была зашыфравана для перадачы праз Сеціва.
pageInfo_Privacy_Encrypted2 = Шыфраванне робіць складаным прагляд звестак, якія перадаюцца паміж камп'ютарамі, неаўтарызаваным бокам. Такім чынам, малаверагодна, што хто-небудзь чытае гэту старонку, калі яна ідзе праз сетку.
pageInfo_MixedContent = Злучэнне часткова зашыфравана
pageInfo_MixedContent2 = Часткі старонкі, якую вы праглядаеце, не былі зашыфраваны для перадачы праз Сеціва.
pageInfo_WeakCipher = Ваша злучэнне з гэтым сайтам выкарыстоўвае слабае шыфраванне, і не прыватнае. Іншыя людзі могуць бачыць вашы звесткі і мяняць паводзіны вэб-сайта.
pageInfo_CertificateTransparency_Compliant = Гэты вэб-сайт адпавядае патрабаванням палітыкі Празрыстасці Сертыфікату.
# Token Manager
password_not_set = (не вызначаны)
