# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

ShowHidden = සැඟවුණු වස්තු පෙන්වන්න
DirColName = නම
DirColSize = ප්‍රමාණය
DirColMTime = අවසාන සංශෝධනය
DirFileLabel = ගොනුව:
CookieBlockedByPermission = අභිරුචි දත්තකඩ අවසරය නිසා “%1$S” හි දත්තකඩ හෝ ආචයනය වෙත ප්‍රවේශය විමසන ඉල්ලීම අවහිර කෙරිණි.
# LOCALIZATION NOTE (CookieOversize): %1$S is the cookie name. %2$S is the number of bytes. "B" means bytes.
CookieOversize = “%1$S” දත්තකඩ ප්‍රමාණය ඉතා විශාල බැවින් වලංගු නොවේ. උපරිම ප්‍රමාණය බ. %2$S කි.
# LOCALIZATION NOTE (CookieRejectedHttpOnlyButFromScript): %1$S is the cookie name.
CookieRejectedHttpOnlyButFromScript = දැනටමත් HTTP-පමණි දත්තකඩක් තිබෙන නමුත් අත්පත නව එකක් ගබඩා කිරීමට උත්සාහ කළ නිසා “%1$S” දත්තකඩ ප්‍රතික්‍ෂේප කර ඇත.
# LOCALIZATION NOTE (CookieRejectedSecureButHttp): %1$S is the cookie name.
CookieRejectedSecureButNonHttps = HTTPS නොවන දත්තකඩක් “සුරක්‍ෂිත” ලෙස සැකසීමට නොහැකි නිසා “%1$S” දත්තකඩ ප්‍රතික්‍ෂේප කර ඇත.
# LOCALIZATION NOTE (CookieRejectedThirdParty): %1$S is the cookie response header.
CookieRejectedThirdParty = “%1$S” දත්තකඩ තෙවන පාර්ශ්ව ලෙස ප්‍රතික්‍ෂේප කර ඇත.
# LOCALIZATION NOTE (CookieRejectedNonsecureOverSecure): %1$S is the cookie name.
CookieRejectedNonsecureOverSecure = “ආරක්‍ෂිත” දත්තකඩක් පවතින නිසා “%1$S” දත්තකඩ ප්‍රතික්‍ෂේප කර ඇත.
