#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Krishnababu Krothapalli &lt;k.meetme@gmail.com&gt; </em:contributor> <em:contributor>Arjuna Rao Chavala &lt;arjunaraoc@gmail.com&gt; </em:contributor>

#unfilter emptyLines
