# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SaveImageTitle = Spremi sliku
SaveMediaTitle = Spremanje medija
SaveVideoTitle = Spremi video
SaveAudioTitle = Spremi zvuk
SaveLinkTitle = Spremi kao
WebPageCompleteFilter = Web stranica, potpuno
WebPageHTMLOnlyFilter = Web stranica, samo HTML
WebPageXHTMLOnlyFilter = Web stranica, samo XHTML
WebPageSVGOnlyFilter = Web stranica, samo SVG
WebPageXMLOnlyFilter = Web stranica, samo XML
# LOCALIZATION NOTE (UntitledSaveFileName):
#    This is the default filename used when saving a file if a filename could
#    not be determined or if a filename was invalid. A period and file
#    extension may be appended to this string.
UntitledSaveFileName = Bez naslova
