#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Martin Cantieni</em:contributor> <em:contributor>Gion-Andri Cantieni</em:contributor> <em:contributor>Sara Hermann</em:contributor> <em:contributor>cordial sustegn da la Lia Rumantscha</em:contributor>

#unfilter emptyLines
