#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title Bookmarks
#define bookmarks_heading Bookmarks



#define bookmarks_toolbarfolder Bookmarks Toolbar Folder
#define bookmarks_toolbarfolder_description Add bookmarks to this folder to see them displayed on the Bookmarks Toolbar

# LOCALIZATION NOTE (getting_started):
# link title for http://gu-IN.www.mozilla.com/gu-IN/firefox/central/
#define getting_started Getting Started

# LOCALIZATION NOTE (latest_headlines):
# link title for the live bookmarks sample, a redirect on
# http://gu-IN.fxfeeds.mozilla.com/gu-IN/firefox/headlines.xml
# Changing the redirect is subject to approval of l10n-drivers.
#define latest_headlines Latest Headlines

# LOCALIZATION NOTE (firefox_heading):
# Firefox links folder name
#define firefox_heading Mozilla Firefox

# LOCALIZATION NOTE (firefox_help):
# link title for http://gu-IN.www.mozilla.com/gu-IN/firefox/help/
#define firefox_help Help and Tutorials

# LOCALIZATION NOTE (firefox_customize):
# link title for http://gu-IN.www.mozilla.com/gu-IN/firefox/customize/
#define firefox_customize Customize Firefox

# LOCALIZATION NOTE (firefox_community):
# link title for http://gu-IN.www.mozilla.com/gu-IN/firefox/community/
#define firefox_community Get Involved

# LOCALIZATION NOTE (firefox_about):
# link title for http://gu-IN.www.mozilla.com/gu-IN/firefox/about/
#define firefox_about About Us

#unfilter emptyLines
