#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title બુકમાર્ક
#define bookmarks_heading બુકમાર્ક

#define bookmarks_toolbarfolder બુકમાર્ક સાધનો ફોલ્ડર
#define bookmarks_toolbarfolder_description બુકમાર્ક સાધનપટ્ટી પર જોવા માટે આ ફોલ્ડરમાં બુકમાર્ક ઉમેરો

# LOCALIZATION NOTE (getting_started):
# link title for http://en-US.www.mozilla.com/en-US/firefox/central/
#define getting_started શરૂ કરો

# LOCALIZATION NOTE (latest_headlines):
# link title for the live bookmarks sample, a redirect on
# http://en-US.fxfeeds.mozilla.com/en-US/firefox/headlines.xml
# Changing the redirect is subject to approval of l10n-drivers.
#define latest_headlines તાજેતરના સમાચાર

# LOCALIZATION NOTE (firefox_heading):
# Firefox links folder name
#define firefox_heading મોઝિલ્લા ફાયરફોક્સ

# LOCALIZATION NOTE (firefox_help):
# link title for http://en-US.www.mozilla.com/en-US/firefox/help/
#define firefox_help મદદ અને માર્ગદર્શિકાઓ

# LOCALIZATION NOTE (firefox_customize):
# link title for http://en-US.www.mozilla.com/en-US/firefox/customize/
#define firefox_customize ફાયરફોક્સ વૈવિધ્યપૂર્ણ બનાવો

# LOCALIZATION NOTE (firefox_community):
# link title for http://en-US.www.mozilla.com/en-US/firefox/community/
#define firefox_community જોડાઇ જાવ

# LOCALIZATION NOTE (firefox_about):
# link title for http://en-US.www.mozilla.com/en-US/about/
#define firefox_about અમારા વિશે

#unfilter emptyLines
