# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Saxlanılmış Hesablar
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = URL-u köçür
    .accesskey = y
launch-site-url-cmd =
    .label = URL-u ziyarət et
    .accesskey = V
copy-username-cmd =
    .label = İstifadəçi adını köçür
    .accesskey = k
edit-username-cmd =
    .label = İstifadəçi adını dəyişdir
    .accesskey = r
copy-password-cmd =
    .label = Parolu Köçür
    .accesskey = K
edit-password-cmd =
    .label = Parolu Dəyişdir
    .accesskey = ə
search-filter =
    .accesskey = S
    .placeholder = Axtar
column-heading-site =
    .label = Sayt
column-heading-username =
    .label = İstifadəçi adı
column-heading-password =
    .label = Parol
column-heading-time-created =
    .label = İlk istifadə edilib
column-heading-time-last-used =
    .label = Son istifadə edilib
column-heading-time-password-changed =
    .label = Son dəyişdirilib
column-heading-times-used =
    .label = İstifadə edilmə sayı
remove =
    .label = Sil
    .accesskey = R
import =
    .label = İdxal et…
    .accesskey = a
close-button =
    .label = Qapat
    .accesskey = Q
show-passwords =
    .label = Parolları Göstər
    .accesskey = P
hide-passwords =
    .label = Parolları Gizlət
    .accesskey = P
logins-description-all = Bu saytlar üçün olan hesablarınız kompüterinizdə saxlanılır
logins-description-filtered = Aşağıdakı hesablar axtarışınıza uyğun gəlir:
remove-all =
    .label = Hamısını Sil
    .accesskey = A
remove-all-shown =
    .label = Görünənləri Sil
    .accesskey = A
remove-all-passwords-prompt = Bütün parolları silmək istədiyinizə əminsiniz?
remove-all-passwords-title = Bütün parolları sil
no-master-password-prompt = Parollarınızı göstərmək istədiyinizə əminsiniz?
auto-fill-logins-and-passwords =
    .label = Giriş və parolları avtomatik doldur
