# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Időtúllépés
openFile = Fájl megnyitása
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = %1$S-keresés erre: „%2$S”
contextMenuSearch.accesskey = K
contextMenuPrivateSearch = Keresés egy privát ablakban
contextMenuPrivateSearch.accesskey = p
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = %S keresés egy privát ablakban
contextMenuPrivateSearchOtherEngine.accesskey = k
bookmarkAllTabsDefault = [Mappa neve]
unsignedAddonsDisabled.message = Legalább egy telepített kiegészítő nem ellenőrizhető, és le lett tiltva.
unsignedAddonsDisabled.learnMore.label = További tudnivalók
unsignedAddonsDisabled.learnMore.accesskey = T
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Utolsó hozzáférés: %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = %S:// hivatkozások
crashedpluginsMessage.title = A(z) %S bővítmény összeomlott.
crashedpluginsMessage.reloadButton.label = Újratöltés
crashedpluginsMessage.reloadButton.accesskey = r
crashedpluginsMessage.submitButton.label = Hibajelentés küldése
crashedpluginsMessage.submitButton.accesskey = H
crashedpluginsMessage.learnMore = További tudnivalók…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Ide szeretett volna eljutni: %S?
keywordURIFixup.goTo = Igen, vigyél ide: %S
keywordURIFixup.goTo.accesskey = I
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Frissítés erre: %S
update.downloadAndInstallButton.accesskey = F
menuOpenAllInTabs.label = Mindegyik megnyitása külön lapon
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Oldal újratöltése
tabHistory.goBack = Visszaugrás erre az oldalra
tabHistory.goForward = Előreugrás erre az oldalra
# URL Bar
pasteAndGo.label = Beillesztés és ugrás
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Aktuális oldal újratöltése (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Az oldal betöltésének megszakítása (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Nagyítási szint visszaállítása (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Olvasó nézet átkapcsolása (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, Nagyítási szint visszaállítása
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Könyvjelzők megjelenítése (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = A folyamatban lévő letöltések állapotának megjelenítése (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Új ablak megnyitása (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Új lap megnyitása (%S)
newTabContainer.tooltip = Új lap megnyitása (%S)\nNyomja meg és tartsa lenyomva egy új konténerlap megnyitásához
newTabAlwaysContainer.tooltip = Válasszon konténert az új lap megnyitásához
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Engedélyezi, hogy a(z) %S használja a HTML5 vászon képadatait?
canvas.siteprompt2.warning = Ez arra is használható, hogy egyedileg azonosítsák a számítógépét.
canvas.block = Tiltás
canvas.block.accesskey = T
canvas.allow2 = Engedélyezés
canvas.allow2.accesskey = E
canvas.remember2 = Döntés megjegyzése
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Ellenőrizte: %S
identity.identified.verified_by_you = Biztonsági kivételt adott hozzá ehhez a webhelyhez.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Tanúsítvány kiállítva ennek: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Nem biztonságos
identity.notSecure.tooltip = A kapcsolat nem biztonságos
identity.extension.label = Kiegészítő (%S)
identity.extension.tooltip = Kiegészítő által betöltve: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Kicsinyítés (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Nagyítási szint visszaállítása (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Nagyítás (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Kivágás (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Másolás (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Beillesztés (%S)
geolocation.allow = Engedélyezés
geolocation.allow.accesskey = E
geolocation.block = Tiltás
geolocation.block.accesskey = T
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Ez megnyitja a rendszer helybeállításait. Adja meg a helymeghatározási engedélyt a %S számára.
geolocation.shareWithSite4 = Engedélyezi, hogy a(z) %S elérje a tartózkodási helyét?
geolocation.shareWithFile4 = Engedélyezi ennek a helyi fájlnak, hogy elérje a tartózkodási helyét?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Engedélyezi, hogy a(z) %1$S megengedje a(z) %2$S oldalnak, hogy elérje a tartózkodási helyét?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Adjon helymeghatározási engedélyt a %S számára a rendszerbeállításokban.
geolocation.systemSettingsTitle = Helymeghatározási engedélyre vár
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = A rendszer kérni fogja, hogy adja meg ezt az engedélyt a %S számára.
geolocation.remember = A döntés megjegyzése
# Virtual Reality Device UI
xr.allow2 = Engedélyezés
xr.allow2.accesskey = E
xr.block = Tiltás
xr.block.accesskey = T
xr.shareWithSite4 = Engedélyezi a(z) %S számára a virtuális valóság eszközeinek elérését? Ez érzékeny információkat szivárogtathat ki.
xr.shareWithFile4 = Engedélyezi e helyi fájl számára a virtuális valóság eszközeinek elérését? Ez érzékeny információkat szivárogtathat ki.
xr.remember = A döntés megjegyzése
# Persistent storage UI
persistentStorage.allow = Engedélyezés
persistentStorage.allow.accesskey = E
persistentStorage.block.label = Tiltás
persistentStorage.block.accesskey = T
persistentStorage.allowWithSite2 = Engedélyezi, hogy a(z) %S adatokat tároljon az állandó tárolóban?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Engedélyezés
webNotifications.allow2.accesskey = E
webNotifications.notNow = Most nem
webNotifications.notNow.accesskey = n
webNotifications.never = Sose engedélyezze
webNotifications.never.accesskey = s
webNotifications.alwaysBlock = Tiltás mindig
webNotifications.alwaysBlock.accesskey = T
webNotifications.block = Tiltás
webNotifications.block.accesskey = T
webNotifications.receiveFromSite3 = Engedélyezi, hogy a(z) %S értesítéseket küldjön?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = A(z) %S más alkalmazásokat és szolgáltatásokat akar elérni ezen az eszközön.
localhost.remember2 = Választás megjegyzése ehhez az oldalhoz
localhost.allowlabel = Engedélyezés
localhost.blocklabel = Tiltás
localhost.allow.accesskey = E
localhost.block.accesskey = T
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = A(z) %S a helyi hálózatra csatlakozó eszközök alkalmazásait és szolgáltatásait akarja elérni.
localNetwork.remember2 = Választás megjegyzése ehhez az oldalhoz
localNetwork.allowLabel = Engedélyezés
localNetwork.allow.accesskey = E
localNetwork.blockLabel = Tiltás
localNetwork.block.accesskey = T
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Oldal elhagyása
safebrowsing.getMeOutOfHereButton.accessKey = O
safebrowsing.deceptiveSite = Félrevezető oldal!
safebrowsing.notADeceptiveSiteButton.label = Ez nem félrevezető oldal…
safebrowsing.notADeceptiveSiteButton.accessKey = n
safebrowsing.reportedAttackSite = Bejelentett támadó webhely!
safebrowsing.notAnAttackButton.label = Ez nem támadó webhely…
safebrowsing.notAnAttackButton.accessKey = E
safebrowsing.reportedUnwantedSite = Bejelentett, nem kívánatos szoftvereket terjesztő oldal!
safebrowsing.reportedHarmfulSite = Bejelentett ártalmas oldal!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Keresés itt: %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Újraindítja a %Sot hibaelhárítási módban?
troubleshootModeRestartPromptMessage = Kiegészítői, témái és egyéni beállításai ideiglenesen letiltásra kerülnek.
troubleshootModeRestartButton = Újraindítás
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Ez az oldal lelassítja a %1$S futását. A böngésző felgyorsítása érdekében állítsa le ezt az oldalt.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Egy weboldal lelassítja a %1$S futását. A böngésző felgyorsítása érdekében állítsa le azt az oldalt.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = A(z) „%1$S” lelassítja a %2$S futását. A böngésző felgyorsítása érdekében állítsa le azt az oldalt.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = A(z) „%1$S” lelassítja a %2$S futását. A böngésző felgyorsítása érdekében állítsa le azt a kiegészítőt.
processHang.add-on.learn-more.text = További tudnivalók
processHang.button_stop2.label = Leállítás
processHang.button_stop2.accessKey = L
processHang.button_debug.label = Parancsfájl hibakeresése
processHang.button_debug.accessKey = h
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Ablak megjelenítése teljes képernyős módban (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Oldalsáv mozgatása balra
sidebar.moveToRight = Oldalsáv mozgatása jobbra
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Az oldalon lévő egyes hangok vagy videók lejátszásához engedélyezni kell a DRM-et.
emeNotifications.drmContentDisabled.button.label = DRM engedélyezése
emeNotifications.drmContentDisabled.button.accesskey = D
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = A %S az oldalon lévő hangok vagy videók lejátszásához szükséges összetevőket telepít. Próbálja újra később.
emeNotifications.unknownDRMSoftware = Ismeretlen
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = %S testreszabása
decoder.noCodecs.button = Tudja meg, hogyan
decoder.noCodecs.accesskey = T
decoder.noCodecsLinux.message = Videolejátszáshoz szükség lehet a szükséges videokodekek telepítésére.
decoder.noHWAcceleration.message = A videominőség javításához szükség lehet a Microsoft Media Feature Pack telepítésére.
decoder.noPulseAudio.message = Hanglejátszáshoz szükség lehet a szükséges PulseAudio szoftver telepítésére.
decoder.unsupportedLibavcodec.message = A libavcodec sebezhető lehet, vagy nem támogatott, és frissíteni kell a videolejátszáshoz.
decoder.decodeError.message = Hiba történt a média-erőforrás dekódolása közben.
decoder.decodeError.button = Hibás webhely bejelentése
decoder.decodeError.accesskey = j
decoder.decodeWarning.message = Helyrehozható hiba történt a média-erőforrás dekódolása közben.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Az internet elérése előtt be kell jelentkezni a hálózatra.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Hálózati bejelentkezés oldal megnyitása
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = A(z) %S engedélyei
permissions.remove.tooltip = Törli ezt az engedélyt és újra megkérdezi
permissions.fullscreen.promptCanceled = Függőben lévő engedélykérelem megszakítva: az engedélykéréseket nem szabad azelőtt kiadni, hogy a DOM teljes képernyősre vált.
permissions.fullscreen.fullScreenCanceled = Kilépés a teljes képernyős DOM-ból: az engedélykéréseket nem szabad kiadni, ha a DOM teljes képernyős.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64 bites
aboutDialog.architecture.thirtyTwoBit = 32 bites
midi.allow.label = Engedélyezés
midi.allow.accesskey = E
midi.block.label = Tiltás
midi.block.accesskey = T
midi.remember = A döntés megjegyzése
midi.shareWithFile = Engedélyezi ennek a helyi fájlnak, hogy elérje a MIDI eszközeit?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Engedélyezi, hogy a(z) %S elérje a MIDI eszközeit?
midi.shareSysexWithFile = Engedélyezi ennek a helyi fájlnak, hogy elérje a MIDI eszközeit és hogy SysEx üzeneteket küldjön/fogadjon?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Engedélyezi, hogy a(z) %S elérje a MIDI eszközeit és hogy SysEx üzeneteket küldjön/fogadjon?
serial.allow.label = Engedélyezés
serial.allow.accesskey = E
serial.block.label = Tiltás
serial.block.accesskey = T
serial.shareWithFile = Engedélyezi ennek a helyi fájlnak, hogy elérje a soros portjait?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Engedélyezi, hogy a(z) %S elérje a soros portjait?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Vissza
storageAccess1.Allow.label = Engedélyezés
storageAccess1.Allow.accesskey = E
storageAccess1.DontAllow.label = Tiltás
storageAccess1.DontAllow.accesskey = T
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Engedélyezi, hogy a(z) %1$S használja a sütijeit a(z) %2$S webhelyen?
storageAccess1.hintText = Érdemes lehet letiltani a hozzáférést, ha nem világos, hogy a(z) %1$S webhelynek miért van szüksége ezekre az adatokra.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Keressen rá az interneten erre: „%S”
