# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Сохранить
dialogTitleAddBookmark = Новая закладка
dialogTitleAddMulti = Новые закладки
dialogTitleEdit = Свойства для «%S»
dialogTitleAddNewBookmark2 = Добавить закладку
dialogTitleEditBookmark = Изменить «%S»
dialogTitleEditBookmark2 = Изменить закладку
dialogTitleAddBookmarkFolder = Добавить папку закладок
dialogTitleEditBookmarkFolder = Изменить папку закладок
bookmarkAllTabsDefault = [Имя папки]
newFolderDefault = Новая папка
newBookmarkDefault = Новая закладка
