# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

3 = Го барам %1$S…
4 = Се поврзав со %1$S…
5 = Испраќам барање до %1$S…
6 = Примам податоци од %1$S…
7 = Се поврзувам со %1$S…
8 = Прочитав %1$S
9 = Запишав %1$S
10 = Во исчекување на %1$S…
11 = Најден е %1$S…
12 = TLS ракување со %1$S…
13 = TLS ракувањето заврши за %1$S…
RepostFormData = Оваа страница се пренасочува кон кова локација. Дали сакате да ги препратите податоците од образецот на новата локација?
# Directory listing strings
DirTitle = Содржина на %1$S
DirGoUp = Нагоре во директориум од повисоко ниво
ShowHidden = Покажувај скриени објекти
DirColName = Име
DirColSize = Големина
DirColMTime = Последна промена
DirFileLabel = Датотека:
SuperfluousAuth = Ќе се пријавите на мрежното место „%1$S“ со корисничкото име „%2$S“, но тоа не бара да се идентификувате. Ова можеби е обид да бидете измамени. \n\nДали „%1$S“ е местото што сакате да го посетите?
AutomaticAuth = Ќе се пријавите на мрежното место „%1$S“ со корисничкото име „%2$S“.
TrackerUriBlockedByETP = Ресурсот на “%1$S” беше блокиран бидејќи засилената заштита од следење е овозможена.
TrackerUriBlocked = Ресурсот на “%1$S” беше блокиран бидејќи блокирањето на содржина е овозможено.
UnsafeUriBlocked = Ресурсот на “%1$S” беше блокиран од безбедното прелистување.
# LOCALIZATION NOTE (StrictUrlProtocolSetter): %1$S is the URL that has attempted to be changed. %2$S is the invalid target protocol.
StrictUrlProtocolSetter = Промената на URL-то “%1$S“ во протокол “%2$S“ беше блокирана.
# LOCALIZATION NOTE (CORPBlocked): %1$S is the URL of the blocked resource. %2$S is the URL of the MDN page about CORP.
CORPBlocked = Ресурсот на “%1$S” беше блокиран поради (недостаток на) неговото загавие за Cross-Origin-Resource-Policy. Повеќе %2$S
CookieBlockedByPermission = Барањето за пристап до колачиња или складиште на “%1$S” беше блокирано поради поставените дозволи за колачиња.
CookieBlockedTrackerByETP = Барањето за пристап до колачиња или складиште на “%1$S” беше блокирано бидејќи дојде од следач и Подобрената заштита од следење е овозможена.
CookieBlockedTracker = Барањето за пристап до колачиња или складиште на “%1$S” беше блокирано бидејќи дојде од следач и блокирањето на содржина е овозможено.
CookieBlockedAll = Барањето за пристап до колачиња или складиште на “%1$S” беше блокирано бидејќи ги блокираме сите барања за пристап.
CookieBlockedForeignByETP = Барањето за пристап до колачиња или складиште на “%1$S” беше блокирано бидејќи ги блокираме сите барања за пристап од трети страни и Подобрената заштита од следење е овозможена.
CookieBlockedForeign = Барањето за пристап до колачиња или складиште на “%1$S” беше блокирано бидејќи ги блокираме сите барања за пристап од трети страни и блокирањето на содржина е овозможено.
# As part of dynamic state partitioning, third-party resources might be limited to "partitioned" storage access that is separate from the first-party context.
# This allows e.g. cookies to still be set, and prevents tracking without totally blocking storage access. This message is shown in the web console when this happens
# to inform developers that their storage is isolated.
CookiePartitionedForeign2 = Делумен пристап до колачиња или складиште му беше даден на “%1$S” бидејќи е вчитан во контекст на трета страна и динамичко делење е овозможено.
# LOCALIZATION NOTE (CookieAllowedForOriginByStorageAccessAPI): %2$S and %1$S are URLs.
CookieAllowedForOriginByStorageAccessAPI = Доделен е пристап до складирање за извор “%2$S” на “%1$S”.
# LOCALIZATION NOTE (CookieAllowedForOriginByHeuristic): %2$S and %1$S are URLs.
CookieAllowedForOriginByHeuristic = Автоматски е доделен пристап до складирање за извор “%2$S” на “%1$S”.
# LOCALIZATION NOTE (CookieAllowedForFpiByHeuristic): %2$S and %1$S are URLs.
CookieAllowedForFpiByHeuristic = Автоматски е доделен пристап за изолирање на први страни за “%2$S” на “%1$S”.
# LOCALIZATION NOTE (CookieAllowedForDFPIByHeuristic): %2$S and %1$S are URLs.
CookieAllowedForDFPIByHeuristic = Автоматски е доделен пристап до складирање за динамично делење за “%2$S” на “%1$S”.
# LOCALIZATION NOTE (APIDeprecationWarning): %1$S is the deprecated API; %2$S is the API function that should be used.
APIDeprecationWarning = Предупредување: ‘%1$S’ е застарено, користете ‘%2$S’
# LOCALIZATION NOTE (ResourceBlockedCORS): %1$S is the url of the resource blocked by ORB. $2$S is the reason.
# example: The resource at <url> was blocked by OpaqueResponseBlocking. Reason: “nosniff with either blocklisted or text/plain”.
ResourceBlockedORB = Ресурсот на “%1$S” беше блокиран од OpaqueResponseBlocking. Причина: “%2$S”.
InvalidHTTPResponseStatusLine = Линијата за статус на HTTP одговорот е неважечка
