#filter emptyLines

# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1/GPL 2.0/LGPL 2.1
#
# The contents of this file are subject to the Mozilla Public License Version
# 1.1 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
# Contributor(s):
#   Gintautas Grigas <grigas@ktl.mii.lt>
#   Tatjana Jevsikova <tatjanaj@julius.ktl.mii.lt>
#   Rimas Kudelis <rq@akl.lt>
#
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 2 or later (the "GPL"), or
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
#
# ***** END LICENSE BLOCK *****



# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title Adresynas
#define bookmarks_heading Adresynas

#define bookmarks_toolbarfolder Adresyno juosta
#define bookmarks_toolbarfolder_description Čia įdėti adresai rodomi naršyklės adresyno juostoje

# LOCALIZATION NOTE (getting_started):
# link title for http://www.mozilla.com/lt/firefox/central/
#define getting_started Naudojimasis naršykle

# LOCALIZATION NOTE (latest_headlines):
# link title for the live bookmarks sample, a redirect on
# http://fxfeeds.mozilla.com/lt/firefox/headlines.xml
# Changing the redirect is subject to approval of l10n-drivers.
#define latest_headlines Naujienos

# LOCALIZATION NOTE (firefox_heading):
# Firefox links folder name
#define firefox_heading Mozilla Firefox

# LOCALIZATION NOTE (firefox_help):
# link title for http://www.mozilla.com/lt/firefox/help/
#define firefox_help Žinynas ir pagalba

# LOCALIZATION NOTE (firefox_customize):
# link title for http://www.mozilla.com/lt/firefox/customize/
#define firefox_customize „Firefox“ pritaikymas savo poreikiams

# LOCALIZATION NOTE (firefox_community):
# link title for http://www.mozilla.com/lt/firefox/community/
#define firefox_community Kaip prisidėti prie programos tobulinimo

# LOCALIZATION NOTE (firefox_about):
# link title for http://www.mozilla.com/lt/firefox/about/
#define firefox_about Apie „Mozilla“

#unfilter emptyLines
