# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Acessi sarvæ
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Còpia URL
    .accesskey = i
launch-site-url-cmd =
    .label = Vixita URL
    .accesskey = V
copy-username-cmd =
    .label = Còpia nomme utente
    .accesskey = u
edit-username-cmd =
    .label = Cangia nomme utente
    .accesskey = g
copy-password-cmd =
    .label = Còpia Paròlla segreta
    .accesskey = C
edit-password-cmd =
    .label = Cangia paròlla segreta
    .accesskey = n
search-filter =
    .accesskey = Ç
    .placeholder = Çerca
column-heading-site =
    .label = Scito
column-heading-username =
    .label = Nomme de l'utente
column-heading-password =
    .label = Paròlla segreta
column-heading-time-created =
    .label = Primma vòtta
column-heading-time-last-used =
    .label = Urtima vòtta
column-heading-time-password-changed =
    .label = Urtimo cangiamento
column-heading-times-used =
    .label = Numero vòtte
remove =
    .label = Scancella
    .accesskey = S
import =
    .label = Inpòrta…
    .accesskey = I
close-button =
    .label = Særa
    .accesskey = S
show-passwords =
    .label = Mostra Paròlla segreta
    .accesskey = P
hide-passwords =
    .label = Ascondi Paròlla segreta
    .accesskey = P
logins-description-all = I dæti d'acesso pe sti sciti en sarvæ in sciô computer
logins-description-filtered = Sti dæti d'acesso corispondan a-i critei de riçerca:
remove-all =
    .label = Scancella tutto
    .accesskey = S
remove-all-shown =
    .label = Scancella tutto quello visto
    .accesskey = S
remove-all-passwords-prompt = T'ê seguo che ti veu scancelâ tutte e paròlle segrete?
remove-all-passwords-title = Leva do mezo tutte e paròlle segrete
no-master-password-prompt = T'ê seguo de mostrâ a paròlla segreta?
