# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language-name-af = अफ्रिकी
language-name-am = अम्हारिक
language-name-an = अरागोनिज
language-name-as = आसामी
language-name-ay = आइमारा
language-name-az = अजरबैजानी
language-name-ba = वासकिर
language-name-bh = बिहारी
language-name-bi = बिसलामा
language-name-bm = बामबारा
language-name-bn = बङ्गाली
language-name-bo = तिब्बती
language-name-br = ब्रेटन
language-name-bs = बोस्नियाली
language-name-ch = चामोरो
language-name-cs = चेक
language-name-cv = चुभास
language-name-de = जर्मन
language-name-el = ग्रीक
language-name-eo = एस्पेरान्तो
language-name-et = एस्टोनियन
language-name-ff = फुलाह
language-name-fr = फ्रान्सेली
language-name-fy = फ्रिसियन
language-name-ga = आइरिस
language-name-gl = ग्यालिसियन
language-name-gn = गुअरानि
language-name-gu = गुजराती
language-name-ha = हाउसा
language-name-he = हिब्रु
language-name-hi = हिन्दी
language-name-ho = हिरि मोतु
language-name-hz = हेरेरो
language-name-ia = इन्तरलिङ्ग्या
language-name-ig = इगबो
language-name-ii = सिचुवान यि
language-name-ik = इनुपियाक
language-name-io = इडो
language-name-is = आइसलान्डीक
language-name-it = इटालियन
language-name-iu = इनुकटिटुट
language-name-ja = जापानी
language-name-kg = कङ्गो
language-name-ki = किकुयु
language-name-kk = कजाक
language-name-kn = कन्नाडा
language-name-ko = कोरियाली
language-name-kr = कानुरी
language-name-ks = कश्मिरी
language-name-ku = कुर्दिश
language-name-kv = कोमी
language-name-kw = कोर्निश
language-name-la = ल्याटिन
language-name-lb = लक्जेमबोरिगिज
language-name-ln = लिनगाला
language-name-lu = लुबा-कातान्जा
language-name-mh = मार्शेले
language-name-mi = माओरी
language-name-mr = मराठी
language-name-ms = मले
language-name-my = बर्मेली
language-name-na = नाउरु
language-name-ne = नेपाली
language-name-no = नर्वेली
language-name-nr = डेबेले, दक्षिण
language-name-nso = सोथो, उत्तरी
language-name-ny = चिचेवा
language-name-pi = पाली
language-name-pt = पोर्तुगाली
language-name-qu = क्वेचुवा
language-name-sa = संस्कृत
language-name-sd = सिन्दी
language-name-se = उत्तरिय सामी
language-name-sk = स्लोभाक
language-name-sm = सामोआन
language-name-sn = सोना
language-name-so = सोमाली
language-name-sq = अल्वानियन
language-name-st = सोथो, दक्षिणी
language-name-sw = स्वाहिली
language-name-ta = तामिल
language-name-tg = ताजिक
language-name-tig = टिग्रे
language-name-to = टोङ्गा
language-name-ug = इग्हुर
language-name-uk = युक्रेनियन
language-name-ur = उर्दु
language-name-uz = उज्बेक
language-name-ve = भेन्डा
language-name-vo = भोलापुक
language-name-wa = वालुन
language-name-wo = वलोफ
language-name-yi = यिड्‌डिस
language-name-zu = जुलु
