# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

jump = گوم زیڌن
press = تپنیڌن
check = نشووه زیڌن
uncheck = وورداشتن نشووه
select = پسند
open = گۊشیڌن
close = بستن
switch = آلشت
click = کیلیک
collapse = کۊتال کردن
expand = بولند کردن
activate = فعال کردن
cycle = گردش
# These messages are reported by accessibility clients such as screen readers to
# indicate landmarks, which are significant sections of a document to which
# users might want to navigate quickly. See this page for more information:
# https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/general-principles.html
banner = بنر
complementary = موکمل
contentinfo = دووسمندیا موئتوا
region = وولات
# LOCALIZATION NOTE (inputColorValue): %1$S%%, %2$S%%, and %3$S%% represent the red, green, and blue color values as a percentage.
inputColorValue = %1$S%% سوئر %2$S%% ساوز %3$S%% کوۊ
