# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

print-setup =
    .title = পৃষ্ঠার বৈশিষ্ট্য নির্ধারণ
custom-prompt-title = স্বনির্ধারিত পংক্তি...
custom-prompt-prompt = হেডার/ফুটার হিসাবে ব্যবহারের উদ্দেশ্যে নিজের পছন্দসই পংক্তি লিখুন
basic-tab =
    .label = বিন্যাস & বিকল্প
advanced-tab =
    .label = মার্জিন & হেডার/Footer
format-group-label =
    .value = বিন্যাস
orientation-label =
    .value = দিশা:
portrait =
    .label = প্রতিকৃতি
    .accesskey = P
landscape =
    .label = আড়াআড়ি
    .accesskey = L
scale =
    .label = মাপ:
    .accesskey = S
scale-percent =
    .value = %
shrink-to-fit =
    .label = পৃষ্ঠার প্রস্থ অনুসারে সংকুচন করা হবে
    .accesskey = W
options-group-label =
    .value = বিকল্প
print-bg =
    .label = ব্যাকগ্রাউন্ড প্রিন্ট করা হবে (রং ও ছবি)
    .accesskey = B
margin-group-label-inches =
    .value = মার্জিন (ইঞ্চি)
margin-group-label-metric =
    .value = মার্জিন (মিলিমিটার)
margin-top =
    .value = ঊর্ধ্বে:
    .accesskey = T
margin-top-invisible =
    .value = ঊর্ধ্বে:
margin-bottom =
    .value = নীচে:
    .accesskey = B
margin-bottom-invisible =
    .value = নীচে:
margin-left =
    .value = বাঁদিকে
    .accesskey = L
margin-left-invisible =
    .value = বাঁদিকে
margin-right =
    .value = ডানদিকে:
    .accesskey = ড
margin-right-invisible =
    .value = ডানদিকে:
header-footer-label =
    .value = হেডার & ফুটার
hf-left-label =
    .value = বাঁদিকে:
hf-center-label =
    .value = কেন্দ্রস্থিত:
hf-right-label =
    .value = ডানদিকে:
header-left-tip =
    .tooltiptext = বাঁদিকের হেডার
header-center-tip =
    .tooltiptext = কেন্দ্রস্থিত হেডার
header-right-tip =
    .tooltiptext = ডানদিকের হেডার
footer-left-tip =
    .tooltiptext = বাঁদিকের ফুটার
footer-center-tip =
    .tooltiptext = কেন্দ্রস্থিত ফুটার
footer-right-tip =
    .tooltiptext = ডানদিকের ফুটার
hf-blank =
    .label = --শূণ্য--
hf-title =
    .label = শিরোনাম
hf-url =
    .label = URL
hf-date-and-time =
    .label = তারিখ/সময়
hf-page =
    .label = পৃষ্ঠা #
hf-page-and-total =
    .label = সর্বমোট পৃষ্ঠা #, বর্তমান পৃষ্ঠা #
hf-custom =
    .label = স্বনির্ধারিত...
print-preview-window =
    .title = প্রিন্ট কর্মের পূর্বপ্রদর্শন
print-title =
    .value = শিরোনাম:
print-preparing =
    .value = প্রস্তুতি...
print-progress =
    .value = প্রগতি:
print-window =
    .title = প্রিন্ট কর্ম
print-complete =
    .value = প্রিন্ট কর্ম সমাপ্ত।
# Variables
# $percent (integer) - Number of printed percentage
print-percent =
    .value = { $percent }%
dialog-cancel-label = বাতিল
dialog-close-label = বন্ধ করুন
