# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dateformat-label =
    .value = Текстов формат на датата:
    .accesskey = Т
#   $date (String) - the formatted example date
dateformat-long =
    .label = Дълъг: { $date }
#   $date (String) - the formatted example date
dateformat-short =
    .label = Кратък: { $date }
timezone-label =
    .value = Часови пояс:
weekstart-label =
    .value = Първи ден от седмицата:
    .accesskey = П
show-weeknumber-label =
    .label = Показване номера на седмицата в изгледите и минимесеца
    .accesskey = с
dayweek-legend = Дневен и седмичен изглед
visible-hours-label =
    .value = Показване
    .accesskey = П
visible-hours-end-label =
    .value = часа едновременно
day-start-label =
    .value = Денят започва в:
    .accesskey = Д
day-end-label =
    .value = Денят свършва в:
    .accesskey = н
midnight-label =
    .label = Полунощ
noon-label =
    .label = Обед
multiweek-legend = Многоседмичен изглед
number-of-weeks-label =
    .value = Показвани седмици (включително изминали седмици)
    .accesskey = с
week-0-label =
    .label = нито една
week-1-label =
    .label = 1 седмица
week-2-label =
    .label = 2 седмици
week-3-label =
    .label = 3 седмици
week-4-label =
    .label = 4 седмици
week-5-label =
    .label = 5 седмици
week-6-label =
    .label = 6 седмици
previous-weeks-label =
    .value = Показвани изминали седмици:
    .accesskey = П
task-start-label =
    .value = Начална дата:
task-start-1-label =
    .label = Няма
task-start-2-label =
    .label = Начало на деня
task-start-3-label =
    .label = Край на деня
task-start-4-label =
    .label = Утре
task-start-5-label =
    .label = Следваща седмица
task-start-6-label =
    .label = Относително текущото време
task-start-7-label =
    .label = Относително началото
task-start-8-label =
    .label = Относително следващия час
task-due-label =
    .value = Краен срок:
accessibility-legend = Достъпност
accessibility-colors-label =
    .label = Цветове, оптимизирани за достъпност
    .accesskey = Ц
reminder-legend = Когато е време за припомняне:
reminder-default-sound-label =
    .label = Стандартен звук
    .accesskey = С
reminder-browse-sound-label =
    .label = Разглеждане…
    .accesskey = Р
reminder-default-legend = Настройки по подразбиране за припомняне
event-alarm-label =
    .value = Алармиране за събития:
    .accesskey = А
alarm-on-label =
    .label = Да
alarm-off-label =
    .label = Не
task-alarm-label =
    .value = Алармиране за задачи:
    .accesskey = р
event-alarm-time-label =
    .value = Подразбиращо се време за припомняне преди събитие:
    .accesskey = с
task-alarm-time-label =
    .value = Подразбиращо се време за припомняне преди събитие:
    .accesskey = с
category-edit-label = Редактиране на категория
category-overwrite-title = Внимание: Дублиращо се име
category-overwrite = Вече съществува такава категория.Искате ли да я заместите?
category-blank-warning = Трябва да въведете име на категория.
