# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = 正在解析 { $host }…
network-connection-status-connected = 已连接到 { $host }…
network-connection-status-sending-request = 正在发送请求到 { $host }…
network-connection-status-transferring-data = 正在传输来自 { $host } 的数据…
network-connection-status-connecting = 正在连接 { $host }…
network-connection-status-wrote = 写入 { $host }
network-connection-status-waiting = 等待 { $host }…
network-connection-status-looked-up = 已查询 { $host }…
