# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

title = Par tīklu
warning = Šis ir ļoti eksperimentāls. Nelietojiet šo bez pieredzes vai pieaugušo uzraudzības.
show-next-time-checkbox = Rādīt šo paziņojumu nākamreiz
ok = Labi
http = HTTP
sockets = Sockets
dns = DNS
websockets = WebSockets
refresh = Atjaunināt
auto-refresh = Automātiski atjaunināt katras 3 sekundes
hostname = Adrese
port = Ports
http2 = HTTP/2
ssl = SSL
active = Aktīvs
idle = Dīkstāvē
host = Adrese
tcp = TCP
sent = Nosūtīts
received = Saņemts
family = Saime
trr = TRR
addresses = Adreses
expires = Noilgums (sekundes)
messages-sent = Nosūtītie ziņojumi
messages-received = Saņemtie ziņojumi
bytes-sent = Nosūtītie baiti
bytes-received = Saņemtie baiti
logging = Reģistrēšana
log-tutorial = Apskatiet <a data-l10n-name="logging">HTTP reģistrēšana</a>, lai iegūtu papildu informāciju, kā lietot šo rīku.
current-log-file = Pašreizējais reģistrācijas fails:
current-log-modules = Pašreizējais reģistrācijas modulis:
set-log-file = Iestatīt reģistrēšanas failu
set-log-modules = Iestatīt reģistrēšanas moduli
start-logging = Sākt reģistrēšanu
stop-logging = Pārtraukt reģistrēšanu
dns-lookup = DNS uzmeklēšana
dns-lookup-button = Atrast
dns-domain = Domēns:
dns-lookup-table-column = IP
rcwn = RCWN statistika
rcwn-status = RCWN statuss
rcwn-cache-won-count = Kešatmiņas uzvaru skaits
rcwn-net-won-count = Tīkla uzvaru skaits
total-network-requests = Kopējais tīkla pieprasījumu skaits
rcwn-operation = Kešatmiņas darbība
rcwn-perf-open = Atvērt
rcwn-perf-read = Lasīt
rcwn-perf-write = Rakstīt
rcwn-perf-entry-open = Atvērts ieraksts
rcwn-avg-short = Īss vidējais
rcwn-avg-long = Garš vidējais
rcwn-std-dev-long = Gara standarta nobīde
rcwn-cache-slow = Kešatmiņas lēnumu skaits
rcwn-cache-not-slow = Kešatmiņas ne lēnumu skaits
