# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title دڵخوازەکان
#define bookmarks_heading دڵخوازەکان

#define bookmarks_toolbarfolder بوخچەی توڵامرازی دڵخوازەکان
#define bookmarks_toolbarfolder_description دڵخواز بکە ئەم بوخچەیەوە بۆ ئەوەی بیانبینیت لە توڵامرازی دڵخوازەکان

# LOCALIZATION NOTE (getting_started):
# link title for https://www.mozilla.org/en-US/firefox/central/
#define getting_started دەستپێبکە

# LOCALIZATION NOTE (firefox_heading):
# Firefox links folder name
#define firefox_heading مۆزیللا فایەرفۆکس

# LOCALIZATION NOTE (firefox_help):
# link title for https://www.mozilla.org/en-US/firefox/help/
#define firefox_help یارمەتی و فێرکاری

# LOCALIZATION NOTE (firefox_customize):
# link title for https://www.mozilla.org/en-US/firefox/customize/
#define firefox_customize فایەرفۆکس بەخواستی خۆت

# LOCALIZATION NOTE (firefox_community):
# link title for https://www.mozilla.org/en-US/contribute/
#define firefox_community بەشدار بە

# LOCALIZATION NOTE (firefox_about):
# link title for https://www.mozilla.org/en-US/about/
#define firefox_about دەربارەی ئێمە

# LOCALIZATION NOTE (nightly_heading):
# Firefox Nightly links folder name
#define nightly_heading سەرچاوەی فایەرفۆکسی شەوانەیی

# LOCALIZATION NOTE (nightly_blog):
# Nightly builds only, link title for https://blog.nightly.mozilla.org/
#define nightly_blog بڵاگی فایەرفۆکسی شەوانەیی

# LOCALIZATION NOTE (bugzilla):
# Nightly builds only, link title for https://bugzilla.mozilla.org/
#define bugzilla شوێنکەوتەی کەلێنی مۆزیللا

# LOCALIZATION NOTE (mdn):
# Nightly builds only, link title for https://developer.mozilla.org/
#define mdn ڕایەڵەی گەشەپێدەرانی مۆزیللا

# LOCALIZATION NOTE (nightly_tester_tools):
# Nightly builds only, link title for https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/
#define nightly_tester_tools ئامرازەکانی تاقیکەری شەوانەیی

# LOCALIZATION NOTE (crashes):
# Nightly builds only, link title for about:crashes
#define crashes هەموو داخستنە لە ناکاوەکان

# LOCALIZATION NOTE (irc):
# Nightly builds only, link title for ircs://irc.mozilla.org/nightly
#define irc شەوانە تاوتوێ بکە لە IRC

# LOCALIZATION NOTE (planet):
# Nightly builds only, link title for https://planet.mozilla.org/
#define planet هەسارەی مۆزیللا

#unfilter emptyLines
