# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host } සෝදිසි කරමින්...
network-connection-status-connected = { $host } වෙත සම්බන්‍ධයි…
network-connection-status-sending-request = { $host } වෙත ඉල්ලීම යැවෙමින්…
network-connection-status-transferring-data = { $host } වෙතින් දත්ත හුවමාරු වෙමින්…
network-connection-status-connecting = { $host } වෙත සම්බන්ධ වෙමින්…
network-connection-status-waiting = { $host } සඳහා රැඳෙමින්…
