# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title बुकमार्क\u0020


#define bookmarks_heading बुकमार्क\u0020


#define bookmarks_toolbarfolder बुकमार्कस् साधनपट्टी फोल्डर


#define bookmarks_toolbarfolder_description बुकमार्कस् साधनपट्टेचेर दाखोवपाखातीर बुकमार्कस् ह्या फोल्डरांत जोडात


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/firefox/central/


#define getting_started चालू जाता


# LOCALIZATION NOTE (firefox_heading):


# Firefox links folder name


#define firefox_heading मॉझिला फायरफॉक्स


# LOCALIZATION NOTE (firefox_help):


# link title for https://www.mozilla.org/en-US/firefox/help/


#define firefox_help मदत आणि शिकवणी


# LOCALIZATION NOTE (firefox_customize):


# link title for https://www.mozilla.org/en-US/firefox/customize/


#define firefox_customize फायरफॉक्स कस्टमायज करात


# LOCALIZATION NOTE (firefox_community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox_community सामील जायात


# LOCALIZATION NOTE (firefox_about):


# link title for https://www.mozilla.org/en-US/about/


#define firefox_about आमचे विशीं


#unfilter emptyLines
