# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Ateiza tròppo longa
openFile = Arvi schedaio
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Riçerca "%2$S" con %1$S
contextMenuSearch.accesskey = r
bookmarkAllTabsDefault = [Nomme da cartella]
unsignedAddonsDisabled.message = Quarche conponente azonto instalou o l'é stæto dizativou perché no ò pòsciuo verificali.
unsignedAddonsDisabled.learnMore.label = Atre informaçioin
unsignedAddonsDisabled.learnMore.accesskey = A
crashedpluginsMessage.title = O plugin %S o s'é ciantou.
crashedpluginsMessage.reloadButton.label = Carega torna a pagina
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = Segnala un problema
crashedpluginsMessage.submitButton.accesskey = S
crashedpluginsMessage.learnMore = Pe saveine de ciu…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Ti voeivi arvî %S?
keywordURIFixup.goTo = Sci, arvi %S
keywordURIFixup.goTo.accesskey = S
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Agiorna a %S
update.downloadAndInstallButton.accesskey = A
menuOpenAllInTabs.label = Arvi tutto inti feuggi
tabHistory.goBack = Vanni inderê
tabHistory.goForward = Vanni avanti
# URL Bar
pasteAndGo.label = Incòlla & Vanni
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Recarega a pagina corente (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Fermite de caregâ sta pagina (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Repiggia o livello de zoom (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Cangia a-o mòddo leuta (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Amia i segnalibbri (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Mostra l’avansamento di descaregamenti in corso (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Arvi 'n neuvo barcon (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Arvi neuvo feuggio (%S)
newTabAlwaysContainer.tooltip = Çerni un contegnitô pe arvî un neuvo feuggio
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Verificou da: %S
identity.identified.verified_by_you = T’æ azonto 'na eceçion de seguessa pe sto scito.
identity.identified.state_and_country = %S, %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = No seguo
identity.notSecure.tooltip = A conescion a no l'é segua
identity.extension.label = Estenscion (%S)
identity.extension.tooltip = Caregou da l'estenscion: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Zoom ciù picin (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Reinpòsta o zoom (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Zoom ciù grande (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Taggia (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Còpia (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Incòlla (%S)
geolocation.remember = Aregòrda sta decixon
# Persistent storage UI
persistentStorage.allow = Permetti
persistentStorage.allow.accesskey = P
webNotifications.notNow = Òua No
webNotifications.notNow.accesskey = n
webNotifications.never = No permette mai
webNotifications.never.accesskey = m
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Pòrtime feua de chi!
safebrowsing.getMeOutOfHereButton.accessKey = P
safebrowsing.deceptiveSite = Scito inganevole!
safebrowsing.notADeceptiveSiteButton.label = Questo o no l'é 'n scito inganevole…
safebrowsing.notADeceptiveSiteButton.accessKey = I
safebrowsing.reportedAttackSite = L'é stæto segnaou comme scito de atacco!
safebrowsing.notAnAttackButton.label = Sto chi o no l'é 'n scito de atacco…
safebrowsing.notAnAttackButton.accessKey = a
safebrowsing.reportedUnwantedSite = O scito ch'o gh'aiva do software no desiderou o l'é stæto segnalou
safebrowsing.reportedHarmfulSite = Segnala scito pericoloso!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Riçerca %S
processHang.add-on.learn-more.text = Atre informaçioin
processHang.button_debug.label = Xeua o debug do script
processHang.button_debug.accessKey = X
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Mostra o barcon a tutto schermo (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Mescia bara de scianco a mancinn-a
sidebar.moveToRight = Mescia bara de scianco a drita
emeNotifications.drmContentDisabled.button.label = Ativa DRM
emeNotifications.drmContentDisabled.button.accesskey = A
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = Inpostaçioin in corso dei componenti necessari pe riproduî i contegnui aodio ò video prezenti inta pagina. Preuva torna ciù tardi.%0.S
emeNotifications.unknownDRMSoftware = Scònosciuo
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Personalizza %S
decoder.noCodecs.button = Comme se fa
decoder.noCodecs.accesskey = C
decoder.noCodecsLinux.message = Pe vedde o video ti doviesci instalâ i codec video domandæ.
decoder.noHWAcceleration.message = Pe vedde megio o video ti doviesci instalâ o Media Feature Pack de Microsoft.
decoder.noPulseAudio.message = Pe sentî sto òudio ti doviesci instalâ o software PulseAudio domandou.
decoder.unsupportedLibavcodec.message = libavcodec o peu êse vulenrabile ò no soportou, e ti doviesci agiornalo pe vedde sto video.
decoder.decodeError.message = S'é verificou 'n'erô inta decodifica da risorsa media.
decoder.decodeError.button = Denonçia Problema Scito
decoder.decodeError.accesskey = D
decoder.decodeWarning.message = Gh'é stæto 'n erô che ghe se peu dâ recatto mentre faxeivo a decodifica de 'na risorsa media.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Ti devi acede a sta ræ prima che ti ti pòsse navegâ into Internet.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Arvi a pagina de intrâ da ræ
permissions.remove.tooltip = Scancella sto permisso e domanda torna
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bit
aboutDialog.architecture.thirtyTwoBit = 32-bit
midi.remember = Aregòrda sta decixon
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Inderê
