# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Нигоҳ доштан
dialogTitleAddBookmark = Хатбараки нав
dialogTitleAddMulti = Хатбаракҳои нав
dialogTitleEdit = Хусусиятҳо барои “%S”
dialogTitleAddNewBookmark2 = Илова кардани хатбарак
dialogTitleEditBookmark = Таҳрир кардани «%S»
dialogTitleEditBookmark2 = Таҳрир кардани хатбарак
dialogTitleAddBookmarkFolder = Илова кардани ҷузвдони хатбаракҳо
dialogTitleEditBookmarkFolder = Таҳрир кардани ҷузвдони хатбаракҳо
bookmarkAllTabsDefault = [Номи ҷузвдон]
newFolderDefault = Ҷузвдони нав
newBookmarkDefault = Хатбараки нав
