# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loginsDescriptionAll2 = В компютъра са запазени регистрациите в следните сайтове
# LOCALIZATION NOTE (useASecurelyGeneratedPassword):
# Shown in the autocomplete popup to allow filling a generated password into a password field.
useASecurelyGeneratedPassword = Използвайте сигурно генерирана парола
# LOCALIZATION NOTE (generatedPasswordWillBeSaved):
# %S will contain the brandShorterName. This informs the user that the generated password will be automatically saved.
generatedPasswordWillBeSaved = %S ще запази паролата за тази страница.
# LOCALIZATION NOTE (loginHostAge):
# This is used to show the context menu login items with their age.
# 1st string is the username for the login, 2nd is the login's age.
loginHostAge = %1$S (%2$S)
# LOCALIZATION NOTE (noUsername):
# String is used on the context menu when a login doesn't have a username.
noUsername = Няма потребителско име
# LOCALIZATION NOTE (displaySameOrigin):
# String is used on the autocomplete row when the login origin is a domain match with the document origin
displaySameOrigin = От страницата
# LOCALIZATION NOTE (insecureFieldWarningDescription2):
# %1$S will contain insecureFieldWarningLearnMore and look like a link to indicate that clicking will open a tab with support information.
insecureFieldWarningDescription2 = Връзката е незащитена. Въведените тук данни за вход могат да бъдат компрометирани. %1$S
insecureFieldWarningLearnMore = Научете повече
# LOCALIZATION NOTE (managePasswords.label):
# This label is used in the footer of login autocomplete menus.
managePasswords.label = Управляване на пароли
