# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Ներմուծման աւգնական
import-from =
    { PLATFORM() ->
        [windows] Ներմուծել ընտրանքները, էջանիշերը, պատմութիւնը, գաղտնաբառերը եւ այլ տուեալներ այստեղից՝
       *[other] Ներմուծել կարգաւորումները, էջանիշները, գաղտնաբառերը եւ այլ տուեալներ՝
    }
import-from-bookmarks = Ներմուծել էջանիշները՝
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-edge-legacy =
    .label = Microsoft Edge Legacy
    .accesskey = L
import-from-edge-beta =
    .label = Microsoft Edge Beta
    .accesskey = d
import-from-nothing =
    .label = Ոչինչ չներմուծել
    .accesskey = D
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chrome-beta =
    .label = Chrome Beta
    .accesskey = B
import-from-chrome-dev =
    .label = Chrome Dev
    .accesskey = D
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = X
import-from-360se =
    .label = 360 անվտանգ զննարկիչ
    .accesskey = 3
no-migration-sources = Չգտնուեց ծրագիր, որը պարունակում է էջանիշեր, պատմութիւն կամ գաղտնաբառ։
import-source =
    .label = Ներմուծել կարգաւորումները եւ տուեալները
import-items-title =
    .label = Ինչն է ներմուծուելու
import-items-description = Ընտրէք, թէ ինչ պէտք է ներմուծուի՝
import-migrating-title =
    .label = Ներմուծուում է…
import-migrating-description = Ներկա պահին ներմուծուում են հետեւեալ բաղադրիչները…
import-select-profile-title =
    .label = Ընտրէք հաշիւը
import-select-profile-description = Կարող եք ներմուծել հետեւեալ հաշիւներից՝
import-done-title =
    .label = Ներմուծումն աւարտուեց
import-done-description = Հետեւեալ բաղադրիչները յաջողութեամբ ներմուծուեցին՝
import-close-source-browser = Շարունակելուց առաջ խնդրում ենք համոզուել, որ ընտրուած դիտարկիչը փակ է։
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = { $source }-ից
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-edge-beta = Microsoft Edge Beta
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chrome-beta = Google Chrome Beta
source-name-chrome-dev = Google Chrome Dev
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 անվտանգ զննարկիչ
imported-safari-reading-list = Ընթերցացուցակ (Safari-ից)
imported-edge-reading-list = Ընթերցացուցակ (Edge-ից)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Համացանցի ընտրանքները
    .value = Համացանցի ընտրանքները
browser-data-edge-1 =
    .label = Կարգաւորումներ
    .value = Կարգաւորումներ
browser-data-safari-1 =
    .label = Կարգաւորումներ
    .value = Կարգաւորումներ
browser-data-chrome-1 =
    .label = Կարգաւորումներ
    .value = Կարգաւորումներ
browser-data-canary-1 =
    .label = Կարգաւորումներ
    .value = Կարգաւորումներ
browser-data-360se-1 =
    .label = Կարգաւորումներ
    .value = Կարգաւորումներ
browser-data-ie-2 =
    .label = Նշոցիկներ
    .value = Նշոցիկներ
browser-data-edge-2 =
    .label = Նշոցիկներ
    .value = Նշոցիկներ
browser-data-safari-2 =
    .label = Նշոցիկներ
    .value = Նշոցիկներ
browser-data-chrome-2 =
    .label = Նշոցիկներ
    .value = Նշոցիկներ
browser-data-canary-2 =
    .label = Նշոցիկներ
    .value = Նշոցիկներ
browser-data-firefox-2 =
    .label = Նշոցիկներ
    .value = Նշոցիկներ
browser-data-360se-2 =
    .label = Նշոցիկներ
    .value = Նշոցիկներ
browser-data-ie-4 =
    .label = Զննարկման պատմութիւնը
    .value = Զննարկման պատմութիւնը
browser-data-edge-4 =
    .label = Զննարկման պատմութիւնը
    .value = Զննարկման պատմութիւնը
browser-data-safari-4 =
    .label = Զննարկման պատմութիւնը
    .value = Զննարկման պատմութիւնը
browser-data-chrome-4 =
    .label = Զննարկման պատմութիւնը
    .value = Զննարկման պատմութիւնը
browser-data-canary-4 =
    .label = Զննարկման պատմութիւնը
    .value = Զննարկման պատմութիւնը
browser-data-firefox-history-and-bookmarks-4 =
    .label = Զննարկման պատմութիւն եւ էջանիշեր
    .value = Զննարկման պատմութիւն եւ էջանիշեր
browser-data-360se-4 =
    .label = Զննարկման պատմութիւն
    .value = Զննարկման պատմութիւն
browser-data-ie-8 =
    .label = Պահպանուել է պատմութիւնից
    .value = Պահպանուել է պատմութիւնից
browser-data-edge-8 =
    .label = Պահպանուել է պատմութիւնից
    .value = Պահպանուել է պատմութիւնից
browser-data-safari-8 =
    .label = Պահպանուել է պատմութիւնից
    .value = Պահպանուել է պատմութիւնից
browser-data-chrome-8 =
    .label = Պահպանուել է պատմութիւնից
    .value = Պահպանուել է պատմութիւնից
browser-data-canary-8 =
    .label = Պահպանուել է պատմութիւնից
    .value = Պահպանուել է պատմութիւնից
browser-data-firefox-8 =
    .label = Պահպանուել է պատմութիւնից
    .value = Պահպանուել է պատմութիւնից
browser-data-360se-8 =
    .label = Պահպանուել է պատմութիւնից
    .value = Պահպանուել է պատմութիւնից
browser-data-ie-16 =
    .label = Պահպանուած գաղտնաբառերը
    .value = Պահպանուած գաղտնաբառերը
browser-data-edge-16 =
    .label = Պահպանուած գաղտնաբառերը
    .value = Պահպանուած գաղտնաբառերը
browser-data-safari-16 =
    .label = Պահպանուած գաղտնաբառերը
    .value = Պահպանուած գաղտնաբառերը
browser-data-chrome-16 =
    .label = Պահպանուած գաղտնաբառերը
    .value = Պահպանուած գաղտնաբառերը
browser-data-canary-16 =
    .label = Պահպանուած գաղտնաբառերը
    .value = Պահպանուած գաղտնաբառերը
browser-data-firefox-16 =
    .label = Պահպանուած գաղտնաբառերը
    .value = Պահպանուած գաղտնաբառերը
browser-data-360se-16 =
    .label = Պահպանուած գաղտնաբառերը
    .value = Պահպանուած գաղտնաբառերը
browser-data-ie-32 =
    .label = Ընտրեալներ
    .value = Ընտրեալներ
browser-data-edge-32 =
    .label = Ընտրեալներ
    .value = Ընտրեալներ
browser-data-safari-32 =
    .label = Էջանիշեր
    .value = Էջանիշեր
browser-data-chrome-32 =
    .label = Էջանիշեր
    .value = Էջանիշեր
browser-data-canary-32 =
    .label = Էջանիշեր
    .value = Էջանիշեր
browser-data-360se-32 =
    .label = Էջանիշեր
    .value = Էջանիշեր
browser-data-ie-64 =
    .label = Այլ տուեալներ
    .value = Այլ տուեալներ
browser-data-edge-64 =
    .label = Այլ տուեալներ
    .value = Այլ տուեալներ
browser-data-safari-64 =
    .label = Այլ տուեալներ
    .value = Այլ տուեալներ
browser-data-chrome-64 =
    .label = Այլ տուեալներ
    .value = Այլ տուեալներ
browser-data-canary-64 =
    .label = Այլ տուեալներ
    .value = Այլ տուեալներ
browser-data-firefox-other-64 =
    .label = Այլ տուեալներ
    .value = Այլ տուեալներ
browser-data-360se-64 =
    .label = Այլ տուեալներ
    .value = Այլ տուեալներ
browser-data-firefox-128 =
    .label = Պատուհաններ եւ ներդիրներ
    .value = Պատուհաններ եւ ներդիրներ
