# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

reload-tab =
    .label = Կրկին բեռնել ներդիրը
    .accesskey = R
select-all-tabs =
    .label = Ընտրել բոլոր ներդիրները
    .accesskey = S
duplicate-tab =
    .label = Կրկնաւրինակել ներդիրը
    .accesskey = D
duplicate-tabs =
    .label = Կրկնաւրինակել բոլոր ներդիրները
    .accesskey = D
close-tabs-to-the-end =
    .label = Փակել ներդիրները աջից
    .accesskey = i
close-other-tabs =
    .label = Փակել միւս ներդիրները
    .accesskey = o
reload-tabs =
    .label = Կրկին բեռնել ներդիրները
    .accesskey = R
pin-tab =
    .label = Ամրացնել ներդիրը
    .accesskey = P
unpin-tab =
    .label = Ապամրացնել ներդիրը
    .accesskey = p
pin-selected-tabs =
    .label = Ամրացնել ներդիրները
    .accesskey = P
unpin-selected-tabs =
    .label = Ապամրացնել ներդիրները
    .accesskey = p
bookmark-selected-tabs =
    .label = Էջանշել ներդիրները…
    .accesskey = B
bookmark-tab =
    .label = Էջանշել ներդիրները
    .accesskey = B
reopen-in-container =
    .label = Կրկին բացել պարունակում
    .accesskey = e
move-to-start =
    .label = Տեղափոխել մեկնարկ
    .accesskey = S
move-to-end =
    .label = Տեղափոխել վերջ
    .accesskey = E
move-to-new-window =
    .label = Տեղափոխել նոր պատուհան
    .accesskey = W
undo-close-tab =
    .label = Յետարկել փակուած ներդիրը
    .accesskey = U
close-tab =
    .label = Փակել ներդիրը
    .accesskey = c
close-tabs =
    .label = Փակել ներդիրները
    .accesskey = S
move-tabs =
    .label = Տեղափոխել ներդիրները
    .accesskey = v
move-tab =
    .label = Տեղափոխել ներդիրը
    .accesskey = v
