# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Mpurtazziuni cunnuciuta
import-from =
    { PLATFORM() ->
        [windows] Mporta i prifirenzi, i nzingalibbri, a cronuluggìa, i chiavi e l'autri dati di:
       *[other] Mporta i prifirenzi, i nzingalibbri, a cronuluggìa, i chiavi e l'autri dati di:
    }
import-from-bookmarks = Mporta i nzingalibbri di:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = x
import-from-360se =
    .label = 360 Secure Browser
    .accesskey = 3
no-migration-sources = Nun potti truvari nuḍḍu prugramma ca cc'àvi dati di nzingalibbri, cronuluggìa o chiavi.
import-source =
    .label = Pigghia mpustazziuna e dati
import-items-title =
    .label = Cosi di pigghiari
import-items-description = Scegghi quali cosi pigghiari:
import-migrating-title =
    .label = Staju mpurtannu…
import-migrating-description = Staju mpurtannu sti cosi…
import-select-profile-title =
    .label = Scegghi u profilu
import-select-profile-description = Chisti sunu i profila ca poi scègghiri:
import-done-description = Chisti sunnu i cosi ca potti pigghiari:
import-close-source-browser = Pi favuri vidi si u navigaturi ca scigghisti fu chiusu prima di cuntinuari.
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = Di { $source }
imported-safari-reading-list = Lista di littura (di Safari)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Prifirenzi Internet
    .value = Prifirenzi Internet
browser-data-edge-1 =
    .label = Mpustazziuni
    .value = Mpustazziuni
browser-data-safari-1 =
    .label = Prifirenzi
    .value = Prifirenzi
browser-data-chrome-1 =
    .label = Prifirenzi
    .value = Prifirenzi
browser-data-canary-1 =
    .label = Prifirenzi
    .value = Prifirenzi
browser-data-360se-1 =
    .label = Prifirenzi
    .value = Prifirenzi
browser-data-ie-2 =
    .label = Viscotta
    .value = Viscotta
browser-data-edge-2 =
    .label = Viscotta
    .value = Viscotta
browser-data-safari-2 =
    .label = Viscotta
    .value = Viscotta
browser-data-chrome-2 =
    .label = Viscotta
    .value = Viscotta
browser-data-canary-2 =
    .label = Viscotta
    .value = Viscotta
browser-data-firefox-2 =
    .label = Viscotta
    .value = Viscotta
browser-data-360se-2 =
    .label = Viscotta
    .value = Viscotta
browser-data-ie-4 =
    .label = Cronuluggìa di navigazziuni
    .value = Cronuluggìa di navigazziuni
browser-data-edge-4 =
    .label = Cronuluggìa di navigazziuni
    .value = Cronuluggìa di navigazziuni
browser-data-safari-4 =
    .label = Cronuluggìa di navigazziuni
    .value = Cronuluggìa di navigazziuni
browser-data-chrome-4 =
    .label = Cronuluggìa di navigazziuni
    .value = Cronuluggìa di navigazziuni
browser-data-canary-4 =
    .label = Cronuluggìa di navigazziuni
    .value = Cronuluggìa di navigazziuni
browser-data-firefox-history-and-bookmarks-4 =
    .label = Cronuluggìa di navigazziuni e nzingalibbri
    .value = Cronuluggìa di navigazziuni e nzingalibbri
browser-data-360se-4 =
    .label = Cronuluggìa di navigazziuni
    .value = Cronuluggìa di navigazziuni
browser-data-ie-8 =
    .label = Cronuluggìa dî mòduli sarbati
    .value = Cronuluggìa dî mòduli sarbati
browser-data-edge-8 =
    .label = Cronuluggìa dî mòduli sarbati
    .value = Cronuluggìa dî mòduli sarbati
browser-data-safari-8 =
    .label = Cronuluggìa dî mòduli sarbati
    .value = Cronuluggìa dî mòduli sarbati
browser-data-chrome-8 =
    .label = Cronuluggìa dî mòduli sarbati
    .value = Cronuluggìa dî mòduli sarbati
browser-data-canary-8 =
    .label = Cronuluggìa dî mòduli sarbati
    .value = Cronuluggìa dî mòduli sarbati
browser-data-firefox-8 =
    .label = Cronuluggìa dî mòduli sarbati
    .value = Cronuluggìa dî mòduli sarbati
browser-data-360se-8 =
    .label = Cronuluggìa dî mòduli sarbati
    .value = Cronuluggìa dî mòduli sarbati
browser-data-ie-16 =
    .label = Chiavi sarbati
    .value = Chiavi sarbati
browser-data-edge-16 =
    .label = Chiavi sarbati
    .value = Chiavi sarbati
browser-data-safari-16 =
    .label = Chiavi sarbati
    .value = Chiavi sarbati
browser-data-chrome-16 =
    .label = Chiavi sarbati
    .value = Chiavi sarbati
browser-data-canary-16 =
    .label = Chiavi sarbati
    .value = Chiavi sarbati
browser-data-firefox-16 =
    .label = Chiavi sarbati
    .value = Chiavi sarbati
browser-data-360se-16 =
    .label = Chiavi sarbati
    .value = Chiavi sarbati
browser-data-ie-32 =
    .label = Favuruti
    .value = Favuruti
browser-data-edge-32 =
    .label = Favuruti
    .value = Favuruti
browser-data-safari-32 =
    .label = Nzingalibbri
    .value = Nzingalibbri
browser-data-chrome-32 =
    .label = Nzingalibbri
    .value = Nzingalibbri
browser-data-canary-32 =
    .label = Nzingalibbri
    .value = Nzingalibbri
browser-data-360se-32 =
    .label = Nzingalibbri
    .value = Nzingalibbri
browser-data-ie-64 =
    .label = Autri dati
    .value = Autri dati
browser-data-edge-64 =
    .label = Autri dati
    .value = Autri dati
browser-data-safari-64 =
    .label = Autri dati
    .value = Autri dati
browser-data-chrome-64 =
    .label = Autri dati
    .value = Autri dati
browser-data-canary-64 =
    .label = Autri dati
    .value = Autri dati
browser-data-firefox-other-64 =
    .label = Autri dati
    .value = Autri dati
browser-data-360se-64 =
    .label = Autri dati
    .value = Autri dati
browser-data-firefox-128 =
    .label = Finestri e schedi
    .value = Finestri e schedi
