# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Λήξη χρόνου
openFile = Άνοιγμα αρχείου
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Αναζήτηση στο %1$S για «%2$S»
contextMenuSearch.accesskey = ζ
contextMenuPrivateSearch = Αναζήτηση σε ιδιωτικό παράθυρο
contextMenuPrivateSearch.accesskey = ζ
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Αναζήτηση με %S σε ιδιωτικό παράθυρο
contextMenuPrivateSearchOtherEngine.accesskey = σ
bookmarkAllTabsDefault = [Όνομα φακέλου]
unsignedAddonsDisabled.message = Ένα ή περισσότερα εγκατεστημένα πρόσθετα δεν μπορούν να επαληθευτούν και έχουν απενεργοποιηθεί.
unsignedAddonsDisabled.learnMore.label = Μάθετε περισσότερα
unsignedAddonsDisabled.learnMore.accesskey = Μ
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Τελευταία πρόσβαση %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = Σύνδεσμοι %S://
crashedpluginsMessage.title = Το άρθρωμα %S κατέρρευσε.
crashedpluginsMessage.reloadButton.label = Ανανέωση σελίδας
crashedpluginsMessage.reloadButton.accesskey = ν
crashedpluginsMessage.submitButton.label = Υποβολή αναφοράς κατάρρευσης
crashedpluginsMessage.submitButton.accesskey = β
crashedpluginsMessage.learnMore = Μάθετε περισσότερα…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Μήπως θέλατε να μεταβείτε στο %S;
keywordURIFixup.goTo = Ναι, μετάβαση στο %S
keywordURIFixup.goTo.accesskey = Ν
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Ενημέρωση σε %S
update.downloadAndInstallButton.accesskey = Ε
menuOpenAllInTabs.label = Άνοιγμα όλων σε καρτέλες
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Ανανέωση σελίδας
tabHistory.goBack = Επιστροφή στη σελίδα
tabHistory.goForward = Μετάβαση μπροστά στη σελίδα
# URL Bar
pasteAndGo.label = Επικόλληση και μετάβαση
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Ανανέωση τρέχουσας σελίδας (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Διακοπή φόρτωσης σελίδας (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Επαναφορά επιπέδου ζουμ (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Εναλλαγή προβολής ανάγνωσης (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, Επαναφορά επιπέδου ζουμ
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Προβολή σελιδοδεικτών (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Προβολή προόδου τρεχουσών λήψεων (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Άνοιγμα νέου παραθύρου (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Άνοιγμα νέας καρτέλας (%S)
newTabContainer.tooltip = Άνοιγμα νέας καρτέλας (%S)\nΠατήστε παρατεταμένα για άνοιγμα νέας θεματικής καρτέλας
newTabAlwaysContainer.tooltip = Επιλέξτε ενότητα για άνοιγμα νέας καρτέλας
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Να επιτρέπεται στο %S η χρήση δεδομένων εικόνας καμβά HTML5;
canvas.siteprompt2.warning = Αυτό μπορεί να χρησιμοποιηθεί για την αναγνώριση του υπολογιστή σας.
canvas.block = Φραγή
canvas.block.accesskey = Φ
canvas.allow2 = Αποδοχή
canvas.allow2.accesskey = Α
canvas.remember2 = Απομνημόνευση απόφασης
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Επαλήθευση από: %S
identity.identified.verified_by_you = Έχετε προσθέσει μια εξαίρεση ασφαλείας για αυτόν τον ιστότοπο.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Το πιστοποιητικό εκδόθηκε για: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Μη ασφαλής
identity.notSecure.tooltip = Η σύνδεση δεν είναι ασφαλής
identity.extension.label = Επέκταση (%S)
identity.extension.tooltip = Φορτώθηκε από επέκταση: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Σμίκρυνση (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Επαναφορά επιπέδου ζουμ (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Μεγέθυνση (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Αποκοπή (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Αντιγραφή (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Επικόλληση (%S)
geolocation.allow = Αποδοχή
geolocation.allow.accesskey = Α
geolocation.block = Φραγή
geolocation.block.accesskey = Φ
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Θα ανοίξουν οι ρυθμίσεις τοποθεσίας του συστήματος. Παραχωρήστε την άδεια τοποθεσίας στο %S.
geolocation.shareWithSite4 = Να επιτρέπεται στο %S η πρόσβαση στην τοποθεσία σας;
geolocation.shareWithFile4 = Να επιτρέπεται σε αυτό το τοπικό αρχείο η πρόσβαση στην τοποθεσία σας;
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Να επιτρέπεται στο %1$S να παραχωρεί στο %2$S την άδεια για πρόσβαση στην τοποθεσία σας;
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Παραχωρήστε την άδεια τοποθεσίας στο %S από τις ρυθμίσεις συστήματος.
geolocation.systemSettingsTitle = Σε αναμονή για άδειας τοποθεσίας
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Το σύστημα θα σας ζητήσει να παραχωρήσετε αυτό το δικαίωμα στο %S.
geolocation.remember = Απομνημόνευση απόφασης
# Virtual Reality Device UI
xr.allow2 = Αποδοχή
xr.allow2.accesskey = Α
xr.block = Φραγή
xr.block.accesskey = Φ
xr.shareWithSite4 = Να επιτρέπεται στο %S η πρόσβαση σε συσκευές εικονικής πραγματικότητας; Ενδέχεται να εκτεθούν ευαίσθητες πληροφορίες.
xr.shareWithFile4 = Να επιτρέπεται σε αυτό το τοπικό αρχείο η πρόσβαση σε συσκευές εικονικής πραγματικότητας; Ενδέχεται να εκτεθούν ευαίσθητες πληροφορίες.
xr.remember = Απομνημόνευση απόφασης
# Persistent storage UI
persistentStorage.allow = Αποδοχή
persistentStorage.allow.accesskey = Α
persistentStorage.block.label = Φραγή
persistentStorage.block.accesskey = Φ
persistentStorage.allowWithSite2 = Να επιτρέπεται στο %S η αποθήκευση δεδομένων στη μόνιμη αποθήκευση;
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Αποδοχή
webNotifications.allow2.accesskey = Α
webNotifications.notNow = Όχι τώρα
webNotifications.notNow.accesskey = τ
webNotifications.never = Οριστική απόρριψη
webNotifications.never.accesskey = τ
webNotifications.alwaysBlock = Φραγή πάντα
webNotifications.alwaysBlock.accesskey = ρ
webNotifications.block = Φραγή
webNotifications.block.accesskey = Φ
webNotifications.receiveFromSite3 = Να επιτρέπεται στο %S η αποστολή ειδοποιήσεων;
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = Το %S ζητά πρόσβαση σε άλλες εφαρμογές και υπηρεσίες αυτής της συσκευής.
localhost.remember2 = Απομνημόνευση επιλογής για αυτόν τον ιστότοπο
localhost.allowlabel = Αποδοχή
localhost.blocklabel = Φραγή
localhost.allow.accesskey = Α
localhost.block.accesskey = Φ
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = Το %S ζητά πρόσβαση σε εφαρμογές και υπηρεσίες συσκευών συνδεδεμένων στο τοπικό σας δίκτυο.
localNetwork.remember2 = Απομνημόνευση επιλογής για αυτόν τον ιστότοπο
localNetwork.allowLabel = Αποδοχή
localNetwork.allow.accesskey = Α
localNetwork.blockLabel = Φραγή
localNetwork.block.accesskey = Φ
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Θέλω να φύγω από εδώ!
safebrowsing.getMeOutOfHereButton.accessKey = γ
safebrowsing.deceptiveSite = Παραπλανητικός ιστότοπος!
safebrowsing.notADeceptiveSiteButton.label = Αυτός δεν είναι παραπλανητικός ιστότοπος…
safebrowsing.notADeceptiveSiteButton.accessKey = Δ
safebrowsing.reportedAttackSite = Έχει αναφερθεί ως ιστότοπος επιθέσεων!
safebrowsing.notAnAttackButton.label = Αυτός δεν είναι ιστότοπος επιθέσεων…
safebrowsing.notAnAttackButton.accessKey = θ
safebrowsing.reportedUnwantedSite = Έχει αναφερθεί ως ιστότοπος ανεπιθύμητου λογισμικού!
safebrowsing.reportedHarmfulSite = Αναφέρθηκε επιβλαβής ιστότοπος!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Αναζήτηση «%S»
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Εκκίνηση %S σε λειτουργία επίλυσης προβλημάτων;
troubleshootModeRestartPromptMessage = Οι επεκτάσεις, τα θέματα και οι προσαρμοσμένες ρυθμίσεις σας θα απενεργοποιηθούν προσωρινά.
troubleshootModeRestartButton = Επανεκκίνηση
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Αυτή η σελίδα επιβραδύνει το %1$S. Για να επιταχύνετε το πρόγραμμα περιήγησής σας, τερματίστε τη.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Μια ιστοσελίδα επιβραδύνει το %1$S. Για να επιταχύνετε το πρόγραμμα περιήγησής σας, τερματίστε τη.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = Το «%1$S» επιβραδύνει το %2$S. Για να επιταχύνετε το πρόγραμμα περιήγησής σας, τερματίστε αυτήν τη σελίδα.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = Το «%1$S» επιβραδύνει το %2$S. Για να επιταχύνετε το πρόγραμμα περιήγησής σας, τερματίστε αυτήν την επέκταση.
processHang.add-on.learn-more.text = Μάθετε περισσότερα
processHang.button_stop2.label = Διακοπή
processHang.button_stop2.accessKey = Δ
processHang.button_debug.label = Έλεγχος σφαλμάτων σεναρίου
processHang.button_debug.accessKey = Έ
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Προβολή παραθύρου σε πλήρη οθόνη (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Μετακίνηση πλαϊνής γραμμής στα αριστερά
sidebar.moveToRight = Μετακίνηση πλαϊνής γραμμής στα δεξιά
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Θα πρέπει να ενεργοποιήσετε το DRM για αναπαραγωγή ήχου ή βίντεο στη σελίδα.
emeNotifications.drmContentDisabled.button.label = Ενεργοποίηση DRM
emeNotifications.drmContentDisabled.button.accesskey = Ε
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = Το %S εγκαθιστά κάποια απαραίτητα στοιχεία προκειμένου να γίνει αναπαραγωγή ήχου ή βίντεο στη σελίδα. Δοκιμάστε ξανά αργότερα.
emeNotifications.unknownDRMSoftware = Άγνωστο
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Προσαρμογή του %S
decoder.noCodecs.button = Μάθετε πώς
decoder.noCodecs.accesskey = Θ
decoder.noCodecsLinux.message = Για την αναπαραγωγή βίντεο, ενδέχεται να χρειάζεται η εγκατάσταση των απαραίτητων αποκωδικοποιητών βίντεο.
decoder.noHWAcceleration.message = Για τη βελτίωση της ποιότητας των βίντεο, ενδέχεται να χρειάζεται η εγκατάσταση του Πακέτου δυνατοτήτων media της Microsoft.
decoder.noPulseAudio.message = Για την αναπαραγωγή ήχου, ίσως χρειαστεί να εγκαταστήσετε το λογισμικό PulseAudio.
decoder.unsupportedLibavcodec.message = Το libavcodec παρουσιάζει ευπάθειες ασφάλειας ή δεν υποστηρίζεται και πρέπει να ενημερωθεί για την αναπαραγωγή βίντεο.
decoder.decodeError.message = Προέκυψε σφάλμα κατά την αποκωδικοποίηση ενός πόρου πολυμέσων.
decoder.decodeError.button = Αναφορά ζητήματος ιστοτόπου
decoder.decodeError.accesskey = Α
decoder.decodeWarning.message = Προέκυψε ανακτήσιμο σφάλμα κατά την αποκωδικοποίηση ενός πόρου πολυμέσων.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Πρέπει να συνδεθείτε σε αυτό το δίκτυο πριν μπορέσετε να αποκτήσετε πρόσβαση στο διαδίκτυο.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Άνοιγμα σελίδας σύνδεσης σε δίκτυο
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Δικαιώματα του %S
permissions.remove.tooltip = Αφαίρεση δικαιώματος και ερώτηση ξανά
permissions.fullscreen.promptCanceled = Ακυρώθηκαν τα εκκρεμή αιτήματα δικαιωμάτων: τα αιτήματα δικαιωμάτων δεν πρέπει να εκδίδονται πριν από την είσοδο σε πλήρη οθόνη DOM.
permissions.fullscreen.fullScreenCanceled = Έγινε έξοδος από την πλήρη οθόνη DOM: τα αιτήματα δικαιωμάτων δεν πρέπει να εκδίδονται κατά τη χρήση σε πλήρη οθόνη DOM.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bit
aboutDialog.architecture.thirtyTwoBit = 32-bit
midi.allow.label = Αποδοχή
midi.allow.accesskey = Α
midi.block.label = Φραγή
midi.block.accesskey = Φ
midi.remember = Απομνημόνευση απόφασης
midi.shareWithFile = Να επιτρέπεται σε αυτό το τοπικό αρχείο η πρόσβαση στις συσκευές MIDI σας;
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Να επιτρέπεται στο %S η πρόσβαση στις συσκευές MIDI σας;
midi.shareSysexWithFile = Να επιτρέπεται σε αυτό το τοπικό αρχείο η πρόσβαση στις συσκευές MIDI σας και η αποστολή/λήψη μηνυμάτων SysEx;
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Να επιτρέπεται στο %S η πρόσβαση στις MIDI συσκευές σας και η αποστολή/λήψη μηνυμάτων SysEx;
serial.allow.label = Αποδοχή
serial.allow.accesskey = Α
serial.block.label = Φραγή
serial.block.accesskey = Φ
serial.shareWithFile = Να επιτρέπεται σε αυτό το τοπικό αρχείο η πρόσβαση στις σειριακές θύρες σας;
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Να επιτραπεί στο %S η πρόσβαση στις σειριακές σας θύρες;
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Πίσω
storageAccess1.Allow.label = Αποδοχή
storageAccess1.Allow.accesskey = Α
storageAccess1.DontAllow.label = Φραγή
storageAccess1.DontAllow.accesskey = Φ
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Να επιτρέπεται στο %1$S να χρησιμοποιεί τα cookie του στο %2$S;
storageAccess1.hintText = Ίσως θελήσετε να αποκλείσετε την πρόσβαση εάν δεν είναι σαφές το γιατί το %1$S χρειάζεται αυτά τα δεδομένα.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Αναζήτηση στο διαδίκτυο για «%S»
