# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Yakon taq kitikirib'al molojri'ïl
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Tiwachib'ëx URL
    .accesskey = x
launch-site-url-cmd =
    .label = Titz'et URL
    .accesskey = T
copy-username-cmd =
    .label = Tiwachib'ëx Rub'i' Winäq
    .accesskey = R
edit-username-cmd =
    .label = Tinuk' Rub'i' Winäq
    .accesskey = n
copy-password-cmd =
    .label = Tiwachib'ëx Ewan Tzij
    .accesskey = T
edit-password-cmd =
    .label = Tinuk' Ewan Tzij
    .accesskey = T
search-filter =
    .accesskey = T
    .placeholder = Tikanöx
column-heading-site =
    .label = Ruxaq k'amaya'l
column-heading-username =
    .label = Rub'i' winäq
column-heading-password =
    .label = Ewan tzij
column-heading-time-created =
    .label = Nab'ey mul okisan
column-heading-time-last-used =
    .label = Ruk'isib'äl mul okisan
column-heading-time-password-changed =
    .label = Ruk'isib'äl Mul Xjal
column-heading-times-used =
    .label = Janipe' Okisan
remove =
    .label = Tiyuj
    .accesskey = y
import =
    .label = Tijik' pe…
    .accesskey = T
close-button =
    .label = Titz'apïx
    .accesskey = T
show-passwords =
    .label = Kek'ut Ewan taq Tzij
    .accesskey = E
hide-passwords =
    .label = Ke'ewäx ri ewan taq tzij
    .accesskey = e
logins-description-all = Ri kitikirib'al moloj re taq ruxaq k'amaya'l re' yeyak pan akematz'ib'
logins-description-filtered = Re jujun kitikirib'al molojri'ïl re', nikik'äm ki' rik'in ri nakanoj:
remove-all =
    .label = Keyuj Ronojel
    .accesskey = R
remove-all-shown =
    .label = Keyuj Ronojel Ek'utun pe
    .accesskey = R
remove-all-passwords-prompt = ¿At jikïl chi nawajo' ye'ayüj ronojel ri ewan taq tzij?
remove-all-passwords-title = Keyuj ronojel ri ewan taq tzij
no-master-password-prompt = ¿La at jikïl chi nawajo' ye'ak'üt pe ri ewan taq atzij?
auto-fill-logins-and-passwords =
    .label = Ruyonil ketz'aqatisäx ri tikirib'äl molojri'ïl chuqa' ewan taq tzij
