# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Speichern
dialogTitleAddBookmark = Neues Lesezeichen
dialogTitleAddMulti = Neue Lesezeichen
dialogTitleEdit = Eigenschaften für "%S"
dialogTitleAddNewBookmark2 = Lesezeichen hinzufügen
dialogTitleEditBookmark = "%S" bearbeiten
dialogTitleEditBookmark2 = Lesezeichen bearbeiten
dialogTitleAddBookmarkFolder = Lesezeichenordner hinzufügen
dialogTitleEditBookmarkFolder = Lesezeichenordner bearbeiten
bookmarkAllTabsDefault = [Ordnername]
newFolderDefault = Neuer Ordner
newBookmarkDefault = Neues Lesezeichen
