# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host } aranıyor…
network-connection-status-connected = { $host } sunucusuna bağlanıldı…
network-connection-status-sending-request = { $host } sunucusuna istek iletiliyor…
network-connection-status-transferring-data = { $host } konumundan veri aktarılıyor…
network-connection-status-connecting = { $host } sunucusuna bağlanılıyor…
network-connection-status-read = { $host } okunuyor
network-connection-status-wrote = { $host } yazılıyor
network-connection-status-waiting = { $host } bekleniyor…
network-connection-status-looked-up = { $host } aranıyor…
network-connection-status-tls-handshake = { $host } ile TLS el sıkışması yapılıyor…
network-connection-status-tls-handshake-finished = { $host } ile TLS el sıkışması tamamlandı…
