# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Lagrede innlogginger
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-username-cmd =
    .label = Kopier brukernavn
    .accesskey = o
edit-username-cmd =
    .label = Rediger brukernavn
    .accesskey = d
copy-password-cmd =
    .label = Kopier passord
    .accesskey = K
edit-password-cmd =
    .label = Rediger passord
    .accesskey = R
column-heading-site =
    .label = Nettsted
column-heading-username =
    .label = Brukernavn
column-heading-password =
    .label = Passord
column-heading-time-created =
    .label = Først brukt
column-heading-time-last-used =
    .label = Sist brukt
column-heading-time-password-changed =
    .label = Sist endret
column-heading-times-used =
    .label = Ganger brukt
remove =
    .label = Fjern
    .accesskey = F
import =
    .label = Importer …
    .accesskey = I
close-button =
    .label = Lukk
    .accesskey = L
show-passwords =
    .label = Vis passord
    .accesskey = V
hide-passwords =
    .label = Skjul passord
    .accesskey = S
logins-description-filtered = Følgende innlogginger passer til søket:
remove-all-passwords-prompt = Er du sikker på at du vil slette alle passord?
remove-all-passwords-title = Slett alle passord
no-master-password-prompt = Er du sikker på at du vil vise passordene?
