# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Zäit iwwerschratt
openFile = Fichier opmaachen
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = %1$S-Sich no “%2$S”
contextMenuSearch.accesskey = S
bookmarkAllTabsDefault = [Numm vum Dossier]
unsignedAddonsDisabled.learnMore.label = Fir méi ze wëssen
unsignedAddonsDisabled.learnMore.accesskey = L
crashedpluginsMessage.reloadButton.label = Säit nei lueden
crashedpluginsMessage.learnMore = Fir méi ze wëssen…
keywordURIFixup.goTo.accesskey = Y
tabHistory.goBack = Zréck op dës Säit
tabHistory.goForward = Virugoen op dës Säit
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Aktuell Säit nei lueden (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S %%
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Deng Lieszeeche weisen (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Eng nei Fënster opmaachen (%S)
identity.extension.label = Erweiderung (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Kopéieren (%S)
# Persistent storage UI
persistentStorage.allow = Zouloossen
persistentStorage.allow.accesskey = A
webNotifications.notNow = Net Elo
webNotifications.notNow.accesskey = n
webNotifications.never = Ni zouloossen
webNotifications.never.accesskey = v
safebrowsing.getMeOutOfHereButton.accessKey = G
safebrowsing.notADeceptiveSiteButton.accessKey = D
safebrowsing.notAnAttackButton.accessKey = A
processHang.add-on.learn-more.text = Fir méi ze wëssen
emeNotifications.unknownDRMSoftware = Onbekannt
