#filter emptyLines

#define MOZ_LANGPACK_CREATOR The Irish Mozilla Localisation Team

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Michael Bauer</em:contributor> <em:contributor>Cillian de Roiste</em:contributor> <em:contributor>Cian Duffy</em:contributor> <em:contributor>Conor Farrell</em:contributor> <em:contributor>Marion Gunn</em:contributor> <em:contributor>Panu Petteri Höglund</em:contributor> <em:contributor>Brian King</em:contributor> <em:contributor>Iarla Mac Aodha Bhuí</em:contributor> <em:contributor>Diarmaid Mac Mathúna</em:contributor> <em:contributor>Dáithi Mac Sithigh</em:contributor> <em:contributor>Enda McGuinness</em:contributor> <em:contributor>Séamus Ó Ciardhuáin</em:contributor> <em:contributor>Caoimhín Ó Donnaile</em:contributor> <em:contributor>Tony Pratschke</em:contributor> <em:contributor>Rüdiger Reinhardt</em:contributor> <em:contributor>Kevin Scannell</em:contributor> 
#unfilter emptyLines
