# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dateformat-label =
    .value = Data testu formatua:
    .accesskey = D
#   $date (String) - the formatted example date
dateformat-long =
    .label = Luzea: { $date }
#   $date (String) - the formatted example date
dateformat-short =
    .label = Laburra: { $date }
weekstart-label =
    .value = Astea noiz hasi:
    .accesskey = h
day-1-name =
    .label = Igandea
day-2-name =
    .label = Astelehena
day-3-name =
    .label = Asteartea
day-4-name =
    .label = Asteazkena
day-5-name =
    .label = Osteguna
day-6-name =
    .label = Ostirala
day-7-name =
    .label = Larunbata
dayweek-legend = Eguneko eta asteko ikuspegia
visible-hours-label =
    .value = Erakutsi:
    .accesskey = r
visible-hours-end-label =
    .value = ordu aldi berean
day-start-label =
    .value = Eguna hasten da:
    .accesskey = E
day-end-label =
    .value = Eguna bukatzen da:
    .accesskey = b
midnight-label =
    .label = Gauerdia
noon-label =
    .label = Eguerdia
multiweek-legend = Aste anitzeko ikuspegia
week-1-label =
    .label = aste 1
week-2-label =
    .label = 2 aste
week-3-label =
    .label = 3 aste
week-4-label =
    .label = 4 aste
week-5-label =
    .label = 5 aste
week-6-label =
    .label = 6 aste
previous-weeks-label =
    .value = Ikusiko diren aurreko asteak:
    .accesskey = a
task-start-label =
    .value = Hasiera-data:
task-start-1-label =
    .label = Bat ere ez
task-start-2-label =
    .label = Egunaren hasiera
task-start-3-label =
    .label = Egunaren amaiera
task-start-4-label =
    .label = Bihar
task-start-5-label =
    .label = Hurrengo astea
task-start-6-label =
    .label = Uneko orduarekiko erlatiboa
task-start-7-label =
    .label = Hasierarekiko erlatiboa
task-start-8-label =
    .label = Hurrengo orduarekiko erlatiboa
task-due-label =
    .value = Muga-data:
accessibility-legend = Erabilgarritasuna
accessibility-colors-label =
    .label = Optimizatu koloreak erabilgarritasunerako
    .accesskey = k
reminder-legend = Gogorarazle bat muga-egunean denean:
reminder-play-checkbox =
    .label = Soinu bat jo
    .accesskey = s
reminder-browse-sound-label =
    .label = Arakatu…
    .accesskey = A
reminder-dialog-label =
    .label = Erakutsi gogorarazlearen elkarrizketa-koadroa
    .accesskey = x
default-snooze-label =
    .value = Geroko uzteko luzera lehenetsia:
    .accesskey = G
alarm-on-label =
    .label = Gaitu
alarm-off-label =
    .label = Ezgaitu
event-alarm-time-label =
    .value = Gertaeren aurretik gogorarazleari ezarriko zaion denbora lehenetsia:
    .accesskey = u
category-edit-label = Kategoria editatu
category-overwrite-title = Oharra: Bikoiztutako izena
category-overwrite = Badago izen horretako kategoria bat dagoeneko. Gainidatzi nahi al duzu?
category-blank-warning = Kategoria izen bat sartu behar duzu.
