# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

print-setup =
    .title = ڕێکخستنی پەڕە
custom-prompt-title = دڵخواز…
custom-prompt-prompt = سەرپەڕ و پێپەڕی خوازراوی بنووسە
basic-tab =
    .label = جۆر و هەڵبژاردەکان
advanced-tab =
    .label = قەراخ & سەرپەڕ/پێپەڕ
format-group-label =
    .value = جۆر
orientation-label =
    .value = ئاڕاستە:
portrait =
    .label = پۆرترەیت(درێژ)
    .accesskey = p
landscape =
    .label = پانیی
    .accesskey = L
scale =
    .label = پێوانە:
    .accesskey = S
scale-percent =
    .value = %
shrink-to-fit =
    .label = ڕاکێشان بۆ پڕبوونی لە پانی پەڕە
    .accesskey = w
options-group-label =
    .value = هەڵبژاردەکان
margin-group-label-inches =
    .value = قەراخ (ئینچ)
margin-group-label-metric =
    .value = قەراخ(ملیمەتر)
margin-top =
    .value = سەرەوە:
    .accesskey = T
margin-top-invisible =
    .value = سەرەوە:
margin-bottom =
    .value = خوارەوە:
    .accesskey = B
margin-bottom-invisible =
    .value = خوارەوە:
margin-left =
    .value = چەپ:
    .accesskey = L
margin-left-invisible =
    .value = چەپ:
margin-right =
    .value = ڕاست
    .accesskey = R
margin-right-invisible =
    .value = ڕاست:
header-footer-label =
    .value = سەرپەڕ و پێپەڕ
hf-left-label =
    .value = چەپ:
hf-center-label =
    .value = ناوەڕاست:
hf-right-label =
    .value = ڕاست:
header-left-tip =
    .tooltiptext = سەرپەڕی چەپ
header-center-tip =
    .tooltiptext = سەرپەڕی ناوەڕاست
header-right-tip =
    .tooltiptext = سەرپەڕی ڕاست
footer-left-tip =
    .tooltiptext = پێپەڕی چەپ
footer-center-tip =
    .tooltiptext = پێپەڕی ناوەڕاست
footer-right-tip =
    .tooltiptext = پێپەڕی ڕاست
hf-blank =
    .label = --blank--
hf-title =
    .label = سەردێڕ
hf-url =
    .label = بەستەر
hf-date-and-time =
    .label = بەروار/کات
hf-page =
    .label = پەڕەی #
hf-page-and-total =
    .label = پەڕەی # لە #
hf-custom =
    .label = دڵخواز…
print-preview-window =
    .title = پێشبینی چاپ
print-title =
    .value = سەردێڕ:
print-preparing =
    .value = ئامادەکردن…
print-progress =
    .value = ڕەوت:
print-window =
    .title = چاپکردن
print-complete =
    .value = چاپکردن تەواو بوو.

# Variables
# $percent (integer) - Number of printed percentage
print-percent =
    .value = { $percent }٪
dialog-cancel-label = پاشگەزبوونەوە
dialog-close-label = داخستن
