# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Tempo esgotado
openFile = Abrir ficheiro
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Buscar "%2$S" en %1$S
contextMenuSearch.accesskey = B
contextMenuPrivateSearch = Buscar nunha xanela privada
contextMenuPrivateSearch.accesskey = h
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Buscar con %S nunha xanela privada
contextMenuPrivateSearchOtherEngine.accesskey = h
bookmarkAllTabsDefault = [Nome do cartafol]
unsignedAddonsDisabled.message = Desactiváronse un ou máis complementos instalados porque non foi posíbel verificalos.
unsignedAddonsDisabled.learnMore.label = Máis información
unsignedAddonsDisabled.learnMore.accesskey = f
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Último acceso %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = Ligazóns %S://
crashedpluginsMessage.title = Fallou o engadido %S.
crashedpluginsMessage.reloadButton.label = Recargar a páxina
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = Enviar un informe de falla
crashedpluginsMessage.submitButton.accesskey = E
crashedpluginsMessage.learnMore = Saber máis…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Quizais quería ir a %S?
keywordURIFixup.goTo = Si, abrir %S
keywordURIFixup.goTo.accesskey = S
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Actualizar á %S
update.downloadAndInstallButton.accesskey = u
menuOpenAllInTabs.label = Abrir todo en lapelas
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Recargar a páxina
tabHistory.goBack = Retroceder a esta páxina
tabHistory.goForward = Avanzar a esta páxina
# URL Bar
pasteAndGo.label = Pegar e ir
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Recargar a páxina actual (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Deter a carga desta páxina (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Restabelecer a ampliación (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Conmutar a vista de lectura (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, restablecer o nivel de zoom
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Amosar os marcadores (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Amosar o progreso das descargas activas (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Abrir unha nova xanela (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Abrir unha nova lapela (%S)
newTabContainer.tooltip = Abra unha lapela nova (%S)\n Manteña premida para abrir unha lapela de contedores nova
newTabAlwaysContainer.tooltip = Seleccione contedor para abrir unha nova lapela
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Permitir que %S empregue os datos da súa imaxe de lenzo de HTML5?
canvas.siteprompt2.warning = Pódese empregar para identificar o seu computador univocamente.
canvas.block = Bloquear
canvas.block.accesskey = B
canvas.allow2 = Permitir
canvas.allow2.accesskey = A
canvas.remember2 = Lembrar esta decisión
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Verificado por: %S
identity.identified.verified_by_you = Engadiu unha excepción de seguranza para este sitio
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Certificado emitido para: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Inseguro
identity.notSecure.tooltip = A conexión non é segura
identity.extension.label = Extensión (%S)
identity.extension.tooltip = Cargada pola extensión: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Reducir (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Restabelecer a ampliación (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Ampliar (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Cortar (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Copiar (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Pegar (%S)
geolocation.allow = Permitir
geolocation.allow.accesskey = A
geolocation.block = Bloquear
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Isto abrirá a configuración de localización do sistema. Concédelle permiso de localización a %S.
geolocation.shareWithSite4 = Permitir que %S acceda a súa localización?
geolocation.shareWithFile4 = Permitir que este ficheiro local acceda á súa localización?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Permitir que %1$S lle dea permiso a %2$S para acceder á súa posición?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Outorgar a %S permiso de localización na configuración do sistema.
geolocation.systemSettingsTitle = Agardando permiso de localización
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = O sistema pedirache que concedas este permiso a %S.
geolocation.remember = Lembrar esta decisión
# Virtual Reality Device UI
xr.allow2 = Permitir
xr.allow2.accesskey = A
xr.block = Bloquear
xr.block.accesskey = B
xr.shareWithSite4 = Permitir que %S acceda a dispositivos de realidade virtual? Isto pode expoñer información confidencial.
xr.shareWithFile4 = Permitir que este ficheiro local acceda a dispositivos de realidade virtual? Isto pode expor información confidencial.
xr.remember = Lembrar esta decisión
# Persistent storage UI
persistentStorage.allow = Permitir
persistentStorage.allow.accesskey = P
persistentStorage.block.label = Bloquear
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Permitir que %S almacene datos en almacenamento persistente?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Permitir
webNotifications.allow2.accesskey = A
webNotifications.notNow = Agora non
webNotifications.notNow.accesskey = n
webNotifications.never = Non permitir nunca
webNotifications.never.accesskey = u
webNotifications.alwaysBlock = Bloquear sempre
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = Bloquear
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Permitir que %S envíe notificacións?
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Sáqueme de aquí!
safebrowsing.getMeOutOfHereButton.accessKey = q
safebrowsing.deceptiveSite = Sitio enganoso!
safebrowsing.notADeceptiveSiteButton.label = Non é un sitio enganoso…
safebrowsing.notADeceptiveSiteButton.accessKey = g
safebrowsing.reportedAttackSite = Sitio denunciado como atacante!
safebrowsing.notAnAttackButton.label = Non é un sitio atacante…
safebrowsing.notAnAttackButton.accessKey = A
safebrowsing.reportedUnwantedSite = Sitio denunciado de servir software non desexado!
safebrowsing.reportedHarmfulSite = Sitio reportado como danoso!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Buscar %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Reiniciar %S no modo de resolución de problemas?
troubleshootModeRestartPromptMessage = As súas extensións, temas e axustes personalizados serán desactivadas temporalmente.
troubleshootModeRestartButton = Reiniciar
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Esta páxina está a enlentecer o %1$S. Para acelerar o navegador, pare esta páxina.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Unha páxina web está a enlentecer o %1$S. Para acelerar o navegador, pare esa páxina.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = «%1$S» está a enlentecer o %2$S. Para acelerar o navegador, pare esa páxina.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = «%1$S» está a enlentecer o %2$S. Para acelerar o navegador, pare esa extensión.
processHang.add-on.learn-more.text = Máis información
processHang.button_stop2.label = Parar
processHang.button_stop2.accessKey = S
processHang.button_debug.label = Depurar o script
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Amosar a xanela en pantalla completa (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Mover a barra lateral á esquerda
sidebar.moveToRight = Mover a barra lateral á dereita
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Debe activar o DRM para reproducir algún son ou vídeo nesta páxina.
emeNotifications.drmContentDisabled.button.label = Activar DRM
emeNotifications.drmContentDisabled.button.accesskey = A
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S está instalando compoñentes necesarios para reproducir o son ou vídeo nesta páxina. Tente de novo máis tarde.
emeNotifications.unknownDRMSoftware = Descoñecido
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Personalizar %S
decoder.noCodecs.button = Aprender como
decoder.noCodecs.accesskey = S
decoder.noCodecsLinux.message = Para reproducir o vídeo, precisa instalar os códecs de vídeo necesarios.
decoder.noHWAcceleration.message = Para mellorar a calidade do vídeo, precisa instalar Microsoft’s Media Feature Pack.
decoder.noPulseAudio.message = Para reproducir o son, precisa instalar o software necesario de PulseAudio.
decoder.unsupportedLibavcodec.message = A biblioteca libavcodec podería ser vulnerábel ou non compatíbel, e debería actualizarse para reproducir vídeos.
decoder.decodeError.message = Produciuse un erro ao descodificar un recurso multimedia.
decoder.decodeError.button = Informar dun fallo no sitio
decoder.decodeError.accesskey = I
decoder.decodeWarning.message = Produciuse un erro recuperable ao descodificar un recurso multimedia.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Debe identificarse nesta rede para acceder á Internet.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Abrir a páxina de acceso á rede
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Permisos para %S
permissions.remove.tooltip = Borrar este permiso e preguntar de novo
permissions.fullscreen.promptCanceled = Canceláronse as solicitudes de permiso pendentes: non se deben emitir solicitudes de permiso antes de entrar a DOM en pantalla completa.
permissions.fullscreen.fullScreenCanceled = Saíu de pantalla completa de DOM: non se deben emitir solicitudes de permiso mentres se atopa en pantalla completa de DOM.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64 bits
aboutDialog.architecture.thirtyTwoBit = 32 bits
midi.allow.label = Permitir
midi.allow.accesskey = A
midi.block.label = Bloquear
midi.block.accesskey = B
midi.remember = Lembrar esta decisión
midi.shareWithFile = Permitir que este ficheiro local acceda aos seus ficheiros de MIDI?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Permitir que %S acceda aos seus dispositivos de MIDI?
midi.shareSysexWithFile = Permitir que este ficheiro local acceda aos seus dispositivos de MIDI e envíe/reciba mensaxes SysEx?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Permitir que %S acceda aos seus dispositivos de MIDI e envíe/reciba mensaxes SysEx?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Atrás
storageAccess1.Allow.label = Permitir
storageAccess1.Allow.accesskey = A
storageAccess1.DontAllow.label = Bloquear
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Permitir que %1$S empregue as súas cookies en %2$S?
storageAccess1.hintText = Será mellor que bloque o acceso se non ten claro para que necesita %1$S os seus datos.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Buscar «%S» na web
