# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Neno malu { $host }…
network-connection-status-connected = Okube bot { $host }…
network-connection-status-sending-request = Cwalo kwac bot { $host }…
network-connection-status-transferring-data = Kobo tic ki bot { $host }…
network-connection-status-connecting = Tye kakube bot { $host }…
network-connection-status-read = Kwan { $host }
network-connection-status-wrote = Co { $host }
network-connection-status-waiting = Kuro pi { $host }…
network-connection-status-looked-up = Oneno malo { $host }…
network-connection-status-tls-handshake = Timo kube me TLS i { $host }…
network-connection-status-tls-handshake-finished = Kube me TLS otum pi { $host }…
