# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = یہ صفحہ ایک نئے محل وقوع کی طرف بھیجا جا رہا ہے۔ کیا آپ اپنا ٹائپ کیے ہوئے فارم کوائف نئے محل وقوع پر دوبارہ بھیجنا چاہتے ہیں؟
# Directory listing strings
DirTitle = %1$S کا اشاریہ
DirGoUp = اعلیٰ تر سطح ڈائریکٹری تک
ShowHidden = پوشیدہ آبجیکٹ دکھائیں
DirColName = نام
DirColSize = سائز
DirColMTime = آخری بار ترمیم کردہ
DirFileLabel = مسل:
UnsafeUriBlocked = %1$S پر ذریعہ محفوظ شدہ براؤزنگ کی طرف سے روک دیا گیا۔
CookieBlockedByPermission = "%1$S" پر کوکیز یا اسٹوریج تک رسائی کی درخواست کو کسٹم کوکی کی اجازت کی وجہ سے روک دیا گیا تھا۔
CookieBlockedAll = %1$Sپر کوکی یا اسٹوریج تک رسائی کی درخواست مسدود کردی گئی تھی کیونکہ ہم اسٹوریج تک رسائی کی تمام درخواستوں کو مسدود کررہے ہیں۔
