# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = A procurar { $host }…
network-connection-status-connected = Ligação estabelecida a { $host }…
network-connection-status-sending-request = A enviar pedido a { $host }…
network-connection-status-transferring-data = A transferir dados de { $host }…
network-connection-status-connecting = A estabelecer ligação a { $host }…
network-connection-status-read = Leu { $host }
network-connection-status-wrote = Escrito { $host }
network-connection-status-waiting = A aguardar por { $host }…
network-connection-status-looked-up = Procurou { $host }…
network-connection-status-tls-handshake = A realizar um handshake TLS para { $host }…
network-connection-status-tls-handshake-finished = O handshake TLS concluiu para { $host }…
