# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host }-г хайж байна…
network-connection-status-connected = { $host }-д холбогдсон…
network-connection-status-sending-request = { $host } рүү хүсэлт илгээж байна…
network-connection-status-transferring-data = { $host }-с өгөгдөл дамжуулж байна…
network-connection-status-connecting = { $host }-тай холбогдож байна…
network-connection-status-read = Уншсан { $host }
network-connection-status-wrote = Бичсэн { $host }
network-connection-status-waiting = { $host }-г хүлээж байна…
network-connection-status-looked-up = { $host }-г хайж байна…
