# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Salve
dialogTitleAddBookmark = Gnûf segnelibri
dialogTitleAddMulti = Gnûfs segnelibris
dialogTitleEdit = Proprietâts par “%S”
dialogTitleAddNewBookmark2 = Zonte segnelibri
dialogTitleEditBookmark = Modifiche “%S”
dialogTitleEditBookmark2 = Modifiche segnelibri
dialogTitleAddBookmarkFolder = Zonte cartele di segnelibris
dialogTitleEditBookmarkFolder = Modifiche cartele di segnelibris
bookmarkAllTabsDefault = [Non de cartele]
newFolderDefault = Gnove cartele
newBookmarkDefault = Gnûf segnelibri
