# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = विझार्ड आयात करा
import-from =
    { PLATFORM() ->
        [windows] पर्याय, वाचनखूणा, इतिहास, पासवर्ड व इतर माहिती येथून आयात करा:
       *[other] याअाधी वापरात असलेली आवडीनिवडी, वाचनखूणा, इतिहास, पासवर्ड व इतर) माहिती येथून आयात करा:
    }
import-from-bookmarks = वाचनखूणा येथून आयात करा:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-nothing =
    .label = काहिही आयात करू नका
    .accesskey = D
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = x
import-from-360se =
    .label = 360 सुरक्षित ब्राउझर
    .accesskey = 3
no-migration-sources = वाचनखूणा, इतिहास किंवा पासवर्ड विषयी माहिती देणारे कुठलेही कार्यक्रम आढळले नाही.
import-source =
    .label = आवडीनिवडी आणि माहिती येथून आयात करा
import-items-title =
    .label = आयात करण्यासाठीचे घटक
import-items-description = कोणते घटक आयात करायचे ते निवडा:
import-migrating-title =
    .label = आयात करत आहे…
import-migrating-description = खालील घटक सध्या आयात केले जात आहेत…
import-select-profile-title =
    .label = निवडसंच निवडा
import-select-profile-description = आयात करण्यासाठी पुढील निवडसंच उपलब्ध आहेत:
import-done-title =
    .label = आयात करणे पुर्ण झाले
import-done-description = खालील घटक यशस्वीरित्या आयात केले गेले:
import-close-source-browser = कृपया पुढे जायच्या पहिले निवडलेला ब्राउझर बंद आहे याची खात्री करा.
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = { $source } पासून
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-safari = सफारि
source-name-canary = Google Chrome Canary
source-name-chrome = गूगल क्रोम
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 सुरक्षित ब्राउझर
imported-safari-reading-list = सूची वाचत आहे (सफारीपासून)
imported-edge-reading-list = सूची वाचत आहे (Edge मधून)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = इंटरनेट पर्याय
    .value = इंटरनेट पर्याय
browser-data-edge-1 =
    .label = सेटिंग
    .value = सेटिंग
browser-data-safari-1 =
    .label = प्राधान्यक्रम
    .value = प्राधान्यक्रम
browser-data-chrome-1 =
    .label = प्राधान्यक्रम
    .value = प्राधान्यक्रम
browser-data-canary-1 =
    .label = प्राधान्यक्रम
    .value = प्राधान्यक्रम
browser-data-360se-1 =
    .label = प्राधान्यक्रम
    .value = प्राधान्यक्रम
browser-data-ie-2 =
    .label = कूकिज
    .value = कूकिज
browser-data-edge-2 =
    .label = कूकिज
    .value = कूकिज
browser-data-safari-2 =
    .label = कूकिज
    .value = कूकिज
browser-data-chrome-2 =
    .label = कूकिज
    .value = कूकिज
browser-data-canary-2 =
    .label = कूकिज
    .value = कूकिज
browser-data-firefox-2 =
    .label = कूकिज
    .value = कूकिज
browser-data-360se-2 =
    .label = कूकिज
    .value = कूकिज
browser-data-ie-4 =
    .label = इतिहास संचार
    .value = इतिहास संचार
browser-data-edge-4 =
    .label = इतिहास संचार
    .value = इतिहास संचार
browser-data-safari-4 =
    .label = इतिहास संचार
    .value = इतिहास संचार
browser-data-chrome-4 =
    .label = ब्राउजिंग इतिहास
    .value = ब्राउजिंग इतिहास
browser-data-canary-4 =
    .label = ब्राउजिंग इतिहास
    .value = ब्राउजिंग इतिहास
browser-data-firefox-history-and-bookmarks-4 =
    .label = इतिहास व वाचनखूणांचे संचारन
    .value = इतिहास व वाचनखूणांचे संचारन
browser-data-360se-4 =
    .label = इतिहास संचार
    .value = इतिहास संचार
browser-data-ie-8 =
    .label = प्रपत्र इतिहास साठवा
    .value = प्रपत्र इतिहास साठवा
browser-data-edge-8 =
    .label = साठवलेला फॉर्म इतिहास
    .value = साठवलेला फॉर्म इतिहास
browser-data-safari-8 =
    .label = प्रपत्र इतिहास साठवा
    .value = प्रपत्र इतिहास साठवा
browser-data-chrome-8 =
    .label = इतिहासातून साठवले
    .value = इतिहासातून साठवले
browser-data-canary-8 =
    .label = इतिहासातून साठवले
    .value = इतिहासातून साठवले
browser-data-firefox-8 =
    .label = इतिहासातून साठवलेले
    .value = इतिहासातून साठवलेले
browser-data-360se-8 =
    .label = साठवलेला फॉर्म इतिहास
    .value = साठवलेला फॉर्म इतिहास
browser-data-ie-16 =
    .label = साठवलेले पासवर्ड
    .value = साठवलेले पासवर्ड
browser-data-edge-16 =
    .label = साठवलेले पासवर्ड
    .value = साठवलेले पासवर्ड
browser-data-safari-16 =
    .label = साठवलेले पासवर्ड
    .value = साठवलेले पासवर्ड
browser-data-chrome-16 =
    .label = साठवलेले पासवर्ड
    .value = साठवलेले पासवर्ड
browser-data-canary-16 =
    .label = साठवलेले पासवर्ड
    .value = साठवलेले पासवर्ड
browser-data-firefox-16 =
    .label = साठवलेले पासवर्ड
    .value = साठवलेले पासवर्ड
browser-data-360se-16 =
    .label = साठवलेले पासवर्ड
    .value = साठवलेले पासवर्ड
browser-data-ie-32 =
    .label = पसंतीचे
    .value = पसंतीचे
browser-data-edge-32 =
    .label = पसंतीचे
    .value = पसंतीचे
browser-data-safari-32 =
    .label = वाचनखूणा
    .value = वाचनखूणा
browser-data-chrome-32 =
    .label = वाचनखूणा
    .value = वाचनखूणा
browser-data-canary-32 =
    .label = वाचनखूणा
    .value = वाचनखूणा
browser-data-360se-32 =
    .label = वाचनखूणा
    .value = वाचनखूणा
browser-data-ie-64 =
    .label = इतर माहिती
    .value = इतर माहिती
browser-data-edge-64 =
    .label = इतर माहिती
    .value = इतर माहिती
browser-data-safari-64 =
    .label = इतर माहिती
    .value = इतर माहिती
browser-data-chrome-64 =
    .label = इतर डाटा
    .value = इतर डाटा
browser-data-canary-64 =
    .label = इतर डाटा
    .value = इतर डाटा
browser-data-firefox-other-64 =
    .label = इतर माहिती
    .value = इतर माहिती
browser-data-360se-64 =
    .label = इतर माहिती
    .value = इतर माहिती
browser-data-firefox-128 =
    .label = चौकट व टॅब
    .value = चौकट व टॅब
