# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

e2e-intro-description = Pro inviar messages cifrate o signate digitalmente, tu debe configurar un technologia de cryptographia OpenPGP o S/MIME.
openpgp-keygen-title-label =
    .title = Generar clave OpenPGP
openpgp-cancel-key =
    .label = Cancellar
    .tooltiptext = Cancellar generation de clave
openpgp-key-gen-expiry-title =
    .label = Expiration del clave
openpgp-key-gen-expire-label = Le clave expirara in:
openpgp-key-gen-days-label =
    .label = dies
openpgp-key-gen-months-label =
    .label = menses
openpgp-key-gen-years-label =
    .label = annos
openpgp-key-gen-no-expiry-label =
    .label = Le clave non expira
openpgp-key-gen-key-size-label = Dimension del clave:
openpgp-key-gen-console-label = Generation del clave
openpgp-key-gen-key-type-label = Typo de clave
openpgp-key-gen-key-type-rsa =
    .label = RSA
openpgp-key-gen-key-type-ecc =
    .label = ECC (curva elliptic)
openpgp-advanced-prefs-button-label =
    .label = Avantiate…
openpgp-keygen-desc = <a data-l10n-name="openpgp-keygen-desc-link">Nota: Le generation de clave pote occupar usque plure minutas pro completar.</a> Non exir del application durante que es in curso le generation del clave. Navigar activemente o exequer operationes intensive pro le disco durante le generation del clave replena le 'piscina aleatori' e accelera le procedura. Tu sera alertate quando generation del clave es completate.
openpgp-key-expiry-label =
    .label = Date de expiration
openpgp-key-id-label =
    .label = ID de clave
openpgp-cannot-change-expiry = La structura de iste clave es complexe, la cambio de su data de expiration non es supportate.
openpgp-key-man-title =
    .title = Gestor de clave OpenPGP
openpgp-key-man-generate =
    .label = Nove par de claves
    .accesskey = N
openpgp-key-man-gen-revoke =
    .label = Certificato de revocation
    .accesskey = r
openpgp-key-man-ctx-gen-revoke-label =
    .label = Genera e salva le certificato de revocation
openpgp-key-man-file-menu =
    .label = File
    .accesskey = F
openpgp-key-man-edit-menu =
    .label = Rediger
    .accesskey = R
openpgp-key-man-view-menu =
    .label = Vider
    .accesskey = V
openpgp-key-man-generate-menu =
    .label = Generar
    .accesskey = G
openpgp-key-man-keyserver-menu =
    .label = Servitor de clave
    .accesskey = c
openpgp-key-man-import-public-from-file =
    .label = Importar clave(s) public ex file
    .accesskey = e
openpgp-key-man-import-secret-from-file =
    .label = Importar clave(s) secrete ex file
openpgp-key-man-import-sig-from-file =
    .label = Importar revocation(es) ex file
openpgp-key-man-import-from-clipbrd =
    .label = Importar clave(s) ex area de transferentia
    .accesskey = t
openpgp-key-man-import-from-url =
    .label = Importar clave(s) ex URL
    .accesskey = U
openpgp-key-man-export-to-file =
    .label = Exportar clave(s) public a file
    .accesskey = a
openpgp-key-man-send-keys =
    .label = Inviar clave(s) public per email
    .accesskey = e
openpgp-key-man-backup-secret-keys =
    .label = Reservar clave(s) public in file
    .accesskey = R
openpgp-key-man-discover-cmd =
    .label = Discoperir claves online
    .accesskey = D
openpgp-key-man-discover-prompt = Pro discoperir claves OpenPGP online, sur servitores-de-claves o per le protocollo WKD, Insere un adresse email o a ID de clave.
openpgp-key-man-discover-progress = In cerca…
openpgp-key-copy-key =
    .label = Copiar clave public
    .accesskey = C
openpgp-key-export-key =
    .label = Exportar un clave public a file
    .accesskey = x
openpgp-key-backup-key =
    .label = Reservar un clave public in un file
    .accesskey = R
openpgp-key-send-key =
    .label = Inviar un clave public per email
    .accesskey = I
openpgp-key-man-copy-to-clipbrd =
    .label = Copiar un clave public al area de transferentia
    .accesskey = C
openpgp-key-man-ctx-expor-to-file-label =
    .label = Exportar claves a file
openpgp-key-man-ctx-copy-to-clipbrd-label =
    .label = Copiar un clave public al area de transferentia
openpgp-key-man-close =
    .label = Clauder
openpgp-key-man-del-key =
    .label = Deler le clave(s)
    .accesskey = D
openpgp-delete-key =
    .label = Deler le clave
    .accesskey = D
openpgp-key-man-revoke-key =
    .label = Revocar le clave
    .accesskey = R
openpgp-key-man-key-props =
    .label = Proprietates del clave
    .accesskey = P
openpgp-key-man-key-more =
    .label = Plus
    .accesskey = P
openpgp-key-man-view-photo =
    .label = ID de photo
    .accesskey = I
openpgp-key-man-ctx-view-photo-label =
    .label = Vider ID photo
openpgp-key-man-user-id-label =
    .label = Nomine
openpgp-key-man-fingerprint-label =
    .label = Dactylogramma
openpgp-key-man-filter-label =
    .placeholder = Cercar claves
openpgp-key-man-select-all-key =
    .key = e
openpgp-key-man-key-details-key =
    .key = I
openpgp-key-details-title =
    .title = Proprietates del clave
openpgp-key-details-signatures-tab =
    .label = Certificationes
openpgp-key-details-structure-tab =
    .label = Structura
openpgp-key-details-uid-certified-col =
    .label = ID usator/Certificate per
openpgp-key-details-user-id2-label = Presumite proprietario de clave
openpgp-key-details-id-label =
    .label = ID
openpgp-key-details-key-type-label = Typo
openpgp-key-details-algorithm-label =
    .label = Algorithmo
openpgp-key-details-size-label =
    .label = Dimension
openpgp-key-details-created-label =
    .label = Crear
openpgp-key-details-created-header = Create
openpgp-key-details-expiry-label =
    .label = Date de expiration
openpgp-key-details-expiry-header = Date de expiration
openpgp-key-details-usage-label =
    .label = Uso
openpgp-key-details-fingerprint-label = Dactylogramma
openpgp-key-details-sel-action =
    .label = Eliger le action…
    .accesskey = E
openpgp-card-details-close-window-label =
    .buttonlabelaccept = Clauder
openpgp-acceptance-label =
    .label = Tu acceptation
openpgp-personal-yes-label =
    .label = Si, tractar iste clave como clave personal.
openpgp-copy-cmd-label =
    .label = Copiar

## e2e encryption settings

openpgp-add-key-button =
    .label = Adder clave…
    .accesskey = A
e2e-learn-more = Saper plus
openpgp-keygen-success = Clave OpenPGP generate con successo!
openpgp-keygen-import-success = Clave OpenPGP importate con successo!
openpgp-keygen-external-success = ID clave GnuPG externe salvate!

## OpenPGP Key selection area

openpgp-radio-none =
    .label = Nulle
openpgp-key-expired-image =
    .tooltiptext = Clave expirate
openpgp-key-expand-section =
    .tooltiptext = Plus de informationes
openpgp-key-revoke-title = Revocar le clave
openpgp-key-edit-title = Cambiar claves OpenPGP
openpgp-manager-button =
    .label = Gestor de clave OpenPGP
    .accesskey = c
openpgp-key-remove-external =
    .label = Remover clave GnuPG externe
    .accesskey = e
key-external-label = Clave GnuPG externe
# Strings in keyDetailsDlg.xhtml
key-type-public = clave public
key-type-primary = clave primari
key-type-subkey = sub-clave
key-type-pair = copula de claves (clave secrete e clave public)
key-expiry-never = nunquam
key-usage-encrypt = Cryptar
key-usage-sign = Signar
key-usage-certify = Certificar
key-usage-authentication = Authentication
key-does-not-expire = Le clave non expira
# Strings in mimeDecrypt.jsm
mime-decrypt-encrypted-part-attachment-label = Parte de message cryptate
# Strings in keyserver.jsm
keyserver-error-aborted = Abortate
keyserver-error-unknown = Un error incognite occurreva
keyserver-error-unavailable = Servitor-de-claves indisponibile
keyserver-error-security-error = Le servitor non supporta accesso cryptate.
keyserver-error-certificate-error = Le certificato del servitor-de-claves non es valide.
keyserver-error-unsupported = Le servitor-de-claves non es disponibile.
expiry-open-key-manager = Aperir le gestor de clave OpenPGP
expiry-open-key-properties = Aperir proprietates del clave
# Strings filters.jsm
filter-folder-required = Tu debe eliger un plica de destination.
filter-term-pgpencrypted-label = Cryptate OpenPGP
import-info-bits = Bits
import-info-created = Create
import-info-fpr = Dactylogramma
import-info-no-keys = Nulle claves importate
# Strings in enigmailKeyManager.js
import-from-clip = Vole tu importar alcun claves ab area de transferentia?
import-from-url = Discargar clave public ex iste URL:
key-man-loading-keys = Cargamento claves, attende…
save-keys-ok = Claves salvate con successo.
save-keys-failed = Salvamento claves fallite!
general-error = Error: { $reason }
dlg-button-delete = &Deler

## Account settings export output

# Strings in gnupg-keylist.jsm
keyring-photo = Photo
key-man-button-revoke-key = &Revocar clave
# Strings in keyRing.jsm & decryption.jsm
key-man-button-import = &Importar
delete-key-title = Deler clave OpenPGP
# Strings used in trust.jsm
key-valid-unknown = incognite
key-valid-invalid = non valide
key-valid-disabled = disactivate
key-valid-revoked = revocate
key-valid-expired = expirate
key-trust-marginal = marginal
key-trust-group = (gruppo)
# Strings used in commonWorkflows.js
import-key-file = Importar le file clave OpenPGP
import-rev-file = Importar le le revocation del file OpenPGP
gnupg-file = Files GnuPG
import-keys-failed = Importation de claves fallite!
passphrase-prompt = Insere le phrase contrasigno que disbloca le sequente clave: { $key }
# Strings used in enigmailKeygen.js
save-revoke-cert-as = Crear e salvar le certificato de revocation
