#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

# LOCALIZATION NOTE: Some of these URLs are currently 404s, but should be coming
# online shortly.

# LOCALIZATION NOTE (bookmarks_title):
# title for the folder that will contains the default bookmarks
#define bookmarks_title 모바일

# LOCALIZATION NOTE (bookmarks_aboutBrowser):
# link title for about:fennec
#define bookmarks_aboutBrowser Firefox 소개

# LOCALIZATION NOTE (bookmarks_addons):
# link title for https://addons.mozilla.org/en-US/mobile
#define bookmarks_addons Firefox: 부가 기능

# LOCALIZATION NOTE (bookmarks_support):
# link title for https://mobile.support.mozilla.com
#define bookmarks_support Firefox: 고객 지원

# LOCALIZATION NOTE (bookmarks_marketplace):
# link title for https://marketplace.firefox.com
#define bookmarks_marketplace Firefox Marketplace

#unfilter emptyLines
