# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Selvitetään verkko-osoitetta { $host }…
network-connection-status-connected = Yhteys muodostettu osoitteeseen { $host }…
network-connection-status-sending-request = Lähetetään pyyntöä osoitteeseen { $host }…
network-connection-status-transferring-data = Siirretään dataa osoitteesta { $host }…
network-connection-status-connecting = Muodostetaan yhteyttä osoitteeseen { $host }…
network-connection-status-read = { $host } luettu
network-connection-status-wrote = { $host } kirjoitettu
network-connection-status-waiting = Odotetaan vastausta osoitteesta { $host }…
network-connection-status-looked-up = Selvitettiin verkko-osoite { $host }…
network-connection-status-tls-handshake = Suoritetaan TLS-kättelyä palvelimeen { $host }…
network-connection-status-tls-handshake-finished = TLS-kättely palvelimelle { $host } valmistui…
