#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're 

# live.


#define bookmarks_title Boekmerke


#define bookmarks_heading Boekmerke


# LOCALIZATION NOTE (bookmarks_addons):


# link title for https://en-US.add-ons.mozilla.com/en-US/firefox/bookmarks/


#define bookmarks_addons Kry boekmerkbyvoegings


#define bookmarks_toolbarfolder Boekmerknutsbalkvouer


#define bookmarks_toolbarfolder_description Voeg boekmerke by hierdie gids sodat hulle vertoon op die Boekmerknutsbalk


# LOCALIZATION NOTE (getting_started):


# link title for http://en-US.www.mozilla.com/en-US/firefox/central/


#define getting_started Hoe om te begin


# LOCALIZATION NOTE (latest_headlines):


# link title for the live bookmarks sample, a redirect on


# http://en-US.fxfeeds.mozilla.com/en-US/firefox/headlines.xml


# Changing the redirect is subject to approval of l10n-drivers.


#define latest_headlines Jongste hooftrekke


# LOCALIZATION NOTE (firefox_heading):


# Firefox links folder name


#define firefox_heading Mozilla Firefox


# LOCALIZATION NOTE (firefox_help):


# link title for http://en-US.www.mozilla.com/en-US/firefox/help/


#define firefox_help Hulp en tutoriale


# LOCALIZATION NOTE (firefox_customize):


# link title for http://en-US.www.mozilla.com/en-US/firefox/customize/


#define firefox_customize Pasmaak Firefox


# LOCALIZATION NOTE (firefox_community):


# link title for http://en-US.www.mozilla.com/en-US/firefox/community/


#define firefox_community Raak betrokke


# LOCALIZATION NOTE (firefox_about):


# link title for http://en-US.www.mozilla.com/en-US/firefox/about/


#define firefox_about Aangaande ons


#unfilter emptyLines
