# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = క్రింది ప్రయోజనాల కొరకు “%S” ను నమ్మాలని అనుకొంటున్నారా?
unnamedCA = ధృవీకరణపత్రం అధారిటీ (పేరులేదు)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = ఈ ధృవీకరణపత్రం బ్యాకప్‌ను ఎన్క్రిప్టు చేయుటకు ఉపయోగించిన సంకేతపదమును ప్రవేశపెట్టుము:
# Page Info
pageInfo_NoEncryption = అనుసంధానం గుప్తీకరింపబడలేదు
pageInfo_Privacy_None1 = వెబ్ సైటు %S మీరు దర్శించుతున్నటువంటి పేజీకొరకు ఎన్క్రిప్షన్ మద్దతునీయదు.
pageInfo_Privacy_None2 = ఎన్క్రిప్షన్ చేయకుండా సమాచారాన్ని అంతర్జాలములో పంపితే అది బదిలీకరించుతున్నప్పుడు వేరే వారిద్వారా చూడబడుతుంది. 
pageInfo_Privacy_None4 = మీరు చూస్తున్న పేజీ అంతర్జాలం ద్వారా బదిలీ కాక మునుపు ఎన్‌క్రిప్ట్ కాలేదు.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = కనెక్షన్ యెన్క్రిప్ట్ చేయబడింది (%1$S, %2$S బిట్ కీలు, %3$S)
pageInfo_BrokenEncryption = బ్రోకెన్ ఎన్క్రిప్షన్ (%1$S, %2$S బిట్ కీలను, %3$S)
pageInfo_Privacy_Encrypted1 = మీరు చూస్తున్న పేజీ అంతర్జాలం ద్వారా బదిలీ అయ్యే ముందే ఎన్‌క్రిప్ట్ అయింది.
pageInfo_Privacy_Encrypted2 = ఎన్క్రిప్షన్ కంప్యూటర్లు మధ్య ప్రయాణించే సమాచారం వీక్షించడానికి అనధికార వ్యక్తులు కష్టతరం చేస్తోంది. ఇది నెట్వర్క్ వ్యాప్తంగా వెళ్లాయి ఎవరైనా ఈ పేజీ చదివే అందువలన అవకాశం ఉంది.
pageInfo_MixedContent = అనుసంధానం పరోక్షంగా ఎన్క్రిప్ట్ చేయబడింది.
pageInfo_MixedContent2 = అంతర్జాలమునందు బదిలీకరించకమునుపు మీరు చూస్తున్నటువంటి పేజీయొక్క పార్టులు ఎన్క్రిప్టుచేయబడలేదు.
pageInfo_WeakCipher = ఈ వెబ్సైట్కు మీ కనెక్షన్ బలహీన ఎన్క్రిప్షన్ ను ఉపయోగిస్తుంది మరియు అది ప్రైవేట్ కాదు. ఇతర ప్రజలు మీ సమాచారాన్ని వీక్షించేందుకు లేదా వెబ్సైట్ యొక్క ప్రవర్తనను మార్చవచ్చు.
pageInfo_CertificateTransparency_Compliant = ఈ వెబ్ సైటు ధృవపత్ర పారదర్శకత విధానానికి లోబడింది.
# Token Manager
password_not_set = (అమర్చబడ లేదు)
