#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

# LOCALIZATION NOTE: Some of these URLs are currently 404s, but should be coming
# online shortly.

# LOCALIZATION NOTE (bookmarks_title):
# title for the folder that will contains the default bookmarks
#define bookmarks_title Záložky

# LOCALIZATION NOTE (bookmarks_about):
# link title for about:fennec
#define bookmarks_aboutBrowser Firefox: O prohlížeči

# LOCALIZATION NOTE (bookmarks_addons):
# link title for https://addons.mozilla.org/en-US/mobile
#define bookmarks_addons Firefox: Doplňky

# LOCALIZATION NOTE (bookmarks_support):
# link title for https://support.mozilla.org/mobile
#define bookmarks_support Firefox: Podpora

# LOCALIZATION NOTE (bookmarks_aboutHome):
# link title for about:home
#define bookmarks_aboutHome Startovní stránka

#unfilter emptyLines
