# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-connected = Ceangailte le { $host }…
network-connection-status-sending-request = Iarratas á sheoladh chuig { $host }…
network-connection-status-transferring-data = Sonraí á n-aistriú ó { $host }…
network-connection-status-connecting = Ag ceangal le { $host }…
network-connection-status-read = Léadh { $host }
network-connection-status-wrote = Scríobhadh { $host }
network-connection-status-waiting = Ag feitheamh le { $host }…
network-connection-status-looked-up = Cuardaíodh { $host }…
