# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Notice: If you're updating this list, you should also
###         update the list in mozIntl.js.

region-name-ad = Andorra
region-name-af = Afganistan
region-name-ag = Antigua eta Barbuda
region-name-ai = Anguilla
region-name-al = Albania
region-name-am = Armenia
region-name-ao = Angola
region-name-aq = Antartika
region-name-ar = Argentina
region-name-as = Amerikar Samoa
region-name-at = Austria
region-name-au = Australia
region-name-aw = Aruba
region-name-az = Azerbaijan
region-name-ba = Bosnia eta Herzegovina
region-name-bb = Barbados
region-name-bd = Bangladesh
region-name-be = Belgika
region-name-bf = Burkina Faso
region-name-bg = Bulgaria
region-name-bh = Bahrain
region-name-bi = Burundi
region-name-bj = Benin
region-name-bm = Bermuda
region-name-bo = Bolivia
region-name-br = Brasil
region-name-bt = Bhutan
region-name-bv = Bouvet uhartea
region-name-bw = Botswana
region-name-by = Belarus
region-name-bz = Belize
region-name-ca = Kanada
region-name-cc = Cocos (Keeling) Uharteak
region-name-cf = Afrika Erdiko Errepublika
region-name-ch = Suitza
region-name-ck = Cook Uharteak
region-name-cl = Txile
region-name-cm = Kamerun
region-name-cn = Txina
region-name-co = Kolonbia
region-name-cr = Costa Rica
region-name-cu = Kuba
region-name-cx = Christmas Uhartea
region-name-cy = Txipre
region-name-cz = Txekiar errepublika
region-name-de = Alemania
region-name-dj = Djibouti
region-name-dk = Dinamarka
region-name-dm = Dominika
region-name-do = Dominikar errepublika
region-name-dz = Aljeria
region-name-ec = Ekuador
region-name-ee = Estonia
region-name-eg = Egipto
region-name-eh = Mendebaldeko Sahara
region-name-er = Eritrea
region-name-es = Espainia
region-name-et = Etiopia
region-name-fi = Finlandia
region-name-fj = Fidji
region-name-fo = Faroe uharteak
region-name-fr = Frantzia
region-name-ga = Gabon
region-name-gb = Erresuma Batua
region-name-gd = Granada
region-name-ge = Georgia
region-name-gf = Guyana Frantsesa
region-name-gg = Guernsey
region-name-gh = Ghana
region-name-gi = Gibraltar
region-name-gl = Groenlandia
region-name-gn = Ginea
region-name-gp = Guadalupe
region-name-gq = Ekuatore Ginea
region-name-gr = Grezia
region-name-gt = Guatemala
region-name-gu = Guam
region-name-gw = Guinea-Bissau
region-name-gy = Guyana
region-name-hk = Hong Kong
region-name-hm = Heard eta McDonald Uharteak
region-name-hn = Honduras
region-name-hr = Kroazia
region-name-ht = Haiti
region-name-hu = Hungaria
region-name-id = Indonesia
region-name-ie = Irlanda
region-name-il = Israel
region-name-im = Man uhartea
region-name-in = India
region-name-io = Ozeano Indikoko Lurralde Britaniarra
region-name-iq = Irak
region-name-ir = Iran
region-name-is = Islandia
region-name-it = Italia
region-name-je = Jersey
region-name-jm = Jamaika
region-name-jo = Jordania
region-name-jp = Japonia
region-name-ke = Kenya
region-name-kg = Kirgizistan
region-name-kh = Kanbodia
region-name-ki = Kiribati
region-name-km = Comoros
region-name-kn = Saint Kitts eta Nevis
region-name-kw = Kuwait
region-name-ky = Kaiman Uharteak
region-name-kz = Kazakhstan
region-name-la = Laos
region-name-lb = Libano
region-name-lc = Saint Lucia
region-name-li = Liechtenstein
region-name-lk = Sri Lanka
region-name-lr = Liberia
region-name-ls = Lesotho
region-name-lt = Lithuania
region-name-lu = Luxenburgo
region-name-lv = Latvia
region-name-ly = Libia
region-name-ma = Maroko
region-name-mc = Monako
region-name-md = Moldabiako errepublika
region-name-mg = Madagascar
region-name-mh = Marshall Uharteak
region-name-ml = Mali
region-name-mn = Mongolia
region-name-mp = Ipar Mariana Uharteak
region-name-mq = Martinika
region-name-mr = Mauritania
region-name-ms = Montserrat
region-name-mt = Malta
region-name-mu = Maurizio
region-name-mv = Maldivak
region-name-mw = Malawi
region-name-mx = Mexiko
region-name-my = Malasia
region-name-mz = Mozambique
region-name-na = Namibia
region-name-nc = Kaledonia Berria
region-name-ne = Niger
region-name-nf = Norfolk Uharteak
region-name-ng = Nigeria
region-name-ni = Nikaragua
region-name-nl = Herbehereak
region-name-no = Norvegia
region-name-np = Nepal
region-name-nr = Nauru
region-name-nu = Niue
region-name-nz = Zelanda Berria
region-name-om = Oman
region-name-pa = Panama
region-name-pe = Peru
region-name-pf = Polinesia Frantziarra
region-name-pg = Papua Ginea Berria
region-name-ph = Filipinak
region-name-pk = Pakistan
region-name-pl = Polonia
region-name-pm = Saint-Pierre eta Mikelune
region-name-pr = Puerto Rico
region-name-pt = Portugal
region-name-pw = Palau
region-name-py = Paraguai
region-name-qa = Katar
region-name-re = Reunion
region-name-ro = Errumania
region-name-rw = Rwanda
region-name-sa = Saudi Arabia
region-name-sb = Salomon Uharteak
region-name-sc = Seychelles
region-name-sd = Sudan
region-name-se = Suedia
region-name-sg = Singapur
region-name-si = Eslovenia
region-name-sk = Eslovakia
region-name-sl = Sierra Leona
region-name-sm = San Marino
region-name-sn = Senegal
region-name-so = Somalia
region-name-sr = Surinam
region-name-st = Sao Tome eta Principe uharteak
region-name-sv = El Salvador
region-name-sy = Siria
region-name-sz = Swazilandia
region-name-tc = Turkiar eta Caicos Uharteak
region-name-td = Txad
region-name-tg = Togo
region-name-th = Thailandia
region-name-tj = Tajikistan
region-name-tk = Tokelau
region-name-tl = Ekialdeko Timor
region-name-tm = Turkmenistan
region-name-tn = Tunez
region-name-to = Tonga
region-name-tr = Turkia
region-name-tt = Trinidad eta Tobago
region-name-tv = Tuvalu
region-name-tw = Taiwan
region-name-tz = Tanzania
region-name-ua = Ukraina
region-name-ug = Uganda
region-name-us = Estatu Batuak
region-name-uy = Uruguai
region-name-uz = Uzbekistan
region-name-va = Vatikano Hiriko Estatua
region-name-vc = Saint Vincent eta Grenadinak
region-name-ve = Venezuela
region-name-vn = Vietnam
region-name-vu = Vanuatu
region-name-wf = Wallis eta Futuna
region-name-ws = Samoa
region-name-ye = Yemen
region-name-yt = Mayotte
region-name-za = Hegoafrika
region-name-zm = Zambia
region-name-zw = Zimbawe
