#filter emptyLines
#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Boniface Challo (translation)</em:contributor> <em:contributor>Alex Wafula (review)</em:contributor> <em:contributor>Translate.org.za (technical)</em:contributor>

#unfilter emptyLines