# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE These strings are used in the shared React components,
# so files in `devtools/client/shared/components/*`.

# LOCALIZATION NOTE (frame.unknownSource): When we do not know the source filename of
# a frame, we use this string instead.
frame.unknownSource = (unbekannt)
# LOCALIZATION NOTE (frame.viewsourceindebugger): The label for the tooltip when hovering over
# a source link that links to the debugger.
# %S represents the URL to match in the debugger.
frame.viewsourceindebugger = Quelltext im Debugger anzeigen → %S
# LOCALIZATION NOTE (frame.viewsourceinstyleeditor): The label for the tooltip when hovering over
# a source link that links to the Style Editor.
# %S represents the URL to match in the style editor.
frame.viewsourceinstyleeditor = Quelle in Stilbearbeitung anzeigen → %S
# LOCALIZATION NOTE (notificationBox.closeTooltip): The content of a tooltip that
# appears when hovering over the close button in a notification box.
notificationBox.closeTooltip = Diese Mitteilung schließen
# LOCALIZATION NOTE (appErrorBoundary.description): This is the information displayed
# once the panel errors.
# %S represents the name of panel which has the crash.
appErrorBoundary.description = Die %S-Ansicht ist abgestürzt.
# LOCALIZATION NOTE (appErrorBoundary.fileBugButton): This is the text that appears in
# the button to visit the bug filing link.
appErrorBoundary.fileBugButton = Fehlermeldung einreichen
# LOCALIZATION NOTE (appErrorBoundary.reloadPanelInfo): This is the text that appears
# after the panel errors to instruct the user to reload the panel.
appErrorBoundary.reloadPanelInfo = Schließen und öffnen Sie den Werkzeugkasten, um diesen Fehler zu beheben.
# LOCALIZATION NOTE(searchModifier.regExpModifier): A search option
# when searching text in a file
searchModifier.regExpModifier = Regulären Ausdruck verwenden
# LOCALIZATION NOTE(searchModifier.caseSensitiveModifier): A search option
# when searching text in a file
searchModifier.caseSensitiveModifier = Groß-/Kleinschreibung
# LOCALIZATION NOTE(searchModifier.wholeWordModifier): A search option
# when searching text in a file
searchModifier.wholeWordModifier = Nur ganzes Wort
# LOCALIZATION NOTE (searchBox.clearButtonTitle): The title of the SearchBox clear input
# button, which is displayed when the input is not empty.
searchBox.clearButtonTitle = Filtereingabe löschen
# LOCALIZATION NOTE treeNode.collapseButtonTitle): The title of the Tree node toggle
# button when the node is expanded.
treeNode.collapseButtonTitle = Einklappen
# LOCALIZATION NOTE treeNode.expandButtonTitle): The title of the Tree node toggle
# button when the node is collapsed.
treeNode.expandButtonTitle = Ausklappen
# LOCALIZATION NOTE (editor.searchResults1): Semi-colon list of plural forms.
# See: http://developer.mozilla.org/en/docs/Localization_and_Plurals
# Editor Search bar message to summarize the selected search result. e.g. 5 of 10 results.
editor.searchResults1 = %d von #1 Treffer;%d von #1 Treffern
# LOCALIZATION NOTE (editor.noResultsFound): Editor Search bar message
# for when no results found.
editor.noResultsFound = Keine Ergebnisse gefunden
# LOCALIZATION NOTE (sourceSearch.resultsSummary2): Semi-colon list of plural forms.
# See: http://developer.mozilla.org/en/docs/Localization_and_Plurals
# Shows a summary of the number of matches for autocomplete
sourceSearch.resultsSummary2 = #1 Treffer;#1 Treffer
# LOCALIZATION NOTE (sourceSearch.search.placeholder2): placeholder text in
# the source search input bar
sourceSearch.search.placeholder2 = In Datei suchen…
