# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

#define Welcome_Title 安裝 $ProductName$

#define Welcome_MessageWelcome 歡迎使用 %s

#define Welcome_Message0 您目前正要安裝的版本是 %s 2 Alpha 1。

#define Welcome_Message1 中文語言由林弘德 (piaip@csie.ntu.edu.tw) 所維護，並感謝臺灣 Mozilla 社群 (http://moztw.org/) 的參與和協助。

#define Welcome_Message2 建議先關閉其它執行中程式，並移除舊版 (舊信件、通訊錄等各種設定會自動保留下來)

#define Welcome_Message3 【安裝請先移除舊版或裝到不同目錄】

#define License_Title 軟體授權同意書

#define License_SubTitle 使用軟體的授權、保證與聲明

#define License_Message0 請仔細閱讀以下的授權同意書。如果您懶得看或看不懂英文，請起碼記得：這個軟體是免費的，不過我們不為它負任何責任，也沒有任何保證。

#define License_Accept 我接受上述條款(&A)

#define License_Decline 我「拒絕」接受上述條款(&T)

#define Type_Title 安裝方式

#define Type_SubTitle 選取安裝選項

#define Type_Message0 請選擇安裝方式後按「下一步」。

#define Standard_Short 標準(&S)

#define Standard_Long 安裝一般常用元件

#define Custom_Short 自訂(&C)

#define Custom_Long 自行指定要安裝的元件。 不建議新手使用。

#define Select_Title 選用元件

#define Select_SubTitle 可加強 $ProductName$ 的功能

#define Select_Message0 選取其它想安裝的元件後按「下一步」。

#define Path_Title 安裝目錄

#define Path_SubTitle $ProductName$ 會安裝到哪個目錄

#define Path_Message0 將會安裝 $ProductName$ 到下面指定的目錄：

#define Integration_Title 設定程式捷徑

#define Integration_SubTitle 建立程式圖示

#define Integration_Message0 建立可執行 $ProductShortName$ 的圖示於:

#define Integration_Desktop 桌面

#define Integration_StartMenu 開始功能表的程式集內

#define Integration_QuickLaunch 快速啟動列

#define SelectFolder_Title 安裝 $ProductName$ - 指定程式目錄

#define SelectFolder_Message0 安裝程式會將程式圖示加入下面指定的程式集列表中。 確定或修改完成後請按下一步繼續。

#define Advanced_Title 安裝 $ProductName$ - 進階設定

#define Advanced_Message0 If your Internet connection requires a proxy server, enter your server name and port information.  If your Internet connection doesn't require a proxy server, leave the fields blank.

#define Install_Title 總結

#define Install_SubTitle 已經可以開始安裝 $ProductName$。

#define Install_MessageInstall 安裝程式現在會開始安裝下列元件:

#define Install_MessageDownload 安裝程式現在會開始下載並安裝下列元件:

#define Install_Message0 請按「下一步」以繼續

#define Downloading_Title 正在下載

#define Downloading_SubTitle 正在下載所需的元件...

#define Downloading_Blurb 正在下載安裝 $ProductName$ 所需的檔案。

#define Downloading_FileName 正在下載:

#define Downloading_Time 剩餘時間:

#define Installing_Title 正在安裝

#define Installing_SubTitle 正在安裝 $ProductName$...

#define Installing_Blurb 正在安裝應用程式

#define Installing_Status 準備檔案:

#define Installing_Component 正在安裝:

#define Success_Title 安裝完成

#define Success_Header 安裝完成

#define Success_Message0 已成功安裝 %s。

#define Success_Message1 關於中文版與其它相關資訊請見 http://moztw.org/ - Mozilla Taiwan

#define Success_Launch 馬上執行「%s」

#define Check_Message 已成功下載 $ProductName$ 。 繼續安裝前會先關閉 $ProductNameInternal$ 。請按確定以繼續。

#define Check_FullMessage 繼續安裝前要先關閉 $ProductNameInternal$ 。按下確定後會自動關閉 $ProductNameInternal$  並繼續安裝程序。

#define Check_Wait 正在關閉 $ProductNameInternal$ ，請稍候...

#define Component_XPCOM XPCOM 跨平台程式庫

#define Component_Mail $ProductName$

#define Component_Offline 離線瀏覽

#define Component_Offline_Long 讓 $ProductName$ 支援離線瀏覽、閱讀郵件與文章

#define Component_RSS RSS 元件

#define Component_RSS_Long 讓 $ProductName$ 可以瀏覽 RSS

#define Component_QFA 錯誤回報工具

#define Component_QFA_Long 用來在 $ProductName$ 程式錯誤時回報資訊
