# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Notice: If you're updating this list, you should also
###         update the list in mozIntl.js.

region-name-ad = Անդորրա
region-name-ae = Միացեալ Եմիրութիւնք Արաբացւոց
region-name-af = Աւգանիստան
region-name-al = Աղբանիա
region-name-am = Հայք
region-name-ao = Անգոլա
region-name-aq = Անտարկտիկա
region-name-ar = Արգենտինա
region-name-at = Աւստիա
region-name-au = Աւստրաղիա
region-name-aw = Արուբա
region-name-az = Ադրբեջան
region-name-ba = Բոսնիա եւ Հերցեգովինա
region-name-bb = Բարբադոս
region-name-bd = Բանգլադեշ
region-name-bg = Բուղգարիա
region-name-bh = Բահրէն
region-name-bi = Բուրունդի
region-name-bj = Բենին
region-name-bn = Բրունէ
region-name-bo = Բողիւիա
region-name-br = Բրազիղիա
region-name-bt = Բութան
region-name-bw = Բոթսուանա
region-name-by = Բելառուս
region-name-bz = Բելիզ
region-name-ca = Կանադա
region-name-cd = Կոնգո (Քինշասա)
region-name-cf = Կենտրոնական Ափրիկէեան Հանրապետութիւն
region-name-cg = Կոնգո (Բրազաւիղ)
region-name-ch = Զուիցերա
region-name-ci = Կոտ դ'Իւուար
region-name-cl = Չիղէ
region-name-cm = Կամերուն
region-name-cn = Չինաստան
region-name-co = Կողոմբիա
region-name-cr = Կոստա Ռիկա
region-name-cu = Կուբա
region-name-cy = Կիւպրոս
region-name-cz = Չեխիա
region-name-de = Գերմանիա
region-name-dg = Դիեգո Գարսիա
region-name-dj = Ջիբուտի
region-name-ec = Եկուադոր
region-name-ee = Եստոնիա
region-name-eg = Եգիպտոս
region-name-eh = Արեւմտեան Սահարա
region-name-er = Երիտրէա
region-name-es = Իսպանիա
region-name-et = Եթովպիա
region-name-fj = Փիջի
region-name-fr = Գաղղիա
region-name-ga = Գաբոն
region-name-gb = Մեծ Բրիտանիա
region-name-gd = Գրենադա
region-name-ge = Վիրք
region-name-gh = Գանա
region-name-gm = Գամբիա
region-name-gn = Գուինէա
region-name-gr = Եղղադա
region-name-gt = Գուատեմաղա
region-name-gu = Գուամ
region-name-hk = Հոնգ Կոնգ
region-name-hn = Հոնդուրաս
region-name-hr = Խորուաթիա
region-name-ht = Հայիթի
region-name-hu = Հունգարիա
region-name-id = Ինդոնեզիա
region-name-in = Հնդկաստան
region-name-iq = Իրաք
region-name-ir = Երանշահր
region-name-it = Իտաղիա
region-name-jo = Յորդանան
region-name-ke = Քենիա
region-name-kh = Կամբոջա
region-name-kp = Հիւսիսային Կորէա
region-name-kr = Հարաւային Կորէա
region-name-kw = Քուէթ
region-name-la = Լայոս
region-name-lb = Լիբանան
region-name-lk = Շրի Ղանկա
region-name-lr = Ղիբերիա
region-name-mc = Մոնակո
region-name-me = Մոնտենեգրո
region-name-mf = Սուրբ Մարտին
region-name-mg = Մադագասկար
region-name-mk = Մակեդոնիա
region-name-ml = Մաղի
region-name-mm = Միանմար
region-name-mn = Մոնգողիա
region-name-mr = Մաւրիտանիա
region-name-mx = Մեխիկո
region-name-my = Մաղազիա
region-name-mz = Մոզամբիկ
region-name-na = Նամիբիա
region-name-nc = Նոր Կաղեդոնիա
region-name-ne = Նիգեր
region-name-ng = Նիգերիա
region-name-ni = Նիկարագուա
region-name-np = Նեպալ
region-name-nr = Նաուրու
region-name-nz = Նոր Զեղանդիա
region-name-om = Ոման
region-name-pa = Պանամա
region-name-pe = Պերու
region-name-pg = Պապուա Նոր Գուինէա
region-name-ph = Փիղիպինք
region-name-pk = Պակիստան
region-name-pl = Լեհաստան
region-name-pr = Պուերտո Ռիկո
region-name-py = Պարագուայ
region-name-qa = Քաթար
region-name-re = Ռէունիոն
region-name-ro = Հռովմանիա
region-name-rs = Սերբիա
region-name-ru = Ռուսաստան
region-name-rw = Ռուանդա
region-name-sa = Սաուդեան Արաբիա
region-name-sd = Սուդան
region-name-se = Շուեդիա
region-name-sg = Սինգապուր
region-name-si = Սղովենիա
region-name-sk = Սղովակիա
region-name-sl = Սիերա Ղէոնե
region-name-tt = Տրինիդադ եւ Տոբագո
