# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = Bu sayfa başka bir qonuma yönlendiriliyor. Yazdığınız form verisini yeni qonuma da göndermek ister misiniz?
# Directory listing strings
DirTitle = %1$S dizini
DirGoUp = Üst düzeydeki dizine git
ShowHidden = Gizli nesnelerni köster
DirColName = İsim
DirColSize = Boyut
DirColMTime = Son değişiklik
DirFileLabel = Dosye:\u0020
UnsafeUriBlocked = “%1$S” adresindeki qaynaq Emin Kezinüv tarafından bloklandı.
CookieBlockedByPermission = “%1$S” üzerindeki çöreklerge yaki mağazğa irişim istemi şahsiyleştirilgen çörek ruhsetinden dolayı bloklandı.
CookieBlockedAll = “%1$S” üzerindeki çöreklerge yaki mağazğa irişim istemi episi mağaz irişim istemlerini bloklağanımızdan dolayı bloklandı.
