# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Alert = هوشدار
Confirm = قوۊل
ConfirmCheck = قوۊل
Prompt = پورس کردن
# LOCALIZATION NOTE - %S is brandFullName
PromptUsernameAndPassword3 = ائراز هۊویت اخو - %S
# LOCALIZATION NOTE - %S is brandFullName
PromptPassword3 = رزم اخو - %S
Select = پسند
OK = خا
Cancel = لقو
Yes = &هری
No = &ن
Save = &زفت
Revert = &وورگندن
DontSave = زفت &نکۊنین
ScriptDlgGenericHeading = [برنومه جاوا اسکریپت]
ScriptDlgHeading = بلگه %S اگو:
ScriptDlgNullPrincipalHeading = ای بلگه اگو:
ScriptDialogLabel = ز وورکل نیمدریا نۊ و دست ای بلگه جلاو گری بۊ.
ScriptDialogLabelNullPrincipal = نهلی ی وارسۊوی دیری ز ای وبگه فشناڌه بۊ
# LOCALIZATION NOTE (ScriptDialogLabelContentPrincipal):
# %S is either the domain and port of the site prompting, or the name of
# an add-on prompting.
ScriptDialogLabelContentPrincipal = نهلی ی وارسۊوی دیری ز %S فشناڌه بۊ
ScriptDialogPreventTitle = تاییڌ ترجیهات مربۊت و ای نیمدری
# LOCALIZATION NOTE (EnterLoginForRealm3, EnterLoginForProxy3):
# %1 is an untrusted string provided by a remote server. It could try to
# take advantage of sentence structure in order to mislead the user (see
# bug 244273). %1 should be integrated into the translated sentences as
# little as possible. %2 is the url of the site being accessed.
EnterLoginForRealm3 = %2$S درخاست نوم منتوری وو رزم ایسا ن داره. ای وبگه اگو: «%1$S»
EnterUserPasswordFor2 = %1$S درخاست نوم منتوری وو رزم ایسا ن داره.
EnterPasswordFor = زیڌن رزم سی %1$S و ری %2$S
EnterCredentials = ای وبگه ز ایسا اخو ک و من بیاین.
# %S is the username for which a password is requested.
EnterPasswordOnlyFor = ای وبگه ز ایسا اخو ک و عونوان %S و من بیاین.
SignIn = و من ٱووڌن
