# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Alert = هوشدار
Confirm = قوۊل
ConfirmCheck = قوۊل
Prompt = پورس کردن
Select = پسند
OK = خا
Cancel = لقو
Yes = &هری
No = &ن
Save = &زفت
Revert = &وورگندن
DontSave = زفت &نکۊنین
ScriptDlgGenericHeading = [برنومه جاوا اسکریپت]
ScriptDlgHeading = بلگه %S اگو:
ScriptDlgNullPrincipalHeading = ای بلگه اگو:
ScriptDialogLabel = ز وورکل نیمدریا نۊ و دست ای بلگه جلاو گری بۊ.
EnterUserPasswordFor2 = %1$S درخاست نوم منتوری وو رزم ایسا ن داره.
SignIn = و من ٱووڌن
