# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE (uninstall.confirmation.title) %S is the name of the extension which is about to be uninstalled.
uninstall.confirmation.title = پاک کردن پۊرنیڌن %S
uninstall.confirmation.button-0.label = پاک کردن پۊرنیڌن
uninstall.confirmation.button-1.label = پۊرسته بمئنه
saveaspdf.saveasdialog.title = زفت و عونوان
newTabControlled.learnMore = قلوه دووسته بۊین
homepageControlled.learnMore = قلوه دووسته بۊین
tabHideControlled.learnMore = قلوه دووسته بۊین
