# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# These strings are used in the native GTK, Mac and Windows print dialogs.

# GTK titles:
printTitleGTK = چاپ
optionsTabLabelGTK = گۊزینه یل
# Mac titles:
optionsTitleMac = گۊزینه یل:
appearanceTitleMac = شؽوات:
pageHeadersTitleMac = سر بلگه یل:
pageFootersTitleMac = پا بلگه یل:
# Windows titles:
optionsTitleWindows = گۊزینه یل

# TRANSLATOR NOTE: For radio button labels and check button labels, an underscore _
# before a character will turn that character into an accesskey in the GTK dialog.
# e.g. "_As laid out" will make A the accesskey.
# In the Windows labels, use an ampersand (&).
# On Mac, underscores will be stripped.

selectionOnly = چاپ بشن پ_سند وابیڌه
left = چپ
center = منجقا
right = راست
headerFooterBlank = ‐‐پتی‐‐
headerFooterTitle = عونوان
headerFooterURL = نشۊوی اینترنتی
headerFooterPage = بلگه #
headerFooterPageTotal = بلگه # ز #
headerFooterCustom = سفارشی…
# These are for the summary view in the Mac dialog:
summarySelectionOnlyTitle = چاپ بشن پسند وابیڌه
summaryOnValue = رۊشن
summaryOffValue = کۊر
