# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

#define Welcome_Title $ProductName$ Setup

#define Welcome_MessageWelcome Welcome to %s!

#define Welcome_Message0 You are about to install %s 2 Alpha 1.

#define Welcome_Message1 It is strongly recommended that you exit all Windows programs before running this Setup program.

#define Welcome_Message2 Click Cancel to quit Setup and then close any programs you have running.  Click Next to continue the Setup program.

#define Welcome_Message3 Click Next to continue installing %s 2 Alpha 1.

#define License_Title Software License Agreement

#define License_SubTitle Terms and conditions for using this software.

#define License_Message0 Please read the following license agreement. Use the scroll bar to view the rest of this agreement.

#define License_Accept I &Accept the terms of the License Agreement

#define License_Decline I do NO&T Accept the terms of the License Agreement

#define Type_Title Setup Type

#define Type_SubTitle Choose setup options.

#define Type_Message0 Choose the type of Setup you prefer, then click Next.

#define Standard_Short &Standard

#define Standard_Long Thunderbird will be installed with the most common options.

#define Custom_Short &Custom

#define Custom_Long You may choose individual options to be installed. Recommended for experienced users.

#define Select_Title Select Components

#define Select_SubTitle Additional components that enhance $ProductName$.

#define Select_Message0 Choose additional components you want to install, then click Next.

#define Path_Title Install Folder

#define Path_SubTitle Where $ProductName$ will be installed.

#define Path_Message0 $ProductName$ will be installed into the following folder:

#define Integration_Title Set Up Shortcuts

#define Integration_SubTitle Creates Program Icons

#define Integration_Message0 Create icons for $ProductShortName$:

#define Integration_Desktop On my Desktop

#define Integration_StartMenu In my Start Menu Programs folder

#define Integration_QuickLaunch In my Quick Launch bar

#define SelectFolder_Title $ProductName$ Setup - Select Program Folder

#define SelectFolder_Message0 Setup will add program icons to the Program Folder listed below.  You may type a new folder name, or select one from the Existing Folders list.  Click Next to continue.

#define Advanced_Title $ProductName$ Setup - Advanced Settings

#define Advanced_Message0 If your Internet connection requires a proxy server, enter your server name and port information.  If your Internet connection doesn't require a proxy server, leave the fields blank.

#define Install_Title Summary

#define Install_SubTitle Ready to start installing $ProductName$.

#define Install_MessageInstall Setup will now install the following components:

#define Install_MessageDownload Setup will now download and install the following components:

#define Install_Message0 Click Next to continue.

#define Downloading_Title Downloading

#define Downloading_SubTitle Downloading required components...

#define Downloading_Blurb Setup is downloading the files required to install $ProductName$.

#define Downloading_FileName Currently Downloading:

#define Downloading_Time Time Remaining:

#define Installing_Title Installing

#define Installing_SubTitle Installing $ProductName$...

#define Installing_Blurb Setup is installing application files.

#define Installing_Status Preparing File:

#define Installing_Component Currently Installing:

#define Success_Title Install Complete

#define Success_Header Install Complete

#define Success_Message0 %s was successfully installed.

#define Success_Message1 Click Finish to complete Setup.

#define Success_Launch Launch %s now.

#define Check_Message Download of $ProductName$ was successful. $ProductNameInternal$ must be closed to proceed with installation. Click OK to exit $ProductNameInternal$ automatically and to begin installation.

#define Check_FullMessage $ProductNameInternal$ must be closed to proceed with installation. Click OK to exit $ProductNameInternal$ automatically and to begin installation.

#define Check_Wait Shutting down $ProductNameInternal$.  Please wait...

#define Component_XPCOM Cross Platform COM

#define Component_Mail $ProductName$

#define Component_Offline Offline Support

#define Component_Offline_Long Adds Offline support to $ProductName$ Mail.

#define Component_RSS RSS Support

#define Component_RSS_Long Adds RSS support to $ProductName$.

#define Component_QFA Quality Feedback Agent

#define Component_QFA_Long for reporting $ProductName$ crash information
