
# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=Rregullimi i $ProductName$-it
Welcome_MessageWelcome=Mirësevini te %s!
Welcome_Message0=Jeni gati për të instaluar %s 2 Alpha 1.
Welcome_Message1=Këshillohet fuqimisht të dilni prej tërë programeve Windows para se të xhironi këtë program Rregullimi.
Welcome_Message2=Klikoni Anulo për të lënë Rregullimin dhe mbyllur mandej çdo program që po xhironi.  Klikoni Pasues për të vazhduar me programin Rregullim.
Welcome_Message3=Klikoni Pasues për të vazhduar me instalimin e %s-it 2 Alpha 1.

License_Title=Marrëveshje Licence Software-i
License_SubTitle=Terma dhe kushte për përdorimin e këtij software-i.
License_Message0=Ju lutem lexoni marrëveshjen vijuese për licencën. Përdorni shtylla rrëshqitjesh për të parë pjesën e mbetur të kësaj marrëveshjeje.
License_Accept=I &Pranoj termat e Marrëveshjes së Licencës
License_Decline=&NUK i pranoj termat e Marrëveshjes së Licencës

Type_Title=Lloj Rregullimi
Type_SubTitle=Zgjidhni mundësitë e rregullimit.
Type_Message0=Zgjidhni llojin e Rregullimit që parapëlqeni, mandej klikoni Pasues.

Standard_Short=&Standard
Standard_Long=Thunderbird Shfletuesi do të instalohet me mundësitë më të zakonshme.

Custom_Short=&Vetjak
Custom_Long=Mund të zgjidhni për instalim mundësi vetjake. E këshillueshme për përdorues të sprovuar.

Select_Title=Përzgjidhni Përbërës
Select_SubTitle=Përbërësa shtesë që thellojnë $ProductName$-in.
Select_Message0=Zgjidhni përbërësa shtesë të cilët doni të instalohen, mandej klikoni Pasues.

Path_Title=Dosje Instalimi
Path_SubTitle=Ku do të instalohet $ProductName$-i.
Path_Message0=$ProductName$-i do të instalohet brenda dosjes vijuese:

Integration_Title=Caktoni Shkurtprerje
Integration_SubTitle=Krijon Ikona Programi
Integration_Message0=Krijo ikona për $ProductShortName$:

Integration_Desktop=Te Desktopi im
Integration_StartMenu=Te dosja ime Menu Nisjesh Programesh
Integration_QuickLaunch=Te shtylla ime Nisje e Shpejtë

SelectFolder_Title=Rregullimi i $ProductName$-it - Përzgjidhni Dosje Programi
SelectFolder_Message0=Rregullimi do të shtojë ikona programi te Dosje Programesh listuar më poshtë.  Mund të shtypni një emër dosjeje të re, ose përzgjidhni një nga lista e Dosjeve Ekzistuese.  Klikoni Pasues për të vazhduar.

Advanced_Title=Rregullimi i $ProductName$-it - Rregullime të Mëtejshëm
Advanced_Message0=Nëse lidhja juaj me Internetin lyp një shërbyes ndërmjetës, jepni emrin e shërbyesit tuaj dhe të dhëna porte.  Nëse lidhja juaj me Internetin nuk lyp një shërbyes ndërmjetës, lërini bosh kutitë.

Install_Title=Përmbledhje
Install_SubTitle=Gati për fillimin e instalimit të $ProductName$-it.
Install_MessageInstall=Rregullimi tani do të instalojë përbërësit vijues:
Install_MessageDownload=Rregullimi do të shkarkojë dhe instalojë tani përbërësit vijues:
Install_Message0=Klikoni Pasues për të vazhduar.

Downloading_Title=Po shkarkoj
Downloading_SubTitle=Po shkarkoj përbërësit e nevojshëm...
Downloading_Blurb=Rregullimi po shkarkon kartelat e nevojshme për instalimin e $ProductName$-it.
Downloading_FileName=Tani Po Shkarkoj:
Downloading_Time=Kohë e Mbetur:

Installing_Title=Po instaloj
Installing_SubTitle=Po instaloj $ProductName$-in...
Installing_Blurb=Rregullimi po instalon kartelat e zbatimit. 
Installing_Status=Po përgatis Kartelë:
Installing_Component=Tani Po Instaloj:

Success_Title=Instalim i Plotë
Success_Header=Instalim i Plotë
Success_Message0=%s-i u instalua me sukses.
Success_Message1=Klikoni Përfundo për të plotësuar Rregullimin. 
Success_Launch=Nis %s-in tani.

Check_Message=Shkarkimi i $ProductName$-it qe i sukseshëm. $ProductNameInternal$-i duhet mbyllur që të mund të vazhdohet me instalimin. Klikoni OK për të dalë automatikisht prej $ProductNameInternal$-it dhe për të filluar instalimin.
Check_FullMessage=$ProductNameInternal$-i duhet mbyllur për të vazhduar me instalimin. Klikoni OK për të dalë automatikisht prej $ProductNameInternal$-it dhe për të filluar instalimin.
Check_Wait=Po mbyll $ProductNameInternal$-in.  Ju lutem prisni...

Component_XPCOM=COM Ndërplatformëshe
Component_Mail=$ProductName$
Component_Offline=Mbështetje "Offline"
Component_Offline_Long=Shton mbështetje "Offline" për Postën $ProductName$.
Component_RSS=Mbështetje për RSS
Component_RSS_Long=Shton te $ProductName$-i mbështetje për RSS.
Component_QFA=Quality Feedback Agent
Component_QFA_Long=për raportim të dhënash vithisjeje të $ProductName$-it
