#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title 书签
#define bookmarks_heading 书签

#define bookmarks_toolbarfolder 书签工具栏文件夹
#define bookmarks_toolbarfolder_description 添加到此文件夹的书签会被显示到书签工具栏中

# LOCALIZATION NOTE (getting_started):
# link title for http://en-US.www.mozilla.com/en-US/firefox/central/
#define getting_started 新手上路

# LOCALIZATION NOTE (latest_headlines):
# link title for the live bookmarks sample, a redirect on
# http://en-US.fxfeeds.mozilla.com/en-US/firefox/headlines.xml
# Changing the redirect is subject to approval of l10n-drivers.
#define latest_headlines 最新头条

# LOCALIZATION NOTE (firefox_heading):
# Firefox links folder name
#define firefox_heading Mozilla Firefox

# LOCALIZATION NOTE (firefox_help):
# link title for http://en-US.www.mozilla.com/en-US/firefox/help/
#define firefox_help 帮助和教程

# LOCALIZATION NOTE (firefox_customize):
# link title for http://en-US.www.mozilla.com/en-US/firefox/customize/
#define firefox_customize 自定义 Firefox

# LOCALIZATION NOTE (firefox_community):
# link title for http://en-US.www.mozilla.com/en-US/firefox/community/
#define firefox_community 加入进来

# LOCALIZATION NOTE (firefox_about):
# link title for http://en-US.www.mozilla.com/en-US/firefox/about/
#define firefox_about 关于我们

#unfilter emptyLines
