# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

text-action-undo =
    .label = Յետարկել
    .accesskey = U
text-action-undo-shortcut =
    .key = Z
text-action-redo =
    .label = Կրկնել
    .accesskey = R
text-action-redo-shortcut =
    .key = Y
text-action-cut =
    .label = Կտրել
    .accesskey = t
text-action-cut-shortcut =
    .key = X
text-action-copy =
    .label = Պատճենել
    .accesskey = C
text-action-copy-shortcut =
    .key = C
text-action-paste =
    .label = Տեղադրել
    .accesskey = P
text-action-paste-shortcut =
    .key = V
text-action-delete =
    .label = Ջնջել
    .accesskey = D
text-action-select-all =
    .label = Նշել բոլորը
    .accesskey = A
text-action-select-all-shortcut =
    .key = A
text-action-spell-no-suggestions =
    .label = Ուղղագրական առաջարկներ չկան
text-action-spell-add-to-dictionary =
    .label = Աւելացնել բառարանում
    .accesskey = ո
text-action-spell-undo-add-to-dictionary =
    .label = Չեղարկել աւելացումը բառարանում
    .accesskey = ե
text-action-spell-check-toggle =
    .label = Ստուգել ուղղագրութիւնը
    .accesskey = ն
text-action-spell-add-dictionaries =
    .label = Աւելացնել բառարաններ…
    .accesskey = Ա
text-action-spell-dictionaries =
    .label = Լեզուներ
    .accesskey = Լ
text-action-search-text-box-clear =
    .title = Մաքրել
