# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = กำลังมองหา { $host }…
network-connection-status-connected = เชื่อมต่อไปยัง { $host } แล้ว…
network-connection-status-sending-request = กำลังส่งคำขอไปยัง { $host }…
network-connection-status-transferring-data = กำลังถ่ายโอนข้อมูลจาก { $host }…
network-connection-status-connecting = กำลังเชื่อมต่อไปยัง { $host }…
network-connection-status-read = อ่าน { $host }
network-connection-status-wrote = เขียน { $host }
network-connection-status-waiting = กำลังรอ { $host }…
network-connection-status-looked-up = มองหา { $host } แล้ว…
network-connection-status-tls-handshake = กำลังดำเนินการแฮนด์เชค TLS กับ { $host }…
network-connection-status-tls-handshake-finished = แฮนด์เชค TLS เสร็จสิ้นสำหรับ { $host }…
