# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language-name-aa = Ekyiri
language-name-ab = Abkhazian
language-name-ae = Avɛstan
language-name-af = Afrikaans
language-name-ak = Akan
language-name-am = Amarik
language-name-an = Aragones kasa
language-name-ar = Arabik
language-name-as = Assames kasa
language-name-ast = Asturia
language-name-av = Avarik
language-name-ay = Aymara
language-name-az = Azɛbaigyan kasa
language-name-ba = Bashkir kasa
language-name-be = Bɛlarus kasa
language-name-bg = Bɔlgeria kasa
language-name-bh = Bihari kasa
language-name-bi = Bislama kasa
language-name-bm = Bambara kasa
language-name-bn = Bengali kasa
language-name-bo = Tibɛt kasa
language-name-br = Brɛton
language-name-bs = Bosnia kasa
language-name-ca = Katalan
language-name-ce = Kyɛkyen
language-name-ch = Kyamorro
language-name-co = Kɔɔsika kasa
language-name-cr = Kree
language-name-cs = Kyɛk kasa
language-name-csb = Kashub kasa
language-name-cu = Kyɛɛkye Slavik
language-name-cv = Kyuvahye kasa
language-name-cy = Wɛlhye
language-name-da = Danihye
language-name-de = Gyaaman
language-name-dsb = Sɔrbia Famu kasa
language-name-dv = Divehi
language-name-dz = Dzongka kasa
language-name-ee = Ayigbe
language-name-el = Greek kasa
language-name-en = Borɔfo
language-name-eo = Ɛspɛranto kasa
language-name-es = Spain kasa
language-name-et = Ɛstonia kasa
language-name-eu = Baske kasa
language-name-fa = Pɛɛhyia kasa
language-name-ff = Fula kasa
language-name-fi = Finland kasa
language-name-fj = Figyi kasa
language-name-fo = Farofo kasa
language-name-fr = Frɛnkye
language-name-fur = Friulia kasa
language-name-fy = Frisia kasa
language-name-ga = Aerihye kasa
language-name-gd = Skɔtfo Gaelik kasa
language-name-gl = Galihyia kasa
language-name-gn = Guarani kasa
language-name-gu = Gugyarati
language-name-gv = Manks kasa
language-name-ha = Hausa
language-name-haw = Hawaiifo kasa
language-name-he = Hebrefo kasa
language-name-hi = Hindi
language-name-hil = Hiligaynon kasa
language-name-ho = Hiri Motu kasa
language-name-hr = Kroehyia kasa
language-name-hsb = Sɔrbia Sorosoro kasa
language-name-ht = Haiti kasa
language-name-hu = Hangri kasa
language-name-hy = Aamɛnia kasa
language-name-hz = Hɛrɛro
language-name-ia = Intalingua kasafra
language-name-id = Indonihyia kasa
language-name-ie = Intalingue kasafra
language-name-ig = Igbo
language-name-ii = Sikyuan Yi kasa
language-name-ik = Inupiak
language-name-io = Ido
language-name-is = Aesland kasa
language-name-it = Italy kasa
language-name-iu = Inuktitut
language-name-ja = Gyapan kasa
language-name-jv = Gyabanis kasa
language-name-ka = Gyɔgyea kasa
language-name-kg = Kongo
language-name-ki = Kikuyu
language-name-kj = Kuanyama
language-name-kk = Kazak
language-name-kl = Greenman kasa
language-name-km = Khmɛɛ
language-name-kn = Kanada
language-name-ko = Korea kasa
language-name-kok = Konkani kasa
language-name-kr = Kanuri
language-name-ks = Kahyemɛɛ kasa
language-name-ku = Kɛɛdihyefo kasa
language-name-kv = Komi kasa
language-name-kw = Kɔɔnwɔl kasa
language-name-ky = Kɛɛges kasa
language-name-la = Latin
language-name-lb = Laksembɛg kasa
language-name-lg = Ganda
language-name-li = Limbɔrgan
language-name-ln = Lingala
language-name-lo = Lao
language-name-lt = Lituwenia kasa
language-name-lu = Luba-Katanga
language-name-lv = Latvia kasa
language-name-mg = Malagasi
language-name-mh = Mahyalɛs
language-name-mi = Maori
language-name-mk = Masedonia kasa
language-name-ml = Malayalam
language-name-mn = Mɔngolia kasa
language-name-mr = Marati
language-name-ms = Malay kasa
language-name-mt = Mɔlta kasa
language-name-my = Bɛɛmis kasa
language-name-na = Naworu kasa
language-name-nb = Nɔɔwe Bokmål kasa
language-name-nd = Ndebele, Atifi
language-name-ne = Nɛpal kasa
language-name-ng = Ndonga kasa
language-name-nl = Dɛɛkye
language-name-nn = Nɔɔwefo Nynorsk kasa
language-name-no = Nɔɔwefo kasa
language-name-nr = Ndebele, Anaafo
language-name-nso = Sotho, Atifi
language-name-nv = Navagyo kasa
language-name-ny = Kyikyewa kasa
language-name-oc = Osita kasa
language-name-oj = Ogyibwa kasa
language-name-om = Oromo kasa
language-name-os = Osɛhyia kasa
language-name-pa = Pungyabi kasa
language-name-pi = Pali kasa
language-name-pl = Pɔland kasa
language-name-ps = Pahyeto kasa
language-name-pt = Pɔɔtugal kasa
language-name-qu = Kwɛkyua kasa
language-name-rm = Rhaeto-Romanik kasa
language-name-rn = Kirundi
language-name-ro = Romenia kasa
language-name-ru = Rahyia kasa
language-name-rw = Kinyarwanda
language-name-sa = Sanskrit
language-name-sc = Sadinia kasa
language-name-sd = Sindhi kasa
language-name-se = Sami etifi kasa
language-name-sg = Sango kasa
language-name-si = Singhala kasa
language-name-sk = Slovakia kasa
language-name-sl = Slovenia kasa
language-name-sm = Samoa kasa
language-name-sn = Hyɔna
language-name-so = Somalia kasa
language-name-son = Songae
language-name-sq = Albenia kasa
language-name-sr = Sɛɛbia kasa
language-name-ss = Siswati
language-name-st = Sotho, Anaafo
language-name-su = Sundan kasa
language-name-sv = Sweden kasa
language-name-sw = Swahili
language-name-ta = Tamil kasa
language-name-te = Telugu kasa
language-name-tg = Tajikistan kasa
language-name-th = Taeland kasa
language-name-ti = Tigrinya
language-name-tig = Tigre kasa
language-name-tk = Tɛkmɛnistan kasa
language-name-tl = Tagalog kasa
language-name-tlh = Klingon kasa
language-name-tn = Tswana
language-name-to = Tonga kasa
language-name-tr = Tɛrki kasa
language-name-ts = Tsonga kasa
language-name-tt = Tatar kasa
language-name-tw = Twi
language-name-ty = Tahiti kasa
language-name-ug = Uighur kasa
language-name-uk = Ukren kasa
language-name-ur = Urdu kasa
language-name-uz = Uzbɛkistan kasa
language-name-ve = Vɛnda kasa
language-name-vi = Viɛtnam kasa
language-name-vo = Volapük kasa
language-name-wa = Walun kasa
language-name-wen = Sɔrbia kasa
language-name-wo = Wɔlɔf
language-name-xh = Xhosa
language-name-yi = Yidihye kasa
language-name-yo = Yoruba
language-name-za = Zhuang kasa
language-name-zh = Kyaena kasa
language-name-zu = Zulu
