# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Notice: If you're updating this list, you should also
###         update the list in mozIntl.js.

region-name-ad = Andora
region-name-af = Afganistan
region-name-ag = Antigua ne Baabuda
region-name-ai = Anguila
region-name-al = Albenia
region-name-am = Aamɛnia
region-name-ao = Angola
region-name-aq = Antaktika
region-name-ar = Agyɛntina
region-name-as = Amɛrika Samoa
region-name-at = Ɔstria
region-name-au = Ɔstrelia
region-name-aw = Aruba
region-name-az = Azebaegyan
region-name-ba = Bosnia ne Hɛzegovina
region-name-bb = Baabados
region-name-bd = Bangladɛhye
region-name-be = Bɛlgyium
region-name-bf = Bɔkina Faso
region-name-bg = Bɔlgeria
region-name-bh = Baren
region-name-bi = Burundi
region-name-bj = Bɛnin
region-name-bm = Bɛmuda
region-name-bo = Bolivia
region-name-br = Brazil
region-name-bt = Butan
region-name-bv = Buvɛt Island
region-name-bw = Bɔtswana
region-name-by = Bɛlarus
region-name-bz = Beliz
region-name-ca = Kanada
region-name-cc = Kokos (Keeling) Islands
region-name-cf = Afrika Finimfin Man
region-name-ch = Swetzaland
region-name-ck = Kook Nsupɔw
region-name-cl = Kyili
region-name-cm = Kamɛrun
region-name-cn = Kyaena
region-name-co = Kolombia
region-name-cr = Kɔsta Rika
region-name-cu = Kuba
region-name-cx = Kristmas Island
region-name-cy = Saeprɔs
region-name-cz = Kyɛk Kurokɛse
region-name-de = Gyaaman
region-name-dj = Gyibuti
region-name-dk = Dɛnmak
region-name-dm = Dɔmeneka
region-name-do = Dɔmeneka Kurokɛse
region-name-dz = Ɔlgyeria
region-name-ec = Ikuwadɔ
region-name-ee = Ɛstonia
region-name-eg = Nisrim
region-name-eh = Westen Sahara
region-name-er = Ɛritrea
region-name-es = Spain
region-name-et = Ithiopia
region-name-fi = Finland
region-name-fj = Figyi
region-name-fo = Farofo Aeland
region-name-fr = Frɛnkyeman
region-name-ga = Gabɔn
region-name-gb = Ahendiman Nkabom
region-name-gd = Grenada
region-name-ge = Gyɔgyea
region-name-gf = Frɛnkye Gayana
region-name-gg = Gwɛnsey
region-name-gh = Gaana
region-name-gi = Gyebralta
region-name-gl = Greenman
region-name-gn = Gini
region-name-gp = Guwadelup
region-name-gq = Gini Ikuweta
region-name-gr = Greekman
region-name-gt = Guwatemala
region-name-gu = Guam
region-name-gw = Gini-Bisaw
region-name-gy = Gayana
region-name-hk = Hong Kong
region-name-hm = Heard Aeland ɛne McDonald Aeland
region-name-hn = Hɔnduras
region-name-hr = Krowehyia
region-name-ht = Heiti
region-name-hu = Hangari
region-name-id = Indɔnehyia
region-name-ie = Aereland
region-name-il = Israel
region-name-im = Isle of Man
region-name-in = India
region-name-io = Britainfo Hɔn Man Wɔ India Po No Mu
region-name-iq = Irak
region-name-ir = Iran
region-name-is = Aesland
region-name-it = Itali
region-name-je = Gyɛɛsey
region-name-jm = Gyameka
region-name-jo = Gyɔdan
region-name-jp = Gyapan
region-name-ke = Kɛnya
region-name-kg = Kɛɛgestan
region-name-kh = Kambodia
region-name-ki = Kiribati
region-name-km = Kɔmɔrɔs
region-name-kn = Saint Kitts and Nɛves
region-name-kw = Kuwete
region-name-ky = Kemanfo Islands
region-name-kz = Kazakstan
region-name-la = Laos
region-name-lb = Lɛbanɔn
region-name-lc = Saint Lucia
region-name-li = Lektenstaen
region-name-lk = Sri Lanka
region-name-lr = Laeberia
region-name-ls = Lɛsutu
region-name-lt = Lituwenia
region-name-lu = Laksembɛg
region-name-lv = Latvia
region-name-ly = Libya
region-name-ma = Moroko
region-name-mc = Mɔnako
region-name-md = Mɔldova
region-name-me = Mɔntenɛgro
region-name-mf = Saint Maten
region-name-mg = Madagaska
region-name-mh = Marshall Islands
region-name-ml = Mali
region-name-mn = Mɔngolia
region-name-mp = Northern Mariana Islands
region-name-mq = Matinik
region-name-mr = Mɔretenia
region-name-ms = Mantserat
region-name-mt = Mɔlta
region-name-mu = Mɔrehyeɔs
region-name-mv = Maldives
region-name-mw = Malawi
region-name-mx = Mɛksiko
region-name-my = Malehyia
region-name-mz = Mozambik
region-name-na = Namibia
region-name-nc = Kaledonia Foforo
region-name-ne = Nigyɛ
region-name-nf = Nɔfolk Aeland
region-name-ng = Naegyeria
region-name-ni = Nekaraguwa
region-name-nl = Nɛdɛland
region-name-no = Nɔɔwe
region-name-np = Nɛpɔl
region-name-nr = Naworu
region-name-nu = Niyu
region-name-nz = Ziland Foforo
region-name-om = Oman
region-name-pa = Panama
region-name-pe = Peru
region-name-pf = Frɛnkye Polynehyia
region-name-pg = Papua Guinea Foforo
region-name-ph = Philippines
region-name-pk = Pakistan
region-name-pl = Poland
region-name-pm = Saint Pierre ne Miquelon
region-name-pr = Puɛto Riko
region-name-pt = Pɔtugal
region-name-pw = Palau
region-name-py = Paraguay
region-name-qa = Kata
region-name-re = Reyuniɔn
region-name-ro = Romenia
region-name-rs = Sɛɛbia
region-name-rw = Rwanda
region-name-sa = Saudi Arabia
region-name-sb = Solomon Islands
region-name-sc = Seyhyɛl
region-name-sd = Sudan
region-name-se = Sweden
region-name-sg = Singapɔ
region-name-si = Slovinia
region-name-sk = Slovakia
region-name-sl = Sierra Leone
region-name-sm = San Marino
region-name-sn = Senegal
region-name-so = Somalia
region-name-sr = Suriname
region-name-st = São Tomé ne Príncipe
region-name-sv = Ɛl Salvadɔ
region-name-sy = Siria
region-name-sz = Swaziland
region-name-tc = Turks ne Caicos Islands
region-name-td = Kyad
region-name-tg = Togo
region-name-th = Taeland
region-name-tj = Tajikistan
region-name-tk = Tokelau
region-name-tl = Timor-Leste
region-name-tm = Tɛkmɛnistan
region-name-tn = Tunihyia
region-name-to = Tonga
region-name-tr = Tɛɛki
region-name-tt = Trinidad ne Tobago
region-name-tv = Tuvalu
region-name-tw = Taiwan
region-name-tz = Tanzania
region-name-ua = Ukren
region-name-ug = Uganda
region-name-us = Amɛrika
region-name-uy = Yurugwae
region-name-uz = Uzbɛkistan
region-name-va = Vatikan Man
region-name-vc = Saint Vincent ne Grenadines
region-name-ve = Venezuela
region-name-vn = Viɛtnam
region-name-vu = Vanuatu
region-name-wf = Wallis ne Futuna
region-name-ws = Samoa
region-name-ye = Yɛmɛn
region-name-yt = Mayɔte
region-name-za = Afrika Anaafo
region-name-zm = Zambia
region-name-zw = Zembabwe
