# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Chcesz wierzić „%S“ przi tych cylach?
unnamedCA = Wystowca certyfikatu (bez miana)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Wkludź hasło, co było użyte przi szyfrowaniu ibrycznyj kopii tego certyfikatu:
# Page Info
pageInfo_NoEncryption = Połōnczynie niy ma szyfrowane
pageInfo_Privacy_None1 = Necowy serwer %S niy ôbsuguje szyfrowanio strōny, na kero zaglōndosz.
pageInfo_Privacy_None2 = Na informacyje posyłane bez internet bez szyfrowanio może fto zaglōndać.
pageInfo_Privacy_None4 = Strōna, na kero zaglōndosz, niy była szyfrowano przed przesłaniym bez internet.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Szyfrowane połōnczynie (%1$S, %2$S-bitowe klucze, %3$S)
pageInfo_BrokenEncryption = Złōmane szyfrowanie (%1$S, %2$S-bitowe klucze, %3$S)
pageInfo_Privacy_Encrypted1 = Strōna, na kero zaglōndosz, była szyfrowano przed przesłaniym bez internet.
pageInfo_Privacy_Encrypted2 = Skuli szyfrowanio ôsoby bez uprawniyń bydōm mieć ciynżyj ôboczyć na informacyje, co idōm miyndzy kōmputrami. Skuli tego je mało prawdopodobne, iże fto poczytoł ta strōna, jak wandrowała po necu.
pageInfo_MixedContent = Połōnczynie je po tajli szyfrowane
pageInfo_MixedContent2 = Niykere kōnski pokazowanyj strōny niy były szyfrowane przed przesłaniym bez internet.
pageInfo_WeakCipher = Twoej połōnczynie z tōym serwerym używo słabego szyfrowanio i niy ma prywatne. Inksze ludzie poradzōm ôboczyć twoje dane abo zmiynić zachowanie tyj strōny.
pageInfo_CertificateTransparency_Compliant = Ta strōna sztimuje ze prawidłami Certificate Transparency.
# Token Manager
password_not_set = (niynastawiōne)
