# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SaveImageTitle = Stoor prent
SaveMediaTitle = Stoor media
SaveVideoTitle = Stoor video
SaveAudioTitle = Stoor klank
SaveLinkTitle = Stoor as
WebPageCompleteFilter = Webbladsy, volledig
WebPageHTMLOnlyFilter = Webbladsy, net HTML
WebPageXHTMLOnlyFilter = Webbladsy, net XHTML
WebPageSVGOnlyFilter = Webbladsy, net SVG
WebPageXMLOnlyFilter = Webbladsy, net XML
