# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

password-not-set =
    .value = (no set)
failed-pw-change = No able tae chynge Maister Passwird.
incorrect-pw = Ye didnae inpit whit's the richt Maister Passwird the noo. Gie it anither shot.
pw-change-ok = Maister Passwird chynged wioot onie problems.
pw-empty-warning = Yer stored wab and email passwird, form data, and preevat keys willnae be bieldit.
pw-erased-ok = Ye've dichtit yer Maister Passwird. { pw-empty-warning }
pw-not-wanted = Haud on! Ye've decidit no tae yaise a Maister Passwird. { pw-empty-warning }
pw-change2empty-in-fips-mode = Ye're in FIPS mode jist noo. FIPS needs a Maister Passwird that isnae tuim.
failed-pp-change = No able tae chynge Primary Passwird.
incorrect-pp = Ye didnae inpit the Primary Passwird that's richt jist noo. Gie it anither shot.
pp-change-ok = Primary Passwird chynged wioot onie problems.
pp-empty-warning = Your stored passwirds and preevat keys willnae be bieldit.
pp-erased-ok = Ye've dichtit yer Primary Passwird. { pp-empty-warning }
pp-not-wanted = Haud on! Ye've decidit no tae yaise a Primary Passwird. { pp-empty-warning }
pp-change2empty-in-fips-mode = The noo, ye're in FIPS modes. FIPS needs a Primary Passwird that isnae tuim.
pw-change-success-title = Passwird Chynge Wirked
pw-change-failed-title = Passwird Chynge Didnae Wirk
pw-remove-button =
    .label = Remuive
set-password =
    .title = Chynge Maister Passwird
primary-password-dialog =
    .title = Primary Passwird
set-password-old-password = Passwird the noo:
set-password-new-password = Inpit new passwird:
set-password-reenter-password = Inpit passwird aince mair:
set-password-meter = Passwird quality meter
set-password-meter-loading = Loadin
master-password-admin = Your admeenistrator needs ye tae hae a Maister Passwird set fur tae save passwirds.
master-password-description = A Maister Passwird is yaised fur tae bield sensitive information sic as site passwirds. Gin ye mak a Maister Passwird ye'll be speirt tae inpit it aince per session when { -brand-short-name } fetches saved information bieldit by the passwird.
master-password-warning = Mak siccar ye mind the Maister Passwird ye've set. Gin ye forget yer Maister Passwird, ye'll no be able tae hae ingang tae onie o the information bieldit by it.
remove-password =
    .title = Remuive Maister Passwird
primary-password-admin = Your admeenistrator needs ye tae hae a Primary Passwird set fur tae save logins and passwirds.
primary-password-description = A Primary Passwird is yaised fur tae bield some sensitive information, sic as logins and passwirds, on this device. Gin ye mak a Primary Passwird ye'll be speirt tae inpit it aince per session when { -brand-short-name } fetches saved information bieldit by the passwird.
primary-password-warning = Mak siccar ye mind the Primary Passwird ye've set. Gin ye forget yer Primary Passwird, ye'll no be able tae hae ingang tae onie o the information bieldit by it on this device.
remove-primary-password =
    .title = Remuive Primary Passwird
remove-info =
    .value = Ye maun inpit yer current passwird fur tae gang forrit:
remove-warning1 = Yer Maister Passwird is yaised fur tae bield sensitive information sic as site passwirds.
remove-warning2 = Gin ye remuive yer Maister Passwird yer information willnae be bieldit gin yer computer is unnermined.
remove-primary-password-warning1 = Yer Primary Passwird is yaised fur tae bield sensitive information sic as logins and passwirds.
remove-primary-password-warning2 = Gin ye remuive yer Primary Passwird yer information willnae be bieldit gin yer computer is unnermined.
remove-password-old-password =
    .value = Passwird the noo:
