# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = විවෘත කරන්න
    .accesskey = O
places-open-all-in-tabs =
    .label = සියල්ල ටැබ තුළ විවෘත කරන්න
    .accesskey = O
places-view =
    .label = දසුන්
    .accesskey = w
places-by-date =
    .label = දිනය අනුව
    .accesskey = D
places-by-site =
    .label = අඩවිය අනුව
    .accesskey = S
places-by-most-visited =
    .label = වැඩි පිවිසුම්වාර ගණන අනුව
    .accesskey = V
places-by-last-visited =
    .label = අවසන්වර පිවිසුම අනුව
    .accesskey = L
places-by-day-and-site =
    .label = දිනය සහ අඩවිය අනුව පෙළ ගැසු
    .accesskey = t
places-history-search =
    .placeholder = සෙවුම් ඉතිහාසය
places-history =
    .aria-label = ඉතිහාසය
places-bookmarks-search =
    .placeholder = සෙවුම් පිටුසලකුණු
places-delete-domain-data =
    .label = මෙම පිටුව ගැන නොසිතන්න
    .accesskey = F
places-sortby-name =
    .label = නම අනුව පෙළ ගැසු
    .accesskey = r
places-file-close =
    .label = වසන්න
    .accesskey = C
places-cmd-close =
    .key = w
places-view-menu-columns =
    .label = තීරු දර්ශනය
    .accesskey = C
places-view-menu-sort =
    .label = අනුපිළිවෙලට සැකසු
    .accesskey = S
places-view-sort-unsorted =
    .label = අනුපිළිවෙලට නොසැකසු
    .accesskey = U
places-view-sort-ascending =
    .label = A > Z පිළිවෙළ
    .accesskey = A
places-view-sort-descending =
    .label = Z > A පිළිවෙළ
    .accesskey = Z
places-cmd-backup =
    .label = රක්‍ෂිතය…
    .accesskey = B
places-cmd-restore-from-file =
    .label = ගොනුව තෝරන්න…
    .accesskey = C
places-view-sort-col-name =
    .label = නම
places-view-sort-col-tags =
    .label = ලේබල
places-view-sort-col-url =
    .label = පිහිටුම
places-view-sort-col-visit-count =
    .label = පිවිසුම් එකතුව
places-view-sort-col-date-added =
    .label = එක් කළා
places-view-sort-col-last-modified =
    .label = අවසන් වෙනස්කම
places-cmd-find-key =
    .key = f
places-back-button =
    .tooltiptext = පසුපසට යන්න
places-forward-button =
    .tooltiptext = ඉදිරියට යන්න
places-details-pane-select-an-item-description = වත්කම් දර්ශනයට සහ සැකසීමට අයිතමයක් තෝරන්න
