# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = שמירה
dialogTitleAddBookmark = הוספת סימנייה
dialogTitleAddMulti = יצירת סימניות לכל הלשוניות
dialogTitleEdit = מאפיינים עבור "%S"
dialogTitleAddNewBookmark2 = הוספת סימנייה
dialogTitleEditBookmark = עריכת ״%S״
dialogTitleEditBookmark2 = עריכת סימנייה
dialogTitleAddBookmarkFolder = הוספת תיקיית סימניות
dialogTitleEditBookmarkFolder = עריכת תיקיית סימניות
bookmarkAllTabsDefault = [שם תיקייה]
newFolderDefault = תיקייה חדשה
newBookmarkDefault = סימנייה חדשה
