# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language-name-aa = آفار
language-name-ab = ابخازی
language-name-ach = اچولی
language-name-ae = اویسٹن
language-name-af = افریقانی
language-name-ak = عکن
language-name-am = امہارى
language-name-an = ایراگونیز
language-name-ar = عربی
language-name-as = آسامی
language-name-ast = آسٹرین
language-name-av = اویرک
language-name-ay = ایمارا
language-name-az = آزربائیجانی
language-name-ba = باشکیر
language-name-be = بیلاروسی
language-name-bg = بلغاری
language-name-bh = بہاری
language-name-bi = بسلاما
language-name-bm = بامبرا
language-name-bn = بنگالی
language-name-bo = تبتى
language-name-br = بریٹون
language-name-bs = بوسینی
language-name-ca = کٹالن
language-name-cak = کاکچیل
language-name-ce = چیچن
language-name-ch = چمورو
language-name-co = کارسیکائی
language-name-cr = کرعی
language-name-crh = کرایمن ٹاٹر
language-name-cs = چیک
language-name-csb = کشوبیئن
language-name-cu = چرچ سلاوی
language-name-cv = كوئیش
language-name-cy = ویلش
language-name-da = ‏‏ڈینیش
language-name-de = جرمن
language-name-dsb = ہیٹھلی ساربیائی
language-name-dv = دھیوی
language-name-dz = زونکا
language-name-ee = اوی
language-name-el = یونانی
language-name-en = انگریزی
language-name-eo = اسپرانٹو
language-name-es = سپینی
language-name-et = ایسٹونی
language-name-eu = باسک
language-name-fa = فارسی
language-name-ff = فولا
language-name-fi = فینش
language-name-fj = فجی
language-name-fo = فاروس
language-name-fr = فرانسیسی
language-name-fur = فریولیئن
language-name-fy = فریسیان
language-name-ga = آئرش
language-name-gd = اسکاٹی گائل
language-name-gl = گیلیکین
language-name-gn = گورانی
language-name-gu = گجراتی
language-name-gv = مانوی
language-name-ha = ہوسا
language-name-haw = ہوائی
language-name-he = عبرانی
language-name-hi = ہندی
language-name-hil = ہیلیگینون
language-name-ho = ہیری موٹو
language-name-hr = کروشین
language-name-hsb = اتلی سربین
language-name-ht = ہیٹین
language-name-hu = ہنگرین
language-name-hy = آرمینی
language-name-hz = ہریرو
language-name-ia = انٹرلنگوا
language-name-id = انڈونیشی
language-name-ie = انٹرلنگو
language-name-ig = اگبو
language-name-ii = سچوان ژی
language-name-ik = انوپياک
language-name-io = ایڈی
language-name-is = آئی لینڈی
language-name-it = اٹالین
language-name-iu = اینک ٹیٹوٹ
language-name-ja = جاپانی
language-name-jv = جاوانیس
language-name-ka = جارجین
