# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Notice: If you're updating this list, you should also
###         update the list in mozIntl.js.

region-name-ad = آندورہ
region-name-ae = متحدہ عرب امارات
region-name-af = افغانستان
region-name-ag = انٹیگا اور باربودا
region-name-ai = آنگویلا
region-name-al = البانیہ
region-name-am = آرمینیا
region-name-ao = انگولا
region-name-aq = انٹارکٹیکا
region-name-ar = ارجنٹینا
region-name-as = امریکی ساموا
region-name-at = آسٹریا
region-name-au = آسٹریلیا
region-name-aw = آروبا
region-name-az = آذربائیجان
region-name-ba = بوسنیا و ہرزیگووینا
region-name-bb = باربدوس
region-name-bd = بنگلہ دیش
region-name-be = بلجیئم
region-name-bf = برکینا فاسو
region-name-bg = بلغاریہ
region-name-bh = بحرین
region-name-bi = برونڈی
region-name-bj = بینن
region-name-bl = سینٹ بارٹہلمی
region-name-bm = برمودا
region-name-bn = برونائی
region-name-bo = بولیویا
region-name-bq = نیوس ، سنٹ یوسٹیشیس ،تے صبا
region-name-bq-2018 = کاربین نیدرلینڈ
region-name-br = برازیل
region-name-bs = بہاماز، دی
region-name-bt = بھوٹان
region-name-bv = بووٹ آِلینڈ
region-name-bw = بوٹسوانا
region-name-by = بیلارس
region-name-bz = بیلزے
region-name-ca = کینیڈا
region-name-cc = کوکوس (کیلنگ) آئلینڈز
region-name-cd = کانگو-کنشاسا
region-name-cf = وسطی افریقائی جمہوریہ
region-name-cg = کانگو (برازاویلے)
region-name-ch = سوئٹزر لینڈ
region-name-ci = آئیوری کوسٹ
region-name-ck = جزائر کک
region-name-cl = چائل
region-name-cm = کیمرون
region-name-cn = چین
region-name-co = کولمبیا
region-name-cp = کلپرٹن جزیرہ
region-name-cr = کوسٹاریکا
region-name-cu = کیوبا
region-name-cv = کیپ وردے
region-name-cv-2020 = کیپ وردے
region-name-cw = کیوراساؤ
region-name-cx = کرسمس جزیرہ
region-name-cy = قبرص
region-name-cz = جمہوریہ چیک
region-name-cz-2019 = چیچیا
region-name-de = جرمنی
region-name-dg = ڈیاگو گارسیا
region-name-dj = جبوتی
region-name-dk = ڈنمارک
region-name-dm = ڈومینیکا
region-name-do = ڈومینیکائی جمہوریہ
region-name-dz = الجیریا
region-name-ec = ایکواڈور
region-name-ee = استونیا
region-name-eg = مصر
region-name-eh = مغربی سہارا
region-name-er = اریٹریہ
region-name-es = سپین
region-name-et = ایتھوپیا
region-name-fi = فن لینڈ
region-name-fj = فجی
region-name-fk = جزائر فاک لینڈ (مالویناس)
region-name-fm = مائکرونیزیا، وفاقی ریاستوں
region-name-fo = فارو جزائر
region-name-fr = فرانس
region-name-ga = گبون
region-name-gb = برطانیہ
region-name-gd = گریناڈا
region-name-ge = جارجیا
region-name-gf = فرانیسی گنی
region-name-gg = گیرنسی
region-name-gh = گھانا
region-name-gi = جبرالٹر
region-name-gl = گرین لینڈ
region-name-gm = گیمبیا،
region-name-gn = گنی
region-name-gp = گواڈیلوپ
region-name-gq = استوائی گنی
region-name-gr = یونان
region-name-gs = جنوبی جارجیہ تے جنوبی سینڈوچ جزائر
region-name-gt = گوئٹے مالا
region-name-gu = گام
region-name-gw = گنی بساؤ
