#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

#define MOZ_LANGPACK_HOMEPAGE http://www.hacksrus.com/~ginda/venkman/

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Adrian Kalla</em:contributor> <em:contributor>Marek Wawoczny</em:contributor> <em:contributor>Piotr Bartecki</em:contributor> <em:contributor>Rafał Likus</em:contributor>

#unfilter emptyLines
