#filter emptyLines

#define MOZ_LANGPACK_CREATOR Тим дебагера за јаваскрипт

#define MOZ_LANGPACK_HOMEPAGE http://www.hacksrus.com/~ginda/venkman/

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Филип Милетић</em:contributor> <em:contributor>Наше писмо</em:contributor>\n

#unfilter emptyLines
