# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host } ostalaria ebazten…
network-connection-status-connected = Konektatuta - { $host }…
network-connection-status-sending-request = Eskaera bidaltzen --> { $host }…
network-connection-status-transferring-data = { $host } --> Datuak transferitzen…
network-connection-status-connecting = Konektatzen - { $host }…
network-connection-status-read = { $host } irakurri du
network-connection-status-wrote = { $host } idatzi du
network-connection-status-waiting = { $host }(r)en zain…
network-connection-status-looked-up = { $host } ostalaria ebatzita…
network-connection-status-tls-handshake = { $host }(r)ekin TLS diosala burutzen…
network-connection-status-tls-handshake-finished = { $host }(r)ekin TLS diosala amaituta…
