# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = उइजार्डखौ लाबो
import-from =
    { PLATFORM() ->
        [windows] निफ्राय उफ्रा, बुकमार्क, जारिमिन, पासवर्ड आरो गुबुन डाटा लाबो:
       *[other] निफ्राय पसन्द, बुकमार्क, जारिमिन, पासवर्ड आरो गुबुन डाटा लाबो:
    }
import-from-bookmarks = निफ्राय बुकमार्कफोरखौ लाबो:
import-from-ie =
    .label = माइक्र'सफ्ट इन्टारनेट एक्सप्ल'रार
    .accesskey = M
import-from-nothing =
    .label = जेबो लाबोनो नाङा
    .accesskey = D
import-from-safari =
    .label = साफारि
    .accesskey = S
import-from-chrome =
    .label = क्रम
    .accesskey = C
import-from-chrome-dev =
    .label = क्रम देभ
    .accesskey = D
import-from-firefox =
    .label = फायारफक्स
    .accesskey = x
no-migration-sources = बुकमार्क, जारिमिन एबा पासवार्ड डाटा थानाय जेबो डाटा मोनाखै।
import-source =
    .label = सेटिं आरो डाटाखौ लाबो
import-items-title =
    .label = लाबोबो थाखाय आइटेमफोर
import-items-description = लाबोनांगौ आइटेमफोरखौ सायख:
import-migrating-title =
    .label = लाबो गासिनो दङ...
import-migrating-description = गाहायनि आइटेमफोरखौ दा लाबोनाय जागासिनो दङ...
import-select-profile-title =
    .label = प्रफाइल सायख
import-select-profile-description = ..निफ्राय गाहायनि प्रफाइलफोरखौ लाबोनो थाखाय मोननो हाथाव:
import-done-title =
    .label = लाबोनाया जोबबाय
import-done-description = गाहायनि आइटेमफोरखौ जाफुंसारै लाबोबाय:
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = { $source } निफ्राय
source-name-ie = इन्टारनेट एक्सप्ल'रार
source-name-safari = साफारि
source-name-chrome = गुगल क्रम
source-name-chrome-beta = गुगल क्रम बेटा
source-name-chrome-dev = गुगल क्रम देभ
source-name-firefox = मजिला फायारफक्स
imported-safari-reading-list = (साफारि निफ्राय) लिस्टखौ फराय गासिनो दं

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = इन्टारनेट उफ्राफोर
    .value = इन्टारनेट उफ्राफोर
browser-data-edge-1 =
    .label = सेटिं
    .value = सेटिं
browser-data-safari-1 =
    .label = पसन्दफोर
    .value = पसन्दफोर
browser-data-chrome-1 =
    .label = पसन्दफोर
    .value = पसन्दफोर
browser-data-canary-1 =
    .label = पसन्दफोर
    .value = पसन्दफोर
browser-data-ie-2 =
    .label = कुकिफोर
    .value = कुकिफोर
browser-data-edge-2 =
    .label = कुकिफोर
    .value = कुकिफोर
browser-data-safari-2 =
    .label = कुकिफोर
    .value = कुकिफोर
browser-data-chrome-2 =
    .label = कुकिफोर
    .value = कुकिफोर
browser-data-canary-2 =
    .label = कुकिफोर
    .value = कुकिफोर
browser-data-firefox-2 =
    .label = कुकिफोर
    .value = कुकिफोर
browser-data-360se-2 =
    .label = कुकिफोर
    .value = कुकिफोर
browser-data-ie-4 =
    .label = ब्राउजिं जारिमिन
    .value = ब्राउजिं जारिमिन
browser-data-edge-4 =
    .label = ब्राउजिं जारिमिन
    .value = ब्राउजिं जारिमिन
browser-data-safari-4 =
    .label = ब्राउजिं जारिमिन
    .value = ब्राउजिं जारिमिन
browser-data-chrome-4 =
    .label = ब्राउजिं जारिमिन
    .value = ब्राउजिं जारिमिन
browser-data-canary-4 =
    .label = ब्राउजिं जारिमिन
    .value = ब्राउजिं जारिमिन
browser-data-firefox-history-and-bookmarks-4 =
    .label = ब्राउजिं जारिमिन आरो बुकमार्क
    .value = ब्राउजिं जारिमिन आरो बुकमार्क
browser-data-360se-4 =
    .label = ब्राउजिं जारिमिन
    .value = ब्राउजिं जारिमिन
browser-data-ie-8 =
    .label = थिना दोननाय फर्म जारिमिन
    .value = थिना दोननाय फर्म जारिमिन
browser-data-edge-8 =
    .label = थिना दोननाय फर्म जारिमिन
    .value = थिना दोननाय फर्म जारिमिन
browser-data-safari-8 =
    .label = थिना दोननाय फर्म जारिमिन
    .value = थिना दोननाय फर्म जारिमिन
browser-data-chrome-8 =
    .label = थिना दोननाय फर्म जारिमिन
    .value = थिना दोननाय फर्म जारिमिन
browser-data-canary-8 =
    .label = थिना दोननाय फर्म जारिमिन
    .value = थिना दोननाय फर्म जारिमिन
browser-data-firefox-8 =
    .label = थिना दोननाय फर्म जारिमिन
    .value = थिना दोननाय फर्म जारिमिन
browser-data-360se-8 =
    .label = थिना दोननाय फर्म जारिमिन
    .value = थिना दोननाय फर्म जारिमिन
browser-data-ie-16 =
    .label = थिना दोनखानाय पासवार्ड
    .value = थिना दोनखानाय पासवार्ड
browser-data-edge-16 =
    .label = थिना दोनखानाय पासवार्ड
    .value = थिना दोनखानाय पासवार्ड
browser-data-safari-16 =
    .label = थिना दोनखानाय पासवार्ड
    .value = थिना दोनखानाय पासवार्ड
browser-data-chrome-16 =
    .label = थिना दोनखानाय पासवार्ड
    .value = थिना दोनखानाय पासवार्ड
browser-data-canary-16 =
    .label = थिना दोनखानाय पासवार्ड
    .value = थिना दोनखानाय पासवार्ड
browser-data-firefox-16 =
    .label = थिना दोनखानाय पासवार्ड
    .value = थिना दोनखानाय पासवार्ड
browser-data-360se-16 =
    .label = थिना दोनखानाय पासवार्ड
    .value = थिना दोनखानाय पासवार्ड
browser-data-safari-32 =
    .label = बुकमार्क
    .value = बुकमार्क
browser-data-chrome-32 =
    .label = बुकमार्क
    .value = बुकमार्क
browser-data-canary-32 =
    .label = बुकमार्क
    .value = बुकमार्क
browser-data-360se-32 =
    .label = बुकमाकॅफोर
    .value = बुकमाकॅफोर
browser-data-ie-64 =
    .label = गुबुन डाटा
    .value = गुबुन डाटा
browser-data-edge-64 =
    .label = गुबुन डाटा
    .value = गुबुन डाटा
browser-data-safari-64 =
    .label = गुबुन डाटा
    .value = गुबुन डाटा
browser-data-chrome-64 =
    .label = गुबुन डाटा
    .value = गुबुन डाटा
browser-data-canary-64 =
    .label = गुबुन डाटा
    .value = गुबुन डाटा
browser-data-firefox-other-64 =
    .label = गुबुन डाटा
    .value = गुबुन डाटा
browser-data-360se-64 =
    .label = गुबुन डाटा
    .value = गुबुन डाटा
browser-data-firefox-128 =
    .label = उइन्ड'स आरो टेबफोर
    .value = उइन्ड'स आरो टेबफोर
