# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# DO NOT ADD THINGS OTHER THAN ERROR MESSAGES HERE.
# This file gets parsed into a JS dictionary of all known error message ids in
# gen_aboutneterror_codes.py . If we end up needing fluent attributes or
# refactoring them in some way, the script will need updating.

psmerr-ssl-disabled = रैखाथियै फोनांजाब खालामनो हाया मानोना SSL प्र'ट'कलखौ लोरबां खालामनाय जाबाय।
psmerr-ssl2-disabled = रैखाथियै फोनांजाब खालामनो हाया मानोना बे साइटआ SSL प्र'ट'कलनि गोजाम आरो रैखाथि-नङै बिसानखौ बाहायो।

# This is a multi-line message.
psmerr-hostreusedissuerandserial =
    नोंथाङा मोनसे बाहायजायै सार्टिफिकेट मोनबाय। अननानै सार्भार खुंगिरि एबा इ-मेइल थान्दैजों जगाजग खालाम आरो गाहायनि फोरमायथिहोग्राखौ हो:
    
    नोंथांनि सार्टिफिकेटआव सार्टिफिकेट अथ'रिटिजों दिहुनजानाय गुबुन मोनसे सार्टिफिकेट बादि एखे फारि अनजिमा दं। मोनसे रुजुजायै फारि अनजिमा गोनां मोनसे गोदान सार्टिफिकेट ला।

ssl-error-no-cypher-overlap = पियारजों रैखाथियै सुंजाबथाय खालामनो हाया: जेबो सरासनस्रा इनक्राइपसन एलग'रिडम गैया
ssl-error-no-certificate = थार फोरमाननि थाखाय गोनांथि जानाय चार्टिफिकेट एबा साबि नागिरना दिहुननो हायाखै।
ssl-error-bad-certificate = पियारजों रैखाथियै सुंजाबथाय खालामनो हायाखै: पियारेनि सार्टिफिकेटखौ नेवसिबाय।
ssl-error-bad-client = सार्भारा क्लाइन्ट निफ्राय फैनाय गाज्रि डाटाजों मोगा मोगि जाबाय।
ssl-error-bad-server = क्लाइन्टआ सार्भार निफ्राय फैनाय गाज्रि डाटाजों मोगा मोगि जाबाय।
ssl-error-unsupported-certificate-type = मदद होजायै चार्टिफिकेट रोखोम।
ssl-error-unsupported-version = पियारआ रैखाथि प्र'ट'कलनि मदद होजायै लिरस्लायनायखौ बाहाय गासिनो दङ।
ssl-error-wrong-certificate = क्लाइट थारफोरमानआ फेलें जाबाय: साबि डाटाबेसआव थानाय प्राइभेट साबिआ सार्टिफिकेट डाटाबेसआव थानाय पाब्लिक साबिजों गोरोबा।
ssl-error-bad-cert-domain = पियारजों रैखाथियै सुंजाबथाय खालामनो हायाखै: खावलायखानाय डमेइन मुंआ सार्भारनि सार्टिफिकेटजों गोरोबा।
ssl-error-ssl2-disabled = पियारआ SSL लिरस्लायनाय 2 खौल' मदद होयो, जायखौ जायगानि महरै लोरबां खालामनाय जायो।
ssl-error-bad-mac-read = SSL आ गोरोनथि खौरां थार फोरमान क'डजों लोगोसे मोनसे रेकर्ड मोनबाय।
ssl-error-bad-mac-alert = SSL पियारआ गोरोनथि खौरां थार फोरमान क'डखौ रिपर्ट खालामो।
ssl-error-bad-cert-alert = SSL पियारआ नोंथांनि चार्टिफिकेटखौ नायबिजिरनो हाया।
ssl-error-revoked-cert-alert = SSL पियारआ बोखारनाय बादि नोंथांनि चार्टिफिकेटखौ नेवसिबाय।
ssl-error-expired-cert-alert = SSL पियारआ मेयाद बारनाय बादि नोंथांनि चार्टिफिकेटखौ नेवसिबाय।
ssl-error-ssl-disabled = फोनांजाब खालामनो हाया: SSL आ लोरबां।
ssl-error-fortezza-pqg = फोनांजाब खालामनो हाया: SSL पियारआ गुबुन मोनसे FORTEZZA डमेइनआव दङ।
ssl-error-unknown-cipher-suite = मोनसे मोनथिमोनै SSL सिपार सुइटखौ खावलायनाय जाबाय।
ssl-error-no-ciphers-supported = बे प्रग्रामाव जेबो सिपार सुइट गैया आरो मावथि खालामाखै।
ssl-error-bad-block-padding = SSL आ गाज्रि ब्लक पेड्डिंजों मोनसे रेकर्ड मोनबाय।
ssl-error-rx-record-too-long = SSL आ मोनसे रेकर्ड मोनबाय जायनि गोलावथिया गनायथिनायखौ बारलाङो।
ssl-error-tx-record-too-long = SSL आ मोनसे रेकर्डखौ दैथाय हरनो नाजाबाय जाय बांसिन गनायथिनाय सिमाखौ बारबाय।
ssl-error-rx-malformed-hello-request = SSL आ मोनसे गाज्रि महरनि हेल्ल' खावलायनाय हेन्डशेक खौरां मोनबाय।
ssl-error-rx-malformed-client-hello = SSL आ मोनसे गाज्रि महरनि क्लाइन्ट हेल्ल' हेन्डशेक खौरां मोनबाय।
ssl-error-rx-malformed-server-hello = SSL आ मोनसे गाज्रि महरनि सार्भार हेल्ल' हेन्डशेक खौरां मोनबाय।
ssl-error-rx-malformed-certificate = SSL आ मोनसे गाज्रि महरनि चार्टिफिकेट हेन्डशेक खौरां मोनबाय।
ssl-error-rx-malformed-server-key-exch = SSL आ मोनसे गाज्रि महरनि सार्भार साबि सोलाय सोल' हेन्डशेक खौरां मोनबाय।
ssl-error-rx-malformed-cert-request = SSL आ मोनसे गाज्रि महरनि चार्टिफिकेट खावलायनाय हेन्डशेक खौरां मोनबाय।
ssl-error-rx-malformed-hello-done = SSL आ मोनसे गाज्रि महरनि सार्भार हेल्ल' मावखांबाय हेन्डशेक खौरां मोनबाय।
ssl-error-rx-malformed-cert-verify = SSL आ मोनसे गाज्रि महरनि चार्टिफिकेट नायबिजिरनाय हेन्डशेक खौरां मोनबाय।
ssl-error-rx-malformed-client-key-exch = SSL आ मोनसे गाज्रि महरनि क्लाइन्ट साबि सोलाय सोल' हेन्डशेक खौरां मोनबाय।
ssl-error-rx-malformed-finished = SSL आ मोनसे गाज्रि महरनि फोजोबनाय हेन्डशेक खौरां मोनबाय।
ssl-error-rx-malformed-change-cipher = SSL आ मोनसे गाज्रि महरनि सोलायनाय सिपार स्पेक रेकर्ड मोनबाय।
ssl-error-rx-malformed-alert = SSL आ मोनसे गाज्रि महरनि सांग्रां रेकर्ड मोनबाय।
ssl-error-rx-malformed-handshake = SSL आ मोनसे गाज्रि महरनि हेन्डशेक रेकर्ड मोनबाय।
ssl-error-rx-malformed-application-data = SSL आ मोनसे गाज्रि महरनि एप्लिकेसन डाटा रेकर्ड मोनबाय।
ssl-error-rx-unexpected-hello-request = SSL आ मोनसे मिजिंथियै हेल्ल' खावलायनाय हेन्डशेक खौरां मोनबाय।
ssl-error-rx-unexpected-client-hello = SSL आ मोनसे मिजिंथियै क्लाइन्ट हेल्ल' हेन्डशेक खौरां मोनबाय।
ssl-error-rx-unexpected-server-hello = SSL आ मोनसे मिजिंथियै सार्भार हेल्ल' हेन्डशेक खौरां मोनबाय।
ssl-error-rx-unexpected-certificate = SSL आ मोनसे मिजिंथियै चार्टिफिकेट हेन्डशेक खौरां मोनबाय।
ssl-error-rx-unexpected-server-key-exch = SSL आ मोनसे मिजिंथियै सार्भार साबि सोलाय सोल' हेन्डशेक खौरां मोनबाय।
ssl-error-rx-unexpected-cert-request = SSL आ मोनसे मिजिंथियै चार्टिफिकेट खावलायनाय हेन्डशेक खौरां मोनबाय।
ssl-error-rx-unexpected-hello-done = SSL आ मोनसे मिजिंथियै सार्भार हेल्ल' मावखांबाय हेन्डशेक खौरां मोनबाय।
ssl-error-rx-unexpected-cert-verify = SSL आ मोनसे मिजिंथियै चार्टिफिकेट नायबिजिरनाय खौरां मोनबाय।
ssl-error-rx-unexpected-client-key-exch = SSL आ मोनसे मिजिंथियै क्लाइन्ट साबि सोलाय सोल' हेन्डशेक खौरां मोनबाय।
ssl-error-rx-unexpected-finished = SSL आ मोनसे मिजिंथियै फोजोबनाय हेन्डशेक खौरां मोनबाय।
ssl-error-rx-unexpected-change-cipher = SSL आ मोनसे मिजिंथियै सोलायनाय सिपार स्पेक रेकर्ड मोनबाय।
ssl-error-rx-unexpected-alert = SSL आ मोनसे मिजिंथियै सांग्रां रेकर्ड मोनबाय।
ssl-error-rx-unexpected-handshake = SSL आ मोनसे मिजिंथियै हेन्डशेक रेकर्ड मोनबाय।
ssl-error-rx-unexpected-application-data = SSL आ मोनसे मिजिंथियै एप्लिकेसन डाटा रेकर्ड मोनबाय।
ssl-error-rx-unknown-record-type = SSL आ मोनसे मोनथिमोनै आयदा रोखोमजों रेकर्ड मोनबाय।
ssl-error-rx-unknown-handshake = SSL आ मोनसे मोनथिमोनै खौरां रोखोमजों हेन्डशेक खौरां मोनबाय।
ssl-error-rx-unknown-alert = SSL आ मोनसे मोनथिमोनै सांग्रांजों सांग्रां रेकर्ड मोनबाय।
ssl-error-close-notify-alert = SSL पियारआ बे फोनांजाबखौ बन्द खालामबाय।
ssl-error-handshake-unexpected-alert = SSL पियारआ गाव मोननाय हेन्डशेक खौरांखौ मिजिंथियाखैमोन।
ssl-error-decompression-failure-alert = SSL पियारआ मोननाय मोनसे SSL रेकर्डखौ जाफुंसारै डिकमप्रेस खालामनो हायाखै।
ssl-error-handshake-failure-alert = SSL पियारआ रैखाथि पेरामिटारनि मोनसे आजावथाव जथायखौ बन्दबस्ट खालामनो हायाखै।
ssl-error-illegal-parameter-alert = SSL पियारआ मोनसे हेन्डशेक खौरांखौ गनायजायै आयदानि थाखाय नेवसिबाय।
ssl-error-unsupported-cert-alert = SSL पियारआ गाव मोननाय चार्टिफिकेट रोखोमखौ मदद होआ।
ssl-error-certificate-unknown-alert = SSL पियारआ गाव मोननाय चार्टिफिकेटजों थि खालामै जेंना दङमोन।
ssl-error-generate-random-failure = SSL आ बेनि मोनसे फेलें रेण्डम अनजिमा दिहुनग्राखौ बाहायदोंमोन।
ssl-error-sign-hashes-failure = नोंथांनि चार्टिफिकेटखौ नायबिजिरनो गोनांथि जानाय डाटाखौ डिजिटालि सहि होनो हायाखै।
ssl-error-extract-public-key-failure = SSL आ पाब्लिक साबिखौ पियार चार्टिफिकेट निफ्राय लाबोनो हायाखैमोन।
ssl-error-server-key-exchange-failure = SSL सार्भार साबि सोलाय सोल' हेन्डशेकखौ प्रचेछ खालामनाय समाव थि नङै फेलें जाबाय।
ssl-error-client-key-exchange-failure = SSL क्लाइन्ट साबि सोलाय सोल' हेन्डशेकखौ प्रचेछ खालामनाय समाव थि नङै फेलें जाबाय।
ssl-error-encryption-failure = बाल्क डाटा इनक्रिपसन एलग'रिडमआ सायखखानाय सिपार सुइटआव फेलें जादोंमोन।
ssl-error-decryption-failure = बाल्क डाटा डिक्रिपसन एलग'रिडमआ सायखखानाय सिपार सुइटआव फेलें जादोंमोन।
ssl-error-socket-write-failure = सकेटखौ आन्डारलाइन खालामनो इनक्राइप्टेड डाटाखौ लिरनो नाजानायाव फेलें जादोंमोन।
ssl-error-md5-digest-failure = MD5 डाइजेस्ट खामानिआ फेलें जाबाय।
ssl-error-sha-digest-failure = SHA-1 डाइजेस्ट खामानिआ फेलें जाबाय।
ssl-error-mac-computation-failure = MAC हिसाबआ फेलें जाबाय।
ssl-error-sym-key-context-failure = समान साबि लोब्बागोनांखौ सोरजिनो फेलें जाबाय।
ssl-error-sym-key-unwrap-failure = समान साबिखौ क्लाइन्ट साबि सोलाय सोल' खौरांआव खोबसिनै खालामनो फेलें जाबाय।
ssl-error-pub-key-size-limit-exceeded = SSL सार्भारआ दैथायनाय चिफार सुइटजों डमेस्टिक-ग्रेड पाब्लिक साबिखौ बाहायनो नाजाबाय।
ssl-error-iv-param-failure = PKCS11 क'डआ मोनसे IV खौ पारामआव राव सोलायनो फेलें जाबाय।
ssl-error-init-cipher-suite-failure = सायखखानाय सिपार सुइटखौ जागायनो फेलें जाबाय।
ssl-error-session-key-gen-failure = क्लाइन्टआ SSL जुथुमानि थाखाय जुथुमा साबिखौ दिहुननो फेलें जाबाय।
ssl-error-no-server-key-for-alg = सार्भारहा नाजानाय साबि सोलाय सोल' एलग'रिडमनि थाखाय जेबो साबि गैया।
ssl-error-token-insertion-removal = अपारेसन सोलिबाय थानाय समाव PKCS#11 टकेनखौ सोसननाय एबा गैया खालामनाय जादोंमोन।
ssl-error-token-slot-not-found = मोनसे गोनांथि अपारेसननि थाखाय जेबो PKCS#11 टकेन मोननाय जायाखै।
ssl-error-no-compression-overlap = पियारजों रैखाथियै सुंजाबथाय खालामनो हाया: जेबो सरासनस्रा नारसिनाय एलग'रिडम गैया
ssl-error-handshake-not-completed = दानि हेन्डसेकआ फुरा जायागौमानि गुबुन मोनसे SSL हेन्डसेकखौ जागायनो हाया।
ssl-error-bad-handshake-hash-value = पियार निफ्राय गोरोनथि हेन्डशेक हेछ बेसेनफोर मोनबाय।
ssl-error-cert-kea-mismatch = होखानाय सार्टिफिकेटखौ सायखखानाय साबि सोलाय सोल' एलग'रिडमजों बाहायनो हाया।
ssl-error-no-trusted-ssl-client-ca = SSL क्लाइन्ट थार फोरमाननि थाखाय चार्टिफिकेट अथ'रिटिखौ फोथायनाय जाया।
ssl-error-session-not-found = क्लाइन्ट SSL जुथुमा ID खौ सार्भारनि जुथुमा केछआव मोननाय जाया।
ssl-error-decryption-failed-alert = पियारआ गाव मोननाय मोनसे SSL रेकर्डखौ डिक्राइप्ट खालामनो हायाखै।
ssl-error-record-overflow-alert = पियारआ मोनसे SSL रेकर्ड मोनबाय जायखौ गोलाव सम गनायथि जादोंमोन।
ssl-error-unknown-ca-alert = पियारआ नोंथांनि चार्टिफिकेटखौ इसु खालामनाय CA खौ सिनायथिया एबा फोथाया।
ssl-error-access-denied-alert = पियारआ मोनसे बाहाय जाथाव चार्टिफिकेट मोनबाय, नाथाय हाबनो हायाखै।
ssl-error-decode-error-alert = पियारआ मोनसे SSL हेन्डशेक खौरांखौ डिक'ड खालामनो हायाखै।
ssl-error-decrypt-error-alert = पियारआ फेलें सहि नायबिजिरनाय एबा साबि सोलाय सोल'खौ रिपर्ट खालामो।
ssl-error-export-restriction-alert = पियारआ दैथायनाय नेमखान्थिखौ मानियै बन्दबस्तखौ रिपर्ट खालामो।
ssl-error-protocol-version-alert = पियारआ गोरोबथिगोयै एबा मदद होजायै प्र'ट'कल लिरस्लायनायखौ रिपर्ट खालामो।
ssl-error-insufficient-security-alert = सार्भारनो क्लाइन्टआ मदद होनाय निख्रुइ बांसिन रैखाथि गोनां सिपारफोर नांगौ जायो।
ssl-error-internal-error-alert = पियारआ इसिङारि गोरोनथि जानायखौ रिपर्ट खालामो।
ssl-error-user-canceled-alert = पियार बाहायग्राया हेन्डशेकखौ नेवसिगारबाय।
ssl-error-no-renegotiation-alert = पियारआ SSL रैखाथि पारामिटारफोरनि फिन बन्दबस्तखौ गनायथि होआ।
ssl-error-server-cache-not-configured = SSL सार्भार केछखौ बे सकेटनि थाखाय महर दानाय आरो लोरबां खालामनाय जाया।
ssl-error-unsupported-extension-alert = SSL पियारआ खावलायखानाय TLS हेल्ल' बारायनायखौ मदद होआ।
ssl-error-certificate-unobtainable-alert = SSL पियारआ नोंथांनि चार्टिफिकेटखौ होखानाय URL निफ्राय मोननो हायाखै।
ssl-error-unrecognized-name-alert = SSL पियारहा खावलायखानाय DNS मुंनि थाखाय जेबो चार्टिफिकेट गैया।
ssl-error-bad-cert-status-response-alert = SSL पियारआ मोनसे OCSP फिननायखौ बेनि चार्टिफिकेटनि थाखा मोननो हायाखैमोन।
ssl-error-bad-cert-hash-value-alert = SSL पियारआ गाज्रि चार्टिफिकेट हेश बेसेनखौ रिपर्ट खालामबाय।
ssl-error-rx-unexpected-new-session-ticket = SSL आ मोनसे मिजिंथियै गोदान जथुम्मा टिकेट हेन्डसेक खौरां मोनबाय
ssl-error-rx-malformed-new-session-ticket = SSL आ मोनसे गाज्रिमहर गोदान जथुम्मा टिकेट हेन्डसेक खौरांखौ मोनबाय।
ssl-error-decompression-failure = SSL आ मोनसे नारसिनजानाय रेकर्ड मोनबाय जायखौ डिकमप्रेस खालामनो हाया।
ssl-error-renegotiation-not-allowed = फिन बन्दबस्टखौ बे SSL सकेटआव गनायथिनाय जाया।
ssl-error-unsafe-negotiation = पियारा गोजाम आदब (गोहोमगोनाङै गाग्लोबनाय) हेन्दसेकखौ नाजादों।
ssl-error-rx-unexpected-uncompressed-record = SSL आ मोनसे मिजिंथियै कमप्रेस खालामै रेकर्ड मोनबाय।
ssl-error-weak-server-ephemeral-dh-key = SSL आ मोनसे लोरबां ephemeral Diffie-Hellman साबिखौ सार्भार साबि सोलाय-सोल' हेन्डसेक खौरांआव मोनबाय।
ssl-error-next-protocol-data-invalid = SSL आ बाहायजायै NPN फेहेरनाय डाटाखौ मोनबाय।
ssl-error-feature-not-supported-for-ssl2 = SSL आखुथाया SSL 2.0 फोनांजाबनि थाखाय हेफाजाब होजाया।
ssl-error-feature-not-supported-for-servers = SSL आखुथाया सार्भारनि थाखाय हेफाजाब होजाया
ssl-error-feature-not-supported-for-clients = SSL आखुथाया क्लाइटनि थाखाय हेफाजाब होजाया
ssl-error-invalid-version-range = SSL बिसान सिमासारिआ बाहाय जाथाव नङा।
ssl-error-cipher-disallowed-for-version = SSL पियारआ सायखखानाय प्र'ट'कल बिसाननि थाखाय गनायथिहोयै मोनसे चिफार सुइटखौ सायखबाय।
ssl-error-rx-malformed-hello-verify-request = SSL आ मोनसे गाज्रि महर हेल्ल' थारबिजिरनाय खावलायनाय हेन्डसेक खौरां मोनबाय।
ssl-error-rx-unexpected-hello-verify-request = SSL आ मोनसे मिजिंथियै हेल्ल' थारबिजिरनाय खावलायनाय हेन्डसेक खौरां मोनबाय।
ssl-error-feature-not-supported-for-version = SSL आखुथाया प्र'ट'कल बिसाननि थाखाय हेफाजाब होजाया।
ssl-error-rx-unexpected-cert-status = SSL आ मोनसे मिजिंथियै सार्टिफिरेट थाथाइ हेन्डशेक खौरां मोनबाय।
ssl-error-unsupported-hash-algorithm = TLS जों बाहायजानाय हेफाजाब होजायै हेस एलग'रिडम।
ssl-error-digest-failure = डाइजेस्ट खामानिआ फेलें जाबाय
ssl-error-incorrect-signature-algorithm = गोरोन्थि सहि एलग'रिडमखौ डिजिटालि-सहि होनाय गुदिमुवाआव थिक खालामबाय।
ssl-error-next-protocol-no-callback = उननि प्र'ट'कल बन्दबस्ट फेहेरनायखौ हाहोनाय खालामदोंमोन, नाथाय कलबेकखौ गोनांथि जानायनि सिगां खोमोरदोंमोन।
ssl-error-next-protocol-no-protocol = सार्भारआ प्र'ट'कलखौ हेफाजाब होआ, क्लाइन्टआ ALPN फेहेरनायआव फोसावदिङो।
ssl-error-inappropriate-fallback-alert = सार्भारआ हेन्डसेकखौ नेवसिबाय मानोना क्लाइन्टआ सार्भार हेफाजाब होनाय निख्रुइ खमसिन TLS बिसानाव डाउनग्रेड खालामबाय।
sec-error-io = रैखाथि मोनथाय गोहो थानाय समाव मोनसे I/O गोरोनथि जाबाय।
sec-error-library-failure = रैखाथि बिजाब बाख्रि फेलें।
sec-error-bad-data = रैखाथि बिजाब बाख्रि: गाज्रि डाटा मोनबाय।
sec-error-output-len = रैखाथि बिजाब बाख्रि: आउटपुट गोलाव गोरोनथि।
sec-error-input-len = रैखाथि बिजाब बाख्रिआ इनपुट गोलाव गोरोनथिखौ बाहायबाय।
sec-error-invalid-args = रैखाथि बिजाब बाख्रि: बाहायजायै बाथ्राबानफोर।
sec-error-invalid-algorithm = रैखाथि बिजाब बाख्रि: बाहायजायै एलग'रिडम।
sec-error-invalid-ava = रैखाथि बिजाब बाख्रि: बाहायजायै AVA
sec-error-invalid-time = समनि स्ट्रिंखौ गोरोनथियै फरमेट दानाय जाबाय।
sec-error-bad-der = रैखाथि बिजाब बाख्रि: DER-एनक'डेड खौरांखौ गोरोनथियै फरमेट खालामबाय।
sec-error-bad-signature = पियारनि चार्टिफिकेटहा मोनसे बाहायजायै सहि दङ।
sec-error-expired-certificate = पियारनि चार्टिफिकेटआ मेयाद बारबाय।
sec-error-revoked-certificate = पियारनि चार्टिफिकेटखौ बोखारनाय जाबाय।
sec-error-unknown-issuer = पियारनि चार्टिफिकेट इसु खालामग्राखौ सिनायथिनाय जायाखै।
sec-error-bad-key = पियारनि पाब्लिक साबिया बाहायजायै।
sec-error-bad-password = हाबहोनाय रैखाथि पासवर्डआ गोरोनथि।
sec-error-no-nodelock = रैखाथि बिजाब बाख्रि: नडलक गैया
sec-error-bad-database = रैखाथि बिजाब बाख्रि: गाज्रि डाटाबेस
sec-error-no-memory = रैखाथि बिजाब बाख्रि: मेमरि रानना होनाया फेलें जाबाय।
sec-error-untrusted-issuer = पियारनि चार्टिफिकेट इसु खालामग्राखौ बाहायग्राजों फोथायै बादि दाग होनाय जाबाय।
sec-error-untrusted-cert = पियारनि चार्टिफिकेटखौ बाहायग्राजों फोथायै बादि दाग होनाय जाबाय।
sec-error-duplicate-cert = चार्टिफिकेटआ नोंथांनि डाटाबेसआव सिगाङावनो दङ।
sec-error-duplicate-cert-name = डाउनल'ड खालामखानाय चार्टिफिकेटनि मुंआ नोंथांनि डाटाबेसआव सिगाङावनो थाखानायखौ मोनसे डुप्लिकेट खालामो।
sec-error-adding-cert = डाटाबेसआव चार्टिफिकेटखौ दाजाबदेरनायाव जानाय गोरोनथि।
sec-error-filing-key = बे चार्टिफिकेटनि थाखाय साबिखौ फिन फाइल खालामनायाव जानाय गोरोनथि।
sec-error-no-key = बे चार्टिफिकेटनि थाखाय प्राइभेट साबिखौ साबि डाटाबेसआव मोननो हाया।
sec-error-cert-valid = बे चार्टिफिकेटआ बाहाय जाथाव।
sec-error-cert-not-valid = बे चार्टिफिकेटआ बाहाय जाथाव नङा।
sec-error-cert-no-response = सारट बिजाब बाख्रि: जेबो फिन होयाखै
sec-error-expired-issuer-certificate = सार्टिफिकेट दिहुनग्रानि सार्टिफिकेटआ मेयाद बारबाय। नोंथांनि सिस्टेमनि अक्ट' आरो समखौ आनजाद खालाम।
sec-error-crl-expired = सार्टिफिकेटनि दिहुनग्रानि थाखाय CRL आ मेयाद बारबाय। बेखौ आपडेट खालाम एबा सिस्टेमनि अक्ट' आरो समखौ आनजाद खालाम।
sec-error-crl-bad-signature = चार्टिफिकेट इसु खालामग्रानि थाखाय CRL हा बाहायजायै सहि दङ।
sec-error-crl-invalid = गोदान CRL हा मोनसे बाहायजायै फरमेट दङ।
sec-error-extension-value-invalid = चार्टिफिकेट बारायनाय बेसेना बाहायजायै।
sec-error-extension-not-found = चार्टिफिकेट बारायनायखौ मोनाखै।
sec-error-ca-cert-invalid = इसु खालामग्रा चार्टिफिकेटआ बाहायजायै।
sec-error-path-len-constraint-invalid = चार्टिफिकेट लामा गोलावथि बाध्यआ बाहायजायै।
sec-error-cert-usages-invalid = चार्टिफिकेट बाहायथि फोथारा बाहायजायै।
sec-internal-only = **इसिंआरि ONLY मडुल**
sec-error-invalid-key = साबिया खावलायखानाय अपारेसनखौ मदद होआ।
sec-error-unknown-critical-extension = चार्टिफिकेटआव मोनथिमोनै खैफोदगोनां बारायनाय दङ।
sec-error-old-crl = गोदान CRL आ दानि मोनसे निख्रुइ उननि नङा।
sec-error-no-email-cert = इनक्राइप्ट खालामाखै एबा सहि होआखै: थेवबो नोंथांहा मोनसे इ-मेइल चार्टिफिकेट गैया।
sec-error-no-recipient-certs-query = इनक्राइप्ट खालामाखै: थेवबो नोंथांहा मोनफा मोनग्रानि थाखाय चार्टिफिकेट गैया।
sec-error-not-a-recipient = डिक्राइप्ट खालामनो हाया: नोंथाङा मोनग्रा नङा, एबा गोरोबनाय सार्टिफिकेट आरो प्राइभेट साबिखौ मोनाखै।
sec-error-pkcs7-keyalg-mismatch = डिक्राइप्ट खालामनो हाया: साबि इनक्राइपसन एलग'रिडमआ नोंथांनि सार्टिफिकेटजों गोरोबा।
sec-error-pkcs7-bad-signature = सहि थारबिजिरनाया फेलें जाबाय: जेबो सहि होग्रा मोनाखै, जोबोद गोबां सहि होग्रा मोनबाय, एबा गोरोबै एबा गाज्रि जानाय डाटा मोनबाय।
sec-error-unsupported-keyalg = मदद होजायै एबा मोनथिमोनै साबि एलग'रिडम।
sec-error-decryption-disallowed = डिक्राइप्ट खालामनो हाया: इनक्राइपटेडआ मोनसे गनायथि होजायै एलग'रिडम एबा साबि महरखौ बाहाय गासिनो दङ।
xp-sec-fortezza-no-card = जेबो फर्टेज्जा कार्ड मोनाखै
xp-sec-fortezza-none-selected = जेबो फर्टेज्जा कार्ड सायखयाखै
xp-sec-fortezza-more-info = ..आव गोबां मोनथिहोनाय मोननो थाखाय मोनसे सुबुंथाय सायख
xp-sec-fortezza-person-not-found = सुबुंथाय मोनाखै
xp-sec-fortezza-no-more-info = बै सुबुंथायाव जेबो मोनथिहोनाय गैया
xp-sec-fortezza-bad-pin = बाहायजायै पिन
xp-sec-fortezza-person-error = फर्टेज्जा सुबुंथायखौ जागायनो हायाखै।
sec-error-no-krl = बे साइटनि चार्टिफिकेटनि थाखाय KRL मोनाखै।
sec-error-krl-expired = बे साइटनि चार्टिफिकेटनि थाखाय KRL आ मेयाद बारबाय।
sec-error-krl-bad-signature = बे साइटनि चार्टिफिकेटनि थाखाय KRL हा मोनसे बाहायजायै सहि दङ।
sec-error-revoked-key = बे साइटनि चार्टिफिकेटनि थाखाय KRL खौ बोखारबाय।
sec-error-krl-invalid = गोदान KRL हा मोनसे बाहायजायै फरमेट दङ।
sec-error-need-random = रैखाथि बिजाब बाख्रि: रेन्डम डाटा नांगौ
sec-error-no-module = रैखाथि बिजाब बाख्रि: जेबो रैखाथि मडुलआ खावलायखानाय अपारेसनखौ मावफुनो हाया।
sec-error-no-token = रैखाथि कार्ड एबा टकेनआ गैया, जागायनांगोन एबा बोखारबाय।
sec-error-read-only = रैखाथि बिजाब बाख्रि: फरायनो-थाखायल' डाटाबेस
sec-error-no-slot-selected = जेबो स्लट एबा टकेन सायखयाखै
sec-error-cert-nickname-collision = एखे उफ्रामुंनि चार्टिफिकेटआ सिगाङावनो दङ।
sec-error-key-nickname-collision = एखे उफ्रामुंनि साबिआ सिगाङावनो दङ।
sec-error-safe-not-created = रैखाथि बेसाद सोरजिनाय समाव जानाय गोरोनथि
sec-error-baggage-not-created = थफला-थफलि बेसाद सोरजिनाय समाव जानाय गोरोनथि
xp-java-remove-principal-error = गाहायखौ गैया खालामनो हायाखै
xp-java-delete-privilege-error = खाबुखौ खोमोरनो हायाखै
xp-java-cert-not-exists-error = बे गाहायहा चार्टिफिकेट गैया
sec-error-bad-export-algorithm = गोनांथि जानाय एलग'रिडमआ गनायथि गैया।
sec-error-exporting-certificates = चार्टिफिकेटफोरखौ दैथाय हरनो नाजानायाव जानाय गोरोनथि।
sec-error-importing-certificates = चार्टिफिकेटफोरखौ लाबोनो नाजानायाव जानाय गोरोनथि।
sec-error-pkcs12-unsupported-transport-mode = लाबोनो हायाखै। खालि पासवर्ड खौसेथि आरो गुमुर मडफोरखौल' मदद होनाय जायो।
sec-error-user-cancelled = बाहायग्राया नेवसिगारखौ प्रेस खालामबाय।
sec-error-pkcs12-duplicate-data = लाबोयाखै, डाटाबेसआव सिगाङावनो दङ।
sec-error-message-send-aborted = खौरांखौ दैथाय हराखै।
sec-error-inadequate-key-usage = नाजानाय अपारेसननि थाखाय चार्टिफिकेट साबि बाहायथिया थोआ।
sec-error-inadequate-cert-type = चार्टिफिकेट रोखोमखौ एप्लिकेसननि थाखाय गनायथिनाय जाया।
sec-error-cert-addr-mismatch = सहि होनाय सार्टिफिकेटनि थंआ खौरां हेडारनि थंजों गोरोबा।
sec-error-keygen-fail = पाब्लिक/प्राइभेट साबि जराखौ दिहुननो हायाखै।
sec-error-bad-nickname = चार्टिफिकेट उफ्रामुंखौ सिगाङावनो बाहाय खाबाय।
sec-error-not-fortezza-issuer = पियार FORTEZZA जिनज्रिहा FORTEZZA-नङै चार्टिफिकेट दङ।
sec-error-cannot-move-sensitive-key = बद गोनां साबिखौ गोनांथि जानाय जायगायाव लांनो हाया।
sec-error-js-invalid-module-name = बाहायजायै मडुल मुं
sec-error-js-invalid-dll = बाहायजायै मडुल लामा/फाइलमुं
sec-error-js-add-mod-failure = मडुल दाजाबदेरनो हायाखै
sec-error-js-del-mod-failure = मडुलखौ खोमोरनो हायाखै
sec-error-old-krl = गोदान KRL आ दानि मोनसे निख्रुइ उननि नङा।
sec-error-cert-not-in-name-space = बे सार्टिफिकेटनि थाखाय सार्टिफिकेट अथ'रिटिहा बे मुंनि सार्टिफिकेट दिहुननो गनायथि गैया।
sec-error-krl-not-yet-valid = बे चार्टिफिकेटनि थाखाय साबि रिभ'केसन लिस्टआ थेवबो बाहाय जाथाव नङा।
sec-error-crl-not-yet-valid = बे चार्टिफिकेटनि थाखाय चार्टिफिकेट रिभ'केसन लिस्टआ थेवबो बाहाय जाथाव नङा।
sec-error-unknown-cert = खावलायखानाय चार्टिफिकेटखौ मोनाखै।
sec-error-unknown-signer = सहि होग्रानि चार्टिफिकेटखौ मोनाखै।
sec-error-cert-bad-access-location = चार्टिफिकेट थाखोमान सार्भारनि थाखाय जायगाहा बाहायजायै फरमेट दङ।
sec-error-ocsp-unknown-response-type = OCSP फिननायखौ आबुङै डिक'ड खालामनो हाया; बेयो मोनसे मोनथिमोनै रोखाम।
sec-error-ocsp-bad-http-response = OCSP सार्भारा मिजिंथियै/बाहायजायै HTTP डाटाखौ फैफिन होबाय।
sec-error-ocsp-malformed-request = OCSP सार्भारा गाज्रि जानो गोनां खावलायनाय एबा गाज्रियै महर दानायखौ मोनबाय।
sec-error-ocsp-server-error = OCSP सार्भाराव इसिंआरि गोरोनथि जाबाय।
sec-error-ocsp-try-server-later = OCSP सार्भारा उनाव फिन नाजानो बोसोन होयो।
sec-error-ocsp-request-needs-sig = OCSP सार्भारनो बे खावलायनायाव मोनसे सहि गोनांथि जायो।
sec-error-ocsp-unauthorized-request = OCSP सार्भारा बे खावलायनायखौ मोनथाय गोहो गोयै बादि नेवसिबाय।
sec-error-ocsp-unknown-response-status = OCSP सार्भारा मोनसे सिनायथि खालाम जाथावै थाखोमानखौ फैफिन होबाय।
sec-error-ocsp-unknown-cert = OCSP सार्भारहा चार्टिफिकेटनि थाखाय जेबो थाखोमान गैया।
sec-error-ocsp-not-enabled = बे अपारेसनखौ मावफुंनायनि सिगां नोंथाङा OCSP खौ मावथि खालाम थारनांगोन।
sec-error-ocsp-no-default-responder = बे अपारेसनखौ मावफुंनायनि सिगां नोंथाङा OCSP डिफल्ट फिन होग्राखौ फजथारनांगोन।
sec-error-ocsp-malformed-response = OCSP सार्भार निफ्राय फैनाय फिननाया गाज्रि जाबाय एबा बेखौ गाज्रियै महर दानाय जाबाय।
sec-error-ocsp-unauthorized-response = OCSP फिननायनि सहि होग्राहा बे सार्टिफिकेटनि थाखाय थाथाइ होनो मोनथाय गैया।
sec-error-ocsp-future-response = OCSP फिननाया दासिमबो बाहाय जाथाव नङा (इयुनाव मोनसे डाटा थागोन)।
sec-error-ocsp-old-response = OCSP फिननायाव गोजाम मोनथिहोनाय दङ।
sec-error-digest-not-found = CMS एबा PKCS #7 डाइजेस्टखौ सहि होनाय खौरांआव मोननाय जायाखै।
sec-error-unsupported-message-type = CMS एबा PKCS #7 खौरां रोखोमखौ मदद होनाय जाया।
sec-error-module-stuck = PKCS #11 मडुलखौ गैया खालामनो हाया मानोना बेयो दासिमबो बाहाय जागासिनो दङ।
sec-error-bad-template = ASN.1 डाटाखौ डिक'ड खालामनो हायाखै। थिक खालामखानाय टेमप्लेटआ बाहायजायै।
sec-error-crl-not-found = CRL जों गोरोबनाय मोनाखै।
sec-error-reused-issuer-and-serial = नोंथाङा मोनसे थाखानाय cert बादि एखे दिहुनग्रा/फारिजों cert खौ लाबोनो नाजागासिनो दं, नाथाय बैयो एखे cert नङा।
sec-error-busy = NSS आ शाट डाउन खालामनो हायाखै। बेसादफोरा दासिमबो बाहाय जागासिनो दङ।
sec-error-extra-input = DER-इनक'डेड खौरांआव बाहायफेरै बांद्राय डाटा दङ।
sec-error-unsupported-elliptic-curve = मदद होजायै गोलाव महरनि खेंख्रा हांखो
sec-error-unsupported-ec-point-form = मदद होजायै गोलाव महरनि खेंख्रा हांखो बिन्दो फर्म
sec-error-unrecognized-oid = सिनायथिगोयै बेसाद सिनायथिग्रा
sec-error-ocsp-invalid-signing-cert = OCSP फिननायाव बाहायजायै OCSP सहि होनाय चार्टिफिकेट।
sec-error-revoked-certificate-crl = चार्टिफिकेटखौ इसु खालामग्रानि चार्टिफिकेट रिभ'केसन लिस्टआव बातिल खालामनाय जायो।
sec-error-revoked-certificate-ocsp = इसु खालामग्रा OCSP फिनहोग्राया चार्टिफिकेट बातिल खालामनायखौ रिपर्ट खालामो।
sec-error-crl-invalid-version = इसु खालामग्रानि चार्टिफिकेट रिभ'केसन लिस्टहा मोनसे मोनथिमोनै लिरस्लायनाय अनजिमा दङ।
sec-error-crl-v1-critical-extension = इसु खालामग्रानि V1 चार्टिफिकेट रिभ'केसन लिस्टहा मोनसे खैफोदगोनां बारायनाय दङ।
sec-error-crl-unknown-critical-extension = दिहुनग्रानि V2 सार्टिफिकेट रिभ'केसन लिस्टहा मोनसे मोनथिमोनै गोब्राब फेहेरनाय दं।
sec-error-unknown-object-type = मोनथिमोनै बेसाद रोखोमखौ थिक खालामबाय
sec-error-incompatible-pkcs11 = PKCS #11 ड्राइभारा स्पेकखौ मोनसे अरजाथावै राहाजों नेन सिफायो।
sec-error-no-event = बे समाव जेबो गोदान जायगा जाथाय गैया।
sec-error-crl-already-exists = CRL आ सिगाङावनो दङ।
sec-error-not-initialized = NSS खौ जागायाखै।
sec-error-token-not-logged-in = अपारेसना फेलें जाबाय मानोना PKCS#11 टकेनखौ लग इन खालामनाय जायाखै।
sec-error-ocsp-responder-cert-invalid = महर दानाय OCSP फिननायनि चार्टिफिकेटआ बाहायजायै।
sec-error-ocsp-bad-signature = OCSP फिननाया मोनसे बाहायजायै सहि।
sec-error-out-of-search-limits = Cert बाहायजाथाव नागिरनाया नागिरनाय सिमानि बाइजोआव दं।
sec-error-invalid-policy-mapping = पलिसि मेपिंयाव जायखिजाया पलिसि दं
sec-error-policy-validation-failed = Cert जिनजिरिआ पलिसि बाहायजाथावखौ फेलें खालामो
sec-error-unknown-aia-location-type = मोनथिमोनै जायगा रोखोमा cert AIA फेहेरनायाव दं।
sec-error-bad-http-response = सार्भारा गाज्रि HTTP फिननायखौ फैफिनहोबाय
sec-error-bad-ldap-response = सार्भारा गाज्रि LDAP फिननायखौ फैफिनहोबाय
sec-error-failed-to-encode-data = ASN1 एनक'डारजों लोगोसे डाटाखौ एनक'ड खालामनो फेलें जाबाय
sec-error-bad-info-access-location = cert फेहेरनायाव गाज्रि फोरमायथिहोग्रा हाबनाय जायगा
sec-error-libpkix-internal = चार्ट भेलिडेसननि समाव Libpkix इसिंनि गोरोन्थि जादोंमोन।
sec-error-pkcs11-general-error = मोनसे PKCS #11 मडुलआ CKR_GENERAL_ERROR खौ फैफिनहोबाय, मोनफिन हायै गोरोन्थि ओंखारनायखौ दिन्थियो।
sec-error-pkcs11-device-error = मोनसे PKCS #11 मडुलआ CKR_DEVICE_ERROR खौ फैफिनहोबाय, टकेन एबा स्लटजों मोनसे जेंना जाबाय होननानै दिन्थियो।
sec-error-bad-info-access-method = चार्टिफिकेट फेहेरनायाव मोनथिमोनै फोरमायथिहोग्रा हाबनाय खान्थि
sec-error-crl-import-failed = मोनसे CRL लाबोनो नाजानायाव जानाय गोरोन्थि।
sec-error-expired-password = बे पासवार्डआ मेयाद बारबाय।
sec-error-locked-password = बे पासवार्डआ लक जाबाय।
sec-error-unknown-pkcs11-error = मोनथिमोनै PKCS #11 गोरोन्थि
sec-error-bad-crl-dp-url = CRL बिलाइनाव बिन्दो मुंआव बाहायजायै एबा हेफाजाबहोजायै URL
sec-error-cert-signature-algorithm-disabled = सहि एलग'रिडमनि हेफाजाबजों बे सार्टिफिकेटखौ सहि होदोंमोन, बैयो लोरबां जाबाय मानोना बेयो रैखाथि नङा।
mozilla-pkix-error-key-pinning-failure = सार्भारआ साबि pinning (HPKP) खौ बाहायो नाथाय pinset जों गोरोबथाव जेबो फोथायथाव सार्टिफिकेट जिनजिरि गायसननो हायाखै। साबि pinning सिफायनायखौ नेवसिनो हाया।
mozilla-pkix-error-ca-cert-used-as-end-entity = सार्भारआ सार्टिफिकेटखौ सार्टिफिकेट अथ'रिटि महरै सिनायथि होनानै गुदि हेंथा फेहेरनायजों बाहायो। मोजाङै दिहुननाय सार्टिफिकेटनि थाखाय बेबाइदि जानाङा।
mozilla-pkix-error-inadequate-key-size = सार्भारआ मोनसे फिसा महरनि साबिजों सार्टिफिकेटखौ दिन्थिबाय, नाथाय बेयो रैखाथि फोनांजाब गायसननो जोबोद फिसा।
mozilla-pkix-error-v1-cert-used-as-ca = मोनसे X.509 बिसान 1 सार्टिफिकेटआ फोथायथाव एंकर नङा जायखौ सार्भारनि सार्टिफिकेट दिहुननो बाहायनाय जादोंमोन। X.509 बिसान 1 सार्टिफिकेटखौ हेंथा होदोंमोन आरो बेखौ गुबुन सार्टिफिकेट सहि होनो बाहायनाङा।
