# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = खेव
    .accesskey = O
places-open-all-in-tabs =
    .label = गासैखौबो टेबाव खेव
    .accesskey = O
places-view =
    .label = नुथाय
    .accesskey = w
places-by-date =
    .label = अक्‍त' मथे
    .accesskey = D
places-by-site =
    .label = साइट मथे
    .accesskey = S
places-by-most-visited =
    .label = बांसिन थांजानाय मथे
    .accesskey = V
places-by-last-visited =
    .label = जोबथा थांजानाय मथे
    .accesskey = L
places-by-day-and-site =
    .label = अक्‍त' आरो साइट मथे
    .accesskey = t
places-history-search =
    .placeholder = नागिरनायनि जारिमिन
places-history =
    .aria-label = जारिमिन
places-bookmarks-search =
    .placeholder = बुकमार्कफोरखौ नागिर
places-delete-domain-data =
    .label = बे साइटखौ बाव लां
    .accesskey = F
places-sortby-name =
    .label = मुं मथे थख' साजाय
    .accesskey = r
places-library =
    .title = बिजाब बाख्रि
    .style = width:700px; height:500px;
places-cmd-close =
    .key = w
places-view-sort-col-name =
    .label = मुं
places-view-sort-col-tags =
    .label = टेगफोर
places-view-sort-col-url =
    .label = जायगा
places-view-sort-col-most-recent-visit =
    .label = दासो थांनाय
places-view-sort-col-visit-count =
    .label = नायनो थांनाय काउन्ट
places-view-sort-col-date-added =
    .label = दाजाबदेरबाय
places-view-sort-col-last-modified =
    .label = जोबथा महर सोलायबाय
places-cmd-find-key =
    .key = f
places-back-button =
    .tooltiptext = थांफिन
places-forward-button =
    .tooltiptext = सिगांथि थां
places-details-pane-select-an-item-description = नायनो थाखाय मोनसे आइटेम सायख आरो बेनि आखुथायफोरखौ सुजु
