# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loginsDescriptionAll2 = निम्न साइटहरूको लगइनहरू तपाईँको कम्प्युटरमा संग्रह गरिएको छ
# LOCALIZATION NOTE (loginHostAge):
# This is used to show the context menu login items with their age.
# 1st string is the username for the login, 2nd is the login's age.
loginHostAge = %1$S (%2$S)
# LOCALIZATION NOTE (noUsername):
# String is used on the context menu when a login doesn't have a username.
noUsername = प्रयोगकर्ता नाम छैन
# LOCALIZATION NOTE (insecureFieldWarningDescription2):
# %1$S will contain insecureFieldWarningLearnMore and look like a link to indicate that clicking will open a tab with support information.
insecureFieldWarningDescription2 = जडान सुरक्षित छैन । प्रविष्टी गरिएको लग इनहरू सार्वजनिक हुन सक्छन् ।%1$S
insecureFieldWarningLearnMore = अझ जान्नुहोस्
