# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Do you want to trust "%S" for the  following purposes?
unnamedCA = சான்றிதழ் ஆணையம் (பெயரிடாதது)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = காப்பு சான்றிதழை மறைகுறியாக்க பயன்படுத்தப்பட்ட கடவுச்சொல்லை உள்ளிடவும்:
# Page Info
pageInfo_NoEncryption = இணைப்பு குறிமுறையாக்கப்படவில்லை
pageInfo_Privacy_None1 = The web site %S does not support  encryption for the page you are viewing.
pageInfo_Privacy_None2 = Information sent over the Internet without  encryption can be seen by other people while it is in transit.
pageInfo_Privacy_None4 = நீங்கள் பார்க்கும் பக்கம் இணையத்தில் பகிரப்படும் முன் குறிமுறையாக்கப்படாதது.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = இணைப்பு குறிமுறையாக்கப்பட்டது (%1$S, %2$S பிட் சாவிகள், %3$S)
pageInfo_BrokenEncryption = முறிந்த மறைகுறியாக்கம் (%1$S, %2$S பிட் சாவிகள், %3$S)
pageInfo_Privacy_Encrypted1 = The page you are viewing was  encrypted before being transmitted over the Internet.
pageInfo_Privacy_Encrypted2 = கணினிகளுக்கிடைய பரிமாறிக்கொள்ளப்படும் தகவலை அதிகாரமற்ற ஆட்களால் பார்க்க முடியாதபடி குறியாக்கம் செய்யப்படுகிறது. படிக்கும் யாவருக்கும் இந்தப் பக்கம் பிணையங்கள் ஊடாக கடந்துச் செல்கிறது என்பது உறுதி.
pageInfo_MixedContent = பகுதி இணைப்பு மட்டுமே குறியாக்கம் செய்யப்பட்டது
pageInfo_MixedContent2 = Parts of the page you are viewing were  not encrypted before being transmitted over the Internet.
pageInfo_WeakCipher = இத்தளத்திற்கான உங்கள் இணைப்பு வலுவற்ற மறைகுறியாக்கத்தைப் பயன்படுத்துவதால் தனிப்பட்டதாகாது. எனவே பிற நபர்கள் தகவல்களைப் பார்க்க அல்லது தளத்தின் நடத்தைகளை மாற்ற முடியும்.
# Token Manager
password_not_set = (அமையவில்லை)
