# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = یہ ویب پیج چُھ ریڈاریکٹْہ کرنْہ یوان أکس نوِ جایِہ کُن۔ کیاہ توہیہ کْرواہ پسند فارم ڈاٹا دوبار سوزُن یوس توہیہ ٹایِپ کورمُت چُھ نْو جایِہ کُن؟
# Directory listing strings
DirTitle = %1$S اُك فہرست
DirGoUp = ہیرمئ تہ كئ ڈایریكٹری تام
ShowHidden = ژۄر۪ی تھئومئت اوبجیكٹس ہئویو
DirColName = ناو
DirColSize = سایز
DirColMTime = ٲخری تبدیل كرموْت
DirFileLabel = فایل:
