# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loginsDescriptionAll2 = பின்வரும் இணையதளங்களின் கடவுச்சொற்கள் உங்கள் கணினியில் சேமிக்கப்பட்டுள்ளது
# LOCALIZATION NOTE (loginHostAge):
# This is used to show the context menu login items with their age.
# 1st string is the username for the login, 2nd is the login's age.
loginHostAge = %1$S (%2$S)
# LOCALIZATION NOTE (noUsername):
# String is used on the context menu when a login doesn't have a username.
noUsername = பயனர் பெயர் இல்லை
# LOCALIZATION NOTE (insecureFieldWarningDescription2):
# %1$S will contain insecureFieldWarningLearnMore and look like a link to indicate that clicking will open a tab with support information.
insecureFieldWarningDescription2 = இத்தளத்துடனான இணைப்பு பாதுகாப்பற்றது. இங்கு உள்ளிட்ட உள்நுழைவுகளைச் சமரசம் செய்ய முடியும். %1$S
insecureFieldWarningLearnMore = மேலும் அறிய
