#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title چوب‌الف‌ها
#define bookmarks_heading چوب‌الف‌ها

# LOCALIZATION NOTE (bookmarks_addons):
# link title for https://en-US.add-ons.mozilla.com/en-US/firefox/bookmarks/
#define bookmarks_addons دریافت افزودنی‌های چوب‌الف

#define bookmarks_toolbarfolder پوشهٔ نوار ابزار چوب‌الف‌ها
#define bookmarks_toolbarfolder_description چوب‌الف‌های این پوشه در «نوار ابزار چوب‌الف‌ها» نمایش داده خواهند شد

# LOCALIZATION NOTE (getting_started):
# link title for http://en-US.www.mozilla.com/en-US/firefox/central/
#define getting_started چگونه شروع کنم

# LOCALIZATION NOTE (latest_headlines):
# link title for the live bookmarks sample, a redirect on
# http://en-US.fxfeeds.mozilla.com/en-US/firefox/headlines.xml
# Changing the redirect is subject to approval of l10n-drivers.
#define latest_headlines اهم اخبار

# LOCALIZATION NOTE (firefox_heading):
# Firefox links folder name
#define firefox_heading موزیلا فایرفاکس

# LOCALIZATION NOTE (firefox_help):
# link title for http://en-US.www.mozilla.com/en-US/firefox/help/
#define firefox_help راهنما و برنامه‌های آموزشی

# LOCALIZATION NOTE (firefox_customize):
# link title for http://en-US.www.mozilla.com/en-US/firefox/customize/
#define firefox_customize سفارشی‌سازی فایرفاکس

# LOCALIZATION NOTE (firefox_community):
# link title for http://en-US.www.mozilla.com/en-US/firefox/community/
#define firefox_community مشارکت کردن

# LOCALIZATION NOTE (firefox_about):
# link title for http://en-US.www.mozilla.com/en-US/firefox/about/
#define firefox_about دربارهٔ ما

#unfilter emptyLines
