# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Notice: If you're updating this list, you should also
###         update the list in mozIntl.js.

region-name-ad = آندورہ
region-name-af = افغانستان
region-name-ag = انٹیگا اور باربودا
region-name-ai = آنگویلا
region-name-al = البانیہ
region-name-am = آرمینیا
region-name-ao = انگولا
region-name-as = امریکی ساموا
region-name-aw = آروبا
region-name-az = آذربائیجان
region-name-ba = بوسنیا و ہرزیگووینا
region-name-bb = باربدوس
region-name-bd = بنگلہ دیش
region-name-bf = برکینا فاسو
region-name-bg = بلغاریہ
region-name-bi = برونڈی
region-name-bj = بینن
region-name-bm = برمودا
region-name-bt = بھوٹان
region-name-bv = بووٹ آِلینڈ
region-name-bw = بوٹسوانا
region-name-by = بیلارس
region-name-cc = کوکوس (کیلنگ) آئلینڈز
region-name-cf = وسطی افریقائی جمہوریہ
region-name-ck = جزائر کک
region-name-cm = کیمرون
region-name-cu = کیوبا
region-name-cx = کرسمس جزیرہ
region-name-cy = قبرص
region-name-cz = جمہوریہ چیک
region-name-dj = جبوتی
region-name-dk = ڈنمارک
region-name-dm = ڈومینیکا
region-name-ee = استونیا
region-name-eh = مغربی سہارا
region-name-er = اریٹریہ
region-name-et = ایتھوپیا
region-name-fj = فجی
region-name-fo = فارو جزائر
region-name-ga = گبون
region-name-gd = گریناڈا
region-name-ge = جارجیا
region-name-gf = فرانیسی گنی
region-name-gg = گیرنسی
region-name-gh = گھانا
region-name-gi = جبرالٹر
region-name-gl = گرین لینڈ
region-name-gn = گنی
region-name-gp = گواڈیلوپ
region-name-gq = استوائی گنی
region-name-gr = یونان
region-name-gu = گام
region-name-gw = گنی بساؤ
region-name-gy = گے آنا
region-name-hm = ہیرڈ جزیرہ و میکڈونلڈ جزائر
region-name-hr = کروشیا
region-name-ht = ہیٹی
region-name-hu = ہنگری
region-name-id = انڈونیشیا
region-name-il = اسرائیل
region-name-im = آئل آف مین
region-name-io = برٹش انڈین آوشن ٹریٹری
region-name-ir = ایران
region-name-je = جرسی
region-name-ke = کینیا
region-name-kg = قرغزستان
region-name-kh = کمبوڈیا
region-name-ki = کری باتی
region-name-km = کوموروس
region-name-kn = سینٹ کٹس و نیویس
region-name-ky = جزائر کیمن
region-name-kz = قازقستان
region-name-la = لاؤس
region-name-lc = سینٹ لیوشیا
region-name-lk = سری لنکا
region-name-lr = لائبیریا
region-name-ls = لیسوتھو
region-name-lt = لیتھوینیا
region-name-lv = لیٹویا
region-name-md = مالدوا
region-name-me = مانٹینیگرو
region-name-mf = سینٹ مارٹین
region-name-mg = مڈغاسکر
region-name-mh = مارشل جزائر
region-name-ml = مالی
region-name-mn = منگولیا
region-name-mp = شمالی ماریانا جزائر
region-name-mq = ماریطنیق
region-name-mr = ماریطانیہ
region-name-ms = مانٹسریٹ
region-name-mt = مالٹا
region-name-mu = ماریشس
region-name-mv = مالدیپ
region-name-mw = ملاوی
region-name-mz = موزنبیق
region-name-na = نمبیا
region-name-nc = نیوکیلے ڈونیا
region-name-ne = نائجر
region-name-nf = نارفوک جزیرہ
region-name-ng = نائجیریا
region-name-nl = نیدرلینڈز
region-name-no = ناروے
region-name-np = نیپال
region-name-nu = نیو
region-name-pf = فرانسیسی پولنیشیا
region-name-pg = پاپوا نیو گنی
region-name-pm = سینٹ پیری و میکولن
region-name-pt = پرتگال
region-name-pw = پالو
region-name-re = ری یونین
region-name-ro = رومانیہ
region-name-rs = سربیا
region-name-rw = روانڈا
region-name-sb = سولومن جزائر
region-name-sc = سیشیلز
region-name-sd = سوڈان
region-name-si = سلوانیا
region-name-sk = سلواکیا
region-name-sl = سیرا لیون
region-name-sm = سان مرینو
region-name-sn = سینیگال
region-name-so = صومالیہ
region-name-sr = سری نام
region-name-st = ساو ٹومی اور پرنسپی
region-name-sz = سوازی لینڈ
region-name-tc = ترک و کیکوس جزائر
region-name-td = چاڈ
region-name-tg = ٹوگو
region-name-th = تھائی لینڈ
region-name-tj = تاجکستان
region-name-tk = ٹوکیلاؤ
region-name-tl = تیمور-لیستی
region-name-tm = ترکمانستان
region-name-tr = ترکی
region-name-tt = ٹرینیڈاڈ اور ٹوباگو
region-name-tv = توالو
region-name-tz = تنزانیہ
region-name-ua = یوکرائن
region-name-ug = یوگنڈا
region-name-uz = ازبکستان
region-name-va = ویٹیکن سٹی
region-name-vc = سینٹ ونسنٹ اور گریناڈینز
region-name-vn = ویت نام
region-name-vu = وانواٹو
region-name-ws = ساموا
region-name-yt = مائیوٹ
region-name-zm = زیمبیا
