# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Phewuhwa'j piisanxi web-te { $host }…
network-connection-status-connected = Çxkhitxawa'j { $host }…
network-connection-status-sending-request = Mkaa pẽyna { $host }...
network-connection-status-transferring-data = Kajxkhẽwujna majuy pta'sxna { $host }…
network-connection-status-connecting = Çxkhitxawa'j { $host }…
network-connection-status-read = Jxpaywa'h  { $host }
network-connection-status-wrote = Fxi'wah { $host }
network-connection-status-waiting = ũjxthasna { $host }…
network-connection-status-looked-up = Uynxisaa { $host }…
