# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-transferring-data = { $host } தளத்திலிருந்து தகவல் பெறப்படுகிறது...
network-connection-status-connecting = { $host } உடன் இணைக்கிறது...
network-connection-status-read = { $host } படி
network-connection-status-wrote = { $host } எழுதப்பட்டது
network-connection-status-waiting = { $host } தளத்திற்காகக் காத்திருக்கிறது...
network-connection-status-looked-up = { $host } ஐ தேடியது…
network-connection-status-tls-handshake = { $host } உடன் TLS கைக்குளுக்கல் நடைப்பெறுகிறது…
network-connection-status-tls-handshake-finished = { $host } உடனான TLS கைக்குளுக்கல் முடிந்தது…
