# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

search-header-shortcut =
    .key = f
loading-label =
    .value = Загрузка…
list-empty-installed =
    .value = У вас няма ніводнага ўсталяванага дадатку гэтага тыпу
list-empty-available-updates =
    .value = Абнаўленні не знойдзеныя
list-empty-recent-updates =
    .value = Нядаўна вы не абнаўлялі ніякіх дадаткаў
list-empty-find-updates =
    .label = Знайсці абнаўленні
list-empty-button =
    .label = Падрабязней пра дадаткі
install-addon-from-file =
    .label = Усталяваць дадатак з файла…
    .accesskey = У
tools-menu =
    .tooltiptext = Прылады для ўсіх дадаткаў
cmd-show-details =
    .label = Паказаць больш звестак
    .accesskey = П
cmd-find-updates =
    .label = Знайсці абнаўленні
    .accesskey = З
cmd-enable-theme =
    .label = Ужыць тэму
    .accesskey = У
cmd-disable-theme =
    .label = Спыніць ужыванне тэмы
    .accesskey = у
cmd-install-addon =
    .label = Усталяваць
    .accesskey = У
cmd-contribute =
    .label = Ахвяраваць
    .accesskey = А
    .tooltiptext = Ахвяраваць сродкі на распрацоўку гэтага дадатку
discover-title = Што такое дадаткі?
detail-version =
    .label = Версія
detail-last-updated =
    .label = Апошняе абнаўленне
detail-contributions-description = Распрацоўца гэтага дадатка просіць падтрымаць яго распрацоўку невялікім ахвяраваннем.
detail-home =
    .label = Хатняя старонка
detail-home-value =
    .value = { detail-home.label }
detail-repository =
    .label = Профіль дадатка
detail-repository-value =
    .value = { detail-repository.label }
detail-check-for-updates =
    .label = Знайсці абнаўленні
    .accesskey = н
    .tooltiptext = Праверыць, ці існуюць абнаўленні гэтага дадатку
detail-rating =
    .value = Ацэнка
addon-restart-now =
    .label = Перазапусціць зараз
