# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Identificacións gardadas
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Copiar URL
    .accesskey = U
launch-site-url-cmd =
    .label = Visitar URL
    .accesskey = V
copy-username-cmd =
    .label = Copiar nome de usuario
    .accesskey = u
edit-username-cmd =
    .label = Editar nome de usuario
    .accesskey = d
copy-password-cmd =
    .label = Copiar contrasinal
    .accesskey = C
edit-password-cmd =
    .label = Editar contrasinal
    .accesskey = E
search-filter =
    .accesskey = s
    .placeholder = Buscar
column-heading-site =
    .label = Sitio
column-heading-username =
    .label = Nome de usuario
column-heading-password =
    .label = Contrasinal
column-heading-time-created =
    .label = Usado por primeira vez
column-heading-time-last-used =
    .label = Usado por última vez
column-heading-time-password-changed =
    .label = Cambiado por última vez
column-heading-times-used =
    .label = Veces usado
remove =
    .label = Eliminar
    .accesskey = E
import =
    .label = Importar…
    .accesskey = I
close-button =
    .label = Pechar
    .accesskey = P
show-passwords =
    .label = Amosar os contrasinais
    .accesskey = M
hide-passwords =
    .label = Agochar os contrasinais
    .accesskey = O
logins-description-all = As identificacións dos seguintes sitios están almacenadas no computador
logins-description-filtered = As seguintes identificacións coinciden coa súa busca:
remove-all =
    .label = Retirar todas
    .accesskey = A
remove-all-shown =
    .label = Retirar as mostradas
    .accesskey = A
remove-all-passwords-prompt = Confirma que quere retirar todos os contrasinais?
remove-all-passwords-title = Retirar todos os contrasinais
no-master-password-prompt = Confirma que quere amosar os seus contrasinais?
