# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

customize-mode-restore-defaults =
    .label = Врати на подразумевано
customize-mode-menu-and-toolbars-header = Превуците своје омиљене ставке на траку са алаткама или у додатни мени.
customize-mode-overflow-list-title = Додатни мени
customize-mode-uidensity =
    .label = Збијеност
customize-mode-done =
    .label = Готово
customize-mode-lwthemes-menu-manage =
    .label = Управљај
    .accesskey = M
customize-mode-toolbars =
    .label = Траке са алаткама
customize-mode-titlebar =
    .label = Насловна трака
customize-mode-uidensity-menu-touch =
    .label = На додир
    .accesskey = T
    .tooltiptext = На додир
customize-mode-uidensity-auto-touch-mode-checkbox =
    .label = Користи На додир у режиму таблета
customize-mode-extra-drag-space =
    .label = Превуци простор
customize-mode-lwthemes =
    .label = Теме
customize-mode-overflow-list-description = Овде превуците ставке како би вам биле надохват руке али ван траке са алаткама.
customize-mode-uidensity-menu-normal =
    .label = Обично
    .accesskey = N
    .tooltiptext = Обично
customize-mode-uidensity-menu-compact =
    .label = Компактно
    .accesskey = C
    .tooltiptext = Компактно
customize-mode-uidensity-menu-compact-unsupported =
    .label = Компактно (није подржано)
    .accesskey = К
    .tooltiptext = Компактно (није подржано)
customize-mode-lwthemes-menu-get-more =
    .label = Набавите теме
    .accesskey = G
customize-mode-undo-cmd =
    .label = Поништи
customize-mode-lwthemes-my-themes =
    .value = Моје теме
customize-mode-touchbar-cmd =
    .label = Прилагоди додирну траку…
customize-mode-downloads-button-autohide =
    .label = Сакриј дугме када нема преузимања
