# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = Отвори
    .accesskey = О
places-open-tab =
    .label = Отвори у новом језичку
    .accesskey = ј
places-open-all-in-tabs =
    .label = Отвори све у језичцима
    .accesskey = ј
places-open-window =
    .label = Отвори у новом прозору
    .accesskey = н
places-open-private-window =
    .label = Отвори у новом приватном прозору
    .accesskey = п
places-new-bookmark =
    .label = Нова забелешка…
    .accesskey = Н
places-new-folder-contextmenu =
    .label = Нови директоријум…
    .accesskey = д
places-new-folder =
    .label = Нови директоријум…
    .accesskey = д
places-new-separator =
    .label = Нови сепаратор
    .accesskey = С
places-view =
    .label = Преглед
    .accesskey = е
places-by-date =
    .label = По датуму
    .accesskey = д
places-by-site =
    .label = По сајту
    .accesskey = с
places-by-most-visited =
    .label = По посећености
    .accesskey = ћ
places-by-last-visited =
    .label = По последњој посети
    .accesskey = њ
places-by-day-and-site =
    .label = По датуму и сајту
    .accesskey = и
places-delete-domain-data =
    .label = Заборави на овај сајт
    .accesskey = б
places-sortby-name =
    .label = Сортирај по имену
    .accesskey = и
places-properties =
    .label = Својства
    .accesskey = о
