# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

report-broken-site-mainview-title = Пријавите неисправан сајт
report-broken-site-panel-header =
    .label = Пријавите неисправан сајт
    .title = Пријавите неисправан сајт
report-broken-site-panel-intro-text = Ваш извештај нам помаже да разумемо и поправимо проблеме у { -brand-product-name } како бисмо га учинили бољим за све.
report-broken-site-panel-learn-more-link = Сазнајте више
report-broken-site-panel-intro = Помозите да { -brand-product-name } буде бољи за све. { -vendor-short-name } користи податке које шаљете да реше проблеме на сајту.
report-broken-site-panel-url = URL адреса
report-broken-site-panel-reason-label = Шта није у реду?
report-broken-site-panel-reason-optional-label = Шта не ради? (опционо)
report-broken-site-panel-reason-choose =
    .label = Изаберите разлог
report-broken-site-panel-reason-load =
    .label = Веб сајт се не учитава
# These terms are referring to ecommerce websites
report-broken-site-panel-reason-checkout =
    .label = Не могу да платим, завршим куповину или купујем
report-broken-site-panel-reason-slow2 =
    .label = Веб сајт је спор
report-broken-site-panel-reason-media2 =
    .label = Видео се не репродукује или не учитава
report-broken-site-panel-reason-content2 =
    .label = Недостаје садржај
report-broken-site-panel-reason-account2 =
    .label = Не могу да се пријавим или региструјем
report-broken-site-panel-reason-adblocker2 =
    .label = Веб сајт је тражио да искључим блокатор огласа
report-broken-site-panel-reason-notsupported =
    .label = Прегледач није подржан или је блокиран
report-broken-site-panel-reason-other =
    .label = Нешто друго
report-broken-site-panel-description-label = Опишите проблем
report-broken-site-panel-description =
    .placeholder = Шта се десило? Шта је требало да се деси? Да ли је искључивање заштите од праћења помогло?
report-broken-site-panel-description-optional-label = Опишите проблем (опционо)
report-broken-site-panel-send-more-info-link = Пошаљите више информација
report-broken-site-panel-button-cancel =
    .label = Откажи
report-broken-site-panel-button-okay =
    .label = У реду
report-broken-site-panel-button-send =
    .label = Пошаљи
report-broken-site-panel-report-sent-label = Ваш извештај је послан
report-broken-site-panel-report-sent-header =
    .label = Ваш извештај је послан
    .title = Ваш извештај је послан
report-broken-site-panel-report-sent-text = Хвала што помажете { -brand-product-name }-у да интернет буде отворенији, приступачнији и бољи за све.
report-broken-site-panel-invalid-url-label = Унесите важећу URL адресу
report-broken-site-panel-missing-reason-label = Одаберите разлог
report-broken-site-panel-blocked-trackers-label =
    .label = Пошаљите URL-ове блокиране заштитом од праћења
report-broken-site-panel-blocked-trackers-description = Побољшана заштита од праћења може блокирати пратиоце и скрипте који су неким веб сајтовима потребни за правилан рад.
report-broken-site-panel-preview-button =
    .label = Прегледај извештај
report-broken-site-panel-preview-header =
    .label = Прегледај извештај
