# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = وقت ختم
openFile = فائل کھولو
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = %1$S ڳولو %2$S کیتے
contextMenuSearch.accesskey = S
contextMenuPrivateSearch = نجی ونڈو وچ ڳولو
contextMenuPrivateSearch.accesskey = h
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = نجی ونڈو وِچ %S دے نال ڳولو
contextMenuPrivateSearchOtherEngine.accesskey = h
bookmarkAllTabsDefault = [فولڈر دا ناں]
unsignedAddonsDisabled.message = ہک یا زیادہ انسٹال تھئے ایڈ آنز دی تصدیق نہیں کیتی ونڄ سڳدی تے انہاں کوں غیر فعال کر ݙتا ڳیا ہے۔
unsignedAddonsDisabled.learnMore.label = ٻیا سِکھو
unsignedAddonsDisabled.learnMore.accesskey = L
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = چھیکڑی رسائی %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = %S:// لنکس
crashedpluginsMessage.title = %S پلگ ان تباہ تھی ڳیا ہے
crashedpluginsMessage.reloadButton.label = ورقہ ولدا لوڈ کرو
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = تباہی دی رپورٹ ارسال کرو
crashedpluginsMessage.submitButton.accesskey = S
crashedpluginsMessage.learnMore = ٻیا سکھو …
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = کیا تساں %S تے ونڄݨ چاہندے او؟
keywordURIFixup.goTo = جیاں، میکوں %S تے گھن ڄلو
keywordURIFixup.goTo.accesskey = Y
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = %S کوں اپ ڈیٹ کرو
update.downloadAndInstallButton.accesskey = U
menuOpenAllInTabs.label = سبھ ٹیباں وِچ کھولو
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = ایہ ورقہ ولدا لوڈ کرو
tabHistory.goBack = ایں ورقے تے ول ونڄو
tabHistory.goForward = ایں ورقے تے اڳو تے ودھو
# URL Bar
pasteAndGo.label = چسپاں کرو تے ونڄو
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = موجودہ ورقے کوں دوبارہ لوڈ کرو (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = ایں ورقے کوں لوڈ کرݨ بند کرو (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = زوم سطح ولا سیٹ کرو (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = ریڈر ویو کوں ٹوگل کرو (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%، زوم لیول ری سیٹ کرو
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = اپݨیاں نشانیاں ݙکھاؤ (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = جاری ڈاونلوڈز دی حالت ݙکھاؤ (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = نویں ونڈو کھولو (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = نویں ٹیب کھولو (%S)
newTabContainer.tooltip = ہک نویں ٹیب کھولو (%S)\n ہک نواں کنٹینر ٹیب کھولݨ کیتے دبائئ رکھو
newTabAlwaysContainer.tooltip = نویں ٹیب کھولݨ کیتے ہک کنٹینر دا انتخاب کرو
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = %S کوں اپݨا HTML5 کینوس امیج ڈیٹا استعمال کرݨ دی اجازت ݙیوو؟
canvas.siteprompt2.warning = ایہ تہاݙے کمپیوٹر دی نویکلی سنڄاݨ کیتے  استعمال کیتا ونڄ سڳدا ہے۔
canvas.block = بلاک کرو
canvas.block.accesskey = B
canvas.allow2 = اجازت ݙیوو
canvas.allow2.accesskey = A
canvas.remember2 = ایہ فیصلہ یاد رکھو
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = توثیق کردہ برائے: %S
identity.identified.verified_by_you = تساں ایں سائٹ کیتے حفاظتی استثناء شامل کیتا ہے۔
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = سرٹیفکیٹ جاری کیتا ڳیا: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = محفوظ کائنی
identity.notSecure.tooltip = کنکشن محفوظ کائنی۔
identity.extension.label = ایکسٹینشن (%S)
identity.extension.tooltip = ایکسٹینشن دی طرفوں لوڈ تھیا: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = زوم آؤٹ (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = زوم لیول ولدا سیٹ کرو (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = زوم ان (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = (%S) کٹو
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = (%S) نقل کرو
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = (%S) چسپاں کرو
geolocation.allow = اجازت ݙیوو
geolocation.allow.accesskey = A
geolocation.block = بلاک کرو
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = ایہ سسٹم جاء ترتیباں کھول ݙیسی۔ سوہݨا، %S کوں جاء اجازتاں ݙیوو۔
geolocation.shareWithSite4 = %S کوں تہاݙے مقام تک رسائی دی اجازت ݙیوو؟
geolocation.shareWithFile4 = ایں مقامی فائل کوں تہاݙے مقام تک رسائی دی اجازت ݙیوو؟
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = %1$S کوں %2$S کوں تہاݙے مقام تک رسائی دی اجازت ݙیوݨ دی اجازت ݙیوو؟
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = سسٹم ترتیباں وچ %S مقام دی اجازت ݙیوو۔
geolocation.systemSettingsTitle = محل وقوع دیاں اجازتاں دی تانگھ وچ ہے
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = سسٹم تہاکوں ایہ اجازت %S کوں ݙیوݨ کیتے آکھسی۔
geolocation.remember = ایہ فیصلہ یاد رکھو
# Virtual Reality Device UI
xr.allow2 = اجازت ݙیوو
xr.allow2.accesskey = A
xr.block = بلاک کرو
xr.block.accesskey = B
xr.shareWithSite4 = %S کوں ورچوئل رئیلٹی ڈیوائساں تک رسائی دی اجازت ݙیوو؟ ایہ حساس معلومات کوں بے نقاب کر سڳدا ہے۔
xr.shareWithFile4 = ایں مقامی فائل کوں ورچوئل رئیلٹی ڈیوائساں تک رسائی دی اجازت ݙیوو؟ ایہ حساس معلومات کوں پدھرا کر سڳدا ہے۔
xr.remember = ایہ فیصلہ یاد رکھو
# Persistent storage UI
persistentStorage.allow = اجازت ݙیوو
persistentStorage.allow.accesskey = A
persistentStorage.block.label = بلاک کرو
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = %S کوں مستقل سٹوریج وِچ ڈیٹا ذخیرہ کرݨ دی اجازت ݙیوو؟
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = اجازت ݙیوو
webNotifications.allow2.accesskey = A
webNotifications.notNow = ہݨ نہ
webNotifications.notNow.accesskey = n
webNotifications.never = کݙاہیں اجازت نہ ݙیو
webNotifications.never.accesskey = v
webNotifications.alwaysBlock = ہمیشاں بلاک کرو
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = بلاک کرو
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = %S کوں اطلاع نامے بھیڄݨ دی اجازت ݙیوو؟
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = میکوں اتھوں کڈھو!
safebrowsing.getMeOutOfHereButton.accessKey = G
safebrowsing.deceptiveSite = فریبی سائٹ!
safebrowsing.notADeceptiveSiteButton.label = ایہ فریبی سائٹ کائنی …
safebrowsing.notADeceptiveSiteButton.accessKey = D
safebrowsing.reportedAttackSite = اٹیک سائٹ رپورٹ کیتی ڳئی!
safebrowsing.notAnAttackButton.label = ایہ ہک اٹیک سائٹ کائنی …
safebrowsing.notAnAttackButton.accessKey = A
safebrowsing.reportedUnwantedSite = اݨ بھاوݨی سافٹ ویئر سائٹ رپورٹ تھئی!
safebrowsing.reportedHarmfulSite = نقصانی سائٹ دی اطلاع ݙتی ڳئی!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = %S ڳولو
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = %S کوں ٹربل شوٹ موڈ وِچ دوبارہ شروع کرو؟
troubleshootModeRestartPromptMessage = تہاݙیاں ایکسٹینشنز، تھیمز تے حسب ضرورت ترتیباں عارضی طور تے غیر فعال تھی ویسن۔
troubleshootModeRestartButton = دوبارہ شروع کرو
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = ایہ ورقہ %1$S کوں مٹھا کریندا پیا ہے۔ اپݨے براؤزر کوں تکھا کرݨ کیتے، ایں ورقے کوں بند کرو۔
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = ہک ویب ورقہ %1$S کوں مٹھا کریندا پیا ہے۔ اپݨے براؤزر کوں تکھا کرݨ کیتے، ایں ورقے کوں روک ݙیو۔
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = "%1$S" %2$S کوں مٹھا کر یندا پیا ہے۔ اپݨے براؤزر کوں تیز کرݨ کیتے، ایں ورقے کوں روک ݙیو۔
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = "%1$S" %2$S کوں مٹھا کریندا پیا ہے۔ اپݨے براؤزر کوں تکھا کرݨ کیتے، ایں ایکسٹینشن کوں روک ݙیو۔
processHang.add-on.learn-more.text = ٻیا سِکھو
processHang.button_stop2.label = رک ون٘ڄو
processHang.button_stop2.accessKey = S
processHang.button_debug.label = ٹھیک تھیا سکرپٹ
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = ونڈو کوں پوری سکرین وِچ ݙکھاؤ (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = سائیڈ بار کوں کھٻے پاسے سورو
sidebar.moveToRight = سائیڈ بار کوں سڄے پاسے سورو
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = تہاکوں ایں ورقے تے کجھ آڈیو یا ویڈیو چلاوݨ کیتے DRM  کوں فعال کرݨا چاہیدا ہے۔
emeNotifications.drmContentDisabled.button.label = DRM فعال کرو
emeNotifications.drmContentDisabled.button.accesskey = E
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S ایں ورقے تے آڈیو یا ویڈیو چلاوݨ کیتے ضروری اجزاء انسٹال کریندا پیا ہے۔ براہ کرم کجھ دیر بعد کوشش کرو۔
emeNotifications.unknownDRMSoftware = اݨ ڄاتا
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = %S من مرضی دا
decoder.noCodecs.button = ڄاݨو کیویں
decoder.noCodecs.accesskey = L
decoder.noCodecsLinux.message = ویڈیو چلاوݨ کیتے، تہاکوں مطلوبہ ویڈیو کوڈیکس انسٹال کرݨ دی لوڑ پئے سڳدی اے۔
decoder.noHWAcceleration.message = ویڈیو دے معیار کوں بہتر بݨاوݨ کیتے، تہاکوں Microsoft دا میڈیا فیچر پیک انسٹال کرݨ دی ضرورت پئے سڳدی ہے۔
decoder.noPulseAudio.message = آڈیوں کوں چلاوݨ کیتے، تہاکوں مطلوبہ PulseAudio سافٹ ویئر انسٹال کرݨ دی ضرورت پئےسڳدی ہے۔
decoder.unsupportedLibavcodec.message = libavcodec کمزور تھی سڳدا ہے یا تعاون یافتہ کائنی، تے ویڈیو چلاوݨ کیتے اینکوں اپ ڈیٹ کیتا ونڄݨا چاہیدا ہے۔
decoder.decodeError.message = میڈیا ریسورس کوں ڈی کوڈ کریندے ویلھے ہک خرابی پیش آڳئی ہے۔
decoder.decodeError.button = سائٹ دا مسئلہ رپورٹ کرو
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = میڈیا ریسورس کوں ڈی کوڈ کریندے ویلھے ہک قابل بازیافت خرابی پیش آڳئی ہے۔
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = انٹرنیٹ تائیں رسائی حاصل کرݨ کنوں پہلے تہاکوں ایں نیٹ ورک وِچ لاگ ان تھیوݨا پوسے۔
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = نیٹ ورک دا لاگ ان ورقہ کھولو
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = %S کیتے اجازتاں
permissions.remove.tooltip = ایں اجازت کوں خالی کرو تے دوبارہ پچھو
permissions.fullscreen.promptCanceled = زیر التواء اجازت دیاں درخواستاں منسوخ: DOM  پوری سکرین وِچ داخل تھیوݨ توں پہلے اجازت دیاں درخواستاں جاری نہیں رکھݨیاں چاہیدیاں۔
permissions.fullscreen.fullScreenCanceled = DOM فل سکرین کنوں ٻاہر نکھتا: DOM فل سکرین وِچ رہندیں ہوئیں اجازت دیاں درخواستاں جاری نہیں کرݨیاں چاہیدیاں۔
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64ــ بٹ
aboutDialog.architecture.thirtyTwoBit = 32-بٹ
midi.allow.label = اجازت ݙیوو
midi.allow.accesskey = A
midi.block.label = بلاک کرو
midi.block.accesskey = B
midi.remember = ایہ فیصلہ یاد رکھو
midi.shareWithFile = ایں مقامی فائل کوں تہاݙے MIDI آلات تئیں رسائی دی اجازت ݙیووں؟
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = %S کوں تہاݙیاں MIDI  ڈیوائساں تائیں رسائی دی اجازت ݙیوو؟
midi.shareSysexWithFile = ایں مقامی فائل کوں تہاݙیاں MIDI ڈیوائیساں تائیں رسائی تے SysEx سنیہے بھیڄݨ/وصول کرݨ دی اجازت ݙیوو؟
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = %S کوں تہاݙیاں MIDI  ڈیوائساں تائیں رسائی تے SysEx سنیہے بھیڄݨ/ وصول کرݨ دی اجازت ݙیوو؟
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = پچھوں
storageAccess1.Allow.label = اجازت ݙیوو
storageAccess1.Allow.accesskey = A
storageAccess1.DontAllow.label = بلاک کرو
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = %1$S کوں %2$S تے ایندیاں کوکیاں استعمال کرݨ دی اجازت ݙیوو؟
storageAccess1.hintText = جے ایہ نشابر کائنی تاں %1$S کوں ایں ڈیٹا دی ضرورت کیوں ہے تاں تساں رسائی کوں روکݨ چاہندے او۔
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = %S کیتے ویب ڳولو
