# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

title = Желі туралы
warning = Бұл әлі сыналуда. Үлкендердің көмегі болмаса, қолданбаңыз.
show-next-time-checkbox = Осы ескертуді келесі ретте көрсету
ok = ОК
http = HTTP
sockets = Сокеттер
dns = DNS
websockets = WebSockets
refresh = Жаңарту
auto-refresh = Әр 3 секунд сайын жаңарту
hostname = Хост аты
port = Порт
http2 = HTTP/2
ssl = SSL
active = Белсенді
idle = Іссіз
host = Хост
tcp = TCP
sent = Жіберілген
received = Алынған
family = Отбасы
addresses = Адрестер
expires = Мерзімі бітеді (секунд)
messages-sent = Жіберілген хабарламалар
messages-received = Алынған хабарламалар
bytes-sent = Жіберілген байттар
bytes-received = Алынған байттар
logging = Журналдау
current-log-file = Ағымдағы журналдау файлы:
current-log-modules = Ағымдағы журналдау модульдері:
set-log-file = Журналдау файлын орнату
set-log-modules = Журналдау модульдерін орнату
start-logging = Журналдауды бастау
stop-logging = Журналдауды аяқтау
dns-lookup = DNS іздеуі
dns-lookup-button = Шешу
dns-domain = Домен:
dns-lookup-table-column = IP адрестері
rcwn = RCWN статистикасы
rcwn-status = RCWN қалып-күйі
rcwn-cache-won-count = Кэшке сәтті қатынаудың саны
rcwn-net-won-count = Желіге қатынаудың саны
total-network-requests = Желілік сұранымдардың жалпы саны
rcwn-operation = Кэш операциялары
rcwn-perf-open = Ашу
rcwn-perf-read = Оқу
rcwn-perf-write = Жазу
rcwn-perf-entry-open = Нәрсе ашық
rcwn-avg-short = Қысқа орташа мәні
rcwn-avg-long = Ұзақ орташа мәні
rcwn-std-dev-long = Ұзақ стандартты ауытқу
rcwn-cache-slow = Кэшке баяу қатынаудың саны
rcwn-cache-not-slow = Кэшке баяу емес қатынаудың саны
