# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = ଏହି ୱେବ ପୃଷ୍ଠାଟି ଗୋଟିଏ ନୂତନ ସ୍ଥାନକୁ ପୁନଃପ୍ରେରଣ ହୋଇଯାଇଛି. ନୂତନ ସ୍ଥାନରେ ଟାଇପ କରିଥିବା ଫର୍ମ ତଥ୍ୟକୁ ପୁଣି ପଠାଇବାକୁ ଆପଣ ପସନ୍ଦ କରିବେ କି?
# Directory listing strings
DirTitle = %1$S ର ଅନୁକ୍ରମଣିକା
DirGoUp = ଉଚ୍ଚ ସ୍ତରର ଡିରେକ୍ଟୋରୀ ପର୍ଯ୍ୟନ୍ତ
ShowHidden = ଲୁକ୍କାୟିତ ବସ୍ତୁଗୁଡ଼ିକୁ ଦର୍ଶାନ୍ତୁ
DirColName = ନାମ
DirColSize = ଆକାର
DirColMTime = ପୂର୍ବ ପରିବର୍ତ୍ତନ
DirFileLabel = ଫାଇଲ:\u0020
