# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

print-setup =
    .title = Pagina-instellingen
custom-prompt-title = Aangepast…
custom-prompt-prompt = Geef uw eigen kop-/voettekst
basic-tab =
    .label = Formaat & opties
advanced-tab =
    .label = Marges & kop-/voetteksten
format-group-label =
    .value = Formaat
orientation-label =
    .value = Oriëntatie:
scale-percent =
    .value = %
options-group-label =
    .value = Opties
margin-group-label-inches =
    .value = Marges (inches)
margin-group-label-metric =
    .value = Marges (millimeters)
margin-top-invisible =
    .value = Boven:
margin-bottom-invisible =
    .value = Onder:
margin-left-invisible =
    .value = Links:
margin-right-invisible =
    .value = Rechts:
header-footer-label =
    .value = Kop- & voetteksten
hf-left-label =
    .value = Links:
hf-center-label =
    .value = Midden:
hf-right-label =
    .value = Rechts:
header-left-tip =
    .tooltiptext = Linker koptekst
header-center-tip =
    .tooltiptext = Middelste koptekst
header-right-tip =
    .tooltiptext = Rechter koptekst
footer-left-tip =
    .tooltiptext = Linker voettekst
footer-center-tip =
    .tooltiptext = Middelste voettekst
footer-right-tip =
    .tooltiptext = Rechter voettekst
hf-blank =
    .label = --blanco--
hf-title =
    .label = Titel
hf-url =
    .label = URL
hf-date-and-time =
    .label = Datum/Tijd
hf-page =
    .label = Pagina #
hf-page-and-total =
    .label = Pagina # van #
hf-custom =
    .label = Aangepast…
print-title =
    .value = Titel:
print-preparing =
    .value = Voorbereiden…
print-progress =
    .value = Voortgang:
print-window =
    .title = Afdrukken
print-complete =
    .value = Afdrukken is voltooid.
# Variables
# $percent (integer) - Number of printed percentage
print-percent =
    .value = { $percent }%
dialog-cancel-label = Annuleren
dialog-close-label = Sluiten
