#filter emptyLines
# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title Doo-šilbawey


#define bookmarks_heading Doo-šilbawey


#define bookmarks_toolbarfolder Doo-šilbay goyjinay žeeri foolo


#define bookmarks_toolbarfolder_description Doo-šilbayaŋ tonton foolaa woo ga ka dii yey war boŋ doo-šilbawey goyjinay žeeroo ra.


# LOCALIZATION NOTE (getting_started):

# link title for http://en-US.www.mozilla.com/en-US/firefox/central/

#define getting_started Go ma tun nda Firefox


# LOCALIZATION NOTE (latest_headlines):

# link title for the live bookmarks sample, a redirect on

# http://en-US.fxfeeds.mozilla.com/en-US/firefox/headlines.xml

# Changing the redirect is subject to approval of l10n-drivers.

#define latest_headlines Albahar kokorantey


# LOCALIZATION NOTE (firefox_heading):

# Firefox links folder name

#define firefox_heading Mozilla Firefox


# LOCALIZATION NOTE (firefox_help):

# link title for http://en-US.www.mozilla.com/en-US/firefox/help/

#define firefox_help Faaba nda fahamitiirawey


# LOCALIZATION NOTE (firefox_customize):

# link title for http://en-US.www.mozilla.com/en-US/firefox/customize/

#define firefox_customize Firefox hanse war boŋše


# LOCALIZATION NOTE (firefox_community):

# link title for http://en-US.www.mozilla.com/en-US/firefox/community/

#define firefox_community Kanbuzaamay


# LOCALIZATION NOTE (firefox_about):

# link title for http://en-US.www.mozilla.com/en-US/about/

#define firefox_about Mozilla ga


#unfilter emptyLines