# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

unnamedCA = Entidá certificadora (ensin nome)
# Page Info
pageInfo_NoEncryption = Conexón ensin cifrar
pageInfo_Privacy_None2 = La información que s'unvia per internet ensin cifrar puen vela terceros mentanto se tresmite.
pageInfo_Privacy_None4 = La páxina que ves nun se cifró enantes de tresmitila per internet.
pageInfo_Privacy_Encrypted1 = La páxina que ves cifróse enantes de tresmitila per internet.
pageInfo_MixedContent = Conexón parcialmente cifrada
# Token Manager
password_not_set = (nun s'afitó)
