# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Kel Wizard ki woko
import-from =
    { PLATFORM() ->
        [windows] Gin ayera me Kelo ki woko, Alama me buk, Gin mukato, Mung me donyo kacel ki tic mogo ki bot:
       *[other] Kel ki woko ter, Alama me buk, Gin mukato, Mung me donyo kacel ki tic mogo kibot:
    }
import-from-bookmarks = Kel Alama buk kiwoko ki bot:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-nothing =
    .label = Pe ikel gin mo ki woko
    .accesskey = P
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chrome-beta =
    .label = Chrome Beta
    .accesskey = B
import-from-chrome-dev =
    .label = Chrome Dev
    .accesskey = D
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = x
import-from-360se =
    .label = 360 layeny ma tye ki ber bedo
    .accesskey = 3
no-migration-sources = Pe tye purugram mo matye ki tic me alama buk, gin mukato onyo mung me donyo ma kiromo nongo.
import-source =
    .label = Kel Ter kacel ki Tic ki woko
import-items-title =
    .label = Jami me akela ki woko
import-items-description = Yer jami me akela ki woko:
import-migrating-title =
    .label = Kelo ki woko…
import-migrating-description = Jami magi kombedi kitye ka kelo ki woko…
import-select-profile-title =
    .label = Yer Profile
import-select-profile-description = Profile magi nonge me kel ki iye:
import-done-title =
    .label = Kel ki woko otum
import-done-description = Jami magi okele maber ki woko:
import-close-source-browser = Tim ber inen ni layeny ma kiyero ni kiloro woko mapud pe imede anyim.
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = Ki i { $source }
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chrome-beta = Google Chrome Beta
source-name-chrome-dev = Google Chrome Dev
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 layeny ma tye ki ber bedo
imported-safari-reading-list = Kwano nying (Ki i Safari)
imported-edge-reading-list = Jami akwana (Ki i Edge)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Gin ayera me Intanet
    .value = Gin ayera me Intanet
browser-data-edge-1 =
    .label = Ter
    .value = Ter
browser-data-safari-1 =
    .label = Ter
    .value = Ter
browser-data-chrome-1 =
    .label = Ter
    .value = Ter
browser-data-canary-1 =
    .label = Ter
    .value = Ter
browser-data-360se-1 =
    .label = Ter
    .value = Ter
browser-data-ie-2 =
    .label = Angija
    .value = Angija
browser-data-edge-2 =
    .label = Angija
    .value = Angija
browser-data-safari-2 =
    .label = Angija
    .value = Angija
browser-data-chrome-2 =
    .label = Angija
    .value = Angija
browser-data-canary-2 =
    .label = Angija
    .value = Angija
browser-data-firefox-2 =
    .label = Angija
    .value = Angija
browser-data-360se-2 =
    .label = Angija
    .value = Angija
browser-data-ie-4 =
    .label = Gin mukato me yeny
    .value = Gin mukato me yeny
browser-data-edge-4 =
    .label = Gin mukato me yeny
    .value = Gin mukato me yeny
browser-data-safari-4 =
    .label = Gin mukato me yeny
    .value = Gin mukato me yeny
browser-data-chrome-4 =
    .label = Gin mukato me yeny
    .value = Gin mukato me yeny
browser-data-canary-4 =
    .label = Gin mukato me yeny
    .value = Gin mukato me yeny
browser-data-firefox-history-and-bookmarks-4 =
    .label = Gin mukato me yeny kacel ki Alama me buk
    .value = Gin mukato me yeny kacel ki Alama me buk
browser-data-360se-4 =
    .label = Gin mukato me yeny
    .value = Gin mukato me yeny
browser-data-ie-8 =
    .label = Kigwoko ki i Gin mukato
    .value = Kigwoko ki i Gin mukato
browser-data-edge-8 =
    .label = Kigwoko ki i Gin mukato
    .value = Kigwoko ki i Gin mukato
browser-data-safari-8 =
    .label = Kigwoko ki i Gin mukato
    .value = Kigwoko ki i Gin mukato
browser-data-chrome-8 =
    .label = Kigwoko ki i Gin mukato
    .value = Kigwoko ki i Gin mukato
browser-data-canary-8 =
    .label = Kigwoko ki i Gin mukato
    .value = Kigwoko ki i Gin mukato
browser-data-firefox-8 =
    .label = Kigwoko ki i Gin mukato
    .value = Kigwoko ki i Gin mukato
browser-data-360se-8 =
    .label = Kigwoko ki i Gin mukato
    .value = Kigwoko ki i Gin mukato
browser-data-ie-16 =
    .label = Mung me donyo ma kigwoko
    .value = Mung me donyo ma kigwoko
browser-data-edge-16 =
    .label = Mung me donyo ma kigwoko
    .value = Mung me donyo ma kigwoko
browser-data-safari-16 =
    .label = Mung me donyo ma kigwoko
    .value = Mung me donyo ma kigwoko
browser-data-chrome-16 =
    .label = Mung me donyo ma kigwoko
    .value = Mung me donyo ma kigwoko
browser-data-canary-16 =
    .label = Mung me donyo ma kigwoko
    .value = Mung me donyo ma kigwoko
browser-data-firefox-16 =
    .label = Mung me donyo ma kigwoko
    .value = Mung me donyo ma kigwoko
browser-data-360se-16 =
    .label = Mung me donyo ma kigwoko
    .value = Mung me donyo ma kigwoko
browser-data-ie-32 =
    .label = Ma imaro loyo
    .value = Ma imaro loyo
browser-data-edge-32 =
    .label = Ma imaro loyo
    .value = Ma imaro loyo
browser-data-safari-32 =
    .label = Alama buk
    .value = Alama buk
browser-data-chrome-32 =
    .label = Alama buk
    .value = Alama buk
browser-data-canary-32 =
    .label = Alama buk
    .value = Alama buk
browser-data-360se-32 =
    .label = Alama buk
    .value = Alama buk
browser-data-ie-64 =
    .label = Tic mukene
    .value = Tic mukene
browser-data-edge-64 =
    .label = Data mukene
    .value = Data mukene
browser-data-safari-64 =
    .label = Tic mukene
    .value = Tic mukene
browser-data-chrome-64 =
    .label = Tic mukene
    .value = Tic mukene
browser-data-canary-64 =
    .label = Tic mukene
    .value = Tic mukene
browser-data-firefox-other-64 =
    .label = Tic mukene
    .value = Tic mukene
browser-data-360se-64 =
    .label = Data mukene
    .value = Data mukene
browser-data-firefox-128 =
    .label = Dirica ki dirica matino
    .value = Dirica ki dirica matino
