# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

ssl-error-bad-server = Latic okelo tic marac ki llapok tic.
ssl-error-ssl2-disabled = Pia cwako ka SSL cik 2, ma kigengo woko.
ssl-error-bad-mac-read = SSL gamo rekod kwede coc twero kwena ma pe atir.
ssl-error-bad-mac-alert = SSLpia cwalo nyig coc me twero pa kwena ma pe atir.
ssl-error-bad-cert-alert = SSL pia pe romo yubu waraga mamegi.
ssl-error-revoked-cert-alert = SSL pia okwero waraga mamegi macalo kiloyo teko ne.
ssl-error-expired-cert-alert = SSL pia okwero waraga macalo kare ne okato.
ssl-error-ssl-disabled = Pe romo kube: SSL ki kwanyo woko.
ssl-error-fortezza-pqg = Pe romo kube: SSL pia tye i FORTEZZA mukene me gang.
ssl-error-no-ciphers-supported = Suit me chiper bene tye ci tiyo i purugram man.
ssl-error-bad-block-padding = SSL ogamo rekod kwede cido marac.
ssl-error-rx-record-too-long = SSL ogamo rekod ma okato lac me twero mamite.
ssl-error-rx-malformed-change-cipher = SSL ogamo bal me Lok rekod me Chiper Spec.
ssl-error-rx-malformed-alert = SSL ogamo rekod me Bedo Atera.
ssl-error-rx-unexpected-alert = SSL ogamo rekod me Bedo atera ma pe kigeno.
ssl-error-rx-unexpected-handshake = SSL ogamo rekod me Yengo cing ma pe kigeno.
ssl-error-rx-unexpected-application-data = SSL ogamo rekod me Cwalo Tic ma pe kigeno.
ssl-error-rx-unknown-record-type = SSL ogamo rekod kwede kit jami me yie ma pe ngene.
ssl-error-rx-unknown-handshake = SSLL ogamo kwena me yengo cing kwede kit kwena ma pe ngene.
ssl-error-rx-unknown-alert = SSL ogamo rekod me bedo atera kwede tito lok me bedo atera ma pe ngene.
ssl-error-close-notify-alert = SSL pia ocego kube man woko.
ssl-error-handshake-unexpected-alert = SSL pia pe onongo obedo kageno kwena me yengo cing ma en ogamo.
ssl-error-decompression-failure-alert = SSL pia pe onongo twero yaro loyo ne SSL rekod ma en ogamo.
ssl-error-handshake-failure-alert = SSL pia pe onongo twero laro dul me gwoko kuc me paramita ma kiyee woko.
ssl-error-unsupported-cert-alert = SSL pia pe cwako te waraga i kit ma en ogamo kwede.
ssl-error-sign-hashes-failure = Pe onongo romo nyutu tic mamite me moko waraga mamegi.
ssl-error-md5-digest-failure = MD5 kelo tic woko pe olare.
ssl-error-sha-digest-failure = SHA-1 kelo tic woko pe olare.
ssl-error-mac-computation-failure = MAC tiyo cura ne ki kompiuta pe olare.
ssl-error-pub-key-size-limit-exceeded = SSL Lapok tic otemo tic ki rwom-ma gang lagony pa lwak kwede suiti me chiper mawoko.
ssl-error-iv-param-failure = PKCS11 coc okwero gonyo IV dwoko i param.
ssl-error-init-cipher-suite-failure = Okwero dwoko suiti me chiper ma kiyero.
ssl-error-session-key-gen-failure = Latic okwero kelo lagony me kare pi kare me SSL.
ssl-error-no-server-key-for-alg = Lapok tic pe ki lagony pi namba me namba ma kitemo leyo ne.
ssl-error-token-insertion-removal = PKCS#11 kiroyo pwoc onyo kikwanyo kun tic onongo tye kawot anyim.
ssl-error-token-slot-not-found = Ku PKCS#11 pwoc onongo twero nonge pi tiyo tic mamite.
ssl-error-no-compression-overlap = Pe romo kube kakare kwede pia: pe tye rido cura mo marwate.
ssl-error-handshake-not-completed = Pe romo dwoko SSL mukene me yengo cing ni oo ka yengo cing matye otyeko.
ssl-error-no-trusted-ssl-client-ca = Pe tye twero me waraga mo keken ma kigeno pi SSL twero me latic.
ssl-error-decryption-failed-alert = Kijuko woko pia me coyo SSL rekod ma en ogamo.
ssl-error-record-overflow-alert = Pia ogamo rekod me SSL ma onongo bor loyo twero ma kimino.
ssl-error-unknown-ca-alert = Pia pe ngeno ki geno CA ma omino waraga mamegi.
ssl-error-access-denied-alert = Pia ogamo waraga matye katic, ento donyo gutyeko kwero woko.
ssl-error-decode-error-alert = Pia pe onongo romo cwalo SSL kwena me yengo cing.
ssl-error-protocol-version-alert = Ripot me pia pe rwate onyo cik me coc mape kicwako te.
ssl-error-insufficient-security-alert = Lapok tic mito ni kigwoko chipers maber maloyo en ma latic ocwako.
ssl-error-no-renegotiation-alert = Pia pe mino twero me laro nitit pi SSL paramita me gwoko kuc.
ssl-error-server-cache-not-configured = SSL kagwoko lapok tic pe kicano ki pe kigengo pi bur mac man.
ssl-error-unsupported-extension-alert = SSL pia pe cwako te TLS ma kikwayo pire hello nya ne.
ssl-error-certificate-unobtainable-alert = SSL pia pe twero nongo waraga mamegi ki URL ma kipoko.
ssl-error-bad-cert-status-response-alert = SSL pia onongo pe romo nongo OCSP lagam pi waraga ne.
ssl-error-rx-unexpected-uncompressed-record = SSL ogamo rekod ma pe kiyung mape kigeno.
sec-error-library-failure = poto pa ot me gwoko kuc.
sec-error-bad-data = ot me gwoko kuc: ogamo tic marac.
sec-error-output-len = ot me gwoko kuc: bal malac ma donyo woko.
sec-error-input-len = ot me kagwoko kuc obedo ki bal madwong iyie.
sec-error-invalid-ava = ot me gwoko kuc: AVA ma pe tiyo.
sec-error-no-nodelock = ot me gwoko kuc: pung.
sec-error-bad-database = ot me gwoko kuc: kagwoko tic marac.
sec-error-no-memory = ot me gwoko tic: poto pa kabedo pa lapo wic.
sec-error-duplicate-cert = Waraga bene dong tye i kagwoko tic mamegi.
sec-error-adding-cert = Bal i medo waraga i kagwoko tic.
sec-error-filing-key = Bal i piko lagony man me waraga.
sec-error-no-key = Lagony pa dano pi waraga man pe romo nonge iyi kagwoko tic
sec-error-cert-valid = Waraga man tye katic.
sec-error-cert-not-valid = Waraga man pe tye katic.
sec-error-cert-no-response = Ot gwoko waraga: Lagam pe
sec-error-crl-invalid = CRL Manyen tye ikit mape tiyo.
sec-error-path-len-constraint-invalid = Lac pa yo beo pe tiyo.
sec-error-cert-usages-invalid = Di bar me tic pa waraga pe tiyo.
sec-error-unknown-critical-extension = Waraga tye ki nya marac mape ngene.
sec-error-old-crl = CRL Manyen pe obino lacen loyo en matye.
sec-error-no-email-cert = Pe ki cono onyo keto capa cing: ipe ki waraga me email.
sec-error-unsupported-keyalg = Kicwako ku onyo ngene ku en namba me lagony.
sec-error-decryption-disallowed = Pe romo kwanye: kwanye kun tiyo ki wek woko namba onyo kit lagony.
xp-sec-fortezza-no-card = Pe kinongo kad me Fortezza
xp-sec-fortezza-none-selected = Pe kiyero kad me Fortezza
xp-sec-fortezza-more-info = Tim ber iyer piri keni wek inong ngec madwong ikom
xp-sec-fortezza-person-not-found = Piri keni pe ononge
xp-sec-fortezza-no-more-info = Pe tye ngec madong ikomi keni
xp-sec-fortezza-bad-pin = Pin mape tiyo
sec-error-krl-invalid = KRL Manyen tye ki yub ma pe tiyo.
sec-error-need-random = ot me gwoko kuc: mito tic me acuda.
sec-error-no-module = ot me gwoko kuc: pe tye dul me gwoko kuc ma romo tiyo tic ma kikwayo.
sec-error-read-only = ot me gwoko kuc: kwan-keken kagwoko tic.
sec-error-no-slot-selected = Pe ki bur onyo pwoc ma kiyero.
sec-error-safe-not-created = bal kun cweyo gin mo ma ogwoke maber
sec-error-baggage-not-created = bal kun cweyo gin me jami
sec-error-bad-export-algorithm = Namba mamite kikwero woko.
sec-error-exporting-certificates = Bal itemo me cwalo woko waraga.
sec-error-importing-certificates = Bal itemo me kelo waraga ki woko.
sec-error-pkcs12-duplicate-data = Pe okelo ki woko, bene dong tye ikagwoko tic.
sec-error-message-send-aborted = Pe kicwalo kwena.
sec-error-inadequate-cert-type = Pe kimoko kit waraga me cwalo tic.
sec-error-cert-addr-mismatch = Adress iyi waraga me keto cing pe rwate ki adressma i lawic kwena.
sec-error-keygen-fail = Pe romo kelo lagony mukene pa lwak/la dano.
sec-error-not-fortezza-issuer = Pia FORTEZZA chain pe tye ki FORTEZZA Waraga.
sec-error-cannot-move-sensitive-key = Lagony mapo pe kiromo nyiko ne dwoko i bur ka ma mite iye.
sec-error-js-add-mod-failure = Pe romo medo dul
sec-error-js-del-mod-failure = Pe romo kwanyo woko dul
sec-error-old-krl = KRL Manyen pe cok loyo en matye.
sec-error-cert-not-in-name-space = Twero me moka pi waraga man pe ki twero me mino waraga kwede nying man.
sec-error-krl-not-yet-valid = Loyo teko me nying lagony pi waraga man pwod pe tiyo.
sec-error-crl-not-yet-valid = Loyo teko me nying waraga pi waraga man pwod pe tiyo.
sec-error-ocsp-unknown-response-type = OCSP lagam pe romo cwale llung; obedo kit mape ngene.
sec-error-ocsp-not-enabled = Myero imi tit bot OCSP mapwod pe icako tiyo tic man.
sec-error-ocsp-no-default-responder = Myero iter OCSP lagam me gang mapwod pe icako tiyo tic man.
sec-error-crl-not-found = Pe kinongo CRL marwate.
sec-error-reused-issuer-and-serial = I tye katemo kelo ki woko waraga kwede lami ne marwate/nyige macalo waraga metye, ento meno pe obedo waraga marwate.
sec-error-busy = NSS pe onongo romo neke. Gin man pwod tye katic.
sec-error-extra-input = DER-kwena ma kicwalo tye ki tic ma pe kitiyo kwede ata.
sec-error-unrecognized-oid = Lapok yore Cal ma pe ngene.
sec-error-ocsp-invalid-signing-cert = OCSP mape tiyo keto capa cing i waraga iyi OCSP lagam.
sec-error-unknown-object-type = Kit cal ma pe ngene ma kipoko yore.
sec-error-incompatible-pkcs11 = PKCS #11 deribwa turo spec i iyore ma pe rwate.
sec-error-no-event = Pe tye bur mo manyen manonge i cawa man.
sec-error-crl-already-exists = CRL bene dong tye.
sec-error-not-initialized = NSS pe ki dwoko ne.
sec-error-token-not-logged-in = Tiyo tic pe olare pien PKCS#11 pe kiketo pwoc iyie.
sec-error-ocsp-bad-signature = OCSP lagam tye ki capa cing mape tiyo.
sec-error-out-of-search-limits = Yeny me tic pa waraga okato dit me yeny woko
sec-error-invalid-policy-mapping = Goyo map me cik tye ki cik mo
sec-error-unknown-aia-location-type = Kit kabedo ma pe ngene i waraga AIA nya ne
sec-error-bad-info-access-location = Ngec marac odonyo ikabedo ma i nya me waraga
