# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = Yab
    .accesskey = Y
places-open-all-in-tabs =
    .label = Yab weng i dirica matino
    .accesskey = Y
places-view =
    .label = Nen
    .accesskey = n
places-by-date =
    .label = Ki Nino dwe
    .accesskey = N
places-by-site =
    .label = Ki Kakube
    .accesskey = K
places-by-most-visited =
    .label = Ki Ma kilimo loyo
    .accesskey = M
places-by-last-visited =
    .label = Ki Ma kilimo me agiki
    .accesskey = a
places-by-day-and-site =
    .label = Ki Nino dwe kacel ki Kakube
    .accesskey = n
places-history-search =
    .placeholder = Yeny gin mukato
places-history =
    .aria-label = Gin mukato
places-bookmarks-search =
    .placeholder = Yeny alamabuk
places-delete-domain-data =
    .label = Wek wii owil woko ikom pot buk man
    .accesskey = W
places-sortby-name =
    .label = Yek ki nying
    .accesskey = r
places-library =
    .title = Ot gwoko buk
    .style = width:700px; height:500px;
places-organize-button =
    .label = Yubi
    .tooltiptext = Yub alama me pot buk mamegi
    .accesskey = Y
places-organize-button-mac =
    .label = Yubi
    .tooltiptext = Yub alama me pot buk mamegi
places-cmd-close =
    .key = w
places-view-button =
    .label = Neno
    .tooltiptext = Lok neno ni
    .accesskey = N
places-view-button-mac =
    .label = Neno
    .tooltiptext = Lok neno ni
places-view-menu-columns =
    .label = Nyut Rek ati
    .accesskey = R
places-view-sort-unsorted =
    .label = Ma pe kiyeko
    .accesskey = M
places-cmd-restore-from-file =
    .label = Yer Pwail…
    .accesskey = Y
places-import-bookmarks-from-html =
    .label = Kel alama me pot buk ki woko i HTML…
    .accesskey = K
places-view-sort-col-tags =
    .label = Lanyut
places-view-sort-col-url =
    .label = Kabedo
places-view-sort-col-date-added =
    .label = Kimedo
places-cmd-find-key =
    .key = f
places-back-button =
    .tooltiptext = Dok cen
