# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = উইজাৰ্ড ইমপোৰ্ট কৰক
import-from-bookmarks = ইয়াৰ পৰা পত্ৰচিহ্ন ইমপোৰ্ট কৰক:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-source =
    .label = পছন্দ আৰু তথ্য ইমপোৰ্ট কৰক
import-items-title =
    .label = ইমপোৰ্ট কৰিব লগা বস্তু
import-migrating-title =
    .label = ইমপোৰ্ট কৰা হৈছে...
import-migrating-description = নিম্নলিখিত বস্তু বৰ্ত্তমানে ইমপোৰ্ট কৰা হৈছে...
import-select-profile-description = ৰ পৰা নিম্নলিখিত আলেখ্য ইমপোৰ্ট কৰিবলৈ পোৱা যায়:
import-done-title =
    .label = ইমপোৰ্ট সম্পূৰ্ণ হ'ল
import-done-description = নিম্নলিখিত বস্তু সফলভাবে ইমপোৰ্ট কৰা হ'ল:
source-name-ie = Internet Explorer
source-name-safari = Safari
source-name-chrome = Google Chrome
source-name-firefox = Mozilla Firefox

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = ইন্টাৰনেট বিকল্পসমূহ
    .value = ইন্টাৰনেট বিকল্পসমূহ
browser-data-safari-1 =
    .label = পছন্দসমূহ
    .value = পছন্দসমূহ
browser-data-chrome-1 =
    .label = পছন্দসমূহ
    .value = পছন্দসমূহ
browser-data-canary-1 =
    .label = পছন্দসমূহ
    .value = পছন্দসমূহ
browser-data-ie-2 =
    .label = কুকিসমূহ
    .value = কুকিসমূহ
browser-data-safari-2 =
    .label = কুকিসমূহ
    .value = কুকিসমূহ
browser-data-chrome-2 =
    .label = কুকিসমূহ
    .value = কুকিসমূহ
browser-data-canary-2 =
    .label = কুকিসমূহ
    .value = কুকিসমূহ
browser-data-firefox-2 =
    .label = কুকিসমূহ
    .value = কুকিসমূহ
browser-data-ie-8 =
    .label = সংৰক্ষিত ফৰ্মৰ ইতিহাস
    .value = সংৰক্ষিত ফৰ্মৰ ইতিহাস
browser-data-safari-8 =
    .label = সংৰক্ষিত ফৰ্মৰ ইতিহাস
    .value = সংৰক্ষিত ফৰ্মৰ ইতিহাস
browser-data-chrome-8 =
    .label = সংৰক্ষিত ফৰ্মৰ ইতিহাস
    .value = সংৰক্ষিত ফৰ্মৰ ইতিহাস
browser-data-canary-8 =
    .label = সংৰক্ষিত ফৰ্মৰ ইতিহাস
    .value = সংৰক্ষিত ফৰ্মৰ ইতিহাস
browser-data-firefox-8 =
    .label = সংৰক্ষিত ফৰ্মৰ ইতিহাস
    .value = সংৰক্ষিত ফৰ্মৰ ইতিহাস
browser-data-safari-32 =
    .label = পত্ৰচিহ্নসমূহ
    .value = পত্ৰচিহ্নসমূহ
browser-data-chrome-32 =
    .label = পত্ৰচিহ্নসমূহ
    .value = পত্ৰচিহ্নসমূহ
browser-data-canary-32 =
    .label = পত্ৰচিহ্নসমূহ
    .value = পত্ৰচিহ্নসমূহ
browser-data-ie-64 =
    .label = অন্য তথ্য
    .value = অন্য তথ্য
browser-data-safari-64 =
    .label = অন্য তথ্য
    .value = অন্য তথ্য
browser-data-chrome-64 =
    .label = অন্য তথ্য
    .value = অন্য তথ্য
browser-data-canary-64 =
    .label = অন্য তথ্য
    .value = অন্য তথ্য
