# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Importo vediklis
import-from =
    { PLATFORM() ->
        [windows] Importuoti parinktis, adresyną, žurnalą, slaptažodžius ir kitus duomenis iš:
       *[other] Importuoti nuostatas, adresyną, žurnalą, slaptažodžius ir kitus duomenis iš:
    }
import-from-bookmarks = Importuoti adresyną iš:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = „Microsoft Edge“
    .accesskey = E
import-from-nothing =
    .label = Nieko neimportuoti
    .accesskey = N
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = „Chrome Canary“
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chromium =
    .label = „Chromium“
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = F
import-from-360se =
    .label = „360 Secure Browser“
    .accesskey = 3
no-migration-sources = Nepavyko rasti programų, kuriose būtų adresyno, naršymo žurnalo ar įrašytų slaptažodžių duomenų.
import-source =
    .label = Duomenų ir nuostatų importas
import-items-title =
    .label = Importuotini elementai
import-items-description = Pasirinkite, ką importuoti:
import-migrating-title =
    .label = Importuojama…
import-migrating-description = Importuojami šie elementai…
import-select-profile-title =
    .label = Profilio pasirinkimas
import-select-profile-description = Galima importuoti iš šių profilių:
import-done-title =
    .label = Importas baigtas
import-done-description = Sėkmingai importuota:
import-close-source-browser = Prieš tęsdami įsitikinkite, kad pasirinkta naršyklė yra išjungta.
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = Iš „{ $source }“
source-name-ie = Internet Explorer
source-name-edge = „Microsoft Edge“
source-name-safari = Safari
source-name-canary = „Google Chrome Canary“
source-name-chrome = Google Chrome
source-name-chromium = „Chromium“
source-name-firefox = Mozilla Firefox
source-name-360se = „360 Secure Browser“
imported-safari-reading-list = Skaitinių sąrašas (iš „Safari“)
imported-edge-reading-list = Skaitinių sąrašas (iš „Edge“)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Interneto nuostatos
    .value = Interneto nuostatos
browser-data-edge-1 =
    .label = Nuostatos
    .value = Nuostatos
browser-data-safari-1 =
    .label = Nuostatos
    .value = Nuostatos
browser-data-chrome-1 =
    .label = Nuostatos
    .value = Nuostatos
browser-data-canary-1 =
    .label = Nuostatos
    .value = Nuostatos
browser-data-360se-1 =
    .label = Nuostatos
    .value = Nuostatos
browser-data-ie-2 =
    .label = Slapukai
    .value = Slapukai
browser-data-edge-2 =
    .label = Slapukai
    .value = Slapukai
browser-data-safari-2 =
    .label = Slapukai
    .value = Slapukai
browser-data-chrome-2 =
    .label = Slapukai
    .value = Slapukai
browser-data-canary-2 =
    .label = Slapukai
    .value = Slapukai
browser-data-firefox-2 =
    .label = Slapukai
    .value = Slapukai
browser-data-360se-2 =
    .label = Slapukai
    .value = Slapukai
browser-data-ie-4 =
    .label = Naršymo retrospektyva
    .value = Naršymo retrospektyva
browser-data-edge-4 =
    .label = Naršymo žurnalas
    .value = Naršymo žurnalas
browser-data-safari-4 =
    .label = Naršymo žurnalas
    .value = Naršymo žurnalas
browser-data-chrome-4 =
    .label = Naršymo istorija
    .value = Naršymo istorija
browser-data-canary-4 =
    .label = Naršymo istorija
    .value = Naršymo istorija
browser-data-firefox-history-and-bookmarks-4 =
    .label = Naršymo žurnalas ir adresynas
    .value = Naršymo žurnalas ir adresynas
browser-data-360se-4 =
    .label = Naršymo žurnalas
    .value = Naršymo žurnalas
browser-data-ie-8 =
    .label = Įrašyti formų duomenys
    .value = Įrašyti formų duomenys
browser-data-edge-8 =
    .label = Įrašyti formų duomenys
    .value = Įrašyti formų duomenys
browser-data-safari-8 =
    .label = Įrašyti formų duomenys
    .value = Įrašyti formų duomenys
browser-data-chrome-8 =
    .label = Įrašyti formų duomenys
    .value = Įrašyti formų duomenys
browser-data-canary-8 =
    .label = Įrašyti formų duomenys
    .value = Įrašyti formų duomenys
browser-data-firefox-8 =
    .label = Įrašyti formų duomenys
    .value = Įrašyti formų duomenys
browser-data-360se-8 =
    .label = Įrašyti formų duomenys
    .value = Įrašyti formų duomenys
browser-data-ie-16 =
    .label = Įrašyti slaptažodžiai
    .value = Įrašyti slaptažodžiai
browser-data-edge-16 =
    .label = Įrašyti slaptažodžiai
    .value = Įrašyti slaptažodžiai
browser-data-safari-16 =
    .label = Įrašyti slaptažodžiai
    .value = Įrašyti slaptažodžiai
browser-data-chrome-16 =
    .label = Įrašyti slaptažodžiai
    .value = Įrašyti slaptažodžiai
browser-data-canary-16 =
    .label = Įrašyti slaptažodžiai
    .value = Įrašyti slaptažodžiai
browser-data-firefox-16 =
    .label = Įrašyti slaptažodžiai
    .value = Įrašyti slaptažodžiai
browser-data-360se-16 =
    .label = Įrašyti slaptažodžiai
    .value = Įrašyti slaptažodžiai
browser-data-ie-32 =
    .label = Adresynas
    .value = Adresynas
browser-data-edge-32 =
    .label = Adresynas
    .value = Adresynas
browser-data-safari-32 =
    .label = Adresynas
    .value = Adresynas
browser-data-chrome-32 =
    .label = Žymės
    .value = Žymės
browser-data-canary-32 =
    .label = Žymės
    .value = Žymės
browser-data-360se-32 =
    .label = Adresynas
    .value = Adresynas
browser-data-ie-64 =
    .label = Kiti duomenys
    .value = Kiti duomenys
browser-data-edge-64 =
    .label = Kiti duomenys
    .value = Kiti duomenys
browser-data-safari-64 =
    .label = Kiti duomenys
    .value = Kiti duomenys
browser-data-chrome-64 =
    .label = Kiti duomenys
    .value = Kiti duomenys
browser-data-canary-64 =
    .label = Kiti duomenys
    .value = Kiti duomenys
browser-data-firefox-other-64 =
    .label = Kiti duomenys
    .value = Kiti duomenys
browser-data-360se-64 =
    .label = Kiti duomenys
    .value = Kiti duomenys
browser-data-firefox-128 =
    .label = Langai ir kortelės
    .value = Langai ir kortelės
