# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

ssl-error-bad-client = Tenaren tok imot ugyldige data frå klienten.
ssl-error-bad-server = Klienten tok imot ugyldige data frå tenaren.
ssl-error-unsupported-certificate-type = Ikkje støtta sertifikattype.
ssl-error-bad-mac-read = SSL tok imot eit dokument med ugyldig meldingsautentiseringskode.
ssl-error-bad-mac-alert = SSL-verten rapporterte ein ugyldig meldingsautentiseringskode.
ssl-error-revoked-cert-alert = SSL-verten avslo sertifikatet ditt som tilbakekalt.
ssl-error-expired-cert-alert = SSL-verten avslo sertifikatet ditt som utgått på dato.
ssl-error-rx-malformed-hello-request = SSL tok imot ein Hello-førespurnad med feil format i handhelsinga.
ssl-error-rx-malformed-cert-request = SSL tok imot ei sertifikatførespurnad-handhelsing med feil format.
ssl-error-rx-malformed-hello-done = SSL tok imot ei tenar Hallo-Fullført handhelsing med feil format.
ssl-error-rx-malformed-cert-verify = SSL tok imot ei melding med ugyldig Certificate Verify-handhelsing.
ssl-error-rx-malformed-client-key-exch = SSL tok imot ei melding med ugyldig Client Key Exchange-handhelsing.
ssl-error-rx-malformed-finished = SSL tok imot ei melding med ugyldig Finished-handhelsing.
ssl-error-rx-malformed-change-cipher = SSL tok imot eit ugyldig Change Cipher Spec-element.
ssl-error-rx-malformed-alert = SSL tok imot eit ugyldig Alert-element.
ssl-error-rx-malformed-handshake = SSL tok imot eit ugyldig Handhelsings-element.
ssl-error-rx-malformed-application-data = SSL tok imot eit ugyldig Application Data-element.
ssl-error-rx-unexpected-hello-request = SSL tok imot ei uventa Hello Request-handhelsing.
ssl-error-rx-unexpected-client-hello = SSL tok imot ei uventa Client Hello-handhelsing.
ssl-error-rx-unexpected-server-hello = SSL tok imot ei uventa Server Hello-handhelsing.
ssl-error-rx-unexpected-certificate = SSL tok imot ei uventa Certificate-handhelsing.
ssl-error-rx-unexpected-server-key-exch = SSL tok imot ei uventa Server Key Exchange-handhelsing.
ssl-error-rx-unexpected-cert-request = SSL tok imot ei uventa Certificate Request-handhelsing.
ssl-error-rx-unexpected-hello-done = SSL tok imot ei uventa Server Hello Done-handhelsing.
ssl-error-rx-unexpected-cert-verify = SSL tok imot ei uventa Certificate Verify-handhelsing.
ssl-error-rx-unexpected-client-key-exch = SSL tok imot ei uventa Client Key Exchange-handhelsing.
ssl-error-rx-unexpected-finished = SSL tok imot ei uventa Finished-handhelsing.
ssl-error-rx-unexpected-change-cipher = SSL tok imot eit uventa Change Cipher Spec-element.
ssl-error-rx-unexpected-alert = SSL tok imot eit uventa Alert-element.
ssl-error-rx-unexpected-handshake = SSL tok imot eit uventa Handhelsing-element.
ssl-error-rx-unexpected-application-data = SSL tok imot eit uventa Application Data-element.
ssl-error-rx-unknown-record-type = SSL tok imot eit element med ukjent innhaldstype.
ssl-error-rx-unknown-handshake = SSL tok imot ei handhelsing-melding med ukjent meldingstype.
ssl-error-rx-unknown-alert = SSL tok imot eit varselelement med ukjent varsel-skildring.
ssl-error-handshake-unexpected-alert = SSL-motparten venta ikkje handhelsing-meldinga som han tok imot.
ssl-error-illegal-parameter-alert = SSL-motparten avslo ei handhelsing-melding sidan ho inneheldt ugyldig data.
ssl-error-unsupported-cert-alert = SSL-motparten har ikkje støtte for sertifikatstypen som han tok imot.
ssl-error-certificate-unknown-alert = SSL-motparten har eit uspesifisert problem med sertifikatet han tok imot.
ssl-error-generate-random-failure = SSL oppdaga eit problem med slumptallsgeneratoren.
ssl-error-server-key-exchange-failure = Ein uspesifisert feil oppstod under SSL Server Key Exchange-handhelsinga.
ssl-error-client-key-exchange-failure = Ein uspesifisert feil oppstod under SSL Client Key Exchange-handhelsinga.
ssl-error-md5-digest-failure = MD5-fingeravtrykksfunksjon feila.
ssl-error-sha-digest-failure = SHA-1-fingeravtrykksfunksjon feila.
ssl-error-mac-computation-failure = MAC-komputasjon feila.
ssl-error-handshake-not-completed = Kan ikkje initiere fleire SSL-handhelsingar før noverande handhelsing er fullført.
ssl-error-no-trusted-ssl-client-ca = Ingen sertifikatsautoritetar er tiltrudd for SSL klientautentisering.
ssl-error-access-denied-alert = Motparten tok imot eit gyldig sertifikat, men tilgang vart nekta.
ssl-error-export-restriction-alert = Motparten rapporterer at forhandlinga ikkje er i samsvar med offentlege eksportreglar.
ssl-error-protocol-version-alert = Motparten rapporterer om inkompatible eller ustøtta protokollversjonar.
ssl-error-internal-error-alert = Motparten rapporterer om at han har fått ein intern feil.
ssl-error-user-canceled-alert = Brukaren hos motparten avbraut handhelsinga.
ssl-error-server-cache-not-configured = SSL-tenaren sitt snøgglager er ikkje konfigurert, og ikkje slått av for denne socketen.
ssl-error-unsupported-extension-alert = SSL-motparten støttar ikkje den førespurde TLS hello-utvidinga.
ssl-error-bad-cert-status-response-alert = SSL-motparten klarte ikkje å ta imot ein OCSP-respons for sertifikatet sitt.
ssl-error-bad-cert-hash-value-alert = SSL-motparten rapporterer om ugyldig listeverdi i sertifikatet.
sec-error-invalid-time = Tidsstreng har ugyldig format.
sec-error-retry-password = Nytt passord er ugyldig.  Prøv på nytt.
sec-error-duplicate-cert = Sertifikatet finst allereie i databasen din.
sec-error-adding-cert = Ein feil oppstod ved tillegging av sertifikatet i databasen.
sec-error-cert-valid = Sertifikatet er gyldig.
sec-error-cert-not-valid = Sertifikatet er ikkje gyldig.
sec-error-cert-no-response = Cert-bibliotek: Ingen respons
sec-error-crl-invalid = Ny CRL har eit ugyldig format.
sec-error-extension-value-invalid = Utvidingsverdi i sertifikatet er ugyldig.
sec-error-extension-not-found = Sertifikatsutviding vart ikkje funne.
sec-error-ca-cert-invalid = Utskrivarsertifikatet er ugyldig.
sec-error-path-len-constraint-invalid = Avgrensing på sertifikatets stilengde er ugyldig.
sec-error-cert-usages-invalid = Bruksmåte-feltet til sertifikatet er ugyldig.
sec-internal-only = **Modul BERRE for intern bruk**
sec-error-old-crl = Ny CRL er ikkje nyare enn den som er aktiv no.
sec-error-pkcs7-bad-signature = Signaturverifikasjon feila: ingen signerar funne, for mange signerarar funne, eller ugyldige/øydelagde data.
xp-sec-fortezza-no-card = Ingen Fortezza-kort vart funne
xp-sec-fortezza-none-selected = Ingen Fortezza-kort er valt
xp-sec-fortezza-no-more-info = Har ikkje meir informasjon om den personlegdomen
xp-sec-fortezza-bad-pin = Ugyldig Pin
sec-error-krl-invalid = Ny KRL har ugyldig format.
sec-error-no-slot-selected = Ingen element eller stad vart valt.
sec-error-cert-nickname-collision = Eit sertifikat med same kallenamn finst alt.
sec-error-baggage-not-created = ein feil oppstod under opprettinga av bagasjeobjekt
sec-error-exporting-certificates = Feil ved eksport av sertifikat.
sec-error-user-cancelled = Brukaren trykte på avbryt.
sec-error-pkcs12-duplicate-data = Ikkje importert, finst allereie i databasen.
sec-error-message-send-aborted = Melding ikkje sendt.
sec-error-inadequate-cert-type = Sertifikatstypen er ikkje godkjent for denne bruksmåten.
sec-error-cert-addr-mismatch = Adresse i signatursertifikatet stemmer ikkje med adressa i meldingshovudet.
sec-error-bad-nickname = Kallenamnet til sertifikatet er alt i bruk.
sec-error-js-invalid-module-name = Ugyldig modulnamn.
sec-error-js-invalid-dll = Ugyldig modulsti/filnamn
sec-error-ckl-conflict = Ny CKL har forskjellig utskrivar enn gjeldande CKL.  Slett gjeldande CKL.
sec-error-cert-bad-access-location = Adressa til sertifikatsstatustenaren har ugyldig format.
sec-error-ocsp-unknown-response-type = Klarte ikkje å dekode OCSP-responsen; han har ugyldig type.
sec-error-ocsp-bad-http-response = OCSP-tenaren returnerte uventa/ugyldige HTTP-data.
sec-error-ocsp-server-error = OCSP-tenaren opplevde ein intern feil.
sec-error-ocsp-request-needs-sig = OCSP-tenaren krev ein signatur for denne førespurnaden.
sec-error-ocsp-unauthorized-request = OCSP-tenaren har avslått førespurnaden som uautorisert.
sec-error-ocsp-unknown-response-status = OCSP-tenaren returnerte ein ikkje attkjennande status.
sec-error-ocsp-unknown-cert = OCSP-tenaren har ingen status for sertifikatet.
sec-error-ocsp-not-enabled = Du må slå på OCSP før du utfører denne handlinga.
sec-error-ocsp-future-response = OCSP-responsen er ikkje gyldig enno (inneheld ein dato i framtida).
sec-error-digest-not-found = CMS eller PKCS #7 fingeravtrykk vart ikkje funne i den signerte meldinga.
sec-error-unsupported-message-type = CMS eller PKCS #7 meldingstype er ikkje støtta.
sec-error-crl-not-found = Ingen passande CRL blei funne.
sec-error-extra-input = DER-koda melding inneheheld ekstra ubrukte data.
sec-error-unsupported-elliptic-curve = Ikkje støtta elliptisk kurve.
sec-error-unsupported-ec-point-form = Ikkje støtta elliptisk kurvepunktform.
sec-error-unrecognized-oid = Ukjend objektidentifikasjon.
sec-error-ocsp-invalid-signing-cert = Ugyldig OCSP signerersertifikat i OCSP-respons.
sec-error-incompatible-pkcs11 = PKCS #11 drivar krenkjer spesifikasjonen på ein ukompatibel måte.
sec-error-no-event = Ingen nye plasshendingar er tilgjengelege no.
sec-error-crl-already-exists = CRL-en finst alt.
sec-error-not-initialized = NSS er ikkje initialisert.
sec-error-token-not-logged-in = Operasjonen feila fordi PKCS#11-elementet ikkje er innlogga.
sec-error-ocsp-bad-signature = OCSP-responsen har ein ugyldig signatur.
