# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

psmerr-ssl-disabled = 無法安全連線，因為 SSL 通訊協定已停用。
psmerr-ssl2-disabled = 無法安全連線，因為該網站使用舊版、不安全的 SSL 通訊協定。
ssl-error-export-only-server = 無法安全通訊，節點不支援高等級加密。
ssl-error-us-only-server = 無法安全通訊，不支援節點所要求的高等級加密。
ssl-error-no-certificate = 找不到鑑別需要的憑證或金鑰。
ssl-error-bad-client = 伺服器從用戶端收到損壞的資料。
ssl-error-bad-server = 用戶端從伺服器收到損壞的資料。
ssl-error-unsupported-certificate-type = 不支援的憑證類型。
ssl-error-wrong-certificate = 用戶端鑑別失敗: 金鑰資料庫中的私密金鑰和憑證資料庫中的公開金鑰不符。
ssl-error-bad-mac-read = SSL 接收了含錯誤訊息鑑別碼的記錄。
ssl-error-ssl-disabled = 無法連線: SSL 已停用。
ssl-error-bad-block-padding = SSL 收到含損壞區塊填充的記錄。
ssl-error-rx-record-too-long = SSL 收到含超出最大允許字串長度的記錄。
ssl-error-tx-record-too-long = SSL 試圖傳送超出最大允許字串長度的記錄。
ssl-error-rx-unexpected-hello-request = SSL 收到未預期的 Hello 請求交握訊息。
ssl-error-rx-unexpected-hello-done = SSL 收到未預期的伺服器 Hello 完成交握訊息。
ssl-error-rx-unexpected-change-cipher = SSL 收到未預期的變更密文格式記錄。
ssl-error-rx-unexpected-alert = SSL 收到未預期的警告記錄。
ssl-error-rx-unexpected-handshake = SSL 收到未預期的交握記錄。
ssl-error-rx-unexpected-application-data = SSL 收到未預期的程式資料記錄。
ssl-error-rx-unknown-record-type = SSL 收到含未知內容類型的記錄。
ssl-error-rx-unknown-handshake = SSL 收到含未知訊息類型的交握訊息。
ssl-error-rx-unknown-alert = SSL 收到含未知警告敘述的警告記錄。
ssl-error-generate-random-failure = SSL 的隨機數字產生器失效。
ssl-error-server-key-exchange-failure = 處理 SSL 伺服器金鑰交換交握時遇到不明原因的失敗。
ssl-error-client-key-exchange-failure = 處理 SSL 用戶端金鑰交換交握時遇到不明原因的失敗。
ssl-error-socket-write-failure = 試圖寫入加密資訊到其下的 socket 失敗。
ssl-error-md5-digest-failure = MD5 摘要函式失效。
ssl-error-sha-digest-failure = SHA-1 摘要函式失效。
ssl-error-mac-computation-failure = MAC 計算失敗。
ssl-error-sym-key-context-failure = 建立對稱式金鑰內容失敗。
ssl-error-sym-key-unwrap-failure = 於用戶端金鑰交換訊息展開對稱式金鑰時失敗。
ssl-error-iv-param-failure = 將 PKCS11 代碼轉譯為 IV 到參數時失敗。
ssl-error-session-key-gen-failure = 用戶端產生用於 SSL 連線的連線金鑰失敗。
ssl-error-no-server-key-for-alg = 伺服器沒有金鑰可供嘗試金鑰交換演算法。
ssl-error-token-insertion-removal = 操作進行時 PKCS#11 token 已插入或移除。
ssl-error-token-slot-not-found = 找不到 PKCS#11 token 完成要求的操作。
ssl-error-handshake-not-completed = 到目前的交握完成前無法初始其他的 SSL 交握。
ssl-error-cert-kea-mismatch = 提供的憑證無法用於所選的金鑰交換演算法。
ssl-error-session-not-found = 伺服器的連線快取中找不到用戶端的 SSL 連線 ID。
ssl-error-insufficient-security-alert = 伺服器請求的密文比用戶端可支援的安全性更高。
ssl-error-server-cache-not-configured = SSL 伺服器快取未組態且未於此 socket 停用。
sec-error-io = 在安全鑑別時發生 I/O 錯誤。
sec-error-library-failure = 安全函式庫失效。
sec-error-bad-data = 安全函式庫: 已收到損壞資料。
sec-error-output-len = 安全函式庫: 輸出長度錯誤。
sec-error-input-len = 安全函式庫遇到輸入長度錯誤。
sec-error-invalid-args = 安全函式庫: 無效的參數。
sec-error-invalid-algorithm = 安全函式庫: 無效的演算法。
sec-error-invalid-ava = 安全函式庫: 無效的 AVA。
sec-error-invalid-time = 不正確的時間字串格式。
sec-error-bad-der = 安全函式庫: 不正確的 DER 編碼訊息格式。
sec-error-bad-password = 輸入的安全密碼不正確。
sec-error-retry-password = 輸入的新密碼不正確，請再試一次。
sec-error-no-nodelock = 安全函式庫: 無 nodelock。
sec-error-bad-database = 安全函式庫: 損壞的資料庫。
sec-error-no-memory = 安全函式庫: 記憶體定址失敗。
sec-error-duplicate-cert = 憑證已存在於資料庫中。
sec-error-duplicate-cert-name = 所下載的憑證名稱和資料庫中的記錄重複。
sec-error-adding-cert = 新增憑證到資料庫時錯誤。
sec-error-filing-key = 重新填寫此憑證的金鑰時錯誤。
sec-error-no-key = 資料庫中找不到此憑證的私密金鑰。
sec-error-cert-valid = 此憑證有效。
sec-error-cert-not-valid = 此憑證無效。
sec-error-cert-no-response = 憑證函式庫: 無回應
sec-error-crl-bad-signature = 憑證簽發者的廢止清冊含無效的簽章。
sec-error-crl-invalid = 新憑證廢止清冊的格式無效。
sec-error-extension-value-invalid = 憑證擴充欄位的值無效。
sec-error-extension-not-found = 找不到憑證的擴充欄位。
sec-error-ca-cert-invalid = 簽發者的憑證無效。
sec-error-path-len-constraint-invalid = 憑證路徑長度限制無效。
sec-error-cert-usages-invalid = 憑證使用的欄位無效。
sec-internal-only = **專供內部使用的模組**
sec-error-unknown-critical-extension = 憑證含未知的 Critical 擴充欄位。
sec-error-old-crl = 新憑證廢止清冊不能比目前的清冊還晚。
sec-error-pkcs7-bad-signature = 簽章鑑別失敗: 找不到簽署者、找到太多簽署者或收到不正確、損毀的資料。
sec-error-unsupported-keyalg = 不支援或未知的金鑰演算法。
sec-error-decryption-disallowed = 無法解密: 加密資訊使用不允許的演算法或金鑰長度。
xp-sec-fortezza-no-card = 找不到 Fortezza 卡
xp-sec-fortezza-none-selected = 未選擇 Fortezza 卡
xp-sec-fortezza-bad-pin = 無效的 PIN
sec-error-no-krl = 找不到此網站憑證的金鑰廢止清冊。
sec-error-krl-expired = 此網站憑證的金鑰廢止清冊已過期。
sec-error-krl-bad-signature = 此網站憑證的金鑰廢止清冊含無效的簽章。
sec-error-revoked-key = 此網站憑證的金鑰廢止清冊金鑰已廢止。
sec-error-krl-invalid = 新金鑰廢止清冊格式無效。
sec-error-need-random = 安全函式庫: 需要隨機資料。
sec-error-no-module = 安全函式庫: 無安全模組能完成請求的操作。
sec-error-no-token = 安全卡或 Token 不存在、需要初始化或已被取出。
sec-error-read-only = 安全函式庫: 資料庫是唯讀狀態。
sec-error-no-slot-selected = 未選擇 Slot 或 Token。
sec-error-cert-nickname-collision = 憑證內含的相同暱稱已存在。
sec-error-key-nickname-collision = 金鑰內含的相同暱稱已存在。
sec-error-safe-not-created = 建立安全物件時錯誤
sec-error-baggage-not-created = 建立包裹物件時錯誤
xp-java-remove-principal-error = 無法移除 Principal
xp-java-delete-privilege-error = 無法刪除 Privilege
xp-java-cert-not-exists-error = 此 Principal 沒有憑證
sec-error-bad-export-algorithm = 所需的演算法不被允許。
sec-error-exporting-certificates = 嘗試匯出憑證時錯誤。
sec-error-importing-certificates = 嘗試匯入憑證時錯誤。
sec-error-pkcs12-decoding-pfx = 無法匯入，解碼錯誤，檔案無效。
sec-error-pkcs12-unsupported-transport-mode = 無法匯入，只支援密碼完整性及隱私模式。
sec-error-pkcs12-corrupt-pfx-structure = 無法匯入，檔案結構損毀。
sec-error-pkcs12-unsupported-pbe-algorithm = 無法匯入，加密演算法不支援。
sec-error-pkcs12-unsupported-version = 無法匯入，檔案版本不支援。
sec-error-pkcs12-privacy-password-incorrect = 無法匯入，隱私密碼不正確。
sec-error-pkcs12-cert-collision = 無法匯入，資料庫中已有相同的暱稱。
sec-error-user-cancelled = 使用者按下「取消」。
sec-error-pkcs12-duplicate-data = 未匯入，資料庫已有資料。
sec-error-message-send-aborted = 訊息未送出。
sec-error-inadequate-key-usage = 試圖操作的憑證金鑰用法不正確。
sec-error-inadequate-cert-type = 程式的憑證類型未被核准。
sec-error-pkcs12-unable-to-import-key = 無法匯入，試圖匯入私密金鑰時錯誤。
sec-error-pkcs12-unable-to-write = 無法匯出，無法寫入匯出檔案。
sec-error-pkcs12-unable-to-read = 無法匯入，無法讀取匯入檔案。
sec-error-pkcs12-key-database-not-initialized = 無法匯出，金鑰資料庫毀損或已刪除。
sec-error-keygen-fail = 無法產生公開╱私密金鑰對。
sec-error-invalid-password = 輸入的密碼無效，請選擇其他的密碼。
sec-error-retry-old-password = 輸入的舊密碼不正確，請再試一次。
sec-error-bad-nickname = 憑證暱稱已被使用。
sec-error-cannot-move-sensitive-key = Sensitive 金鑰無法移到所需要的 Slot。
sec-error-js-invalid-module-name = 模組名稱無效。
sec-error-js-invalid-dll = 模組路徑╱檔名無效。
sec-error-js-del-mod-failure = 無法刪除模組
sec-error-old-krl = 新金鑰廢止清冊不能比目前的清冊還晚。
sec-error-ckl-conflict = 新洩漏金鑰清冊和目前的清冊簽發者不同，請刪除目前的洩漏金鑰清冊。
sec-error-cert-not-in-name-space = 此憑證的憑證機構不允許用此名稱簽發憑證。
sec-error-krl-not-yet-valid = 此憑證的金鑰廢止清冊尚未驗證。
sec-error-crl-not-yet-valid = 此憑證的憑證廢止清冊尚未驗證。
sec-error-unknown-cert = 找不到請求的憑證。
sec-error-unknown-signer = 找不到簽署者的憑證。
sec-error-cert-bad-access-location = 憑證狀態伺服器位置的格式無效。
sec-error-ocsp-unknown-response-type = OCSP 回應無法被完全解碼；回應是未知的類型。
sec-error-ocsp-bad-http-response = OCSP 伺服器回傳了未預期╱無效的 HTTP 資料。
sec-error-ocsp-malformed-request = OCSP 伺服器發現請求已損毀或格式不正確。
sec-error-ocsp-server-error = OCSP 伺服器發生內部錯誤。
sec-error-ocsp-request-needs-sig = OCSP 伺服器需要此請求的簽章。
sec-error-ocsp-unauthorized-request = OCSP 伺服器已拒絕此未授權的請求。
sec-error-ocsp-unknown-response-status = OCSP 伺服器回傳了未辨識的狀態。
sec-error-ocsp-unknown-cert = OCSP 伺服器沒有憑證狀態。
sec-error-ocsp-malformed-response = 從 OCSP 伺服器傳來的回應已損毀或格式不正確。
sec-error-ocsp-unauthorized-response = OCSP 回應的簽署者未獲授權回應此憑證的狀態。
sec-error-ocsp-old-response = OCSP 回應內含過期的資訊。
sec-error-digest-not-found = 簽章訊息中找不到 CMS 或 PKCS #7 摘要。
sec-error-unsupported-message-type = CMS 或 PKCS #7 訊息類型不支援。
sec-error-module-stuck = PKCS #11 模組正在使用中，無法移除。
sec-error-bad-template = 無法解碼 ASN.1 資料，指定的範本無效。
sec-error-crl-not-found = 找不到相符的憑證廢止清冊。
sec-error-busy = NSS 無法關閉，物件還在使用中。
sec-error-extra-input = DER 編碼訊息含有額外的未使用資料。
sec-error-unsupported-elliptic-curve = 不支援的橢圓曲線。
sec-error-unsupported-ec-point-form = 不支援的橢圓曲線點格式。
sec-error-ocsp-invalid-signing-cert = OCSP 回應含無效的 OCSP 簽署憑證。
sec-error-revoked-certificate-crl = 在簽發者憑證廢止清單中的憑證已廢止。
sec-error-revoked-certificate-ocsp = 簽發者的 OCSP 回應者回報憑證已廢止。
sec-error-crl-invalid-version = 簽發者的憑證廢止清冊有未知的版本號碼。
sec-error-crl-v1-critical-extension = 簽發者的 V1 憑證廢止清單為 Critical 擴充欄位。
sec-error-crl-unknown-critical-extension = 簽發者的 V2 憑證廢止清單為未知的 Critical 擴充欄位。
sec-error-unknown-object-type = 指定的物件類型未知。
sec-error-incompatible-pkcs11 = PKCS #11 的驅動程式以不相容的方式違反規格。
sec-error-no-event = 目前沒有新 Slot 事件。
sec-error-crl-already-exists = 憑證廢止清冊已存在。
sec-error-not-initialized = NSS 尚未初始化。
sec-error-token-not-logged-in = 操作失敗，因為 PKCS#11 token 未登入。
sec-error-ocsp-responder-cert-invalid = 所設定 OCSP 回應者的憑證無效。
sec-error-ocsp-bad-signature = OCSP 回應含無效的簽章。
