# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


# DO NOT ADD THINGS OTHER THAN ERROR MESSAGES HERE.
# This file gets parsed into a JS dictionary of all known error message ids in
# gen_aboutneterror_codes.py . If we end up needing fluent attributes or
# refactoring them in some way, the script will need updating.

psmerr-ssl-disabled = SSL කෙටුම්පත අබල නිසා ආරක්‍ෂිතව සම්බන්ධ වීමට නොහැකිය.
psmerr-ssl2-disabled = අඩවිය මගින් SSL කෙටුම්පතෙහි පරණ, අනාරක්‍ෂිත අනුවාදයක් භාවිතා කරන නිසා ආරක්‍ෂිතව සම්බන්ධ වීමට නොහැකිය.
# This is a multi-line message.
psmerr-hostreusedissuerandserial =
    ඔබට වලංගු නොවන සහතිකයක් ලැබී ඇත. සේවාදායක පරිපාලක හෝ ලියුම්කරු අමතා ඔවුන්ට පහත තොරතුරු සපයන්න:
    
    සහතික අධිකාරිය විසින් නිකුත් කරන ලද තවත් සහතිකයකට සමාන අනුක්‍රමික අංකයක් ඔබගේ සහතිකයේ අඩංගු වේ. අනන්‍ය අනුක්‍රමික අංකයක් අඩංගු නව සහතිකයක් ගන්න.
ssl-error-no-certificate = සත්‍යාපනය සඳහා අවශ්‍ය සහතිකය හෝ යතුර සොයා ගැනීමට නොහැකි විය.
ssl-error-bad-client = අනුග්‍රාහකයේ නරක දත්ත සේවාදායකයට සමාසදය වී ඇත.
ssl-error-bad-server = අනුග්‍රාහකයේ නරක දත්ත සේවාදායකයට සමාසදය වී ඇත.
ssl-error-unsupported-certificate-type = සහය නොදක්වන සහතික වර්ගයකි.
ssl-error-wrong-certificate = අනුග්‍රාහකය සත්‍යාපනයට අසමත් විය: ප්‍රධාන දත්ත ගබඩාවේ පෞද්ගලික යතුර සහතික දත්ත ගබඩාවේ පොදු යතුර සමඟ නොගැළපේ.
ssl-error-bad-mac-read = SSL වෙත වැරදි පණිවිඩ සත්‍යාපන කේතයක් සහිත වාර්තාවක් ලැබිණි.
ssl-error-ssl-disabled = සබැඳීමට නොහැකිය: SSL අබල කර ඇත.
ssl-error-fortezza-pqg = සබැඳීමට නොහැකිය: SSL සාමානය වෙනත් FORTEZZA වසමක ඇත.
ssl-error-unknown-cipher-suite = නොදන්නානා SSL කේතාංක කට්ටලයක් ඉල්ලා ඇත.
ssl-error-no-ciphers-supported = මෙම වැඩසටහනේ කේතාංක කට්ටල නැත, හෝ සබල කර ද නැත.
ssl-error-rx-record-too-long = උපරිම අවසර දිය හැකි දිග ඉක්මවන වාර්තාවක් SSL වෙත ලැබිණි.
ssl-error-tx-record-too-long = උපරිම අවසර දිය හැකි දිග ඉක්මවන වාර්තාවක් යැවීමට SSL තැත් කෙරිණි.
ssl-error-rx-unexpected-hello-request = අතට අත දීමේ අනපේක්‍ෂිත ආයුබෝවන් ඉල්ලීමක පණිවිඩයක් SSL වෙත ලැබිණි.
ssl-error-rx-unexpected-client-hello = අනුග්‍රාහක අතට අත දීමේ අනපේක්‍ෂිත ආයුබෝවන් පණිවිඩයක් SSL වෙත ලැබිණි.
ssl-error-rx-unexpected-server-hello = සේවාදායක අතට අත දීමේ අනපේක්‍ෂිත ආයුබෝවන් පණිවිඩයක් SSL වෙත ලැබිණි.
ssl-error-rx-unexpected-certificate = සහතිකය අතට අත දීමේ අනපේක්‍ෂිත පණිවිඩයක් SSL වෙත ලැබිණි.
ssl-error-rx-unexpected-server-key-exch = සේවාදායකයේ යතුර හුවමාරු වන අතට අත දීමේ අනපේක්‍ෂිත පණිවිඩයක් SSL වෙත ලැබිණි.
ssl-error-rx-unexpected-cert-request = සහතිකය ඉල්ලන අතට අත දීමේ අනපේක්‍ෂිත පණිවිඩයක් SSL වෙත ලැබිණි.
ssl-error-rx-unexpected-cert-verify = සහතිකය තහවුරු කරන අතට අත දීමේ අනපේක්‍ෂිත පණිවිඩයක් SSL වෙත ලැබිණි.
ssl-error-rx-unexpected-client-key-exch = අනුග්‍රාහකයේ යතුර හුවමාරු වන අනපේක්‍ෂිත අතට අත දීමේ පණිවිඩයක් SSL වෙත ලැබිණි.
ssl-error-rx-unexpected-alert = අනපේක්‍ෂිත ඇඟවීම් වාර්තාවක් SSL වෙත ලැබිණි.
ssl-error-rx-unexpected-handshake = අනපේක්‍ෂිත අතට අත දීමේ වාර්තාවක් SSL වෙත ලැබිණි.
ssl-error-rx-unexpected-application-data = අනපේක්‍ෂිත යෙදුම් දත්ත වාර්තාවක් SSL වෙත ලැබිණි.
ssl-error-rx-unknown-record-type = නොදන්නා අන්තර්ගත වර්ගයක් සහිත වාර්තාවක් SSL වෙත ලැබිණි.
ssl-error-rx-unknown-handshake = නොදන්නා පණිවිඩ වර්ගයක් සහිත අතට අත දීමේ පණිවිඩයක් SSL වෙත ලැබුණි.
ssl-error-rx-unknown-alert = නොදන්නා ඇඟවීම් විස්තරයක් සහිත ඇඟවීම් වාර්තාවක් SSL වෙත ලැබුණි.
ssl-error-close-notify-alert = SSL සාමානය මෙම සම්බන්ධතාවය වසා ඇත.
ssl-error-unsupported-cert-alert = ලැබුණු වර්ගයේ සහතික සඳහා SSL සාමානය සහය නොදක්වයි.
ssl-error-sign-hashes-failure = ඔබගේ සහතිකය තහවුරු කිරීමට අවශ්‍ය දත්ත අංකිතව අත්සන් කළ නොහැකිය.
ssl-error-mac-computation-failure = මා.ප්‍ර.පා. ආගණනයට අසමත් විය.
ssl-error-session-key-gen-failure = SSL වාරය සඳහා වාර යතුරු උත්පාදනයට සේවාදායකය අසමත් විය.
ssl-error-handshake-not-completed = වත්මන් අතට අත දීම සම්පූර්ණ වන තුරු තවත් SSL අතට අත දීමක් ඇරඹීමට නොහැකිය.
ssl-error-session-not-found = අනුග්‍රාහකයේ SSL වාර හැඳු. සේවාදායකයේ වාර නිහිතයේ හමු නොවිණි.
ssl-error-decryption-failed-alert = ලැබුණු SSL වාර්තාවක් විකේතනය කිරීමට සාමානයට නොහැකි විය.
ssl-error-unknown-ca-alert = සාමානය ඔබගේ සහතිකය නිකුත් කළ CA නොහඳුනයි සහ විශ්වාස නොකරයි.
ssl-error-decode-error-alert = SSL අතට අත දීමේ පණිවිඩයක් සාමානයට විකේතනය කළ නොහැකි විය.
ssl-error-decrypt-error-alert = අත්සන සත්‍යාපනයට හෝ යතුර හුවමාරුවට අසමත් වූ බව සාමානය වාර්තා කරයි.
ssl-error-protocol-version-alert = නොගැළපෙන හෝ සහය නොදක්වන කෙටුම්පත් අනුවාදයක් සාමානය වාර්තා කරයි.
ssl-error-insufficient-security-alert = අනුග්‍රාහකය සහාය දක්වන කේතාංක වලට වඩා ආරක්‍ෂිත එකක් සේවාදායකයට අවශ්‍යයි.
ssl-error-internal-error-alert = සාමානය අභ්‍යන්තර දෝෂයක් අත්විඳි බව වාර්තා කරයි.
ssl-error-user-canceled-alert = සාමානය අතට අත දීම අවලංගු කෙරිණි.
ssl-error-server-cache-not-configured = මෙම කෙවෙනියට SSL සේවාදායක නිහිතය වින්‍යාසගත කර නැත හා අබල කර නැත.
ssl-error-unsupported-extension-alert = SSL සාමානය ඉල්ලූ TLS ආයුබෝවන් දිගුව සඳහා සහය නොදක්වයි.
ssl-error-certificate-unobtainable-alert = සපයා ඇති URL එකෙන් ඔබගේ සහතිකය ලබා ගැනීමට SSL අග්‍රයට නොහැකි විය.
ssl-error-unrecognized-name-alert = ඉල්ලූ DNS නමට SSL අග්‍රය සතුව සහතික නොමැත.
ssl-error-bad-cert-status-response-alert = එහි සහතිකයට OCSP ප්‍රතිචාරයක් ලබා ගැනීමට SSL අග්‍රයට නොහැකි විය.
ssl-error-bad-cert-hash-value-alert = SSL peer reported bad certificate hash value.
ssl-error-rx-unexpected-new-session-ticket = SSL received an unexpected New Session Ticket handshake message.
ssl-error-rx-malformed-new-session-ticket = SSL received a malformed New Session Ticket handshake message.
ssl-error-decompression-failure = SSL received a compressed record that could not be decompressed.
ssl-error-renegotiation-not-allowed = Renegotiation is not allowed on this SSL socket.
ssl-error-unsafe-negotiation = Peer attempted old style (potentially vulnerable) handshake.
ssl-error-rx-unexpected-uncompressed-record = SSL received an unexpected uncompressed record.
ssl-error-weak-server-ephemeral-dh-key = SSL received a weak ephemeral Diffie-Hellman key in Server Key Exchange handshake message.
ssl-error-next-protocol-data-invalid = SSL received invalid NPN extension data.
ssl-error-feature-not-supported-for-ssl2 = SSL feature not supported for SSL 2.0 connections.
ssl-error-feature-not-supported-for-servers = SSL feature not supported for servers.
ssl-error-feature-not-supported-for-clients = SSL feature not supported for clients.
ssl-error-invalid-version-range = SSL වෙළුම් පරාසය වලංගු නැත.
ssl-error-cipher-disallowed-for-version = SSL සම තෝරාගත් ප්රොටොකෝලය අනුවාදය සඳහා ඉඩ ෙනොදිය වූ ​​කේතාංක සූට් තෝරා ගන්නා ලදී.
ssl-error-rx-malformed-hello-verify-request = SSL ලබුනු 'malformed Hello' පණිවිඩය ඉල්ලීම් තහවුරු කරන්න ලද 'handshake' පණිවිඩයකි
ssl-error-rx-unexpected-hello-verify-request = SSL අනපේක්ෂිත හෙලෝ ඉල්ලීම් තහවුරු කරන්න ලද 'handshake' පණිවිඩය ලැබී .
ssl-error-feature-not-supported-for-version = SSL ලක්ෂණය සේවාදායක පහසුකම් සපයන්නේ නැත .
ssl-error-rx-unexpected-cert-status = බලාපොරොත්තු නොවූ සහතික පිළිගැනීමේ පණිවිඩයක් SSL ට ලැබුණි.
ssl-error-unsupported-hash-algorithm = TLS සම විසින් භාවිතා සහය නොදක්වන හැෂ් ඇල්ගොරිධම .
ssl-error-digest-failure = ධාරණය කිරීමේ ක්‍රියාව අසමත් විය.
ssl-error-incorrect-signature-algorithm = එය ඩිජිටල් අත්සන් අංගයක් , හි නිශ්චිතව දක්වා වැරදි අත්සන ඇල්ගොරිධම .
ssl-error-next-protocol-no-callback = ඊළඟ ප්රොටොකෝලය සාකච්ඡා දීර්ඝ සක්රීය කරන ලදී , නමුත් callback පෙර අවශ්ය කරනු සඳහා කරන ලදී.
ssl-error-next-protocol-no-protocol = සේවාදායකය සේවාදායකයා ALPN දීර්ඝ ප්රචාරය බවට කිසිදු මැඩීමට සඳහා සහය දක්වයි.
ssl-error-inappropriate-fallback-alert = සේවාලාභියා විසින් සේවාදායකය ආධාරක , වඩා අඩු TLS අනුවාදය බාල්දු නිසා සේවාදායකය 'handshake' ප්රතික්ෂේප කලේ ය.
sec-error-io = ආරක්ෂණ අවසර ලබා දීමේදී I/O දෝෂයක් මතු විය.
sec-error-library-failure = ආරක්ෂණ පුස්තකාලය අසමත් වීම.
sec-error-bad-data = ආරක්ෂණ පුස්තකාලය: නරක දත්ත ලැබුණි.
sec-error-output-len = ආරක්ෂණ පුස්තකාලය: ප්‍රතිදාන දිගෙහි දොෂයක්.
sec-error-input-len = ආරක්ෂණ පුස්තකාලයට ප්‍රදාන දිගෙහි දෝෂයක් හමුවී ඇත.
sec-error-invalid-args = ආරක්ෂණ පුස්තකාලය: පරාමිතීන් අවලංගුය.
sec-error-invalid-algorithm = ආරක්ෂණ පුස්තකාලය: අවලංගු ඇල්ගොරිතම.
sec-error-invalid-ava = ආරක්ෂණ පුස්තකාලය: අවලංගු AVA.
sec-error-invalid-time = අවිධිමත් ලෙස සකසන ලද වේලා අනුලකුණු වැල.
sec-error-bad-der = ආරක්ෂණ පුස්තකාලය: අවිධිමත් ලෙස සකසන ලද DER-කේතාංකිත පණිවිඩය.
sec-error-bad-signature = අග්‍රයේ සහතිකයේ අවිධිමත් අත්සනක් ඇත.
sec-error-expired-certificate = අග්‍රයේ සහතිකය කල් ඉකුත් වී ඇත.
sec-error-revoked-certificate = අග්‍රයේ සහතිකය ඉල්ලා අස් කරගෙන ඇත.
sec-error-unknown-issuer = අග්‍රයේ සහතිකය නිකුත් කරන්නා නොහඳුනයි.
sec-error-bad-key = අග්‍රයේ පොදු යතුර අවලංගුයි.
sec-error-bad-password = ඇතුල් කරන ලද ආරක්ෂණ රහස් පදය අසත්‍යය.
sec-error-no-nodelock = security library: no nodelock.
sec-error-bad-database = ආරක්ෂණ පුස්තකාලය: නරක දත්ත ගබඩාව.
sec-error-no-memory = ආරක්ෂණ පුස්තකාලය: මතක පැවරීම අසමත් වීම.
sec-error-untrusted-issuer = අග්‍රයේ සහතිකය නිකුත් කරන්නා භාවිතා කරන්නා විසින් විශ්වාස නොකරන බවට සළකුණු කර ඇත.
sec-error-untrusted-cert = අග්‍රයේ සහතිකය භාවිතා කරන්නා විසින් විශ්වාස නොකරන බවට සළකුණු කර ඇත.
sec-error-duplicate-cert = සහතිකය දැනටමත් ඔබගේ දත්ත ගබඩාවේ පවතී.
sec-error-duplicate-cert-name = බාගත කළ සහතික නාමය දැනටමත් ඔබගේ දත්ත ගොනුවේ ඇති එකක් හා අනු පිටපත් කරයි.
sec-error-adding-cert = සහතිකය දත්ත ගබඩාවට එක් කිරීමේදී දෝෂයක්.
sec-error-filing-key = මෙම සහතිකය සඳහා යතුර නැවත පිරවීමේදී දෝෂයක්.
sec-error-no-key = මෙම සහතිකය සඳහා පුද්ගලික යතුර යතුරු දත්ත ගබඩාවේ සොයා ගැනීමට නොහැක
sec-error-cert-valid = මෙම සහතිකය වලංගුයි.
sec-error-cert-not-valid = මෙම සහතිකය අවලංගුයි.
sec-error-cert-no-response = Cert Library: No Response
sec-error-crl-bad-signature = සහතිකයේ නිකුත් කරන්නා සඳහා CRT සඳහා අවලංගු අත්සනක් ඇත.
sec-error-crl-invalid = නව CRL ට අවලංගු අකෘතියක් ඇත.
sec-error-extension-value-invalid = සහතික දිගු අගය අවලංගුය.
sec-error-extension-not-found = සහතික දිගුව හමු නොවුණි.
sec-error-ca-cert-invalid = නිකුත් කරන්නාගේ සහතිකය අවලංගුය.
sec-error-path-len-constraint-invalid = සහතික පෙතෙහි දිග වැළැක්වීම අවලංගුයි.
sec-error-cert-usages-invalid = සහතික භාවිතා කිරීමේ ක්ෂේත්‍රය අවලංගුය.
sec-internal-only = **Internal ONLY module**
sec-error-invalid-key = ඉල්ලූ ක්‍රියාව සඳහා ක්‍රියාව සහය දක්වන්නේ නැත.
sec-error-unknown-critical-extension = සහතිකයේ නොදන්නා අවදානම් දිගුවක් අඩංගු වේ.
sec-error-old-crl = නව CRL දැනට පවතින එකට වඩා අවර නොවේ.
sec-error-no-email-cert = සංකේතාංකනය හෝ අත්සන් කර නැත: ඔබට තවමත් විද්‍යුත් ලිපින සහතිකයක් නොමැත.
sec-error-no-recipient-certs-query = සංකේතාංකනය කර නැත: ඔබට සෑම ප්‍රතිග්‍රාහකයෙකු සඳහාම සහතිකයක් නොමැත.
sec-error-not-a-recipient = Cannot decrypt: you are not a recipient, or matching certificate and private key not found.
sec-error-pkcs7-keyalg-mismatch = Cannot decrypt: key encryption algorithm does not match your certificate.
sec-error-pkcs7-bad-signature = අත්සන සහතික කිරීම අසමත්විය: අත්සන් කරන්නෙක් හමු නොවුණි, බොහෝ අත්සන් කරන්නන් හමු වුණි, නැත්නම් අක්‍රමානුකූල හෝ වැරදි දත්ත.
sec-error-unsupported-keyalg = සහය නොදක්වන හෝ නොදන්නා යතුරු ඇල්ගොරිතම.
sec-error-decryption-disallowed = Cannot decrypt: encrypted using a disallowed algorithm or key size.
xp-sec-fortezza-no-card = Fortezza පත්‍ර හමු නොවුණි
xp-sec-fortezza-none-selected = Fortezza පත්‍ර තෝරා නොගැනුණි
xp-sec-fortezza-more-info = කරුණාකර වැඩි විස්තර ලබා ගැනීමට පුද්ගලත්වයක් තෝරන්න
xp-sec-fortezza-person-not-found = පුද්ගලත්වයක් හමු නොවුණි
xp-sec-fortezza-no-more-info = එම පුද්ගලත්වය ගැන වැඩි විස්තර නොමැත
xp-sec-fortezza-bad-pin = අවලංගු රහස් අංකය
xp-sec-fortezza-person-error = Fortezza පුද්ගලත්වයක් ආරම්භ කිරීමට නොහැකි විය.
sec-error-no-krl = මෙම අඩවියේ සහතිකය සඳහා KRL හමු වී නොමැත.
sec-error-krl-expired = මෙම අඩවියේ සහතිකය අඳහා KRL කල් ඉකුත් වී ඇත.
sec-error-krl-bad-signature = මෙම අඩවියේ සහතිකය සඳහා KRL ට අවලංගු අත්සනක් ඇත.
sec-error-revoked-key = මෙම අඩවියේ සහතිකය සඳහා යතුර අවලංගු කර ඇත.
sec-error-krl-invalid = නව KRL ට අවලංගු ආකෘතියක් ඇත.
sec-error-need-random = ආරක්ෂණ පුස්තකාලය: අහඹු දත්ත අවශ්‍යයි.
sec-error-no-module = ආරක්ෂණ පුස්තකාලය: ඉල්ලූ ක්‍රියාව සිදු කිරීමට කිසිම ආරක්ෂණ ඒකකයකට නොහැක.
sec-error-no-token = ආරක්ෂණ පත හෝ සංඥාව නොපවතී, ඇරඹීමට අවශ්‍යයි, හෝ ඉවත් කර ඇත.
sec-error-read-only = ආරක්ෂණ පුස්තකාලය: කියවීමට පමණක් වූ දත්ත ගබඩාව.
sec-error-no-slot-selected = සංඥාවක් හෝ තව්වක් තෝරා නොගැනුණි.
sec-error-cert-nickname-collision = එම විකට නම ඇති සහතිකයක් දැනටමත් පවතී.
sec-error-key-nickname-collision = එම විකට නම ඇති යතුරක් දැනටමත් පවතී.
sec-error-safe-not-created = සුරක්ෂිත වස්තුවක් සෑදීමේදී දෝෂයක්
sec-error-baggage-not-created = ආම්පන්න වස්තුවක් සෑදීමේදී දෝෂයක්
xp-java-remove-principal-error = ප්‍රධානියා ඉවත් කිරීමට නොහැකි විය
xp-java-delete-privilege-error = වරප්‍රසාදය ඉවත් කිරීමට නොහැකි විය
xp-java-cert-not-exists-error = මෙම ප්‍රධානියාට සහතිකයක් නොමැත
sec-error-bad-export-algorithm = ඉල්ලූ ඇල්ගොරිතමට අවසර දී නොමැත.
sec-error-exporting-certificates = සහතික අපනයනය කිරීමේදී දෝෂයක්.
sec-error-importing-certificates = සහතික ආනයනය කිරීමේදී දෝෂයක්.
sec-error-user-cancelled = භාවිතා කරන්නා නැවැත්වීම ඔබන ලදි.
sec-error-pkcs12-duplicate-data = ආනයනය නොකෙරිණි, දැනටමත් දත්ත ගබඩාවේ පවතී.
sec-error-message-send-aborted = පණිවිඩය නොයැවුණි.
sec-error-inadequate-key-usage = ඉල්ලූ ක්‍රියාව සඳහා සහතික යතුරු භාවිතය නොසෑහේ.
sec-error-inadequate-cert-type = වැඩසටහන සඳහා සහතික ආකාරය අනුමත කර නොමැත.
sec-error-cert-addr-mismatch = සහතිකය අත්සන් කිරීමේ ලිපිනය පණිවිඩය සිරසේ ලිපිනය හා නොගැළපේ.
sec-error-keygen-fail = පොදු/පුදිගලික යතුරු යුගලයක් නිපදවීමට නොහැක.
sec-error-bad-nickname = සහතිකයේ විකට නාමය දැනටමත් භාවිතයේ පවතී.
sec-error-not-fortezza-issuer = FORTEZZA අග්‍ර දාමයේ FORTEZZA නොවන සහතිකයක් ඇත.
sec-error-cannot-move-sensitive-key = සංවේදී යතුර එය අවශ්‍ය තව්වට චලිත කරවීමට නොහැක.
sec-error-js-invalid-module-name = ඒකක නම අවලංගුයි.
sec-error-js-invalid-dll = ඒකක පෙත/ගොනු නාමය අවලංගුයි
sec-error-js-add-mod-failure = ඒකකය එක් කිරීමට නොහැක
sec-error-js-del-mod-failure = ඒකකය මැකීමට නොහැක
sec-error-old-krl = නව KRL පැරණි එකට වඩා අවර නැත.
sec-error-cert-not-in-name-space = මෙම සහතිකය සඳහා වූ සහතික කිරීමේ අධිකාරියට මෙම නමින් සහතිකයක් නිකුත් කිරීමට අවසර දී නොමැත.
sec-error-krl-not-yet-valid = මෙම සහතිකය සඳහා වූ යතුරු අහෝසි කිරීමේ ලැයිස්තුව තවමත් වලංගු නැත.
sec-error-crl-not-yet-valid = මෙම සහතිකය සඳහා වූ සහතික අහෝසි කිරීමේ ලැයිස්තුව තවමත් වලංගු නැත.
sec-error-unknown-cert = ඉල්ලූ සහතිකය සොයා ගැනීමට නොහැකි විය.
sec-error-unknown-signer = අත්සන් කරන්නාගේ සහතිකය සොයා ගැනීමට නොහැකි විය.
sec-error-cert-bad-access-location = The location for the certificate status server has invalid format.
sec-error-ocsp-unknown-response-type = OCSP ප්‍රතිචාරය සම්පූර්ණයෙන්ම තේරුම් ගැනීමට නොහැක; එන නොදන්නා ආකාරයකින් තිබේ.
sec-error-ocsp-bad-http-response = OCSP සේවකයා බලාපොරොත්තු නොවූ/අවලංගු HTTP දත්ත නැවත එවා තිබේ.
sec-error-ocsp-malformed-request = ඉල්ලීම දූෂණය වී හෝ අනිසි ලෙස සකසා ඇති බව OCSP සේවකයා සොයා ගන්නා ලදි.
sec-error-ocsp-server-error = OCSP සේවකයාට අභ්‍යන්තර දෝෂයක් හමු විය.
sec-error-ocsp-try-server-later = OCSP සේවකයා පසුව නැවත උත්සහ කිරීමට යෝජනා කරයි.
sec-error-ocsp-request-needs-sig = මෙම ඉල්ලීම කෙරෙහි OCSP සේවකයා අත්සනක් ඉල්ලයි.
sec-error-ocsp-unauthorized-request = OCSP සේවකයා මෙම ඉල්ලීම අවසර නොමැති ලෙස ප්‍රතික්ෂේප කර ඇත.
sec-error-ocsp-unknown-response-status = OCSP සේවකයා හඳුනාගනීමට නොහැකි තත්වයක් ආපසු එවන ලදි.
sec-error-ocsp-unknown-cert = OCSP සේවකයාට සහතිකය සඳහා තත්වයක් නොමැත.
sec-error-ocsp-not-enabled = මෙම ක්‍රියාව සිදු කිරීමට පෙර ඔබ OCSP ක්‍රියාත්මක කළ යුතුය.
sec-error-ocsp-no-default-responder = මෙම ක්‍රියාව සිදු කිරීමට පෙර ඔබ OCSP පෙරනිමි ප්‍රතිචාරකයා සකසා තිබිය යුතුය.
sec-error-ocsp-malformed-response = OCSP සේවකයාගෙන් ලැබුණු ප්‍රතිවාරය දූෂණය හෝ අනිසි ලෙස සකසා තිබුණි.
sec-error-ocsp-unauthorized-response = OCSP ප්‍රතිචාතය අත්සන් කරන්නාට මෙම සහතිකය සඳහා තත්වයක් ලබා දීමට අවසර නැත.
sec-error-ocsp-future-response = OCSP ප්‍රතිචාරය තවමත් වලංගු නැත (ඉදිරි දත්තයක් අදංගු වේ).
sec-error-ocsp-old-response = OCSP ප්‍රතිවාරයේ කල් ඉකුත් වූ තොරතුරු අඩංගු වේ.
sec-error-digest-not-found = The CMS හෝ PKCS #7 සඟරාව අත්සන් කරන ලද පණිවිඩ වල හමු නොවුණි.
sec-error-unsupported-message-type = CMS හෝ PKCS #7 පණිවිඩ වර්ගය සහය නොදක්වයි.
sec-error-module-stuck = PKCS #11 ඒකකය තවමත් භාවිතයේ පවතින නිසා ඉවත් කිරීමට නොහැකි විය.
sec-error-bad-template = ASN.1 දත්ත තේරුම් ගැනීමට නොහැකි විය. විශේෂණය කළ ආකෘතිය අවලංගු විය.
sec-error-crl-not-found = ගැළපෙන CRL එකක් හමු නොවුණි.
sec-error-reused-issuer-and-serial = You are attempting to import a cert with the same issuer/serial as an existing cert, but that is not the same cert.
sec-error-busy = NSS චැඩ නැවැත්වීමට නොහැකි විය. වස්තූන් තවමත් භාවිතයේ පවතී.
sec-error-extra-input = DER-කේතාංකිත පණිවිඩයේ භාවිතා නොකල වැඩිපුර දත්ත අදංගු වේ.
sec-error-unsupported-elliptic-curve = සහය නොදක්වන ඉලිප්සීය වක්‍රය.
sec-error-unsupported-ec-point-form = සහය නොදක්වන ඉලිප්සීය වක්‍ර ලක්ෂ ආකාරය.
sec-error-unrecognized-oid = හඳුනා නොගත් වස්තූන් හඳුන්වනය.
sec-error-ocsp-invalid-signing-cert = OCSP ප්‍රතිචාරයේ අවලංගු OCSP අත්සන් කිරීමක්.
sec-error-revoked-certificate-crl = නිකුත් කරන්නාගේ සහතික අහෝසි කිරීමේ ලැයිස්තුවේ සහතිකය අහෝසි කර ඇත.
sec-error-revoked-certificate-ocsp = නිකුත් කරන්නාගේ OCSP ප්‍රතිවාරකය සහතිකය අහෝසි කළ බව වාර්තා කරයි.
sec-error-crl-invalid-version = නොදන්නා අනුවාද අංකයක් නිකුත් කරන්නාගේ සහතික අහෝසි කිරීමේ ලැයිස්තුවේ තිබේ.
sec-error-crl-v1-critical-extension = අවදානම් දිගුවක් නිකුත් කරන්නාගේ V1 සහතික අහෝසි කිරීමේ ලැයිස්තුවේ තිබේ.
sec-error-crl-unknown-critical-extension = නොදන්නා අවදානම් දිගුවක් නිකුත් කරන්නාගේ V2 සහතික අහෝසි කිරීමේ ලැයිස්තුවේ තිබේ.
sec-error-unknown-object-type = නොදන්නා වස්තු වර්ගයක් විශේෂණය කර ඇත.
sec-error-incompatible-pkcs11 = PKCS #11 driver violates the spec in an incompatible way.
sec-error-no-event = නව නාලිකා වැඩසටහනක් මෙම මොහොතේ ප්‍රයෝජනය සඳහා නොමැත.
sec-error-crl-already-exists = CRL දැනටමත් පවතී.
sec-error-not-initialized = NSS ආරම්භ කර නැත.
sec-error-token-not-logged-in = ක්‍රියාව PKCS#11 සංඥාව පිවිසී නොමැති නිසා අසාර්ථක විය.
sec-error-ocsp-responder-cert-invalid = වින්‍යාසගත කරන ලද OCSP ප්‍රතිචාරකයේ සහතිකය අවලංගුයි.
sec-error-ocsp-bad-signature = OCSP ප්‍රතිචාරයට අවලංගු අත්සනක් ඇත.
sec-error-out-of-search-limits = Cert validation search is out of search limits
sec-error-invalid-policy-mapping = Policy mapping contains anypolicy
sec-error-policy-validation-failed = Cert chain fails policy validation
sec-error-unknown-aia-location-type = Unknown location type in cert AIA extension
sec-error-bad-http-response = Server returned bad HTTP response
sec-error-bad-ldap-response = Server returned bad LDAP response
sec-error-failed-to-encode-data = Failed to encode data with ASN1 encoder
sec-error-bad-info-access-location = Bad information access location in cert extension
sec-error-libpkix-internal = Libpkix internal error occured during cert validation.
sec-error-pkcs11-general-error = A PKCS #11 module returned CKR_GENERAL_ERROR, indicating that an unrecoverable error has occurred.
sec-error-pkcs11-device-error = A PKCS #11 module returned CKR_DEVICE_ERROR, indicating that a problem has occurred with the token or slot.
sec-error-bad-info-access-method = Unknown information access method in certificate extension.
sec-error-crl-import-failed = Error attempting to import a CRL.
sec-error-expired-password = The password expired.
sec-error-locked-password = The password is locked.
sec-error-unknown-pkcs11-error = Unknown PKCS #11 error.
sec-error-bad-crl-dp-url = Invalid or unsupported URL in CRL distribution point name.
sec-error-cert-signature-algorithm-disabled = ආරක්ශාකාරී නොවූ නිසා අක්‍රීය කළ සන්කිරීම් ඇල්ගොරිතමයක් භාවිතයෙන් මෙම සහතිකය සන් කර ඇත.
mozilla-pkix-error-key-pinning-failure = මෙම සේවාදායකය යතුරු ඇමිනුමට (HPKP) සහය දක්වන නමුත් ඇමිණුම් කට්ටලයට තහවුරු කළ හැකි සහතික මාලාවක් සැකසිය නොහැකි විය යතුරු ඇමිනුම් උල්ලංඝනයන් අතික්‍රමණය කළ නොහැක.
mozilla-pkix-error-ca-cert-used-as-end-entity = මෙම සේවාදායකය සහතික බලධාරී හඳුනාගැනීමට මූලික නිරෝධය දිගුවක් සහිත සහතිකයක් භාවිත කරයි. නිසිපරිදි නිකුත් කළ සහතිකයකට, මෙය ගැටළුවක් නොවේ.
mozilla-pkix-error-inadequate-key-size = මෙම සේවාදායකය විසින් ආරක්ශාකාරී සබඳතාවක් ඇරඹීමට නොහැකි තරම් කුඩා යතුරු ප්‍රමාණයක් සහිත සහතිකයක් පිළිගැන්විනි.
mozilla-pkix-error-v1-cert-used-as-ca = X.509 අනුවාදය නැංගුරම් සේවාදායකය සහතිකය නිකුත් කිරීම සඳහා භාවිතා කරන ලදී , භාරයක් නොවන බව 1 සහතිකය. X.509 අනුවාදය 1 සහතික නොසලකා හරිනු ලැබ ඇති අතර, අනෙකුත් සහතික අත්සන් කිරීමට භාවිතා කල යුතු නොවේ.
