# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = খুলুন
    .accesskey = O
places-open-all-in-tabs =
    .label = ট্যাবে সব খুলুন
    .accesskey = O
places-add-bookmark =
    .label = বুকমার্ক যোগ করুন…
    .accesskey = B
places-view =
    .label = প্রদর্শন
    .accesskey = w
places-by-date =
    .label = তারিখ অনুসারে
    .accesskey = D
places-by-site =
    .label = সাইট অনুসারে
    .accesskey = S
places-by-most-visited =
    .label = সর্বাধিক প্রদর্শিত
    .accesskey = V
places-by-last-visited =
    .label = শেষবার প্রদর্শিত
    .accesskey = L
places-by-day-and-site =
    .label = তারিখ ও সাইট অনুসারে
    .accesskey = t
places-history-search =
    .placeholder = ইতিহাস খুঁজুন
places-history =
    .aria-label = ইতিহাস
places-bookmarks-search =
    .placeholder = বুকমার্ক অনুসন্ধান
places-delete-domain-data =
    .label = এই সাইটটি মনে রাখা হবে না
    .accesskey = F
places-sortby-name =
    .label = নাম অনুসারে সাজান
    .accesskey = r
places-library =
    .title = লাইব্রেরি
    .style = width:700px; height:500px;
places-library2 =
    .title = লাইব্রেরি
    .style = min-width:700px; min-height:500px;
places-organize-button =
    .label = সংগঠিতকরণ
    .tooltiptext = আপনার বুকমার্ক সংগঠিত করুন
    .accesskey = O
places-organize-button-mac =
    .label = সংগঠিতকরণ
    .tooltiptext = আপনার বুকমার্ক সংগঠিত করুন
places-file-close =
    .label = বন্ধ
    .accesskey = C
places-cmd-close =
    .key = w
places-view-button =
    .label = প্রদর্শন
    .tooltiptext = আপনার দৃশ্যপট পরিবর্তন করুন
    .accesskey = V
places-view-button-mac =
    .label = প্রদর্শন
    .tooltiptext = আপনার দৃশ্যপট পরিবর্তন করুন
places-view-menu-columns =
    .label = কলাম প্রদর্শন করা হবে
    .accesskey = C
places-view-menu-sort =
    .label = সাজানো
    .accesskey = S
places-view-sort-unsorted =
    .label = অবিন্যস্ত
    .accesskey = U
places-view-sort-ascending =
    .label = A থেকে Z ক্রমে
    .accesskey = A
places-view-sort-descending =
    .label = Z থেকে A ক্রমে
    .accesskey = Z
places-maintenance-button =
    .label = আমদানি ও ব্যাকআপ
    .tooltiptext = আপনার বুকমার্ক আমদানি করুন ও ব্যাকআপ রাখুন
    .accesskey = I
places-maintenance-button-mac =
    .label = আমদানি ও ব্যাকআপ
    .tooltiptext = আপনার বুকমার্ক আমদানি করুন ও ব্যাকআপ রাখুন
places-cmd-backup =
    .label = ব্যাকআপ…
    .accesskey = B
places-cmd-restore =
    .label = পুনরুদ্ধার
    .accesskey = R
places-cmd-restore-from-file =
    .label = ফাইল নির্বাচন…
    .accesskey = C
places-import-bookmarks-from-html =
    .label = HTML থেকে বুকমার্ক আমদানি করুন…
    .accesskey = I
places-export-bookmarks-to-html =
    .label = HTML এ বুকমার্ক এক্সপোর্ট করুন…
    .accesskey = E
places-import-other-browser =
    .label = অন্যান্য ব্রাউজার থেকে ডাটা ইম্পোর্ট করুন…
    .accesskey = A
places-view-sort-col-name =
    .label = নাম
places-view-sort-col-tags =
    .label = ট্যাগ
places-view-sort-col-url =
    .label = অবস্থান
places-view-sort-col-most-recent-visit =
    .label = সবচেয়ে সাম্প্রতিক পরিদর্শন
places-view-sort-col-visit-count =
    .label = পরিদর্শনের সংখ্যা
places-view-sort-col-date-added =
    .label = যোগ হয়েছে
places-view-sort-col-last-modified =
    .label = সর্বশেষ পরিবর্তন
places-cmd-find-key =
    .key = f
places-back-button =
    .tooltiptext = পূর্ববর্তী স্থানে ফিরে যাবে
places-forward-button =
    .tooltiptext = পরবর্তী অংশে যাও
places-details-pane-select-an-item-description = একটি আইটেম নির্বাচন করে তার বৈশিষ্ট্য প্রদর্শন ও পরিবর্তন
