# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = Отвори
    .accesskey = O
places-open-tab =
    .label = Отвори на новој картици
    .accesskey = О
places-open-in-tab =
    .label = Отвори на новој картици
    .accesskey = к
places-open-all-bookmarks =
    .label = Отвори све обележиваче
    .accesskey = б
places-open-all-in-tabs =
    .label = Отвори све на картицама
    .accesskey = О
places-open-window =
    .label = Отвори у новом прозору
    .accesskey = т
places-open-private-window =
    .label = Отвори у новом приватном прозору
    .accesskey = в
places-new-bookmark =
    .label = Нови обележивач…
    .accesskey = б
places-new-folder-contextmenu =
    .label = Нова фасцикла…
    .accesskey = ф
places-new-folder =
    .label = Нова фасцикла…
    .accesskey = ф
places-new-separator =
    .label = Нови разделник
    .accesskey = р
places-open-in-window =
    .label = Отвори у новом прозору
    .accesskey = п
places-open-in-private-window =
    .label = Отвори у новом приватном прозору
    .accesskey = т
places-add-bookmark =
    .label = Додај обележивач…
    .accesskey = б
places-add-folder-contextmenu =
    .label = Додај фасциклу…
    .accesskey = ф
places-add-folder =
    .label = Додај фасциклу…
    .accesskey = ф
places-add-separator =
    .label = Додај разделник
    .accesskey = р
places-view =
    .label = Приказ
    .accesskey = р
places-by-date =
    .label = По датуму
    .accesskey = D
places-by-site =
    .label = По сајту
    .accesskey = S
places-by-most-visited =
    .label = По посећености
    .accesskey = V
places-by-last-visited =
    .label = По последњој посети
    .accesskey = L
places-by-day-and-site =
    .label = По датуму и сајту
    .accesskey = t
places-history-search =
    .placeholder = Претражите историју
places-bookmarks-search =
    .placeholder = Претражите обележиваче
places-delete-domain-data =
    .label = Заборави на овај сајт
    .accesskey = F
places-sortby-name =
    .label = Сортирај по имену
    .accesskey = r
places-properties =
    .label = Својства
    .accesskey = С
# places-edit-bookmark and places-edit-generic will show one or the other and can have the same access key.
places-edit-bookmark =
    .label = Уреди обележивач…
    .accesskey = б
places-edit-generic =
    .label = Уреди…
    .accesskey = У
# Managed bookmarks are created by an administrator and cannot be changed by the user.
managed-bookmarks =
    .label = Управљај обележивачима
# This label is used when a managed bookmarks folder doesn't have a name.
managed-bookmarks-subfolder =
    .label = Подфасцикла
# This label is used for the "Other Bookmarks" folder that appears in the bookmarks toolbar.
other-bookmarks-folder =
    .label = Остали обележивачи
