# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = Veke
    .accesskey = V
places-open-all-in-tabs =
    .label = Hemûyan di Hilpekînan de Veke
    .accesskey = H
places-view =
    .label = Bibîne
    .accesskey = B
places-by-date =
    .label = Li gorî dîrokê
    .accesskey = d
places-by-site =
    .label = Malper
    .accesskey = M
places-by-most-visited =
    .label = Yên Herî Zêde Vebûne
    .accesskey = V
places-by-last-visited =
    .label = Yên di dawiyê de vebûne
    .accesskey = Y
places-by-day-and-site =
    .label = Li gorî dîrok û malperê
    .accesskey = L
places-history =
    .aria-label = Raborî
places-delete-domain-data =
    .label = Vê rûpelê ji bîr bike
    .accesskey = b
places-sortby-name =
    .label = li Gorî Navan Rêz Bike
    .accesskey = R
places-library =
    .title = Pirtûkxane
    .style = width:700px; height:500px;
places-view-sort-ascending =
    .label = A > Z Rêz Bike
    .accesskey = A
places-view-sort-descending =
    .label = Z > A Rêz Bike
    .accesskey = Z
places-view-sort-col-name =
    .label = Nav
places-view-sort-col-tags =
    .label = Etîket
places-view-sort-col-visit-count =
    .label = Hejmara Vebûnê
places-view-sort-col-date-added =
    .label = Têxistin
places-back-button =
    .tooltiptext = Here paş
places-forward-button =
    .tooltiptext = Here pêş
places-details-pane-select-an-item-description = Ji bo nîşandan û serrastkirina taybetmendiyan yekê hilbijêre
