# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title बुकमार्क


#define bookmarks_heading बुकमार्क


#define bookmarks_toolbarfolder बुकमार्क टुलबार फल्डार


#define bookmarks_toolbarfolder_description बुकमार्क टुलबारआव दिन्थिफुंनाय बुकमार्कखौ नायनो बेफोरखौ बे फल्डारजों दाजाबदेर


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/firefox/central/


#define getting_started जागाय गासिनो दं


# LOCALIZATION NOTE (firefox_heading):


# Firefox links folder name


#define firefox_heading मजिला फायारफक्स


# LOCALIZATION NOTE (firefox_help):


# link title for https://www.mozilla.org/en-US/firefox/help/


#define firefox_help मदद आरो टिउट'रियाल


# LOCALIZATION NOTE (firefox_customize):


# link title for https://www.mozilla.org/en-US/firefox/customize/


#define firefox_customize फायारफक्सखौ गावनि गोसोबादि खालाम


# LOCALIZATION NOTE (firefox_community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox_community थाफा


# LOCALIZATION NOTE (firefox_about):


# link title for https://www.mozilla.org/en-US/about/


#define firefox_about जोंनि सोमोन्दै


#unfilter emptyLines
