# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = შენახვა
dialogTitleAddBookmark = ახალი სანიშნი
dialogTitleAddMulti = ახალი სანიშნები
dialogTitleEdit = „%S“ – პარამეტრები
dialogTitleAddNewBookmark2 = სანიშნის დამატება
dialogTitleEditBookmark = „%S“ – ჩასწორება
dialogTitleEditBookmark2 = სანიშნის ჩასწორება
dialogTitleAddBookmarkFolder = სანიშნის საქაღალდის დამატება
dialogTitleEditBookmarkFolder = სანიშნის საქაღალდის ჩასწორება
bookmarkAllTabsDefault = [საქაღალდის სახელი]
newFolderDefault = ახალი საქაღალდე
newBookmarkDefault = ახალი სანიშნი
