# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Ndihmës Importimesh
import-from =
    { PLATFORM() ->
        [windows] Importo Mundësi, Faqerojtës, Historik, Fjalëkalime dhe të dhëna të tjera nga:
       *[other] Importo Parapëlqime, Faqerojtës, Historik, Fjalëkalime dhe të dhëna të tjera prej:
    }
import-from-bookmarks = Importo Faqerojtës nga:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-edge-legacy =
    .label = Microsoft Edge Legacy
    .accesskey = L
import-from-edge-beta =
    .label = Microsoft Edge Beta
    .accesskey = d
import-from-nothing =
    .label = Mos importo gjë
    .accesskey = J
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chrome-beta =
    .label = Chrome Beta
    .accesskey = B
import-from-chrome-dev =
    .label = Chrome Dev
    .accesskey = D
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = F
import-from-360se =
    .label = 360 Secure Browser
    .accesskey = 3
no-migration-sources = Nuk u gjetën dot programe që përmbajnë faqerojtës, historik apo fjalëkalime.
import-source =
    .label = Importo Rregullime dhe Të dhëna
import-items-title =
    .label = Objekte për Importim
import-items-description = Përzgjidhni cilët objekte të importohen:
import-migrating-title =
    .label = Po importohet…
import-migrating-description = Po importohen objektet vijuese…
import-select-profile-title =
    .label = Përzgjidhni Profil
import-select-profile-description = Është e mundur të importohen profilet vijues:
import-done-title =
    .label = Importim i Plotësuar
import-done-description = Objektet vijuese u importuan me sukses:
import-close-source-browser = Ju lutemi, para se të vazhdohet, sigurohuni që shfletuesi i përzgjedhur të jetë i mbyllur.
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = Nga { $source }
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-edge-beta = Microsoft Edge Beta
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chrome-beta = Google Chrome Beta
source-name-chrome-dev = Google Chrome Dev
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Secure Browser
imported-safari-reading-list = Listë Leximesh (Prej Safari-t)
imported-edge-reading-list = Listë Leximesh (Prej Edge-it)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Mundësi Interneti
    .value = Mundësi Interneti
browser-data-edge-1 =
    .label = Rregullime
    .value = Rregullime
browser-data-safari-1 =
    .label = Parapëlqime
    .value = Parapëlqime
browser-data-chrome-1 =
    .label = Parapëlqime
    .value = Parapëlqime
browser-data-canary-1 =
    .label = Parapëlqime
    .value = Parapëlqime
browser-data-360se-1 =
    .label = Parapëlqime
    .value = Parapëlqime
browser-data-ie-2 =
    .label = Cookies
    .value = Cookies
browser-data-edge-2 =
    .label = Cookies
    .value = Cookies
browser-data-safari-2 =
    .label = Cookies
    .value = Cookies
browser-data-chrome-2 =
    .label = Cookies
    .value = Cookies
browser-data-canary-2 =
    .label = Cookies
    .value = Cookies
browser-data-firefox-2 =
    .label = Cookies
    .value = Cookies
browser-data-360se-2 =
    .label = Cookies
    .value = Cookies
browser-data-ie-4 =
    .label = Historik Shfletimi
    .value = Historik Shfletimi
browser-data-edge-4 =
    .label = Historik Shfletimi
    .value = Historik Shfletimi
browser-data-safari-4 =
    .label = Historik Shfletimi
    .value = Historik Shfletimi
browser-data-chrome-4 =
    .label = Historik Shfletimi
    .value = Historik Shfletimi
browser-data-canary-4 =
    .label = Historik Shfletimi
    .value = Historik Shfletimi
browser-data-firefox-history-and-bookmarks-4 =
    .label = Historik Shfletimi dhe Faqerojtës
    .value = Historik Shfletimi dhe Faqerojtës
browser-data-360se-4 =
    .label = Historik Shfletimi
    .value = Historik Shfletimi
browser-data-ie-8 =
    .label = Historik Formularësh të Ruajtur
    .value = Historik Formularësh të Ruajtur
browser-data-edge-8 =
    .label = Historik Formularësh të Ruajtur
    .value = Historik Formularësh të Ruajtur
browser-data-safari-8 =
    .label = Historik Formularësh të Ruajtur
    .value = Historik Formularësh të Ruajtur
browser-data-chrome-8 =
    .label = Historik Formularësh të Ruajtur
    .value = Historik Formularësh të Ruajtur
browser-data-canary-8 =
    .label = Historik Formularësh të Ruajtur
    .value = Historik Formularësh të Ruajtur
browser-data-firefox-8 =
    .label = Historik Formularësh të Ruajtur
    .value = Historik Formularësh të Ruajtur
browser-data-360se-8 =
    .label = Historik Formularësh të Ruajtur
    .value = Historik Formularësh të Ruajtur
browser-data-ie-16 =
    .label = Fjalëkalime të Ruajtur
    .value = Fjalëkalime të Ruajtur
browser-data-edge-16 =
    .label = Fjalëkalime të Ruajtur
    .value = Fjalëkalime të Ruajtur
browser-data-safari-16 =
    .label = Fjalëkalime të Ruajtur
    .value = Fjalëkalime të Ruajtur
browser-data-chrome-16 =
    .label = Fjalëkalime të Ruajtur
    .value = Fjalëkalime të Ruajtur
browser-data-canary-16 =
    .label = Fjalëkalime të Ruajtur
    .value = Fjalëkalime të Ruajtur
browser-data-firefox-16 =
    .label = Fjalëkalime të Ruajtur
    .value = Fjalëkalime të Ruajtur
browser-data-360se-16 =
    .label = Fjalëkalime të Ruajtur
    .value = Fjalëkalime të Ruajtur
browser-data-ie-32 =
    .label = Më të pëlqyerit
    .value = Më të pëlqyerit
browser-data-edge-32 =
    .label = Më të pëlqyerit
    .value = Më të pëlqyerit
browser-data-safari-32 =
    .label = Faqerojtës
    .value = Faqerojtës
browser-data-chrome-32 =
    .label = Faqerojtës
    .value = Faqerojtës
browser-data-canary-32 =
    .label = Faqerojtës
    .value = Faqerojtës
browser-data-360se-32 =
    .label = Faqerojtës
    .value = Faqerojtës
browser-data-ie-64 =
    .label = Të dhëna të Tjera
    .value = Të dhëna të Tjera
browser-data-edge-64 =
    .label = Të dhëna të Tjera
    .value = Të dhëna të Tjera
browser-data-safari-64 =
    .label = Të dhëna të Tjera
    .value = Të dhëna të Tjera
browser-data-chrome-64 =
    .label = Të dhëna të Tjera
    .value = Të dhëna të Tjera
browser-data-canary-64 =
    .label = Të dhëna të Tjera
    .value = Të dhëna të Tjera
browser-data-firefox-other-64 =
    .label = Të dhëna të Tjera
    .value = Të dhëna të Tjera
browser-data-360se-64 =
    .label = Të dhëna të Tjera
    .value = Të dhëna të Tjera
browser-data-firefox-128 =
    .label = Dritare dhe Skeda
    .value = Dritare dhe Skeda
