# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

ssl-error-bad-client = Shërbyesi hasi të dhëna klienti të dëmtuara.
ssl-error-bad-server = Klienti hasi të dhëna shërbyesi të dëmtuara.
ssl-error-unsupported-certificate-type = Lloj i pambuluar dëshmie.
ssl-error-unsupported-version = Ana tjetër po përdor version të pambuluar protokoll sigurie.
ssl-error-ssl2-disabled = Ana tjetër mbulon vetëm versionin 2 për SSL-në, çka është lokalisht e çaktivizuar.
ssl-error-bad-mac-read = SSL-ja mori regjistrim me një Kod të pasaktë Mirëfilltësimi Mesazhi.
ssl-error-bad-block-padding = SSL-ja mori regjistrim me bllok mbushjeje të dëmtuar.
ssl-error-rx-record-too-long = SSL-ja mori regjistrim që tejkalonte gjatësinë më të madhe të lejueshme.
ssl-error-tx-record-too-long = SSL-ja bëri përpjekje të dërgonte regjistrim që tejkalonte gjatësinë më të madhe të lejueshme.
ssl-error-rx-malformed-hello-request = SSL-ja mori mesazh duarshtrëngimi Kërkesë për Hello të keqformuar.
ssl-error-rx-malformed-client-hello = SSL-ja mori mesazh duarshtrëngimi Klient Hello të keqformuar.
ssl-error-rx-malformed-server-hello = SSL-ja mori mesazh duarshtrëngimi Shërbyes Hello të keqformuar.
ssl-error-rx-malformed-certificate = SSL-ja mori mesazh duarshtrëngimi Dëshmi të keqformuar.
ssl-error-rx-malformed-cert-request = SSL-ja mori mesazh duarshtrëngimi Kërkesë Dëshmie të keqformuar.
ssl-error-rx-malformed-hello-done = SSL-ja mori mesazh duarshtrëngimi Hello Shërbyesi Kryer të keqformuar.
ssl-error-rx-malformed-cert-verify = SSL-ja mori mesazh duarshtrëngimi Vërtetim Dëshmie të keqformuar.
ssl-error-rx-malformed-finished = SSL-ja mori mesazh duarshtrëngimi Mbaruar të keqformuar.
ssl-error-rx-malformed-alert = SSL-ja mori regjistrim Alarmi të keqformuar.
ssl-error-rx-malformed-handshake = SSL-ja mori regjistrim Duarshtrëngimi të keqformuar.
ssl-error-rx-unexpected-hello-request = SSL-ja mori mesazh Kërkesë Hello të papritur.
ssl-error-rx-unexpected-client-hello = SSL-ja mori mesazh Hello Klienti të papritur.
ssl-error-rx-unexpected-server-hello = SSL-ja mori mesazh Hello Shërbyesi të papritur.
ssl-error-rx-unexpected-certificate = SSL-ja mori mesazh duarshtrëngimi Dëshmi të papritur.
ssl-error-rx-unexpected-cert-request = SSL-ja mori mesazh duarshtrëngimi Kërkesë Dëshmie të papritur.
ssl-error-rx-unexpected-hello-done = SSL-ja mori mesazh duarshtrëngimi Hello Shërbyesi Kryer të papritur.
ssl-error-rx-unexpected-cert-verify = SSL-ja mori mesazh duarshtrëngimi Vërtetim Dëshmie të papritur.
ssl-error-rx-unexpected-finished = SSL-ja mori mesazh duarshtrëngimi Mbaruar të papritur.
ssl-error-rx-unexpected-alert = SSL-ja mori regjistrim Alarmi të papritur.
ssl-error-rx-unexpected-handshake = SSL-ja mori regjistrim Duarshtrëngimi të papritur.
ssl-error-rx-unknown-record-type = SSL-ja mori regjistrim me lloj të panjohur të dhënash.
ssl-error-rx-unknown-handshake = SSL-ja mori mesazh duarshtrëngimi me lloj të panjohur mesazhi.
ssl-error-rx-unknown-alert = SSL-ja mori regjistrim alarmi me përshkrim të panjohur alarmi.
ssl-error-generate-random-failure = SSL-ja doli huq në një nga provat me prodhuesin e vet të numrave të rastësishëm.
ssl-error-md5-digest-failure = Funksioni "digest" MD5 dështoi.
ssl-error-sha-digest-failure = Funksioni "digest" SHA-1 dështoi.
ssl-error-mac-computation-failure = Përllogaritja MAC dështoi.
ssl-error-record-overflow-alert = Ana tjetër mori regjistrim SSL që qe më i gjatë se sa lejohet.
ssl-error-access-denied-alert = Ana tjetër mori dëshmi të vlefshme, por iu mohua hyrja.
ssl-error-user-canceled-alert = Përdoruesi i anës tjetër anuloi duarshtrëngimin.
ssl-error-server-cache-not-configured = Fshehtinë SSL shërbyesi e paformësuar dhe jo e aktivizuar për këtë "socket".
sec-error-io = Ndodhi një gabim I/O gjatë autorizimit të sigurisë.
sec-error-library-failure = dështim librarie sigurie.
sec-error-bad-data = librari sigurie: u morën të dhëna të dëmtuara.
sec-error-output-len = librari sigurie: gabim gjatësie daljeje.
sec-error-input-len = librarisë së sigurisë i ndodhi një gabim gjatësie hyrjeje.
sec-error-invalid-args = librari sigurie: argumente të pavlefshëm.
sec-error-invalid-algorithm = librari sigurie: algoritëm i pavlefshëm.
sec-error-invalid-ava = librari sigurie: AVA e pavlefshme.
sec-error-invalid-time = Varg kohe i formatuar pasaktësisht.
sec-error-bad-der = librari sigurie: mesazh i koduar si DER i formatuar pasaktësisht.
sec-error-bad-signature = Dëshmia e anës tjetër ka nënshkrim të pavlefshëm.
sec-error-expired-certificate = Dëshmia e anës tjetër ka skaduar.
sec-error-revoked-certificate = Dëshmia e anës tjetër është zhvleftësuar.
sec-error-unknown-issuer = Dëshmia e anës tjetër përmban lëshues të panjohur.
sec-error-bad-key = Kyçi publik i anës tjetër është i pavlefshëm.
sec-error-bad-password = Fjalëkalimi i sigurisë i dhënë është i pasaktë.
sec-error-no-nodelock = librari sigurie: pa "nodelock".
sec-error-bad-database = librari sigurie: bazë e dëmtuar të dhënash.
sec-error-no-memory = librari sigurie: dështim në sigurim kujtese.
sec-error-untrusted-issuer = Lëshuesi i dëshmisë së anës tjetër është shënuar nga përdoruesi si jo i besuar.
sec-error-untrusted-cert = Dëshmia e anës tjetër është shënuar nga përdoruesi si jo e besuar.
sec-error-duplicate-cert = Dëshmia ekziston tashmë në bazën tuaj të të dhënave.
sec-error-duplicate-cert-name = Emri i dëshmisë së shkarkuar përsëdyt një që gjendet një herë në bazën tuaj të të dhënave.
sec-error-adding-cert = Gabim gjatë shtimit të dëshmisë te baza e të dhënave.
sec-error-filing-key = Gabim në riskedimin e kyçit për këtë dëshmi.
sec-error-cert-valid = Kjo dëshmi është e vlefshme.
sec-error-cert-no-response = Librari Dëshmish: Pa Përgjigje
sec-error-extension-value-invalid = Vlera e zgjerimit të dëshmisë është e pavlefshme.
sec-error-ca-cert-invalid = Dëshmia e lëshuesit është e pavlefshme.
sec-error-path-len-constraint-invalid = Kufizimi i gjatësisë së shtegut të dëshmisë është i pavlefshëm.
sec-error-cert-usages-invalid = Fusha e përdorimeve të dëshmisë është e pavlefshme.
sec-internal-only = **Modul VETËM i brendshëm**
sec-error-unknown-critical-extension = Dëshmia përmban zgjerim kritik të panjohur.
sec-error-unsupported-keyalg = Algoritëm i pambuluar ose i panjohur.
xp-sec-fortezza-bad-pin = Pin i Pavlefshëm
sec-error-krl-invalid = KRL-ja e re ka format të pavlefshëm.
sec-error-need-random = librari sigurie: lyp të dhëna të rastësishme.
sec-error-read-only = librari sigurie: bazë të dhënash vetëm për lexim.
sec-error-cert-nickname-collision = Ka tashmë një dëshmi me të njëjtën nofkë.
sec-error-key-nickname-collision = Ka tashmë një kyç me të njëjtën nofkë.
sec-error-baggage-not-created = gabim gjatë krijimit të objektit bagazh
sec-error-exporting-certificates = Gabim gjatë përpjekjes për eksportim dëshmie.
sec-error-importing-certificates = Gabim gjatë përpjekjes për importim dëshmie.
sec-error-user-cancelled = Përdoruesi shtypi Cancel.
sec-error-pkcs12-duplicate-data = E paimportuar, tashmë në bazën e të dhënave.
sec-error-inadequate-key-usage = Përdorim i papërshtatshëm kyçi dëshmie për veprimin e provuar.
sec-error-bad-nickname = Nofkë dëshmie tashmë në përdorim.
sec-error-js-invalid-module-name = Emër moduli i pavlefshëm.
sec-error-js-invalid-dll = Shteg ose emër kartele moduli i pavlefshëm
sec-error-ocsp-bad-http-response = Shërbyesi OCSP ktheu të dhëna HTTP të papritura ose të pavlefshme.
sec-error-ocsp-malformed-request = Shërbyesi OCSP e gjeti kërkesën të dëmtuar ose të formuar pasaktësisht.
sec-error-ocsp-server-error = Shërbyesi OCSP pati një gabim të brendshëm.
sec-error-ocsp-request-needs-sig = Shërbyesi OCSP lyp nënshkrim për këtë kërkesë.
sec-error-ocsp-unauthorized-request = Shërbyesi OCSP e hodhi tej këtë kërkesë si të paautorizuar.
sec-error-ocsp-unknown-response-status = Shërbyesi OCSP u përgjigj me një gjendje të panjohshme.
sec-error-ocsp-not-enabled = Duhet të aktivizoni OCSP-në përpara se të përmbushni këtë veprim.
sec-error-ocsp-no-default-responder = Duhet të caktoni përgjigjësin parazgjedhje OCSP përpara kryerjes së këtij veprimi.
sec-error-ocsp-malformed-response = Përgjigja prej shërbyesit OCSP qe e dëmtuar ose e formuar pasaktësisht.
sec-error-unsupported-message-type = Lloji i CMS-së apo Mesazhit "PKCS #7" nuk mbulohet.
sec-error-extra-input = Mesazhi i koduar DER përmbante të dhëna ekstra të papërdorura.
sec-error-unrecognized-oid = Identifikues i Papranuar Objekti.
sec-error-ocsp-invalid-signing-cert = Dëshmi nënshkrimi OCSP e pavlefshme në përgjigje OCSP.
sec-error-revoked-certificate-crl = Sipas listës së shfuqizimit të dëshmive të lëshuesit dëshmia është e shfuqizuar.
sec-error-crl-invalid-version = Lista e Shfuqizimit të Dëshmive e lëshuesit ka numër versioni të panjohur.
sec-error-crl-v1-critical-extension = Lista V1 e Shfuqizimit të Dëshmive e lëshuesit ka zgjerim kritik.
sec-error-crl-unknown-critical-extension = Lista V2 e Shfuqizimit të Dëshmive e lëshuesit ka zgjerim kritik të panjohur.
sec-error-unknown-object-type = U tregua lloj i panjohur objekti.
sec-error-incompatible-pkcs11 = Përudhësi PKCS #11 dhunon përcaktimet në mënyrë të papërputhshme.
sec-error-ocsp-responder-cert-invalid = Dëshmia e formësuar për përgjigjësin OCSP është e pavlefshme.
sec-error-ocsp-bad-signature = Përgjigja OCSP ka nënshkrim të pavlefshëm.
