# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Inicis de sessió desats
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Copia l'URL
    .accesskey = C
launch-site-url-cmd =
    .label = Visita l'URL
    .accesskey = V
copy-username-cmd =
    .label = Copia el nom d'usuari
    .accesskey = u
edit-username-cmd =
    .label = Edita el nom d'usuari
    .accesskey = d
copy-password-cmd =
    .label = Copia la contrasenya
    .accesskey = C
edit-password-cmd =
    .label = Edita la contrasenya
    .accesskey = E
search-filter =
    .accesskey = C
    .placeholder = Cerca
column-heading-site =
    .label = Lloc
column-heading-username =
    .label = Nom d'usuari
column-heading-password =
    .label = Contrasenya
column-heading-time-created =
    .label = Primer ús
column-heading-time-last-used =
    .label = Darrer ús
column-heading-time-password-changed =
    .label = Darrer canvi
column-heading-times-used =
    .label = Nombre d'usos
remove =
    .label = Elimina
    .accesskey = E
import =
    .label = Importa…
    .accesskey = I
close-button =
    .label = Tanca
    .accesskey = c
show-passwords =
    .label = Mostra les contrasenyes
    .accesskey = M
hide-passwords =
    .label = Amaga les contrasenyes
    .accesskey = m
logins-description-all = S'han emmagatzemat les dades d'inici de sessió dels llocs següents en el vostre ordinador
logins-description-filtered = Les dades d'inici de sessió següents coincideixen amb la vostra cerca:
remove-all =
    .label = Elimina-ho tot
    .accesskey = t
remove-all-shown =
    .label = Elimina tot allò que es mostra
    .accesskey = t
remove-all-passwords-prompt = Esteu segur que voleu eliminar totes les contrasenyes?
remove-all-passwords-title = Eliminació de totes les contrasenyes
no-master-password-prompt = Esteu segur que voleu mostrar les vostres contrasenyes?
auto-fill-logins-and-passwords =
    .label = Emplena automàticament inicis de sessió i contrasenyes
