# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

third-party-page-title = තෙවන පාර්ශව ඒකක තොරතුරු
third-party-section-title = { -brand-short-name } හි තෙවන පාර්ශව ඒකක ලේඛනය
third-party-message-empty = තෙවන පාර්ශව ඒකක අනාවරණය නොවිණි.
third-party-message-no-duration = පටිගත කර නැත
third-party-detail-version = ගොනුවේ අනුවාදය
third-party-detail-app = යෙදුම
third-party-detail-publisher = ප්‍රකාශක
third-party-th-duration = පූරණය වීමේ පරාසය (මි.ත.)
third-party-th-status = තත්‍වය
third-party-tag-ime = IME
    .title = තෙවන පාර්ශ්ව IME භාවිතා කරන විට මෙම වර්ගයේ ඒකකයක් පූරණය වේ.
third-party-status-loaded = පූරණය විය
third-party-status-blocked = අවහිරයි
third-party-status-redirected = යළි හරවා යැවිණි
third-party-button-copy-to-clipboard = අමු දත්ත පසුරුපුවරුවට පිටපත් කරන්න
third-party-loading-data =
    .alt = පද්ධතියේ තොරතුරු පූරණය වෙමින්...
    .title = පද්ධතියේ තොරතුරු පූරණය වෙමින්...
third-party-button-reload = පද්ධතියේ තොරතුරු සමඟ යළි පූරණය කරන්න
    .title = පද්ධතියේ තොරතුරු සමඟ යළි පූරණය කරන්න
third-party-button-open =
    .title = ගොනුවේ ස්ථානය අරින්න…
third-party-button-to-block =
    .title = මෙම ඒකකය අවහිර කරන්න
    .aria-label = මෙම ඒකකය අවහිර කරන්න
third-party-button-to-unblock =
    .title = දැනට අවහිරයි. එය අනවහිර කිරීමට ඔබන්න.
    .aria-label = දැනට අවහිරයි. එය අනවහිර කිරීමට ඔබන්න.
third-party-button-to-unblock-disabled =
    .title = මෙම { -brand-short-name } ධාවනය සඳහා අවහිර ලැයිස්තුව අබල කර තිබුණත් දැනට අවහිර කර ඇති ලෙස සලකුණු කර ඇත. එය අනවහිර කිරීමට ඔබන්න.
    .aria-label = මෙම { -brand-short-name } ධාවනය සඳහා අවහිර ලැයිස්තුව අබල කර තිබුණත් දැනට අවහිර කර ඇති ලෙස සලකුණු කර ඇත. එය අනවහිර කිරීමට ඔබන්න.
third-party-button-to-block-module = මෙම ඒකකය අවහිර කරන්න
    .title = මෙම ඒකකය අවහිර කරන්න
    .aria-label = මෙම ඒකකය අවහිර කරන්න
third-party-button-to-unblock-module = මෙම ඒකකය අනවහිර කරන්න
    .title = දැනට අවහිරයි. එය අනවහිර කිරීමට ඔබන්න.
    .aria-label = දැනට අවහිරයි. එය අනවහිර කිරීමට ඔබන්න.
third-party-button-to-unblock-module-disabled = මෙම ඒකකය අනවහිර කරන්න (අවහිර ලැයිස්තුව දැනට අබලයි)
    .title = මෙම { -brand-short-name } ධාවනය සඳහා අවහිර ලැයිස්තුව අබල කර තිබුණත් දැනට අවහිර කර ඇති ලෙස සලකුණු කර ඇත. එය අනවහිර කිරීමට ඔබන්න.
    .aria-label = මෙම { -brand-short-name } ධාවනය සඳහා අවහිර ලැයිස්තුව අබල කර තිබුණත් දැනට අවහිර කර ඇති ලෙස සලකුණු කර ඇත. එය අනවහිර කිරීමට ඔබන්න.
third-party-button-expand =
    .title = සවිස්තරාත්මක තොරතුරු පෙන්වන්න
third-party-button-collapse =
    .title = සවිස්තරාත්මක තොරතුරු හකුළන්න
third-party-blocking-requires-restart = තෙවන පාර්ශ්ව ඒකකයක් අවහිර කිරීමට { -brand-short-name } යළි ඇරඹිය යුතුය.
third-party-should-restart-title = { -brand-short-name } යළි අරඹන්න
third-party-restart-now = යළි අරඹන්න
third-party-restart-later = පසුව යළි අරඹන්න
third-party-blocked-by-builtin =
    .title = { -brand-short-name } මගින් අවහිරයි
    .alt = { -brand-short-name } මගින් අවහිරයි
