# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = E batla { $host }…
network-connection-status-connected = E golagane le { $host }…
network-connection-status-sending-request = E romela kopo go { $host }…
network-connection-status-transferring-data = E fetisa tshedimosetso go tswa { $host }…
network-connection-status-connecting = E golagana le { $host }…
network-connection-status-read = Buisa { $host }
network-connection-status-wrote = Kwadile { $host }
network-connection-status-waiting = E emetse { $host }…
