# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Razrešujem naslov { $host }…
network-connection-status-connected = Povezava s stranjo { $host } vzpostavljena…
network-connection-status-sending-request = Pošiljanje zahtevka na { $host }…
network-connection-status-transferring-data = Prenašanje podatkov s strani { $host }…
network-connection-status-connecting = Povezovanje na stran { $host } …
network-connection-status-read = Prebrano { $host }
network-connection-status-wrote = Zapisano { $host }
network-connection-status-waiting = Čakanje na { $host }…
network-connection-status-looked-up = Najdeno { $host }…
network-connection-status-tls-handshake = Izvajanje rokovanja TLS s { $host } …
network-connection-status-tls-handshake-finished = Rokovanje TLS končano za { $host } …
