# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = Aquesta pàgina web s'està redirigint a una altra ubicació. Voleu reenviar-hi les dades del formulari que heu introduït?
# Directory listing strings
DirTitle = Índex de %1$S
DirGoUp = Cap a un directori de nivell superior
ShowHidden = Mostra els objectes ocults
DirColName = Nom
DirColSize = Mida
DirColMTime = Darrera modificació
DirFileLabel = Fitxer:
UnsafeUriBlocked = La funció de navegació segura ha blocat el recurs del lloc «%1$S».
CookieBlockedByPermission = S'ha blocat la sol·licitud d'accés a les galetes o a l'emmagatzematge en «%1$S» a causa del permís personalitzat de galetes.
CookieBlockedAll = S'ha blocat la sol·licitud d'accés a les galetes o a l'emmagatzematge en «%1$S» perquè s'estan blocant totes les sol·licituds d'accés a l'emmagatzematge.
# LOCALIZATION NOTE (CookieAllowedForOriginByStorageAccessAPI): %2$S and %1$S are URLs.
CookieAllowedForOriginByStorageAccessAPI = S'ha concedit accés a l'emmagatzematge per a l'origen «%2$S» en «%1$S».
# LOCALIZATION NOTE (CookieAllowedForOriginByHeuristic): %2$S and %1$S are URLs.
CookieAllowedForOriginByHeuristic = S'ha concedit accés automàticament a l'emmagatzematge per a l'origen «%2$S» en «%1$S».
# LOCALIZATION NOTE (CookieRejectedThirdParty): %1$S is the cookie response header.
CookieRejectedThirdParty = La galeta «%1$S» s'ha rebutjat perquè és de tercers.
