# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = کیا آپ مندرجہ ذیل مقاصد کے لیے "%S" پر بھروسا کرنا چاہتے ہیں؟
unnamedCA = مقتدرہ تصدیق نامہ(بے نام)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = برائے مہربانی وہ پاس ورڈ داخل کریں جو یہ تصدیق نامہ پشتارہ خفیہ کرنے میں استعمال کیا گیا تھا۔
# Page Info
pageInfo_NoEncryption = کنکشن خفیہ کردہ نہیں ہے
pageInfo_Privacy_None1 = ویب سائٹ %S اس صفحے کےلیے خفیہ کاری کی معاونت نہیں کرتی جو آپ نظارہ کر رہے ہیں۔
pageInfo_Privacy_None2 = انٹر نیٹ پر بغیر خفیہ کاری کے بھیجی گئی معلومات، راستے میں دیگر لوگوں سے دیکھی جا سکتے ہیں۔
pageInfo_Privacy_None4 = صفحہ آپ دیکھ رہے ہیں انٹرنیٹ پر منتقل کئے جانے سے پہلے مرموز نہیں کیا گیا تھا.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = کنکشن خفیہ کردہ (%1$S, %2$S bit keys, %3$S)
pageInfo_BrokenEncryption = شکستہ خفیہ کاری(%1$S, %2$S bit keys, %3$S)
pageInfo_Privacy_Encrypted1 = وہ صفحہ جو آپ نظارہ کر رہے ہیں، انٹر نیٹ پر منتقل ہونے سے پیلے خفیہ کردہ کیا گیا تھا۔
pageInfo_Privacy_Encrypted2 = خفیہ کاری کا یہ مشکل غیر مجاز لوگوں کے کمپیوٹرز کے درمیان سفر کی معلومات کو دیکھنے کے لئے کرتا ہے. ایسا نہیں ہے کہ اس کے نیٹ ورک بھر میں سفر کے طور پر کسی کو اس صفحے پڑھا اس لئے امکان نہیں ہے.
pageInfo_MixedContent = کنکشن جزوی خفیہ کردہ ہے
pageInfo_MixedContent2 = صفحے کے ٹکڑے جو آپ نظارہ کر رہے ہیں، انٹر نیٹ پر منتقل ہونے سے پہلے خفیہ کردہ نہیں ہوئے تھے۔
pageInfo_WeakCipher = آپکا کنکشن اس ویبسائٹ سے کمزور خفیہ کاری کا استعمال کرہا ہے اور یہ نجی نہیں ہے۔ دیگر لوگ آپ کی معلومات دیکھ سکتے ہیں یا ویب سائٹ کا رویہ بدل سکتے ہیں۔
# Token Manager
password_not_set = (سیٹ نہیں)
