# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Kutafuta { $host }…
network-connection-status-connected = Imeunganishwa kwa { $host }…
network-connection-status-sending-request = Kutuma ombi kwa { $host }…
network-connection-status-transferring-data = Kuhamisha data kutoka { $host }…
network-connection-status-connecting = Kuunganisha kwa { $host }…
network-connection-status-read = Soma { $host }
network-connection-status-wrote = Iliandika { $host }
network-connection-status-waiting = Kusubiri { $host }…
network-connection-status-looked-up = Kutafuta { $host }…
