#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Amitakhya Phukan &lt;aphukan@fedoraproject.org&gt;</em:contributor> <em:contributor>Nilamdyuti Goswami &lt;ngoswami@redhat.com&gt;</em:contributor>

#unfilter emptyLines
