# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title نشان زَد


#define bookmarks_heading نشان زَد


#define bookmarks_toolbarfolder بوک مارْک ٹول بار فولڈر


#define bookmarks_toolbarfolder_description جمع کْریو بوک مارْک یتھ فولڈرس تِم وچھنْہ باپت ڈیسپْلے گأمْت بوک مارْک ٹول بارس پیٹھ


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/firefox/central/


#define getting_started شروع كران


# LOCALIZATION NOTE (firefox_heading):


# Firefox links folder name


#define firefox_heading موزیلا فایرفاکس


# LOCALIZATION NOTE (firefox_help):


# link title for https://www.mozilla.org/en-US/firefox/help/


#define firefox_help مدد تْہ ٹیوٹوریل


# LOCALIZATION NOTE (firefox_customize):


# link title for https://www.mozilla.org/en-US/firefox/customize/


#define firefox_customize فایر فوکْس کْریو کسٹامایِز


# LOCALIZATION NOTE (firefox_community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox_community شأمل گْژھیو


# LOCALIZATION NOTE (firefox_about):


# link title for https://www.mozilla.org/en-US/about/


#define firefox_about اسِہ مُتلق


#unfilter emptyLines
