# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=Namestitev $ProductName$
Welcome_MessageWelcome=Dobrodošli v %s
Welcome_Message0=Namestili boste %s.
Welcome_Message1=Priporočamo vam, da končate vse ostale programe, preden nadaljujete z namestitvijo.
Welcome_Message2=Kliknite gumb Prekliči za izhod, nato pa pozaprite programe. Kliknite gumb Naprej za nadaljevanje.
Welcome_Message3=Kliknite gumb Naprej za nadaljevanje namestitve programa %s.

License_Title=Licenca programske opreme
License_SubTitle=Pogoji uporabe te programske opreme.
License_Message0=Prosimo, preberite naslednjo licenco. Uporabite drsnik, da boste lahko prebrali vso.
License_Accept=&Sprejmem pogoje licence
License_Decline=&NE sprejmem pogojev licence

Type_Title=Vrsta namestitve
Type_SubTitle=Izbira možnosti namestitve.
Type_Message0=Izberite želeno vrsto namestitve, nato pa kliknite gumb Naprej.

Standard_Short=&Standardna
Standard_Long=Thunderbird bo nameščen z najbolj pogosto izbranimi možnostmi.

Custom_Short=Po &meri
Custom_Long=Izberete lahko posamezne module za namestitev. Priporočeno za napredne uporabnike.

Select_Title=Izbira komponent
Select_SubTitle=Dodatne komponente, ki dodajo vrednost programu $ProductName$.
Select_Message0=Izberite želene dodatne komponente; zatem kliknite gumb Naprej.

Path_Title=Namestitveni imenik
Path_SubTitle=Vanj bo nameščen program $ProductName$.
Path_Message0=$ProductName$ bo nameščen v naslednji imenik:

Integration_Title=Namestitev bližnjic
Integration_SubTitle=Izdelava ikon programa
Integration_Message0=Izdelaj ikone za $ProductName$:

Integration_Desktop=na namizju
Integration_StartMenu=v ustreznem imeniku menija Start
Integration_QuickLaunch=v vrstico hitrega zagona

SelectFolder_Title=Namestitev $ProductName$ - Izbira programskega imenika
SelectFolder_Message0=Ikone programa bodo dodane v imenik, določen spodaj. Če želite, lahko izberete drug imenik. Kliknite gumb Naprej za nadaljevanje.

Advanced_Title=Namestitev $ProductName$ - Napredne nastavitve
Advanced_Message0=V kolikor vaša povezava do interneta zahteva strežnik proxy, vnesite ime strežnika in podatke o vratih. V nasprotnem primeru pustite ta polja prazna.

Install_Title=Povzetek
Install_SubTitle=Vse je nared za namestitev programa $ProductName$.
Install_MessageInstall=Naslednje komponente bodo zdaj nameščene:
Install_MessageDownload=Naslednje komponente bodo zdaj prenesene in nato nameščene:
Install_Message0=Kliknite gumb Naprej za nadaljevanje.

Downloading_Title=Prenašanje
Downloading_SubTitle=Prenašanje zahtevane komponente ...
Downloading_Blurb=Prenašanje datoteke, potrebne za namestitev programa $ProductName$.
Downloading_FileName=Trenutno poteka prenos komponente:
Downloading_Time=Preostanek:

Installing_Title=Nameščanje
Installing_SubTitle=Nameščam $ProductName$ ...
Installing_Blurb=Nameščam programske datoteke.
Installing_Status=Pripravljam datoteko:
Installing_Component=Trenutno nameščam:

Success_Title=Namestitev končana
Success_Header=Namestitev končana
Success_Message0=Uspešno ste namestili program %s.
Success_Message1=Kliknite gumb Končaj za zaključek namestitve.
Success_Launch=Poženi %s.

Check_Message=Prenos programa $ProductName$ je uspel. Program $ProductNameInternal$ morate zapreti, če želite nadaljevati z namestitvijo. Kliknite gumb V redu sa samodejen izhod in začetek namestitve.
Check_FullMessage=Program $ProductNameInternal$ morate zapreti, če želite nadaljevati z namestitvijo. Kliknite gumb V redu sa samodejen izhod in začetek namestitve.
Check_Wait=Zaključevanje programa $ProductNameInternal$. Prosim, počakajte ...

Component_XPCOM=Cross-Platform COM
Component_Mail=$ProductName$
Component_Offline=Podpora delu brez povezave
Component_Offline_Long=Doda podporo delu brez povezave
Component_RSS=Podpora RSS
Component_RSS_Long=Doda podporo RSS
Component_QFA=Program za poročanje o kakovosti
Component_QFA_Long=Za poročanje o sesutjih programa $ProductName$
