# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

print-setup =
    .title = Saife Ayarlaması
custom-prompt-title = Özel…
custom-prompt-prompt = Özel başlıq/ayaqlıq metnini kirsetiñiz
basic-tab =
    .label = Format & Seçenekler
advanced-tab =
    .label = Kenarlar & Başlıq/Ayaqlıq
format-group-label =
    .value = Format
orientation-label =
    .value = Yöneldirim:
portrait =
    .label = Portret
    .accesskey = P
landscape =
    .label = Manzara
    .accesskey = M
scale =
    .label = Miqyas:
    .accesskey = s
scale-percent =
    .value = %
shrink-to-fit =
    .label = Saife Kenişligine sığuv içün tarlat
    .accesskey = K
options-group-label =
    .value = Seçenekler
print-bg =
    .label = Arqazeminni Bastır (tüsler & suretler)
    .accesskey = A
margin-group-label-inches =
    .value = Kenarlar (düym)
margin-group-label-metric =
    .value = Kenarlar (millimetre)
margin-top =
    .value = Üst:
    .accesskey = s
margin-top-invisible =
    .value = Üst:
margin-bottom =
    .value = Tüp:
    .accesskey = T
margin-bottom-invisible =
    .value = Tüp:
margin-left =
    .value = Sol:
    .accesskey = l
margin-left-invisible =
    .value = Sol:
margin-right =
    .value = Oñ:
    .accesskey = O
margin-right-invisible =
    .value = Oñ:
header-footer-label =
    .value = Başlıqlar & Ayaqlıqlar
hf-left-label =
    .value = Sol:
hf-center-label =
    .value = Merkez:
hf-right-label =
    .value = Oñ:
header-left-tip =
    .tooltiptext = Sol başlıq
header-center-tip =
    .tooltiptext = Merkez başlıq
header-right-tip =
    .tooltiptext = Oñ başlıq
footer-left-tip =
    .tooltiptext = Sol ayaqlıq
footer-center-tip =
    .tooltiptext = Merkez ayaqlıq
footer-right-tip =
    .tooltiptext = Oñ ayaqlıq
hf-blank =
    .label = --boş--
hf-title =
    .label = Serleva
hf-url =
    .label = Adres
hf-date-and-time =
    .label = Tarih/Saat
hf-page =
    .label = Saife #
hf-page-and-total =
    .label = Saife #/#
hf-custom =
    .label = Özel…
print-preview-window =
    .title = Bastıruv Ögbaqışı
print-title =
    .value = Serleva:
print-preparing =
    .value = Azırlana…
print-progress =
    .value = Teraqqiyat:
print-window =
    .title = Bastırıla
print-complete =
    .value = Bastıruv Tamamlandı.
# Variables
# $percent (integer) - Number of printed percentage
print-percent =
    .value = { $percent }%
dialog-cancel-label = Vazgeç
dialog-close-label = Qapat
