# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host } खौ नायगासिनो दङ...
network-connection-status-connected = { $host } आव फोनांजाब खालामबाय...
network-connection-status-sending-request = { $host } आव खावलायनाय दैथाय हरगासिनो दङ...
network-connection-status-transferring-data = डाटाखौ { $host } निफ्राय गुबुन जायगायाव सोलाय होगासिनो दङ...
network-connection-status-connecting = { $host } आव फोनांजाब खालाम गासिनो दङ...
network-connection-status-read = { $host } फराय
network-connection-status-wrote = { $host } लिरदोंमोन
network-connection-status-waiting = { $host } नि थाखाय नेगासिनो दङ...
network-connection-status-looked-up = { $host } मोनबाय...
