# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=Встановлення $ProductName$
Welcome_MessageWelcome=Ласкаво просимо до %s!
Welcome_Message0=Ви збираєтесь встановити %s 2 Alpha 1.
Welcome_Message1=Рекомендуємо вийти з усіх програм Windows перед запуском цієї програми.
Welcome_Message2=Натисніть "Скасувати", щоб вийти з програми встановлення та закрити всі програми, що працюють. Натисніть "Далі", щоб продовжити процес встановлення.
Welcome_Message3=Натисніть "Далі", щоб продовжити встановлення %s 2 Alpha 1.

License_Title=Ліцензійна угода
License_SubTitle=Правила та умови використання цієї програми.
License_Message0=Будь ласка, прочитайте наступну ліцензійну угоду. Для перегляду документу далі використовуйте полосу прокрутки.
License_Accept=Я &приймаю умови Ліцензійної угоди
License_Decline=Я &НЕ приймаю умови Ліцензійної угоди

Type_Title=Тип установки
Type_SubTitle=Виберіть тип установки.
Type_Message0=Виберіть тип установки, котру хочете виконати, і натисніть "Далі".

Standard_Short=&Звичайна
Standard_Long=$ProductName$ буде встановлено в типовій комплектації.

Custom_Short=&Вибіркова
Custom_Long=Ви можете самостійно обрати компоненти для встановлення. Рекомендовано для досвіченим користувачам.

Select_Title=Вибір компонентів
Select_SubTitle=Додаткові корисні компоненти $ProductName$.
Select_Message0=Оберіть додаткові компоненти для встановлення, потім натисніть кнопку "Далі".

Path_Title=Вибір теки
Path_SubTitle=Виберіть теку куди буде встановлено $ProductName$.
Path_Message0=$ProductName$ буде встановлено в наступну теку:

Integration_Title=Створення ярликів
Integration_SubTitle=Створення значків для програми
Integration_Message0=Створити ярлики для $ProductShortName$:

Integration_Desktop=На стільниці
Integration_StartMenu=У меню "Пуск"
Integration_QuickLaunch=У панелі швидкого запуску

SelectFolder_Title=Встановлення $ProductName$ — вибір теки для меню "Програми"
SelectFolder_Message0=Програма встановлення додасть ярлики програми у вказану нижче теку меню "Програми". Ви можете вказати нову назву чи вибрати одну зі списку вже наявних. Для продовження натисніть "Далі".

Advanced_Title=Встановлення $ProductName$ — Додаткові налаштування
Advanced_Message0=Якщо для з’єднання з інтернетом Вам потрібен проксі-сервер, введіть його ім’я та порт. Якщо для з’єднання з інтернетом вам проксі-сервер не потрібен — лишіть ці поля пустими.

Install_Title=Початок встановлення
Install_SubTitle=Все готово до початку встановлення $ProductName$.
Install_MessageInstall=Програма встановлення незабаром встановить наступні компоненти:
Install_MessageDownload=Програма встановлення зараз завантажить та встановить наступні компоненти:
Install_Message0=Натисніть "Далі" для продовження.

Downloading_Title=Триває завантаження
Downloading_SubTitle=Триває завантаження необхідних компонентів…
Downloading_Blurb=Програма встановлення завантажує необхідні для встановлення $ProductName$ файли.
Downloading_FileName=Зараз завантажується:
Downloading_Time=Лишилось часу:

Installing_Title=Триває встановлення
Installing_SubTitle=Триває встановлення $ProductName$…
Installing_Blurb=Встановлюються файли програми. 
Installing_Status=Підготовка файлу:
Installing_Component=Зараз встановлюється:

Success_Title=Встановлення завершено
Success_Header=Встановлення завершено
Success_Message0=%s був успішно встановлений.
Success_Message1=Натисніть "Гаразд" щоб завершити встановлення.
Success_Launch=Запустити %s.

Check_Message=Завантаження $ProductName$ успішно завершено. Програму $ProductNameInternal$ слід закрити, щоб продовжити встановлення. Натисніть "OK" для автоматичного виходу з $ProductNameInternal$ та початку встановлення.
Check_FullMessage=Програма $ProductNameInternal$ має бути закрита для продовження встановлення. Натисніть "OK" для автоматичного виходу з $ProductNameInternal$ та початку встановлення.
Check_Wait=Завершення роботи $ProductNameInternal$. Будь ласка зачекайте…

Component_XPCOM=Крос-платформенний COM
Component_Mail=$ProductName$
Component_Offline=Довідка $ProductName$
Component_Offline_Long=Додає онлайн-підтримку до $ProductName$.
Component_RSS=Підтримка RSS
Component_RSS_Long=Додає підтримку RSS до $ProductName$.
Component_QFA=Quality Feedback Agent
Component_QFA_Long=Відправляє звіти про збої в $ProductName$
