# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Inget svar
openFile = Öppna fil
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Sök på %1$S efter “%2$S”
contextMenuSearch.accesskey = S
contextMenuPrivateSearch = Sök i ett privat fönster
contextMenuPrivateSearch.accesskey = S
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Sök med %S i ett privat fönster
contextMenuPrivateSearchOtherEngine.accesskey = S
bookmarkAllTabsDefault = [Mappnamn]
unsignedAddonsDisabled.message = Ett eller flera installerade tillägg inte kan verifieras och har inaktiverats.
unsignedAddonsDisabled.learnMore.label = Lär dig mer
unsignedAddonsDisabled.learnMore.accesskey = L
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Senaste åtkomst %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = %S:// länkar
crashedpluginsMessage.title = Insticksmodulen %S har kraschat.
crashedpluginsMessage.reloadButton.label = Hämta om sida\u0020
crashedpluginsMessage.reloadButton.accesskey = H
crashedpluginsMessage.submitButton.label = Skicka en kraschrapport\u0020
crashedpluginsMessage.submitButton.accesskey = S
crashedpluginsMessage.learnMore = Läs mer…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Menade du att gå till %S?
keywordURIFixup.goTo = Ja, ta mig till %S
keywordURIFixup.goTo.accesskey = J
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Uppdatera till %S\u0020
update.downloadAndInstallButton.accesskey = U
menuOpenAllInTabs.label = Öppna alla i flikar
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Ladda om sidan
tabHistory.goBack = Gå bakåt till denna sida
tabHistory.goForward = Gå framåt till denna sida
# URL Bar
pasteAndGo.label = Klistra in och öppna
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Ladda om aktuell sida (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Sluta ladda denna sida (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Återställ zoomnivå (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Växla läsvy (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, Återställ zoomnivån
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Visa dina bokmärken (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Visa förloppet för pågående filhämtningar (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Öppna ett nytt fönster (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Öppna en ny flik (%S)
newTabContainer.tooltip = Öppna en ny flik (%S)\nTryck och håll kvar för att öppna en ny innehållsflik
newTabAlwaysContainer.tooltip = Välj behållare för att öppna en ny flik
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Tillåt %S att använda dina HTML5-kanvasbilddata?
canvas.siteprompt2.warning = Detta kan användas för att unikt identifiera din dator.
canvas.block = Blockera
canvas.block.accesskey = B
canvas.allow2 = Tillåt
canvas.allow2.accesskey = T
canvas.remember2 = Kom ihåg detta beslut
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Verifierat av: %S
identity.identified.verified_by_you = Du har lagt till ett säkerhetsundantag för den här platsen.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Certifikat utfärdat till: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Inte säker
identity.notSecure.tooltip = Anslutningen är inte säker
identity.extension.label = Tillägg (%S)
identity.extension.tooltip = Laddad av tillägg: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Zooma ut (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Återställ zoomnivå (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Zooma in (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Klipp ut (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Kopiera (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Klistra in (%S)
geolocation.allow = Tillåt
geolocation.allow.accesskey = T
geolocation.block = Blockera
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Detta öppnar systemets platsinställningar. Vänligen ge platsbehörighet till %S.
geolocation.shareWithSite4 = Tillåt %S att använda din plats?
geolocation.shareWithFile4 = Tillåt den här lokala filen att använda din plats?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Tillåt %1$S att ge %2$S behörighet att använda din plats?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Bevilja %S platsbehörighet i systeminställningarna.
geolocation.systemSettingsTitle = Väntar på platsbehörighet
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Systemet kommer att be dig att bevilja denna behörighet till %S.
geolocation.remember = Kom ihåg detta beslut
# Virtual Reality Device UI
xr.allow2 = Tillåt
xr.allow2.accesskey = T
xr.block = Blockera
xr.block.accesskey = B
xr.shareWithSite4 = Ge %S åtkomst till virtual reality-enheter? Detta kan avslöja känslig information.
xr.shareWithFile4 = Ge den här lokala filen åtkomst till virtual reality-enheter? Detta kan avslöja känslig information.
xr.remember = Kom ihåg detta val
# Persistent storage UI
persistentStorage.allow = Tillåt
persistentStorage.allow.accesskey = T
persistentStorage.block.label = Blockera
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Tillåta %S att lagra data i beständig lagring?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Tillåt
webNotifications.allow2.accesskey = T
webNotifications.notNow = Inte nu
webNotifications.notNow.accesskey = n
webNotifications.never = Tillåt aldrig
webNotifications.never.accesskey = d
webNotifications.alwaysBlock = Blockera alltid
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = Blockera
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Tillåta %S att skicka aviseringar?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S vill komma åt andra appar och tjänster på den här enheten.
localhost.remember2 = Kom ihåg mitt val för den här sidan
localhost.allowlabel = Tillåt
localhost.blocklabel = Blockera
localhost.allow.accesskey = T
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S vill komma åt appar och tjänster på enheter anslutna till ditt lokala nätverk.
localNetwork.remember2 = Kom ihåg mitt val för den här sidan
localNetwork.allowLabel = Tillåt
localNetwork.allow.accesskey = T
localNetwork.blockLabel = Blockera
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Ta mig härifrån!
safebrowsing.getMeOutOfHereButton.accessKey = T
safebrowsing.deceptiveSite = Vilseledande webbplats!
safebrowsing.notADeceptiveSiteButton.label = Detta är inte en vilseledande webbplats…
safebrowsing.notADeceptiveSiteButton.accessKey = v
safebrowsing.reportedAttackSite = Rapporterat skadlig plats!
safebrowsing.notAnAttackButton.label = Detta är inte en angreppswebbplats…
safebrowsing.notAnAttackButton.accessKey = e
safebrowsing.reportedUnwantedSite = Rapporterad webbplats med oönskad programvara!
safebrowsing.reportedHarmfulSite = Rapporterad skadlig webbplats!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Sök på %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Starta om %S i felsökningsläge?
troubleshootModeRestartPromptMessage = Dina tillägg, teman och anpassade inställningar inaktiveras tillfälligt.
troubleshootModeRestartButton = Starta om
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Den här sidan slöar ner %1$S. Stoppa den här sidan för att snabba upp din webbläsare.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = En webbsida slöar ner %1$S. Stoppa sidan för att snabba upp din webbläsare.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = "%1$S" slöar ner %2$S. Stoppa sidan för att snabba upp din webbläsare.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = "%1$S" slöar ner %2$S. För att snabba upp din webbläsare, stoppa tillägget.
processHang.add-on.learn-more.text = Läs mer
processHang.button_stop2.label = Stoppa
processHang.button_stop2.accessKey = S
processHang.button_debug.label = Felsök skript
processHang.button_debug.accessKey = A
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Visa fönstret i helskärm (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Flytta sidofält till vänster
sidebar.moveToRight = Flytta sidofält till höger
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Du måste aktivera DRM för att spela upp ljud eller video på den här sidan.
emeNotifications.drmContentDisabled.button.label = Aktivera DRM
emeNotifications.drmContentDisabled.button.accesskey = A
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S installerar komponenter som krävs för att spela ljud eller video på denna sida. Försök igen senare.
emeNotifications.unknownDRMSoftware = Okänd
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Anpassa %S
decoder.noCodecs.button = Lär dig hur
decoder.noCodecs.accesskey = L
decoder.noCodecsLinux.message = För att spela upp video, kan du behöva installera nödvändiga video-codec.
decoder.noHWAcceleration.message = För att förbättra videokvaliteten, kan du behöva installera Microsofts Media Feature Pack.
decoder.noPulseAudio.message = Att spela upp ljud, kan du behöva installera PulseAudio programvara som krävs.
decoder.unsupportedLibavcodec.message = libavcodec kan vara sårbar eller stöds inte och bör uppdateras för att spela upp video.
decoder.decodeError.message = Ett fel uppstod vid avkodning en mediaresurs.
decoder.decodeError.button = Rapportera webbplatsproblem
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = Ett återhämtningsbart fel uppstod vid avkodning en mediaresurs.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Du måste logga in på nätverket innan du kan ansluta till Internet.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Öppna inloggningssida för nätverk
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Rättigheter för %S
permissions.remove.tooltip = Rensa denna behörighet och fråga igen
permissions.fullscreen.promptCanceled = Avbröt väntande behörighetsförfrågningar: behörighetsförfrågningar bör inte utfärdas innan du går in i DOM-helskärm.
permissions.fullscreen.fullScreenCanceled = Avlutade DOM-helskärm: behörighetsbegäranden ska inte utfärdas när du är i DOM-helskärm.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bitars
aboutDialog.architecture.thirtyTwoBit = 32-bitars
midi.allow.label = Tillåt
midi.allow.accesskey = T
midi.block.label = Blockera
midi.block.accesskey = B
midi.remember = Kom ihåg detta beslut
midi.shareWithFile = Tillåt den här lokala filen att komma åt dina MIDI-enheter?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Tillåt %S att komma åt dina MIDI-enheter?
midi.shareSysexWithFile = Tillåt den här lokala filen att komma åt dina MIDI-enheter och skicka/ta emot SysEx-meddelanden?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Tillåt %S att komma åt dina MIDI-enheter och skicka/ta emot SysEx-meddelanden?
serial.allow.label = Tillåt
serial.allow.accesskey = T
serial.block.label = Blockera
serial.block.accesskey = B
serial.shareWithFile = Tillåta den här lokala filen åtkomst till dina serieportar?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Tillåta %S åtkomst till dina serieportar?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Tillbaka
storageAccess1.Allow.label = Tillåt
storageAccess1.Allow.accesskey = T
storageAccess1.DontAllow.label = Blockera
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Tillåt %1$S att använda sina kakor på %2$S?
storageAccess1.hintText = Du kan blockera åtkomst om det inte är klart varför %1$S behöver denna information.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Sök på webben efter "%S"
