# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Notice: If you're updating this list, you should also
###         update the list in mozIntl.js.

region-name-ag = Antiga d Barbuda
region-name-ai = Angiya
region-name-al = Albaniya
region-name-am = Arminya
region-name-ao = Angula
region-name-ar = Aṛjuntin
region-name-at = Ustriya
region-name-aw = Aruba
region-name-az = Azerbiǧan
region-name-be = Biljik
region-name-bi = Burundi
region-name-bj = Binin
region-name-bl = San Baṛtilimi
region-name-bn = Brunay
region-name-bo = Bulivya
region-name-bq = Buniṛ, Sint Usṭasius, d Saba
region-name-br = Brizil
region-name-bs = Bahamaṣ
region-name-bt = Buṭan
region-name-bw = Butswana
region-name-by = Bilarus
region-name-bz = Biliz
region-name-ca = Kanada
region-name-cc = Tigzirin n kuku
region-name-cd = Kungu-Kincaṣa
region-name-cg = Kungu-Bṛazavil
region-name-ch = Swis
region-name-ck = Tigzirin n Kuk
region-name-cl = Cili
region-name-cm = Kamirun
region-name-cn = Cin
region-name-co = Kulumbi
region-name-cp = Tigzirt n Klipirṭun
region-name-cr = Kusta Rika
region-name-cu = Kuba
region-name-cv = Kap Vir
region-name-cx = Tigzrin n Kristmaṣ
region-name-cy = Cipr
region-name-dj = Ǧibuti
region-name-dk = Danmaṛk
region-name-dm = Duminik
region-name-dz = Zzayer
region-name-ee = Istunya
region-name-eg = Maṣer
region-name-er = Iritirya
region-name-es = Spanya
region-name-et = Ityupya
region-name-fj = Fiǧi
region-name-fk = Tigzirin n Malwin
region-name-fm = Mikrunizya
region-name-fr = Fṛansa
region-name-ga = Gabun
region-name-gd = Grinada
region-name-ge = Jyuṛjya
region-name-gm = Gambya
region-name-gn = Ginya
region-name-gp = Gwadlup
region-name-gq = Ginya Tasebgast
region-name-gr = Grig
region-name-gt = Gwatimala
region-name-gu = Gwam
region-name-gw = Ginya bisaw
region-name-hm = Tigzirin n Hird d Tigzirin n MakDunald
region-name-hn = Hunduṛas
region-name-ht = Hayti
region-name-id = Indunizya
region-name-ie = Iṛland
region-name-il = Izrayil
region-name-im = Tigzirt n Man
region-name-in = Hend
region-name-io = Timura n ugaraw ahendi abṛitani
region-name-iq = Ɛiṛaq
region-name-ir = Iṛan
region-name-is = Island
region-name-je = Jiṛzi
region-name-jo = Juṛdan
region-name-jp = Japun
region-name-ke = Kinya
region-name-ki = Kiribati
region-name-km = Kumuṛ
region-name-kn = San-Kits-d-Nivis
region-name-kp = Kuriya n ugafa
region-name-kr = Kuriya n uwezlu
region-name-kw = Kuwayt
region-name-ky = Tigzirin n Kayman
region-name-kz = Kazaxistan
region-name-la = Lawus
region-name-lc = Sant Lusi
region-name-li = Lictencṭayn
region-name-lk = Sri Lanka
region-name-ls = Lizuṭu
region-name-lt = Litwanya
region-name-lv = Litunya
region-name-ly = Libya
region-name-ma = Meṛṛuk
region-name-mc = Munaku
region-name-md = Muldavya
region-name-me = Muntinigru
region-name-mf = San Maṛtan
region-name-mg = Madagaskaṛ
region-name-mk = Masidunya
region-name-ml = Mali
region-name-mm = Burma
region-name-mn = Mungulya
region-name-mo = Makawu
region-name-mq = Maṛtinik
region-name-mt = Malṭ
region-name-mu = Muris
region-name-mv = Maldiv
region-name-mw = Malawi
region-name-mx = Meksik
region-name-my = Malizya
region-name-mz = Muzumbik
region-name-na = Namibya
region-name-nf = Tigzirtn n Nuṛfulk
region-name-ng = Nijirya
region-name-ni = Nikaṛagwa
region-name-nl = Huland
region-name-no = Nuṛvij
region-name-np = Nipal
region-name-nr = Nuṛu
region-name-nu = Niyu
region-name-om = Ɛuman
region-name-pa = Panama
region-name-pe = Piru
region-name-ph = Filipin
region-name-pk = Pakistan
region-name-pm = San-Pyir-d-Miklun
region-name-pn = Tigzirin n Pitkaṛn
region-name-pr = Puṛṭu Riku
region-name-pt = Purtugal
region-name-qm = Tigzirin n Midway
region-name-qs = Bassas da India
region-name-qu = Juan de Nova Island
region-name-qw = Tigzirin n Wayk
region-name-qx = Tigzirin Gluṛiyuzu
region-name-qz = Akṛutiri
region-name-re = Tigzirt n Riyunyun
region-name-ro = Ṛumanya
region-name-rs = Ṣirbya
region-name-ru = Rrus
region-name-rw = Ṛwanda
region-name-sc = Sicil
region-name-sd = Sudan
region-name-se = Swid
region-name-sg = Singapur
region-name-sh = Saint Helena, Ascension, and Tristan da Cunha
region-name-si = Sluvinya
region-name-sk = Sluvakya
region-name-sl = Sirra Lyun
region-name-sm = San Maṛinu
region-name-sn = Sinigal
region-name-so = Ṣumal
region-name-sr = Surinam
region-name-st = Ṣaw Tumi d Prinsip
region-name-sv = Salvaduṛ
region-name-sx = San Maṛtan
region-name-sy = Surya
region-name-td = Čad
region-name-tf = Timura n Uwezlu n Fṛansa d Anṭaṛktik
region-name-tg = Ṭugu
region-name-th = Ṭayland
region-name-tj = Tajikistan
region-name-tk = Ṭuklu
region-name-tl = Timur n usamar
region-name-tn = Tunes
region-name-tr = Ṭurk
region-name-tw = Ṭaywan
region-name-tz = Tanẓanya
region-name-ug = Uganda
region-name-us = Marikan
region-name-uy = Urugway
region-name-vc = San-Vansun-d-grinadin
region-name-vg = Virgin Islands, British
region-name-vi = Virgin Islands, U.S.
region-name-vn = Vyiṭnam
region-name-ws = Samwa
region-name-xa = Tigzirin n Acmuṛ d Kaṛtyi
region-name-xb = Tigzirt n Baker
region-name-xc = Tigzirin n Kuṛal Si
region-name-xd = Dhekelia
region-name-xe = Tigzirt n Urupa
region-name-xg = Gaza Strip
region-name-xh = Tigzirt n Hawland
region-name-xj = Jan Mayen
region-name-xk = Kuṣuvu
region-name-xl = Tigzirt n Palmira
region-name-xm = Kingman Reef
region-name-xp = Tigzirin n Parasel
region-name-xq = Tigzirt Jarvis
region-name-xr = Svalbard
region-name-xs = Tigzirin n Spratly
region-name-xt = Tigzirin tṛumlin
region-name-xu = Tigzirt n Jhonston
region-name-xv = Tigzirt n Navaṣa
region-name-xw = Tama n usamar
region-name-ye = Yaman
region-name-yt = Mayuṭ
region-name-za = Tafriqt n Wenzul
region-name-zm = Ẓambya
region-name-zw = Zimbabwi
