#filter emptyLines
#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>San James</em:contributor> <em:contributor>War Child Holland-Uganda</em:contributor><em:contributor>Acuma George Patric</em:contributor> <em:contributor>Keneth Ogwal</em:contributor><em:contributor>Dan Jasper Okello</em:contributor> <em:contributor>June</em:contributor>

#unfilter emptyLines