#filter emptyLines

#define MOZ_LANGPACK_CREATOR मदन पुरस्कार पुस्तकालय, www.mpp.org.np

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>बसन्त कृष्ण श्रेष्ठ</em:contributor><em:contributor>basanta.shrestha@gmail.com</em:contributor> <em:contributor>info@mpp.org.np</em:contributor>

#unfilter emptyLines
