# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Ҷустуҷӯи { $host }…
network-connection-status-connected = Ба { $host } пайваст шудааст…
network-connection-status-sending-request = Фиристодани дархост ба { $host }…
network-connection-status-transferring-data = Интиқоли маълумот аз { $host }…
network-connection-status-connecting = Ба { $host } пайваст шуда истодааст…
network-connection-status-read = { $host } хонда шудааст
network-connection-status-wrote = { $host } навишта шудааст
network-connection-status-waiting = Дар интизори ҷавоб аз { $host }…
network-connection-status-looked-up = { $host } ёфт шуд…
network-connection-status-tls-handshake = Иҷрокунии дастфишории TLS бо { $host }…
network-connection-status-tls-handshake-finished = Дастфишории TLS бо { $host } анҷом ёфт…
