# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Spasi
dialogTitleAddBookmark = Add Bookmark
dialogTitleAddMulti = Bookmark All Tabs
dialogTitleEdit = Osobine za "%S"
dialogTitleAddNewBookmark2 = Dodaj zabilješku
dialogTitleEditBookmark = Uredi “%S”
dialogTitleEditBookmark2 = Uredi zabilješku
dialogTitleAddBookmarkFolder = Dodaj folder sa zabilješkom
dialogTitleEditBookmarkFolder = Uredi folder sa zabilješkom
bookmarkAllTabsDefault = [Naziv direktorija]
newFolderDefault = Novi direktorij
newBookmarkDefault = Nova Zabilješka
