# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

print-setup =
    .title = Sayfa Yapısı
basic-tab =
    .label = Biçim ve seçenekler
format-group-label =
    .value = Biçim
scale-percent =
    .value = %
shrink-to-fit =
    .label = Sayfa boyutuna sığdır
    .accesskey = d
options-group-label =
    .value = Seçenekler
print-bg =
    .label = Arka planı yazdır (renkler ve resimler)
    .accesskey = k
margin-group-label-inches =
    .value = Kenarlar (inç)
margin-group-label-metric =
    .value = Kenarlar (milimetre)
margin-top =
    .value = Üst:
    .accesskey = t
margin-top-invisible =
    .value = Üst:
margin-bottom =
    .value = Alt:
    .accesskey = A
margin-bottom-invisible =
    .value = Alt:
margin-left =
    .value = Sol:
    .accesskey = l
margin-left-invisible =
    .value = Sol:
margin-right =
    .value = Sağ:
    .accesskey = S
margin-right-invisible =
    .value = Sağ:
hf-left-label =
    .value = Sol:
hf-center-label =
    .value = Merkez:
hf-right-label =
    .value = Sağ:
hf-blank =
    .label = --boş--
hf-title =
    .label = Başlık
hf-url =
    .label = Adres
hf-date-and-time =
    .label = Tarih/Saat
hf-page =
    .label = Sayfa #
print-preview-window =
    .title = Yazdırma Ön İzleme
print-title =
    .value = Başlık:
print-preparing =
    .value = Hazırlanıyor…
print-progress =
    .value = İlerleme:
print-window =
    .title = Yazdırılıyor
print-complete =
    .value = Yazdırma tamamlandı.
# Variables
# $percent (integer) - Number of printed percentage
print-percent =
    .value = %{ $percent }
dialog-cancel-label = Vazgeç
dialog-close-label = Kapat
