# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = محفوظ شدہ لاگ ان
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = URL نقل کریں
    .accesskey = Y
launch-site-url-cmd =
    .label = URL ملاحظہ کریں
    .accesskey = V
copy-username-cmd =
    .label = صارف نام نقل کریں
    .accesskey = ص
edit-username-cmd =
    .label = صارف کا نام تبدیل کریں
    .accesskey = ب
copy-password-cmd =
    .label = پاس ورڈ نقل کریں
    .accesskey = ن
edit-password-cmd =
    .label = پاس ورڈ تدوین کریں
    .accesskey = ت
search-filter =
    .accesskey = ت
    .placeholder = تلاش کریں
column-heading-site =
    .label = سائٹ
column-heading-username =
    .label = نام صارف
column-heading-password =
    .label = پاس ورڈ
column-heading-time-created =
    .label = پہلے استعمال شدہ
column-heading-time-last-used =
    .label = آخری استعمال
column-heading-time-password-changed =
    .label = آخری بار تبدیل شدہ
column-heading-times-used =
    .label = وقتی استعمال شدہ
remove =
    .label = ہٹائیں
    .accesskey = ہ
import =
    .label = درآمد کریں...
    .accesskey = د
close-button =
    .label = بند کریں
    .accesskey = ب
show-passwords =
    .label = پاس ورڈ نمائش کریں
    .accesskey = P
hide-passwords =
    .label = پاس ورڈ چھپائیں
    .accesskey = P
logins-description-all = مندرجہ زیل سائیٹس کہ لاگان آپکے کمپیوٹر پر محفوظ ہیں
logins-description-filtered = مندرحہ زیل لاگ ان آپکی تلاش سے مشابہت رکھتے ہیں
remove-all =
    .label = تمام ہٹائیں
    .accesskey = ت
remove-all-shown =
    .label = تمام دکھائیں ہٹائیں
    .accesskey = ت
remove-all-passwords-prompt = کیا آپ واقعی تمام پاس ورڈ ہٹانا چاہتے ہیں؟
remove-all-passwords-title = تمام پاس ورڈ ہٹائیں
no-master-password-prompt = کیا آپ واقعی اپنے پاس ورڈ نمائش کرنا چاہتے ہیں؟
auto-fill-logins-and-passwords =
    .label = خودبخود فل ہونے والے لاگ انز اور پاس ورڈز
