# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

appmenu-update-available =
    .label = এটা নতুন { -brand-shorter-name } আপডেট উপলব্ধ।
    .buttonlabel = আপডেট ডাউনল'ড কৰক
    .buttonaccesskey = D
    .secondarybuttonlabel = এতিয়া নহয়
    .secondarybuttonaccesskey = N
appmenu-update-available-message = গতি আৰু গোপনিয়তা উন্নীত কৰিবলৈ আপোনাৰ { -brand-shorter-name } আপডেট কৰক।
appmenu-update-manual =
    .label = { -brand-shorter-name } শেহতীয়া সংস্কৰণলৈ আপডেট হ'ব পৰা নাই
    .buttonlabel = { -brand-shorter-name } ডাউনল'ড কৰক
    .buttonaccesskey = D
    .secondarybuttonlabel = এতিয়া নহয়
    .secondarybuttonaccesskey = N
appmenu-update-manual-message = { -brand-shorter-name }-ৰ সতেজ কপি এটা ডাউনল'ড কৰক আৰু সেইটো ইনষ্টল কৰাত আমি আপোনাক সহায় কৰিম।
appmenu-update-whats-new =
    .value = নতুন কি আছে চাওক।
appmenu-update-unsupported =
    .label = { -brand-shorter-name } শেহতীয়া সংস্কৰণলৈ আপডেট হোৱাত অক্ষম।
    .buttonlabel = অধিক জানক
    .buttonaccesskey = L
    .secondarybuttonlabel = বন্ধ কৰক
    .secondarybuttonaccesskey = C
appmenu-update-unsupported-message = { -brand-shorter-name }-ৰ শেহতীয়া সংস্কৰণ আপোনাৰ ছিষ্টেমত সমৰ্থিত নহয়।
appmenu-update-restart =
    .label = { -brand-shorter-name } আপডেট কৰিবলৈ পুনৰাৰম্ভ কৰক
    .buttonlabel = পুনৰাৰম্ভ কৰি পুনঃস্থাপন কৰক
    .buttonaccesskey = R
    .secondarybuttonlabel = এতিয়া নহয়
    .secondarybuttonaccesskey = N
appmenu-update-restart-message = দ্ৰুত পুনৰাৰম্ভৰ পিছত, { -brand-shorter-name }-এ ব্যক্তিগত ব্ৰাউজিং ম'ডত নথকা আপোনাৰ সকলো খোলা টেব আৰু উইণ্ড' পুনঃস্থাপন কৰিব।
appmenu-addon-private-browsing-installed =
    .buttonlabel = ঠিক আছে, বুজিছোঁ
    .buttonaccesskey = O
appmenu-addon-post-install-message = <image data-l10n-name='addon-menu-icon'></image> মেন্যুত <image data-l10n-name='addon-install-icon'></image>-ত ক্লিক কৰি আপোনাৰ এড-অ'নবোৰ পৰিচালনা কৰক।
appmenu-update-available2 =
    .label = আপডেট উপলব্ধ
    .buttonlabel = ডাউনল'ড কৰক
    .buttonaccesskey = ল
    .secondarybuttonlabel = বৰখাস্ত কৰক
    .secondarybuttonaccesskey = ব
appmenu-update-available-message2 = { -brand-shorter-name }-ৰ শেহতীয়া সংস্কৰণ ডাউনল'ড কৰক।
appmenu-update-manual2 =
    .label = আপডেট উপলব্ধ
    .buttonlabel = ডাউনল'ড কৰক
    .buttonaccesskey = ল
    .secondarybuttonlabel = বৰখাস্ত কৰক
    .secondarybuttonaccesskey = ব
appmenu-update-unsupported2 =
    .label = আপডেট কৰিব পৰা নগ'ল
    .buttonlabel = অধিক জানক
    .buttonaccesskey = ন
    .secondarybuttonlabel = বৰখাস্ত কৰক
    .secondarybuttonaccesskey = ব
appmenu-update-unsupported-message2 = আপোনাৰ অপাৰেটিং ছিষ্টেমটো { -brand-shorter-name }-ৰ শেহতীয়া সংস্কৰণৰ সৈতে সুসংগত নহয়।
appmenu-update-restart2 =
    .label = আপডেট উপলব্ধ
    .buttonlabel = আপডেট কৰি পুনৰাৰম্ভ কৰক
    .buttonaccesskey = প
    .secondarybuttonlabel = বৰখাস্ত কৰক
    .secondarybuttonaccesskey = ব
appmenu-update-restart-message2 = { -brand-shorter-name }-ৰ শেহতীয়া সংস্কৰণ লাভ কৰক। খোলা টেব আৰু উইণ্ড'সমূহ পুনঃস্থাপন কৰা হ'ব।
appmenu-addon-post-install-incognito-checkbox =
    .label = এই এক্সটেনশ্যনক ব্যক্তিগত উইণ্ড'বোৰত চলাৰ অনুমতি দিয়ক
    .accesskey = A
appmenu-new-tab-controlled =
    .label = আপোনাৰ নতুন টেব সলনি হৈছে।
    .buttonlabel = সালসলনি ৰাখক
    .buttonaccesskey = K
    .secondarybuttonlabel = এক্সটেনশ্যন নিষ্ক্ৰিয় কৰক
    .secondarybuttonaccesskey = D
appmenu-homepage-controlled =
    .label = আপোনাৰ মুখ্য পৃষ্ঠা সলনি হৈছে।
    .buttonlabel = সালসলনি ৰাখক
    .buttonaccesskey = K
    .secondarybuttonlabel = এক্সটেনশ্যন নিষ্ক্ৰিয় কৰক
    .secondarybuttonaccesskey = D
appmenu-tab-hide-controlled =
    .label = আপোনাৰ লুকুৱা টেবসমূহত প্ৰৱেশ কৰক
    .buttonlabel = টেবসমূহ লুকুৱাই ৰাখক
    .buttonaccesskey = K
    .secondarybuttonlabel = এক্সটেনশ্যন নিষ্ক্ৰিয় কৰক
    .secondarybuttonaccesskey = D
