# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

appmenu-update-available2 =
    .buttonlabel = ডাউনল'ড কৰক
    .buttonaccesskey = ল
    .label = আপডেট উপলব্ধ
    .secondarybuttonlabel = বৰখাস্ত কৰক
    .secondarybuttonaccesskey = ব
appmenu-update-available-message2 = { -brand-shorter-name }-ৰ শেহতীয়া সংস্কৰণ ডাউনল'ড কৰক।
appmenu-update-manual2 =
    .buttonlabel = ডাউনল'ড কৰক
    .buttonaccesskey = ল
    .label = আপডেট উপলব্ধ
    .secondarybuttonlabel = বৰখাস্ত কৰক
    .secondarybuttonaccesskey = ব
appmenu-update-manual-message2 = { -brand-shorter-name } স্বয়ংক্ৰিয়ভাৱে আপডেট কৰিব পৰা নগ'ল। নতুন সংস্কৰণ ডাউনল'ড কৰক — আপুনি সাঁচি থোৱা তথ্য বা অনুকূলন নেহেৰুৱায়।
appmenu-update-unsupported2 =
    .buttonlabel = অধিক জানক
    .buttonaccesskey = ন
    .label = আপডেট কৰিব পৰা নগ'ল
    .secondarybuttonlabel = বৰখাস্ত কৰক
    .secondarybuttonaccesskey = ব
appmenu-update-unsupported-message2 = আপোনাৰ অপাৰেটিং ছিষ্টেমটো { -brand-shorter-name }-ৰ শেহতীয়া সংস্কৰণৰ সৈতে সুসংগত নহয়।
appmenu-update-restart2 =
    .buttonlabel = আপডেট কৰি পুনৰাৰম্ভ কৰক
    .buttonaccesskey = প
    .label = আপডেট উপলব্ধ
    .secondarybuttonlabel = বৰখাস্ত কৰক
    .secondarybuttonaccesskey = ব
appmenu-update-restart-message2 = { -brand-shorter-name }-ৰ শেহতীয়া সংস্কৰণ লাভ কৰক। খোলা টেব আৰু উইণ্ড'সমূহ পুনঃস্থাপন কৰা হ'ব।
appmenu-update-other-instance =
    .buttonlabel = যেনেতেনে { -brand-shorter-name } আপডেট কৰক
    .buttonaccesskey = U
    .label = { -brand-shorter-name }-এ শেহতীয়া সংস্কৰণলৈ স্বয়ংক্ৰিয়ভাৱে আপডেট কৰিব পৰা নাই।
    .secondarybuttonlabel = এতিয়া নহয়
    .secondarybuttonaccesskey = N
appmenu-update-other-instance-message = এটা নতুন { -brand-shorter-name } আপডেট উপলব্ধ যদিও ইনষ্টল কৰিব নোৱাৰি কিয়নো { -brand-shorter-name }-ৰ আন এটা প্ৰতিলিপি চলি আছে। আপডেটটো অব্যাহত ৰাখিবলৈ সেইটো বন্ধ কৰক নাইবা যিকোনো প্ৰকাৰে আপডেট কৰাটো বাছি লওক (আপুনি ইয়াক পুনৰাৰম্ভ নকৰালৈকে আনটো প্ৰতিলিপি সঠিকভাৱে কাম নকৰিবও পাৰে)।
appmenu-addon-post-install-message3 = এপ্লিকেশ্যন মেন্যুৰ জৰিয়তে আপোনাৰ এড-অন আৰু থীমসমূহ পৰিচালনা কৰক।
appmenu-new-tab-controlled-changes =
    .buttonlabel = সাল-সলনি ৰাখক
    .buttonaccesskey = ক
    .label = আপোনাৰ নতুন টেব সলনি হৈছে।
    .secondarybuttonlabel = নতুন টেবসমূহ পৰিচালনা কৰক
    .secondarybuttonaccesskey = প
appmenu-homepage-controlled-changes =
    .buttonlabel = সাল-সলনি ৰাখক
    .buttonaccesskey = ক
    .label = আপোনাৰ গৃহপৃষ্ঠা সলনি হৈছে।
    .secondarybuttonlabel = গৃহপৃষ্ঠা পৰিচালনা কৰক
    .secondarybuttonaccesskey = প
appmenu-tab-hide-controlled =
    .buttonlabel = টেবসমূহ লুকুৱাই ৰাখক
    .buttonaccesskey = K
    .label = আপোনাৰ লুকুৱা টেবসমূহত প্ৰৱেশ কৰক
    .secondarybuttonlabel = এক্সটেনশ্যন নিষ্ক্ৰিয় কৰক
    .secondarybuttonaccesskey = D
