# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language-name-aa = אפאר
language-name-ab = אבחזית
language-name-ae = אווסטית
language-name-af = אפריקאנס
language-name-am = אמהרית
language-name-ar = ערבית
language-name-as = אסאמית
language-name-ast = שפת אסטוריאס
language-name-ay = איימרה
language-name-az = אזרבאיג׳אנית
language-name-ba = באשקירית
language-name-bg = בולגרית
language-name-bh = ביהארית
language-name-bi = ביסלמה
language-name-bm = במברה
language-name-bn = בנגלית
language-name-bo = טיבטית
language-name-bs = בוסנית
language-name-ca = קטלאנית
language-name-ce = צ׳צ׳נית
language-name-co = קורסיקנית
language-name-cr = קרי
language-name-cs = צ׳כית
language-name-cu = סלאבית כנסייתית
language-name-da = דנית
language-name-de = גרמנית
language-name-el = יוונית
language-name-en = אנגלית
language-name-eo = אספרנטו
language-name-es = ספרדית
language-name-et = אסטונית
language-name-eu = בסקית
language-name-fa = פרסית
language-name-fi = פינית
language-name-fj = פיג׳ית
language-name-fo = פארואזית
language-name-fr = צרפתית
language-name-fur = פריולית
language-name-ga = אירית
language-name-gd = גאלית סקוטית
language-name-gn = גוארני
language-name-gu = גוג׳ראטית
language-name-gv = מנקס
language-name-ha = האוסה
language-name-he = עברית
language-name-hi = הינדית
language-name-hr = קרואטית
language-name-ht = האיטית
language-name-hu = הונגרית
language-name-hy = ארמנית
language-name-id = אינדונזית
language-name-io = אידו
language-name-is = איסלנדית
language-name-it = איטלקית
language-name-ja = יפנית
language-name-kg = קונגו
language-name-ki = קיקויו
language-name-kk = קזחית
language-name-kl = גרינלנדית
language-name-km = קמבודית
language-name-kn = קנאדה
language-name-kok = קונקאני
language-name-ks = קשמירית
language-name-ku = כורדית
language-name-kv = קומי
language-name-kw = קורני
language-name-ky = קירגיזית
language-name-la = לטינית
language-name-lb = לוקסמבורגית
language-name-lo = לאו
language-name-lt = ליטאית
language-name-lv = לטבית
language-name-mg = מלגאשית
language-name-mh = שפת איי מרשל
language-name-mi = מאורית
language-name-mk = מקדונית
language-name-ml = מליאלאם
language-name-mn = מונגולית
language-name-mr = מרטהי
language-name-ms = מלזית
language-name-my = בורמזית
language-name-na = נאורו
language-name-nb = נורווגית בוקמאל
language-name-nd = נדבלה צפונית
language-name-ne = נפאלית
language-name-nl = הולנדית
language-name-nn = נורווגית נינורסק
language-name-no = נורווגית
language-name-nr = נדבלה דרומית
language-name-nv = נאבאחו
language-name-os = אוסטית
language-name-pi = פלי
language-name-pl = פולנית
language-name-ps = פשטונית
language-name-ro = רומנית
language-name-ru = רוסית
language-name-sa = סנסקריט
language-name-se = סאמי צפונית
language-name-si = ציילונית
language-name-sk = סלובקית
language-name-sl = סלובנית
language-name-sm = סמואית
language-name-so = סומאלית
language-name-sq = אלבנית
language-name-sr = סרבית
language-name-st = סוטו, מזרחית
language-name-su = סודנית
language-name-sv = שוודית
language-name-sw = סווהילית
language-name-ta = טמילית
language-name-te = טלוגו
language-name-tg = טאג׳יקית
language-name-th = תאילנדית
language-name-ti = טיגרינית
language-name-tk = טורקמנית
language-name-tl = טגלוג
language-name-tlh = קלינגונית
language-name-tn = טסואנה
language-name-to = טונגה
language-name-ts = טסונגה
language-name-tt = טטארית
language-name-ty = טהיטית
language-name-uk = אוקראינית
language-name-ur = אורדו
language-name-uz = אוזבקית
language-name-ve = וונדה
language-name-vi = ויאטנמית
language-name-wa = ולונית
language-name-wen = סורבית
language-name-yo = יורובה
language-name-zh = סינית
language-name-zu = זולו
