# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Simpan
dialogTitleAddBookmark = Tambah Markah
dialogTitleAddMulti = Buat Markah Semua Tab
dialogTitleEdit = Properti untuk "%S"
dialogTitleAddNewBookmark2 = Tambah markah
dialogTitleEditBookmark = Edit “%S”
dialogTitleEditBookmark2 = Edit markah
dialogTitleAddBookmarkFolder = Tambahkan folder markah
dialogTitleEditBookmarkFolder = Edit folder markah
bookmarkAllTabsDefault = [Nama Folder]
newFolderDefault = Folder Baru
newBookmarkDefault = Markah Baru
