# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = იძებნება { $host }…
network-connection-status-connected = დაუკავშირდა { $host }…
network-connection-status-sending-request = იღებს მოთხოვნას { $host }…
network-connection-status-transferring-data = მონაცემთა გადმოტანა – { $host }…
network-connection-status-connecting = უკავშირდება { $host }…
network-connection-status-looked-up = მოიძებნა { $host }…
network-connection-status-tls-handshake = კავშირის TLS-დამოწმება – { $host }…
network-connection-status-tls-handshake-finished = TLS-დამოწმება დასრულდა – { $host }…
