# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = यो वेब पृष्ठ नयाँ ठेगानामा पुनःनिर्देशित भईरहेको छ। के तपाईँ आफूले टाइप गर्नुभएको फाराम डाटालाई नयाँ ठेगानामा पुनः पठाउन चाहनुहुन्छ?
# Directory listing strings
DirTitle = %1$S को अनुक्रमणिका
DirGoUp = उच्च तहको डाइरेक्टरीसम्म
ShowHidden = लुकेका वस्तुहरू देखाउनुहोस्
DirColName = नाम
DirColSize = साइज
DirColMTime = पछिल्लो परिमार्जित
DirFileLabel = फाइल:
UnsafeUriBlocked = सुरक्षित ब्राउजिङ्गले “%1$S” मा भएको संसाधन अबरुद्द गरेकोछ ।
