# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = ഈ വെബ് താള്‍ ഒരു പുതിയ സ്ഥലത്തേക്ക് മാറ്റപ്പെടുന്നു. നിങ്ങള്‍ പുതിയ സ്ഥലത്തേക്ക്  ടൈപ്പ് ചെയ്ത ഡേറ്റാ വീണ്ടും അയയ്ക്കണമോ?
# Directory listing strings
DirTitle = %1$S-നുള്ള സൂചിക
DirGoUp = ഉയര്‍ന്ന ലവല്‍ ഡയറക്ടറി വരെ
ShowHidden = അദൃശ്യമായ വസ്തുക്കള്‍ കാണിക്കുക
DirColName = പേരു്
DirColSize = വലിപ്പം
DirColMTime = ഏറ്റവും ഒടുവില്‍ മാറ്റം വരുത്തിയതു്
DirFileLabel = ഫയല്‍:
