# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loginsDescriptionAll2 = ਅੱਗੇ ਦਿੱਤੀਆਂ ਸਾਈਟਾਂ ਲਈ ਲਾਗਇਨ ਤੁਹਾਡੇ ਕੰਪਿਊਟਰ 'ਤੇ ਸੰਭਾਲੇ ਗਏ ਹਨ
# LOCALIZATION NOTE (useASecurelyGeneratedPassword):
# Shown in the autocomplete popup to allow filling a generated password into a password field.
useASecurelyGeneratedPassword = ਸੁਰੱਖਿਅਤ ਰੂਪ ‘ਚ ਤਿਆਰ ਕੀਤਾ ਪਾਸਵਰਡ ਵਰਤੋਂ
# LOCALIZATION NOTE (generatedPasswordWillBeSaved):
# %S will contain the brandShorterName. This informs the user that the generated password will be automatically saved.
generatedPasswordWillBeSaved = ਇਸ ਵੈੱਬਸਾਈਟ ਲਈ %S ਇਹ ਪਾਸਵਰਡ ਨੂੰ ਸੰਭਾਲੇਗਾ।
# LOCALIZATION NOTE (loginHostAge):
# This is used to show the context menu login items with their age.
# 1st string is the username for the login, 2nd is the login's age.
loginHostAge = %1$S (%2$S)
# LOCALIZATION NOTE (noUsername):
# String is used on the context menu when a login doesn't have a username.
noUsername = ਕੋਈ ਵਰਤੋਂਕਾਰ ਨਾਂ ਨਹੀਂ ਹੈ
# LOCALIZATION NOTE (displaySameOrigin):
# String is used on the autocomplete row when the login origin is a domain match with the document origin
displaySameOrigin = ਇਸ ਵੈੱਬਸਾਈਟ ਤੋਂ
# LOCALIZATION NOTE (autocompleteEditLogin):
# Accessible label for the edit button shown on a saved-login row in the
# autocomplete popup.
autocompleteEditLogin = ਲਾਗਇਨ ਨੂੰ ਸੋਧੋ
# LOCALIZATION NOTE (insecureFieldWarningDescription2):
# %1$S will contain insecureFieldWarningLearnMore and look like a link to indicate that clicking will open a tab with support information.
insecureFieldWarningDescription2 = ਇਹ ਕਨੈਕਸ਼ਨ ਸੁਰੱਖਿਅਤ ਨਹੀਂ ਹੈ। ਇੱਥੇ ਦਿੱਤੇ ਲਾਗਇਨ ਚੋਰੀ ਹੋ ਸਕਦੇ ਹਨ। %1$S
insecureFieldWarningLearnMore = ਹੋਰ ਜਾਣੋ
# LOCALIZATION NOTE (managePasswords.label):
# This label is used in the footer of login autocomplete menus.
managePasswords.label = ਪਾਸਵਰਡਾਂ ਦਾ ਇੰਤਜ਼ਾਮ
