# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Notice: If you're updating this list, you should also
###         update the list in mozIntl.js.

region-name-ad = एन्ड'रा
region-name-af = आफगानिस्तान
region-name-ag = एन्टिगुवा आरो बारबुडा
region-name-ai = एंगुइला
region-name-al = आल्बेनिया
region-name-am = आर्मेनिया
region-name-ao = एंगला
region-name-aq = एन्टारटिका
region-name-ar = आर्जेन्टिना
region-name-as = आमेरिकान साम'आ
region-name-at = अस्ट्रिया
region-name-au = अस्ट्रेलिया
region-name-aw = एरुबा
region-name-az = आजारबैजानि
region-name-ba = बस्निया आरो हार्जेग'भिना
region-name-bb = बारबाडस
region-name-bd = बांलादेश
region-name-be = बेलजियाम
region-name-bf = बुरकिना फास'
region-name-bg = बुलगेरिया
region-name-bh = बाहरेइन
region-name-bi = बुरुन्डि
region-name-bj = बेनिन
region-name-bm = बारमुडा
region-name-bo = बलिभिया
region-name-br = ब्राजिल
region-name-bt = भुटान
region-name-bv = बौभेट आइलेन्ड
region-name-bw = बटस्वाना
region-name-by = बेलारुस
region-name-bz = बेलिज
region-name-ca = कानाडा
region-name-cc = ककस (किलिं) द्विप
region-name-cd = कंग'-किनशासा{ " " }
region-name-cf = मिरु आफ्रिका फोरजाखानथि
region-name-cg = कंग'-ब्रेजाभिल
region-name-ch = सुइजारलेण्ड
region-name-ck = कुक आइलेन्ड
region-name-cl = चिलि
region-name-cm = केमेरुन
region-name-cn = चीन
region-name-co = कलम्बिया
region-name-cr = कस्टा रिका
region-name-cu = किउबा
region-name-cx = क्रिस्टमास आइलेन्ड
region-name-cy = सिपरास
region-name-cz = चेक फोरजाखानथि{ "   " }
region-name-de = जार्मानि
region-name-dj = जिबौटि
region-name-dk = डेनमार्क
region-name-dm = डमिनिका
region-name-do = डमिनिकन रिपाब्लिक
region-name-dz = अलजिरिया
region-name-ec = इकाउडर
region-name-ee = इस्ट'निया
region-name-eg = इजिप्ट
region-name-eh = सोनाबारि साहारा
region-name-er = इरिट्रि
region-name-es = स्पेइन
region-name-et = इथिअपिया
region-name-fi = फिनलेण्ड
region-name-fj = फिजि
region-name-fo = फेरु आइलेन्ड
region-name-fr = फ्रान्स
region-name-ga = गेबन
region-name-gb = इउनाइटेड किंडम
region-name-gd = ग्रेनाडा
region-name-ge = जर्जियान
region-name-gf = फ्रेन्स गुइना
region-name-gg = गुर्नसे
region-name-gh = घाना
region-name-gi = गिब्रेल्टा
region-name-gl = ग्रिनलेन्ड
region-name-gn = गुइनिया
region-name-gp = गुयाडेलुप
region-name-gq = इकुवेटरियाल गुइनिया
region-name-gr = ग्रिस
region-name-gt = गुवाटेमाला
region-name-gu = गुयाम
region-name-gw = गुइनिया-बिसाव
region-name-gy = गुइयाना
region-name-hk = हं कं
region-name-hm = हार्ड आइलेन्ड आरो मेक आइलेन्डस
region-name-hn = हन्डुरास
region-name-hr = क्रसिया
region-name-ht = हाइटि
region-name-hu = हांगेरि
region-name-id = इन्ड'नेसिया
region-name-ie = आयारलेण्ड
region-name-il = इजराइल
region-name-im = आइल अफ मेन
region-name-in = भारत
region-name-io = ब्रिटिश भारतारि लैथोमा ओनसोल
region-name-iq = इराक
region-name-ir = इरान
region-name-is = आइचलेण्ड
region-name-it = इटालि
region-name-je = जार्सि
region-name-jm = जामाइका
region-name-jo = जर्डान
region-name-jp = जापान
region-name-ke = केनिया
region-name-kg = केरगेजस्तान
region-name-kh = कम्बडिया
region-name-ki = कारिबाटि
region-name-km = क'म'र'स
region-name-kn = सेन्ट किटस आरो नेभिस
region-name-kw = कुवेट
region-name-ky = केइमेन आइलेन्ड
region-name-kz = काजाखस्तान
region-name-la = लाअस
region-name-lb = लेबानन
region-name-lc = सेन्ट लुसिया
region-name-li = लिचेनस्टेन
region-name-lk = श्रि लंका
region-name-lr = लिबेरिया
region-name-ls = लेस'थ'
region-name-lt = लिटुआनिया
region-name-lu = लाक्सेमबार्ग
region-name-lv = लाटभिया
region-name-ly = लिबिया
region-name-ma = म'र'क'
region-name-mc = मनेक'
region-name-md = मलड'भा
region-name-me = मन्टेनेग्र'
region-name-mf = सेन्ट मार्टिन
region-name-mg = माडागास्कार
region-name-mh = मारशाल आइलेन्ड
region-name-ml = मालि
region-name-mn = मंगलिया
region-name-mp = साहा मानियाना द्विप
region-name-mq = मार्टिनिक
region-name-mr = मौरिटानिया
region-name-ms = मन्टसेराट
region-name-mt = माल्टा
region-name-mu = मौरिसास
region-name-mv = मालडिभ
region-name-mw = मालावि
region-name-mx = मेक्सिक
region-name-my = मालाइशिया
region-name-mz = मजाम्बिक
region-name-na = नामिबिया
region-name-nc = निउ सेलेडनिया
region-name-ne = निगार
region-name-nf = नरफक आइलेन्ड
region-name-ng = नाइजेरिया
region-name-ni = निकारगुवा
region-name-nl = नेडारलेण्ड
region-name-no = नरवे
region-name-np = नेपाल
region-name-nr = नाउरु
region-name-nu = निउ
region-name-nz = निउ जिलेण्ड
region-name-om = अमान
region-name-pa = पानामा
region-name-pe = पेरु
region-name-pf = फ्रान्स पलिनिसिया
region-name-pg = पापुआ निउ गुइनि
region-name-ph = फिलिपिनस
region-name-pk = पाकिस्तान
region-name-pl = पलेण्ड
region-name-pm = सेन्ट पियारि आरो मिकुइलन
region-name-pr = पुर्ट रिक'
region-name-pt = पुर्टगाल
region-name-pw = पालाउ
region-name-py = पारागुवे
region-name-qa = काटार
region-name-re = रिइउनियन
region-name-ro = रमानिया
region-name-rs = सार्बिया
region-name-rw = रवाण्डा
region-name-sa = सौदि आरबिया
region-name-sb = स'ल'म'न आइलेन्ड
region-name-sc = सेइसिलिस
region-name-sd = सुडान
region-name-se = छुइडेन
region-name-sg = सिंगापुर
region-name-si = स्लभेनिया
region-name-sk = स्लभाकिया
region-name-sl = सिरा लिअन
region-name-sm = सान मेरिन'
region-name-sn = सेनेगाल
region-name-so = समालिया
region-name-sr = सुरिनाम
region-name-st = साअ टम आरो प्रिनसिपि
region-name-sv = इल सालभेडर
region-name-sy = सिरिया
region-name-sz = स्वाजिलेन्ड
region-name-tc = तुर्कस आरो कैकस आइलेन्ड
region-name-td = छाद
region-name-tg = ट'ग'
region-name-th = थाइलेण्ड
region-name-tj = टाजिकिस्तान
region-name-tk = टकेलु
region-name-tl = टिमुर-लिस्टे
region-name-tm = तुर्कमेनिस्तान
region-name-tn = टुनिसिया
region-name-to = टंगा
region-name-tr = तुर्कि
region-name-tt = ट्रिनिदाद आरो टबेग'
region-name-tv = टुभेलु
region-name-tw = ताइवान
region-name-tz = टानजानिया
region-name-ua = इउक्रेन
region-name-ug = उगान्डा
region-name-us = जुथाय रायजो
region-name-uy = उरूगुवे
region-name-uz = उजबेकिस्टान
region-name-va = भाटिकान सिटि
region-name-vc = सेन्ट भिनसेन्ट आरो ग्रेनाडिनस
region-name-ve = भेनेजुवेला
region-name-vn = भियेटनाम
region-name-vu = भेनुआटु
region-name-wf = वालिस आरो फुटुना
region-name-ws = साम'आ
region-name-ye = येमेन
region-name-yt = माय'टि
region-name-za = खोला आफ्रिका
region-name-zm = जाम्बिया
region-name-zw = जिम्बाबे
