# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = Omuko gw'lutiimbe luno gusengulwa okuguzza mukifo ekijja. Wandiyagade okuwereza byowandise mu flugo mukifo ekijja?
# Directory listing strings
DirTitle = Endagirilo ya %1$S
DirGoUp = Paka ku nsibuko ya kinnemu
ShowHidden = Laga ebintu ebikwekeddwa
DirColName = Erinnya
DirColSize = Obunene
DirColMTime = Lwe kyasemba okukyuusibwa
DirFileLabel = Fayiro:\u0020
