# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Tidsavbrudd
openFile = Åpne fil
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Søk på %1$S etter «%2$S»
contextMenuSearch.accesskey = S
contextMenuPrivateSearch = Søk i et privat vindu
contextMenuPrivateSearch.accesskey = k
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Søk med %S i et privat vindu
contextMenuPrivateSearchOtherEngine.accesskey = k
bookmarkAllTabsDefault = [Mappenavn]
unsignedAddonsDisabled.message = En eller flere installerte utvidelser kan ikke bekreftes, og har blitt slått av.
unsignedAddonsDisabled.learnMore.label = Les mer
unsignedAddonsDisabled.learnMore.accesskey = L
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Siste tilgang %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = %S://-lenker
crashedpluginsMessage.title = Programtillegget %S krasjet.
crashedpluginsMessage.reloadButton.label = Oppdater siden
crashedpluginsMessage.reloadButton.accesskey = O
crashedpluginsMessage.submitButton.label = Send inn en krasjrapport
crashedpluginsMessage.submitButton.accesskey = S
crashedpluginsMessage.learnMore = Mer info …
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Mente du å gå til %S?
keywordURIFixup.goTo = Ja, gå til %S
keywordURIFixup.goTo.accesskey = J
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Oppdater til %S
update.downloadAndInstallButton.accesskey = O
menuOpenAllInTabs.label = Åpne alle i faner
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Last denne siden på nytt
tabHistory.goBack = Gå tilbake til denne siden
tabHistory.goForward = Gå frem til denne siden
# URL Bar
pasteAndGo.label = Lim inn og åpne
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Oppdater denne siden (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Stopp lasting av denne siden (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Tilbakestill zoom (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Slå av/på lesevisning (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S %%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, Tilbakestill zoomnivå
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Vis bokmerkene (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Viser fremdriften til pågående nedlastinger (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Åpne et nytt vindu (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Åpne en ny fane (%S)
newTabContainer.tooltip = Åpne en ny fane (%S)\nTrykk og hold nede for å åpne en ny beholderfane
newTabAlwaysContainer.tooltip = Velg beholder for å åpne en ny fane
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Tillate %S å bruke dine HTML5-canvas-bildedata?
canvas.siteprompt2.warning = Dette kan brukes til å unikt identifisere din datamaskin.
canvas.block = Blokker
canvas.block.accesskey = B
canvas.allow2 = Tillat
canvas.allow2.accesskey = T
canvas.remember2 = Husk dette valget
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Bekreftet av: %S
identity.identified.verified_by_you = Du har laget et sikkerhetsunntak for dette nettstedet.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Sertifikat utstedt til: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Ikke sikker
identity.notSecure.tooltip = Tilkoblingen er ikke sikker
identity.extension.label = Utvidelse (%S)
identity.extension.tooltip = Lastet av utvidelsen: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Zoom ut (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Tilbakestill zoom-nivå (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Zoom inn (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Klipp ut (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Kopier (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Lim inn (%S)
geolocation.allow = Tillat
geolocation.allow.accesskey = T
geolocation.block = Blokker
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Dette vil åpne systemets innstillinger for plassering. Gi plasseringstillatelse til %S.
geolocation.shareWithSite4 = Tillat %S å få tilgang til posisjonen din?
geolocation.shareWithFile4 = Tillat denne lokale filen å få tilgang til posisjonen din?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Tillate %1$S å gi %2$S tillatelse til å få tilgang til din plassering?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Gi %S plasseringstillatelse i systeminnstillingene.
geolocation.systemSettingsTitle = Venter på plasseringstillatelse
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Systemet vil be deg om å gi denne tillatelsen til %S.
geolocation.remember = Husk denne avgjørelsen
# Virtual Reality Device UI
xr.allow2 = Tillat
xr.allow2.accesskey = T
xr.block = Blokker
xr.block.accesskey = B
xr.shareWithSite4 = Tillate %S å få tilgang til virtuell virkelighet-enheter? Dette kan eksponere sensitiv informasjon.
xr.shareWithFile4 = Tillate denne lokale filen å få tilgang til virtuell virkelighet-enheter? Dette kan eksponere sensitiv informasjon.
xr.remember = Husk dette valget
# Persistent storage UI
persistentStorage.allow = Tillat
persistentStorage.allow.accesskey = T
persistentStorage.block.label = Blokker
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Tillate %S å lagre data i vedvarende lagring?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Tillat
webNotifications.allow2.accesskey = T
webNotifications.notNow = Ikke nå
webNotifications.notNow.accesskey = n
webNotifications.never = Tillat aldri
webNotifications.never.accesskey = a
webNotifications.alwaysBlock = Blokker alltid
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = Blokker
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Tillat %S å sende varsler?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S vil ha tilgang til andre apper og tjenester på denne enheten.
localhost.remember2 = Husk valget mitt for dette nettstedet
localhost.allowlabel = Tillat
localhost.blocklabel = Blokker
localhost.allow.accesskey = T
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S vil ha tilgang til apper og tjenester på enheter som er koblet til ditt lokale nettverk.
localNetwork.remember2 = Husk valget mitt for dette nettstedet
localNetwork.allowLabel = Tillat
localNetwork.allow.accesskey = T
localNetwork.blockLabel = Blokker
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Få meg bort herfra!
safebrowsing.getMeOutOfHereButton.accessKey = F
safebrowsing.deceptiveSite = Villedende nettsted!
safebrowsing.notADeceptiveSiteButton.label = Dette er ikke et villedende nettsted …
safebrowsing.notADeceptiveSiteButton.accessKey = d
safebrowsing.reportedAttackSite = Rapportert angrepsnettsted!
safebrowsing.notAnAttackButton.label = Dette er ikke en angrepsnettside …
safebrowsing.notAnAttackButton.accessKey = e
safebrowsing.reportedUnwantedSite = Rapportert uønsket programvare-nettsted!
safebrowsing.reportedHarmfulSite = Rapportert skadelig nettsted!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Søk %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Starte %S på nytt i feilsøkingsmodus?
troubleshootModeRestartPromptMessage = Dine utvidelser, tema og tilpassede innstillinger vil midlertidig slås av.
troubleshootModeRestartButton = Start på nytt
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Denne nettsiden gjør at %1$S går tregere. Stopp denne siden for å øke hastigheten på nettleseren din.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = En nettside gjør at %1$S går tregere. Stopp den siden for å øke hastigheten på nettleseren din.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = «%1$S» gjør at %2$S går tregere. Stopp den siden for å øke hastigheten på nettleseren din.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = «%1$S» gjør at %2$S går tregere. Stopp den utvidelsen for å øke hastigheten på nettleseren din.
processHang.add-on.learn-more.text = Les mer
processHang.button_stop2.label = Stopp
processHang.button_stop2.accessKey = S
processHang.button_debug.label = Feilsøk skript
processHang.button_debug.accessKey = F
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Vis vinduet i fullskjerm (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Flytt sidestolpe til venstre
sidebar.moveToRight = Flytt sidestolpe til høyre
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Du må aktivere DRM for å spille lyd eller video på denne siden.
emeNotifications.drmContentDisabled.button.label = Slå på DRM
emeNotifications.drmContentDisabled.button.accesskey = S
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S installerer komponentene som trengs for å spille av lyden eller videoen på denne siden. Prøv igjen senere.
emeNotifications.unknownDRMSoftware = Ukjent
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Tilpass %S
decoder.noCodecs.button = Finn ut hvordan
decoder.noCodecs.accesskey = F
decoder.noCodecsLinux.message = For å spille av videoer må du installere de påkrevde video-kodekene.
decoder.noHWAcceleration.message = For å forbedre videokvalitet må du kanskje installere Microsofts Media Feature Pack.
decoder.noPulseAudio.message = For å spille av lyd, må du kanskje installere den påkrevde PulseAudio-programvaren.
decoder.unsupportedLibavcodec.message = libavcode kan være sårbart eller ikke støttet, og burde oppdateres for å spille video.
decoder.decodeError.message = Det oppstod en feil under dekoding av en medieressurs.
decoder.decodeError.button = Rapporter problem med nettsted
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = En gjenopprettelig feil oppstod ved dekoding av en medieressurs.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Du må logge inn på nettverket før du får tilgang til Internett.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Åpne innloggingsside for nettverk
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Tillatelser for %S
permissions.remove.tooltip = Fjern denne tillatelsen og spør igjen
permissions.fullscreen.promptCanceled = Avbrutt ventende tillatelsesforespørsler: tillatelsesforespørsler bør ikke utstedes før du går inn i DOM-fullskjerm.
permissions.fullscreen.fullScreenCanceled = Avsluttet DOM-fullskjerm: tillatelsesforespørsler skal ikke utstedes mens du er i DOM-fullskjerm.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bits
aboutDialog.architecture.thirtyTwoBit = 32-bits
midi.allow.label = Tillat
midi.allow.accesskey = T
midi.block.label = Blokker
midi.block.accesskey = B
midi.remember = Husk dette valget
midi.shareWithFile = Tillat denne lokale filen å få tilgang til MIDI-enhetene dine?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Tillate %S å få tilgang til MIDI-enhetene dine?
midi.shareSysexWithFile = Tillate denne lokale filen å få tilgang til MIDI-enhetene dine og sende/motta SysEx-meldinger?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Tillat %S å få tilgang til MIDI-enhetene dine og sende/motta SysEx-meldinger?
serial.allow.label = Tillat
serial.allow.accesskey = T
serial.block.label = Blokker
serial.block.accesskey = B
serial.shareWithFile = Tillat denne lokale filen å få tilgang til dine serieporter?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Tillat %S å få tilgang til dine serieporter?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Tilbake
storageAccess1.Allow.label = Tillat
storageAccess1.Allow.accesskey = T
storageAccess1.DontAllow.label = Blokker
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Vil du tillate %1$S å bruke sine infokapsler på %2$S?
storageAccess1.hintText = Det kan være lurt å blokkere tilgang hvis det ikke er klart hvorfor %1$S trenger disse dataene.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Søk på nettet etter «%S»
