# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Consultar { $host }…
network-connection-status-connected = Connectà cun { $host }…
network-connection-status-sending-request = Trametter la dumonda a { $host }…
network-connection-status-transferring-data = Transmetter las datas da { $host }…
network-connection-status-connecting = Connectar cun { $host }…
network-connection-status-read = Legì { $host }
network-connection-status-wrote = Scrit { $host }
network-connection-status-waiting = Spetgar { $host }…
network-connection-status-looked-up = Tschertgar { $host }…
network-connection-status-tls-handshake = Exequir in handshake TLS cun { $host }…
network-connection-status-tls-handshake-finished = Il handshake TLS è terminà per { $host }…
