# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = খুলুন
    .accesskey = O
places-open-all-in-tabs =
    .label = ট্যাবের মধ্যে সকল প্রদর্শন করা হবে
    .accesskey = O
places-view =
    .label = প্রদর্শন
    .accesskey = প
places-by-date =
    .label = তারিখ অনুযায়ী
    .accesskey = D
places-by-site =
    .label = সাইট অনুযায়ী
    .accesskey = S
places-by-most-visited =
    .label = সর্বাধিক পরিদর্শন অনুযায়ী
    .accesskey = V
places-by-last-visited =
    .label = সর্বশেষ পরিদর্শন অনুযায়ী
    .accesskey = L
places-by-day-and-site =
    .label = তারিখ ও সাইট অনুযায়ী
    .accesskey = ত
places-history-search =
    .placeholder = ইতিহাস খুঁজুন
places-history =
    .aria-label = ইতিহাস
places-bookmarks-search =
    .placeholder = বুকমার্কগুলি খুঁজুন
places-delete-domain-data =
    .label = এই সাইট সম্বন্ধে তথ্য সংরক্ষণ করা হবে না
    .accesskey = F
places-sortby-name =
    .label = নাম অনুসারে সুবিন্যস্ত করুন
    .accesskey = r
places-library =
    .title = লাইব্রেরি
    .style = width:700px; height:500px;
places-library2 =
    .title = লাইব্রেরি
    .style = min-width:700px; min-height:500px;
places-organize-button =
    .label = সংগঠিত
    .tooltiptext = বুকমার্ক সুবিন্যস্ত করুন
    .accesskey = O
places-organize-button-mac =
    .label = সংগঠিত
    .tooltiptext = বুকমার্ক সুবিন্যস্ত করুন
places-file-close =
    .label = বন্ধ করুন
    .accesskey = C
places-cmd-close =
    .key = w
places-view-button =
    .label = প্রদর্শন
    .tooltiptext = প্রদর্শন পরিবর্তন করুন
    .accesskey = V
places-view-button-mac =
    .label = প্রদর্শন
    .tooltiptext = প্রদর্শন পরিবর্তন করুন
places-view-menu-columns =
    .label = কলাম প্রদর্শন করা হবে
    .accesskey = C
places-view-menu-sort =
    .label = ক্রমবিন্যাস
    .accesskey = S
places-view-sort-unsorted =
    .label = অবিন্যাস্ত
    .accesskey = U
places-view-sort-ascending =
    .label = ছোট থেকে বড়
    .accesskey = A
places-view-sort-descending =
    .label = Z > A ক্রমবিন্যাস
    .accesskey = Z
places-maintenance-button =
    .label = ইমপোর্ট ও ব্যাক-আপ করুন
    .tooltiptext = বুকমার্ক ইম্পোর্ট ও ব্যাক-আপ করুন
    .accesskey = I
places-maintenance-button-mac =
    .label = ইমপোর্ট ও ব্যাক-আপ করুন
    .tooltiptext = বুকমার্ক ইম্পোর্ট ও ব্যাক-আপ করুন
places-cmd-backup =
    .label = ব্যাক-আপ করুন…
    .accesskey = B
places-cmd-restore =
    .label = পুনরুদ্ধার
    .accesskey = R
places-cmd-restore-from-file =
    .label = ফাইল নির্বাচন করুন…
    .accesskey = C
places-import-bookmarks-from-html =
    .label = HTML থেকে বুকমার্ক ইম্পোর্ট করুন…
    .accesskey = I
places-export-bookmarks-to-html =
    .label = HTML-এ বুকমার্ক এক্সপোর্ট করুন…
    .accesskey = E
places-import-other-browser =
    .label = অন্য ব্রাউজার থেকে তথ্য ইম্পোর্ট করুন…
    .accesskey = A
places-view-sort-col-name =
    .label = নাম
places-view-sort-col-tags =
    .label = ট্যাগ
places-view-sort-col-url =
    .label = অবস্থান
places-view-sort-col-most-recent-visit =
    .label = সাম্প্রতিক ভিজিট
places-view-sort-col-visit-count =
    .label = পরিদর্শনের সংখ্যা
places-view-sort-col-date-added =
    .label = যোগ হওয়ার তারিখ
places-view-sort-col-last-modified =
    .label = সর্বশেষ পরিবর্তনের সময়
places-cmd-find-key =
    .key = f
places-back-button =
    .tooltiptext = পূর্ববর্তী স্থানে চলুন
places-forward-button =
    .tooltiptext = পরবর্তী স্থানে এগিয়ে চলুন
places-details-pane-select-an-item-description = কোনো বস্তু প্রদর্শন করার জন্য ও সেটির বৈশিষ্ট্য পরিবর্তের উদ্দেশ্যে নির্বাচন করুন
