# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

custom-prompt-title = Oanpast...
basic-tab =
    .label = Formaat & opsjes
format-group-label =
    .value = Formaat
orientation-label =
    .value = Oriïntaasje:
portrait =
    .label = Steand
    .accesskey = S
landscape =
    .label = Lizzend
    .accesskey = L
scale =
    .label = Op grutte:
    .accesskey = g
scale-percent =
    .value = %
shrink-to-fit =
    .label = Ferlytsje oant papierformaat
    .accesskey = F
options-group-label =
    .value = Opsjes
margin-group-label-inches =
    .value = Marges (inches)
margin-group-label-metric =
    .value = Marges (millimeters)
margin-top =
    .value = Boppe:
    .accesskey = B
margin-top-invisible =
    .value = Boppe:
margin-bottom =
    .value = Under:
    .accesskey = U
margin-bottom-invisible =
    .value = Under:
margin-right =
    .value = Rjochts:
    .accesskey = R
margin-right-invisible =
    .value = Rjochts:
hf-center-label =
    .value = Midden:
hf-right-label =
    .value = Rjochts:
header-center-tip =
    .tooltiptext = Middelste koptekst
header-right-tip =
    .tooltiptext = Rjochter koptekst
hf-blank =
    .label = --blanko--
hf-title =
    .label = Titel
hf-url =
    .label = URL
hf-date-and-time =
    .label = Datum/Tiid
hf-page =
    .label = Side #
hf-page-and-total =
    .label = Side # fan #
hf-custom =
    .label = Oanpast...
print-preview-window =
    .title = Ofdrukfoarbyld
print-title =
    .value = Titel:
print-preparing =
    .value = Tarieding...
print-progress =
    .value = Foartgong:
print-window =
    .title = Ofdrukke
print-complete =
    .value = Ofdrukken is klear.
# Variables
# $percent (integer) - Number of printed percentage
print-percent =
    .value = { $percent }%
dialog-close-label = Slute
