# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Поиск { $host }…
network-connection-status-connected = Соединено с { $host }…
network-connection-status-sending-request = Отправка запроса на { $host }…
network-connection-status-transferring-data = Передача данных с { $host }…
network-connection-status-connecting = Соединение с { $host }…
