# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Quere confiar en "%S" para as seguintes finalidades?
unnamedCA = Entidade de acreditación (sen nome)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Introduza o contrasinal utilizado para cifrar esta copia de seguranza do certificado:
# Page Info
pageInfo_NoEncryption = Conexión non cifrada
pageInfo_Privacy_None1 = O sitio web %S non é compatíbel co cifrado da páxina que está a ver.
pageInfo_Privacy_None2 = A información enviada pola Internet sen cifrar pode ser visualizada por outras persoas durante o seu tránsito.
pageInfo_Privacy_None4 = A páxina que está a ver non se cifrou antes de ser transmitida pola Internet.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Conexión cifrada (%1$S, chaves de %2$S bits, %3$S)
pageInfo_BrokenEncryption = Cifrado non fiábel (%1$S, chaves de %2$S bits, %3$S)
pageInfo_Privacy_Encrypted1 = A páxina que está a ver cifrouse antes de ser transmitida pola Internet.
pageInfo_Privacy_Encrypted2 = O cifrado dificulta que persoas non autorizadas visualicen a información que transita entre computadores. Por tanto é pouco probábel que alguén lese esta páxina mentres viaxaba pola rede.
pageInfo_MixedContent = Conexión parcialmente cifrada
pageInfo_MixedContent2 = Partes da páxina que está a ver non se cifraron antes de ser transmitidas pola Internet.
pageInfo_WeakCipher = A conexión con este sitio web usa un cifrado débil e non é privada. Outras persoas poden ver a súa información ou modificar o comportamento do sitio web.
pageInfo_CertificateTransparency_Compliant = Este sitio web cumpre coa política de transparencia de certificados.
# Token Manager
password_not_set = (sen definir)
