# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = Hierdie webbladsy word na 'n nuwe ligging herverwys. Wil u die vormdata wat u ingevul het, na die nuwe ligging toe herstuur?
# Directory listing strings
DirTitle = Indeks van %1$S
DirGoUp = Boontoe na hoërvlak-subgids
ShowHidden = Wys versteekte objekte
DirColName = Naam
DirColSize = Grootte
DirColMTime = Laas gewysig
DirFileLabel = Lêer:\u0020
UnsafeUriBlocked = Die hulpbron by “%1$S” is deur Safe Browsing geblokkeer.
