# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

ssl-error-export-only-server = Неможливо спілкуватись конфіденційно. Вузол не підтримує високорівневе шифрування.
ssl-error-no-certificate = Не вдалось знайти сертифікат чи ключ необхідний для засвідчення.
ssl-error-bad-certificate = З вузлом неможливо спілкуватись конфіденційно: сертифікат вузла відхилено.
ssl-error-bad-client = Сервер отримав від клієнта хибні дані.
ssl-error-bad-server = Клієнт отримав від сервера хибні дані.
ssl-error-unsupported-version = Вузол використовує непідтримувану версію протоколу секретності.
ssl-error-wrong-certificate = Засвідчення клієнта не вдалось: приватний ключ у базі ключів не відповідає публічному ключу у базі сертифікатів.
ssl-error-ssl2-disabled = Вузол підтримує лише SSL версії 2, котра у вас вимкнена.
ssl-error-bad-mac-read = SSL отримав запис з невірним Кодом засвідчення повідомлення.
ssl-error-bad-mac-alert = Вузол SSL повідомляє невірний Код засвідчення повідомлення.
ssl-error-bad-cert-alert = Вузол SSL не може перевірити ваш сертифікат.
ssl-error-revoked-cert-alert = Вузол SSL відхилив ваш сертифікат як відкликаний.
ssl-error-expired-cert-alert = Вузол SSL відхилив ваш сертифікат як застарілий.
ssl-error-ssl-disabled = Неможливо з’єднатись: SSL вимкнено.
ssl-error-fortezza-pqg = Неможливо з’єднатись: вузол SSL належить до іншого домену FORTEZZA.
ssl-error-unknown-cipher-suite = Вимагається невідомий пакет шифрів SSL.
ssl-error-bad-block-padding = SSL отримав запис з хибним заповненням блоку.
ssl-error-rx-record-too-long = SSL отримав запис що перевищує максимально допустиму довжину.
ssl-error-tx-record-too-long = SSL спробував надіслати запис що перевищує максимально допустиму довжину.
ssl-error-rx-malformed-hello-request = SSL отримав спотворене повідомлення рукостискання «Запит привітання».
ssl-error-rx-malformed-client-hello = SSL отримав спотворене повідомлення рукостискання «Привітання клієнта».
ssl-error-rx-malformed-server-hello = SSL отримав спотворене повідомлення рукостискання «Привітання сервера».
ssl-error-rx-malformed-certificate = SSL отримав спотворене повідомлення рукостискання «Сертифікат».
ssl-error-rx-malformed-server-key-exch = SSL отримав спотворене повідомлення рукостискання «Обмін ключами сервера».
ssl-error-rx-malformed-cert-request = SSL отримав спотворене повідомлення рукостискання «Запит сертифікату».
ssl-error-rx-malformed-hello-done = SSL отримав спотворене повідомлення рукостискання «Привітання сервера завершено».
ssl-error-rx-malformed-cert-verify = SSL отримав спотворене повідомлення рукостискання «Перевірка сертифікату».
ssl-error-rx-malformed-client-key-exch = SSL отримав спотворене повідомлення рукостискання «Обмін ключами клієнта».
ssl-error-rx-malformed-finished = SSL отримав спотворене повідомлення рукостискання «Завершено».
ssl-error-rx-malformed-alert = SSL отримав спотворений запис «Тривога».
ssl-error-rx-malformed-handshake = SSL отримав спотворений запис «Рукостискання».
ssl-error-rx-malformed-application-data = SSL отримав спотворений запис «Прикладні дані».
ssl-error-rx-unexpected-hello-request = SSL отримав неочікуване повідомлення рукостискання «Запит привітання».
ssl-error-rx-unexpected-client-hello = SSL отримав неочікуване повідомлення рукостискання «Привітання клієнта».
ssl-error-rx-unexpected-server-hello = SSL отримав неочікуване повідомлення рукостискання «Привітання сервера».
ssl-error-rx-unexpected-certificate = SSL отримав неочікуване повідомлення рукостискання «Сертифікат».
ssl-error-rx-unexpected-server-key-exch = SSL отримав неочікуване повідомлення рукостискання «Обмін ключами сервера».
ssl-error-rx-unexpected-cert-request = SSL отримав неочікуване повідомлення рукостискання «Запит сертифікату».
ssl-error-rx-unexpected-hello-done = SSL отримав неочікуване повідомлення рукостискання «Привітання сервера завершено».
ssl-error-rx-unexpected-cert-verify = SSL отримав неочікуване повідомлення рукостискання «Перевірка сертифікату».
ssl-error-rx-unexpected-client-key-exch = SSL отримав неочікуване повідомлення рукостискання «Обмін ключами клієнта».
ssl-error-rx-unexpected-finished = SSL отримав неочікуване повідомлення рукостискання «Завершено».
ssl-error-rx-unexpected-alert = SSL отримав неочікуваний запис «Тривога».
ssl-error-rx-unexpected-handshake = SSL отримав неочікуваний запис «Рукостискання».
ssl-error-rx-unexpected-application-data = SSL отримав неочікуваний запис «Прикладні дані».
ssl-error-rx-unknown-record-type = SSL отримав запис з невідомим типом змісту.
ssl-error-rx-unknown-handshake = SSL отримав повідомлення рукостискання невідомого типу.
ssl-error-rx-unknown-alert = SSL отримав запис «Тривога» з невідомим описом тривоги.
ssl-error-close-notify-alert = Вузол SSL закрив це з’єднання.
ssl-error-handshake-unexpected-alert = Вузол SSL не очікував отриманого повідомлення рукостискання.
ssl-error-decompression-failure-alert = Вузол SSL не зміг успішно розпакувати отриманий запис SSL.
ssl-error-handshake-failure-alert = Вузол SSL не зміг домовитись про прийнятний набір параметрів безпеки.
ssl-error-illegal-parameter-alert = Вузол SSL відхилив повідомлення рукостискання через неприйнятний вміст.
ssl-error-unsupported-cert-alert = Вузол SSL не підтримує сертифікати того типу що він щойно отримав.
ssl-error-certificate-unknown-alert = Вузол SSL має якусь проблему з сертифікатами того типу що він щойно отримав.
ssl-error-generate-random-failure = Генератор випадкових чисел у SSL зазнав збою.
ssl-error-server-key-exchange-failure = Невказана відмова під час обробки рукостискання SSL «Обмін ключами сервера».
ssl-error-client-key-exchange-failure = Невказана відмова під час обробки рукостискання SSL «Обмін ключами клієнта».
ssl-error-encryption-failure = Алгоритм групового шифрування дав збій на вибраному пакеті шифрів.
ssl-error-decryption-failure = Алгоритм групового дешифрування дав збій на вибраному пакеті шифрів.
ssl-error-socket-write-failure = Спроба запису шифрованих даних у сокет нижнього рівня провалилась.
ssl-error-sha-digest-failure = Функція SHA-1 дала збій.
ssl-error-mac-computation-failure = Обчислення MAC завершено невдало.
ssl-error-sym-key-context-failure = Відмова при створенні симетричного ключового контексту.
ssl-error-sym-key-unwrap-failure = Відмова при створенні симетричного ключа в повідомленні обміну клієнтськими ключами.
ssl-error-pub-key-size-limit-exceeded = SSL Сервер намагався використовувати публічний ключ внутрішнього рівня з набором експортних шифрів.
ssl-error-init-cipher-suite-failure = Невдача ініціалізації вибраного набору шифрів.
ssl-error-session-key-gen-failure = Невдача генерації ключів сесії для сесії SSL.
ssl-error-no-server-key-for-alg = Сервер не має ключа для виконаного алгоритму обміну ключами.
ssl-error-token-insertion-removal = PKCS#11 знак був вставлений або видалений, поки операція була в прогресі.
ssl-error-token-slot-not-found = No PKCS#11 неможливо знайти знак для виконання необхідної операції.
ssl-error-handshake-not-completed = Неможливо ініціювати інше SSL рукостискання доки поточне з’єднання не закінчилось.
ssl-error-bad-handshake-hash-value = Отримано некоректне значення хешу рукостискання від вузла.
ssl-error-cert-kea-mismatch = Забезпечене свідоцтво не може використовуватися з вибраним алгоритмом обміну ключами.
ssl-error-no-trusted-ssl-client-ca = Жодному центру сертифікації не довірено автентифікацію SSL клієнта.
ssl-error-session-not-found = Ідентифікатора SSL сесії клієнта не знайдено в кеші сесії сервера.
ssl-error-decryption-failed-alert = Вузол не зміг розшифрувати SSL запис який він отримав.
ssl-error-record-overflow-alert = Вузол отримав SSL запис який був довший ніж дозволяється.
ssl-error-unknown-ca-alert = Вузол не знає і не довіряє центру сертифікації що видав ваш сертифікат.
ssl-error-access-denied-alert = Вузол отримав дійсний сертифікат, але доступ був заборонений.
ssl-error-decode-error-alert = Вузол не зміг декодувати повідомлення SSL рукостискання.
ssl-error-decrypt-error-alert = Вузол повідомляє невдачу перевірки підпису або обміну ключами.
ssl-error-export-restriction-alert = Вузол повідомляє що узгодження не відповідають правилам експорту.
ssl-error-protocol-version-alert = Вузол повідомляє несумісну версію протоколу, або таку що не підтримується.
ssl-error-internal-error-alert = Вузол повідомляє що виникла внутрішня помилка.
ssl-error-user-canceled-alert = Користувач вузла перервав рукостискання.
ssl-error-no-renegotiation-alert = Вузол не допускає перегляд параметрів безпеки SSL.
ssl-error-server-cache-not-configured = Кеш SSL сервера не налаштований і не вимкнений для цього сокета.
ssl-error-unsupported-extension-alert = Вузол SSL не підтримує запитаного розширення привітання TLS.
ssl-error-certificate-unobtainable-alert = Вузол SSL не зміг отримати ваш сертифікат з наданого URL.
ssl-error-unrecognized-name-alert = Вузол SSL не має сертифікатів для ім’я DNS що запитувалось.
sec-error-io = Під час авторизації безпеки виникла помилка вводу/виводу.
sec-error-bad-data = бібліотека безпеки: отримано неправильні дані.
sec-error-output-len = бібліотека безпеки: помилка вихідної довжини.
sec-error-input-len = бібліотека безпеки отримала помилку вхідної довжини.
sec-error-invalid-args = бібліотека безпеки: неправильні аргументи.
sec-error-invalid-algorithm = бібліотека безпеки: неправильний алгоритм.
sec-error-invalid-ava = бібліотека безпеки: неправильна AVA.
sec-error-invalid-time = неналежно форматована стрічка часу.
sec-error-bad-der = бібліотека безпеки: неналежно форматоване DER-encoded повідомлення.
sec-error-bad-signature = Сертифікат має має нечинну сиґнатуру.
sec-error-expired-certificate = Сертифікат вузла застарів.
sec-error-revoked-certificate = Сертифікат вузла був відкликаний.
sec-error-bad-key = Публічний ключ вузла неправильний.
sec-error-bad-password = Пароль введено неправильно.
sec-error-retry-password = Новий пароль введено неправильно. Будь ласка, спробуйте ще раз.
sec-error-no-nodelock = бібліотека безпеки: no nodelock.
sec-error-bad-database = бібліотека безпеки: неправильна база даних.
sec-error-untrusted-issuer = Центр сертифікації до видав сертифікат вузла позначено користувачем як не вартий довіри.
sec-error-untrusted-cert = Сертифікат вузла позначено користувачем як не вартий довіри.
sec-error-duplicate-cert = Сертифікат вже присутній в вашій базі даних.
sec-error-cert-valid = Цей сертифікат дійсний.
sec-error-cert-not-valid = Цей сертифікат недійсний.
sec-error-crl-invalid = Новий список відкликаних сертифікатів має нечинний формат.
sec-internal-only = **Модуль ВИКЛЮЧНО для внутрішнього вжитку**
sec-error-invalid-key = Ключ не підтримує запитану операцію.
sec-error-unknown-critical-extension = Сертифікат містить невідом важливе розширення.
sec-error-old-crl = Новий список відкликаних сертифікатів не пізніший за поточний.
sec-error-no-recipient-certs-query = Не зашифровано: ви не маєте сертифікатів для кожного з отримувачів.
sec-error-not-a-recipient = Неможливо розшифрувати: ви не є отримувачем, або відповідні сертифікат та приватний ключ не знайдені.
sec-error-pkcs7-keyalg-mismatch = Неможливо розшифрувати: ключовий алгоритм шифрування не відповідає вашому сертифікату.
sec-error-unsupported-keyalg = Непідтримуваний або невідомий ключовий алгоритм.
sec-error-decryption-disallowed = Неможливо розшифрувати: шифрування використовує заборонений алгоритм або розмір ключа.
xp-sec-fortezza-no-card = Картки Fortezza не знайдені
xp-sec-fortezza-none-selected = Жодної картки Fortezza не вибрано
xp-sec-fortezza-person-not-found = Особистість не знайдено
xp-sec-fortezza-bad-pin = Неправильний Pin
xp-sec-fortezza-person-error = Не вдалось ініціалізувати особистості Fortezza
sec-error-krl-expired = KRL на сертифікат цього сайту застарів.
sec-error-krl-bad-signature = KRL на сертифікат цього сайту має неправильний підпис.
sec-error-revoked-key = Ключ на сертифікат цього сайту було відкликано.
sec-error-krl-invalid = Новий KRL ма неправильний формат.
sec-error-no-module = бібліотека безпеки: жоден модуль безпеки не здатен виконати запитану операцію.
sec-error-no-token = Картка чи жетон безпеки не існує, потребує ініціалізації чи була вилучена.
sec-error-read-only = бібліотека безпеки: база даних тільки для читання.
sec-error-no-slot-selected = Жодного роз’єму чи жетону не вибрано.
sec-error-cert-nickname-collision = Сертифікат з тим же прізвиськом вже існує.
sec-error-key-nickname-collision = Ключ з тим же прізвиськом вже існує.
sec-error-safe-not-created = помилка створення безпечного об’єкту
sec-error-baggage-not-created = помилка створення багажного об’єкту
xp-java-remove-principal-error = Не можу вилучити принципала
sec-error-bad-export-algorithm = Запитаний алгоритм не дозволено.
sec-error-exporting-certificates = Помилка під час спроби експортувати сертифікати.
sec-error-importing-certificates = Помилка під час спроби імпортувати сертифікати.
sec-error-pkcs12-decoding-pfx = Неможливо імпортуватиt. Помилка декодування. Файл неправильний.
sec-error-pkcs12-invalid-mac = Неможливо імпортувати. Хибний MAC.  Неправильний пароль або зіпсований файл.
sec-error-pkcs12-unsupported-mac-algorithm = Неможливо імпортувати.  Алгоритм MAC не підтримується.
sec-error-pkcs12-unsupported-transport-mode = Неможливо імпортувати. Підтримуються лише режими цілісності паролів та приватності.
sec-error-pkcs12-corrupt-pfx-structure = Неможливо імпортувати. Пошкоджена структура файлу.
sec-error-pkcs12-unsupported-pbe-algorithm = Неможливо імпортувати. Алгоритм шифрування не підтримується.
sec-error-pkcs12-unsupported-version = Неможливо імпортувати.  Версія файлу не підтримується.
sec-error-pkcs12-privacy-password-incorrect = Неможливо імпортувати.  Неправильний пароль приватності.
sec-error-pkcs12-cert-collision = Неможливо імпортувати.  Те ж прізвище вже існує в базі даних.
sec-error-user-cancelled = Користувач натиснув «скасувати».
sec-error-pkcs12-duplicate-data = Не імпортовано, вже в базі даних.
sec-error-message-send-aborted = Повідомлення не відіслано.
sec-error-pkcs12-unable-to-import-key = Неможливо імпортувати.  Помилка спроби імпортувати приватний ключ.
sec-error-pkcs12-unable-to-locate-object-by-name = Неможливо експортувати. Неможливо знайти сертифікат чи ключ за прізвиськом.
sec-error-pkcs12-unable-to-export-key = Неможливо експортувати.  Приватний ключ не вдалось знайти та експортувати.
sec-error-pkcs12-unable-to-write = Неможливо експортувати.  Неможливо писати у експортний файл.
sec-error-pkcs12-unable-to-read = Неможливо імпортувати.  Неможливо читати імпортований файл.
sec-error-pkcs12-key-database-not-initialized = Неможливо експортувати. База даних ключів пошкоджена чи стерта.
sec-error-keygen-fail = Не можу створити пару публічний/приватний ключ.
sec-error-retry-old-password = Старий пароль введено неправильно. Спробуйте ще раз.
sec-error-bad-nickname = Псевдонім сертифіката вже використовується.
sec-error-not-fortezza-issuer = Вузол у ланцюгу FORTEZZA має не-FORTEZZA сертифікат.
sec-error-cannot-move-sensitive-key = Чутливий ключ не може бути переміщений у те гніздо де він потрібен.
sec-error-js-invalid-module-name = Недійсне ім’я модуля.
sec-error-js-invalid-dll = Недійсний шлях/ім’я модуля
sec-error-js-add-mod-failure = Неможливо додати модуль
sec-error-js-del-mod-failure = Неможливо вилучити модуль
sec-error-old-krl = Новий KRL не старший за поточний.
sec-error-unknown-cert = Запитаний сертифікат не вдалось знайти.
sec-error-unknown-signer = Сертифікат підписувача не вдалось знайти.
sec-error-cert-bad-access-location = Розташування серверу статусів сертифікатів має хибний формат.
sec-error-ocsp-unknown-response-type = Відповідь OCSP неможливо декодувати, вона невідомого типу.
sec-error-ocsp-bad-http-response = Сервер OCSP повернув неочікувані/хибні  HTTP дані.
sec-error-ocsp-malformed-request = Сервер OCSP вважає запит спотвореним або невірно сформованим.
sec-error-ocsp-server-error = Сервер OCSP потерпів від внутрішньої помилки.
sec-error-ocsp-try-server-later = Сервер OCSP радить спробувати пізніше.
sec-error-ocsp-request-needs-sig = Сервер OCSP вимагає підпис на цей запит.
sec-error-ocsp-unknown-response-status = Сервер OCSP повернув нерозпізнаний статус.
sec-error-ocsp-not-enabled = Ви повинні увімкнути OCSP перед виконанням цієї операції.
sec-error-ocsp-no-default-responder = Ви повинні встановити типового респондента  OCSP перед виконанням цієї операції.
sec-error-ocsp-malformed-response = Відповідь від сервера OCSP була спотворена або невірно сформована.
sec-error-ocsp-unauthorized-response = Підписувач відповіді OCSP не вповноважений повідомляти статус цього сертифіката.
sec-error-ocsp-future-response = Відповідь OCSP ще не дійсна (містить дату у майбутньому).
sec-error-ocsp-old-response = Відповідь OCSP містить застарілу інформацію.
sec-error-unsupported-message-type = CMS з PKCS #7 Тип повідомлення не підтримується.
sec-error-module-stuck = PKCS #11 модуль не може бути вилучено оскільки він все ще використовується.
sec-error-bad-template = Не можливо декодувати дані ASN.1. Вказаний шаблон є хибним.
sec-error-crl-not-found = Жодного відповідного CRL не знайдено.
sec-error-busy = NSS не зміг завершитись. Об’єкти все ще використовуються.
sec-error-unsupported-elliptic-curve = Непідтримувана еліптична крива.
sec-error-unsupported-ec-point-form = Непідтримувана форма точки еліптичної кривої.
sec-error-unknown-object-type = Вказано об’єкт невідомого типу
sec-error-incompatible-pkcs11 = Драйвер PKCS #11 порушує специфікацію у несумісний спосіб.
sec-error-crl-already-exists = CRL вже існує.
sec-error-not-initialized = NSS не ініціалізовано.
sec-error-ocsp-responder-cert-invalid = Сертифікат настроєного відповідача OCSP неправильний.
sec-error-ocsp-bad-signature = Відповідь OCSP має неправильний підпис.
