# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

report-broken-site-mainview-title = Повідомити про пошкоджений сайт
report-broken-site-panel-header =
    .label = Повідомити про пошкоджений сайт
    .title = Повідомити про пошкоджений сайт
report-broken-site-panel-intro-text = Ваш звіт допомагає нам проаналізувати й усунути проблеми в { -brand-product-name }, щоб зробити його кращим для всіх.
report-broken-site-panel-learn-more-link = Докладніше
report-broken-site-panel-intro = Допоможіть зробити { -brand-product-name } кращим для всіх. { -vendor-short-name } використовує інформацію, яку ви надсилаєте, для вирішення проблем з вебсайтами.
report-broken-site-panel-url = URL
report-broken-site-panel-reason-label = Що не так?
report-broken-site-panel-reason-optional-label = Що не так? (необов'язково)
report-broken-site-panel-reason-choose =
    .label = Виберіть причину
report-broken-site-panel-reason-load =
    .label = Сайт не завантажується
# These terms are referring to ecommerce websites
report-broken-site-panel-reason-checkout =
    .label = Неможливо сплатити, оформити замовлення або зробити покупку
report-broken-site-panel-reason-slow2 =
    .label = Сайт працює повільно
report-broken-site-panel-reason-media2 =
    .label = Відео не відтворюється або не завантажується
report-broken-site-panel-reason-content2 =
    .label = Відсутній вміст
report-broken-site-panel-reason-account2 =
    .label = Неможливо ввійти або зареєструватися
report-broken-site-panel-reason-adblocker2 =
    .label = Сайт вимагає вимкнути блокувальник реклами
report-broken-site-panel-reason-notsupported =
    .label = Браузер не підтримується або блокується
report-broken-site-panel-reason-other =
    .label = Щось інше
report-broken-site-panel-description-label = Опишіть проблему
report-broken-site-panel-description =
    .placeholder = Що сталося? Що мало статися? Чи допомогло вимкнення захисту від відстеження?
report-broken-site-panel-description-optional-label = Опишіть проблему (необов'язково)
report-broken-site-panel-send-more-info-link = Надішліть більше інформації
report-broken-site-panel-button-cancel =
    .label = Скасувати
report-broken-site-panel-button-okay =
    .label = Гаразд
report-broken-site-panel-button-send =
    .label = Надіслати
report-broken-site-panel-report-sent-label = Ваш звіт надіслано
report-broken-site-panel-report-sent-header =
    .label = Ваш звіт надіслано
    .title = Ваш звіт надіслано
report-broken-site-panel-report-sent-text = Дякуємо, що допомагаєте { -brand-product-name } зробити Інтернет більш відкритим, доступним і кращим для всіх.
report-broken-site-panel-invalid-url-label = Введіть дійсний URL
report-broken-site-panel-missing-reason-label = Виберіть причину
report-broken-site-panel-blocked-trackers-label =
    .label = Надсилати URL-адреси, заблоковані захистом від стеження
report-broken-site-panel-blocked-trackers-description = Розширений захист від стеження може блокувати елементи, необхідні для належної роботи деяких вебсайтів.
report-broken-site-panel-preview-button =
    .label = Переглянути звіт
report-broken-site-panel-preview-header =
    .label = Переглянути звіт
