# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

certmgr-title =
    .title = सार्टिफिकेट मेनेजार
certmgr-tab-mine =
    .label = नोंथांनि सार्टिफिकेटफोर
certmgr-tab-people =
    .label = सुबुं
certmgr-tab-servers =
    .label = सार्भारफोर
certmgr-tab-ca =
    .label = अथ'रिटि
certmgr-edit-ca-cert2 =
    .title = CA सार्टिफिकेट फोथायनाय सेटिंखौ सुजु
    .style = min-width: 48em;
certmgr-edit-cert-edit-trust = फोथायनाय सेटिंखौ सुजु:
certmgr-edit-cert-trust-ssl =
    .label = बे सार्टिफिकेटा वेबसाइटफोरखौ सिनायथिनो हायो।
certmgr-edit-cert-trust-email =
    .label = बे सार्टिफिकेटआ मेइल बाहायग्राफोरखौ सिनायथिनो हायो।
certmgr-delete-cert2 =
    .title = सार्टिफिकेट खोमोर
    .style = min-width: 48em; min-height: 24em;
certmgr-cert-name =
    .label = सार्टिफिकेटनि मुं
certmgr-cert-server =
    .label = सार्भार
certmgr-token-name =
    .label = रैखाथि डिभाइस
certmgr-begins-label =
    .label = आव जागायो
certmgr-expires-label =
    .label = ..आव मेयाद बारलाङो
certmgr-email =
    .label = इ-मेइल थं
certmgr-serial =
    .label = फारि अनजिमा
certmgr-view =
    .label = नुथाय...
    .accesskey = V
certmgr-edit =
    .label = फोथायनायखौ सुजु...
    .accesskey = E
certmgr-export =
    .label = दैथाय हर...
    .accesskey = x
certmgr-delete =
    .label = खोमोर...
    .accesskey = D
certmgr-delete-builtin =
    .label = खोमोर एबा फोथायनो नाङा...
    .accesskey = D
certmgr-backup =
    .label = बेकआप ला...
    .accesskey = B
certmgr-backup-all =
    .label = गासैखौबो बेकआप ला...
    .accesskey = k
certmgr-restore =
    .label = लाबो...
    .accesskey = m
certmgr-add-exception =
    .label = एंगारथायखौ दाजाबदेर...
    .accesskey = x
exception-mgr =
    .title = रैखाथि एंगारथायखौ दाजाबदेर
exception-mgr-extra-button =
    .label = रैखाथि एंगारथायखौ रोखा खालाम
    .accesskey = C
exception-mgr-supplemental-warning = आइनजों गोरोबनाय बेंक, बाख्रि आरो गुबुन राइजो-राजानि साइटआ नोंथांखौ बेबाइदि खालामनो थिननाय नङा।
exception-mgr-cert-location-url =
    .value = जायगा:
exception-mgr-cert-location-download =
    .label = सार्टिफिकेट मोन
    .accesskey = G
exception-mgr-cert-status-view-cert =
    .label = नुथाय...
    .accesskey = V
exception-mgr-permanent =
    .label = बे एंगारथायखौ जुगामियै स्टर खालाम
    .accesskey = P
pk11-bad-password = हाबहोनाया पासवर्डआ गोरोन्थि।
pkcs12-decode-err = फाइलखौ डिक'ड खालामनो फेलें जाबाय। बेयो PKCS #12 फरमेटआव नङा, एबा गाज्रि खालामबाय, एबा नोंथाङा हाबहोनाय पासवार्डआ गोरोन्थिमोन।
pkcs12-unknown-err-restore = मोनथिमोनै जाहोननि थाखाय PKCS #12 फाइलखौ लाबोफिननो फेलें जाबाय।
pkcs12-unknown-err-backup = मोनथिमोनै जाहोननि थाखाय PKCS #12 बेकआप फाइलखौ सोरजिनो फेलें जाबाय।
pkcs12-unknown-err = मोनथिमोनै जाहोननि थाखाय PKCS #12 अपारेसन फेलें जाबाय।
pkcs12-info-no-smartcard-backup = स्मार्ट कार्ड बाइदि मोनसे हार्डवेयार रैखाथि डिभाइस निफ्राय सार्टिफिकेटखौ बेकआप लानो सम्भाव नङा।
pkcs12-dup-data = चार्टिफिकेट आरो प्राइभेट साबिआ सिगाङावनो रैखाथि डिभाइसयाव दङ।

## For Deleting Certificates

delete-email-cert-confirm = नोंथाङा थारैनो बे सार्टिफिकेटखौ खोमोरनो सानो नामा?
