# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = Laman ini sedang diarah ke lokasi baru. Adakah anda ingin hantar semula bentuk data yang anda taip ke lokasi yang baru?
# Directory listing strings
DirTitle = Indeks %1$S
DirGoUp = Naik sehingga paras teratas direktori
ShowHidden = Papar objek tersorok
DirColName = Nama
DirColSize = Saiz
DirColMTime = Terakhir Diubah
DirFileLabel = Fail:
UnsafeUriBlocked = The resource at “%1$S” was blocked by Safe Browsing.
CookieBlockedByPermission = Permintaan untuk mengakses kuki atau storan ke “%1$S” telah disekat kerana penyesuaian keizinan kuki.
CookieBlockedAll = Permintaan untuk mengakses kuki atau storan ke “%1$S” telah disekat kerana kami menyekat semua permintaan mengakses storan.
