# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Nachschlagen von { $host }…
network-connection-status-connected = Verbunden mit { $host }…
network-connection-status-sending-request = Senden der Anfrage an { $host }…
network-connection-status-transferring-data = Übertragen der Daten von { $host }…
network-connection-status-connecting = Verbinden mit { $host }…
network-connection-status-read = { $host } gelesen
network-connection-status-wrote = { $host } geschrieben
network-connection-status-waiting = Warten auf { $host }…
network-connection-status-looked-up = { $host } nachgeschlagen…
network-connection-status-tls-handshake = TLS-Handshake mit { $host } wird durchgeführt…
network-connection-status-tls-handshake-finished = TLS-Handshake mit { $host } wurde abgeschlossen…
