# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = Otevřít
    .accesskey = O
places-open-tab =
    .label = Otevřít v novém panelu
    .accesskey = p
places-open-all-in-tabs =
    .label = Otevřít vše v panelech
    .accesskey = p
places-open-window =
    .label = Otevřít v novém okně
    .accesskey = t
places-open-private-window =
    .label = Otevřít v novém anonymním okně
    .accesskey = a
places-new-bookmark =
    .label = Nová záložka…
    .accesskey = N
places-new-folder-contextmenu =
    .label = Nová složka…
    .accesskey = s
places-new-folder =
    .label = Nová složka…
    .accesskey = v
places-new-separator =
    .label = Nový oddělovač
    .accesskey = d
places-view =
    .label = Zobrazit
    .accesskey = Z
places-by-date =
    .label = Podle data
    .accesskey = d
places-by-site =
    .label = Podle názvu stránky
    .accesskey = s
places-by-most-visited =
    .label = Podle počtu návštěv
    .accesskey = n
places-by-last-visited =
    .label = Podle poslední návštěvy
    .accesskey = P
places-by-day-and-site =
    .label = Podle data a serveru
    .accesskey = a
places-delete-domain-data =
    .label = Odebrat celý web
    .accesskey = w
places-sortby-name =
    .label = Seřadit podle názvu
    .accesskey = S
places-properties =
    .label = Vlastnosti
    .accesskey = V
