# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Zaman aşımı
openFile = Dosya aç
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = “%2$S” sözünü %1$S ile ara
contextMenuSearch.accesskey = a
contextMenuPrivateSearch = Gizli pencerede ara
contextMenuPrivateSearch.accesskey = G
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Gizli pencerede %S ile ara
contextMenuPrivateSearchOtherEngine.accesskey = G
bookmarkAllTabsDefault = [Klasör adı]
unsignedAddonsDisabled.message = Yüklü eklentilerden biri veya birkaçı doğrulanamadığı için devre dışı bırakıldı.
unsignedAddonsDisabled.learnMore.label = Daha fazla bilgi alın
unsignedAddonsDisabled.learnMore.accesskey = D
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Son erişim: %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = %S:// bağlantıları
crashedpluginsMessage.title = %S yan uygulaması çöktü.
crashedpluginsMessage.reloadButton.label = Sayfayı tazele
crashedpluginsMessage.reloadButton.accesskey = S
crashedpluginsMessage.submitButton.label = Çökme raporu gönder
crashedpluginsMessage.submitButton.accesskey = r
crashedpluginsMessage.learnMore = Daha fazla bilgi al…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = %S adresine mi gitmek istemiştiniz?
keywordURIFixup.goTo = Evet, %S adresine git
keywordURIFixup.goTo.accesskey = E
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = %S sürümüne güncelle
update.downloadAndInstallButton.accesskey = s
menuOpenAllInTabs.label = Tümünü sekmelerde aç
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Sayfayı tazele
tabHistory.goBack = Bu sayfaya geri git
tabHistory.goForward = Bu sayfaya doğru git
# URL Bar
pasteAndGo.label = Yapıştır ve git
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Geçerli sayfayı tazele (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Sayfayı yüklemeyi durdur (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Yakınlaştırma düzeyini sıfırla (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Okuyucu görünümünü aç/kapat (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %%%S
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %%%S, Yakınlaştırma düzeyini sıfırla
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Yer imlerimi göster (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Devam eden indirme işlemlerinin durumunu göster (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Yeni bir pencere aç (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Yeni sekme aç (%S)
newTabContainer.tooltip = Yeni sekme aç (%S)\nYeni bir kapsayıcı sekme açmak için basılı tutun
newTabAlwaysContainer.tooltip = Yeni sekme açmak için kapsayıcı seçin
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = %S HTML5 canvas görsel verilerinizi kullanabilsin mi?
canvas.siteprompt2.warning = Bu izin, bilgisayarınızı benzersiz bir şekilde tanımlamak için kullanılabilir.
canvas.block = Engelle
canvas.block.accesskey = E
canvas.allow2 = İzin ver
canvas.allow2.accesskey = z
canvas.remember2 = Bu kararı hatırla
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Doğrulayan: %S
identity.identified.verified_by_you = Bu siteye güvenlik ayrıcalığı tanıdınız.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Sertifika sahibi: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Güvenli değil
identity.notSecure.tooltip = Bağlantı güvenli değil
identity.extension.label = Uzantı (%S)
identity.extension.tooltip = %S uzantısı tarafından yüklendi
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Uzaklaştır (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Yakınlaştırma düzeyini sıfırla (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Yakınlaştır (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Kes (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Kopyala (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Yapıştır (%S)
geolocation.allow = İzin ver
geolocation.allow.accesskey = z
geolocation.block = Engelle
geolocation.block.accesskey = E
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Sisteminizin konum ayarları açılacaktır. Lütfen %S uygulamasına konum izni verin.
geolocation.shareWithSite4 = %S konumunuza erişebilsin mi?
geolocation.shareWithFile4 = Bu yerel dosya konumunuza erişebilsin mi?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = %1$S %2$S sitesinin konumunuza erişmesine izin versin mi?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Sistem ayarlarından %S uygulamasına konum izni verin.
geolocation.systemSettingsTitle = Konum izni bekleniyor
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Sistem %S uygulamasına bu izni vermenizi isteyecek.
geolocation.remember = Bu kararı hatırla
# Virtual Reality Device UI
xr.allow2 = İzin ver
xr.allow2.accesskey = z
xr.block = Engelle
xr.block.accesskey = E
xr.shareWithSite4 = %S sanal gerçeklik cihazlarına erişebilsin mi? Hassas bilgileriniz de paylaşılabilir.
xr.shareWithFile4 = Bu yerel dosya sanal gerçeklik cihazlarına erişebilsin mi? Hassas bilgileriniz de paylaşılabilir.
xr.remember = Bu kararı hatırla
# Persistent storage UI
persistentStorage.allow = İzin ver
persistentStorage.allow.accesskey = z
persistentStorage.block.label = Engelle
persistentStorage.block.accesskey = E
persistentStorage.allowWithSite2 = %S kalıcı depolama alanında veri depolayabilsin mi?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = İzin ver
webNotifications.allow2.accesskey = z
webNotifications.notNow = Şimdi değil
webNotifications.notNow.accesskey = D
webNotifications.never = Asla izin verme
webNotifications.never.accesskey = A
webNotifications.alwaysBlock = Her zaman engelle
webNotifications.alwaysBlock.accesskey = E
webNotifications.block = Engelle
webNotifications.block.accesskey = E
webNotifications.receiveFromSite3 = %S bildirim gönderebilsin mi?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S bu cihazdaki diğer uygulama ve hizmetlere erişmek istiyor.
localhost.remember2 = Bu sitedeki seçimimi hatırla
localhost.allowlabel = İzin ver
localhost.blocklabel = Engelle
localhost.allow.accesskey = z
localhost.block.accesskey = E
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S yerel ağınıza bağlı cihazlardaki uygulama ve hizmetlere erişmek istiyor.
localNetwork.remember2 = Bu sitedeki seçimimi hatırla
localNetwork.allowLabel = İzin ver
localNetwork.allow.accesskey = z
localNetwork.blockLabel = Engelle
localNetwork.block.accesskey = E
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Beni buradan kurtar!
safebrowsing.getMeOutOfHereButton.accessKey = k
safebrowsing.deceptiveSite = Aldatıcı site!
safebrowsing.notADeceptiveSiteButton.label = Bu site aldatıcı değil…
safebrowsing.notADeceptiveSiteButton.accessKey = d
safebrowsing.reportedAttackSite = Saldırı sitesi olarak bildirilmiş!
safebrowsing.notAnAttackButton.label = Bu bir saldırı sitesi değil…
safebrowsing.notAnAttackButton.accessKey = d
safebrowsing.reportedUnwantedSite = İstenmeyen yazılım sitesi!
safebrowsing.reportedHarmfulSite = Bu sitenin zararlı olabileceği bildirildi!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = %S araması
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = %S sorun giderme modunda yeniden başlatılsın mı?
troubleshootModeRestartPromptMessage = Uzantılarınız, temalarınız ve özel ayarlarınız geçici olarak devre dışı bırakılacak.
troubleshootModeRestartButton = Yeniden başlat
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Bu sayfa %1$S tarayıcınızı yavaşlatıyor. Tarayıcınızı hızlandırmak için bu sayfayı durdurabilirsiniz.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Bir web sayfası %1$S tarayıcınızı yavaşlatıyor. Tarayıcınızı hızlandırmak için o sayfayı durdurabilirsiniz.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = “%1$S” %2$S tarayıcınızı yavaşlatıyor. Tarayıcınızı hızlandırmak için o sayfayı durdurabilirsiniz.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = “%1$S” %2$S tarayıcınızı yavaşlatıyor. Tarayıcınızı hızlandırmak için bu uzantıyı durdurabilirsiniz.
processHang.add-on.learn-more.text = Daha fazla bilgi al
processHang.button_stop2.label = Durdur
processHang.button_stop2.accessKey = D
processHang.button_debug.label = Betikte hata ayıkla
processHang.button_debug.accessKey = B
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Pencereyi tam ekran olarak göster (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Kenar çubuğunu sola taşı
sidebar.moveToRight = Kenar çubuğunu sağa taşı
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Bu sayfadaki bazı ses veya videoları oynatmak için DRM’i etkinleştirmelisiniz.
emeNotifications.drmContentDisabled.button.label = DRM’i etkinleştir
emeNotifications.drmContentDisabled.button.accesskey = D
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S bu sayfadaki ses ve videoyu oynatmak için gereken bileşenleri yüklüyor. Lütfen daha sonra tekrar deneyin.
emeNotifications.unknownDRMSoftware = Bilinmiyor
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = %S tarayıcısını özelleştir
decoder.noCodecs.button = Nasıl yapılacağını öğren
decoder.noCodecs.accesskey = N
decoder.noCodecsLinux.message = Video oynatmak için gereken video codec’lerini yüklemeniz gerekebilir.
decoder.noHWAcceleration.message = Video kalitesini yükseltmek için Microsoft’tan Media Feature Pack’i yüklemeniz gerekebilir.
decoder.noPulseAudio.message = Ses çalmak için gereken PulseAudio yazılımını yüklemeniz gerekebilir.
decoder.unsupportedLibavcodec.message = libavcodec güvenli değil veya desteklenmiyor. Video oynatmak için güncellenmesi gerekiyor.
decoder.decodeError.message = Bir multimedya kaynağı çözülürken hata oluştu.
decoder.decodeError.button = Site sorununu bildir
decoder.decodeError.accesskey = S
decoder.decodeWarning.message = Bir multimedya kaynağı çözülürken kurtarılabilir bir hata oluştu.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = İnternete erişebilmek için önce bu ağa giriş yapmalısınız.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Ağa giriş sayfasını aç
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = %S izinleri
permissions.remove.tooltip = Bu izni kaldır ve yeniden sor
permissions.fullscreen.promptCanceled = Bekleyen izin istekleri iptal edildi: İzin istekleri DOM tam ekrana geçmeden önce yapılmamalıdır.
permissions.fullscreen.fullScreenCanceled = DOM tam ekrandan çıkıldı: İzin istekleri DOM tam ekrandayken yapılmamalıdır.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64 bit
aboutDialog.architecture.thirtyTwoBit = 32 bit
midi.allow.label = İzin ver
midi.allow.accesskey = z
midi.block.label = Engelle
midi.block.accesskey = E
midi.remember = Bu kararı hatırla
midi.shareWithFile = Bu yerel dosya MIDI cihazlarınıza erişebilsin mi?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = %S MIDI cihazlarınıza erişebilsin mi?
midi.shareSysexWithFile = Bu yerel dosya MIDI cihazlarınıza erişebilsin ve SysEx mesajları alıp gönderebilsin mi?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = %S MIDI cihazlarınıza erişebilsin ve SysEx mesajları alıp gönderebilsin mi?
serial.allow.label = İzin ver
serial.allow.accesskey = z
serial.block.label = Engelle
serial.block.accesskey = E
serial.shareWithFile = Bu yerel dosya seri bağlantı noktalarınıza erişebilsin mi?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = %S seri bağlantı noktalarınıza erişebilsin mi?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Geri dön
storageAccess1.Allow.label = İzin ver
storageAccess1.Allow.accesskey = z
storageAccess1.DontAllow.label = Engelle
storageAccess1.DontAllow.accesskey = E
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = %1$S, çerezlerini %2$S sitesinde kullanabilsin mi?
storageAccess1.hintText = %1$S sitesinin bu veriye neden ihtiyaç duyduğunu bilmiyorsanız erişimi engelleyebilirsiniz.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = “%S” terimini web’de ara
