# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Importowy zastojnik
import-from =
    { PLATFORM() ->
        [windows] Nastajenja, cytańske znamjenja, historiju, gronidła a hynakše daty importěrowaś z:
       *[other] Nastajenja, cytańske znamjenja, historiju, gronidła a hynakše daty importěrowaś z:
    }
import-from-bookmarks = Cytańske znamjenja importěrowaś z:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-edge-legacy =
    .label = Microsoft Edge Legacy
    .accesskey = L
import-from-edge-beta =
    .label = Microsoft Edge Beta
    .accesskey = d
import-from-nothing =
    .label = Nic njeimportěrowaś
    .accesskey = N
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chrome-beta =
    .label = Chrome Beta
    .accesskey = B
import-from-chrome-dev =
    .label = Chrome Dev
    .accesskey = D
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = x
import-from-360se =
    .label = 360 Secure Browser
    .accesskey = 3
no-migration-sources = Žedne programy namakane, kótarež wopśimuju cytańske znamjenja, historiju abo gronidła.
import-source =
    .label = Daty a nastajenja importěrowaś
import-items-title =
    .label = Objekty za importěrowanje
import-items-description = Wubjeŕśo objekty za importěrowanje:
import-migrating-title =
    .label = Importěrujo se…
import-migrating-description = Slědujuce objekty se rowno importěruju…
import-select-profile-title =
    .label = Profil wubraś
import-select-profile-description = Slědujuce profile stoje k dispoziciji za importěrowanje z:
import-done-title =
    .label = Importěrowanje dokóńćone
import-done-description = Slědujuce objekty su se z wuspěchom importěrowali:
import-close-source-browser = Pšosym zawěsććo, až wubrany wobglědowak jo zacynjony, nježli až pókšacujośo.
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = Z { $source }
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-edge-beta = Microsoft Edge Beta
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chrome-beta = Google Chrome Beta
source-name-chrome-dev = Google Chrome Dev
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Secure Browser
imported-safari-reading-list = Cytańska lisćina (ze Safari)
imported-edge-reading-list = Cytańska lisćina (z Edge)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Internetne nastajenja
    .value = Internetne nastajenja
browser-data-edge-1 =
    .label = Nastajenja
    .value = Nastajenja
browser-data-safari-1 =
    .label = Nastajenja
    .value = Nastajenja
browser-data-chrome-1 =
    .label = Nastajenja
    .value = Nastajenja
browser-data-canary-1 =
    .label = Nastajenja
    .value = Nastajenja
browser-data-360se-1 =
    .label = Nastajenja
    .value = Nastajenja
browser-data-ie-2 =
    .label = Cookieje
    .value = Cookieje
browser-data-edge-2 =
    .label = Cookieje
    .value = Cookieje
browser-data-safari-2 =
    .label = Cookieje
    .value = Cookieje
browser-data-chrome-2 =
    .label = Cookieje
    .value = Cookieje
browser-data-canary-2 =
    .label = Cookieje
    .value = Cookieje
browser-data-firefox-2 =
    .label = Cookieje
    .value = Cookieje
browser-data-360se-2 =
    .label = Cookieje
    .value = Cookieje
browser-data-ie-4 =
    .label = Pśeglědowańska historija
    .value = Pśeglědowańska historija
browser-data-edge-4 =
    .label = Pśeglědowańska historija
    .value = Pśeglědowańska historija
browser-data-safari-4 =
    .label = Pśeglědowańska historija
    .value = Pśeglědowańska historija
browser-data-chrome-4 =
    .label = Pśeglědowańska historija
    .value = Pśeglědowańska historija
browser-data-canary-4 =
    .label = Pśeglědowańska historija
    .value = Pśeglědowańska historija
browser-data-firefox-history-and-bookmarks-4 =
    .label = Historija a cytańske znamjenja
    .value = Historija a cytańske znamjenja
browser-data-360se-4 =
    .label = Pśeglědowańska historija
    .value = Pśeglědowańska historija
browser-data-ie-8 =
    .label = Składowana formularna historija
    .value = Składowana formularna historija
browser-data-edge-8 =
    .label = Składowana formularna historija
    .value = Składowana formularna historija
browser-data-safari-8 =
    .label = Składowana formularna historija
    .value = Składowana formularna historija
browser-data-chrome-8 =
    .label = Składowana formularna historija
    .value = Składowana formularna historija
browser-data-canary-8 =
    .label = Składowana formularna historija
    .value = Składowana formularna historija
browser-data-firefox-8 =
    .label = Składowana formularna historija
    .value = Składowana formularna historija
browser-data-360se-8 =
    .label = Składowana formularna historija
    .value = Składowana formularna historija
browser-data-ie-16 =
    .label = Składowane gronidła
    .value = Składowane gronidła
browser-data-edge-16 =
    .label = Składowane gronidła
    .value = Składowane gronidła
browser-data-safari-16 =
    .label = Składowane gronidła
    .value = Składowane gronidła
browser-data-chrome-16 =
    .label = Składowane gronidła
    .value = Składowane gronidła
browser-data-canary-16 =
    .label = Składowane gronidła
    .value = Składowane gronidła
browser-data-firefox-16 =
    .label = Składowane gronidła
    .value = Składowane gronidła
browser-data-360se-16 =
    .label = Składowane gronidła
    .value = Składowane gronidła
browser-data-ie-32 =
    .label = Fawority
    .value = Fawority
browser-data-edge-32 =
    .label = Fawority
    .value = Fawority
browser-data-safari-32 =
    .label = Cytańske znamjenja
    .value = Cytańske znamjenja
browser-data-chrome-32 =
    .label = Cytańske znamjenja
    .value = Cytańske znamjenja
browser-data-canary-32 =
    .label = Cytańske znamjenja
    .value = Cytańske znamjenja
browser-data-360se-32 =
    .label = Cytańske znamjenja
    .value = Cytańske znamjenja
browser-data-ie-64 =
    .label = Druge daty
    .value = Druge daty
browser-data-edge-64 =
    .label = Druge daty
    .value = Druge daty
browser-data-safari-64 =
    .label = Druge daty
    .value = Druge daty
browser-data-chrome-64 =
    .label = Druge daty
    .value = Druge daty
browser-data-canary-64 =
    .label = Druge daty
    .value = Druge daty
browser-data-firefox-other-64 =
    .label = Druge daty
    .value = Druge daty
browser-data-360se-64 =
    .label = Druge daty
    .value = Druge daty
browser-data-firefox-128 =
    .label = Wokna a rejtariki
    .value = Wokna a rejtariki
