# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language-name-aa = Afar
language-name-ab = Abkhazia
language-name-ach = Acholi
language-name-ae = Avèsta
language-name-af = Afrikaans
language-name-ak = Akan
language-name-am = Amhar
language-name-an = Aragon
language-name-ar = Arab
language-name-as = Assam
language-name-ast = Asturia
language-name-av = Avar
language-name-ay = Aymara
language-name-az = Azèrbaijan
language-name-ba = Bashkir
language-name-be = Bèlarusia
language-name-bg = Bulgaria
language-name-bh = Bihari
language-name-bi = Bislama
language-name-bm = Bambara
language-name-bn = Banggali
language-name-bo = Tibèt
language-name-br = Brèton
language-name-bs = Bosnia
language-name-ca = Katalonia
language-name-cak = Kaqchikel
language-name-ce = Chèchnya
language-name-ch = Chamorro
language-name-co = Korsika
language-name-cr = Cree
language-name-crh = Tatar Krimèa
language-name-cs = Cèkô
language-name-da = Dènmark
language-name-de = Jeureuman
language-name-dv = Divèhi
language-name-dz = Dzongkha
language-name-el = Yunani
language-name-en = Inggréh
language-name-eo = Èspèranto
language-name-es = Seupanyo
language-name-et = Èstonia
language-name-eu = Basqué
language-name-fa = Parisi
language-name-ff = Fulah
language-name-fi = Finlandia
language-name-fj = Fiji
language-name-fo = Faroe
language-name-fr = Peurancih
language-name-fur = Friulia
language-name-fy = Frisia
language-name-ga = Irlandia
language-name-gl = Galicia
language-name-gn = Guarani
language-name-gu = Gujarat
language-name-gv = Manx
language-name-ha = Hausa
language-name-haw = Hawaii
language-name-he = Ibrani
language-name-hil = Hiligaynon
language-name-ho = Hiri Motu
language-name-hr = Kroasia
language-name-ht = Haiti
language-name-hu = Hongaria
language-name-hy = Armènia
language-name-hz = Hèrèro
language-name-ia = Interlingua
language-name-ie = Interlingué
language-name-ig = Igbo
language-name-ik = Inupiaq
language-name-is = Islandia
language-name-it = Itali
language-name-iu = Inuktitut
language-name-ja = Jeupun
language-name-jv = Jawa
language-name-ka = Gèorgia
language-name-kab = Kabyle
language-name-kg = Kongo
language-name-ki = Kikuyu
language-name-kj = Kuanyama
language-name-kk = Kazakh
language-name-kl = Greenland
language-name-km = Khmèr
language-name-kn = Kannada
language-name-ko = Korèa
language-name-kok = Konkani
language-name-kr = Kanuri
language-name-ks = Kashmiri
language-name-ku = Kurdi
language-name-kv = Komi
language-name-la = Latin
language-name-lg = Ganda
language-name-lt = Lituania
language-name-lv = Latvia
language-name-ml = Malayalam
language-name-mn = Mongolia
language-name-mt = Malta
language-name-my = Burma
language-name-na = Nauru
language-name-ne = Nèpali
language-name-no = Norwègia
language-name-pa = Punjabi
language-name-pl = Bahsa Polandia
language-name-pt = Bahsa Portugéh
language-name-ro = Bahsa Rumania
language-name-sk = Bahsa Slowakia
language-name-sq = Bahsa Albania
language-name-sr = Bahsa Sèrbia
