# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Salva
dialogTitleAddBookmark = Nuovo segnalibro
dialogTitleAddMulti = Nuovi segnalibri
dialogTitleEdit = Proprietà di “%S”
dialogTitleAddNewBookmark2 = Aggiungi segnalibro
dialogTitleEditBookmark = Modifica “%S”
dialogTitleEditBookmark2 = Modifica segnalibro
dialogTitleAddBookmarkFolder = Aggiungi cartella dei segnalibri
dialogTitleEditBookmarkFolder = Modifica cartella dei segnalibri
bookmarkAllTabsDefault = [Nome cartella]
newFolderDefault = Nuova cartella
newBookmarkDefault = Nuovo segnalibro
