# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Acerca dos seus direitos
rights-intro = O { -brand-full-name } é um software livre e de código aberto, construído por uma comunidade de milhares de pessoas por todo o mundo. Existem algumas coisas que deve saber:
rights-intro-point-3 = Algumas funcionalidades no { -brand-short-name }, tais como o relator de falhas, dão-lhe a opção de fornecer feedback à { -vendor-short-name }. Ao escolher enviar feedback, você dá à { -vendor-short-name } autorização para utilizar o feedback para melhorar os seus produtos, para publicar o feedback nos seus websites e para distribuir o feedback.
rights-intro-point-4 = Como é que usamos a sua informação pessoal e feedback enviados para a { -vendor-short-name } através do { -brand-short-name } é descrito na <a data-l10n-name="mozilla-privacy-policy-link">Política de privacidade do { -brand-short-name }</a>.
rights-intro-point-4-unbranded = Quaisquer políticas de privacidade aplicáveis a este produto devem ser colocadas aqui.
rights-safebrowsing-term-2 = Selecione a seleção de segurança
rights-safebrowsing-term-3 = Desmarque a opção para "{ enableSafeBrowsing-label }"
enableSafeBrowsing-label = Bloquear conteúdo perigoso e decetivo
rights-safebrowsing-term-4 = A navegação segura está agora desativada
rights-locationawarebrowsing-term-3 = Duplo clique na preferência geo.enabled
rights-locationawarebrowsing-term-4 = A navegação com conhecimento da localização está agora desativada
rights-webservices-term-1 = A { -vendor-short-name } os seus contribuidores, licenciantes e parceiros trabalham para fornecer os serviços mais precisos e atualizados.  No entanto, não podemos garantir que esta informação é abrangente e livre de erros.  Por exemplo, o serviço de navegação segura poderá não identificar alguns sites perigosos e identificar alguns sites seguros com erro e, no serviço de localização, todas as localizações devolvidas pelos nossos fornecedores do serviço são apenas estimativas e nem nós nem os nossos fornecedores do serviço garantimos a exatidão das localizações fornecidas.
rights-webservices-term-2 = A { -vendor-short-name } pode descontinuar ou alterar os serviços a qualquer momento.
rights-webservices-term-3 = Está à vontade para utilizar estes Serviços que acompanham a sua versão do { -brand-short-name }, e a { -vendor-short-name } concede-lhe os direitos necessários para o fazer.  A { -vendor-short-name } e os seus licenciantes reservam todos os outros direitos nos Serviços.  Estes termos não têm a intenção de limitar quaisquer direitos sobre as licenças de código aberto aplicáveis ao { -brand-short-name } e às correspondentes versões do código fonte do { -brand-short-name }.
rights-webservices-term-4 = <strong>Os serviços são disponibilizados "as-is."  A { -vendor-short-name }, os seus contribuidores, licenciantes e distribuidores renunciam a todas as garantias, sejam elas explícitas ou implícitas, incluindo sem limites, garantias que o serviço é comercial e serve para os seus objetivos pessoais.  Você é responsável por selecionar os serviços para os seus propósitos, assim como a qualidade e o desempenho dos serviços. Algumas jurisdições não permitem a exclusão ou a limitação de garantias implícitas, como tal este aviso poderá não ser adequado para si.</strong>
rights-webservices-term-5 = <strong>Exceto quando obrigatório por lei, a { -vendor-short-name }, os seus contribuidores, licenciantes e distribuidores não poderão ser responsabilizados por qualquer dano indireto, especial, acidental, consequente, punitivo, exemplares ou danos diretos decorrentes da utilização do { -brand-short-name } e os seus serviços.  A responsabilidade coletiva sob estes termos, não poderá exceder $500 (quinhentos dólares). Algumas jurisdições não permitem a exclusão ou a limitação de alguns danos e, como tal, esta exclusão e limitação poderá não ser aplicável a si.</strong>
rights-webservices-term-6 = A { -vendor-short-name } poderá atualizar os termos conforme necessário de tempos a tempos. Estes termos não poderão ser alterados ou cancelados sem o acordo escrito da { -vendor-short-name }.
rights-webservices-term-7 = Estes termos são regidos pelas leis do estado da Califórnia, E.U.A., excluindo conflitos de provisão de leis. Se algum destes termos for identificado como inválido ou sem valor jurídico, as restantes porções manterão a sua força e efeito. No evento de um conflito entre uma versão traduzida destes termos e a versão em Inglês, a versão em Inglês é a que prevalece.
