# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Siriwat Aumngamsup</em:contributor> <em:contributor>Chakard Chalayut</em:contributor> <em:contributor>Jittat Fakcharoenphol</em:contributor> <em:contributor>Isriya Paireepairit</em:contributor> <em:contributor>Nattawat Palakawong Na Ayudhaya</em:contributor> <em:contributor>Patcharaporn Pansuwan</em:contributor> <em:contributor>Polawat Phetra</em:contributor> <em:contributor>Poakpong Phongsasanongkul</em:contributor> <em:contributor>Rerng-rit Rakkanittakorn</em:contributor> <em:contributor>Patinya Sangiamchit</em:contributor> <em:contributor>Phisit Siprasatthong</em:contributor> <em:contributor>Pittaya Sroilong</em:contributor> <em:contributor>Arthit Suriyawongkul</em:contributor> <em:contributor>Patipat Susumpow</em:contributor><em:contributor>Wichai Termwuttipreecha</em:contributor>

#unfilter emptyLines
