# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=$ProductName$-opstelling
Welcome_MessageWelcome=Welkom by %s!
Welcome_Message0=You are about to install %s 2 Alpha 1.

Welcome_Message1=Ons beveel sterk aan dat jy alle Windows-programme afsluit voor jy hierdie opstellingsprogram laat loop.
Welcome_Message2=Kliek Kanselleer om die opstelling af te sluit en sluit dan enige programme wat tans loop, ook af.  Kliek Volgende om met die opstellingsprogram voort te gaan.
Welcome_Message3=Click Next to continue installing %s 2 Alpha 1.


License_Title=Sagtewarelisensie-ooreenkoms
License_SubTitle=Bepalings en voorwaardes vir die gebruik van hierdie sagteware.
License_Message0=Lees asseblief die volgende lisensieooreenkoms. Gebruik die rolbalk om die res van hierdie ooreenkoms te vertoon.
License_Accept=Ek &aanvaar die bepalings van die lisensieooreenkoms
License_Decline=Ek aanvaar &NIE die bepalings van die lisensieooreenkoms nie

Type_Title=Opstellingsoort
Type_SubTitle=Kies opstellingsopsies.
Type_Message0=Kies die tipe opstelling wat jy verkies, en kliek dan Volgende.

Standard_Short=&Standaard
Standard_Long=Thunderbird sal met die algemeenste opsies geïnstalleer word.

Custom_Short=&Pasmaak
Custom_Long=Jy kan kies watter individuele opsies geïnstalleer moet word. Aanbeveel vir ervare gebruikers.

Select_Title=Kies komponente
Select_SubTitle=Bykomstige komponente wat $ProductName$ verbeter.
Select_Message0=Kies bykomstige komponente dat jy wil installeer, en kliek dan Volgende.

Path_Title=Installasievouer
Path_SubTitle=Waar $ProductName$ geïnstalleer gaan word.
Path_Message0=$ProductName$ sal in die volgende vouer geïnstalleer word:

Integration_Title=Stel kortpaaie op
Integration_SubTitle=Skep programikone
Integration_Message0=Skep ikone vir $ProductShortName$:

Integration_Desktop=Op my werkskerm
Integration_StartMenu=In die Programs-vouer van my Start-kieslys
Integration_QuickLaunch=In my Quick Launch-balk

SelectFolder_Title=$ProductName$-opstelling - Kies programvouer
SelectFolder_Message0=Die opstellingsprogram sal programikone by die Programs-vouer voeg wat hieronder gelys is.  Jy kan 'n nuwe vouernaam intik, of een uit die lys bestaande vouers kies.  Kliek Volgende om voort te gaan.

Advanced_Title=$ProductName$-opstelling - Gevorderde opstelling
Advanced_Message0=As jou internetverbinding vereis dat jy 'n instaanbediener gebruik, tik dan jou bedienernaam en poortinligting in.  As jou internetverbinding nie vereis dat jy 'n instaanbediener gebruik nie, los die velde leeg.

Install_Title=Opsomming
Install_SubTitle=Gereed om $ProductName$ te begin installeer.
Install_MessageInstall=Die opstellingsprogram sal in die volgende komponente installeer:
Install_MessageDownload=Die opstellingsprogram sal in die volgende komponente aflaai en installeer:
Install_Message0=Kliek Volgende om voort te gaan.

Downloading_Title=Laai tans af
Downloading_SubTitle=Laai tans vereiste komponente af...
Downloading_Blurb=Die opstellingsprogram laai tans die lêers af wat nodig is om $ProductName$ te installeer.
Downloading_FileName=Laai tans af:
Downloading_Time=Tyd oor:

Installing_Title=Installeer tans
Installing_SubTitle=Installeer tans $ProductName$...
Installing_Blurb=Die opstellingsprogram installeer tans toepassingslêers.
Installing_Status=Berei tans lêer voor:
Installing_Component=Installeer tans:

Success_Title=Installering afgehandel
Success_Header=Installering afgehandel
Success_Message0=%s is suksesvol geïnstalleer.
Success_Message1=Kliek Klaar om die opstellingsprogram af te sluit.
Success_Launch=Laat %s nou loop.

Check_Message=Aflaai van $ProductName$ was suksesvol. $ProductNameInternal$ moet afgesluit word om met die installasie voort te gaan. Kliek OK om $ProductNameInternal$ outomaties af te sluit en met installasie te begin.
Check_FullMessage=$ProductNameInternal$ moet afgesluit word om met die installasie voort te gaan. Kliek OK om $ProductNameInternal$ outomaties af te sluit en met installasie te begin.
Check_Wait=Sluit tans $ProductNameInternal$ af.  Wag asseblief...

Component_XPCOM=Kruisplatform-COM
Component_Mail=$ProductName$
Component_Offline=Aflyn-steun
Component_Offline_Long=Voeg aflynsteun by $ProductName$-posprogram.
Component_RSS=RSS-steun
Component_RSS_Long=Voeg RSS-steun by $ProductName$.
Component_QFA=Gehalteterugvoeragent
Component_QFA_Long=om omvalinligting oor $ProductName$ aan te meld
