# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

text-action-undo =
    .label = کیتا اݨ کیتا
    .accesskey = U
text-action-undo-shortcut =
    .key = Z
text-action-redo =
    .label = ولدا کرو
    .accesskey = R
text-action-redo-shortcut =
    .key = Y
text-action-cut =
    .label = کٹو
    .accesskey = t
text-action-cut-shortcut =
    .key = X
text-action-copy =
    .label = نقل کرو
    .accesskey = C
text-action-copy-shortcut =
    .key = C
text-action-paste =
    .label = چمباڑو
    .accesskey = P
text-action-paste-no-formatting =
    .label = فارمیٹنگ دے بغیر پیسٹ کرو
    .accesskey = m
text-action-paste-shortcut =
    .key = V
text-action-delete =
    .label = مٹاؤ
    .accesskey = D
text-action-select-all =
    .label = سارے منتخب کرو
    .accesskey = A
text-action-select-all-shortcut =
    .key = A
text-action-spell-no-suggestions =
    .label = ہجے دیاں کوئی تجویزاں کائنی
text-action-spell-add-to-dictionary =
    .label = ڈکشنری وِچ شامل کرو
    .accesskey = o
text-action-spell-undo-add-to-dictionary =
    .label = لغت وِچ شامل کرو کوں کالعدم کرو
    .accesskey = n
text-action-spell-check-toggle =
    .label = ہجے چیک کرو
    .accesskey = g
text-action-spell-add-dictionaries =
    .label = لغات شامل کرو…
    .accesskey = A
text-action-spell-dictionaries =
    .label = زباناں
    .accesskey = L
text-action-search-text-box-clear =
    .title = صاف کرو
text-action-highlight-selection =
    .label = چوݨ کوں نمایاں کرو
