# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Conexiones guardadas
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Copiar URL
    .accesskey = y
launch-site-url-cmd =
    .label = Visitar URL
    .accesskey = V
copy-username-cmd =
    .label = Copiar nombre de usuario
    .accesskey = U
edit-username-cmd =
    .label = Editar nombre de usuario
    .accesskey = d
copy-password-cmd =
    .label = Copiar contraseña
    .accesskey = C
edit-password-cmd =
    .label = Editar contraseña
    .accesskey = E
search-filter =
    .accesskey = S
    .placeholder = Buscar
column-heading-site =
    .label = Sitio
column-heading-username =
    .label = Nombre de usuario
column-heading-password =
    .label = Contraseña
column-heading-time-created =
    .label = Primer uso
column-heading-time-last-used =
    .label = Último uso
column-heading-time-password-changed =
    .label = Último cambio
column-heading-times-used =
    .label = Número de usos
remove =
    .label = Eliminar
    .accesskey = r
import =
    .label = Importar…
    .accesskey = I
close-button =
    .label = Cerrar
    .accesskey = C
show-passwords =
    .label = Mostrar contraseñas
    .accesskey = P
hide-passwords =
    .label = Ocultar contraseñas
    .accesskey = P
logins-description-all = Las conexiones para los siguientes sitios son almacenadas en tu computador
logins-description-filtered = Las siguientes conexiones coinciden con tu búsqueda:
remove-all =
    .label = Eliminar todas
    .accesskey = A
remove-all-shown =
    .label = Eliminar todas las mostradas
    .accesskey = A
remove-all-passwords-prompt = ¿Estás seguro de que deseas eliminar todas las contraseñas?
remove-all-passwords-title = Eliminar todas las contraseñas
no-master-password-prompt = ¿Estás seguro de que deseas mostrar tus contraseñas?
auto-fill-logins-and-passwords =
    .label = Autocompletar conexiones y contraseñas
