# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SaveImageTitle = Saglobuot attālu
SaveMediaTitle = Saglobuot
SaveVideoTitle = Saglobuot video
SaveAudioTitle = Saglobuot audio
SaveLinkTitle = Saglobuot kai
WebPageCompleteFilter = Šķārsteikla lopa, vysa
WebPageHTMLOnlyFilter = Šķārsteikla lopa, tikai HTML
WebPageXHTMLOnlyFilter = Šķārsteikla lopa, tikai XHTML
WebPageSVGOnlyFilter = Šķārsteikla lopa, tikai SVG
WebPageXMLOnlyFilter = Šķārsteikla lopa, tikai XML
