# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host } کوں لبھیندا پیا ہے…
network-connection-status-connected = { $host } نال کنکٹ  ہے…
network-connection-status-sending-request = { $host } کوں درخواست بھیڄی ویندی پئی ہے…
network-connection-status-transferring-data = { $host } کنوں ڈیٹا منتقل کیتا ویندا پیا ہے…
network-connection-status-connecting = { $host } نال کنکٹ تھیندا پیا ہے…
network-connection-status-read = { $host } پڑھو
network-connection-status-wrote = { $host } لکھیا
network-connection-status-waiting = { $host } دا انتظار تھیندا پیا ہے…
network-connection-status-looked-up = لبھ گھدا ڳئے { $host }…
network-connection-status-tls-handshake = { $host } کنوں TLS ہینڈ شیک کریندا پیا ہے…
network-connection-status-tls-handshake-finished = TLS ہینڈ شیک { $host } کیتے ختم تھیا…
