# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Recherche de l’hôte { $host }…
network-connection-status-connected = Connecté à { $host }…
network-connection-status-sending-request = Envoi d’une requête à { $host }…
network-connection-status-transferring-data = Transfert des données depuis { $host }…
network-connection-status-connecting = Connexion à { $host }…
network-connection-status-read = Données transférées depuis { $host }
network-connection-status-wrote = Données envoyées vers { $host }
network-connection-status-waiting = En attente de { $host }…
network-connection-status-looked-up = Recherche de { $host }…
network-connection-status-tls-handshake = Établissement d’une liaison TLS avec { $host }…
network-connection-status-tls-handshake-finished = Liaison TLS établie avec { $host }…
