# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Szukanie { $host }…
network-connection-status-connected = Połōnczōne ze { $host }…
network-connection-status-sending-request = Posyłanie prośby do { $host }…
network-connection-status-transferring-data = Przesyłanie danych ze { $host }…
network-connection-status-connecting = Łōnczynie ze { $host }…
network-connection-status-read = Przeczytane { $host }
network-connection-status-wrote = Zapisane { $host }
network-connection-status-waiting = Czekanie na { $host }…
network-connection-status-looked-up = Znodniynte { $host }…
network-connection-status-tls-handshake = Zawiōnzowanie połōnczynio TLS do { $host }…
network-connection-status-tls-handshake-finished = Je zawiōnzane połōnczynie TLS do { $host }…
