# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Lagre
dialogTitleAddBookmark = Legg til bokmerke
dialogTitleAddMulti = Bokmerk alle faner
dialogTitleEdit = Eigenskapar for «%S»
dialogTitleAddNewBookmark2 = Legg til bokmerke
dialogTitleEditBookmark = Rediger “%S”
dialogTitleEditBookmark2 = Redigere bokmerke
dialogTitleAddBookmarkFolder = Legg til bokmerkemappe
dialogTitleEditBookmarkFolder = Redigere bokmerkemappe
bookmarkAllTabsDefault = [Mappenamn]
newFolderDefault = Ny mappe
newBookmarkDefault = Nytt bokmerke
