# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-username-cmd =
    .label = Kopier brugernavn
    .accesskey = o
copy-password-cmd =
    .label = Kopier adgangskode
    .accesskey = K
search-filter =
    .accesskey = S
    .placeholder = Søg
column-heading-site =
    .label = Websted
column-heading-username =
    .label = Brugernavn
column-heading-password =
    .label = Adgangskode
column-heading-time-created =
    .label = Først brugt
column-heading-time-last-used =
    .label = Sidst brugt
column-heading-time-password-changed =
    .label = Sidst ændret
column-heading-times-used =
    .label = Antal gange brugt
remove =
    .label = Fjern
    .accesskey = F
close-button =
    .label = Luk
    .accesskey = L
logins-description-filtered = Følgende logins passer på din søgning:
remove-all =
    .label = Fjern alle
    .accesskey = a
remove-all-shown =
    .label = Fjern alle viste
    .accesskey = a
remove-all-passwords-prompt = Er du sikker på, at du vil fjerne alle dine gemte adgangskoder?
remove-all-passwords-title = Fjern alle gemte adgangskoder
no-master-password-prompt = Er du sikker på, at du vil have vist dine adgangskoder?
