# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = 保存
dialogTitleAddBookmark = 新しいブックマーク
dialogTitleAddMulti = 新しいブックマーク
dialogTitleEdit = "%S" のプロパティ
dialogTitleAddNewBookmark2 = 新しいブックマークを追加
dialogTitleEditBookmark = “%S” を編集
dialogTitleEditBookmark2 = ブックマークを編集
dialogTitleAddBookmarkFolder = ブックマークフォルダーを追加
dialogTitleEditBookmarkFolder = ブックマークフォルダーを編集
bookmarkAllTabsDefault = [フォルダーの名前]
newFolderDefault = 新しいフォルダー
newBookmarkDefault = 新しいブックマーク
