# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=$ProductName$ telepítő
Welcome_MessageWelcome=Üdvözli a %s
Welcome_Message0=Ez a varázsló telepíti a %s 3 Alpha 1 változatát.
Welcome_Message1=A telepítőprogram futtatása előtt erősen javallt kilépni minden más programból.
Welcome_Message2=Kattintson a Mégse gombra, és zárja be az összes futó alkalmazást, vagy kattintson a Tovább gombra a telepítés folytatásához.
Welcome_Message3=Kattintson a Tovább gombra a %s 3 Alpha 1 telepítésének folytatásához.

License_Title=Szoftverlicenc-szerződés
License_SubTitle=A szoftver használatának feltételei.
License_Message0=Olvassa el a felhasználói szerződést. A gördítősáv mozgatásával a szerződés további részei is olvashatóvá válnak.
License_Accept=&Elfogadom a licencszerződés feltételeit.
License_Decline=&Nem fogadom el a licencszerződés feltételeit.

Type_Title=Telepítés típusa
Type_SubTitle=Válassza ki a telepítés típusát.
Type_Message0=Kattintson a kívánt telepítési típusra, majd nyomja meg a Tovább gombot.

Standard_Short=&Szokásos
Standard_Long=A Thunderbird telepítése a leggyakoribb összetevőkkel.

Custom_Short=&Egyéni
Custom_Long=A telepítendő összetevők kiválasztása. Haladó felhasználóknak javasolt.

Select_Title=Összetevők kiválasztása
Select_SubTitle=További összetevők, amelyek a $ProductName$ tudását bővítik.
Select_Message0=Válassza ki a telepítendő további összetevőket, majd kattintson a Tovább gombra.

Path_Title=Célkönyvtár
Path_SubTitle=A $ProductName$ telepítési helye.
Path_Message0=A $ProductName$ a következő mappába lesz telepítve:

Integration_Title=Parancsikonok beállítása
Integration_SubTitle=Programikonok létrehozása
Integration_Message0=$ProductShortName$-ikonok létrehozása a következő helyeken:

Integration_Desktop=Asztal
Integration_StartMenu=Start menü Programok mappája
Integration_QuickLaunch=Gyorsindítás eszköztár

SelectFolder_Title=$ProductName$ telepítő - Program mappájának kiválasztása
SelectFolder_Message0=A telepítő a lent megjelenített programmappába helyezi el a program ikonjait. Megadhat egy új mappanevet, vagy választhat a már meglévő mappák közül. A folytatáshoz kattintson a Tovább gombra.

Advanced_Title=$ProductName$ telepítő - Haladó beállítások
Advanced_Message0=Ha az internetkapcsolathoz proxykiszolgálóra van szüksége, itt adhatja meg a szükséges adatokat. Ha az internetkapcsolathoz nincs szüksége proxykiszolgálóra, hagyja üresen az alábbi mezőket.

Install_Title=Összefoglaló
Install_SubTitle=Készen áll a $ProductName$ telepítésére.
Install_MessageInstall=A következő összetevők lesznek telepítve:
Install_MessageDownload=A következő összetevők lesznek letöltve és telepítve:
Install_Message0=A folytatáshoz kattintson a Tovább gombra.

Downloading_Title=Letöltés
Downloading_SubTitle=A szükséges összetevők letöltése...
Downloading_Blurb=A telepítőprogram letölti a $ProductName$ telepítéséhez szükséges összetevőket.
Downloading_FileName=Jelenlegi letöltés:
Downloading_Time=Hátralévő idő:

Installing_Title=Telepítés
Installing_SubTitle=A $ProductName$ telepítése...
Installing_Blurb=A telepítőprogram az alkalmazás fájljait telepíti. 
Installing_Status=Fájl előkészítése:
Installing_Component=Telepítés:

Success_Title=A telepítés kész
Success_Header=A telepítés kész
Success_Message0=A %s sikeresen telepítve lett.
Success_Message1=A telepítés befejezéséhez kattintson a Befejezés gombra. 
Success_Launch=A %s indítása.

Check_Message=A $ProductName$ sikeresen letöltődött. A telepítés folytatásához be kell zárnia a $ProductNameInternal$ programot. Kattintson az OK gombra a $ProductNameInternal$ automatikus bezárásához és a telepítés megkezdéséhez.
Check_FullMessage=A telepítés folytatásához be kell zárnia a $ProductNameInternal$ programot. Kattintson az OK gombra a $ProductNameInternal$ automatikus bezárásához és a telepítés megkezdéséhez.
Check_Wait=A $ProductNameInternal$ leállítása folyamatban. Kérem, várjon...

Component_XPCOM=Keresztplatformos COM
Component_Mail=$ProductName$
Component_Offline=Kapcsolat nélküli munka
Component_Offline_Long=Kapcsolat nélküli munka támogatása a $ProductName$ levelezőprogramban.
Component_RSS=RSS-támogatás
Component_RSS_Long=RSS támogatása a $ProductName$ programban.
Component_QFA=Quality Feedback Agent
Component_QFA_Long=A $ProductName$ programhibáinak jelentésére szolgáló eszköz.
