# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Mga naka-save na Login
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Copy URL
    .accesskey = y
launch-site-url-cmd =
    .label = Visit URL
    .accesskey = V
copy-username-cmd =
    .label = Kopyahin ang Username
    .accesskey = U
edit-username-cmd =
    .label = I-edit ang Username
    .accesskey = d
copy-password-cmd =
    .label = Kopyahin ang Password
    .accesskey = K
edit-password-cmd =
    .label = I-edit ang Password
    .accesskey = E
search-filter =
    .accesskey = S
    .placeholder = Hanapin
column-heading-site =
    .label = Site
column-heading-username =
    .label = Username
column-heading-password =
    .label = Password
column-heading-time-created =
    .label = Unang Ginamit
column-heading-time-last-used =
    .label = Huling Ginamit
column-heading-time-password-changed =
    .label = Huling Binago
column-heading-times-used =
    .label = Bilang ng Paggamit
remove =
    .label = Alisin
    .accesskey = R
import =
    .label = I-import...
    .accesskey = I
close-button =
    .label = Isara
    .accesskey = I
show-passwords =
    .label = Ipakita ang mga Password
    .accesskey = P
hide-passwords =
    .label = Itago ang mga Password
    .accesskey = P
logins-description-all = Ang mga pag-login para sa mga sumusunod na site ay naka-imbak sa iyong computer
logins-description-filtered = Ang sumusunod na logins ay tumugma sa iyong paghanap:
remove-all =
    .label = Tanggalin lahat
    .accesskey = A
remove-all-shown =
    .label = Tanggalin lahat ng nakikita
    .accesskey = A
remove-all-passwords-prompt = Sigurado ka bang gusto mong tanggalin ang lahat na mga password?
remove-all-passwords-title = Tanggalin ang Lahat na mga Password
no-master-password-prompt = Sigurado ka bang gusto mong ipakita ang mga password mo?
auto-fill-logins-and-passwords =
    .label = Mag-autofill ng mga login at password
