# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = के तपाईँ यी उद्देश्यहरूका लागि %S लाई विश्वास गर्न चाहनुहुन्छ?
unnamedCA = प्रमाणपत्र अधिकारी (नाम नभएको)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = कृपया यो प्रमाणपत्र जगेडालाई गोप्य राख्न प्रयोग गरिएको गोप्यशब्द प्रविष्ट गर्नुहोस्।
# Page Info
pageInfo_NoEncryption = जडान गोप्य छैन
pageInfo_Privacy_None1 = The web site %S does not support encryption for the page you are viewing.
pageInfo_Privacy_None2 = पारवहन भएको बेला गुप्तिकरण बिना इन्टरनेटमा पठाएको सूचना अन्य मानिसले पनि देख्न सक्नेछन् ।
pageInfo_Privacy_None4 = तपाईँले हेरिरहनुभएको पृष्ठलाई इन्टरनेटमा प्रसारण गर्नु पहिले गुप्तिकरण गरिएको थिएन।
pageInfo_Privacy_Encrypted1 = तपाईँले हेरिरहनुभएको पृष्ठलाई इन्टरनेटमा सार्नुभन्दा पहिले गोप्य बनाइएको थियो।
pageInfo_Privacy_Encrypted2 = गुप्तीकरणले अनधिकृत मान्छेहरूलाई कम्प्युटरहरूका बीच हुने जानकारीको आदान-प्रदान हेर्न अप्ठ्यारो पार्छ। त्यसैले यो पृष्ठलाई सञ्जाल वरपर कसैले पढ्ने धेरै सम्भावना छैन।
pageInfo_MixedContent = जडान आंशिक रूपमा गुप्तिकरण गरियो
pageInfo_MixedContent2 = तपाईँले हेरिरहनु भएको पृष्ठको भागहरू इन्टरनेट माथि संचारित हुनुभन्दा पहिले गुप्तिकृत गरिएको थिएन।
# Token Manager
password_not_set = (सेट नगरिएको)
