# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# DO NOT ADD THINGS OTHER THAN ERROR MESSAGES HERE.
# This file gets parsed into a JS dictionary of all known error message ids in
# gen_aboutneterror_codes.py . If we end up needing fluent attributes or
# refactoring them in some way, the script will need updating.

# Variables:
# $hostname (String) - Hostname of the website with SSL error.
# $errorMessage (String) - Error message corresponding to the type of error we are experiencing.
ssl-connection-error = { $hostname } adresine bağlanğanda bir hata yaşandı. { $errorMessage }

# Variables:
# $error (string) - NSS error code string that specifies type of cert error. e.g. unknown issuer, invalid cert, etc.
cert-error-code-prefix = Hata kodu: { $error }

psmerr-ssl-disabled = Güvenli olarak bağlanamıyor, çünkü SSL iletişim kuralı devre dışı bırakıldı.
psmerr-ssl2-disabled = Güvenli olarak bağlanamıyor, çünkü site SSL iletişim kuralının eski ve güvensiz sürümünü qullana.

# This is a multi-line message.
psmerr-hostreusedissuerandserial =
    Keçersiz bir şeadetname aldıñız. Lütfen sunucı memurı ile temasqa keçip ya da muhbiriñizge e-poçta yazıp aşağıdaki malümatnı beriñiz:
    
    Şeadetnameñiz, bu şeadetname salâhiyeti tarafından ihrac etilgen başqa bir şeadetname ile aynı seriya nomerasını ihtiva ete. Lütfen emsalsiz bir seriya numarasına saip yañı bir şeadetname elde etiñiz.

ssl-error-export-only-server = Güvenli iletişim kurulamadı. Karşı taraf yüksek düzeyde şifrelemeyi desteklemiyor.
ssl-error-us-only-server = Güvenli iletişim kurulamadı. Karşı taraf şu an desteklenmeyen yüksek düzey şifreleme istiyor.
ssl-error-no-cypher-overlap = Karşı tarafla güvenli iletişim kurulamadı: Ortak bir şifreleme çözüm yolu yok.
ssl-error-no-certificate = Doğrulama için gereken onay belgesi ya da anahtar bulunamadı.
ssl-error-bad-certificate = Karşı tarafla güvenli iletişim kurulamadı: Karşı tarafın onay belgesi reddedildi.
ssl-error-bad-client = Sunucu istemcide kötü veri ile karşılaştı.
ssl-error-bad-server = İstemci sunucuda kötü veri ile karşılaştı.
ssl-error-unsupported-certificate-type = Desteklenmeyen onay belgesi türü.
ssl-error-unsupported-version = Karşı taraf desteklenmeyen bir güvenlik iletişim kuralı kullanıyor.
ssl-error-wrong-certificate = İstemci doğrulaması başarısız oldu: Anahtar veritabanındaki özel anahtar, onay belgesi veritabanındaki genel anahtarla eşleşmiyor.
ssl-error-bad-cert-domain = Karşı tarafla güvenli iletişim kurulamadı: Çağrılan alan adı ile sunucunun onay belgesi eşleşmiyor.
ssl-error-post-warning = Tanılmağan SSL hata kodu.
ssl-error-ssl2-disabled = Karşı taraf sadece, yerel olarak devre dışı olan SSL 2 sürümünü destekliyor.
ssl-error-bad-mac-read = SSL geçersiz ileti doğrulama kodu içeren bir kayıt aldı.
ssl-error-bad-mac-alert = SSL eşi, geçersiz bir ileti doğrulama kodu bildiriyor.
ssl-error-bad-cert-alert = SSL eşi onay belgenizin doğruluğunu kanıtlayamıyor.
ssl-error-revoked-cert-alert = SSL eşi onay belgenizi hükümsüz olduğu gerekçesiyle geri çevirdi.
ssl-error-expired-cert-alert = SSL eşi onay belgenizi süresinin dolduğu gerekçesiyle geri çevirdi.
ssl-error-ssl-disabled = Bağlanılamıyor: SSL devre dışı.
ssl-error-fortezza-pqg = Bağlanılamıyor: SSL eşi diğer bir FORTEZZA alan adında.
ssl-error-unknown-cipher-suite = Bilinmeyen bir SSL şifreleme takımı istendi.
ssl-error-no-ciphers-supported = Bu programda hiçbir şifreleme takımı yok ve devrede değil.
ssl-error-bad-block-padding = SSL, fena blok şiltelemesine saip olğan bir qaydnı aldı.
ssl-error-rx-record-too-long = SSL izin verilen uzunluğu aşan bir kayıt aldı.
ssl-error-tx-record-too-long = SSL izin verilen uzunluğu aşan bir kayıt göndermeye kalktı.
ssl-error-rx-malformed-hello-request = SSL kusurlu bir karşılaşama iletisi aldı.
ssl-error-rx-malformed-client-hello = SSL kusurlu bir istemci karşılama iletisi aldı.
ssl-error-rx-malformed-server-hello = SSL kusurlu bir sunucu karşılama iletisi aldı.
ssl-error-rx-malformed-certificate = SSL kusurlu bir onay belgesi karşılama iletisi aldı.
ssl-error-rx-malformed-server-key-exch = SSL kusurlu bir sunucu anahtar değişimi karşılama iletisi aldı.
ssl-error-rx-malformed-cert-request = SSL kusurlu bir onay belgesi isteği karşılama iletisi aldı.
ssl-error-rx-malformed-hello-done = SSL kusurlu bir sunucuyu başarılı karşılaşama iletisi aldı.
ssl-error-rx-malformed-cert-verify = SSL kusurlu bir onay belgesi doğrulaması karşılaşama iletisi aldı.
ssl-error-rx-malformed-client-key-exch = SSL kusurlu bir istemci anahtar değişimi karşılama iletisi aldı.
ssl-error-rx-malformed-finished = SSL kusurlu bir bitiş karşılama iletisi aldı.
ssl-error-rx-malformed-change-cipher = SSL kusurlu bir şifreleme değişim kaydı aldı.
ssl-error-rx-malformed-alert = SSL kusurlu bir uyarı kaydı aldı.
ssl-error-rx-malformed-handshake = SSL kusurlu bir karşılama kaydı aldı.
ssl-error-rx-malformed-application-data = SSL kusurlu bir uygulama veri kaydı aldı.
ssl-error-rx-unexpected-hello-request = SSL beklenmeyen bir karşılama isteği iletisi aldı.
ssl-error-rx-unexpected-client-hello = SSL beklenmeyen bir istemci karşılama iletisi aldı.
ssl-error-rx-unexpected-server-hello = SSL beklenmeyen bir sunucu karşılama iletisi aldı.
ssl-error-rx-unexpected-certificate = SSL beklenmeyen bir onay belgesi karşılama iletisi aldı.
ssl-error-rx-unexpected-server-key-exch = SSL beklenmeyen bir sunucu anahtar değişimi karşılama iletisi aldı.
ssl-error-rx-unexpected-cert-request = SSL beklenmeyen bir onay belgesi isteği karşılama iletisi aldı.
ssl-error-rx-unexpected-hello-done = SSL beklenmeyen bir sunucuyu başarılı karşılaşama iletisi aldı.
ssl-error-rx-unexpected-cert-verify = SSL beklenmeyen bir onay belgesi doğrulaması karşılaşama iletisi aldı.
ssl-error-rx-unexpected-client-key-exch = SSL beklenmeyen bir sunucu anahtar değişimi karşılama iletisi aldı.
ssl-error-rx-unexpected-finished = SSL beklenmeyen bir bitiş karşılama iletisi aldı.
ssl-error-rx-unexpected-change-cipher = SSL beklenmeyen bir şifreleme değişim kaydı aldı.
ssl-error-rx-unexpected-alert = SSL beklenmeyen bir uyarı kaydı aldı.
ssl-error-rx-unexpected-handshake = SSL beklenmeyen bir karşılama kaydı aldı.
ssl-error-rx-unexpected-application-data = SSL beklenmeyen bir uygulama veri kaydı aldı.
ssl-error-rx-unknown-record-type = SSL bilinmeyen bir içerik türüyle ilgili kayıt aldı.
ssl-error-rx-unknown-handshake = SSL bilinmeyen bir türde karşılama iletisi aldı.
ssl-error-rx-unknown-alert = SSL bilinmeyen tanım taşıyan bir uyarı kaydı aldı.
ssl-error-close-notify-alert = SSL eşi bu bağlantıyı kesti.
ssl-error-handshake-unexpected-alert = SSL eşi aldığı karşılama iletisini beklemiyordu.
ssl-error-decompression-failure-alert = SSL eşi aldığı SSL kaydını açmayı başaramadı.
ssl-error-handshake-failure-alert = SSL eşi kabul edilebilir sayıda güvenlik değişkeniyle karşılıklı görüşmeyi sağlayamadı.
ssl-error-illegal-parameter-alert = SSL eşi kabul edilemez içerik yüzünden karşılama iletisini geri çevirdi.
ssl-error-unsupported-cert-alert = SSL eşi aldığı türdeki onay belgelerini desteklemiyor.
ssl-error-certificate-unknown-alert = SSL eşi aldığı onay belgeleriyle belirlenemeyen türde sorunlar yaşadı.
ssl-error-generate-random-failure = SSL rastlantısal numara üretecinde bir sorun yaşadı.
ssl-error-sign-hashes-failure = Onay belgenizin doğruluğunu kanıtlayacak veri, sayısal olarak imzalanamadı.
ssl-error-extract-public-key-failure = SSL karşı tarafın onay belgesinden genel anahtarı çıkaramadı.
ssl-error-server-key-exchange-failure = SSL sunucusu anahtar değiştirme karşılaması sırasında belirtilmemiş bir hatayla karşılaştı.
ssl-error-client-key-exchange-failure = SSL istemcisi anahtar değiştirme karşılaması sırasında belirtilmemiş bir hatayla karşılaştı.
ssl-error-encryption-failure = Seçili şifreleme takımındaki toplu veri şifreleme çözüm yolu başarısız oldu.
ssl-error-decryption-failure = Seçili şifreleme takımındaki toplu veri şifre çözme çözüm yolu başarısız oldu.
ssl-error-socket-write-failure = Temeli oluşturan yuvaya şifreli veri yazmaya çalışma girişimi başarısız oldu.
ssl-error-md5-digest-failure = MD5 derleme işlevi çalışmadı.
ssl-error-sha-digest-failure = SHA-1 derleme işlevi çalışmadı.
ssl-error-mac-computation-failure = MAC esaplaması muvafaqiyetsiz.
ssl-error-sym-key-context-failure = Simetrik anahtar içeriği üretimi başarısız oldu.
ssl-error-sym-key-unwrap-failure = İstemci anahtar değişim iletisindeki simetrik anahtar çözülemedi.
ssl-error-pub-key-size-limit-exceeded = SSL sunucusu yerel düzeydeki genel anahtarla dışa aktarılan şifreleme takımını kullanmayı denedi.
ssl-error-iv-param-failure = PKCS11 kodu, bir IV'yi bir değişkene çeviremedi.
ssl-error-init-cipher-suite-failure = Seçilen şifreleme takımı çalıştırılamadı.
ssl-error-session-key-gen-failure = İstemci, SSL oturumu için anahtar üretmeyi beceremedi.
ssl-error-no-server-key-for-alg = Sunucu, üzerinde çalışılan değişim çözüm yolu için hiçbir anahtara sahip değil.
ssl-error-token-insertion-removal = İşlem sürerken PKCS#11 işareti eklendi ya da kaldırıldı.
ssl-error-token-slot-not-found = Gerekli bir işlemi yapmak üzere aranan PKCS#11 işareti bulunamadı.
ssl-error-no-compression-overlap = Karşı tarafla güvenli iletişim kurulamadı: Ortak bir sıkıştırma çözüm yolu yok.
ssl-error-handshake-not-completed = Hâlihazırdaki SSL karşılaması bitmeden başka bir karşılamaya girişilemez.
ssl-error-bad-handshake-hash-value = Eşten yanlış karşılama özeti değerleri alındı.
ssl-error-cert-kea-mismatch = Sunulan onay belgesi seçilen anahtar değiştirme çözüm yoluyla kullanılamaz.
ssl-error-no-trusted-ssl-client-ca = SSL istemci doğrulaması konusunda hiçbir onay belgesi yetkilisine güvenilmiyor.
ssl-error-session-not-found = İstemcinin SSL oturum kimliği sunucunun oturum ön belleğinde bulunamadı.
ssl-error-decryption-failed-alert = Eş, aldığı bir SSL kaydının şifresini çözemedi.
ssl-error-record-overflow-alert = Eş izin verilenden daha uzun olan bir SSL kaydı aldı.
ssl-error-unknown-ca-alert = Eş, onay belgenizi dağıtan yetkiliyi tanımıyor ve ona güvenmiyor.
ssl-error-access-denied-alert = Eş geçerli bir onay belgesi aldı, ancak erişim engellendi.
ssl-error-decode-error-alert = Eş bir SSL karşılama iletisini çözemedi.
ssl-error-decrypt-error-alert = Eş imza doğrulama ya da anahtar değişim hatası olduğunu bildiriyor.
ssl-error-export-restriction-alert = Eş görüşmenin ihracat düzenlemeleriyle uyumlu olmadığını bildiriyor.
ssl-error-protocol-version-alert = Eş uyumsuz ya da desteklenmeyen iletişim kuralı sürümü olduğunu bildiriyor.
ssl-error-insufficient-security-alert = Sunucu için şifrelerin istemcinin desteklediğinden daha güvenli olması gerekiyor.
ssl-error-internal-error-alert = Eş bir iç hata yaşadığını bildiriyor.
ssl-error-user-canceled-alert = Eş kullanıcı karşılamayı iptal etti.
ssl-error-no-renegotiation-alert = Eş SSL güvenlik değişkenlerinin yeniden görüşülmesine izin vermiyor.
ssl-error-server-cache-not-configured = SSL sunucusu bu yuva için ayarlanmadı ve devre dışı bırakılmadı.
ssl-error-unsupported-extension-alert = SSL eşi istenen TLS eklentisini desteklemiyor.
ssl-error-certificate-unobtainable-alert = SSL eşi verdiğiniz URL'den onay belgenize ulaşamadı.
ssl-error-unrecognized-name-alert = SSL eşi istenen DNS için onay belgesine sahip değil.
ssl-error-bad-cert-status-response-alert = SSL eşi onay belgesi için OCSP yanıtı almayı beceremedi.
ssl-error-bad-cert-hash-value-alert = SSL eşi bozulmuş onay belgesi özeti olduğunu bildirdi.
ssl-error-rx-unexpected-new-session-ticket = SSL beklenmegen bir Yañı Oturım Bileti el sıqışma mesajı aldı.
ssl-error-rx-malformed-new-session-ticket = SSL fena-şekilli bir Yañı Oturım Bileti el sıqışma mesajı aldı.
ssl-error-decompression-failure = SSL kenişletilamağan sıqıştırılğan bir qayd aldı.
ssl-error-renegotiation-not-allowed = Bu SSL oyuğı üzerinde kene kelişüv caiz degildir.
ssl-error-unsafe-negotiation = Aqran, eski uslûp (potensial olaraq zedelenebilir) el sıqışmasına talpındı.
ssl-error-rx-unexpected-uncompressed-record = SSL beklenmegen bir sıqıştırılmağan qayd aldı.
ssl-error-weak-server-ephemeral-dh-key = SSL, Sunucı Anahtarı Teatisi el sıqışma mesajında zayıf bir qısqa ömürli Diffie-Hellman anahtarı aldı.
ssl-error-next-protocol-data-invalid = SSL keçersiz NPN uzantı verileri aldı.
ssl-error-feature-not-supported-for-ssl2 = SSL 2.0 bağlantıları içün SSL hususiyeti desteklenmey.
ssl-error-feature-not-supported-for-servers = SSL hususiyeti sunucılar içün desteklenmey.
ssl-error-feature-not-supported-for-clients = SSL hususiyeti müşteriler içün desteklenmey.
ssl-error-invalid-version-range = SSL sürüm menzili keçerli degildir.
ssl-error-cipher-disallowed-for-version = SSL aqranı, saylanğan protokol sürümi içün izin berilmegen bir şifreleme paketi sayladı.
ssl-error-rx-malformed-hello-verify-request = SSL fena-şekilli bir Selâm Doğrulama İstemi elsıqışma mesajı aldı.
ssl-error-rx-unexpected-hello-verify-request = SSL beklenmegen bir Selâm Doğrulama İstemi elsıqışma mesajı aldı.
ssl-error-feature-not-supported-for-version = SSL hususiyeti protokol sürümi içün desteklenmey.
ssl-error-rx-unexpected-cert-status = SSL, beklenmegen bir Şeadetname Statusı elsıqışma mesajı aldı.
ssl-error-unsupported-hash-algorithm = TLS aqranı, desteklenmegen bir qıyım (heş) algoritması qullana.
ssl-error-digest-failure = Hazim funksiyası çaqtı.
ssl-error-incorrect-signature-algorithm = Raqamsal-imzalı unsurda yañlış imza algoritması belirtilgen.
ssl-error-next-protocol-no-callback = Soñraki protokol körüşme uzantısı qabilleştirilgen edi, ama keriçağırım ihtiyac tuyulmazdan evvel temizlendi.
ssl-error-next-protocol-no-protocol = Sunucı, müşteriniñ ALPN uzantısında tanıtqanı iç bir protokolnı desteklemey.
ssl-error-inappropriate-fallback-alert = Sunucı elsıqışmanı redetti çünki müşteri sunucınıñ desteklegeninden tüşük bir TLS sürümine alt-qademeledi.
ssl-error-weak-server-cert-key = Sunucı şeadetnamesi fazla zayıf bir aleniy anahtar ihtiva ete edi.
ssl-error-rx-short-dtls-read = DTLS qaydı içün buferde yeterli yer yoq.
ssl-error-no-supported-signature-algorithm = Desteklengen bir TLS imza algoritması endamlandırılmağandır.
ssl-error-unsupported-signature-algorithm = Aqran, desteklenmegen bir imza ve qıyım (hash) algoritması bileşkesini qullandı.
ssl-error-missing-extended-master-secret = Aqran, doğru bir extended_master_secret uzantısı olmadan devam ettirmege çalıştı.
ssl-error-unexpected-extended-master-secret = Aqran, beklenmegen bir extended_master_secret uzantısı ile devam ettirmege çalıştı.
sec-error-io = Güvenlik doğrulaması sırasında giriş-çıkış hatası meydana geldi.
sec-error-library-failure = Güvenlik kitaplığı hatası.
sec-error-bad-data = Güvenlik kitaplığı: Kötü veri alındı.
sec-error-output-len = Güvenlik kitaplığı: Çıktı uzunluğu hatası.
sec-error-input-len = Güvenlik kitaplığı girdi uzunluğu hatası yaşadı.
sec-error-invalid-args = Güvenlik kitaplığı: Geçersiz bağımsız değişkenler.
sec-error-invalid-algorithm = Güvenlik kitaplığı: Geçersiz çözüm yolu.
sec-error-invalid-ava = Güvenlik kitaplığı: Geçersiz AVA.
sec-error-invalid-time = Düzgün biçimlendirilmemiş tarih dizgisi.
sec-error-bad-der = Güvenlik kitaplığı: Düzgün biçimlendirilmemiş DER şifreli ileti.
sec-error-bad-signature = Aqrannıñ şeadetnamesi keçersiz bir imzağa saip.
sec-error-expired-certificate = Eşin onay belgesinin süresi doldu.
sec-error-revoked-certificate = Eşin onay belgesi hükümsüz olmuş.
sec-error-unknown-issuer = Eşin onay belgesini dağıtan tanınmıyor.
sec-error-bad-key = Eşin genel anahtarı geçersiz.
sec-error-bad-password = Girilen güvenlik parolası yanlış.
sec-error-retry-password = Yeni parola yanlış girildi. Lütfen yeniden deneyin.
sec-error-no-nodelock = Güvenlik kitaplığı: Düğüm kilidi yok.
sec-error-bad-database = Güvenlik kitaplığı: Bozuk veritabanı.
sec-error-no-memory = Güvenlik kitaplığı: Bellek paylaşım hatası.
sec-error-untrusted-issuer = Eşin onay belgesi dağıtıcısı, kullanıcı tarafından güvenilmez olarak işaretlendi.
sec-error-untrusted-cert = Eşin onay belgesi, kullanıcı tarafından güvenilmez olarak işaretlendi.
sec-error-duplicate-cert = Onay belgesi zaten veritabanınızda var.
sec-error-duplicate-cert-name = Onay belgesinin ismi veritabanınızdakiyle aynı.
sec-error-adding-cert = Onay belgesini veritabanına eklerken hata meydana geldi.
sec-error-filing-key = Onay belgesinin anahtarı yeniden doldurulurken hata meydana geldi.
sec-error-no-key = Bu onay belgesinin özel anahtarı veritabanında bulunamıyor.
sec-error-cert-valid = Bu onay belgesi geçerli.
sec-error-cert-not-valid = Bu onay belgesi geçerli değil.
sec-error-cert-no-response = Onay belgesi kitaplığı: Yanıt yok.
sec-error-expired-issuer-certificate = Onay belgesi dağıtıcısının onay belgesinin süresi dolmuş. Sistem tarihi ve saatini gözden geçirin.
sec-error-crl-expired = Onay belgesi dağıtıcısının hükümsüzler listesinin süresi dolmuş. Listeyi güncelleyin ya da sistem tarihi ve saatini gözden geçirin.
sec-error-crl-bad-signature = Onay belgesi dağıtıcısının hükümsüzler listesinin geçersiz imzası var.
sec-error-crl-invalid = Yeni hükümsüzler listesi geçersiz biçime sahip.
sec-error-extension-value-invalid = Onay belgesi uzantı değeri geçersiz.
sec-error-extension-not-found = Onay belgesi uzantısı bulunamadı.
sec-error-ca-cert-invalid = Dağıtıcının onay belgesi geçersiz.
sec-error-path-len-constraint-invalid = Onay belgesi konum uzunluğu sınırı geçersiz.
sec-error-cert-usages-invalid = Onay belgesi kullanım alanı geçersiz.
sec-internal-only = **SADECE iç birim**
sec-error-invalid-key = Anahtar istenen işlemi desteklemiyor.
sec-error-unknown-critical-extension = Onay belgesi bilinmeyen kritik uzantılar içeriyor.
sec-error-old-crl = Yeni hükümsüzler listesinin tarihi hâlihazırdakinden daha yeni değil.
sec-error-no-email-cert = Şifrelenmemiş ya da imzalanmamış: Henüz e-posta onay belgeniz yok.
sec-error-no-recipient-certs-query = Şifrelenmegen: er bir alıcı içün şeadetnameleriñiz yoqtır.
sec-error-not-a-recipient = Şifre çözülemiyor: Alıcı siz değilsiniz ya da birbiriyle eşleşen onay belgesi ya da özel anahtar bulunamadı.
sec-error-pkcs7-keyalg-mismatch = Şifre çözülemiyor: Anahtar şifreleme çözüm yolu onay belgenizle eşleşmiyor.
sec-error-pkcs7-bad-signature = Anahtar doğrulaması başarısız oldu: İmzacı bulunamamış, çok fazla imzacı bulunmuş  ya da düzgün olmayan veya eksik veri ile işlem yapılmış olabilir.
sec-error-unsupported-keyalg = Desteklenmeyen ya da bilinmeyen anahtar çözüm yolu.
sec-error-decryption-disallowed = Şifre çözülemiyor: İzin verilmeyen bir çözüm yoluyla ya da anahtar boyutunda şifrelenmiş.
xp-sec-fortezza-bad-card = Fortezza kartı düzgün olarak çalıştırılamadı. Lütfen çıkarıp dağıtıcınıza geri götürün.
xp-sec-fortezza-no-card = Fortezza kartı bulunamadı
xp-sec-fortezza-none-selected = Fortezza kartı seçilmedi
xp-sec-fortezza-more-info = Lütfen daha fazla bilgi almak üzere bir kişilik seçin
xp-sec-fortezza-person-not-found = Kişilik bulunamadı
xp-sec-fortezza-no-more-info = Bu kişilikle ilgili daha fazla bilgi yok
xp-sec-fortezza-bad-pin = Geçersiz kişisel tanımlama numarası
xp-sec-fortezza-person-error = Fortezza kişiliklerine ulaşılamadı.
sec-error-no-krl = Bu siteyle ilgili herhangi bir geçersiz anahtar listesi bulunamadı.
sec-error-krl-expired = Bu sitenin geçersiz anahtar listesinin süresi dolmuş.
sec-error-krl-bad-signature = Bu sitenin geçersiz anahtar listesinin anahtarı geçersiz.
sec-error-revoked-key = Bu sitenin onay belgesi anahtarı hükümsüzleşmiş.
sec-error-krl-invalid = Yeni geçersiz anahtar listesinin biçimi geçersiz.
sec-error-need-random = Güvenlik kitaplığı: rastgele veri gerekiyor.
sec-error-no-module = Güvenlik kitaplığı: İç bir güvenlik birimi istenen işlemi gerçekleştiremiyor.
sec-error-no-token = Güvenlik kartı ya da işareti yok, başlatılması gerek ya da silinmiş olabilir.
sec-error-read-only = Güvenlik kitaplığı: Veritabanı salt okunur.
sec-error-no-slot-selected = Yuva ya da işaret seçilmedi.
sec-error-cert-nickname-collision = Aynı takma adı taşıyan bir onay belgesi zaten var.
sec-error-key-nickname-collision = Aynı takma adı taşıyan bir anahtar zaten var.
sec-error-safe-not-created = Güvenli nesne oluşturulurken hata meydana geldi.
sec-error-baggage-not-created = Bagaj nesnesi oluşturulurken hata meydana geldi.
xp-java-remove-principal-error = Baş bölüm kaldırılamadı.
xp-java-delete-privilege-error = Ayrıcalık ortadan kaldırılamadı
xp-java-cert-not-exists-error = Bu baş bölümün onay belgesi yok
sec-error-bad-export-algorithm = İstenen çözüm yoluna izin verilmiyor.
sec-error-exporting-certificates = Onay belgeleri dışa aktarılırken hata meydana geldi.
sec-error-importing-certificates = Onay belgeleri içe aktarılırken hata meydana geldi.
sec-error-pkcs12-decoding-pfx = İçe aktarılamıyor. Çözüm hatası. Dosya geçersiz.
sec-error-pkcs12-invalid-mac = İçe aktarılamıyor. Geçersiz MAC. Geçersiz parola ya da eksik dosya söz konusu.
sec-error-pkcs12-unsupported-mac-algorithm = İçe aktarılamıyor. MAC çözüm yolu desteklenmiyor.
sec-error-pkcs12-unsupported-transport-mode = İçe aktarılamıyor. Sadece parola bütünleşmesi ve gizlilik kipleri destekleniyor.
sec-error-pkcs12-corrupt-pfx-structure = İçe aktarılamıyor. Dosya yapısı eksik.
sec-error-pkcs12-unsupported-pbe-algorithm = İçe aktarılamıyor. Şifreleme çözüm yolu desteklenmiyor.
sec-error-pkcs12-unsupported-version = İçe aktarılamıyor. Dosya sürümü desteklenmiyor.
sec-error-pkcs12-privacy-password-incorrect = İçe aktarılamıyor. Geçersiz gizlilik parolası.
sec-error-pkcs12-cert-collision = İçe aktarılamıyor. Veritabanında aynı takma ad var.
sec-error-user-cancelled = Qullanıcı vazgeç dögmesine bastı.
sec-error-pkcs12-duplicate-data = İçe aktarılamadı; veritabanında zaten var.
sec-error-message-send-aborted = İleti gönderilmedi.
sec-error-inadequate-key-usage = Onay belgesi anahtar kullanımı yapılmaya kalkışılan işlem için yetersiz.
sec-error-inadequate-cert-type = Onay belgesi türü uygulama için onaylanmış değil.
sec-error-cert-addr-mismatch = İmzalanan onay belgesindeki adres üst bilgideki adresle uyuşmadı.
sec-error-pkcs12-unable-to-import-key = İçe aktarılamadı. Özel anahtarın içe aktarılması sırasında sorun yaşandı.
sec-error-pkcs12-importing-cert-chain = İçe aktarılamadı. Onay belgesi zincirinin aktarılması sırasında hata meydana geldi.
sec-error-pkcs12-unable-to-locate-object-by-name = Dışa aktarılamadı. Onay belgesine ya da anahtara takma ad kullanılarak ulaşılamadı.
sec-error-pkcs12-unable-to-export-key = Dışa aktarılamadı. Özel anahtar bulunamadı ve dışa aktarılamadı.
sec-error-pkcs12-unable-to-write = Dışa aktarılamadı. Dışa aktarma dosyasına yazılamadı.
sec-error-pkcs12-unable-to-read = Dışa aktarılamadı. İçe aktarma dosyası okunamadı.
sec-error-pkcs12-key-database-not-initialized = Dışa aktarılamadı. Anahtar veritabanı bozuk ya da silinmiş.
sec-error-keygen-fail = Özel ve genel anahtar ikilisi üretilemiyor.
sec-error-invalid-password = Girilen parola geçersiz. Lütfen farklı bir tane seçin.
sec-error-retry-old-password = Eski parola yanlış girildi. Lütfen yeniden deneyin.
sec-error-bad-nickname = Onay belgesi takma adı hâlihazırda kullanılıyor.
sec-error-not-fortezza-issuer = Eşin FORTEZZA zinciri has FORTEZZA olmayan onay belgesi içeriyor.
sec-error-cannot-move-sensitive-key = Duyarlı bir anahtar ihtiyaç duyulan yuvaya taşınamıyor.
sec-error-js-invalid-module-name = Geçersiz birim adı.
sec-error-js-invalid-dll = Geçersiz birim yolu veya dosya adı
sec-error-js-add-mod-failure = Birim eklenemiyor
sec-error-js-del-mod-failure = Birim silinemiyor
sec-error-old-krl = Yeni hükümsüz anahtar listesinin tarihi hâlihazırdakinden daha yeni değil.
sec-error-ckl-conflict = Yeni uyumsuz anahtar listesinin dağıtıcısı şu anki listenin dağıtıcısından farklı. Geçerli listeyi silin.
sec-error-cert-not-in-name-space = Bu onay belgesinin yetkilisine bu isimle dağıtım yapma izin verilmiyor.
sec-error-krl-not-yet-valid = Bu onay belgesinin hükümsüz anahtar listesi henüz geçerli değil.
sec-error-crl-not-yet-valid = Bu onay belgesinin hükümsüz onay belgesi listesi henüz geçerli değil.
sec-error-unknown-cert = İstenen onay belgesi bulunamadı.
sec-error-unknown-signer = Dağıtıcının onay belgesi bulunamadı.
sec-error-cert-bad-access-location = Onay belgesi durum sunucusunun konumu geçersiz biçimde.
sec-error-ocsp-unknown-response-type = OCSP yanıtı tamamen çözülemiyor; bilinmeyen bir türde.
sec-error-ocsp-bad-http-response = OCSP sunucusu beklenmeyen ya da geçersiz HTTP verisi aldı.
sec-error-ocsp-malformed-request = OCSP sunucusu isteğin yarıda kesilmiş ya da düzgün olmayan biçimde olduğunu fark etti.
sec-error-ocsp-server-error = OCSP sunucusu iç hata yaşadı.
sec-error-ocsp-try-server-later = OCSP sunucusu daha sonra denenmesini öneriyor.
sec-error-ocsp-request-needs-sig = OCSP sunucusu bu istekte imza gerektiğini söylüyor.
sec-error-ocsp-unauthorized-request = OCSP sunucusu yetkisiz olduğu gerekçesiyle bu isteği geri çevirdi.
sec-error-ocsp-unknown-response-status = OCSP sunucusu algılanamayan bir durumla karşılaştı.
sec-error-ocsp-unknown-cert = OCSP sunucusu onay belgesiyle ilgili herhangi bir durum bildiriminde bulunamıyor.
sec-error-ocsp-not-enabled = Bu işlemi gerçekleştirmeden önce OCSP'yi devreye sokmalısınız.
sec-error-ocsp-no-default-responder = Bu işlemi gerçekleştirmeden önce OCSP'yi öntanımlı yanıt verici olarak ayarlamalısınız.
sec-error-ocsp-malformed-response = OCSP sunucusunun yanıtı bozuk ya da düzgün olmayan biçimde.
sec-error-ocsp-unauthorized-response = OCSP yanıtının dağıtıcısı bu onay belgesiyle ilgili durum bildirmeye yetkili değil.
sec-error-ocsp-future-response = OCSP yanıtı henüz geçerli değil, çünkü ileri bir tarih taşıyor.
sec-error-ocsp-old-response = OCSP yanıtı zamanı geçmiş bilgi içeriyor.
sec-error-digest-not-found = İmzalanan iletide CMS ya da PKCS #7 özeti bulunamadı.
sec-error-unsupported-message-type = CMS ya da PKCS #7 ileti türü desteklenmiyor.
sec-error-module-stuck = PKCS #11 birimi kaldırılamıyor çünkü hâlen kullanımda.
sec-error-bad-template = ASN.1 verisi çözülemiyor. Belirtilen kalıp geçersizdi.
sec-error-crl-not-found = Eşleşen hükümsüz onay belgesi listesi bulunamadı.
sec-error-reused-issuer-and-serial = Var olan bir onay belgesiyle aynı dağıtıcı ya da seri numarasına saip bir onay belgesini içe aktarmaya çalışıyorsunuz, ancak bunlar aynı onay belgeleri değil.
sec-error-busy = NSS kapatılamadı. Nesneler hâlâ kullanımda.
sec-error-extra-input = DER şifreli ileti kullanılmayan fazladan veri içeriyor.
sec-error-unsupported-elliptic-curve = Desteklenmeyen oval eğri.
sec-error-unsupported-ec-point-form = Desteklenmeyen oval eğri noktası şekli.
sec-error-unrecognized-oid = Tanınmayan Nesne Tanımlayıcısı.
sec-error-ocsp-invalid-signing-cert = OCSP yanıtında geçersiz OCSP onay belgesi imzası var.
sec-error-revoked-certificate-crl = Onay belgesi, dağıtıcının hükümsüz onay belgeleri listesinde yer alıyor.
sec-error-revoked-certificate-ocsp = Dağıtıcının OCSP yanıtçısı, onay belgesinin hükümsüz olduğunu bildiriyor.
sec-error-crl-invalid-version = Dağıtıcının hükümsüz onay belgeleri listesi bilinmeyen bir sürüm numarasına saip.
sec-error-crl-v1-critical-extension = Dağıtıcının V1 hükümsüz onay belgesi listesi kritik bir uzantıya saip.
sec-error-crl-unknown-critical-extension = Dağıtıcının V2 hükümsüz onay belgesi listesi bilinmeyen kritik bir uzantıya saip.
sec-error-unknown-object-type = Bilinmeyen nesne türü belirtildi.
sec-error-incompatible-pkcs11 = PKCS #11 sürücüsü tanımlamayı uygunsuz yolla ihlâl ediyor.
sec-error-no-event = Şimdilik yañı bir yuva vaqiası yoqtır.
sec-error-crl-already-exists = Hükümsüz onay belgesi listesi kullanımda.
sec-error-not-initialized = NSS başlatılmadı.
sec-error-token-not-logged-in = İşlem başarısızlıkla sonuçlandı, çünkü PKCS#11 belirkesi giriş yapmış değil.
sec-error-ocsp-responder-cert-invalid = Ayarlanan OCSP yanıtçısının onay belgesi geçersiz.
sec-error-ocsp-bad-signature = OCSP cevabı keçersiz bir imzağa saiptir.
sec-error-out-of-search-limits = Şeadetname keçerlileme qıdırması qıdırma limitleriniñ tışındadır
sec-error-invalid-policy-mapping = Siyaset haritalaması anypolicy ihtiva ete
sec-error-policy-validation-failed = Şeadetname zıncırı siyaset keçerlilemesinden keçmey
sec-error-unknown-aia-location-type = Şeadetname AIA uzantısında bilinmegen qonum türü
sec-error-bad-http-response = Sunucı fena HTTP cevabını qaytardı
sec-error-bad-ldap-response = Sunucı fena LDAP cevabını qaytardı
sec-error-failed-to-encode-data = Veriler ASN1 kodlandırıcısı ile kodlandırılamadı
sec-error-bad-info-access-location = Şeadetname uzantısında fena malümat irişimi qonumı
sec-error-libpkix-internal = Şeadetname keçerlilemesi esnasında Libpkix dahiliy hatası sudur etti.
sec-error-pkcs11-general-error = Bir PKCS #11 modüli qurtarılalmağan bir hatanıñ sudur etken olğanını köstergen CKR_GENERAL_ERROR qaytardı.
sec-error-pkcs11-function-failed = Bir PKCS #11 modüli istengen işlevniñ icra etilamağanını köstergen CKR_FUNCTION_FAILED qaytardı. Aynı ameliyeniñ tekrar deñenmesi muvafaqiyetli olabilir.
sec-error-pkcs11-device-error = Bir PKCS #11 modüli jeton yaki yuva ile bir meseleniñ sudur etken olğanını köstergen CKR_DEVICE_ERROR qaytardı.
sec-error-bad-info-access-method = Şeadetname uzantısında bilinmegen malümat irişimi usulı.
sec-error-crl-import-failed = Bir Şeadetname Keri-çağırım Listesini (CRL) ital etmege talpınğanda hata.
sec-error-expired-password = Sır-söz eskirgen.
sec-error-locked-password = Sır-söz kilitli.
sec-error-unknown-pkcs11-error = Bilinmegen PKCS #11 hatası.
sec-error-bad-crl-dp-url = CRL dağıtım noqtası isminde keçersiz yaki desteklenmegen URL.
sec-error-cert-signature-algorithm-disabled = Şeadetname, emniyetli olmağanından dolayı ğayrıqabilleştirilgen bir imza algoritması qullanılaraq imzalandı.
mozilla-pkix-error-key-pinning-failure = Sunucı anahtar tüyreme (HPKP) qullana amma tüyreme kümesi ile eşleşken itimatlı bir şeadetname zıncırı inşa etilamadı. Anahtar tüyreme ihlâlleri üstünden aydanalmaz.
mozilla-pkix-error-ca-cert-used-as-end-entity = Sunucı, kendisini şeadetname salâhiyeti olaraq kimliklendirgen temel qısıtlamalar uzantısı ile bir şeadetname qullana. Münasip-ihraclı şeadetname içün böyle olmaması lâzim.
mozilla-pkix-error-inadequate-key-size = Sunucı, emniyetli bir bağlantı tesisi içün anahtar uzunlığı fazla qısqa olğan bir şeadetname ibraz etti.
mozilla-pkix-error-v1-cert-used-as-ca = Sunucınıñ şeadetnamesini ihrac etmek içün bir itimat lengeri olmağan bir X.509 sürüm 1 şeadetnamesi qullanıldı. X.509 sürüm 1 şeadetnameleri taqbih etilgendir ve diger şeadetnamelerni imzalamaq içün qullanılmamaları lâzim.
mozilla-pkix-error-not-yet-valid-certificate = Sunucı, ale keçerli olmağan bir şeadetname ibraz etti.
mozilla-pkix-error-not-yet-valid-issuer-certificate = Sunucınıñ şeadetnamesini ihrac etmek içün ale keçerli olmağan bir şeadetname qullanıldı.
mozilla-pkix-error-signature-algorithm-mismatch = Şeadetnameniñ imza alanındaki imza algoritması, signatureAlgorithm alanındaki algoritma ile eşleşmey.
mozilla-pkix-error-ocsp-response-for-cert-missing = OCSP cevabı doğrulana olğan şeadetname içün bir status dahil etmey.
mozilla-pkix-error-validity-too-long = Sunucı fazla uzun keçerli olğan bir şeadetname ibraz etti.
mozilla-pkix-error-required-tls-feature-missing = Şart olğan bir TLS hususiyeti eksiktir.
mozilla-pkix-error-invalid-integer-encoding = Sunucı, keçersiz bir tamsayı kodlaması muhteviy bir şeadetname sundı. Adetiy sebepleri arasında menfiy seri numaraları, menfiy RSA modüli ve kereginden daha uzun kodlandırmalar olabilir.
mozilla-pkix-error-empty-issuer-name = Sunucı, boş bir ihraccı güzide adını (DN) muhteviy bir şeadetname ibraz etti.
mozilla-pkix-error-additional-policy-constraint-failed = Bu şeadetnameni doğrulağanda ek bir siyaset qısıtlaması muvaffaqiyetsiz edi.
mozilla-pkix-error-self-signed-cert = Şeadetnamege itimat etilmey çünki öz-imzalıdır.
