# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = Адкрыць
    .accesskey = А
places-open-tab =
    .label = Адкрыць у новай картцы
    .accesskey = в
places-open-all-in-tabs =
    .label = Адкрыць усе ў картках
    .accesskey = у
places-open-window =
    .label = Адкрыць у новым акне
    .accesskey = н
places-open-private-window =
    .label = Адкрыць у новым прыватным акне
    .accesskey = п
places-new-bookmark =
    .label = Новая закладка…
    .accesskey = Н
places-new-folder-contextmenu =
    .label = Новая папка…
    .accesskey = п
places-new-folder =
    .label = Новая папка…
    .accesskey = Н
places-new-separator =
    .label = Новы межнік
    .accesskey = м
places-view =
    .label = Прагляд
    .accesskey = г
places-by-date =
    .label = Па даце
    .accesskey = д
places-by-site =
    .label = Па сайце
    .accesskey = п
places-by-most-visited =
    .label = Па колькасці наведванняў
    .accesskey = л
places-by-last-visited =
    .label = Па апошнім наведванні
    .accesskey = а
places-by-day-and-site =
    .label = Па даце і сайце
    .accesskey = і
places-history-search =
    .placeholder = Шукаць у гісторыі
places-bookmarks-search =
    .placeholder = Шукаць у закладках
places-delete-domain-data =
    .label = Забыць гэты сайт
    .accesskey = З
places-sortby-name =
    .label = Сартаваць па назве
    .accesskey = н
places-properties =
    .label = Уласцівасці
    .accesskey = У
