# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Скончыўся час, патрэбны для выканання дзеяння
openFile = Адкрыць файл
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Шукаць "%2$S" у %1$S
contextMenuSearch.accesskey = Ш
contextMenuPrivateSearch = Пошук у прыватным акне
contextMenuPrivateSearch.accesskey = р
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Пошук у %S у прыватным акне
contextMenuPrivateSearchOtherEngine.accesskey = р
bookmarkAllTabsDefault = [Назва папкі]
unsignedAddonsDisabled.message = Адзін або некалькі з усталяваных дадаткаў не могуць быць правераны, таму яны былі адключаны.
unsignedAddonsDisabled.learnMore.label = Даведацца больш
unsignedAddonsDisabled.learnMore.accesskey = Д
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Апошні доступ %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = Спасылкі %S://
crashedpluginsMessage.title = Плагін %S пацярпеў крах.
crashedpluginsMessage.reloadButton.label = Перазагрузіць старонку
crashedpluginsMessage.reloadButton.accesskey = П
crashedpluginsMessage.submitButton.label = Даслаць справаздачу пра падзенне браўзера
crashedpluginsMessage.submitButton.accesskey = Д
crashedpluginsMessage.learnMore = Даведацца больш…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Вы мелі на ўвазе пераход на %S?
keywordURIFixup.goTo = Так, перайсці на %S
keywordURIFixup.goTo.accesskey = Т
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Абнавіць да %S
update.downloadAndInstallButton.accesskey = А
menuOpenAllInTabs.label = Адкрыць усе ў картках
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Абнавіць гэту старонку
tabHistory.goBack = Вярнуцца на гэтую старонку
tabHistory.goForward = Пайсці на гэтую старонку
# URL Bar
pasteAndGo.label = Уставіць і перайсці
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Абнавіць дзейную старонку (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Спыніць загрузку старонкі (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Аднавіць маштаб (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Пераключыць рэжым чытальніка (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, Скінуць маштаб
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Паказаць вашы закладкі (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Паказаць прагрэс бягучых сцягванняў (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Адкрыць новае вакно (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Адкрыць новую картку (%S)
newTabContainer.tooltip = Адкрыць новую картку (%S)\nНацісніце і ўтрымлівайце, каб адкрыць новую картку кантэйнера
newTabAlwaysContainer.tooltip = Выберыце кантэйнер, каб адкрыць новую картку
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Дазволіць %S выкарыстоўваць вашы дадзеныя canvas-выявы HTML5?
canvas.siteprompt2.warning = Гэта можа быць выкарыстана для адназначнай ідэнтыфікацыі вашага камп'ютара.
canvas.block = Блакаваць
canvas.block.accesskey = Б
canvas.allow2 = Дазволіць
canvas.allow2.accesskey = Д
canvas.remember2 = Запомніць гэты выбар
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Праверана: %S
identity.identified.verified_by_you = Вы дадалі выключэнне бяспекі для гэтага сайта.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Сертыфікат выдадзены: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Не абаронена
identity.notSecure.tooltip = Злучэнне не бяспечнае
identity.extension.label = Пашырэнне (%S)
identity.extension.tooltip = Загружана пашырэннем: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Паменшыць (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Скінуць узровень павелічэння (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Павялічыць (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Выразаць (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Капіяваць (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Уставіць (%S)
geolocation.allow = Дазволіць
geolocation.allow.accesskey = Д
geolocation.block = Блакаваць
geolocation.block.accesskey = Б
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Гэта адкрые сістэмныя налады месцазнаходжання. Калі ласка, дайце %S дазвол на доступ да месцазнаходжання.
geolocation.shareWithSite4 = Дазволіць %S доступ да вашага месцазнаходжання?
geolocation.shareWithFile4 = Дазволіць гэтаму лакальнаму файлу доступ да вашага месцазнаходжання?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Дазволіць %1$S даць %2$S доступ да вашага месцазнаходжання?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Даць %S дазвол на вызначэнне месцазнаходжання ў наладах сістэмы.
geolocation.systemSettingsTitle = Чакаецца дазвол на доступ да месцазнаходжання
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Сістэма папросіць вас даць гэты дазвол для %S.
geolocation.remember = Памятаць гэтае рашэнне
# Virtual Reality Device UI
xr.allow2 = Дазволіць
xr.allow2.accesskey = Д
xr.block = Блакаваць
xr.block.accesskey = Б
xr.shareWithSite4 = Дазволіць %S атрымліваць доступ да прылад віртуальнай рэальнасці? Гэта можа адкрыць канфідэнцыяльную інфармацыю.
xr.shareWithFile4 = Дазволіць гэтаму лакальнаму файлу атрымліваць доступ да прылад віртуальнай рэальнасці? Гэта можа адкрыць канфідэнцыяльную інфармацыю.
xr.remember = Запомніць гэты выбар
# Persistent storage UI
persistentStorage.allow = Дазволіць
persistentStorage.allow.accesskey = Д
persistentStorage.block.label = Блакаваць
persistentStorage.block.accesskey = Б
persistentStorage.allowWithSite2 = Дазволіць %S захоўваць дадзеныя ў пастаянным сховішчы?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Дазволіць
webNotifications.allow2.accesskey = Д
webNotifications.notNow = Не зараз
webNotifications.notNow.accesskey = Н
webNotifications.never = Ніколі не дазваляць
webNotifications.never.accesskey = л
webNotifications.alwaysBlock = Заўсёды блакаваць
webNotifications.alwaysBlock.accesskey = Б
webNotifications.block = Блакаваць
webNotifications.block.accesskey = Б
webNotifications.receiveFromSite3 = Дазволіць %S адпраўляць вам абвесткі?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S хоча атрымаць доступ да іншых праграм і службаў на гэтай прыладзе.
localhost.remember2 = Запомніць мой выбар для гэтага сайта
localhost.allowlabel = Дазволіць
localhost.blocklabel = Блакаваць
localhost.allow.accesskey = Д
localhost.block.accesskey = Б
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S хоча атрымаць доступ да праграм і службаў на прыладах, падлучаных да вашай лакальнай сеткі.
localNetwork.remember2 = Запомніць мой выбар для гэтага сайта
localNetwork.allowLabel = Дазволіць
localNetwork.allow.accesskey = Д
localNetwork.blockLabel = Блакаваць
localNetwork.block.accesskey = Б
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Пакінуць гэта месца!
safebrowsing.getMeOutOfHereButton.accessKey = П
safebrowsing.deceptiveSite = Падроблены сайт!
safebrowsing.notADeceptiveSiteButton.label = Гэта не падроблены сайт…
safebrowsing.notADeceptiveSiteButton.accessKey = П
safebrowsing.reportedAttackSite = Папярэджанне: нападны сайт!
safebrowsing.notAnAttackButton.label = Гэты сайт не атакуе камп'ютары…
safebrowsing.notAnAttackButton.accessKey = А
safebrowsing.reportedUnwantedSite = Есць інфармацыя, што гэты сайт змяшчае непажаданыя праграмы!
safebrowsing.reportedHarmfulSite = Вядомы шкодны сайт!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Пошук %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Перазапусціць %S у рэжыме вырашэння праблем?
troubleshootModeRestartPromptMessage = Вашы пашырэнні, тэмы і асабістыя налады будуць часова адключаны.
troubleshootModeRestartButton = Перазапусціць
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Гэта старонка запавольвае %1$S. Каб паскорыць працу вашага браўзера, спыніце гэтую старонку.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Вэб-старонка запавольвае %1$S. Каб паскорыць працу вашага браўзера, спыніце тую старонку.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = “%1$S” запавольвае %2$S. Каб паскорыць працу вашага браўзера, спыніце тую старонку.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = “%1$S” запавольвае %2$S. Каб паскорыць ваш браўзер, спыніце гэтае пашырэнне.
processHang.add-on.learn-more.text = Падрабязней
processHang.button_stop2.label = Спыніць
processHang.button_stop2.accessKey = ы
processHang.button_debug.label = Наладзіць сцэнар
processHang.button_debug.accessKey = Н
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Паказаць акно на увесь экран (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Перамясціць бакавую панэль улева
sidebar.moveToRight = Перамясціць бакавую панэль управа
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Вы павінны ўключыць DRM, каб прайграць некаторыя аўдыё ці відэа на гэтай старонцы.
emeNotifications.drmContentDisabled.button.label = Уключыць DRM
emeNotifications.drmContentDisabled.button.accesskey = У
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S усталёўвае кампаненты, неабходныя для прайгравання аўдыё або відэа на гэтай старонцы. Калі ласка, паўтарыце спробу пазней.
emeNotifications.unknownDRMSoftware = Невядома
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Уладкаваць %S
decoder.noCodecs.button = Даведацца, як
decoder.noCodecs.accesskey = Д
decoder.noCodecsLinux.message = Для прайгравання відэа вам можа спатрэбіцца ўсталяванне неабходных відэакодэкаў.
decoder.noHWAcceleration.message = Для паляпшэння якасці відэа вам можа спатрэбіцца Media Feature Pack ад Microsoft.
decoder.noPulseAudio.message = Для прайгравання аўдыё вам можа спатрэбіцца неабходнае праграмнае забеспячэнне PulseAudio.
decoder.unsupportedLibavcodec.message = libavcodec можа быць пашкоджаны ці не падтрымліваецца, і павінен быць абноўлены для прайгравання відэа.
decoder.decodeError.message = Пры дэкадаванні медыя адбылася памылка.
decoder.decodeError.button = Паведаміць аб праблеме з сайтам
decoder.decodeError.accesskey = П
decoder.decodeWarning.message = Пры дэкадаванні медыя адбылася памылка, якую можна выправіць.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Вы павінны ўвайсці ў гэту сетку перад тым, як зможаце атрымаць доступ у Інтэрнэт.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Адкрыць старонку ўваходу ў сетку
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Дазволы для %S
permissions.remove.tooltip = Выдаліць гэты дазвол і спытаць зноў
permissions.fullscreen.promptCanceled = Ануляваны чаканыя запыты дазволу: запыты на дазвол не павінны выдавацца перад уваходам у поўнаэкранны DOM.
permissions.fullscreen.fullScreenCanceled = Поўнаэкранны рэжым DOM выключаны: запыты на дазвол не павінны выдавацца ў час поўнаэкраннага DOM.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-біт
aboutDialog.architecture.thirtyTwoBit = 32-біт
midi.allow.label = Дазволіць
midi.allow.accesskey = Д
midi.block.label = Блакаваць
midi.block.accesskey = Б
midi.remember = Запомніць гэты выбар
midi.shareWithFile = Дазволіць гэтаму лакальнаму файлу доступ да вашых прылад MIDI?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Дазволіць %S доступ да вашых прылад MIDI?
midi.shareSysexWithFile = Дазволіць гэтаму лакальнаму файлу доступ да вашых прылад MIDI, а таксама дасылаць/атрымліваць SysEx паведамленні?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Дазволіць %S доступ да вашых прылад MIDI, а таксама дасылаць/атрымліваць SysEx паведамленні?
serial.allow.label = Дазволіць
serial.allow.accesskey = Д
serial.block.label = Блакаваць
serial.block.accesskey = Б
serial.shareWithFile = Дазволіць гэтаму лакальнаму файлу доступ да вашых паслядоўных партоў?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Дазволіць %S доступ да вашых паслядоўных партоў?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Назад
storageAccess1.Allow.label = Дазволiць
storageAccess1.Allow.accesskey = Д
storageAccess1.DontAllow.label = Блакаваць
storageAccess1.DontAllow.accesskey = Б
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Дазволiць %1$S выкарыстоўваць свае кукi на %2$S?
storageAccess1.hintText = Вы можаце заблакаваць доступ, калі няясна, навошта %1$S патрэбны гэтыя дадзеныя.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Шукаць у Інтэрнэце “%S”
