# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Vyhledávání { $host }…
network-connection-status-connected = Připojeno k { $host }…
network-connection-status-sending-request = Odesílání požadavku na { $host }…
network-connection-status-transferring-data = Přenášení dat z { $host }…
network-connection-status-connecting = Připojování k { $host }…
network-connection-status-read = Přečteno { $host }
network-connection-status-wrote = Zapsáno { $host }
network-connection-status-waiting = Čekání na { $host }…
network-connection-status-looked-up = Vyhledáno { $host }…
network-connection-status-tls-handshake = Navazování TLS spojení k { $host }…
network-connection-status-tls-handshake-finished = TLS spojení k { $host } navázáno…
