# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Vyhledávání { $host }…
network-connection-status-connected = Připojeno k { $host }…
network-connection-status-sending-request = Odesílání požadavku na { $host }…
network-connection-status-transferring-data = Přenášení dat z { $host }…
network-connection-status-connecting = Připojování k { $host }…
