# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

formPostSecureToInsecureWarning.title = Безбедносно предупредување
formPostSecureToInsecureWarning.message = Информациите што ги внесовте на оваа страница ќе бидат испратени преку небезбедна врска и може да бидат прочитани од трета страна.\n\nДали сте сигурни дека сакате да ги испратите овие информации?
formPostSecureToInsecureWarning.continue = Продолжи
