# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SaveImageTitle = Снимање на слика
SaveMediaTitle = Сними медиум
SaveVideoTitle = Снимање на видео
SaveAudioTitle = Снимање на аудио
SaveLinkTitle = Снимање на врска
WebPageCompleteFilter = Мрежна страница, целосна
WebPageHTMLOnlyFilter = Мрежна страница, само HTML
WebPageXHTMLOnlyFilter = Мрежна страница, само XHTML
WebPageSVGOnlyFilter = Мрежна страница, само SVG
WebPageXMLOnlyFilter = Мрежна страница, само XML
# LOCALIZATION NOTE (UntitledSaveFileName):
#    This is the default filename used when saving a file if a filename could
#    not be determined or if a filename was invalid. A period and file
#    extension may be appended to this string.
UntitledSaveFileName = Без наслов
