# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE (uninstall.confirmation.title) %S is the name of the extension which is about to be uninstalled.
uninstall.confirmation.title = Деинсталирај %S
# LOCALIZATION NOTE (uninstall.confirmation.message) %S is the name of the extension which is about to be uninstalled.
uninstall.confirmation.message = Проширувањто “%S” бара да се деинсталира. Што би сакале да направите?
uninstall.confirmation.button-0.label = Деинсталирај
uninstall.confirmation.button-1.label = Задржи
saveaspdf.saveasdialog.title = Сними како
# LOCALIZATION NOTE (newTabControlled.message2) %S is the icon and name of the extension which updated the New Tab page.
newTabControlled.message2 = Проширување, %S, ја промени страницата што ја гледате кога ќе отворите ново јазиче.
newTabControlled.learnMore = Дознајте повеќе
# LOCALIZATION NOTE (homepageControlled.message) %S is the icon and name of the extension which updated the homepage.
homepageControlled.message = Проширување, %S, го промени тоа што го гледате кога ја отварате домашната страница или нови прозорци.
homepageControlled.learnMore = Дознајте повеќе
# LOCALIZATION NOTE (tabHideControlled.message) %1$S is the icon and name of the extension which hid tabs, %2$S is the icon of the all tabs button.
tabHideControlled.message = Проширувањето %1$S крие некои од Вашите јазичиња. Сè уште можете да пристапите до сите ваши јазичиња преку %2$S.
tabHideControlled.learnMore = Дознајте повеќе
