# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Tebɣiḍ ad tegreḍ taflest di "%S" i tiggawin-agi?
unnamedCA = Adabu n uselken (ulac isem)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Ma ulac aɣilif, sekcem awal uffir ittusqedcen i wewgelhen n weḥraz n uselkin-agi.
# Page Info
pageInfo_NoEncryption = Tuqqna ur teţwawgelhen ara
pageInfo_Privacy_None1 = Asmel web %S ur isefrak ara awgelhen i wesbtar ittuskanen akka tura.
pageInfo_Privacy_None2 = Talɣut ittwaznen ɣef Internet s war awgelhen zemren ad tt-walin imdanen-nniḍen ticki tettwazan.
pageInfo_Privacy_None4 = Asebter i tettwaliḍ akka tura, yettwawgelhen send tuzzna yines ɣeṛ Internet.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Tuqqna tettuwgelhen (%1$S, %2$S bit keys, %3$S)
pageInfo_BrokenEncryption = Tuqqna taraɣelsant (tisura %1$S, %2$S ibiten, %3$S)
pageInfo_Privacy_Encrypted1 = Asebter yettwaskanen yakan tura, yettwawgelhen send tuzna-yines ɣeṛ Internet.
pageInfo_Privacy_Encrypted2 = Awgelhen yettara askan n usebter yewɛeṛ ticki tewwazan gar iselkimen i yemdanen ur nettwasireg ara. Ihi ur yezmir ara akken yiwen ad iɣaṛ asebter-agi ticki iteddu deg uẓeṭṭa.
pageInfo_MixedContent = Tuqqna s uwegelhen amuran
pageInfo_MixedContent2 = Kra n yeḥricen n usebter yettwaskanen akka tura, ur ttwawgelhen ara send tuzna nsen ɣeṛ Internet.
pageInfo_WeakCipher = Tuqqna-inek ɣeṛ usmel-a tesseqdac awgelhen fessusen ur nelli ara d uslig. Imadanen nniḍen zemren ad walin talɣut neɣ ad sniflen tiddin n usmel.
pageInfo_CertificateTransparency_Compliant = Asmel-agi web yettqadeṛ tasertit taserwestant n uselkin.
# Token Manager
password_not_set = (ur iţusbadu ara)
