# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Timp scjadût
openFile = Vierç file
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Cîr “%2$S” cun %1$S
contextMenuSearch.accesskey = u
contextMenuPrivateSearch = Cîr intun barcon privât
contextMenuPrivateSearch.accesskey = h
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Cîr cun %S intun barcon privât
contextMenuPrivateSearchOtherEngine.accesskey = h
bookmarkAllTabsDefault = [Non de cartele]
unsignedAddonsDisabled.message = Nol è stât pussibil verificâ un o plui components adizionâi instalâts e duncje a son stâts disativâts.
unsignedAddonsDisabled.learnMore.label = Plui informazions
unsignedAddonsDisabled.learnMore.accesskey = L
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Ultin acès: %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = Colegaments %S://
crashedpluginsMessage.title = Il plugin %S al è colassât.
crashedpluginsMessage.reloadButton.label = Torne cjame la pagjine
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = Mande une segnalazion di colàs
crashedpluginsMessage.submitButton.accesskey = S
crashedpluginsMessage.learnMore = Plui informazions…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Volevistu lâ su %S?
keywordURIFixup.goTo = Sì, puartimi su %S
keywordURIFixup.goTo.accesskey = S
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Inzorne ae version %S
update.downloadAndInstallButton.accesskey = I
menuOpenAllInTabs.label = Vierç dut in schedis
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Torne cjame cheste pagjine
tabHistory.goBack = Torne indaûr a cheste pagjine
tabHistory.goForward = Va indevant a cheste pagjine
# URL Bar
pasteAndGo.label = Tache e va
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Torne cjarie cheste pagjine (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Ferme di cjariâ cheste pagjine (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Ristabilìs il nivel di ingrandiment (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Comute viodude di leture (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, ristabilìs il nivel di zoom predefinît
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Mostre i tiei segnelibris (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Visualize l'avanzament dai file che si sta discjamant (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Vierç un gnûf barcon (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Vierç une gnove schede (%S)
newTabContainer.tooltip = Vierç une gnove schede (%S)\nTen fracât par vierzi une gnove schede contignidôr
newTabAlwaysContainer.tooltip = Selezione un contignidôr par vierzi une gnove schede
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Permeti a %S di doprâ i dâts des imagjins canvas HTML5?
canvas.siteprompt2.warning = Chestis informazions a podaressin vignî dopradis par identificâ in mût univoc il to computer.
canvas.block = Bloche
canvas.block.accesskey = B
canvas.allow2 = Permet
canvas.allow2.accesskey = P
canvas.remember2 = Visiti cheste decision
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Verificât par: %S
identity.identified.verified_by_you = Tu âs zontât une ecezion ae sigurece par chest sît.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Certificât dât fûr a: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = No sigûr
identity.notSecure.tooltip = La conession no je sigure
identity.extension.label = Estension (%S)
identity.extension.tooltip = Cjariade de estension: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Impiçulìs (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Azere nivel di ingrandiment (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Ingrandìs (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Taie (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Copie (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Tache (%S)
geolocation.allow = Permet
geolocation.allow.accesskey = P
geolocation.block = Bloche
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = A vignaran viertis lis impostazions di sisteme pe posizion. Garantìs a %S il permès di acedi ae posizion.
geolocation.shareWithSite4 = Permeti a %S di acedi ae tô posizion?
geolocation.shareWithFile4 = Permeti a chest file locâl di acedi ae tô posizion?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Permeti a %1$S di concedi a %2$S i permès par acedi ae tô posizion?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Garantî a %S il permès di acedi ae posizion tes impostazions di sisteme.
geolocation.systemSettingsTitle = In spiete dal permès di acedi ae posizion
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Il sisteme al domandarà di garantî chest permès a %S.
geolocation.remember = Visiti cheste decision
# Virtual Reality Device UI
xr.allow2 = Permet
xr.allow2.accesskey = P
xr.block = Bloche
xr.block.accesskey = B
xr.shareWithSite4 = Permeti a %S di acedi ai dispositîfs di realtât virtuâl? Chest al podarès palesâ informazions sensibilis riservadis.
xr.shareWithFile4 = Permeti a chest file locâl di acedi ai dispositîfs di realtât virtuâl? Chest al podarès palesâ informazions sensibilis riservadis.
xr.remember = Visiti cheste decision
# Persistent storage UI
persistentStorage.allow = Permet
persistentStorage.allow.accesskey = P
persistentStorage.block.label = Bloche
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Permeti a %S di memorizâ dâts tal archivi persistent?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Permet
webNotifications.allow2.accesskey = P
webNotifications.notNow = No cumò
webNotifications.notNow.accesskey = c
webNotifications.never = No sta permeti mai
webNotifications.never.accesskey = m
webNotifications.alwaysBlock = Bloche simpri
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = Bloche
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Permeti a %S di mandâ notifichis?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S al vûl rivâ a acedi a altris aplicazions e servizis su chest dispositîf.
localhost.remember2 = Visiti la mê sielte par chest sît
localhost.allowlabel = Permet
localhost.blocklabel = Bloche
localhost.allow.accesskey = P
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S al vûl rivâ a acedi aes aplicazions e ai servizis sui dispositîfs conetûts te tô rêt locâl.
localNetwork.remember2 = Visiti la mê sielte par chest sît
localNetwork.allowLabel = Permet
localNetwork.allow.accesskey = P
localNetwork.blockLabel = Bloche
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Tirimi fûr di ca!
safebrowsing.getMeOutOfHereButton.accessKey = T
safebrowsing.deceptiveSite = Sît ingjanôs!
safebrowsing.notADeceptiveSiteButton.label = Chest nol è un sît ingjanôs…
safebrowsing.notADeceptiveSiteButton.accessKey = I
safebrowsing.reportedAttackSite = Sît segnalât come malevul!
safebrowsing.notAnAttackButton.label = Chest nol è un sît malevul…
safebrowsing.notAnAttackButton.accessKey = a
safebrowsing.reportedUnwantedSite = Sît segnalât che al conten software malvolût!
safebrowsing.reportedHarmfulSite = Sît segnalât come danôs!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Cîr %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Tornâ a inviâ %S in modalitât risoluzion problemis?
troubleshootModeRestartPromptMessage = Lis tôs estensions, i temis e lis impostazions personalizadis a vignaran disativadis in mût temporani.
troubleshootModeRestartButton = Torne invie
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = %1$S al sta lant plui a planc par vie di cheste pagjine. Par sveltî il navigadôr, ferme cheste pagjine.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = %1$S al sta lant plui a planc par colpe di un pagjine. Par sveltî il navigadôr, ferme chê pagjine
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = “%1$S” al sta morestant %2$S. Par sveltî il navigadôr, ferme chê pagjine.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = “%1$S” al sta morestant %2$S. Par sveltî il navigadôr, ferme chê estension.
processHang.add-on.learn-more.text = Plui informazions
processHang.button_stop2.label = Ferme
processHang.button_stop2.accessKey = F
processHang.button_debug.label = Debug dal script
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Visualize il barcon a plen visôr (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Sposte sbare laterâl a çampe
sidebar.moveToRight = Sposte sbare laterâl a diestre
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Tu scugnis abilitâ il DRM par riprodusi cualchi contignût audio o video su cheste pagjine.
emeNotifications.drmContentDisabled.button.label = Abilite DRM
emeNotifications.drmContentDisabled.button.accesskey = E
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S al sta instalant components necessaris par riprodusi il contignût audio o video su cheste pagjine. Torne prove plui indenant.
emeNotifications.unknownDRMSoftware = No cognossût
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Personalize %S
decoder.noCodecs.button = Impare cemût
decoder.noCodecs.accesskey = I
decoder.noCodecsLinux.message = Par riprodusi il video tu podaressis vê di instalâ i codecs video necessaris.
decoder.noHWAcceleration.message = Par miorâ la cualitât video tu podaressis vê di instalâ il pachet di funzionalitâts multimediâls di Microsoft.
decoder.noPulseAudio.message = Par riprodusi l'audio tu podaressis vê di instalâ il software PulseAudio necessari.
decoder.unsupportedLibavcodec.message = libavcodec al podarès jessi vulnerabil o nol è supuartât e, par riprodusi il video, tu varessis di inzornâlu.
decoder.decodeError.message = Al è capitât un erôr intant che si decodificave une risorse multimediâl.
decoder.decodeError.button = Segnale probleme cul sît
decoder.decodeError.accesskey = S
decoder.decodeWarning.message = Al è capitât un erôr recuperabil intant che si decodificave une risorse multimediâl.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Tu scugnis eseguî l'acès a cheste rêt prime di podê lâ su internet.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Vierç la pagjine di acès de rêt
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Permès par %S
permissions.remove.tooltip = Scancele chescj permès e torne domande
permissions.fullscreen.promptCanceled = Richiestis di permès in spiete anuladis: no si varès di fâ richiestis di permès prime di jentrâ in modalitât plen visôr DOM.
permissions.fullscreen.fullScreenCanceled = Jessût de modalitât plen visôr DOM: no si varès di fâ richiestis di permè intant che si stâ in modalitât plen visôr DOM.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bit
aboutDialog.architecture.thirtyTwoBit = 32-bit
midi.allow.label = Permet
midi.allow.accesskey = P
midi.block.label = Bloche
midi.block.accesskey = B
midi.remember = Visiti cheste decision
midi.shareWithFile = Permeti a chest file locâl di acedi ai tiei dispositîfs MIDI?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Permeti a %S di acedi ai tiei dispositîfs MIDI?
midi.shareSysexWithFile = Permeti a chest file locâl di acedi ai tiei dispositîfs MIDI e inviâ/ricevi messaçs SysEx?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Permeti a %S di acedi ai tiei dispositîfs MIDI e inviâ/ricevi messaçs SysEx?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Indaûr
storageAccess1.Allow.label = Permet
storageAccess1.Allow.accesskey = P
storageAccess1.DontAllow.label = Bloche
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Permeti a %1$S di doprâ i siei cookies su %2$S?
storageAccess1.hintText = Tu puedis decidi di blocâ l'acès se no ti è clâr il motîf parcè che %1$S al vedi bisugne di chescj dâts.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Cîr “%S” tal web
