# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

removeButton = Noņemt
# LOCALIZATION NOTE (activeStatus): Displayed for an active study
activeStatus = Aktīvs
# LOCALIZATION NOTE (completeStatus): Displayed for a study that is already complete
completeStatus = Pabeigts
updateButtonWin = Atjaunināt iestatījumus
updateButtonUnix = Atjaunināt iestatījumus
learnMore = Uzzināt vairāk
noStudies = Jūs vēl neesat piedalījušies nevienā pētījumā.
disabledList = Šis ir visu jūsu pētījumu saraksts. Jauni pētījumi netiks veikti.
# LOCALIZATION NOTE (enabledList): %S is brandShortName (e.g. Firefox)
enabledList = Kas ir šis? %S laiku pa laikam var uzstādīt un palaist pētījumus.
