# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE (resetUnusedProfile.message): %S is brandShortName.
resetUnusedProfile.message = Šķiet, ka %S nav kādu laiku izmantots. Vai satīrīt to svaigai, kā no jauna pieredzei? Starp citu, laipni lūdzam atpakaļ!
# LOCALIZATION NOTE (resetUninstalled.message): %S is brandShortName.
resetUninstalled.message = Izskatās, ka esat pārinstalējis %S. Gribat, lai satīram visu, lai tā būu kā jauna?
# LOCALIZATION NOTE (refreshProfile.resetButton.label): %S is brandShortName.
refreshProfile.resetButton.label = Atjaunināt %S…
refreshProfile.resetButton.accesskey = t
