#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

# LOCALIZATION NOTE: Some of these URLs are currently 404s, but should be coming
# online shortly.

# LOCALIZATION NOTE (bookmarks_title):
# title for the folder that will contains the default bookmarks
#define bookmarks_title Mobyl

# LOCALIZATION NOTE (bookmarks_welcome):
# link title for about:firstrun
#define bookmarks_welcome Firefox: Wolkom

# LOCALIZATION NOTE (bookmarks_aboutBrowser):
# link title for about:fennec
#define bookmarks_aboutBrowser Firefox: Oer jo browser

# LOCALIZATION NOTE (bookmarks_weave):
# link title for https://www.mozilla.com/en-US/mobile/weave
#define bookmarks_sync Firefox: Syngronisearje mei Weave Sync

# LOCALIZATION NOTE (bookmarks_addons):
# link title for https://addons.mozilla.org/en-US/mobile
#define bookmarks_addons Firefox: Oanpasse mei tafoegings

# LOCALIZATION NOTE (bookmarks_support):
# link title for https://mobile.support.mozilla.com
#define bookmarks_support Firefox: Stipe

#unfilter emptyLines
