# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Tempo esgotado
openFile = Abrir arquivo
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Pesquisar “%2$S” no %1$S
contextMenuSearch.accesskey = P
contextMenuPrivateSearch = Pesquisar em uma janela privativa
contextMenuPrivateSearch.accesskey = e
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Pesquisar com %S em uma janela privativa
contextMenuPrivateSearchOtherEngine.accesskey = e
bookmarkAllTabsDefault = [Nome da pasta]
unsignedAddonsDisabled.message = Uma ou mais extensões instaladas não puderam ser verificadas e foram desativadas.
unsignedAddonsDisabled.learnMore.label = Saiba mais
unsignedAddonsDisabled.learnMore.accesskey = b
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Último acesso %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = Links %S://
crashedpluginsMessage.title = O plugin %S falhou.
crashedpluginsMessage.reloadButton.label = Recarregar página
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = Enviar um relatório de falha
crashedpluginsMessage.submitButton.accesskey = E
crashedpluginsMessage.learnMore = Saiba mais…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Você quis dizer abrir %S?
keywordURIFixup.goTo = Sim, abrir %S
keywordURIFixup.goTo.accesskey = S
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Atualizar para %S
update.downloadAndInstallButton.accesskey = A
menuOpenAllInTabs.label = Abrir tudo em abas
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Recarregar esta página
tabHistory.goBack = Voltar para esta página
tabHistory.goForward = Avançar para esta página
# URL Bar
pasteAndGo.label = Colar e abrir
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Recarregar página atual (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Interromper o carregamento desta página (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Redefinir o nível de zoom (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Ativar/Desativar modo de leitura (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, redefinir nível de zoom
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Mostrar seus favoritos (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Exibir o progresso dos downloads em andamento (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Abrir uma nova janela (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Abrir nova aba (%S)
newTabContainer.tooltip = Abrir nova aba (%S)\nMantenha pressionado para abrir nova aba contêiner
newTabAlwaysContainer.tooltip = Selecione um contêiner para abrir uma nova aba
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Permitir que %S use seus dados de imagem de canvas HTML5?
canvas.siteprompt2.warning = Isso pode ser usado para identificar unicamente este computador.
canvas.block = Bloquear
canvas.block.accesskey = B
canvas.allow2 = Permitir
canvas.allow2.accesskey = P
canvas.remember2 = Memorizar esta decisão
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Homologado por: %S
identity.identified.verified_by_you = Você adicionou uma exceção de segurança para este site.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Certificado emitido para: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Não seguro
identity.notSecure.tooltip = Conexão não segura
identity.extension.label = Extensão (%S)
identity.extension.tooltip = Carregado pela extensão: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Reduzir (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Redefinir nível de zoom (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Ampliar (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Cortar (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Copiar (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Colar (%S)
geolocation.allow = Permitir
geolocation.allow.accesskey = P
geolocation.block = Bloquear
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Isto abre as configurações de localização do sistema. Dê permissão de localização ao %S.
geolocation.shareWithSite4 = Permitir que %S acesse sua localização?
geolocation.shareWithFile4 = Permitir que este arquivo local acesse sua localização?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Permitir que %1$S dê permissão para %2$S acessar sua localização?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Conceder permissão de localização para %S nas configurações do sistema.
geolocation.systemSettingsTitle = Aguardando permissão de localização
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = O sistema irá pedir para você conceder esta permissão ao %S.
geolocation.remember = Memorizar esta decisão
# Virtual Reality Device UI
xr.allow2 = Permitir
xr.allow2.accesskey = P
xr.block = Bloquear
xr.block.accesskey = B
xr.shareWithSite4 = Permitir que %S acesse dispositivos de realidade virtual? Isto pode expor informações sensíveis.
xr.shareWithFile4 = Permitir que este arquivo local acesse dispositivos de realidade virtual? Isto pode expor informações sensíveis.
xr.remember = Memorizar esta decisão
# Persistent storage UI
persistentStorage.allow = Permitir
persistentStorage.allow.accesskey = P
persistentStorage.block.label = Bloquear
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Permitir que %S armazene dados no armazenamento persistente?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Permitir
webNotifications.allow2.accesskey = P
webNotifications.notNow = Agora não
webNotifications.notNow.accesskey = n
webNotifications.never = Nunca permitir
webNotifications.never.accesskey = a
webNotifications.alwaysBlock = Sempre bloquear
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = Bloquear
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Permitir que %S envie notificações?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S quer acessar outros aplicativos e serviços neste dispositivo.
localhost.remember2 = Lembrar minha escolha para este site
localhost.allowlabel = Permitir
localhost.blocklabel = Bloquear
localhost.allow.accesskey = P
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S quer acessar aplicativos e serviços em dispositivos conectados à sua rede local.
localNetwork.remember2 = Lembrar minha escolha para este site
localNetwork.allowLabel = Permitir
localNetwork.allow.accesskey = P
localNetwork.blockLabel = Bloquear
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Me tire daqui!
safebrowsing.getMeOutOfHereButton.accessKey = M
safebrowsing.deceptiveSite = Site enganoso!
safebrowsing.notADeceptiveSiteButton.label = Este não é um site enganoso…
safebrowsing.notADeceptiveSiteButton.accessKey = e
safebrowsing.reportedAttackSite = Denunciado como site de ataque!
safebrowsing.notAnAttackButton.label = Este não é um site de ataque…
safebrowsing.notAnAttackButton.accessKey = a
safebrowsing.reportedUnwantedSite = Denunciado como site de software indesejado!
safebrowsing.reportedHarmfulSite = Site nocivo denunciado!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Pesquisar %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Reiniciar o %S em modo de solução de problemas?
troubleshootModeRestartPromptMessage = Suas extensões, temas e configurações personalizadas são temporariamente desativadas.
troubleshootModeRestartButton = Reiniciar
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Esta página está reduzindo a velocidade do %1$S. Para acelerar seu navegador, interrompa esta página.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Uma página web está reduzindo a velocidade do %1$S. Para acelerar seu navegador, interrompa essa página.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = “%1$S” está reduzindo a velocidade do %2$S. Para acelerar seu navegador, interrompa essa página.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = “%1$S” está reduzindo a velocidade do %2$S. Para acelerar seu navegador, interrompa essa extensão.
processHang.add-on.learn-more.text = Saiba mais
processHang.button_stop2.label = Parar
processHang.button_stop2.accessKey = P
processHang.button_debug.label = Depurar script
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Janela em tela inteira (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Mover painel para esquerda
sidebar.moveToRight = Mover painel para direita
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Você deve ativar o DRM para reproduzir algum áudio ou vídeo nesta página.
emeNotifications.drmContentDisabled.button.label = Ativar DRM
emeNotifications.drmContentDisabled.button.accesskey = A
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S está instalando componentes necessários para reprodução do áudio ou vídeo nesta página. Tente novamente mais tarde.
emeNotifications.unknownDRMSoftware = Desconhecido
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Personalizar o %S
decoder.noCodecs.button = Saiba como
decoder.noCodecs.accesskey = S
decoder.noCodecsLinux.message = Para reproduzir o vídeo, você pode precisar instalar codecs de vídeo necessários.
decoder.noHWAcceleration.message = Para melhorar a qualidade do vídeo, pode ser necessário instalar o Media Feature Pack da Microsoft.
decoder.noPulseAudio.message = Para reproduzir áudio, pode ser necessário instalar o PulseAudio.
decoder.unsupportedLibavcodec.message = libavcodec pode ser vulnerável ou não suportado e deve ser atualizado para reproduzir o vídeo.
decoder.decodeError.message = Ocorreu um erro ao decodificar um recurso de mídia.
decoder.decodeError.button = Relatar problema no site
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = Ocorreu um erro recuperável ao decodificar um recurso de mídia.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Você precisa se autenticar nesta rede para poder acessar a internet.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Abrir página de acesso à rede
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Permissões de %S
permissions.remove.tooltip = Limpar esta permissão e perguntar novamente
permissions.fullscreen.promptCanceled = Canceladas requisições de permissão pendentes: requisições de permissão não devem ser emitidas antes de entrar em DOM de tela inteira.
permissions.fullscreen.fullScreenCanceled = Saiu do DOM de tela inteira: requisições de permissão não devem ser emitidas enquanto estiver em DOM de tela inteira.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64 bits
aboutDialog.architecture.thirtyTwoBit = 32 bits
midi.allow.label = Permitir
midi.allow.accesskey = P
midi.block.label = Bloquear
midi.block.accesskey = B
midi.remember = Memorizar esta decisão
midi.shareWithFile = Permitir que este arquivo local acesse seus dispositivos MIDI?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Permitir que %S acesse seus dispositivos MIDI?
midi.shareSysexWithFile = Permitir que este arquivo local acesse seus dispositivos MIDI e envie/receba mensagens SysEx?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Permitir que %S acesse seus dispositivos MIDI e envie/receba mensagens SysEx?
serial.allow.label = Permitir
serial.allow.accesskey = P
serial.block.label = Bloquear
serial.block.accesskey = B
serial.shareWithFile = Permitir que este arquivo local acesse suas portas seriais?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Permitir que %S acesse suas portas seriais?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Voltar
storageAccess1.Allow.label = Permitir
storageAccess1.Allow.accesskey = P
storageAccess1.DontAllow.label = Bloquear
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Permitir que %1$S use seus cookies em %2$S?
storageAccess1.hintText = Você pode escolher bloquear o acesso, se não estiver claro o motivo de %1$S precisar desses dados.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Pesquisar “%S” na web
