# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Anicios de sesión guardaos
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Copiar URL
    .accesskey = y
launch-site-url-cmd =
    .label = Visitar URL
    .accesskey = V
copy-username-cmd =
    .label = Copiar nome d'usuariu
    .accesskey = N
edit-username-cmd =
    .label = Editar nome d'usuariu
    .accesskey = d
copy-password-cmd =
    .label = Copiar contraseña
    .accesskey = C
edit-password-cmd =
    .label = Editar contraseña
    .accesskey = E
search-filter =
    .accesskey = G
    .placeholder = Guetar
column-heading-site =
    .label = Sitiu
column-heading-username =
    .label = Nome d'usuariu
column-heading-password =
    .label = Contraseña
column-heading-time-created =
    .label = Usu primeru
column-heading-time-last-used =
    .label = Usu caberu
column-heading-time-password-changed =
    .label = Cambéu caberu
column-heading-times-used =
    .label = Númberos d'usu
remove =
    .label = Desaniciar
    .accesskey = D
import =
    .label = Importar…
    .accesskey = I
close-button =
    .label = Zarrar
    .accesskey = Z
logins-description-all = Guárdense nel ordenador los anicios de sesión pa los sitios de darréu
logins-description-filtered = Los anicios de sesión de darréu concasen cola to gueta:
remove-all =
    .label = Desaniciar too
    .accesskey = T
remove-all-shown =
    .label = Desaniciar tolo amosao
    .accesskey = T
remove-all-passwords-prompt = ¿De xuru que desees desaniciar les contraseñes?
remove-all-passwords-title = Desaniciar toles contraseñes
no-master-password-prompt = ¿De xuru que desees amosar les contraseñes?
