# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = הדף הנוכחי מפנה למיקום חדש. האם ברצונך לשלוח את מידע הטופס שהקלדת למיקום החדש?
# Directory listing strings
DirTitle = מפתח של %1$S‎
DirGoUp = לספרייה ברמה גבוהה יותר
ShowHidden = הצגת אובייקטים נסתרים
DirColName = שם
DirColSize = גודל
DirColMTime = שינוי אחרון
DirFileLabel = קובץ:
UnsafeUriBlocked = המשאב „%1$S“ נחסם על־ידי גלישה בטוחה.
CookieBlockedByPermission = בקשת גישה לעוגייה או אחסון ב־”%1$S” נחסמה עקב הרשאות עוגייה מותאמות אישית.
