# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

print-setup =
    .title = Configuración de página
custom-prompt-prompt = Ingrese su texto personalizado para encabezado/pie
advanced-tab =
    .label = Márgenes y encabezado/pie
format-group-label =
    .value = Formato
orientation-label =
    .value = Orientación:
scale-percent =
    .value = %
options-group-label =
    .value = Opciones
margin-group-label-inches =
    .value = Márgenes (pulgadas)
margin-group-label-metric =
    .value = Márgenes (milímetros)
margin-top-invisible =
    .value = Superior:
margin-bottom-invisible =
    .value = Inferior:
margin-left-invisible =
    .value = Izquierda:
margin-right-invisible =
    .value = Derecha:
header-footer-label =
    .value = Encabezado y pie
hf-left-label =
    .value = Izquierda:
hf-center-label =
    .value = Centro:
hf-right-label =
    .value = Derecha:
header-left-tip =
    .tooltiptext = Encabezado a la izquierda
header-center-tip =
    .tooltiptext = Encabezado centrado
header-right-tip =
    .tooltiptext = Encabezado a la derecha
footer-left-tip =
    .tooltiptext = Pie a la izquierda
footer-center-tip =
    .tooltiptext = Pie centrado
footer-right-tip =
    .tooltiptext = Pie a la derecha
hf-blank =
    .label = --en blanco--
hf-title =
    .label = Título
hf-url =
    .label = URL
hf-date-and-time =
    .label = Fecha/hora
hf-page =
    .label = Página #
hf-page-and-total =
    .label = Página # de #
print-preview-window =
    .title = Vista Previa
print-title =
    .value = Título:
print-preparing =
    .value = Preparando...
print-progress =
    .value = Progreso:
print-window =
    .title = Imprimiendo{ " " }
print-complete =
    .value = La impresión ha finalizado.
# Variables
# $percent (integer) - Number of printed percentage
print-percent =
    .value = { $percent }%
dialog-cancel-label = Cancelar
dialog-close-label = Cerrar{ " " }
