# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = Sta pagina chi a sta pe portate inte 'n neuvo indirisso. T'eu respedî i dæti che t'æ scrito into neuvo indirisso?
# Directory listing strings
DirTitle = Indice de %1$S
DirGoUp = Vanni in sciù fin a-a cartella ciù erta
ShowHidden = Fanni vedde i ògetti ascosi
DirColName = Nomme
DirColSize = Dimenscion
DirColMTime = Cangiou o
DirFileLabel = Schedaio:
UnsafeUriBlocked = A risorsa in “%1$S” a l'é blocâ da-a Navegaçion Segua.
