# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE (RootCertModuleName): string limit is 64 bytes after
# conversion to UTF-8.
# length_limit = 64 bytes
RootCertModuleName = Modili laltu dugg na
# LOCALIZATION NOTE (ManufacturerID): string limit is 32 bytes after conversion
# to UTF-8.
# length_limit = 32 bytes
ManufacturerID = Mozilla.org
# LOCALIZATION NOTE (PrivateTokenDescription): string limit is 32 bytes after
# conversion to UTF-8.
# length_limit = 32 bytes
PrivateTokenDescription = Sa kaarange bopp
# LOCALIZATION NOTE (PrivateSlotDescription): string limit is 64 bytes after
# conversion to UTF-8.
# length_limit = 64 bytes
PrivateSlotDescription = Caabi biir bu PSM
# LOCALIZATION NOTE (Fips140TokenDescription): string limit is 32 bytes after
# conversion to UTF-8.
# length_limit = 32 bytes
Fips140TokenDescription = Ndombo kaarange (FIPS)
# LOCALIZATION NOTE (nick_template): $1s is the common name from a cert (e.g. "Mozilla"), $2s is the CA name (e.g. VeriSign)
nick_template = ID %2$s ci %1$s
CertUnknown = Xameesuko
CertOrgUnknown = (Xameesuko)
