#=This file is in the UTF-8 encoding. It is *not*
#=a Java .properties file and does *not* use \escapes

Welcome_Title=Инсталација на $ProductName$
Welcome_MessageWelcome=Добродојдовте во %s!
Welcome_Message0=Ќе го инсталирате %s.
Welcome_Message1=Строго се препорачува да ги напуштите сите активни Windows програми пред да продолжите со инсталацијата.
Welcome_Message2=Кликнете на „Откажи“ за да ја прекинете инсталацијата и потоа исклучете ги активните програми.  Кликнете на „Напред“ за да продолжите со инсталацијата.
Welcome_Message3=Кликнете на „Напред“ за да продолжите со инсталацијата на %s.

License_Title=Договор за лиценца на софтверот
License_SubTitle=Начини и услови за користење на овој софтвер.
License_Message0=Ве молиме прочитајте го следниов договор за лиценца. Користете ја лентата за лизгање за да го прочитате остатокот од договорот.
License_Accept=Ги приф&аќам условите на договорот
License_Decline=НЕ ги прифаќам услови&те на договорот

Type_Title=Тип на инсталација
Type_SubTitle=Одберете опции за инсталација.
Type_Message0=Одберете го типот на инсталацијата и потоа кликнете „Напред“.

Standard_Short=&Стандарден
Standard_Long=Thunderbird ќе биде инсталиран со вообичаените опции.

Custom_Short=&Сопствен
Custom_Long=Можете да одберете индивидуални опции за инсталација. Препорачливо за напредни корисници.

Select_Title=Одбирање на компоненти
Select_SubTitle=Допопнителни компоненти што го подобруваат $ProductName$.
Select_Message0=Одберете ги дополнителните компоненти за инсталација и кликнете „Напред“.

Path_Title=Папка за инсталација
Path_SubTitle=Местото каде што ќе биде инсталиран $ProductName$.
Path_Message0=$ProductName$ ќе биде инсталиран во следнава папка:

Integration_Title=Поврзување на кратенки
Integration_SubTitle=Креирање на икони за програмата
Integration_Message0=Креирај икони за $ProductShortName$:

Integration_Desktop=На мојата работна површина
Integration_StartMenu=Во мојата папка за програми во старт менито
Integration_QuickLaunch=Во мојата лента за брзо лансирање

SelectFolder_Title=Инсталација на $ProductName$: одберете папка за програмата
SelectFolder_Message0=Инсталацијата ќе додаде икони за програмата во папката за програми.  Можете да внесете ново име за папка или пак да користите некоја од постоечките папки.  Кликнете на „Напред“ за да продолжите.

Advanced_Title=Инсталација на $ProductName$: напредни поставки
Advanced_Message0=Ако Вашата Интернет врска бара сервер посредник, внесете информации за Вашиот сервер и порта. Ако Вашата Интернет врска не бара сервер посредник, оставете ги полињата празни.

Install_Title=Резиме
Install_SubTitle=Се е подготвено за инсталација на $ProductName$.
Install_MessageInstall=Програмата за инсталирање ќе ги инсталира следниве компоненти:
Install_MessageDownload=Програмата за инсталирање ќе ги преземе и инсталира следниве компоненти:
Install_Message0=кликнете „Напред“ за да продолжите.

Downloading_Title=Преземање
Downloading_SubTitle=Ги преземам потребните компоненти…
Downloading_Blurb=Програмата за инсталирање ги презема датотеките потребни за инсталација на $ProductName$.
Downloading_FileName=Сега се презема:
Downloading_Time=Преостанато време:

Installing_Title=Инсталација
Installing_SubTitle=Инсталирање на $ProductName$…
Installing_Blurb=Програмата за инсталирање ги инсталира датотеките на програмата.
Installing_Status=Припремам датотека:
Installing_Component=Сега се инсталира:

Success_Title=Инсталацијата е завршена
Success_Header=Инсталацијата е завршена
Success_Message0=%s беше успешно инсталиран.
Success_Message1=Кликнете на „Заврши“ за да завршите со инсталацијата.
Success_Launch=Веднаш стартувај го %s.

Check_Message=Преземањето на $ProductName$ заврши успешно. $ProductNameInternal$ мора да биде затворен за да продолжите со инсталацијата. Кликнете на „Во ред“ за автоматски да излезете од $ProductNameInternal$ и да почнете со инсталацијата.
Check_FullMessage=$ProductNameInternal$ мора да биде затворен за да продолжите со инсталацијата. Кликнете на „Во ред“ за автоматски да излезете од $ProductNameInternal$ и да почнете со инсталацијата.
Check_Wait=$ProductNameInternal$ се исклучува.  Причекајте…

Component_XPCOM=Меѓу-платформски COM
Component_Mail=$ProductName$
Component_Offline=Локална поддршка
Component_Offline_Long=Додава локална поддршка на $ProductName$ Mail.
Component_RSS=RSS поддршка
Component_RSS_Long=Додава RSS поддршка на $ProductName$.
Component_QFA=Агент за контрола на квалитетот
Component_QFA_Long=Служи за пријавување на информации за уривање на $ProductName$
