# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

e2e-intro-description = Aby skoděrowane abo digitalnje signěrowane powěsći pósłał, musyśo koděrowańsku technologiju konfigurěrowaś, pak OpenPGP pak S/MIME.
openpgp-key-user-id-label = Konto / Wužywaŕski ID
openpgp-keygen-title-label =
    .title = OpenPGP-kluc napóraś
openpgp-cancel-key =
    .label = Pśetergnuś
    .tooltiptext = Napóranje kluca pśetergnuś
openpgp-key-gen-days-label =
    .label = dnjow
openpgp-key-gen-months-label =
    .label = mjasecow
openpgp-key-gen-years-label =
    .label = lět
openpgp-key-gen-no-expiry-label =
    .label = Kluc njespadnjo
openpgp-key-gen-key-size-label = Wjelikosć kluca
openpgp-key-gen-console-label = Naporanje kluca
openpgp-key-gen-key-type-label = Klucowy typ
openpgp-key-gen-key-type-rsa =
    .label = RSA
openpgp-key-gen-key-type-ecc =
    .label = ECC (Elliptic Curve)
openpgp-generate-key =
    .label = Kluč wutworić
    .tooltiptext = Napórajo nowy góźecy se OPenPGP-kluc za koděrowanjee a/abo signěrowanje
openpgp-advanced-prefs-button-label =
    .label = Rozšyrjony…
openpgp-key-id-label =
    .label = ID kluca
openpgp-key-man-generate =
    .label = Nowy klucowy por
    .accesskey = k
openpgp-key-man-file-menu =
    .label = Dataja
    .accesskey = D
openpgp-key-man-edit-menu =
    .label = Wobźěłaś
    .accesskey = b
openpgp-key-man-view-menu =
    .label = Naglěd
    .accesskey = N
openpgp-key-man-generate-menu =
    .label = Napóraś
    .accesskey = N
openpgp-key-man-discover-progress = Pyta se…
openpgp-key-copy-key =
    .label = Zjawny kluc kopěrowaś
    .accesskey = Z
openpgp-key-export-key =
    .label = Zjawny kluc do dataje eksportěrowaś
    .accesskey = d
openpgp-key-man-copy-to-clipbrd =
    .label = Zjawne kluce do mjazywótkłada kopěrowaś
    .accesskey = Z
openpgp-key-man-ctx-expor-to-file-label =
    .label = Kluce do dataje eksportěrowaś
openpgp-key-man-ctx-copy-to-clipbrd-label =
    .label = Zjawne kluce do mjazywótkłada kopěrowaś
openpgp-key-man-close =
    .label = Zacyniś
openpgp-key-man-del-key =
    .label = Kluce wulašowaś
    .accesskey = l
openpgp-delete-key =
    .label = Kluc wulašowaś
    .accesskey = l
openpgp-key-man-revoke-key =
    .label = Kluc wótwołaś
    .accesskey = t
openpgp-key-man-key-props =
    .label = Klucowe kakosći
    .accesskey = K
openpgp-key-man-key-more =
    .label = Wěcej
    .accesskey = W
openpgp-key-man-view-photo =
    .label = ID fota
    .accesskey = f
openpgp-key-man-ctx-view-photo-label =
    .label = ID fota pokazaś
openpgp-key-man-show-invalid-keys =
    .label = Njepłaśiwe kluce zwobrazniś
    .accesskey = N
openpgp-key-man-user-id-label =
    .label = Mě
openpgp-key-man-fingerprint-label =
    .label = Palcowy wótśišć
openpgp-key-man-select-all =
    .label = Wšykne kluce wubraś
    .accesskey = y
openpgp-key-man-filter-label =
    .placeholder = Za klucami pytaś
openpgp-key-man-select-all-key =
    .key = A
openpgp-key-man-key-details-key =
    .key = I
openpgp-key-details-title =
    .title = Klucowe kakosći
openpgp-key-details-structure-tab =
    .label = Struktura
openpgp-key-details-id-label =
    .label = ID
openpgp-key-details-key-type-label = Typ
openpgp-key-details-key-part-label =
    .label = Klucowy źěl
openpgp-key-details-algorithm-label =
    .label = Algoritmus
openpgp-key-details-size-label =
    .label = Wjelikosć
openpgp-key-details-created-label =
    .label = Napórany
openpgp-key-details-created-header = Napórany
openpgp-key-details-usage-label =
    .label = Wužywanje
openpgp-key-details-fingerprint-label = Palcowy wótśišć
openpgp-key-details-sel-action =
    .label = Akciju wubraś…
    .accesskey = b
openpgp-card-details-close-window-label =
    .buttonlabelaccept = Zacyniś
openpgp-acceptance-rejected-label =
    .label = Ně, toś ten kluc wótpokazaś.
openpgp-acceptance-undecided-label =
    .label = Hyšći nic, snaź pózdźej.
openpgp-copy-cmd-label =
    .label = Kopěrowaś

## e2e encryption settings

openpgp-add-key-button =
    .label = Kluc pśidaś…
    .accesskey = K
e2e-learn-more = Dalšne informacije

## OpenPGP Key selection area

openpgp-radio-none =
    .label = Žeden
openpgp-key-expand-section =
    .tooltiptext = Dalšne informacije

## Account settings export output

