# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Cercante { $host }…
network-connection-status-connected = Connectite a { $host }…
network-connection-status-sending-request = Invio de requesta a { $host }…
network-connection-status-transferring-data = Transferente datos ab { $host }…
network-connection-status-connecting = Connexion a { $host }…
network-connection-status-wrote = Scripte { $host }
network-connection-status-waiting = Attendente { $host }…
network-connection-status-looked-up = Recerca de { $host }…
network-connection-status-tls-handshake = Negotiante le connexion TLS con { $host }…
network-connection-status-tls-handshake-finished = Le negotiation de connexion TLS con { $host } finiva…
