# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-sending-request = Invio de requesta a { $host }…
network-connection-status-connecting = Connexion a { $host }…
network-connection-status-wrote = Scripte { $host }
network-connection-status-waiting = Attendente { $host }…
network-connection-status-looked-up = Recerca de { $host }…
