# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Mencari { $host }…
network-connection-status-connected = Disambung ke { $host }…
network-connection-status-sending-request = Menghantar permohonan ke { $host }…
network-connection-status-transferring-data = Memindahkan data daripada { $host }…
network-connection-status-connecting = Menyambung ke { $host }…
network-connection-status-read = Baca { $host }
network-connection-status-wrote = Ditulis { $host }
network-connection-status-waiting = Menunggu { $host }…
network-connection-status-looked-up = Mencari { $host }…
network-connection-status-tls-handshake = Melaksanakan jabat tangan TLS ke { $host }…
network-connection-status-tls-handshake-finished = Jabat tangan TLS siap untuk { $host }…
