# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = यह वेब पृष्ठ नये स्थान में फिर प्रेषित किया जा रहा है. क्या आप फॉर्म आंकड़ा को फिर भेजना चाहते हैं जिसे आपने नये स्थान में फिर टाइप किया है?
# Directory listing strings
DirTitle = Index of %1$S
DirGoUp = उच्चतर स्तर निर्देशिका तक
ShowHidden = छिपी वस्तु दिखाएँ
DirColName = नाम
DirColSize = आकार
DirColMTime = अंतिम रूपांतरित
DirFileLabel = फाइल:\u0020
UnsafeUriBlocked = “%1$S” पर संसाधन सुरक्षित ब्राउज़िंग द्वारा अवरोधित किया गया था.
