# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Tiempo excediu
openFile = Ubrir fichero
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Mirar "%2$S" en %1$S
contextMenuSearch.accesskey = S
contextMenuPrivateSearch = Mirar en una finestra privada
contextMenuPrivateSearch.accesskey = M
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Mirar con %S en una finestra privada
contextMenuPrivateSearchOtherEngine.accesskey = M
bookmarkAllTabsDefault = [Nombre d'a carpeta]
unsignedAddonsDisabled.message = Uno u mas complementos instalaus no se pueden verificar y s'han desactivau.
unsignedAddonsDisabled.learnMore.label = Saber-ne mas
unsignedAddonsDisabled.learnMore.accesskey = S
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Zaguer acceso %S
crashedpluginsMessage.title = O plugin %S ha fallau.
crashedpluginsMessage.reloadButton.label = Recargar a imachen
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = Ninviar un reporte de fallo
crashedpluginsMessage.submitButton.accesskey = N
crashedpluginsMessage.learnMore = Saber-ne mas…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = No querría ir ta %S?
keywordURIFixup.goTo = Sí, leva me enta %S
keywordURIFixup.goTo.accesskey = S
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Esviellar a la versión %S
update.downloadAndInstallButton.accesskey = a
menuOpenAllInTabs.label = Ubrir tot en pestanyas
tabHistory.goBack = Tornar ta ista pachina
tabHistory.goForward = Abanzar a ista pachina
# URL Bar
pasteAndGo.label = Apegar-lo y ir-ie
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Recargar la pachina actual (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Deixar de cargar ista pachina (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Reiniciar lo nivel de zoom (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Cambiar la vista de lectura (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Amostrar os suyos marcapachinas (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Amostrar o progreso d'as descargas en curso (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Ubrir una finestra nueva (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Ubrir una nueva etiqueta (%S)
newTabContainer.tooltip = Ubrir una nueva pestanya (%S)\nPreta y mantiene pa ubrir una nueva pestanya contenedera
newTabAlwaysContainer.tooltip = Triar un contenedor pa ubirr una nuevas pestanya
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Verificau por: %S
identity.identified.verified_by_you = Ha adhibiu una excepción de seguranza ta iste puesto.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Certificau emitiu a: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Inseguro
identity.notSecure.tooltip = La connexión no ye segura
identity.extension.label = Extensión (%S)
identity.extension.tooltip = Cargau per la extensión: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Achiquir (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Reiniciar lo nivel de zoom (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Agrandir (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Retallar (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Copiar (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Apegar (%S)
geolocation.remember = Recordar ista decisión
xr.remember = Recordar esta decisión
# Persistent storage UI
persistentStorage.allow = Permitir
persistentStorage.allow.accesskey = A
webNotifications.notNow = No pas agora
webNotifications.notNow.accesskey = n
webNotifications.never = No permitir nunca
webNotifications.never.accesskey = v
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Saca-me d'aquí!
safebrowsing.getMeOutOfHereButton.accessKey = S
safebrowsing.deceptiveSite = Iste puesto puet estar malicioso!
safebrowsing.notADeceptiveSiteButton.label = Iste no ye un puesto malicioso…
safebrowsing.notADeceptiveSiteButton.accessKey = m
safebrowsing.reportedAttackSite = S'ha informau que iste ye un puesto web atacant!
safebrowsing.notAnAttackButton.label = Isto no ye un puesto atacant…
safebrowsing.notAnAttackButton.accessKey = a
safebrowsing.reportedUnwantedSite = Puesto denunciau como de Softwar no deseyau!
safebrowsing.reportedHarmfulSite = Puesto reportau como perchudicial!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Mirar %S
processHang.add-on.learn-more.text = Saber-ne mas
processHang.button_debug.label = Depurar o script
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Amostrar a finestra en pantalla completa (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Mover la barra lateral enta la zurda
sidebar.moveToRight = Mover la barra lateral enta la Dreita
emeNotifications.drmContentDisabled.button.label = Activar DRM
emeNotifications.drmContentDisabled.button.accesskey = A
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S ye instalando components necesarias ta reproducir l'audio u o video d'ista pachina. Intente-lo dimpués.\u0020
emeNotifications.unknownDRMSoftware = Desconoixiu
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Personalizar lo %S
decoder.noCodecs.button = Aprenda cómo
decoder.noCodecs.accesskey = L
decoder.noCodecsLinux.message = Pa reproducir video, talment le calga instalar los codecs de video requiestos.
decoder.noHWAcceleration.message = Pa amillorar la qualidat de video, talment le calga instalar lo Microsoft’s Media Feature Pack.
decoder.noPulseAudio.message = Pa reproducir audio, talment le calga instalar el programa PuleAudio necesario.
decoder.unsupportedLibavcodec.message = libavcodec puet estar vulnerable u no ye soportau, y habría d'actualizar-se a play video.
decoder.decodeError.message = Ha ocurriu una error entre que descodificaba un recurso multimedia.
decoder.decodeError.button = Reportar un problema con o puesto
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = Una error recuperabla ha ocurriu entre que se descodificaba un recuso multimedia.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Ha d'iniciar la sesión en iste ret antes que no pueda acceder a Internet.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Ubrir la pachina d'Inicio de ret
permissions.remove.tooltip = Borrar iste permiso y tornar a preguntar
permissions.fullscreen.promptCanceled = Demandas de permiso en espera canceladas: las demandas de permiso no se pueden emitir antes de dentrar en modo DOM pantalla completa.
permissions.fullscreen.fullScreenCanceled = S'ha saliu de DOM pantalla completa: las demandas de permiso no se pueden emitir mientras se ye en modo DOM pantalla completa.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64 bits
aboutDialog.architecture.thirtyTwoBit = 32 bits
midi.remember = Acordar-se d'esta decisión
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Enta zaga
