# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Vyhľadáva sa adresa { $host }…
network-connection-status-connected = Pripojené k { $host }…
network-connection-status-sending-request = Odosiela sa požiadavka na { $host }…
network-connection-status-transferring-data = Prenášajú sa údaje z { $host }…
network-connection-status-connecting = Pripája sa k { $host }…
network-connection-status-waiting = Čaká sa na { $host }…
network-connection-status-looked-up = Vyhľadaná adresa { $host }…
network-connection-status-tls-handshake = Nadväzovanie TLS spojenia s { $host }…
network-connection-status-tls-handshake-finished = TLS spojenie s { $host } bolo nadviazané…
