# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loginsDescriptionAll2 = ഈ സൈറ്റുകളിലേയ്ക്കുള്ല പ്രവേശനം നിങ്ങളുടെ കമ്പ്യുട്ടറില്‍ സൂക്ഷിച്ചിട്ടുണ്ട്
# LOCALIZATION NOTE (useASecurelyGeneratedPassword):
# Shown in the autocomplete popup to allow filling a generated password into a password field.
useASecurelyGeneratedPassword = സുരക്ഷിതായി ഉണ്ടാക്കിയ ഒളിവാക്കു് ഉപയോഗിക്കുക
# LOCALIZATION NOTE (generatedPasswordWillBeSaved):
# %S will contain the brandShorterName. This informs the user that the generated password will be automatically saved.
generatedPasswordWillBeSaved = ഈ വെബിടത്തിനുള്ള ഒളിവാക്കു് %S കരുതിവയ്ക്കും.
# LOCALIZATION NOTE (loginHostAge):
# This is used to show the context menu login items with their age.
# 1st string is the username for the login, 2nd is the login's age.
loginHostAge = %1$S (%2$S)
# LOCALIZATION NOTE (noUsername):
# String is used on the context menu when a login doesn't have a username.
noUsername = ഉപയോക്തൃനാമമില്ല
# LOCALIZATION NOTE (displaySameOrigin):
# String is used on the autocomplete row when the login origin is a domain match with the document origin
displaySameOrigin = ഈ വെബിടത്തിൽ നിന്നു്
# LOCALIZATION NOTE (insecureFieldWarningDescription2):
# %1$S will contain insecureFieldWarningLearnMore and look like a link to indicate that clicking will open a tab with support information.
insecureFieldWarningDescription2 = ഈ ബന്ധം സുരക്ഷിതമല്ല. ഇവിടെ നല്‍കിയ പ്രവേശനങ്ങള്‍ പുറത്ത് പോയിട്ടുണ്ടാവാം. %1$S
insecureFieldWarningLearnMore = കൂടുതല്‍ അറിയുക
# LOCALIZATION NOTE (managePasswords.label):
# This label is used in the footer of login autocomplete menus.
managePasswords.label = ഒളിവാക്കുകൾ കൈകാര്യം ചെയ്യുക
