# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Buscando { $host }…
network-connection-status-connected = Conectéstite a { $host }…
network-connection-status-sending-request = Unviando la solicitú a { $host }…
network-connection-status-transferring-data = Tresfiriendo datos de { $host }…
network-connection-status-connecting = Conectando a { $host }…
network-connection-status-read = Lleóse { $host }
network-connection-status-wrote = Escribióse { $host }
network-connection-status-waiting = Esperando a { $host }…
network-connection-status-looked-up = Buscóse { $host }…
