# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = "%S"ga quyidagi maqsadlarda ishonishni xohlaysizmi?
unnamedCA = Sertifikatni tasdiqdan oʻtkazish (nomlanmagan)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Ushbu sertifikat zahirasini kodlash uchun foydalanilgan parolni kiriting.
# Page Info
pageInfo_NoEncryption = Ulanish kodlanmagan
pageInfo_Privacy_None1 = Siz ko‘rayotgan sahifa uchun kodlashni %S sayti qo‘llab-quvvatlamaydi.
pageInfo_Privacy_None2 = Internet orqali jo‘natilgan kodlanmagan ma’lumotlarni u o‘tkazilayotganda boshqa odamlar ko‘rishi mumkin.
pageInfo_Privacy_None4 = Siz ko‘rayotgan sahifa internetga uzatilishidan oldin kodlanmagan.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Ulanish kodlangan (%1$S, %2$S bit kalitlar, %3$S)
pageInfo_BrokenEncryption = Buzilgan kodlash (%1$S, %2$S bit kalitlar, %3$S)
pageInfo_Privacy_Encrypted1 = Siz ko‘rayotgan sahifa internetga uzatilishidan oldin kodlangan.
pageInfo_Privacy_Encrypted2 = Ma’lumotlarni kompyuterlararo uzatilayotganda kodlash begona odamlar ularni ko‘rishini qiyinlashtiradi. Shuning uchun ma’lumotlar tarmoqda uzatilayotganda ularni o‘qish holati deyarli uchramaydi.
pageInfo_MixedContent = Ulanish qisman kodlangan
pageInfo_MixedContent2 = Siz ko‘rayotgan sahifa qismlari internetga qo‘yilishdan oldin kodlanmagan.
pageInfo_WeakCipher = Bu saytga ulanish kuchsiz shifrlashdandan foydalanmoqda. Bu esa maxfiy emas. Boshqalar ma’lumotlaringizni ko‘rish yoki saytning xususiyatlarini o‘zgartirisi mumkin.
# Token Manager
password_not_set = (o‘rnatilmagan)
