# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = Bu səhifə başqa bir ünvana yönləndirilir. Yazdığınız form məlumatını yeni ünvana da göndərmək istəyirsiniz?
# Directory listing strings
DirTitle = %1$S qovluğunu
DirGoUp = Yüksək səviyyədəki qovluğa keç
ShowHidden = Gizli elementləri göstər
DirColName = Ad
DirColSize = Həcmi
DirColMTime = Son Dəyişiklik
DirFileLabel = Fayl:\u0020
UnsafeUriBlocked = “%1$S” vəsaiti Təhlükəsiz Səyahət tərəfindən əngəllənib.
CookieBlockedByPermission = Fərdi çərəz icazələrinə əsasən “%1$S” ünvanının çərəz və anbar istəyi əngəlləndi.
CookieBlockedAll = Bütün anbar istəklərini əngəllədiyimiz üçün “%1$S” ünvanının çərəz və anbar istəyi əngəlləndi.
