# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Varmentajaan %S luotetaan seuraavissa toimissa:
unnamedCA = Varmentaja (nimeämättä)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Kirjoita salasana, jota käytettiin varmenteiden varmuuskopion salaukseen:
# Page Info
pageInfo_NoEncryption = Yhteys ei ole salattu
pageInfo_Privacy_None1 = Palvelin %S ei käytä salausta tällä sivulla.
pageInfo_Privacy_None2 = Sivulliset voivat lukea verkossa salaamatta siirrettyjä tietoja.
pageInfo_Privacy_None4 = Tarkastelemaasi sivua ei salattu ennen kuin se lähetettiin Internetin kautta.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Yhteys salattu (%1$S, %2$S-bittinen avain, %3$S)
pageInfo_BrokenEncryption = Rikkinäinen salaus (%1$S, %2$S-bittinen avain, %3$S)
pageInfo_Privacy_Encrypted1 = Tämä sivu salattiin ennen sen siirtoa.
pageInfo_Privacy_Encrypted2 = Salauksen vuoksi asiattomien on hyvin vaikea tarkastella tietokoneiden välillä siirtyvää tietoa. Siksi on epätodennäköistä, että kukaan luki tätä sivua sen siirtyessä verkon yli.
pageInfo_MixedContent = Yhteys osittain salattu
pageInfo_MixedContent2 = Osia avatusta sivusta ei salattu ennen sen siirtoa.
pageInfo_WeakCipher = Yhteytesi verkkosivustoon käyttää heikkoa salausta eikä sen takia ole yksityinen. Sivullisten on mahdollista tarkastella antamiasi tietoja tai vaikuttaa sivuston toimintaan.
pageInfo_CertificateTransparency_Compliant = Tämä sivusto noudattaa varmenteiden avoimuuden (certificate transparency) käytäntöä.
# Token Manager
password_not_set = (ei ole asetettu)
