# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Variables:
# $hostname (String) - Hostname of the website with SSL error.
# $errorMessage (String) - Error message corresponding to the type of error we are experiencing.
ssl-connection-error = Un error occurreva durante un connexion a { $hostname }. { $errorMessage }
# Variables:
# $error (string) - NSS error code string that specifies type of cert error. e.g. unknown issuer, invalid cert, etc.
cert-error-code-prefix = Codice de error: { $error }
ssl-error-no-certificate = Incapace a trovar le certificato o le clave necessari pro le authentication.
ssl-error-bad-certificate = Incapace a communicar in maniera secur con le par: le certificato del par esseva rejectate.
ssl-error-bad-client = Le servitor incontrava mal datos ex le cliente.
ssl-error-bad-server = Le cliente incontrava mal datos ex le servitor.
ssl-error-unsupported-certificate-type = Typo de certificato non admittite.
ssl-error-unsupported-version = Le par usa un version non supportate del protocollo de securitate.
ssl-error-wrong-certificate = Authentication de cliente fallite: le clave private in le base de datos del claves non concorda con le clave public in le base de datos del certificato.
ssl-error-bad-cert-domain = Incapace a communicar con securitate con le par: le nomine de dominio requirite non corresponde al certificato del servitor.
ssl-error-post-warning = Codice de error SSL incognite.
ssl-error-ssl2-disabled = Le par supporta solo le version 2 de SSL, que es disactivate.
ssl-error-bad-mac-read = SSL recipeva un registration con un codice de authentication de message incorrecte.
ssl-error-bad-mac-alert = Le par SSL reporta un codice de authentication de message incorrecte.
ssl-error-bad-cert-alert = Le par SSL non pote verificar tu certificate.
ssl-error-revoked-cert-alert = Le par SSL rejectava tu certificato como revocate.
ssl-error-expired-cert-alert = Le par SSL rejectava tu certificato como expirate.
ssl-error-ssl-disabled = Impossibile connecter se: SSL disativate.
ssl-error-fortezza-pqg = Impossibile connecter: le par SSL es in un altere dominio de FORTEZZA.
ssl-error-rx-malformed-change-cipher = SSL recipeva un registration de Change Cipher Spec malformate.
ssl-error-rx-malformed-alert = SSL recipeva un registration de aviso malformate.
ssl-error-rx-malformed-application-data = SSL recipeva un registration de datos de application malformate.
ssl-error-rx-unknown-record-type = SSL recipeva un registration con un typo de contento incognite.
ssl-error-rx-unknown-alert = SSL recipeva un registration de alerta con un description del alerta incognite.
ssl-error-close-notify-alert = Le par SSL claudeva iste connexion.
ssl-error-decompression-failure-alert = Le par SSL era incapace a decomprimer con successo un registration SSL recipite.
ssl-error-unsupported-cert-alert = Le par SSL non gere certificatos del typo que illo recipeva.
ssl-error-certificate-unknown-alert = Le par SSL habeva alcun problema non specificate con le certificato que illo recipeva.
ssl-error-generate-random-failure = SSL incontrava un falta de su generator de numeros aleatori.
ssl-error-sign-hashes-failure = Incapace a signar digitalmente le datos requirite pro verificar tu certificato.
ssl-error-extract-public-key-failure = SSL era incapace a extraher le clave public ex le certificato de par.
ssl-error-mac-computation-failure = Computation MAC fallite.
ssl-error-iv-param-failure = Le codice PKCS11 falleva a traducer un IV in un parametro.
ssl-error-session-key-gen-failure = Le cliente falleva a crear le clave de session pro le session SSL.
ssl-error-no-server-key-for-alg = Le servitor ha nulle claves pro le tentativa del algoritmo de cambio del clave.
ssl-error-no-compression-overlap = Incapace a communicar in maniera secur con le par: nulle algorithmos de compression in commun.
ssl-error-decryption-failed-alert = Le par esseva incapace a decryptar un registration SSL que illo recipeva.
ssl-error-record-overflow-alert = Le par recipeva un registration SSL que esseva plus longe que permittite.
ssl-error-unknown-ca-alert = Le par non recognosce, ni confide in le CA que emitteva tu certificato.
ssl-error-access-denied-alert = Le par recipeva un certificato valide, ma le accesso era negate.
ssl-error-protocol-version-alert = Le par reporta un version de protocollo incompatibile o non supportate.
ssl-error-internal-error-alert = Le par reporta que a illo occurreva un error interne.
ssl-error-no-renegotiation-alert = Le par non permitte le renegotiation del parametros de securitate SSL.
ssl-error-server-cache-not-configured = Cache del servitor SSL non configurate e non disactivate pro iste interfacie de connexion.
ssl-error-unsupported-extension-alert = Le par SSL non supporta le extension hello TLS requirite.
ssl-error-certificate-unobtainable-alert = Le par SSL non pote obtener tu certificato ex le URL supplite.
ssl-error-unrecognized-name-alert = Le par SSL ha nulle certificato pro le nomine de DNS requirite.
ssl-error-bad-cert-status-response-alert = Le par SSL non poteva obtener un responsa OCSP pro su certificato.
ssl-error-bad-cert-hash-value-alert = Le par SSL reportava un valor errate del hash del certificato.
ssl-error-decompression-failure = SSL recipeva un registration comprimite que non pote ser decomprimite.
ssl-error-renegotiation-not-allowed = Le renegotiation non es permittite sur iste interfacie de connexion SSL.
ssl-error-next-protocol-data-invalid = SSL recipeva datos de extension NPN non valide.
ssl-error-feature-not-supported-for-ssl2 = Functionalitate SSL non gerite pro connexiones SSL 2.0.
ssl-error-feature-not-supported-for-servers = Functionalitate SSL non gerite pro le servitores.
ssl-error-feature-not-supported-for-clients = Functionalitate SSL non gerite pro le clientes.
ssl-error-invalid-version-range = Le campo del version SSL non es valide.
ssl-error-feature-not-supported-for-version = Functionalitate SSL non gerite pro le version del protocollo.
ssl-error-unsupported-hash-algorithm = Algorithmo de hash non supportate, usate per le par TLS.
ssl-error-incorrect-signature-algorithm = Algorithmo de signatura incorrecte specificate in un elemento signate digitalmente.
ssl-error-weak-server-cert-key = Le certificato del servitor includeva un clave public que era trop debile.
ssl-error-no-supported-signature-algorithm = Nulle algorithmo de signatura TLS supportate era configurate.
ssl-error-unsupported-signature-algorithm = Le par usava un combination non supportate de signatura e de algorithmo de hash.
sec-error-io = Un error de I/O occurreva durante le autorisation de securitate.
sec-error-library-failure = falta de bibliotheca de securitate.
sec-error-bad-data = bibliotheca de securitate: recipite mal datos.
sec-error-output-len = bibliotheca de securitate: error de longor de emission.
sec-error-input-len = bibliotheca de securitate: error de longor de immission.
sec-error-invalid-args = bibliotheca de securitate: argumentos non valide.
sec-error-invalid-algorithm = bibliotheca de securitate: algorithmo non valide.
sec-error-invalid-ava = bibliotheca de securitate: AVA non valide.
sec-error-bad-der = bibliotheca de securitate: message codificate per DER, formatate impropriemente.
sec-error-bad-signature = Le certificato del par ha un signatura non valide.
sec-error-expired-certificate = Le certificato del par es expirate.
sec-error-revoked-certificate = Le certificato del par ha essite revocate.
sec-error-unknown-issuer = Le certificato del par non es recognite.
sec-error-bad-key = Le clave public del par non es valide.
sec-error-bad-password = Le contrasigno de securitate inserite es incorrecte.
sec-error-bad-database = bibliotheca de securitate: mal base de datos.
sec-error-no-memory = bibliotheca de securitate: error de allocation de memoria.
sec-error-duplicate-cert = Le certificate existe jam in tu base de datos.
sec-error-duplicate-cert-name = Nomine del certificato discargate duplicate, uno jam in tu base de datos.
sec-error-adding-cert = Error a adder le certificato al base de datos.
sec-error-no-key = Le clave private pro iste certificato non pote ser trovate in le base de datos
sec-error-cert-valid = Iste certificato es valide.
sec-error-cert-not-valid = Iste certificato es invalide.
sec-error-cert-no-response = Bibliotheca de certificato: nulle responsa
sec-error-crl-bad-signature = Le CRL pro le emittitor del certificato ha un signatura non valide.
sec-error-crl-invalid = Le nove CRL ha un formato non valide.
sec-error-extension-value-invalid = Le valor de extension del certificato non es valide.
sec-error-extension-not-found = Extension del certificato non trovate.
sec-error-ca-cert-invalid = Le certificato del emittitor non es valide.
sec-internal-only = **modulo SOLMENTE interne**
sec-error-invalid-key = Le clave non gere le operation requirite.
sec-error-unknown-critical-extension = Le certificato contine un extension critic incognite.
sec-error-old-crl = Le nove CRL non es plus recente de illo actual.
sec-error-unsupported-keyalg = Algorithmo del clave non supportate o incognite.
xp-sec-fortezza-no-card = Nulle cartas de Fortezza trovate
xp-sec-fortezza-none-selected = Nulle carta de Fortezza seligite
xp-sec-fortezza-more-info = Por favor elige un personalitate pro obtener informationes re illo
xp-sec-fortezza-person-not-found = Personality non trovate
xp-sec-fortezza-no-more-info = Nulle altere informationes re ille Personalitate
xp-sec-fortezza-bad-pin = Pin invalide
xp-sec-fortezza-person-error = Impossibile initialisar le personalitates de Fortezza.
sec-error-no-krl = Nulle KRL pro iste certificato de sito trovate.
sec-error-krl-expired = Le KRL pro iste certificato de sito ha expirate.
sec-error-krl-bad-signature = Le KRL pro iste certificato de sito ha un signatura non valide.
sec-error-revoked-key = Le clave pro iste certificato de sito ha essite revocate.
sec-error-krl-invalid = Le nove KRL ha un formato non valide.
sec-error-no-token = Carta de securitate o token inexistente, a initialisar o removite.
sec-error-read-only = bibliotheca de securitate: base de datos solo a leger.
sec-error-no-slot-selected = Nulle slot o token era seligite.
sec-error-cert-nickname-collision = Un certificato con le mesme supernomine jam existe.
sec-error-key-nickname-collision = Un clave con le mesme supernomine jam existe.
sec-error-bad-export-algorithm = Le algorithmo requirite non es consentite.
sec-error-pkcs12-decoding-pfx = Incapace a importar. Error de decodification. File non valide.
sec-error-pkcs12-invalid-mac = Incapace a importar. MAC non valide. Contrasigno incorrecte o file corrupte.
sec-error-pkcs12-unsupported-mac-algorithm = Incapace a importar. Algorithmo MAC non gerite.
sec-error-pkcs12-unsupported-transport-mode = Incapace a importar. Solo le integritate del contrasigno e le modos de confidentialitate es gerite.
sec-error-pkcs12-corrupt-pfx-structure = Incapace a importar. Le structura del file es corrupte.
sec-error-pkcs12-unsupported-version = Incapace a importar. Version de file non gerite.
sec-error-pkcs12-privacy-password-incorrect = Incapace a importar. Contrasigno de confidentialitate incorrecte.
sec-error-pkcs12-cert-collision = Incapace a importar. Le mesme supernomine jam existe in le base de datos.
sec-error-user-cancelled = Le usator pulsava Cancel.
sec-error-pkcs12-duplicate-data = Non importate, jam in le base de datos.
sec-error-message-send-aborted = Message non inviate.
sec-error-inadequate-key-usage = Le uso del clave de certificato non es adequate al operation tentate.
sec-error-inadequate-cert-type = Typo de certificato non approbate pro le application.
sec-error-pkcs12-unable-to-import-key = Incapace a importar. Error in le tentativa de importar le clave private.
sec-error-pkcs12-importing-cert-chain = Incapace a importar. Error in le tentativa de importar le catena de certificatos.
sec-error-pkcs12-key-database-not-initialized = Incapace a exportar. Base de datos de clave corrumpite o cancellate.
sec-error-invalid-password = Le contrasigno inserite non es valide. Tenta con uno differente.
sec-error-js-invalid-module-name = Nomine de modulo invalide.
sec-error-js-add-mod-failure = Incapace a adder modulo
sec-error-js-del-mod-failure = Incapace a deler modulo
sec-error-old-krl = Le nove KRL non es plus recente de illo actual.
sec-error-unknown-cert = Le certificato requirite es introvabile.
sec-error-unknown-signer = Le certificato del signator es introvabile.
sec-error-cert-bad-access-location = Le position pro le servitor de stato del certificato ha un formato non valide.
sec-error-ocsp-unknown-response-type = Le responsa OCSP non pote ser decodificate totalmente; illo es de un typo incognite.
sec-error-ocsp-bad-http-response = Le servitor OCSP retornava datos HTTP inexpectate/invalide.
sec-error-ocsp-server-error = Le servitor OCSP suffreva de un error interne.
sec-error-ocsp-try-server-later = Le servitor OCSP suggere de reprobar plus tarde.
sec-error-ocsp-request-needs-sig = Le servitor OCSP require un signatura sur iste requesta.
sec-error-ocsp-unauthorized-request = Le servitor OCSP refusava iste requesta como non autorisate.
sec-error-ocsp-unknown-response-status = Le servitor OCSP retornava un stato irrecognoscibile.
sec-error-ocsp-unknown-cert = Le servitor OCSP ha nulle stato pro le certificato.
sec-error-ocsp-not-enabled = Tu debe activar OCSP ante que exequer iste operation.
sec-error-ocsp-malformed-response = Le responsa ex le servitor OCSP era corrupte o mal formate.
sec-error-ocsp-unauthorized-response = Le signator del responsa OCSP non es autorisate a dar le stato pro iste certificato.
sec-error-ocsp-future-response = Le responsa del OCSP non es ancora valide (contine un data in le futur).
sec-error-ocsp-old-response = Le responsa del OCSP contine un information obsolete.
sec-error-digest-not-found = Le sumpto de CMS o PKCS #7 non era trovate in un message signate.
sec-error-unsupported-message-type = Le typo de message CMS o PKCS #7 non es gerite.
sec-error-module-stuck = Impossibile remover le modulo PKCS #11 perque illo es ancora in uso.
sec-error-bad-template = Impossibile decodificar le datos ASN.1. Le modello specificate non era valide.
sec-error-crl-not-found = Nulle CRL concordante trovate.
sec-error-busy = NSS non pote arrestar se. Objectos es ancora in uso.
sec-error-extra-input = Message codificate-DER contineva datos extra non usate.
sec-error-unsupported-elliptic-curve = Curva elliptic non gerite.
sec-error-unsupported-ec-point-form = Forma de puncto de curva elliptic non gerite.
sec-error-unrecognized-oid = Identificator de objecto incognite.
sec-error-ocsp-invalid-signing-cert = Certificato de signatura OCSP non valide in le responsa OCSP.
sec-error-revoked-certificate-crl = Le certificato es revocate in un lista de revocation de certificatos del emittitor.
sec-error-unknown-object-type = Typo de objecto incognite specificate.
sec-error-no-event = Nulle nove evento de slot es actualmente disponibile.
sec-error-crl-already-exists = Le CRL existe jam.
sec-error-not-initialized = NSS non es initialisate.
sec-error-token-not-logged-in = Le operation falleva perque le token PKCS#11 non es authenticate.
sec-error-ocsp-responder-cert-invalid = Le certificato del responditor OCSP configurate non es valide.
sec-error-ocsp-bad-signature = Le responsa de OCSP ha un signatura invalide.
sec-error-out-of-search-limits = Le recerca de validation del certificato es foras del limites de recerca
sec-error-invalid-policy-mapping = Le mappa del politica contine irregularitates
sec-error-policy-validation-failed = Le catena de certificato falle de politica de validation
sec-error-unknown-aia-location-type = Typo de position incognite in le extension AIA del certificato
sec-error-bad-http-response = Le servitor rendeva un mal responsa HTTP
sec-error-bad-ldap-response = Le servitor rendeva un mal responsa LDAP
sec-error-failed-to-encode-data = Falta a codificar datos per le codificator ASN1
sec-error-bad-info-access-location = Mal information del position de accesso in le certificato de extension
sec-error-libpkix-internal = Error interne de Libpkix durante le validation del certificato.
sec-error-pkcs11-general-error = Un modulo PKCS #11 retornava CKR_GENERAL_ERROR, indicante le occurrentia de un error irrecovrabile.
sec-error-pkcs11-function-failed = Un modulo PKCS #11 retornava CKR_FUNCTION_FAILED, indicante le function requirite non pote ser exequite. Reprobar de novo pote haber successo.
sec-error-pkcs11-device-error = Un modulo PKCS #11 retornava CKR_DEVICE_ERROR, indicante le occurrentia de un problema con le token o le slot.
sec-error-bad-info-access-method = Methodo de accesso al informationes incognite in extension de certificato.
sec-error-crl-import-failed = Error al tentativa de importar un CRL.
sec-error-expired-password = Contrasigno expirate.
sec-error-locked-password = Contrasigno blocate.
sec-error-unknown-pkcs11-error = Error incognite PKCS #11.
sec-error-bad-crl-dp-url = URL non valide o non gerite in un puncto de distribution CRL.
sec-error-cert-signature-algorithm-disabled = Le certificato era signate per un algorithmo de signatura disactivate perque non secur.
mozilla-pkix-error-not-yet-valid-certificate = Le servitor presentava un certificato que non es plus valide.
mozilla-pkix-error-not-yet-valid-issuer-certificate = Un certificato que non es plus valide era presentate pro emitter le certificato del servitor.
mozilla-pkix-error-signature-algorithm-mismatch = Le algorithmo de signatura in le campo signatura del certificato non corresponde al algorithmo in su campo signatureAlgorithm.
mozilla-pkix-error-ocsp-response-for-cert-missing = Le responsa de OCSP non include un stato pro le certificato a verificar.
mozilla-pkix-error-validity-too-long = Le servitor presentava un certificato invalide perque trop longe.
mozilla-pkix-error-required-tls-feature-missing = Un characteristica de TLS necessari manca.
mozilla-pkix-error-invalid-integer-encoding = Le servitor presentava un certificato que contine un codification non valide de un numero integre. Numeros serial negative, modulos RSA negative e codificationes plus longe quam necesse es causas commun.
mozilla-pkix-error-empty-issuer-name = Le servitor presentava un certificato con un nomine distincte del emittitor vacue.
mozilla-pkix-error-additional-policy-constraint-failed = Un altere coercition de regulamento falleva durante le validation de iste certificato.
mozilla-pkix-error-self-signed-cert = Le certificato non es fidite per que illo es auto-signate.
