# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

reload-tab =
    .label = Recargar le scheda
    .accesskey = R
select-all-tabs =
    .label = Seliger tote le schedas
    .accesskey = S
duplicate-tab =
    .label = Duplicar le scheda
    .accesskey = D
duplicate-tabs =
    .label = Duplicar le schedas
    .accesskey = D
close-tabs-to-the-end =
    .label = Clauder le schedas a dextera
    .accesskey = h
close-other-tabs =
    .label = Clauder le altere schedas
    .accesskey = l
reload-tabs =
    .label = Recargar le schedas
    .accesskey = R
pin-tab =
    .label = Clavar le scheda
    .accesskey = v
unpin-tab =
    .label = Disclavar le scheda
    .accesskey = v
pin-selected-tabs =
    .label = Fixar le schedas
    .accesskey = F
unpin-selected-tabs =
    .label = Liberar le schedas
    .accesskey = L
bookmark-selected-tabs =
    .label = Marcar schedas…
    .accesskey = s
bookmark-tab =
    .label = Marcar le scheda
    .accesskey = M
reopen-in-container =
    .label = Reaperir in un scheda contextual
    .accesskey = e
move-to-start =
    .label = Mover al initio
    .accesskey = i
move-to-end =
    .label = Mover al fin
    .accesskey = f
move-to-new-window =
    .label = Displaciar a un nove fenestra
    .accesskey = f
undo-close-tab =
    .label = Reaperir le ultime scheda claudite
    .accesskey = u
close-tab =
    .label = Clauder le scheda
    .accesskey = C
close-tabs =
    .label = Clauder le schedas
    .accesskey = S
move-tabs =
    .label = Mover le schedas
    .accesskey = v
move-tab =
    .label = Mover le scheda
    .accesskey = v
