# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title ᱯᱩᱛᱷᱤ ᱪᱤᱱᱦᱟ. ᱠᱚ
#define bookmarks_heading ᱯᱩᱛᱷᱤ ᱪᱤᱱᱦᱟ. ᱠᱚ

#define bookmarks_toolbarfolder ᱵᱩᱠᱢᱟᱨᱠ ᱦᱟᱹᱛᱤᱭᱟᱹᱨ ᱯᱚᱴᱚᱢ
#define bookmarks_toolbarfolder_description ᱵᱩᱠᱢᱟᱨ ᱠᱚ ᱨᱮᱭᱟ ᱦᱟᱹᱛᱤᱭᱟᱨ ᱵᱟᱨ ᱨᱮ ᱫᱚᱠᱷᱟᱣ ᱪᱷᱚ ᱞᱟᱹᱜᱤᱫ ᱱᱚᱶᱟ ᱯᱚᱴᱚᱢ ᱨᱮ ᱵᱩᱠᱢᱟᱨᱠ ᱠᱚ ᱥᱮᱞᱮᱫ ᱢᱮ

# LOCALIZATION NOTE (getting_started):
# link title for https://www.mozilla.org/en-US/firefox/central/
#define getting_started ᱮᱛᱦᱚᱵ ᱥᱚᱡᱽ

# LOCALIZATION NOTE (firefox_heading):
# Firefox links folder name
#define firefox_heading Mozilla Firefox

# LOCALIZATION NOTE (firefox_get_help):
# link title for https://www.mozilla.org/en-US/firefox/help/
#define firefox_get_help ᱜᱚᱲᱚ ᱤᱫᱤ ᱢᱮ

# LOCALIZATION NOTE (firefox_customize):
# link title for https://www.mozilla.org/en-US/firefox/customize/
#define firefox_customize Firefox ᱫᱚ ᱠᱩᱥᱤᱭᱟᱠ ᱛᱮ ᱛᱮᱭᱟᱨ ᱢᱮ

# LOCALIZATION NOTE (firefox_community):
# link title for https://www.mozilla.org/en-US/contribute/
#define firefox_community ᱪᱷᱩᱴᱟᱹᱣᱜ ᱢᱮ

# LOCALIZATION NOTE (firefox_about):
# link title for https://www.mozilla.org/en-US/about/
#define firefox_about ᱟᱞᱮ ᱵᱟᱵᱚᱛ

# LOCALIZATION NOTE (nightly_heading):
# Firefox Nightly links folder name
#define nightly_heading Firefox Nightly ᱡᱤᱱᱤᱥ ᱠᱚ

# LOCALIZATION NOTE (nightly_blog):
# Nightly builds only, link title for https://blog.nightly.mozilla.org/
#define nightly_blog Firefox Nightly ᱵᱞᱚᱜᱽ

# LOCALIZATION NOTE (bugzilla):
# Nightly builds only, link title for https://bugzilla.mozilla.org/
#define bugzilla Mozilla Bug ᱜᱷᱮᱨ ᱮᱥᱮᱫ

# LOCALIZATION NOTE (mdn):
# Nightly builds only, link title for https://developer.mozilla.org/
#define mdn Mozilla ᱰᱮᱵᱷᱞᱚᱯᱟᱹᱨ ᱡᱟᱹᱞᱤ

# LOCALIZATION NOTE (nightly_tester_tools):
# Nightly builds only, link title for https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/
#define nightly_tester_tools Nightly ᱡᱟᱸᱪ ᱦᱟᱹᱛᱤᱭᱟᱨ ᱠᱚ

# LOCALIZATION NOTE (crashes):
# Nightly builds only, link title for about:crashes
#define crashes ᱟᱢᱟᱜ ᱡᱷᱚᱛᱚ ᱰᱤᱜᱟᱹᱣ ᱡᱤᱱᱤᱥ ᱠᱚ

# LOCALIZATION NOTE (planet):
# Nightly builds only, link title for https://planet.mozilla.org/
#define planet Planet Mozilla

#unfilter emptyLines
