# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loginsDescriptionAll2 = Infurmaziuns d'annunzia per las suandantas websites èn memorisadas sin tes computer
# LOCALIZATION NOTE (useASecurelyGeneratedPassword):
# Shown in the autocomplete popup to allow filling a generated password into a password field.
useASecurelyGeneratedPassword = Utilisar in pled-clav generà a moda segira
# LOCALIZATION NOTE (generatedPasswordWillBeSaved):
# %S will contain the brandShorterName. This informs the user that the generated password will be automatically saved.
generatedPasswordWillBeSaved = %S vegn a memorisar quest pled-clav per questa website.
# LOCALIZATION NOTE (loginHostAge):
# This is used to show the context menu login items with their age.
# 1st string is the username for the login, 2nd is the login's age.
loginHostAge = %1$S (%2$S)
# LOCALIZATION NOTE (noUsername):
# String is used on the context menu when a login doesn't have a username.
noUsername = Nagin num d'utilisader
# LOCALIZATION NOTE (displaySameOrigin):
# String is used on the autocomplete row when the login origin is a domain match with the document origin
displaySameOrigin = Da questa website
# LOCALIZATION NOTE (insecureFieldWarningDescription2):
# %1$S will contain insecureFieldWarningLearnMore and look like a link to indicate that clicking will open a tab with support information.
insecureFieldWarningDescription2 = Questa connexiun n'è betg segira. Infurmaziuns d'annunzia endatadas qua èn eventualmain periclitadas. %1$S
insecureFieldWarningLearnMore = Ulteriuras infurmaziuns
# LOCALIZATION NOTE (managePasswords.label):
# This label is used in the footer of login autocomplete menus.
managePasswords.label = Administrar ils pleds-clav
