# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Wutum njaatige { $host }…
network-connection-status-connected = Jokkoo ci { $host }…
network-connection-status-sending-request = Yonnee laaj ci { $host }…
network-connection-status-transferring-data = Toxal rootaan yi dale ko ci { $host }…
network-connection-status-connecting = Jokkoo ci { $host }…
network-connection-status-read = Rootaan yi ñu toxal dale ko ci { $host }
network-connection-status-wrote = Rootaan yi ñu yonnee mu jëm ci { $host }
network-connection-status-waiting = Xaar bi ci { $host }…
network-connection-status-looked-up = Wutum njaatige { $host }…
