# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Įrašyti prisijungimai
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Kopijuoti URL
    .accesskey = j
launch-site-url-cmd =
    .label = Aplankyti URL
    .accesskey = n
copy-username-cmd =
    .label = Kopijuoti naudotojo vardą
    .accesskey = n
edit-username-cmd =
    .label = Keisti naudotojo vardą
    .accesskey = e
copy-password-cmd =
    .label = Kopijuoti slaptažodį
    .accesskey = K
edit-password-cmd =
    .label = Keisti slaptažodį
    .accesskey = K
search-filter =
    .accesskey = I
    .placeholder = Ieškoti
column-heading-site =
    .label = Saityno sritis
column-heading-username =
    .label = Abonento vardas
column-heading-password =
    .label = Slaptažodis
column-heading-time-created =
    .label = Pirmąkart naudotas
column-heading-time-last-used =
    .label = Paskiausiai naudotas
column-heading-time-password-changed =
    .label = Paskiausiai pakeistas
column-heading-times-used =
    .label = Naudotas kartų
remove =
    .label = Pašalinti
    .accesskey = š
import =
    .label = Importuoti…
    .accesskey = I
close-button =
    .label = Užverti
    .accesskey = U
show-passwords =
    .label = Rodyti slaptažodžius
    .accesskey = s
hide-passwords =
    .label = Nerodyti slaptažodžių
    .accesskey = s
logins-description-all = Kompiuteryje yra įrašyti šių svetainių prisijungimai
logins-description-filtered = Paieškos kriterijų atitinka šie prisijungimai:
remove-all =
    .label = Pašalinti visus
    .accesskey = v
remove-all-shown =
    .label = Pašalinti visus rodomus
    .accesskey = v
remove-all-passwords-prompt = Ar tikrai pašalinti visus slaptažodžius?
remove-all-passwords-title = Slaptažodžių šalinimas
no-master-password-prompt = Ar tikrai parodyti slaptažodžius?
auto-fill-logins-and-passwords =
    .label = Automatiškai užpildyti prisijungimų vardus ir slaptažodžius
