# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = ئەم ماڵپەڕەوە گوازرایەوە بۆ شوێنیکی تر. دەتەوێت فۆرمی زانیارییەکانی بنێریتەوە بۆ شوێنە نوێییەکە؟
# Directory listing strings
DirTitle = پیڕستی %1$S
DirGoUp = بۆ پێڕستی سەرەوە ئەوەی کە ئاستی بەرزترە
ShowHidden = تەنە شارەوەکان پیشان بدە
DirColName = ناو
DirColSize = قەبارە
DirColMTime = دووا دەستکاری
DirFileLabel = پەڕگە:
UnsafeUriBlocked = سەرچاوەکانی “%1$S” بلۆککرا لەڕێگەی گەڕانی پارێزراو.
