# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language-name-aa = آفار
language-name-ab = ابخازی
language-name-ach = اچولی
language-name-ae = اویسٹن
language-name-af = افریقانی
language-name-ak = عکن
language-name-am = امہارى
language-name-an = ایراگونیز
language-name-ar = عربی
language-name-as = آسامی
language-name-ast = آسٹرین
language-name-av = اویرک
language-name-ay = ایمارا
language-name-az = آزربائیجانی
language-name-ba = باشکیر
language-name-be = بیلاروسی
language-name-bg = بلغاری
language-name-bh = بہاری
language-name-bi = بسلاما
language-name-bm = بامبرا
language-name-bn = بنگالی
language-name-bo = تبتى
language-name-br = بریٹون
language-name-bs = بوسینی
language-name-ca = کٹالن
language-name-cak = کاکچیل
language-name-ce = چیچن
language-name-ch = چمورو
language-name-co = کارسیکائی
language-name-cr = کرعی
language-name-crh = کرایمن ٹاٹر
language-name-cs = چیک
language-name-csb = کشوبیئن
language-name-cu = چرچ سلاوی
language-name-cv = كوئیش
language-name-cy = ویلش
language-name-da = ‏‏ڈینیش
language-name-de = جرمن
language-name-dsb = ہیٹھلی ساربیائی
language-name-dv = دھیوی
language-name-dz = زونکا
language-name-ee = اوی
language-name-el = یونانی
language-name-en = انگریزی
language-name-eo = اسپرانٹو
language-name-es = سپینی
language-name-et = ایسٹونی
language-name-eu = باسک
language-name-fa = فارسی
language-name-ff = فولا
language-name-fi = فینش
language-name-fj = فجی
language-name-fo = فاروس
language-name-fr = فرانسیسی
language-name-fur = فریولیئن
language-name-fy = فریسیان
language-name-ga = آئرش
language-name-gd = اسکاٹی گائل
language-name-gl = گیلیکین
language-name-gn = گورانی
language-name-gu = گجراتی
language-name-gv = مانوی
language-name-ha = ہوسا
language-name-haw = ہوائی
language-name-he = عبرانی
language-name-hi = ہندی
language-name-hil = ہیلیگینون
language-name-ho = ہیری موٹو
language-name-hr = کروشین
language-name-hsb = اتلی سربین
language-name-ht = ہیٹین
language-name-hu = ہنگرین
language-name-hy = آرمینی
language-name-hz = ہریرو
language-name-ia = انٹرلنگوا
language-name-id = انڈونیشی
language-name-ie = انٹرلنگو
language-name-ig = اگبو
language-name-ii = سچوان ژی
language-name-ik = انوپياک
language-name-io = ایڈی
language-name-is = آئی لینڈی
language-name-it = اٹالین
language-name-iu = اینک ٹیٹوٹ
language-name-ja = جاپانی
language-name-jv = جاوانیس
language-name-ka = جارجین
language-name-kab = کبائل
language-name-kg = کانگو
language-name-ki = کی کو یو
language-name-kj = كیونیاما
language-name-kk = کزاک
language-name-kl = گرین لینڈک
language-name-km = خمِر
language-name-kn = کناڈا
language-name-ko = کورین
language-name-kok = کونکانی
language-name-kr = کنوری
language-name-ks = کشمیری
language-name-ku = کرد
language-name-kv = کومی
language-name-kw = كارنش
language-name-ky = کرغیزی
language-name-la = لاطینی
language-name-lb = لیسم برگی
language-name-lg = گنڈا
language-name-li = لم برگن
language-name-lij = لیگورین
language-name-ln = لنگالی
language-name-lo = لاؤ
language-name-lt = لیتھونی
language-name-ltg = لٹگالین
language-name-lu = لیوبا-کٹانگا
language-name-lv = لاٹیوی
language-name-mai = مائتھیلی
language-name-meh = جنوب مغربی لیکسی آکو میکسٹیک
language-name-mg = مالاگاسی
language-name-mh = مارشیلائی
language-name-mi = ماوری
language-name-mix = میکس ٹیپیک میکسٹیک
language-name-mk = مقدونی
language-name-ml = ملیالم
language-name-mn = منگولین
language-name-mr = میراٹھی
language-name-ms = مالی
language-name-mt = مالٹی
language-name-my = برمی
language-name-na = نورو
language-name-nb = نارویجی بوکمال
language-name-nd = دبیل، شمالی
language-name-ne = نیپالی
language-name-ng = این ڈونگا
language-name-nl = ڈچ
language-name-nn = نارویجی نورسک
language-name-no = نارویجی
language-name-nr = دبیل، جنوبی
language-name-nso = سوتھو، شمالی
language-name-nv = نواجو
language-name-ny = چیچیوا
language-name-oc = آكسيٹان
language-name-oj = اوجیبوے
language-name-om = اورومو
language-name-or = اوڑیہ
language-name-os = اوسیٹیائی
language-name-pa = پنجابی
language-name-pi = پالی
language-name-pl = پولش
language-name-ps = پشتو
language-name-pt = پرتگیزی
language-name-qu = قیچوا
language-name-rm = رومی ریتو
language-name-rn = کیروندی
language-name-ro = رومانی
language-name-ru = روسی
language-name-rw = کنیا روانڈا
language-name-sa = سنسکرت
language-name-sat = سنتالی
language-name-sc = سردینی
language-name-sco = سکوٹس
language-name-sd = سندھی
language-name-se = شمالی سامی
language-name-sg = سانگو
language-name-si = سنہالی
language-name-sk = سلواک
language-name-skr = سرائیکی
language-name-sl = سلو وینی
language-name-sm = ساموائی
language-name-sn = شونا
language-name-so = سومالی
language-name-son = سانگھے
language-name-sq = البانی
language-name-sr = سربی
language-name-ss = سواتی
language-name-st = سوتھو، جنوبی
language-name-su = سوڈانی
language-name-sv = سویڈش
language-name-sw = سواحلی
language-name-szl = سیلیسی
language-name-ta = تامل
language-name-te = تیلگو
language-name-tg = تاجک
language-name-th = تھائی
language-name-ti = ٹيگرنيا
language-name-tig = ٹیگری
language-name-tk = ترکمانی
language-name-tl = ٹیگ لاگ
language-name-tlh = کلنگن
language-name-tn = ٹسوانا
language-name-to = ٹونگا
language-name-tr = ترکی
language-name-trs = ٹرائکی
language-name-ts = ٹسونگا
language-name-tt = تاتار
language-name-tw = توی
language-name-ty = تہیتی
language-name-ug = ییغور
language-name-uk = یوکرائنی
language-name-ur = اردو
language-name-uz = اُزبک
language-name-ve = وینڈا
language-name-vi = ویت نامی
language-name-vo = ولاپک
language-name-wa = والون
language-name-wen = سوربیں
language-name-wo = وُلوف
language-name-xh = ہوسا
language-name-yi = یدش
language-name-yo = یور
language-name-za = زہوینگ
language-name-zam = میاحوآٹین زاپوٹیک
language-name-zh = چینی
language-name-zu = زولو
