# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Notice: If you're updating this list, you should also
###         update the list in mozIntl.js.

region-name-ad = এণ্ড'ৰা
region-name-ae = সংযুক্ত আৰব আমিৰাত
region-name-af = আফগানিস্তান
region-name-ag = এণ্টিগুৱা আৰু বাৰবুডা
region-name-ai = এংগুইলা
region-name-al = আলবেনিয়া
region-name-am = আৰ্মেনিয়া
region-name-ao = এংগোলা
region-name-aq = এণ্টাৰ্কটিকা
region-name-ar = আৰ্জেনটিনা
region-name-as = আমেৰিকান ছামোৱা
region-name-at = অষ্ট্ৰিয়া
region-name-au = অষ্ট্ৰেলিয়া
region-name-aw = আৰুবা
region-name-az = আজাৰবাইজান
region-name-ba = ব'ছনিয়া আৰু হাৰ্জগ'ভিনা
region-name-bb = বাৰ্বাড'ছ
region-name-bd = বাংলাদেশ
region-name-be = বেলজিয়াম
region-name-bf = বুৰ্কিনা ফাছ'
region-name-bg = বুলগেৰিয়া
region-name-bh = বাহৰেইন
region-name-bi = বুৰুণ্ডি
region-name-bj = বেনিন
region-name-bl = ছেইণ্ট বাৰথেলেমী
region-name-bm = বাৰ্মুডা
region-name-bn = ব্ৰুনেই
region-name-bo = ব'লিভিয়া
region-name-bq = বনেইৰ, ছিণ্ট এউষ্টাটচিউছ আৰু ছাবা
region-name-br = ব্ৰাজিল
region-name-bs = বাহামাছ, দি
region-name-bt = ভুটান
region-name-bv = বুভে দ্বীপ
region-name-bw = ব'টছুৱানা
region-name-by = বেলাৰুছ
region-name-bz = বেলিজে
region-name-ca = কানাডা
region-name-cc = ক'ক'ছ (কিলিং) দ্বীপপুঞ্জ
region-name-cd = কংগ' (কিনশ্বাছা)
region-name-cf = মধ্য আফ্ৰিকান প্ৰজাতন্ত্ৰ
region-name-cg = কংগ' (ব্ৰাজাভিল)
region-name-ch = ছুইজাৰলেণ্ড
region-name-ci = আইভৰি ক'ষ্ট
region-name-ck = কুক দ্বীপপুঞ্জ
region-name-cl = চিলি
region-name-cm = কেমেৰুণ
region-name-cn = চীন
region-name-co = ক'ল'ম্বিয়া
region-name-cp = ক্লিপাৰট'ন দ্বীপ
region-name-cr = ক'ষ্টা ৰিকা
region-name-cu = কিউবা
region-name-cv = কাব' ভাৰ্ডে
region-name-cw = কুৰাকাঅ'
region-name-cx = ক্ৰিষ্টমাছ দ্বীপ
region-name-cy = ছাইপ্ৰাছ
region-name-cz = চেক প্ৰজাতন্ত্ৰ
region-name-de = জাৰ্মানি
region-name-dg = ডিয়েগ' গাৰচিয়া
region-name-dj = জিবুতি
region-name-dk = ডেনমাৰ্ক
region-name-dm = ড'মিনিকা
region-name-do = ড'মিনিকান প্ৰজাতন্ত্ৰ
region-name-dz = আলজেৰিয়া
region-name-ec = ইকুয়েড'ৰ
region-name-ee = ইষ্ট'নিয়া
region-name-eg = মিছৰ
region-name-eh = পশ্চিম ছাহাৰা
region-name-er = এৰিট্ৰিয়া
region-name-es = স্পেইন
region-name-et = ইথিঅ'পিয়া
region-name-fi = ফিনলেণ্ড
region-name-fj = ফিজি
region-name-fk = ফ'কলেণ্ড দ্বীপপুঞ্জ (ইছলাছ মালভিনাছ)
region-name-fm = ফেডাৰেটেড ষ্টেট অৱ মাইক্ৰনেছিয়া
region-name-fo = ফেৰ' দ্বীপপুঞ্জ
region-name-fr = ফ্ৰাঞ্চ
region-name-ga = গেবন
region-name-gb = যুক্তৰাজ্য
region-name-gd = গ্ৰেনাডা
region-name-ge = জৰ্জিয়া
region-name-gf = ফ্ৰেঞ্চ গায়ানা
region-name-gg = গুৱেৰ্নছে
region-name-gh = ঘানা
region-name-gi = জিব্ৰাল্টাৰ
region-name-gl = গ্ৰিনলেন্ড
region-name-gm = গেম্বিয়া, দি
region-name-gn = গিনি
region-name-gp = গুয়াডেল্যুপ
region-name-gq = ইকুয়েটোৰিয়াল গিনি
region-name-gr = গ্ৰিছ
region-name-gs = দক্ষিণ জৰ্জিয়া আৰু দক্ষিণ ছেণ্ডৱিচ দ্বীপপুঞ্জ
region-name-gt = গুয়াতেমালা
region-name-gu = গুয়াম
region-name-gw = গিনি-বিছাউ
region-name-gy = গায়ানা
region-name-hk = হং কং
region-name-hm = হাৰ্ড দ্বীপপুঞ্জ আৰু মেকডোনাল্ড দ্বীপপুঞ্জ
region-name-hn = হন্ডুৰাছ
region-name-hr = ক্ৰোয়েছিয়া
region-name-ht = হাইতি
region-name-hu = হাঙ্গেৰি
region-name-id = ইন্দোনেছিয়া
region-name-ie = আইৰলেন্ড
region-name-il = ইজৰাইল
region-name-im = আইল অফ মেন
region-name-in = ভাৰত
region-name-io = ব্ৰিটিশ ভাৰত মহাছাগরীয় অঞ্চল
region-name-iq = ইৰাক
region-name-ir = ইৰান
region-name-is = আইছলেন্ড
region-name-it = ইটালি
region-name-je = জাৰ্চি
region-name-jm = জামাইকা
region-name-jo = জৰ্ডান
region-name-jp = জাপান
region-name-ke = কেনিয়া
region-name-kg = কিৰ্গিজস্তান
region-name-kh = কেম্বোডিয়া
region-name-ki = কিৰিবাছ
region-name-km = কোমোৰোছ
region-name-kn = ছেন্ট কিটছ আৰু নেভিছ
region-name-kp = কৰিয়া, উত্তৰ
region-name-kr = কৰিয়া, দক্ষিণ
region-name-kw = কুৱেইত
region-name-ky = কেমেন দ্বীপপুঞ্জ
region-name-kz = কাজাখস্তান
region-name-la = লাওছ
region-name-lb = লেবানন
region-name-lc = ছেন্ট লুছিয়া
region-name-li = লিখতেনস্টাইন
region-name-lk = শ্রীলঙ্কা
region-name-lr = লাইবেৰিয়া
region-name-ls = লেছোথো
region-name-lt = লিথুয়ানিয়া
region-name-lu = লাক্সেম্বুৰ্গ
region-name-lv = লাটভিয়া
region-name-ly = লিবিয়া
region-name-ma = মৰোক্কো
region-name-mc = মোনাকো
region-name-md = মোল্ডোভা প্ৰজাতন্ত্ৰ
region-name-me = মন্টেনেগ্ৰো
region-name-mf = ছেন্ট মাৰ্টিন
region-name-mg = মাদাগাস্কাৰ
region-name-mh = মাৰ্শাল দ্বীপপুঞ্জ
region-name-mk = মেচিড'নিয়া
region-name-ml = মালি
region-name-mm = বৰ্মা
region-name-mn = মঙ্গোলিয়া
region-name-mo = মাকাউ
region-name-mp = উত্তৰ মাৰিয়ানা দ্বীপপুঞ্জ
region-name-mq = মাৰ্টিনিক
region-name-mr = মৰিটানিয়া
region-name-ms = মন্টছেৰাত
region-name-mt = মল্টা
region-name-mu = মৰিচাছ
region-name-mv = মালডিভছ
region-name-mw = মালাউই
region-name-mx = মেক্সিকো
region-name-my = মালেছিয়া
region-name-mz = মোজাম্বিক
region-name-na = নামিবিয়া
region-name-nc = নিউ কেলেডোনিয়া
region-name-ne = নাইজাৰ
region-name-nf = নৰফোল্ক দ্বীপ
region-name-ng = নাইজেৰিয়া
region-name-ni = নিকাৰাগুয়া
region-name-nl = নেদাৰলেন্ড
region-name-no = নৰৱে
region-name-np = নেপাল
region-name-nr = নাউৰু
region-name-nu = নিউ
region-name-nz = নিউজিলেন্ড
region-name-om = ওমান
region-name-pa = পানামা
region-name-pe = পেৰু
region-name-pf = ফ্ৰেঞ্চ পলিনেছিয়া
region-name-pg = পাপুয়া নিউ গিনি
region-name-ph = ফিলিপাইনছ
region-name-pk = পাকিস্তান
region-name-pl = পোলেন্ড
region-name-pm = ছেন্ট পিয়েৰ আৰু মিকেলন
region-name-pn = পিটকে'ৰ্ণ দ্বীপ
region-name-pr = পুয়েৰ্তো ৰিকো
region-name-pt = পোৰ্টুগাল
region-name-pw = পালাউ
region-name-py = পাৰাগুৱে
region-name-qa = কাতাৰ
region-name-qm = মিডৱে' দ্বীপপুঞ্জ
region-name-qs = ভাৰতীয় বাছা
region-name-qu = জুৱান ডে ন'ভা দ্বীপ
region-name-qw = ৱেক দ্বীপ
region-name-qx = গ্ল'ৰিয়'ছ' দ্বীপপুঞ্জ
region-name-qz = এক্ৰ'টিৰি
region-name-re = ৰিইউনিয়ান
region-name-ro = ৰোমানিয়া
region-name-rs = ছাৰ্বিয়া
region-name-ru = ৰাছিয়া
region-name-rw = ৰৱান্ডা
region-name-sa = চাউদি আৰব
region-name-sb = ছলোমান দ্বীপপুঞ্জ
region-name-sc = ছেছেলছ
region-name-sd = চুদান
region-name-se = চুইডেন
region-name-sg = চিঙ্গাপুৰ
region-name-sh = ছেইণ্ট হেলেনা, এছেনশ্যন আৰু ট্ৰিষ্টেন ডা কুনহা
region-name-si = স্লোভেনিয়া
region-name-sk = স্লোভাকিয়া
region-name-sl = ছিয়েৰা লিওন
region-name-sm = ছান মাৰিনো
region-name-sn = ছেনেগাল
region-name-so = চোমালিয়া
region-name-sr = চুৰিনাম
region-name-ss = দক্ষিণ ছুডান
region-name-st = ছাও টোমে আৰু প্ৰিন্সিপে
region-name-sv = এল ছালভাডৰ
region-name-sx = ছেণ্ট মার্টিন
region-name-sy = ছিৰিয়া
region-name-sz = ছোৱাজিলেন্ড
region-name-tc = টাৰ্কছ আৰু কেইকোছ দ্বীপ
region-name-td = চাড
region-name-tf = ফ্ৰাঞ্চৰ দক্ষিণ আৰু এণ্টাৰ্কটিক ভূমি
region-name-tg = টোগো
region-name-th = থাইলেন্ড
region-name-tj = তাজিকিস্তান
region-name-tk = টোকেলাউ
region-name-tl = টিমোৰ-লেস্তে
region-name-tm = তুৰ্কমেনিস্তান
region-name-tn = টিউনিছিয়া
region-name-to = টোঙ্গা
region-name-tr = তুৰ্কি
region-name-tt = ত্ৰিনিদাদ
region-name-tv = টুভালু
region-name-tw = তাইৱান
region-name-tz = তানজানিয়া
region-name-ua = ইউক্ৰেন
region-name-ug = উগান্ডা
region-name-us = মাৰ্কিন যুক্তৰাষ্ট্ৰ
region-name-uy = উৰুগুৱে
region-name-uz = উজ্বেকিস্তান
region-name-va = ভেটিকান
region-name-vc = ছেন্ট ভিনছেন্ট আৰু গ্ৰেনাডিনছ
region-name-ve = ভেনেজুয়েলা
region-name-vg = ভাৰ্জিন দ্বীপপুঞ্জ, ব্ৰিটিছ
region-name-vi = ভাৰ্জিন দ্বীপপুঞ্জ, ইউ.এছ.
region-name-vn = ভিয়েতনাম
region-name-vu = ভানুয়াটু
region-name-wf = ৱালিছ আৰু ফুটুনা
region-name-ws = ছামোয়া
region-name-xa = এশ্বম'ৰ আৰু কাৰ্টিয়াৰ দ্বীপপুঞ্জ
region-name-xb = বাকেৰ দ্বীপ
region-name-xc = ক'ৰাল সমুদ্ৰ দ্বীপ
region-name-xd = ঢেকেলিয়া
region-name-xe = ইউৰ'পা দ্বীপ
region-name-xg = গাজা ষ্ট্ৰিপ
region-name-xh = হ'লেণ্ড দ্বীপ
region-name-xj = জান ময়েন
region-name-xk = ক'ছ'ভ'
region-name-xl = পালমিৰা এট'ল
region-name-xm = কিংমেন ৰীফ
region-name-xp = পাৰাচেল দ্বীপপুঞ্জ
region-name-xq = জাৰভিছ দ্বীপপুঞ্জ
region-name-xr = ছুৱালবাৰ্ড
region-name-xs = স্প্ৰেটলি দ্বীপপুঞ্জ
region-name-xt = ট্ৰমেলিন দ্বীপ
region-name-xu = জ'নছ'ন এট'ল
region-name-xv = নাভাছা দ্বীপ
region-name-xw = ৱেষ্ট বেংক
region-name-ye = ইয়েমেন
region-name-yt = মেওতে
region-name-za = দক্ষিণ আফ্ৰিকা
region-name-zm = জাম্বিয়া
region-name-zw = জিম্বাবুয়ে
