# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Adakah anda ingin percaya "%S" untuk kegunaan berikut?
unnamedCA = Autoriti Sijil (tidak bernama)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Sila masukkan kata laluan yang digunakan untuk menyulitkan sijil sandaran ini:
# Page Info
pageInfo_NoEncryption = Sambungan Tidak Dienkripsi
pageInfo_Privacy_None1 = Laman web %S tidak menyokong enkripsi halaman yang anda sedang layari.
pageInfo_Privacy_None2 = Maklumat yang dihantar melalui Internet tanpa enkripsi boleh dilihat oleh pihak lain ketika dalam transit.
pageInfo_Privacy_None4 = Halaman yang sedang anda tonton tidak terenkripsi sebelum dihantar melalui Internet.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Sambungan Dienkrip (%1$S, %2$S bit kekunci, %3$S)
pageInfo_BrokenEncryption = Enkripsi Rosak (%1$S, %2$S kekunci bit, %3$S)
pageInfo_Privacy_Encrypted1 = Halaman yang anda sedang papar telah dienkripsi sebelum dihantar melalui Internet.
pageInfo_Privacy_Encrypted2 = Enkripsi menyukarkan orang yang tidak diberkenaan untuk melihat maklumat yang dihantar ke dalam sesebuah komputer. Oleh itu, kemungkinan besar tidak ada sesiapa yang membaca halaman ini semasa dihantar ke seluruh rangkaian.
pageInfo_MixedContent = Sebahagian Sambungan Dienkripsi
pageInfo_MixedContent2 = Sebahagian halaman yang anda sedang papar tidak dienkripsi sebelum dihantar melalui Internet.
pageInfo_WeakCipher = Sambungan anda ke laman web ini menggunakan enkripsi yang lemah dan tiada privasi. Orang lain boleh melihat maklumat atau mengubah tingkah laku laman web anda.
pageInfo_CertificateTransparency_Compliant = This website complies with the Certificate Transparency policy.
# Token Manager
password_not_set = (tidak ditetapkan)
