# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host } সন্ধান কৰা হৈছে…
network-connection-status-connected = { $host } লৈ সংযুক্ত…
network-connection-status-sending-request = { $host } লৈ অনুৰোধ পঠিওৱা হৈছে…
network-connection-status-transferring-data = { $host } ৰ পৰা তথ্য পোৱা হৈছে…
network-connection-status-connecting = { $host } লৈ সংযোগ কৰা হৈছে…
network-connection-status-read = { $host } পঢ়া হ'ল
network-connection-status-wrote = { $host } লিখা হ'ল
network-connection-status-waiting = { $host } লৈ লিখা হৈছে…
network-connection-status-looked-up = { $host } দেখা হৈছে…
network-connection-status-tls-handshake = { $host }-ৰ লগত TLS হেণ্ডশ্বেক কৰি থকা হৈছে…
network-connection-status-tls-handshake-finished = { $host }-ৰ বাবে TLS হেণ্ডশ্বেক শেষ হ'ল…
