# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Sa gayi'ìt sesión ngà naginu sà'
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Nako' URL ni nachru' ané
    .accesskey = y
launch-site-url-cmd =
    .label = Gatu ni'iajt URL
    .accesskey = V
copy-username-cmd =
    .label = Nako' nī nachrun' a'ngô hiūj u si yuguî'
    .accesskey = U
edit-username-cmd =
    .label = Nachrūn si yuguît
    .accesskey = d
copy-password-cmd =
    .label = Nako' da'nga' hùii nī nachrun' a'ngô hiūj u
    .accesskey = C
edit-password-cmd =
    .label = Nachrūn da'nga' huìi
    .accesskey = E
search-filter =
    .accesskey = S
    .placeholder = Nana'uì'
column-heading-site =
    .label = Sîtio
column-heading-username =
    .label = Si yuguî rè'
column-heading-password =
    .label = Danga' huìi
column-heading-time-created =
    .label = Sa garajsun sinïnt
column-heading-time-last-used =
    .label = Sa garajsun rukù nï't
column-heading-time-password-changed =
    .label = Sa nadunâ rukù nï't
column-heading-times-used =
    .label = Diû garajsunt
remove =
    .label = Guxūn
    .accesskey = R
import =
    .label = Ga’nïnj gan’an a’ngô hiūj u…
    .accesskey = I
close-button =
    .label = Narán
    .accesskey = C
show-passwords =
    .label = Digun da'nga huii
    .accesskey = P
hide-passwords =
    .label = Gachi hui' da'nga'a
    .accesskey = P
logins-description-all = Da' gayi'i nej sesión riña a'ngo sitio ni nun sa' ma riña si aga' re'
logins-description-filtered = Nej sa ayi'ie sesión ni nikaj dugui'ij nga sa nana'ui' re':
remove-all =
    .label = Guxun' dara'anj
    .accesskey = A
remove-all-shown =
    .label = Guxun' Ni digun' dara'anj
    .accesskey = N
remove-all-passwords-prompt = ¿ Hua hià ruat dure' daran' da'nga huii vè'ej?
remove-all-passwords-title = Dure' daran' da'nga huii
no-master-password-prompt = ¿ Hua hiá ruat digan nej da'nga huii vè'ej?
