# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

jump = گوم زیڌن
press = تپنیڌن
check = نشووه زیڌن
uncheck = وورداشتن نشووه
select = پسند
open = گۊشیڌن
close = بستن
switch = آلشت
click = کیلیک
collapse = کۊتال کردن
expand = بولند کردن
activate = فعال کردن
cycle = گردش
# An action provided to accessibility clients such as screen readers to allow
# them to click an element when the click will be handled by a container
# (ancestor) element. This is not normally reported to users.
clickAncestor = ری جد کلیک کۊنین
# Universal Access API support
# (Mac Only)
# The Role Description for AXWebArea (the web widget). Like in Safari.
htmlContent = موئتوا HTML
# The Role Description for the Tab button.
tab = بلگه
# The Role Description for definition list dl, dt and dd
term = استلا
definition = تعریف
# The Role Description for an input type="search" text field
searchTextField = بشن پیتینیڌن هؽلی
# Role Description (exposed as AXTitle) for datepickers
dateField = فیلد تاریخ
# The Role Description for WAI-ARIA Landmarks
application = برنومه
search = پیتینیڌن
banner = بنر
navigation = ناوبری
complementary = موکمل
content = موئتوا
main = ٱسلی
# The (spoken) role description for various WAI-ARIA roles
alert = هوشدار
alertDialog = هوشدار موکالمه
dialog = موهاوره
article = مقاله
document = سند
# The (spoken) role description for the WAI-ARIA figure role
# https://w3c.github.io/aria/core-aam/core-aam.html#role-map-figure
figure = شلگ
# The (spoken) role description for the WAI-ARIA heading role
# https://w3c.github.io/aria/core-aam/core-aam.html#role-map-heading
heading = سر فسل
log = تفاقا
marquee = marquee
math = ریازی
note = ویرداشت
region = وولات
status = وزعیت برنومه
timer = زمووݩ سنج
tooltip = هیاری هر دمۊوی
separator = سوا ساز
tabPanel = جاگه بلگه
# The roleDescription for the html:mark element
highlight = هایلایت کردن
# The roleDescription for the details element
details = جۊزعیات
# The roleDescription for the summary element
summary = خولاسه
# LOCALIZATION NOTE (inputColorValue): %1$S%%, %2$S%%, and %3$S%% represent the red, green, and blue color values as a percentage.
inputColorValue = %1$S%% سوئر %2$S%% ساوز %3$S%% کوۊ
