# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

e2e-intro-description = För att skicka krypterade eller digitalt signerade meddelanden måste du konfigurera en krypteringsteknik, antingen OpenPGP eller S/MIME.
e2e-intro-description-more = Välj din personliga nyckel för att aktivera användning av OpenPGP eller ditt personliga certifikat för att aktivera användning av S/MIME. För en personlig nyckel eller certifikat äger du motsvarande hemlig nyckel.
openpgp-key-user-id-label = Konto / användar-ID
openpgp-keygen-title-label =
    .title = Generera OpenPGP-nyckel
openpgp-cancel-key =
    .label = Avbryt
    .tooltiptext = Avbryt nyckelgenerering
openpgp-key-gen-expiry-title =
    .label = Nyckeln upphör
openpgp-key-gen-expire-label = Nyckeln upphör om
openpgp-key-gen-days-label =
    .label = dagar
openpgp-key-gen-months-label =
    .label = månader
openpgp-key-gen-years-label =
    .label = år
openpgp-key-gen-no-expiry-label =
    .label = Nyckeln upphör inte
openpgp-key-gen-key-size-label = Nyckelstorlek
openpgp-key-gen-console-label = Nyckelgenerering
openpgp-key-gen-key-type-label = Nyckeltyp
openpgp-key-gen-key-type-rsa =
    .label = RSA
openpgp-key-gen-key-type-ecc =
    .label = ECC (elliptisk kurva)
openpgp-generate-key =
    .label = Generera nyckel
    .tooltiptext = Genererar en ny OpenPGP-kompatibel nyckel för kryptering och/eller signering
openpgp-advanced-prefs-button-label =
    .label = Avancerat…
openpgp-keygen-desc = <a data-l10n-name="openpgp-keygen-desc-link">OBS: Nyckelgenerering kan ta upp till flera minuter att slutföra.</a> Stäng inte programmet medan nyckelgenerering pågår. Om du surfar eller utför en hårddiskaktivitet under nyckelgenerering kommer du att fylla på den "slumpmässiga poolen" och påskynda processen. Du får en varning när nyckelgenerering är klar.
openpgp-key-expiry-label =
    .label = Upphör
openpgp-key-id-label =
    .label = Nyckel-ID
openpgp-cannot-change-expiry = Detta är en nyckel med en komplex struktur, ändring av dess utgångsdatum stöds inte.
openpgp-key-man-title =
    .title = OpenPGP-nyckelhanterare
openpgp-key-man-generate =
    .label = Nytt nyckelpar
    .accesskey = N
openpgp-key-man-gen-revoke =
    .label = Återkallningscertifikat
    .accesskey = t
openpgp-key-man-ctx-gen-revoke-label =
    .label = Skapa och spara återkallningscertifikat
openpgp-key-man-file-menu =
    .label = Arkiv
    .accesskey = A
openpgp-key-man-edit-menu =
    .label = Redigera
    .accesskey = R
openpgp-key-man-view-menu =
    .label = Visa
    .accesskey = V
openpgp-key-man-generate-menu =
    .label = Generera
    .accesskey = G
openpgp-key-man-keyserver-menu =
    .label = Nyckelserver
    .accesskey = N
openpgp-key-man-import-public-from-file =
    .label = Importera publika nycklar från fil
    .accesskey = m
openpgp-key-man-import-secret-from-file =
    .label = Importera hemliga nycklar från fil
openpgp-key-man-import-sig-from-file =
    .label = Importera återkallelse från fil
openpgp-key-man-import-from-clipbrd =
    .label = Importera nycklar från Urklipp
    .accesskey = p
openpgp-key-man-import-from-url =
    .label = Importera nycklar från URL
    .accesskey = U
openpgp-key-man-export-to-file =
    .label = Exportera publika nycklar till fil
    .accesskey = E
openpgp-key-man-send-keys =
    .label = Skicka publika nycklar via e-post
    .accesskey = S
openpgp-key-man-backup-secret-keys =
    .label = Säkerhetskopiera hemliga nycklar till fil
    .accesskey = S
openpgp-key-man-discover-cmd =
    .label = Hitta nycklar online
    .accesskey = H
openpgp-key-man-discover-prompt = Om du vill hitta OpenPGP-nycklar online, på nyckelservrar eller använda WKD-protokollet anger du antingen en e-postadress eller ett nyckel-ID.
openpgp-key-man-discover-progress = Söker…
openpgp-key-copy-key =
    .label = Kopiera publik nyckel
    .accesskey = K
openpgp-key-export-key =
    .label = Exportera publik nyckel till fil
    .accesskey = E
openpgp-key-backup-key =
    .label = Säkerhetskopiera hemlig nyckel till fil
    .accesskey = S
openpgp-key-send-key =
    .label = Skicka publik nyckel via e-post
    .accesskey = S
openpgp-key-man-copy-to-clipbrd =
    .label = Kopiera publika nycklar till Urklipp
    .accesskey = K
openpgp-key-man-ctx-expor-to-file-label =
    .label = Exportera nycklar till fil
openpgp-key-man-ctx-copy-to-clipbrd-label =
    .label = Kopiera publika nycklar till Urklipp
openpgp-key-man-close =
    .label = Stäng
openpgp-key-man-reload =
    .label = Ladda om nyckelcache
    .accesskey = L
openpgp-key-man-change-expiry =
    .label = Ändra utgångsdatum
    .accesskey = n
openpgp-key-man-del-key =
    .label = Ta bort nycklar
    .accesskey = T
openpgp-delete-key =
    .label = Ta bort nyckel
    .accesskey = T
openpgp-key-man-revoke-key =
    .label = Återkalla nyckel
    .accesskey = t
openpgp-key-man-key-props =
    .label = Nyckelegenskaper
    .accesskey = N
openpgp-key-man-key-more =
    .label = Mer
    .accesskey = M
openpgp-key-man-view-photo =
    .label = Foto-ID
    .accesskey = F
openpgp-key-man-ctx-view-photo-label =
    .label = Visa foto-ID
openpgp-key-man-show-invalid-keys =
    .label = Visa ogiltiga nycklar
    .accesskey = V
openpgp-key-man-show-others-keys =
    .label = Visa nycklar från andra personer
    .accesskey = a
openpgp-key-man-user-id-label =
    .label = Namn
openpgp-key-man-fingerprint-label =
    .label = Fingeravtryck
openpgp-key-man-select-all =
    .label = Välj alla nycklar
    .accesskey = V
openpgp-key-man-empty-tree-tooltip =
    .label = Ange söktermer i rutan ovan
openpgp-key-man-nothing-found-tooltip =
    .label = Inga nycklar matchar dina söktermer
openpgp-key-man-please-wait-tooltip =
    .label = Vänta medan nycklar laddas…
openpgp-key-man-filter-label =
    .placeholder = Sök efter nycklar
openpgp-key-man-select-all-key =
    .key = a
openpgp-key-details-title =
    .title = Nyckelegenskaper
openpgp-key-details-signatures-tab =
    .label = Certifieringar
openpgp-key-details-structure-tab =
    .label = Strukturerad
openpgp-key-details-uid-certified-col =
    .label = Användar-ID / Certifierat av
openpgp-key-details-user-id2-label = Påstådd nyckelägare
openpgp-key-details-id-label =
    .label = ID
openpgp-key-details-key-type-label = Typ
openpgp-key-details-key-part-label =
    .label = Nyckeldel
openpgp-key-details-algorithm-label =
    .label = Algoritm
openpgp-key-details-size-label =
    .label = Storlek
openpgp-key-details-created-label =
    .label = Skapad
openpgp-key-details-created-header = Skapad
openpgp-key-details-expiry-label =
    .label = Upphör
openpgp-key-details-expiry-header = Upphör
openpgp-key-details-usage-label =
    .label = Användning
openpgp-key-details-fingerprint-label = Fingeravtryck
openpgp-key-details-sel-action =
    .label = Välj åtgärd…
    .accesskey = V
openpgp-key-details-also-known-label = Påstådda alternativa identiteter för nyckelägaren:
openpgp-card-details-close-window-label =
    .buttonlabelaccept = Stäng
openpgp-acceptance-label =
    .label = Dina accepterade
openpgp-acceptance-rejected-label =
    .label = Nej, avvisa den här nyckeln.
openpgp-acceptance-undecided-label =
    .label = Inte ännu, kanske senare.
openpgp-acceptance-unverified-label =
    .label = Ja, men jag har inte verifierat att det är rätt nyckel.
openpgp-acceptance-verified-label =
    .label = Ja, jag har personligen verifierat att denna nyckel har rätt fingeravtryck.
key-accept-personal =
    För denna nyckel har du både den publika och den hemliga delen. Du kan använda den som en personlig nyckel.
    Om du fick den här nyckeln av någon annan, använd inte den som en personlig nyckel.
key-personal-warning = Skapade du den här nyckeln själv och det visade ägarskapet av nyckeln hänvisar till dig själv?
openpgp-personal-no-label =
    .label = Nej, använd inte den som min personliga nyckel.
openpgp-personal-yes-label =
    .label = Ja, behandla den här nyckeln som en personlig nyckel.
openpgp-copy-cmd-label =
    .label = Kopiera

## e2e encryption settings


## OpenPGP Key selection area


## Account settings export output

# Strings used in trust.jsm
key-valid-unknown = okänd
key-valid-invalid = ogiltig
key-valid-disabled = inaktiverad
key-valid-revoked = återkallad
key-valid-expired = upphörd
key-trust-untrusted = ej betrodd
key-trust-full = betrodd
key-trust-group = (grupp)
# Strings used in commonWorkflows.js
import-key-file = Importera OpenPGP-nyckelfil
import-rev-file = Importera OpenPGP-återkallningsfil
gnupg-file = GnuPG-filer
import-keys-failed = Importering av nycklarna misslyckades
passphrase-prompt = Ange lösenfrasen som låser upp följande nyckel: { $key }
file-to-big-to-import = Denna fil är för stor. Importera inte en stor uppsättning nycklar på en gång.
# Strings used in enigmailKeygen.js
save-revoke-cert-as = Skapa och spara återkallningscertifikat
revoke-cert-ok = Återkallningscertifikatet har skapats. Du kan använda det för att upphäva din publika nyckel, t.ex. om du skulle förlora din hemliga nyckel.
revoke-cert-failed = Återkallningscertifikatet kunde inte skapas.
gen-going = Nyckelgenerering pågår redan!
dlg-button-ok = &OK
dlg-button-close = &Stäng
dlg-button-cancel = &Avbryt
dlg-no-prompt = Visa inte denna dialogruta igen.
enig-prompt = OpenPGP-prompt
enig-confirm = OpenPGP-bekräftelse
enig-alert = OpenPGP-varning
enig-info = OpenPGP-information
# Strings used in persistentCrypto.jsm
dlg-button-retry = &Försök igen
dlg-button-skip = &Hoppa över
# Strings used in enigmailCommon.js
enig-error = OpenPGP-fel
enig-alert-title =
    .title = OpenPGP-varning
