# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Spamiyntane dane logowanio
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Kopiuj adresa URL
    .accesskey = j
launch-site-url-cmd =
    .label = Nawiydź adresa URL
    .accesskey = N
copy-username-cmd =
    .label = Kopiuj miano ôd używocza
    .accesskey = U
edit-username-cmd =
    .label = Edytuj miano ôd używocza
    .accesskey = d
copy-password-cmd =
    .label = Kopiuj hasło
    .accesskey = K
edit-password-cmd =
    .label = Edytuj hasło
    .accesskey = E
search-filter =
    .accesskey = S
    .placeholder = Szukej
column-heading-site =
    .label = Strōna
column-heading-username =
    .label = Miano ôd używocza
column-heading-password =
    .label = Hasło
column-heading-time-created =
    .label = Piyrsze użycie
column-heading-time-last-used =
    .label = Ôstatnie użycie
column-heading-time-password-changed =
    .label = Ôstatnio zmiana
column-heading-times-used =
    .label = Wiela razy użyte
remove =
    .label = Skasuj
    .accesskey = S
import =
    .label = Importuj…
    .accesskey = I
close-button =
    .label = Zawrzij
    .accesskey = Z
show-passwords =
    .label = Pokoż hasła
    .accesskey = H
hide-passwords =
    .label = Skryj hasła
    .accesskey = H
logins-description-all = Na tym kōmputrze sōm schrōniōne dane logowanio do tych strōn
logins-description-filtered = Te dane logowanio sztimujōm z twojim szukaniym:
remove-all =
    .label = Skasuj wszyskie
    .accesskey = W
remove-all-shown =
    .label = Skasuj wszyskie pokozane
    .accesskey = W
remove-all-passwords-prompt = Na zicher chcesz skasować wszyskie hasła?
remove-all-passwords-title = Skasuj wszyskie hasła
no-master-password-prompt = Na zicher chcesz pokozać wszyskie hasła?
auto-fill-logins-and-passwords =
    .label = Autōmatycznie wkludzej dane logowanio i hasła
