# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SaveImageTitle = Tereka Ekifananyi
SaveVideoTitle = Tereka Vidiyo
SaveAudioTitle = Tereka Akatambi kamalobozzi
SaveLinkTitle = Tereka Nga
WebPageCompleteFilter = Omuko gwo'Lutimbe, guwedde
WebPageHTMLOnlyFilter = Omuko gwo'Lutimbe, HTML yokka
WebPageXHTMLOnlyFilter = Omuko gwo'Lutimbe, XHTML yokka
WebPageSVGOnlyFilter = Omuko gwo'Lutimbe, SVG gwokka
WebPageXMLOnlyFilter = Omuko gwo'Lutimbe, XML yokka
