# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = बे वेब बिलाइखौ गोदान जायगायाव फिन बिथोन होनाय जागासिनो दं। नोंथाङा गोदान जायगायाव टाइप खालामनाय फर्म डाटाखौ फिन दैथाय हरना लुबैयो नामा?
# Directory listing strings
DirTitle = %1$S नि नायखांफारि
DirGoUp = गोजौ लेभेल डिरेक्टरि सिम
ShowHidden = दोनखोमानाय बेसादखौ दिनथि
DirColName = मुं
DirColSize = महर
DirColMTime = जोबथा महर सोलायबाय
DirFileLabel = फाइल:
