# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = સાચવેલા લોગિન
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = URL ની નકલ
    .accesskey = y
launch-site-url-cmd =
    .label = URL પર જાઓ
    .accesskey = V
copy-username-cmd =
    .label = વપરાશકર્તાનામની નકલ કરો
    .accesskey = U
edit-username-cmd =
    .label = વપરાશકર્તાનામ સંપાદિત કરો
    .accesskey = d
copy-password-cmd =
    .label = પાસવર્ડની નકલ કરો
    .accesskey = C
edit-password-cmd =
    .label = પાસવર્ડ સંપાદિત કરો
    .accesskey = E
search-filter =
    .accesskey = S
    .placeholder = શોધો
column-heading-site =
    .label = સાઈટ
column-heading-username =
    .label = વપરાશકર્તા નામ
column-heading-password =
    .label = પાસવર્ડ
column-heading-time-created =
    .label = પ્રથમ વપરાયેલ
column-heading-time-last-used =
    .label = છેલ્લે વપરાયેલ
column-heading-time-password-changed =
    .label = છેલ્લે બદલાયેલ
column-heading-times-used =
    .label = વપરાયેલ સમય
remove =
    .label = દૂર કરો
    .accesskey = R
import =
    .label = આયાત કરો ...
    .accesskey = I
close-button =
    .label = બંધ કરો
    .accesskey = C
show-passwords =
    .label = પાસવર્ડો બતાવો
    .accesskey = P
hide-passwords =
    .label = પાસવર્ડો છુપાવો
    .accesskey = P
logins-description-all = નિચેની સાઇટ્સના લૉગિનો તમારા કમ્પ્યૂટર પર સંગ્રહિત છે
logins-description-filtered = નીચેના લૉગિનો તમારી શોધ સાથે મેળ ખાય છે:
remove-all =
    .label = બધુ દૂર કરો
    .accesskey = A
remove-all-shown =
    .label = બધુ બતાવેલુ દૂર કરો
    .accesskey = A
remove-all-passwords-prompt = શું તમે ખરેખર બધા પાસવર્ડો દૂર કરવા માંગો છો?
remove-all-passwords-title = બધા પાસવર્ડો દૂર કરો
no-master-password-prompt = શું તમે ખરેખર તમારા પાસવર્ડો બતાવવા માંગો છો?
auto-fill-logins-and-passwords =
    .label = ઑટોફિલ લૉગિન અને પાસવર્ડ્સ
