# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Dh'fhalbh an ùine air
openFile = Fosgail faidhle
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Lorg le %1$S airson “%2$S”
contextMenuSearch.accesskey = S
contextMenuPrivateSearch = Lorg am broinn uinneag phrìobhaideach
contextMenuPrivateSearch.accesskey = h
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Lorg le %S am broinn uinneag phrìobhaideach
contextMenuPrivateSearchOtherEngine.accesskey = h
bookmarkAllTabsDefault = [Ainm pasgain]
unsignedAddonsDisabled.message = Bha co-dhiù aon tuilleadan ann nach deach a dhearbhadh agus chaidh an cur à comas.
unsignedAddonsDisabled.learnMore.label = Barrachd fiosrachaidh
unsignedAddonsDisabled.learnMore.accesskey = r
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Chaidh inntrigeadh %S an turas mu dheireadh
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = Ceanglaichean %S://
crashedpluginsMessage.title = Thuislich am plugan %S.
crashedpluginsMessage.reloadButton.label = Ath-luchdaich an duilleag
crashedpluginsMessage.reloadButton.accesskey = t
crashedpluginsMessage.submitButton.label = Cuir a-steach aithisg tuislidh
crashedpluginsMessage.submitButton.accesskey = s
crashedpluginsMessage.learnMore = Tuilleadh eòlais…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = An robh thu an dùil tadhal air %S?
keywordURIFixup.goTo = Bha, nach stiùir sibh mi gu %S?
keywordURIFixup.goTo.accesskey = Y
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Ùraich gu %S
update.downloadAndInstallButton.accesskey = u
menuOpenAllInTabs.label = Fosgail gach duilleag ann an taba
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Ath-luchdaich an duilleag seo
tabHistory.goBack = Till dhan duilleag seo
tabHistory.goForward = Rach air adhart dhan duilleag seo
# URL Bar
pasteAndGo.label = Cuir ann ⁊ tadhail air
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Ath-luchdaich an duilleag làithreach (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Sguir de luchdadh na duilleige seo (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Ath-shuidhich ìre an t-sùm (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Toglaich sealladh an leughadair (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Seall na comharran-lìn agad (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Seall adhartas nan rudan a tha 'gan luchdadh a-nuas (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Fosgail uinneag ùr (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Fosgail taba ùr (%S)
newTabContainer.tooltip = Fosgail taba ùr (%S)\nBrùth is cùm sìos airson taba soithich ùr fhosgladh
newTabAlwaysContainer.tooltip = Tagh soitheach airson taba ùr fhosgladh
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = An doir thu cead dha %S airson dàta deilbh a’ chanabhais HTML5 agad a chleachdadh?
canvas.siteprompt2.warning = Dh’fhaoidte gun gabh a chleachdadh airson an coimpiutair agad aithneachadh.
canvas.block = Bac
canvas.block.accesskey = B
canvas.allow2 = Ceadaich
canvas.allow2.accesskey = a
canvas.remember2 = Cuimhnich an co-dhùnadh seo
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Dearbhte le: %S
identity.identified.verified_by_you = Chuir thu ris eisgeachd tèarainteachd airson na làraich seo.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Chaidh an teisteanas fhoillseachadh dha: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Neo-thèarainte
identity.notSecure.tooltip = Chan eil an ceangal tèarainte
identity.extension.label = Leudachan (%S)
identity.extension.tooltip = Air a luchdadh leis an leudachan %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Sùm a-mach (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Ath-shuidhich ìre an t-sùm (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Sùm a-steach (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Gearr (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Lethbhreac (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Cuir ann (%S)
geolocation.allow = Ceadaich
geolocation.allow.accesskey = a
geolocation.block = Bac
geolocation.block.accesskey = B
geolocation.shareWithSite4 = An doir thu cead air d’ ionad dha %S?
geolocation.shareWithFile4 = An doir thu cead air d’ ionad dhan fhaidhle ionadail seo?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = An doir thu cead dha %1$S gun doir e cead dha %2$S air d’ ionad?
geolocation.remember = Cuimhnich an co-dhùnadh seo
# Virtual Reality Device UI
xr.allow2 = Ceadaich
xr.allow2.accesskey = a
xr.block = Bac
xr.block.accesskey = B
xr.shareWithSite4 = An doir thu cead dha %S gun inntrig e uidheaman na fìorachd bhiortail? Dh’fhaoidte gun nochd seo fiosrachadh dìomhair.
xr.shareWithFile4 = An doir thu cead dhan fhaidhle ionadail seo gun inntrig e uidheaman na fìorachd bhiortail? Dh’fhaoidte gun nochd seo fiosrachadh dìomhair.
xr.remember = Cuimhnich an co-dhùnadh seo
# Persistent storage UI
persistentStorage.allow = Ceadaich
persistentStorage.allow.accesskey = A
persistentStorage.block.label = Bac
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = An doir thu cead dha %S dàta a chumail san stòras bhuan?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Ceadaich
webNotifications.allow2.accesskey = a
webNotifications.notNow = Cha doir an-dràsta
webNotifications.notNow.accesskey = n
webNotifications.never = Cha doir idir
webNotifications.never.accesskey = v
webNotifications.alwaysBlock = Bac an-còmhnaidh
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = Bac
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = An doir thu cead dha %S brathan a chur?
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = A-mach às an àite seo leam!
safebrowsing.getMeOutOfHereButton.accessKey = m
safebrowsing.deceptiveSite = Làrach ionnsaighe!
safebrowsing.notADeceptiveSiteButton.label = Chan e làrach foill a tha seo…
safebrowsing.notADeceptiveSiteButton.accessKey = f
safebrowsing.reportedAttackSite = Chaidh aithris gur e làrach ionnsaighe a tha seo!
safebrowsing.notAnAttackButton.label = Chan e làrach ionnsaighe a tha seo…
safebrowsing.notAnAttackButton.accessKey = a
safebrowsing.reportedUnwantedSite = Làrach a sgaoileas bathar-bog gun iarrtas!
safebrowsing.reportedHarmfulSite = Dèan aithris gur e làrach dochainneach a tha seo!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Lorg air %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = A bheil thu airson %S ath-thòiseachadh ann am modh fuasgladh dhuilgheadasan?
troubleshootModeRestartPromptMessage = Cuiridh sinn na leudachain, na h-ùrlaran ’s na roghainnean gnàthaichte agad à comas rè seal.
troubleshootModeRestartButton = Ath-thòisich
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Tha an duilleag seo a’ cur maille air %1$S. Airson am brabhsair agad a dhèanamh nas luaithe, cuir stad air an duilleag sin.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Tha duilleag-lìn a’ cur maille air %1$S. Airson am brabhsair agad a dhèanamh nas luaithe, cuir stad air an duilleag ud.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = Tha “%1$S” a’ cur maille air %2$S. Airson am brabhsair agad a dhèanamh nas luaithe, cuir stad air an duilleag ud.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = Tha “%1$S” a’ cur maille air %2$S. Airson am brabhsair agad a dhèanamh nas luaithe, cuir stad air an leudachan sin.
processHang.add-on.learn-more.text = Barrachd fiosrachaidh
processHang.button_stop2.label = Cuir stad air
processHang.button_stop2.accessKey = s
processHang.button_debug.label = Dì-bhugaich an sgriobt
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Seall an uinneag air an làn-sgrìn (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Gluais am bàr-taoibh gun taobh chlì
sidebar.moveToRight = Gluais am bàr-taoibh gun taobh deas
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Feumaidh tu DRM a chur an comas gus cuid dhen fhuaim no video air an duilleag seo a chluich.
emeNotifications.drmContentDisabled.button.label = Cuir DRE an comas
emeNotifications.drmContentDisabled.button.accesskey = E
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = Tha %S a' stàladh co-phàirtean air a bheil feum gus an fhuaim no video air an duilleag seo a chluich. Feuch ris a-rithist an ceann greis.
emeNotifications.unknownDRMSoftware = Neo-aithnichte
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Gnàthaich %S
decoder.noCodecs.button = Barrachd fiosrachaidh
decoder.noCodecs.accesskey = L
decoder.noCodecsLinux.message = Feumaidh tu na video codecs air a bheil feum a stàladh mus urrainn dhut video a chluich.
decoder.noHWAcceleration.message = Feumaidh tu am Media Feature Pack aig Microsoft a stàladh airson piseach a chur air a’ video.
decoder.noPulseAudio.message = Feumaidh tu am bathar-bog PulseAudio air a bheil feum a stàladh mus urrainn dhut fuaim a chluich.
decoder.unsupportedLibavcodec.message = Dh’fhaoidte gum bi libavcodec so-mhillidh no nach eil taic ris agus gu bheil feum air ùrachadh mus urrainn dhut video a chluich.
decoder.decodeError.message = Thachair mearachd rè dì-chòdachadh goireas a’ mheadhain.
decoder.decodeError.button = Dèan aithris air duilgheadas leis an làrach
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = Thachair mearachd rè dì-chòdachadh goireas a’ mheadhain ach is urrainn dhuinn aiseag a dhèanamh.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Feumaidh tu clàradh a-steach dhan lìonra seo mus fhaigh thu cothrom air an eadar-lìon.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Fosgail an duilleag airson clàradh a-steach do lìonra
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Ceadan airson %S
permissions.remove.tooltip = Falamhaich an cead seo ’s faighnich a-rithist
permissions.fullscreen.promptCanceled = Chaidh sgur de dh’iarrtas air cead: cha bu chòir iarrtas air cead a dhèanamh ro dhol a-steach air DOM làn-sgrìn.
permissions.fullscreen.fullScreenCanceled = Chaidh DOM làn-sgrìn fhàgail: cha bu chòir iarrtas air cead a dhèanamh fhad ’s a bhios sinn ann an DOM làn-sgrìn.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bit
aboutDialog.architecture.thirtyTwoBit = 32-bit
midi.allow.label = Ceadaich
midi.allow.accesskey = a
midi.block.label = Bac
midi.block.accesskey = B
midi.remember = Cuimhnich an co-dhùnadh seo
midi.shareWithFile = An doir thu cead dhan fhaidhle ionadail seo air na h-uidheaman MIDI agad?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = An doir thu cead air na h-uidheaman MIDI agad dha %S?
midi.shareSysexWithFile = An doir thu cothrom air na h-uidheaman MIDI dhan fhaidhle ionadail seo agus cead teachdaireachdan SysEx a chur is fhaighinn?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = An doir thu cothrom air na h-uidheaman MIDI dha %S agus cead teachdaireachdan SysEx a chur is fhaighinn?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Air ais
storageAccess1.Allow.label = Ceadaich
storageAccess1.Allow.accesskey = A
storageAccess1.DontAllow.label = Bac
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = A bheil thu airson leigeil le %1$S na briosgaidean aice a chleachadh air %2$S?
storageAccess1.hintText = Dh’fhaoidte gum b’ fheàirrde dhut an t-inntrigeadh a bhacadh mur eil thu cinnteach carson a dh’fheumas %1$S an dàta seo.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Lorg “%S” air an lìon
