# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

#define MOZ_LANGPACK_CREATOR Netscape.com

# If non-English locales wish to credit multiple contributors, uncomment this

# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>அருண்பிரகாஷ்</em:contributor> <em:contributor>தங்கமணி அருண்</em:contributor> <em:contributor>ஜெயா குமார்</em:contributor> <em:contributor>இளந்தமிழ்</em:contributor> <em:contributor>வீரா குமார்</em:contributor>

#unfilter emptyLines
