# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Gushakisha { $host }...
network-connection-status-connected = Yinjizwe mu { $host }...
network-connection-status-sending-request = Kohereza ibisabwa kuri { $host }...
network-connection-status-transferring-data = Kohereza ibyatanzwe bivuye kuri { $host }...
network-connection-status-connecting = Kwinjira muri { $host }...
network-connection-status-read = Gusoma { $host }...
network-connection-status-wrote = Yanditse { $host }...
network-connection-status-waiting = Itegereje { $host }...
