# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

e2e-intro-description = Para enviar mensagens encriptadas ou assinadas digitalmente, tem de configurar uma tecnologia de encriptação, OpenPGP ou S/MIME.
e2e-intro-description-more = Selecione a sua chave pessoal para ativar a utilização do OpenPGP, ou o seu certificado pessoal para ativar a utilização do S/MIME. Para uma chave ou certificado pessoal, você possui a respetiva chave secreta.
openpgp-key-user-id-label = Conta / ID do utilizador
openpgp-keygen-title-label =
    .title = Gerar chave OpenPGP
openpgp-cancel-key =
    .label = Cancelar
    .tooltiptext = Cancelar geração da chave
openpgp-key-gen-expiry-title =
    .label = Validade da chave
openpgp-key-gen-expire-label = A chave expira em
openpgp-key-gen-days-label =
    .label = dias
openpgp-key-gen-months-label =
    .label = meses
openpgp-key-gen-years-label =
    .label = anos
openpgp-key-gen-no-expiry-label =
    .label = A chave não expira
openpgp-key-gen-key-size-label = Tamanho da chave
openpgp-key-gen-console-label = Geração da chave
openpgp-key-gen-key-type-label = Tipo de chave
openpgp-key-gen-key-type-rsa =
    .label = RSA
openpgp-key-gen-key-type-ecc =
    .label = ECC (curva elíptica)
openpgp-generate-key =
    .label = Gerar chave
    .tooltiptext = Gera uma nova chave compatível com o OpenPGP para encriptação e/ou assinatura
openpgp-advanced-prefs-button-label =
    .label = Avançado…
openpgp-keygen-desc = <a data-l10n-name="openpgp-keygen-desc-link">Nota: A geração da chave pode demorar vários minutos para ser concluída.</a> Não saia da aplicação enquanto a geração da chave estiver em curso. Navegar ativamente ou realizar operações com uma utilização intensiva do disco durante a geração da chave irá reabastecer a 'fonte de aleatoriedade' e acelerar o processo. Será alertado quando a geração da chave for concluída.
openpgp-key-expiry-label =
    .label = Validade
openpgp-key-id-label =
    .label = ID da chave
openpgp-cannot-change-expiry = Esta é uma chave com uma estrutura complexa. Não é possível alterar a respetiva data de validade.
openpgp-key-man-title =
    .title = Gestor de chaves OpenPGP
openpgp-key-man-generate =
    .label = Novo par de chaves
    .accesskey = v
openpgp-key-man-gen-revoke =
    .label = Certificado de revogação
    .accesskey = r
openpgp-key-man-ctx-gen-revoke-label =
    .label = Gerar e guardar certificado de revogação
openpgp-key-man-file-menu =
    .label = Ficheiro
    .accesskey = F
openpgp-key-man-edit-menu =
    .label = Editar
    .accesskey = E
openpgp-key-man-view-menu =
    .label = Ver
    .accesskey = V
openpgp-key-man-generate-menu =
    .label = Gerar
    .accesskey = G
openpgp-key-man-keyserver-menu =
    .label = Servidor de chaves
    .accesskey = v
openpgp-key-man-import-public-from-file =
    .label = Importar chave(s) pública(s) do ficheiro
    .accesskey = I
openpgp-key-man-import-secret-from-file =
    .label = Importar chave(s) secreta(s) do ficheiro
openpgp-key-man-import-sig-from-file =
    .label = Importar revogações do ficheiro
openpgp-key-man-import-from-clipbrd =
    .label = Importar chave(s) da área de transferência
    .accesskey = I
openpgp-key-man-import-from-url =
    .label = Importar chave(s) do endereço
    .accesskey = d
openpgp-key-man-export-to-file =
    .label = Exportar chave(s) pública(s) para um ficheiro
    .accesskey = E
openpgp-key-man-send-keys =
    .label = Enviar chave(s) pública(s) por e-mail
    .accesskey = v
openpgp-key-man-backup-secret-keys =
    .label = Fazer uma cópia da(s) chave(s) secreta(s) para um ficheiro
    .accesskey = p
openpgp-key-man-discover-cmd =
    .label = Descobrir chaves na Internet
    .accesskey = D
openpgp-key-man-discover-prompt = Para descobrir chaves OpenPGP na Internet, em servidores de chaves ou utilizando o protocolo WKD, insira um endereço de e-mail ou um ID de chave.
openpgp-key-man-discover-progress = A procurar…
openpgp-key-copy-key =
    .label = Copiar chave pública
    .accesskey = C
openpgp-key-export-key =
    .label = Exportar chave pública para um ficheiro
    .accesskey = E
openpgp-key-backup-key =
    .label = Fazer uma cópia da chave secreta para um ficheiro
    .accesskey = p
openpgp-key-send-key =
    .label = Enviar chave pública por e-mail
    .accesskey = v
openpgp-key-man-copy-to-clipbrd =
    .label = Copiar chave(s) pública(s) para a área de transferência
    .accesskey = C
openpgp-key-man-ctx-expor-to-file-label =
    .label = Exportar chaves para um ficheiro
openpgp-key-man-ctx-copy-to-clipbrd-label =
    .label = Copiar chaves públicas para a área de transferência
openpgp-key-man-close =
    .label = Fechar
openpgp-key-man-reload =
    .label = Recarregar cache de chaves
    .accesskey = R
openpgp-key-man-change-expiry =
    .label = Alterar data de validade
    .accesskey = e
openpgp-key-man-del-key =
    .label = Eliminar chave(s)
    .accesskey = h
openpgp-delete-key =
    .label = Eliminar chave
    .accesskey = m
openpgp-key-man-revoke-key =
    .label = Revogar chave
    .accesskey = R
openpgp-key-man-key-props =
    .label = Propriedades da chave
    .accesskey = h
openpgp-key-man-key-more =
    .label = Mais
    .accesskey = M
openpgp-key-man-view-photo =
    .label = ID da fotografia
    .accesskey = f
openpgp-key-man-ctx-view-photo-label =
    .label = Ver ID da fotografia
openpgp-key-man-show-invalid-keys =
    .label = Mostrar chaves inválidas
    .accesskey = v
openpgp-key-man-show-others-keys =
    .label = Mostrar chaves de outras pessoas
    .accesskey = o
openpgp-key-man-user-id-label =
    .label = Nome
openpgp-key-man-fingerprint-label =
    .label = Identificador digital
openpgp-key-man-select-all =
    .label = Selecionar todas as chaves
    .accesskey = a
openpgp-key-man-empty-tree-tooltip =
    .label = Insira os termos de pesquisa na caixa acima
openpgp-key-man-nothing-found-tooltip =
    .label = Nenhuma chave corresponde aos seus termos de pesquisa
openpgp-key-man-please-wait-tooltip =
    .label = Aguarde enquanto as chaves estão a ser carregadas...
openpgp-key-man-filter-label =
    .placeholder = Pesquisar por chaves
openpgp-key-man-select-all-key =
    .key = T
openpgp-key-man-key-details-key =
    .key = l
openpgp-key-details-title =
    .title = Propriedades da chave
openpgp-key-details-signatures-tab =
    .label = Certificações
openpgp-key-details-structure-tab =
    .label = Estrutura

## e2e encryption settings


## OpenPGP Key selection area


## Account settings export output

