# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = ਕੀ ਤੁਸੀਂ "%S" ਤੇ ਹੇਠ ਦਿੱਤੇ ਮਕਸਦ ਲਈ ਭਰੋਸਾ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?
unnamedCA = ਸਰਟੀਫਿਕੇਟ ਅਥਾਰਟੀ (ਬੇਨਾਮ)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = ਪਾਸਵਰਡ ਦਿਓ, ਜਿਸ ਨੂੰ ਇਹ ਸਰਟੀਫਿਕੇਟ ਬੈਕਅੱਪ ਨੂੰ ਇੰਕ੍ਰਿਪਟ ਕਰਨ ਲਈ ਵਰਤਿਆ ਗਿਆ ਸੀ:
# Page Info
pageInfo_NoEncryption = ਕੁਨੈਕਸ਼ਨ ਇਕ੍ਰਿਪਟਡ ਨਹੀਂ ਹੈ।
pageInfo_Privacy_None1 = ਵੈੱਬ ਸਾਇਟ %S ਸਫਾ, ਜੋ ਕਿ ਤੁਸੀਂ ਵੇਖ ਰਹੇ ਹੋ, ਲਈ ਇਕ੍ਰਿਪਸ਼ਨ ਲਈ ਸਹਿਯੋਗੀ ਨਹੀਂ ਹੈ।
pageInfo_Privacy_None2 = ਇੰਟਰਨੈਟ ਤੇ ਇਕ੍ਰਿਪਸ਼ਨ ਤੋਂ ਭੇਜੀ ਜਾਣਕਾਰੀ ਨੂੰ ਹੋਰ ਵਿਅਕਤੀ ਸੰਚਾਰ ਵੇਖ ਸਕਦੇ ਹਨ।
pageInfo_Privacy_None4 = ਤੁਹਾਡੇ ਵਲੋਂ ਵੇਖਿਆ ਜਾ ਰਿਹਾ ਸਫ਼ਾ ਇੰਟਰਨੈੱਟ ਉੱਤੇ ਭੇਜਣ ਤੋਂ ਪਹਿਲਾਂ ਇੰਕ੍ਰਿਪਟ ਨਹੀਂ ਕੀਤਾ ਗਿਆ ਸੀ।
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = ਕਨੈਕਸ਼ਨ ਇੰਕ੍ਰਿਪਟ ਕੀਤਾ (%1$S, %2$S ਬਿੱਟ ਕੁੰਜੀਆਂ, %3$S)
pageInfo_BrokenEncryption = ਖ਼ਰਾਬ ਇੰਕ੍ਰਿਪਸ਼ਨ (%1$S, %2$S ਬਿੱਟ ਕੁੰਜੀਆਂ, %3$S)
pageInfo_Privacy_Encrypted1 = ਸਫਾ, ਜਿਸ ਨੂੰ ਤੁਸੀਂ ਵੇਖ ਰਹੇ ਹੋ, ਇੰਟਰਨੈੱਟ ਉੱਪਰ ਭੇਜਣ ਤੋਂ ਪਹਿਲਾਂ ਇੰਕ੍ਰਿਪਟਡ ਕੀਤਾ ਗਿਆ ਹੈ।
pageInfo_Privacy_Encrypted2 = ਇਕ੍ਰਿਪਸ਼ਨ ਨਾ-ਪ੍ਰਮਾਣਿਤ ਵਿਅਕਤੀਆਂ ਨੂੰ ਕੰਪਿਊਟਰਾਂ ਵਿੱਚ ਭੇਜੀ ਜਾਣ ਵਾਲੀ ਜਾਣਕਾਰੀ ਨੂੰ ਵੇਖਣਾ ਅਸੰਭਵ ਬਣਾ ਦਿੰਦੀ ਹੈ। ਇਸਕਰਕੇ ਇਸ ਦੀ ਸੰਭਵਨਾ ਬਹੁਤ ਘੱਟ ਹੈ ਕਿ ਨੈੱਟਵਰਕਾਂ ਵਿੱਚ ਭੇਜਣ ਦੌਰਾਨ ਕੋਈ ਇਸ ਸਫੇ ਨੂੰ ਪੜ ਸਕੇ।
pageInfo_MixedContent = ਕਨੈਕਸ਼ਨ ਅਧੂਰਾ ਇੰਕ੍ਰਿਪਟਡ ਹੈ
pageInfo_MixedContent2 = ਸਫ਼ੇ ਦੇ ਹਿੱਸੇ, ਜੋ ਕਿ ਤੁਸੀਂ ਵੇਖ ਰਹੇ ਹੋ, ਇੰਟਰਨੈੱਟ ਉੱਤੇ ਭੇਜਣ ਤੋਂ ਪਹਿਲਾਂ ਇੰਕ੍ਰਿਪਟ ਨਹੀਂ ਹਨ
pageInfo_WeakCipher = ਇਸ ਵੈੱਬਸਾਈਟ ਨਾਲ ਤੁਹਾਡਾ ਕਨੈਕਸ਼ਨ ਕਮਜ਼ੋਰ ਇੰਕ੍ਰਿਪਨ ਵਰਤਦਾ ਹੈ ਅਤੇ ਪ੍ਰਾਈਵੇਟ ਨਹੀਂ ਹੈ। ਤੁਹਾਡੇ ਵਲੋਂ ਦਿੱਤੀ ਜਾਣਕਾਰੀ ਨੂੰ ਹੋਰ ਲੋਕ ਵੇਖ ਸਕਦੇ ਹਨ ਜਾਂ ਵੈੱਬਸਾਈਟ ਦੇ ਰਵੱਈਏ ਨੂੰ ਸੋਧਿਆ ਜਾ ਸਕਦਾ ਹੈ।
pageInfo_CertificateTransparency_Compliant = ਇਹ ਵੈੱਬਸਾਈਟ ਸਰਟੀਫਿਕੇਟ ਟਰਾਂਸਪਰੇਸੀ ਪਾਲਸੀ ਦੇ ਅਨੁਕੂਲ ਹੈ।
# Token Manager
password_not_set = (ਸੈੱਟ ਨਹੀਂ)
