# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

# Roles
menubar = نوار نومگه
scrollbar = نوار اسکرۊل
grip = گرؽڌن
alert = هوشدار
menupopup = نومگه گۊشیڌنی
document = سند
pane = چارچۊ
dialog = موهاوره
separator = سوا ساز
toolbar = نوار ٱوزار
statusbar = نوار وزعیت
table = جدول
columnheader = سر سۊتۊن
rowheader = عونوان ستر
column = سۊتۊن
row = ستر
cell = هووه
link = لینگ
list = نومگه
listitem = موورد نومگه
outline = اوتلاین
outlineitem = مووردا کولی
pagetab = بلگه
propertypage = بلگه خۊسۊسیات
graphic = گرافیک
switch = آلشت
pushbutton = دویمه
checkbutton = دویمه پسند
radiobutton = دویمه رادیۊوی
combobox = جئوه کشاری
progressbar = نوار پؽشرفت
slider = اسلایدر
spinbutton = دویمه لر خردنی
diagram = نمۊدار
animation = پۊیا نمایی
equation = موعادله
buttonmenu = دویمه نومگه
whitespace = فاسله اسبؽڌ
pagetablist = نومگه بلگه یل
canvas = بۊم
checkmenuitem = پسند موورد نومگه
passwordtext = هؽل رزم
radiomenuitem = موورد نومگه رادیۊوی
textcontainer = کادر هؽل
togglebutton = دویمه سۊویچی
treetable = جدول داری
header = سر بلگ
footer = پاورقی
paragraph = پاراگراف
entry = وۊرۊدی
caption = عونوان
heading = سر فسل
section = بشن
form = فورم
comboboxlist = نومگه گۊشیڌنی
comboboxoption = سامووا نومگه گۊشیڌنی
imagemap = نشقه شؽوات
listboxoption = گۊزینه
listbox = جئوه نومگه
flatequation = موعادله قوتبی
gridcell = هووه-هووه
note = ویرداشت
figure = شلگ
definitionlist = نومگه تعریفا
term = استلا
definition = تعریف
mathmltable = جدول ریازی
mathmlcell = هووه
mathmlenclosed = بسته وابیڌه
mathmlfraction = کسر
mathmlfractionwithoutbar = کسر بؽ نوار
mathmlroot = ریشه
mathmlscripted = کود‌نویسی وابیڌه
mathmlsquareroot = ریشه دویوم
# More sophisticated roles which are not actual numeric roles
textarea = ناهیه هؽل
base = پایه
close-fence = دیواره‌ بسته
denominator = مخرج
numerator = سۊرت کسر
open-fence = دیواره واز
overscript = ری نیویسی
presubscript = پؽش هؽل
presuperscript = پؽش هؽل
root-index = پوروفایل ریشه
subscript = لم نویس
superscript = روء نویس
underscript = لم نویس
# More sophisticated object descriptions
headingLevel = درجهٔ سر ٱووڌن %S
# Landmark announcements
banner = بنر
complementary = موکمل
contentinfo = دووسمندیا موئتوا
main = ٱسلی
navigation = ناوبری
search = پیتینیڌن
region = وولات
# Object states
stateRequired = وا الن بۊوس
