# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

# Roles
menubar = نوار نومگه
grip = گرؽڌن
alert = هوشدار
document = سند
table = جدول
columnheader = سر سۊتۊن
column = سۊتۊن
cell = هووه
link = لینگ
list = نومگه
listitem = موورد نومگه
pagetab = بلگه
graphic = گرافیک
switch = آلشت
pushbutton = دویمه
checkbutton = دویمه پسند
spinbutton = دویمه لر خردنی
diagram = نمۊدار
animation = پۊیا نمایی
equation = موعادله
buttonmenu = دویمه نومگه
whitespace = فاسله اسبؽڌ
pagetablist = نومگه بلگه یل
canvas = بۊم
checkmenuitem = پسند موورد نومگه
passwordtext = هؽل رزم
radiomenuitem = موورد نومگه رادیۊوی
textcontainer = کادر هؽل
togglebutton = دویمه سۊویچی
treetable = جدول داری
header = سر بلگ
footer = پاورقی
paragraph = پاراگراف
entry = وۊرۊدی
caption = عونوان
heading = سر فسل
section = بشن
form = فورم
comboboxlist = نومگه گۊشیڌنی
comboboxoption = سامووا نومگه گۊشیڌنی
imagemap = نشقه شؽوات
listboxoption = گۊزینه
listbox = جئوه نومگه
flatequation = موعادله قوتبی
gridcell = هووه-هووه
note = ویرداشت
figure = شلگ
definitionlist = نومگه تعریفا
term = استلا
definition = تعریف
mathmltable = جدول ریازی
mathmlcell = هووه
