# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

# Roles
menubar = نوار نومگه
grip = گرؽڌن
alert = هوشدار
document = سند
table = جدول
columnheader = سر سۊتۊن
column = سۊتۊن
cell = هووه
link = لینگ
list = نومگه
listitem = موورد نومگه
pagetab = بلگه
graphic = گرافیک
switch = آلشت
pushbutton = دویمه
checkbutton = دویمه پسند
note = ویرداشت
