# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=$ProductName$-installatie
Welcome_MessageWelcome=Welkom bij %s
Welcome_Message0=U staat op het punt %s te installeren.
Welcome_Message1=Het wordt sterk aanbevolen alle Windows-programma’s af te sluiten alvorens dit installatieprogramma uit te voeren.
Welcome_Message2=Klik op Annuleren om de installatie te beëindigen en sluit vervolgens alle actieve programma's.  Klik op Volgende om het installatieprogramma voort te zetten.
Welcome_Message3=Klik op Volgende om %s te installeren.

License_Title=Softwarelicentieovereenkomst
License_SubTitle=Voorwaarden en condities voor het gebruik van deze software.
License_Message0=Lees alstublieft de volgende licentieovereenkomst. Gebruik de scrollbalk om de rest van deze overeenkomst te bekijken.
License_Accept=Ik &accepteer de voorwaarden van de licentieovereenkomst
License_Decline=Ik accepteer de voorwaarden van de licentieovereenkomst &NIET

Type_Title=Installatietype
Type_SubTitle=Installatiemethode kiezen.
Type_Message0=Kies het gewenste installatietype en klik daarna op Volgende.

Standard_Short=&Standaard
Standard_Long=Thunderbird zal worden geïnstalleerd met de meest gebruikelijke onderdelen.

Custom_Short=&Aangepast
Custom_Long=U kunt kiezen welke onderdelen worden geïnstalleerd. Aanbevolen voor ervaren gebruikers.

Select_Title=Onderdelen selecteren
Select_SubTitle=Extra onderdelen die $ProductName$ uitbreiden.
Select_Message0=Kies extra onderdelen die u wilt installeren en klik daarna op Volgende.

Path_Title=Installatiemap
Path_SubTitle=Waar $ProductName$ zal worden geïnstalleerd.
Path_Message0=$ProductName$ zal worden geïnstalleerd in de volgende map:

Integration_Title=Snelkoppelingen instellen
Integration_SubTitle=Creëert pictogrammen.
Integration_Message0=Creëer pictogrammen voor $ProductShortName$:

Integration_Desktop=Op mijn bureaublad
Integration_StartMenu=In mijn map Programma’s van het menu Start
Integration_QuickLaunch=In mijn Snel Starten-werkbalk

SelectFolder_Title=$ProductName$-installatie - Programmamap selecteren
SelectFolder_Message0=Het installatieprogramma zal pictogrammen aan de onderstaande programmamap toevoegen.  U kunt een nieuwe mapnaam intypen of een van de bestaande mappen kiezen.  Klik op Volgende om verder te gaan.

Advanced_Title=$ProductName$-installatie - Geavanceerde instellingen
Advanced_Message0=Als uw internetverbinding een proxyserver vereist, voer dan uw servernaam en poortinformatie in.  Als uw internetverbinding geen proxyserver vereist, laat dan de velden leeg.

Install_Title=Samenvatting
Install_SubTitle=Klaar om te starten met het installeren van $ProductName$.
Install_MessageInstall=Het installatieprogramma zal nu de volgende onderdelen installeren:
Install_MessageDownload=Het installatieprogramma zal nu de volgende onderdelen downloaden en installeren:
Install_Message0=Klik op Volgende om verder te gaan.

Downloading_Title=Downloaden
Downloading_SubTitle=Downloaden van vereiste onderdelen...
Downloading_Blurb=Het installatieprogramma downloadt de benodigde bestanden voor de installatie van $ProductName$.
Downloading_FileName=Nu downloaden:
Downloading_Time=Resterende tijd:

Installing_Title=Installeren
Installing_SubTitle=Installeren van $ProductName$...
Installing_Blurb=Het installatieprogramma installeert de benodigde programmabestanden. 
Installing_Status=Voorbereiden van:
Installing_Component=Nu installeren:

Success_Title=Installatie voltooid
Success_Header=Installatie voltooid
Success_Message0=%s is succesvol geïnstalleerd.
Success_Message1=Klik op Voltooien om het installatieprogramma af te sluiten. 
Success_Launch=%s nu opstarten.

Check_Message=Het downloaden van $ProductName$ is geslaagd. $ProductNameInternal$ moet worden afgesloten om de installatie te kunnen vervolgen. Klik op OK om $ProductNameInternal$ automatisch af te sluiten en de installatie te beginnen.
Check_FullMessage=$ProductNameInternal$ moet worden afgesloten om de installatie te kunnen vervolgen. Klik op OK om $ProductNameInternal$ automatisch af te sluiten en de installatie te beginnen.
Check_Wait=Bezig $ProductNameInternal$ af te sluiten.  Even wachten...

Component_XPCOM=Platformonafhankelijke COM
Component_Mail=$ProductName$
Component_Offline=Offlineondersteuning
Component_Offline_Long=Voegt offlineondersteuning toe aan $ProductName$ E-mail.
Component_RSS=RSS-ondersteuning
Component_RSS_Long=Voegt RSS-ondersteuning toe aan $ProductName$.
Component_QFA=Quality Feedback Agent
Component_QFA_Long=voor het rapporteren van $ProductName$ crash-informatie
