# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=Umiselo lwe-$ProductName$
Welcome_MessageWelcome=Wamkelekile kwi-%s!
Welcome_Message0=You are about to install %s 2 Alpha 1.
Welcome_Message1=Kucetyiswa kakhulu ukuba uphume kuzo zonke iinkqubo ze-Windows phambi kokuqhubela phambili le nkqubo Yokumisela.
Welcome_Message2=Nqomfa ku-Rhoxisa ukuze uyeke Kumiselo wandule ukuvala naziphi iinkqubo obuziqhuba.  Nqomfa ku-Okulandelayo ukuze uqhubele phambili ngenkqubo Yokumisela.
Welcome_Message3=Click Next to continue installing %s 2 Alpha 1.

License_Title=Imvumelwano Yelayisensi Yenkqubo
License_SubTitle=Imigqaliselo neemeko zokusebenzisa le nkqubo.
License_Message0=Nceda funda imvumelwano elandelayo yelayisensi. Sebenzisa isixwexwe sokwehlisa usenyusa ukuze ujonge le mvumelwano iphelele.
License_Accept=Ndi&yayamkela imigqaliselo Yemvumelwano Yelayisensi
License_Decline=&Andiyamkeli imigqaliselo Yemvumelwano Yelayisensi

Type_Title=Isimbo Somiselo
Type_SubTitle=Khetha ekunokukhethwa kuko kokumisela.
Type_Message0=Khetha isimbo Sokumisela osithandayo, uze unqomfe ku-Okulandelayo.

Standard_Short=&Eqhelekileyo
Standard_Long=I-Thunderbird iya kuhlohlwa ngamanqaku ekunokukhethwa kuwo angawona axhaphakileyo.

Custom_Short=&Lungiselela
Custom_Long=Unako ukukhetha amanqaku ngamanye ekunokukhethwa kuwo ukuba ahlohlwe. Kucetyiswa ngakumbi kubasebenzisi abanamava.

Select_Title=Khetha Iinxalenye
Select_SubTitle=Iinxalenye ezifakelweyo ezomeleza i-$ProductName$.
Select_Message0=Khetha iinxalenye ezifakelwayo ofuna ukuzihlohla, uze unqomfe ku-Okulandelayo.

Path_Title=Hlohla Isiqulathi Seefayili
Path_SubTitle=Apho i-$ProductName$ iya kuhlohlwa khona.
Path_Message0=I-$ProductName$ iya kuhlohlwa kwisiqulathi seefayili esilandelayo:

Integration_Title=Iindlela Ezinqumlayo Zokumisela
Integration_SubTitle=Kuyilwa Imiqondiso Yokuqulathiweyo Yenkqubo
Integration_Message0=Yila imiqondiso yokuqulathiweyo ye-$ProductShortName$:

Integration_Desktop=Kulwazi lwam Oluseskrinini
Integration_StartMenu=Kwisiqulathi seefayili zam Zeenkqubo Zeemenyu Zokuqalisa
Integration_QuickLaunch=Kwisixwexwe sam Sokundulula Esikhawulezayo

SelectFolder_Title=Umiselo lwe-$ProductName$ - Khetha Isiqulathi Seefayili Zenkqubo
SelectFolder_Message0=Umiselo luya kufakela imiqondiso yokuqulathiweyo yenkqubo Kwisiqulathi Seefayili Zeenkqubo ezidweliswe ngezantsi.  Usenokuchwetheza igama elitsha lesiqulathi seefayili, okanye ukhethe libe linye kuludwe Olukhoyo Lweziqulathi Zeefayili.  Nqomfa ku-Okulandelayo ukuze uqhube.

Advanced_Title=Umiselo lwe-$ProductName$ - Imimiselo Yenqanaba Eliphezulu
Advanced_Message0=Ukuba umdibaniso wakho Wonxibelelwano ufuna iseva engummeli, ngenisa igama leseva yakho kunye nolwazi lwesiqhagamshelanisi.  Ukuba umdibaniso wakho Wonxibelelwano awufuni seva engummeli, shiya imimandla ingenanto.

Install_Title=Isishwankathelo
Install_SubTitle=Sekulungelwe ukuqalisa ngokuhlohla i-$ProductName$.
Install_MessageInstall=Umiselo ngoku luza kuhlohla iinxalenye ezilandelayo:
Install_MessageDownload=Umiselo ngoku luya kuthoba umthwalo ukuze luhlohle iinxalenye ezilandelayo:
Install_Message0=Nqomfa ku-Okulandelayo ukuze uqhube.

Downloading_Title=Kuthotywa umthwalo
Downloading_SubTitle=Kuthotywa umthwalo weenxalenye ezifunekayo...
Downloading_Blurb=Umiselo luthoba umthwalo weefayili ezifunekayo ukuze kuhlohlwe i-$ProductName$.
Downloading_FileName=Okwangoku Kuthotywa Umthwalo:
Downloading_Time=Ixesha Eliseleyo:

Installing_Title=Kuyahlohlwa
Installing_SubTitle=Kuhlohlwa i-$ProductName$...
Installing_Blurb=Umiselo luhlohla iifayili zenkqubo.
Installing_Status=Kulungiswa Ifayili:
Installing_Component=Okwangoku Kuyahlohlwa:

Success_Title=Ukuhlohla Kugqityiwe
Success_Header=Ukuhlohla Kugqityiwe
Success_Message0=I-%s ihlohlwe ngempumelelo.
Success_Message1=Nqomfa ku-Kugqityiwe ukugqibezela Umiselo.
Success_Launch=Ndulula i-%s ngoku.

Check_Message=Ukuthotywa kwe-$ProductName$ kube yimpumelelo. I-$ProductNameInternal$ mayivalwe ukuze kuqhutywe ngokuhlohla. Nqomfa ku-Kulungile ukuze uphume kwi-$ProductNameInternal$ ngokuzenzekela nokuze uqale ngokuhlohla.
Check_FullMessage=I-$ProductNameInternal$ mayivalwe ukuze kuqhutywe ngokuhlohla. Nqomfa ku-Kulungile ukuze uphume kwi-$ProductNameInternal$ ngokuzenzekela nokuze uqale ngokuhlohla.
Check_Wait=Kuvalwa i-$ProductNameInternal$.  Nceda linda...

Component_XPCOM=Nqumla Udweliso Lwenkqubo ye-COM
Component_Mail=$ProductName$
Component_Offline=Inkxaso Ayikho Kwimo yokusebenza
Component_Offline_Long=Kufakelwa inkxaso Engekho Kwimo Yokusebenza kwiMeyile ye-$ProductName$.
Component_RSS=Inkxaso ye-RSS
Component_RSS_Long=Kufakelwa inkxaso ye-RSS kwi-$ProductName$.
Component_QFA=Umphumezi Wengxelo Yomgangatho
Component_QFA_Long=ukwenzela ukunika ingxelo ngolwazi olonakeleyo lwe-$ProductName$
