# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loginsDescriptionAll2 = Innskráningar fyrir eftirfarandi vefsvæði eru geymdar á tölvunni
# LOCALIZATION NOTE (useASecurelyGeneratedPassword):
# Shown in the autocomplete popup to allow filling a generated password into a password field.
useASecurelyGeneratedPassword = Nota öruggt útbúið lykilorð
# LOCALIZATION NOTE (generatedPasswordWillBeSaved):
# %S will contain the brandShorterName. This informs the user that the generated password will be automatically saved.
generatedPasswordWillBeSaved = %S mun vista þetta lykilorð fyrir þetta vefsvæði.
# LOCALIZATION NOTE (loginHostAge):
# This is used to show the context menu login items with their age.
# 1st string is the username for the login, 2nd is the login's age.
loginHostAge = %1$S (%2$S)
# LOCALIZATION NOTE (noUsername):
# String is used on the context menu when a login doesn't have a username.
noUsername = Ekkert notandanafn
# LOCALIZATION NOTE (displaySameOrigin):
# String is used on the autocomplete row when the login origin is a domain match with the document origin
displaySameOrigin = Af þessu vefsvæði
# LOCALIZATION NOTE (insecureFieldWarningDescription2):
# %1$S will contain insecureFieldWarningLearnMore and look like a link to indicate that clicking will open a tab with support information.
insecureFieldWarningDescription2 = Þessi tenging er ekki örugg. Öllum gögnum sem er slegið hér inn eru óörugg. %1$S
insecureFieldWarningLearnMore = Lesa meira
# LOCALIZATION NOTE (managePasswords.label):
# This label is used in the footer of login autocomplete menus.
managePasswords.label = Sýsla með lykilorð
