# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Assistente de importação
import-from-bookmarks = Importar marcadores de:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-nothing =
    .label = Não importar nada
    .accesskey = d
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = x
import-from-360se =
    .label = 360 Secure Browser
    .accesskey = 3
no-migration-sources = Não foram encontrados programas que contenham marcadores, histórico ou palavras-passe.
import-source =
    .label = Importar definições e dados
import-items-title =
    .label = Itens a importar
import-items-description = Selecione os itens a importar:
import-migrating-title =
    .label = A importar…
import-migrating-description = Os seguintes itens estão atualmente a ser importados…
import-select-profile-title =
    .label = Selecionar perfil
import-select-profile-description = Os seguintes perfis estão disponíveis para importação de:
import-done-title =
    .label = Importação concluída
import-done-description = Os seguintes itens foram importados com sucesso:
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = De { $source }
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Secure Browser
imported-safari-reading-list = Lista de leitura (Do Safari)
imported-edge-reading-list = Lista de leitura (do Edge)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Opções de Internet
    .value = Opções de Internet
browser-data-edge-1 =
    .label = Definições
    .value = Definições
browser-data-safari-1 =
    .label = Preferências
    .value = Preferências
browser-data-chrome-1 =
    .label = Preferências
    .value = Preferências
browser-data-canary-1 =
    .label = Preferências
    .value = Preferências
browser-data-360se-1 =
    .label = Preferências
    .value = Preferências
browser-data-ie-2 =
    .label = Cookies
    .value = Cookies
browser-data-edge-2 =
    .label = Cookies
    .value = Cookies
browser-data-safari-2 =
    .label = Cookies
    .value = Cookies
browser-data-chrome-2 =
    .label = Cookies
    .value = Cookies
browser-data-canary-2 =
    .label = Cookies
    .value = Cookies
browser-data-firefox-2 =
    .label = Cookies
    .value = Cookies
browser-data-360se-2 =
    .label = Cookies
    .value = Cookies
browser-data-ie-4 =
    .label = Histórico de navegação
    .value = Histórico de navegação
browser-data-edge-4 =
    .label = Histórico de navegação
    .value = Histórico de navegação
browser-data-safari-4 =
    .label = Histórico de navegação
    .value = Histórico de navegação
browser-data-chrome-4 =
    .label = Histórico de navegação
    .value = Histórico de navegação
browser-data-canary-4 =
    .label = Histórico de navegação
    .value = Histórico de navegação
browser-data-firefox-history-and-bookmarks-4 =
    .label = Histórico de navegação e marcadores
    .value = Histórico de navegação e marcadores
browser-data-360se-4 =
    .label = Histórico de navegação
    .value = Histórico de navegação
browser-data-ie-8 =
    .label = Histórico guardado de formulários
    .value = Histórico guardado de formulários
browser-data-edge-8 =
    .label = Histórico de formulários
    .value = Histórico de formulários
browser-data-safari-8 =
    .label = Histórico guardado de formulários
    .value = Histórico guardado de formulários
browser-data-chrome-8 =
    .label = Histórico guardado de formulários
    .value = Histórico guardado de formulários
browser-data-canary-8 =
    .label = Histórico guardado de formulários
    .value = Histórico guardado de formulários
browser-data-firefox-8 =
    .label = Histórico guardado de formulários
    .value = Histórico guardado de formulários
browser-data-360se-8 =
    .label = Histórico de formulários
    .value = Histórico de formulários
browser-data-ie-16 =
    .label = Palavras-passe guardadas
    .value = Palavras-passe guardadas
browser-data-edge-16 =
    .label = Palavras-passe guardadas
    .value = Palavras-passe guardadas
browser-data-safari-16 =
    .label = Palavras-passe guardadas
    .value = Palavras-passe guardadas
browser-data-chrome-16 =
    .label = Palavras-passe guardadas
    .value = Palavras-passe guardadas
browser-data-canary-16 =
    .label = Palavras-passe guardadas
    .value = Palavras-passe guardadas
browser-data-firefox-16 =
    .label = Palavras-passe guardadas
    .value = Palavras-passe guardadas
browser-data-360se-16 =
    .label = Palavras-passe guardadas
    .value = Palavras-passe guardadas
browser-data-ie-32 =
    .label = Favoritos
    .value = Favoritos
browser-data-edge-32 =
    .label = Favoritos
    .value = Favoritos
browser-data-safari-32 =
    .label = Marcadores
    .value = Marcadores
browser-data-chrome-32 =
    .label = Marcadores
    .value = Marcadores
browser-data-canary-32 =
    .label = Marcadores
    .value = Marcadores
browser-data-360se-32 =
    .label = Marcadores
    .value = Marcadores
browser-data-ie-64 =
    .label = Outros dados
    .value = Outros dados
browser-data-edge-64 =
    .label = Outros dados
    .value = Outros dados
browser-data-safari-64 =
    .label = Outros dados
    .value = Outros dados
browser-data-chrome-64 =
    .label = Outros dados
    .value = Outros dados
browser-data-canary-64 =
    .label = Outros dados
    .value = Outros dados
browser-data-firefox-other-64 =
    .label = Outros dados
    .value = Outros dados
browser-data-360se-64 =
    .label = Outros dados
    .value = Outros dados
browser-data-firefox-128 =
    .label = Janelas e separadores
    .value = Janelas e separadores
