# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

title = Sobre o tráfico da rede
warning = Esta funcionalidade é moi experimental. Non usar sen a supervisión dun adulto.
show-next-time-checkbox = Amosar este aviso a próxima vez
ok = Aceptar
http = HTTP
sockets = Sóckets
dns = DNS
websockets = WebSockets
refresh = Actualizar
auto-refresh = Actualizar automaticamente cada 3 segundos
hostname = Nome do servidor
port = Porto
http2 = HTTP/2
ssl = SSL
active = Activo
idle = Inactivo
host = Servidor
tcp = TCP
sent = Enviados
received = Recibidos
family = Familia
trr = TRR
addresses = Enderezos
expires = Caduca (Segundos)
messages-sent = Mensaxes enviadas
messages-received = Mensaxes recibidas
bytes-sent = Bytes enviados
bytes-received = Bytes recibidos
logging = Rexistro
log-tutorial = Vaia a <a data-l10n-name="logging">HTTP logging</a> para obter instrucións de como se usa esta ferramenta.
current-log-file = Ficheiro actual do rexistro:
current-log-modules = Módulos actuais do rexistro:
set-log-file = Estabelecer un ficheiro de rexistro
set-log-modules = Estabelecer módulos de rexistro
start-logging = Iniciar rexistro
stop-logging = Deter rexistro
dns-lookup = Buscar DNS
dns-lookup-button = Resolución
dns-domain = Dominio:
dns-lookup-table-column = Enderezos IP
rcwn = Estatísticas RCWN
rcwn-status = Estado RCWN
rcwn-cache-won-count = Número de vitorias da caché
rcwn-net-won-count = Número de vitorias da rede
total-network-requests = Número total de solicitudes de rede
rcwn-operation = Operación de caché
rcwn-perf-open = Aperturas
rcwn-perf-read = Lecturas
rcwn-perf-write = Escrituras
rcwn-perf-entry-open = Aperturas de entrada
rcwn-avg-short = Media curta
rcwn-avg-long = Media longa
rcwn-std-dev-long = Desviación estándar longa
rcwn-cache-slow = Reconto de caché lento
rcwn-cache-not-slow = Reconto de caché non lento
