# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Ganukuo' ga'an
import-from =
    { PLATFORM() ->
        [windows] Ganukuo' markador, riña gaché nu', da'ngà huìi ni a'ngò si dato:
       *[other] Ganukuo', preferensia, markador, riña gaché nu', da'ngà huìi ni a'ngò si dato:
    }
import-from-bookmarks = Ganukuo' markador:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-nothing =
    .label = Nitaj si gahuin
    .accesskey = D
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chrome-beta =
    .label = Chrome Beta
    .accesskey = B
import-from-chrome-dev =
    .label = Chrome Dev
    .accesskey = D
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = X
import-from-360se =
    .label = 360 Secure Browser
    .accesskey = 3
no-migration-sources = Nū nari' ma nej programa nikaj markador, riña gaché nu' nej si da'ngà huìi.
import-source =
    .label = Ganukuo' konfigurasiôn ni nej dato
import-items-title =
    .label = Nej sa ganukuo'
import-items-description = Ganahui nej sa hui ruat ganukuajt:
import-migrating-title =
    .label = 'Ngà anukuaj ma...
import-migrating-description = Nej na huin sa 'ngà ganukuaj ma...
import-select-profile-title =
    .label = Nagui Perfil
import-select-profile-description = Ga'ue ganukuo' nej sa ma ñuna:
import-done-title =
    .label = 'Ngà gisij ganukuaj ma
import-done-description = Hue'ê chre ganukuaj ma:
import-close-source-browser = Gi'iaj suntuj u ni gini'iaj si 'ngà arán navegador na hìaj ni gachin ga'anjt ne'ñaan.
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = Riña { $source }
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chrome-beta = Google Chrome Beta
source-name-chrome-dev = Google Chrome Dev
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Secure Browser
imported-safari-reading-list = Nej sa ahio' (si'iaj Safari)
imported-edge-reading-list = Nej sa ahio' (si'iaj Edge)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Nagi'io' internet
    .value = Nagi'io' internet
browser-data-edge-1 =
    .label = Nagi'iô'
    .value = Nagi'iô'
browser-data-safari-1 =
    .label = Sa arajsunt doj
    .value = Sa arajsunt doj
browser-data-chrome-1 =
    .label = Sa arajsunt doj
    .value = Sa arajsunt doj
browser-data-canary-1 =
    .label = Sa arajsunt doj
    .value = Sa arajsunt doj
browser-data-360se-1 =
    .label = Sa arajsunt doj
    .value = Sa arajsunt doj
browser-data-ie-2 =
    .label = Kookies
    .value = Kookies
browser-data-edge-2 =
    .label = Kookies
    .value = Kookies
browser-data-safari-2 =
    .label = Kookies
    .value = Kookies
browser-data-chrome-2 =
    .label = Kookies
    .value = Kookies
browser-data-canary-2 =
    .label = Kookies
    .value = Kookies
browser-data-firefox-2 =
    .label = Kookies
    .value = Kookies
browser-data-360se-2 =
    .label = Kookies
    .value = Kookies
browser-data-ie-4 =
    .label = Riña gaché nu'
    .value = Riña gaché nu'
browser-data-edge-4 =
    .label = Riña gaché nu'
    .value = Riña gaché nu'
browser-data-safari-4 =
    .label = Riña gaché nu'
    .value = Riña gaché nu'
browser-data-chrome-4 =
    .label = Riña gaché nu'
    .value = Riña gaché nu'
browser-data-canary-4 =
    .label = Riña gaché nu'
    .value = Riña gaché nu'
browser-data-firefox-history-and-bookmarks-4 =
    .label = Riña gaché nut ni nej markador
    .value = Riña gaché nut ni nej markador
browser-data-360se-4 =
    .label = Riña gaché nu'
    .value = Riña gaché nu'
browser-data-ie-8 =
    .label = 'Ngà nun sa' nej formulario ni'io'
    .value = 'Ngà nun sa' nej formulario ni'io'
browser-data-edge-8 =
    .label = 'Ngà nun sa' nej formulario ni'io'
    .value = 'Ngà nun sa' nej formulario ni'io'
browser-data-safari-8 =
    .label = 'Ngà nun sa' nej formulario ni'io'
    .value = 'Ngà nun sa' nej formulario ni'io'
browser-data-chrome-8 =
    .label = 'Ngà nun sa' nej formulario ni'io'
    .value = 'Ngà nun sa' nej formulario ni'io'
browser-data-canary-8 =
    .label = 'Ngà nun sa' nej formulario ni'io'
    .value = 'Ngà nun sa' nej formulario ni'io'
browser-data-firefox-8 =
    .label = 'Ngà nun sa' nej formulario ni'io'
    .value = 'Ngà nun sa' nej formulario ni'io'
browser-data-360se-8 =
    .label = 'Ngà nun sa' nej formulario ni'io'
    .value = 'Ngà nun sa' nej formulario ni'io'
browser-data-ie-16 =
    .label = Kontraseña ma sa'aj
    .value = Kontraseña ma sa'aj
browser-data-edge-16 =
    .label = Kontraseña ma sa'aj
    .value = Kontraseña ma sa'aj
browser-data-safari-16 =
    .label = Kontraseña ma sa'aj
    .value = Kontraseña ma sa'aj
browser-data-chrome-16 =
    .label = Kontraseña ma sa'aj
    .value = Kontraseña ma sa'aj
browser-data-canary-16 =
    .label = Kontraseña ma sa'aj
    .value = Kontraseña ma sa'aj
browser-data-firefox-16 =
    .label = Kontraseña ma sa'aj
    .value = Kontraseña ma sa'aj
browser-data-360se-16 =
    .label = Kontraseña ma sa'aj
    .value = Kontraseña ma sa'aj
browser-data-ie-32 =
    .label = Sa nia' ruo'
    .value = Sa nia' ruo'
browser-data-edge-32 =
    .label = Sa nia' ruo'
    .value = Sa nia' ruo'
browser-data-safari-32 =
    .label = Sa raj sun nichrò' doj
    .value = Sa raj sun nichrò' doj
browser-data-chrome-32 =
    .label = Sa raj sun nichrò' doj
    .value = Sa raj sun nichrò' doj
browser-data-canary-32 =
    .label = Sa raj sun nichrò' doj
    .value = Sa raj sun nichrò' doj
browser-data-360se-32 =
    .label = Sa raj sun nichrò' doj
    .value = Sa raj sun nichrò' doj
browser-data-ie-64 =
    .label = A'ngò dato
    .value = A'ngò dato
browser-data-edge-64 =
    .label = A'ngò dato
    .value = A'ngò dato
browser-data-safari-64 =
    .label = A'ngò dato
    .value = A'ngò dato
browser-data-chrome-64 =
    .label = A'ngò dato
    .value = A'ngò dato
browser-data-canary-64 =
    .label = A'ngò dato
    .value = A'ngò dato
browser-data-firefox-other-64 =
    .label = A'ngò dato
    .value = A'ngò dato
browser-data-360se-64 =
    .label = A'ngò dato
    .value = A'ngò dato
browser-data-firefox-128 =
    .label = Ventana ni rakïj nanj
    .value = Ventana ni rakïj nanj
