# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = دەتەوێت “%S” بخەیتە لیستی باوەڕپێکراوەکانەوە بۆ ئەم مەبەستانەی خوارەوە؟
unnamedCA = دەسەڵایی بڕوانامە (بێ ناو)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = تکایە وشەی تێپەڕبوون کە بەکارهێنرابوو بۆ کلیلیدانی ئەم پاڵپشتییە(باکئەپ):
# Page Info
pageInfo_NoEncryption = پەیوەندی کلیل نەدراوە
pageInfo_Privacy_None1 = ماڵپەڕی %S پشتگیر بە کلیلیکردن ناکات بۆ ئەو پەرەی دەتەوێت بیبینی.
pageInfo_Privacy_None2 = زانیاری نێردراو لە ڕێگەی ئینتەرنێتەوە کە کلیلنەدرابێت دەتوانرێت ببینرێت لە لایەن کەسانی ترەوە کاتێک لە ڕێگەی ناردندایە.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = پەیوەندی کلیلدراوە (%1$S، کلیلی %2$S بتی، %3$S)
pageInfo_BrokenEncryption = کلیدانی شکاو (%1$S، کلیلی %2$S بتی، %3$S)
pageInfo_MixedContent = پەیوەندی بە نیمچەیی کلیلدراوە
# Token Manager
password_not_set = (ئامادە نەکراوە)
