# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE (accessibility.contrast.ratio): A title text for the color contrast
# ratio description, used by the accessibility highlighter to display the value. %S in the
# content will be replaced by the contrast ratio numerical value.
accessibility.contrast.ratio = کنتراست: %S
# LOCALIZATION NOTE (accessibility.contrast.ratio.error): A title text for the color
# contrast ratio, used when the tool is unable to calculate the contrast ratio value.
accessibility.contrast.ratio.error = محاسبه امکان‌پذیر نیست
# LOCALIZATION NOTE (accessibility.contrast.ratio.label): A title text for the color
# contrast ratio description, used together with the actual values.
accessibility.contrast.ratio.label = کنتراست:
# LOCALIZATION NOTE (accessibility.contrast.ratio.label.large): A title text for the color
# contrast ratio description that also specifies that the color contrast criteria used is
# if for large text.
accessibility.contrast.ratio.label.large = کنتراست (متن بزرگ):
# LOCALIZATION NOTE (accessibility.text.label.issue.area): A title text that
# describes that currently selected accessible object for an <area> element must have
# its name provided via the alt attribute.
accessibility.text.label.issue.area = برای برچسب‌گذاری عنصرهای «area» که دارای صفت «href» هستند، از صفت «alt» استفاده کنید.
# LOCALIZATION NOTE (accessibility.text.label.issue.dialog): A title text that
# describes that currently selected accessible object for a dialog should have a name
# provided.
accessibility.text.label.issue.dialog = پنجره‌های گفتگو (Dialogs) باید برچسب داشته باشند.
# LOCALIZATION NOTE (accessibility.text.label.issue.document.title): A title text that
# describes that currently selected accessible object for a document must have a name
# provided via title.
accessibility.text.label.issue.document.title = اسناد باید دارای عنوان (title) باشند.
# LOCALIZATION NOTE (accessibility.text.label.issue.embed): A title text that
# describes that currently selected accessible object for an <embed> must have a name
# provided.
accessibility.text.label.issue.embed = محتوای تعبیه‌شده (Embedded) باید برچسب‌گذاری شده باشد.
# LOCALIZATION NOTE (accessibility.text.label.issue.figure): A title text that
# describes that currently selected accessible object for a figure should have a name
# provided.
accessibility.text.label.issue.figure = شکل‌ها (Figures) با زیرنویس اختیاری باید برچسب‌گذاری شوند.
# LOCALIZATION NOTE (accessibility.text.label.issue.fieldset): A title text that
# describes that currently selected accessible object for a <fieldset> must have a name
# provided.
accessibility.text.label.issue.fieldset = عنصرهای «fieldset» باید برچسب‌گذاری شوند.
# LOCALIZATION NOTE (accessibility.text.label.issue.fieldset.legend2): A title text that
# describes that currently selected accessible object for a <fieldset> must have a name
# provided via <legend> element.
accessibility.text.label.issue.fieldset.legend2 = از یک عنصر «legend» برای برچسب‌گذاری «fieldset» استفاده کنید.
# LOCALIZATION NOTE (accessibility.text.label.issue.form): A title text that
# describes that currently selected accessible object for a form element must have a name
# provided.
accessibility.text.label.issue.form = عنصرهای فرم باید برچسب‌گذاری شوند.
# LOCALIZATION NOTE (accessibility.text.label.issue.form.visible): A title text that
# describes that currently selected accessible object for a form element should have a name
# provided via a visible label/element.
accessibility.text.label.issue.form.visible = عنصرهای فرم باید دارای یک برچسب متنیِ مرئی باشند.
# LOCALIZATION NOTE (accessibility.text.label.issue.frame): A title text that
# describes that currently selected accessible object for a <frame> must have a name
# provided.
accessibility.text.label.issue.frame = عنصرهای «frame» باید برچسب‌گذاری شوند.
# LOCALIZATION NOTE (accessibility.text.label.issue.glyph): A title text that
# describes that currently selected accessible object for a <mglyph> must have a name
# provided via alt attribute.
accessibility.text.label.issue.glyph = برای برچسب‌گذاری عنصرهای «mglyph» از صفت «alt» استفاده کنید.
# LOCALIZATION NOTE (accessibility.text.label.issue.heading): A title text that
# describes that currently selected accessible object for a heading must have a name
# provided.
accessibility.text.label.issue.heading = سربرگ‌ها (Headings) باید برچسب‌گذاری شوند.
# LOCALIZATION NOTE (accessibility.text.label.issue.heading.content): A title text that
# describes that currently selected accessible object for a heading must have visible
# content.
accessibility.text.label.issue.heading.content = سربرگ‌ها باید دارای محتوای متنیِ مرئی باشند.
# LOCALIZATION NOTE (accessibility.text.label.issue.iframe): A title text that
# describes that currently selected accessible object for an <iframe> have a name
# provided via title attribute.
accessibility.text.label.issue.iframe = برای توصیف محتوای «iframe» از صفت «title» استفاده کنید.
# LOCALIZATION NOTE (accessibility.text.label.issue.image): A title text that
# describes that currently selected accessible object for graphical content must have a
# name provided.
accessibility.text.label.issue.image = محتوای دارای تصویر باید برچسب‌گذاری شود.
# LOCALIZATION NOTE (accessibility.text.label.issue.interactive): A title text that
# describes that currently selected accessible object for interactive element must have a
# name provided.
accessibility.text.label.issue.interactive = عنصرهای تعاملی باید برچسب‌گذاری شوند.
# LOCALIZATION NOTE (accessibility.text.label.issue.optgroup.label2): A title text that
# describes that currently selected accessible object for an <optgroup> must have a
# name provided via label attribute.
accessibility.text.label.issue.optgroup.label2 = از صفت «label» برای برچسب‌گذاری یک «optgroup» استفاده کنید.
# LOCALIZATION NOTE (accessibility.text.label.issue.toolbar): A title text that
# describes that currently selected accessible object for a toolbar must have a
# name provided when there is more than one toolbar in the document.
accessibility.text.label.issue.toolbar = هنگامی که بیش از یک نوارابزار در سند وجود دارد، نوارابزارها باید برچسب‌گذاری شوند.
# LOCALIZATION NOTE (accessibility.keyboard.issue.semantics): A title text that
# describes that currently selected accessible object is focusable and should
# indicate that it could be interacted with.
accessibility.keyboard.issue.semantics = عنصرهای با قابلیت دریافت فوکوس باید معناشناسیِ (Semantics) تعاملی داشته باشند.
# LOCALIZATION NOTE (accessibility.keyboard.issue.tabindex): A title text that
# describes that currently selected accessible object has a corresponding
# DOMNode that defines a tabindex attribute greater that 0 which can result in
# unexpected behaviour when navigating with keyboard.
accessibility.keyboard.issue.tabindex = از به‌کارگیری صفت «tabindex» با مقدار بزرگ‌تر از صفر خودداری کنید.
# LOCALIZATION NOTE (accessibility.keyboard.issue.action): A title text that
# describes that currently selected accessible object is interactive but can not
# be activated using keyboard or accessibility API.
accessibility.keyboard.issue.action = عنصرهای تعاملی باید از طریق صفحه‌کلید قابل فعال‌سازی باشند.
# LOCALIZATION NOTE (accessibility.keyboard.issue.focusable): A title text that
# describes that currently selected accessible object is interactive but is not
# focusable with a keyboard.
accessibility.keyboard.issue.focusable = عنصرهای تعاملی باید با صفحه‌کلید قابل فوکوس باشند.
# LOCALIZATION NOTE (accessibility.keyboard.issue.focus.visible): A title text
# that describes that currently selected accessible object is focusable but
# might not have appropriate focus styling.
accessibility.keyboard.issue.focus.visible = عنصر با قابلیت فوکوس ممکن است فاقد استایل مناسبِ حالت فوکوس باشد.
# LOCALIZATION NOTE (accessibility.keyboard.issue.mouse.only): A title text that
# describes that currently selected accessible object is not focusable and not
# semantic but can be activated via mouse (e.g. has click handler).
accessibility.keyboard.issue.mouse.only = عنصرهای قابل کلیک باید با صفحه‌کلید قابل فوکوس باشند و معناشناسیِ تعاملی داشته باشند.
