# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = இந்த இணைய பக்கம் வேறு இடத்திற்கு திசை மாற்றப்பட்டது. நீங்கள் தட்டச்சு செய்த தகவலை புதிய இடத்திற்கு அனுப்ப விருப்பமா?
# Directory listing strings
DirTitle = %1$S இன் அகரவரிசை
DirGoUp = மேல் மட்ட அடைவுக்கு செல்
ShowHidden = மறைக்கப்பட்ட பொருட்களை காட்டு
DirColName = பெயர்
DirColSize = அளவு
DirColMTime = கடைசியாக மாற்றப்பட்டது
DirFileLabel = கோப்பு:
UnsafeUriBlocked = பாதுகாப்பு உலாவலால் “%1$S” தளத்தில் உள்ள வளம் தடுக்கப்பட்டது.
