# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = O weladenniñ { $host }…
network-connection-status-connected = Kennasket ouzh { $host }…
network-connection-status-sending-request = O kas an azgoulenn da { $host }…
network-connection-status-transferring-data = O treuzkas roadennoù adalek { $host }…
network-connection-status-connecting = O kennaskañ ouzh { $host }…
network-connection-status-read = Roadennoù lennet diouzh { $host }
network-connection-status-wrote = Roadennoù kaset da { $host }
network-connection-status-waiting = O c'hortoz { $host }…
network-connection-status-looked-up = Klask { $host }…
network-connection-status-tls-handshake = O seveniñ ar c'hennask TLS e { $host }…
network-connection-status-tls-handshake-finished = Echuet eo seveniñ ar c'hennask TLS evit { $host }...
