# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

ssl-error-no-certificate = Cha ghabh an ceadachas no an iuchair air a bheil feum airson dearbhadh a lorg.
ssl-error-bad-client = Fhuair am frithealaiche droch dhàta on chliant.
ssl-error-bad-server = Fhuair am frithealaiche droch dhàta on fhrithealaiche.
ssl-error-unsupported-certificate-type = Chan eil taic ann ris an t-seòrsa seo de theisteanas.
ssl-error-unsupported-version = Tha an seise a' cleachdadh tionndadh dhen phròtacal tèarainteachd nach eil taic ris.
ssl-error-wrong-certificate = Dh'fhàillig dearbhadh a' chliant: chan eil an iuchair phrìobhaideach ann an stòr-dàta nan iuchraichean a' freagairt ris an iuchair phoblach ann an stòr-dàta nan teisteanasan.
ssl-error-ssl2-disabled = Tha an seise a' cur taic ri SSL tionndadh 2 a-mhàin, rud a tha air a chur à comas gu h-ionadail.
ssl-error-bad-mac-read = Fhuair SSL clàr le còd dearbhadh teachdaireachd mì-cheart ann.
ssl-error-bad-mac-alert = Tha an seise SSL a' dèanamh aithris air còd dearbhadh teachdaireachd mì-cheart.
ssl-error-bad-cert-alert = Chan urrainn dhan t-seise SSL an teisteanas agad a dhearbhadh.
ssl-error-revoked-cert-alert = Dhiùlt an seise SSL an teisteanas agad is e ag ràdh gun deach a chùl-ghairm.
ssl-error-expired-cert-alert = Dhiùlt an seise SSL an teisteanas agad is e ag ràdh gun do dh'fhalbh an ùine air.
ssl-error-ssl-disabled = Cha ghabh ceangal a dhèanamh: tha SSL air a chur à comas.
ssl-error-unknown-cipher-suite = Chaidh sreath-sifir SSL neo-aithnichte iarraidh.
ssl-error-no-ciphers-supported = Chan eil sreath-sifir ann agus an comas sa phrògram seo.
ssl-error-bad-block-padding = Fhuair SSL clàr le droch phadadh bluic.
ssl-error-rx-record-too-long = Fhuair SSL clàr a chaidh thairis air an fhad a tha ceadaichte.
ssl-error-tx-record-too-long = Dh'fheuch SSL ri clàr a chur a-null a chaidh thairis air an fhad a tha ceadaichte.
ssl-error-rx-malformed-hello-request = Fhuair SSL teachdaireachd crathadh-làimhe Hello Request mhì-chumte.
ssl-error-rx-malformed-client-hello = Fhuair SSL teachdaireachd crathadh-làimhe Client Hello mhì-chumte.
ssl-error-rx-malformed-server-hello = Fhuair SSL teachdaireachd crathadh-làimhe Server Hello mhì-chumte.
ssl-error-rx-malformed-certificate = Fhuair SSL teachdaireachd crathadh-làimhe Certificate mhì-chumte.
ssl-error-rx-malformed-server-key-exch = Fhuair SSL teachdaireachd crathadh-làimhe Server Key Exchange mhì-chumte.
ssl-error-rx-malformed-cert-request = Fhuair SSL teachdaireachd crathadh-làimhe Certificate Request mhì-chumte.
ssl-error-rx-malformed-hello-done = Fhuair SSL teachdaireachd crathadh-làimhe Server Hello Done mhì-chumte.
ssl-error-rx-malformed-client-key-exch = Fhuair SSL teachdaireachd crathadh-làimhe Client Key Exchange mhì-chumte.
ssl-error-rx-malformed-finished = Fhuair SSL teachdaireachd crathadh-làimhe Finished mhì-chumte.
ssl-error-rx-malformed-change-cipher = Fhuair SSL clàr Change Cipher Spec mì-chumte.
ssl-error-rx-malformed-alert = Fhuair SSL clàr caismeachd mì-chumte.
ssl-error-rx-malformed-handshake = Fhuair SSL clàr Handshake mì-chumte.
ssl-error-rx-malformed-application-data = Fhuair SSL clàr Application Data mì-chumte.
ssl-error-rx-unexpected-hello-request = Fhuair SSL teachdaireachd crathadh-làimhe Hello Request ris nach robh dùil.
ssl-error-rx-unexpected-client-hello = Fhuair SSL teachdaireachd crathadh-làimhe Client Hello ris nach robh dùil.
ssl-error-rx-unexpected-server-hello = Fhuair SSL teachdaireachd crathadh-làimhe Server Hello ris nach robh dùil.
ssl-error-rx-unexpected-certificate = Fhuair SSL teachdaireachd crathadh-làimhe Certificate ris nach robh dùil.
ssl-error-rx-unexpected-server-key-exch = Fhuair SSL teachdaireachd crathadh-làimhe Server Key Exchange ris nach robh dùil.
ssl-error-rx-unexpected-cert-request = Fhuair SSL teachdaireachd crathadh-làimhe Certificate Request ris nach robh dùil.
ssl-error-rx-unexpected-hello-done = Fhuair SSL teachdaireachd crathadh-làimhe Server Hello Done ris nach robh dùil.
ssl-error-rx-unexpected-cert-verify = Fhuair SSL teachdaireachd crathadh-làimhe Certificate Verify ris nach robh dùil.
ssl-error-rx-unexpected-client-key-exch = Fhuair SSL teachdaireachd crathadh-làimhe Client Key Exchange ris nach robh dùil.
ssl-error-rx-unexpected-finished = Fhuair SSL teachdaireachd crathadh-làimhe Finished ris nach robh dùil.
ssl-error-rx-unexpected-change-cipher = Fhuair SSL clàr Change Ciper Spec ris nach robh dùil.
ssl-error-rx-unexpected-alert = Fhuair SSL clàr caismeachd ris nach robh dùil.
ssl-error-rx-unexpected-handshake = Fhuair SSL clàr crathaidh-làimhe ris nach robh dùil.
ssl-error-rx-unexpected-application-data = Fhuair SSL clàr Application Data ris nach robh dùil.
ssl-error-rx-unknown-record-type = Fhuair SSL clàr anns a bha seòrsa neo-aithnichte de shusbaint.
ssl-error-rx-unknown-handshake = Fhuair SSL teachdaireachd cràthaidh-làimhe anns a bha seòrsa neo-aithnichte de theachdaireachd.
ssl-error-rx-unknown-alert = Fhuair SSL clàr caismeachd sa bha tuairisgeul caismeachd neo-aithnichte.
ssl-error-close-notify-alert = Dhùin an seise SSL an ceangal seo.
ssl-error-handshake-unexpected-alert = Cha robh dùil aig an t-seise SSL ris an teachdaireachd crathaidh-làimhe a fhuair e.
ssl-error-decompression-failure-alert = Cha b' urrainn do sheise SSL clàr SSL a fhuair e a dhì-dhùmhlachadh gu soirbheachail.
ssl-error-handshake-failure-alert = Cha b' urrainn dhan t-seise SSL seata freagarrach de pharamadairean tèarainteachd a cho-rèiteachadh.
ssl-error-illegal-parameter-alert = Dhiùlt an seise SSL teachdaireachd crathaidh-làimhe airson susbaint mì-fhreagarrach.
ssl-error-unsupported-cert-alert = Chan eil an seise SSL a' cur taic ri teisteanasan dhen t-seòrsa a fhuair e.
ssl-error-certificate-unknown-alert = Bha duilgheadas neo-shònraichte aig an t-seise SSL leis an teisteanas a fhuair e.
ssl-error-generate-random-failure = Dh'fhàillig an gineadair àireamhan tuaireamach aig SSL.
ssl-error-sign-hashes-failure = Cha do ghabh ainm digiteach a chur ris an dàta air a bheil feum gus an teisteanas agad a dhearbhadh.
ssl-error-server-key-exchange-failure = Fàillinn neo-shònraichte rè làimhseachadh crathadh-làimhe SSL Server Key Exchange.
ssl-error-client-key-exchange-failure = Fàillinn neo-shònraichte rè làimhseachadh crathadh-làimhe SSL Client Key Exchange.
ssl-error-md5-digest-failure = Dh'fhàillig am foincsean eagaraidh MD5.
ssl-error-sym-key-context-failure = Dh'fhàillig cruthachadh an co-theacs Symmetric Key.
ssl-error-sym-key-unwrap-failure = Dh'fhàillig dì-phasgadh an Symmetric Key anns an teachdaireachd Client Key Exchange.
ssl-error-pub-key-size-limit-exceeded = Dh'fheuch am frithealaiche SSL ri iuchair phoblach de dh'ìre dhachaigheil a chleachdadh le sreath-sifir às-phortaidh.
ssl-error-iv-param-failure = Dh'fhàillig còd PKCS11 le eadar-theangachadh IV gu paramadair.
ssl-error-init-cipher-suite-failure = Dh'fhàillig tòiseachadh an t-sreatha-sifir a chaidh a thaghadh.
ssl-error-session-key-gen-failure = Dh'fhàillig gineadh nan iuchraichean seisein airson seisean SSL air a' chliant.
ssl-error-no-server-key-for-alg = Chan eil iuchair aig an fhrithealaiche airson algairim malairt na h-iuchrach a dh'fheuchadh.
ssl-error-token-insertion-removal = Chaidh tòcan PKCS#11 a chur ann no a thoirt air falbh rè an obrachaidh.
ssl-error-token-slot-not-found = Cha deach tòcan PKCS#11 a lorg gus obrachadh riatanach a dhèanamh.
ssl-error-no-compression-overlap = Cha ghabh conaltradh tèarainte a dhèanamh ris an t-seise: chan eil algairim(ean) dùmhlachaidh coitcheann ann.
ssl-error-handshake-not-completed = Cha ghabh crathadh-làimhe SSL eile a thòiseachadh mus dàining an crathadh làithreach gu crìoch.
ssl-error-bad-handshake-hash-value = Fhuaradh luachan-hais mì-cheart airson crathadh-làimhe on t-seise.
ssl-error-cert-kea-mismatch = Cha ghabh an teisteanas a fhuaradh a chleachdadh le algairim malairt na h-iuchrach a chaidh a thaghadh.
ssl-error-no-trusted-ssl-client-ca = Chan eil earbsa ann an ùghdarras teisteanais sam bith airson dearbhadh cliant SSL.
ssl-error-record-overflow-alert = Fhuair an seise clàr SSL nach eil ceadaichte tuilleadh.
ssl-error-unknown-ca-alert = Chan eil an seise ag aithneachadh ùghdarras nan teisteanasan a chuir a-mach an teisteanas agad is chan eil earbsa aige ann.
ssl-error-decrypt-error-alert = Tha an seise ag aithris gun do dh'fhàillig dearbhadh an t-soidhnidh no malairt na h-iuchrach.
ssl-error-export-restriction-alert = Tha an seise ag aithris nach eil an co-rèiteachadh a' gèilleadh ris na riaghailtean às-phortadh.
ssl-error-protocol-version-alert = Tha an seise ag aithris gu bheil tionndadh a' phròtacail neo-chòrdail no gun taic.
ssl-error-insufficient-security-alert = Feumaidh am frithealaiche sifirean nas tèarainte na an fheadhainn a tha an cliant a' cur taic riutha an-dràsta.
ssl-error-user-canceled-alert = Sguir an cleachdaiche seise dhen chrathadh-làimhe.
ssl-error-no-renegotiation-alert = Chan eil an seise a' toirt cead do dh'ath-cho-rèiteachadh nam paramadairean tèarainteachd SSL.
ssl-error-server-cache-not-configured = Cha deach tasgadan an fhrithealaichean SSL a rèiteachadh agus a chur à comas airson na socaide seo.
ssl-error-unsupported-extension-alert = Chan eil an seise SSL a' cur taic ris an leudachan TLS Hello a chaidh iarraidh.
ssl-error-certificate-unobtainable-alert = Cha b' urrainn dhan t-seise SSL an teisteanas agad fhaighinn on URL a thug thu dha.
ssl-error-unrecognized-name-alert = Chan eil teisteanas aig an t-seise SSL airson an ainm DNS a chaidh iarraidh.
ssl-error-bad-cert-status-response-alert = Cha b' urrainn dhan t-seise SSL freagairt OCSP fhaighinn airson an teisteanais aige.
ssl-error-bad-cert-hash-value-alert = Dh'aithris an seise SSL gun robh droch luach-hais aig an teisteanas.
ssl-error-unsafe-negotiation = Dh'fheuch an seise ri crathadh-làimhe seann nòsach a dhèanamh (a dh'fhaodadh a bhith so-leònte).
ssl-error-rx-unexpected-uncompressed-record = Fhuair SSL clàr neo-dhùmhlaichte ris nach robh dùil.
ssl-error-weak-server-ephemeral-dh-key = Fhuair SSL iuchair Diffie-Hellman lag is gearr-shaoghalach ann an teachdaireachd crathadh-làimhe Server Key Exchange.
sec-error-io = Thachair mearachd I/O rè an ùghdarrachaidh thèarainteachd.
sec-error-library-failure = fàillinn na leabhar-lainn thèarainteachd.
sec-error-bad-data = leabhar-lann tèarainteachd: fhuaradh droch dhàta.
sec-error-output-len = leabhar-lann tèarainteachd: mearachd le faid an às-chuir.
sec-error-input-len = thachair mearachd le faid an in-chuir ris an leabhar-lann tèarainteachd.
sec-error-invalid-args = leabhar-lann tèarainteachd: argamaidean mì-dhligheach.
sec-error-invalid-algorithm = leabhar-lann tèarainteachd: algairim mhì-dhligheach.
sec-error-invalid-ava = leabhar-lann tèarainteachd: AVA mì-dhligheach.
sec-error-invalid-time = Sreang ama air a dhroch chumadh.
sec-error-bad-der = leabhar-lann tèarainteachd: teachdaireachd air a dhroch fhòrmatadh ann an còdachadh DER.
sec-error-bad-password = Tha am facal-faire tèarainteachd a chuir thu a-steach cearr.
sec-error-no-nodelock = leabhar-lann tèarainteachd: gun ghlas nòid.
sec-error-bad-database = leabhar-lann tèarainteachd: droch stòr-dàta.
sec-error-duplicate-cert = Tha an teisteanas san stòr-dàta agad mu thràth.
sec-error-adding-cert = Thachair mearachd fhad 's a chaidh an teisteanas a chur ris an stòr-dàta.
sec-error-filing-key = Thachair mearachd le faidhleadh na h-iuchrach airson an teisteanais seo.
sec-error-cert-valid = Tha an teisteanas seo dligheach.
sec-error-cert-not-valid = Chan eil an teisteanas seo dligheach.
sec-error-cert-no-response = Leabhar-lann teisteanais: Gun fhreagairt
sec-error-crl-invalid = Tha fòrmat mì-dhligheach aig an CRL ùr.
sec-error-extension-value-invalid = Tha luach leudachan an teisteanais mì-dhligheach.
sec-error-extension-not-found = Cha deach leudachan an teisteanais a lorg.
sec-error-ca-cert-invalid = Tha teisteanas an fhoillsicheir mì-dhligheach.
sec-error-path-len-constraint-invalid = Tha am bacadh air faid slighe an teisteanais mì-dhligheach.
sec-error-cert-usages-invalid = Tha an raon airson cleachdadh nan teisteanasan mì-dhligheach.
sec-internal-only = **Mòideal dhen taobh a-staigh A-MHÀIN**
sec-error-invalid-key = Chan eil an iuchair a' cur taic ris an obrachadh a chaidh iarradh.
sec-error-unknown-critical-extension = Tha leudachan neo-aithnichte èiginneach anns an teisteanas.
sec-error-old-crl = Chan eil an CRL ùr as dèidh an fhir làithrich.
sec-error-pkcs7-bad-signature = Dh'fhàillig dearbhadh an ainm: cha deach soidhnichear a lorg, chaidh cus dhiubh a lorg no dàta mì-cheart no truaillte.
sec-error-unsupported-keyalg = Algairim iuchrach neo-aithnichte no gun taic.
xp-sec-fortezza-no-card = Cha deach cairt Fortezza a lorg
xp-sec-fortezza-none-selected = Cha deach cairt Fortezza a thaghadh
xp-sec-fortezza-more-info = Tagh a' phearsantachd a tha thu ag iarraidh barrachd fiosrachaidh mu dhèidhinn
xp-sec-fortezza-person-not-found = Cha deach a' phearsantachd a lorg
xp-sec-fortezza-no-more-info = Chan eil barrachd fiosrachaidh mun phearsantachd seo ann
xp-sec-fortezza-bad-pin = PIN mì-dhligheach
sec-error-krl-invalid = Tha fòrmat liosta nan iuchraichean a chaidh a chùl-ghairm mì-dhligheach.
sec-error-need-random = leabhar-lann tèarainteach: feum air dàta tuaireamach.
sec-error-no-module = leabhar-lann tèarainteach: chan urrainn do mhòideal tèarainteachd sam bith an t-obrachadh a dh'iarr thu a dhèanamh.
sec-error-no-token = Chan eil a' chairt no an tòcan tèarainteachd ann, feumaidh a thòiseachadh no chaidh a thoirt air falbh.
sec-error-read-only = leabhar-lann tèarainteach: stòr-dàta ri leughadh a-mhàin.
sec-error-no-slot-selected = Cha deach sliotan no tòcan a thaghadh.
sec-error-cert-nickname-collision = Tha teisteanas air a bheil an dearbh fhar-ainm ann mu thràth.
sec-error-key-nickname-collision = Tha iuchair air a bheil an dearbh fhar-ainm ann mu thràth.
sec-error-bad-export-algorithm = Chan eil an algairim air a bheil feum ceadaichte.
sec-error-exporting-certificates = Mearachd ann an às-phortadh nan teisteanasan.
sec-error-importing-certificates = Mearachd le ion-phortadh nan teisteanasan.
sec-error-user-cancelled = Bhriog an cleachdaiche air "Sguir dheth".
sec-error-pkcs12-duplicate-data = Cha deach ion-phortadh, tha e san stòr-dàta mu thràth.
sec-error-message-send-aborted = Cha deach an teachdaireachd a chur.
sec-error-inadequate-key-usage = Chan eil cleachdadh iuchair an teisteanais freagarrach airson an obrachaidh a chaidh iarraidh.
sec-error-cert-addr-mismatch = Chan eil an seòladh san teisteanas soidhnidh a' freagairt ris an t-seòladh ann am bann-cinn na teachdaireachd.
sec-error-keygen-fail = Cha ghabh cèile iuchraichean poblach/prìobhaideach a ghineadh.
sec-error-bad-nickname = Tha far-ainm an teisteanais 'ga chleachdadh mu thràth.
sec-error-not-fortezza-issuer = Tha teisteanas neo-Fortezza aig slabhraidh Fortezza an t-seise.
sec-error-cannot-move-sensitive-key = Cha ghabh iuchair chugallach a ghluasad dhan t-sliotan far a bheil feum air.
sec-error-js-invalid-module-name = Ainm mì-dhligheach air a' mhòideal.
sec-error-js-invalid-dll = Ainm mì-dhligheach air slighe no ainm faidhle a' mhòideil
sec-error-js-add-mod-failure = Cha ghabh am mòideal a chur ris
sec-error-js-del-mod-failure = Cha ghabh am mòideal a sguabadh às
sec-error-old-krl = Chan eil liosta nan iuchraichean a chaidh a chùl-ghairm as dèidh an fhir làithrich.
sec-error-cert-not-in-name-space = Chan eil cead aig ùghdarras teisteanachaidh an teisteanais seo teisteanas leis an ainm seo fhoillseachadh.
sec-error-krl-not-yet-valid = Chan eil liosta cùl-ghairm nan iuchraichean airson an teisteanais seo dligheach fhathast.
sec-error-crl-not-yet-valid = Chan eil liosta cùl-ghairm nan teisteanasan airson an teisteanais seo dligheach fhathast.
sec-error-unknown-cert = Cha deach an teisteanas a dh'iarr thu a lorg.
sec-error-cert-bad-access-location = Tha fòrmat mì-dhligheach air àite frithealaiche inbhe an teisteanais.
sec-error-ocsp-unknown-response-type = Cha ghabh an fhreagairt OCSP a dhì-chòdadh gu lèir; chan aithnichear a sheòrsa.
sec-error-ocsp-bad-http-response = Thill am frithealaiche OCSP dàta HTTP ris nach robh dùil no a tha mì-dhligheach.
sec-error-ocsp-malformed-request = Mheas am frithealaiche OCSP gu bheil an t-iarrtas air a thruailleadh no air a dhroch chumadh.
sec-error-ocsp-server-error = Thachair mearachd taobh a-staigh an fhrithealaiche OCSP.
sec-error-ocsp-try-server-later = Tha am frithealaiche OCSP a' moladh dhut feuchainn ris a-rithist an ceann tàmaill.
sec-error-ocsp-request-needs-sig = Feumaidh am frithealaiche OCSP ainm ris an iarrtas seo.
sec-error-ocsp-unauthorized-request = Dhiùlt am frithealaiche OCSP an t-iarrtas seo a chionn 's nach eil ùghdarras aige.
sec-error-ocsp-unknown-response-status = Thill am frithealaiche OCSP inbhe nach gabh aithneachadh.
sec-error-ocsp-unknown-cert = Chan eil inbhe airson an teisteanais seo aig an fhrithealaiche OCSP.
sec-error-ocsp-not-enabled = Feumaidh tu OCSP a chur an comas mus dèan thu seo.
sec-error-ocsp-no-default-responder = Feumaidh tu freagairiche OCSP bunaiteach a shuidheachadh mus dèan thu seo.
sec-error-ocsp-malformed-response = Chaidh freagairt an fhrithealaiche OCSP a thruailleadh no a dhroch cumadh.
sec-error-ocsp-unauthorized-response = Chan eil ùghdarras aig soidhniche na freagairt OCSP inbhe a thoirt seachad airson an teisteanais seo.
sec-error-ocsp-future-response = Chan eil an fhreagairt OCSP dligheach fhathast (tha ceann-là san àm ri teachd ann).
sec-error-ocsp-old-response = Tha fiosrachadh anns an fhreagairt OCSP a dh'fhalbh an ùine air.
sec-error-digest-not-found = Cha deach an gearr-chunntas CMS no PKCS #7 a lorg san teachdaireachd shoidhnichte.
sec-error-unsupported-message-type = Chan eil taic ann ri seòrsa na teachdaireachd CMS no PKCS #7.
sec-error-module-stuck = Cha do ghabh am mòideal PKCS #11 a thoirt air falbh a chionn 's gu bheilear 'ga chleachdadh fhathast.
sec-error-bad-template = Cha do ghabh an dàta ASN.1 a dhì-chòdadh. Bha an teamplaid a chaidh a shònrachadh mì-dhligheach.
sec-error-crl-not-found = Cha deach liosta nan teisteanasan a chaidh a chùl-ghairm a lorg.
sec-error-reused-issuer-and-serial = Tha thu a' feuchainn ri teisteanas a thoirt a-steach aig a bheil an dearbh fhoillsichear/àireamh shreathach 's a tha aig teisteanas làithreach ach chan e an dearbh theisteanas a tha ann.
sec-error-extra-input = Tha dàta a bharrachd 's gun chleachdadh anns an teachdaireachd a chaidh a chòdachadh a-rèir DER.
sec-error-unsupported-elliptic-curve = Lùb eileapsach gun taic ris.
sec-error-unsupported-ec-point-form = Lùb eileapsach ann am foirm puinge gun taic ris.
sec-error-ocsp-invalid-signing-cert = Teisteanas soidhnidh OCSP neo-dhligheach san fhreagairt OCSP.
sec-error-incompatible-pkcs11 = Tha an draibhear PKCS #11 a' milleadh an t-sònrachais air dòigh neo-chòrdail.
sec-error-no-event = Chan eil tachartas sliotain ùr ri fhaighinn an-dràsta.
sec-error-crl-already-exists = Tha liosta de theisteanasan a chaidh a chùl-ghairm ann mu thràth.
sec-error-not-initialized = Cha deach an NSS a thòiseachadh.
sec-error-token-not-logged-in = Dh'fhàillig an t-obrachadh a chionn 's nach deach an tòcan PKCS #11 a logadh a-steach.
sec-error-ocsp-bad-signature = Tha ainm mì-dhligheach ris an fhreagairt OCSP.
sec-error-out-of-search-limits = Tha rannsachadh dearbhachadh an teisteanais taobh a-muigh raon an rannsachaidh
sec-error-invalid-policy-mapping = Tha anypolicy ann am mapadh a' phoileasaidh
sec-error-policy-validation-failed = Tha slabhraidh nan teisteanas a' fàilligeadh an dearbhachaidh phoileasaidh
sec-error-unknown-aia-location-type = Tha àite de sheòrsa neo-aithnichte ann an leudachan AIA an teisteanais
sec-error-bad-http-response = Thill am frithealaiche droch fhreagairt HTTP
sec-error-bad-ldap-response = Thill am frithealaiche droch fhreagairt LDAP
sec-error-failed-to-encode-data = Dh'fhàillig còdachadh an dàta le còdaichear ASN1
sec-error-bad-info-access-location = Droch àite inntrigeadh fiosrachaidh ann an leudachan an teisteanais
sec-error-pkcs11-general-error = Thill mòideal PKCS #11 CKR_GENERAL_ERROR agus tha seo a' cur 'nar sùilean gun do thachair mearachd nach gabh aiseag.
sec-error-pkcs11-device-error = Thill mòideal PKCS #11 CKR_DEVICE_ERROR agus tha sin a' cur 'nar sùilean gun do dh'èirich duilgheadas ris an tòcan no ris an t-sliotan.
sec-error-bad-info-access-method = Tha dòigh inntrigidh neo-aithnichte do dh'fhiosrachadh ann an leudachan an teisteanais.
sec-error-crl-import-failed = Thachair mearachd nuair a bhathar airson CRL ion-phortadh.
