# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

title = Informazions su le rêt
warning = In fase sperimentâl. Doprâ nome in presince di un adult.
show-next-time-checkbox = Torne a fâ viodi chest avîs la prossime volte
ok = Va ben
http = HTTP
sockets = Sockets
dns = DNS
websockets = WebSockets
refresh = Rinfrescje
auto-refresh = Inzorne ogni 3 seconts
hostname = Non host
port = Puarte:
http2 = HTTP/2
ssl = SSL
active = Ative
idle = Inatîf
host = Servidôr:
tcp = TCP
sent = Mandadis
received = Ricevudis
family = Famee
trr = TRR
addresses = Direzions
expires = Scjât tra (seconts)
messages-sent = Messaçs mandâts
messages-received = Messaçs ricevûts
bytes-sent = Bytes mandâts
bytes-received = Bytes ricevûts
logging = Regjistrazion
log-tutorial = Viôt <a data-l10n-name="logging">HTTP regjistrazion</a> par consultâ lis istruzions sul ûs di chest imprescj.
current-log-file = File di regjistri atuâl:
current-log-modules = Modui di regjistri atuai:
set-log-file = Imposte file di regjistri
set-log-modules = Imposte modui di regjistri
start-logging = Comence regjistri
stop-logging = Ferme regjistri
dns-lookup = Ricercje DNS
dns-lookup-button = Risolf
dns-domain = Domini:
dns-lookup-table-column = IPs
rcwn = Statistichis RCWN
rcwn-status = Stât RCWN
rcwn-cache-won-count = Numar de vitoriis de cache
rcwn-net-won-count = Numar de vitoriis de rêt
total-network-requests = Numar di domandis totâls de rêt
rcwn-operation = Operazion de cache
rcwn-perf-open = Vierç
rcwn-perf-read = Lei
rcwn-perf-write = Scrîf
rcwn-perf-entry-open = Vôs vierç
rcwn-avg-short = Medie curte
rcwn-avg-long = Medie lungje
rcwn-std-dev-long = Deviazion standard lungje
rcwn-cache-slow = Numar di voltis de cache lente
rcwn-cache-not-slow = Numar di voltis de cache no lente
