# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Ekiseera kiweddeyo
openFile = Bikula Fayiro
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Noonya %1$S kulwa "%2$S"
bookmarkAllTabsDefault = [Erinnya ly'etterekero lya fayiro]
crashedpluginsMessage.title = Ekisonsekwamu %S kyizikidde.
crashedpluginsMessage.learnMore = Manya Ebisingawo…
menuOpenAllInTabs.label = Byonna Biggulewo mu Awaddirira
tabHistory.goBack = Ddayo ku muko guno
tabHistory.goForward = Weyongereyo mumaso ku muko gunno
# URL Bar
pasteAndGo.label = Teeka wano & Genda
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Bikakasiddwa: %S
identity.identified.verified_by_you = Ogasse obukuumi obusuffu ku kibanja kino.
identity.identified.state_and_country = %S, %S
safebrowsing.reportedAttackSite = Ekibanja Ekilopeddwa nga Kirebidwa!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Noonya %S
