# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Temps excedit
openFile = Obri fitxer
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Cerca «%2$S» a %1$S
contextMenuSearch.accesskey = C
contextMenuPrivateSearch = Cerca en una finestra privada
contextMenuPrivateSearch.accesskey = f
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Cerca amb %S en una finestra privada
contextMenuPrivateSearchOtherEngine.accesskey = f
bookmarkAllTabsDefault = [Nom de la carpeta]
unsignedAddonsDisabled.message = Un o més complements instal·lats no estan verificats i s'han inhabilitat.
unsignedAddonsDisabled.learnMore.label = Més informació
unsignedAddonsDisabled.learnMore.accesskey = M
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Últim accés %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = Enllaços %S://
crashedpluginsMessage.title = El connector %S ha fallat.
crashedpluginsMessage.reloadButton.label = Torna a carregar la pàgina
crashedpluginsMessage.reloadButton.accesskey = r
crashedpluginsMessage.submitButton.label = Envia un informe de fallada
crashedpluginsMessage.submitButton.accesskey = f
crashedpluginsMessage.learnMore = Més informació…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Potser volíeu anar a %S?
keywordURIFixup.goTo = Sí, vés a %S
keywordURIFixup.goTo.accesskey = S
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Actualitza a la versió %S
update.downloadAndInstallButton.accesskey = A
menuOpenAllInTabs.label = Obri-ho tot en pestanyes
tabHistory.goBack = Vés arrere a esta pàgina
tabHistory.goForward = Vés avant a esta pàgina
# URL Bar
pasteAndGo.label = Apega i vés-hi
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Actualitza la pàgina actual (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Para la càrrega d'esta pàgina (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Reinicia el nivell de zoom (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Activa/desactiva el mode de lectura (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Mostra les adreces d'interés (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Mostra el progrés de les baixades en curs (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Obri una finestra nova (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Obri una pestanya nova (%S)
newTabContainer.tooltip = Obri una pestanya nova (%S)\nManteniu premut per obrir una pestanya de contenidor nova
newTabAlwaysContainer.tooltip = Selecciona un contenidor per obrir una pestanya nova
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Voleu permetre que %S utilitze les vostres dades d'imatge de llenç HTML5?
canvas.siteprompt2.warning = Esta informació es podria utilitzar per identificar inequívocament el vostre ordinador.
canvas.block = Bloca
canvas.block.accesskey = B
canvas.allow2 = Permet
canvas.allow2.accesskey = P
canvas.remember2 = Recorda esta decisió
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Verificat per: %S
identity.identified.verified_by_you = Heu afegit una excepció de seguretat per a este lloc web.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Certificat emés per a: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Insegur
identity.notSecure.tooltip = La connexió no és segura
identity.extension.label = Extensió (%S)
identity.extension.tooltip = Carregat per l'extensió: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Redueix (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Reinicia el nivell de zoom (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Amplia (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Retalla (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Copia (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Apega (%S)
geolocation.allow = Permet
geolocation.allow.accesskey = P
geolocation.block = Bloca
geolocation.block.accesskey = B
geolocation.shareWithSite4 = Voleu permetre que %S accedisca a la vostra ubicació?
geolocation.shareWithFile4 = Voleu permetre que este fitxer local accedisca a la vostra ubicació?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Voleu permetre que %1$S doni permís a %2$S per a accedir a la vostra ubicació?
geolocation.remember = Recorda esta decisió
# Virtual Reality Device UI
xr.allow2 = Permet
xr.allow2.accesskey = P
xr.block = Bloca
xr.block.accesskey = B
xr.shareWithSite4 = Voleu permetre que %S accedisca als dispositius de realitat virtual? Això podria exposar informació confidencial.
xr.shareWithFile4 = Voleu permetre que este fitxer local accedisca als dispositius de realitat virtual? Això podria exposar informació confidencial.
xr.remember = Recorda esta decisió
# Persistent storage UI
persistentStorage.allow = Permet
persistentStorage.allow.accesskey = P
persistentStorage.block.label = Bloca
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Voleu permetre que %S guarde dades en l'emmagatzematge persistent?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Permet
webNotifications.allow2.accesskey = P
webNotifications.notNow = Ara no
webNotifications.notNow.accesskey = n
webNotifications.never = No permetes mai
webNotifications.never.accesskey = m
webNotifications.alwaysBlock = Bloca sempre
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = Bloca
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Voleu permetre que %S envie notificacions?
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Trau-me d'ací!
safebrowsing.getMeOutOfHereButton.accessKey = T
safebrowsing.deceptiveSite = Este lloc pot ser enganyós!
safebrowsing.notADeceptiveSiteButton.label = No és cap lloc enganyós…
safebrowsing.notADeceptiveSiteButton.accessKey = e
safebrowsing.reportedAttackSite = S'ha informat que es tracta d'un lloc atacant!
safebrowsing.notAnAttackButton.label = No és cap lloc atacant…
safebrowsing.notAnAttackButton.accessKey = a
safebrowsing.reportedUnwantedSite = Este lloc pot contindre programari indesitjable!
safebrowsing.reportedHarmfulSite = S'ha informat que el lloc web és maliciós!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Cerca %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Voleu reiniciar el %S en mode de resolució de problemes?
troubleshootModeRestartPromptMessage = Les extensions, els temes i els paràmetres personalitzats s'inhabilitaran temporalment.
troubleshootModeRestartButton = Reinicia
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Esta pàgina fa que el %1$S vagi més lent. Per accelerar el navegador, pareu-la.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Una pàgina web fa que el %1$S vagi més lent. Per accelerar el navegador, pareu-la.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = La pàgina «%1$S» fa que el %2$S vagi més lent. Per accelerar el navegador, pareu-la.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = L'extensió «%1$S» fa que el %2$S vagi més lent. Per accelerar el navegador, pareu-la.
processHang.add-on.learn-more.text = Més informació
processHang.button_stop2.label = Para
processHang.button_stop2.accessKey = P
processHang.button_debug.label = Depura l'script
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Mostra la finestra a pantalla completa (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Col·loca la barra lateral a l'esquerra
sidebar.moveToRight = Col·loca la barra lateral a la dreta
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Cal activar el DRM per reproduir àudio o vídeo d'esta pàgina.
emeNotifications.drmContentDisabled.button.label = Activa el DRM
emeNotifications.drmContentDisabled.button.accesskey = v
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = El %S està instal·lant els components necessaris per reproduir l'àudio o vídeo d'esta pàgina. Torneu-ho a provar més tard.
emeNotifications.unknownDRMSoftware = Desconegut
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Personalitzeu el %S
decoder.noCodecs.button = Vegeu com fer-ho
decoder.noCodecs.accesskey = V
decoder.noCodecsLinux.message = Per reproduir vídeo, potser vos cal instal·lar els còdecs de vídeo necessaris.
decoder.noHWAcceleration.message = Per millorar la qualitat del vídeo, potser vos cal instal·lar el Media Feature Pack de Microsoft.
decoder.noPulseAudio.message = Per reproduir àudio, potser vos cal instal·lar el programari PulseAudio necessari.
decoder.unsupportedLibavcodec.message = libavcodec podria ser vulnerable o incompatible, i cal actualitzar-lo per reproduir vídeo.
decoder.decodeError.message = S'ha produït un error en descodificar un recurs multimèdia.
decoder.decodeError.button = Informa d'un problema amb el lloc
decoder.decodeError.accesskey = I
decoder.decodeWarning.message = S'ha produït un error recuperable en descodificar un recurs multimèdia.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Heu d'iniciar la sessió en esta xarxa per poder accedir a Internet.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Obri la pàgina d'inici de sessió a la xarxa
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Permisos per a %S
permissions.remove.tooltip = Esborra este permís i torna-ho a demanar
permissions.fullscreen.promptCanceled = S'han cancel·lat les sol·licituds de permís pendents: no es poden emetre sol·licituds de permís abans d'entrar en la pantalla completa de DOM.
permissions.fullscreen.fullScreenCanceled = S'ha eixit de la pantalla completa de DOM: no es poden emetre sol·licituds de permís mentre estigueu en la pantalla completa de DOM.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64 bits
aboutDialog.architecture.thirtyTwoBit = 32 bits
midi.allow.label = Permet
midi.allow.accesskey = P
midi.block.label = Bloca
midi.block.accesskey = B
midi.remember = Recorda esta decisió
midi.shareWithFile = Voleu permetre que este fitxer local accedisca als dispositius MIDI?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Voleu permetre que %S accedisca als dispositius MIDI?
midi.shareSysexWithFile = Voleu permetre que este fitxer local accedisca als dispositius MIDI i envie/reba missatges SysEx?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Voleu permetre que %S accedisca als dispositius MIDI i envie/reba missatges SysEx?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Arrere
storageAccess1.Allow.label = Permet
storageAccess1.Allow.accesskey = P
storageAccess1.DontAllow.label = Bloca
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Voleu permetre que %1$S utilitze llurs galetes en %2$S?
storageAccess1.hintText = Si no teniu clar per què %1$S necessita estes dades, podeu blocar l'accés.
