# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Времето истече
openFile = Отвори датотека
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Барај „%2$S“ на %1$S
contextMenuSearch.accesskey = Б
bookmarkAllTabsDefault = [Име на папка]
unsignedAddonsDisabled.learnMore.label = Дознајте повеќе
crashedpluginsMessage.title = Приклучокот %S се урна.
crashedpluginsMessage.reloadButton.label = Превчитај ја страната
crashedpluginsMessage.reloadButton.accesskey = П
crashedpluginsMessage.submitButton.label = Испрати извештај за проблемот
crashedpluginsMessage.submitButton.accesskey = И
crashedpluginsMessage.learnMore = Дознај повеќе…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Мислевте да појдете до %S?
keywordURIFixup.goTo = Да, однеси ме до %S
keywordURIFixup.goTo.accesskey = Д
menuOpenAllInTabs.label = Отвори сè во јазичиња
tabHistory.goBack = Врати се до оваа страница
tabHistory.goForward = Оди напред до оваа страница
# URL Bar
pasteAndGo.label = Залепи и оди
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Превчитај ја страницата (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Запри го вчитувањето на оваа страница (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Ресетирај приказ (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Отвори во нов прозорец (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Отвори во ново јазиче (%S)
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Потврдено од: %S
identity.identified.verified_by_you = Додадовте безбедносен исклучок за ова место
identity.identified.state_and_country = %S, %S
identity.extension.label = Проширување (%S)
identity.extension.tooltip = Вчитано преку проширување: %S
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Копирај (%S)
# Persistent storage UI
persistentStorage.allow = Дозволи
persistentStorage.allow.accesskey = Д
webNotifications.never = Никогаш не дозволувај
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Однеси ме на сигурно!
safebrowsing.getMeOutOfHereButton.accessKey = д
safebrowsing.reportedAttackSite = Напаѓачко место!
safebrowsing.notAnAttackButton.label = Ова не е напаѓачко место…
safebrowsing.notAnAttackButton.accessKey = О
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Пребарај на %S
processHang.add-on.learn-more.text = Дознајте повеќе
emeNotifications.drmContentDisabled.button.label = Овозможи DRM
emeNotifications.unknownDRMSoftware = Непознато
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Прилагодување на %S
decoder.noCodecs.button = Дознајте како
decoder.noCodecs.accesskey = Д
decoder.decodeError.button = Пријави проблем со мрежно место
decoder.decodeError.accesskey = П
permissions.remove.tooltip = Одземи ја оваа дозвола и прашај повторно
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-битен
aboutDialog.architecture.thirtyTwoBit = 32-битен
