# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Sprievodca importom
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-nothing =
    .label = Nič neimportovať
    .accesskey = r
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-360se =
    .label = 360 Secure Browser
    .accesskey = 3
no-migration-sources = Nebol nájdený žiadny program, ktorý by obsahoval záložky, históriu alebo uložené heslá.
import-source =
    .label = Import nastavení a údajov
import-items-title =
    .label = Položky na import
import-migrating-title =
    .label = Importuje sa…
import-migrating-description = Práve sa importujú tieto položky…
import-select-profile-title =
    .label = Výber profilu
import-select-profile-description = Importovať možno tieto profily:
import-done-description = Úspešne boli importované tieto položky:
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Secure Browser
imported-safari-reading-list = Zoznam na prečítanie (zo Safari)
imported-edge-reading-list = Zoznam na prečítanie (z Microsoft Edge)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-360se-1 =
    .label = Nastavenia
    .value = Nastavenia
browser-data-ie-2 =
    .label = Súbory cookies
    .value = Súbory cookies
browser-data-edge-2 =
    .label = Súbory cookies
    .value = Súbory cookies
browser-data-safari-2 =
    .label = Súbory cookies
    .value = Súbory cookies
browser-data-chrome-2 =
    .label = Súbory cookies
    .value = Súbory cookies
browser-data-canary-2 =
    .label = Súbory cookies
    .value = Súbory cookies
browser-data-firefox-2 =
    .label = Súbory cookies
    .value = Súbory cookies
browser-data-360se-2 =
    .label = Súbory cookies
    .value = Súbory cookies
browser-data-chrome-4 =
    .label = História prehliadania
    .value = História prehliadania
browser-data-canary-4 =
    .label = História prehliadania
    .value = História prehliadania
browser-data-firefox-history-and-bookmarks-4 =
    .label = História prehliadania a záložky
    .value = História prehliadania a záložky
browser-data-360se-4 =
    .label = História prehliadania
    .value = História prehliadania
browser-data-ie-8 =
    .label = Údaje zadané do formulárov
    .value = Údaje zadané do formulárov
browser-data-edge-8 =
    .label = Údaje zadané do formulárov
    .value = Údaje zadané do formulárov
browser-data-safari-8 =
    .label = Údaje zadané do formulárov
    .value = Údaje zadané do formulárov
browser-data-chrome-8 =
    .label = Údaje zadané do formulárov
    .value = Údaje zadané do formulárov
browser-data-canary-8 =
    .label = Údaje zadané do formulárov
    .value = Údaje zadané do formulárov
browser-data-firefox-8 =
    .label = Údaje zadané do formulárov
    .value = Údaje zadané do formulárov
browser-data-360se-8 =
    .label = Údaje zadané do formulárov
    .value = Údaje zadané do formulárov
browser-data-ie-16 =
    .label = Uložené heslá
    .value = Uložené heslá
browser-data-edge-16 =
    .label = Uložené heslá
    .value = Uložené heslá
browser-data-safari-16 =
    .label = Uložené heslá
    .value = Uložené heslá
browser-data-chrome-16 =
    .label = Uložené heslá
    .value = Uložené heslá
browser-data-canary-16 =
    .label = Uložené heslá
    .value = Uložené heslá
browser-data-firefox-16 =
    .label = Uložené heslá
    .value = Uložené heslá
browser-data-360se-16 =
    .label = Uložené heslá
    .value = Uložené heslá
browser-data-ie-32 =
    .label = Obľúbené položky
    .value = Obľúbené položky
browser-data-edge-32 =
    .label = Obľúbené položky
    .value = Obľúbené položky
browser-data-safari-32 =
    .label = Záložky
    .value = Záložky
browser-data-chrome-32 =
    .label = Záložky
    .value = Záložky
browser-data-canary-32 =
    .label = Záložky
    .value = Záložky
browser-data-360se-32 =
    .label = Záložky
    .value = Záložky
browser-data-ie-64 =
    .label = Iné údaje
    .value = Iné údaje
browser-data-edge-64 =
    .label = Iné údaje
    .value = Iné údaje
browser-data-safari-64 =
    .label = Iné údaje
    .value = Iné údaje
browser-data-chrome-64 =
    .label = Iné údaje
    .value = Iné údaje
browser-data-canary-64 =
    .label = Iné údaje
    .value = Iné údaje
browser-data-firefox-other-64 =
    .label = Iné údaje
    .value = Iné údaje
browser-data-360se-64 =
    .label = Iné údaje
    .value = Iné údaje
browser-data-firefox-128 =
    .label = Okná a karty
    .value = Okná a karty
