# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = Sprievodca importom
import-from =
    { PLATFORM() ->
        [windows] Importovať nastavenia, záložky, históriu, heslá a ostatné údaje z aplikácie:
       *[other] Importovať nastavenia, záložky, históriu, heslá a ostatné údaje z aplikácie:
    }
import-from-bookmarks = Importovať záložky z aplikácie:
import-from-ie =
    .label = Microsoft Internet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-edge-legacy =
    .label = Microsoft Edge Legacy
    .accesskey = L
import-from-edge-beta =
    .label = Microsoft Edge Beta
    .accesskey = d
import-from-nothing =
    .label = Nič neimportovať
    .accesskey = r
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chrome-beta =
    .label = Chrome Beta
    .accesskey = B
import-from-chrome-dev =
    .label = Chrome Dev
    .accesskey = D
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = x
import-from-360se =
    .label = 360 Secure Browser
    .accesskey = 3
no-migration-sources = Nebol nájdený žiadny program, ktorý by obsahoval záložky, históriu alebo uložené heslá.
import-source =
    .label = Import nastavení a údajov
import-items-title =
    .label = Položky na import
import-items-description = Vyberte položky, ktoré chcete importovať:
import-migrating-title =
    .label = Importuje sa…
import-migrating-description = Práve sa importujú tieto položky…
import-select-profile-title =
    .label = Výber profilu
import-select-profile-description = Importovať možno tieto profily:
import-done-title =
    .label = Import bol dokončený
import-done-description = Úspešne boli importované tieto položky:
import-close-source-browser = Pred pokračovaním sa uistite, že vybraný prehliadač nie je spustený.
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = Z prehliadača { $source }
source-name-ie = Internet Explorer
source-name-edge = Microsoft Edge
source-name-edge-beta = Microsoft Edge Beta
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chrome-beta = Google Chrome Beta
source-name-chrome-dev = Google Chrome Dev
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Secure Browser
imported-safari-reading-list = Zoznam na prečítanie (zo Safari)
imported-edge-reading-list = Zoznam na prečítanie (z Microsoft Edge)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = Možnosti internetu
    .value = Možnosti internetu
browser-data-edge-1 =
    .label = Nastavenia
    .value = Nastavenia
browser-data-safari-1 =
    .label = Nastavenia
    .value = Nastavenia
browser-data-chrome-1 =
    .label = Nastavenia
    .value = Nastavenia
browser-data-canary-1 =
    .label = Nastavenia
    .value = Nastavenia
browser-data-360se-1 =
    .label = Nastavenia
    .value = Nastavenia
browser-data-ie-2 =
    .label = Súbory cookies
    .value = Súbory cookies
browser-data-edge-2 =
    .label = Súbory cookies
    .value = Súbory cookies
browser-data-safari-2 =
    .label = Súbory cookies
    .value = Súbory cookies
browser-data-chrome-2 =
    .label = Súbory cookies
    .value = Súbory cookies
browser-data-canary-2 =
    .label = Súbory cookies
    .value = Súbory cookies
browser-data-firefox-2 =
    .label = Súbory cookies
    .value = Súbory cookies
browser-data-360se-2 =
    .label = Súbory cookies
    .value = Súbory cookies
browser-data-ie-4 =
    .label = História prehliadania
    .value = História prehliadania
browser-data-edge-4 =
    .label = História prehliadania
    .value = História prehliadania
browser-data-safari-4 =
    .label = História prehliadania
    .value = História prehliadania
browser-data-chrome-4 =
    .label = História prehliadania
    .value = História prehliadania
browser-data-canary-4 =
    .label = História prehliadania
    .value = História prehliadania
browser-data-firefox-history-and-bookmarks-4 =
    .label = História prehliadania a záložky
    .value = História prehliadania a záložky
browser-data-360se-4 =
    .label = História prehliadania
    .value = História prehliadania
browser-data-ie-8 =
    .label = Údaje zadané do formulárov
    .value = Údaje zadané do formulárov
browser-data-edge-8 =
    .label = Údaje zadané do formulárov
    .value = Údaje zadané do formulárov
browser-data-safari-8 =
    .label = Údaje zadané do formulárov
    .value = Údaje zadané do formulárov
browser-data-chrome-8 =
    .label = Údaje zadané do formulárov
    .value = Údaje zadané do formulárov
browser-data-canary-8 =
    .label = Údaje zadané do formulárov
    .value = Údaje zadané do formulárov
browser-data-firefox-8 =
    .label = Údaje zadané do formulárov
    .value = Údaje zadané do formulárov
browser-data-360se-8 =
    .label = Údaje zadané do formulárov
    .value = Údaje zadané do formulárov
browser-data-ie-16 =
    .label = Uložené heslá
    .value = Uložené heslá
browser-data-edge-16 =
    .label = Uložené heslá
    .value = Uložené heslá
browser-data-safari-16 =
    .label = Uložené heslá
    .value = Uložené heslá
browser-data-chrome-16 =
    .label = Uložené heslá
    .value = Uložené heslá
browser-data-canary-16 =
    .label = Uložené heslá
    .value = Uložené heslá
browser-data-firefox-16 =
    .label = Uložené heslá
    .value = Uložené heslá
browser-data-360se-16 =
    .label = Uložené heslá
    .value = Uložené heslá
browser-data-ie-32 =
    .label = Obľúbené položky
    .value = Obľúbené položky
browser-data-edge-32 =
    .label = Obľúbené položky
    .value = Obľúbené položky
browser-data-safari-32 =
    .label = Záložky
    .value = Záložky
browser-data-chrome-32 =
    .label = Záložky
    .value = Záložky
browser-data-canary-32 =
    .label = Záložky
    .value = Záložky
browser-data-360se-32 =
    .label = Záložky
    .value = Záložky
browser-data-ie-64 =
    .label = Iné údaje
    .value = Iné údaje
browser-data-edge-64 =
    .label = Iné údaje
    .value = Iné údaje
browser-data-safari-64 =
    .label = Iné údaje
    .value = Iné údaje
browser-data-chrome-64 =
    .label = Iné údaje
    .value = Iné údaje
browser-data-canary-64 =
    .label = Iné údaje
    .value = Iné údaje
browser-data-firefox-other-64 =
    .label = Iné údaje
    .value = Iné údaje
browser-data-360se-64 =
    .label = Iné údaje
    .value = Iné údaje
browser-data-firefox-128 =
    .label = Okná a karty
    .value = Okná a karty
