# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = Otvoriť
    .accesskey = O
places-open-tab =
    .label = Otvoriť na novej karte
    .accesskey = v
places-open-all-in-tabs =
    .label = Otvoriť všetko na kartách
    .accesskey = k
places-open-window =
    .label = Otvoriť v novom okne
    .accesskey = m
places-open-private-window =
    .label = Otvoriť v novom súkromnom okne
    .accesskey = s
places-new-bookmark =
    .label = Nová záložka…
    .accesskey = N
places-new-folder-contextmenu =
    .label = Nový priečinok…
    .accesskey = r
places-new-folder =
    .label = Nový priečinok…
    .accesskey = o
places-new-separator =
    .label = Nový oddeľovač
    .accesskey = d
places-view =
    .label = Zobraziť
    .accesskey = b
places-by-date =
    .label = podľa dátumu
    .accesskey = d
places-by-site =
    .label = podľa názvu stránky
    .accesskey = s
places-by-most-visited =
    .label = podľa počtu návštev
    .accesskey = v
places-by-last-visited =
    .label = podľa poslednej návštevy
    .accesskey = l
places-by-day-and-site =
    .label = podľa dátumu a názvu stránky
    .accesskey = t
places-delete-domain-data =
    .label = Zabudnúť na túto stránku
    .accesskey = b
places-sortby-name =
    .label = Usporiadať podľa názvu
    .accesskey = r
places-properties =
    .label = Vlastnosti
    .accesskey = i
