# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Talɣut ɣef izerfan-ik
rights-intro = { -brand-full-name } d aseɣẓan ilelli yeldin, mahlent yifḍan n imţekkiyen deg umaḍal. Atan wayen issefk ad teẓreḍ:
rights-intro-point-1 = { -brand-short-name } yellan akken llant tiskarin n<a data-l10n-name="mozilla-public-license-link">Turagt tazayezt n Mozilla</a>. Aya yebɣa ad d-yini tzemreḍ ad tqedceḍ, ad tneɣleḍ u ad tzuzreḍ { -brand-short-name } i wiyaḍ.  Tzemreḍ daɣen ad tesnifleḍ tangalt aɣbalu n { -brand-short-name } akken tesriḍ. Turagt tazayezt n Mozilla ad k-teǧǧ daɣen ad tzuzreḍ ileqman ittusniflen.
rights-intro-point-3 = Kra n tmahilin deg { -brand-short-name } am uneqqis n uɣelluy, ad k-yeǧǧ ad d-terreḍ talɣut i { -vendor-short-name }. Ma tferneḍ ad tazneḍ tilɣa-yagi, ad tmuddeḍ i { -vendor-short-name } tasiregt n useqdec n telɣut-agi n tririt akken ad isnerni ifarisen- ines, ad isuffeɣ tiririt-agi ɣef yesmal-ines web, u ad ten-imudd i wiyaḍ.
rights-intro-point-5 = Kra n temhalin n { -brand-short-name } seqdacent tanfiwin n telɣut ɣef Web; acu kan, ur nezmir ara aneḍmen ɣer 100% d akken ur gbirent ara tuccḍiwin. Tzemreḍ ad tafeḍ talɣut leqqayen, ula d talɣut ɣef urermed n tanfiwin di <a data-l10n-name="mozilla-service-terms-link">Tiwtilin n useqdec</a>.
rights-webservices = { -brand-full-name } iseqdac tanfiwin n telɣut Web  ("Services") akken ad k-d-imudd kra n temhalin di lqem-agi imsin n { -brand-short-name } akken d-ittwaskan daw-a. Ma tebɣiḍ ur teseqdaceḍ ara yiwet si tanfiwin-agi neɣ ma tebɣiḍ ur tqebleḍ ara tiwtilin-agi, tzemreḍ ad tekkseḍ armad n temhalt neɣ tanfa. Ma ulac aɣilif, wali:<a data-l10n-name="mozilla-disable-service-link">dagi</a>Tzemreḍ ad tekkseḍ armad n timahilin d tanfiwin-nniḍen deg ismenyifen n usnas.
rights-webservices-term-unbranded = Issefk akk tisertiyin n tbaḍnit ittusnasen ɣef useɣẓan-agi ad ttwabedrent dagi.
rights-webservices-term-1 = { -vendor-short-name } d imttekiyen-ines, imuragen, d imendiden mahalen akken ad farasen tanfiwin tufrinin u d timaynutin. Acu kan, ur nezmir ara ad neḍmen d akken talɣut-agi ad tili leqqayet neɣ ur ɣur-s ara tucḍiwin. Amedya, tanfa n usewḥel n yir isemlen web tezmer ur tessawaḍ ara ad temmel kra n isemlen iweɛren neɣ ad tecceḍ di kra deg-sen yellan d iɣelsanen. Ayen-nniḍen, akk adigen yettwamlen sɣuṛ tanfa n usideg n tirakalt d asteg kan, mačči d nekkni neɣ isaǧǧawen n tanfa a yizmiren ad ḍemnen tisseddi-nsen.
rights-webservices-term-3 = Ansuf yiss-k ɣeṛ useqdec n tanfiwin-agi s lqem n { -brand-short-name } i tent-id-iseglan, u { -vendor-short-name } ad k-iḍmen izerfan isran. { -vendor-short-name } d imuragen-ines ḥeṛṛen akk izerfan-nniḍen n uselkin di tanfiwin. Tiwtilin-agi ur llint ara akken ad errent tilisa i yizarfan id-fkan iselkan n useɣẓan ilelli ittusnasen ɣef { -brand-short-name } neɣ ɣef tengalt taɣbalut n ileqman n { -brand-short-name }.
rights-webservices-term-4 = <strong>Tanfiwin ttunefkent "am kken." { -vendor-short-name }, imttekkiyen-is, imuragen d iwziwzayen, ur ittak ara asdem, ama s wudem aflalay neɣ araflalay, ula s war talast, isedman anida tanfa tezmer ad tettwazenz u ad tettuserwes akken llan wasaren-inek. Ad tawiḍ akk tamasit n ufran n tanfiwinn wayen tesriḍ, taɣaṛa, neɣ tamellit n tanfiwin. Kra n isuḍaf ur sirigen ara tukksa neɣ tiggin n talast n isedman iraflalayen, ihi tawtilit-agi n war asdem ur tettusnas ara fell-ak.</strong>
