#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're 

# live.


#define bookmarks_title বুকমার্ক


#define bookmarks_heading বুকমার্ক


# LOCALIZATION NOTE (bookmarks_addons):


# link title for https://en-US.add-ons.mozilla.com/en-US/firefox/bookmarks/


#define bookmarks_addons বুকমার্কের অতিরিক্ত সামগ্রী প্রাপ্ত হোন


#define bookmarks_toolbarfolder টুলবার ফোল্ডার বুকমার্ক করে


#define bookmarks_toolbarfolder_description বুকমার্ক টুলবারে দেখার জন্য এই ফোল্ডারে বুকমার্ক দিন


# LOCALIZATION NOTE (getting_started):


# link title for http://en-US.www.mozilla.com/en-US/firefox/central/


#define getting_started প্রথমবার শুরু করার সময়


# LOCALIZATION NOTE (latest_headlines):


# link title for the live bookmarks sample, a redirect on


# http://en-US.fxfeeds.mozilla.com/en-US/firefox/headlines.xml


# Changing the redirect is subject to approval of l10n-drivers.


#define latest_headlines সাম্প্রতিক শিরোনামসমূহ


# LOCALIZATION NOTE (firefox_heading):


# Firefox links folder name


#define firefox_heading মজিলা ফায়ারফক্স


# LOCALIZATION NOTE (firefox_help):


# link title for http://en-US.www.mozilla.com/en-US/firefox/help/


#define firefox_help সাহায্য এবং টিউটোরিয়াল


# LOCALIZATION NOTE (firefox_customize):


# link title for http://en-US.www.mozilla.com/en-US/firefox/customize/


#define firefox_customize ফায়ারফক্স কাস্টোমাইজ করুন


# LOCALIZATION NOTE (firefox_community):


# link title for http://en-US.www.mozilla.com/en-US/firefox/community/


#define firefox_community যুক্ত হোন


# LOCALIZATION NOTE (firefox_about):


# link title for http://en-US.www.mozilla.com/en-US/firefox/about/


#define firefox_about আমাদের সম্পর্কে


#unfilter emptyLines
