# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host }-നായി തിരയുന്നു...
network-connection-status-connected = { $host }-ലേക്ക് കണക്ട് ചെയ്തിരിക്കുന്നു...
network-connection-status-sending-request = { $host }-ലേക്ക് ആവശ്യം അറിയിക്കുന്നു...
network-connection-status-transferring-data = { $host }-ല്‍ നിന്നും ഡേറ്റാ നീക്കുന്നു...
network-connection-status-connecting = { $host }-ലേക്ക് കണക്ട് ചെയ്തിരിക്കുന്നു...
network-connection-status-read = { $host }  വായിക്കുക
network-connection-status-wrote = { $host } എഴുതിയിരിക്കുന്നു
network-connection-status-waiting = { $host }-നായി കാത്തിരിക്കുന്നു...
network-connection-status-looked-up = { $host } തെരയുന്നു…
