# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Ñeel say àq
rights-intro = { -brand-full-name } jëfekaay bu kenn moomul te ubbeeku la, ñi ko defar ay téemeéri nit lañu ci àdduna bépp. Am na lenn loo ci war a xam:
rights-intro-point-1 = { -brand-short-name } mi ngi jàppandi ci anami <a data-l10n-name="mozilla-public-license-link">Mozilla Public License</a>. Lii dafay wone ni man nga jëfandikoo, duppi ak tasaare { -brand-short-name }. Man nga itam soppi yoonu gongikuwaayu { -brand-short-name } ci sa coobare. Sañal gu Mozilla may na la nga tasaare sumb yi nga soppi.
rights-intro-point-3 = Am na ay solo ci { -brand-short-name }, niki yëgalekaayu taxaw bi, di na la may nga yónnee ag tontu { -vendor-short-name }. Boo taamoo yónnee tontu gi, mooy ne sañal nga { -vendor-short-name } muy jëfandikoo tontu gi ngir gën a baaxal mbir mi, siiwal tontu yi ci dali webam yi, te it ak di wesaare tontu yi.
rights-intro-point-4 = Ni ñuy jëfandikoo say xibaari bopp ak tontu gi ngay yónnee { -vendor-short-name } ci ndimbalu { -brand-short-name } ñi ngi koy faramfàcce ci <a data-l10n-name="mozilla-privacy-policy-link">Politigu sutura bu { -brand-short-name }</a>.
rights-intro-point-5 = Yenn solo yu { -brand-short-name } dañuy faral a jëfandikooy xibaar yu nekk ci web bi, ba tax, maneesul a wax ci lu wóor 100 % ne amuñuy njuumte. Yeneeni xibaar, bokk nañ ci nan nga man a doxadil solo yiy jëfandikoo yooyu xibaar, manees na leen gis ci <a data-l10n-name="mozilla-service-terms-link">anami njëfandikoo gi</a>.
rights-intro-point-5-unbranded = Su fekkee xeltéef bi dugal na sarwiis web, aanamau jëfandikoo yépp te ñu mëñ leen jëfe ngir benn walla ay sarwiis war nañu jappaloo ak seksiyoŋ bi <a data-l10n-name="mozilla-website-services-link">Sarwiisi dalub web yi</a> seksiyoŋ.
rights-intro-point-6 = Ngir man a taal yenn xeeti ëmbéefi wideo, { -brand-short-name } dafay yebbe feneen yenn ciy yokkéef yuy tekki ëmbéef.
rights-webservices = { -brand-full-name } dafay jëfandikoo ay joxekaayu xibaar yu web ngir man di joxe yenn ci solo yees la jébbal ak bii sumb bu { -brand-short-name } ci anam yiñ la biral sànk. Soo bëggul jëfandikoo yenn ci yooyu joxekaayu xibaar walla nga jàpp ne anam yees la biral sànk jaaduwuñ, man ngaa doxadil yooyu solo. Ay tektal ci naka lees man a doxadilee senn solo si man nga koo gis ci <a data-l10n-name="mozilla-disable-service-link">fii</a>. Yeneen solo yi man nga leen doxadilee ci jekk-jekkaluwaayu Jëfekaay bi.
rights-locationawarebrowsing = <strong>Joow ci fi nga dëkke : </strong>mi ngiy am soo ko laajee. Amul benn xibaar ci fi nga dëkk bu ñuy yonnee te du si sa ndigal. Soo bëggee suuxal doxalin lépp toppal tektal yii :
rights-locationawarebrowsing-term-1 = Ci banqaasu màkkaan tappeel<code>ci mbiri:config</code>
rights-locationawarebrowsing-term-2 = Wut ci geo.enabled
rights-webservices-unbranded = Fii war na am noo gise sarwisi dalub web yi and ak xeltéef bi, and ak ay tektal ci naka lañu leen di suuxalee bu waree ne.
rights-webservices-term-2 = { -vendor-short-name } mën na taxawal walla soppi Sarwiis yi ni mu ko neexe.
rights-webservices-term-3 = Mën jëfandikoo sarwiis yi ànd ak sumbu { -brand-short-name } te { -vendor-short-name } mën na la gaarantil ay sañ sañ yi tax nga mën ko def. { -vendor-short-name } ak ñi ñu jox yaatal jël nañu yeneen sañ sañ yépp ci sarwiis yi. Doxal yii nak du caageenu wutal app sañ sañi xeltéef yi amul moomeel te taq ci { -vendor-short-name } ak suulaale cosaan yu sumb yi and ak { -vendor-short-name }.
rights-webservices-term-4 = <strong>Liggéey yi "niki nii" lees leen di jébbale. { -vendor-short-name }, ay cërukatam, sañalkat aki séddalekat, joxewuñ ci genn wóoral, muy lees bind walla pattaaral, bokk nañ ci ci lu amul dig, wóoral yi ni Liggéey yi manees na leen jaay te man nañoo faj say soxla. Yaay gàddu bépp tukkéef ci tànn Liggéey yi nga soxla, seen baaxaay ak gaawaay. Ci yenn yoon yi dañuy tere ku dàq walla digal wóoral yees pattaaral, kon wàll woowu man naa bañ a dox ci yaw.</strong>
