# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# String will be replaced by brandShortName.
saveLogin = Дали би сакале %S да го запамети ова пријавување?
rememberButton = Запамети
neverButton = Никогаш
# String is the login's hostname
updatePassword = Ажурирај ја снимената лозинка за %S?
updatePasswordNoUser = Ажурирај ја снимената лозинка за ова пријавување?
updateButton = Ажурирај
dontUpdateButton = Не ажурирај
# Copy of the toolkit's passwordmgr.properties
userSelectText2 = Изберете пријава за ажурирање:
passwordChangeTitle = Потврдување на промената на лозинката
# Strings used by PromptService.js
username = Корисничко име
password = Лозинка
