#filter emptyLines
#define MOZ_LANGPACK_CREATOR mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Rajesh Ranjan (mozilla hindi coordinator, email: rajeshkajha@yahoo.com) </em:contributor> <em:contributor>Vaibhav Agarwal, Matrubhasha Team</em:contributor><em:contributor>Ashishi Gupta, Matrubhasha Team</em:contributor>

#unfilter emptyLines