# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

savePasswordTitle = قوۊل
saveLoginButtonAllow.label = زفت
saveLoginButtonDeny.label = زفت نکۊنین
saveLoginButtonDeny.accesskey = ز
saveLoginButtonNever.label = هرگشت زفت مکوݩ
insecureFieldWarningLearnMore = قلوه دووسته بۊین
