# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

savePasswordTitle = قوۊل
# LOCALIZATION NOTE (saveLoginMsg2, saveLoginMsgNoUser2):
# %S is the login's hostname.
saveLoginMsg2 = زفت کردن و من ٱووڌن سی %S؟
saveLoginMsgNoUser2 = زفت کردن رزم سی %S؟
saveLoginButtonAllow.label = زفت
saveLoginButtonAllow.accesskey = ز
saveLoginButtonDeny.label = زفت نکۊنین
saveLoginButtonDeny.accesskey = ز
saveLoginButtonNever.label = هرگشت زفت مکوݩ
saveLoginButtonNever.accesskey = e
# LOCALIZATION NOTE (updateLoginMsg3, updateLoginMsgNoUser3):
# %S is the login's hostname.
updateLoginMsg3 = ورۊ رسۊوی و من ٱووڌن سی %S؟
updateLoginMsgNoUser3 = ورۊ رسۊوی رزم سی %S؟
updateLoginButtonText = ورۊ رسۊوی
updateLoginButtonAccessKey = U
updateLoginButtonDeny.label = ورۊ رسۊوی نبۊوه
updateLoginButtonDeny.accesskey = و
# LOCALIZATION NOTE (noUsernamePlaceholder):
# This is displayed in place of the username when it is missing.
noUsernamePlaceholder = بؽ نوم منتوری
togglePasswordLabel = نشووݩ داڌن رزم
togglePasswordAccessKey2 = h
notNowButtonText = سکو &ن
# LOCALIZATION NOTE (loginHostAge):
# This is used to show the context menu login items with their age.
# 1st string is the username for the login, 2nd is the login's age.
loginHostAge = %1$S (%2$S)
# LOCALIZATION NOTE (noUsername):
# String is used on the context menu when a login doesn't have a username.
noUsername = بؽ نوم منتوری
# LOCALIZATION NOTE (displaySameOrigin):
# String is used on the autocomplete row when the login origin is a domain match with the document origin
displaySameOrigin = ز ای وبگه
insecureFieldWarningLearnMore = قلوه دووسته بۊین
# LOCALIZATION NOTE (managePasswords.label):
# This label is used in the footer of login autocomplete menus.
managePasswords.label = دؽوۉداری رزما
