# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Yakon taq kitikirib'al molojri'ïl
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-provider-url-cmd =
    .label = Tiwachib'ëx URL
    .accesskey = w
copy-username-cmd =
    .label = Tiwachib'ëx Winäq
    .accesskey = W
edit-username-cmd =
    .label = Tinuk' rub'i' Winäq
    .accesskey = n
copy-password-cmd =
    .label = Tiwachib'ëx Ewan Tzij
    .accesskey = w
edit-password-cmd =
    .label = Tinuk' Ewan Tzij
    .accesskey = n
search-filter =
    .accesskey = K
    .placeholder = Kanoxïk
column-heading-provider =
    .label = Ajya'öl
column-heading-username =
    .label = Rub'i' winäq
column-heading-password =
    .label = Ewan tzij
column-heading-time-created =
    .label = Nab'ey mul okisan
column-heading-time-last-used =
    .label = Ruk'isib'äl mul okisan
column-heading-time-password-changed =
    .label = Ruk'isib'äl Mul Jalwachin
column-heading-times-used =
    .label = Taq Mul Okisan
remove =
    .label = Tiyuj
    .accesskey = y
import =
    .label = Tijik' pe…
    .accesskey = j
close-button =
    .label = Titz'apïx
    .accesskey = z
show-passwords =
    .label = Kek'ut ri Ewan taq Tzij
    .accesskey = E
hide-passwords =
    .label = Ke'ewäx ri Ewan taq Tzij
    .accesskey = E
logins-description-all = Ri kitikirib'al moloj re taq ajya'öl re' yeyak pan akematz'ib'
logins-description-filtered = Re jujun kitikirib'al molojri'ïl re', nikik'äm ki' rik'in ri nakanoj:
remove-all =
    .label = Keyuj Konojel
    .accesskey = o
remove-all-passwords-prompt = ¿At jikïl chi nawajo' ye'ayüj el konojel ri ewan taq tzij?
remove-all-passwords-title = Keyuj konojel ri ewan taq tzij
no-master-password-prompt = ¿La at jikïl chi nawajo' ye'ak'üt pe ri ewan taq atzij?
