# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = يتمّ إعادة توجيه هذه الصّفحة إلى موقع جديد. هل تريد إعادة إرسال بيانات الاستمارة التي أدخلتها إلى الموقع الجّديد؟
# Directory listing strings
DirTitle = فهرس %1$S
DirGoUp = فوق إلى المجلد ذي المستوى الأعلى
ShowHidden = اعرض الكائنات المخفية
DirColName = الاسم
DirColSize = الحجم
DirColMTime = آخر تعديل
DirFileLabel = ملف:\u0020
UnsafeUriBlocked = الموْرِد في ”%1$S“ حجبه التصفح الآمن.
CookieBlockedByPermission = مُنع طلب الوصول إلى الكعكات أو التخزين في ”%1$S“ بسبب تصريح الكعكات المخصّص.
# LOCALIZATION NOTE (CookieAllowedForOriginByStorageAccessAPI): %2$S and %1$S are URLs.
CookieAllowedForOriginByStorageAccessAPI = مُنح حق الوصول إلى التخزين للمصدر “%2$S” في “%1$S”.
# LOCALIZATION NOTE (CookieAllowedForOriginByHeuristic): %2$S and %1$S are URLs.
CookieAllowedForOriginByHeuristic = مُنح حق الوصول إلى التخزين تلقائيًا للمصدر “%2$S” في “%1$S”.
