# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = සුරකින්න
dialogTitleAddBookmark = නව පොත්යොමුව
dialogTitleAddMulti = නව පොත්යොමු
dialogTitleEdit = “%S” සඳහා ගුණාංග
dialogTitleAddNewBookmark2 = පොත්යොමුවක් තබන්න
dialogTitleEditBookmark = “%S” සංස්කරණය
dialogTitleEditBookmark2 = පොත්යොමුව සංස්කරණය‍
dialogTitleAddBookmarkFolder = පොත්යොමු බහාලුමක් එක් කරන්න
dialogTitleEditBookmarkFolder = පොත්යොමු බහාලුම සංස්කරණය
bookmarkAllTabsDefault = [බහාලුමේ නම]
newFolderDefault = නව බහාලුම
newBookmarkDefault = නව පොත්යොමුව
