#filter emptyLines

#define MOZ_LANGPACK_CREATOR L’équipe FrenchMozilla

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Frédéric Chateaux</em:contributor><em:contributor>Cédric Corazza</em:contributor><em:contributor>Philippe Dessante</em:contributor><em:contributor>Benoît Leseul</em:contributor>


#unfilter emptyLines
