# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

print-setup =
    .title = Tero Pot Buk
custom-prompt-prompt = Ket yik nyig coc mamegi me lawie/late
format-group-label =
    .value = Yore me waraga
orientation-label =
    .value = Kagwoko coc acoya pi agoa:
portrait =
    .label = Cal me wie
    .accesskey = C
landscape =
    .label = Ma labuto
    .accesskey = M
scale =
    .label = Lapim:
    .accesskey = L
shrink-to-fit =
    .label = Jwik wek odony i pot buk Borne
    .accesskey = B
options-group-label =
    .value = Me ayera
margin-group-label-metric =
    .value = Twoke (milimita)
margin-top =
    .value = Wie:
    .accesskey = W
margin-top-invisible =
    .value = Wie:
margin-bottom =
    .value = Te:
    .accesskey = T
margin-bottom-invisible =
    .value = Te:
margin-left =
    .value = Tung acam:
    .accesskey = T
margin-left-invisible =
    .value = Tung acam:
margin-right =
    .value = Tung acuc:
    .accesskey = T
margin-right-invisible =
    .value = Tung acuc:
hf-left-label =
    .value = Tung acam:
hf-center-label =
    .value = Dyere:
hf-right-label =
    .value = Acuc:
header-left-tip =
    .tooltiptext = Lawie me tung acam
header-center-tip =
    .tooltiptext = Lawie me dyere
header-right-tip =
    .tooltiptext = Lawie me tung acuc
footer-left-tip =
    .tooltiptext = Late me tung acam
footer-center-tip =
    .tooltiptext = Late me dyere
footer-right-tip =
    .tooltiptext = Late me tung acuc
hf-blank =
    .label = --blank--
hf-title =
    .label = Wie madito
hf-url =
    .label = URL
hf-date-and-time =
    .label = Nino dwe/Cawa
hf-page =
    .label = Pot buk #
hf-page-and-total =
    .label = Pot buk # me #
print-preparing =
    .value = Yube…
print-window =
    .title = Goyo
print-complete =
    .value = Otyeko goyo coc.
dialog-close-label = Lor
