# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Considerare attendibile “%S” per i seguenti utilizzi?
unnamedCA = Autorità di certificazione (senza nome)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Inserire la password utilizzata per crittare la copia di backup di questo certificato.
# Page Info
pageInfo_NoEncryption = Connessione non crittata
pageInfo_Privacy_None1 = Il sito %S non supporta la crittazione per la pagina visualizzata.
pageInfo_Privacy_None2 = Le informazioni non crittate trasmesse attraverso Internet possono essere intercettate da terzi durante il transito.
pageInfo_Privacy_None4 = La pagina visualizzata non è stata crittata prima della trasmissione via Internet.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Connessione crittata (%1$S, chiavi a %2$S bit, %3$S)
pageInfo_BrokenEncryption = Crittazione non funzionante (%1$S, chiavi a %2$S bit, %3$S)
pageInfo_Privacy_Encrypted1 = La pagina visualizzata è stata crittata prima della trasmissione via Internet.
pageInfo_Privacy_Encrypted2 = La crittazione rende difficile osservare le informazioni scambiate tra computer a persone non autorizzate. È quindi improbabile che qualcuno sia riuscito a leggere il contenuto di questa pagina durante il transito attraverso la rete.
pageInfo_MixedContent = Connessione parzialmente crittata
pageInfo_MixedContent2 = Alcuni elementi della pagina che si sta visualizzando non sono stati crittati prima della trasmissione via Internet.
pageInfo_WeakCipher = La connessione con questo sito web utilizza una crittografia debole e non è privata. Altre persone potrebbero visualizzare le informazioni trasmesse o modificare il comportamento del sito.
pageInfo_CertificateTransparency_Compliant = Questo sito web è conforme ai criteri di controllo per la trasparenza dei certificati.
# Token Manager
password_not_set = (non impostata)
