# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Lumagpas na sa oras
openFile = Magbukas ng File
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Hanapin sa %1$S ang “%2$S”
contextMenuSearch.accesskey = S
contextMenuPrivateSearch = Maghanap gamit ang Private Window
contextMenuPrivateSearch.accesskey = h
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Maghanap gamit ang %S sa Private Window
contextMenuPrivateSearchOtherEngine.accesskey = h
bookmarkAllTabsDefault = [Pangalan ng Folder]
unsignedAddonsDisabled.message = Isa o higit pang mga add-on ay hindi maaaring maberipika at ito ay nai-disable.
unsignedAddonsDisabled.learnMore.label = Alamin
unsignedAddonsDisabled.learnMore.accesskey = L
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Huling access %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = %S:// links
crashedpluginsMessage.title = Nag-crash ang plugin na %S.
crashedpluginsMessage.reloadButton.label = i-Reload ang pahina
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = Magpasa ng crash report
crashedpluginsMessage.submitButton.accesskey = S
crashedpluginsMessage.learnMore = Alamin…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Ang ibig mo bang sabihin ay pumunta sa %S?
keywordURIFixup.goTo = Oo, dalhin mo ako sa %S
keywordURIFixup.goTo.accesskey = Y
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = I-update sa %S
update.downloadAndInstallButton.accesskey = U
menuOpenAllInTabs.label = Buksan Lahat sa mga Tab
tabHistory.goBack = Bumalik sa pahinang ito
tabHistory.goForward = Pumunta sa pahinang ito
# URL Bar
pasteAndGo.label = i-Paste at Puntahan
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = i-Reload ang pahinang ito (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Ihinto ang paglo-load ng pahinang ito (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = I-reset ang zoom level (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Toggle reader view (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Ipakita ang iyong mga bookmark (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Ipakita ang pagsulong sa mga kasalukuyang download (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Magbukas ng bagong window (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Magbukas ng bagong tab (%S)
newTabContainer.tooltip = Magbukas ng bagong tab (%S)\nPindutin nang ilang segundo para magbukas ng bagong container tab
newTabAlwaysContainer.tooltip = Pumili ng container para makapagbukas ng bagong tab
canvas.block = Harangin
canvas.block.accesskey = B
canvas.allow2 = Payagan
canvas.allow2.accesskey = A
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Pinatunayin ni: %S
identity.identified.verified_by_you = Nagdagdag ka ng security exception para sa site na ito.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Certificate issued to: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Hindi Ligtas
identity.notSecure.tooltip = Ang Koneksyon ay hindi ligtas
identity.extension.label = Extension (%S)
identity.extension.tooltip = Ni-load ng extension: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Paliitin (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = I-reset ang zoom level (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Palakihin (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = i-Cut (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Kopyahin (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = i-Paste (%S)
geolocation.allow.accesskey = A
geolocation.block.accesskey = B
geolocation.remember = Tandaan ang desisyon na ito
xr.allow2.accesskey = A
xr.block.accesskey = B
xr.remember = Tandaan ang desisyon na ito
# Persistent storage UI
persistentStorage.allow = Payagan
persistentStorage.allow.accesskey = A
persistentStorage.block.accesskey = B
webNotifications.allow2.accesskey = A
webNotifications.notNow = Huwag ngayon
webNotifications.notNow.accesskey = n
webNotifications.never = Huwag Payagan Kailanman
webNotifications.never.accesskey = v
webNotifications.alwaysBlock.accesskey = B
webNotifications.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Itakas mo ako rito!
safebrowsing.getMeOutOfHereButton.accessKey = G
safebrowsing.deceptiveSite = Mapanlinlang na Site!
safebrowsing.notADeceptiveSiteButton.label = Hindi ito isang mapanlinlang na site…
safebrowsing.notADeceptiveSiteButton.accessKey = D
safebrowsing.reportedAttackSite = Iniulat na Attack Site!
safebrowsing.notAnAttackButton.label = Hindi ito isang attack site...
safebrowsing.notAnAttackButton.accessKey = A
safebrowsing.reportedUnwantedSite = Iniulat na Unwanted Software Site!
safebrowsing.reportedHarmfulSite = Iniulat ang Mapanganib na Site!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Hanapin ang %S
processHang.add-on.learn-more.text = Matuto ng mahigit pa
processHang.button_stop2.accessKey = S
processHang.button_debug.label = I-debug ang Script
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Ipakita ang window sa buong screen (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Ilipat ang Sidebar sa Kaliwa
sidebar.moveToRight = Ilipat ang Sidebar sa Kanan
emeNotifications.drmContentDisabled.button.label = Paganahin ang DRM
emeNotifications.drmContentDisabled.button.accesskey = E
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = Ang %S ay nag-i-install ng mga kinakailangang component para mapaandar ang audio o video sa pahinang ito. Subukan uli mamaya.
emeNotifications.unknownDRMSoftware = Hindi Alam
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = I-customize ang %S
decoder.noCodecs.button = Alamin kung paano
decoder.noCodecs.accesskey = L
decoder.noCodecsLinux.message = Upang may-play ng video, maaaring kailanganin mong i-install ang kinakailangang mga video codec.
decoder.noHWAcceleration.message = Upang mapabuti ang kalidad ng video, maaaring kailanganin mong i-install ang Media Feature Pack ng Microsoft.
decoder.noPulseAudio.message = Upang mag-play ng audio, maaaring kailangan mong i-install ang kinakailangang software na PulseAudio.
decoder.unsupportedLibavcodec.message = maaaring mahina ang libavcodec o hindi suportado, at dapat ma-update upang i-play ang video.
decoder.decodeError.message = May naganap na error habang nagde-decode sa pinagkukuhanan ng media.
decoder.decodeError.button = Mag-report ng Issue sa Site
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = Isang recoverable na error ang naganap habang nagde-decode sa pinagkukuhanan ng media.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Dapat kang mag-log in sa network na ito bago mo ma-access ang Internet.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Buksan ang Pahina ng Network Login
permissions.remove.tooltip = Burahing ang pahintulot na ito at mag-tanong muli
permissions.fullscreen.promptCanceled = Kinansela ang mga pending na mga permission request: ang mga permission request ay hindi dapat ma-issue bago pumasok sa DOM fullscreen.
permissions.fullscreen.fullScreenCanceled = Lumabas sa DOM fullscreen: ang mga permission request ay hindi dapat ma-issue habang naka-DOM fullscreen.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bit
aboutDialog.architecture.thirtyTwoBit = 32-bit
midi.allow.label = Payagan
midi.allow.accesskey = A
midi.block.label = Harangin
midi.block.accesskey = B
midi.remember = Tandaan ang desisyon na ito
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Balikan
storageAccess1.Allow.accesskey = A
storageAccess1.DontAllow.accesskey = B
