# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SaveImageTitle = ذخیرهٔ تصویر
SaveMediaTitle = ذخیره رسانه
SaveVideoTitle = ذخیرهٔ ویدیو
SaveAudioTitle = ذخیرهٔ پروندهٔ صوتی
SaveLinkTitle = ذخیره به نام
WebPageCompleteFilter = صفحهٔ وب، کامل
WebPageHTMLOnlyFilter = صفحهٔ وب، فقط HTML‏
WebPageXHTMLOnlyFilter = صفحهٔ وب، فقط XHTML‏
WebPageSVGOnlyFilter = صفحهٔ وب، فقط SVG‏
WebPageXMLOnlyFilter = صفحهٔ وب، فقط XML‏
