# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# "Listen, which allows users to listen to Firefox reading the text,
# instead of having to read it themselves." This is the name
# of the feature and it is the label for the popup button.
# Header for the narrate menu
read-aloud-header = بلندخوانی
# %S is the keyboard shortcut for the listen command
read-aloud-label = بلندخوانی (%S)
# %S is the keyboard shortcut for the skip back command
previous-label = عقب (%S)
# %S is the keyboard shortcut for the start command
start-label = شروع (%S)
# %S is the keyboard shortcut for the stop command
stop-label = توقف (%S)
# Keyboard shortcut to toggle the narrate feature
narrate-key-shortcut = N
# %S is the keyboard shortcut for the skip forward command
next-label = جلو (%S)
speed = سرعت
slow-speed-label = کند کردن خوانش
fast-speed-label = تند کردن خوانش
select-voice-header = صدا
# Default voice is determined by the language of the document.
defaultvoice = پیش‌فرض
# Voice name and language.
# eg. David (English)
voiceLabel = %S (%S)
