# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language-name-aa = Afar Dili
language-name-ab = Abazaca
language-name-ach = Açoli
language-name-ae = Avesta Dili
language-name-af = Afrikaans Dili
language-name-ak = Akan Dili
language-name-am = Amharic Dili
language-name-an = Aragon Dili
language-name-ar = Arapça
language-name-as = Assam Dili
language-name-ast = Asturias Dili
language-name-av = Avarca
language-name-ay = Aymara Dili
language-name-az = Azerice
language-name-ba = Başqurtça
language-name-be = Belarus Dili
language-name-bg = Bulgarca
language-name-bh = Bihari Dili
language-name-bi = Bislama Dili
language-name-bm = Bambara Dili
language-name-bn = Bengal Dili
language-name-bo = Tibet Dili
language-name-br = Breton Dili
language-name-bs = Boşnakça
language-name-ca = Katalanca
language-name-cak = Kakçikelce
language-name-ce = Çeçence
language-name-ch = Chamorro Dili
language-name-co = Korsika Dili
language-name-cr = Cree Dili
language-name-crh = QIRIMTATARCA (Qırım Türkçesi)
language-name-cs = Çek Dili
language-name-csb = Qaşubca
language-name-cu = Slav Kilise Dili
language-name-cv = Çuvaş Dili
language-name-cy = Galce
language-name-da = Danca
language-name-de = Almanca
language-name-dsb = Aşağı Sorbca
language-name-dv = Divehi Dili
language-name-dz = Zonka (Bhutan) Dili
language-name-ee = Ewe Dili
language-name-el = Yunanca
language-name-en = İngilizce
language-name-eo = Esperanto
language-name-es = İspanyolca
language-name-et = Estonya Dili
language-name-eu = Baskça
language-name-fa = Farsça
language-name-ff = Fulah Dili
language-name-fi = Fince
language-name-fj = Fiji Dili
language-name-fo = Faroe Dili
language-name-fr = Fransızca
language-name-fur = Friulyan
language-name-fy = Frisyan Dili
language-name-ga = İrce
language-name-gd = İskoç Keltçesi
language-name-gl = Galce
language-name-gn = Guarani Dili
language-name-gu = Gujarati Dili
language-name-gv = Man Dili
language-name-ha = Hausa Dili
language-name-haw = Hawaice
language-name-he = İbraniyce
language-name-hi = Hintçe
language-name-hil = Hiligaynon
language-name-ho = Hiri Motu Dili
language-name-hr = Hırvatça
language-name-hsb = Yukarı Sorbiyan Dili
language-name-ht = Haiti Dili
language-name-hu = Macarca
language-name-hy = Ermenice
language-name-hz = Herero Dili
language-name-ia = İnterlingua
language-name-id = Endonezya Dili
language-name-ie = Interlingue
language-name-ig = Igbo Dili
language-name-ii = Sichuan Yi Dili
language-name-ik = Inupiak Dili
language-name-io = Ido Dili
language-name-is = İzlanda Dili
language-name-it = İtalyanca
language-name-iu = Inuktitut Dili
language-name-ja = Japonca
language-name-jv = Java Dili
language-name-ka = Gürcüce
language-name-kab = Kabilçe
language-name-kg = Kongo Dili
language-name-ki = Kikuyu Dili
language-name-kj = Kuanyama Dili
language-name-kk = Kazakça
language-name-kl = Grönland Dili
language-name-km = Kamboçya Dili
language-name-kn = Kanada Dili
language-name-ko = Korece
language-name-kok = Konkani Dili
language-name-kr = Kanuri Dili
language-name-ks = Keşmir Dili
language-name-ku = Kürtçe
language-name-kv = Komi Dili
language-name-kw = Cornish Dili
language-name-ky = Qırğızca
language-name-la = Latince
language-name-lb = Lüksemburg Dili
language-name-lg = Ganga
language-name-li = Liburg Dili
language-name-lij = Ligure
language-name-ln = Lingala Dili
language-name-lo = Lao Dili
language-name-lt = Litvanya Dili
language-name-ltg = Latgaleçe
language-name-lu = Luba Katanga Dili
language-name-lv = Litvanya Dili
language-name-mai = Maithili
language-name-meh = Cenubiy-ğarbiy Tlaşiako Miştek
language-name-mg = Madagaskar Dili
language-name-mh = Marshall Dili
language-name-mi = Maori Dili
language-name-mix = Miştepek Miştek
language-name-mk = Makedonca
language-name-ml = Malayalam
language-name-mn = Moğolca
language-name-mr = Marati Dili
language-name-ms = Malezyaca Dili
language-name-mt = Malta Dili
language-name-my = Burma Dili
language-name-na = Nauru Dili
language-name-nb = Norveççe (Bokmal) Dili
language-name-nd = Ndebele, Kuzey Dili
language-name-ne = Nepal Dili
language-name-ng = Ndonga Dili
language-name-nl = Felemenkçe
language-name-nn = Norveççe (Nynorsk) Dili
language-name-no = Norveççe
language-name-nr = Ndebele, Güney Dili
language-name-nso = Sotho, Kuzey Dili
language-name-nv = Navajo Dili
language-name-ny = Chichewa Dili
language-name-oc = Occitan Dili
language-name-oj = Ojibwa Dili
language-name-om = Oromo Dili
language-name-or = Oriyaca
language-name-os = Osetya Dili
language-name-pa = Pencap Dili
language-name-pi = Pali Dili
language-name-pl = Lehçe
language-name-ps = Paştu Dili
language-name-pt = Portekizce
language-name-qu = Quechua Dili
language-name-rm = Romanş Dili
language-name-rn = Kirundi Dili
language-name-ro = Romence
language-name-ru = Rusça
language-name-rw = Kinyarwanda Dili
language-name-sa = Sanskritçe
language-name-sc = Sardinya Dili
language-name-sd = Sind Dili
language-name-se = Nord Sami
language-name-sg = Sangro Dili
language-name-si = Seylan Dili
language-name-sk = Slovakça
language-name-sl = Slovence
language-name-sm = Samoan Dili
language-name-sn = Shona Dili
language-name-so = Somali Dili
language-name-son = Soñayca
language-name-sq = Arnavutça
language-name-sr = Sırpça
language-name-ss = Siswati Dili
language-name-st = Sesotho Dili
language-name-su = Sudan Dili
language-name-sv = İsveççe
language-name-sw = Swahili Dili
language-name-ta = Tamil Dili
language-name-te = Telugu Dili
language-name-tg = Tacik Dili
language-name-th = Tayca
language-name-ti = Tigrinya Dili
language-name-tig = Tigre
language-name-tk = Türkmence
language-name-tl = Tagalogça
language-name-tlh = Klingon
language-name-tn = Tswana Dili
language-name-to = Tonga Dili
language-name-tr = Türkçe
language-name-ts = Tsonga Dili
language-name-tt = İdil-Ural Tatarcası
language-name-tw = Twi Dili
language-name-ty = Tahiti Dili
language-name-ug = Uyğurca
language-name-uk = Ukraince
language-name-ur = Urduca
language-name-uz = Özbekçe
language-name-ve = Venda Dili
language-name-vi = Vietnamca
language-name-vo = Volapük
language-name-wa = Walloon Dili
language-name-wen = Sorbiyan Dili
language-name-wo = Wolof Dili
language-name-xh = Xhosa Dili
language-name-yi = Eskenazi Dili
language-name-yo = Yoruba Dili
language-name-za = Zuang Dili
language-name-zam = Miahuatlán Zapotekçesi
language-name-zh = Çince
language-name-zu = Zulu Dili
