# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Notice: If you're updating this list, you should also
###         update the list in mozIntl.js.

region-name-ad = Andorra
region-name-ae = Birleşik Arap Emirlikleri
region-name-af = Afganistan
region-name-ag = Antigua ve Barbuda
region-name-ai = Anguilla
region-name-al = Arnavutlıq
region-name-am = Ermenistan
region-name-ao = Angola
region-name-aq = Antarktika
region-name-ar = Arjantin
region-name-as = Amerika Samoası
region-name-at = Avusturya
region-name-au = Avustralya
region-name-aw = Aruba
region-name-az = Azerbaycan
region-name-ba = Bosna Hersek
region-name-bb = Barbados
region-name-bd = Bangladeş
region-name-be = Belçika
region-name-bf = Burkina Faso
region-name-bg = Bulgaristan
region-name-bh = Bahreyn
region-name-bi = Burundi
region-name-bj = Benin
region-name-bl = Aziz Barthelemy
region-name-bm = Bermuda
region-name-bn = Bruney
region-name-bo = Bolivya
region-name-bq = Bonaire, Sint Eustatius ve Saba
region-name-br = Brezilya
region-name-bs = Bahamalar
region-name-bt = Butan
region-name-bv = Bouvet Adası
region-name-bw = Botsvana
region-name-by = Beyaz Rusya
region-name-bz = Beliz
region-name-ca = Kanada
region-name-cc = Cocos (Keeling) Adaları
region-name-cd = Kongo (Kinşasa)
region-name-cf = Orta Afrika Cumhuriyeti
region-name-cg = Kongo (Brazzaville)
region-name-ch = İsviçre
region-name-ci = Filtişi Sahili
region-name-ck = Cook Adaları
region-name-cl = Şili
region-name-cm = Kamerun
region-name-cn = Çin
region-name-co = Kolombiya
region-name-cp = Clipperton Adası
region-name-cr = Kosta Rica
region-name-cu = Küba
region-name-cv = Yeşil Burun
region-name-cw = Curaçao
region-name-cx = Christmas Adası
region-name-cy = Güney Kıbrıs Rum Kesimi
region-name-cz = Çek Cumhuriyeti
region-name-de = Almanya
region-name-dg = Diego Garcia
region-name-dj = Cibuti
region-name-dk = Danimarka
region-name-dm = Dominik
region-name-do = Dominik Cumhuriyeti
region-name-dz = Cezayir
region-name-ec = Ekvador
region-name-ee = Estonya
region-name-eg = Mısır
region-name-eh = Batı Sahara
region-name-er = Eritre
region-name-es = İspanya
region-name-et = Etiyopya
region-name-fi = Finlandiya
region-name-fj = Fiji
region-name-fk = Falkland Adaları (Islas Malvinas)
region-name-fm = Mikroneziye Federalleşken Devletleri
region-name-fo = Faroe Adaları
region-name-fr = Fransa
region-name-ga = Gabon
region-name-gb = Birleşik Krallık
region-name-gd = Grenada
region-name-ge = Gürcistan
region-name-gf = Fransız Guyanası
region-name-gg = Guernsey
region-name-gh = Gana
region-name-gi = Cebelitarık
region-name-gl = Grönland
region-name-gm = Gambiya
region-name-gn = Gine
region-name-gp = Guadeloupe
region-name-gq = Ekvatoral Gine
region-name-gr = Yunanistan
region-name-gs = Cenubiy Gürcistan ve Cenubiy Sandviç Adaları
region-name-gt = Guatemala
region-name-gu = Guam
region-name-gw = Gine Bissau
region-name-gy = Guyana
region-name-hk = Hong Kong
region-name-hm = Heard Adası ve McDonald Adaları
region-name-hn = Honduras
region-name-hr = Hırvatistan
region-name-ht = Haiti
region-name-hu = Macaristan
region-name-id = Endonezya
region-name-ie = İrlanda
region-name-il = İsrail
region-name-im = Man Adası
region-name-in = Hindistan
region-name-io = Britanya'nın Hint Okyanusu Toprakları
region-name-iq = Irak
region-name-ir = İran
region-name-is = İzlanda
region-name-it = İtalya
region-name-je = Jersey
region-name-jm = Jamaika
region-name-jo = Ürdün
region-name-jp = Japonya
region-name-ke = Kenya
region-name-kg = Kırgızistan
region-name-kh = Kamboçya
region-name-ki = Kiribati
region-name-km = Komolar
region-name-kn = Saint Kitts ve Nevis
region-name-kp = Koreya, Şimaliy
region-name-kr = Koreya, Cenubiy
region-name-kw = Kuveyt
region-name-ky = Cayman Adaları
region-name-kz = Kazakistan
region-name-la = Laos
region-name-lb = Lübnan
region-name-lc = Aziz Lucia
region-name-li = Lihtenştayn
region-name-lk = Şri Lanka
region-name-lr = Liberya
region-name-ls = Lesotho
region-name-lt = Litvanya
region-name-lu = Lüksemburg
region-name-lv = Letonya
region-name-ly = Libya
region-name-ma = Fas
region-name-mc = Monako
region-name-md = Moldova
region-name-me = Karadağ
region-name-mf = Aziz Martin
region-name-mg = Madagaskar
region-name-mh = Marshall Adaları
region-name-mk = Makedoniya
region-name-ml = Mali
region-name-mm = Burma
region-name-mn = Moğolistan
region-name-mo = Makao
region-name-mp = Kuzey Mariana Adaları
region-name-mq = Martinik
region-name-mr = Moritanya
region-name-ms = Montserrat
region-name-mt = Malta
region-name-mu = Mauritius
region-name-mv = Maldivler
region-name-mw = Malavi
region-name-mx = Meksika
region-name-my = Malezya
region-name-mz = Mozambik
region-name-na = Namibya
region-name-nc = Yeni Kaledonya
region-name-ne = Nijer
region-name-nf = Norfolk Adası
region-name-ng = Nijerya
region-name-ni = Nikaragua
region-name-nl = Hollanda
region-name-no = Norveç
region-name-np = Nepal
region-name-nr = Nauru
region-name-nu = Niue
region-name-nz = Yeni Zelanda
region-name-om = Umman
region-name-pa = Panama
region-name-pe = Peru
region-name-pf = Fransız Polinezyası
region-name-pg = Papua Yeni Gine
region-name-ph = Filipinler
region-name-pk = Pakistan
region-name-pl = Polonya
region-name-pm = Saint Pierre ve Miquelon
region-name-pn = Pitcairn Adaları
region-name-pr = Porto Riko
region-name-pt = Portekiz
region-name-pw = Palau
region-name-py = Paraguay
region-name-qa = Katar
region-name-qm = Midway Adaları
region-name-qs = Bassas da India
region-name-qu = Juan de Nova Adası
region-name-qw = Wake Adası
region-name-qx = Glorioso Adaları
region-name-qz = Akrotiri
region-name-re = Reunion
region-name-ro = Romanya
region-name-rs = Sırbistan
region-name-ru = Rusiye
region-name-rw = Ruanda
region-name-sa = Suudi Arabistan
region-name-sb = Solomon Adaları
region-name-sc = Seyşeller
region-name-sd = Sudan
region-name-se = İsveç
region-name-sg = Singapur
region-name-sh = Saint Helena, Ascension ve Tristan da Cunha
region-name-si = Slovenya
region-name-sk = Slovakya
region-name-sl = Sierra Leone
region-name-sm = San Marino
region-name-sn = Senegal
region-name-so = Somali
region-name-sr = Surinam
region-name-ss = Cenubiy Sudan
region-name-st = Sao Tome ve Principe
region-name-sv = El Salvador
region-name-sx = Sint Maarten
region-name-sy = Suriye
region-name-sz = Svaziland
region-name-tc = Turks ve Caicos Adaları
region-name-td = Çad
region-name-tf = Fransız Cenubiy ve Antarktik Diyarlar
region-name-tg = Togo
region-name-th = Tayland
region-name-tj = Tacikistan
region-name-tk = Tokelau
region-name-tl = Doğu Timor
region-name-tm = Türkmenistan
region-name-tn = Tunus
region-name-to = Tonga
region-name-tr = Türkiye
region-name-tt = Trinidad Tobago
region-name-tv = Tuvalu
region-name-tw = Tayvan
region-name-tz = Tanzanya
region-name-ua = Ukrayna
region-name-ug = Uganda
region-name-us = AQŞ
region-name-uy = Uruguay
region-name-uz = Özbekistan
region-name-va = Vatikan
region-name-vc = Saint Vincent ve Grenadineler
region-name-ve = Venezuela
region-name-vg = Virgin Adalar, İngliz
region-name-vi = Virgin Adalar, A.Q.Ş.
region-name-vn = Vyetnam
region-name-vu = Vanuatu
region-name-wf = Wallis ve Futuna
region-name-ws = Samoa
region-name-xa = Ashmore ve Cartier Adaları
region-name-xb = Baker Adası
region-name-xc = Mercan Denizi Adaları
region-name-xd = Dikelya
region-name-xe = Europa Adası
region-name-xg = Gazze Şeridi
region-name-xh = Howland Adası
region-name-xj = Jan Mayen
region-name-xk = Kosova
region-name-xl = Palmyra Atolü
region-name-xm = Kingman Resifi
region-name-xp = Paracel Adaları
region-name-xq = Jarvis Adası
region-name-xr = Svalbard
region-name-xs = Spratly Adaları
region-name-xt = Tromelin Adası
region-name-xu = Johnston Atoll
region-name-xv = Navassa Adası
region-name-xw = Batı Şeria
region-name-ye = Yemen
region-name-yt = Mayotte
region-name-za = Cenubiy Africa
region-name-zm = Zambiya
region-name-zw = Zimbabve
