# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Ønsker du at stole på "%S" til følgende formål?
unnamedCA = Certifikatautoritet (unavngivet)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Indtast den adgangskode, der blev brugt til at kryptere denne certifikat-backup:
# Page Info
pageInfo_NoEncryption = Forbindelsen er ikke krypteret
pageInfo_Privacy_None1 = Webstedet %S understøtter ikke kryptering af den side du kigger på.
pageInfo_Privacy_None2 = Oplysninger der sendes over internettet uden kryptering kan læses af andre, mens de bliver sendt.
pageInfo_Privacy_None4 = Den aktuelle side blev ikke krypteret, før den blev sendt over internettet.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Forbindelsen er krypteret (%1$S, %2$S-bit-nøgle, %3$S)
pageInfo_BrokenEncryption = Kryptering er brudt (%1$S, %2$S-bit-nøgle, %3$S)
pageInfo_Privacy_Encrypted1 = Den aktuelle side blev krypteret, før den blev sendt over internettet.
pageInfo_Privacy_Encrypted2 = Kryptering gør det meget vanskeligt for uautoriserede personer at aflæse informationer, der sendes mellem computere. Det er derfor meget usandsynligt, at nogen kunne se denne side, da den blev sendt over nettet.
pageInfo_MixedContent = Forbindelsen er delvist krypteret
pageInfo_MixedContent2 = Dele af den aktuelle side blev ikke krypteret, før den blev sendt over nettet.
pageInfo_WeakCipher = Din forbindelse til webstedet benytter en svag kryptering, og den er derfor ikke sikker. Fremmede kan se de overførte data eller ændre på webstedets opførsel.
pageInfo_CertificateTransparency_Compliant = Dette websted overholder politikken for certifikat-gennemsigtighed.
# Token Manager
password_not_set = (ikke sat)
