# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Čas vypršal
openFile = Otvoriť súbor
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Vyhľadať "%2$S" na webe pomocou %1$S
contextMenuSearch.accesskey = V
contextMenuPrivateSearch = Vyhľadať v súkromnom okne
contextMenuPrivateSearch.accesskey = h
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Vyhľadať v súkromnom okne pomocou %S
contextMenuPrivateSearchOtherEngine.accesskey = h
bookmarkAllTabsDefault = [Názov priečinka]
unsignedAddonsDisabled.message = Jeden alebo viac doplnkov nebolo možné overiť a preto boli zakázané.
unsignedAddonsDisabled.learnMore.label = Ďalšie informácie
unsignedAddonsDisabled.learnMore.accesskey = a
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Posledný prístup: %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = Odkazy %S://
crashedpluginsMessage.title = Zásuvný modul %S zlyhal.
crashedpluginsMessage.reloadButton.label = Obnoviť stránku
crashedpluginsMessage.reloadButton.accesskey = b
crashedpluginsMessage.submitButton.label = Odoslať správu o zlyhaní
crashedpluginsMessage.submitButton.accesskey = d
crashedpluginsMessage.learnMore = Ďalšie informácie…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Chceli ste navštíviť stránku %S?
keywordURIFixup.goTo = Áno, prejsť na %S
keywordURIFixup.goTo.accesskey = o
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Aktualizovať na verziu %S
update.downloadAndInstallButton.accesskey = A
menuOpenAllInTabs.label = Otvoriť všetko na kartách
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Obnoviť túto stránku
tabHistory.goBack = Prejsť späť na túto stránku
tabHistory.goForward = Prejsť dopredu na túto stránku
# URL Bar
pasteAndGo.label = Prilepiť a prejsť
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Načítať najnovšiu verziu stránky (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Zastaviť načítavanie tejto stránky (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Vynulovať úroveň priblíženia (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Prepne zobrazenie Čítačka (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S %%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, Obnoviť úroveň priblíženia
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Zobrazí vaše záložky (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Zobrazí stav sťahovania súborov (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Otvorí nové okno (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Otvorí novú kartu (%S)
newTabContainer.tooltip = Otvorí novú kartu (%S)\nPodržaním tlačidla otvorí novú kontajnerovú kartu
newTabAlwaysContainer.tooltip = Otvorí novú kontajnerovú kartu
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Povoliť stránke %S používať údaje z canvasu HTML5?
canvas.siteprompt2.warning = Môže byť použité na jednoznačnú identifikáciu vášho počítača.
canvas.block = Zakázať
canvas.block.accesskey = Z
canvas.allow2 = Povoliť
canvas.allow2.accesskey = P
canvas.remember2 = Zapamätať si toto rozhodnutie
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Overil ju %S
identity.identified.verified_by_you = Pre túto stránku ste pridali bezpečnostnú výnimku.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Certifikát bol vydaný pre: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Nezabezpečené
identity.notSecure.tooltip = Pripojenie nie je zabezpečené
identity.extension.label = Rozšírenie (%S)
identity.extension.tooltip = Načítané doplnkom: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Oddialiť stránku (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Obnoviť úroveň priblíženia (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Priblížiť stránku (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Vystrihnúť (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Kopírovať (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Prilepiť (%S)
geolocation.allow = Povoliť
geolocation.allow.accesskey = P
geolocation.block = Zakázať
geolocation.block.accesskey = Z
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Tým sa otvoria nastavenia systému pre zisťovanie polohy. Udeľte oprávnenie pre %S na zisťovanie polohy.
geolocation.shareWithSite4 = Povoliť stránke %S pristupovať k vašej polohe?
geolocation.shareWithFile4 = Chcete tomuto lokálnemu súboru povoliť prístup k vašej polohe?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Chcete stránke %1$S povoliť, aby umožnila  prístup k vašej polohe pre %2$S?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Udeľte oprávnenie na zisťovanie polohy pre %S v systémových nastaveniach.
geolocation.systemSettingsTitle = Čaká sa na oprávnenie zisťovania polohy
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Systém vás požiada o udelenie tohto oprávnenia pre %S.
geolocation.remember = Zapamätať si toto rozhodnutie
# Virtual Reality Device UI
xr.allow2 = Povoliť
xr.allow2.accesskey = P
xr.block = Zakázať
xr.block.accesskey = Z
xr.shareWithSite4 = Chcete stránke %S povoliť prístup k vašim zariadeniam pre virtuálnu realitu? Môže dôjsť k odhaleniu citlivých informácií.
xr.shareWithFile4 = Chcete tomuto lokálnemu súboru povoliť prístup k vašim zariadeniam pre virtuálnu realitu? Môže dôjsť k odhaleniu citlivých informácií.
xr.remember = Zapamätať si toto rozhodnutie
# Persistent storage UI
persistentStorage.allow = Povoliť
persistentStorage.allow.accesskey = P
persistentStorage.block.label = Zakázať
persistentStorage.block.accesskey = Z
persistentStorage.allowWithSite2 = Chcete stránke %S povoliť ukladanie údajov do trvalého úložiska?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Povoliť
webNotifications.allow2.accesskey = P
webNotifications.notNow = Teraz nie
webNotifications.notNow.accesskey = n
webNotifications.never = Nikdy nepovoliť
webNotifications.never.accesskey = v
webNotifications.alwaysBlock = Vždy zakázať
webNotifications.alwaysBlock.accesskey = V
webNotifications.block = Zakázať
webNotifications.block.accesskey = Z
webNotifications.receiveFromSite3 = Povoliť stránke %S posielať notifikácie?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S chce získať prístup k iným aplikáciám a službám na tomto zariadení.
localhost.remember2 = Zapamätať si moju voľbu pre túto stránku
localhost.allowlabel = Povoliť
localhost.blocklabel = Zakázať
localhost.allow.accesskey = P
localhost.block.accesskey = Z
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S chce získať prístup k aplikáciám a službám na zariadeniach pripojených k vašej lokálnej sieti.
localNetwork.remember2 = Zapamätať si moju voľbu pre túto stránku
localNetwork.allowLabel = Povoliť
localNetwork.allow.accesskey = P
localNetwork.blockLabel = Zakázať
localNetwork.block.accesskey = Z
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Rýchlo odtiaľto preč!
safebrowsing.getMeOutOfHereButton.accessKey = R
safebrowsing.deceptiveSite = Podvodná stránka!
safebrowsing.notADeceptiveSiteButton.label = Toto nie je podvodná stránka…
safebrowsing.notADeceptiveSiteButton.accessKey = o
safebrowsing.reportedAttackSite = Nahlásená škodlivá stránka!
safebrowsing.notAnAttackButton.label = Toto nie je škodlivá stránka…
safebrowsing.notAnAttackButton.accessKey = T
safebrowsing.reportedUnwantedSite = Nahlásená stránka s nevyžiadaným softvérom!
safebrowsing.reportedHarmfulSite = Nahlásená škodlivá stránka!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Vyhľadávanie na %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Chcete reštartovať %S v režime riešenia problémov?
troubleshootModeRestartPromptMessage = Vaše rozšírenia, témy vzhľadu a vlastné nastavenia budú dočasne zakázané.
troubleshootModeRestartButton = Reštartovať
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Táto stránka spomaľuje %1$S. Ak chcete svoj prehliadač zrýchliť, zastavte načítavanie tejto stránky.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Webová stránka spomaľuje %1$S. Ak chcete svoj prehliadač zrýchliť, zastavte načítavanie danej stránky.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = Stránka “%1$S” spomaľuje %2$S. Ak chcete svoj prehliadač zrýchliť, zastavte načítavanie danej stránky.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = Rozšírenie “%1$S” spomaľuje %2$S. Ak chcete svoj prehliadač zrýchliť, zastavte dané rozšírenie.
processHang.add-on.learn-more.text = Ďalšie informácie
processHang.button_stop2.label = Zastaviť
processHang.button_stop2.accessKey = Z
processHang.button_debug.label = Ladiť skript
processHang.button_debug.accessKey = L
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Zobraziť okno na celú obrazovku (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Presunúť bočný panel doľava
sidebar.moveToRight = Presunúť bočný panel doprava
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Pre prehranie zvuku alebo videa na tejto stránke musíte najprv povoliť DRM.
emeNotifications.drmContentDisabled.button.label = Povoliť DRM
emeNotifications.drmContentDisabled.button.accesskey = o
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S inštaluje komponenty potrebné na prehratie zvuku alebo videa na tejto stránke. Skúste to znova neskôr.
emeNotifications.unknownDRMSoftware = Neznámy
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Prispôsobiť %S
decoder.noCodecs.button = Ďalšie informácie
decoder.noCodecs.accesskey = m
decoder.noCodecsLinux.message = Na prehrávanie videa môže byť potrebné nainštalovať video kodeky.
decoder.noHWAcceleration.message = Pre zlepšenie kvality videa môže byť potrebné nainštalovať Media Feature Pack od Microsoftu.
decoder.noPulseAudio.message = Na prehrávanie hudby môže byť potrebné nainštalovať softvér PulseAudio.
decoder.unsupportedLibavcodec.message = Verzia knižnice libavcodec môže byť zraniteľná alebo nie je podporovaná a na prehrávanie videa je potrebná jej aktualizácia.
decoder.decodeError.message = Pri dekódovaní média sa vyskytla chyba.
decoder.decodeError.button = Nahlásiť problém so stránkou
decoder.decodeError.accesskey = r
decoder.decodeWarning.message = Pri dekódovaní média sa vyskytla chyba, ktorú možno opraviť.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Pre prístup na internet sa musíte najprv prihlásiť k tejto sieti.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Otvoriť prihlasovaciu stránku k sieti
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Oprávnenia pre %S
permissions.remove.tooltip = Vymazať toto oprávnenie a znova sa opýtať
permissions.fullscreen.promptCanceled = Čakajúce žiadosti o povolenie boli zrušené: žiadosti o povolenie by nemali byť vydané pred vstupom do režimu na celú obrazovku.
permissions.fullscreen.fullScreenCanceled = Ukončený režim na celú obrazovku: žiadosti o povolenie by nemali byť vydané, keď ste v režime na celú obrazovku.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64‑bitová verzia
aboutDialog.architecture.thirtyTwoBit = 32‑bitová verzia
midi.allow.label = Povoliť
midi.allow.accesskey = P
midi.block.label = Zakázať
midi.block.accesskey = Z
midi.remember = Zapamätať si toto rozhodnutie
midi.shareWithFile = Chcete tomuto lokálnemu súboru povoliť prístup k MIDI zariadeniam?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Povoliť stránke %S pristupovať k MIDI zariadeniam?
midi.shareSysexWithFile = Chcete tomuto lokálnemu súboru povoliť prístup k MIDI zariadeniam a k odosielaniu/prijímaniu správ SysEx?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Chcete stránke %S povoliť prístup k MIDI zariadeniam a k odosielaniu/prijímaniu správ SysEx?
serial.allow.label = Povoliť
serial.allow.accesskey = P
serial.block.label = Zakázať
serial.block.accesskey = Z
serial.shareWithFile = Povoliť tomuto lokálnemu súboru prístup k vašim sériovým portom?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Povoliť stránke %S pristupovať k vašim sériovým portom?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Naspäť
storageAccess1.Allow.label = Povoliť
storageAccess1.Allow.accesskey = o
storageAccess1.DontAllow.label = Zakázať
storageAccess1.DontAllow.accesskey = a
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Chcete povoliť stránke %1$S používať svoje súbory cookie aj na stránke %2$S?
storageAccess1.hintText = Ak nie je jasné, prečo %1$S potrebuje tieto údaje, môžete jej prístup zakázať.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Vyhľadať “%S” na webe
