# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Chwilio { $host }…
network-connection-status-connected = Cysylltwyd â { $host }…
network-connection-status-sending-request = Anfon cais at { $host }…
network-connection-status-transferring-data = Trosglwyddo data o { $host }…
network-connection-status-connecting = Cysylltu â { $host }…
network-connection-status-read = Darllen { $host }
network-connection-status-wrote = Ysgrifennwyd { $host }
network-connection-status-waiting = Aros am { $host }…
network-connection-status-looked-up = Wedi chwilio am { $host }…
network-connection-status-tls-handshake = Cyflawni ysgwyd llaw TLS i { $host }…
network-connection-status-tls-handshake-finished = Mae'r TLS ysgwyd llaw wedi gorffen ar gyfer { $host }…
