# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-connected = پەیوەندی بەست بە { $host }…
network-connection-status-sending-request = داواکاری دەنێردرێت بۆ { $host }…
network-connection-status-transferring-data = هاوردەکردنی زانیارییەکان لە { $host }…
network-connection-status-connecting = پەیوەندی دەبەستێت بە { $host }…
network-connection-status-read = خوێندنەوەی { $host }
network-connection-status-wrote = نووسرا لە { $host }
network-connection-status-waiting = جاوەڕێکردنی { $host }…
network-connection-status-looked-up = گەڕان بەدوای { $host }…
network-connection-status-tls-handshake = ئەنجامدانی گرێدانی TLS بۆ { $host }…
network-connection-status-tls-handshake-finished = گرێدانی TLS تەواو بوو بۆ { $host }…
