# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Дали сакате да му верувате на %S за следново?
unnamedCA = Авторитет за сертификати (неименуван)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Внесете ја лозинката што се користела за шифрирање на оваа резервна копија на сертификатот:
# Page Info
pageInfo_NoEncryption = Врската не е енкриптирана
pageInfo_Privacy_None1 = Мрежното место %S не поддржува енкрипција за страницата која ја гледате.
pageInfo_Privacy_None2 = Информациите кои преку Интернет се праќаат без енкрипција можат да бидат видени од други луѓе.
pageInfo_Privacy_None4 = Страницата што ја гледате не беше шифрирана пред да се пренесе преку интернет.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Шифрирана врска (%1$S, %2$S бит клучеви, %3$S)
pageInfo_BrokenEncryption = Неисправно шифрирање (%1$S, %2$S битни клучеви, %3$S)
pageInfo_Privacy_Encrypted1 = Страницата што ја гледате беше шифрирана пред да се пренесе преку интернет.
pageInfo_Privacy_Encrypted2 = Шифрирањето им отежнува на неовластените лица да ги прегледуваат информациите што патуваат меѓу компјутерите. Затоа е малку веројатно дека некој ја прочитал оваа страница додека патувала низ мрежата.
pageInfo_MixedContent = Врската е само делумно енкриптирана
pageInfo_MixedContent2 = Делови од страницата што ја гледате не беа шифрирани пред да се пренесат преку интернет.
pageInfo_WeakCipher = Вашата врска со ова мрежно место користи слаба енкрипција и не е приватна. Други луѓе можат да ги видат Вашите информации или да го променат однесувањето на мрежното место.
pageInfo_CertificateTransparency_Compliant = Ова мрежно место е во согласност со политиката за транспарентност на сертификати.
# Token Manager
password_not_set = (ненаместено)
