# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE (CSPEvalScriptViolation):
# Don't translate/change "'unsafe-eval'", including the single quote.
# %1$S is the entire directive that has been violated. (e.g. "default-src 'none'")
# %2$S is the type of directive used by the resource (e.g. script-src)
CSPEvalScriptViolation = تنظیمات صفحه مانع از اجرای JavaScript eval (%2$S) شد زیرا دستورالعمل زیر را نقض می‌کند: «%1$S» ('unsafe-eval' وجود ندارد)
# LOCALIZATION NOTE (CSPROEvalScriptViolation):
# Don't translate "Report-Only" as it's part of the name Content-Security-Policy-Report-Only.
# Don't translate/change "'unsafe-eval'", including the single quote.
# %1$S is the entire directive that has been violated. (e.g. "default-src 'none'")
# %2$S is the type of directive used by the resource (e.g. script-src)
CSPROEvalScriptViolation = (خط‌مشی Report-Only) تنظیمات صفحه مانع از اجرای JavaScript eval (%2$S) می‌شد زیرا دستورالعمل زیر را نقض می‌کند: «%1$S» ('unsafe-eval' وجود ندارد)
# LOCALIZATION NOTE (CSPWasmEvalScriptViolation):
# WebAssembly is a feature name.
# Don't translate/change "'wasm-unsafe-eval'" or "'unsafe-eval'", including the single quote.
# %1$S is the entire directive that has been violated. (e.g. "default-src 'none'")
# %2$S is the type of directive used by the resource (e.g. script-src)
CSPWasmEvalScriptViolation = تنظیمات صفحه مانع از اجرای WebAssembly (%2$S) شد زیرا دستورالعمل زیر را نقض می‌کند: «%1$S» ('wasm-unsafe-eval' یا 'unsafe-eval' وجود ندارد)
# LOCALIZATION NOTE (CSPROWasmEvalScriptViolation):
# Don't translate "Report-Only" as it's part of the name Content-Security-Policy-Report-Only.
# WebAssembly is a feature name.
# Don't translate/change "'wasm-unsafe-eval'" or "'unsafe-eval'", including the single quote.
# %1$S is the entire directive that has been violated. (e.g. "default-src 'none'")
# %2$S is the type of directive used by the resource (e.g. script-src)
CSPROWasmEvalScriptViolation = (خط‌مشی Report-Only) تنظیمات صفحه مانع از اجرای WebAssembly (%2$S) می‌شد زیرا دستورالعمل زیر را نقض می‌کند: «%1$S» ('wasm-unsafe-eval' یا 'unsafe-eval' وجود ندارد)
# LOCALIZATION NOTE (CSPTrustedTypesPolicyViolation):
# Don't translate "Trusted Types" because it's a feature name.
# %1$S is the entire directive (name and value) that has been violated (e.g. "trusted types X").
CSPTrustedTypesPolicyViolation = تنظیمات صفحه مانع از ایجاد خط‌مشی Trusted Types شد زیرا دستورالعمل زیر را نقض می‌کند: «%1$S»
# LOCALIZATION_NOTE (CSPROTrustedTypesPolicyViolation):
# Don't translate "Trusted Types" because it's a feature name.
# %1$S is the entire directive (name and value) that has been violated (e.g. "trusted types X").
CSPROTrustedTypesPolicyViolation = (خط‌مشی Report-Only) تنظیمات صفحه مانع از ایجاد خط‌مشی Trusted Types می‌شد زیرا دستورالعمل زیر را نقض می‌کند: «%1$S»
# LOCALIZATION NOTE (CSPTrustedTypesSinkViolation):
# Don't translate "require-trusted-types-for 'script'", because it's the CSP directive.
CSPTrustedTypesSinkViolation = تنظیمات صفحه مانع از انتساب به یک injection sink شد زیرا دستورالعمل زیر را نقض می‌کند: «require-trusted-types-for 'script'»
# LOCALIZATION NOTE (CSPROTrustedTypesSinkViolation):
# Don't translate "require-trusted-types-for 'script'", because it's the CSP directive.
# Don't translate "Report-Only" as it's part of the name Content-Security-Policy-Report-Only.
CSPROTrustedTypesSinkViolation = (خط‌مشی Report-Only) تنظیمات صفحه مانع از انتساب به یک injection sink می‌شد زیرا دستورالعمل زیر را نقض می‌کند: «require-trusted-types-for 'script'»
# LOCALIZATION NOTE (CSPStyleViolation):
# %1$S is the entire directive that has been violated. (e.g. "default-src 'none'")
# %2$S is the URI of the resource which violated the directive.
# %3$S is the type of directive used by the resource (e.g. style-src)
CSPStyleViolation = تنظیمات صفحه مانع از اعمال سبک (%3$S) در %2$S شد زیرا دستورالعمل زیر را نقض می‌کند: «%1$S»
# LOCALIZATION NOTE (CSPROStyleViolation):
# Don't translate "Report-Only" as it's part of the name Content-Security-Policy-Report-Only.
# %1$S is the entire directive that has been violated. (e.g. "default-src 'none'")
# %2$S is the URI of the resource which violated the directive.
# %3$S is the type of directive used by the resource (e.g. style-src)
CSPROStyleViolation = (خط‌مشی Report-Only) تنظیمات صفحه مانع از اعمال سبک (%3$S) در %2$S می‌شد زیرا دستورالعمل زیر را نقض می‌کند: «%1$S»
# LOCALIZATION NOTE (CSPScriptViolation):
# %1$S is the entire directive that has been violated. (e.g. "default-src 'none'")
# %2$S is the URI of the resource which violated the directive.
# %3$S is the type of directive used by the resource (e.g. script-src-elem)
CSPScriptViolation = تنظیمات صفحه مانع از اجرای اسکریپت (%3$S) در %2$S شد زیرا دستورالعمل زیر را نقض می‌کند: «%1$S»
# LOCALIZATION NOTE (CSPROScriptViolation):
# Don't translate "Report-Only" as it's part of the name Content-Security-Policy-Report-Only.
# %1$S is the entire directive that has been violated. (e.g. "default-src 'none'")
# %2$S is the URI of the resource which violated the directive.
# %3$S is the type of directive used by the resource (e.g. script-src-elem)
CSPROScriptViolation = (خط‌مشی Report-Only) تنظیمات صفحه مانع از اجرای اسکریپت (%3$S) در %2$S می‌شد زیرا دستورالعمل زیر را نقض می‌کند: «%1$S»
# LOCALIZATION NOTE (CSPWorkerViolation):
# %1$S is the entire directive that has been violated. (e.g. "default-src 'none'")
# %2$S is the URI of the resource which violated the directive.
# %3$S is the type of directive used by the resource (e.g. worker-src)
CSPWorkerViolation = تنظیمات صفحه مانع از اجرای اسکریپت Worker (%3$S) در %2$S شد زیرا دستورالعمل زیر را نقض می‌کند: «%1$S»
# LOCALIZATION NOTE (CSPROWorkerViolation):
# Don't translate "Report-Only" as it's part of the name Content-Security-Policy-Report-Only.
# %1$S is the entire directive that has been violated. (e.g. "default-src 'none'")
# %2$S is the URI of the resource which violated the directive.
# %3$S is the type of directive used by the resource (e.g. worker-src)
CSPROWorkerViolation = (خط‌مشی Report-Only) تنظیمات صفحه مانع از اجرای اسکریپت Worker (%3$S) در %2$S می‌شد زیرا دستورالعمل زیر را نقض می‌کند: «%1$S»
# LOCALIZATION NOTE (CSPGenericViolation):
# %1$S is the entire directive that has been violated. (e.g. "default-src 'none'")
# %2$S is the URI of the resource which violated the directive.
# %3$S is the type of directive used by the resource (e.g. image-src)
CSPGenericViolation = تنظیمات صفحه مانع از بارگذاری منبع (%3$S) در %2$S شد زیرا دستورالعمل زیر را نقض می‌کند: «%1$S»
# LOCALIZATION NOTE (CSPROGenericViolation):
# Don't translate "Report-Only" as it's part of the name Content-Security-Policy-Report-Only.
# %1$S is the entire directive that has been violated. (e.g. "default-src 'none'")
# %2$S is the URI of the resource which violated the directive.
# %3$S is the type of directive used by the resource (e.g. image-src)
CSPROGenericViolation = (خط‌مشی Report-Only) تنظیمات صفحه مانع از بارگذاری منبع (%3$S) در %2$S می‌شد زیرا دستورالعمل زیر را نقض می‌کند: «%1$S»
# LOCALIZATION NOTE (triedToSendReport):
# %1$S is the URI we attempted to send a report to.
triedToSendReport = تلاش برای ارسال گزارش به نشانی اینترنتی (URI) نامعتبر: «%1$S»
tooManyReports = از ارسال بیش از حد گزارش‌های CSP در یک بازهٔ زمانی کوتاه جلوگیری شد.
# LOCALIZATION NOTE (couldNotParseReportURI):
# %1$S is the report URI that could not be parsed
couldNotParseReportURI = نشانی اینترنتی (URI) گزارش تجزیه نشد: %1$S
# LOCALIZATION NOTE (couldNotProcessUnknownDirective):
# %1$S is the unknown directive
couldNotProcessUnknownDirective = دستورالعمل ناشناختهٔ «%1$S» پردازش نشد
# LOCALIZATION NOTE (ignoringUnknownOption):
# %1$S is the option that could not be understood
ignoringUnknownOption = نادیده گرفتن گزینهٔ ناشناختهٔ %1$S
# LOCALIZATION NOTE (ignoringDuplicateSrc):
# %1$S defines the duplicate src
ignoringDuplicateSrc = نادیده گرفتن منبع تکراری %1$S
# LOCALIZATION NOTE (ignoringInvalidToken):
# %1$S defines the name of the directive
# %2$S is the token string containing non-ASCII characters.
ignoringInvalidToken = نادیده گرفتن دستورالعمل «%1$S» به دلیل وجود نویسه‌های نامعتبر «%2$S» در توکن
# LOCALIZATION NOTE (ignoringSrcFromMetaCSP):
# %1$S defines the ignored src
ignoringSrcFromMetaCSP = نادیده گرفتن منبع «%1$S» (در صورت تحویل از طریق عنصر meta پشتیبانی نمی‌شود).
# LOCALIZATION NOTE (ignoringSrcWithinNonceOrHashDirective):
# %1$S is the ignored src (e.g. "unsafe-inline")
# %2$S is the directive (e.g. "script-src-elem")
ignoringSrcWithinNonceOrHashDirective = نادیده گرفتن «%1$S» در %2$S: nonce-source یا hash-source مشخص شده است
# LOCALIZATION NOTE (ignoringScriptSrcForStrictDynamic):
# %1$S is the ignored src
# %1$S is the directive src (e.g. "script-src-elem")
# 'strict-dynamic' should not be localized
ignoringScriptSrcForStrictDynamic = نادیده گرفتن «%1$S» در %2$S: 'strict-dynamic' مشخص شده است
# LOCALIZATION NOTE (ignoringStrictDynamic):
# %1$S is the ignored src
ignoringStrictDynamic = نادیده گرفتن منبع «%1$S» (تنها درون script-src پشتیبانی می‌شود).
# LOCALIZATION NOTE (ignoringUnsafeEval):
# %1$S is the csp directive (e.g. script-src-elem)
# 'unsafe-eval' and 'wasm-unsafe-eval' should not be localized
ignoringUnsafeEval = نادیده گرفتن 'unsafe-eval' یا 'wasm-unsafe-eval' درون «%1$S».
# LOCALIZATION NOTE (strictDynamicButNoHashOrNonce):
# %1$S is the csp directive that contains 'strict-dynamic'
# 'strict-dynamic' should not be localized
strictDynamicButNoHashOrNonce = کلیدواژهٔ 'strict-dynamic' درون «%1$S» بدون هیچ nonce یا hash معتبری ممکن است مانع از بارگذاری همهٔ اسکریپت‌ها شود
# LOCALIZATION NOTE (reportURInotHttpsOrHttp2):
# %1$S is the ETLD of the report URI that is not HTTP or HTTPS
reportURInotHttpsOrHttp2 = نشانی اینترنتی گزارش (%1$S) باید یک نشانی HTTP یا HTTPS باشد.
# LOCALIZATION NOTE (reportURINorReportToNotInReportOnlyHeader):
# %1$S is the ETLD of the page with the policy
reportURINorReportToNotInReportOnlyHeader = این سایت (%1$S) دارای یک خط‌مشی Report-Only بدون هیچ‌کدام از دستورالعمل‌های report-uri یا report-to است. CSP هیچ نقضی از این خط‌مشی را مسدود نمی‌کند و قادر به گزارش آن نخواهد بود.
# LOCALIZATION NOTE (failedToParseUnrecognizedSource):
# %1$S is the CSP Source that could not be parsed
failedToParseUnrecognizedSource = تجزیهٔ منبع ناشناختهٔ %1$S ناموفق بود
# LOCALIZATION NOTE (upgradeInsecureRequest):
# %1$S is the URL of the upgraded request; %2$S is the upgraded scheme.
upgradeInsecureRequest = ارتقای درخواست ناامن «%1$S» جهت استفاده از «%2$S»
# LOCALIZATION NOTE (ignoreSrcForDirective):
ignoreSrcForDirective = نادیده گرفتن srcها برای دستورالعمل «%1$S»
# LOCALIZATION NOTE (hostNameMightBeKeyword):
# %1$S is the hostname in question and %2$S is the keyword
hostNameMightBeKeyword = تفسیر %1$S به عنوان نام میزبان، نه کلیدواژه. اگر قصد استفاده به عنوان کلیدواژه را داشتید، از «'%2$S'» (درون علامت نقل‌قول تکی) استفاده کنید.
# LOCALIZATION NOTE (notSupportingDirective):
# directive is not supported (e.g. 'reflected-xss')
notSupportingDirective = دستورالعمل «%1$S» پشتیبانی نمی‌شود. این دستورالعمل و مقادیر آن نادیده گرفته خواهند شد.
# LOCALIZATION NOTE (blockAllMixedContent):
# %1$S is the URL of the blocked resource load.
blockAllMixedContent = مسدود کردن درخواست ناامن «%1$S».
# LOCALIZATION NOTE (ignoringDirectiveWithNoValues):
# %1$S is the name of a CSP directive that requires additional values
ignoringDirectiveWithNoValues = نادیده گرفتن «%1$S» به دلیل عدم وجود هرگونه پارامتر.
# LOCALIZATION NOTE (ignoringInvalidGroupSyntax):
# %1$S is the whole group name being parsed
# %2$S is the bad character (e.g. a / slash, $ dollar etc.)
ignoringInvalidGroupSyntax = نادیده گرفتن گروه دستورالعمل report-to «%1$S» با توکن نامعتبر «%2$S».
# LOCALIZATION NOTE (ignoringReportOnlyDirective):
# %1$S is the directive that is ignored in report-only mode.
ignoringReportOnlyDirective = نادیده گرفتن دستورالعمل sandbox هنگامی که در یک خط‌مشی گزارش‌تنها (Report-Only) ارائه شده است: «%1$S»
# LOCALIZATION NOTE (IgnoringSrcBecauseOfDirective):
# %1$S is the name of the src that is ignored.
# %2$S is the name of the directive that causes the src to be ignored.
IgnoringSrcBecauseOfDirective = نادیده گرفتن «%1$S» به دلیل وجود دستورالعمل «%2$S».
# LOCALIZATION NOTE (IgnoringSourceWithinDirective):
# %1$S is the ignored src
# %2$S is the directive  which supports src
IgnoringSourceWithinDirective = نادیده گرفتن منبع «%1$S» (درون «%2$S» پشتیبانی نمی‌شود).
# LOCALIZATION NOTE (IgnoringSourceWithinDirective):
# %1$S is the ignored src
obsoleteBlockAllMixedContent = نادیده گرفتن «%1$S»؛ ارتقای نمایش محتوای آمیخته باعث منسوخ شدن block-all-mixed-content شده است.
# CSP Errors:
# LOCALIZATION NOTE (couldntParseInvalidSource):
# %1$S is the source that could not be parsed
couldntParseInvalidSource = تجزیهٔ منبع نامعتبر %1$S امکان‌پذیر نیست
# LOCALIZATION NOTE (couldntParseInvalidHost):
# %1$S is the host that's invalid
couldntParseInvalidHost = تجزیهٔ میزبان نامعتبر %1$S امکان‌پذیر نیست
# LOCALIZATION NOTE (couldntParsePort):
# %1$S is the string source
couldntParsePort = تجزیهٔ درگاه (Port) در %1$S امکان‌پذیر نیست
# LOCALIZATION NOTE (duplicateDirective):
# %1$S is the name of the duplicate directive
duplicateDirective = دستورالعمل‌های تکراری %1$S شناسایی شد. همه به‌جز اولین مورد نادیده گرفته خواهند شد.
# LOCALIZATION NOTE (couldntParseInvalidSandboxFlag):
# %1$S is the option that could not be understood
couldntParseInvalidSandboxFlag = پرچم نامعتبر sandbox «%1$S» تجزیه نشد
# LOCALIZATION NOTE (invalidNumberOfTrustedTypesForDirectiveValues):
# %1$S is the number of passed tokens.
invalidNumberOfTrustedTypesForDirectiveValues = تعداد توکن‌های دریافتی برای دستورالعمل «require-trusted-types-for» نامعتبر است: %1$S؛ ۱ مورد مورد انتظار بود
# LOCALIZATION NOTE (invalidRequireTrustedTypesForDirectiveValue):
# %1$S is the passed token
invalidRequireTrustedTypesForDirectiveValue = توکن دریافتی برای دستورالعمل «require-trusted-types-for» نامعتبر است: %1$S؛ 'script' مورد انتظار بود
# LOCALIZATION NOTE (invalidTrustedTypesExpression):
# %1$S is the passed token
invalidTrustedTypesExpression = توکن دریافتی برای دستورالعمل «trusted-types» نامعتبر است: %1$S
# LOCALIZATION NOTE (CSPMessagePrefix):
# Do not translate "Content-Security-Policy", only handle spacing for the colon.
# %S is a console message that is being prefixed here.
CSPMessagePrefix = Content-Security-Policy: %S
# LOCALIZATION NOTE (CSPInlineStyleViolation):
# %1$S is the entire directive that has been violated. (e.g. "default-src 'none'")
# %2$S is the type of directive used by the resource (e.g. style-src-elem)
# %3$S is a SHA256 hash string.
# Don't translate anything inside ''
CSPInlineStyleViolation2 = تنظیمات صفحه مانع از اعمال یک سبک درون‌خطی (%2$S) شد زیرا دستورالعمل زیر را نقض می‌کند: «%1$S». استفاده از هش ('sha256-%3$S'، برای صفت‌های style نیازمند 'unsafe-hashes' است) یا یک nonce را در نظر بگیرید.
# LOCALIZATION NOTE (CSPROInlineStyleViolation):
# Don't translate "Report-Only" as it's part of the name Content-Security-Policy-Report-Only.
# %1$S is the entire directive that has been violated. (e.g. "default-src 'none'")
# %2$S is the type of directive used by the resource (e.g. style-src-elem)
# %3$S is a SHA256 hash string.
# Don't translate anything inside ''
CSPROInlineStyleViolation2 = (خط‌مشی Report-Only) تنظیمات صفحه مانع از اعمال یک سبک درون‌خطی (%2$S) می‌شد زیرا دستورالعمل زیر را نقض می‌کند: «%1$S». استفاده از هش ('sha256-%3$S'، برای صفت‌های style نیازمند 'unsafe-hashes' است) یا یک nonce را در نظر بگیرید.
# LOCALIZATION NOTE (CSPInlineScriptViolation):
# %1$S is the entire directive that has been violated. (e.g. "default-src 'none'")
# %2$S is the type of directive used by the resource (e.g. script-src-elem)
# %3$S is a SHA256 hash string.
# Don't translate anything inside ''
CSPInlineScriptViolation2 = تنظیمات صفحه مانع از اجرای یک اسکریپت درون‌خطی (%2$S) شد زیرا دستورالعمل زیر را نقض می‌کند: «%1$S». استفاده از هش ('sha256-%3$S') یا یک nonce را در نظر بگیرید.
# LOCALIZATION NOTE (CSPROInlineScriptViolation):
# Don't translate "Report-Only" as it's part of the name Content-Security-Policy-Report-Only.
# %1$S is the entire directive that has been violated. (e.g. "default-src 'none'")
# %2$S is the type of directive used by the resource (e.g. script-src-elem)
# %3$S is a SHA256 hash string.
# Don't translate anything inside ''
CSPROInlineScriptViolation2 = (خط‌مشی Report-Only) تنظیمات صفحه مانع از اجرای یک اسکریپت درون‌خطی (%2$S) می‌شد زیرا دستورالعمل زیر را نقض می‌کند: «%1$S». استفاده از هش ('sha256-%3$S') یا یک nonce را در نظر بگیرید.
# LOCALIZATION NOTE (CSPEventHandlerScriptViolation):
# %1$S is the entire directive that has been violated. (e.g. "default-src 'none'")
# %2$S is the type of directive used by the resource (e.g. script-src-attr)
# %3$S is a SHA256 hash string.
# Don't translate anything inside ''
CSPEventHandlerScriptViolation2 = تنظیمات صفحه مانع از اجرای یک گردانندهٔ رویداد (%2$S) شد زیرا دستورالعمل زیر را نقض می‌کند: «%1$S». استفاده از هش ('sha256-%3$S') همراه با 'unsafe-hashes' را در نظر بگیرید.
# LOCALIZATION NOTE (CSPROEventHandlerScriptViolation):
# Don't translate "Report-Only" as it's part of the name Content-Security-Policy-Report-Only.
# %1$S is the entire directive that has been violated. (e.g. "default-src 'none'")
# %2$S is the type of directive used by the resource (e.g. script-src-attr)
# %3$S is a SHA256 hash string.
# Don't translate anything inside ''
CSPROEventHandlerScriptViolation2 = (خط‌مشی Report-Only) تنظیمات صفحه مانع از اجرای یک گردانندهٔ رویداد (%2$S) می‌شد زیرا دستورالعمل زیر را نقض می‌کند: «%1$S». استفاده از هش ('sha256-%3$S') همراه با 'unsafe-hashes' را در نظر بگیرید.
