# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Rehwehwɛ { $host }…
network-connection-status-connected = Edu { $host }…
network-connection-status-sending-request = Repɛ asɛm efiri { $host }…
network-connection-status-transferring-data = Regye data efiri { $host }…
network-connection-status-connecting = Rekɔ { $host }…
network-connection-status-read = Kenkan { $host }
network-connection-status-wrote = Kyerɛɛw { $host }
network-connection-status-waiting = Retweɔn { $host }…
network-connection-status-looked-up = Hwehwɛɛ { $host }…
