# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE  (gotoLineCmd.promptTitle): This is the dialog title used
# when the user wants to jump to a specific line number in the code. You can
# access this feature by pressing Ctrl-J on Windows/Linux or Cmd-J on Mac.
gotoLineCmd.promptTitle = Dem ci rëdd...
# LOCALIZATION NOTE  (autocompletion.commandkey): This is the key, used with
# Ctrl, for code autocompletion.
# Do not localize "Space", it's the key identifier, not a message displayed to
# the user.
autocompletion.commandkey = Space
