# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language-name-aa = Afar
language-name-ab = Abchasko
language-name-ach = Acholi
language-name-ae = Awestańsko
language-name-af = Afrikaans
language-name-ak = Akan
language-name-am = Amharsko
language-name-an = Aragōńsko
language-name-ar = Arabsko
language-name-as = Asamsko
language-name-ast = Asturyjsko
language-name-av = Awarsko
language-name-ay = Ajmara
language-name-az = Azerbejdżańsko
language-name-ba = Baszkirsko
language-name-be = Białorusko
language-name-bg = Bułgarsko
language-name-bh = Biharsko
language-name-bi = Bislama
language-name-bm = Bambara
language-name-bn = Bengalsko
language-name-bo = Tybetańsko
language-name-br = Bretōńsko
language-name-bs = Bośniacko
language-name-ca = Katalōńsko
language-name-cak = Kaqchikel
language-name-ce = Czeczyńsko
language-name-ch = Chamorro
language-name-co = Korsykańsko
language-name-cr = Cree
language-name-crh = Krymsko tatarsko
language-name-cs = Czesko
language-name-csb = Kaszubsko
language-name-cu = Staro-cerkiewno-słowiańsko
language-name-cv = Czuwasko
language-name-cy = Walijsko
language-name-da = Duńsko
language-name-de = Niymecko
language-name-dsb = Dolnołużycko
language-name-dv = Malediwsko
language-name-dz = Dzongka
language-name-ee = Ewe
language-name-el = Grecko
language-name-en = Angelsko
language-name-eo = Esperanto
language-name-es = Hiszpańsko
language-name-et = Estōńsko
language-name-eu = Baskijsko
language-name-fa = Persko
language-name-ff = Ful
language-name-fi = Fińsko
language-name-fj = Fidżyjsko
language-name-fo = Faroesko
language-name-fr = Francusko
language-name-fur = Friulsko
language-name-fy = Fryzyjsko
language-name-ga = Irlandzko
language-name-gd = Szkocko gaelicko
language-name-gl = Galicyjsko
language-name-gn = Guarani
language-name-gu = Gudżarati
language-name-gv = Manksowo
language-name-ha = Hausa
language-name-haw = Hawajsko
language-name-he = Hebrajsko
language-name-hi = Hindi
language-name-hil = Hiligaynon
language-name-ho = Hiri Motu
