# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Želiš li vjerovati „%S” za sljedeće svrhe?
unnamedCA = Certifikacijsko tijelo (bezimeno)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Molim upišite lozinku s kojom je šifrirana sigurnosna kopija ovog certifikata:
# Page Info
pageInfo_NoEncryption = Nešifrirana veza
pageInfo_Privacy_None1 = Web stranica %S ne podržava šifriranje stranice koju gledaš.
pageInfo_Privacy_None2 = Informacije koje su poslane putem interneta bez prethodnog šifriranja mogu vidjeti ostali tijekom prijenosa.
pageInfo_Privacy_None4 = Stranica koju gledaš nije šifrirana prije slanja putem interneta.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Veza šifrirana (%1$S, %2$S bitni ključevi, %3$S)
pageInfo_BrokenEncryption = Neispravno šifriranje (%1$S, %2$S bitni ključevi, %3$S)
pageInfo_Privacy_Encrypted1 = Stranica koju gledaš šifrirana je prije slanja putem interneta.
pageInfo_Privacy_Encrypted2 = Šifriranje otežava neovlaštenim osobama pregledavanje informacija koje putuju između računala. Stoga je mala vjerojatnost da je netko pročitao ovu stranicu dok je putovala mrežom.
pageInfo_MixedContent = Djelomično šifrirana veza
pageInfo_MixedContent2 = Dijelovi stranice koju gledaš nisu šifrirani prije slanja putem interneta.
pageInfo_WeakCipher = Veza s ovom stranicom koristi slabo šifriranje, te nije privatna. Ostali ljudi mogu vidjeti tvoje podatke ili promijeniti ponašanje web stranice.
pageInfo_CertificateTransparency_Compliant = Ova web stranica je u skladu s politikom transparentnosti certifikata.
# Token Manager
password_not_set = (nije postavljeno)
