# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = इसके लिये देख रहा है { $host }...
network-connection-status-connected = { $host } में जुड़ा...
network-connection-status-sending-request = { $host } में आग्रह भेज रहा है...
network-connection-status-transferring-data = { $host } से आंकड़ा हस्तांतरित कर रहा है...
network-connection-status-connecting = { $host } में जुड़ा है...
network-connection-status-read = { $host } पढें
network-connection-status-wrote = { $host } लिखा
network-connection-status-waiting = { $host } के लिये प्रतीक्षारत...
network-connection-status-looked-up = { $host } के लिए देखा…
network-connection-status-tls-handshake = { $host } से एक TLS हैंड्शेक करते हुए…
network-connection-status-tls-handshake-finished = { $host } से TLS हैंड्शेक पूरा हो गया…
