# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Çerco { $host }…
network-connection-status-connected = Conesso a { $host }…
network-connection-status-sending-request = Mando a domanda a { $host }…
network-connection-status-transferring-data = Trasferiscio i dæti da { $host }…
network-connection-status-connecting = Conescion a { $host }…
network-connection-status-read = Lezo { $host }
network-connection-status-wrote = Scrito { $host }
network-connection-status-waiting = Aspeto { $host }…
network-connection-status-looked-up = Riçercou { $host }…
network-connection-status-tls-handshake = Fasso un handshske TLS pe { $host }…
network-connection-status-tls-handshake-finished = O handshake TLS o l'é finio pe { $host }…
