# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Uložit
dialogTitleAddBookmark = Přidat záložku
dialogTitleAddMulti = Přidat všechny panely do záložek
dialogTitleEdit = Vlastnosti „%S“
dialogTitleAddNewBookmark2 = Přidat záložku
dialogTitleEditBookmark = Upravit „%S“
dialogTitleEditBookmark2 = Upravit záložku
dialogTitleAddBookmarkFolder = Přidat složku záložek
dialogTitleEditBookmarkFolder = Upravit složku záložek
bookmarkAllTabsDefault = [Název složky]
newFolderDefault = Nová složka
newBookmarkDefault = Nová záložka
