# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Время ожидания истекло
openFile = Открыть файл
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Искать «%2$S» в %1$S
contextMenuSearch.accesskey = И
contextMenuPrivateSearch = Искать в приватном окне
contextMenuPrivateSearch.accesskey = в
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Искать с помощью %S в приватном окне
contextMenuPrivateSearchOtherEngine.accesskey = в
bookmarkAllTabsDefault = [Имя папки]
unsignedAddonsDisabled.message = Одно или несколько установленных дополнений не могут быть проверены, поэтому они были отключены.
unsignedAddonsDisabled.learnMore.label = Подробнее
unsignedAddonsDisabled.learnMore.accesskey = П
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Последний доступ %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = Ссылки %S://
crashedpluginsMessage.title = Плагин %S аварийно завершил работу.
crashedpluginsMessage.reloadButton.label = Перезагрузить страницу
crashedpluginsMessage.reloadButton.accesskey = П
crashedpluginsMessage.submitButton.label = Отправить сообщение о падении
crashedpluginsMessage.submitButton.accesskey = П
crashedpluginsMessage.learnMore = Подробнее…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Возможно, вы хотели перейти на %S?
keywordURIFixup.goTo = Да, перейти на %S
keywordURIFixup.goTo.accesskey = Д
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Обновить до %S
update.downloadAndInstallButton.accesskey = Н
menuOpenAllInTabs.label = Открыть всё во вкладках
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Перезагрузить эту страницу
tabHistory.goBack = Вернуться на эту страницу
tabHistory.goForward = Перейти на эту страницу
# URL Bar
pasteAndGo.label = Вставить и перейти
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Обновить текущую страницу (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Остановить загрузку страницы (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Сбросить масштаб (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Включить/отключить вид для чтения (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, Сбросить масштаб
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Показать ваши закладки (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Показать ход текущих загрузок (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Открыть новое окно (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Открыть новую вкладку (%S)
newTabContainer.tooltip = Открыть новую вкладку (%S)\nНажмите и удерживайте, чтобы открыть новую вкладку в контейнере
newTabAlwaysContainer.tooltip = Выберите контейнер, чтобы открыть новую вкладку
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Разрешить %S использовать ваши данные из HTML5 canvas-изображения?
canvas.siteprompt2.warning = Это может использоваться для однозначной идентификации вашего компьютера.
canvas.block = Блокировать
canvas.block.accesskey = Б
canvas.allow2 = Разрешить
canvas.allow2.accesskey = Р
canvas.remember2 = Запомнить это решение
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Подтверждено: %S
identity.identified.verified_by_you = Вы добавили исключение безопасности для этого сайта.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Сертификат выдан: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Не защищено
identity.notSecure.tooltip = Соединение не защищено
identity.extension.label = Расширение (%S)
identity.extension.tooltip = Загружено расширением: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Уменьшить (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Сбросить масштаб (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Увеличить (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Вырезать (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Копировать (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Вставить (%S)
geolocation.allow = Разрешить
geolocation.allow.accesskey = Р
geolocation.block = Блокировать
geolocation.block.accesskey = Б
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Это действие откроет системные настройки местоположения. Предоставьте %S разрешение на обнаружение местоположения.
geolocation.shareWithSite4 = Разрешить %S доступ к вашему местоположению?
geolocation.shareWithFile4 = Разрешить этому локальному файлу доступ к вашему местоположению?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Разрешить %1$S предоставить %2$S доступ к вашему местоположению?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Предоставить %S разрешение на определение местоположения в системных настройках.
geolocation.systemSettingsTitle = Ожидание разрешения на определение местоположения
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Система попросит вас предоставить это разрешение %S.
geolocation.remember = Запомнить это решение
# Virtual Reality Device UI
xr.allow2 = Разрешить
xr.allow2.accesskey = Р
xr.block = Блокировать
xr.block.accesskey = Б
xr.shareWithSite4 = Разрешить %S доступ к устройствам виртуальной реальности? Это может привести к раскрытию личной информации.
xr.shareWithFile4 = Разрешить этому локальному файлу доступ к устройствам виртуальной реальности? Это может привести к раскрытию личной информации.
xr.remember = Запомнить это решение
# Persistent storage UI
persistentStorage.allow = Разрешить
persistentStorage.allow.accesskey = Р
persistentStorage.block.label = Блокировать
persistentStorage.block.accesskey = Б
persistentStorage.allowWithSite2 = Разрешить %S хранить данные в постоянном хранилище?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Разрешить
webNotifications.allow2.accesskey = Р
webNotifications.notNow = Не сейчас
webNotifications.notNow.accesskey = н
webNotifications.never = Никогда не разрешать
webNotifications.never.accesskey = и
webNotifications.alwaysBlock = Всегда блокировать
webNotifications.alwaysBlock.accesskey = Е
webNotifications.block = Блокировать
webNotifications.block.accesskey = Б
webNotifications.receiveFromSite3 = Разрешить %S отправлять уведомления?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S хочет получить доступ к другим приложениям и службам на этом устройстве.
localhost.remember2 = Запомнить мой выбор для этого сайта
localhost.allowlabel = Разрешить
localhost.blocklabel = Блокировать
localhost.allow.accesskey = A
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S хочет получить доступ к приложениям и службам на устройствах, подключённых к вашей локальной сети.
localNetwork.remember2 = Запомнить мой выбор для этого сайта
localNetwork.allowLabel = Разрешить
localNetwork.allow.accesskey = A
localNetwork.blockLabel = Блокировать
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Заберите меня отсюда!
safebrowsing.getMeOutOfHereButton.accessKey = З
safebrowsing.deceptiveSite = Поддельный сайт!
safebrowsing.notADeceptiveSiteButton.label = Это не поддельный сайт…
safebrowsing.notADeceptiveSiteButton.accessKey = Н
safebrowsing.reportedAttackSite = Есть информация, что это — атакующий сайт!
safebrowsing.notAnAttackButton.label = Это — не атакующий сайт…
safebrowsing.notAnAttackButton.accessKey = Н
safebrowsing.reportedUnwantedSite = Есть информация, что этот сайт содержит нежелательные программы!
safebrowsing.reportedHarmfulSite = Есть информация, что этот сайт представляет опасность!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Поиск по %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Перезапустить %S в безопасном режиме?
troubleshootModeRestartPromptMessage = Ваши расширения, темы и собственные настройки будут временно отключены.
troubleshootModeRestartButton = Перезапустить
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Эта страница замедляет %1$S. Чтобы ускорить работу браузера, остановите её.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Веб-страница замедляет %1$S. Чтобы ускорить работу браузера, остановите её.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = «%1$S» замедляет %2$S. Чтобы ускорить работу браузера, остановите эту страницу.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = «%1$S» замедляет %2$S. Чтобы ускорить работу браузера, остановите это расширение.
processHang.add-on.learn-more.text = Подробнее
processHang.button_stop2.label = Остановить
processHang.button_stop2.accessKey = О
processHang.button_debug.label = Отладить скрипт
processHang.button_debug.accessKey = Л
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Открыть окно в полноэкранном режиме (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Переместить боковую панель влево
sidebar.moveToRight = Переместить боковую панель вправо
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Для проигрывания некоторых аудио или видео на этой странице нужно включить DRM.
emeNotifications.drmContentDisabled.button.label = Включить DRM
emeNotifications.drmContentDisabled.button.accesskey = В
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S устанавливает компоненты, необходимые для воспроизведения аудио или видео на этой странице. Пожалуйста, попробуйте ещё раз позже.
emeNotifications.unknownDRMSoftware = Неизвестно
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Настройка %S
decoder.noCodecs.button = Подробнее
decoder.noCodecs.accesskey = П
decoder.noCodecsLinux.message = Для воспроизведения видео вам может потребоваться установить необходимые видеокодеки.
decoder.noHWAcceleration.message = Для улучшения качества видео вам может потребоваться установить Мedia Feature Pack от Microsoft.
decoder.noPulseAudio.message = Для воспроизведения аудио вам может потребоваться установить необходимое программное обеспечение PulseAudio.
decoder.unsupportedLibavcodec.message = libavcodec может быть уязвим или не поддерживаться и должен быть обновлён для воспроизведения видео.
decoder.decodeError.message = При декодировании медиаресурса произошла ошибка.
decoder.decodeError.button = Сообщить о проблеме с сайтом
decoder.decodeError.accesskey = П
decoder.decodeWarning.message = При декодировании медиаресурса произошла ошибка, которую можно исправить.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Вы должны войти в эту сеть перед тем, как сможете получить доступ к Интернету.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Открыть страницу входа в сеть
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Разрешения для %S
permissions.remove.tooltip = Удалить это разрешение и спросить снова
permissions.fullscreen.promptCanceled = Ожидание запросов на разрешение прекращено: запросы на разрешение не должны отправляться до перехода в полноэкранный режим DOM.
permissions.fullscreen.fullScreenCanceled = Выход из полноэкранного режима DOM: запросы на разрешение не должны отправляться при нахождении в полноэкранном режиме DOM.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-разрядная
aboutDialog.architecture.thirtyTwoBit = 32-разрядная
midi.allow.label = Разрешить
midi.allow.accesskey = Р
midi.block.label = Блокировать
midi.block.accesskey = Б
midi.remember = Запомнить это решение
midi.shareWithFile = Разрешить этому локальному файлу доступ к вашим MIDI-устройствам?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Разрешить %S доступ к вашим MIDI-устройствам?
midi.shareSysexWithFile = Разрешить этому локальному файлу доступ к вашим MIDI-устройствам и отправку/получение SysEx-сообщений?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Разрешить %S доступ к вашим MIDI-устройствам и отправку/получение SysEx-сообщений?
serial.allow.label = Разрешить
serial.allow.accesskey = Ф
serial.block.label = Блокировать
serial.block.accesskey = И
serial.shareWithFile = Разрешить этому локальному файлу доступ к вашим последовательным портам?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = Разрешить %S доступ к вашим последовательным портам?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Назад
storageAccess1.Allow.label = Разрешить
storageAccess1.Allow.accesskey = Р
storageAccess1.DontAllow.label = Блокировать
storageAccess1.DontAllow.accesskey = Б
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Разрешить %1$S использовать собственные куки на %2$S?
storageAccess1.hintText = Вы можете заблокировать доступ, если не понимаете, зачем %1$S нужны эти данные.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Искать в Интернете «%S»
