# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Kredenciale Hyrjesh të Ruajtura
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Kopjoji URL-në
    .accesskey = U
launch-site-url-cmd =
    .label = Vizitoje URL-në
    .accesskey = V
copy-username-cmd =
    .label = Kopjo Emër Përdoruesi
    .accesskey = E
edit-username-cmd =
    .label = Përpunoni Emrin e Përdoruesit
    .accesskey = d
copy-password-cmd =
    .label = Kopjo Fjalëkalimin
    .accesskey = K
edit-password-cmd =
    .label = Përpunoni Fjalëkalimin
    .accesskey = F
search-filter =
    .accesskey = K
    .placeholder = Kërko
column-heading-site =
    .label = Sajt
column-heading-username =
    .label = Emër përdoruesi
column-heading-password =
    .label = Fjalëkalim
column-heading-time-created =
    .label = Përdorur Së Pari
column-heading-time-last-used =
    .label = Përdorur Së Fundi
column-heading-time-password-changed =
    .label = Ndryshuar Së Fundi
column-heading-times-used =
    .label = Numër Përdorimesh
remove =
    .label = Hiqe
    .accesskey = H
import =
    .label = Importoni…
    .accesskey = I
close-button =
    .label = Mbylleni
    .accesskey = M
show-passwords =
    .label = Shfaqi Fjalëkalimet
    .accesskey = a
hide-passwords =
    .label = Fshihi Fjalëkalimet
    .accesskey = i
logins-description-all = Kredencialet për sajtet vijues janë të depozituara në kompjuterin tuaj
logins-description-filtered = Me kërkimin tuaj përputhen kredencialet vijuese për hyrje:
remove-all =
    .label = Hiqi Krejt
    .accesskey = K
remove-all-shown =
    .label = Hiqi Krejt të Shfaqurit
    .accesskey = K
remove-all-passwords-prompt = Jeni i sigurt se doni të hiqen tërë fjalëkalimet?
remove-all-passwords-title = Hiqini tërë fjalëkalimet
no-master-password-prompt = Jeni i sigurt se doni të shfaqen fjalëkalimet tuaj?
auto-fill-logins-and-passwords =
    .label = Vetëplotëso kredenciale hyrjeje dhe fjalëkalime
