# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Voulez-vous faire confiance à « %S » pour les actions suivantes ?
unnamedCA = Autorité de certification (pas de nom)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Veuillez saisir le mot de passe portable de sécurité protégeant ce certificat de sécurité et la clé privée :
# Page Info
pageInfo_NoEncryption = Connexion non chiffrée
pageInfo_Privacy_None1 = Le site web %S ne prend pas en charge le chiffrement pour la page actuellement affichée.
pageInfo_Privacy_None2 = Les informations envoyées sur Internet sans chiffrement peuvent être vues par d’autres personnes durant leur transit.
pageInfo_Privacy_None4 = La page actuellement affichée n’a pas été chiffrée avant d’avoir été envoyée sur Internet.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Connexion chiffrée (clés %1$S, %2$S bits, %3$S)
pageInfo_BrokenEncryption = Chiffrement non fiable (clés %1$S, %2$S bits, %3$S)
pageInfo_Privacy_Encrypted1 = La page actuellement affichée a été chiffrée avant d’avoir été envoyée sur Internet.
pageInfo_Privacy_Encrypted2 = Le chiffrement rend très difficile aux personnes non autorisées la visualisation de la page durant son transit entre ordinateurs. Il est donc très improbable que quelqu’un puisse lire cette page durant son transit sur le réseau.
pageInfo_MixedContent = Connexion partiellement chiffrée
pageInfo_MixedContent2 = Certaines parties de la page que vous visionnez n’ont pas été chiffrées avant d’être transmises sur Internet.
pageInfo_WeakCipher = La connexion vers ce site possède un niveau de chiffrement trop bas et n’est pas privée. N’importe qui est en mesure d’afficher vos informations ou de modifier le comportement du site web.
pageInfo_CertificateTransparency_Compliant = Ce site web respecte la politique de transparence du certificat.
# Token Manager
password_not_set = (non défini)
