#filter emptyLines

#define MOZ_LANGPACK_CREATOR vi.mozilla.org

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>NGUYỄN Mạnh Hùng</em:contributor> <em:contributor>NGUYỄN Xuân Minh</em:contributor> <em:contributor>HUỲNH Hải Đăng</em:contributor> <em:contributor>BÙI Việt Khoa</em:contributor> <em:contributor>TRẦN Nguyên Sơn</em:contributor>

#unfilter emptyLines
