# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

addons-window =
    .title = Ldi amsefrak n izegrar
search-header-shortcut =
    .key = f
loading-label =
    .value = Asali…
list-empty-installed =
    .value = Ur ɣur-k ara azegrir yettwasebden n tewsit-agi{ " " }
list-empty-available-updates =
    .value = ulac ileqman yettwafen
list-empty-recent-updates =
    .value = Acḥal aya ur tesnifleḍ ara izegrar-ik
list-empty-find-updates =
    .label = Senqed ma llan ileqman
list-empty-button =
    .label = Issin ugar ɣef izegrar
install-addon-from-file =
    .label = Sebded azegrir seg ufaylu…
    .accesskey = S
tools-menu =
    .tooltiptext = Ifecka i yizegrar imaṛṛa
show-all-extensions-button =
    .label = Sken akk iseɣzaf
debug-addons =
    .label = Izegrar n tseɣtit
    .accesskey = I
cmd-show-details =
    .label = Sken ugar n telɣut
    .accesskey = S
cmd-find-updates =
    .label = Nadi ileqman
    .accesskey = N
cmd-enable-theme =
    .label = Snes asentel
    .accesskey = S
cmd-disable-theme =
    .label = Kkes asentel
    .accesskey = K
cmd-install-addon =
    .label = Sebded
    .accesskey = S
cmd-contribute =
    .label = Ţekki
    .accesskey = k
    .tooltiptext = Ţekki di tneflit n uzegrir
detail-version =
    .label = Lqem
detail-last-updated =
    .label = Aleqqem aneggaru
detail-update-type =
    .value = Aleqqem awurman
detail-update-default =
    .label = Awennez amezwaru
    .tooltiptext = Sebded ileqman s wudem awurman ma yella d-amezwer kan.
detail-update-automatic =
    .label = Yermed
    .tooltiptext = Sebded ileqman s wudem awurman
detail-update-manual =
    .label = Yensa
    .tooltiptext = Ur sebdad ara ileqman s wudem awurman
detail-home =
    .label = Asebter agejdan
detail-home-value =
    .value = { detail-home.label }
detail-repository =
    .label = Amaɣnu n uzegrir
detail-repository-value =
    .value = { detail-repository.label }
detail-check-for-updates =
    .label = Senqed ma llan ileqman imaynuten
    .accesskey = S
    .tooltiptext = senqed ileqman n uzegrir-agi
detail-rating =
    .value = Adakaḍ
addon-restart-now =
    .label = Ales asenker tura
disabled-unsigned-heading =
    .value = Kra n izegrar yettwassensen
disabled-unsigned-description = Izegrar-agi ur ttwasneqden ara i useqdec n { -brand-short-name }. Tzemreḍ <label data-l10n-name="find-addons">nadi izegrar igdazalen</label> neɣ suter aneflay aten id-isenqed.
disabled-unsigned-learn-more = Issin ugar ɣef ayen n mahel akken ak-d-mudd ugar n tɣellist s srid.
disabled-unsigned-devinfo = ineflayen yebɣan ad sneqden izegrar nsen zemren ad d-awin ugar n telɣut ma ɣṛan <label data-l10n-name="learn-more">s ufus</label>.
plugin-deprecation-description = Tettut kra? Kra nizegrar ur ttwasefranken ara tura di { -brand-short-name }. <label data-l10n-name="learn-more">Issin ugar</label>
