# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host } ізделуде…
network-connection-status-connected = { $host } адресімен байланысқан…
network-connection-status-sending-request = { $host } адресіне сұраным жіберу…
network-connection-status-transferring-data = { $host } адресінен деректерді алу…
network-connection-status-connecting = { $host } адресімен байланысты орнату…
network-connection-status-tls-handshake = { $host } адресімен TLS байланысын орнату жүруде…
network-connection-status-tls-handshake-finished = { $host } адресімен TLS байланысын орнату аяқталды…
