# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Ajalimiit ületatud
openFile = Faili avamine
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Otsi mootoriga %1$S fraasi "%2$S"
contextMenuSearch.accesskey = i
contextMenuPrivateSearch = Otsi privaatses aknas
contextMenuPrivateSearch.accesskey = p
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Otsi otsingumootoriga %S privaatses aknas
contextMenuPrivateSearchOtherEngine.accesskey = p
bookmarkAllTabsDefault = [Kausta nimi]
unsignedAddonsDisabled.message = Vähemalt üht paigaldatud lisa polnud võimalik verifitseerida. Verifitseerimata lisad keelati.
unsignedAddonsDisabled.learnMore.label = Rohkem teavet
unsignedAddonsDisabled.learnMore.accesskey = R
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Asukohta vaadati viimati %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = %S:// lingid
crashedpluginsMessage.title = Plugin %S on kokku jooksnud.
crashedpluginsMessage.reloadButton.label = Laadi leht uuesti
crashedpluginsMessage.reloadButton.accesskey = L
crashedpluginsMessage.submitButton.label = Sisesta vearaport
crashedpluginsMessage.submitButton.accesskey = S
crashedpluginsMessage.learnMore = Rohkem teavet…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Kas soovisid minna aadressile "%S"?
keywordURIFixup.goTo = Jah, ava aadress "%S"
keywordURIFixup.goTo.accesskey = J
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Uuenda versioonile %S
update.downloadAndInstallButton.accesskey = U
menuOpenAllInTabs.label = Ava kõik kaartidel
tabHistory.goBack = Mine tagasi sellele lehele
tabHistory.goForward = Mine edasi sellele lehele
# URL Bar
pasteAndGo.label = Aseta ja mine
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Laadi leht uuesti (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Peata selle lehe laadimine (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Lähtesta suurendamine (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Lülita lugemisvaade sisse/välja (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Kuva järjehoidjaid (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Kuva käimasolevate allalaadimiste edenemist (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Ava uus aken (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Ava uus kaart (%S)
newTabContainer.tooltip = Ava uus kaart (%S)\nKonteineris avamiseks hoia nuppu all
newTabAlwaysContainer.tooltip = Vali uue kaardi avamiseks konteiner
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Kas lubada saidil %S kasutada sinu HTML5 kanvaa piltide andmeid?
canvas.siteprompt2.warning = Seda saab kasutada sinu arvuti ainulaadseks tuvastamiseks.
canvas.block = Bloki
canvas.block.accesskey = B
canvas.allow2 = Luba
canvas.allow2.accesskey = L
canvas.remember2 = See otsus peetakse meeles
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Verifitseerija: %S
identity.identified.verified_by_you = Sa oled selle lehe kohta lisanud turvalisuse erandi
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Serdi omanik: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Pole turvaline
identity.notSecure.tooltip = Ühendus pole turvaline
identity.extension.label = Laiendus (%S)
identity.extension.tooltip = Laaditud järgneva laienduse poolt: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Vähenda (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Lähtesta suurendamine (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Suurenda (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Lõika (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Kopeeri (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Aseta (%S)
geolocation.allow = Luba
geolocation.allow.accesskey = L
geolocation.block = Bloki
geolocation.block.accesskey = B
geolocation.shareWithSite4 = Kas anda saidile %S ligipääs sinu asukoha andmetele?
geolocation.shareWithFile4 = Kas anda sellele kohalikule failile ligipääs sinu asukoha andmetele?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Kas lubad saidil %1$S anda ligipääs sinu asukoha andmetele saidile %2$S?
geolocation.remember = See otsus jäetakse meelde
# Virtual Reality Device UI
xr.allow2 = Luba
xr.allow2.accesskey = L
xr.block = Bloki
xr.block.accesskey = B
xr.shareWithSite4 = Kas anda saidile %S ligipääs virtuaalreaalsuse seadmetele? See võib paljastada tundlikku teavet.
xr.shareWithFile4 = Kas anda sellele kohalikule failile ligipääs virtuaalreaalsuse seadmetele? See võib paljastada tundlikku teavet.
xr.remember = See otsus peetakse meeles
# Persistent storage UI
persistentStorage.allow = Luba
persistentStorage.allow.accesskey = L
persistentStorage.block.label = Bloki
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Kas lubada saidil %S salvestada andmeid püsivalt?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Luba
webNotifications.allow2.accesskey = L
webNotifications.notNow = Mitte praegu
webNotifications.notNow.accesskey = M
webNotifications.never = Ära luba mitte kunagi
webNotifications.never.accesskey = r
webNotifications.alwaysBlock = Blokitakse alati
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = Bloki
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Kas lubada saidil %S saata teavitusi?
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Aita mind siit välja!
safebrowsing.getMeOutOfHereButton.accessKey = A
safebrowsing.deceptiveSite = Veebivõltsingu hoiatus!
safebrowsing.notADeceptiveSiteButton.label = See pole veebivõltsing…
safebrowsing.notADeceptiveSiteButton.accessKey = S
safebrowsing.reportedAttackSite = Ründava veebilehe hoiatus!
safebrowsing.notAnAttackButton.label = See pole ründav veebileht…
safebrowsing.notAnAttackButton.accessKey = S
safebrowsing.reportedUnwantedSite = Soovimatu tarkvara levitamise kahtlus!
safebrowsing.reportedHarmfulSite = Kahjuliku veebilehe hoiatus!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Otsi lehelt %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Kas taaskäivitada %S tõrkeotsingurežiimis?
troubleshootModeRestartPromptMessage = Ajutiselt keelatakse laiendused, teemad ja kohandatud sätted.
troubleshootModeRestartButton = Taaskäivita
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = See leht aeglustab %1$Si. Brauseri kiirendamiseks peata see leht.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Veebileht aeglustab %1$Si. Brauseri kiirendamiseks peata see leht.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = Kaart “%1$S” aeglustab %2$Si. Brauseri kiirendamiseks peata see leht.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = Laiendus “%1$S” aeglustab %2$Si. Brauseri kiirendamiseks peata see laiendus.
processHang.add-on.learn-more.text = Rohkem teavet
processHang.button_stop2.label = Peata
processHang.button_stop2.accessKey = P
processHang.button_debug.label = Debugi skripti
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Kuva akent täisekraanirežiimis (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Liiguta külgriba vasakule
sidebar.moveToRight = Liiguta külgriba paremale
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Osa sellel lehel oleva audio või video esitamiseks tuleb lubada DRM.
emeNotifications.drmContentDisabled.button.label = Luba DRM
emeNotifications.drmContentDisabled.button.accesskey = L
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S paigaldab komponente, mis on vajalikud sellel lehel oleva audio või video esitamiseks. Palun proovi hiljem uuesti.
emeNotifications.unknownDRMSoftware = Tundmatu
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = %Si kohandamine
decoder.noCodecs.button = Rohkem teavet
decoder.noCodecs.accesskey = R
decoder.noCodecsLinux.message = Video esitamiseks tuleb paigaldada nõutud videokoodekid.
decoder.noHWAcceleration.message = Video kvaliteedi parandamiseks võid paigaldada Microsofti meediumifunktsioonide paketi.
decoder.noPulseAudio.message = Heli esitamiseks on võib-olla vaja paigaldada tarkvara PulseAudio.
decoder.unsupportedLibavcodec.message = libavcodec võib olla haavatav või pole toetatud ning video esitamiseks tuleks see uuendada.
decoder.decodeError.message = Meediaressursi dekodeerimisel esines viga.
decoder.decodeError.button = Anna teada saidil olevast veast
decoder.decodeError.accesskey = A
decoder.decodeWarning.message = Meediaressursi dekodeerimisel esines parandatav viga.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Internetti pääsemiseks pead sellesse võrku sisse logima.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Ava sisselogimisleht
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Saidi %S õigused
permissions.remove.tooltip = Eemalda see luba ja küsi uuesti
permissions.fullscreen.promptCanceled = Ootel õigustetaotlus tühistati: õigustetaotlust ei tohiks enne täisekraanirežiimi sisenemist esitada.
permissions.fullscreen.fullScreenCanceled = Täisekraanirežiimist väljuti: õigustetaotlust ei tohiks täisekraanirežiimis olles esitada.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bitine
aboutDialog.architecture.thirtyTwoBit = 32-bitine
midi.allow.label = Luba
midi.allow.accesskey = L
midi.block.label = Bloki
midi.block.accesskey = B
midi.remember = See otsus peetakse meeles
midi.shareWithFile = Kas lubad sellel kohalikul failil ligi pääseda oma MIDI-seadmetele?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Kas lubad saidil %S ligi pääseda oma MIDI-seadmetele?
midi.shareSysexWithFile = Kas lubad saidil %S ligi pääseda oma MIDI-seadmetele ja saata ning võtta vastu SysEx sõnumeid?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Kas lubad saidil %S ligi pääseda oma MIDI-seadmetele ja saata ning võtta vastu SysEx sõnumeid?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Tagasi
storageAccess1.Allow.label = Luba
storageAccess1.Allow.accesskey = L
storageAccess1.DontAllow.label = Bloki
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Kas lubad saidil %1$S kasutada oma küpsiseid saidil %2$S?
storageAccess1.hintText = Võid selle ligipääsu blokkida, kui pole selge, miks sait %1$S neid andmeid vajab.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Otsi veebist fraasi “%S”
