# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-connected = Ga ciya nda { $host }…
network-connection-status-sending-request = Goo ma hãayan sanba { $host } do…
network-connection-status-transferring-data = Goo ma bayhayey berandi ka hun { $host } do…
network-connection-status-connecting = Goo ma ciya { $host } še…
network-connection-status-read = { $host } caw
network-connection-status-wrote = Hantumandi { $host } ga
network-connection-status-waiting = Goo ma { $host } batu…
network-connection-status-looked-up = Na { $host } guna…
