# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Търсене на { $host }…
network-connection-status-connected = Свързване с { $host }…
network-connection-status-sending-request = Заявка до { $host }…
network-connection-status-transferring-data = Прехвърляне на данни от { $host }…
network-connection-status-connecting = Свързване с { $host }…
network-connection-status-read = Прочетен е { $host }
network-connection-status-wrote = Записан е { $host }
network-connection-status-waiting = Изчакване на { $host }…
network-connection-status-looked-up = Търсене на { $host }…
network-connection-status-tls-handshake = Здрависване по TLS с { $host }…
network-connection-status-tls-handshake-finished = Здрависването по TLS с { $host } завършено…
