# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Info Masuk Tersimpan
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Salin URL
    .accesskey = S
launch-site-url-cmd =
    .label = Kunjungi URL
    .accesskey = K
copy-username-cmd =
    .label = Salin Nama Pengguna
    .accesskey = P
edit-username-cmd =
    .label = Edit Nama Pengguna
    .accesskey = d
copy-password-cmd =
    .label = Salin Sandi
    .accesskey = S
edit-password-cmd =
    .label = Edit Sandi
    .accesskey = E
search-filter =
    .accesskey = C
    .placeholder = Cari
column-heading-site =
    .label = Situs
column-heading-username =
    .label = Nama Pengguna
column-heading-password =
    .label = Sandi
column-heading-time-created =
    .label = Pertama Digunakan
column-heading-time-last-used =
    .label = Terakhir Digunakan
column-heading-time-password-changed =
    .label = Terakhir Diubah
column-heading-times-used =
    .label = Jumlah Penggunaan
remove =
    .label = Hapus
    .accesskey = H
import =
    .label = Impor…
    .accesskey = I
close-button =
    .label = Tutup
    .accesskey = T
show-passwords =
    .label = Tampilkan Sandi
    .accesskey = T
hide-passwords =
    .label = Sembunyikan Sandi
    .accesskey = S
logins-description-all = Info masuk untuk situs berikut telah disimpan pada komputer Anda
logins-description-filtered = Info masuk berikut ini cocok dengan pencarian Anda:
remove-all =
    .label = Hapus Semua
    .accesskey = S
remove-all-shown =
    .label = Hapus Semua Yang Muncul
    .accesskey = S
remove-all-passwords-prompt = Yakin akan menghapus semua sandi?
remove-all-passwords-title = Hapus seluruh sandi
no-master-password-prompt = Yakin ingin menampilkan sandi Anda?
auto-fill-logins-and-passwords =
    .label = Isi info masuk dan kata sandi secara otomatis
