# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

ssl-error-no-cypher-overlap = పీర్‌తో సురక్షితంగా సంప్రదింపు జరుపలేకపోయింది: ఏ వుమ్మడి ఎన్క్రిప్షన్ అల్గార్దెమ్(లు) లేవు.
ssl-error-no-certificate = ధృవీకరణకు తప్పనిసరైన ధృవీకరణపత్రంగాని లేదా కీగాని కనబడలేదు.
ssl-error-ssl2-disabled = పీర్ స్థానికంగా అచేతనం చేసిన, SSL వర్షన్ 2 మాత్రమే మద్దతిస్తోంది.
ssl-error-ssl-disabled = అనుసంధానం కాలేదు: SSL అచేతనం చేయబడింది.
ssl-error-unknown-cipher-suite = ఒక తెలియని SSL సైఫర్ సూట్ అభ్యర్ధించబడింది.
ssl-error-bad-block-padding = చెడ్డ బ్లాక్ పాడింగ్‌తో SSL ఒక రికార్డు‌ పొందింది.
ssl-error-rx-record-too-long = గరిష్టంగా అనుమతించిన పొడవును మించిన రికార్డు‌ను SSL పొందింది.
ssl-error-tx-record-too-long = గరిష్టంగా అనుమతించిన పొడవును మించిన రికార్డు‌ను SSL పంపుటకు ప్రయత్నించింది.
ssl-error-rx-unexpected-hello-request = SSL అనుకోని హెల్లో అభ్యర్ధన హాండ్‌షేక్ సందేశాన్ని పొందింది.
ssl-error-rx-unexpected-client-hello = SSL అనుకోని క్లైంట్ హెల్లో హాండ్‌షేక్ సందేశాన్ని పొందింది.
ssl-error-rx-unexpected-server-hello = SSL అనుకోని సేవిక హెల్లో హాండ్‌షేక్ సందేశాన్ని పొందింది.
ssl-error-rx-unexpected-hello-done = SSL అనుకోని సేవిక హెల్లో డన్ హాండ్‌షేక్ సందేశాన్ని పొందింది.
ssl-error-rx-unexpected-client-key-exch = SSL అనుకోని క్లైంట్ కీ ఎక్సేంజ్ హాండ్‌షేక్ సందేశాన్ని పొందింది.
ssl-error-rx-unexpected-change-cipher = SSL అనుకోని చేంజ్ సైఫర్ స్పెక్ రికార్డు‌ను పొందింది.
ssl-error-rx-unexpected-alert = SSL అనుకోని ఎలర్టు రికార్డు‌ను పొదింది.
ssl-error-rx-unexpected-handshake = SSL అనుకోని హాండ్‌షేక్ రికార్డు‌ను పొందింది.
ssl-error-rx-unexpected-application-data = SSL అనుకోని అనువర్తనం డాటా రికార్డు‌ను పొందింది.
ssl-error-rx-unknown-record-type = SSL తెలియని సారము రకముతో ఒక రికార్డు‌ను పొందింది.
ssl-error-rx-unknown-handshake = SSL ఒక తెలియని సందేశరకముతో హాండ్‌షేక్ సందేశాన్ని పొందింది.
ssl-error-rx-unknown-alert = SSL తెలియని ఎలర్టు వివరణతో ఒక ఎలర్టు ‌ రికార్డు‌ను పొందింది.
ssl-error-close-notify-alert = SSL పీర్ ఈ అనుసంధానాన్ని మూసివేసినది.
ssl-error-handshake-unexpected-alert = SSL పీర్ అదిపొందిన హాండ్‌షేక్ సందేశం కొరకు చూడుటలేదు.
ssl-error-handshake-failure-alert = SSL పీర్ ఆమోదయోగ్యమైన రక్షణ పారామితుల సమితిని సంధిచేయలేక పోతోంది.
ssl-error-illegal-parameter-alert = SSL పీర్ ఆమోదయోగ్యంకాని సారముకొరకు హండ్‌షేక్ సందేశాన్ని తిరస్కరించింది.
ssl-error-unsupported-cert-alert = SSL పీర్ అదిపొందిన ఈరకం ధృవీకరణపత్రములకు మద్దతీయదు.
ssl-error-generate-random-failure = SSL దాని రాండమ్ నంబర్ జనరేటర్ వైఫల్యాన్ని చవిచూసింది.
ssl-error-sign-hashes-failure = మీ ధృవీకరణపత్రాన్ని నిర్ధారించుటకు అవసరమైన డాటాను డిజిటల్‌గా సైన్ చేయలేకపోతోంది.
ssl-error-client-key-exchange-failure = SSL క్లైంట్ కీ ఎక్సేంజ్ హాండ్‌షేక్ జరుపుతున్నప్పుడు తెలియని వైఫల్యం.
ssl-error-decryption-failure = బల్కుడాటా ఎన్క్రిప్షన్ అల్గార్దెమ్ ఎంపికచేసిన సైఫర్ సూట్‌నందు వైఫల్యమైంది.
ssl-error-socket-write-failure = అండర్‌లేయింగ్ సాకెట్‌కు ఎన్క్రిప్టెడ్ డాటాను వ్రాయుప్రయత్నం విఫలమైంది.
ssl-error-sha-digest-failure = SHA-1 డైజస్ట్ కార్యక్రమం విఫలమైంది..
ssl-error-mac-computation-failure = MAC గణనము విఫలమైంది.
ssl-error-sym-key-unwrap-failure = క్లైంట్ కీ ఎక్సేంజ్ సందేశంనందు సిమ్మెట్రిక్ కీ అన్‌వ్రాప్ విఫలమైంది.
ssl-error-iv-param-failure = PKCS11 కోడ్ IVను పరమ్‌లోకు అనువదించుటలో విఫలమైంది.
ssl-error-init-cipher-suite-failure = ఎంపికచేసిన సైఫర్ సూట్‌ను సిద్దముచేయుటలో విఫలమైంది.
ssl-error-token-slot-not-found = కావలిసిన ఆపరేషన్ చేయుటకు PKCS#11 టోకెన్ కనబడలేదు.
ssl-error-no-compression-overlap = పీర్‌తో సురక్షితంగా సంప్రదించలేదు: ఏ వుమ్మడి కంప్రెషన్ అల్గార్దెమ్(లు) లేవు.
ssl-error-handshake-not-completed = ప్రస్తుత హాండ్‌షేక్ పూర్తగునంతవరకు వేరే SSL హాండ్‌షేక్‌ను సిద్దంచేయలేదు.
ssl-error-record-overflow-alert = అనుమతించిన దానికన్నా పొడవైన SSL రికార్డు‌ను పీర్ పొందింది.
ssl-error-decode-error-alert = పీర్ SSL హాండ్‌షేక్ సందేశంను డీకోడ్ చేయలేకపోయింది.
ssl-error-decrypt-error-alert = పీర్ సంతకం నిర్ధారణ వైఫల్యాన్ని లేదా కీ ఎక్సేంజ్‌ను నివేదిస్తోంది.
ssl-error-protocol-version-alert = పీర్ సారూప్యంకాని లేదా మద్దతీయని ప్రొటోకాల్ వర్షన్‌ను నివేదిస్తోంది.
ssl-error-internal-error-alert = అంతర్గతదోషము వుందని పీర్ నివేదిస్తోంది.
ssl-error-user-canceled-alert = పీర్ వాడుకరి హాండ్‌షేక్‌ను రద్దుచేసినది.
ssl-error-no-renegotiation-alert = పీర్ SSL రక్షణ పారామితుల సంధీకరణను అనుమతించుటలేదు.
ssl-error-unsupported-extension-alert = SSL పీర్ అభ్యర్దించిన TLS హెల్లో పొడిగింపును మద్దతించదు.
sec-error-library-failure = రక్షణ లైబ్రరీ వైఫల్యం.
sec-error-bad-data = రక్షణ లైబ్రరీ: చెడ్డ డాటాను పొందింది.
sec-error-output-len = రక్షణ లైబ్రరీ: అవుట్‌పుట్ పొడవు దోషము.
sec-error-input-len = రక్షణ లైబ్రరీ ఒక ఇన్‌పుట్ పొడవు దోషమును చూసింది.
sec-error-invalid-args = రక్షణ లైబ్రరీ: సరికాని ఆర్గుమెంట్సు‌.
sec-error-invalid-ava = రక్షణ లైబ్రరీ: సరికాని AVA.
sec-error-invalid-time = అసంబద్దంగా ఫార్మాట్‌చేసిన టైమ్ స్ట్రింగ్.
sec-error-bad-der = రక్షణ లైబ్రరీ: అసంబద్దంగా ఫార్మాట్‌చేసిన DER-ఎన్‌కోడెడ్ సందేశం.
sec-error-no-memory = రక్షణ లైబ్రరీ: మెమొరీ కేటాయింపు విఫలమైంది.
sec-error-crl-invalid = కొత్త CRL చెల్లని ఫార్మాట్ కలిగివుంది.
sec-internal-only = **మాడ్యూల్ అతర్గతం మాత్రమే**
sec-error-pkcs7-bad-signature = సంతకం నిర్ధారణ విఫలమైంది:ఎటువంచి సైనర్ కనబడలేదు, ఎక్కువమంది సైనర్సు ‌ కనబడినారు, లేదా సరికాని లేదా పాడైన డాటా కనబడింది.
sec-error-unsupported-keyalg = మద్దతీయని లేదా తెలియని కీఅల్గార్దెమ్.
xp-sec-fortezza-no-card = ఎటువంచి ఫార్టెజ్జా కార్డ్సుకనబడలేదు.
xp-sec-fortezza-none-selected = ఎటువంటి ఫార్టెజ్జా కార్డ్సుఎంపికకాలేదు.
xp-sec-fortezza-more-info = ఎక్కువ సమాచారం పొందుటకు దయచేసి ఆపర్సనాలిటిని ఎంపికచేసుకోండి
xp-sec-fortezza-person-not-found = పర్సనాలికి కనబడలేదు
xp-sec-fortezza-no-more-info = ఆపర్సనాలిటిపై ఎటువంటి సమాచారంలేదు
xp-sec-fortezza-bad-pin = చెల్లని పిన్
xp-sec-fortezza-person-error = ఫార్టెజ్జా పర్సనాలిటీలను సిద్దంచేయలేదు.
sec-error-krl-expired = ఈ సైటుయొక్క ధృవీకరణపత్రంకు KRL కాలముతీరినది.
sec-error-krl-bad-signature = ఈ సైటుయొక్క ధృవీకరణపత్రంకు KRL చెల్లని సంతకంకలిగివుంది.
sec-error-need-random = రక్షణ లైబ్రరీ: రాండమ్ డాటా అవసరం.
sec-error-no-module = రక్షణ లైబ్రరీ: అభ్యర్దించిన ఆపరేషన్‌ను ఏరక్షణ మాడ్యూల్ జరుపలేదు.
sec-error-read-only = రక్షణ లైబ్రరీ: డాటాబేస్ చదువుటకు-మాత్రమే.
sec-error-no-slot-selected = ఎటువంటి స్లాట్ లేదా టోకెన్ ఎంపికకాలేదు.
sec-error-key-nickname-collision = ఒక కీ ఇప్పటికే అదేనిక్‌నేమ్‌తోవుంది.
sec-error-baggage-not-created = బాగేజ్ ఆబ్జెక్ట్ ను సృష్టిస్తుంటే దోషము
xp-java-remove-principal-error = ఈసూత్రంను తీసివేయలేదు
xp-java-delete-privilege-error = ప్రివిలైజ్‌ను తొలగించలేదు
sec-error-bad-export-algorithm = అవసరమైన అల్గార్దెమ్ అనుమతించబడదు.
sec-error-exporting-certificates = ధృవీకరణపత్రాలను ఎగుమతిచేయుటలో దోషము.
sec-error-importing-certificates = ధృవీకరణపత్రాలను దిగుమతిచేయుటలో దోషము.
sec-error-user-cancelled = వాడుకరి రద్దుచేయి నొక్కినాడు.
sec-error-message-send-aborted = సందేశం పంపబడింది
sec-error-cert-addr-mismatch = సైనింగ్ ధృవీకరణపత్రంనందలి చిరునామా సందేశం పీఠికల(హెడర్సు)నందలి చిరునామాతో సరిపోలడంలేదు.
sec-error-js-add-mod-failure = మాడ్యూల్‌ను జతచేయలేదు
sec-error-js-del-mod-failure = మాడ్యూల్‌ను తొలగించలేదు
sec-error-old-krl = కొత్త KRL ప్రస్తుతందానికన్నా తరువాతది కాదు.
sec-error-ocsp-server-error = OCSP సేవిక అంతర్గత దోషమును చవిచూసింది.
sec-error-ocsp-try-server-later = OCSP తరువాత ప్రయత్నించమని సూచిస్తోంది.
sec-error-ocsp-request-needs-sig = OCSP సేవిక ఈఅభ్యర్దనపై ఒక సంతకం అవసరం.
sec-error-ocsp-unauthorized-request = OCSP సేవిక ఈఅభ్యర్ధనను అనధికారికమైనదిగా తిరస్కరించింది.
sec-error-ocsp-unknown-response-status = OCSP సేవిక గుర్తించలేని స్థితిని తిప్పియిచ్చింది.
sec-error-ocsp-unknown-cert = OCSP సేవిక ధృవీకరణపత్రంకు ఎటువంచి స్థితిని కలిగిలేదు.
sec-error-ocsp-not-enabled = ఈ ఆపరేషన్ జరుపుటకు ముందుగా మీరు OCSPను చెతనంచేయాలి.
sec-error-ocsp-malformed-response = OCSP సేవకనుండి వచ్చిన స్పందన పాడైనది లేదా అసంబద్దంగా రూపొందింది.
sec-error-ocsp-unauthorized-response = OCSP స్పందన యొక్క సైనర్ ఈధృవీకరణపత్రంకు స్థితిని ఇచ్చుటకు అధికారికంలేదు.
sec-error-digest-not-found = CMS లేదా PKCS #7 డైజెస్టు ‌ సైన్‌డ్ సందేశంనందు కనబడలేదు.
sec-error-unsupported-message-type = CMS లేదా PKCS #7 సందేశం రకము మద్దతీయనిది.
sec-error-bad-template = ASN.1 డాటాను డీకోడ్‌చేయలేము. తెలుపబడిన టెంప్లేట్ చెల్లనిది.
sec-error-unsupported-elliptic-curve = మద్దతీయని దీర్ఘవృత్తం వంపు.
sec-error-unsupported-ec-point-form = మద్దతీయని దీర్ఘవృత్తం వంపు బిందువు రూపము.
sec-error-unrecognized-oid = గుర్తించబడని ఆబ్జక్టు ‌ ఐడెంటిఫైర్.
sec-error-unknown-object-type = ఇచ్చిన ఆబ్జక్టు ‌ రకము తెలియనిది.
sec-error-no-event = ప్రస్తుతం ఎటువంటి కొత్త స్లాట్ ఘటన అందుబాటులోలేదు.
sec-error-not-initialized = NSS ఇంకా సిద్దీకరించలేదు.
sec-error-ocsp-bad-signature = OCSP ప్రతిస్పందన చెల్లని సంతకం కలిగివుంది.
sec-error-invalid-policy-mapping = పాలసీ మాపింగ్ అనునది యే పాలసీనైనా కలిగివుండును
sec-error-policy-validation-failed = Cert చైన్ పాలసీ నిర్థారణను విఫలంచేయును.
sec-error-unknown-aia-location-type = cert AIA పొడిగింపునందు స్థాన రకం తెలియనిది.
sec-error-expired-password = సంకేతపదం కాలంచెల్లెను.
sec-error-locked-password = సంకేతపదం లాకైంది.
sec-error-unknown-pkcs11-error = తెలియని PKCS #11 దోషం.
