#filter emptyLines

#define MOZ_LANGPACK_CREATOR ChatZilla გუნდი

#define MOZ_LANGPACK_HOMEPAGE http://chatzilla.hacksrus.com/

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>გია შერვაშიძე</em:contributor> <em:contributor>Alan (G12r)</em:contributor>

#unfilter emptyLines
