# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

appmenu-update-available2 =
    .label = Dostupna je nova verzija
    .buttonlabel = Preuzmi
    .buttonaccesskey = P
    .secondarybuttonlabel = Odbaci
    .secondarybuttonaccesskey = O
appmenu-update-available-message2 = Preuzmi najnoviju verziju { -brand-shorter-name(case: "gen") }.
appmenu-update-manual2 =
    .label = Dostupna je nova verzija
    .buttonlabel = Preuzmi
    .buttonaccesskey = P
    .secondarybuttonlabel = Odbaci
    .secondarybuttonaccesskey = O
appmenu-update-manual-message2 = { -brand-shorter-name } se nije mogao automatski aktualizirati. Preuzmi novu verziju – nećeš izgubiti spremljene podatke niti prilagodbe.
appmenu-update-unsupported2 =
    .label = Neuspjelo aktualiziranje
    .buttonlabel = Saznaj više
    .buttonaccesskey = S
    .secondarybuttonlabel = Odbaci
    .secondarybuttonaccesskey = O
appmenu-update-unsupported-message2 = Tvoj operacijski sustav nije kompatibilan s najnovijom { -brand-shorter-name } verzijom.
appmenu-update-restart2 =
    .label = Dostupna je nova verzija
    .buttonlabel = Preuzmi i ponovo pokreni
    .buttonaccesskey = P
    .secondarybuttonlabel = Odbaci
    .secondarybuttonaccesskey = d
appmenu-update-restart-message2 = Nabavi najnoviju { -brand-shorter-name } verziju. Otvorene kartice i prozori će se obnoviti.
appmenu-update-other-instance =
    .label = { -brand-shorter-name } se ne može automatski aktualizirati na najnoviju verziju.
    .buttonlabel = Svejedno aktualiziraj { -brand-shorter-name }
    .buttonaccesskey = S
    .secondarybuttonlabel = Ne sada
    .secondarybuttonaccesskey = N
appmenu-update-other-instance-message = Novo aktualiziranje za { -brand-shorter-name } je dostupno, ali ne može se instalirati jer je pokrenuta druga instanca { -brand-shorter-name(case: "gen") }. Potrebno ju je zatvoriti za nastavak aktualizacije ili ipak nastaviti aktualizaciju bez zatvaranja (druga instanca možda neće raditi ispravno dok nije ponovno pokrenuta).
appmenu-addon-private-browsing-installed2 =
    .buttonlabel = U redu
    .buttonaccesskey = U
appmenu-addon-post-install-message3 = Upravljaj svojim dodacima i temama iz izbornika aplikacije.
appmenu-addon-post-install-incognito-checkbox =
    .label = Dozvoli ovom dodatku da radi u privatnom prozoru
    .accesskey = a
appmenu-new-tab-controlled-changes =
    .label = Tvoja nova kartica je promijenjena.
    .buttonlabel = Zadrži promjene
    .buttonaccesskey = Z
    .secondarybuttonlabel = Upravljaj novim karticama
    .secondarybuttonaccesskey = U
appmenu-homepage-controlled-changes =
    .label = Tvoja početna stranica je promijenjena.
    .buttonlabel = Zadrži promjene
    .buttonaccesskey = Z
    .secondarybuttonlabel = Upravljaj početnom stranicom
    .secondarybuttonaccesskey = U
appmenu-tab-hide-controlled =
    .label = Pristupite svojim skrivenim karticama
    .buttonlabel = Drži kartice skrivenim
    .buttonaccesskey = k
    .secondarybuttonlabel = Onemogući dodatak
    .secondarybuttonaccesskey = d
