# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# This is a multi-line message.
psmerr-hostreusedissuerandserial =
    អ្នក​បាន​ទទួល​វិញ្ញាបនបត្រ​មិន​ត្រឹមត្រូវ ។ សូម​ទាក់ទង​អ្នក​គ្រប់គ្រង​ម៉ាស៊ីន​បម្រើ ឬ​អ៊ីមែល​ដោយ​ផ្ញើ​នូវ​ព័ត៌មាន​ដូច​ខាងក្រោម​ដល់​ពួកគេ ៖
    
     វិញ្ញាបនបត្រ​របស់​អ្នក​មាន​លេខ​សម្គាល់​ដូច​គ្នា​នឹង​វិញ្ញាបនបត្រ​មួយ​ផ្សេងទៀត​ដែល​បាន​ចេញ​ដោយ​ប្រភព​វិញ្ញាបនបត្រ ។ សូម​ទទួល​យក​វិញ្ញាបនបត្រ​ថ្មី​ដែល​មាន​នូវ​លេខ​សម្គាល់​តែមួយ ។
ssl-error-no-cypher-overlap = មិន​អាច​ទាក់ទង​ជាមួយ​ម៉ាស៊ីន​ដូច​គ្នា​ដោយ​សុវត្ថិភាព​បាន​ទេ ៖ គ្មាន​ក្បួន​ដោះស្រាយ​ការ​អ៊ិនគ្រីប​ទូទៅ​ឡើយ ។
ssl-error-no-certificate = មិន​អាច​រក​​​​វិញ្ញាបនបត្រ​ ឬ​​សោ​​ចាំបាច់​សម្រាប់​​ផ្ទៀងផ្ទាត់​ភាព​ត្រឹមត្រូវ​ឡើយ ។
ssl-error-bad-client = ម៉ាស៊ីន​បម្រើ​បាន​ជួប​​ប្រទះ​ទិន្នន័យ​មិន​ត្រឹមត្រូវ​ពី​ម៉ាស៊ីន​ភ្ញៀវ ។
ssl-error-bad-server = ម៉ាស៊ីន​ភ្ញៀវ​បាន​ជួប​ប្រទះ​ទិន្នន័យ​​ខូច​ពី​ម៉ាស៊ីន​បម្រើ ។
ssl-error-unsupported-certificate-type = ប្រភេទ​វិញ្ញាបនបត្រ​ដែល​មិន​គាំ​ទ្រ ។
ssl-error-unsupported-version = ម៉ាស៊ីន​ដូចគ្នា​ដែល​ប្រើ​កំណែ​​ពិធីការ​សុវត្ថិភាព​ដែល​មិន​បាន​គាំទ្រ ។
ssl-error-wrong-certificate = បាន​បរាជ័យ​ក្នុង​ការ​ផ្ទៀងផ្ទាត់​ភាព​ត្រឹមត្រូវ​របស់​ម៉ាស៊ីន​ភ្ញៀវ ៖ កូនសោ​ឯកជន​​នៅ​ក្នុង​មូលដ្ឋាន​ទិន្នន័យ​របស់​កូន​សោ​ដែល​មិន​ផ្គូផ្គង​កូនសោ​សាធារណៈ​នៅ​ក្នុង​មូលដ្ឋាន​ទិន្នន័យ​របស់​វិញ្ញាបនបត្រ ។
ssl-error-ssl2-disabled = ម៉ាស៊ីន​ដូចគ្នា​តែប៉ុណ្ណោះ​គាំទ្រ​កំណែ SSL ២ ដែល​ត្រូវ​បាន​បិទ​ជា​មូលដ្ឋាន ។
ssl-error-bad-mac-read = SSL បាន​ទទួល​កំណត់ត្រា​​ដោយ​មាន​កូដ​ក្នុង​ការ​ផ្ទៀងផ្ទាត់​ភាព​ត្រឹមត្រូវ​នៃ​សារ​មិន​ត្រឹមត្រូវ ។
ssl-error-bad-mac-alert = ម៉ាស៊ីន​ដូចគ្នា​របស់ SSL រាយការណ៍​កូដ​ក្នុង​ការ​ផ្ទៀងផ្ទាត់​ភាព​ត្រឹមត្រូវ​នៃ​សារ​មិន​ត្រឹមត្រូវ ។
ssl-error-bad-cert-alert = ម៉ាស៊ីន​ដូចគ្នា​របស់ SSL មិន​អាច​ផ្ទៀងផ្ទាត់​វិញ្ញាបនបត្រ​របស់​អ្នក​បាន​ទេ ។
ssl-error-revoked-cert-alert = ម៉ាស៊ីន​ដូច​គ្នា​របស់ SSL បាន​ច្រានចោល​​វិញ្ញាបនបត្រ​របស់​អ្នក​​នៅ​ពេល​​បាន​ដកហូត​វិញ ។
ssl-error-expired-cert-alert = ម៉ាស៊ីន​បម្រើ​របស់ SSL បាន​ច្រានចោល​វិញ្ញាបនបត្រ​របស់​អ្នក​​ពីព្រោះ​​ផុត​កំណត់ ។
ssl-error-ssl-disabled = មិន​អាច​តភ្ជាប់​ ៖ SSL ត្រូវ​បាន​បិទ ។
ssl-error-fortezza-pqg = មិន​អាច​តភ្ជាប់ ៖ ម៉ាស៊ីន​ដូចគ្នា​របស់ SSL គឺ​នៅ​ក្នុង​ដែន​របស់ FORTEZZA ផ្សេង​ទៀត ។
ssl-error-unknown-cipher-suite = ឈុត​​សរសេរ​សម្ងាត់​របស់ SSL ដែល​មិន​ស្គាល់​ត្រូវ​បាន​ស្នើ ។
ssl-error-no-ciphers-supported = គ្មាន​ឈុត​សរសេរ​សម្ងាត់​ត្រូវ​បាន​បង្ហាញ និង​បើក​នៅ​ក្នុង​កម្មវិធី​នេះ​ទេ ។
ssl-error-bad-block-padding = SSL បាន​ទទួល​កំណត់ត្រា​ដោយ​មាន​ចន្លោះ​ប្លុក​​ខូច ។
ssl-error-rx-record-too-long = SSL បាន​ទទួល​កំណត់ត្រា​ដែល​លើស​​ប្រវែង​ដែល​អនុញ្ញាត​ឲ្យ​​អតិបរមា ។
ssl-error-tx-record-too-long = SSL បាន​ប៉ុនប៉ង​​ក្នុង​ការ​ផ្ញើ​កំណត់ត្រា​ដែល​​​លើ​ប្រវែង​ដែល​អនុញ្ញាត​ឲ្យ​អតិបរមា ។
ssl-error-rx-malformed-hello-request = SSL បាន​ទទួល​សារ​ស្នើ​សូម​បាន​ទទួល​ដែល​មិន​ត្រឹមត្រូវ ។
ssl-error-rx-malformed-client-hello = SSL បាន​ទទួល​​សារ​​ម៉ាស៊ីន​ភ្ញៀវ​បាន​ទទួល​មិន​​ត្រឹមត្រូវ ។
ssl-error-rx-malformed-server-hello = SSL បាន​ទទួល​​សារ​ម៉ាស៊ីន​បម្រើ​បាន​ទទួល​មិន​ត្រឹមត្រូវ ។
ssl-error-rx-malformed-certificate = SSL បាន​ទទួល​សារ​វិញ្ញាបនបត្រ​បាន​ទទួល​មិន​ត្រឹមត្រូវ ។
ssl-error-rx-malformed-server-key-exch = SSL បាន​ទទួល​សារ Server Key Exchange handshake ដែល​មាន​ទ្រង់ទ្រាយ​មិន​ត្រឹមត្រូវ ។
ssl-error-rx-malformed-cert-request = SSL បាន​ទទួល​សារ​ស្នើ​​វិញ្ញាបនបត្រ​បាន​ទទួល​មិន​ត្រឹមត្រូវ ។
ssl-error-rx-malformed-hello-done = SSL បាន​ទទួល​សារ​​ម៉ាស៊ីន​បម្រើ​​រួច​រាល់​បាន​ទទួល​​​មិន​ត្រឹមត្រូវ ។
ssl-error-rx-malformed-cert-verify = SSL បាន​ទទួល​សារ​វិញ្ញាបនបត្រ​ផ្ទៀងផ្ទាត់​បាន​ទទួល​មិន​ត្រឹមត្រូវ ។
ssl-error-rx-malformed-client-key-exch = SSL បាន​ទទួល​សារ Client Key Exchange handshake ដែល​មាន​ទ្រង់ទ្រាយ​មិន​ត្រឹមត្រូវ ។
ssl-error-rx-malformed-finished = SSL បាន​ទទួល​សារ​បញ្ចប់​បាន​ទទួល​មិន​ត្រឹមត្រូវ ។
ssl-error-rx-malformed-change-cipher = SSL បាន​ទទួល​កំណត់ត្រា Change Cipher Spec ដែល​មាន​ទ្រង់ទ្រាយ​មិន​ត្រឹមត្រូវ ។
ssl-error-rx-malformed-alert = SSL បាន​ទទួល​កំណត់ត្រា​​អំពី​សញ្ញា​ព្រមាន​មិន​ត្រឹមត្រូវ ។
ssl-error-rx-malformed-handshake = SSL បាន​ទទួល​កំណត់ត្រា​បាន​ទ​ទួល​មិន​ត្រឹមត្រូវ ។
ssl-error-rx-malformed-application-data = SSL បាន​ទទួល​កំណត់ត្រា​ទិន្នន័យ​កម្មវិធី​មិន​ត្រឹមត្រូវ ។
ssl-error-rx-unexpected-hello-request = SSL បាន​ទទួល​សារ​ដែល​មិន​រំពឹង​​ស្នើ​បាន​ទទួល​មិន​ត្រឹមត្រូវ ។
ssl-error-rx-unexpected-client-hello = SSL បាន​ទទួល​សារ Client Hello handshake ដែល​មិន​បាន​រំពឹង ។
ssl-error-rx-unexpected-server-hello = SSL បាន​ទទួល​សារ​ម៉ាស៊ីន​បម្រើ​ដែល​មិន​រំពឹង​​បាន​ទទួល ។
ssl-error-rx-unexpected-certificate = SSL បាន​ទទួល​សារ​វិញ្ញាបនបត្រ​ដែល​មិន​រំពឹង​បាន​ទទួល ។
ssl-error-rx-unexpected-server-key-exch = SSL បាន​ទទួល​សារ Server Key Exchange handshake ដែល​មិន​បាន​រំពឹង ។
ssl-error-rx-unexpected-cert-request = SSL បាន​ទទួល​សារ​សំណើ​វិញ្ញាបនបត្រ​ដែល​មិន​រំពឹង​បាន​ទទួល​ ។
ssl-error-rx-unexpected-hello-done = SSL បាន​ទទួល​សារ​ម៉ាស៊ីន​បម្រើ​រួចរាល់​ដែល​មិន​រំពឹង ។
ssl-error-rx-unexpected-cert-verify = SSL បាន​ទទួល​សារ​​ក្នុង​ការ​ផ្ទៀងផ្ទាត់​វិញ្ញាបនបត្រ​​​ដែល​មិន​រំពឹង ។
ssl-error-rx-unexpected-client-key-exch = SSL បាន​ទទួល​សារ Client Key Exchange handshake ដែល​មិន​បាន​រំពឹង ។
ssl-error-rx-unexpected-finished = SSL បាន​ទទួល​សារ​បាន​បញ្ចប់​ដែល​មិន​រំពឹង​​បាន​ទទួល ។
ssl-error-rx-unexpected-change-cipher = SSL បាន​ទទួល​កំណត់ត្រា Change Cipher Spec ដែល​មិន​បាន​រំពឹង ។
ssl-error-rx-unexpected-alert = SSL បាន​ទទួល​កំណត់​ត្រា​អំពី​សញ្ញា​ព្រមាន​ដែល​មិន​រំពឹង ។
ssl-error-rx-unexpected-handshake = SSL បាន​ទទួល​កំណត់​ត្រា​ដែល​មិន​រំពឹង​បាន​ទទួល ។
ssl-error-rx-unexpected-application-data = SSL បាន​ទទួល​កំណត់ត្រា​ទិន្នន័យ​កម្មវិធី​ដែល​មិន​រំពឹង ។
ssl-error-rx-unknown-record-type = SSL បាន​ទួល​​កំណត់ត្រា​ដោយ​មាន​ប្រភេទ​មាតិកា​ដែល​មិន​ស្គាល់ ។
ssl-error-rx-unknown-handshake = SSL បាន​ទទួល​​សារ​បាន​ទួល​ដោយ​មាន​ប្រភេទ​សារ​ដែល​មិន​ស្គាល់ ។
ssl-error-rx-unknown-alert = SSL បាន​ទទួល​កំណត់ត្រា​អំពី​សញ្ញា​ព្រមាន​ដោយ​មាន​​សេចក្ដី​ពិពណ៌នា​អំពី​សញ្ញា​ព្រមាន​​ដែល​មិន​ស្គាល់ ។
ssl-error-close-notify-alert = ម៉ាស៊ីន​ដូច​គ្នា​របស់ SSL បាន​បិទ​ការ​តភ្ជាប់​នេះ ។
ssl-error-handshake-unexpected-alert = ម៉ាស៊ីន​ដូចគ្នា​របស់ SSL ដែល​​មិន​រំពឹង​​សារ​​បាន​ទទួល​ដែល​វា​បាន​ទទួល ។
ssl-error-decompression-failure-alert = ម៉ាស៊ីន​ដូច​គ្នា​របស់ SSL មិន​អាច​​ពន្លា​ដោយ​ជោគជ័យ​កំណត់ត្រា​របស់ SSL ​ដែល​វា​បាន​ទទួល​ឡើយ ។
ssl-error-handshake-failure-alert = ម៉ាស៊ីន​ដូចគ្នា SSL មិន​អាច​ធ្វើការ​ចរចារ​ព្រមព្រៀង​ពី​បណ្ដុំ​ប៉ារ៉ាម៉ែត្រ​សុវត្ថិភាព​ដែល​អាច​ទទួល​យក​បាន ។
ssl-error-illegal-parameter-alert = ម៉ាស៊ីន​ដូច​គ្នា​របស់ SSL បាន​ច្រានចោល​សារ​បាន​ទទួល​​សម្រាប់​មាតិកា​ដែល​មិន​អាច​ទទួល​យក​បាន ។
ssl-error-unsupported-cert-alert = ម៉ាស៊ីន​ដូច​គ្នា​របស់ SSL មិន​បាន​គាំទ្រ​ប្រភេទ​វិញ្ញាបនបត្រ​ដែល​វា​បាន​ទទួល​ឡើយ ។
ssl-error-certificate-unknown-alert = ម៉ាស៊ីន​ដូច​គ្នា​របស់ SSL មាន​បញ្ហា​ដែល​មិន​រំពឹង​មួយ​ចំនួន​ដោយ​មាន​វិញ្ញាបនបត្រ​ដែល​វា​បាន​ទទួល ។
ssl-error-generate-random-failure = SSL បាន​ជួប​បរាជ័យ​ក្នុង​ការ​បង្កើត​លេខ​ចៃដន្យ​របស់​វា ។
ssl-error-sign-hashes-failure = មិន​អាច​​ចុះ​ហត្ថលេខា​ទិន្នន័យ​ដោយ​ឌីជីថល ដើម្បី​ផ្ទៀងផ្ទាត់​វិញ្ញាបនបត្រ​របស់​អ្នក​បាន​ឡើយ ។
ssl-error-server-key-exchange-failure = ភាព​បរាជ័យ​ដែល​មិន​បាន​បញ្ជាក់​ខណៈ​ពេល​កំពុង​ដំណើរការ​ការ​ផ្លាស់ប្ដូរ​ម៉ាស៊ីន​បម្រើ​របស់ SSL ។
ssl-error-client-key-exchange-failure = ភាព​បរាជ័យ​ដែល​មិន​បាន​បញ្ជាក់​ខណៈ​ពេល​កំពុង​ដំណើរការ​ការ​ផ្លាស់ប្ដូរ​កូនសោ​ម៉ាស៊ីន​ភ្ញៀវ​របស់ SSL ។
ssl-error-encryption-failure = បាន​បរាជ័យ​ក្បួន​ដោះស្រាយ​ការ​អ៊ិនគ្រីប​ទិន្នន័យ​​អំពី​ទំហំ​​ក្នុង​ឈុត​សរសេរ​សម្ងាត់​ដែល​បាន​ជ្រើស ។
ssl-error-decryption-failure = បាន​បរាជ័យ​ក្បួន​ដោះស្រាយ​​ការ​ឌិគ្រីប​ទិន្នន័យ​អំពី​ទំហំ​ក្នុង​ឈុត​សរសេរ​សម្ងាត់​ដែល​បាន​ជ្រើស ។
ssl-error-socket-write-failure = ប៉ុនប៉ង​ក្នុង​ការ​សរសេរ​ទិន្នន័យ​ដែល​បាន​អ៊ិនគ្រីប​រន្ធ​ដែល​ជា​មូលដ្ឋាន​បាន​បរាជ័យ ។
ssl-error-md5-digest-failure = បាន​បរាជ័យ​មុខងារ​កម្រង​​អត្ថបទ​សង្ខេប​របស់ ​MD5 ។
ssl-error-sha-digest-failure = បាន​បរាជ័យ​មុខងារ​កម្រង​អត្ថបទ​សង្ខេប​របស់ SHA-1 ។
ssl-error-mac-computation-failure = បាន​បរាជ័យ​ក្នុង​ការ​គណនា MAC ។
ssl-error-sym-key-context-failure = ​បរាជ័យ​ក្នុង​ការ​បង្កើត​បរិបទ​អំពី​កូនសោ​ស៊ីមេទ្រី ។
ssl-error-sym-key-unwrap-failure = បរាជ័យ​​ក្នុង​ការ​ពន្លា​កូនសោ​ស៊ីមេទ្រី​​ក្នុង​សារ​ផ្លាស់ប្ដូរ​កូនសោ​ម៉ាស៊ីន​ភ្ញៀវ ។
ssl-error-pub-key-size-limit-exceeded = ម៉ាស៊ីន​បម្រើ​របស់ SSL បាន​ប៉ុនប៉ង​​​ក្នុង​ការ​ប្រើ​កូនសោ​សាធារណៈ​​​ថ្នាក់​​ក្នុង​តំបន់​ដោយ​មាន​ឈុត​សរសេរ​សម្ងាត់​នាំចេញ ។
ssl-error-iv-param-failure = កូដ PKCS11 បាន​បរាជ័យ​ក្នុង​ការ​បកប្រែ IV ទៅជា​ប៉ារ៉ាម៉ែត្រ ។
ssl-error-init-cipher-suite-failure = បាន​បរាជ័យ​ក្នុង​ការ​​រៀបចំ​ឈុត​សរសេរ​សម្ងាត់​ដែល​បាន​ជ្រើស ។
ssl-error-session-key-gen-failure = ម៉ាស៊ីន​ភ្ញៀវ​បាន​បរាជ័យ​ក្នុង​ការ​បង្កើត​កូនសោ​សម័យ​សម្រាប់​សម័យ​របស់ SSL ។
ssl-error-no-server-key-for-alg = ម៉ាស៊ីន​បម្រើ​គ្មាន​កូនសោ​សម្រាប់​ក្បួន​​ដោះស្រាយ​​ការ​ផ្លាស់ប្ដូរ​កូនសោ​ដែល​បាន​ប៉ុនប៉ង​ឡើយ ។
ssl-error-token-insertion-removal = PKCS#11 token ត្រូវ​បាន​បញ្ចូល ឬ​យក​ចេញ​ ខណៈ​ពេល​ប្រតិបត្តិការ​កំពុង​ដំណើរការ ។
ssl-error-token-slot-not-found = No PKCS#11 token អាច​ត្រូវ​បាន​រក​ឃើញ​​ក្នុង​ការ​ប្រតិបត្តិការ​ដែល​បាន​ស្នើ ។
ssl-error-no-compression-overlap = មិន​អាច​​​ទំនាក់ទំនង​ជា​មួយ​ម៉ាស៊ីន​ដូចគ្នា​ដោយ​សុវត្ថិភាព​ឡើយ ៖ គ្មាន​ក្បួន​ដោះស្រាយ​​អំពី​ការ​បង្ហាប់​ទូទៅ​ឡើយ ។
ssl-error-handshake-not-completed = មិន​អាច​ផ្ដើម​ SSL ផ្សេង​ទៀត​បាន​ទេ​​រហូត​ដល់​បាន​ទទួល​បច្ចុប្បន្ន​​បាន​បញ្ចប់ ។
ssl-error-bad-handshake-hash-value = បាន​ទទួល​តម្លៃ​សញ្ញា​បាន​ទទួល​មិន​ត្រឹមត្រូវ​ពី​ម៉ាស៊ីន​ដូចគ្នា ។
ssl-error-cert-kea-mismatch = មិន​អាច​ប្រើ​វិញ្ញាបនបត្រ​ដែល​បាន​ផ្ដល់​ជាមួយ​ក្បួន​ដោះស្រាយ​​ការ​ផ្លាស់ប្ដូរ​កូនសោ​ដែល​បាន​ជ្រើស​ឡើយ ។
ssl-error-no-trusted-ssl-client-ca = គ្មាន​ប្រភព​វិញ្ញាបនបត្រ​ដែល​គួរ​ឲ្យ​ទុកចិត្ត​បាន​សម្រាប់​ការ​ផ្ទៀងផ្ទាត់​ភាព​ត្រឹមត្រូវ​ម៉ាស៊ីន​ភ្ញៀវ SSL ។
ssl-error-decryption-failed-alert = ម៉ាស៊ីន​ដូចគ្នា​មិន​អាច​​​ឌិគ្រីប​​កំណត់ត្រា​របស់ SSL ​ដែល​វា​បាន​ទទួល​ឡើយ ។
ssl-error-record-overflow-alert = ម៉ាស៊ីន​ដូចគ្នា​បាន​ទទួល​កំណត់ត្រា​របស់ SSL ដែល​​ត្រូវ​បាន​អនុញ្ញាត​ឲ្យ​​វែង​ជាង ។
ssl-error-unknown-ca-alert = ម៉ាស៊ីន​ដូចគ្នា មិន​ស្គាល់ និង​ទុកចិត្ត​លើ​ប្រភព​វិញ្ញាបនបត្រ​ដែល​ចេញផ្សាយ​ដោយ​វិញ្ញាបនបត្រ​របស់​អ្នក​ទេ ។
ssl-error-access-denied-alert = ម៉ាស៊ីន​ដូច​គ្នា​បាន​ទទួល​វិញ្ញាបនបត្រ​មិន​ត្រឹមត្រូវ ប៉ុន្តែ​​​ចូល​ដំណើរការ​ត្រូវ​បាន​បដិសេធ ។
ssl-error-decode-error-alert = ម៉ាស៊ីន​ដូចគ្នា​មិន​អាច​ឌិកូដ​សារ​បាន​ទទួល​របស់ SSL បាន​ទេ ។
ssl-error-decrypt-error-alert = បរាជ័យ​ក្នុង​ការ​ផ្ទៀងផ្ទាត់​ហត្ថលេខា​របាយការណ៍​ម៉ាស៊ីន​ដូចគ្នា ឬ​​ការ​ផ្លាស់ប្ដូរ​កូនសោ ។
ssl-error-export-restriction-alert = ម៉ាស៊ីន​ដូចគ្នា រាយការណ៍​ថា​ការ​ចរចារ​មិន​អនុលោម​តាម​បទបញ្ជា​នាំចេញ ។
ssl-error-protocol-version-alert = របាយការណ៍​ម៉ាស៊ីន​ដូច​គ្នា​ដែល​មិន​ឆប​គ្នា ឬ​​កំណែ​ពិធីការ​ដែល​មិន​បាន​គាំទ្រ ។
ssl-error-insufficient-security-alert = ម៉ាស៊ីន​បម្រើ​ទាមទារ​សរសេរ​សម្ងាត់​​ដែល​​មាន​សុវត្ថិភាព​ជាង​​ដែល​បាន​គាំទ្រ​ម៉ាស៊ីន​ភ្ញៀវ ។
ssl-error-internal-error-alert = របាយការណ៍​​អំពី​ម៉ាស៊ីន​ដូចគ្នា​ដែល​វា​បាន​ទទួល​បទពិសោធន៍​​​ពី​កំហុស​ខាងក្រៅ ។
ssl-error-user-canceled-alert = អ្នក​ប្រើ​ម៉ាស៊ីន​ដូចគ្នា​បាន​បោះបង់​បាន​ទទួល ។
ssl-error-no-renegotiation-alert = ម៉ាស៊ីន​ដូចគ្នា មិន​អនុញ្ញាត​ការ​ចរចារ​ឡើងវិញ​នៃ​ប៉ារ៉ាម៉ែត្រ​សុវត្ថិភាព​របស់ SSL ឡើយ ។
ssl-error-server-cache-not-configured = ឃ្លាំង​សម្ងាត់​ម៉ាស៊ីន​បម្រើ​របស់ SSL ​មិន​បាន​កំណត់​រចនាសម្ព័ន្ធ និង​មិន​បាន​បិទ​សម្រាប់​រន្ធ​នេះ​ទេ ។
ssl-error-unsupported-extension-alert = ម៉ាស៊ីន​ដូចគ្នា​របស់ SSL ​មិន​គាំទ្រ​ផ្នែក​បន្ថែម TLS ដែល​បាន​ស្នើ​ឡើយ ។
ssl-error-certificate-unobtainable-alert = ម៉ាស៊ីន​ដូចគ្នា​របស់ SSL មិន​មាន​វិញ្ញាបនបត្រ​របស់​អ្នក​​បាន​គាំទ្រ​ពី URL ឡើយ ។
ssl-error-unrecognized-name-alert = ម៉ាស៊ីន​ដូចគ្នា​របស់ SSL គ្មាន​វិញ្ញាបនបត្រ​សម្រាប់​ឈ្មោះ​​របស់ DNS ដែល​បាន​ស្នើ​ឡើយ ។
ssl-error-bad-cert-status-response-alert = ម៉ាស៊ីន​ដូចគ្នា​របស់ SSL មិន​អាច​ទទួល​​យក​ការ​ឆ្លើយតប​របស់ OCSP សម្រាប់​វិញ្ញាបនបត្រ​របស់​វា​បាន​ឡើយ ។
ssl-error-bad-cert-hash-value-alert = ម៉ាស៊ីន​ដូចគ្នា​របស់ SSL បាន​រាយការណ៍​អំពី​តម្លៃ​សញ្ញា​របស់​វិញ្ញាបនបត្រ​​ដែល​មិន​ត្រឹមត្រូវ ។
ssl-error-rx-unexpected-new-session-ticket = SSL បាន​ទទួល​សារ​សំបុត្រ​សម័យ​ថ្មី​ដែល​មិន​បាន​រំពឹង​បាន​ទទួល ។
ssl-error-rx-malformed-new-session-ticket = SSL បាន​ទទួល​សារ​សំបុត្រ​សម័យ​ថ្មី​បាន​ទទួល​មិន​ត្រឹមត្រូវ ។
ssl-error-decompression-failure = SSL បាន​ទទួល​កំណត់ត្រា​ដែល​បាន​បង្ហាប់​​ថា​មិន​អាច​ត្រូវ​បាន​​ពន្លា ។
ssl-error-renegotiation-not-allowed = មិន​អនុញ្ញាត​ឲ្យ​ការ​ចរចា​ជាថ្មី​នៅ​លើ​រន្ធ​របស់ SSL នេះ​ទេ ។
ssl-error-unsafe-negotiation = ម៉ាស៊ីន​ដូចគ្នា​បាន​ប៉ុនប៉ង​រចនាប័ទ្ម​ចាស់​ (មាន​សក្ដានុពល​ដែល​អាច​បាត់បង់) ។
ssl-error-rx-unexpected-uncompressed-record = SSL បាន​ទទួល​កំណត់ត្រា​ដែល​មិន​បាន​បង្ហាប់​ដែល​មិន​បាន​រំពឹង ។
ssl-error-weak-server-ephemeral-dh-key = SSL បាន​ទទួល​កូនសោ​ Diffie-Hellman ដែល​ខ្សោយ​នៅ​ក្នុង​សារ​ការ​ផ្លាស់ប្ដូរ​កូនសោ​​​របស់​ម៉ាស៊ីន​បម្រើ​ ។
ssl-error-next-protocol-data-invalid = SSL បាន​ទទួល​ទិន្នន័យ​ផ្នែក​បន្ថែម NPN ដែល​មិន​ត្រឹមត្រូវ ។
ssl-error-feature-not-supported-for-ssl2 = លក្ខណ​ពិសេស​របស់ SSL មិន​បាន​គាំទ្រ​ការ​តភ្ជាប់ SSL ២.០ ទេ ។
ssl-error-feature-not-supported-for-servers = លក្ខណ​ពិសេស​របស់ SSL មិន​បាន​គាំទ្រ​ម៉ាស៊ីន​បម្រើ​ទេ ។
ssl-error-feature-not-supported-for-clients = លក្ខណ​ពិសេស​របស់ SSL មិន​បាន​គាំទ្រ​ម៉ាស៊ីន​ភ្ញៀវ​ទេ ។
sec-error-io = កំហុស I/O បាន​កើតឡើង​អំឡុង​ពេល​ផ្ទៀងផ្ទាត់​ភាព​ត្រឹមត្រូវ​សុវត្ថិភាព ។
sec-error-library-failure = បរាជ័យ​បណ្ណាល័យ​សុវត្ថិភាព ។
sec-error-bad-data = បណ្ណាល័យ​សុវត្ថិភាព ៖ បាន​ទទួល​ទិន្នន័យ​​ដែល​ខូច ។
sec-error-output-len = បណ្ណាល័យ​សុវត្ថិភាព ៖ កំហុស​ប្រវែង​លទ្ធផល ។
sec-error-input-len = បណ្ណាល័យ​សុវត្ថិភាព​បាន​ទទួល​បទពិសោធន៍​ពី​កំហុស​ប្រវែង​​លទ្ធផល ។
sec-error-invalid-args = បណ្ណាល័យ​សុវត្ថិភាព ៖ អាគុយម៉ង់​មិន​ត្រឹមត្រូវ ។
sec-error-invalid-algorithm = បណ្ណាល័យ​សុវត្ថិភាព ៖ ក្បួន​ដោះស្រាយ​មិន​ត្រឹមត្រូវ ។
sec-error-invalid-ava = បណ្ណាល័យ​សុវត្ថិភាព ៖ AVA មិន​ត្រឹមត្រូវ ។
sec-error-invalid-time = ខ្សែ​អក្សរ​​ពេលវេលា​​ដែល​​បាន​ធ្វើ​ទ្រង់ទ្រាយ​មិន​ត្រឹមត្រូវ ។
sec-error-bad-der = បណ្ណាល័យ​សុវត្ថិភាព ៖ សារ​ DER-បាន​អ៊ិនកូដ​ដែល​បាន​ធ្វើ​ទ្រង់ទ្រាយ​មិន​ត្រឹមត្រូវ ។
sec-error-bad-password = បាន​បញ្ចូល​ពាក្យសម្ងាត់​សុវត្ថិភាព​មិន​ត្រឹមត្រូវ ។
sec-error-no-nodelock = បណ្ណាល័យ​សុវត្ថិភាព ៖ គ្មាន nodelock ។
sec-error-bad-database = បណ្ណាល័យ​សុវត្ថិភាព ៖ មូលដ្ឋាន​ទិន្នន័យ​ខូច ។
sec-error-no-memory = បណ្ណាល័យ​សុវត្ថិភាព ៖ បរាជ័យ​ក្នុង​ការ​បម្រុង​ទុក​អង្គ​ចងចាំ ។
sec-error-duplicate-cert = មាន​វិញ្ញាបនបត្រ​រួចហើយ​នៅ​ក្នុង​មូលដ្ឋាន​ទិន្នន័យ​របស់​អ្នក ។
sec-error-adding-cert = កំហុស​ក្នុង​ការ​បន្ថែម​វិញ្ញាបនបត្រ​ទៅកាន់​មូលដ្ឋាន​ទិន្នន័យ ។
sec-error-filing-key = កំហុស​ក្នុង​ការ​ដាក់​ឯកសារ​សោ​ឡើង​វិញ សម្រាប់​វិញ្ញាបនបត្រ​នេះ ។
sec-error-no-key = សោ​ឯកជន​សម្រាប់​វិញ្ញាបនបត្រ​នេះ​មិន​អាច​ត្រូវ​បាន​រក​ឃើញ​នៅ​ក្នុង​មូលដ្ឋាន​ទិន្នន័យ​សោ​ឡើយ
sec-error-cert-valid = វិញ្ញាបនបត្រ​នេះ​​ត្រឹមត្រូវ​ហើយ ។
sec-error-cert-not-valid = វិញ្ញាបនបត្រ​នេះ​មិន​ត្រឹមត្រូវ​ទេ ។
sec-error-cert-no-response = បណ្ណាល័យ​វិញ្ញាបនបត្រ ៖ គ្មាន​ចម្លើយ​តប
sec-error-crl-invalid = CRL ថ្មី មាន​ទ្រង់ទ្រាយ​មិន​ត្រឹមត្រូវ​ឡើយ ។
sec-error-extension-value-invalid = តម្លៃ​​ផ្នែក​បន្ថែម​របស់​វិញ្ញាបនបត្រ​មិន​ត្រឹមត្រូវ​ទេ ។
sec-error-extension-not-found = រក​មិន​ឃើញ​ផ្នែក​បន្ថែម​របស់​វិញ្ញាបនបត្រ​ឡើយ ។
sec-error-ca-cert-invalid = វិញ្ញាបនបត្រ​របស់​អ្នក​ចេញ​ផ្សាយ​មិន​ត្រឹមត្រូវ​ឡើយ ។
sec-error-path-len-constraint-invalid = កម្រិត​ប្រវែង​ផ្លូវ​របស់​វិញ្ញាបនបត្រ​មិន​ត្រឹមត្រូវ​ទេ ។
sec-error-cert-usages-invalid = វាល​ក្នុង​ការ​ប្រើ​វិញ្ញាបនបត្រ​មិន​ត្រឹមត្រូវ​ទេ ។
sec-internal-only = **តែ​ខាងក្នុង​ម៉ូឌុល​ប៉ុណ្ណោះ**
sec-error-invalid-key = សោ​មិន​គាំទ្រ​ប្រតិបត្តិការ​ដែល​បាន​ស្នើ​ទេ ។
sec-error-unknown-critical-extension = កម្រិត​វិញ្ញាបនបត្រ​ដែល​មិន​ស្គាល់​ផ្នែក​បន្ថែម​សំខាន់​បំផុត ។
sec-error-old-crl = CRL ថ្មី​​​​មិន​តិច​ជាង​មួយ​បច្ចុប្បន្ន​ឡើយ ។
sec-error-no-email-cert = មិន​បាន​អ៊ិនគ្រីប ឬ​ចុះហត្ថលេខា​ឡើយ ៖ អ្នក​​​មិនទាន់​មាន​វិញ្ញាបនបត្រ​អ៊ីមែល​នៅ​ឡើយ​ទេ ។
sec-error-no-recipient-certs-query = មិន​បាន​អ៊ិនគ្រីប ៖ អ្នក​​គ្មាន​វិញ្ញាបនបត្រ​សម្រាប់​អ្នក​ទទួល​​ម្នាក់ៗ​ឡើយ ។
sec-error-not-a-recipient = មិន​អាច​ឌិគ្រីប​ឡើយ ៖ អ្នក​មិន​មែន​ជា​អ្នក​ទទួល​ឡើយ ឬ​រក​មិន​ឃើញ​សោ​ឯកជន និង​វិញ្ញាបនបត្រ​ដែល​ផ្គូផ្គង ។
sec-error-pkcs7-keyalg-mismatch = មិន​អាច​ឌិគ្រីប​ឡើយ ៖ ក្បួន​ដោះស្រាយ​​ក្នុង​ការ​អ៊ិនគ្រីប​សោ​មិន​ផ្គូផ្គង​វិញ្ញាបនបត្រ​របស់​អ្នក​ទេ ។
sec-error-pkcs7-bad-signature = បាន​បរាជ័យ​ក្នុង​ការ​ផ្ទៀងផ្ទាត់​ហត្ថលេខា ៖ រក​មិន​ឃើញ​អ្នក​ចុះ​ហត្ថលេខា​ឡើយ ទិន្នន័យ​ខូច ឬ​មិន​ត្រឹមត្រូវ ។
sec-error-unsupported-keyalg = ក្បួន​ដោះស្រាយ​​សោ​ដែល​មិន​ស្គាល់ ឬ​មិន​បាន​គាំទ្រ ។
sec-error-decryption-disallowed = មិន​អាច​ឌិគ្រីប​ឡើយ ៖ បាន​ឌិគ្រីប​​ដោយ​ប្រើ​ក្បួន​ដោះស្រាយ​​ដែល​មិន​បាន​អនុញ្ញាត ឬ​ទំហំ​សោ ។
xp-sec-fortezza-no-card = រក​មិន​ឃើញ​កាត​របស់ Fortezza ឡើយ
xp-sec-fortezza-none-selected = មិន​បាន​ជ្រើស​កាត Fortezza ឡើយ
xp-sec-fortezza-more-info = សូម​ជ្រើស​បុគ្គលិកលក្ខណៈ​ ដើម្បី​ទទួល​បាន​ព័ត៌មាន​បន្ថែម​នៅ​លើ
xp-sec-fortezza-person-not-found = រក​មិន​ឃើញ​បុគ្គលិកលក្ខណៈ​ឡើយ
xp-sec-fortezza-no-more-info = គ្មាន​ព័ត៌មាន​បន្ថែម​នៅ​លើ​បុគ្គលិកលក្ខណៈ​​នោះ​ទេ
xp-sec-fortezza-bad-pin = Pin មិន​ត្រឹមត្រូវ
sec-error-krl-invalid = KRL ថ្មី​មាន​ទ្រង់ទ្រាយ​មិន​ត្រឹមត្រូវ ។
sec-error-need-random = បណ្ណាល័យ​សុវត្ថិភាព ៖ ត្រូវការ​ទិន្នន័យ​​ចៃដន្យ ។
sec-error-no-module = បណ្ណាល័យ​សុវត្ថិភាព ៖ គ្មាន​ម៉ូឌុល​សុវត្ថិភាព​អាច​ប្រតិបត្តិ​លើ​ប្រតិបត្តិការ​ដែល​បាន​ស្នើ​ឡើយ ។
sec-error-no-token = គ្មាន​ថូខឹន ឬ​កាត​សុវត្ថិភាព​ឡើយ ចាំបាច់​ត្រូវ​រៀបចំ ឬ​​​​​​យកចេញ ។
sec-error-read-only = បណ្ណាល័យ​សុវត្ថិភាព ៖ មូលដ្ឋាន​ទិន្នន័យ​បាន​តែ​អាន ។
sec-error-no-slot-selected = មិន​បាន​ជ្រើស​ថូខឹន ឬ​រន្ធ​ឡើយ ។
sec-error-cert-nickname-collision = មាន​វិញ្ញាបនបត្រ​​ដែល​មាន​​សម្មតិនាម​ដូច​គ្នា​​ហើយ ។
sec-error-key-nickname-collision = មាន​សោ​ដែល​មាន​សម្មតិនាម​ដូច​គ្នា​​ហើយ ។
sec-error-safe-not-created = កំហុស​ខណៈ​ពេល​បង្កើត​វត្ថុ​សុវត្ថិភាព
sec-error-baggage-not-created = កំហុស​ខណៈ​ពេល​បង្កើត​វត្ថុ​កញ្ចប់
sec-error-bad-export-algorithm = ក្បួន​ដោះស្រាយ​ដែល​បាន​ទាមទារ​មិន​ត្រូវ​បាន​អនុញ្ញាត​ឡើយ ។
sec-error-exporting-certificates = កំហុស​ក្នុង​ការ​ប៉ុនប៉ង​នាំ​វិញ្ញាបនបត្រ​ចេញ ។
sec-error-importing-certificates = កំហុស​ក្នុង​ការ​ប៉ុនប៉ង​នាំ​វិញ្ញាបនបត្រ​​ចូល ។
sec-error-user-cancelled = អ្នក​ប្រើ​បាន​ចុច​បោះបង់ ។
sec-error-pkcs12-duplicate-data = មិន​អាច​នាំចូល​បាន​ទេ មាន​នៅ​ក្នុង​មូលដ្ឋាន​ទិន្នន័យ​រួចហើយ ។
sec-error-message-send-aborted = សារ​មិន​បាន​ផ្ញើ ។
sec-error-inadequate-key-usage = ការ​ប្រើ​សោ​​របស់​វិញ្ញាបនបត្រ​មិន​ត្រឹមត្រូវ សម្រាប់​ប្រតិបត្តិការ​ដែល​បាន​ប៉ុនប៉ង ។
sec-error-inadequate-cert-type = ប្រភេទ​វិញ្ញាបនបត្រ​មិន​យល់ព្រម​សម្រាប់​កម្មវិធី​ឡើយ ។
sec-error-cert-addr-mismatch = អាសយដ្ឋាន​ក្នុង​ការ​ចុះហត្ថលេខា​វិញ្ញាបនបត្រ​មិន​ផ្គូផ្គង​នឹង​អាសយដ្ឋាន​នៅ​ក្នុង​បឋមកថា​របស់​សារ​ឡើយ ។
sec-error-keygen-fail = មិន​អាច​បង្កើត​គូ​សោ សាធារណៈ/ឯកជន​ បាន​​ឡើយ ។
sec-error-bad-nickname = កំពុង​ប្រើ​សម្មតិនាម​របស់​វិញ្ញាបនបត្រ ។
sec-error-not-fortezza-issuer = ខ្សែស្រឡាយ FORTEZZA នៃ​ម៉ាស៊ីន​ដូចគ្នា មាន​វិញ្ញាបនបត្រ​ដែល​មិន​មែន​ជា FORTEZZA ។
sec-error-cannot-move-sensitive-key = មិន​អាច​ផ្លាស់ទី​កូនសោ sensitive ទៅកាន់​រន្ធ​ដែល​ត្រូវការ​វា ។
sec-error-js-invalid-module-name = ឈ្មោះ​របស់​​ម៉ូឌុល​មិន​ត្រឹមត្រូវ ។
sec-error-js-invalid-dll = ផ្លូវ/ឈ្មោះ​ឯកសារ​របស់​ម៉ូឌុល​មិន​ត្រឹមត្រូវ
sec-error-js-add-mod-failure = មិន​អាច​បន្ថែម​ម៉ូឌុល​បាន​ទេ
sec-error-js-del-mod-failure = មិន​អាច​លុប​ម៉ូឌុល​បាន​ទេ​
sec-error-old-krl = KRL ថ្មី​មិន​តិច​ជាង​មួយ​បច្ចុប្បន្ន​ឡើយ ។
sec-error-cert-not-in-name-space = បញ្ជាក់​ប្រភព​សម្រាប់​វិញ្ញាបនបត្រ​នេះ​គ្មាន​សិទ្ធិ​​ចេញ​វិញ្ញាបនបត្រ​ដែល​មាន​​ឈ្មោះ​នេះ​ទេ ។
sec-error-krl-not-yet-valid = រាយ​បញ្ជី​ក្នុង​ការ​ដកហូត​សោ​សម្រាប់​វិញ្ញាបនបត្រ​នេះ​មិន​ត្រឹមត្រូវ​ឡើយ ។
sec-error-crl-not-yet-valid = រាយ​បញ្ជី​ក្នុង​ការ​ដកហូត​​វិញ្ញាបនបត្រ​សម្រាប់​វិញ្ញាបនបត្រ​នេះ​មិន​​ត្រឹមត្រូវ​ឡើយ ។
sec-error-unknown-cert = រក​មិន​ឃើញ​វិញ្ញាបនបត្រ​ដែល​បាន​ស្នើ​ឡើយ ។
sec-error-cert-bad-access-location = ការ​បម្រុងទុក​សម្រាប់​ម៉ាស៊ីន​បម្រើ​ស្ថានភាព​របស់​វិញ្ញាបនបត្រ​មាន​ទ្រង់ទ្រាយ​មិន​ត្រឹមត្រូវ​ឡើយ ។
sec-error-ocsp-unknown-response-type = ចម្លើយតប​របស់ OCSP មិន​អាច​​ត្រូវ​បាន​ឌិកូដ​ដោយ​ពេញលេញ​ឡើយ វា​មាន​ប្រភេទ​ដែល​មិន​ស្គាល់ ។
sec-error-ocsp-bad-http-response = ម៉ាស៊ីន​បម្រើ​របស់ OCSP បាន​ត្រឡប់​ទិន្នន័យ​របស់  HTTP ដែល​មិន​បាន​រំពឹង/មិន​ត្រឹមត្រូវ ។
sec-error-ocsp-malformed-request = រក​ឃើញ​ម៉ាស៊ីន​បម្រើ​របស់ OCSP សំណើ​ត្រូវ​បាន​ខូច ឬ​ទ្រង់ទ្រាយ​មិន​ត្រឹមត្រូវ ។
sec-error-ocsp-server-error = ម៉ាស៊ីន​បម្រើ​របស់ OCSP បាន​ទទួល​​បទពិសោធន៍​អំពី​កំហុស​ខាងក្រៅ ។
sec-error-ocsp-try-server-later = ម៉ាស៊ីន​បម្រើ​របស់ OCSP ផ្ដល់​យោបល់​ឲ្យ​ព្យាយាម​ម្ដងទៀត​ពេលក្រោយ ។
sec-error-ocsp-request-needs-sig = ម៉ាស៊ីន​បម្រើ OCSP ទាមទារ​​ហត្ថលេខា​នៅ​លើ​សំណើ​នេះ ។
sec-error-ocsp-unauthorized-request = ម៉ាស៊ីន​បម្រើ​របស់ OCSP បដិសេធ​សំណើ​នេះ​​ដូច​ដែល​​មិន​​បាន​អនុញ្ញាត ។
sec-error-ocsp-unknown-response-status = ម៉ាស៊ីន​បម្រើ​របស់ OCSP បាន​ត្រឡប់​ស្ថានភាព​ដែល​មិន​អាច​ទទួល​ស្គាល់ ។
sec-error-ocsp-unknown-cert = ម៉ាស៊ីន​បម្រើ​របស់ OCSP គ្មាន​ស្ថានភាព​​សម្រាប់​វិញ្ញាបនបត្រ​ឡើយ ។
sec-error-ocsp-not-enabled = អ្នក​ត្រូវតែ​បើក OCSP មុន​ពេល​​ធ្វើ​ប្រតិបត្តិការ​នេះ ។
sec-error-ocsp-no-default-responder = អ្នក​​ត្រូវ​តែ​កំណត់​កម្មវិធី​ឆ្លើយតប​លំនាំ​ដើម​របស់ OCSP មុន​ពេល​ធ្វើ​ប្រតិបត្តិការ​នេះ ។
sec-error-ocsp-malformed-response = ចម្លើយតប​ពី​ម៉ាស៊ីន​របស់ OCSP ខូច​ ឬ​​​មាន​ទម្រង់​មិន​ត្រឹមត្រូវ ។
sec-error-ocsp-unauthorized-response = កម្មវិធី​​ចុះ​ហត្ថលេខា​ក្នុង​ការ​ឆ្លើយ​តប​របស់ OCSP មិន​ត្រូវ​បាន​អនុញ្ញាត​ឲ្យ​ស្ថានភាព​សម្រាប់​វិញ្ញាបនបត្រ​​នេះ​ទេ ។
sec-error-ocsp-future-response = ចម្លើយតប​របស់ OCSP ​មិន​​ត្រឹមត្រូវ​ឡើយ (មាន​កាលបរិច្ឆេទ​​ជា​លក្ខណៈ​ពិសេស​) ។
sec-error-ocsp-old-response = ចម្លើយតប​របស់ OCSP មាន​ព័ត៌មាន​ហួសសម័យ ។
sec-error-digest-not-found = រក​មិន​ឃើញ CMS ឬ PKCS #7 Digest នៅ​ក្នុង​សារ​ដែល​បាន​ចុះហត្ថលេខា​ឡើយ ។
sec-error-unsupported-message-type = ប្រភេទ​សារ CMS ឬ PKCS #7 មិន​ត្រូវ​បាន​គាំទ្រ​ឡើយ ។
sec-error-module-stuck = មិន​អាច​ផ្លាស់ទី​ម៉ូឌុល​របស់ PKCS #11 បាន​ទេ ពីព្រោះ​​វា​កំពុង​​ប្រើ ។
sec-error-bad-template = មិន​អាច​ឌិកូដ​ទិន្នន័យ ASN.1 បាន​ទេ ។ ពុម្ព​ដែល​បាន​បញ្ជាក់​មិន​ត្រឹមត្រូវ​ឡើយ ។
sec-error-crl-not-found = រក​មិន​ឃើញ CRL ដែល​ផ្គូផ្គង​ឡើយ ។
sec-error-reused-issuer-and-serial = អ្នក​កំពុង​ប៉ុនប៉ង​នាំចូល​វិញ្ញាបនបត្រ​ដោយមាន អ្នក​ចេញ/សៀរៀល ដូចជា​វិញ្ញាបនបត្រ​ដែល​មាន​ស្រាប់ ប៉ុន្តែ​​គ្មាន​វិញ្ញាបនបត្រ​ដូច​គ្នា​ទេ ។
sec-error-busy = NSS មិន​អាច​បិទ​បាន​ទេ ។ វត្ថុ​កំពុង​តែ​ប្រើ ។
sec-error-extra-input = សារ​ដែល​បាន​អ៊ិនកូដ​ជា DER មាន​ទិន្នន័យ​ដែល​មិន​ចាំបាច់​ច្រើន​ទៀត ។
sec-error-unsupported-elliptic-curve = ខ្សែ​កោង​​រាង​ពងក្រពើ​ដែល​មិន​បាន​គាំទ្រ ។
sec-error-unsupported-ec-point-form = ទម្រង់​​ចំណុច​ខ្សែ​កោង​រាងពងក្រពើ​ដែល​មិន​បាន​គាំទ្រ ។
sec-error-unrecognized-oid = ឧបករណ៍​សម្គាល់​​វត្ថុ​ដែល​មិន​ស្គាល់ ។
sec-error-ocsp-invalid-signing-cert = វិញ្ញាបនបត្រ​ក្នុង​ការ​ចុះហត្ថលេខា OCSP មិន​ត្រឹមត្រូវ​ក្នុង​ការ​ឆ្លើយតប​​​នៃ OCSP ។
sec-error-unknown-object-type = បាន​បញ្ជាក់​​ប្រភេទ​វត្ថុ​ដែល​មិន​ស្គាល់ ។
sec-error-incompatible-pkcs11 = កម្មវិធី​បញ្ជា​របស់ PKCS #11 ​​បំពាន​សេចក្ដី​បញ្ជាក់​វិធី​ដែល​មិន​ត្រូវ​គ្នា ។
sec-error-no-event = គ្មាន​ព្រឹត្តិការណ៍​រន្ធ​ថ្មី​ដែល​​មាន​នៅ​ពេលវេលា​នេះ​ឡើយ ។
sec-error-crl-already-exists = មាន CRL រួចហើយ ។
sec-error-not-initialized = NSS មិន​ត្រូវ​បាន​ចាប់ផ្ដើម​​ឡើយ ។
sec-error-token-not-logged-in = បាន​បរាជ័យ​ក្នុង​ការ​ប្រតិបត្តិការ ពីព្រោះ​ថូខឹន PKCS#11 មិន​ត្រូវ​បាន​ចូល​ឡើយ ។
sec-error-ocsp-bad-signature = ចម្លើយតប​របស់ OCSP មាន​ហត្ថលេខា​មិន​ត្រឹមត្រូវ ។
sec-error-out-of-search-limits = អស់​ពេល​ស្វែងរក​សុពលភាព​របស់​វិញ្ញាបនបត្រ
sec-error-invalid-policy-mapping = គោលការណ៍​ដែល​​មាន​ការ​ផ្គូផ្គង​​ជាមួយ​គោលការណ៍​មួយ​ចំនួន
sec-error-policy-validation-failed = ខ្សែស្រឡាយ​​​​វិញ្ញាបនបត្រ​បរាជ័យ​សុពល​​ភាព​​​របស់​​គោល​​ការណ៍
sec-error-unknown-aia-location-type = ប្រភេទ​ទីតាំង​ដែល​មិន​ស្គាល់​​នៅ​ផ្នែក​បន្ថែម AIA របស់​វិញ្ញាបនបត្រ
sec-error-bad-http-response = ម៉ាស៊ីន​បម្រើ​បាន​ឆ្លើយតប​ថា​​ HTTP មិន​ត្រឹមត្រូវ
sec-error-bad-ldap-response = ម៉ាស៊ីន​បម្រើ​បាន​ឆ្លើយតប​ថា LDAP មិន​ត្រឹមត្រូវ
sec-error-failed-to-encode-data = បាន​បរាជ័យ​ក្នុង​ការ​ឌិកូដ​ទិន្នន័យ​ដោយ​មាន​​អ៊ិនកូឌ័រ ASN1
sec-error-bad-info-access-location = ទីតាំង​ក្នុង​ការ​ចូល​ដំណើរការ​ព័ត៌មាន​មិន​ត្រឹមត្រូវ​​នៅ​ក្នុង​ផ្នែក​បន្ថែម​របស់​វិញ្ញាបនបត្រ
sec-error-libpkix-internal = កំហុស​ខាងក្នុង​របស់ Libpkix បាន​កើតឡើង​អំឡុង​ពេល​​សុពលភាព​របស់​​វិញ្ញាបនបត្រ ។
sec-error-pkcs11-general-error = ម៉ូឌុល​របស់ A PKCS #11 បាន​ត្រឡប់ CKR_GENERAL_ERROR បង្ហាញ​ថា​កំហុស​ដែល​មិន​អាច​យក​បាន​វិញ​​កើត​ឡើង ។
sec-error-pkcs11-device-error = ម៉ូឌុល​របស់ A PKCS #11 បាន​ត្រឡប់ CKR_DEVICE_ERROR បង្ហាញ​ថា​មាន​បញ្ហា​កើត​ឡើង​ជាមួយ​ថូខឹន ឬ​រន្ធ ។
sec-error-bad-info-access-method = វិធីសាស្ត្រ​ក្នុង​ការ​ចូល​ដំណើរការ​ព័ត៌មាន​ដែល​មិន​ស្គាល់​នៅ​ផ្នែក​បន្ថែម​របស់​វិញ្ញាបនបត្រ ។
sec-error-crl-import-failed = កំហុស​ក្នុង​ការ​ប៉ុនប៉ង​​ការ​នាំចូល CRL ។
sec-error-expired-password = ពាក្យសម្ងាត់​បាន​ផុត​កំណត់ ។
sec-error-locked-password = ពាក្យសម្ងាត់​ត្រូវ​បាន​ចាក់សោ ។
sec-error-unknown-pkcs11-error = មិន​ស្គាល់​កំហុស PKCS #11 ។
sec-error-bad-crl-dp-url = URL មិន​ត្រឹមត្រូវ ឬ​មិន​បាន​គាំទ្រ​នៅ​ក្នុង​ឈ្មោះ​ចំណុច​ការបែងចែក CRL ។
sec-error-cert-signature-algorithm-disabled = វិញ្ញាបនបត្រ​ត្រូវ​បាន​ចុះហត្ថលេខា​ដោយ​ក្បួន​ដោះស្រាយ​ ដែល​ត្រូវ​បាន​បិទ ដោយ​សារ​តែ​វា​គ្មាន​សុវត្ថិភាព ។
