# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Enregistrer
dialogTitleAddBookmark = Nouveau marque-page
dialogTitleAddMulti = Nouveaux marque-pages
dialogTitleEdit = Propriétés de « %S »
dialogTitleAddNewBookmark2 = Ajouter un marque-page
dialogTitleEditBookmark = Modifier « %S »
dialogTitleEditBookmark2 = Modifier le marque-page
dialogTitleAddBookmarkFolder = Ajouter un dossier de marque-pages
dialogTitleEditBookmarkFolder = Modifier un dossier de marque-pages
bookmarkAllTabsDefault = [Nom du dossier]
newFolderDefault = Nouveau dossier
newBookmarkDefault = Nouveau marque-page
