# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Alzar-lo
dialogTitleAddBookmark = Adhibir un marcapachinas
dialogTitleAddMulti = Adhibir nuevos marcapachinas
dialogTitleEdit = Propiedatz de “%S”
dialogTitleAddNewBookmark2 = Anyadir marcapachinas
dialogTitleEditBookmark = Editar “%S”
dialogTitleEditBookmark2 = Editar marcapachinas
dialogTitleAddBookmarkFolder = Anyadir carpeta de marcapachinas
dialogTitleEditBookmarkFolder = Editar carpeta de marcapachinas
bookmarkAllTabsDefault = [Nombre d'a carpeta]
newFolderDefault = Nueva carpeta
newBookmarkDefault = Nuevo marcapachinas
