# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Leita uppi { $host }…
network-connection-status-connected = Tengist við { $host }…
network-connection-status-sending-request = Sendi beiðni til { $host }…
network-connection-status-transferring-data = Næ í gögn frá { $host }…
network-connection-status-connecting = Tengist við { $host }…
network-connection-status-read = Les { $host }
network-connection-status-wrote = Skrifaði { $host }
network-connection-status-waiting = Bíð eftir { $host }…
network-connection-status-looked-up = Fletti upp { $host }…
network-connection-status-tls-handshake = Framkvæmi TLS samskipti við { $host }…
network-connection-status-tls-handshake-finished = Búið er að framkvæma TLS samskipti við { $host }…
