# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Го барам { $host }…
network-connection-status-connected = Се поврзав со { $host }…
network-connection-status-sending-request = Испраќам барање до { $host }…
network-connection-status-transferring-data = Примам податоци од { $host }…
network-connection-status-connecting = Се поврзувам со { $host }…
network-connection-status-read = Прочитав { $host }
network-connection-status-wrote = Запишав { $host }
network-connection-status-waiting = Во исчекување на { $host }…
network-connection-status-looked-up = Најден е { $host }…
