# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

timezone-label =
    .value = Crios Ama:
weekstart-label =
    .value = Tosaigh an tseachtain ar:
    .accesskey = T
dayweek-legend = Amhairc Lae agus Seachtaine
visible-hours-label =
    .value = Taispéain:
    .accesskey = a
visible-hours-end-label =
    .value = uaire ag aon am amháin
day-start-label =
    .value = Tosaíonn an lá ag:
    .accesskey = l
day-end-label =
    .value = Críochnaíonn an lá ag:
    .accesskey = g
multiweek-legend = Amharc Ilseachtaine
number-of-weeks-label =
    .value = Méid réamhshocraithe seachtainí a thaispeánfar (seachtainí roimh ré san áireamh):
    .accesskey = e
week-0-label =
    .label = neamhní
week-1-label =
    .label = 1 seachtain
week-2-label =
    .label = 2 sheachtain
week-3-label =
    .label = 3 seachtaine
week-4-label =
    .label = 4 seachtaine
week-5-label =
    .label = 5 seachtaine
week-6-label =
    .label = 6 seachtaine
previous-weeks-label =
    .value = Seachtainí roimhe seo le taispeáint:
    .accesskey = S
todaypane-legend = Pána Inniu
task-start-1-label =
    .label = Gan sonrú
task-start-2-label =
    .label = Tús an Lae
task-start-3-label =
    .label = Deireadh an Lae
task-start-4-label =
    .label = Amárach
task-start-5-label =
    .label = An tSeachtain Seo Chugainn
task-start-6-label =
    .label = I gcoibhneas leis an am reatha
task-start-7-label =
    .label = I gcoibhneas leis an tosach
task-start-8-label =
    .label = I gcoibhneas leis an chéad uair eile
reminder-legend = Nuair a bhíonn meabhrúchán réidh:
reminder-play-checkbox =
    .label = Seinn fuaim
    .accesskey = s
reminder-play-alarm-button =
    .label = Seinn
    .accesskey = S
reminder-default-sound-label =
    .label = Úsáid an fhuaim réamhshocraithe
    .accesskey = r
reminder-browse-sound-label =
    .label = Brabhsáil…
    .accesskey = B
reminder-dialog-label =
    .label = Taispeáin an dialóg mheabhrúcháin
    .accesskey = L
reminder-default-legend = Réamhshocruithe Meabhrúcháin
event-alarm-label =
    .value = Meabhrúcháin réamshocraithe ar imeachtaí:
    .accesskey = e
alarm-on-label =
    .label = Ann
alarm-off-label =
    .label = As
task-alarm-label =
    .value = Meabhrúcháin réamhshocraithe ar thascanna:
    .accesskey = a
event-alarm-time-label =
    .value = Achar réamhshocraithe roimh imeacht a thabharfar an meabhrúchán:
    .accesskey = r
task-alarm-time-label =
    .value = Achar réamhshocraithe roimh thasc a thabharfar an meabhrúchán:
    .accesskey = o
category-edit-label = Cuir Catagóir in Eagar
category-overwrite-title = Rabhadh: Ainm dúblach
category-overwrite = Tá catagóir ann cheana darb ainm sin. An bhfuil fonn ort é a fhorscríobh?
category-blank-warning = Caithfidh tú ainm a chur ar an chatagóir.
