# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE (nick_template): $1s is the common name from a cert (e.g. "Mozilla"), $2s is the CA name (e.g. VeriSign)
nick_template = %1$s’s %2$s ID
CertDumpKUSign = -taɁ lélù
CertDumpKUCertSign = Certificate Signer
CertDumpKUCRLSigner = CRL Signer
CertUnknown = Ngyéntá
CertOrgUnknown = (ngyéntá)
