# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = გსურთ ენდოთ “%S”-ს შემდეგი მიზნებისთვის?
unnamedCA = სერტიფიკატის გამცემი (უსახელო)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = გთხოვთ, შეიყვანოთ პაროლი, რომელიც ამ სერტიფიკატის მარქაფის დაშიფვრის დროს იყო გამოყენებული:
# Page Info
pageInfo_NoEncryption = კავშირი დაუშიფრავია
pageInfo_Privacy_None1 = საიტი %S არ იძლევა ამ გვერდის დაშიფვრის შესაძლებლობას.
pageInfo_Privacy_None2 = ინტერნეტით გადაცემისას დაუშიფრავი ინფორმაცია ადვილადაა ხელმისაწვდომი გარეშე პირთათვის.
pageInfo_Privacy_None4 = გვერდი, რომელსაც ათვალიერებთ, ინტერნეტით გადაცემამდე არ დაშიფრულა.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = კავშირი დაშიფრულია (%1$S, გასაღების სიგრძე %2$S ბიტი, %3$S)
pageInfo_BrokenEncryption = დაზიანებული დაშიფვრა (%1$S, გასაღების სიგრძე %2$S ბიტი, %3$S)
pageInfo_Privacy_Encrypted1 = გვერდი, რომელსაც ათვალიერებთ, ინტერნეტით გადაცემამდე დაიშიფრა.
pageInfo_Privacy_Encrypted2 = დაშიფვრა უძნელებს უცხო პირებს, უნებართვოდ იხილონ კომპიუტერებს შორის მიმოცვლილი ინფორმაცია. ამიტომ ნაკლებ სავარაუდოა, ქსელში გადაცემისას ვინმემ იხილოს ეს გვერდი.
pageInfo_MixedContent = კავშირი ნაწილობრივ დაშიფრულია
pageInfo_MixedContent2 = გვერდის შიგთავსის ნაწილი, რომელსაც ათვალიერებთ, ინტერნეტით გადაცემამდე არ დაშიფრულა.
pageInfo_WeakCipher = საიტთან კავშირისას სუსტი დაშიფვრაა გამოყენებული, რაც ვერ უზრუნველყოფს პირადი მონაცემების უსაფრთხოებას. შესაძლოა, სხვებმაც იხილონ გადაცემული ინფორმაცია, ან საიტის შიგთავსი შეცვალონ.
pageInfo_CertificateTransparency_Compliant = ეს საიტი აკმაყოფილებს სერტიფიკატის გამჭვირვალობის დებულების მოთხოვნებს.
# Token Manager
password_not_set = (არ მითითებულა)
