# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Po shihet për { $host }…
network-connection-status-connected = U lidh me { $host }…
network-connection-status-sending-request = Po dërgohet kërkesë te { $host }…
network-connection-status-transferring-data = Po shpërngulen të dhëna prej { $host }…
network-connection-status-connecting = Po bëhet lidhja me { $host }…
network-connection-status-read = U lexua { $host }
network-connection-status-wrote = U shkrua { $host }
network-connection-status-waiting = Po pritet për { $host }…
network-connection-status-looked-up = U kërkua për { $host }…
network-connection-status-tls-handshake = Po kryhet një duarshtrëngim TLS me { $host }…
network-connection-status-tls-handshake-finished = Duarshtrëngimi TLS përfundoi për { $host }…
