# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

print-setup =
    .title = Setup ng Pahina
custom-prompt-title = Custom…
custom-prompt-prompt = Ilagay ang iyong custom na teksto para sa header/footer
basic-tab =
    .label = Format & Opsyon
advanced-tab =
    .label = Mga Margin & Header/Footer
format-group-label =
    .value = Format
orientation-label =
    .value = Orientasyon:
portrait =
    .label = Portrait
    .accesskey = P
landscape =
    .label = Landscape
    .accesskey = L
scale =
    .label = Sukatan:
    .accesskey = S
scale-percent =
    .value = %
shrink-to-fit =
    .label = Paliitin para magkasya sa Lapad ng Pahina
    .accesskey = W
options-group-label =
    .value = Options
print-bg =
    .label = I-printa ang Background (mga kulay & mga larawan)
    .accesskey = B
margin-group-label-inches =
    .value = Margins (mga pulgada)
margin-group-label-metric =
    .value = Mga margin (millimeter)
margin-top =
    .value = Tuktok:
    .accesskey = T
margin-top-invisible =
    .value = Tuktok:
margin-bottom =
    .value = Bottom:
    .accesskey = B
margin-bottom-invisible =
    .value = Bottom:
margin-left =
    .value = Kaliwa:
    .accesskey = l
margin-left-invisible =
    .value = Kaliwa:
margin-right =
    .value = Right:
    .accesskey = R
margin-right-invisible =
    .value = Right:
header-footer-label =
    .value = Headers & Footers
hf-left-label =
    .value = Kaliwa:
hf-center-label =
    .value = Sentro:
hf-right-label =
    .value = Kanan:
header-left-tip =
    .tooltiptext = Kaliwang header
header-center-tip =
    .tooltiptext = Sentrong header
header-right-tip =
    .tooltiptext = Kanang header
footer-left-tip =
    .tooltiptext = Kaliwang footer
footer-center-tip =
    .tooltiptext = Sentrong footer
footer-right-tip =
    .tooltiptext = Kanang footer
hf-blank =
    .label = --blank--
hf-title =
    .label = Pamagat
hf-url =
    .label = URL
hf-date-and-time =
    .label = Petsa/Oras
hf-page =
    .label = Pahina #
hf-page-and-total =
    .label = Pahina # ng #
hf-custom =
    .label = Custom…
print-preview-window =
    .title = Print Preview
print-title =
    .value = Pamagat:
print-preparing =
    .value = Paghahanda
print-progress =
    .value = Progreso:
print-window =
    .title = Inililimbag
print-complete =
    .value = Ang Pag-imprenta ay tapos na.
# Variables
# $percent (integer) - Number of printed percentage
print-percent =
    .value = { $percent }%
dialog-cancel-label = Kanselahin
dialog-close-label = Isara
