# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=$ProductName$ Peakanyo
Welcome_MessageWelcome=Amogetšwe go %s!
Welcome_Message0=You are about to install %s 2 Alpha 1.
Welcome_Message1=Go tloga go šišinywa gore o tšwe mananeong ka moka a Windows pele ga ge o ka sepetša lenaneo le la Peakanyo.
Welcome_Message2=Kgotla Khansela go tšwa go Peakanyo gomme o tswalele mananeo a mangwe le a mangwe a o bego o a sepetša.  Kgotla Latela go tšwelapele ka lenaneo la Peakanyo.
Welcome_Message3=Click Next to continue installing %s 2 Alpha 1.

License_Title=Tumelelano ya Laesense ya Tshedimošo (ya khomphuthara)
License_SubTitle=Mabaka le maemo a go šomiša tshedimošo ye.
License_Message0=Ka kgopelo bala tumelelano ya laesense ye e latelago. Šomiša sekorolo-paa go lebelela tumelelano ye ka moka.
License_Accept=Ke &Amogela mabaka a Tumelelano ya Laesense
License_Decline=G&A ke Amogele mabaka a Tumelelo ya Laesense

Type_Title=Mohuta wa Peakanyo
Type_SubTitle=Kgetha dikgetho tša dipeakanyo.
Type_Message0=Kgetha mohuta wa Dipeakanyo wo o o ratago, gomme o kgotle Latela.

Standard_Short=&Maemo
Standard_Long=Thunderbird e tla lokelwa le dikgetho tše tlwaelegilego kudu.

Custom_Short=&Tlwaelo
Custom_Long=O ka kgetha dikgetho tše di ka lokelwago. Šišinyeditšwego badiriši ba maitemogelo.

Select_Title=Kgetha Dikarolwana
Select_SubTitle=Dikarolwana tša tlaleletšo tšeo di godišago $ProductName$.
Select_Message0=Kgetha dikarolwana tša tlaleletšo tšeo o nyakago go di lokela, gomme o kgotle Latela.

Path_Title=Lokela Foltara
Path_SubTitle=Moo $ProductName$ le tla lokelwago.
Path_Message0=$ProductName$ le tla lokelwa ka go foltara ye e latelago:

Integration_Title=Beakanya Ditselakgaoletša
Integration_SubTitle=Hlama Diaekhone tša Mananeo
Integration_Message0=Hlama diaekhone tša $ProductShortName$:

Integration_Desktop=Mo go Tesekethopo ya ka
Integration_StartMenu=Ka gare ga foltara ya ka ya Mananeo a Kgetho ya go Thoma
Integration_QuickLaunch=Ka gare ga paa ya ka ya Hloma ka Tšhoganetšo

SelectFolder_Title=$ProductName$ Peakanyo - Kgetha Foltara ya Lenaneo
SelectFolder_Message0=Peakanyo e tla lokela diaekhone tša lenaneo go Foltara ya Lenaneo yeo e tšwelelago ka fase.  O ka thaepa leina le leswa la foltara, goba o kgethe le tee go tšwa go tlhopho ya Difoltara tše di le go Gona.  Kgotla Latela go tšwelapele.

Advanced_Title=$ProductName$ Peakanyo - Dipeakanyo tše Gatetšego pele
Advanced_Message0=Ge kgokaganyo ya gago ya Inthanete e nyaka sebara ya sebaka, lokela leina la sebara ya gago le tshedimoso ya bohlomelo.  Ge kgokagano ya gago ya Inthanete e sa nyake sebara ya sebaka, tlogela mafelo a se a ngwalwa selo.

Install_Title=Kakaretšo
Install_SubTitle=Itokišeditše go thoma go lokela $ProductName$.
Install_MessageInstall=Peakanyo gabjale e tla lokela dikarolwana tše di latelago:
Install_MessageDownload=Peakanyo gabjale e tla bula le go lokela dikarolwana tše di latelago:
Install_Message0=Kgotla Latela go tšwelapele.

Downloading_Title=E a bula
Downloading_SubTitle=E bula dikarolwana tše di nyakegago...
Downloading_Blurb=Peakanyo e laolla difaele tšeo di nyakegago go lokela $ProductName$.
Downloading_FileName=Gabjale e a bula:
Downloading_Time=Nako ye e Šetšego:

Installing_Title=Go lokela
Installing_SubTitle=Go lokela $ProductName$...
Installing_Blurb=Peakanyo e hloma difaele tša tirišo.
Installing_Status=Go lokiša Faele:
Installing_Component=E a Lokela Gabjale:

Success_Title=Go lokela go Phethilwe
Success_Header=Go lokela go Phethilwe
Success_Message0=%s was successfully installed.
Success_Message1=Kgotla Fetša go feleletša Peakanyo.
Success_Launch=Launch %s now.

Check_Message=Go bula ga $ProductName$ go atlegile. $ProductNameInternal$ go swanetše go tswalelwa go tšwelapele ka go lokela. Kgotla Lokile go tšwa $ProductNameInternal$ ka tsela ya othomethiki le go thoma go lokela.
Check_FullMessage=$ProductNameInternal$ se swanetše go tswalela go tšwelapele ka go lokela. Kgotla Lokile go tšwa go $ProductNameInternal$ ka tsela ya othomethiki gomme o thome go lokela.
Check_Wait=Tswalela $ProductNameInternal$.  Ka kgopelo letela...

Component_XPCOM=Polatefomo ya go Selaganya ya COM
Component_Mail=$ProductName$
Component_Offline=Thekgo ya ntle le kgokagano ya megala
Component_Offline_Long=Lokela thekgo ya ntle le kgokagano ya megala go $ProductName$ Molaetša.
Component_RSS=Thekgo ya RSS
Component_RSS_Long=Lokela thekgo ya RSS go $ProductName$.
Component_QFA=Moemedi wa Dipoelo tša Khwalithi
Component_QFA_Long=go bega $ProductName$ tshedimošo ya go senyega
