# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Notice: If you're updating this list, you should also
###         update the list in mozIntl.js.

region-name-ad = Andòrra
region-name-ae = U.A.E.
region-name-af = Afganistan
region-name-ag = Antigoa e Barboda
region-name-ai = Angoilla
region-name-ao = Angòla
region-name-aq = Antartide
region-name-ar = Argentinn-a
region-name-as = Sonòa Americhen
region-name-at = Aostria
region-name-au = Aostralia
region-name-aw = Aroba
region-name-ba = Bòsnia e Herzegòvina
region-name-bb = Barbadòs
region-name-be = Belgio
region-name-bg = Bolgaria
region-name-bm = Bermoda
region-name-bn = Bronei Darussalam
region-name-bw = Bòtswana
region-name-cd = Còngo-Kinshasa
region-name-cg = Còngo-Brazzaville
region-name-ch = Svissera
region-name-ci = Costa d'avòio
region-name-cl = Cile
region-name-cn = Cina
region-name-co = Colòmbia
region-name-cr = Còsta Rica
region-name-cu = Coba
region-name-cy = Cipro
region-name-de = Germania
region-name-dj = Djibouti
region-name-dk = Danimarca
region-name-dm = Dòminica
region-name-ec = Ecoador
region-name-ee = Estònia
region-name-eg = Egitto
region-name-eh = Sahara Ponente
region-name-es = Spagna
region-name-et = Etiòpia
region-name-fi = Finlandia
region-name-fm = Micrònesia
region-name-fr = Fransa
region-name-ga = Gabòn
region-name-gd = Granada
region-name-ge = Geòrgia
region-name-gf = Guiana Franceize
region-name-gi = Gibiltæra
region-name-gl = Gròenlandia
region-name-gn = Goinea
region-name-gp = Goadelope
region-name-gq = Goinea Equatoriâ
region-name-gr = Grecia
region-name-gt = Goatemala
region-name-gu = Goam
region-name-gw = Goinea-Bissau
region-name-hk = Hòn Còng
region-name-hn = Hòndoras
region-name-hr = Cròazia
region-name-hu = Ungheria
region-name-ie = Irlanda
region-name-il = Israele
region-name-is = Islanda
region-name-it = Italia
region-name-jo = Giòrdania
region-name-jp = Giappon
region-name-kh = Cambògia
region-name-km = Comoròs
region-name-kn = Saint Kitts e Nevis
region-name-kp = Corea N
region-name-kr = Corea S
region-name-kw = Kuwait
region-name-kz = Kazakistan
region-name-la = Laòs
region-name-lb = Libano
region-name-lc = Santa Lucia
region-name-li = Liechtenstein
region-name-ls = Lezoto
region-name-lu = Lossenborgo
region-name-lv = Lettònia
region-name-ly = Libia
region-name-ma = Marocco
region-name-mc = Mònaco
region-name-md = Mòldòva
region-name-me = Mònteneigro
region-name-mm = Mianmar
region-name-mn = Mongòlia
region-name-ms = Montserrat
region-name-mv = Maldive
region-name-mx = Messico
region-name-my = Malesia
region-name-mz = Mònzanbico
region-name-ni = Nicaragoa
region-name-nl = Òlanda
region-name-nr = Naorô
region-name-om = Òman
region-name-pe = Peró
region-name-pf = Polinesia Franceize
region-name-pl = Pòlònia
region-name-pm = Saint Pierre e Miquelon
region-name-pt = Pòrtogallo
region-name-pw = Palao
region-name-rw = Roanda
region-name-sa = Arabia Saodita
region-name-se = Sveçia
region-name-sg = Singapô
region-name-sh = Sant'Elena
region-name-sk = Slovacchia
region-name-sl = Sierra Lion
region-name-sm = San Marin
region-name-st = Sao Tome e Principe
region-name-sv = O salvatô
region-name-sy = Siria
region-name-tf = Teritöio Françeize meridionâ
region-name-tg = Tògo
region-name-th = Tailandia
region-name-tk = Tokelao
region-name-tl = Timor-est
region-name-to = Tònga
region-name-tr = Turchia
region-name-tt = Trinidad e Tòbago
region-name-tv = Tovalû
region-name-ua = Ucraina
region-name-va = Çitæ do Vatican
region-name-vc = Saint Vincent e Grenadine
region-name-ve = Venezoela
region-name-wf = Wallis e Futuna
region-name-ws = Samòa
region-name-yt = Maiòtte
region-name-za = Sudafrica
