# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Leitar etter { $host }…
network-connection-status-connected = Tilkopla { $host } …
network-connection-status-sending-request = Sender førespurnad til { $host } …
network-connection-status-transferring-data = Fører over data frå { $host } …
network-connection-status-connecting = Koplar til { $host }…
network-connection-status-read = Las { $host }
network-connection-status-wrote = Skreiv { $host }
network-connection-status-waiting = Ventar på { $host } …
network-connection-status-looked-up = Leita etter { $host }…
network-connection-status-tls-handshake = Utfører ei TLS-handhelsing med { $host }…
network-connection-status-tls-handshake-finished = TLS-handhelsing fullført for { $host }…
