# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Ustalanie adresu serwera { $host }…
network-connection-status-connected = Połączono z { $host }…
network-connection-status-sending-request = Wysyłanie żądania do { $host }…
network-connection-status-transferring-data = Przesyłanie danych z { $host }…
network-connection-status-connecting = Łączenie się z { $host }…
network-connection-status-read = Odczytano { $host }
network-connection-status-wrote = Zapisano { $host }
network-connection-status-waiting = Oczekiwanie na { $host }…
network-connection-status-looked-up = Odnaleziono { $host }…
network-connection-status-tls-handshake = Negocjacja TLS z { $host }…
network-connection-status-tls-handshake-finished = Ukończono negocjację TLS z { $host }…
