# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Mbaroi Koha
openFile = Hap Kartelë
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Kërkoni me %1$S për "%2$S"
contextMenuSearch.accesskey = m
contextMenuPrivateSearch = Kërko në Dritare Private
contextMenuPrivateSearch.accesskey = o
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Kërko me %S në një Dritare Private
contextMenuPrivateSearchOtherEngine.accesskey = o
bookmarkAllTabsDefault = [Emër Dosjeje]
unsignedAddonsDisabled.message = S’verifikohet dot një ose më tepër shtesa të instaluara dhe u çaktivizuan.
unsignedAddonsDisabled.learnMore.label = Mësoni Më Tepër
unsignedAddonsDisabled.learnMore.accesskey = M
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Përdorimi i fundit %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = Lidhje %S://
crashedpluginsMessage.title = Shtojca %S u vithis.
crashedpluginsMessage.reloadButton.label = Ringarkoje faqen
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = Parashtroni një njoftim vithisjeje
crashedpluginsMessage.submitButton.accesskey = P
crashedpluginsMessage.learnMore = Mësoni Më Tepër…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Te %S synonit të shkonit?
keywordURIFixup.goTo = Po, shpjemëni te %S
keywordURIFixup.goTo.accesskey = P
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Përditësoje me %S
update.downloadAndInstallButton.accesskey = P
menuOpenAllInTabs.label = Hapi Krejt në Skeda
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Ringarkoni këtë faqe
tabHistory.goBack = Shko mbrapsht te kjo faqe
tabHistory.goForward = Shko përpara te kjo faqe
# URL Bar
pasteAndGo.label = Ngjite dhe Vazhdo
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Ringarkoni faqen e tanishme (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Ndalni ngarkimin e kësaj faqeje (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Zeroni shkallën e zoom-it (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Hapni/mbyllni pamjen Lexues (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, Rikthe shkallë zmadhimi/zvogëlimi te parazgjedhja
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Shfaqni faqerojtësit tuaj (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Shfaqni ecurinë e shkarkimeve që kryhen (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Hapni një dritare të re (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Hapni një skedë të re (%S)
newTabContainer.tooltip = Hape në një skedë të re (%S)\nShtypeni dhe mbajeni të shtypur që të hapet një skedë e re kontejneri
newTabAlwaysContainer.tooltip = Përzgjidhni një kontejner për hapje skede të re
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = Të lejohet %S të përdor të dhëna tuajat figure kanavace HTML5?
canvas.siteprompt2.warning = Kjo mund të përdoret për të identifikuar në mënyrë unike kompjuterin tuaj.
canvas.block = Bllokoje
canvas.block.accesskey = B
canvas.allow2 = Lejoje
canvas.allow2.accesskey = L
canvas.remember2 = Mbaje mend këtë vendim
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Vërtetuar nga: %S
identity.identified.verified_by_you = Keni shtuar përjashtim sigurie për këtë sajt
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Dëshmi lëshuar për: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Jo e Siguruar
identity.notSecure.tooltip = Lidhja s’është e siguruar
identity.extension.label = Zgjerim (%S)
identity.extension.tooltip = Ngarkuar nga zgjerimi: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Zvogëlojeni (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Zeroni shkallën e zoom-it (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Zmadhojeni (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Prijeni (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Kopjojeni (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Ngjiteni (%S)
geolocation.allow = Lejoje
geolocation.allow.accesskey = L
geolocation.block = Bllokoje
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Kjo do të hapë rregullime sistemi për vendndodhjet. Ju lutemi, akordoni leje vendndodhjeje për %S.
geolocation.shareWithSite4 = Të lejohet %S të përdorë vendndodhjen tuaj?
geolocation.shareWithFile4 = Të lejohet kjo kartelë vendore të hyjë në të dhënat për vendndodhjen tuaj?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = Të lejohet %1$S të japë leje %2$S për të përdorur vendndodhjen tuaj?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Akordoni leje vendndodhjeje për %S që nga rregullimet e sistemit.
geolocation.systemSettingsTitle = Në Pritje Për Leje Vendndodhjesh
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Sistemi do t’ju kërkojë të akordoni këtë leje për %S.
geolocation.remember = Mbaje mend këtë vendim
# Virtual Reality Device UI
xr.allow2 = Lejoje
xr.allow2.accesskey = L
xr.block = Bllokoje
xr.block.accesskey = B
xr.shareWithSite4 = Të lejohet %S të përdorë pajisje realiteti virtual? Kjo mund të ekspozojë informacion rezervat.
xr.shareWithFile4 = Të lejohet kjo kartelë vendore të përdorë pajisje realiteti virtual? Kjo mund të ekspozojë informacion rezervat.
xr.remember = Mbaje mend këtë vendim
# Persistent storage UI
persistentStorage.allow = Lejoje
persistentStorage.allow.accesskey = L
persistentStorage.block.label = Bllokoje
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = Të lejohet %S të depozitojë të dhëna në depozitë të qëndrueshme?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Lejoje
webNotifications.allow2.accesskey = L
webNotifications.notNow = Jo Tani
webNotifications.notNow.accesskey = j
webNotifications.never = Mos e Lejo Kurrë
webNotifications.never.accesskey = u
webNotifications.alwaysBlock = Bllokoje Përherë
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = Bllokoje
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = Të lejohet %S të dërgojë njoftime?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S dëshiron të përdorë aplikacione dhe shërbime të tjera në këtë pajisje.
localhost.remember2 = Mbaje mend zgjedhjen time për këtë sajt
localhost.allowlabel = Lejoje
localhost.blocklabel = Bllokoje
localhost.allow.accesskey = L
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S dëshiron të përdorë aplikacione dhe shërbime në pajisje të lidhura te rrjeti juaj vendor.
localNetwork.remember2 = Mbaje mend zgjedhjen time për këtë sajt
localNetwork.allowLabel = Lejoje
localNetwork.allow.accesskey = L
localNetwork.blockLabel = Bllokoje
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Hiqmë prej këtej!
safebrowsing.getMeOutOfHereButton.accessKey = H
safebrowsing.deceptiveSite = Sajt i Rremë!
safebrowsing.notADeceptiveSiteButton.label = Ky s’është sajt i rremë…
safebrowsing.notADeceptiveSiteButton.accessKey = R
safebrowsing.reportedAttackSite = I raportuar si Sajt Sulmesh!
safebrowsing.notAnAttackButton.label = Ky s’është sajt sulmesh…
safebrowsing.notAnAttackButton.accessKey = S
safebrowsing.reportedUnwantedSite = I raportuar si Sajt Software-i të Padëshiruar!
safebrowsing.reportedHarmfulSite = Sajt i Raportuar Si i Dëmshëm!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Kërko te %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = Të riniset %S nën Mënyrën Diagnostikim?
troubleshootModeRestartPromptMessage = Zgjerimet, temat dhe rregullimet tuaja të përshtatura do të çaktivizohen përkohësisht.
troubleshootModeRestartButton = Rinise
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Kjo faqe po ngadalëson %1$S. Që shfletuesi juaj të bëhet më i shpejtë, ndaleni këtë faqe.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Një faqe po ngadalëson %1$S. Që shfletuesi juaj të bëhet më i shpejtë, ndaleni këtë faqe.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = “%1$S” po ngadalëson %2$S. Që shfletuesi juaj të bëhet më i shpejtë, ndaleni këtë faqe.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = “%1$S” po ngadalëson %2$S. Që shfletuesi juaj të bëhet më i shpejtë, ndaleni atë zgjerim.
processHang.add-on.learn-more.text = Mësoni më tepër
processHang.button_stop2.label = Ndale
processHang.button_stop2.accessKey = N
processHang.button_debug.label = Diagnostikojeni Programthin
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Shfaqeni dritaren sa krejt ekrani (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Shpjere Anështyllën Majtas
sidebar.moveToRight = Shpjere Anështyllën Djathtas
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Që të luhet video ose audio në këtë faqe, duhet të aktivizoni DRM-në.
emeNotifications.drmContentDisabled.button.label = Aktivizoje DRM-n
emeNotifications.drmContentDisabled.button.accesskey = A
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S-i po instalon përbërës të nevojshëm për të luajtur audio ose video në këtë faqe. Ju lutemi, riprovoni më vonë.
emeNotifications.unknownDRMSoftware = I panjohur
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Përshtateni %S-in
decoder.noCodecs.button = Mësoni se si
decoder.noCodecs.accesskey = M
decoder.noCodecsLinux.message = Që të luani videon, mund t’ju duhet të instaloni kodekët e domosdoshëm për video.
decoder.noHWAcceleration.message = Që të përmirësoni cilësinë e videos, mund t’ju duhet të instaloni Media Feature Pack të Microsoft-it.
decoder.noPulseAudio.message = Që të luhet audio, mund  t’ju duhet të instaloni software-in e domosdoshëm PulseAudio.
decoder.unsupportedLibavcodec.message = libavcodec mund të jetë i cenueshëm, ose nuk mbulohet dhe duhet përditësuar që të luhet videoja.
decoder.decodeError.message = Ndodhi një gabim gjatë shkodimit të një burimi media.
decoder.decodeError.button = Raporto problem sajti
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = Ndodhi një gabim i riparueshëm gjatë shkodimit të një burimi media.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Duhet të bëni hyrjen në këtë rrjet, përpara se të përdorni Internetin.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Hap faqe hyrjeje në rrjet
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Leje për %S
permissions.remove.tooltip = Spastroje këtë leje dhe pyet sërish
permissions.fullscreen.promptCanceled = Janë anuluar kërkesa lejesh pezull: kërkesat për leje s’duhet bërë përpara se të kalohet në DOM sa-krejt-ekrani.
permissions.fullscreen.fullScreenCanceled = U dol nga DOM sa-krejt-ekrani: kërkesat për leje s’duhet bërë teksa gjendet në DOM sa-krejt-ekrani.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bit
aboutDialog.architecture.thirtyTwoBit = 32-bit
midi.allow.label = Lejoje
midi.allow.accesskey = L
midi.block.label = Bllokoje
midi.block.accesskey = B
midi.remember = Mbaje mend këtë vendim
midi.shareWithFile = Të lejohet kjo kartelë vendore të përdorë pajisje tuajat MIDI?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = Të lejohet %S të përdorë pajisje tuajat MIDI?
midi.shareSysexWithFile = Të lejohet kjo kartelë vendore të përdorë pajisje tuajat MIDI dhe të dërgojë/marrë mesazhe SysEx?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = Të lejohet %S të përdorë pajisje tuajat MIDI dhe të dërgojë/marrë mesazhe SysEx?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Mbrapsht
storageAccess1.Allow.label = Lejoje
storageAccess1.Allow.accesskey = L
storageAccess1.DontAllow.label = Bllokoje
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = Të lejohet %1$S të përdorë cookie-t e veta në %2$S?
storageAccess1.hintText = Mund të doni t’i bllokoni hyrjen, nëse s’është e qartë pse i duhen këto të dhëna %1$S.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Kërkoni në internet për “%S”
