# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Vai uzticēties “%S” zemāk esošajiem nolūkiem?
unnamedCA = Sertifikātu autoritāte (nenosaukta)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Lūgums ievadīt paroli, kas tika izmantota, lai šifrētu šo sertifikāta dublējumu:
# Page Info
pageInfo_NoEncryption = Savienojums nav šifrēts
pageInfo_Privacy_None1 = Tīmekļvietne %S neatbalsta pašreiz atvērtās lapas šifrēšanu.
pageInfo_Privacy_None2 = Internetā bez šifrēšanas nosūtīto informāciju tās pārsūtīšanas laikā var redzēt citi cilvēki.
pageInfo_Privacy_None4 = Šīs lapas saturs pirms sūtīšanas netika nošifrēs.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Šifrēts savienojums (%1$S, %2$S bitu atslēgas, %3$S)
pageInfo_BrokenEncryption = Šifrēts savienojums (%1$S, %2$S bitu atslēgas, %3$S)
pageInfo_Privacy_Encrypted1 = Šīs lapas saturs pirms sūtīšanas tika nošifrēs.
pageInfo_Privacy_Encrypted2 = Šifrēšana traucē nevēlamiem cilvēkiem piekļūt jūsu informācijai, kamēr tā tiek sūtīta starp datoriem internetā. Šīs lapas saturu visdrīzāk neviens nenolasīja, kamēr tā ceļoja internetā.
pageInfo_MixedContent = Savienojums daļēji šifrēts
pageInfo_MixedContent2 = Apskatāmās lapas daļas netika šifrētas pirms nosūtīšanas internetā.
pageInfo_WeakCipher = Jūsu savienojums ar šo lapu izmanto vāju šifrēšanu un nav privāts. Citi cilvēki var aplūkot jūsu informāciju vai modificēt lapas uzvedību.
pageInfo_CertificateTransparency_Compliant = Šī tīmekļvietne ievēro sertifikātu caurspīdības pamatnostādni.
# Token Manager
password_not_set = (nav iestatīts)
