# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = ورودهای ذخیره شده
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = رونوشت از آدرس
    .accesskey = y
launch-site-url-cmd =
    .label = مشاهدهٔ آدرس
    .accesskey = V
copy-username-cmd =
    .label = رونوشت از نام‌کاربری
    .accesskey = ن
edit-username-cmd =
    .label = تصحیح نام کاربری
    .accesskey = ت
copy-password-cmd =
    .label = رونوشت برداشتن از گذرواژه
    .accesskey = ر
edit-password-cmd =
    .label = ویرایش گذرواژه
    .accesskey = گ
search-filter =
    .accesskey = ج
    .placeholder = جست‌وجو:
column-heading-site =
    .label = پایگاه
column-heading-username =
    .label = نام کاربر
column-heading-password =
    .label = گذرواژه
column-heading-time-created =
    .label = اولین بار استفاده
column-heading-time-last-used =
    .label = آخرین بار استفاده
column-heading-time-password-changed =
    .label = آخرین تغییر
column-heading-times-used =
    .label = زمان استفاده شده
remove =
    .label = حذف
    .accesskey = ح
import =
    .label = وارد کردن…
    .accesskey = و
close-button =
    .label = بستن
    .accesskey = ب
show-passwords =
    .label = نشان دادن گذرواژه‌ها
    .accesskey = P
hide-passwords =
    .label = مخفی کردن گذرواژه‌ها
    .accesskey = P
logins-description-all = گذرواژه‌های مربوط به سایت‌های مقابل بر روی رایانه شما ذخیره شده است
logins-description-filtered = گذرواژه‌های زیر با جست‌وجوی شما منطیق هستند:
remove-all =
    .label = حذف همه
    .accesskey = ه
remove-all-shown =
    .label = حذف تمام موارد نمایان
    .accesskey = ت
remove-all-passwords-prompt = آیا مطمئنید که می‌خواهید تمامی گذرواژه‌هایتان را حذف کنید؟
remove-all-passwords-title = حذف همهٔ گذرواژه‌ها
no-master-password-prompt = آیا مطمئنید که می‌خواهید گذرواژه‌هایتان نشان داده شوند؟
