# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Über Ihre Rechte
rights-intro-point-4 = Wie wir Ihre über { -brand-short-name } an { -vendor-short-name } abgesendeten persönlichen Daten und Ihr Feedback nutzen, ist beschrieben in der <a data-l10n-name="mozilla-privacy-policy-link">{ -brand-short-name }-Datenschutzerklärung</a>.
rights-intro-point-6 = Zur Wiedergabe einiger Videoinhalte lädt { -brand-short-name } bestimmte Entschlüsselungskomponenten von Dritten herunter.
rights-webservices = { -brand-full-name } verwendet web-basierte Informationsdienste ("Services"), um einige der Funktionen anbieten zu können, die Ihnen für den Gebrauch mit der Binaryversion von { -brand-short-name } unter den unten angegebenen Bedingungen zur Verfügung gestellt werden. Falls Sie die Dienste oder einen davon nicht verwenden möchten oder die Bedingungen für Sie nicht akzeptabel sind, können Sie die Funktion oder die Service(s) deaktivieren. Anleitungen dafür, wie Sie eine bestimmte Funktion oder einen Service deaktivieren können, finden Sie <a data-l10n-name="mozilla-disable-service-link">hier</a>. Andere Funktionen und Dienste können in den Anwendungseinstellungen deaktiviert werden.
rights-webservices-term-1 = { -vendor-short-name } und die Mitwirkenden, Lizenzgeber und Partner versuchen die genausten und aktuellsten Services zur Verfügung zu stellen. Allerdings kann nicht garantiert werden, dass die Daten umfassend und fehlerfrei sind.  Beispielsweise könnte der SafeBrowsing-Service manche riskanten Websites als sicher einstufen und manche sicheren Websites fälschlicherweise als riskant. Und für standortbezogene Dienste gilt, dass alle Standortdaten, die von unseren Service-Providern geliefert werden, nur Schätzungen darstellen, und weder wir noch unsere Service-Provider garantieren für die Genauigkeit der Standortdaten.
rights-webservices-term-3 = Sie sind eingeladen, diese Dienste mit der dazugehörigen { -brand-short-name }-Version zu verwenden, und { -vendor-short-name } erteilt Ihnen die Rechte dies zu tun. { -vendor-short-name } und ihre Lizenzgeber behalten sich alle anderen Rechte an den Diensten vor. Diese Bedingungen beabsichtigen nicht, jegliche Rechte einzuschränken, die von Open-Source-Lizenzen gewährt werden, die auf { -brand-short-name } und entsprechende Quellcode-Versionen von { -brand-short-name } anwendbar sind.
rights-webservices-term-4 = <strong>Die Dienste werden "wie es ist" zur Verfügung gestellt. { -vendor-short-name }, ihre Mitwirkenden, Lizenzgeber und Distributoren gewähren keinerlei Gewährleistung, weder ausdrücklich noch implizit, einschließlich – aber nicht begrenzt auf – Marktreife oder Verwendbarkeit für einen bestimmten Zweck. Das volle Risiko bezüglich der Auswahl des für Sie richtigen Dienstes und die Qualität und Leistungsfähigkeit des Dienstes liegt bei Ihnen. Manche Gerichtsbarkeiten erlauben nicht den Ausschluss oder die Eingrenzung von implizierten Risiken, so dass dieser Haftungsausschluss möglicherweise nicht für Sie gilt.</strong>
rights-webservices-term-5 = <strong>In keinem Fall, außer wenn durch geltendes Recht gefordert, sind { -vendor-short-name }, ihre Mitwirkenden, Lizenzgeber oder Distributoren für irgendwelchen indirekten oder speziellen Schäden, Schäden durch Seiteneffekte (Nebenwirkungen) oder Folgeschäden, die aus der Benutzung von { -brand-short-name } oder den Diensten folgen, haftbar. Die gesamte Haftbarkeit unter diesen Bedingungen beschränkt sich auf maximal $500 (fünfhundert Dollar). Manche Gerichtsbarkeiten erlauben nicht den Ausschluss oder die Eingrenzung von bestimmten Risiken, so dass diese Ausschlüsse oder Eingrenzungen möglicherweise nicht für Sie gelten.</strong>
