# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SaveImageTitle = Resmi kaydet
SaveMediaTitle = Ortamı kaydet
SaveVideoTitle = Videoyu kaydet
SaveAudioTitle = Sesi kaydet
SaveLinkTitle = Farklı kaydet
WebPageCompleteFilter = Web sayfası, tümüyle
WebPageHTMLOnlyFilter = Web sayfası, sadece HTML
WebPageXHTMLOnlyFilter = Web sayfası, sadece XHTML
WebPageSVGOnlyFilter = Web sayfası, sadece SVG
WebPageXMLOnlyFilter = Web sayfası, sadece XML
# LOCALIZATION NOTE (UntitledSaveFileName):
#    This is the default filename used when saving a file if a filename could
#    not be determined or if a filename was invalid. A period and file
#    extension may be appended to this string.
UntitledSaveFileName = Başlıksız
