# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

appmenu-update-available =
    .label = Un hizivadenn nevez a zo evit { -brand-shorter-name }.
    .buttonlabel = Pellgargañ an hizivadenn
    .buttonaccesskey = P
    .secondarybuttonlabel = Diwezhatoc'h
    .secondarybuttonaccesskey = D
appmenu-update-available-message = Hizivait { -brand-shorter-name } evit gwellaat e dizh hag e brevezded.
appmenu-update-manual =
    .label = N’haller ket hizivaat { -brand-shorter-name } d’an handelv nevez.
    .buttonlabel = Pellgargañ { -brand-shorter-name }
    .buttonaccesskey = P
    .secondarybuttonlabel = Ket bremañ
    .secondarybuttonaccesskey = K
appmenu-update-manual-message = Pellgargit un eilad nevez eus { -brand-shorter-name } ha skoazellañ a raimp d’e staliañ.
appmenu-update-whats-new =
    .value = Lennit petra zo nevez.
appmenu-update-unsupported =
    .label = { -brand-shorter-name } n’hall ket hizivaat d’an handelv diwezhañ.
    .buttonlabel = Gouzout hiroc’h
    .buttonaccesskey = G
    .secondarybuttonlabel = Serriñ
    .secondarybuttonaccesskey = S
appmenu-update-unsupported-message = Handelv diwezhañ { -brand-shorter-name } n'eo ket skoret war ho reizhad.
appmenu-update-restart =
    .label = Adloc'hit evit hizivaat { -brand-shorter-name }
    .buttonlabel = Adloc'hañ hag atoriñ
    .buttonaccesskey = A
    .secondarybuttonlabel = Diwezhatoc'h
    .secondarybuttonaccesskey = D
appmenu-update-restart-message = Goude un adloc'hadur prim e vo atoret gant { -brand-shorter-name } ho holl ivinelloù ha prenestroù na oa ket e mod merdeiñ prevez.
appmenu-addon-private-browsing-installed =
    .buttonlabel = Mat eo, komprenet am eus
    .buttonaccesskey = M
appmenu-addon-post-install-message = Merit hoc'h askouezhioù en ur glikañ war <image data-l10n-name='addon-install-icon'></image> el lañser <image data-l10n-name='addon-menu-icon'></image>.

appmenu-update-available2 =
    .label = Hizivadenn hegerz
    .buttonlabel = Pellgargañ
    .buttonaccesskey = P
    .secondarybuttonlabel = Skarzhañ
    .secondarybuttonaccesskey = S
appmenu-update-available-message2 = Pellgargañ handelv diwezhañ { -brand-shorter-name }.
appmenu-update-manual2 =
    .label = Hizivadenn hegerz
    .buttonlabel = Pellgargañ
    .buttonaccesskey = P
    .secondarybuttonlabel = Skarzhañ
    .secondarybuttonaccesskey = S
appmenu-update-manual-message2 = { -brand-shorter-name } ne c’hall ket en em hizivaat en un doare emgefreek. Pellgargit an handelv diwezhañ — ne vo ket kollet ganeoc'h ho titouroù enrollet ha personeladurioù.
appmenu-update-unsupported2 =
    .label = Ne c’hall ket hizivaat
    .buttonlabel = Gouzout hiroc'h
    .buttonaccesskey = G
    .secondarybuttonlabel = Skarzhañ
    .secondarybuttonaccesskey = S
appmenu-update-unsupported-message2 = Ho reizhiad korvoiñ ne genglot ket gant handelv diwezhañ { -brand-shorter-name }.
appmenu-update-restart2 =
    .label = Hizivadenn hegerz
    .buttonlabel = Hizivaat hag adloc’hañ
    .buttonaccesskey = H
    .secondarybuttonlabel = Skarzhañ
    .secondarybuttonaccesskey = S
appmenu-update-restart-message2 = Tapit handelv diwezhañ { -brand-shorter-name }. Assavet e vo an holl brenestroù hag ivinelloù.
appmenu-update-other-instance =
    .label = N'eo ket gouest { -brand-shorter-name } da hizivaat ent emgefreek betek an handelv diwezhañ
    .buttonlabel = Hizivaat { -brand-shorter-name } memestra
    .buttonaccesskey = H
    .secondarybuttonlabel = Ket bremañ
    .secondarybuttonaccesskey = K
appmenu-update-other-instance-message = Un hizivadenn nevez eus { -brand-shorter-name } a zo hegerz, met n’hall ket bezañ staliet dre ma zo ur staliadenn all eus { -brand-shorter-name } a zo lañset. Serrit anezhi evit kenderc'hel gant an hizivadenn, pe dibabit da hizivaat memestra (gallout a ra ar staliadenn all chom hep mont en-dro betek ma adloc'hfec'h anezhi).

appmenu-addon-private-browsing-installed2 =
    .buttonlabel = Mat eo
    .buttonaccesskey = M
appmenu-addon-post-install-message3 = Merit hoc'h askouezhioù hag ho neuzioù dre lañser an arload.
appmenu-addon-post-install-incognito-checkbox =
    .label = Aotren an askouezh-mañ da vezañ lañset en ur prenestr merdeiñ prevez
    .accesskey = A
    
appmenu-new-tab-controlled =
    .label = Kemmet eo bet pajenn an ivinell nevez.
    .buttonlabel = Mirout ar c'hemmoù
    .buttonaccesskey = M
    .secondarybuttonlabel = Diweredekaat an askouezh
    .secondarybuttonaccesskey = D
appmenu-homepage-controlled =
    .label = Kemmet eo bet ho pennbajenn.
    .buttonlabel = Mirout ar c'hemmoù
    .buttonaccesskey = K
    .secondarybuttonlabel = Diweredekaat an askouezh
    .secondarybuttonaccesskey = D

appmenu-new-tab-controlled-changes =
    .label = Kemmet eo bet pajenn an ivinell nevez.
    .buttonlabel = Mirout ar c'hemmoù
    .buttonaccesskey = M
    .secondarybuttonlabel = Ardeiñ an ivinelloù nevez
    .secondarybuttonaccesskey = A
appmenu-homepage-controlled-changes =
    .label = Kemmet eo bet ho pennbajenn.
    .buttonlabel = Mirout ar c'hemmoù
    .buttonaccesskey = M
    .secondarybuttonlabel = Ardeiñ ar pennbajenn
    .secondarybuttonaccesskey = A
appmenu-tab-hide-controlled =
    .label = Haeziñ hoc'h ivinelloù kuzh
    .buttonlabel = Derc'hel an ivinelloù kuzhet
    .buttonaccesskey = D
    .secondarybuttonlabel = Diweredekaat an askouezhioù
    .secondarybuttonaccesskey = D
