# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

appmenu-update-available2 =
    .buttonlabel = Pellgargañ
    .buttonaccesskey = P
    .label = Hizivadenn hegerz
    .secondarybuttonlabel = Skarzhañ
    .secondarybuttonaccesskey = S
appmenu-update-available-message2 = Pellgargañ handelv diwezhañ { -brand-shorter-name }.
appmenu-update-manual2 =
    .buttonlabel = Pellgargañ
    .buttonaccesskey = P
    .label = Hizivadenn hegerz
    .secondarybuttonlabel = Skarzhañ
    .secondarybuttonaccesskey = S
appmenu-update-manual-message2 = { -brand-shorter-name } ne c’hall ket en em hizivaat en un doare emgefreek. Pellgargit an handelv diwezhañ — ne vo ket kollet ganeoc'h ho titouroù enrollet ha personeladurioù.
appmenu-update-unsupported2 =
    .buttonlabel = Gouzout hiroc'h
    .buttonaccesskey = G
    .label = Ne c’hall ket hizivaat
    .secondarybuttonlabel = Skarzhañ
    .secondarybuttonaccesskey = S
appmenu-update-unsupported-message2 = Ho reizhiad korvoiñ ne genglot ket gant handelv diwezhañ { -brand-shorter-name }.
appmenu-update-restart2 =
    .buttonlabel = Hizivaat hag adloc’hañ
    .buttonaccesskey = H
    .label = Hizivadenn hegerz
    .secondarybuttonlabel = Skarzhañ
    .secondarybuttonaccesskey = S
appmenu-update-restart-message2 = Tapit handelv diwezhañ { -brand-shorter-name }. Assavet e vo an holl brenestroù hag ivinelloù.
appmenu-theme-installed =
    .secondarybuttonlabel = Dizober
    .secondarybuttonaccesskey = i
appmenu-update-other-instance =
    .buttonlabel = Hizivaat { -brand-shorter-name } memestra
    .buttonaccesskey = H
    .label = N'eo ket gouest { -brand-shorter-name } da hizivaat ent emgefreek betek an handelv diwezhañ
    .secondarybuttonlabel = Ket bremañ
    .secondarybuttonaccesskey = K
appmenu-update-other-instance-message = Un hizivadenn nevez eus { -brand-shorter-name } a zo hegerz, met n’hall ket bezañ staliet dre ma zo ur staliadenn all eus { -brand-shorter-name } a zo lañset. Serrit anezhi evit kenderc'hel gant an hizivadenn, pe dibabit da hizivaat memestra (gallout a ra ar staliadenn all chom hep mont en-dro betek ma adloc'hfec'h anezhi).
appmenu-addon-post-install-message3 = Merit hoc'h askouezhioù hag ho neuzioù dre lañser an arload.
appmenu-new-tab-controlled-changes =
    .buttonlabel = Mirout ar c'hemmoù
    .buttonaccesskey = M
    .label = Kemmet eo bet pajenn an ivinell nevez.
    .secondarybuttonlabel = Ardeiñ an ivinelloù nevez
    .secondarybuttonaccesskey = A
appmenu-homepage-controlled-changes =
    .buttonlabel = Mirout ar c'hemmoù
    .buttonaccesskey = M
    .label = Kemmet eo bet ho pennbajenn.
    .secondarybuttonlabel = Ardeiñ ar pennbajenn
    .secondarybuttonaccesskey = A
appmenu-tab-hide-controlled =
    .buttonlabel = Derc'hel an ivinelloù kuzhet
    .buttonaccesskey = D
    .label = Haeziñ hoc'h ivinelloù kuzh
    .secondarybuttonlabel = Diweredekaat an askouezhioù
    .secondarybuttonaccesskey = D
