# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE  (autocompletion.notFound): This is the text shown in
# the documentation popup if Tern fails to find a type for the object.
autocompletion.notFound = ਨਹੀਂ ਲੱਭਾ
