# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Gordetako saio-hasierak
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Kopiatu URLa
    .accesskey = o
launch-site-url-cmd =
    .label = Bisitatu URLa
    .accesskey = B
copy-username-cmd =
    .label = Kopiatu erabiltzaile-izena
    .accesskey = e
edit-username-cmd =
    .label = Editatu erabiltzaile-izena
    .accesskey = d
copy-password-cmd =
    .label = Kopiatu pasahitza
    .accesskey = K
edit-password-cmd =
    .label = Editatu pasahitza
    .accesskey = E
search-filter =
    .accesskey = B
    .placeholder = Bilatu
column-heading-site =
    .label = Gunea
column-heading-username =
    .label = Erabiltzaile-izena
column-heading-password =
    .label = Pasahitza
column-heading-time-created =
    .label = Lehenengoz erabilia
column-heading-time-last-used =
    .label = Azkenekoz erabilia
column-heading-time-password-changed =
    .label = Azken aldaketa
column-heading-times-used =
    .label = Erabilitako aldiak
remove =
    .label = Kendu
    .accesskey = K
import =
    .label = Inportatu…
    .accesskey = I
close-button =
    .label = Itxi
    .accesskey = x
show-passwords =
    .label = Erakutsi pasahitzak
    .accesskey = P
hide-passwords =
    .label = Ezkutatu pasahitzak
    .accesskey = P
logins-description-all = Ondorengo guneetako saio-hasierak daude gordeta
logins-description-filtered = Ondorengo saio-hasierak bat datoz zure bilaketarekin:
remove-all =
    .label = Kendu denak
    .accesskey = d
remove-all-shown =
    .label = Kendu erakutsitako denak
    .accesskey = d
remove-all-passwords-prompt = Ziur zaude pasahitz guztiak ezabatu nahi dituzula?
remove-all-passwords-title = Ezabatu pasahitz guztiak
no-master-password-prompt = Ziur zaude pasahitzak erakutsi nahi dituzula?
auto-fill-logins-and-passwords =
    .label = Automatikoki bete erabiltzaile-izen eta pasahitzak
