# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = چوونەژوورەوە پاشەکەوتکراوەکان...
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = بەستەر لەبەربگرەوە
    .accesskey = y
launch-site-url-cmd =
    .label = سەردانی بەستەر بکە
    .accesskey = V
copy-username-cmd =
    .label = ناوی بەکارهێنەر لەبەربگرەوە
    .accesskey = U
edit-username-cmd =
    .label = ناوی بەکارهێنەر دەستکاری بکە
    .accesskey = d
copy-password-cmd =
    .label = وشەی تێپەڕبوون لەبەر بگرەوە
    .accesskey = C
edit-password-cmd =
    .label = وشەی تێپەڕبوون دەستکاری بکە
    .accesskey = E
search-filter =
    .accesskey = S
    .placeholder = گەڕان
column-heading-site =
    .label = ماڵپەڕ
column-heading-username =
    .label = ناوی بەکارهێنەر
column-heading-password =
    .label = وشەی تێپەڕبوون
column-heading-time-created =
    .label = یەکەم بەکارهێنراو
column-heading-time-last-used =
    .label = دووا بەکارهێنان
column-heading-time-password-changed =
    .label = دووا گۆڕانکاری
column-heading-times-used =
    .label = جاری بەکارهێنان
remove =
    .label = بیسڕەوە
    .accesskey = R
import =
    .label = هاوردەکردن...
    .accesskey = I
close-button =
    .label = داخستن
    .accesskey = C
show-passwords =
    .label = وشەی تێپەڕبوون پیشان بدە
    .accesskey = P
hide-passwords =
    .label = وشەی تێپەڕبوون بشارەوە
    .accesskey = P
logins-description-all = چوونژوورەوە بۆ ئەم ماڵپەڕانە لەناو کۆمپیوتەرەکەت هەڵدەگیرێت
logins-description-filtered = ئەم چوونەژوورەوانە گەڕانەکەی تۆ دەگرێتەوە:
remove-all =
    .label = هەمووی بسڕەوە
    .accesskey = A
remove-all-shown =
    .label = هەموو پیشاندراوەکان بسڕەوە
    .accesskey = A
remove-all-passwords-prompt = ئایا تۆ دڵنیایت کە دەتەوێت هەموو وشەی تێپەڕبوونەکان بسڕیتەوە؟
remove-all-passwords-title = هەموو وشەی تێپەڕبوونەکان بسڕەوە
no-master-password-prompt = ئایا تۆ دڵنیایت کە دەتەوێت هەموو وشەی تێپەڕبوونەکان پیشان بدەیت؟
auto-fill-logins-and-passwords =
    .label = پڕکردنەوەی خۆکاری چوونەژوور و وشە تێپەڕەکان
