# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

migration-wizard =
    .title = İtalât Siirbazı
import-from =
    { PLATFORM() ->
        [windows] İhtiyariyatnı, Saife-imlerini, Keçmişni, Sır-sözlerni ve diger verilerni şuradan ital et:
       *[other] Tercihlerni, Saife-imlerini, Keçmişni, Sır-sözlerni ve diger verilerni şuradan ital et:
    }
import-from-bookmarks = Saife-imlerini şuradan ital et:
import-from-ie =
    .label = Microsoft İnternet Explorer
    .accesskey = M
import-from-edge =
    .label = Microsoft Edge
    .accesskey = E
import-from-nothing =
    .label = İç bir şeyni ital etme
    .accesskey = m
import-from-safari =
    .label = Safari
    .accesskey = S
import-from-canary =
    .label = Chrome Canary
    .accesskey = n
import-from-chrome =
    .label = Chrome
    .accesskey = C
import-from-chrome-beta =
    .label = Chrome Beta
    .accesskey = B
import-from-chrome-dev =
    .label = Chrome Dev
    .accesskey = D
import-from-chromium =
    .label = Chromium
    .accesskey = u
import-from-firefox =
    .label = Firefox
    .accesskey = x
import-from-360se =
    .label = 360 Emniyetli Kezici
    .accesskey = 3
no-migration-sources = Saife-imlerini, keçmişni yaki sır-söz verilerini ihtiva etken iç bir program tapılamadı.
import-source =
    .label = Tesbitler ve Verilerniñ İtalâtı
import-items-title =
    .label = İtal Etilecek Adedler
import-items-description = İtal etilecek unsurlarnı sayla:
import-migrating-title =
    .label = İtal etile…
import-migrating-description = Aşağıdaki unsurlar al-azırda ital etile…
import-select-profile-title =
    .label = Profil Sayla
import-select-profile-description = İtal etilebilecek aşağıdaki profiller mevcuttır:
import-done-title =
    .label = İtalât Tamam
import-done-description = Aşağıdaki unsurlar muvafaqiyetnen ital etildi:
import-close-source-browser = Devam etmezden evvel lütfen saylanğan keziciniñ qapalı olğanından emin oluñız.
# Displays which browser the bookmarks are being imported from
#
# Variables:
#   $source (String): The browser the user has chosen to import bookmarks from.
imported-bookmarks-source = Şuradan: { $source }
source-name-ie = İnternet Explorer
source-name-edge = Microsoft Edge
source-name-safari = Safari
source-name-canary = Google Chrome Canary
source-name-chrome = Google Chrome
source-name-chrome-beta = Google Chrome Beta
source-name-chrome-dev = Google Chrome Dev
source-name-chromium = Chromium
source-name-firefox = Mozilla Firefox
source-name-360se = 360 Emniyetli Kezici
imported-safari-reading-list = Oquma Listesi (Safari'den)
imported-edge-reading-list = Oquma Listesi (Edge'den)

# Import Sources
# Note: When adding an import source for profile reset, add the string name to
# resetProfile.js if it should be listed in the reset dialog.

browser-data-ie-1 =
    .label = İnternet İhtiyariyatı
    .value = İnternet İhtiyariyatı
browser-data-edge-1 =
    .label = Ayarlar
    .value = Ayarlar
browser-data-safari-1 =
    .label = Tercihler
    .value = Tercihler
browser-data-chrome-1 =
    .label = Tercihler
    .value = Tercihler
browser-data-canary-1 =
    .label = Tercihler
    .value = Tercihler
browser-data-360se-1 =
    .label = Tercihler
    .value = Tercihler
browser-data-ie-2 =
    .label = Çörekler
    .value = Çörekler
browser-data-edge-2 =
    .label = Çörekler
    .value = Çörekler
browser-data-safari-2 =
    .label = Çörekler
    .value = Çörekler
browser-data-chrome-2 =
    .label = Çörekler
    .value = Çörekler
browser-data-canary-2 =
    .label = Çörekler
    .value = Çörekler
browser-data-firefox-2 =
    .label = Çörekler
    .value = Çörekler
browser-data-360se-2 =
    .label = Çörekler
    .value = Çörekler
browser-data-ie-4 =
    .label = Kezinüv Keçmişi
    .value = Kezinüv Keçmişi
browser-data-edge-4 =
    .label = Kezinüv Keçmişi
    .value = Kezinüv Keçmişi
browser-data-safari-4 =
    .label = Kezinüv Keçmişi
    .value = Kezinüv Keçmişi
browser-data-chrome-4 =
    .label = Kezinüv Keçmişi
    .value = Kezinüv Keçmişi
browser-data-canary-4 =
    .label = Kezinüv Keçmişi
    .value = Kezinüv Keçmişi
browser-data-firefox-history-and-bookmarks-4 =
    .label = Kezinme Keçmişi ve Saifeimleri
    .value = Kezinme Keçmişi ve Saifeimleri
browser-data-360se-4 =
    .label = Kezinüv Keçmişi
    .value = Kezinüv Keçmişi
browser-data-ie-8 =
    .label = Saqlanğan Forma Keçmişi
    .value = Saqlanğan Forma Keçmişi
browser-data-edge-8 =
    .label = Saqlanğan Forma Keçmişi
    .value = Saqlanğan Forma Keçmişi
browser-data-safari-8 =
    .label = Saqlanğan Forma Keçmişi
    .value = Saqlanğan Forma Keçmişi
browser-data-chrome-8 =
    .label = Saqlanğan Forma Keçmişi
    .value = Saqlanğan Forma Keçmişi
browser-data-canary-8 =
    .label = Saqlanğan Forma Keçmişi
    .value = Saqlanğan Forma Keçmişi
browser-data-firefox-8 =
    .label = Saqlanğan Forma Keçmişi
    .value = Saqlanğan Forma Keçmişi
browser-data-360se-8 =
    .label = Saqlanğan Forma Keçmişi
    .value = Saqlanğan Forma Keçmişi
browser-data-ie-16 =
    .label = Saqlanğan Sır-sözler
    .value = Saqlanğan Sır-sözler
browser-data-edge-16 =
    .label = Saqlanğan Sır-sözler
    .value = Saqlanğan Sır-sözler
browser-data-safari-16 =
    .label = Saqlanğan Sır-sözler
    .value = Saqlanğan Sır-sözler
browser-data-chrome-16 =
    .label = Saqlanğan Sır-sözler
    .value = Saqlanğan Sır-sözler
browser-data-canary-16 =
    .label = Saqlanğan Sır-sözler
    .value = Saqlanğan Sır-sözler
browser-data-firefox-16 =
    .label = Saqlanğan Sır-sözler
    .value = Saqlanğan Sır-sözler
browser-data-360se-16 =
    .label = Saqlanğan Sır-sözler
    .value = Saqlanğan Sır-sözler
browser-data-ie-32 =
    .label = Favoritler
    .value = Favoritler
browser-data-edge-32 =
    .label = Favoritler
    .value = Favoritler
browser-data-safari-32 =
    .label = Saife-imleri
    .value = Saife-imleri
browser-data-chrome-32 =
    .label = Saifeimleri
    .value = Saifeimleri
browser-data-canary-32 =
    .label = Saifeimleri
    .value = Saifeimleri
browser-data-360se-32 =
    .label = Saifeimleri
    .value = Saifeimleri
browser-data-ie-64 =
    .label = Diger veriler
    .value = Diger veriler
browser-data-edge-64 =
    .label = Diger Veriler
    .value = Diger Veriler
browser-data-safari-64 =
    .label = Diger veriler
    .value = Diger veriler
browser-data-chrome-64 =
    .label = Diger Veriler
    .value = Diger Veriler
browser-data-canary-64 =
    .label = Diger Veriler
    .value = Diger Veriler
browser-data-firefox-other-64 =
    .label = Diger veriler
    .value = Diger veriler
browser-data-360se-64 =
    .label = Diger Veriler
    .value = Diger Veriler
browser-data-firefox-128 =
    .label = Pencereler ve İlmekler
    .value = Pencereler ve İlmekler
