# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = Aç
    .accesskey = A
places-open-all-in-tabs =
    .label = Episini İlmeklerde Aç
    .accesskey = e
places-view =
    .label = Körünim
    .accesskey = K
places-by-date =
    .label = Tarihqa Köre
    .accesskey = T
places-by-site =
    .label = Saytqa Köre
    .accesskey = S
places-by-most-visited =
    .label = Eñ Büyük Ziyaret Sayısına Köre
    .accesskey = Z
places-by-last-visited =
    .label = Soñki Ziyaret Etilgenlerge Köre
    .accesskey = o
places-by-day-and-site =
    .label = Tarih ve Saytqa Köre
    .accesskey = v
places-history-search =
    .placeholder = Keçmişni qıdır
places-history =
    .aria-label = Keçmiş
places-bookmarks-search =
    .placeholder = Saife-imlerini qıdır
places-delete-domain-data =
    .label = Bu Sayt Aqqında Unut
    .accesskey = U
places-sortby-name =
    .label = İsim boyunca Sırala
    .accesskey = r
places-library =
    .title = Kitaphane
    .style = width:700px; height:531px;
places-organize-button =
    .label = Tertiple
    .tooltiptext = Saife-imleriñizni tertipleñiz
    .accesskey = T
places-organize-button-mac =
    .label = Tertiple
    .tooltiptext = Saife-imleriñizni tertipleñiz
places-file-close =
    .label = Qapat
    .accesskey = Q
places-cmd-close =
    .key = w
places-view-button =
    .label = Körünimler
    .tooltiptext = Körünimiñizni deñiştiriñiz
    .accesskey = K
places-view-button-mac =
    .label = Körünimler
    .tooltiptext = Körünimiñizni deñiştiriñiz
places-view-menu-columns =
    .label = Sutunlarnı Köster
    .accesskey = S
places-view-menu-sort =
    .label = Sırala
    .accesskey = S
places-view-sort-unsorted =
    .label = Sıralanmağan
    .accesskey = m
places-view-sort-ascending =
    .label = A > Z Sıralama Tertibi
    .accesskey = A
places-view-sort-descending =
    .label = Z > A Sıralama Tertibi
    .accesskey = Z
places-maintenance-button =
    .label = İtalât ve Yedekleme
    .tooltiptext = Saife-imleriñizni ital etiñiz ve yedekleñiz
    .accesskey = i
places-maintenance-button-mac =
    .label = İtalât ve Yedekleme
    .tooltiptext = Saife-imleriñizni ital etiñiz ve yedekleñiz
places-cmd-backup =
    .label = Yedekle…
    .accesskey = Y
places-cmd-restore =
    .label = Keri tikle
    .accesskey = K
places-cmd-restore-from-file =
    .label = Dosyeni Sayla…
    .accesskey = s
places-import-bookmarks-from-html =
    .label = Saife-imlerini HTML'den İtal Et…
    .accesskey = t
places-export-bookmarks-to-html =
    .label = Saife-imlerini HTML'ge İhrac Et…
    .accesskey = h
places-import-other-browser =
    .label = Başqa Bir Keziciden Verilerni İtal Et…
    .accesskey = B
places-view-sort-col-name =
    .label = İsim
places-view-sort-col-tags =
    .label = Nişanlar
places-view-sort-col-url =
    .label = Qonum
places-view-sort-col-most-recent-visit =
    .label = Soñki Ziyaret
places-view-sort-col-visit-count =
    .label = Ziyaret Sayısı
places-view-sort-col-date-added =
    .label = Eklengen
places-view-sort-col-last-modified =
    .label = Soñki Deñişiklik
places-cmd-find-key =
    .key = f
places-back-button =
    .tooltiptext = Keri bar
places-forward-button =
    .tooltiptext = İleri bar
places-details-pane-select-an-item-description = Hasiyetlerini körip tarir etmek içün bir unsur saylañız
