# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Пошук { $host }…
network-connection-status-connected = Сполучено з { $host }…
network-connection-status-sending-request = Надсилання запиту на { $host }…
network-connection-status-transferring-data = Передача даних з { $host }…
network-connection-status-connecting = З'єднання з { $host }…
network-connection-status-read = Прочитано { $host }
network-connection-status-wrote = Записано { $host }
network-connection-status-waiting = Очікування відповіді з { $host }…
network-connection-status-looked-up = Знайдено { $host }…
network-connection-status-tls-handshake = Виконання TLS рукостискання до { $host }…
network-connection-status-tls-handshake-finished = TLS рукостискання завершено для { $host }…
