# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

breakpointMenuItem.deleteSelf2.accesskey = R
breakpointMenuItem.deleteOthers2.accesskey = h
breakpointMenuItem.deleteAll2.accesskey = a
sourceTabs.closeTab.accesskey = c
sourceTabs.closeTab.key = CmdOrCtrl+W
sourceTabs.closeOtherTabs.accesskey = o
sourceTabs.closeTabsToEnd.accesskey = e
sourceTabs.closeAllTabs.accesskey = a
