# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host } కోసం చూస్తోంది…
network-connection-status-connected = { $host }కు అనుసంధానమయ్యింది…
network-connection-status-sending-request = { $host }కు అభ్యర్ధన పంపిస్తోంది…
network-connection-status-transferring-data = { $host } నుండి డేటా బదిలీ అవుతోంది…
network-connection-status-connecting = { $host }కు అనుసంధానమవుతోంది…
network-connection-status-read = { $host } చదువబడింది
network-connection-status-wrote = { $host } వ్రాయబడింది
network-connection-status-waiting = { $host } కొరకు వేచివుంది…
network-connection-status-looked-up = { $host } కోసం చూసాం…
