# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Tiempo excedido
openFile = Abrir archivo
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = Buscar “%2$S” en %1$S
contextMenuSearch.accesskey = B
contextMenuPrivateSearch = Buscar en ventana privada
contextMenuPrivateSearch.accesskey = h
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Buscar con %S en una ventana privada
contextMenuPrivateSearchOtherEngine.accesskey = h
bookmarkAllTabsDefault = [Nombre de la carpeta]
unsignedAddonsDisabled.message = Uno o más complementos instalados no pueden ser verificados y han sido deshabilitados.
unsignedAddonsDisabled.learnMore.label = Más información
unsignedAddonsDisabled.learnMore.accesskey = S
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Último acceso %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = enlaces %S://
crashedpluginsMessage.title = El plugin %S dejó de funcionar.
crashedpluginsMessage.reloadButton.label = Recargar la página
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = Enviar un reporte del fallo
crashedpluginsMessage.submitButton.accesskey = E
crashedpluginsMessage.learnMore = Más información…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = ¿Quizá querías ir a %S?
keywordURIFixup.goTo = Si, llévame a %S
keywordURIFixup.goTo.accesskey = Y
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Actualizar a %S
update.downloadAndInstallButton.accesskey = u
menuOpenAllInTabs.label = Abrir todo en pestañas
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Recargar esta página
tabHistory.goBack = Volver a esta página
tabHistory.goForward = Adelantar a esta página
# URL Bar
pasteAndGo.label = Pegar e ir
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Volver a cargar la página actual (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Detener la carga de esta página (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Restablecer el nivel de zoom (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Cambiar vista de lectura (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S %%, Restablecer nivel de zoom
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Mostrar tus marcadores (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Mostrar el progreso de las descargas en curso (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Abrir una nueva ventana (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Abrir una nueva pestaña (%S)
newTabContainer.tooltip = Abrir una nueva pestaña (%S)\nMantén presionado para abrir una nueva pestaña de contenedor
newTabAlwaysContainer.tooltip = Seleccionar contenedor para abrir una nueva pestaña
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = ¿Permitir que %S use tus datos de imagen de canvas HTML5?
canvas.siteprompt2.warning = Esto se puede utilizar para identificar a tu equipo de forma única.
canvas.block = Bloquear
canvas.block.accesskey = B
canvas.allow2 = Permitir
canvas.allow2.accesskey = P
canvas.remember2 = Recordar esta decisión
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Verificado por: %S
identity.identified.verified_by_you = Has agregado una excepción de seguridad para este sitio.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Certificado emitido a nombre de: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = No segura
identity.notSecure.tooltip = La conexión no es segura
identity.extension.label = Extensión (%S)
identity.extension.tooltip = Cargada por la extensión: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Reducir (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Restablecer el nivel de zoom (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Ampliar (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Cortar (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Copiar (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Pegar (%S)
geolocation.allow = Permitir
geolocation.allow.accesskey = P
geolocation.block = Bloquear
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Esto abrirá los ajustes de ubicación del sistema. Otorga permisos de ubicación a %S.
geolocation.shareWithSite4 = ¿Permitir a %S acceder a tu ubicación?
geolocation.shareWithFile4 = ¿Permitir a este archivo local acceder a tu ubicación?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = ¿Permitir que %1$S dé permiso a %2$S para acceder a tu ubicación?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = Otorgar permiso de ubicación a %S en los ajustes del sistema.
geolocation.systemSettingsTitle = Esperando permisos de ubicación
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = El sistema te pedirá que otorgues este permiso a %S.
geolocation.remember = Recordar esta decisión
# Virtual Reality Device UI
xr.allow2 = Permitir
xr.allow2.accesskey = P
xr.block = Bloquear
xr.block.accesskey = B
xr.shareWithSite4 = ¿Permitir que %S acceda a dispositivos de realidad virtual? Esto puede exponer información sensible.
xr.shareWithFile4 = ¿Permitir que este archivo local acceda a dispositivos de realidad virtual? Esto puede exponer información sensible.
xr.remember = Recordar esta decisión
# Persistent storage UI
persistentStorage.allow = Permitir
persistentStorage.allow.accesskey = A
persistentStorage.block.label = Bloquear
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = ¿Permitir que %S almacene datos en el almacenamiento persistente?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Permitir
webNotifications.allow2.accesskey = P
webNotifications.notNow = Ahora no
webNotifications.notNow.accesskey = n
webNotifications.never = No permitir nunca
webNotifications.never.accesskey = v
webNotifications.alwaysBlock = Bloquear siempre
webNotifications.alwaysBlock.accesskey = B
webNotifications.block = Bloquear
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = ¿Permitir a %S enviar notificaciones?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S quiere acceder a otras apps y servicios en este dispositivo.
localhost.remember2 = Recordar mi elección para este sitio
localhost.allowlabel = Permitir
localhost.blocklabel = Bloquear
localhost.allow.accesskey = A
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S quiere acceder a apps y servicios en dispositivos conectados a la red local.
localNetwork.remember2 = Recordar mi elección para este sitio
localNetwork.allowLabel = Permitir
localNetwork.allow.accesskey = A
localNetwork.blockLabel = Bloquear
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = ¡Sácame de aquí!
safebrowsing.getMeOutOfHereButton.accessKey = S
safebrowsing.deceptiveSite = ¡Sitio engañoso!
safebrowsing.notADeceptiveSiteButton.label = Este no es un sitio engañoso…
safebrowsing.notADeceptiveSiteButton.accessKey = e
safebrowsing.reportedAttackSite = ¡Este sitio web es peligroso!
safebrowsing.notAnAttackButton.label = Este no es un sitio de ataque…
safebrowsing.notAnAttackButton.accessKey = a
safebrowsing.reportedUnwantedSite = ¡Sitio reportado con software malicioso!
safebrowsing.reportedHarmfulSite = ¡Sitio peligroso reportado!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Buscar %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = ¿Reiniciar %S en modo de resolución de problemas?
troubleshootModeRestartPromptMessage = Tus extensiones, temas y ajustes personalizados se deshabilitarán temporalmente.
troubleshootModeRestartButton = Reiniciar
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Esta página está ralentizando %1$S. Para acelerar el navegador, detén esta página.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Una página web está ralentizando %1$S. Para acelerar tu navegador, detén esa página.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = "%1$S" está ralentizando %2$S. Para acelerar tu navegador, detén esa página.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = "%1$S" está ralentizando %2$S. Para acelerar tu navegador, detén esa extensión.
processHang.add-on.learn-more.text = Más información
processHang.button_stop2.label = Detener
processHang.button_stop2.accessKey = D
processHang.button_debug.label = Depurar el script
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Mostrar ventana en pantalla completa (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Mover la barra lateral a la izquierda
sidebar.moveToRight = Mover la barra lateral a la derecha
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Debes activar DRM para reproducir algún audio o video de esta página.
emeNotifications.drmContentDisabled.button.label = Habilitar DRM
emeNotifications.drmContentDisabled.button.accesskey = H
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S está instalando componentes necesarios para reproducir audio o video en esta página. Por favor, intenta de nuevo más tarde.
emeNotifications.unknownDRMSoftware = Desconocido
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = Personalizar %S
decoder.noCodecs.button = Aprende cómo
decoder.noCodecs.accesskey = L
decoder.noCodecsLinux.message = Para reproducir el video, puede ser necesario instalar los códecs de video requeridos.
decoder.noHWAcceleration.message = Para mejorar la calidad de video, puede ser necesario instalar el Media Feature Pack de Microsoft.
decoder.noPulseAudio.message = Para reproducir audio, necesitas instalar el software PulseAudio requerido.
decoder.unsupportedLibavcodec.message = libavcodec puede ser vulnerable o no está soportado y debería actualizarse para reproducir video.
decoder.decodeError.message = Ocurrió un error al decodificar una fuente mediática.
decoder.decodeError.button = Reportar un problema con el sitio
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = Ocurrió un error recuperable mientras se decodificaba una fuente mediática.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Debes acceder a esta red antes de que puedas ingresar a Internet.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Abrir página de inicio de sesión de la red
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Permisos para %S
permissions.remove.tooltip = Borrar este permiso y preguntar de nuevo
permissions.fullscreen.promptCanceled = Se cancelaron las solicitudes de permisos pendientes: las solicitudes de permisos no deben emitirse antes de entrar en DOM a pantalla completa.
permissions.fullscreen.fullScreenCanceled = Se salió de la pantalla completa DOM: no se deben emitir solicitudes de permiso mientras se está en pantalla completa DOM.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-bits
aboutDialog.architecture.thirtyTwoBit = 32-bits
midi.allow.label = Permitir
midi.allow.accesskey = P
midi.block.label = Bloquear
midi.block.accesskey = B
midi.remember = Recordar esta decisión
midi.shareWithFile = ¿Permitir que este archivo local acceda a tus dispositivos MIDI?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = ¿Permitir a %S acceder a tus dispositivos MIDI?
midi.shareSysexWithFile = ¿Permitir a este archivo local acceder a tus dispositivos MIDI y enviar/recibir mensajes SysEx?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = ¿Permitir a %S acceder a tus dispositivos MIDI y enviar/recibir mensajes SysEx?
serial.allow.label = Permitir
serial.allow.accesskey = A
serial.block.label = Bloquear
serial.block.accesskey = B
serial.shareWithFile = ¿Quieres permitir que este archivo local acceda a tus puertos serie?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = ¿Quieres permitir que %S acceda a tus puertos serie?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Atrás
storageAccess1.Allow.label = Permitir
storageAccess1.Allow.accesskey = A
storageAccess1.DontAllow.label = Bloquear
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = ¿Permitir que %1$S use sus cookies en %2$S?
storageAccess1.hintText = Puede que quieras bloquear el acceso si no está claro por qué %1$S necesita estos datos.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Buscar “%S” en internet
