# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loginsDescriptionAll2 = निम्नलिखित साइटों के लिए आपके कंप्यूटर पर लॉगिन जमा हैं
# LOCALIZATION NOTE (generatedPasswordWillBeSaved):
# %S will contain the brandShorterName. This informs the user that the generated password will be automatically saved.
generatedPasswordWillBeSaved = %S इस वेबसाइट के लिए इस पासवर्ड को सहेजेगा।
# LOCALIZATION NOTE (loginHostAge):
# This is used to show the context menu login items with their age.
# 1st string is the username for the login, 2nd is the login's age.
loginHostAge = %1$S (%2$S)
# LOCALIZATION NOTE (noUsername):
# String is used on the context menu when a login doesn't have a username.
noUsername = कोई उपयोक्तानाम नहीं
# LOCALIZATION NOTE (displaySameOrigin):
# String is used on the autocomplete row when the login origin is a domain match with the document origin
displaySameOrigin = इस साइट से
# LOCALIZATION NOTE (insecureFieldWarningDescription2):
# %1$S will contain insecureFieldWarningLearnMore and look like a link to indicate that clicking will open a tab with support information.
insecureFieldWarningDescription2 = यह संपर्क सुरक्षित नहीं है. यहाँ प्रविष्ट किये गये लॉगिन से समझौता किया जा सकता है. %1$S
insecureFieldWarningLearnMore = अधिक जानें
