# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Aşağıdaki amaçlarla “%S” sertifikasına güvenmek istiyor musunuz?
unnamedCA = Sertifika Makamı (isimsiz)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Lütfen bu sertifika yedeğini şifrelemek için kullanılan parolayı girin:
# Page Info
pageInfo_NoEncryption = Bağlantı şifrelenmiyor
pageInfo_Privacy_None1 = %S sitesi görüntülediğiniz sayfa için şifrelemeyi desteklemiyor.
pageInfo_Privacy_None2 = İnternet üzerinden şifrelenmeden gönderilen bilgiler aktarım sırasında başkaları tarafından görülebilir.\u0020
pageInfo_Privacy_None4 = Görüntülediğiniz sayfa internet üzerinden size aktarılmadan önce şifrelenmedi.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Bağlantı şifrelenmiş (%1$S, %2$S bit anahtarlar, %3$S)
pageInfo_BrokenEncryption = Kırılmış şifreleme (%1$S, %2$S bit anahtarlar, %3$S)
pageInfo_Privacy_Encrypted1 = Bu sayfa size ulaşmadan önce şifrelendi.
pageInfo_Privacy_Encrypted2 = Şifreleme, bilgisayarlar arasındaki bilgi alışverişinin yetkisi olmayan üçüncü kişilerce görülmesini zorlaştırır. Dolayısıyla açtığınız bu sayfanın ağ üzerinde dolaşırken birileri tarafından görülme olasılığı çok azdır.
pageInfo_MixedContent = Bağlantı kısmen şifrelenmiş
pageInfo_MixedContent2 = Görüntülediğiniz sayfanın bazı kısımları, internet üzerinden aktarılmadan önce şifrelenmemiş.
pageInfo_WeakCipher = Bu web sitesine bağlantınız zayıf şifreleme kullanıyor ve size özel değil. Başkaları bilgilerinizi görebilir veya web sitesinin davranışını değiştirebilir.
pageInfo_CertificateTransparency_Compliant = Bu web sitesi, Sertifika Şeffaflığı ilkesine uygundur.
# Token Manager
password_not_set = (ayarlanmadı)
