# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-sending-request = S'està enviant la sol·licitud a { $host }…
network-connection-status-transferring-data = S'estan transferint dades de { $host }…
network-connection-status-connecting = S'està connectant a { $host }…
network-connection-status-read = S'ha llegit { $host }
network-connection-status-wrote = S'ha escrit { $host }
network-connection-status-waiting = S'està esperant { $host }…
network-connection-status-looked-up = S'ha consultat { $host }…
network-connection-status-tls-handshake = S'està creant una connexió TLS amb { $host }…
network-connection-status-tls-handshake-finished = S'està finalitzant la connexió TLS amb { $host }…
