# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

report-broken-site-mainview-title = أبلِغ عن موقع معطوب
report-broken-site-panel-header =
    .label = أبلِغ عن موقع معطوب
    .title = أبلِغ عن موقع معطوب
report-broken-site-panel-intro-text = يساعدنا تقريرك في فهم وإصلاح المشكلات في { -brand-product-name } لجعلها أفضل للجميع.
report-broken-site-panel-learn-more-link = اطّلع على المزيد
report-broken-site-panel-intro = ساعد في جعل { -brand-product-name } أفضل للجميع. يستخدم { -vendor-short-name } المعلومات التي ترسلها لإصلاح مشكلات موقع الوِب.
report-broken-site-panel-url = المسار
report-broken-site-panel-reason-label = ما المتعطّل؟
report-broken-site-panel-reason-optional-label = ما المتعطّل؟ (اختياري)
report-broken-site-panel-reason-choose =
    .label = اختر سببًا
report-broken-site-panel-reason-load =
    .label = تعذّر تحميل الموقع
# These terms are referring to ecommerce websites
report-broken-site-panel-reason-checkout =
    .label = لا يمكنني الدفع أو إتمام عملية الشراء أو التسوق
report-broken-site-panel-reason-slow2 =
    .label = الموقع بطيء
report-broken-site-panel-reason-media2 =
    .label = تعذّر تشغيل الفيديو أو تحميله
report-broken-site-panel-reason-content2 =
    .label = محتوى مفقود
report-broken-site-panel-reason-account2 =
    .label = لا يمكنني الولوج أو التسجيل
report-broken-site-panel-reason-adblocker2 =
    .label = طلب الموقع إيقاف مانع الإعلانات
report-broken-site-panel-reason-notsupported =
    .label = المتصفح غير مدعوم أو حُظِر
report-broken-site-panel-reason-other =
    .label = شيء آخر
report-broken-site-panel-description-label = صِف المشكلة
report-broken-site-panel-description =
    .placeholder = ما الذي حدث؟ ما الذي كان ينبغي أن يحدث؟ هل ساعد إيقاف خاصية الحماية من التعقب؟
report-broken-site-panel-description-optional-label = صِف المشكلة (اختياري)
report-broken-site-panel-send-more-info-link = أرسل المزيد من المعلومات
report-broken-site-panel-button-cancel =
    .label = ألغِ
report-broken-site-panel-button-okay =
    .label = حسنًا
report-broken-site-panel-button-send =
    .label = أرسِل
report-broken-site-panel-report-sent-label = أُرسل بلاغك
report-broken-site-panel-report-sent-header =
    .label = أُرسل بلاغك
    .title = أُرسل بلاغك
report-broken-site-panel-report-sent-text = نشكرك على مساعدتك { -brand-product-name } في جعل الوِب أكثر انفتاحًا وسهولة في الوصول إليه وأفضل للجميع.
report-broken-site-panel-invalid-url-label = رجاء أدخل مسارًا سليمًا
report-broken-site-panel-missing-reason-label = الرجاء اختيار سبب
report-broken-site-panel-blocked-trackers-label =
    .label = إرسال روابط المواقع التي حظرتها خاصية الحماية من التعقب
report-broken-site-panel-blocked-trackers-description = قد تمنع خاصية الحماية من التعقب بعض الروابط السكريبتات التي تحتاجها بعض المواقع لتعمل بشكل صحيح.
report-broken-site-panel-preview-button =
    .label = عاين التقرير
report-broken-site-panel-preview-header =
    .label = عاين التقرير
