# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = Zeitüberschreitung
openFile = Datei öffnen
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = %1$S-Suche nach "%2$S"
contextMenuSearch.accesskey = S
contextMenuPrivateSearch = In privatem Fenster suchen
contextMenuPrivateSearch.accesskey = h
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = Mit %S in privatem Fenster suchen
contextMenuPrivateSearchOtherEngine.accesskey = h
bookmarkAllTabsDefault = [Ordnername]
unsignedAddonsDisabled.message = Ein oder mehrere Add-ons konnten nicht verifiziert werden und wurden deshalb deaktiviert.
unsignedAddonsDisabled.learnMore.label = Weitere Informationen
unsignedAddonsDisabled.learnMore.accesskey = W
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = Letzter Zugriff %S
# LOCALIZATION NOTE (openProtocolHandlerPermissionEntryLabel): %S is the scheme of the protocol the site may open an application for. For example: mailto
openProtocolHandlerPermissionEntryLabel = %S://-Links
crashedpluginsMessage.title = Das Plugin "%S" ist abgestürzt.
crashedpluginsMessage.reloadButton.label = Seite neu laden
crashedpluginsMessage.reloadButton.accesskey = S
crashedpluginsMessage.submitButton.label = Absturzbericht senden
crashedpluginsMessage.submitButton.accesskey = A
crashedpluginsMessage.learnMore = Weitere Informationen…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = Wollten Sie %S aufrufen?
keywordURIFixup.goTo = Ja, %S öffnen
keywordURIFixup.goTo.accesskey = J
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = Update auf Version %S durchführen
update.downloadAndInstallButton.accesskey = U
menuOpenAllInTabs.label = Alle in Tabs öffnen
# Unified Back-/Forward Popup
tabHistory.reloadCurrent = Diese Seite neu laden
tabHistory.goBack = Zurück zu dieser Seite
tabHistory.goForward = Vorwärts zu dieser Seite
# URL Bar
pasteAndGo.label = Einfügen & Los
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = Aktuelle Seite neu laden (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = Laden dieser Seite stoppen (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = Zoomfaktor zurücksetzen (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = Leseansicht umschalten (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# LOCALIZATION NOTE(zoom-button.aria-label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.aria-label = %S%%, Zoomfaktor zurücksetzen
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = Lesezeichen verwalten (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = Zeigt den Fortschritt der aktuellen Downloads an (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = Ein neues Fenster öffnen (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = Einen neuen Tab öffnen (%S)
newTabContainer.tooltip = Neuen Tab öffnen (%S)\nAnklicken und gedrückt halten, um Tab in einer Tab-Umgebung zu öffnen
newTabAlwaysContainer.tooltip = Tab-Umgebung für das Öffnen eines neuen Tabs wählen
# Canvas permission prompt
# LOCALIZATION NOTE (canvas.siteprompt2): %S is hostname
canvas.siteprompt2 = %S erlauben, Ihre HTML5-Canvas-Grafikdaten zu verwenden?
canvas.siteprompt2.warning = Dies wird eventuell dazu benutzt, um Ihren Computer im Internet zu identifizieren.
canvas.block = Blockieren
canvas.block.accesskey = B
canvas.allow2 = Erlauben
canvas.allow2.accesskey = E
canvas.remember2 = Entscheidung merken
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = Verifiziert von: %S
identity.identified.verified_by_you = Sie haben eine Sicherheitsausnahme für diese Website hinzugefügt.
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = Zertifikat ausgestellt für: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = Nicht sicher
identity.notSecure.tooltip = Verbindung ist nicht sicher
identity.extension.label = Erweiterung (%S)
identity.extension.tooltip = Geladen durch Erweiterung: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = Verkleinern (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = Zoomfaktor zurücksetzen (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = Vergrößern (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = Ausschneiden (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = Kopieren (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = Einfügen (%S)
geolocation.allow = Erlauben
geolocation.allow.accesskey = E
geolocation.block = Blockieren
geolocation.block.accesskey = B
# %S is replaced by the product name (e.g. Firefox)
geolocation.needsSystemSetting = Dies öffnet die Systemstandorteinstellungen. Bitte geben Sie %S die Standortberechtigung.
geolocation.shareWithSite4 = %S erlauben, auf Ihren Standort zuzugreifen?
geolocation.shareWithFile4 = Dieser lokalen Datei erlauben, auf Ihren Standort zuzugreifen?
# LOCALIZATION NOTE(geolocation.shareWithSiteUnsafeDelegation2):
# %1$S is the first party origin, %2$S is the third party origin.
geolocation.shareWithSiteUnsafeDelegation2 = %1$S erlauben, die Berechtigung für den Zugriff auf Ihren Standort an %2$S weiterzugeben?
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemSettingsMessage = %S die Standortberechtigung in den Systemeinstellungen erlauben.
geolocation.systemSettingsTitle = Wartet auf Standortberechtigung
# %S is replaced by the product name (e.g. Firefox)
geolocation.systemWillRequestPermission = Das System wird Sie bitten, %S diese Berechtigung zu erteilen.
geolocation.remember = Entscheidung merken
# Virtual Reality Device UI
xr.allow2 = Erlauben
xr.allow2.accesskey = E
xr.block = Blockieren
xr.block.accesskey = B
xr.shareWithSite4 = %S erlauben, auf Ihre VR-Geräte (Virtuelle Realität) zuzugreifen? Dies könnte vertrauliche Informationen zugänglich machen.
xr.shareWithFile4 = Dieser lokalen Datei erlauben, auf Ihre VR-Geräte (Virtuelle Realität) zuzugreifen? Dies könnte vertrauliche Informationen zugänglich machen.
xr.remember = Diese Entscheidung merken
# Persistent storage UI
persistentStorage.allow = Erlauben
persistentStorage.allow.accesskey = E
persistentStorage.block.label = Blockieren
persistentStorage.block.accesskey = B
persistentStorage.allowWithSite2 = %S erlauben, Daten im dauerhaften Speicher zu speichern?
# Web notifications UI
# LOCALIZATION NOTE (alwaysBlock, block)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
webNotifications.allow2 = Erlauben
webNotifications.allow2.accesskey = E
webNotifications.notNow = Nicht jetzt
webNotifications.notNow.accesskey = z
webNotifications.never = Nie erlauben
webNotifications.never.accesskey = N
webNotifications.alwaysBlock = Immer blockieren
webNotifications.alwaysBlock.accesskey = b
webNotifications.block = Blockieren
webNotifications.block.accesskey = B
webNotifications.receiveFromSite3 = %S erlauben, Benachrichtigungen zu senden?
# loopback-network and local-network permission UI
# %S is replaced by the origin of the website
localhost.allowWithSite2 = %S will auf andere Apps und Dienste auf diesem Gerät zugreifen.
localhost.remember2 = Meine Entscheidung für diese Website merken
localhost.allowlabel = Erlauben
localhost.blocklabel = Blockieren
localhost.allow.accesskey = E
localhost.block.accesskey = B
# local-network permission UI
# %S is replaced by the origin of the website
localNetwork.allowWithSite2 = %S will auf Apps und Dienste auf Geräten zugreifen, die mit Ihrem lokalen Netzwerk verbunden sind.
localNetwork.remember2 = Meine Entscheidung für diese Website merken
localNetwork.allowLabel = Erlauben
localNetwork.allow.accesskey = E
localNetwork.blockLabel = Blockieren
localNetwork.block.accesskey = B
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = Diese Seite verlassen!
safebrowsing.getMeOutOfHereButton.accessKey = D
safebrowsing.deceptiveSite = Betrügerische Website!
safebrowsing.notADeceptiveSiteButton.label = Dies ist keine betrügerische Website…
safebrowsing.notADeceptiveSiteButton.accessKey = k
safebrowsing.reportedAttackSite = Als attackierend gemeldete Website!
safebrowsing.notAnAttackButton.label = Dies ist keine attackierende Website…
safebrowsing.notAnAttackButton.accessKey = k
safebrowsing.reportedUnwantedSite = Als Seite mit Downloads unerwünschter Software bekannt!
safebrowsing.reportedHarmfulSite = Als schädliche Website gemeldet!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = Suchen mit %S
# troubleshootModeRestart
# LOCALIZATION NOTE (troubleshootModeRestartPromptTitle): %S is the name of the product (e.g., Firefox)
troubleshootModeRestartPromptTitle = %S im Fehlerbehebungsmodus neu starten?
troubleshootModeRestartPromptMessage = Ihre Erweiterungen, Themes und Benutzereinstellungen werden temporär deaktiviert.
troubleshootModeRestartButton = Neu starten
# Process hang reporter
# LOCALIZATION NOTE (processHang.selected_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.selected_tab.label = Diese Seite verlangsamt %1$S. Halten Sie die Seite an, um den Browser zu beschleunigen.
# LOCALIZATION NOTE (processHang.nonspecific_tab.label): %1$S is the name of the product (e.g., Firefox)
processHang.nonspecific_tab.label = Eine Webseite verlangsamt %1$S. Halten Sie die Seite an, um den Browser zu beschleunigen.
# LOCALIZATION NOTE (processHang.specific_tab.label): %1$S is the title of the tab.
# %2$S is the name of the product (e.g., Firefox)
processHang.specific_tab.label = "%1$S" verlangsamt %2$S. Halten Sie die Seite an, um den Browser zu beschleunigen.
# LOCALIZATION NOTE (processHang.add-on.label2): %1$S is the name of the
# extension. %2$S is the name of the product (e.g., Firefox)
processHang.add-on.label2 = "%1$S" verlangsamt %2$S. Halten Sie die Erweiterung an, um den Browser zu beschleunigen.
processHang.add-on.learn-more.text = Weitere Informationen
processHang.button_stop2.label = Anhalten
processHang.button_stop2.accessKey = A
processHang.button_debug.label = Skript untersuchen
processHang.button_debug.accessKey = u
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = Fenster im Vollbildmodus anzeigen (%S)
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = Sidebar nach links verschieben
sidebar.moveToRight = Sidebar nach rechts verschieben
# LOCALIZATION NOTE(emeNotifications.drmContentDisabled.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S will be the 'learn more' link
emeNotifications.drmContentDisabled.message2 = Der DRM-Kopierschutz muss aktiviert werden, um einige Audio- oder Videoelemente auf dieser Seite wiederzugeben.
emeNotifications.drmContentDisabled.button.label = DRM-Kopierschutz aktivieren
emeNotifications.drmContentDisabled.button.accesskey = a
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S installiert zusätzliche Komponenten, welche für die Wiedergabe der Audio- oder Videodateien auf dieser Seite benötigt werden. Versuchen Sie es später erneut.
emeNotifications.unknownDRMSoftware = Unbekannt
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = %S anpassen
decoder.noCodecs.button = So wird's gemacht
decoder.noCodecs.accesskey = S
decoder.noCodecsLinux.message = Zur Wiedergabe des Videos müssen Sie eventuell die dafür notwendigen Video-Decoder installieren.
decoder.noHWAcceleration.message = Zur Verbesserung der Videoqualität müssen Sie eventuell den Media Feature Pack von Microsoft installieren.
decoder.noPulseAudio.message = Zur Audio-Wiedergabe müssen Sie die eventuell benötigte Software PulseAudio installieren.
decoder.unsupportedLibavcodec.message = libavcodec sollte aktualisiert werden, um Videos wiederzugeben, da es gegen Angriffe verwundbar sein könnte oder die installierte Version nicht unterstützt wird.
decoder.decodeError.message = Beim Dekodieren einer Medien-Ressource trat ein Fehler auf.
decoder.decodeError.button = Seitenproblem melden
decoder.decodeError.accesskey = m
decoder.decodeWarning.message = Beim Dekodieren einer Medien-Ressource trat ein behebbarer Fehler auf.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = Sie müssen sich bei dem Netzwerk anmelden, um auf das Internet zugreifen zu können.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = Anmeldeseite des Netzwerks öffnen
# LOCALIZATION NOTE (permissions.header):
# %S is the hostname of the site that is being displayed.
permissions.header = Berechtigungen für %S
permissions.remove.tooltip = Diese Berechtigung löschen und erneut fragen
permissions.fullscreen.promptCanceled = Anfrage für Berechtigung zurückgezogen, da Anfragen nicht vor dem Aufruf des DOM-Vollbildmodus gestartet werden sollen.
permissions.fullscreen.fullScreenCanceled = DOM-Vollbildmodus beendet: Anfrage für Berechtigung wurde während des DOM-Vollbildmodus gestartet.
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-Bit
aboutDialog.architecture.thirtyTwoBit = 32-Bit
midi.allow.label = Erlauben
midi.allow.accesskey = E
midi.block.label = Blockieren
midi.block.accesskey = B
midi.remember = Entscheidung merken
midi.shareWithFile = Dieser lokalen Datei erlauben, auf die MIDI-Geräte zuzugreifen?
# LOCALIZATION NOTE (midi.shareWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareWithSite = %S erlauben, auf die MIDI-Geräte zuzugreifen?
midi.shareSysexWithFile = Dieser lokalen Datei erlauben, auf die MIDI-Geräte zuzugreifen und SysEx-Nachrichten zu empfangen und versenden?
# LOCALIZATION NOTE (midi.shareSysexWithSite): %S is the name of the site URL (https://...) requesting MIDI access
midi.shareSysexWithSite = %S erlauben, auf die MIDI-Geräte zuzugreifen und SysEx-Nachrichten zu empfangen und versenden?
serial.allow.label = Erlauben
serial.allow.accesskey = E
serial.block.label = Blockieren
serial.block.accesskey = B
serial.shareWithFile = Dieser lokalen Datei erlauben, auf die seriellen Ports zuzugreifen?
# LOCALIZATION NOTE (serial.shareWithSite): %S is the name of the site URL (https://...) requesting serial access
serial.shareWithSite = %S erlauben, auf die seriellen Ports zuzugreifen?
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = Zurück
storageAccess1.Allow.label = Erlauben
storageAccess1.Allow.accesskey = E
storageAccess1.DontAllow.label = Blockieren
storageAccess1.DontAllow.accesskey = B
# LOCALIZATION NOTE (storageAccess4.message, storageAccess1.hintText):
# %1$S is the name of the site URL (www.site1.example) trying to track the user's activity.
# %2$S is the name of the site URL (www.site2.example) that the user is visiting.  This is the same domain name displayed in the address bar.
storageAccess4.message = %1$S erlauben, seine Cookies auf %2$S zu verwenden?
storageAccess1.hintText = Möglicherweise möchten Sie den Zugriff blockieren, wenn nicht klar ist, warum %1$S diese Daten benötigt.
# LOCALIZATION NOTE (gnomeSearchProviderSearchWeb):
# Used for search by Gnome Shell activity screen, %S is a searched string.
gnomeSearchProviderSearchWeb = Das Web nach "%S" durchsuchen
