# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

openpgp-key-user-id-label = 帳號 / 使用者 ID
openpgp-keygen-title-label =
    .title = 產生 OpenPGP 金鑰
openpgp-cancel-key =
    .label = 取消
    .tooltiptext = 取消金鑰產生
openpgp-key-gen-expiry-title =
    .label = 金鑰到期日
openpgp-key-gen-expire-label = 金鑰過期時間
openpgp-key-gen-days-label =
    .label = 天
openpgp-key-gen-months-label =
    .label = 月
openpgp-key-gen-years-label =
    .label = 年
openpgp-key-gen-no-expiry-label =
    .label = 金鑰永不過期
openpgp-key-gen-key-size-label = 金鑰大小
openpgp-key-gen-console-label = 金鑰產生方式
openpgp-key-gen-key-type-label = 金鑰類型
openpgp-key-gen-key-type-rsa =
    .label = RSA
openpgp-key-gen-key-type-ecc =
    .label = ECC（橢圓曲線）
openpgp-generate-key =
    .label = 產生金鑰
    .tooltiptext = 產生一把新的 OpenPGP 相容金鑰，進行加密與/或簽章
openpgp-advanced-prefs-button-label =
    .label = 進階…
openpgp-keygen-desc = <a data-l10n-name="openpgp-keygen-desc-link">註: 可能需要花上幾分鐘金鑰才能產生完成。</a>金鑰產生過程中，請不要關閉應用程式。持續上網，或進行需要頻繁讀寫磁碟的動作，可重新補充「隨機程度池」以加速金鑰產生。完成後將提示您金鑰已經產生。
openpgp-key-expiry-label =
    .label = 到期日
openpgp-key-id-label =
    .label = 金鑰 ID
openpgp-key-man-title =
    .title = OpenPGP 金鑰管理員
openpgp-key-man-generate =
    .label = 產生新金鑰對
    .accesskey = K
openpgp-key-man-gen-revoke =
    .label = 撤銷憑證
    .accesskey = R
openpgp-key-man-ctx-gen-revoke-label =
    .label = 產生並儲存撤銷憑證
openpgp-key-man-file-menu =
    .label = 檔案
    .accesskey = F
openpgp-key-man-edit-menu =
    .label = 編輯
    .accesskey = E
openpgp-key-man-view-menu =
    .label = 檢視
    .accesskey = V
openpgp-key-man-generate-menu =
    .label = 產生
    .accesskey = G
openpgp-key-man-keyserver-menu =
    .label = 金鑰伺服器
    .accesskey = K
openpgp-key-man-import-public-from-file =
    .label = 從檔案匯入公鑰
    .accesskey = I
openpgp-key-man-import-secret-from-file =
    .label = 從檔案匯入私鑰
openpgp-key-man-import-sig-from-file =
    .label = 從檔案匯入憑證撤銷資訊
openpgp-key-man-import-from-clipbrd =
    .label = 從剪貼簿匯入金鑰
    .accesskey = I
openpgp-key-man-import-from-url =
    .label = 從網址匯入金鑰
    .accesskey = U
openpgp-key-man-export-to-file =
    .label = 將公鑰匯出成檔案
    .accesskey = E
openpgp-key-man-send-keys =
    .label = 用郵件寄出公鑰
    .accesskey = S
openpgp-key-man-backup-secret-keys =
    .label = 備份私鑰到檔案
    .accesskey = B
openpgp-key-man-discover-cmd =
    .label = 在網路上尋找金鑰
    .accesskey = D
openpgp-key-man-discover-progress = 搜尋中…
openpgp-key-copy-key =
    .label = 複製公鑰
    .accesskey = C
openpgp-key-export-key =
    .label = 將公鑰匯出成檔案
    .accesskey = E
openpgp-key-backup-key =
    .label = 備份私鑰到檔案
    .accesskey = B
openpgp-key-send-key =
    .label = 用郵件寄出公鑰
    .accesskey = S
openpgp-key-man-copy-to-clipbrd =
    .label = 複製公鑰到剪貼簿
    .accesskey = C
openpgp-key-man-ctx-expor-to-file-label =
    .label = 將金鑰匯出成檔案
openpgp-key-man-ctx-copy-to-clipbrd-label =
    .label = 複製公鑰到剪貼簿
openpgp-key-man-close =
    .label = 關閉
openpgp-key-man-reload =
    .label = 重新載入金鑰快取
    .accesskey = R
openpgp-key-man-change-expiry =
    .label = 更改到期日
    .accesskey = E
openpgp-key-man-del-key =
    .label = 刪除金鑰
    .accesskey = D
openpgp-delete-key =
    .label = 刪除金鑰
    .accesskey = D
openpgp-key-man-revoke-key =
    .label = 撤銷金鑰
    .accesskey = R
openpgp-key-man-key-props =
    .label = 金鑰屬性
    .accesskey = K
openpgp-key-man-key-more =
    .label = 更多
    .accesskey = M
openpgp-key-man-view-photo =
    .label = 大頭照
    .accesskey = P
openpgp-key-man-ctx-view-photo-label =
    .label = 檢視大頭照
openpgp-key-man-show-invalid-keys =
    .label = 顯示無效的金鑰
    .accesskey = D
openpgp-key-man-show-others-keys =
    .label = 顯示來自其他人的金鑰
    .accesskey = O
openpgp-key-man-user-id-label =
    .label = 名稱
openpgp-key-man-fingerprint-label =
    .label = 指紋
openpgp-key-man-select-all =
    .label = 選擇所有金鑰
    .accesskey = A
openpgp-key-man-filter-label =
    .placeholder = 搜尋金鑰
openpgp-key-man-select-all-key =
    .key = A
openpgp-key-man-key-details-key =
    .key = I
openpgp-key-details-title =
    .title = 金鑰屬性
openpgp-key-details-signatures-tab =
    .label = 憑證
openpgp-key-details-structure-tab =
    .label = 結構
openpgp-key-details-uid-certified-col =
    .label = 使用者 ID / 認證者
openpgp-key-details-user-id2-label = 聲稱的金鑰擁有者
openpgp-key-details-id-label =
    .label = ID
openpgp-key-details-key-type-label = 類型
openpgp-key-details-key-part-label =
    .label = 金鑰部分
openpgp-key-details-algorithm-label =
    .label = 演算法
openpgp-key-details-size-label =
    .label = 大小
openpgp-key-details-created-label =
    .label = 建立於
openpgp-key-details-created-header = 建立於
openpgp-key-details-expiry-label =
    .label = 到期日
openpgp-key-details-expiry-header = 到期日
openpgp-key-details-usage-label =
    .label = 用途
openpgp-key-details-fingerprint-label = 指紋
openpgp-key-details-sel-action =
    .label = 選擇操作…
    .accesskey = S
openpgp-key-details-also-known-label = 金鑰擁有者聲稱的其他身分:
openpgp-card-details-close-window-label =
    .buttonlabelaccept = 關閉
openpgp-acceptance-label =
    .label = 您是否要接受
openpgp-acceptance-rejected-label =
    .label = 不接受，拒絕此金鑰。
openpgp-acceptance-undecided-label =
    .label = 還沒有決定，之後再說。
openpgp-acceptance-unverified-label =
    .label = 接受，但我還沒有確認過是否為正確金鑰。
openpgp-acceptance-verified-label =
    .label = 接受，我已經確認過金鑰指紋正確。
key-personal-warning = 您是否自行建立了這把金鑰，而且顯示的擁有者資訊也是您自己？
openpgp-personal-no-label =
    .label = 否，不要把這把金鑰當成我的個人金鑰。
openpgp-personal-yes-label =
    .label = 是，請把這把金鑰當成我的個人金鑰。
openpgp-copy-cmd-label =
    .label = 複製

## e2e encryption settings

#   $count (Number) - the number of configured keys associated with the current identity
#   $key (String) - the currently selected OpenPGP key
openpgp-selection-status =
    { $count ->
        [0] 請選擇一把有效的金鑰以開啟 OpenPGP 通訊協定。
       *[other] 您目前設定使用 ID 為 <b>{ $key }</b> 的金鑰
    }
openpgp-add-key-button =
    .label = 新增金鑰…
    .accesskey = A
e2e-learn-more = 了解更多
openpgp-keygen-success = 成功建立 OpenPGP 金鑰！
openpgp-keygen-import-success = 成功匯入 OpenPGP 金鑰！
openpgp-keygen-external-success = 已儲存外部 GnuPG 金鑰 ID！

## OpenPGP Key selection area

openpgp-radio-none =
    .label = 無
openpgp-radio-none-desc = 不要為此身份使用 OpenPGP。
#   $key (String) - the expiration date of the OpenPGP key
openpgp-radio-key-expires = 到期於: { $date }
openpgp-key-expires-image =
    .tooltiptext = 金鑰將於 6 個月內到期
#   $key (String) - the expiration date of the OpenPGP key
openpgp-radio-key-expired = 過期於: { $date }
openpgp-key-expired-image =
    .tooltiptext = 金鑰已過期
openpgp-key-expand-section =
    .tooltiptext = 更多資訊
openpgp-key-revoke-title = 撤銷金鑰
openpgp-key-edit-title = 更改 OpenPGP 金鑰
openpgp-key-edit-date-title = 延後到期日
openpgp-manager-button =
    .label = OpenPGP 金鑰管理員
    .accesskey = K
openpgp-key-remove-external =
    .label = 移除外部金鑰 ID
    .accesskey = E
key-external-label = 外部 GnuPG 金鑰
# Strings in keyDetailsDlg.xhtml
key-type-public = 公鑰
key-type-primary = 主要金鑰
key-type-subkey = 子金鑰
key-type-pair = 金鑰對（私鑰與公鑰）
key-expiry-never = 永不
key-usage-encrypt = 加密
key-usage-sign = 簽署
key-usage-certify = 認證
key-usage-authentication = 驗證
key-does-not-expire = 金鑰永不過期
key-expired-date = 金鑰已於 { $keyExpiry } 過期
key-expired-simple = 金鑰已經過期
key-revoked-simple = 金鑰已被撤銷
# Strings in keyserver.jsm
keyserver-error-aborted = 已中斷

## Account settings export output

import-rev-file = 匯入 OpenPGP 撤銷檔案
# Strings used in enigmailKeygen.js
save-revoke-cert-as = 建立並儲存撤銷憑證
revoke-cert-failed = 無法建立撤銷憑證。
