#filter emptyLines

#define MOZ_LANGPACK_CREATOR Aviary.pl

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.

#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Piotr Komoda</em:contributor> <em:contributor>Zbigniew Braniecki</em:contributor> <em:contributor>Marek Wawoczny</em:contributor> <em:contributor>Piotr Bartecki</em:contributor> <em:contributor>Stefan Plewako</em:contributor>

#unfilter emptyLines
