# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Buka ku { $host }…
network-connection-status-connected = Kuchumene ku { $host }…
network-connection-status-sending-request = Tfumela sicelo ku { $host }…
network-connection-status-transferring-data = Dlulisela lwati ku{ $host }…
network-connection-status-connecting = Kuchumana ku { $host }…
network-connection-status-wrote = Ubhale { $host }
network-connection-status-waiting = Umele { $host }…
