# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Vistaðar innskráningar
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Afrita URL
    .accesskey = y
launch-site-url-cmd =
    .label = Heimsækja URL
    .accesskey = H
copy-username-cmd =
    .label = Afrita notandanafn
    .accesskey = A
edit-username-cmd =
    .label = Breyta notandanafni
    .accesskey = d
copy-password-cmd =
    .label = Afrita lykilorð
    .accesskey = A
edit-password-cmd =
    .label = Breyta lykilorði
    .accesskey = e
search-filter =
    .accesskey = e
    .placeholder = Leita
column-heading-site =
    .label = Vefsvæði
column-heading-username =
    .label = Notandanafn
column-heading-password =
    .label = Lykilorð
column-heading-time-created =
    .label = Fyrst notað
column-heading-time-last-used =
    .label = Síðast notað
column-heading-time-password-changed =
    .label = Seinast breytt
column-heading-times-used =
    .label = Oft notað
remove =
    .label = Fjarlægja
    .accesskey = r
import =
    .label = Import…
    .accesskey = I
close-button =
    .label = Loka
    .accesskey = L
show-passwords =
    .label = Sýna lykilorð
    .accesskey = ð
hide-passwords =
    .label = Fela lykilorð
    .accesskey = ð
logins-description-all = Innskráningar fyrir eftirfarandi vefsvæði eru geymd á tölvunni
logins-description-filtered = Eftirfarandi innskráningar passa við leitina:
remove-all =
    .label = Fjarlægja allt
    .accesskey = a
remove-all-shown =
    .label = Fjarlægja allt sem er sýnilegt
    .accesskey = a
remove-all-passwords-prompt = Ertu viss um að þú viljir eyða öllum lykilorðum?
remove-all-passwords-title = Fjarlægja öll lykilorð
no-master-password-prompt = Ertu viss um að viljir sýna lykilorðin þín?
auto-fill-logins-and-passwords =
    .label = Sjálfvirk útfylling fyrir innskráningar og lykilorð
