# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loginsDescriptionAll2 = အောက်ပါ ဝက်ဆိုက်များ အတွင်း ဝင်ရောက်ထားသော စကားဝှက်များ
# LOCALIZATION NOTE (loginHostAge):
# This is used to show the context menu login items with their age.
# 1st string is the username for the login, 2nd is the login's age.
loginHostAge = %1$S (%2$S)
# LOCALIZATION NOTE (noUsername):
# String is used on the context menu when a login doesn't have a username.
noUsername = အသုံးပြုသူအမည် မပေးထားပါ
# LOCALIZATION NOTE (insecureFieldWarningDescription2):
# %1$S will contain insecureFieldWarningLearnMore and look like a link to indicate that clicking will open a tab with support information.
insecureFieldWarningDescription2 = ယခုချိတ်ဆက်မှုသည် လုံခြုံမှုမရှိပါ။ ယခုနေရာတွင် ဝင်ရောက်သည့် မှတ်တမ်းများသည် ထိခိုက်ခံရနိုင်ဖွယ် ရှိနိုင်သည်။ %1$S
insecureFieldWarningLearnMore = ပိုမိုလေ့လာရန်
