# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=$ProductName$ Instalazioa
Welcome_MessageWelcome=Ongietorri %s-ra!
Welcome_Message0=%s $Version$ instalatzera zoaz.
Welcome_Message1=Gomendagarria da instalazioa abiarazi aurretik windows programa guztiak ixtea.
Welcome_Message2=Utzi klikatu instalazioa uzteko eta orduan abiarazirik dituzun programa guztiak itxi. Hurrengoa 
klikatu Instalazio programarekin aurrera jarraitzeko
Welcome_Message3=Hurrengoa klikatu %s $Version$ instalatzen jarraitzeko.

License_Title=Software Lizentzi Onarpena
License_SubTitle=Software hau erabiltzeko era eta baldintzak.
License_Message0=Mesedez irakurri hurrengo lizentzi onarpena. Kontratuaren amaiera ikusteko korritze barra erabili.
License_Accept= Lizentzi onarpenaren baldintzak &Onartzen ditu
License_Decline=EZ du&t lizentzi onarpenaren baldintzak onartzen

Type_Title=Instalazio Mota
Type_SubTitle=Hautatu instalazio aukerak.
Type_Message0=Hautatu erabili nahi duzun instalazio mota, gero Hurrengoa klikatu.

Standard_Short=E&standarra
Standard_Long=Thunderbird osagai arruntenekin instalatuko da.

Custom_Short=&Pertsonalizatu
Custom_Long=Instalatuko dituzun osagaiak hautatu. Erabiltzaile aurreratuentzat gomendaturik.

Select_Title=Osagaiak AukeratuSelect Components
Select_SubTitle=$ProductName$ osatu dezaketen osagai gehigarriak.
Select_Message0=Hautatu instalatu nahi dituzun osagai gehigarriak, gero Hurrengoa klikatu.

Path_Title=Instalazio Karpeta
Path_SubTitle=$ProductName$ instalatuko den lekua.
Path_Message0=$ProductName$ hurrengo karpeta honetan instalatuko da:

Integration_Title=Laster-markak ezarri
Integration_SubTitle=Programa Ikonoak Sortu
Integration_Message0=$ProductShortName$:-rentzat ikonoa sortu

Integration_Desktop=Nire idazmahaiean
Integration_StartMenu=Nire HAsiera Menuko Programa karpetan
Integration_QuickLaunch=Nire abiarazte azkar barran

SelectFolder_Title=$ProductName$ Instalazioa - Programa karpeta aukeratu
SelectFolder_Message0=Instalazioa beheko Programa Karpetan programa ikonoak gehituko ditu. karpeta izen bat idatzi edo daudenetariko bat hautatu. Hurrengoa klikatu jarraitzeko.

Advanced_Title=$ProductName$ Instalazioa - Ezarpena Aurreratuak
Advanced_Message0=Zure internet konexioak proxy zerbitzari bat erabiltzen badu, idatzi zerbitzari izen eta ataka zenbakia. Zure internet konexioak ez badu proxy-rik erabiltzen hutsi utz ezazu.

Install_Title=Laburpena
Install_SubTitle=Prest $ProductName$ instalatzen hasteko.
Install_MessageInstall=Instalazioak hurrengo osagaiak instalatuko ditu:
Install_MessageDownload=Instalazioak hurrengo osagaiak deskargatu eta instalatuko ditu:
Install_Message0=Hurrengoa klikatu aurrera jarraitzeko.

Downloading_Title=Deskargatzen
Downloading_SubTitle=Beharrezko osagaiak deskargatzen...
Downloading_Blurb=Instalazioa $ProductName$ instalatzeko beharrezkoak diren osagaiak deskargatzen ari da.
Downloading_FileName=Orain deskargatzen:
Downloading_Time=Falta de denbora:

Installing_Title=Instalatzen
Installing_SubTitle=$ProductName$ instalatzen...
Installing_Blurb=Instalazioa aplikazio fitxategiak instalatzen ari da. 
Installing_Status=Fitxategia prestatzen:
Installing_Component=Orain instalatzen:

Success_Title=Instalazioa buruturik
Success_Header=Instalazioa buruturik
Success_Message0=%s $Version$ arrakastatsuki instalatu da.
Success_Message1=Amaiatu klikatu instalazioa osatzeko. 
Success_Launch=%s $Version$ orain abiarazi.

Check_Message=$ProductName$ deskarga osatu da. $ProductNameInternal$ itxi egin behar da instalazioarekin aurrera jarraitzeko. Ados klikatu $ProductNameInternal$ automatikoki itxi eta instalazioa abiarazteko.
Check_FullMessage=$ProductNameInternal$ itxi egin behar da instalazioarekin aurrera jarraitzeko. Ados klikatu $ProductNameInternal$ automatikoki itxi eta instalazioa abiarazteko.
Check_Wait=ProductNameInternal$ ixten. Itxaron mesedez...

Component_XPCOM=Plataforma anitzeko COM
Component_Mail=$ProductName$
Component_Offline=Lineaz-kanpo onarpena
Component_Offline_Long=$ProductName$ ePosta-ri lineaz-kanpo lan egiteko gaitasuna gehitzen dio.
Component_RSS=RSS Onarpena
Component_RSS_Long=$ProductName$-ei RSS onarpena gehitu.
Component_QFA=Kalitate berrelikadura agentea
Component_QFA_Long=$ProductName$ apurtze informazio hedatuarentzat.
