# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Opslaan
dialogTitleAddBookmark = Nieuwe bladwijzer
dialogTitleAddMulti = Nieuwe bladwijzers
dialogTitleEdit = Eigenschappen van ‘%S’
dialogTitleAddNewBookmark2 = Bladwijzer toevoegen
dialogTitleEditBookmark = ‘%S’ bewerken
dialogTitleEditBookmark2 = Bladwijzer bewerken
dialogTitleAddBookmarkFolder = Bladwijzermap toevoegen
dialogTitleEditBookmarkFolder = Bladwijzermap bewerken
bookmarkAllTabsDefault = [Mapnaam]
newFolderDefault = Nieuwe map
newBookmarkDefault = Nieuwe bladwijzer
