# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host } ᱪᱮᱛᱟᱱ ᱨᱮ ᱧᱮᱞᱮᱫᱼᱟ…
network-connection-status-connected = { $host } ᱨᱮ ᱡᱚᱲᱟᱣ ᱟᱠᱟᱱᱟ…
network-connection-status-sending-request = { $host } ᱯᱟᱲᱦᱟᱣ
network-connection-status-transferring-data = { $host } ᱠᱷᱚᱱ ᱰᱟᱴᱟ ᱩᱪᱟᱹᱲᱚᱜᱼᱟ…
network-connection-status-connecting = { $host } ᱡᱚᱲᱟᱣ ᱮᱫᱼᱟ…
network-connection-status-read = { $host } ᱯᱟᱲᱦᱟᱣ
network-connection-status-wrote = { $host } ᱚᱞ ᱟᱠᱟᱱᱟ
network-connection-status-waiting = { $host } ᱞᱟᱹᱜᱤᱫ ᱧᱮᱞᱮᱫᱼᱟ…
network-connection-status-looked-up = { $host } ᱧᱮᱞ ᱠᱮᱫᱼᱟ…
network-connection-status-tls-handshake = { $host } ᱛᱮ TLS ᱛᱤᱢᱮᱲᱟᱣ ᱠᱚᱨᱟᱣᱜ ᱠᱟᱱᱟ …
network-connection-status-tls-handshake-finished = { $host } ᱞᱟᱹᱜᱤᱫ TLS ᱛᱤᱢᱮᱲᱟᱣ ᱯᱩᱨᱟᱹᱣ ᱮᱱᱟ …
