# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

e2e-intro-description = Per inviare messaggi crittati o con firma digitale, configurare una tecnologia di crittografia OpenPGP o S/MIME.
openpgp-key-user-id-label = Account/ID utente
openpgp-keygen-title-label =
    .title = Genera chiave OpenPGP
openpgp-cancel-key =
    .label = Annulla
    .tooltiptext = Annulla generazione della chiave
openpgp-key-gen-expiry-title =
    .label = Scadenza chiave
openpgp-key-gen-expire-label = La chiave scade in
openpgp-key-gen-days-label =
    .label = giorni
openpgp-key-gen-months-label =
    .label = mesi
openpgp-key-gen-years-label =
    .label = anni
openpgp-key-gen-no-expiry-label =
    .label = La chiave non ha scadenza
openpgp-key-gen-key-size-label = Dimensione chiave
openpgp-key-gen-console-label = Generazione chiave
openpgp-key-gen-key-type-label = Tipo di chiave
openpgp-key-gen-key-type-rsa =
    .label = RSA
openpgp-key-gen-key-type-ecc =
    .label = ECC (curva ellittica)
openpgp-generate-key =
    .label = Genera chiave
    .tooltiptext = Genera una nuova chiave OpenPGP adatta per crittografia e/o firma
openpgp-advanced-prefs-button-label =
    .label = Avanzate…
openpgp-key-expiry-label =
    .label = Scadenza
openpgp-key-id-label =
    .label = ID chiave
openpgp-cannot-change-expiry = Questa chiave ha una struttura complessa, la modifica della data di scadenza non è supportata.
openpgp-key-man-title =
    .title = Gestore delle chiavi OpenPGP
openpgp-key-man-gen-revoke =
    .label = Certificato di revoca
    .accesskey = r
openpgp-key-man-ctx-gen-revoke-label =
    .label = Genera e salva il certificato di revoca
openpgp-key-man-file-menu =
    .label = File
    .accesskey = F
openpgp-key-man-edit-menu =
    .label = Modifica
    .accesskey = M
openpgp-key-man-view-menu =
    .label = Visualizza
    .accesskey = V
openpgp-key-man-generate-menu =
    .label = Genera
    .accesskey = G
openpgp-key-man-import-public-from-file =
    .label = Importa chiavi pubbliche da file
    .accesskey = I
openpgp-key-man-import-secret-from-file =
    .label = Importa chiavi segrete da file
openpgp-key-man-import-sig-from-file =
    .label = Importa revoche da file
openpgp-key-man-import-from-clipbrd =
    .label = Importa chiavi dagli appunti
    .accesskey = a
openpgp-key-man-import-from-url =
    .label = Importa chiavi da URL
    .accesskey = U
openpgp-key-man-export-to-file =
    .label = Esporta chiavi pubbliche in un file
    .accesskey = u
openpgp-key-man-send-keys =
    .label = Invia chiavi pubbliche via email
    .accesskey = m
openpgp-key-man-backup-secret-keys =
    .label = Effettua backup delle chiavi segrete su file
    .accesskey = k
openpgp-key-man-discover-progress = Ricerca in corso…
openpgp-key-copy-key =
    .label = Copia chiave pubblica
    .accesskey = h
openpgp-key-export-key =
    .label = Esporta chiave pubblica in un file
    .accesskey = u
openpgp-key-backup-key =
    .label = Effettua backup della chiave segreta su file
    .accesskey = k
openpgp-key-send-key =
    .label = Invia chiave pubblica via email
    .accesskey = m
openpgp-key-man-copy-to-clipbrd =
    .label = Copia chiavi pubbliche negli appunti
    .accesskey = v
openpgp-key-man-ctx-expor-to-file-label =
    .label = Esporta chiavi su file
openpgp-key-man-ctx-copy-to-clipbrd-label =
    .label = Copia chiavi pubbliche negli appunti
openpgp-key-man-close =
    .label = Chiudi
openpgp-key-man-reload =
    .label = Ricarica cache delle chiavi
    .accesskey = R
openpgp-key-man-change-expiry =
    .label = Modifica la data di scadenza
    .accesskey = M
openpgp-key-man-del-key =
    .label = Elimina chiavi
    .accesskey = m
openpgp-delete-key =
    .label = Elimina chiave
    .accesskey = h
openpgp-key-man-revoke-key =
    .label = Revoca chiave
    .accesskey = R
openpgp-key-man-key-props =
    .label = Proprietà chiave
    .accesskey = P
openpgp-key-man-key-more =
    .label = Altro
    .accesskey = A
openpgp-key-man-show-invalid-keys =
    .label = Visualizza chiavi non valide
    .accesskey = V
openpgp-key-man-show-others-keys =
    .label = Visualizza chiavi di altre persone
    .accesskey = n
openpgp-key-man-user-id-label =
    .label = Nome
openpgp-key-man-fingerprint-label =
    .label = Impronta digitale
openpgp-key-man-select-all =
    .label = Seleziona tutte le chiavi
    .accesskey = u
openpgp-key-man-empty-tree-tooltip =
    .label = Inserisci i termini di ricerca nella casella qui sopra
openpgp-key-man-nothing-found-tooltip =
    .label = Nessuna chiave corrispondente ai termini di ricerca
openpgp-key-man-please-wait-tooltip =
    .label = Attendi il caricamento delle chiavi...
openpgp-key-man-select-all-key =
    .key = A
openpgp-key-man-key-details-key =
    .key = I
openpgp-key-details-title =
    .title = Proprietà chiave
openpgp-key-details-signatures-tab =
    .label = Certificazioni
openpgp-key-details-structure-tab =
    .label = Struttura
openpgp-key-details-uid-certified-col =
    .label = ID utente/Certificato da
openpgp-key-details-user-id2-label = Presunto proprietario della chiave
openpgp-key-details-id-label =
    .label = ID
openpgp-key-details-key-type-label = Tipo
openpgp-key-details-algorithm-label =
    .label = Algoritmo
openpgp-key-details-size-label =
    .label = Dimensione
openpgp-key-details-expiry-label =
    .label = Scadenza
openpgp-key-details-expiry-header = Scadenza
openpgp-key-details-fingerprint-label = Impronta digitale
openpgp-card-details-close-window-label =
    .buttonlabelaccept = Chiudi
openpgp-copy-cmd-label =
    .label = Copia

## e2e encryption settings

e2e-learn-more = Ulteriori informazioni
openpgp-keygen-success = Chiave OpenPGP creata correttamente.
openpgp-keygen-import-success = Le chiavi OpenPGP sono state importate correttamente.

## OpenPGP Key selection area


## Account settings export output

# Strings used in trust.jsm
key-valid-unknown = sconosciuta
key-valid-invalid = non valida
key-valid-disabled = disattivata
key-valid-revoked = revocata
