# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

e2e-intro-description = Untuk mengirim pesan terenkripsi atau bertanda tangan digital, Anda perlu mengkonfigurasi teknologi enkripsi, baik OpenPGP maupun S/MIME.
e2e-intro-description-more = Pilih kunci pribadi Anda untuk mengaktifkan penggunaan OpenPGP, atau sertifikat pribadi Anda untuk mengaktifkan penggunaan S/MIME. Untuk kunci pribadi atau sertifikat, Anda memiliki kunci rahasia yang sesuai.
openpgp-key-user-id-label = Akun / ID Pengguna
openpgp-keygen-title-label =
    .title = Hasilkan Kunci OpenPGP
openpgp-cancel-key =
    .label = Batalkan
    .tooltiptext = Batalkan Pembuatan Kunci
openpgp-key-gen-expiry-title =
    .label = Kedaluwarsa kunci
openpgp-key-gen-expire-label = Kunci kedaluwarsa dalam
openpgp-key-gen-days-label =
    .label = hari
openpgp-key-gen-months-label =
    .label = bulan
openpgp-key-gen-years-label =
    .label = tahun
openpgp-key-gen-no-expiry-label =
    .label = Kunci tidak kedaluwarsa
openpgp-key-gen-key-size-label = Ukuran kunci
openpgp-key-gen-console-label = Pembuatan Kunci
openpgp-key-gen-key-type-label = Jenis kunci
openpgp-key-gen-key-type-rsa =
    .label = RSA
openpgp-key-gen-key-type-ecc =
    .label = ECC (Kurva Eliptik)
openpgp-generate-key =
    .label = Hasilkan kunci
    .tooltiptext = Membuat sebuah kunci kepatuhan OpenPGP baru untuk enkripsi dan atau penandatanganan
openpgp-advanced-prefs-button-label =
    .label = Canggih…
openpgp-keygen-desc = <a data-l10n-name="openpgp-keygen-desc-link">CATATAN: Pembuatan kunci mungkin membutuhkan waktu hingga beberapa menit untuk menyelesaikannya.</a> Jangan keluar dari aplikasi saat pembuatan kunci sedang berlangsung. Menjelajah secara aktif atau melakukan operasi intensif disk selama pembuatan kunci akan mengisi kembali 'kumpulan keacakan' dan mempercepat proses. Anda akan diberi tahu saat pembuatan kunci selesai.
openpgp-key-expiry-label =
    .label = Kedaluwarsa
openpgp-key-id-label =
    .label = ID Kunci
openpgp-cannot-change-expiry = Ini adalah kunci dengan struktur yang kompleks, mengubah tanggal kedaluwarsa tidak didukung.
openpgp-key-man-title =
    .title = Manajer Kunci OpenPGP
openpgp-key-man-generate =
    .label = Pasangan Kunci Baru
    .accesskey = K
openpgp-key-man-gen-revoke =
    .label = Sertifikat Pencabutan
    .accesskey = R
openpgp-key-man-ctx-gen-revoke-label =
    .label = Hasilkan & Simpan Sertifikat Pencabutan
openpgp-key-man-file-menu =
    .label = File
    .accesskey = F
openpgp-key-man-edit-menu =
    .label = Sunting
    .accesskey = E
openpgp-key-man-view-menu =
    .label = Tampilkan
    .accesskey = V
openpgp-key-man-generate-menu =
    .label = Menghasilkan
    .accesskey = G
openpgp-key-man-keyserver-menu =
    .label = Keyserver
    .accesskey = K
openpgp-key-man-import-public-from-file =
    .label = Impor Kunci Publik Dari File
    .accesskey = I
openpgp-key-man-import-secret-from-file =
    .label = Impor Kunci Rahasia Dari File
openpgp-key-man-import-sig-from-file =
    .label = Impor Pembatalan Dari File
openpgp-key-man-import-from-clipbrd =
    .label = Impor Kunci Dari Papan Klip
    .accesskey = I
openpgp-key-man-import-from-url =
    .label = Impor Kunci Dari URL
    .accesskey = U
openpgp-key-man-export-to-file =
    .label = Ekspor Kunci Publik Ke File
    .accesskey = E
openpgp-key-man-send-keys =
    .label = Kirim Kunci Publik Lewat Surel
    .accesskey = S
openpgp-key-man-backup-secret-keys =
    .label = Cadangkan Kunci Rahasia Ke File
    .accesskey = C
openpgp-key-man-discover-cmd =
    .label = Temukan Kunci Daring
    .accesskey = D
openpgp-key-man-discover-prompt = Untuk menemukan kunci OpenPGP secara daring, pada server kunci atau menggunakan protokol WKD, masukkan salah satu alamat surel atau ID kunci.
openpgp-key-man-discover-progress = Mencari…
openpgp-key-copy-key =
    .label = Salin Kunci Publik
    .accesskey = C
openpgp-key-export-key =
    .label = Ekspor Kunci Publik Ke File
    .accesskey = E
openpgp-key-backup-key =
    .label = Cadangkan Kunci Rahasia Ke File
    .accesskey = C
openpgp-key-send-key =
    .label = Kirim Kunci Publik Lewat Surel
    .accesskey = S
openpgp-key-man-copy-to-clipbrd =
    .label = Salin Kunci Publik Ke Papan Klip
    .accesskey = c
openpgp-key-man-ctx-expor-to-file-label =
    .label = Ekspor Kunci Ke File
openpgp-key-man-ctx-copy-to-clipbrd-label =
    .label = Salin Kunci Publik Ke Papan Klip
openpgp-key-man-close =
    .label = Tutup
openpgp-key-man-reload =
    .label = Muat Ulang Singgahan Kunci
    .accesskey = M
openpgp-key-man-change-expiry =
    .label = Ubah Tanggal Kedaluwarsa
    .accesskey = e
openpgp-key-man-del-key =
    .label = Hapus Kunci
    .accesskey = H
openpgp-delete-key =
    .label = Hapus Kunci
    .accesskey = H
openpgp-key-man-revoke-key =
    .label = Cabut Kunci
    .accesskey = C
openpgp-key-man-key-props =
    .label = Properti Kunci
    .accesskey = K
openpgp-key-man-key-more =
    .label = Lebih Lanjut
    .accesskey = L
openpgp-key-man-view-photo =
    .label = ID Foto
    .accesskey = F
openpgp-key-man-ctx-view-photo-label =
    .label = Lihat ID Foto
openpgp-key-man-show-invalid-keys =
    .label = Tampilkan kunci yang tidak valid
    .accesskey = d
openpgp-key-man-show-others-keys =
    .label = Tampilkan Kunci Dari Orang Lain
    .accesskey = O
openpgp-key-man-user-id-label =
    .label = Nama

## e2e encryption settings


## OpenPGP Key selection area


## Account settings export output

