#filter emptyLines

#define MOZ_LANGPACK_CREATOR linuxforum.kz

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Baurzhan Muftakhidinov</em:contributor> <em:contributor>Timur Timirkhanov</em:contributor> <em:contributor>Zhanbolat Satybaldinov</em:contributor> <em:contributor>Dauren Sarsenov</em:contributor>

#unfilter emptyLines
