# This file is in the UTF-8 encoding. It is *not*
# a Java .properties file and does *not* use \escapes

Welcome_Title=$ProductName$ Ukuhlaliswa
Welcome_MessageWelcome=Wamukelekile ku %s!
Welcome_Message0=You are about to install %s 2 Alpha 1.
Welcome_Message1=Uyayeleliswa bona uphume kumahlelo we Windows woke ngaphambili kobana usebenzise Ihlelo lesakhiwesi.
Welcome_Message2=Qhwarhaza Cima ukusuka kusakhiwesi ubese uvala woke amahlelo obegade uwasebenzisa.  Qhwarhaza Okulandelako ukuragela phambili nehlelo lesakhiwesi.
Welcome_Message3=Click Next to continue installing %s 2 Alpha 1.

License_Title=Isivumelwano selayisense yehlelo lekhomphyutha
License_SubTitle=Imithetho nemibandela yokusebenzisa ihlelo lekhomphyutheli.
License_Message0=Sibawa ufunde isivumelwano selayisense esilandelako. Sebenzisa isivadlwana sokwehlisa ukubona isivumelwano soke.
License_Accept=&Yamukela imithetho yesivumelwano selayisense
License_Decline=&Angiyamukeli imithetho yesivumelwano selayisense

Type_Title=Ihlobo Lesakhiwo
Type_SubTitle=Yenza ikhetho lesakhiwo.
Type_Message0=Khetha umhlono wesakhiwo owuthandako, bese uqhwarhaza Okulandelako.

Standard_Short=&Ubujamo
Standard_Long=I-Thunderbird izakufakwa ngokuzikhethela okuvamileko.

Custom_Short=&Jayeza
Custom_Long=Ungakhetha ikhetho elingelomuntu ayedwa ukobana lifakwe. Ingasetjenziswa basebenzisi abanelwazi eliphezulu.

Select_Title=Khetha amalunga
Select_SubTitle=Amalunga angezelelweko athuthukisa $ProductName$.
Select_Message0=Khetha amalunga angezelelweko ofuna ukuwafaka, ubese uqhwarhaza Okulandelako.

Path_Title=Faka I-Folda
Path_SubTitle=Kuphi $ProductName$ izokufakwa.
Path_Message0=$ProductName$ izokufakwa emafoldeni alandelako:

Integration_Title=Yakha Iindlela Ezifitjhani
Integration_SubTitle=Yakha Okujamele Amahlelo
Integration_Message0=Yakha Okujamele isijameli se $ProductShortName$:

Integration_Desktop=Kumpheme weKhomphyuthami
Integration_StartMenu=Ehlelweni le-folda yami yokuthoma I-menu
Integration_QuickLaunch=Esivalweni sami sokuhloma masinyana

SelectFolder_Title=$ProductName$ iSakhiwo-Khetha ihlelo le-Folda
SelectFolder_Message0=Isakhiwo sizokungezelela iinjameli zehlelo ku-Folda yehlelo etlolwe ngenzasi.  Ungatlola ibizo le-Folda elitjha, namkha ukhethe linye erherhweni lama-Folda akhona.  Qhwarhaza Okulandelako ukuragela phambili.

Advanced_Title=$ProductName$ Isakhiwo- Ukuhlelwa Okuphambili
Advanced_Message0=Nakube ihlanganiso yakho ye-internet ifuna iphroksi seva, faka ibizo le-seva yakho nemininingwana ye-port.  Nangabe ihlanganiso le-Intaneti yakho alifuni I-phroksi seva tjhiya indawo leyo inganalitho.

Install_Title=Irhunyezo
Install_SubTitle=Ulungele ukuthoma ukufaka $ProductName$.
Install_MessageInstall=Isakhiwo kwanje sizokufaka amalunga alandelako:
Install_MessageDownload=Isakhiwo kwanje sizokukhuphela besifake amalunga alandelako:
Install_Message0=Qhwarhaza Okulandelako ukuragela phambili.

Downloading_Title=Ukukhuphela
Downloading_SubTitle=Amalunga afunekako Wokukhuphela...
Downloading_Blurb=Isakhiwo sikhipha amafayili afuneka kobana afakwe $ProductName$.
Downloading_FileName=Njenganje iyakhuphela:
Downloading_Time=Isikhathi Esiseleko:

Installing_Title=Ukufaka
Installing_SubTitle=Ukufaka $ProductName$...
Installing_Blurb=Isakhiwo sifaka amafayili wesibawo.
Installing_Status=Ukulungiselela Ifayili:
Installing_Component=Iyafaka njenganje:

Success_Title=Faka ngokupheleleko
Success_Header=Ukufaka Kuphelele
Success_Message0=%s was successfully installed.
Success_Message1=Qhwarhaza Kuphelile ukuqedelela Isakhiwo.
Success_Launch=Launch %s now.

Check_Message=Ukukhuphela kwe-$ProductName$ kuphumelele. I-$ProductNameInternal$ kufanele ivalwe ukuragela phambili ngokufaka. Qhwarhaza Kulungile ukuphuma ku-$ProductNameInternal$ ngokuzenzakalela nokuthoma ukufaka.
Check_FullMessage=$ProductNameInternal$ kufanele ivalwe bona uragele phambili nokufaka. Qhwarhaza Kulungile ukuphuma $ProductNameInternal$ ngokuzenzakalela nokuthoma ukufaka.
Check_Wait=Iyavala $ProductNameInternal$.  Sibawa ujame...

Component_XPCOM=Yeqa iPlatfomo COM
Component_Mail=$ProductName$
Component_Offline=Ukusekela okuphume elayinini
Component_Offline_Long=Ngezelela ukusekela kokuphume elayinini ku- $ProductName$ Iposo.
Component_RSS=RSS Ukusekela
Component_RSS_Long=Ngezelela RSS sekela ku $ProductName$.
Component_QFA=Isisebenzi Semilayezo ebuyako Yekhwalithi
Component_QFA_Long=ukubika $ProductName$ Ilwazi elinganamandla
