# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title Cytańske znamjenja


#define bookmarks_heading Cytańske znamjenja


#define bookmarks_toolbarfolder Zarědnik rědki cytańskich znamjenjow


#define bookmarks_toolbarfolder_description Pśidajśo toś tomu zarědnikoju cytańske znamjenja, aby je na rědce cytańskich znamjenjow zwobraznił


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/firefox/central/


#define getting_started Prědne kšace


# LOCALIZATION NOTE (firefox_heading):


# Firefox links folder name


#define firefox_heading Mozilla Firefox


# LOCALIZATION NOTE (firefox_help):


# link title for https://www.mozilla.org/en-US/firefox/help/


#define firefox_help Pomoc a rozpokazanja


# LOCALIZATION NOTE (firefox_customize):


# link title for https://www.mozilla.org/en-US/firefox/customize/


#define firefox_customize Firefox pśiměriś


# LOCALIZATION NOTE (firefox_community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox_community Cyńśo sobu


# LOCALIZATION NOTE (firefox_about):


# link title for https://www.mozilla.org/en-US/about/


#define firefox_about Wó nas


#unfilter emptyLines
