# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = Guardar
dialogTitleAddBookmark = Novo marcador
dialogTitleAddMulti = Novos marcadores
dialogTitleEdit = Propriedades para “%S”
dialogTitleAddNewBookmark2 = Adicionar marcador
dialogTitleEditBookmark = Editar “%S”
dialogTitleEditBookmark2 = Editar marcador
dialogTitleAddBookmarkFolder = Adicionar pasta de marcador
dialogTitleEditBookmarkFolder = Editar pasta de marcador
bookmarkAllTabsDefault = [Nome da pasta]
newFolderDefault = Nova pasta
newBookmarkDefault = Novo marcador
