# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

calendar-title = Օրացույց
calendar-title-reminder = Հիշեցումներ
dateformat-label =
    .value = Ամսաթվի գրույթի ձևաչափ․
    .accesskey = D
#   $date (String) - the formatted example date
dateformat-long =
    .label = Երկար: { $date }
#   $date (String) - the formatted example date
dateformat-short =
    .label = Կարճ: { $date }
timezone-label =
    .value = Ժամային գոտի:
weekstart-label =
    .value = Սկսել շաբաթը ինչից՝
    .accesskey = r
show-weeknumber-label =
    .label = Ցուցադրել շաբաթվա համարը տեսքի և փոքր ամսվա մեջ
    .accesskey = n
workdays-label =
    .value = Աշխատանքային շաբաթվա օրեր․
dayweek-legend = Օրերի և շաբաթների տեսք
visible-hours-label =
    .value = Ցուցադրել.
    .accesskey = o
visible-hours-end-label =
    .value = ժամեր ժամանակում
day-start-label =
    .value = Օրը սկսվում է՝
    .accesskey = D
day-end-label =
    .value = Օրը ավատրվում է՝
    .accesskey = y
location-checkbox =
    .label = Ցուցադրել դիրքը
    .accesskey = L
multiweek-legend = Բազում շաբաթների տեսք
number-of-weeks-label =
    .value = Շաբաթների ցուցադրվող համարներ (նախորդ շաբաթները ներառյալ)․
    .accesskey = e
week-0-label =
    .label = չկա
week-1-label =
    .label = 1 շաբաթ
week-2-label =
    .label = 2 շաբաթ
week-3-label =
    .label = 3 շաբաթ
week-4-label =
    .label = 4 շաբաթ
week-5-label =
    .label = 5 շաբաթ
week-6-label =
    .label = 6 շաբաթ
previous-weeks-label =
    .value = Ցուցադրել նախորդ շաբաթները՝
    .accesskey = P
todaypane-legend = Այսօրվա փեղկ
# Note: "Upcoming" is the name of a section and the translation must match the
# translation of that section name (calendar.upcoming.button.label). Also,
# it should be upper case (as a proper name) if the target language permits.
soon-label =
    .value = Առաջիկա բաժինը ցույց է տալիս.
    .accesskey = U
event-task-legend = Իրադարձություններ և առաջադրանքներ
default-length-label =
    .value = Լռելյայն իրադարձություն և առաջադրանքի մեծություն:
    .accesskey = E
task-start-label =
    .value = Սկզբի ամսաթիվ՝
task-start-1-label =
    .label = Չկա
task-start-2-label =
    .label = Օրվա սկիզբ
task-start-3-label =
    .label = Օրվա ավարտ
task-start-4-label =
    .label = Վաղը
task-start-5-label =
    .label = Հաջորդ շաբաթ
task-start-6-label =
    .label = Հարաբերական է ներկա ժամանակին
task-start-7-label =
    .label = Հարաբերական է սկիզբին
task-start-8-label =
    .label = Հարաբերական է հաջորդ ժամին
task-due-label =
    .value = Վերջնաժամկետ՝
accessibility-legend = Մատչելիություն
accessibility-colors-label =
    .label = Հարմարեցնել գույները մատչելիության համար
    .accesskey = c
reminder-legend = Երբ հիշեցումը ավարտվում է՝
reminder-play-checkbox =
    .label = Նվագարկել ձայն
    .accesskey = s
reminder-play-alarm-button =
    .label = Միացնել
    .accesskey = P
reminder-default-sound-label =
    .label = Օգտագործել լռելյայն ձայն
    .accesskey = d
reminder-custom-sound-label =
    .label = Օգտ. հետևյալ ձայնային նիշը
    .accesskey = U
reminder-browse-sound-label =
    .label = Ընտրել…
    .accesskey = B
reminder-dialog-label =
    .label = Ցուցադրել հիշեցման երկխոսությունը
    .accesskey = x
missed-reminder-label =
    .label = Ցուցադրել բաց թողնված հիշեցումները գրվող օրացույցերի համար
    .accesskey = m
reminder-default-legend = Հիշեցման լռելյայնը
default-snooze-label =
    .value = Ննջեցման լռելյայն տևողություն․
    .accesskey = S
event-alarm-label =
    .value = Սահմանել լռելյայն հիշեցումներ իրադարձությունների համար․
    .accesskey = e
alarm-on-label =
    .label = Միացնել
alarm-off-label =
    .label = Անջատել
task-alarm-label =
    .value = Սահմանել լռելյայն հիշեցում առաջադրանքների համար․
    .accesskey = a
event-alarm-time-label =
    .value = Ժամի լռելյայն հիշեցումը սահմանվել է իրադարձությունից առաջ․
    .accesskey = u
task-alarm-time-label =
    .value = Ժամի լռելյայն հիշեցումը սահմանվել է առաջադրանքից առաջ․
    .accesskey = o
category-new-label = Նոր անվանակարգ
category-edit-label = Խմբագրել անվանակարգը
category-overwrite-title = Զգուշացում. Կրկնօրինակի անուն
category-overwrite = Այդ անվանումով անվանակարգ արդեն գոյություն ունի: Ցանկանու՞մ եք վերագրել այն:
category-blank-warning = Դուք պիտի մուտքագրե՛ք անվանակարգի անուն։
