# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host } کے لیے نظر دوڑا رہا ہے…
network-connection-status-connected = { $host }… سے جڑا ہوا
network-connection-status-sending-request = { $host } کو فرمائش بھیج رہا ہے…
network-connection-status-transferring-data = { $host } سے کوائف منتقل کر رہا ہے…
network-connection-status-connecting = { $host } کے ساتھ جڑ رہا ہے…
network-connection-status-read = { $host } پڑھا
network-connection-status-wrote = { $host } لکھا
network-connection-status-waiting = { $host } کے لیے انتظار کر رہا ہے…
network-connection-status-looked-up = { $host } کے لیے نظر دوڑا رہا ہے…
network-connection-status-tls-handshake = { $host } پر TLS ہینڈشیک کارگردگی کر رحا ہے…
network-connection-status-tls-handshake-finished = { $host } پر TLS ہینڈشیک ختم ہوا…
