# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = URL कपि खालाम
    .accesskey = y
copy-username-cmd =
    .label = कपि खालाम आरो बाहायग्रामुं
    .accesskey = U
edit-username-cmd =
    .label = बाहायग्रामुंखौ सुजु
    .accesskey = d
copy-password-cmd =
    .label = पासर्वडखौ कपि खालाम
    .accesskey = C
edit-password-cmd =
    .label = पासवार्डखौ सुजु
    .accesskey = E
search-filter =
    .accesskey = S
    .placeholder = नागिर
column-heading-site =
    .label = साइट
column-heading-username =
    .label = बाहायग्रा मुं
column-heading-password =
    .label = पासवार्ड
column-heading-time-created =
    .label = गिबि बाहायखानाय
column-heading-time-last-used =
    .label = जोबथा बाहायखानाय
column-heading-time-password-changed =
    .label = जोबथा सोलायनाय
column-heading-times-used =
    .label = बाहायखानाय सम
remove =
    .label = बोखार
    .accesskey = ब
import =
    .label = लाबो...
    .accesskey = I
close-button =
    .label = बन्द खालाम
    .accesskey = C
show-passwords =
    .label = पासवार्डफोरखौ दिन्थि
    .accesskey = P
hide-passwords =
    .label = पासवर्डफोरखौ दोनखुमा
    .accesskey = P
remove-all =
    .label = गासैखौ बोखार
    .accesskey = A
remove-all-shown =
    .label = गासै दिन्थिनायखौ बोखार
    .accesskey = A
remove-all-passwords-prompt = नोंथाङा थारैनो नोंथांनि पासवर्डखौ दिन्थिनो सानो नामा?
remove-all-passwords-title = गासै पासवर्डखौ गैया खालाम
no-master-password-prompt = नोंथाङा थारैनो नोंथांनि पासवर्डखौ दिन्थिनो सानो नामा?
