# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = Adheñchet e vo ar bajennad web-mañ etrezek ul lec'h nevez. Fellout a rafe deoc'h ma vefe adkaset ar furmskridad roadennoù bet enanket ganeoc'h d'al lec'h nevez?
# Directory listing strings
DirTitle = Menegva %1$S
DirGoUp = betek ar c'havlec'hiad a live uheloc'h
ShowHidden = Diskouez an ergorennoù kuzh
DirColName = Anv
DirColSize = Ment
DirColMTime = An hini diwezhañ kemmet
DirFileLabel = Restr:
UnsafeUriBlocked = Stanket eo bet al loaz e “%1$S” gant ar merdeiñ diogel.
CookieBlockedByPermission = Sanket eo bet ar goulenn haeziñ kadaviñ an toupinoù war “%1$S” abalamour da aotreoù toupinoù personelaet.
CookieBlockedAll = Sanket eo bet ar goulenn haeziñ ar c'hadaviñ pe an toupinoù war “%1$S” dre ma stankomp an holl c'houlennoù haeziñ d'ar c'hadaviñ.
