# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE  (inlineStyleSheet): This is the name used for an style sheet
# that is declared inline in the <style> element. Shown in the stylesheets list.
# the argument is the index (order) of the containing <style> element in the
# document.
inlineStyleSheet = <inline style sheet #%S>
# LOCALIZATION NOTE  (importStyleSheet.filter): This is the *.css filter title
importStyleSheet.filter = yêtz CSS
# LOCALIZATION NOTE  (saveStyleSheet.filter): This is the *.css filter title
saveStyleSheet.filter = yêtz CSS
