# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### Notice: If you're updating this list, you should also
###         update the list in mozIntl.js.

region-name-ad = Andora
region-name-af = Afganistan
region-name-ag = Antigua i Barbuda
region-name-ai = Anguila
region-name-al = Albanija
region-name-am = Armenija
region-name-ao = Angola
region-name-aq = Antarctika
region-name-ar = Argentina
region-name-as = Američka Samoa
region-name-at = Austrija
region-name-au = Australija
region-name-aw = Aruba
region-name-az = Azerbajdžan
region-name-ba = Bosna i Hercegovina
region-name-bb = Barbados
region-name-bd = Bangladeš
region-name-be = Belgija
region-name-bf = Burkina Faso
region-name-bg = Bugarska
region-name-bh = Bahrein
region-name-bi = Burundi
region-name-bj = Benin
region-name-bm = Bermuda
region-name-bo = Bolivija
region-name-br = Brazil
region-name-bt = Butan
region-name-bv = Bouvet Otok
region-name-bw = Bocvana
region-name-by = Bjelorusija
region-name-bz = Belize
region-name-ca = Kanada
region-name-cc = Cookovo Otočje (Keeling)
region-name-cf = Centralna Afrička Republika
region-name-ch = Švicarska
region-name-ck = Cookovo Otočje
region-name-cl = Čile
region-name-cm = Kamerun
region-name-cn = Kina
region-name-co = Kolumbija
region-name-cr = Kostarika
region-name-cu = Kuba
region-name-cx = Božično Otočje
region-name-cy = Cipar
region-name-cz = Češka Republika
region-name-de = Njemačka
region-name-dj = Djibouti
region-name-dk = Danska
region-name-dm = Dominika
region-name-do = Dominikanska Republika
region-name-dz = Alžir
region-name-ec = Ekvador
region-name-ee = Estonija
region-name-eg = Egipat
region-name-eh = Zapadna Sahara
region-name-er = Eritreja
region-name-es = Španjolska
region-name-et = Etiopija
region-name-fi = Finska
region-name-fj = Fidži
region-name-fo = Faroe Otočje
region-name-fr = Francuska
region-name-ga = Gabon
region-name-gb = Ujedinjeno Kraljevstvo
region-name-gd = Grenada
region-name-ge = Gruzija
region-name-gf = Francuska Gvajana
region-name-gg = Guernsey
region-name-gh = Gana
region-name-gi = Gibraltar
region-name-gl = Grenland
region-name-gn = Gvineja
region-name-gp = Guadeloupe
region-name-gq = Ekvatorska Gvineja
region-name-gr = Grčka
region-name-gt = Gvatemala
region-name-gu = Guam
region-name-gw = Guinea-Bissau
region-name-gy = Gvajana
region-name-hk = Hong Kong
region-name-hm = Heard Island and McDonald Islands
region-name-hn = Honduras
region-name-hr = Hrvatska
region-name-ht = Haiti
region-name-hu = Mađarska
region-name-id = Indonezija
region-name-ie = Irska
region-name-il = Izrael
region-name-im = Otok Čovjeka
region-name-in = Indija
region-name-io = Teritorij Britanskog Indijskog Oceana
region-name-iq = Irak
region-name-ir = Iran
region-name-is = Island
region-name-it = Italija
region-name-je = Jersey
region-name-jm = Jamajka
region-name-jo = Jordan
region-name-jp = Japan
region-name-ke = Kenija
region-name-kg = Kirgistan
region-name-kh = Kambodža
region-name-ki = Kiribati
region-name-km = Komori
region-name-kn = Saint Kitts and Nevis
region-name-kw = Kuvajt
region-name-ky = Kajmansko Otočje
region-name-kz = Kazakstan
region-name-la = Laos
region-name-lb = Libanon
region-name-lc = Sveta Lucija
region-name-li = Lihtenštajn
region-name-lk = Šri Lanka
region-name-lr = Liberija
region-name-ls = Lesoto
region-name-lt = Litva
region-name-lu = Luksemburg
region-name-lv = Latvija
region-name-ly = Libija
region-name-ma = Maroko
region-name-mc = Monako
region-name-md = Moldavija
region-name-me = Crna Gora
region-name-mf = Sveti Martin
region-name-mg = Madagaskar
region-name-mh = Marshallovo Otočje
region-name-ml = Mali
region-name-mn = Mongolija
region-name-mp = Northern Mariana Islands
region-name-mq = Martinik
region-name-mr = Mauritanija
region-name-ms = Montserrat
region-name-mt = Malta
region-name-mu = Mauricijus
region-name-mv = Maldivi
region-name-mw = Malawi
region-name-mx = Meksiko
region-name-my = Malezija
region-name-mz = Mozambik
region-name-na = Namibija
region-name-nc = Nova Kaledonija
region-name-ne = Niger
region-name-nf = Norfolk Otočje
region-name-ng = Nigerija
region-name-ni = Nikaragva
region-name-nl = Nizozmeska
region-name-no = Norveška
region-name-np = Nepal
region-name-nr = Nauru
region-name-nu = Niue
region-name-nz = Novi Zeland
region-name-om = Oman
region-name-pa = Panama
region-name-pe = Peru
region-name-pf = Francuska Polinezija
region-name-pg = Papua New Guinea
region-name-ph = Filipini
region-name-pk = Pakistan
region-name-pl = Poljska
region-name-pm = Saint Pierre and Miquelon
region-name-pr = Portoriko
region-name-pt = Portugal
region-name-pw = Palau
region-name-py = Paragvaj
region-name-qa = Katar
region-name-re = Reunion
region-name-ro = Rumunjska
region-name-rs = Srbija
region-name-rw = Ruanda
region-name-sa = Saudijska Arabija
region-name-sb = Solomon Otočje
region-name-sc = Sejšeli
region-name-sd = Sudan
region-name-se = Švedska
region-name-sg = Singapur
region-name-si = Slovenija
region-name-sk = Slovačka
region-name-sl = Siera Leon
region-name-sm = San Marino
region-name-sn = Senegal
region-name-so = Somalija
region-name-sr = Surinam
region-name-st = Sao Tome i Principe
region-name-sv = Salvador
region-name-sy = Sirija
region-name-sz = Swaziland
region-name-tc = Turks and Caicos Islands
region-name-td = Čad
region-name-tg = Togo
region-name-th = Tajland
region-name-tj = Tadžikistan
region-name-tk = Tokelau
region-name-tl = Timor-Leste
region-name-tm = Turkmenistan
region-name-tn = Tunis
region-name-to = Tonga
region-name-tr = Turska
region-name-tt = Trinidad i Tobago
region-name-tv = Tuvalu
region-name-tw = Tajvan
region-name-tz = Tanzania
region-name-ua = Ukrajina
region-name-ug = Uganda
region-name-us = Sjedinjene Države
region-name-uy = Urugvaj
region-name-uz = Uzbekistan
region-name-va = Vatican
region-name-vc = Saint Vincent and the Grenadines
region-name-ve = Venecuela
region-name-vn = Vijetnam
region-name-vu = Vanuatu
region-name-wf = Wallis i Futuna
region-name-ws = Samoa
region-name-ye = Jemen
region-name-yt = Mayotte
region-name-za = Južnoafrička Republika
region-name-zm = Zambia
region-name-zw = Zimbabve
