# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = हे वेब पृष्ठ नव्या स्थळास पुन्हा पाठविले जात आहे. फॉर्मची लिखीत माहिती आपण लिहीलेल्या नवीन स्थानास पुन्हा पाठवू इच्छिता?
# Directory listing strings
DirTitle = %1$S ची अणुक्रमणिका
DirGoUp = वरच्या पातळीवरील संचयीकेपर्यंत
ShowHidden = लपविलेले घटक दर्शवा
DirColName = नाव
DirColSize = आकार
DirColMTime = शेवटच्यावेळी संपादीत
DirFileLabel = फाइल:\u0020
UnsafeUriBlocked = “%1$S” येथील संसाधन सुरक्षित ब्राऊझिंग प्रणाली ने अडवला.
