# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = ଖୋଲନ୍ତୁ
    .accesskey = O
places-open-all-in-tabs =
    .label = ସମସ୍ତଙ୍କୁ ଟ୍ୟାବରେ ଖୋଲନ୍ତୁ
    .accesskey = O
places-view =
    .label = ଦୃଶ୍ୟ
    .accesskey = w
places-by-date =
    .label = ତାରିଖ ଦ୍ୱାରା
    .accesskey = D
places-by-site =
    .label = ସାଇଟ ଦ୍ୱାରା
    .accesskey = S
places-by-most-visited =
    .label = ଅଧିକାଂଶ ସମୟରେ ପରିଦର୍ଶିତ ଅନୁସାରେ
    .accesskey = V
places-by-last-visited =
    .label = ଶେଷଥର ପରିଦର୍ଶିତ ଅନୁସାରେ
    .accesskey = L
places-by-day-and-site =
    .label = ତାରିଖ ଏବଂ ସାଇଟ ଦ୍ୱାରା
    .accesskey = t
places-history =
    .aria-label = ପୁରୁଣା ତଥ୍ୟ
places-delete-domain-data =
    .label = ଏହି ସାଇଟ ବିଷୟରେ ଭୁଲିଯାଆନ୍ତୁ
    .accesskey = F
places-sortby-name =
    .label = ନାମ କ୍ରମାନୁସାରେ ସଜାଡନ୍ତୁ
    .accesskey = r
places-library =
    .title = ଲାଇବ୍ରେରୀ
    .style = width:700px; height:500px;
places-file-close =
    .label = ବନ୍ଦକରନ୍ତୁ
    .accesskey = C
places-cmd-close =
    .key = w
places-view-menu-columns =
    .label = ସ୍ତମ୍ଭଗୁଡିକୁ ଦର୍ଶାନ୍ତୁ
    .accesskey = C
places-view-menu-sort =
    .label = ସଜାଡନ୍ତୁ
    .accesskey = S
places-view-sort-unsorted =
    .label = ଅସଜଡା
    .accesskey = U
places-view-sort-ascending =
    .label = A > Z କ୍ରମରେ ସଜାଡନ୍ତୁ
    .accesskey = A
places-view-sort-descending =
    .label = Z > A କ୍ରମରେ ସଜାଡନ୍ତୁ
    .accesskey = Z
places-cmd-backup =
    .label = ନକଲ ସଂରକ୍ଷଣ…
    .accesskey = B
places-cmd-restore =
    .label = ପୁନଃସ୍ଥାପନ
    .accesskey = R
places-cmd-restore-from-file =
    .label = ଫାଇଲ ଚୟନକରନ୍ତୁ…
    .accesskey = C
