# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title Taq retal


#define bookmarks_heading Taq yaketal


#define bookmarks_toolbarfolder Rukajtz'ik taq samajib'äl pa ri ruyakwuj taq yaketal


#define bookmarks_toolbarfolder_description Ke'atz'aqatisaj ri taq yaketal pa re yakwuj re' richin ye'atz'ët pa ri rukajtz'ik taq samajib'äl richin taq yaketal


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/firefox/central/


#define getting_started Rutikirisaxik


# LOCALIZATION NOTE (firefox_heading):


# Firefox links folder name


#define firefox_heading Mozilla Firefox


# LOCALIZATION NOTE (firefox_help):


# link title for https://www.mozilla.org/en-US/firefox/help/


#define firefox_help To'ïk chuqa' taq tijonïk


# LOCALIZATION NOTE (firefox_customize):


# link title for https://www.mozilla.org/en-US/firefox/customize/


#define firefox_customize Tawichinaj Firefox


# LOCALIZATION NOTE (firefox_community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox_community ¡Kato’on!


# LOCALIZATION NOTE (firefox_about):


# link title for https://www.mozilla.org/en-US/about/


#define firefox_about Chi qij röj


#unfilter emptyLines
