# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

appmenu-update-available2 =
    .buttonlabel = ডাউনলোড করুন
    .buttonaccesskey = D
    .label = হালনাগাদ উপলব্ধ রয়েছে
    .secondarybuttonlabel = খারিজ করুন
    .secondarybuttonaccesskey = m
appmenu-update-available-message2 = { -brand-shorter-name }-এর সর্বশেষ সংস্করণটি ডাউনলোড করুন।
appmenu-update-manual2 =
    .buttonlabel = ডাউনলোড করুন
    .buttonaccesskey = D
    .label = হালনাগাদ উপলব্ধ রয়েছে
    .secondarybuttonlabel = খারিজ করুন
    .secondarybuttonaccesskey = m
appmenu-update-manual-message2 = { -brand-shorter-name } স্বয়ংক্রিয়ভাবে হালনাগাদ করা যায়নি। নতুন সংস্করণ ডাউনলোড করুন — আপনার সংরক্ষিত তথ্য বা স্বনির্ধারণগুলো হারিয়ে যাবে না।
appmenu-update-unsupported2 =
    .buttonlabel = আরও জানুন
    .buttonaccesskey = L
    .label = হালনাগাদ করা যাচ্ছে না
    .secondarybuttonlabel = খারিজ করুন
    .secondarybuttonaccesskey = m
appmenu-update-unsupported-message2 = আপনার অপারেটিং সিস্টেম { -brand-shorter-name }-এর সর্বশেষ সংস্করণের সাথে সামঞ্জস্যপূর্ণ নয়।
appmenu-update-restart2 =
    .buttonlabel = হালনাগাদ ও পুনরাম্ভ করুন
    .buttonaccesskey = U
    .label = হালনাগাদ উপলব্ধ রয়েছে
    .secondarybuttonlabel = খারিজ করুন
    .secondarybuttonaccesskey = m
appmenu-update-restart-message2 = { -brand-shorter-name }-এর সর্বশেষ সংস্করণ ব্যবহার করুন৷ ট্যাব খুলুন তখন উইন্ডো পুনরুদ্ধার হয়ে যাবে।
appmenu-update-other-instance =
    .buttonlabel = তবুও { -brand-shorter-name } আপডেট করুন
    .buttonaccesskey = U
    .label = { -brand-shorter-name } সর্বশেষ সংস্করণে স্বয়ংক্রিয়ভাবে আপডেট করতে অক্ষম৷
    .secondarybuttonlabel = এখন নয়
    .secondarybuttonaccesskey = N
appmenu-update-other-instance-message = একটি নতুন { -brand-shorter-name } আপডেট পাওয়া যাচ্ছে, কিন্তু এটি ইনস্টল করা যাবে না কারণ { -brand-shorter-name }-এর অন্য একটি অনুলিপি চলছে৷ আপডেট চালিয়ে যেতে এটি বন্ধ করুন, অথবা যেভাবেই হোক আপডেট করতে বেছে নিন (আপনি এটি পুনরায় চালু না করা পর্যন্ত অন্য অনুলিপি সঠিকভাবে কাজ নাও করতে পারে)।
appmenu-addon-post-install-message3 = অ্যাপ্লিকেশন মেনুর মাধ্যমে আপনার অ্যাড-অন ও থিমগুলি পরিচালনা করুন।
appmenu-new-tab-controlled-changes =
    .buttonlabel = পরিবর্তন থাকুক
    .buttonaccesskey = K
    .label = আপনার নতুন ট্যাব পরিবর্তিত হয়েছে.
    .secondarybuttonlabel = নতুন ট্যাব ব্যবস্থাপনা
    .secondarybuttonaccesskey = M
appmenu-homepage-controlled-changes =
    .buttonlabel = পরিবর্তন থাকুক
    .buttonaccesskey = K
    .label = আপনার হোমপেজ পরিবর্তিত হয়েছে.
    .secondarybuttonlabel = হোমপেজ ব্যবস্থাপনা
    .secondarybuttonaccesskey = M
appmenu-tab-hide-controlled =
    .buttonlabel = ট্যাবগুলো লুকানো রাখুন
    .buttonaccesskey = K
    .label = আপনার লুকানো ট্যাবে প্রবেশ করুন
    .secondarybuttonlabel = এক্সটেনশনটি নিষ্ক্রিয় করুন
    .secondarybuttonaccesskey = D
