# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-intro = { -brand-full-name } အားကမ္ဘာတစ်ဝှမ်းရှိ ထောင်ချီသော အဖွဲ့ဝင်များ မှတည်ဆောက်ခဲ့ပြီး အခမဲ့ပြီး အရင်းအမြစ် ရယူနိုင်သော ဆော့ဝဲတစ်ခုဖြစ်သည်။ ဤတွင်သင်သိရှိထားရန် အချက်အလက် အချို့ရှိသည်၊
rights-intro-point-3 = { -brand-short-name } တွင်ပါဝင်သောအချို့စွမ်းဆောင်ရေးများ (ပြသာနာတင်ပြပေးသူကဲ့သို) သည်သင့်အား တုန့်ပြန်ထင်မြင်ချက်  { -vendor-short-name } သို့ပေးပို့ခွင့်ပြုပါသည်။တုန့်ပြန်ထင်မြင်ချက်ပေးပို့ ခြင်းအား ရွေချယ်ခြင်းအားဖြင့် သင်သည် { -vendor-short-name } အား တုန့်ပြန်ထင်မြင်ချက် အသုံးပြုပြီး၎င်း၏ ထုတ်ကုန်အားအဆင့်တိုးမြှင့်ခြင်း၊တုန့်ပြန်ထင်မြင်ချက် ကို ဝတ်ဆိုက်တွင် တင်ပြခွင့်ပြုခြင်း ဖြန့်ဝင်ခြင်းပြုခြင်း သဘောမည်ပါသည်။
rights-intro-point-4 = သင် { -vendor-short-name } သို့ပေးပို့ခဲ့သော  { -brand-short-name } နှင့်ပတ်သတ်သည် တုန့်ပြန်ထင်မြင်ချက်များ နှင့် ပုဂ္ဂိုလ်ရေးအချက်အလက် များအားမည်သို့အသုံးပြုသည် ကိုဤတွင်ဖော်ပြထားသည်<a data-l10n-name="mozilla-privacy-policy-link">{ -brand-short-name }၏ပရိုက်ဗစ်ဆီပေါ်လစီ</a>.
rights-intro-point-5 = အချို့ { -brand-short-name } ကွန်ယက်အခြေခံ သတင်းအချက်အလက် ဝန်ဆောင်မှုများ အသုံးပြုထားပါသည်။ သို့သော် ကျွန်ုပ်တို့သည် ထိုဝန်ဆောင်မှုများ ရာနှုန်းပြည့် မှန်ကန်ကြောင်း အာမခံချက် မပေးနိုင်ပါ။ ထိုဝန်ဆောင်မှုများကို ရပ်တန့်ခြင်း အစရှိသည့် အသေးစိတ် အကြောင်းအရာများကို ရှာဖွေနိုင်ပါသည်။ <a data-l10n-name="mozilla-service-terms-link">ဝန်ဆောင်မှူဆိုင်ရာစည်းမျဉ်းများ</a>.
rights-intro-point-5-unbranded = အကယ်လို့ဒီထုတ်ကုန်ဟာ ဝတ်ဆိုက်ဝန်ဆောင်မှူများဖြင့်အလုပ်လုပ်သောအရာမဟုတ်ပါက မည်သည့်အသုံးချနိုင်သောဝန်ဆောင်မှူသဘောတူညီချက်များအားလုံးလင်ခ့်ပေးရန်နေရာမှာ<a data-l10n-name="mozilla-website-services-link">ဝတ်ဆိုက်ဝန်ဆောင်မှူများ</a>section.
rights-locationawarebrowsing = <strong>တည်နေရာအလိုက်အင်တာနက်အသုံးပြုခြင်း</strong>is always opt-in.  No location information is ever sent without your permission.  If you wish to disable the feature completely, follow these steps:
rights-locationawarebrowsing-term-3 = Double click on the geo.enabled preference
rights-webservices-term-1 = { -vendor-short-name } နှင့် စေတနာ့ဝန်ထမ်းများ၊ လိုင်စင်ပေးသူများ နှင့်ပါတနာများသည် အတတ်နိုင်ဆုံး တိကျသော ခေတ်မှီသော ဝန်ဆောင်မှူများကို ပေးရန်လုပ်ဆောင်နေကြပါသည်။သို့သော်လည်း ဤသတင်းအချက်အလက် သည် အမှားလုံးဝကင်းပါသည်ဟု ကျွန်ုပ်တို့ အာမမခံပါ။ဥမာအားဖြင့် လုံးခြုံစိတ်ချ အင်တာနက်သုံးစွဲခြင်း ဆားဗစ်သည်အချို့သောဝတ်ဆိုက်များ အား အန္တရာယ်ရှိသည် ဟုမုချမသိနိုင်ကောင်း မသိနိုင်လိမ့်မည်။ ဝန်ဆောင်မှူများအားလုံးသည် ခန့်မှန်းတွက်ချက်ထားသော ဝန်ဆောင်မှူများဖြစ်သည်ကို သတိထားစေလိုပါသည်။
rights-webservices-term-3 = You are welcome to use these Services with the accompanying version of { -brand-short-name }, and { -vendor-short-name } grants you its rights to do so. { -vendor-short-name } and its licensors reserve all other rights in the Services. These terms are not intended to limit any rights granted under open source licenses applicable to { -brand-short-name } and to corresponding source code versions of { -brand-short-name }.
rights-webservices-term-4 = <strong>The Services are provided "as-is." { -vendor-short-name }, its contributors, licensors, and distributors, disclaim all warranties, whether express or implied, including without limitation, warranties that the Services are merchantable and fit for your particular purposes. You bear the entire risk as to selecting the Services for your purposes and as to the quality and performance of the Services. Some jurisdictions do not allow the exclusion or limitation of implied warranties, so this disclaimer may not apply to you.</strong>
