# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Letar efter { $host }…
network-connection-status-connected = Ansluten till { $host }…
network-connection-status-sending-request = Skickar begäran till { $host }…
network-connection-status-transferring-data = Hämtar data från { $host }…
network-connection-status-connecting = Ansluter till { $host }…
network-connection-status-read = Läser { $host }
network-connection-status-wrote = Skrev { $host }
network-connection-status-waiting = Väntar på { $host }…
network-connection-status-looked-up = Letade efter { $host }…
network-connection-status-tls-handshake = Utför en TLS-handskakning till { $host }…
network-connection-status-tls-handshake-finished = TLS-handskakningen slutförd för { $host }…
