# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SaveImageTitle = Tiyak wachib'äl
SaveMediaTitle = Tiyak q'ojom
SaveVideoTitle = Tiyak ri silowachib'äl
SaveAudioTitle = Tiyak K'oxomal
SaveLinkTitle = Tiyak Achi'el
WebPageCompleteFilter = Ruxaq k'amaya'l, tz'aqät
WebPageHTMLOnlyFilter = Ruxaq k'amaya'l, xa xe HTML
WebPageXHTMLOnlyFilter = Ruxaq k'amaya'l, xa xe XHTML
WebPageSVGOnlyFilter = Ruxaq k'amaya'l, xa xe SVG
WebPageXMLOnlyFilter = Ruxaq k'amaya'l, xa xe XML
# LOCALIZATION NOTE (UntitledSaveFileName):
#    This is the default filename used when saving a file if a filename could
#    not be determined or if a filename was invalid. A period and file
#    extension may be appended to this string.
UntitledSaveFileName = Majun b'i'aj
