# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Ցանկանու՞մ եք վստահել "%S"-ին հետևյալ նպատակի համար:
unnamedCA = Վկայագրման կենտրոն (անանուն)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Խնդրեմ նշեք Վկայագրի այս կրկնօրինակը ծածկագրելու համար օգտագործված գաղտնաբառը:
# Page Info
pageInfo_NoEncryption = Կապակցումը Գաղտնագրված չէ
pageInfo_Privacy_None1 = Դիտվող էջի համար %S հանգույցը ծածկագրում չի աջակցում:
pageInfo_Privacy_None2 = Համացանցով ուղղարկված չծածկագրված տեղեկությունը կարող է փոխանցման ընթացքում դիտվել այլ անձաց կողմից:
pageInfo_Privacy_None4 = Ձեր կողմից դիտվող էջը չի ծածկագրվել նախքան համացանցով ուղղարկվելը:
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Կապակցումը գաղտնագրված է (%1$S, %2$S բիթ բանալի, %3$S)
pageInfo_BrokenEncryption = Վնասված գաղտնագրում (%1$S, %2$S բիթ բանալի, %3$S)
pageInfo_Privacy_Encrypted1 = Ձեր կողմից դիտվող էջը ծածկագրվել է նախքան համացանցով ուղղարկվելը:
pageInfo_Privacy_Encrypted2 = Գաղտնագրումը խստիվ բարդացնում է ոչ արտոնյալ անձանց կողմից համակարգիչների միջև ճանապարհորդող տեղեկագրության կարդալը: Այդ իսկ պատճառով խիստ անհավանական է, որ որևէ մեկը այս էջը ցանցով փոխանցվելիս կարդացած լինի:
pageInfo_MixedContent = Կապը մասնակի գաղտնագրված է
pageInfo_MixedContent2 = Ձեր դիտած էջի որոշ մասեր համացանցով փոխանցվելիս չէին գաղտնագրվել:
pageInfo_WeakCipher = Կապակցումը այս կայքին օգտագործում է թույլ գաղտնագրում և գաղտնի չէ: Այլ անձիք կարող են տեսնել ձեր տեղեկատվությունը կամ փոփոխեն կայքի ժառանգորդին:
pageInfo_CertificateTransparency_Compliant = Այս կայքը աշխատում է Վկայագրի թափանցիկության դրույթով:
# Token Manager
password_not_set = (նշված չէ)
