# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Log Masuk Tersimpan
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-site-url-cmd =
    .label = Salin URL
    .accesskey = n
launch-site-url-cmd =
    .label = Layari URL
    .accesskey = L
copy-username-cmd =
    .label = Salin Nama Pengguna
    .accesskey = P
edit-username-cmd =
    .label = Sunting Nama Pengguna
    .accesskey = n
copy-password-cmd =
    .label = Salin Kata Laluan
    .accesskey = S
edit-password-cmd =
    .label = Sunting Kata Laluan
    .accesskey = u
search-filter =
    .accesskey = C
    .placeholder = Cari
column-heading-site =
    .label = Laman
column-heading-username =
    .label = Nama pengguna
column-heading-password =
    .label = Kata laluan
column-heading-time-created =
    .label = Pertama Digunakan
column-heading-time-last-used =
    .label = Terakhir Digunakan
column-heading-time-password-changed =
    .label = Terakhir Diubah
column-heading-times-used =
    .label = Bilangan Digunakan
remove =
    .label = Buang
    .accesskey = B
import =
    .label = Import…
    .accesskey = I
close-button =
    .label = Tutup
    .accesskey = u
show-passwords =
    .label = Papar Kata laluan
    .accesskey = P
hide-passwords =
    .label = Sorok Kata laluan
    .accesskey = P
logins-description-all = Log masuk untuk laman web berikut disimpan dalam komputer anda
logins-description-filtered = Log masuk berikut sepadan dengan carian anda:
remove-all =
    .label = Buang Semua
    .accesskey = S
remove-all-shown =
    .label = Buang Semua Paparan
    .accesskey = S
remove-all-passwords-prompt = Adakah anda pasti mahu mengalih keluar semua kata laluan?
remove-all-passwords-title = Buang semua kata laluan
no-master-password-prompt = Adakah anda pasti mahu memaparkan kata laluan anda?
