# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Bạn có muốn tin tưởng “%S” cho những mục đích sau?
unnamedCA = Cơ quan cấp chứng chỉ (chưa được đặt tên)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Vui lòng nhập mật khẩu đã được sử dụng để mã hóa bản sao lưu chứng chỉ này:
# Page Info
pageInfo_NoEncryption = Kết nối không được mã hóa
pageInfo_Privacy_None1 = Trang web %S không hỗ trợ mã hóa cho trang bạn đang xem.
pageInfo_Privacy_None2 = Thông tin được gửi qua Internet mà không mã hóa có thể bị người khác xem trong khi nó đang được truyền tải.\u0020
pageInfo_Privacy_None4 = Trang bạn đang xem không được mã hóa trước khi nó được truyền tải trên Internet.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Kết nối đã được mã hóa (%1$S, khóa %2$S bit, %3$S)
pageInfo_BrokenEncryption = Mã hóa bị hỏng (%1$S, khóa %2$S bit, %3$S)
pageInfo_Privacy_Encrypted1 = Trang bạn đang xem được mã hóa trước khi nó được truyền tải trên Internet.
pageInfo_Privacy_Encrypted2 = Mã hóa sẽ gây khó khăn cho những người không được ủy quyền xem thông tin di chuyển giữa các máy tính. Do đó, không ai có thể đọc trang này khi nó di chuyển trên mạng.
pageInfo_MixedContent = Kết nối được mã hóa một phần
pageInfo_MixedContent2 = Một số phần của trang bạn đang xem không được mã hóa trước khi được truyền tải trên Internet.
pageInfo_WeakCipher = Kết nối của bạn đến trang web này sử dụng mã hóa yếu và không riêng tư. Những người khác có thể xem thông tin của bạn hoặc sửa đổi hành vi của trang web.
pageInfo_CertificateTransparency_Compliant = Trang web này tuân thủ chính sách Chứng chỉ minh bạch.
# Token Manager
password_not_set = (chưa đặt)
