# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = { $host } qidirlmoqda…
network-connection-status-connected = { $host }`ga ulandi
network-connection-status-sending-request = { $host }`ga soʻrov joʻnatilmoqda…
network-connection-status-transferring-data = { $host }`dan ma`lumot koʻchirib olinmoqda…
network-connection-status-connecting = { $host }`ga ulanmoqda…
network-connection-status-read = { $host }`ni oʻqish
network-connection-status-wrote = { $host } yozdi
network-connection-status-waiting = { $host } kutilmoqda…
network-connection-status-looked-up = { $host } qidirilmoqda…
