# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

appmenu-update-available =
    .label = Навсозии нави { -brand-shorter-name } дастрас аст.
    .buttonlabel = Боргирӣ кардани навсозӣ
    .buttonaccesskey = Б
    .secondarybuttonlabel = Ҳоло не
    .secondarybuttonaccesskey = Н
appmenu-update-available-message = Барои баланд бардоштани суръат ва сатҳи махфият { -brand-shorter-name }-и худро навсозӣ кунед.
appmenu-update-manual =
    .label = { -brand-shorter-name } ба версия нав навсозӣ карда намешавад.
    .buttonlabel = Боргирӣ кардани { -brand-shorter-name }
    .buttonaccesskey = Б
    .secondarybuttonlabel = Ҳоло не
    .secondarybuttonaccesskey = Н
appmenu-update-manual-message = Нусхаи навтарини { -brand-shorter-name }-ро боргирӣ намоед ва мо ба шумо барои насби он кумак мерасонем.
appmenu-update-whats-new =
    .value = Бинед, ки чӣ нав аст.
appmenu-update-unsupported =
    .label = { -brand-shorter-name } ба версия нав навсозӣ карда намешавад.
    .buttonlabel = Маълумоти бештар
    .buttonaccesskey = М
    .secondarybuttonlabel = Пӯшидан
    .secondarybuttonaccesskey = П
appmenu-update-unsupported-message = Версия навтарини { -brand-shorter-name } дар низоми шумо дастгирӣ намешавад.
appmenu-update-restart =
    .label = Барои навсозӣ кардани { -brand-shorter-name } бозоғозӣ кунед.
    .buttonlabel = Аз нав оғоз ва барқарор кардан
    .buttonaccesskey = А
    .secondarybuttonlabel = Ҳоло не
    .secondarybuttonaccesskey = Н
appmenu-update-restart-message = Пас аз бозоғозии тезкор, { -brand-shorter-name } ҳамаи варақаҳо ва равзанаҳои кушодашудаеро, ки дар реҷаи тамошокунии махфӣ намебошанд, барқарор мекунад.
appmenu-update-available2 =
    .label = Навсозӣ дастрас аст
    .buttonlabel = Боргирӣ кардан
    .buttonaccesskey = Б
    .secondarybuttonlabel = Нодида гузарондан
    .secondarybuttonaccesskey = Н
appmenu-update-available-message2 = Версияи охирини { -brand-shorter-name }-ро боргирӣ намоед.
appmenu-update-manual2 =
    .label = Навсозӣ дастрас аст
    .buttonlabel = Боргирӣ кардан
    .buttonaccesskey = Б
    .secondarybuttonlabel = Нодида гузарондан
    .secondarybuttonaccesskey = Н
appmenu-update-unsupported2 =
    .label = Навсозӣ карда нашуд
    .buttonlabel = Маълумоти бештар
    .buttonaccesskey = М
    .secondarybuttonlabel = Нодида гузарондан
    .secondarybuttonaccesskey = Н
appmenu-update-restart2 =
    .label = Навсозӣ дастрас аст
    .buttonlabel = Навсозӣ кардан ва барномаро аз нав оғоз намудан
    .buttonaccesskey = Н
    .secondarybuttonlabel = Нодида гузарондан
    .secondarybuttonaccesskey = Г
appmenu-update-other-instance =
    .label = { -brand-shorter-name } ба версия нав ба таври худкор навсозӣ карда намешавад.
    .buttonlabel = Ба ҳар ҳол { -brand-shorter-name } навсозӣ карда шавад
    .buttonaccesskey = Б
    .secondarybuttonlabel = Ҳоло не
    .secondarybuttonaccesskey = Н
appmenu-update-other-instance-message = Навсозии нави { -brand-shorter-name } дастрас аст, аммо ба сабаби он ки нусхаи дигари { -brand-shorter-name } дар ҳоли иҷро аст, он насб карда намешавад. Барои идома додани навсозӣ, нусхаи дигареро пӯшед ё интихоб кунед, ки навсозӣ ба ҳар ҳол насб карда шавад (нусхаи ҷории дигар метавонад то бозоғозии дубора дуруст кор накунад).
appmenu-addon-private-browsing-installed =
    .buttonlabel = Хуб, фаҳмидам
    .buttonaccesskey = Х
appmenu-addon-post-install-message = Бо зеркунии <image data-l10n-name='addon-install-icon'></image> дар менюи <image data-l10n-name='addon-menu-icon'></image> ҷузъҳои иловагии худро идора намоед.
appmenu-addon-private-browsing-installed2 =
    .buttonlabel = Хуб
    .buttonaccesskey = О
appmenu-addon-post-install-message2 = Васеъшавиҳо ва мавзӯъҳои худро тавассути менюи барномаҳо идора намоед.
appmenu-addon-post-install-incognito-checkbox =
    .label = Иҷозат додани иҷрокунии васеъшавӣ дар равзанаи махфӣ
    .accesskey = A
appmenu-new-tab-controlled =
    .label = Варақаи нави шумо тағйир ёфт.
    .buttonlabel = Нигоҳ доштани тағйирот
    .buttonaccesskey = Н
    .secondarybuttonlabel = Ғайрифаъол кардани васеъшавӣ
    .secondarybuttonaccesskey = Ғ
appmenu-homepage-controlled =
    .label = Саҳифаи асосии шумо тағйир ёфт.
    .buttonlabel = Нигоҳ доштани тағйирот
    .buttonaccesskey = Н
    .secondarybuttonlabel = Ғайрифаъол кардани васеъшавӣ
    .secondarybuttonaccesskey = Ғ
appmenu-new-tab-controlled-changes =
    .label = Варақаи нави шумо тағйир ёфт.
    .buttonlabel = Нигоҳ доштани тағйирот
    .buttonaccesskey = Н
    .secondarybuttonlabel = Идора кардани варақаҳои нав
    .secondarybuttonaccesskey = И
appmenu-homepage-controlled-changes =
    .label = Саҳифаи асосии шумо тағйир ёфт.
    .buttonlabel = Нигоҳ доштани тағйирот
    .buttonaccesskey = Н
    .secondarybuttonlabel = Идора кардани саҳифаи асосӣ
    .secondarybuttonaccesskey = И
appmenu-tab-hide-controlled =
    .label = Дастрасӣ ба варақаҳои пинҳоншудаи шумо
    .buttonlabel = Нигоҳ доштани варақаҳо ҳамчун пинҳоншуда
    .buttonaccesskey = Н
    .secondarybuttonlabel = Ғайрифаъол кардани васеъшавӣ
    .secondarybuttonaccesskey = Ғ
