# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = वेळ संपली
openFile = फाइल उघडा
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = "%2$S"करिता %1$S शोधा
contextMenuSearch.accesskey = S
contextMenuPrivateSearch = खाजगी पटलामध्ये शोधा
contextMenuPrivateSearch.accesskey = h
# LOCALIZATION NOTE (contextMenuPrivateSearchOtherEngine): %S is the search
# engine name as set for Private Browsing mode. This label is only used when
# this engine is different from the default engine name used in normal mode.
contextMenuPrivateSearchOtherEngine = खाजगी पटलामध्ये %S सह शोधा
contextMenuPrivateSearchOtherEngine.accesskey = h
bookmarkAllTabsDefault = [संचिकेचे नाव]
unsignedAddonsDisabled.message = एक किंवा अधिक ॲड-ऑन्स् सत्यापित करता आले नसून ते अक्षम करण्यात आले आहे.
unsignedAddonsDisabled.learnMore.label = अधिक जाणा
unsignedAddonsDisabled.learnMore.accesskey = L
# LOCALIZATION NOTE (geolocationLastAccessIndicatorText): %S is the relative time of the most recent geolocation access (e.g. 5 min. ago)
geolocationLastAccessIndicatorText = शेवटचा प्रवेश %S
crashedpluginsMessage.title = %S प्लगइन क्रॅश झाले.
crashedpluginsMessage.reloadButton.label = पृष्ठ पुनःलोड करा
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = क्रॅश अहवाल सादर करा
crashedpluginsMessage.submitButton.accesskey = S
crashedpluginsMessage.learnMore = अधिक जाणा…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = आपणास %S कडे जायचे?
keywordURIFixup.goTo = होय, मला %S कडे न्या
keywordURIFixup.goTo.accesskey = Y
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = %S करिता अद्यावत करा
update.downloadAndInstallButton.accesskey = U
menuOpenAllInTabs.label = सर्व टॅब उघडा
tabHistory.goBack = येथून मागील पृष्ठावर जा
tabHistory.goForward = येथून पुढिल पृष्ठावर जा
# URL Bar
pasteAndGo.label = चिकटवा व जा
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = चालू पृष्ठ परत दाखल करा (%S)
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = हे पृष्ठ दाखल करणे थांबवा (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = झूम स्तर मूळस्थितीत आणा (%S)
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = वाचक दृष्टीक्षेपात बदला (%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = वाचनखूणा (%S) दाखवा
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = कार्यरत डाऊनलोड्सची प्रगती दाखवा (%S)
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = नवीन पटल (%S) उघडा
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = नवीन टॅब (%S) उघडा
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = %S: द्वारे तपसालेले
identity.identified.verified_by_you = आपण या स्थळाकरीता सुरक्षा अपवाद जोडले आहे
identity.identified.state_and_country = %S, %S
identity.ev.contentOwner2 = यांना प्रमाणपत्र दिले: %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = असुरक्षित
identity.notSecure.tooltip = असुरक्षित जोडणी
identity.extension.label = विस्तार (%S)
identity.extension.tooltip = विस्ताराने लोड केलेले: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = लहान करा (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = झूम स्तर मूळस्थितीत आणा (%S)
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = मोठे करा (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = कापा (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = प्रत बनवा (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = चिकटवा (%S)
geolocation.remember = हा निर्णय लक्षात ठेवा
# Persistent storage UI
persistentStorage.allow = स्वीकारा
persistentStorage.allow.accesskey = A
webNotifications.notNow = आता नाही
webNotifications.notNow.accesskey = n
webNotifications.never = कधीही परवानगी देऊ नका
webNotifications.never.accesskey = v
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = मला येथून बाहेर काढा!
safebrowsing.getMeOutOfHereButton.accessKey = G
safebrowsing.deceptiveSite = फसवी साईट!
safebrowsing.notADeceptiveSiteButton.label = ही साईट फसवी नाही…
safebrowsing.notADeceptiveSiteButton.accessKey = d
safebrowsing.reportedAttackSite = प्रभावीत स्थळ कळविले गेले!
safebrowsing.notAnAttackButton.label = ही अटॅक साइट नाही…
safebrowsing.notAnAttackButton.accessKey = a
safebrowsing.reportedUnwantedSite = नको असलेली सॉफ्टवेअर साईट कळवली!
safebrowsing.reportedHarmfulSite = हानीकारक साइट नोंदवली!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = %S शोधा
processHang.add-on.learn-more.text = अधिक जाणा
processHang.button_debug.label = स्क्रिप्ट डीबग करा
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = पटलला पडदाभर (%S) असे दाखवा
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = बाजूची पट्टी डावीकडे हलवा
sidebar.moveToRight = बाजूची पट्टी उजवीकडे हलवा
emeNotifications.drmContentDisabled.button.label = DRM सक्षम करा
emeNotifications.drmContentDisabled.button.accesskey = E
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = या पृष्ठावरील ऑडियो किंवा व्हिडीओ चालवण्यासाठी, %S आवश्यक घटक प्रस्थापित करत आहे. कृपया नंतर पुन्हा प्रयत्न करा.
emeNotifications.unknownDRMSoftware = अपरिचीत
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = %S स्वपसंती करा
decoder.noCodecs.button = कसे ते शिका
decoder.noCodecs.accesskey = L
decoder.noCodecsLinux.message = व्हिडिओ चालविण्यासाठी, कदाचित आपणास गरजेचे व्हीडीओ कोडेक्स स्थापित करावे लागेल.
decoder.noHWAcceleration.message = व्हिडिओची गुणवत्ता सुधारण्यासाठी, कदाचीत आपणास Microsoft चा मीडिया वैशिष्ट्य पॅक स्थापित करावा लागेल.
decoder.noPulseAudio.message = ऑडिओ चालविण्यासाठी कदाचित आपणास गरजेचे PulseAudio सॉफ्टवेअर स्थापित करावे लागेल.
decoder.unsupportedLibavcodec.message = libavcodec असुरक्षित असेल किंवा समर्थित नाही, व व्हिडिओ चालविण्यासाठी अद्ययावत करावे.
decoder.decodeError.message = एका मिडीया संसाधनाचे निरूपण करताना एक चूक घडली आहे.
decoder.decodeError.button = साईटची त्रुटी दाखल करा
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = एका मिडीया संसाधनाचे निरूपण करताना सुधारणा करता येण्याजोगी एक चूक आढळली आहे
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = इंटरनेट वापरण्या आधी आपल्याला या नेटवर्क मध्ये लॉग इन करावे लागेल.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = नेटवर्क लॉग इन पृष्ठ उघडा
permissions.remove.tooltip = ही परवानगी काढा आणि परत विचारा
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-बिट
aboutDialog.architecture.thirtyTwoBit = 32-बिट
midi.remember = हा निर्णय लक्षात ठेवा
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = मागे
