# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dialogAcceptLabelSaveItem = थिना दोन
dialogTitleAddBookmark = गोदान बुकमार्क
dialogTitleAddMulti = गोदान बुकमार्क
dialogTitleEdit = "%S" नि आखुथायफोर
bookmarkAllTabsDefault = [फल्डारनि मुं]
newFolderDefault = गोदान फल्डार
newBookmarkDefault = गोदान बुकमार्क
