# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

RepostFormData = Ista pachina web se ye reendrezando ta una nueva adreza. Quiere tornar a ninviar os datos d'o formulario que ha empliu ta la nueva adreza?
# Directory listing strings
DirTitle = Indiz de %1$S
DirGoUp = Enta o directorio superior
ShowHidden = Amostrar obchectos amagaus
DirColName = Nombre
DirColSize = Mida
DirColMTime = Zaguera modificación
DirFileLabel = Fichero:\u0020
UnsafeUriBlocked = Lo recurso de “%1$S” ye estau blocau por Safe Browsing.
