# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

nv_timeout = સમય સમાપ્ત
openFile = ફાઈલ ખોલો
# LOCALIZATION NOTE (contextMenuSearch): %1$S is the search engine,
# %2$S is the selection string.
contextMenuSearch = %1$S ને "%2$S" માટે શોધો
contextMenuSearch.accesskey = S
bookmarkAllTabsDefault = [ફોલ્ડર નામ]
unsignedAddonsDisabled.message = એક અથવા વધુ ઇન્સ્ટોલ કરેલ એડ-ઓનની ચકાસણી કરી શકાતી નથી અને અક્ષમ કરવામાં આવી છે.
unsignedAddonsDisabled.learnMore.label = વધુ શીખો
unsignedAddonsDisabled.learnMore.accesskey = L
crashedpluginsMessage.title = %S પ્લગઇન ભાંગી ગયુ છે.
crashedpluginsMessage.reloadButton.label = પૃષ્ઠ ફરીથી લોડ કરો
crashedpluginsMessage.reloadButton.accesskey = R
crashedpluginsMessage.submitButton.label = ભંગાણ અહેવાલો જમા કર્યા
crashedpluginsMessage.submitButton.accesskey = S
crashedpluginsMessage.learnMore = વધુ શીખો…
# Keyword fixup messages
# LOCALIZATION NOTE (keywordURIFixup.message): Used when the user tries to visit
# a local host page, by the time the DNS request recognizes it, we have already
# loaded a search page for the given word.  An infobar then asks to the user
# whether he rather wanted to visit the host.  %S is the recognized host.
keywordURIFixup.message = શું તમારો મતલબ એ %S માં લઇ જવાનો હતો?
keywordURIFixup.goTo = હાં, મને %S માં લો
keywordURIFixup.goTo.accesskey = Y
# Sanitize
# LOCALIZATION NOTE (update.downloadAndInstallButton.label): %S is replaced by the
# version of the update: "Update to 28.0".
update.downloadAndInstallButton.label = %S સુધારો
update.downloadAndInstallButton.accesskey = U
menuOpenAllInTabs.label = બધું ટૅબ્સમાં ખોલો
tabHistory.goBack = આ પાનાં પર પાછા જાવ
tabHistory.goForward = આ પાનાં આગળ જાવ
# URL Bar
pasteAndGo.label = ચોંટાડો અને જાઓ
# LOCALIZATION NOTE (reloadButton.tooltip):
# %S is the keyboard shortcut for reloading the current page
reloadButton.tooltip = હાલનાં પૃષ્ઠનો (%S) ફરીથી લોડ કરો
# LOCALIZATION NOTE (stopButton.tooltip):
# %S is the keyboard shortcut for stopping loading the page
stopButton.tooltip = આ પૃષ્ઠ લોડ કરવાનું રોકો (%S)
# LOCALIZATION NOTE (urlbar-zoom-button.tooltip):
# %S is the keyboard shortcut for resetting the zoom level to 100%
urlbar-zoom-button.tooltip = નાનુ મોટુ કરવાનાં સ્તર (%S) ને પુન:સુયોજિત કરો
# LOCALIZATION NOTE (reader-mode-button.tooltip):
# %S is the keyboard shortcut for entering/exiting reader view
reader-mode-button.tooltip = રીડર દૃશ્ય ટૉગલ કરો(%S)
# LOCALIZATION NOTE(zoom-button.label): %S is the current page zoom level,
# %% will be displayed as a single % character (% is commonly used to define
# format specifiers, so it needs to be escaped).
zoom-button.label = %S%%
# General bookmarks button
# LOCALIZATION NOTE (bookmarksMenuButton.tooltip):
# %S is the keyboard shortcut for "Show All Bookmarks"
bookmarksMenuButton.tooltip = તમારાં બુમાર્કને બતાવો (%S)
# Downloads button tooltip
# LOCALIZATION NOTE (downloads.tooltip):
# %S is the keyboard shortcut for "Downloads"
downloads.tooltip = ચાલતા ડાઉનલોડ (%S) ની પ્રગતિને દર્શાવો
# New Window button tooltip
# LOCALIZATION NOTE (newWindowButton.tooltip):
# %S is the keyboard shortcut for "New Window"
newWindowButton.tooltip = નવી વિન્ડોને ખોલો (%S)
# New Tab button tooltip
# LOCALIZATION NOTE (newTabButton.tooltip):
# %S is the keyboard shortcut for "New Tab"
newTabButton.tooltip = નવી ટૅબને ખોલો (%S)
# LOCALIZATION NOTE (identity.identified.verifier, identity.identified.state_and_country, identity.ev.contentOwner2):
# %S is the hostname of the site that is being displayed.
identity.identified.verifier = દ્વારા ખાતરી થઈ: %S
identity.identified.verified_by_you = તમે આ સાઈટ માટે સુરક્ષા અપવાદ ઉમેરેલ છે
identity.identified.state_and_country = %S, %S
# LOCALIZATION NOTE (identity.notSecure.label):
# Keep this string as short as possible, this is displayed in the URL bar
# use a synonym for "safe" or "private" if "secure" is too long.
identity.notSecure.label = અસુરક્ષિત
identity.extension.label = એક્સટેન્શનો(%S)
identity.extension.tooltip = એક્સ્ટેંશન દ્વારા લોડ: %S
# LOCALIZATION NOTE(zoomReduce-button.tooltip): %S is the keyboard shortcut.
zoomReduce-button.tooltip = નાનુ કરો (%S)
# LOCALIZATION NOTE(zoomReset-button.tooltip): %S is the keyboard shortcut.
zoomReset-button.tooltip = નાનુ મોટુ કરવાનાં સ્તર (%S) ને પુન:સુયોજિત કરો
# LOCALIZATION NOTE(zoomEnlarge-button.tooltip): %S is the keyboard shortcut.
zoomEnlarge-button.tooltip = મોટુ કરો (%S)
# LOCALIZATION NOTE (cut-button.tooltip): %S is the keyboard shortcut.
cut-button.tooltip = કાપો (%S)
# LOCALIZATION NOTE (copy-button.tooltip): %S is the keyboard shortcut.
copy-button.tooltip = નકલ (%S)
# LOCALIZATION NOTE (paste-button.tooltip): %S is the keyboard shortcut.
paste-button.tooltip = ચોંટાડો (%S)
geolocation.remember = આ નિર્ણય યાદ રાખો
# Persistent storage UI
persistentStorage.allow = પરવાનગી આપો
persistentStorage.allow.accesskey = A
webNotifications.notNow = હમણાં નહિં
webNotifications.notNow.accesskey = n
webNotifications.never = ક્યારેય મંજૂરી આપશો નહીં
webNotifications.never.accesskey = v
# Phishing/Malware Notification Bar.
# LOCALIZATION NOTE (notADeceptiveSite, notAnAttack)
# The two button strings will never be shown at the same time, so
# it's okay for them to have the same access key
safebrowsing.getMeOutOfHereButton.label = મને અહીંથી બહાર લઈ જાવ!
safebrowsing.getMeOutOfHereButton.accessKey = G
safebrowsing.deceptiveSite = છેતરામણી સાઇટ!
safebrowsing.notADeceptiveSiteButton.label = આ એક ભ્રામક સાઇટ નથી…
safebrowsing.notADeceptiveSiteButton.accessKey = D
safebrowsing.reportedAttackSite = અહેવાલિત હુમલા સાઈટ!
safebrowsing.notAnAttackButton.label = આ એક હુમલો સાઇટ નથી…
safebrowsing.notAnAttackButton.accessKey = A
safebrowsing.reportedUnwantedSite = જાણ કરેલી અનિચ્છનીય સોફ્ટવેર સાઇટ!
safebrowsing.reportedHarmfulSite = હાનિકારક સાઇટની જાણ કરી!
# LOCALIZATION NOTE (addKeywordTitleAutoFill): %S will be replaced by the page's title
# Used as the bookmark name when saving a keyword for a search field.
addKeywordTitleAutoFill = %S શોધો
processHang.add-on.learn-more.text = વધુ શીખો
processHang.button_debug.label = સ્ક્રિપ્ટ ડિબગ કરો
processHang.button_debug.accessKey = D
# LOCALIZATION NOTE (fullscreenButton.tooltip): %S is the keyboard shortcut for full screen
fullscreenButton.tooltip = સંપૂર્ણ સ્ક્રીન (%S) માં વિન્ડોને દર્શાવો
# These are visible when opening the popup inside the bookmarks sidebar
sidebar.moveToLeft = ડાબી સાઇડબારમાં ખસેડો
sidebar.moveToRight = જમણે સાઇડબાર ખસેડો
emeNotifications.drmContentDisabled.button.label = સક્રિય DRM
emeNotifications.drmContentDisabled.button.accesskey = E
# LOCALIZATION NOTE(emeNotifications.drmContentCDMInstalling.message): NB: inserted via innerHTML, so please don't use <, > or & in this string. %S is brandShortName
emeNotifications.drmContentCDMInstalling.message = %S આ પૃષ્ઠ પર ઑડિઓ અથવા વિડિઓ ચલાવવા માટે જરૂરી ઘટકો ઇન્સ્ટોલ કરી રહ્યું છે. પછીથી ફરી પ્રયત્ન કરો.
emeNotifications.unknownDRMSoftware = અજ્ઞાત
# LOCALIZATION NOTE (customizeMode.tabTitle): %S is brandShortName
customizeMode.tabTitle = %S ને અનુકૂલિત કરો
decoder.noCodecs.button = કેવી રીતે તે જાણો
decoder.noCodecs.accesskey = L
decoder.noCodecsLinux.message = વિડિઓ ચલાવવા માટે, તમારે આવશ્યક વિડિઓ કોડેક્સ ઇન્સ્ટોલ કરવાની જરૂર પડી શકે છે.
decoder.noHWAcceleration.message = વિડિઓ ગુણવત્તા સુધારવા માટે, તમારે Microsoft ના મીડિયા સુવિધા પૅકને ઇન્સ્ટોલ કરવાની જરૂર પડી શકે છે.
decoder.noPulseAudio.message = ઑડિઓ ચલાવવા માટે, તમારે આવશ્યક PulseAudio સૉફ્ટવેર ઇન્સ્ટોલ કરવાની જરૂર પડી શકે છે.
decoder.unsupportedLibavcodec.message = Libavcodec સંવેદનશીલ હોઈ શકે છે અથવા સમર્થિત નથી, અને વિડિઓ ચલાવવા માટે અપડેટ થવું જોઈએ.
decoder.decodeError.message = મીડિયા સંસાધન ડીકોડિંગ કરતી વખતે એક ભૂલ આવી છે.
decoder.decodeError.button = સાઇટ સમસ્યાનો અહેવાલ આપો
decoder.decodeError.accesskey = R
decoder.decodeWarning.message = મીડિયા સ્રોતને ડીકોડિંગ કરતી વખતે પુનઃપ્રાપ્ત ભૂલ આવી.
# LOCALIZATION NOTE (captivePortal.infoMessage3):
# Shown in a notification bar when we detect a captive portal is blocking network access
# and requires the user to log in before browsing.
captivePortal.infoMessage3 = તમે ઇન્ટરનેટ ઍક્સેસ કરી શકો તે પહેલાં તમારે આ નેટવર્કમાં લૉગ ઇન કરવું આવશ્યક છે.
# LOCALIZATION NOTE (captivePortal.showLoginPage2):
# The label for a button shown in the info bar in all tabs except the login page tab.
# The button shows the portal login page tab when clicked.
captivePortal.showLoginPage2 = ઑપન નેટવર્ક લૉગિન પૃષ્ઠ
permissions.remove.tooltip = આ પરવાનગી સાફ કરો અને ફરી પૂછો
# LOCALIZATION NOTE (aboutDialog.architecture.*):
# The sixtyFourBit and thirtyTwoBit strings describe the architecture of the
# current Firefox build: 32-bit or 64-bit. These strings are used in parentheses
# between the Firefox version and the "What's new" link in the About dialog,
# e.g.: "48.0.2 (32-bit) <What's new>" or "51.0a1 (2016-09-05) (64-bit)".
aboutDialog.architecture.sixtyFourBit = 64-બીટ
aboutDialog.architecture.thirtyTwoBit = 32-બીટ
midi.remember = આ નિર્ણયને યાદ રાખો
# LOCALIZATION NOTE (panel.back):
# This is used by screen readers to label the "back" button in various browser
# popup panels, including the sliding subviews of the main menu.
panel.back = પાછળ
