#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

# LOCALIZATION NOTE: Some of these URLs are currently 404s, but should be coming
# online shortly.

# LOCALIZATION NOTE (bookmarks_title):
# title for the folder that will contains the default bookmarks
#define bookmarks_title Mobile

# LOCALIZATION NOTE (bookmarks_aboutBrowser):
# link title for about:fennec
#define bookmarks_aboutBrowser Firefox : À propos de votre navigateur

# LOCALIZATION NOTE (bookmarks_addons):
# link title for https://addons.mozilla.org/en-US/mobile
#define bookmarks_addons Firefox : Personnaliser avec des modules complémentaires

# LOCALIZATION NOTE (bookmarks_support):
# link title for https://mobile.support.mozilla.com
#define bookmarks_support Firefox : Assistance

# LOCALIZATION NOTE (bookmarks_marketplace):
# link title for https://marketplace.firefox.com
#define bookmarks_marketplace Firefox Marketplace

# LOCALIZATION NOTE (bookmarks_restricted_support):
# link title for https://support.mozilla.org/kb/kids
#define bookmarks_restricted_support Aide et assistance pour la version de Firefox spécialement conçue pour les enfants

# LOCALIZATION NOTE (bookmarks_restricted_webmaker):
# link title for https://webmaker.org
#define bookmarks_restricted_webmaker Apprendre le Web : Mozilla Webmaker

#unfilter emptyLines
