# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

appmenu-update-available =
    .label = Dostympno je nowo aktualizacyjo aplikacyji { -brand-shorter-name }.
    .buttonlabel = Pobier aktualizacyjo
    .buttonaccesskey = P
    .secondarybuttonlabel = Niy teroz
    .secondarybuttonaccesskey = N
appmenu-update-available-message = Zaktualizuj aplikacyjo { -brand-shorter-name }, coby miała wiynkszo gibkość i bezpieczyństwo.
appmenu-update-manual =
    .label = { -brand-shorter-name } niy poradzi zainstalować nojnowszyj wersyje.
    .buttonlabel = Pobier: { -brand-shorter-name }
    .buttonaccesskey = P
    .secondarybuttonlabel = Niy teroz
    .secondarybuttonaccesskey = N
appmenu-update-manual-message = Pobier fryszno wersyjo aplikacyji { -brand-shorter-name }, a my pōmogymy ci jōm zainstalować.
appmenu-update-whats-new =
    .value = Wejrzij, co nowego.
appmenu-update-unsupported =
    .label = { -brand-shorter-name } niy poradzi zaktualizować sie do nojnowszyj wersyje.
    .buttonlabel = Przewiydz sie wiyncyj
    .buttonaccesskey = P
    .secondarybuttonlabel = Zawrzij
    .secondarybuttonaccesskey = Z
appmenu-update-unsupported-message = Nojnowszo wersyjo aplikacyje { -brand-shorter-name } niy ma spiyrano na twojim systymie.
appmenu-update-restart =
    .label = Zresztartuj, coby zaktualizować aplikacyjo { -brand-shorter-name }.
    .buttonlabel = Resztartuj i wrōć
    .buttonaccesskey = R
    .secondarybuttonlabel = Niy teroz
    .secondarybuttonaccesskey = N
appmenu-update-restart-message = Po gibkim resztarcie { -brand-shorter-name } wrōci wszyskie ôtwarte karty i ôkna krōm tych we trybie prywatnego przeglōndanio.
appmenu-addon-private-browsing-installed =
    .buttonlabel = Rozumia
    .buttonaccesskey = R
appmenu-addon-post-install-message = Regiyruj swojimi przidowkami bez klikniyńcie <image data-l10n-name='addon-install-icon'></image> w menu <image data-l10n-name='addon-menu-icon'></image>.
appmenu-addon-post-install-incognito-checkbox =
    .label = Zgoda, coby te rozszyrzynie fungowało we prywatnych ôknach
    .accesskey = Z
appmenu-addon-private-browsing =
    .label = Zmiyń jako fungujōm rozszyrzynia we prywatnych ôknach
    .buttonlabel = Regiyruj rozszyrzyniami
    .buttonaccesskey = E
    .secondarybuttonlabel = Rozumia
    .secondarybuttonaccesskey = R
appmenu-addon-private-browsing-message = Nowe rozszyrzynia, co je przidowosz do aplikacyje { -brand-shorter-name }, niy bydōm fungować we prywatnych ôknach, podwiela niy dosz na to zgody w nasztalowaniach.
appmenu-addon-private-browsing-learn-more = Przewiydz sie, jako regiyrować nasztalowaniami rozszyrzyń
appmenu-new-tab-controlled =
    .label = Nowo karta je teroz zmiyniōno.
    .buttonlabel = Spamiyntej zmiany
    .buttonaccesskey = S
    .secondarybuttonlabel = Zastow rozszyrzynie
    .secondarybuttonaccesskey = Z
appmenu-homepage-controlled =
    .label = Sztartowo strōna je teroz zmiyniōno.
    .buttonlabel = Spamiyntej zmiany
    .buttonaccesskey = S
    .secondarybuttonlabel = Zastow rozszyrzynie
    .secondarybuttonaccesskey = Z
appmenu-tab-hide-controlled =
    .label = Dostymp do twojich skrytych kart
    .buttonlabel = Ôstow karty skryte
    .buttonaccesskey = O
    .secondarybuttonlabel = Zastow rozszyrzynie
    .secondarybuttonaccesskey = Z
