# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

places-open =
    .label = Ôdewrzij
    .accesskey = O
places-open-tab =
    .label = Ôdewrzij w nowyj karcie
    .accesskey = w
places-open-all-in-tabs =
    .label = Ôdewrzij wszyskie w kartach
    .accesskey = O
places-open-window =
    .label = Ôdewrzij w nowym ôknie
    .accesskey = N
places-open-private-window =
    .label = Ôdewrzij w nowym prywatnym ôknie
    .accesskey = P
places-new-bookmark =
    .label = Nowo zokłodka…
    .accesskey = Z
places-new-folder-contextmenu =
    .label = Nowy katalog…
    .accesskey = K
places-new-folder =
    .label = Nowy katalog…
    .accesskey = K
places-new-separator =
    .label = Nowy separatōr
    .accesskey = S
places-view =
    .label = Pokoż
    .accesskey = P
places-by-date =
    .label = Podug daty
    .accesskey = D
places-by-site =
    .label = Podug strōny
    .accesskey = S
places-by-most-visited =
    .label = Podug wielości byzuchōw
    .accesskey = B
places-by-last-visited =
    .label = Podug ôstatnigo byzuchu
    .accesskey = Y
places-by-day-and-site =
    .label = Podug daty i strōny
    .accesskey = t
