# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = A bheil thu airson earbsa a chur ann an "%S" a chum na leanas?
unnamedCA = Ùghdarras teisteanachaidh (gun ainm)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Cuir a-steach am facal-faire a chleachd thu gus lethbhreac-glèidhidh an teisteanais seo a chrioptachadh:
# Page Info
pageInfo_NoEncryption = Chan eil an ceangal air a chrioptachadh
pageInfo_Privacy_None1 = Chan eil an làrach-lìn %S a' cur taic ri crioptachadh na duilleige a tha thu a' coimhead air.
pageInfo_Privacy_None2 = 'S urrainn do dhaoine eile fiosrachadh gun chrioptachadh a chuireas tu a-null air an lìon fhaicinn 's e a' trasnadh an lìn.\u0020
pageInfo_Privacy_None4 = Cha deach an duilleag a tha thu a’ coimhead air a chrioptachadh mus deach a chur a-nall thairis air an lìon.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Ceangal crioptaichte (%1$S, %2$S bit keys, %3$S)
pageInfo_BrokenEncryption = Crioptachadh briste (%1$S, %2$S bit keys, %3$S)
pageInfo_Privacy_Encrypted1 = Chaidh an duilleag a tha thu a' coimhead air a chrioptachadh mus deach a chur a-nall thairis air an lìon.
pageInfo_Privacy_Encrypted2 = Bidh e doirbh do dhaoine gun ùghdarras fiosrachadh a tha a' siubhal eadar coimpiutairean fhaicinn ma chaidh a chrioptachadh. Mar sin, chan eil coltas gun leugh duine sam bith an duilleag seo 's e a' siubhal an lìonraidh.
pageInfo_MixedContent = Ceangal air a chrioptachadh gu ìre
pageInfo_MixedContent2 = Cha deach cuid dhen duilleag a tha thu a' coimhead air a chrioptachadh mus deach a chur a-nall thairis air an lìon.
pageInfo_WeakCipher = Tha an ceangal agad ris an làrach seo a’ cleachdadh crioptachadh lag is chan eil e prìobhaideachd. Chì daoine eile am fiosrachadh agad agus is urrainn dhaibh giùlan na làraich-lìn atharrachadh.
pageInfo_CertificateTransparency_Compliant = Tha an làrach-lìn seo a’ gèilleadh ri poileasaidh soilleireachd nan teisteanasan.
# Token Manager
password_not_set = (gun suidheachadh)
