# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Download Cert dialog
# LOCALIZATION NOTE(newCAMessage1):
# %S is a string representative of the certificate being downloaded/imported.
newCAMessage1 = Сіз "%S"-ке келесі мақсаттармен сенуді қалайсыз ба?
unnamedCA = Сертификаттау орталығы (атаусыз)
# PKCS#12 file dialogs
getPKCS12FilePasswordMessage = Сертификаттың қор көшірмесін шифрлеу үшін қолданылған паролді енгізіңіз:
# Page Info
pageInfo_NoEncryption = Байланыс шифрленбеген
pageInfo_Privacy_None1 = Веб-сайт %S  сіз ашып отырған парақ үшін шифрлеуді қолдамайды.
pageInfo_Privacy_None2 = Интернет арқылы берілетін ақпарат шифрленбесе, берілу кезінде оны басқа адамдар көре алады.\u0020
pageInfo_Privacy_None4 = Ашылып тұрған парақ Интернет арқылы берілу алдында шифрленген жоқ.
# LOCALIZATION NOTE (pageInfo_EncryptionWithBitsAndProtocol and pageInfo_BrokenEncryption):
# %1$S is the name of the encryption standard,
# %2$S is the key size of the cipher.
# %3$S is protocol version like "SSL 3" or "TLS 1.2"
pageInfo_EncryptionWithBitsAndProtocol = Байланыс шифрленген (%1$S, %2$S-биттік кілттер, %3$S)
pageInfo_BrokenEncryption = Сынған шифрлеу (%1$S, %2$S-биттік кілттер, %3$S)
pageInfo_Privacy_Encrypted1 = Ашылып тұрған парақ Интернет арқылы берілу алдында шифрленді.
pageInfo_Privacy_Encrypted2 = Интернеттен берілу алдында парақты шифрлеу оны бөтен адамдар оқи алатын мүмкіндігін қиындатады.
pageInfo_MixedContent = Байланыс жартылай шифрленген
pageInfo_MixedContent2 = Ашылып тұрған парақтың бір бөлігі Интернет арқылы берілу алдында шифленбеді.
pageInfo_WeakCipher = Бұл веб сайтқа байланысыңыз әлсіз шифрлеуді қолданады және шын жеке емес. Басқа адамдар сіздің ақпаратыңызды көре алады немесе веб сайттың мінез-құлығын өзгерте алады.
pageInfo_CertificateTransparency_Compliant = Бұл вебсайты Сертификаттар Мөлдірлілігі саясатына сай келеді.
# Token Manager
password_not_set = (орнатылмаған)
