# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Įrašyti prisijungimai
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-provider-url-cmd =
    .label = Kopijuoti URL
    .accesskey = K
copy-username-cmd =
    .label = Kopijuoti naudotojo vardą
    .accesskey = n
edit-username-cmd =
    .label = Keisti naudotojo vardą
    .accesskey = K
copy-password-cmd =
    .label = Kopijuoti slaptažodį
    .accesskey = s
edit-password-cmd =
    .label = Keisti slaptažodį
    .accesskey = t
search-filter =
    .accesskey = S
    .placeholder = Search
column-heading-provider =
    .label = Tiekėjas
column-heading-username =
    .label = Naudotojo vardas
column-heading-password =
    .label = Slaptažodis
column-heading-time-created =
    .label = Pirmąkart naudotas
column-heading-time-last-used =
    .label = Paskiausiai naudotas
column-heading-time-password-changed =
    .label = Paskiausiai pakeistas
column-heading-times-used =
    .label = Naudotas kartų
remove =
    .label = Pašalinti
    .accesskey = a
import =
    .label = Įkelti
    .accesskey = k
close-button =
    .label = Užverti
    .accesskey = U
show-passwords =
    .label = Rodyti slaptažodžius
    .accesskey = R
hide-passwords =
    .label = Nerodyti slaptažodžių
    .accesskey = N
logins-description-all = Šių tiekėjų prisijungimai įrašyti kompiuteryje
logins-description-filtered = Paieškos kriterijų atitinka šie prisijungimai:
remove-all =
    .label = Pašalinti visus
    .accesskey = P
remove-all-shown =
    .label = Pašalinti visus rodomus
    .accesskey = P
remove-all-passwords-prompt = Ar tikrai pašalinti visus slaptažodžius?
remove-all-passwords-title = Slaptažodžių šalinimas
no-master-password-prompt = Ar tikrai parodyti slaptažodžius?
