# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-provider-url-cmd =
    .label = Kopier URL
    .accesskey = U
copy-username-cmd =
    .label = Kopier brugernavn
    .accesskey = o
edit-username-cmd =
    .label = Rediger brugernavn
    .accesskey = d
copy-password-cmd =
    .label = Kopier adgangskode
    .accesskey = K
edit-password-cmd =
    .label = Rediger adgangskode
    .accesskey = e
search-filter =
    .accesskey = S
    .placeholder = Søg
column-heading-provider =
    .label = Udbyder
remove =
    .label = Fjern
    .accesskey = F
import =
    .label = Importer…
    .accesskey = I
close-button =
    .label = Luk
    .accesskey = L
show-passwords =
    .label = Vis adgangskoder
    .accesskey = d
hide-passwords =
    .label = Skjul adgangskoder
    .accesskey = d
remove-all =
    .label = Fjern alle
    .accesskey = a
remove-all-shown =
    .label = Fjern alle viste
    .accesskey = a
