# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

saved-logins =
    .title = Bewarre oanmeldingen
window-close =
    .key = w
focus-search-shortcut =
    .key = f
focus-search-altshortcut =
    .key = k
copy-provider-url-cmd =
    .label = URL kopiearje
    .accesskey = k
copy-username-cmd =
    .label = Brûkersnamme kopiearje
    .accesskey = B
edit-username-cmd =
    .label = Brûkersnamme bewurkje
    .accesskey = w
copy-password-cmd =
    .label = Wachtwurd kopiearje
    .accesskey = e
edit-password-cmd =
    .label = Wachtwurd bewurkje
    .accesskey = j
search-filter =
    .accesskey = S
    .placeholder = Sykje
column-heading-provider =
    .label = Provider
column-heading-username =
    .label = Brûkersnamme
column-heading-password =
    .label = Wachtwurd
column-heading-time-created =
    .label = Earste gebrûk
column-heading-time-last-used =
    .label = Lêste gebrûk
column-heading-time-password-changed =
    .label = Lêst wizige
column-heading-times-used =
    .label = Kearen brûkt
remove =
    .label = Fuortsmite
    .accesskey = F
import =
    .label = Ymportearje…
    .accesskey = Y
close-button =
    .label = Slute
    .accesskey = l
show-passwords =
    .label = Wachtwurden toane
    .accesskey = t
hide-passwords =
    .label = Wachtwurden ferstopje
    .accesskey = f
logins-description-all = Oanmeldingen foar de folgjende providers binne op jo kompjûter bewarre
logins-description-filtered = De folgjende oanmeldingen komme oerien mei jo sykopdracht:
remove-all =
    .label = Alle fuortsmite
    .accesskey = A
remove-all-shown =
    .label = Alle toande fuortsmite
    .accesskey = A
remove-all-passwords-prompt = Binne jo wis dat jo jo wachtwurden fuortsmite wolle?
remove-all-passwords-title = Alle wachtwurden fuortsmite
no-master-password-prompt = Binne jo wis dat jo jo wachtwurden toane wolle?
