# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


## Variables:
##   $host (String): A website host address

network-connection-status-looking-up = Okunonya { $host }…
network-connection-status-connected = Oyungiddwa ku { $host }…
network-connection-status-sending-request = Okuwereza ekisaabiddwa eri { $host }…
network-connection-status-transferring-data = Okukyusa bwiino okuva { $host }…
network-connection-status-connecting = Okunnyunga ku { $host }…
network-connection-status-read = Soma { $host }
network-connection-status-wrote = Yawandiise { $host }
network-connection-status-waiting = Okulindirira { $host }…
network-connection-status-looked-up = Okunonya { $host }…
