# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

appmenu-update-available2 =
    .label = به‌روزرسانی موجود است
    .buttonlabel = دریافت
    .buttonaccesskey = د
    .secondarybuttonlabel = رد
    .secondarybuttonaccesskey = ر
appmenu-update-available-message2 = آخرین نسخه { -brand-shorter-name } را دریافت کنید.
appmenu-update-manual2 =
    .label = به‌روزرسانی موجود است
    .buttonlabel = دریافت
    .buttonaccesskey = د
    .secondarybuttonlabel = رد
    .secondarybuttonaccesskey = ر
appmenu-update-manual-message2 = امکان به‌روزرسانی خودکار { -brand-shorter-name } وجود نداشت. نگارش جدید را بارگیری کنید — اطلاعات ذخیره شده و سفارشی‌سازی‌های خود را از دست نخواهید داد.
appmenu-update-unsupported2 =
    .label = به‌روزرسانی امکان‌پذیر نیست
    .buttonlabel = اطلاعات بیشتر
    .buttonaccesskey = ا
    .secondarybuttonlabel = رد
    .secondarybuttonaccesskey = ر
appmenu-update-unsupported-message2 = سیستم‌عامل شما با آخرین نگارش { -brand-shorter-name } سازگار نیست.
appmenu-update-restart2 =
    .label = به‌روزرسانی موجود است
    .buttonlabel = به‌روزرسانی و راه‌اندازی مجدد
    .buttonaccesskey = ب
    .secondarybuttonlabel = رد
    .secondarybuttonaccesskey = ر
appmenu-update-restart-message2 = آخرین نگارش از { -brand-shorter-name } را دریافت کنید. زبانه‌ها و پنجره‌های باز، بازیابی خواهند شد.
appmenu-update-other-instance =
    .label = { -brand-shorter-name } نمی‌تواند بطور خودکار به آخرین نگارش به‌روزرسانی شود.
    .buttonlabel = به هر حال به‌روزرسانی { -brand-shorter-name } انجام شود
    .buttonaccesskey = U
    .secondarybuttonlabel = هم‌اکنون نه
    .secondarybuttonaccesskey = N
appmenu-update-other-instance-message = یک به‌روزرسانی جدید برای { -brand-shorter-name } در دسترس است، اما به دلیل اینکه نگارش دیگری از { -brand-shorter-name } در حال اجراست، نمی‌توان آن را نصب کرد. برای ادامه به‌روزرسانی آن را ببندید، یا «به هر حال به‌روزرسانی شود» را انتخاب کنید (نگارش دیگر تا زمانی که آن را مجددا راه‌اندازی کنید ممکن است کار نکند).
appmenu-addon-private-browsing-installed2 =
    .buttonlabel = تایید
    .buttonaccesskey = ت
appmenu-addon-post-install-message3 = افزونه‌ها و تم‌های خود را از طریق منو برنامه مدیریت کنید.
appmenu-addon-post-install-incognito-checkbox =
    .label = به این افزونه اجازه‌ی اجرا در پنجره خصوصی را بده
    .accesskey = ب
appmenu-new-tab-controlled-changes =
    .label = زبانهٔ جدید شما تغیر کرده است.
    .buttonlabel = تغییرات حفظ شوند
    .buttonaccesskey = K
    .secondarybuttonlabel = مدیریت زبانه‌های جدید
    .secondarybuttonaccesskey = M
appmenu-homepage-controlled-changes =
    .label = صفحهٔ خانگی شما تغییر کرد.
    .buttonlabel = تغییرات حفظ شوند
    .buttonaccesskey = K
    .secondarybuttonlabel = مدیریت صفحه خانگی
    .secondarybuttonaccesskey = M
appmenu-tab-hide-controlled =
    .label = دسترسی به زبانه‌های مخفی
    .buttonlabel = مخفی نگاه داشتن زبانه‌ها
    .buttonaccesskey = K
    .secondarybuttonlabel = غیرفعال کردن افزودنی‌ها
    .secondarybuttonaccesskey = D
